### ISSUE TITLE
DOWNLOADHANDLER can't check torrent seed ratio in Deluge

### ISSUE THREAD

**Issue by hellsounet** [pymedusa/Medusa#10011]
DOWNLOADHANDLER can't check torrent seed ratio in Deluge and remove them after a certain ratio 
but adding torrents works just fine

Docker image used: v0.5.18-ls84
Deluge 2.0.3-2-201906121747-ubuntu18.04.1, docker also
using deluge webgui method for authentication   

2021-10-31 05:07:33 ERROR    DOWNLOADHANDLER :: [] Exception while checking torrent status. with error: Object of type function is not JSON serializable
Traceback (most recent call last):
  File "/app/medusa/medusa/schedulers/download_handler.py", line 388, in run
    self._check_torrent_ratio(torrent_client)
  File "/app/medusa/medusa/schedulers/download_handler.py", line 317, in _check_torrent_ratio
    client.remove_torrent(hash)
  File "/app/medusa/medusa/clients/torrent/deluge.py", line 310, in remove_torrent
    return self._remove(logging.info)
  File "/app/medusa/medusa/clients/torrent/deluge.py", line 290, in _remove
    post_data = json.dumps({
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable

**Comment by p0psicles** [comment]
Can you try latest version of deluge?
