### ISSUE TITLE
Trakt.tv Max retries exceeded

### ISSUE THREAD

**Issue by neo-neo1** [pymedusa/Medusa#10030]
**Describe the bug**
Enabled trakt.tv next day woke up to ` Max retries exceeded` errors. Please don't hardcode query interval rate and allow users set it. Important if multiple services auto query same trakt.tv account. Also cleaner fix if Trakt.tv changes max query rate in future. **Other PVRs default interval at 24 hours with 6 minimum.**

**To Reproduce**
1. Enable Trakt.tv from `Notifications` page under `Social` tab.
2. Enable `Sync watchlist`, `Remove episode`, `Remove series`, and `Watchlist add method` = `Get whole show`
3. Leave other options default.
4. Click save then wait ~24 hours for error.

**Medusa:**
- Medusa Version: 0.5.20 
- OS: Armbian Buster (Linux-5.4.151-odroidxu4-armv7l)
- Branch: master
 - Python version: 3.8.10
 - Database version:  44.18

**Debug logs:**
```
2021-11-03 03:01:45 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [] Could not connect to Trakt service: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /shows/american-rust/ratings (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb136efe8>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/app/medusa/ext/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/ext/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/app/medusa/ext/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/app/medusa/ext/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/app/medusa/ext/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb136efe8>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/ext/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/ext/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /shows/american-rust/ratings (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb136efe8>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "</app/medusa/ext/decorator.py:decorator-gen-54>", line 2, in _create_recommended_show
  File "/app/medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "/app/medusa/ext/dogpile/lock.py", line 178, in _enter_create
    return self.creator()
  File "/app/medusa/ext/dogpile/cache/region.py", line 995, in gen_value
    created_value = creator(
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 68, in _create_recommended_show
    **{'rating': show.ratings['rating'],
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 517, in _handle_request
    response = requests.request(method, url, params=data,
  File "/app/medusa/ext/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/ext/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /shows/american-rust/ratings (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb136efe8>: Failed to establish a new connection: [Errno -3] Try again'))
```

Also this, not sure if it's related or another cause. My `blacklist` field under Trakt.tv options is blank (default).
```
2021-11-03 03:01:45 WARNING  GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [] Could not get trakt recommended shows for collected because of error: local variable 'blacklist' referenced before assignment

```

**Comment by p0psicles** [comment]
The rate limitting is enforced by trakt.tv api. Don't know what we can do about that?
Something I could improve is the amount of calls we do towards the api. As trakt offers a per episode endpoint, but also a bulk update endpoint. The bulk update endpoint is preferred, but not that easy to incorporate into medusa workflow.

**Comment by p0psicles** [comment]
Can this be closed?
