### ISSUE TITLE
[APP SUBMITTED]: UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-51: ordinal not in range(128)

### ISSUE THREAD

**Issue by skar4242** [pymedusa/Medusa#10103]
### INFO
**Python Version**: `3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]`
**Operating System**: `Linux-5.4.106-1-pve-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@729ab4f066034709137edb43440dba7c84959626
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-11-13 15:10:07 ERROR    TORNADO :: [729ab4f] Uncaught exception in APIv2: UnicodeEncodeError('ascii', '/opt/medusa/themes/dark/assets/img/network/кинопоиск-hd.png', 43, 52, 'ordinal not in range(128)')
Request: GET /medusa/api/v2/series/tvdb355622/asset/network?api_key=********** (127.0.0.1)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/729ab4f066034709137edb43440dba7c84959626/ext/tornado/web.py#L1704">ext/tornado/web.py</a>", line 1704, in _execute
    result = await result
  File "/opt/medusa/<a href="../blob/729ab4f066034709137edb43440dba7c84959626/ext/tornado/gen.py#L769">ext/tornado/gen.py</a>", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/medusa/<a href="../blob/729ab4f066034709137edb43440dba7c84959626/medusa/server/api/v2/base.py#L64">medusa/server/api/v2/base.py</a>", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/medusa/<a href="../blob/729ab4f066034709137edb43440dba7c84959626/ext/tornado/gen.py#L762">ext/tornado/gen.py</a>", line 762, in run
    value = future.result()
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/<a href="../blob/729ab4f066034709137edb43440dba7c84959626/medusa/server/api/v2/series_asset.py#L37">medusa/server/api/v2/series_asset.py</a>", line 37, in get
    media = asset.media
  File "/opt/medusa/<a href="../blob/729ab4f066034709137edb43440dba7c84959626/medusa/media/generic.py#L66">medusa/media/generic.py</a>", line 66, in media
    static_media_path = self.static_media_path
  File "/opt/medusa/<a href="../blob/729ab4f066034709137edb43440dba7c84959626/medusa/media/generic.py#L111">medusa/media/generic.py</a>", line 111, in static_media_path
    if isfile(media_path):
  File "/usr/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 43-51: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Set your Python locale. See this for example: https://linuxpip.org/fix-python-locale-error/
