### ISSUE TITLE
Advice needed please, how to port data/history etc. etc. to new fresh install?

### ISSUE THREAD

**Issue by PlaceboPRS** [pymedusa/Medusa#10112]
**Describe the bug**
Every day my logs are filled with .db related errors, eg after a fresh boot:

2021-11-22 10:47:52 ERROR    APIv2-Thread_0 :: [729ab4f] DB error: DatabaseError('database disk image is malformed')
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 117, in _execute
    return sql_results.fetchall()

And this relates to a lot of different .py files eg base/gen/cache/web etc. etc. 

I'd like to do a completely fresh install but of course keep my list of TV shows (231 Shows (193 Active) ) as well as history and settings etc. etc. I tired changing the directory to "Medusa old", doing a fresh install and then copying over config.ini and main.db and my shows were there but the schedule was completely empty?

**To Reproduce**
Don't think it's reproducible when it's unique to my system?

**Expected behavior**
Logs not to be filled with errors...

**Screenshots**
![image](https://user-images.githubusercontent.com/23120453/142839917-376c71ee-8c55-4fc7-8d05-c04360f016d6.png)

**Medusa (please complete the following information):**
 - OS: Windows 10 21H2
 - Branch: Master
 - Commit: 729ab4f (not sure if this is correct?)
 - Python version: 3.8.6
 - Database version: [e.g. 44.12]

**Debug logs (at least 50 lines):**
2021-11-22 10:47:56 DEBUG	FORCEDSEARCHQUEUE-MANUAL-116551 :: Oznzb Legend :: [729ab4f] User-Agent: Medusa/0.5.20 (Windows; 10; 101ab48a-4b79-11ec-a5fc-001a7dda7115)
2021-11-22 10:47:56 DEBUG	FORCEDSEARCHQUEUE-MANUAL-116551 :: Oznzb Legend :: [729ab4f] GET URL: **********api?t=caps&apikey=********** [Status: 200]
2021-11-22 10:47:52 ERROR	TORNADO :: [729ab4f] Uncaught exception in APIv2: DatabaseError('database disk image is malformed')
Request: GET /api/v2/providers/nzbs_in/results?limit=1000&season=1&episode=2&page=1 (127.0.0.1)
Traceback (most recent call last):
  File "C:\Medusa\ext\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Medusa\ext\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Medusa\medusa\server\api\v2\base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\ext\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\medusa\server\api\v2\providers.py", line 70, in get
    provider_results = provider.cache.get_results(show_slug=show_slug, season=season, episode=episode)
  File "C:\Medusa\medusa\tv\cache.py", line 663, in get_results
    results = cache_db_con.select(
  File "C:\Medusa\medusa\db.py", line 315, in select
    sql_results = self.action(query, args, fetchall=True)
  File "C:\Medusa\medusa\db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Medusa\medusa\db.py", line 117, in _execute
    return sql_results.fetchall()
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:52 ERROR	APIv2-Thread :: [729ab4f] Fatal error executing query: database disk image is malformed
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Medusa\medusa\db.py", line 117, in _execute
    return sql_results.fetchall()
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:52 ERROR	APIv2-Thread :: [729ab4f] DB error: DatabaseError('database disk image is malformed')
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 117, in _execute
    return sql_results.fetchall()
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:52 ERROR	TORNADO :: [729ab4f] Uncaught exception in APIv2: DatabaseError('database disk image is malformed')
Request: GET /api/v2/providers/nzbs_in/results?limit=1000&showslug=tvdb397146&season=1&episode=2&page=1 (127.0.0.1)
Traceback (most recent call last):
  File "C:\Medusa\ext\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Medusa\ext\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Medusa\medusa\server\api\v2\base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\ext\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\medusa\server\api\v2\providers.py", line 70, in get
    provider_results = provider.cache.get_results(show_slug=show_slug, season=season, episode=episode)
  File "C:\Medusa\medusa\tv\cache.py", line 663, in get_results
    results = cache_db_con.select(
  File "C:\Medusa\medusa\db.py", line 315, in select
    sql_results = self.action(query, args, fetchall=True)
  File "C:\Medusa\medusa\db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Medusa\medusa\db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:52 ERROR	APIv2-Thread-6 :: [729ab4f] Fatal error executing query: database disk image is malformed
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Medusa\medusa\db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:52 ERROR	APIv2-Thread-6 :: [729ab4f] DB error: DatabaseError('database disk image is malformed')
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:51 ERROR	TORNADO :: [729ab4f] Uncaught exception in APIv2: DatabaseError('database disk image is malformed')
Request: GET /api/v2/providers/nzbs_in/results?limit=1000&showslug=tvdb306562&season=4&episode=3&page=1 (127.0.0.1)
Traceback (most recent call last):
  File "C:\Medusa\ext\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Medusa\ext\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Medusa\medusa\server\api\v2\base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\ext\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\medusa\server\api\v2\providers.py", line 70, in get
    provider_results = provider.cache.get_results(show_slug=show_slug, season=season, episode=episode)
  File "C:\Medusa\medusa\tv\cache.py", line 663, in get_results
    results = cache_db_con.select(
  File "C:\Medusa\medusa\db.py", line 315, in select
    sql_results = self.action(query, args, fetchall=True)
  File "C:\Medusa\medusa\db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Medusa\medusa\db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:51 ERROR	APIv2-Thread-2 :: [729ab4f] Fatal error executing query: database disk image is malformed
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Medusa\medusa\db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:51 ERROR	APIv2-Thread-2 :: [729ab4f] DB error: DatabaseError('database disk image is malformed')
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:51 ERROR	TORNADO :: [729ab4f] Uncaught exception in APIv2: DatabaseError('database disk image is malformed')
Request: GET /api/v2/providers/nzbs_in/results?limit=1000&season=4&episode=3&page=1 (127.0.0.1)
Traceback (most recent call last):
  File "C:\Medusa\ext\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Medusa\ext\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Medusa\medusa\server\api\v2\base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\ext\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\medusa\server\api\v2\providers.py", line 70, in get
    provider_results = provider.cache.get_results(show_slug=show_slug, season=season, episode=episode)
  File "C:\Medusa\medusa\tv\cache.py", line 663, in get_results
    results = cache_db_con.select(
  File "C:\Medusa\medusa\db.py", line 315, in select
    sql_results = self.action(query, args, fetchall=True)
  File "C:\Medusa\medusa\db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Medusa\medusa\db.py", line 117, in _execute
    return sql_results.fetchall()
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:51 ERROR	APIv2-Thread :: [729ab4f] Fatal error executing query: database disk image is malformed
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Medusa\medusa\db.py", line 117, in _execute
    return sql_results.fetchall()
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:51 ERROR	APIv2-Thread :: [729ab4f] DB error: DatabaseError('database disk image is malformed')
Traceback (most recent call last):
  File "C:\Medusa\medusa\db.py", line 117, in _execute
    return sql_results.fetchall()
sqlite3.DatabaseError: database disk image is malformed
2021-11-22 10:47:51 ERROR	TORNADO :: [729ab4f] Uncaught exception in APIv2: DatabaseError('database disk image is malformed')
Request: GET /api/v2/providers/nzbs_in/results?limit=1000&showslug=tvdb109411&season=2021&episode=12&page=1 (127.0.0.1)
Traceback (most recent call last):
  File "C:\Medusa\ext\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Medusa\ext\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Medusa\medusa\server\api\v2\base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\ext\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Program Files\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\medusa\server\api\v2\providers.py", line 70, in get
    provider_results = provider.cache.get_results(show_slug=show_slug, season=season, episode=episode)

**Additional context**

**Comment by neo-neo1** [comment]
Click on the gear icon and select `Backup and Restore`. You can backup and restore from there.

**Comment by PlaceboPRS** [comment]
> Click on the gear icon and select `Backup and Restore`. You can backup and restore from there.

Well I feel like a dummy now! Thank you so much, it really was that simple! All done now, thank you again I really appreciate it :)
