### ISSUE TITLE
APIv2-Thread_9 :: [f35a19d] Internal Error searching for show

### ISSUE THREAD

**Issue by myopenflixr** [pymedusa/Medusa#10137]
**Describe the bug**
Searching or shows throws error and no results are found.

**To Reproduce**
1. Go to Shows > Add Shows > Add New Show (Type Show Name) (Engilsh) (All Indexers)
2. Click on Search 

**Expected behavior**
Expected search results so that I could add new show

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Ubuntu 18.04.6 x64
 - Branch: Master
 - Commit: f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
 - Python version: 3.6.9
 - Database version: 44.18

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-11-29 08:37:10 ERROR	APIv2-Thread-9 :: [f35a19d] Internal Error searching for show. term(s): ['the beatles get back', 'beatles get back'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/api/v2/internal.py", line 246, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/opt/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/opt/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
AttributeError: 'NoneType' object has no attribute 'status_code'
2021-11-29 08:37:02 INFO	APIv2-Thread-7 :: [f35a19d] Error searching for show. term(s): ['Dave Chappelle: The Closer'] indexer: tmdb error: Show search returned zero results (cannot find show on Indexer)
2021-11-29 08:37:02 ERROR	APIv2-Thread-7 :: [f35a19d] Internal Error searching for show. term(s): ['Dave Chappelle: The Closer'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/api/v2/internal.py", line 246, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/opt/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/opt/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
AttributeError: 'NoneType' object has no attribute 'status_code'
2021-11-29 08:34:07 ERROR	APIv2-Thread-9 :: [f35a19d] Internal Error searching for show. term(s): ['the beatles get back', 'beatles get back'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/api/v2/internal.py", line 246, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/opt/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/opt/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
AttributeError: 'NoneType' object has no attribute 'status_code'
2021-11-29 08:33:59 INFO	APIv2-Thread-7 :: [f35a19d] Error searching for show. term(s): ['Dave Chappelle: The Closer'] indexer: tvdb error: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/search/series?name=dave+chappelle%3A+the+closer (404)
2021-11-29 08:32:57 WARNING	APIv2-Thread-2 :: [f35a19d] Config patch ignored {'subtitles': {'enabled': None}, 'subtitlesMulti': None}
2021-11-29 08:32:28 WARNING	APIv2-Thread-6 :: [f35a19d] Couldn't determine current branch or current branch master doesn't match desired branch develop.
Checkout the desired branch or try again later.
2021-11-29 08:32:28 INFO	APIv2-Thread-6 :: [f35a19d] Config backup successful
2021-11-29 08:32:23 INFO	APIv2-Thread-6 :: [f35a19d] Config backup in progress...
2021-11-29 08:30:36 INFO	MAIN :: [f35a19d] Building internal name cache for all shows
2021-11-29 08:30:36 INFO	MAIN :: [f35a19d] Finished processing 3801 scene exceptions.
2021-11-29 08:30:36 INFO	MAIN :: [f35a19d] Updating exception_cache and exception_season_cache
2021-11-29 08:30:35 INFO	MAIN :: [f35a19d] Checking for scene exceptions updates from AniDB
2021-11-29 08:30:35 INFO	MAIN :: [f35a19d] Checking for XEM scene exceptions updates for TVDBv2
2021-11-29 08:30:35 INFO	MAIN :: [f35a19d] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tmdb.json
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tvmaze.json
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tvdb.json
2021-11-29 08:30:34 INFO	TORNADO :: [f35a19d] Starting Medusa on http://0.0.0.0:8081/tvshows/
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] Starting Medusa [master] using '/opt/medusa/config.ini'
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] 54887: Unable to find IMDb info in the database: How I Met Your Father
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] 12345: Unable to find the show in the database
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] [CACHE-DB] Updated major version to: 4.None
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] [CACHE-DB] Updated major version to: 3.None
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] Proceeding with upgrade
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] Backing up database before upgrade
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] [CACHE-DB] Updated major version to: 2.None
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] Proceeding with upgrade
2021-11-29 08:30:34 INFO	MAIN :: [f35a19d] Backing up database before upgrade
2021-11-29 08:30:33 INFO	MAIN :: [f35a19d] Changed TV download folder to /mnt/Downloads/sabnzbd/complete/TV
2021-11-29 08:30:33 INFO	MAIN :: [f35a19d] Broken providers found: ['danishbits']
2021-11-29 08:30:33 INFO	MAIN :: [f35a19d] Changed https key path to server.key
2021-11-29 08:30:33 INFO	MAIN :: [f35a19d] Changed https cert path to server.crt
2021-11-29 08:30:11 INFO	EVENT-QUEUE :: [f35a19d] Shutting down Tornado
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Saving config file to disk
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Saving all shows to the database
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the EVENT-QUEUE thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the POSTPROCESSORQUEUE thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the POSTPROCESSOR thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the DOWNLOADHANDLER thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the FINDSUBTITLES thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the FINDPROPERS thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the TRAKTCHECKER thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the MANUALSNATCHQUEUE thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the FORCEDSEARCHQUEUE thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the SHOWQUEUE thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the CHECKVERSION thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the EPISODEUPDATER thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the SHOWUPDATER thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the BACKLOG thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Waiting for the DAILYSEARCHER thread to exit
2021-11-29 08:30:10 INFO	EVENT-QUEUE :: [f35a19d] Aborting all threads
2021-11-29 08:30:10 INFO	MAIN :: [f35a19d] Signal 15 caught, saving and exiting...
2021-11-29 08:26:45 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] No needed episodes found
2021-11-29 08:26:42 INFO	SEARCHQUEUE-DAILY-SEARCH :: DogNZB :: [f35a19d] Removing cache entries older than 1 days from dognzb
2021-11-29 08:26:40 INFO	SEARCHQUEUE-DAILY-SEARCH :: NZBGeek :: [f35a19d] Removing cache entries older than 1 days from nzbgeek
2021-11-29 08:26:39 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Using daily search providers
2021-11-29 08:26:39 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Beginning daily search for new episodes
2021-11-29 08:26:39 INFO	POSTPROCESSOR :: [f35a19d] Post-processing completed.
2021-11-29 08:26:39 INFO	POSTPROCESSOR :: [f35a19d] Processing path: /mnt/Downloads/sabnzbd/complete/TV
2021-11-29 08:21:39 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Completed the search for new propers, next check in approx. 14m, 59s
2021-11-29 08:21:39 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] No recently aired new episodes, nothing to search for
2021-11-29 08:21:39 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Using proper search days: 2
2021-11-29 08:21:39 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Beginning proper search for new episodes
2021-11-29 08:21:38 INFO	FINDPROPERS :: [f35a19d] Beginning the search for new propers
2021-11-29 08:16:46 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] No needed episodes found
2021-11-29 08:16:46 INFO	SEARCHQUEUE-DAILY-SEARCH :: NZBGeek :: [f35a19d] Removing cache entries older than 1 days from nzbgeek
2021-11-29 08:16:41 INFO	SEARCHQUEUE-DAILY-SEARCH :: DogNZB :: [f35a19d] Removing cache entries older than 1 days from dognzb
2021-11-29 08:16:39 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Using daily search providers
2021-11-29 08:16:39 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Beginning daily search for new episodes
2021-11-29 08:16:39 INFO	POSTPROCESSOR :: [f35a19d] Post-processing completed.
2021-11-29 08:16:39 INFO	POSTPROCESSOR :: [f35a19d] Processing path: /mnt/Downloads/sabnzbd/complete/TV
2021-11-29 08:06:48 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] No needed episodes found
2021-11-29 08:06:48 INFO	SEARCHQUEUE-DAILY-SEARCH :: NZBGeek :: [f35a19d] Removing cache entries older than 1 days from nzbgeek
2021-11-29 08:06:44 INFO	SEARCHQUEUE-DAILY-SEARCH :: DogNZB :: [f35a19d] Removing cache entries older than 1 days from dognzb
2021-11-29 08:06:41 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Using daily search providers
2021-11-29 08:06:41 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Beginning daily search for new episodes
2021-11-29 08:06:38 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Completed the search for new propers, next check in approx. 14m, 59s
2021-11-29 08:06:38 INFO	POSTPROCESSOR :: [f35a19d] Post-processing completed.
2021-11-29 08:06:38 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] No recently aired new episodes, nothing to search for
2021-11-29 08:06:38 INFO	POSTPROCESSOR :: [f35a19d] Processing path: /mnt/Downloads/sabnzbd/complete/TV
2021-11-29 08:06:38 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Using proper search days: 2
2021-11-29 08:06:38 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Beginning proper search for new episodes
2021-11-29 08:06:37 INFO	FINDPROPERS :: [f35a19d] Beginning the search for new propers
2021-11-29 07:56:46 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] No needed episodes found
2021-11-29 07:56:46 INFO	SEARCHQUEUE-DAILY-SEARCH :: NZBGeek :: [f35a19d] Removing cache entries older than 1 days from nzbgeek
2021-11-29 07:56:42 INFO	SEARCHQUEUE-DAILY-SEARCH :: DogNZB :: [f35a19d] Removing cache entries older than 1 days from dognzb
2021-11-29 07:56:40 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Using daily search providers
2021-11-29 07:56:40 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Beginning daily search for new episodes
2021-11-29 07:56:37 INFO	POSTPROCESSOR :: [f35a19d] Post-processing completed.
2021-11-29 07:56:37 INFO	POSTPROCESSOR :: [f35a19d] Processing path: /mnt/Downloads/sabnzbd/complete/TV
2021-11-29 07:51:37 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Completed the search for new propers, next check in approx. 14m, 58s
2021-11-29 07:51:37 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] No recently aired new episodes, nothing to search for
2021-11-29 07:51:37 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Using proper search days: 2
2021-11-29 07:51:37 INFO	SEARCHQUEUE-PROPER-SEARCH :: [f35a19d] Beginning proper search for new episodes
2021-11-29 07:51:36 INFO	FINDPROPERS :: [f35a19d] Beginning the search for new propers
2021-11-29 07:46:48 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] No needed episodes found
2021-11-29 07:46:41 INFO	SEARCHQUEUE-DAILY-SEARCH :: DogNZB :: [f35a19d] Removing cache entries older than 1 days from dognzb
2021-11-29 07:46:39 INFO	SEARCHQUEUE-DAILY-SEARCH :: NZBGeek :: [f35a19d] Removing cache entries older than 1 days from nzbgeek
2021-11-29 07:46:37 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Using daily search providers
2021-11-29 07:46:37 INFO	POSTPROCESSOR :: [f35a19d] Post-processing completed.
2021-11-29 07:46:37 INFO	POSTPROCESSOR :: [f35a19d] Processing path: /mnt/Downloads/sabnzbd/complete/TV
2021-11-29 07:46:37 INFO	SEARCHQUEUE-DAILY-SEARCH :: [f35a19d] Beginning daily search for new episodes
2021-11-29 07:44:08 ERROR	APIv2-Thread-7 :: [f35a19d] Internal Error searching for show. term(s): ['the voice', 'voice'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/api/v2/internal.py", line 246, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/opt/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/opt/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
AttributeError: 'NoneType' object has no attribute 'status_code'
2021-11-29 07:43:02 ERROR	APIv2-Thread-3 :: [f35a19d] Internal Error searching for show. term(s): ['the beatles', 'beatles'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/api/v2/internal.py", line 246, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/opt/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/opt/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
AttributeError: 'NoneType' object has no attribute 'status_code'
2021-11-29 07:41:04 ERROR	APIv2-Thread-7 :: [f35a19d] Internal Error searching for show. term(s): ['the voice', 'voice'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/api/v2/internal.py", line 246, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/opt/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/opt/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
AttributeError: 'NoneType' object has no attribute 'status_code'
2021-11-29 07:39:59 ERROR	APIv2-Thread-3 :: [f35a19d] Internal Error searching for show. term(s): ['the beatles', 'beatles'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/api/v2/internal.py", line 246, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/opt/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/opt/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/opt/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
```
</details>

**Additional context**
This seems to be an issue with any show that I search for, not just a couple specific shows.

**Comment by p0psicles** [comment]
Any issues connecting to tvmaze API?

**Comment by myopenflixr** [comment]
I also followed the following instructions and this did not resolve the issue.
`Close Medusa, then delete cache.db in your Medusa directory`

**Comment by myopenflixr** [comment]
> Any issues connecting to tvmaze API?

@p0psicles How would I check this?

**Comment by myopenflixr** [comment]
@p0psicles It does appear that I cannot ping api.tvmaze.com from my network. Not sure if this is what you were referring to but I figured I would give this a try and report my results.

**Comment by medariox** [comment]
This schuld already be fixed in the `develop` branch.

**Comment by myopenflixr** [comment]
@medariox When will this fix make it to the `master` branch so that I can start adding new shows again?

**Comment by p0psicles** [comment]
This fix only makes sure you get a nice warning in stead of the stack trace. So just a better error mesage. You'll need to fix your connectivity to tvmaze. Or make sure your doing specific searches using tvdb or tmdb.

**Comment by myopenflixr** [comment]
Any suggestions on how to fix my connection with tvmaze? I can ping tvmaze.com but not api.tvmaze.com. I've never encountered this issue before and not sure where to begin. Nothing has changed on my network that I'm aware of. Everything has worked flawlessly for the past couple of years (until now).

**Comment by p0psicles** [comment]
I don't know. Maybe you got a temp ban? Because of exeeding thresholds? Maybe you can contact them through their forum. Or do some research and check if they do like temp ip bans?

**Comment by medariox** [comment]
Are you using a VPN? They block VPNs that query their API.

**Comment by BenjV** [comment]
If you cannot ping api.tvmaze.com then something is wrong with your own network, I can ping it just fine.
Did you check if you dns is working correct with nslookup:

> nslookup api.tvmaze.com


You can also simply test the TvMaze api by giving this command to your browser.

> https://api.tvmaze.com/search/shows?q=girls

It will return data in json format about the show "girls"

**Comment by myopenflixr** [comment]
I resolved the issue. It my was router/firewall (UniFi Dream Machine Pro) . I had it configured to "Allow" only specific countries and block the rest. However, even though api.tvmaze.com is a German ip address (which I had selected as allowed in the router), the hops to get to me must have traveled through a country I had blocked. I ended up disabling the GeoIP filtering altogether.
