### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Z:\\Torrents\\CompletedDownloads\\Tv\\The.Rookie.S04E08.720p.HEVC.x265-MeGusta[eztv.re].mkv'

### ISSUE THREAD

**Issue by lazeras** [pymedusa/Medusa#10149]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-12-06 15:22:44 ERROR    POSTPROCESSOR :: [f35a19d] Unable to move file Z:\Torrents\CompletedDownloads\Tv\The.Rookie.S04E08.720p.HEVC.x265-MeGusta[eztv.re].mkv to Z:\TVSeries\The Rookie\Season 04\The Rookie - S04E08 - Hit and Run.mkv: PermissionError(13, 'The process cannot access the file because it is being used by another process')
Traceback (most recent call last):
  File "C:\Medusa\Python\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Z:\\Torrents\\CompletedDownloads\\Tv\\The.Rookie.S04E08.720p.HEVC.x265-MeGusta[eztv.re].mkv' -> 'Z:\\TVSeries\\The Rookie\\Season 04\\The Rookie - S04E08 - Hit and Run.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/helpers/__init__.py#L320">medusa\helpers\__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Z:\\Torrents\\CompletedDownloads\\Tv\\The.Rookie.S04E08.720p.HEVC.x265-MeGusta[eztv.re].mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/post_processor.py#L477">medusa\post_processor.py</a>", line 477, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "C:\Medusa\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/helpers/__init__.py#L324">medusa\helpers\__init__.py</a>", line 324, in move_file
    os.unlink(src_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Z:\\Torrents\\CompletedDownloads\\Tv\\The.Rookie.S04E08.720p.HEVC.x265-MeGusta[eztv.re].mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by lazeras** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-01-23 21:26:06 ERROR    POSTPROCESSOR :: [1405fbb] Unable to move file Z:\Torrents\CompletedDownloads\Tv\SEAL.Team.S05E14.720p.HEVC.x265-MeGusta[eztv.re].mkv to Z:\TVSeries\SEAL Team\Season 05\SEAL Team - S05E14 - All Bravo Stations.mkv: PermissionError(13, 'The process cannot access the file because it is being used by another process')
Traceback (most recent call last):
  File "C:\Medusa\Python\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Z:\\Torrents\\CompletedDownloads\\Tv\\SEAL.Team.S05E14.720p.HEVC.x265-MeGusta[eztv.re].mkv' -> 'Z:\\TVSeries\\SEAL Team\\Season 05\\SEAL Team - S05E14 - All Bravo Stations.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/helpers/__init__.py#L320">medusa\helpers\__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Z:\\Torrents\\CompletedDownloads\\Tv\\SEAL.Team.S05E14.720p.HEVC.x265-MeGusta[eztv.re].mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/post_processor.py#L477">medusa\post_processor.py</a>", line 477, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "C:\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/helpers/__init__.py#L324">medusa\helpers\__init__.py</a>", line 324, in move_file
    os.unlink(src_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Z:\\Torrents\\CompletedDownloads\\Tv\\SEAL.Team.S05E14.720p.HEVC.x265-MeGusta[eztv.re].mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
