### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [Errno 13] Permission denied: 'C:\\GitHub\\Medusa\\Logs\\application.log.6'

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#10159]
### INFO
**Python Version**: `3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-12-07 15:13:05 ERROR    TORNADO :: [f35a19d] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/log?level=INFO&thread=&period=one_day&query=&limit=1000 (192.168.2.16)
Traceback (most recent call last):
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/tornado/web.py#L1704">ext\tornado\web.py</a>", line 1704, in _execute
    result = await result
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/tornado/gen.py#L769">ext\tornado\gen.py</a>", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/server/api/v2/base.py#L64">medusa\server\api\v2\base.py</a>", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/tornado/gen.py#L762">ext\tornado\gen.py</a>", line 762, in run
    value = future.result()
  File "C:\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/server/api/v2/log.py#L144">medusa\server\api\v2\log.py</a>", line 144, in get
    return self._paginate(data_generator=data_generator)
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/server/api/v2/base.py#L342">medusa\server\api\v2\base.py</a>", line 342, in _paginate
    results = list(data_generator())[:arg_limit]
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/server/api/v2/log.py#L140">medusa\server\api\v2\log.py</a>", line 140, in data_generator
    for line in read_loglines(**reader_kwargs):
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/logger/__init__.py#L166">medusa\logger\__init__.py</a>", line 166, in read_loglines
    for line in reverse_readlines(f):
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/logger/__init__.py#L259">medusa\logger\__init__.py</a>", line 259, in reverse_readlines
    for block in block_generator(file_path, size=block_size):
  File "C:\GitHub\Medusa\<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/logger/__init__.py#L225">medusa\logger\__init__.py</a>", line 225, in blocks_r
    with io.open(file_path, 'rb') as file_obj:
PermissionError: [Errno 13] Permission denied: 'C:\\GitHub\\Medusa\\Logs\\application.log.6'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Something changed the permissions on that log file.

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-04-20 21:13:12 ERROR    TORNADO :: [e4870f8] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/log?level=INFO&thread=&period=one_day&query=&limit=1000 (192.168.10.76)
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/ext/tornado/web.py#L1704">ext\tornado\web.py</a>", line 1704, in _execute
    result = await result
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/ext/tornado/gen.py#L769">ext\tornado\gen.py</a>", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/api/v2/base.py#L64">medusa\server\api\v2\base.py</a>", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/ext/tornado/gen.py#L762">ext\tornado\gen.py</a>", line 762, in run
    value = future.result()
  File "C:\Medusa\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/api/v2/log.py#L144">medusa\server\api\v2\log.py</a>", line 144, in get
    return self._paginate(data_generator=data_generator)
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/api/v2/base.py#L343">medusa\server\api\v2\base.py</a>", line 343, in _paginate
    results = list(data_generator())[:arg_limit]
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/api/v2/log.py#L140">medusa\server\api\v2\log.py</a>", line 140, in data_generator
    for line in read_loglines(**reader_kwargs):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/logger/__init__.py#L166">medusa\logger\__init__.py</a>", line 166, in read_loglines
    for line in reverse_readlines(f):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/logger/__init__.py#L259">medusa\logger\__init__.py</a>", line 259, in reverse_readlines
    for block in block_generator(file_path, size=block_size):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/logger/__init__.py#L225">medusa\logger\__init__.py</a>", line 225, in blocks_r
    with io.open(file_path, 'rb') as file_obj:
PermissionError: [Errno 13] Permission denied: 'C:\\Medusa\\Data\\Logs\\application.log.3'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-05-07 08:07:03 ERROR    TORNADO :: [e4870f8] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/log?level=INFO&thread=&period=one_day&query=&limit=1000 (192.168.10.76)
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/ext/tornado/web.py#L1704">ext\tornado\web.py</a>", line 1704, in _execute
    result = await result
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/ext/tornado/gen.py#L769">ext\tornado\gen.py</a>", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/api/v2/base.py#L64">medusa\server\api\v2\base.py</a>", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/ext/tornado/gen.py#L762">ext\tornado\gen.py</a>", line 762, in run
    value = future.result()
  File "C:\Medusa\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/api/v2/log.py#L144">medusa\server\api\v2\log.py</a>", line 144, in get
    return self._paginate(data_generator=data_generator)
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/api/v2/base.py#L343">medusa\server\api\v2\base.py</a>", line 343, in _paginate
    results = list(data_generator())[:arg_limit]
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/api/v2/log.py#L140">medusa\server\api\v2\log.py</a>", line 140, in data_generator
    for line in read_loglines(**reader_kwargs):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/logger/__init__.py#L166">medusa\logger\__init__.py</a>", line 166, in read_loglines
    for line in reverse_readlines(f):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/logger/__init__.py#L259">medusa\logger\__init__.py</a>", line 259, in reverse_readlines
    for block in block_generator(file_path, size=block_size):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/logger/__init__.py#L225">medusa\logger\__init__.py</a>", line 225, in blocks_r
    with io.open(file_path, 'rb') as file_obj:
PermissionError: [Errno 13] Permission denied: 'C:\\Medusa\\Data\\Logs\\application.log.1'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
@nydave69 you definitely have some file access issues. Or maybe a dieing disk? But I see other reported issues. And something definitely is wrong with your setup
