### ISSUE TITLE
[APP SUBMITTED]: LookupError: unknown encoding: us-ascii

### ISSUE THREAD

**Issue by papampi** [pymedusa/Medusa#10172]
### INFO
**Python Version**: `3.9.6 (default, Aug 22 2021, 06:41:01) [GCC 8.4.0]`
**Operating System**: `Linux-5.10.60-qnap-x86_64-with-glibc2.27`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
**Link to Log**: https://gist.github.com/779190ee0a5127adf6535202750ea3b0
### ERROR
<pre>
2021-12-17 04:13:16 ERROR    SHOWQUEUE-REFRESH :: [f35a19d] 305582: Error while refreshing show Wynonna Earp. Error: unknown encoding: us-ascii
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/api.py#L64">ext/knowit/api.py</a>", line 64, in know
    result = provider.describe(video_path, context)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/providers/mediainfo.py#L296">ext/knowit/providers/mediainfo.py</a>", line 296, in describe
    video_path, self.executor.location, debug_data())
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/providers/mediainfo.py#L289">ext/knowit/providers/mediainfo.py</a>", line 289, in debug_data
    xml = ensure_text(ElementTree.tostring(media_info.xml_dom)).replace('\r', '').replace('\n', '')
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 1109, in tostring
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 732, in write
  File "/opt/lib/python3.9/contextlib.py", line 117, in __enter__
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 801, in _get_writer
LookupError: unknown encoding: us-ascii

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/queues/show_queue.py#L514">medusa/queues/show_queue.py</a>", line 514, in run
    self.show.refresh_dir()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/tv/series.py#L2048">medusa/tv/series.py</a>", line 2048, in refresh_dir
    self.load_episodes_from_dir()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/tv/series.py#L1098">medusa/tv/series.py</a>", line 1098, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/tv/series.py#L1442">medusa/tv/series.py</a>", line 1442, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/tv/episode.py#L2082">medusa/tv/episode.py</a>", line 2082, in update_status_quality
    new_quality = Quality.name_quality(filepath, self.series.is_anime)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/common.py#L287">medusa/common.py</a>", line 287, in name_quality
    return Quality._extend_quality(name)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/common.py#L394">medusa/common.py</a>", line 394, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/common.py#L416">medusa/common.py</a>", line 416, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/api.py#L70">ext/knowit/api.py</a>", line 70, in know
    raise KnowitException(debug_info(context=context, exc_info=True))
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/api.py#L121">ext/knowit/api.py</a>", line 121, in debug_info
    lines.append(debug_data())
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/providers/mediainfo.py#L289">ext/knowit/providers/mediainfo.py</a>", line 289, in debug_data
    xml = ensure_text(ElementTree.tostring(media_info.xml_dom)).replace('\r', '').replace('\n', '')
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 1109, in tostring
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 732, in write
  File "/opt/lib/python3.9/contextlib.py", line 117, in __enter__
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 801, in _get_writer
LookupError: unknown encoding: us-ascii
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by papampi** [comment]
### INFO
**Python Version**: `3.9.6 (default, Aug 22 2021, 06:41:01) [GCC 8.4.0]`
**Operating System**: `Linux-5.10.60-qnap-x86_64-with-glibc2.27`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
**Link to Log**: https://gist.github.com/c421265d90a0f2f1b53926bffa66af6c
### ERROR
<pre>
2021-12-17 11:37:36 ERROR    SHOWQUEUE-REFRESH :: [f35a19d] 375995: Error while refreshing show Young Rock. Error: unknown encoding: us-ascii
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/api.py#L64">ext/knowit/api.py</a>", line 64, in know
    result = provider.describe(video_path, context)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/providers/mediainfo.py#L296">ext/knowit/providers/mediainfo.py</a>", line 296, in describe
    video_path, self.executor.location, debug_data())
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/providers/mediainfo.py#L289">ext/knowit/providers/mediainfo.py</a>", line 289, in debug_data
    xml = ensure_text(ElementTree.tostring(media_info.xml_dom)).replace('\r', '').replace('\n', '')
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 1109, in tostring
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 732, in write
  File "/opt/lib/python3.9/contextlib.py", line 117, in __enter__
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 801, in _get_writer
LookupError: unknown encoding: us-ascii

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/queues/show_queue.py#L514">medusa/queues/show_queue.py</a>", line 514, in run
    self.show.refresh_dir()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/tv/series.py#L2048">medusa/tv/series.py</a>", line 2048, in refresh_dir
    self.load_episodes_from_dir()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/tv/series.py#L1098">medusa/tv/series.py</a>", line 1098, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/tv/series.py#L1442">medusa/tv/series.py</a>", line 1442, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/tv/episode.py#L2082">medusa/tv/episode.py</a>", line 2082, in update_status_quality
    new_quality = Quality.name_quality(filepath, self.series.is_anime)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/common.py#L287">medusa/common.py</a>", line 287, in name_quality
    return Quality._extend_quality(name)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/common.py#L394">medusa/common.py</a>", line 394, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/medusa/common.py#L416">medusa/common.py</a>", line 416, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/api.py#L70">ext/knowit/api.py</a>", line 70, in know
    raise KnowitException(debug_info(context=context, exc_info=True))
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/api.py#L121">ext/knowit/api.py</a>", line 121, in debug_info
    lines.append(debug_data())
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/f35a19da6bc4efcafff8facca6a4d5b9e3f3f501/ext/knowit/providers/mediainfo.py#L289">ext/knowit/providers/mediainfo.py</a>", line 289, in debug_data
    xml = ensure_text(ElementTree.tostring(media_info.xml_dom)).replace('\r', '').replace('\n', '')
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 1109, in tostring
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 732, in write
  File "/opt/lib/python3.9/contextlib.py", line 117, in __enter__
  File "/opt/lib/python3.9/xml/etree/ElementTree.py", line 801, in _get_writer
LookupError: unknown encoding: us-ascii
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
`us-ascii` is not a valid encoding name.
