### ISSUE TITLE
[APP SUBMITTED]: trakt.errors.NotFoundException: Not Found - method exists, but no record found

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#10176]
### INFO
**Python Version**: `3.8.12 (default, Oct 13 2021, 06:42:42) [Clang 13.0.0 (clang-1300.0.29.3)]`
**Operating System**: `macOS-11.6.1-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [feature/pp-check-corruption](../tree/feature/pp-check-corruption)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@dee6639d07521015926db6886ceb3eaeba652e55
**Link to Log**: https://gist.github.com/bbe223eb74bfc2c07fbca9c4a3f4b52d
### ERROR
<pre>
2021-12-20 01:22:52 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [dee6639] Could not connect to Trakt service: Not Found - method exists, but no record found
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/medusa/show/recommendations/trakt.py#L165">medusa/show/recommendations/trakt.py</a>", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "</Users/ovidijus/Apps/Medusa/ext/decorator.py:decorator-gen-54>", line 2, in _create_recommended_show
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/ext/dogpile/cache/region.py#L1577">ext/dogpile/cache/region.py</a>", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/ext/dogpile/cache/region.py#L1042">ext/dogpile/cache/region.py</a>", line 1042, in get_or_create
    with Lock(
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/ext/dogpile/lock.py#L185">ext/dogpile/lock.py</a>", line 185, in __enter__
    return self._enter()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/ext/dogpile/lock.py#L94">ext/dogpile/lock.py</a>", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/ext/dogpile/lock.py#L178">ext/dogpile/lock.py</a>", line 178, in _enter_create
    return self.creator()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/ext/dogpile/cache/region.py#L995">ext/dogpile/cache/region.py</a>", line 995, in gen_value
    created_value = creator(
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/medusa/show/recommendations/trakt.py#L68">medusa/show/recommendations/trakt.py</a>", line 68, in _create_recommended_show
    **{'rating': show.ratings['rating'],
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/ext/trakt/core.py#L547">ext/trakt/core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/dee6639d07521015926db6886ceb3eaeba652e55/ext/trakt/core.py#L524">ext/trakt/core.py</a>", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by WarEagleUS21** [comment]
### INFO
**Python Version**: `3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [](../tree/)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@027c3d450d87bc35e0e083336fe287984e840d85
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-12-19 00:47:59 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [027c3d4] Could not connect to Trakt service: Not Found - method exists, but no record found
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/medusa/show/recommendations/trakt.py#L165">medusa\show\recommendations\trakt.py</a>", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "<C:\Medusa\Medusa\ext\decorator.py:decorator-gen-54>", line 2, in _create_recommended_show
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/ext/dogpile/cache/region.py#L1577">ext\dogpile\cache\region.py</a>", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/ext/dogpile/cache/region.py#L1042">ext\dogpile\cache\region.py</a>", line 1042, in get_or_create
    with Lock(
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/ext/dogpile/lock.py#L185">ext\dogpile\lock.py</a>", line 185, in __enter__
    return self._enter()
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/ext/dogpile/lock.py#L94">ext\dogpile\lock.py</a>", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/ext/dogpile/lock.py#L178">ext\dogpile\lock.py</a>", line 178, in _enter_create
    return self.creator()
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/ext/dogpile/cache/region.py#L995">ext\dogpile\cache\region.py</a>", line 995, in gen_value
    created_value = creator(
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/medusa/show/recommendations/trakt.py#L68">medusa\show\recommendations\trakt.py</a>", line 68, in _create_recommended_show
    **{'rating': show.ratings['rating'],
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/ext/trakt/core.py#L547">ext\trakt\core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "C:\Medusa\Medusa\<a href="../blob/027c3d450d87bc35e0e083336fe287984e840d85/ext/trakt/core.py#L524">ext\trakt\core.py</a>", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-01-21 01:25:18 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [1405fbb] Could not connect to Trakt service: Not Found - method exists, but no record found
Traceback (most recent call last):
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/show/recommendations/trakt.py#L165">medusa\show\recommendations\trakt.py</a>", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "<C:\GitHub\Medusa\ext\decorator.py:decorator-gen-54>", line 2, in _create_recommended_show
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/region.py#L1577">ext\dogpile\cache\region.py</a>", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/region.py#L1042">ext\dogpile\cache\region.py</a>", line 1042, in get_or_create
    with Lock(
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/lock.py#L185">ext\dogpile\lock.py</a>", line 185, in __enter__
    return self._enter()
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/lock.py#L94">ext\dogpile\lock.py</a>", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/lock.py#L178">ext\dogpile\lock.py</a>", line 178, in _enter_create
    return self.creator()
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/region.py#L995">ext\dogpile\cache\region.py</a>", line 995, in gen_value
    created_value = creator(
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/show/recommendations/trakt.py#L68">medusa\show\recommendations\trakt.py</a>", line 68, in _create_recommended_show
    **{'rating': show.ratings['rating'],
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/trakt/core.py#L547">ext\trakt\core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "C:\GitHub\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/trakt/core.py#L524">ext\trakt\core.py</a>", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-17-amd64-x86_64-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [feature/templated-search-strings](../tree/feature/templated-search-strings)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@fb3dccc7b7f81c90a8518ee522469c4cdcd2f486
**Link to Log**: https://gist.github.com/38e6047021845c1a50320110b5dfdf29
### ERROR
<pre>
2022-01-21 02:23:23 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [fb3dccc] Could not connect to Trakt service: Not Found - method exists, but no record found
Traceback (most recent call last):
  File "/**********/Medusa/medusa/show/recommendations/trakt.py", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "</**********/Medusa/ext/decorator.py:decorator-gen-54>", line 2, in _create_recommended_show
  File "/**********/Medusa/ext/dogpile/cache/region.py", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/**********/Medusa/ext/dogpile/cache/region.py", line 1047, in get_or_create
    async_creator,
  File "/**********/Medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/**********/Medusa/ext/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "/**********/Medusa/ext/dogpile/lock.py", line 178, in _enter_create
    return self.creator()
  File "/**********/Medusa/ext/dogpile/cache/region.py", line 996, in gen_value
    *creator_args[0], **creator_args[1]
  File "/**********/Medusa/medusa/show/recommendations/trakt.py", line 68, in _create_recommended_show
    **{'rating': show.ratings['rating'],
  File "/**********/Medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/**********/Medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.NotFoundException: Not Found - method exists, but no record found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
is this fixable when clearing the dogpile cache?

**Comment by duramato** [comment]
Going to try it
