### ISSUE TITLE
Deluge - AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by taduo** [pymedusa/Medusa#10190]
**Describe the bug**
Deluge integration seams to stop working after the medusa upgrade.
Am not able to fetch a torrent.
Not abe to successfully test in torrent Search settings, getting "Error while testing connection. Check warning logs."
 
**Medusa (please complete the following information):**
- OS: Linux-4.15.0-151-generic-x86_64-with-Ubuntu-18.04-bionic
- Commit: 3e258d2932fcc90437751efc3c5c4b82d447f3c5
- Version: 0.5.21
- Database: 44.18
- Python version: 3.6.9 (default, Dec 8 2021, 21:08:43) [GCC 8.4.0]

**Debug logs (at least 50 lines):**

```
2021-12-22 17:27:54 ERROR    SNATCHQUEUE-SNATCH-276515 :: [3e258d2] Snatch failed! For result: The.Curse.of.Oak.Island.S09E08.Deeper.Digs.Bigger.Stakes.720p.WEB.h264-KOMPOST[rartv]
Traceback (most recent call last):
  File "/home/hd29/**********/apps/medusa/medusa/search/queue.py", line 516, in run
    self.success = snatch_result(result)
  File "/home/hd29/**********/apps/medusa/medusa/search/core.py", line 167, in snatch_result
    client = torrent.get_client_class(app.TORRENT_METHOD)()
  File "/home/hd29/**********/apps/medusa/medusa/clients/torrent/deluge.py", line 125, in __init__
    self._get_auth()
  File "/home/hd29/**********/apps/medusa/medusa/clients/torrent/deluge.py", line 221, in _get_auth
    self._get_version()
  File "/home/hd29/**********/apps/medusa/medusa/clients/torrent/deluge.py", line 238, in _get_version
    split_version = version.json()['result'].split('.')[0:2]
AttributeError: 'NoneType' object has no attribute 'split'
```
</details>

**Additional context**
Using http for the integration.
- Deluge ver: 1.3.15

**Comment by p0psicles** [comment]
my bad. I'll fix it and push a new release.

**Comment by taduo** [comment]
I confirm, with the new release is not working:
Commit: 1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
Version: 0.5.22

Thnak you @p0psicles

**Comment by p0psicles** [comment]
Thank you for reporting!
