### ISSUE TITLE
[APP SUBMITTED]: dbm.error: need 'c' or 'n' flag to open new db

### ISSUE THREAD

**Issue by pct00** [pymedusa/Medusa#10197]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-12-24 01:25:09 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [1405fbb] Could not connect to Trakt service: need 'c' or 'n' flag to open new db
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/show/recommendations/trakt.py#L165">medusa\show\recommendations\trakt.py</a>", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "<C:\Program Files\Medusa\Medusa\ext\decorator.py:decorator-gen-54>", line 2, in _create_recommended_show
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/region.py#L1578">ext\dogpile\cache\region.py</a>", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/region.py#L1047">ext\dogpile\cache\region.py</a>", line 1047, in get_or_create
    async_creator,
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/lock.py#L185">ext\dogpile\lock.py</a>", line 185, in __enter__
    return self._enter()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/lock.py#L87">ext\dogpile\lock.py</a>", line 87, in _enter
    value = value_fn()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/region.py#L977">ext\dogpile\cache\region.py</a>", line 977, in get_value
    value = self._get_from_backend(key)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/region.py#L1265">ext\dogpile\cache\region.py</a>", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/backends/file.py#L217">ext\dogpile\cache\backends\file.py</a>", line 217, in get_serialized
    with self._dbm_file(False) as dbm_obj:
  File "C:\Program Files\Medusa\Python\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/ext/dogpile/cache/backends/file.py#L213">ext\dogpile\cache\backends\file.py</a>", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
  File "C:\Program Files\Medusa\Python\lib\dbm\__init__.py", line 85, in open
    raise error[0]("need 'c' or 'n' flag to open new db")
dbm.error: need 'c' or 'n' flag to open new db
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Looks like your dogpile cache file is corrupt.
Stop medusa.
Remove recommended.dbm
start medusa.

Should be fixed.

**Comment by duramato** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-19-amd64-x86_64-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@70d6f34448b91bcf8b684caeec9fd661d63d9f97
**Link to Log**: https://gist.github.com/34710b593649c457f5f46faef5a40b43
### ERROR
<pre>
2022-04-04 02:11:09 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [70d6f34] Could not connect to Trakt service: need 'c' or 'n' flag to open new db
Traceback (most recent call last):
  File "/**********/Medusa/medusa/show/recommendations/trakt.py", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "</**********/Medusa/ext/decorator.py:decorator-gen-56>", line 2, in _create_recommended_show
  File "/**********/Medusa/ext/dogpile/cache/region.py", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/**********/Medusa/ext/dogpile/cache/region.py", line 1047, in get_or_create
    async_creator,
  File "/**********/Medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/**********/Medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/**********/Medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/**********/Medusa/ext/dogpile/cache/region.py", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/**********/Medusa/ext/dogpile/cache/backends/file.py", line 217, in get_serialized
    with self._dbm_file(False) as dbm_obj:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/**********/Medusa/ext/dogpile/cache/backends/file.py", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
  File "/usr/lib/python3.7/dbm/__init__.py", line 85, in open
    raise error[0]("need 'c' or 'n' flag to open new db")
dbm.error: need 'c' or 'n' flag to open new db
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
