### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'get_id'

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#10194]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-17-amd64-x86_64-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@504ea7c8a6784910a0864dd8fe864b863b545504
**Link to Log**: https://gist.github.com/ac31702d89d3b5fe76296e0ab43d0fbd
### ERROR
<pre>
2021-12-23 11:48:02 ERROR    TORNADO :: [504ea7c] Uncaught exception in APIv2: AttributeError("'NoneType' object has no attribute 'get_id'")
Request: GET /api/v2/internal/getFailed?limit=100 (192.168.1.189)
Traceback (most recent call last):
  File "/**********/Medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/**********/Medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/**********/Medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/**********/Medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/**********/Medusa/medusa/server/api/v2/internal.py", line 68, in get
    return resource_function()
  File "/**********/Medusa/medusa/server/api/v2/internal.py", line 563, in resource_get_failed
    'id': provider.get_id(),
AttributeError: 'NoneType' object has no attribute 'get_id'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
I think this is already fixed
