### ISSUE TITLE
[APP SUBMITTED]: TypeError: index() got an unexpected keyword argument ''

### ISSUE THREAD

**Issue by Antaneyes** [pymedusa/Medusa#10229]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-01-02 15:01:20 ERROR    Thread_13 :: [1405fbb] Exception generated: index() got an unexpected keyword argument ''
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by roil13** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-5.10.63-v7l+-armv7l-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-02-03 15:25:05 ERROR    Thread_17 :: [1405fbb] Exception generated: index() got an unexpected keyword argument ''
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by roil13** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-5.10.63-v7l+-armv7l-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-02-05 22:46:17 ERROR    Thread_8 :: [1405fbb] Exception generated: index() got an unexpected keyword argument 'x'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'x'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Antaneyes** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-04-30 08:31:34 ERROR    Thread_41 :: [e4870f8] Exception generated: index() got an unexpected keyword argument ''
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MatthK** [comment]
### INFO
**Python Version**: `3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0]`
**Operating System**: `Linux-4.15.0-130-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@400903a534414868f6fcf74ea2a5adc71505645d
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-08-09 11:01:55 ERROR    Thread_0 :: [400903a] Exception generated: index() got an unexpected keyword argument 'rest_route'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/400903a534414868f6fcf74ea2a5adc71505645d/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'rest_route'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MatthK** [comment]
### INFO
**Python Version**: `3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0]`
**Operating System**: `Linux-4.15.0-130-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@400903a534414868f6fcf74ea2a5adc71505645d
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-08-20 20:29:58 ERROR    Thread_6 :: [400903a] Exception generated: index() got an unexpected keyword argument 'rand^X'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/400903a534414868f6fcf74ea2a5adc71505645d/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument 'rand^X'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Antaneyes** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@f690170c2cbd9f2804c38a6047059cb1ace8afe3
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-09-20 15:40:42 ERROR    Thread_56 :: [f690170] Exception generated: index() got an unexpected keyword argument ''
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f690170c2cbd9f2804c38a6047059cb1ace8afe3/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by m184711** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@f690170c2cbd9f2804c38a6047059cb1ace8afe3
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-09-22 15:04:23 ERROR    Thread_8 :: [f690170] Exception generated: index() got an unexpected keyword argument ''
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f690170c2cbd9f2804c38a6047059cb1ace8afe3/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MatthK** [comment]
### INFO
**Python Version**: `3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0]`
**Operating System**: `Linux-4.15.0-130-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@f690170c2cbd9f2804c38a6047059cb1ace8afe3
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-09-26 22:16:34 ERROR    Thread_4 :: [f690170] Exception generated: index() got an unexpected keyword argument '1'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/f690170c2cbd9f2804c38a6047059cb1ace8afe3/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument '1'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bhawson** [comment]
### INFO
**Python Version**: `3.9.6 (default, Oct 18 2022, 12:41:40) [Clang 14.0.0 (clang-1400.0.29.202)]`
**Operating System**: `macOS-12.6.3-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@671a44334d98db8a3872b23aa9dd82bb76fbfc4b
**Link to Log**: https://gist.github.com/63a6c2050517a1c5d0ceeab59fe779dc
### ERROR
<pre>
2023-03-18 11:18:07 ERROR    Thread_1 :: [671a443] Exception generated: index() got an unexpected keyword argument ''
Traceback (most recent call last):
  File "/Users/**********/Library/Application Support/Medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by m184711** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-04-09 01:09:22 ERROR    Thread_5 :: [6b37ad0] Exception generated: index() got an unexpected keyword argument ''
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bhawson** [comment]
### INFO
**Python Version**: `3.9.6 (default, Oct 18 2022, 12:41:40) [Clang 14.0.0 (clang-1400.0.29.202)]`
**Operating System**: `macOS-12.6.4-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-04-16 13:59:01 ERROR    Thread_0 :: [6b37ad0] Exception generated: index() got an unexpected keyword argument ''
Traceback (most recent call last):
  File "/Users/**********/Library/Application Support/Medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
TypeError: index() got an unexpected keyword argument ''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MatthK** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-139-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-04-19 04:47:40 ERROR    Thread_0 :: [6b37ad0] Exception generated: Home.index() got an unexpected keyword argument 's'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: Home.index() got an unexpected keyword argument 's'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MatthK** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.4.0-139-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-04-19 04:47:36 ERROR    Thread_0 :: [6b37ad0] Exception generated: Home.index() got an unexpected keyword argument '_method'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: Home.index() got an unexpected keyword argument '_method'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
