### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [Errno 13] Permission denied: 'Z:\\Anime\\The Twelve Kingdoms\\Season 01\\The Twelve Kingdoms - S01E01 - Shadow of the Moon, Sea of the Shadow - Chapter One.mkv'

### ISSUE THREAD

**Issue by lazeras** [pymedusa/Medusa#10281]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-01-27 13:56:18 ERROR    POSTPROCESSQUEUE-POST-PROCESS :: [1405fbb] OSError: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "C:\Medusa\Python\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\Torrents\\New folder\\The Twelve Kingdoms S01 Hi10p.BluRay.FLAC2.0.x264-CTR\\The.Twelve.Kingdoms.S01E01.1080p-Hi10p.BluRay.FLAC2.0.x264-CTR.[756B0532].mkv' -> 'Z:\\Anime\\The Twelve Kingdoms\\Season 01\\The Twelve Kingdoms - S01E01 - Shadow of the Moon, Sea of the Shadow - Chapter One.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/helpers/__init__.py#L320">medusa\helpers\__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [WinError 5] Access is denied: 'Z:\\Torrents\\New folder\\The Twelve Kingdoms S01 Hi10p.BluRay.FLAC2.0.x264-CTR\\The.Twelve.Kingdoms.S01E01.1080p-Hi10p.BluRay.FLAC2.0.x264-CTR.[756B0532].mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/helpers/__init__.py#L293">medusa\helpers\__init__.py</a>", line 293, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'Z:\\Anime\\The Twelve Kingdoms\\Season 01\\The Twelve Kingdoms - S01E01 - Shadow of the Moon, Sea of the Shadow - Chapter One.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by lazeras** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-01-27 14:11:14 ERROR    POSTPROCESSQUEUE-POST-PROCESS :: [1405fbb] OSError: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "C:\Medusa\Python\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'Z:\\Torrents\\New folder\\The Twelve Kingdoms S01 Hi10p.BluRay.FLAC2.0.x264-CTR\\The.Twelve.Kingdoms.S01E12.1080p-Hi10p.BluRay.FLAC2.0.x264-CTR.[0CE37B56].mkv' -> 'Z:\\Anime\\The Twelve Kingdoms\\Season 01\\The Twelve Kingdoms - S01E12 - Shadow of the Moon, Sea of the Shadow - Chapter Twelve.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/helpers/__init__.py#L320">medusa\helpers\__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [WinError 5] Access is denied: 'Z:\\Torrents\\New folder\\The Twelve Kingdoms S01 Hi10p.BluRay.FLAC2.0.x264-CTR\\The.Twelve.Kingdoms.S01E12.1080p-Hi10p.BluRay.FLAC2.0.x264-CTR.[0CE37B56].mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/1405fbb6eb8ef4d20fcca24c32ddca52b11f0f38/medusa/helpers/__init__.py#L293">medusa\helpers\__init__.py</a>", line 293, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'Z:\\Anime\\The Twelve Kingdoms\\Season 01\\The Twelve Kingdoms - S01E12 - Shadow of the Moon, Sea of the Shadow - Chapter Twelve.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
