### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#10366]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-17-amd64-x86_64-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [feature/add-imdb-indexer](../tree/feature/add-imdb-indexer)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6d3c8be811879a3dfb4c815273802114ad90cb98
**Link to Log**: https://gist.github.com/61d12895d14c5369d523c51ad89776b3
### ERROR
<pre>
2022-02-21 18:41:56 ERROR    SHOWQUEUE-REFRESH :: [6d3c8be] 9288030: Error while refreshing show Reacher. Error: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/**********/Medusa/medusa/queues/show_queue.py", line 757, in run
    self.show.refresh_dir()
  File "/**********/Medusa/medusa/tv/series.py", line 2091, in refresh_dir
    self.load_episodes_from_dir()
  File "/**********/Medusa/medusa/tv/series.py", line 1115, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/**********/Medusa/medusa/tv/series.py", line 1488, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/**********/Medusa/medusa/tv/episode.py", line 1157, in create_meta_files
    self.__create_nfo(metadata_provider)
  File "/**********/Medusa/medusa/tv/episode.py", line 1170, in __create_nfo
    result = metadata_provider.create_episode_metadata(self) or result
  File "/**********/Medusa/medusa/metadata/generic.py", line 286, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/**********/Medusa/medusa/metadata/generic.py", line 495, in write_ep_file
    data = self._ep_data(ep_obj)
  File "/**********/Medusa/medusa/metadata/kodi_12plus.py", line 380, in _ep_data
    if 'image' in actor and actor['image'].strip():
AttributeError: 'NoneType' object has no attribute 'strip'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
This one is fixed right?
