### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#10374]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-17-amd64-x86_64-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [feature/add-imdb-indexer](../tree/feature/add-imdb-indexer)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@41a688b431394206d56dc4aefaeab11d7a0c6001
**Link to Log**: https://gist.github.com/f909e8a5005d61b5ef45a245b4fc4f3a
### ERROR
<pre>
2022-02-25 04:43:04 ERROR    SHOWUPDATER :: [41a688b] Problem running show_updater, Indexer IMDb seems to be having issues while trying to get updates for show Reacher. Cause: AttributeError("'NoneType' object has no attribute 'status_code'")
Traceback (most recent call last):
  File "/**********/Medusa/medusa/schedulers/show_updater.py", line 129, in run
    [show.indexerid], from_time=show.last_update_indexer, weeks=update_max_weeks, cache=self.update_cache
  File "/**********/Medusa/medusa/indexers/imdb/api.py", line 681, in get_last_updated_seasons
    self._get_episodes(series_id, detailed=False)
  File "/**********/Medusa/medusa/indexers/imdb/api.py", line 257, in _get_episodes
    if not self[imdb_id]:
  File "/**********/Medusa/medusa/indexers/base.py", line 439, in __getitem__
    selected_series = self._get_series(key)
  File "/**********/Medusa/medusa/indexers/base.py", line 191, in _get_series
    all_series = self.search(series)
  File "/**********/Medusa/medusa/indexers/imdb/api.py", line 184, in search
    show_by_id = self._get_show_by_id(series)
  File "/**********/Medusa/medusa/indexers/imdb/api.py", line 209, in _get_show_by_id
    results = self.imdb_api.get_title(ImdbIdentifier(imdb_id).imdb_id)
  File "/**********/Medusa/ext/imdbpie/imdbpie.py", line 78, in get_title
    self._redirection_title_check(imdb_id)
  File "/**********/Medusa/ext/imdbpie/imdbpie.py", line 329, in _redirection_title_check
    if self.is_redirection_title(imdb_id):
  File "/**********/Medusa/ext/imdbpie/imdbpie.py", line 338, in is_redirection_title
    if response.status_code == httplib.MOVED_PERMANENTLY:
AttributeError: 'NoneType' object has no attribute 'status_code'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Added exception handling
