### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/Medusa#1043]
### INFO

**Python Version**: `2.7.10 (default, Jun 26 2015, 16:00:40) [GCC 4.8.2]`
**Operating System**: `Linux-4.1.18-unRAID-x86_64-AMD_C-60_APU_with_Radeon-tm-_HD_Graphics-with-slackware-14.1`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@43a7a2dedf632b9c3bde07fcb6a07f0099b5f08b
**Link to Log**: https://gist.github.com/29e55d5e215c56b7736e24050208f586
### ERROR

<pre>
2016-09-06 17:46:05 ERROR    SHOWQUEUE-REFRESH :: [43a7a2d] 311537: Error while refreshing show Taboo Tattoo. Error: 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/Sickrage/sickbeard/show_queue.py", line 578, in run
    self.show.refresh_dir()
  File "/usr/local/Sickrage/sickbeard/tv.py", line 1256, in refresh_dir
    self.load_episodes_from_dir()
  File "/usr/local/Sickrage/sickbeard/tv.py", line 598, in load_episodes_from_dir
    parse_result = NameParser(show=self, try_indexers=True).parse(ep_file_name)
  File "/usr/local/Sickrage/sickbeard/name_parser/parser.py", line 235, in parse
    result = self._parse_string(name)
  File "/usr/local/Sickrage/sickbeard/name_parser/parser.py", line 178, in _parse_string
    name=show.name, absolute=a, season=s, episodes=e)
AttributeError: 'NoneType' object has no attribute 'name'
</pre>

---

_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by NicoLeOca** [comment]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@f4308755c9b222bf1a0b36a20b1a7af011a97c7f
**Link to Log**: https://gist.github.com/ef9c9b446949190261ad04090dddf820
### ERROR
<pre>
2016-11-04 03:00:07 ERROR    SHOWUPDATER :: [f430875] Exception generated: 'NoneType' object has no attribute 'paused'
Traceback (most recent call last):
  File "C:\Medusa\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "C:\Medusa\medusa\show_updater.py", line 100, in run
    if not show.paused:
AttributeError: 'NoneType' object has no attribute 'paused'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Looks like it's occurring for the show narcos. @medariox can you check the same?

**Comment by medariox** [comment]
@p0psicles 
Doesn't seem to be the case here. Did a full update and refresh, it doesn't occur with that show.

**Comment by ripper1967** [comment]
I found that  i could  do a manual mass update and refresh without the error, it only seems to produce the error  when the hour i  picked to have it auto update starts

**Comment by ripper1967** [comment]
current dev  this is fixed for me on windows, no more error.

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jul 18 2016, 15:04:44) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@8cd3a58e6d31ade03b213d4bb4f4a88ef0ab3fe1
**Link to Log**: https://gist.github.com/323a727b01355edca36e2985fcffcd6d
### ERROR
<pre>
2016-11-30 11:35:34 ERROR    SEARCHQUEUE-MANUAL-3109 :: [TorrentDay] :: [8cd3a58] Unknown exception while searching TorrentDay. Error: "'NoneType' object has no attribute 'content'"
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/8cd3a58e6d31ade03b213d4bb4f4a88ef0ab3fe1/**********/search/core.py#L557">**********/search/core.py</a>", line 557, in searchProviders
    down_cur_quality, manual_search, manual_search_type)
  File "/home/home/SickRage/<a href="../blob/8cd3a58e6d31ade03b213d4bb4f4a88ef0ab3fe1/**********/providers/generic_provider.py#L193">**********/providers/generic_provider.py</a>", line 193, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/<a href="../blob/8cd3a58e6d31ade03b213d4bb4f4a88ef0ab3fe1/**********/providers/torrent/json/torrentday.py#L78">**********/providers/torrent/json/torrentday.py</a>", line 78, in search
    if not self.login():
  File "/home/home/SickRage/<a href="../blob/8cd3a58e6d31ade03b213d4bb4f4a88ef0ab3fe1/**********/providers/torrent/json/torrentday.py#L200">**********/providers/torrent/json/torrentday.py</a>", line 200, in login
    if not (response.content and response.status_code == 200):
AttributeError: 'NoneType' object has no attribute 'content'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Aah this is buggin me. I'm going to create a PR, where I change getURL to not return None, when requests type is response. THen we see how we go from there. What you guys think?

**Comment by fernandog** [comment]
@p0psicles super's error is because 

1) TD is not checking "if response" as all others providers
2) the response object wasn't created because it couldn't reach TD site

**Comment by fernandog** [comment]
```
~/Medusa/medusa/providers (optimized)$ grep -Ril "if not response" | wc -l
45
```

**Comment by p0psicles** [comment]
No the response object was not created because getURL returned None, as opposed that it should return the response object. This should resolve that: #1707.

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@dd57c33e77ff6f7b3fac5db4b888336ddb3c3407
**Link to Log**: https://gist.github.com/01e66489894f157eec8e2d99d1c6ef5f
### ERROR
<pre>
2016-12-01 20:33:28 ERROR    SHOWQUEUE-REFRESH :: [dd57c33] 8358: Error while refreshing show Pryde of the X-Men. Error: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/show_queue.py#L589">medusa/show_queue.py</a>", line 589, in run
    self.show.write_metadata()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L655">medusa/tv.py</a>", line 655, in write_metadata
    self.__write_show_nfo()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L638">medusa/tv.py</a>", line 638, in __write_show_nfo
    result = cur_provider.create_show_metadata(self) or result
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/generic.py#L247">medusa/metadata/generic.py</a>", line 247, in create_show_metadata
    return self.write_show_file(show_obj)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/generic.py#L392">medusa/metadata/generic.py</a>", line 392, in write_show_file
    data = self._show_data(show_obj)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/kodi_12plus.py#L128">medusa/metadata/kodi_12plus.py</a>", line 128, in _show_data
    my_show = t[int(show_id)]
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/indexer_base.py#L254">medusa/indexers/indexer_base.py</a>", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/tvmaze/tvmaze_api.py#L410">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 410, in _get_show_data
    self._parse_actors(tvmaze_id)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/tvmaze/tvmaze_api.py#L353">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 353, in _parse_actors
    save_actor['image'] = cur_actor.image.get('original')
AttributeError: 'NoneType' object has no attribute 'get'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@dd57c33e77ff6f7b3fac5db4b888336ddb3c3407
**Link to Log**: https://gist.github.com/60fad117267f3c3d9b709a1dc1ce39c9
### ERROR
<pre>
2016-12-01 17:53:09 ERROR    SHOWQUEUE-REFRESH :: [dd57c33] 3798: Error while refreshing show Maximum Choppage. Error: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/show_queue.py#L588">medusa/show_queue.py</a>", line 588, in run
    self.show.refresh_dir()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L1481">medusa/tv.py</a>", line 1481, in refresh_dir
    self.load_episodes_from_dir()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L727">medusa/tv.py</a>", line 727, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L1142">medusa/tv.py</a>", line 1142, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L2605">medusa/tv.py</a>", line 2605, in create_meta_files
    self.__create_nfo()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L2617">medusa/tv.py</a>", line 2617, in __create_nfo
    result = cur_provider.create_episode_metadata(self) or result
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/generic.py#L254">medusa/metadata/generic.py</a>", line 254, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/generic.py#L435">medusa/metadata/generic.py</a>", line 435, in write_ep_file
    data = self._ep_data(ep_obj)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/kodi_12plus.py#L267">medusa/metadata/kodi_12plus.py</a>", line 267, in _ep_data
    my_show = t[ep_obj.show.indexerid]
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/indexer_base.py#L254">medusa/indexers/indexer_base.py</a>", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/tvmaze/tvmaze_api.py#L410">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 410, in _get_show_data
    self._parse_actors(tvmaze_id)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/tvmaze/tvmaze_api.py#L353">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 353, in _parse_actors
    save_actor['image'] = cur_actor.image.get('original')
AttributeError: 'NoneType' object has no attribute 'get'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@dd57c33e77ff6f7b3fac5db4b888336ddb3c3407
**Link to Log**: https://gist.github.com/b65f10e7c09735c10dff74e8bce548dd
### ERROR
<pre>
2016-12-01 17:19:30 ERROR    SHOWQUEUE-REFRESH :: [dd57c33] 10382: Error while refreshing show Feis Chiuil Thiriodh/Tiree Music Festival. Error: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/show_queue.py#L589">medusa/show_queue.py</a>", line 589, in run
    self.show.write_metadata()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L655">medusa/tv.py</a>", line 655, in write_metadata
    self.__write_show_nfo()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L638">medusa/tv.py</a>", line 638, in __write_show_nfo
    result = cur_provider.create_show_metadata(self) or result
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/generic.py#L247">medusa/metadata/generic.py</a>", line 247, in create_show_metadata
    return self.write_show_file(show_obj)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/generic.py#L392">medusa/metadata/generic.py</a>", line 392, in write_show_file
    data = self._show_data(show_obj)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/kodi_12plus.py#L128">medusa/metadata/kodi_12plus.py</a>", line 128, in _show_data
    my_show = t[int(show_id)]
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/indexer_base.py#L254">medusa/indexers/indexer_base.py</a>", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/tvmaze/tvmaze_api.py#L410">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 410, in _get_show_data
    self._parse_actors(tvmaze_id)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/indexers/tvmaze/tvmaze_api.py#L353">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 353, in _parse_actors
    save_actor['image'] = cur_actor.image.get('original')
AttributeError: 'NoneType' object has no attribute 'get'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Should be fixed.

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [binsearch_search](../tree/binsearch_search)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b99a467f0768139ffcf091b3207cfec607951a51
**Link to Log**: https://gist.github.com/4f72a31e8176fdb13c02383184babcbf
### ERROR
<pre>
2017-04-26 00:55:19 ERROR    SEARCHQUEUE-MANUAL-70128 :: [BinSearch] :: [b99a467] Unknown exception while searching BinSearch. Error: "'NoneType' object has no attribute 'group'"
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/search/core.py#L547">medusa/search/core.py</a>", line 547, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/providers/generic_provider.py#L211">medusa/providers/generic_provider.py</a>", line 211, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/providers/nzb/binsearch.py#L91">medusa/providers/nzb/binsearch.py</a>", line 91, in search
    results += self.parse(response.text, mode)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/providers/nzb/binsearch.py#L131">medusa/providers/nzb/binsearch.py</a>", line 131, in parse
    title = title_regex.search(title_field.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd
**Link to Log**: https://gist.github.com/d6106c91770ac3f94e507052960de061
### ERROR
<pre>
2017-09-06 02:06:16 ERROR    SEARCHQUEUE-FORCED-223161 :: [SceneTime] :: [1d0d7ea] Unknown exception while searching SceneTime. Error: "'NoneType' object has no attribute 'text'"
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/search/core.py#L555">medusa/search/core.py</a>", line 555, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/providers/generic_provider.py#L226">medusa/providers/generic_provider.py</a>", line 226, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/providers/torrent/html/scenetime.py#L67">medusa/providers/torrent/html/scenetime.py</a>", line 67, in search
    if not self.login():
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/providers/torrent/html/scenetime.py#L181">medusa/providers/torrent/html/scenetime.py</a>", line 181, in login
    return self.cookie_login('log in')
  File "/home/pi/Medusa/<a href="../blob/1d0d7ea39cddd8b0a40f0dcec26dfa2eeac724fd/medusa/providers/generic_provider.py#L804">medusa/providers/generic_provider.py</a>", line 804, in cookie_login
    not (response.text and response.status_code == 200),
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
### INFO
**Python Version**: `2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]`
**Operating System**: `Linux-4.9.0-4-amd64-x86_64-with-debian-9.2`
**Locale**: `UTF-8`
**Branch**: [feature/fix-saving-nn-cats](../tree/feature/fix-saving-nn-cats)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@e3363605d0119d2f3411746bcc3ad46948aae15f
**Link to Log**: https://gist.github.com/938aa298049cf549392707fa59a24a40
### ERROR
<pre>
2017-11-07 06:00:52 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [e336360] DailySearchQueueItem Exception, error: 'NoneType' object has no attribute 'json'
Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 288, in run
    self.success = snatch_episode(result)
  File "/opt/medusa/medusa/search/core.py", line 134, in snatch_episode
    result_downloaded = sab.send_nzb(result)
  File "/opt/medusa/medusa/clients/nzb/sab.py", line 65, in send_nzb
    data = response.json()
AttributeError: 'NoneType' object has no attribute 'json'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by aerandir83** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-4.2.8-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/9524081afe9448cc2c0be4c6a98941a5
### ERROR
<pre>
2018-02-22 03:15:44 ERROR    SEARCHQUEUE-BACKLOG-260449 :: [ccbc0ce] Checking AniDB scene exceptions update failed for Berserk (2016). Error: 'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "/app/medusa/medusa/scene_exceptions.py", line 411, in _get_anidb_exceptions
    autoCorrectName=True
  File "/app/medusa/lib/adba/aniDBAbstracter.py", line 139, in __init__
    self.name = self._get_name_from_xml(self.aid)
  File "/app/medusa/lib/adba/aniDBAbstracter.py", line 205, in _get_name_from_xml
    for anime in self.allAnimeXML.findall("anime"):
AttributeError: 'NoneType' object has no attribute 'findall'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@55b472b377f5e6c89142eb3c211602ceb1084f3b
**Link to Log**: https://gist.github.com/545cf3afc80ee6e5fdddc3d2f7c7f1f4
### ERROR
<pre>
2018-06-05 19:14:37 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: [55b472b] DailySearchQueueItem Exception, error: 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/55b472b377f5e6c89142eb3c211602ceb1084f3b/medusa/search/queue.py#L263">medusa/search/queue.py</a>", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/home/pi/Medusa/<a href="../blob/55b472b377f5e6c89142eb3c211602ceb1084f3b/medusa/search/core.py#L466">medusa/search/core.py</a>", line 466, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/home/pi/Medusa/<a href="../blob/55b472b377f5e6c89142eb3c211602ceb1084f3b/medusa/tv/cache.py#L202">medusa/tv/cache.py</a>", line 202, in update_cache
    data = self._get_rss_data()
  File "/home/pi/Medusa/<a href="../blob/55b472b377f5e6c89142eb3c211602ceb1084f3b/medusa/tv/cache.py#L185">medusa/tv/cache.py</a>", line 185, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)}
  File "/home/pi/Medusa/<a href="../blob/55b472b377f5e6c89142eb3c211602ceb1084f3b/medusa/providers/torrent/json/btn.py#L99">medusa/providers/torrent/json/btn.py</a>", line 99, in search
    results += self.parse(response.get('torrents', {}), mode)
  File "/home/pi/Medusa/<a href="../blob/55b472b377f5e6c89142eb3c211602ceb1084f3b/medusa/providers/torrent/json/btn.py#L117">medusa/providers/torrent/json/btn.py</a>", line 117, in parse
    title, download_url = self._process_title_and_url(row)
  File "/home/pi/Medusa/<a href="../blob/55b472b377f5e6c89142eb3c211602ceb1084f3b/medusa/providers/torrent/json/btn.py#L186">medusa/providers/torrent/json/btn.py</a>", line 186, in _process_title_and_url
    url = parsed_json.get('DownloadURL').replace('\\/', '/')
AttributeError: 'NoneType' object has no attribute 'replace'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by chest069** [comment]
### INFO
**Python Version**: `2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/889c62fea2623869e0027e21bcf33d03
### ERROR
<pre>
2018-06-29 04:13:30 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 71663: Error while refreshing show The Simpsons. Error: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/show_queue.py#L686">medusa/show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "/opt/medusa/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/tv/series.py#L1713">medusa/tv/series.py</a>", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/opt/medusa/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/tv/series.py#L986">medusa/tv/series.py</a>", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/opt/medusa/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/tv/series.py#L1289">medusa/tv/series.py</a>", line 1289, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "/opt/medusa/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/name_parser/parser.py#L366">medusa/name_parser/parser.py</a>", line 366, in parse
    result = self._parse_string(name)
  File "/opt/medusa/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/name_parser/parser.py#L297">medusa/name_parser/parser.py</a>", line 297, in _parse_string
    new_episode_numbers, new_season_numbers, new_absolute_numbers = self._parse_anime(result)
  File "/opt/medusa/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/name_parser/parser.py#L189">medusa/name_parser/parser.py</a>", line 189, in _parse_anime
    scene_season = scene_exceptions.get_scene_exceptions_by_name(result.series_name)[0][1]
  File "/opt/medusa/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/scene_exceptions.py#L173">medusa/scene_exceptions.py</a>", line 173, in get_scene_exceptions_by_name
    if show_name.lower() in show_names:
AttributeError: 'NoneType' object has no attribute 'lower'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
