### ISSUE TITLE
Bug in failed_processor.py

### ISSUE THREAD

**Issue by frdfsnlght** [pymedusa/Medusa#10473]
**Describe the bug**
Code is trying to join integers when strings are expected.

**To Reproduce**
Try to process a known failed download from Sabnzbd.

**Expected behavior**
I expect the code to work and complete processing a failed download.

**Medusa (please complete the following information):**
 - OS: running Medusa in docker image: linuxserver/medusa
 - Branch: master
 - Version: 0.5.28
 - Python version: 3.9.7

**Debug logs (at least 50 lines):**
<details>

2022-04-03 11:32:29 INFO     Thread_0 :: [] Post processing called with:
path: /media/downloads/complete/tv/Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS
resource: Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS.nzb
2022-04-03 11:32:29 INFO     Thread_0 :: [] Processing path: /media/downloads/complete/tv/Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS
2022-04-03 11:32:29 DEBUG    Thread_0 :: [] Processing resource: Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS.nzb
2022-04-03 11:32:29 INFO     Thread_0 :: [] Post-processing completed.
2022-04-03 11:32:29 INFO     Thread_0 :: [] I did encounter some unprocessable items:
2022-04-03 11:32:29 WARNING  Thread_0 :: [] Missed file: /media/downloads/complete/tv/Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS: Failed download.
2022-04-03 11:32:29 INFO     Thread_0 :: [] Failed download detected: (resource: Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS.nzb, dir: /media/downloads/complete/tv/Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS)
2022-04-03 11:32:29 INFO     Thread_0 :: [] Using nzb_name for release name.
2022-04-03 11:32:29 DEBUG    Thread_0 :: [] Using guessit cache item for Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS
2022-04-03 11:32:29 DEBUG    Thread_0 :: [] No mapping found, returning passed season and episode S04E03 for show Better Call Saul
2022-04-03 11:32:29 DEBUG    Thread_0 :: [] Matched release Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS to a series in your database: Better Call Saul
2022-04-03 11:32:29 DEBUG    Thread_0 :: [] Parsed Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS into title: Better Call Saul, season: 4, episode: [3], screen_size: 1080p, source: Blu-ray, video_codec: H.264, video_encoder: x264, release_group: ROVERS, type: episode, parsing_time: 0.11762619018554688, absolute_episode: [], quality: 1080p BluRay, total_time: 0.14630436897277832
2022-04-03 11:32:29 DEBUG    Thread_0 :: [] Parsed info: title: Better Call Saul, season: 4, episode: [3], screen_size: 1080p, source: Blu-ray, video_codec: H.264, video_encoder: x264, release_group: ROVERS, type: episode, parsing_time: 0.11762619018554688, absolute_episode: [], quality: 1080p BluRay, total_time: 0.14630436897277832
2022-04-03 11:32:29 DEBUG    Thread_0 :: [] Detected as single/multi episode: Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS
2022-04-03 11:32:29 ERROR    Thread_0 :: [] Exception generated: sequence item 0: expected str instance, int found
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/post_process.py", line 101, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "/app/medusa/medusa/process_tv.py", line 237, in run
    process_results.process_failed(path)
  File "/app/medusa/medusa/process_tv.py", line 937, in process_failed
    self.result = processor.process()
  File "/app/medusa/medusa/failed_processor.py", line 86, in process
    segment = self._process_release_name()
  File "/app/medusa/medusa/failed_processor.py", line 66, in _process_release_name
    segment=','.join(ep.episode for ep in segment),
TypeError: sequence item 0: expected str instance, int found

</details>

**Additional context**
I'm trying to get failed downloads working. I download using Sabnzbd and nzbToMedia. The NZB is Better.Call.Saul.S04E03.1080p.BluRay.x264-ROVERS, which consistently fails for me because of missing segments.
When nzbToMedia (nzbToSickBeard) runs, it detects the failed download and passes this to Medusa. Medusa does
it's thing but fails with an exception (see logs).

It seems to me the offending line should be changed to:

```python
    segment=','.join(str(ep.episode) for ep in segment),
```

**Comment by p0psicles** [comment]
Already fixed in the develop branch
