### ISSUE TITLE
Law & Order Organized Crime from TheTVDB can no longer be properly parsed?

### ISSUE THREAD

**Issue by zerojay** [pymedusa/Medusa#10553]
**Describe the bug**
Medusa does its daily check for new episodes, pulls the updated show information from TheTVDB and then fails to properly parse the information given. This leaves the show in an odd state where it looks like the show information says that no episodes exist aside from those that are unaired. All episodes the user has downloaded previously are set to archived and have no episode information anymore. In the Show List, Law & Order Organized Crime now shows up as Unaired.

**To Reproduce**
1. Have Law & Order Organized Crime in your list of shows.
2. Allow Medusa to update the database from TheTVDB.

**Expected behavior**
Medusa should be able to successfully parse the show information from TheTVDB and keep the episode information up-to-date as normal without losing episodes suddenly.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS arm64
 - Branch: master
 - Commit: Latest Docker version - Digest: sha256:07b76eb92a9eaeb4b32c79cff84f57ca59dfab2e6d8fa09efc1f26fef135701b
 - Python version: (unknown, whatever is in the official docker)
 - Database version: (unknown, whatever is in the official docker)

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2022-05-06 19:41:38 INFO	SHOWQUEUE-REFRESH :: Cache check completed
2022-05-06 19:41:38 INFO	SHOWQUEUE-REFRESH :: 383397: Updating NFOs for show with new indexer info
2022-05-06 19:41:38 INFO	SHOWQUEUE-REFRESH :: Trying to clean any empty folder under /tv/Law & Order Organized Crime
2022-05-06 19:41:36 INFO	SHOWQUEUE-REFRESH :: Invalid audio language: 'Law.and.Order.Organized.Crime.S02E10.WEB.x264-TORRENTGALAXY'
2022-05-06 19:41:36 INFO	SHOWQUEUE-REFRESH :: Invalid audio language: 'Law.and.Order.Organized.Crime.S02E18.HDTV.x264-TORRENTGALAXY'
2022-05-06 19:41:35 WARNING	SHOWQUEUE-REFRESH :: An error occurred while parsing: /tv/Law & Order Organized Crime/Season 02/Law & Order Organized Crime - S02E04 - For a Few Lekë More.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                   libmediainfo.so.0                   |
|                         v21.9                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/app/medusa/lib/pymediainfo/__init__.py", line 265, in parse
    raise RuntimeError("An eror occured while opening {0}"
RuntimeError: An eror occured while opening /tv/Law & Order Organized Crime/Season 02/Law & Order Organized Crime - S02E04 - For a Few Lekë More.mkv with libmediainfo
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-05-06 19:41:34 INFO	SHOWQUEUE-REFRESH :: Invalid audio language: 'Law.and.Order.Organized.Crime.S02E13.HDTV.x264-TORRENTGALAXY'
2022-05-06 19:41:34 INFO	SHOWQUEUE-REFRESH :: Invalid audio language: 'Law.and.Order.Organized.Crime.S02E19.HDTV.x264-TORRENTGALAXY'
2022-05-06 19:41:22 INFO	SHOWQUEUE-REFRESH :: 383397: Performing refresh on Law & Order: Organized Crime
2022-05-06 19:41:20 INFO	SHOWQUEUE-UPDATE :: Cache check completed
2022-05-06 19:41:20 INFO	SHOWQUEUE-UPDATE :: Selected poster for series 383397 (score=1.224108385706229, score_bay=1.4482167714124579, rating=2, votes=2, res=680x1000): https://www.thetvdb.com/banners/v4/series/383397/posters/6134ebc5bbacc.jpg
2022-05-06 19:41:20 INFO	SHOWQUEUE-UPDATE :: Selected fanart for series 383397 (score=1.2333333333333334, score_bay=1.4666666666666668, rating=2, votes=2, res=1920x1080): https://www.thetvdb.com/banners/v4/series/383397/backgrounds/6066d5d28bd4a.jpg
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: Copying from /tv/Law & Order Organized Crime/fanart.jpg to /config/cache/images/tvdb/383397.fanart.jpg
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: Copying from /tv/Law & Order Organized Crime/banner.jpg to /config/cache/images/tvdb/383397.banner.jpg
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: Copying from /tv/Law & Order Organized Crime/folder.jpg to /config/cache/images/tvdb/383397.poster.jpg
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: Removed fanart for series Law & Order: Organized Crime
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: Removed poster_thumb for series Law & Order: Organized Crime
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: Removed banner_thumb for series Law & Order: Organized Crime
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: Removed poster for series Law & Order: Organized Crime
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: Removed banner for series Law & Order: Organized Crime
2022-05-06 19:41:19 INFO	SHOWQUEUE-UPDATE :: 383397: Replacing images for show Law & Order: Organized Crime
2022-05-06 19:41:16 INFO	SHOWQUEUE-UPDATE :: Finished processing 1 scene exceptions.
2022-05-06 19:41:16 INFO	SHOWQUEUE-UPDATE :: Updating exception_cache and exception_season_cache
2022-05-06 19:41:16 INFO	FINDSUBTITLES :: No subtitles to download
2022-05-06 19:41:15 INFO	FINDSUBTITLES :: Checking for missed subtitles
2022-05-06 19:39:53 INFO	SHOWQUEUE-REFRESH :: Cache check completed
2022-05-06 19:39:53 INFO	SHOWQUEUE-REFRESH :: 383397: Updating NFOs for show with new indexer info
2022-05-06 19:39:53 INFO	SHOWQUEUE-REFRESH :: Trying to clean any empty folder under /tv/Law & Order Organized Crime
2022-05-06 19:39:46 INFO	SHOWQUEUE-REFRESH :: 383397: Performing refresh on Law & Order: Organized Crime
2022-05-06 19:39:26 INFO	APIv2-Thread-3 :: Broken providers found: ['danishbits', 'btdb', 'hdtorrents']
2022-05-06 19:16:46 INFO	EPISODEUPDATER :: Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2022-05-06 19:10:49 INFO	SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2022-05-06 19:09:49 INFO	SEARCHQUEUE-DAILY-SEARCH :: Using daily search providers
2022-05-06 19:09:48 INFO	SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
```
</details>

I believe that what happened here is that someone updated Season 2, episode 4 in TheTVDB with the ë in it and broke Medusa at some point today. As a workaround, I switched indexers from TheTVDB to Tvmaze for the show and all the episodes appear correct now in Medusa. Tvmaze also has the ë in the episode name, but Medusa does not appear to choke on it.

**Comment by p0psicles** [comment]
i'm guessing there is something going wrong with mediainfo trying to read the specific file.
But when I try to reproduce it with a different video file renamed to `Law & Order Organized Crime - S02E04 - For a Few Lekë More.mkv` it's parsing successful.

Could you try isolating the issue by doing a manual mediainfo scan? I suppose you have mediainfo installed. So you could do a manual `mediainfo [video file]`?

Or else send me the video file. YOu can contact me on discord.
