### ISSUE TITLE
a specific show was not added

### ISSUE THREAD

**Issue by SilentT-FR** [pymedusa/Medusa#10563]
**Describe the bug**
A specific show was not added

**To Reproduce**

1. Go to add show
2. search "Knights of the Zodiac"
3. Clic on  	Knights of the Zodiac 	1986 		IMDb 

**Expected behavior**
The show was added

**Medusa (please complete the following information):**
 - OS: Docker
 - Branch: master 
 - Commit:  Unknown  Version: 0.5.29
 - Python version: 3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]
 - Database version: Database: 44.19

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2022-05-09 22:15:14 INFO     SHOWQUEUE-ADD :: [] Starting to add show by Indexer Id: 161952

Exception in thread SHOWQUEUE-ADD:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner

    self.run()

  File "/app/medusa/medusa/queues/show_queue.py", line 623, in run

    if getattr(api[self.indexer_id], 'seriesname', None) is None:

  File "/app/medusa/medusa/indexers/base.py", line 435, in __getitem__

    self._get_show_data(key, self.config['language'])

  File "/app/medusa/medusa/indexers/imdb/api.py", line 697, in _get_show_data

    series_info = self._get_show_by_id(imdb_id)

  File "/app/medusa/medusa/indexers/imdb/api.py", line 276, in _get_show_by_id

    first_release = sorted(released_in_regions, key=lambda x: x.get('startYear'))

TypeError: '<' not supported between instances of 'int' and 'NoneType'

WARNING:cachecontrol.controller:Cache entry deserialization failed, entry ignored

2022-05-09 22:20:03 INFO     SHOWQUEUE-ADD :: [] Starting to add show by Indexer Id: 161952

Exception in thread SHOWQUEUE-ADD:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner

    self.run()

  File "/app/medusa/medusa/queues/show_queue.py", line 623, in run

    if getattr(api[self.indexer_id], 'seriesname', None) is None:

  File "/app/medusa/medusa/indexers/base.py", line 435, in __getitem__

    self._get_show_data(key, self.config['language'])

  File "/app/medusa/medusa/indexers/imdb/api.py", line 697, in _get_show_data

    series_info = self._get_show_by_id(imdb_id)

  File "/app/medusa/medusa/indexers/imdb/api.py", line 276, in _get_show_by_id

    first_release = sorted(released_in_regions, key=lambda x: x.get('startYear'))

TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
</details>

**Comment by p0psicles** [comment]
I. Believe this is already fixed in develop branch
