### ISSUE TITLE
ImportError: cannot import name 'VideoDimensions'

### ISSUE THREAD

**Issue by ebogaard** [pymedusa/Medusa#10686]
**Describe the bug**
In 1.0.0, it seems there is some problem with the included python libraries. When starting up, this fails with the following error:
```
ImportError: cannot import name 'VideoDimensions'
```

**To Reproduce**
1. Upgrade to 1.0.0 & click yes to restart
2. Restarting fails.
3. Check the error

**Expected behavior**
The included libraries should support starting up of Medusa

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Amalinux 8.6
 - Branch: master
 - Commit: not sure - Release version = v1.0.0
 - Python version: 3.6.8
 - Database version: not sure

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
python3[2175554]: Traceback (most recent call last):
python3[2175554]:   File "/home/ebogaard/Medusa/start.py", line 6, in <module>
python3[2175554]:     from medusa.__main__ import main
python3[2175554]:   File "/home/ebogaard/Medusa/medusa/__init__.py", line 24, in <module>
python3[2175554]:     initialize()
python3[2175554]:   File "/home/ebogaard/Medusa/medusa/init/__init__.py", line 37, in initialize
python3[2175554]:     _configure_guessit()
python3[2175554]:   File "/home/ebogaard/Medusa/medusa/init/__init__.py", line 202, in _configure_guessit
python3[2175554]:     from medusa.name_parser.guessit_parser import (
python3[2175554]:   File "/home/ebogaard/Medusa/medusa/name_parser/guessit_parser.py", line 12, in <module>
python3[2175554]:     from medusa.logger.adapters.style import BraceAdapter
python3[2175554]:   File "/home/ebogaard/Medusa/medusa/logger/__init__.py", line 44, in <module>
python3[2175554]:     import knowit
python3[2175554]:   File "/home/ebogaard/Medusa/ext/knowit/__init__.py", line 19, in <module>
python3[2175554]:     from knowit.api import KnowitException, know
python3[2175554]:   File "/home/ebogaard/Medusa/ext/knowit/api.py", line 7, in <module>
python3[2175554]:     from knowit.provider import Provider
python3[2175554]:   File "/home/ebogaard/Medusa/ext/knowit/provider.py", line 8, in <module>
python3[2175554]:     from knowit.properties import Quantity
python3[2175554]:   File "/home/ebogaard/Medusa/ext/knowit/properties/__init__.py", line 18, in <module>
python3[2175554]:     from knowit.properties.video import (
python3[2175554]: ImportError: cannot import name 'VideoDimensions'
```
</details>

**Additional context**

**Comment by medariox** [comment]
Update to the new version.
