### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by Tailslide** [pymedusa/Medusa#10687]
**Describe the bug**
Pymedusa docker container recently started failing to start

**To Reproduce**
1. Start pymedusa?

**Expected behavior**
It should start

**Debug logs (at least 50 lines):**
Docker Log:

```
Starting medusa as root
Traceback (most recent call last):
  File "/app/medusa/ext/pymediainfo/__init__.py", line 16, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (/usr/local/lib/python3.7/importlib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/app/medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/app/medusa/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/app/medusa/medusa/init/__init__.py", line 202, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "/app/medusa/medusa/name_parser/guessit_parser.py", line 12, in <module>
    from medusa.logger.adapters.style import BraceAdapter
  File "/app/medusa/medusa/logger/__init__.py", line 44, in <module>
    import knowit
  File "/app/medusa/ext/knowit/__init__.py", line 19, in <module>
    from knowit.api import KnowitException, know
  File "/app/medusa/ext/knowit/api.py", line 8, in <module>
    from .providers import (
  File "/app/medusa/ext/knowit/providers/__init__.py", line 5, in <module>
    from knowit.providers.mediainfo import MediaInfoProvider
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 9, in <module>
    from pymediainfo import MediaInfo
  File "/app/medusa/ext/pymediainfo/__init__.py", line 18, in <module>
    import importlib_metadata as metadata  # type: ignore
ModuleNotFoundError: No module named 'importlib_metadata'

this error just keeps repeating as it restarts
```
</details>

**Additional context**

Docker Config:
```
version: '3.8'
services:
  pymedusa:

    image: pymedusa/medusa:latest
    container_name: pymedusa
    environment:
      - TZ=Canada/Mountain
    user: 1027:100
    volumes:
      - /volume1/video:/volume1/video
    restart: always
    ports:
      - "8100:8081"
```

Not sure if this is related:
https://gitlab.com/meltano/sdk/-/merge_requests/31/diffs?commit_id=8bd96092f0205aada2a7a6f0ae019579cffe650e

**Comment by Tailslide** [comment]
I noticed pymedusa/medusa:latest was updated the same time the error started about an hour ago.
Changing to pymedusa/medusa:develop does not fix the error
