### ISSUE TITLE
Medusa can't start the service

### ISSUE THREAD

**Issue by WarEagleUS21** [pymedusa/Medusa#10699]
**Describe the bug**
It is showing that it is paused although I do not know why, it was working fine yesterday and I haven't changed anything.

**To Reproduce**
Try to restart the service and it fails although it doesn't give an error.
Try to resume the service, same thing.
Properties are set to automatic and logon as a service.

**Expected behavior**
I expect it to work.
**Screenshots**
![Screenshot 2022-05-31 195556](https://user-images.githubusercontent.com/81588261/171307080-9670bafa-7d79-4c91-83a2-850945532556.png)
![Screenshot 2022-05-31 195632](https://user-images.githubusercontent.com/81588261/171307134-b25fc12a-4d70-4b61-bdd0-97660cde1e89.png)

**Medusa (please complete the following information):**
Can't give this as the service will not start but it should be the same as the issue I opened up about True Lies.

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

Cannot provide logs at this time, sorry.
</details>

**Additional context**

**Comment by WarEagleUS21** [comment]
Windows 11 Pro OS
Python 3.7.3

Tried running the Sickbeard.py from the Medusa directory and got this error:

PS C:\Medusa\Medusa> C:\Medusa\Python\python.exe "C:\Medusa\Medusa\SickBeard.py" --nolaunch --port=8081 --datadir="C:\Medusa\Data"
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\pymediainfo\__init__.py", line 16, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (C:\Medusa\Python\lib\importlib\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\SickBeard.py", line 6, in <module>
    from medusa.__main__ import main
  File "C:\Medusa\Medusa\medusa\__init__.py", line 24, in <module>
    initialize()
  File "C:\Medusa\Medusa\medusa\init\__init__.py", line 37, in initialize
    _configure_guessit()
  File "C:\Medusa\Medusa\medusa\init\__init__.py", line 202, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "C:\Medusa\Medusa\medusa\name_parser\guessit_parser.py", line 12, in <module>
    from medusa.logger.adapters.style import BraceAdapter
  File "C:\Medusa\Medusa\medusa\logger\__init__.py", line 44, in <module>
    import knowit
  File "C:\Medusa\Medusa\ext\knowit\__init__.py", line 19, in <module>
    from knowit.api import KnowitException, know
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 8, in <module>
    from .providers import (
  File "C:\Medusa\Medusa\ext\knowit\providers\__init__.py", line 5, in <module>
    from knowit.providers.mediainfo import MediaInfoProvider
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 9, in <module>
    from pymediainfo import MediaInfo
  File "C:\Medusa\Medusa\ext\pymediainfo\__init__.py", line 18, in <module>
    import importlib_metadata as metadata  # type: ignore
ModuleNotFoundError: No module named 'importlib_metadata'
PS C:\Medusa\Medusa>

**Comment by WarEagleUS21** [comment]
Got it back. Backed up the Data DIR and then uninstalled Medusa.

Downloaded the 0.6 Windows Installer (it seems to be the latest) and installed it along with Python 3.7.3  and Github 2.22.0. 

It is back and working.

Thanks.
