### ISSUE TITLE
[APP SUBMITTED]: UnboundLocalError: local variable 'parse_result' referenced before assignment

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#10706]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-19-amd64-x86_64-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@15a3936c90fcd24f33e7b86899043dc40cfc93e6
**Link to Log**: https://gist.github.com/5351f176a80ce40cfc6e98c81d4867f2
### ERROR
<pre>
2022-06-02 14:09:09 ERROR    TORNADO :: [15a3936] Uncaught exception in APIv2: UnboundLocalError("local variable 'parse_result' referenced before assignment")
Request: GET /api/v2/guessit?release=Most%2BExpensivest%2BS02E14%2B720p%2BHDTV%2Bx264-YesTV%2B[eztv] 
Traceback (most recent call last):
  File "/**********/Medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/**********/Medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/**********/Medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/**********/Medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/**********/Medusa/medusa/server/api/v2/guessit.py", line 56, in get
    if parse_result:
UnboundLocalError: local variable 'parse_result' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rosavanwinkle** [comment]
### INFO
**Python Version**: `3.9.13 (main, Jul 26 2022, 13:12:30) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.15.18-seedhost-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@1c62acdc4e034951f00db31847bd00479e1db47c
**Link to Log**: https://gist.github.com/ffea5c8a51617179284d422a21c13f3f
### ERROR
<pre>
2022-08-19 05:26:28 ERROR    DOWNLOADHANDLER :: [1c62acd] Exception while checking torrent status. with error: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/connection.py#L158">ext/urllib3/connection.py</a>", line 158, in _new_conn
    conn = connection.create_connection(
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/util/connection.py#L57">ext/urllib3/util/connection.py</a>", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/connectionpool.py#L343">ext/urllib3/connectionpool.py</a>", line 343, in _make_request
    self._validate_conn(conn)
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/connectionpool.py#L839">ext/urllib3/connectionpool.py</a>", line 839, in _validate_conn
    conn.connect()
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/connection.py#L301">ext/urllib3/connection.py</a>", line 301, in connect
    conn = self._new_conn()
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/connection.py#L167">ext/urllib3/connection.py</a>", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fbaf6d44f40>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/requests/adapters.py#L439">ext/requests/adapters.py</a>", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/urllib3/util/retry.py#L398">ext/urllib3/util/retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='server511.seedhost.eu', port=443): Max retries exceeded with url: /**********/rutorrent/plugins/httprpc/action.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbaf6d44f40>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/lib/rtorrent/lib/xmlrpc/requests_transport.py#L119">lib/rtorrent/lib/xmlrpc/requests_transport.py</a>", line 119, in request
    response = requests.post(
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/requests/api.py#L119">ext/requests/api.py</a>", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/requests/api.py#L61">ext/requests/api.py</a>", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/requests/sessions.py#L542">ext/requests/sessions.py</a>", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/requests/sessions.py#L655">ext/requests/sessions.py</a>", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/ext/requests/adapters.py#L516">ext/requests/adapters.py</a>", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='server511.seedhost.eu', port=443): Max retries exceeded with url: /**********/rutorrent/plugins/httprpc/action.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbaf6d44f40>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/medusa/schedulers/download_handler.py#L408">medusa/schedulers/download_handler.py</a>", line 408, in run
    self._clean(torrent_client)
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/medusa/schedulers/download_handler.py#L375">medusa/schedulers/download_handler.py</a>", line 375, in _clean
    if not client.get_status(history_result['info_hash']):
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/medusa/clients/torrent/rtorrent.py#L218">medusa/clients/torrent/rtorrent.py</a>", line 218, in get_status
    torrent = self._torrent_properties(info_hash)
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/medusa/clients/torrent/rtorrent.py#L175">medusa/clients/torrent/rtorrent.py</a>", line 175, in _torrent_properties
    torrent = self.auth.find_torrent(info_hash.upper())
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/lib/rtorrent/__init__.py#L424">lib/rtorrent/__init__.py</a>", line 424, in find_torrent
    return(common.find_torrent(info_hash, self.get_torrents()))
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/lib/rtorrent/__init__.py#L184">lib/rtorrent/__init__.py</a>", line 184, in get_torrents
    results = m.call()[0]  # only sent one call, only need first result
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/lib/rtorrent/rpc/__init__.py#L172">lib/rtorrent/rpc/__init__.py</a>", line 172, in call
    results = m()
  File "/usr/lib/python3.9/xmlrpc/client.py", line 892, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python3.9/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/app/medusa/<a href="../blob/1c62acdc4e034951f00db31847bd00479e1db47c/lib/rtorrent/lib/xmlrpc/requests_transport.py#L147">lib/rtorrent/lib/xmlrpc/requests_transport.py</a>", line 147, in request
    response.status_code,
UnboundLocalError: local variable 'response' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
