### ISSUE TITLE
Medusa service starts, web port not listed

### ISSUE THREAD

**Issue by zmonge** [pymedusa/Medusa#10713]
**Describe the bug**
Medusa service starts with no errors at all, web port not listed

**To Reproduce**
1. Update to last commit: 1c62acdc4e034951f00db331847bd00479e1db47c
2. Restart medusa
3. Reload web page
4. Unable to connect

"Firefox can’t establish a connection to the server at localhost:8081.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web."

**Expected behavior**
A fully functional medusa instance, including web port

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [Raspbian 10 Buster 5.10.103-v7+ 10.12 armv7l]
 - Branch: [master]
 - Commit: [1c62a]
 - Python version: [3.7.3]
 - Database version: [ND]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2022-05-31 08:00:15 INFO     SEARCHQUEUE-DAILY-SEARCH :: [e4870f8] Beginning daily search for new episodes
2022-05-31 08:00:15 INFO     SEARCHQUEUE-DAILY-SEARCH :: [e4870f8] Using daily search providers
2022-05-31 08:00:26 INFO     SEARCHQUEUE-DAILY-SEARCH :: [e4870f8] No needed episodes found
2022-05-31 08:18:21 INFO     FINDSUBTITLES :: [e4870f8] Checking for missed subtitles
2022-05-31 08:18:21 INFO     FINDSUBTITLES :: [e4870f8] No subtitles to download
2022-05-31 08:38:59 INFO     CHECKVERSION :: [e4870f8] New update found, starting auto-updater ...
2022-05-31 08:39:02 INFO     CHECKVERSION :: [e4870f8] Config backup in progress...
2022-05-31 08:40:00 INFO     CHECKVERSION :: [e4870f8] Config backup successful
2022-05-31 08:40:08 INFO     CHECKVERSION :: [1c62acd] Telegram message sent successfully.
2022-05-31 08:40:08 INFO     CHECKVERSION :: [1c62acd] Update was successful!
2022-05-31 08:40:08 INFO     EVENT-QUEUE :: [1c62acd] Aborting all threads
2022-05-31 08:40:08 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the DAILYSEARCHER thread to exit
2022-05-31 08:40:08 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the BACKLOG thread to exit
2022-05-31 08:40:08 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the SHOWUPDATER thread to exit
2022-05-31 08:40:08 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the EPISODEUPDATER thread to exit
2022-05-31 08:40:08 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the CHECKVERSION thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the SHOWQUEUE-REFRESH thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the FORCEDSEARCHQUEUE thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the SNATCHQUEUE-SNATCH-311954 thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the TRAKTCHECKER thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the FINDPROPERS thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the FINDSUBTITLES thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the DOWNLOADHANDLER thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the POSTPROCESSOR thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the POSTPROCESSORQUEUE thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Waiting for the EVENT-QUEUE thread to exit
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Saving all shows to the database
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Saving config file to disk
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Broken providers found: ['danishbits', 'btdb', 'hdtorrents']
2022-05-31 08:40:09 INFO     EVENT-QUEUE :: [1c62acd] Shutting down Tornado
2022-05-31 08:40:14 INFO     EVENT-QUEUE :: [1c62acd] Restarting Medusa with ['/usr/bin/python3', '/opt/medusa/start.py', '-q', '--nolaunch', '--datadir=/opt/medusa']

Not able to get debug logs, even with debug=1 in config.ini, last entry in application.log above, after multiple service restarts, application. log is not being updated.
```
</details>

**Additional context**
pi@phobos:/opt/medusa $ sudo service medusa status
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2022-06-04 13:07:38 CST; 2s ago
 Main PID: 18451 (python3)
    Tasks: 1 (limit: 1597)
   CGroup: /system.slice/medusa.service
           └─18451 /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa

Jun 04 13:07:38 phobos systemd[1]: Started Medusa Daemon.

pi@phobos:/opt/medusa $ nmap localhost
Starting Nmap 7.70 ( https://nmap.org ) at 2022-06-04 13:08 CST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00062s latency).
Not shown: 996 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
53/tcp   open  domain
80/tcp   open  http
9090/tcp open  zeus-admin

pi@phobos:/opt/medusa $ netstat -tunlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:9070            0.0.0.0:*               LISTEN      1126/python3        
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:5335          0.0.0.0:*               LISTEN      -                   
tcp6       0      0 ::1:4711                :::*                    LISTEN      -                   
tcp6       0      0 :::80                   :::*                    LISTEN      -                   
tcp6       0      0 :::53                   :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::9090                 :::*                    LISTEN      -                   
udp        0      0 0.0.0.0:53              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:53895           0.0.0.0:*                           -                   
udp        0      0 127.0.0.1:5335          0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -                   
udp6       0      0 :::53                   :::*                                -                   
udp6       0      0 :::46204                :::*                                -                   
udp6       0      0 :::5353                 :::*                                -

Manual start fails with:

pi@phobos:/opt/medusa/Logs $ /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
Traceback (most recent call last):
  File "/opt/medusa/ext/pymediainfo/__init__.py", line 16, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata' from 'importlib' (/usr/lib/python3.7/importlib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/opt/medusa/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/opt/medusa/medusa/init/__init__.py", line 202, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "/opt/medusa/medusa/name_parser/guessit_parser.py", line 12, in <module>
    from medusa.logger.adapters.style import BraceAdapter
  File "/opt/medusa/medusa/logger/__init__.py", line 44, in <module>
    import knowit
  File "/opt/medusa/ext/knowit/__init__.py", line 19, in <module>
    from knowit.api import KnowitException, know
  File "/opt/medusa/ext/knowit/api.py", line 8, in <module>
    from .providers import (
  File "/opt/medusa/ext/knowit/providers/__init__.py", line 5, in <module>
    from knowit.providers.mediainfo import MediaInfoProvider
  File "/opt/medusa/ext/knowit/providers/mediainfo.py", line 9, in <module>
    from pymediainfo import MediaInfo
  File "/opt/medusa/ext/pymediainfo/__init__.py", line 18, in <module>
    import importlib_metadata as metadata  # type: ignore
ModuleNotFoundError: No module named 'importlib_metadata'

**Comment by zmonge** [comment]
Probably completely unrelated:

Fresh medusa install on raspberry pi 3b+, Bullseye, Python 3.9.2, 5.15.32-v8+, aarch64.
Fails to start web port.

**Comment by medariox** [comment]
Update to the newest release https://github.com/pymedusa/Medusa/releases/tag/v1.0.2
Commit ad2c7adcde31a423ecd3195c1c76f39f67800451

**Comment by zmonge** [comment]
> Update to the newest release https://github.com/pymedusa/Medusa/releases/tag/v1.0.2 Commit [ad2c7ad](https://github.com/pymedusa/Medusa/commit/ad2c7adcde31a423ecd3195c1c76f39f67800451)

This solved it.

Thank you.
