### ISSUE TITLE
KnowIt log 

### ISSUE THREAD

**Issue by crxed9** [pymedusa/Medusa#10731]
**Describe the bug**
My log is getting much longer since the last update because of the KnowIt "visuals" in it.
Does this have a purpose?

<html>
<body>

Medusa Info: | Branch: master
Commit: ad2c7adcde31a423ecd3195c1c76f39f67800451
Version: 1.0.2Database: 44.19
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.19041-SP0
Locale: | nl_NL.cp1252
Timezone: | West-Europa (zomertijd)

</body>
</html>
**Debug logs (at least 50 lines):**

<details>

```
<-- 2022-06-07 04:00:55 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: J:\Downloads\Grabit\Series\TopGear\Season 31\Top Gear - S31E02 - Episode 2.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Program Files (x86)\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Program Files (x86)\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Program Files (x86)\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Program Files (x86)\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Program Files (x86)\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-07 04:00:55 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: J:\Downloads\Grabit\Series\TopGear\Season 31\Top Gear - S31E03 - Episode 3.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Program Files (x86)\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Program Files (x86)\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Program Files (x86)\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Program Files (x86)\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Program Files (x86)\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-07 04:00:32 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: J:\Downloads\Grabit\Series\The Boys\Season 01\The Boys - 1x01 - The Name of the Game.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+ -->
```
</details>

**Comment by p0psicles** [comment]
Could you try the develop branch. Or wait for next release. It should be improved

**Comment by medariox** [comment]
Should be fixed with 1.0.3

**Comment by MatthK** [comment]
I keep getting the same (or similar) warning messages, but I am on 1.0.6. I have posted that as well some time ago in the KnowIt issues, but there was no reaction to this.

```
2022-08-24 23:06:02 INFO	SHOWQUEUE-REFRESH :: [400903a] Cache check completed
2022-08-24 23:06:02 INFO	SHOWQUEUE-REFRESH :: [400903a] 73518: Updating NFOs for show with new indexer info
2022-08-24 23:06:02 INFO	SHOWQUEUE-REFRESH :: [400903a] Trying to clean any empty folder under /mnt/shares/movies/TV Shows - Kids/Maya the Bee
2022-08-24 23:06:01 WARNING	SHOWQUEUE-REFRESH :: [400903a] An error occurred while parsing: /mnt/shares/movies/TV Shows - Kids/Maya the Bee/Season 01/Die Biene Maja - S01E23 - Wie die Grille befreit wurde.mp4
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
|                   libmediainfo.so.0                   |
|                        v17.12                         |
|                                                       |
|                        ffprobe                        |
|                  v3.4.11-0ubuntu0.1                   |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/opt/medusa/ext/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "/opt/medusa/ext/knowit/providers/mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "/opt/medusa/ext/knowit/providers/mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "/opt/medusa/ext/knowit/providers/mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
```

**Comment by medariox** [comment]
Do you have an external Mediainfo version installed? Try to remove it to use the one that ships with Medusa.
