### ISSUE TITLE
[APP SUBMITTED]: TypeError: __new__() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#10762]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-19-amd64-x86_64-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@27eacf550619bd7873c2c6cfa03b6fa84efe0f2f
**Link to Log**: https://gist.github.com/0d7f104cb7e617936a9cab0b7b9ef30d
### ERROR
<pre>
2022-06-15 02:13:04 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [27eacf5] Could not connect to Trakt service: __new__() got an unexpected keyword argument 'type'
Traceback (most recent call last):
  File "/**********/Medusa/medusa/show/recommendations/trakt.py", line 141, in fetch_popular_shows
    not_liked_show = trakt_user.get_list(app.TRAKT_BLACKLIST_NAME) or []
  File "/**********/Medusa/ext/trakt/users.py", line 456, in get_list
    return UserList.get(title, self.username)
  File "/**********/Medusa/ext/trakt/core.py", line 549, in inner
    return generator.send(json_data)
  File "/**********/Medusa/ext/trakt/users.py", line 111, in _get
    ulist = UserList(creator=creator, **data)
TypeError: __new__() got an unexpected keyword argument 'type'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by twolaw** [comment]
The fix is :
- https://github.com/moogar0880/PyTrakt/pull/206

**Comment by duramato** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-19-amd64-x86_64-with-debian-10.11`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@bcc04b769c790e3b17cb9f7148a54da779629361
**Link to Log**: https://gist.github.com/bafb124f09af9224344153fdd2d27c91
### ERROR
<pre>
2022-06-24 02:16:04 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [bcc04b7] Could not connect to Trakt service: __new__() got an unexpected keyword argument 'type'
Traceback (most recent call last):
  File "/**********/Medusa/medusa/show/recommendations/trakt.py", line 141, in fetch_popular_shows
    not_liked_show = trakt_user.get_list(app.TRAKT_BLACKLIST_NAME) or []
  File "/**********/Medusa/ext/trakt/users.py", line 456, in get_list
    return UserList.get(title, self.username)
  File "/**********/Medusa/ext/trakt/core.py", line 549, in inner
    return generator.send(json_data)
  File "/**********/Medusa/ext/trakt/users.py", line 111, in _get
    ulist = UserList(creator=creator, **data)
TypeError: __new__() got an unexpected keyword argument 'type'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
I'll include the updated package, as soon as it's released

**Comment by twolaw** [comment]
The maintainer of the package is not responding :
- https://github.com/moogar0880/PyTrakt/issues/199

I suggest to switch to this active fork :
- https://github.com/glensc/python-trakt/
- https://pypi.org/project/pytrakt/

**Comment by twolaw** [comment]
fixed with #11173 in version [1.0.13](https://github.com/pymedusa/Medusa/releases/tag/v1.0.13)
