### ISSUE TITLE
[APP SUBMITTED]: TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'

### ISSUE THREAD

**Issue by andreadistefano** [pymedusa/Medusa#10801]
### INFO
**Python Version**: `3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]`
**Operating System**: `Linux-5.4.0-122-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@848c29580c303499d7255adc08a04714aefc9eb6
**Link to Log**: https://gist.github.com/2231eb9dd2caa0bbe6770473a984e9e4
### ERROR
<pre>
2022-07-05 18:05:13 ERROR    SNATCHQUEUE-SNATCH-296762 :: [848c295] Snatch failed! For result: Westworld.S04E02.1080p.WEB.H264-CAKES[rartv]
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/medusa/search/queue.py#L516">medusa/search/queue.py</a>", line 516, in run
    self.success = snatch_result(result)
  File "/opt/medusa/<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/medusa/search/core.py#L169">medusa/search/core.py</a>", line 169, in snatch_result
    result_downloaded = client.send_torrent(result)
  File "/opt/medusa/<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/medusa/clients/torrent/generic.py#L230">medusa/clients/torrent/generic.py</a>", line 230, in send_torrent
    r_code = self._add_torrent_uri(result)
  File "/opt/medusa/<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/medusa/clients/torrent/qbittorrent.py#L160">medusa/clients/torrent/qbittorrent.py</a>", line 160, in _add_torrent_uri
    command = 'api/v2/torrents/add' if self.api >= (2, 0, 0) else 'command/download'
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
It's having issues connecting to your qbittorrent client.

**Comment by Bekkenes** [comment]
### INFO
**Python Version**: `3.9.15 (main, Nov 10 2022, 13:00:13) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/c320ea9c92588c5eb54cb6a413e7569e
### ERROR
<pre>
2022-12-01 15:29:10 ERROR    SNATCHQUEUE-SNATCH-341663 :: [] Snatch failed! For result: Titans.2018.S04E06.1080p.WEB.H264-CAKES[rartv]
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 516, in run
    self.success = snatch_result(result)
  File "/app/medusa/medusa/search/core.py", line 169, in snatch_result
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 230, in send_torrent
    r_code = self._add_torrent_uri(result)
  File "/app/medusa/medusa/clients/torrent/qbittorrent.py", line 160, in _add_torrent_uri
    command = 'api/v2/torrents/add' if self.api >= (2, 0, 0) else 'command/download'
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bekkenes** [comment]
### INFO
**Python Version**: `3.9.15 (main, Nov 10 2022, 13:00:13) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/935b45527f5c7669f8221c72da954a2e
### ERROR
<pre>
2022-12-01 14:06:19 ERROR    SNATCHQUEUE-SNATCH-341663 :: [] Snatch failed! For result: Titans.2018.S04E06.1080p.WEB.H264-CAKES.EZTV
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 516, in run
    self.success = snatch_result(result)
  File "/app/medusa/medusa/search/core.py", line 169, in snatch_result
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 235, in send_torrent
    r_code = self._add_torrent_file(result)
  File "/app/medusa/medusa/clients/torrent/qbittorrent.py", line 178, in _add_torrent_file
    command = 'api/v2/torrents/add' if self.api >= (2, 0, 0) else 'command/upload'
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-02-02 11:10:00 ERROR    SNATCHQUEUE-SNATCH-109377 :: [b9292f9] Snatch failed! For result: George.&.Tammy.S01.2160p.PMTP.WEB-DL.DDP5.1.x265-NTb
Traceback (most recent call last):
  File "C:\GitHub\Medusa\<a href="../blob/b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e/medusa/search/queue.py#L516">medusa\search\queue.py</a>", line 516, in run
    self.success = snatch_result(result)
  File "C:\GitHub\Medusa\<a href="../blob/b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e/medusa/search/core.py#L169">medusa\search\core.py</a>", line 169, in snatch_result
    result_downloaded = client.send_torrent(result)
  File "C:\GitHub\Medusa\<a href="../blob/b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e/medusa/clients/torrent/generic.py#L235">medusa\clients\torrent\generic.py</a>", line 235, in send_torrent
    r_code = self._add_torrent_file(result)
  File "C:\GitHub\Medusa\<a href="../blob/b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e/medusa/clients/torrent/qbittorrent.py#L178">medusa\clients\torrent\qbittorrent.py</a>", line 178, in _add_torrent_file
    command = 'api/v2/torrents/add' if self.api >= (2, 0, 0) else 'command/upload'
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
