### ISSUE TITLE
[APP SUBMITTED]: babelfish.exceptions.LanguageReverseError: 'thumb'

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#10804]
### INFO
**Python Version**: `3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@848c29580c303499d7255adc08a04714aefc9eb6
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-07-06 03:23:37 ERROR    SHOWQUEUE-REFRESH :: [] Cannot parse language code 'thumb'
Traceback (most recent call last):
  File "C:\Medusa_1900\<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/ext/babelfish/converters/__init__.py#L168">ext\babelfish\converters\__init__.py</a>", line 168, in reverse
    return self.from_symbol[code]
  File "C:\Medusa_1900\<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/ext/babelfish/converters/__init__.py#L51">ext\babelfish\converters\__init__.py</a>", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'thumb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa_1900\<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/medusa/subtitles.py#L791">medusa\subtitles.py</a>", line 791, in search_external_subtitles
    language = Language.fromname(language_code)
  File "C:\Medusa_1900\<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/ext/babelfish/language.py#L110">ext\babelfish\language.py</a>", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "C:\Medusa_1900\<a href="../blob/848c29580c303499d7255adc08a04714aefc9eb6/ext/babelfish/converters/__init__.py#L170">ext\babelfish\converters\__init__.py</a>", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: 'thumb'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
That's a weird language (code)

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-07-07 08:59:50 ERROR    SHOWQUEUE-REFRESH :: [cb13ff9] Cannot parse language code 'thumb'
Traceback (most recent call last):
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L168">ext\babelfish\converters\__init__.py</a>", line 168, in reverse
    return self.from_symbol[code]
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L51">ext\babelfish\converters\__init__.py</a>", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'thumb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/medusa/subtitles.py#L791">medusa\subtitles.py</a>", line 791, in search_external_subtitles
    language = Language.fromname(language_code)
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/language.py#L110">ext\babelfish\language.py</a>", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L170">ext\babelfish\converters\__init__.py</a>", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: 'thumb'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by xbette** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-12-amd64-x86_64-with-debian-10.6`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@00f4d2b84bef2079ada24a8a841b8c8490da0c98
**Link to Log**: https://gist.github.com/768a60490fd6b414a11603042b5c4770
### ERROR
<pre>
2022-07-13 04:51:43 ERROR    SHOWQUEUE-REFRESH :: [00f4d2b] Cannot parse language code '(2)'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/00f4d2b84bef2079ada24a8a841b8c8490da0c98/ext/babelfish/converters/__init__.py#L168">ext/babelfish/converters/__init__.py</a>", line 168, in reverse
    return self.from_symbol[code]
  File "/opt/medusa/<a href="../blob/00f4d2b84bef2079ada24a8a841b8c8490da0c98/ext/babelfish/converters/__init__.py#L51">ext/babelfish/converters/__init__.py</a>", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: '(2)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/00f4d2b84bef2079ada24a8a841b8c8490da0c98/medusa/subtitles.py#L791">medusa/subtitles.py</a>", line 791, in search_external_subtitles
    language = Language.fromname(language_code)
  File "/opt/medusa/<a href="../blob/00f4d2b84bef2079ada24a8a841b8c8490da0c98/ext/babelfish/language.py#L110">ext/babelfish/language.py</a>", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/opt/medusa/<a href="../blob/00f4d2b84bef2079ada24a8a841b8c8490da0c98/ext/babelfish/converters/__init__.py#L170">ext/babelfish/converters/__init__.py</a>", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: '(2)'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-07-14 03:20:27 ERROR    SHOWQUEUE-REFRESH :: [cb13ff9] Cannot parse language code 'thumb'
Traceback (most recent call last):
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L168">ext\babelfish\converters\__init__.py</a>", line 168, in reverse
    return self.from_symbol[code]
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L51">ext\babelfish\converters\__init__.py</a>", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'thumb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/medusa/subtitles.py#L791">medusa\subtitles.py</a>", line 791, in search_external_subtitles
    language = Language.fromname(language_code)
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/language.py#L110">ext\babelfish\language.py</a>", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L170">ext\babelfish\converters\__init__.py</a>", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: 'thumb'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nydave69** [comment]
### INFO
**Python Version**: `3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-07-14 02:16:42 ERROR    SHOWQUEUE-REFRESH :: [cb13ff9] Cannot parse language code 'eng.sdh'
Traceback (most recent call last):
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L168">ext\babelfish\converters\__init__.py</a>", line 168, in reverse
    return self.from_symbol[code]
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L51">ext\babelfish\converters\__init__.py</a>", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'eng.sdh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/medusa/subtitles.py#L791">medusa\subtitles.py</a>", line 791, in search_external_subtitles
    language = Language.fromname(language_code)
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/language.py#L110">ext\babelfish\language.py</a>", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "C:\Medusa_2000\<a href="../blob/cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8c/ext/babelfish/converters/__init__.py#L170">ext\babelfish\converters\__init__.py</a>", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: 'eng.sdh'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by xbette** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-12-amd64-x86_64-with-debian-10.6`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@135a704943350809d166e26c3751c5738472af97
**Link to Log**: https://gist.github.com/0fcd06e95514ce00028e15359e4f20ce
### ERROR
<pre>
2022-07-18 04:36:46 ERROR    SHOWQUEUE-REFRESH :: [135a704] Cannot parse language code '(2)'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/135a704943350809d166e26c3751c5738472af97/ext/babelfish/converters/__init__.py#L168">ext/babelfish/converters/__init__.py</a>", line 168, in reverse
    return self.from_symbol[code]
  File "/opt/medusa/<a href="../blob/135a704943350809d166e26c3751c5738472af97/ext/babelfish/converters/__init__.py#L51">ext/babelfish/converters/__init__.py</a>", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: '(2)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/135a704943350809d166e26c3751c5738472af97/medusa/subtitles.py#L791">medusa/subtitles.py</a>", line 791, in search_external_subtitles
    language = Language.fromname(language_code)
  File "/opt/medusa/<a href="../blob/135a704943350809d166e26c3751c5738472af97/ext/babelfish/language.py#L110">ext/babelfish/language.py</a>", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/opt/medusa/<a href="../blob/135a704943350809d166e26c3751c5738472af97/ext/babelfish/converters/__init__.py#L170">ext/babelfish/converters/__init__.py</a>", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: '(2)'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Maybe someone can answer this question: https://github.com/pymedusa/Medusa/issues/10804#issuecomment-1177524740

**Comment by xbette** [comment]
> Which subtitle providers do you have enabled?

Danish at my end :)

**Comment by medariox** [comment]
> > Which subtitle providers do you have enabled?
> 
> Danish at my end :)

Not the language, which subtitle provider... opensubtitles, addicted, wizdom... ?

**Comment by xbette** [comment]
> > > Which subtitle providers do you have enabled?
> > 
> > 
> > Danish at my end :)
> 
> Not the language, which subtitle provider... opensubtitles, addicted, wizdom... ?

oh sorry.. not using any subtitle provider, i add the subtitles to the folders manualy cause they normaly follow with the files i put in the folders when i update from original downloaded files. 

i mean. Medusa downloads a episode, and when i then see a episode with danish subs, then i remove old file a put the new in. :)

**Comment by shadownetdev1** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.10.28-Unraid-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-07-24 02:31:56 ERROR    SHOWQUEUE-REFRESH :: [] Cannot parse language code '1.en'
Traceback (most recent call last):
  File "/app/medusa/ext/babelfish/converters/__init__.py", line 168, in reverse
    return self.from_symbol[code]
  File "/app/medusa/ext/babelfish/converters/__init__.py", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: '1.en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/subtitles.py", line 791, in search_external_subtitles
    language = Language.fromname(language_code)
  File "/app/medusa/ext/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/app/medusa/ext/babelfish/converters/__init__.py", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: '1.en'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by shadownetdev1** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-5.10.28-Unraid-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-07-24 02:31:54 ERROR    SHOWQUEUE-REFRESH :: [] Cannot parse language code '2.en'
Traceback (most recent call last):
  File "/app/medusa/ext/babelfish/converters/__init__.py", line 168, in reverse
    return self.from_symbol[code]
  File "/app/medusa/ext/babelfish/converters/__init__.py", line 51, in __getitem__
    return self._store[key.lower()][1]
KeyError: '2.en'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/subtitles.py", line 791, in search_external_subtitles
    language = Language.fromname(language_code)
  File "/app/medusa/ext/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/app/medusa/ext/babelfish/converters/__init__.py", line 170, in reverse
    raise LanguageReverseError(code)
babelfish.exceptions.LanguageReverseError: '2.en'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed in develop.
