### ISSUE TITLE
Exception generated: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by jaxjexjox** [pymedusa/Medusa#10823]
**Describe the bug**

**To Reproduce**

Post process data.
Error appears in the error log

```

2022-07-15 18:10:15 ERROR    Thread_0 :: [cb13ff9] Exception generated: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/post_process.py", line 101, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "/app/medusa/medusa/process_tv.py", line 237, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/medusa/process_tv.py", line 391, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/medusa/process_tv.py", line 657, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 880, in process_media
    self.result = processor.process()
  File "/app/medusa/medusa/post_processor.py", line 1056, in process
    file_path=self.file_path, error=result['errors']), logger.WARNING
TypeError: 'bool' object is not subscriptable
```

**Expected behavior**
No such error

**Screenshots**
N/A - exact error above

**Medusa (please complete the following information):**
Ubuntu 22.04 -  docker host.
 Branch: master
Medusa Info: | Branch: masterCommit: cb13ff926326d6c5c35cd5ab5c13c5e0cf8f0a8cVersion: 1.0.5Database: 44.19
Python Version: | 3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]
SSL Version: | OpenSSL 1.1.1n 15 Mar 2022
OS: | Linux-5.15.0-41-generic-x86_64-with
Locale: | en_US.UTF-8
Timezone: | AEST

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

2022-07-15 18:29:31 ERROR	Thread :: [cb13ff9] Exception generated: 'bool' object is not subscriptable
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/post_process.py", line 101, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "/app/medusa/medusa/process_tv.py", line 237, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/medusa/process_tv.py", line 391, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/medusa/process_tv.py", line 657, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 880, in process_media
    self.result = processor.process()
  File "/app/medusa/medusa/post_processor.py", line 1056, in process
    file_path=self.file_path, error=result['errors']), logger.WARNING
TypeError: 'bool' object is not subscriptable
2022-07-15 18:29:31 INFO	Thread :: [cb13ff9] Checking /downloads/Deadwood.S01E03.Reconnoitering the Rim-1080p.Blu-ray.EAC3.AVC-PiR8.mkv for minimal one video and audio stream
2022-07-15 18:29:31 INFO	Thread :: [cb13ff9] Processing /downloads/Deadwood.S01E03.Reconnoitering the Rim-1080p.Blu-ray.EAC3.AVC-PiR8.mkv
2022-07-15 18:29:31 DEBUG	Thread :: [cb13ff9] Post-processing video files: ['Deadwood.S01E03.Reconnoitering the Rim-1080p.Blu-ray.EAC3.AVC-PiR8.mkv', 'Deadwood.S01E04.Here Was a Man-1080p.Blu-ray.EAC3.AVC-PiR8.mkv', 'Oz.S01E01.The.Routine.1080p.AMZN.WEB-DL.DDP2.0.H.264-pawel2006.mkv', 'Oz.S01E02.Visits.Conjugal.and.Otherwise.1080p.AMZN.WEB-DL.DDP2.0.H.264-pawel2006.mkv', 'Oz.S01E04.Capital.P.1080p.AMZN.WEB-DL.DDP2.0.H.264-pawel2006.mkv', 'Six.Feet.Under.S01E01.Pilot.WEBRip.1080p.AC3.H265-d3g.mkv', 'Six.Feet.Under.S01E02.The.Will.WEBRip.1080p.AC3.H265-d3g.mkv', 'Six.Feet.Under.S01E03.The.Foot.WEBRip.1080p.AC3.H265-d3g.mkv', 'Six.Feet.Under.S01E04.Familia.WEBRip.1080p.AC3.H265-d3g.mkv']
2022-07-15 18:29:31 DEBUG	Thread :: [cb13ff9] Post-processing files: ['Deadwood.S01E03.Reconnoitering the Rim-1080p.Blu-ray.EAC3.AVC-PiR8.mkv', 'Deadwood.S01E04.Here Was a Man-1080p.Blu-ray.EAC3.AVC-PiR8.mkv', 'Oz.S01E01.The.Routine.1080p.AMZN.WEB-DL.DDP2.0.H.264-pawel2006.mkv', 'Oz.S01E02.Visits.Conjugal.and.Otherwise.1080p.AMZN.WEB-DL.DDP2.0.H.264-pawel2006.mkv', 'Oz.S01E04.Capital.P.1080p.AMZN.WEB-DL.DDP2.0.H.264-pawel2006.mkv', 'Six.Feet.Under.S01E01.Pilot.WEBRip.1080p.AC3.H265-d3g.mkv', 'Six.Feet.Under.S01E02.The.Will.WEBRip.1080p.AC3.H265-d3g.mkv', 'Six.Feet.Under.S01E03.The.Foot.WEBRip.1080p.AC3.H265-d3g.mkv', 'Six.Feet.Under.S01E04.Familia.WEBRip.1080p.AC3.H265-d3g.mkv']
2022-07-15 18:29:31 DEBUG	Thread :: [cb13ff9] Processing folder: /downloads
2022-07-15 18:29:31 DEBUG	Thread :: [cb13ff9] No resource_name passed, using path [/downloads] to process as a source folder
2022-07-15 18:29:30 INFO	Thread :: [cb13ff9] Processing path: /downloads
2022-07-15 18:29:30 INFO	Thread :: [cb13ff9] Post processing called with:
path: /downloads
resource: None
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Finished updating network timezones
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] User-Agent: Medusa/1.0.5 (Linux; 5.15.0-41-generic; 84ea9b90-0417-11ed-a526-0242ac110007)
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] GET URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt [Status: 200]
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Started updating network timezones
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for oz set to: oz
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for barry set to: barry
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the wire set to: the wire
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for six feet under set to: six feet under
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for veep set to: veep
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for succession set to: succession
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for deadwood set to: deadwood
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the sopranos set to: the sopranos
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for golgo 13 set to: golgo 13
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for moon knight set to: moon knight
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for love in paradise the caribbean a 90 day story set to: love in paradise, "love in paradise the caribbean", love in paradise the caribbean a 90 day story, love in paradise the caribbean, "love in paradise the caribbean "
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for 90 day fiancé set to: "90 day fiance", 90 day fiance, 90 day fiancé
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for severance set to: severance
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for hanna set to: hanna
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for riget set to: riget
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for tokyo ghoul set to: tokyo ghoul
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for texhnolyze set to: texhnolyze
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for beef house set to: beef house
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the expanse set to: the expanse
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for wolfs rain set to: wolfs rain
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for south park set to: south park
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for broadchurch set to: broadchurch
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for sealab 2021 set to: sealab 2021
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for jujutsu kaisen set to: jujutsu kaisen tv, jujutsu kaisen
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the great british bake off an extra slice set to: the great british bake off an extra slice
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the great british bake off set to: the great british bake off
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for ted lasso set to: ted lasso
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for shameless set to: shameless us, shameless
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for broad city set to: broad city
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for psycho pass set to: psycho pass 2, psycho pass extended edition, psycho pass 3, psycho pass
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for last week tonight with john oliver set to: last week tonight with john oliver
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for genocyber set to: genocyber
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for hellsing ultimate set to: hellsing ultimate ova, hellsing 2006, hellsing ultimate
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for elfen lied set to: elfen lied
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for id invaded set to: id invaded
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for katanagatari set to: katanagatari
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for invincible set to: invincible
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for 90 day the single life set to: 90 day the single life
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for mob psycho 100 set to: mob psycho 100
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for american dad set to: american dad
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for deadly engineering set to: deadly engineering
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for 90 day fiancé happily ever after set to: 90 day fiance happily ever after, 90 day fiancé happily ever after
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the boys set to: the boys
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for 90 day fiancé before the 90 days set to: 90 day fiance before the 90 day, 90 day fiance before the 90 days, 90 day fiancé before the 90 days
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for terrace house tokyo 2019–2020 set to: terrace house tokyo 2019 2020, terrace house tokyo 2019–2020
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for euphoria us set to: euphoria us
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the witcher set to: the witcher
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for 90 day fiancé the other way set to: 90 day fiance the other way, 90 day the other way, 90 day fiancé the other way
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for carnival row set to: carnival row
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the dark crystal age of resistance set to: the dark crystal age of resistance
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for living with yourself set to: living with yourself
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for pennyworth set to: pennyworth
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for castle rock set to: castle rock
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for tom clancys jack ryan set to: tom clancys jack ryan
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the mandalorian set to: the mandalorian
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for the toys that made us set to: the toys that made us
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for terror in resonance set to: terror in resonance
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for one punch man set to: one punch man s2, one punch man 2019, one punch man
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for frisky dingo set to: frisky dingo
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for weighing up the enemy set to: weighing up the enemy
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for steins;gate 0 set to: steins;gate 0
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for check it out with dr steve brule set to: check it out with dr steve brule
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for star trek enterprise set to: star trek enterprise
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for goku midnight eye set to: goku midnight eye
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for planet earth live set to: planet earth live
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for fullmetal alchemist brotherhood set to: fullmetal alchemist brotherhood
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for cowboy bebop set to: cowboy bebop
2022-07-15 18:24:23 DEBUG	MAIN :: [cb13ff9] Internal name cache for comedian
</details>

**Additional context**

Unsure what has gone wrong, run it under docker, has been fine for a while, it's having problems with imports.

**Comment by p0psicles** [comment]
I think you tried to manual postprocess something without providing a path

**Comment by jaxjexjox** [comment]
USER@ubuntuserver:~$ sudo docker exec -i medusa /bin/sh
[sudo] password for USER:
cd /downloads
ls
(files listed here, which are in the show list, about 8 of them)



Also, the "Post-Processing Dir" is correct - I've even re-clicked it to be sure  - it's /downloads

**Comment by p0psicles** [comment]
How was this postprocess action triggered? As the logs show it was triggered using an exteral web call.
It was not triggered through the postprocessor thread.

So this was probably triggered when you tried to run a manual postprocess action?
IF this is true, can you reproduce it each time?

**Comment by jaxjexjox** [comment]
I manually instigated it.
I'll close this as it's gone away for the time being, hopefully not to return.

**Comment by p0psicles** [comment]
Well if I know how to manual instigate it. I might be able to better handle the exception?

**Comment by jaxjexjox** [comment]
Literally from the menus, manual post processing, with some files in the import directory.
It's gone for now.
