### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by artificial-chaos** [pymedusa/Medusa#10946]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@9b23c72f7e24bf638819e32d72f33e433f9649c4
**Link to Log**: https://gist.github.com/c5425e1109bb37af8042f90401daebbb
### ERROR
<pre>
2022-09-28 10:10:57 ERROR    POSTPROCESSOR :: [9b23c72] Environment error: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/schedulers/scheduler.py#L78">medusa/schedulers/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/post_processor.py#L1323">medusa/post_processor.py</a>", line 1323, in process
    notifiers.notify_download(ep_obj)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/__init__.py#L103">medusa/notifiers/__init__.py</a>", line 103, in notify_download
    n.notify_download(ep_obj)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L152">medusa/notifiers/pushover.py</a>", line 152, in notify_download
    self._notify_pushover(title, ep_obj.pretty_name_with_quality())
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L205">medusa/notifiers/pushover.py</a>", line 205, in _notify_pushover
    return self._send_pushover(message, title, sound=sound, user_key=user_key, api_key=api_key, priority=priority)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L96">medusa/notifiers/pushover.py</a>", line 96, in _send_pushover
    conn.request('POST', '/1/messages.json',
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 22] Invalid argument
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Just switch over to telegram or discord

**Comment by artificial-chaos** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@9b23c72f7e24bf638819e32d72f33e433f9649c4
**Link to Log**: https://gist.github.com/dfc18ab17ba46821188a84b99c109782
### ERROR
<pre>
2022-10-29 23:45:41 ERROR    POSTPROCESSOR :: [9b23c72] Environment error: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/schedulers/scheduler.py#L78">medusa/schedulers/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/post_processor.py#L1323">medusa/post_processor.py</a>", line 1323, in process
    notifiers.notify_download(ep_obj)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/__init__.py#L103">medusa/notifiers/__init__.py</a>", line 103, in notify_download
    n.notify_download(ep_obj)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L152">medusa/notifiers/pushover.py</a>", line 152, in notify_download
    self._notify_pushover(title, ep_obj.pretty_name_with_quality())
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L205">medusa/notifiers/pushover.py</a>", line 205, in _notify_pushover
    return self._send_pushover(message, title, sound=sound, user_key=user_key, api_key=api_key, priority=priority)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L96">medusa/notifiers/pushover.py</a>", line 96, in _send_pushover
    conn.request('POST', '/1/messages.json',
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 22] Invalid argument
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by artificial-chaos** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@9b23c72f7e24bf638819e32d72f33e433f9649c4
**Link to Log**: https://gist.github.com/94f795afe20461e644068b836ce8fc47
### ERROR
<pre>
2022-11-15 07:27:01 ERROR    POSTPROCESSOR :: [9b23c72] Environment error: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/schedulers/scheduler.py#L78">medusa/schedulers/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/post_processor.py#L1323">medusa/post_processor.py</a>", line 1323, in process
    notifiers.notify_download(ep_obj)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/__init__.py#L103">medusa/notifiers/__init__.py</a>", line 103, in notify_download
    n.notify_download(ep_obj)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L152">medusa/notifiers/pushover.py</a>", line 152, in notify_download
    self._notify_pushover(title, ep_obj.pretty_name_with_quality())
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L205">medusa/notifiers/pushover.py</a>", line 205, in _notify_pushover
    return self._send_pushover(message, title, sound=sound, user_key=user_key, api_key=api_key, priority=priority)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L96">medusa/notifiers/pushover.py</a>", line 96, in _send_pushover
    conn.request('POST', '/1/messages.json',
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 22] Invalid argument
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by artificial-chaos** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@9b23c72f7e24bf638819e32d72f33e433f9649c4
**Link to Log**: https://gist.github.com/1f703bfdb485076a1084524761b12d2e
### ERROR
<pre>
2023-02-22 15:06:33 ERROR    POSTPROCESSOR :: [9b23c72] Environment error: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/schedulers/scheduler.py#L78">medusa/schedulers/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/post_processor.py#L1323">medusa/post_processor.py</a>", line 1323, in process
    notifiers.notify_download(ep_obj)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/__init__.py#L103">medusa/notifiers/__init__.py</a>", line 103, in notify_download
    n.notify_download(ep_obj)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L152">medusa/notifiers/pushover.py</a>", line 152, in notify_download
    self._notify_pushover(title, ep_obj.pretty_name_with_quality())
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L205">medusa/notifiers/pushover.py</a>", line 205, in _notify_pushover
    return self._send_pushover(message, title, sound=sound, user_key=user_key, api_key=api_key, priority=priority)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/notifiers/pushover.py#L96">medusa/notifiers/pushover.py</a>", line 96, in _send_pushover
    conn.request('POST', '/1/messages.json',
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 22] Invalid argument
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by AubreyKloppers** [comment]
This is happening again, chaps!
