### ISSUE TITLE
Unhashable type reported

### ISSUE THREAD

**Issue by el56** [pymedusa/Medusa#10962]
I received this in my log. I'm reporting it to the developers as requested.

Ubuntu server 22.04

2022-10-13 18:58:57 WARNING  SEARCHQUEUE-BACKLOG-73244 :: [e4b480c] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/opt/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable

**Comment by xbette** [comment]
2022-10-28 04:28:59 WARNING  SHOWQUEUE-REFRESH :: [653207c] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/opt/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable
2022-10-28 04:11:19 WARNING  SHOWQUEUE-SEASON-UPDATE :: [653207c] 393189: Tried loading Andor None from the database with an episode id set to 0. We do not support that. Skipping to next episode.
2022-10-28 04:08:45 WARNING  SHOWQUEUE-UPDATE :: [653207c] 75978: Tried loading Family Guy None from the database with an episode id set to 0. We do not support that. Skipping to next episode.
2022-10-28 03:04:49 WARNING  CHECKVERSION :: [653207c] "/usr/bin/git" fetch --prune origin returned (128) : fatal: unable to access 'https://github.com/pymedusa/Medusa/': Could not resolve host: github.com
2022-10-28 03:04:49 WARNING  CHECKVERSION :: [653207c] Unable to contact github, can't check for update
2022-10-28 03:04:29 WARNING  CHECKVERSION :: [653207c] "/usr/bin/git" ls-remote --heads origin returned (128) : fatal: unable to access 'https://github.com/pymedusa/Medusa/': Could not resolve host: github.com

**Comment by gtlfilms** [comment]
2022-12-02 05:07:07 WARNING  SEARCHQUEUE-BACKLOG-412348 :: [e4870f8] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/app/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable

**Comment by ZMOT7S** [comment]
I received this error and after searching, noticed people were reporting them here. 



2022-12-12 04:44:40 WARNING  SHOWQUEUE-UPDATE :: [e4b480c] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/opt/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable

**Comment by 7ore** [comment]
Same thing. New environment, set up yesterday, using Docker:

`2022-12-23 02:15:43 WARNING  SHOWQUEUE-REFRESH :: [] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/app/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable
2022-12-23 02:10:05 WARNING  SHOWQUEUE-UPDATE :: [] 176941: Tried loading Sherlock None from the database with an episode id set to 0. We do not support that. Skipping to next episode.`
