### ISSUE TITLE
Not working on Python 3.11

### ISSUE THREAD

**Issue by csm10495** [pymedusa/Medusa#11007]
**Describe the bug**
Need to update wrapt for use with Python 3.11

**To Reproduce**
1. Attempt to use Python 3.11 with medusa

**Expected behavior**
Medusa starts

**Screenshots**
N/A

**Medusa (please complete the following information):**
 - OS: Win10x64
 - Branch: master
 - Commit: f690170c2cbd9f2804c38a6047059cb1ace8afe3
 - Python version: 3.11
 - Database version: ?

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
C:\Users\csm10495>c:\medusa\python\scripts\python.exe c:\medusa\medusa\start.py --nolaunch --datadir="C:\medusa\data"
Traceback (most recent call last):
  File "c:\medusa\medusa\start.py", line 6, in <module>
    from medusa.__main__ import main
  File "c:\medusa\medusa\medusa\__main__.py", line 67, in <module>
    from medusa import (
  File "c:\medusa\medusa\medusa\providers\__init__.py", line 41, in <module>
    provider_names = import_providers(__name__)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\medusa\medusa\medusa\providers\__init__.py", line 37, in import_providers
    import_submodules(package_name)
  File "c:\medusa\medusa\medusa\providers\__init__.py", line 25, in import_submodules
    module = importlib.import_module(full_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\medusa\medusa\medusa\providers\generic_provider.py", line 18, in <module>
    from medusa import (
  File "c:\medusa\medusa\medusa\config.py", line 37, in <module>
    from medusa.updater.version_checker import CheckVersion
  File "c:\medusa\medusa\medusa\updater\version_checker.py", line 17, in <module>
    from medusa.updater.docker_updater import DockerUpdateManager
  File "c:\medusa\medusa\medusa\updater\docker_updater.py", line 9, in <module>
    from medusa.updater.source_updater import SourceUpdateManager
  File "c:\medusa\medusa\medusa\updater\source_updater.py", line 12, in <module>
    from github import GithubException
  File "c:\medusa\medusa\ext\github\__init__.py", line 44, in <module>
    from github.MainClass import Github, GithubIntegration
  File "c:\medusa\medusa\ext\github\MainClass.py", line 62, in <module>
    import github.Gist
  File "c:\medusa\medusa\ext\github\Gist.py", line 40, in <module>
    import github.GistComment
  File "c:\medusa\medusa\ext\github\GistComment.py", line 38, in <module>
    import github.NamedUser
  File "c:\medusa\medusa\ext\github\NamedUser.py", line 46, in <module>
    import github.Event
  File "c:\medusa\medusa\ext\github\Event.py", line 37, in <module>
    import github.Organization
  File "c:\medusa\medusa\ext\github\Organization.py", line 56, in <module>
    import github.Repository
  File "c:\medusa\medusa\ext\github\Repository.py", line 96, in <module>
    from deprecated import deprecated
  File "c:\medusa\medusa\ext\deprecated\__init__.py", line 13, in <module>
    from deprecated.classic import deprecated
  File "c:\medusa\medusa\ext\deprecated\classic.py", line 13, in <module>
    import wrapt
  File "c:\medusa\medusa\ext\wrapt\__init__.py", line 10, in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "c:\medusa\medusa\ext\wrapt\decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (C:\Python3\Lib\inspect.py)
```
</details>

**Additional context**

I think we just need to update wrapt to fix this one

**Comment by csm10495** [comment]
I might be able to. When you update an ext do you just copy paste from the repo?

**Comment by medariox** [comment]
@csm10495 The packages usually come from the PyPI source distribution. E.g.: https://pypi.org/project/feedparser/6.0.2/#files

**Comment by medariox** [comment]
Thanks! Fixed with https://github.com/pymedusa/Medusa/pull/11009
