### ISSUE TITLE
[APP SUBMITTED]: FileNotFoundError: [Errno 2] No such file or directory: '/usr/syno/bin/synoindex'

### ISSUE THREAD

**Issue by Bekkenes** [pymedusa/Medusa#11041]
### INFO
**Python Version**: `3.9.15 (main, Nov 10 2022, 13:00:13) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/aebe3f67b9f009ba5dd61bf7d6128a39
### ERROR
<pre>
2022-11-20 17:01:44 ERROR    POSTPROCESSQUEUE-POST-PROCESS :: [] Unable to run synoindex: Error: 2: No such file or directory
Traceback (most recent call last):
  File "/app/medusa/medusa/notifiers/synoindex.py", line 72, in makeObject
    p = subprocess.Popen(synoindex_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/syno/bin/synoindex'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bekkenes** [comment]
### INFO
**Python Version**: `3.9.15 (main, Nov 10 2022, 13:00:13) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-12-07 22:39:11 ERROR    SHOWQUEUE-ADD :: [] Unable to run synoindex: Error: 2: No such file or directory
Traceback (most recent call last):
  File "/app/medusa/medusa/notifiers/synoindex.py", line 72, in makeObject
    p = subprocess.Popen(synoindex_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/syno/bin/synoindex'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by BenjV** [comment]
As of DSM 7 the synoindex does not exist anymore.
So this notification system cannot be used on DSM 7.
