### ISSUE TITLE
[APP SUBMITTED]: medusa.helper.exceptions.DownloadClientConnectionException: Unable to authenticate with rtorrent client: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by dirkronsmans** [pymedusa/Medusa#11047]
### INFO
**Python Version**: `3.8.12 (default, Nov 15 2021, 06:04:41) [GCC 8.5.0]`
**Operating System**: `Linux-4.4.180+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4b480c924d0dbb01417333a5669b3cfcf19f9fe
**Link to Log**: https://gist.github.com/b63259c6c5dc84cdb27caa3db07e0388
### ERROR
<pre>
2022-11-30 20:48:08 ERROR    SNATCHQUEUE-SNATCH-19809 :: [e4b480c] Snatch failed! For result: The.Resident.S06E09.720p.HEVC.x265-MeGusta
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/urllib3/connection.py#L158">ext/urllib3/connection.py</a>", line 158, in _new_conn
    conn = connection.create_connection(
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/urllib3/util/connection.py#L57">ext/urllib3/util/connection.py</a>", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/urllib3/connectionpool.py#L354">ext/urllib3/connectionpool.py</a>", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1295, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1341, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1290, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 986, in send
    self.connect()
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/urllib3/connection.py#L181">ext/urllib3/connection.py</a>", line 181, in connect
    conn = self._new_conn()
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/urllib3/connection.py#L167">ext/urllib3/connection.py</a>", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa4dfe39b50>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/requests/adapters.py#L439">ext/requests/adapters.py</a>", line 439, in send
    resp = conn.urlopen(
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/urllib3/util/retry.py#L398">ext/urllib3/util/retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='**********.seedbox.io', port=80): Max retries exceeded with url: /rutorrent/plugins/httprpc/action.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4dfe39b50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/lib/rtorrent/lib/xmlrpc/requests_transport.py#L119">lib/rtorrent/lib/xmlrpc/requests_transport.py</a>", line 119, in request
    response = requests.post(
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/requests/api.py#L119">ext/requests/api.py</a>", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/requests/api.py#L61">ext/requests/api.py</a>", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/requests/sessions.py#L542">ext/requests/sessions.py</a>", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/requests/sessions.py#L655">ext/requests/sessions.py</a>", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/ext/requests/adapters.py#L516">ext/requests/adapters.py</a>", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='**********.seedbox.io', port=80): Max retries exceeded with url: /rutorrent/plugins/httprpc/action.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa4dfe39b50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/medusa/clients/torrent/rtorrent.py#L57">medusa/clients/torrent/rtorrent.py</a>", line 57, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/lib/rtorrent/__init__.py#L87">lib/rtorrent/__init__.py</a>", line 87, in __init__
    self._verify_conn()
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/lib/rtorrent/__init__.py#L126">lib/rtorrent/__init__.py</a>", line 126, in _verify_conn
    assert 'system.client_version' in self._get_rpc_methods(
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/lib/rtorrent/__init__.py#L164">lib/rtorrent/__init__.py</a>", line 164, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/lib/rtorrent/__init__.py#L154">lib/rtorrent/__init__.py</a>", line 154, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/lib/rtorrent/lib/xmlrpc/requests_transport.py#L147">lib/rtorrent/lib/xmlrpc/requests_transport.py</a>", line 147, in request
    response.status_code,
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/medusa/search/queue.py#L516">medusa/search/queue.py</a>", line 516, in run
    self.success = snatch_result(result)
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/medusa/search/core.py#L168">medusa/search/core.py</a>", line 168, in snatch_result
    client = torrent.get_client_class(app.TORRENT_METHOD)()
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/medusa/clients/torrent/rtorrent.py#L36">medusa/clients/torrent/rtorrent.py</a>", line 36, in __init__
    self._get_auth()
  File "/volume1/@appstore/medusa/src/<a href="../blob/e4b480c924d0dbb01417333a5669b3cfcf19f9fe/medusa/clients/torrent/rtorrent.py#L61">medusa/clients/torrent/rtorrent.py</a>", line 61, in _get_auth
    raise DownloadClientConnectionException(f'Unable to authenticate with rtorrent client: {error}')
medusa.helper.exceptions.DownloadClientConnectionException: Unable to authenticate with rtorrent client: local variable 'response' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dirkronsmans** [comment]
### INFO
**Python Version**: `3.8.12 (default, Nov 15 2021, 06:04:41) [GCC 8.5.0]`
**Operating System**: `Linux-4.4.180+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@671a44334d98db8a3872b23aa9dd82bb76fbfc4b
**Link to Log**: https://gist.github.com/dirkronsmans/1e15b14057bfd821754ef451134d0e3a
### ERROR
<pre>
2023-03-21 03:27:58 ERROR    SNATCHQUEUE-SNATCH-60 :: [671a443] Snatch failed! For result: NCIS.S20E17.720p.HEVC.x265-MeGusta
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/urllib3/connection.py#L158">ext/urllib3/connection.py</a>", line 158, in _new_conn
    conn = connection.create_connection(
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/urllib3/util/connection.py#L57">ext/urllib3/util/connection.py</a>", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/urllib3/connectionpool.py#L354">ext/urllib3/connectionpool.py</a>", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1295, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1341, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1290, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 986, in send
    self.connect()
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/urllib3/connection.py#L181">ext/urllib3/connection.py</a>", line 181, in connect
    conn = self._new_conn()
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/urllib3/connection.py#L167">ext/urllib3/connection.py</a>", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8403d30340>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/requests/adapters.py#L489">ext/requests/adapters.py</a>", line 489, in send
    resp = conn.urlopen(
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/urllib3/util/retry.py#L398">ext/urllib3/util/retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='**********.seedbox.io', port=80): Max retries exceeded with url: /rutorrent/plugins/httprpc/action.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8403d30340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/lib/rtorrent/lib/xmlrpc/requests_transport.py#L119">lib/rtorrent/lib/xmlrpc/requests_transport.py</a>", line 119, in request
    response = requests.post(
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/requests/api.py#L115">ext/requests/api.py</a>", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/requests/api.py#L59">ext/requests/api.py</a>", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/requests/sessions.py#L587">ext/requests/sessions.py</a>", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/requests/sessions.py#L701">ext/requests/sessions.py</a>", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/ext/requests/adapters.py#L565">ext/requests/adapters.py</a>", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='**********.seedbox.io', port=80): Max retries exceeded with url: /rutorrent/plugins/httprpc/action.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8403d30340>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/medusa/clients/torrent/rtorrent.py#L57">medusa/clients/torrent/rtorrent.py</a>", line 57, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/lib/rtorrent/__init__.py#L87">lib/rtorrent/__init__.py</a>", line 87, in __init__
    self._verify_conn()
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/lib/rtorrent/__init__.py#L126">lib/rtorrent/__init__.py</a>", line 126, in _verify_conn
    assert 'system.client_version' in self._get_rpc_methods(
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/lib/rtorrent/__init__.py#L164">lib/rtorrent/__init__.py</a>", line 164, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/lib/rtorrent/__init__.py#L154">lib/rtorrent/__init__.py</a>", line 154, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/lib/rtorrent/lib/xmlrpc/requests_transport.py#L147">lib/rtorrent/lib/xmlrpc/requests_transport.py</a>", line 147, in request
    response.status_code,
UnboundLocalError: local variable 'response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/medusa/search/queue.py#L516">medusa/search/queue.py</a>", line 516, in run
    self.success = snatch_result(result)
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/medusa/search/core.py#L173">medusa/search/core.py</a>", line 173, in snatch_result
    client = torrent.get_client_class(app.TORRENT_METHOD)()
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/medusa/clients/torrent/rtorrent.py#L36">medusa/clients/torrent/rtorrent.py</a>", line 36, in __init__
    self._get_auth()
  File "/volume1/@appstore/medusa/src/<a href="../blob/671a44334d98db8a3872b23aa9dd82bb76fbfc4b/medusa/clients/torrent/rtorrent.py#L61">medusa/clients/torrent/rtorrent.py</a>", line 61, in _get_auth
    raise DownloadClientConnectionException(f'Unable to authenticate with rtorrent client: {error}')
medusa.helper.exceptions.DownloadClientConnectionException: Unable to authenticate with rtorrent client: local variable 'response' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
