### ISSUE TITLE
Cannot add Trakt account to Medusa

### ISSUE THREAD

**Issue by farffy** [pymedusa/Medusa#11050]
When I click on 'Connect to your trakt account' nothing happens.  When I look at the logs I get a 403 response, so it's being blocked

**Medusa (please complete the following information):**
 - OS: Linux Mint 21
 - Branch: master
 - Commit: unknown
 - Python version: 3.9.15 
 - Database version: 44.19

**Debug logs (at least 50 lines):**
2022-12-06 12:21:01 WARNING	Thread :: Unable to test TRAKT: ForbiddenException(<Response [403]>)
Traceback (most recent call last):
  File "/app/medusa/medusa/notifiers/trakt.py", line 159, in test_notify
    trakt_user = get_trakt_user()
  File "/app/medusa/medusa/helpers/trakt.py", line 23, in get_trakt_user
    user = users.get_user_settings()
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.ForbiddenException: Forbidden - invalid API key or unapproved app
2022-12-06 12:21:01 WARNING	Thread :: Unable to get trakt user, error: Forbidden - invalid API key or unapproved app
Traceback (most recent call last):
  File "/app/medusa/medusa/helpers/trakt.py", line 23, in get_trakt_user
    user = users.get_user_settings()
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.ForbiddenException: Forbidden - invalid API key or unapproved app
2022-12-06 12:20:59 WARNING	APIv2-Thread :: Could not get the `removed from medusa` list
Traceback (most recent call last):
  File "/app/medusa/medusa/server/api/v2/recommended.py", line 48, in get
    data['removedFromMedusa'] = TraktPopular().get_removed_from_medusa()
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 128, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.ForbiddenException: Forbidden - invalid API key or unapproved app

**Comment by adamgoldberg** [comment]
Same issue.  Anyone working on this?
