### ISSUE TITLE
Medusa does not recognize file of show "1923"

### ISSUE THREAD

**Issue by anonvoy** [pymedusa/Medusa#11067]
**Describe the bug**
Medusa does not recognize a file of the show 1923 (the show as such was added without any problem from TVmaze). It is not post processed because Medusa apparently does not recognize the file is for the show 1923. It seems some parser does not interpret "1923" as the title, but as a year (which it is of course, but in this case it's also a title). Or do the nzbtomedia scripts interfere?

Apparently Medusa also does not "see" the files at Indexers, see [this Reddit thread](https://www.reddit.com/r/PyMedusa/comments/zowa4p/scene_exceptions_1923/).

**To Reproduce**
1. Download a file of the show 1923.
2. Try to have manual post processing process it.

**Expected behavior**
Files are recognized and post processed as normal.

**Medusa (please complete the following information):**
 - OS: OpenSUSE 15.4
 - Branch: master
 - Commit: 0b9b58d184ae4fc5467f3474d452f888dfbaac10
 - Python version: 3.6.15
 - Database version: 44.19

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2022-12-18 16:16:45 WARNING  Thread_11 :: [0b9b58d] Processing failed for /home/abc/abcswap/sabnzbd/complete/tv4/1923 S01E01 1080p AMZN WEB-DL DDP5 1 H 264-NTb/1923.S01E01.1923.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb-transcoded.mkv: This show isn't in your list, you need to add it before post-processing an episode
2022-12-18 16:16:45 WARNING  Thread_11 :: [0b9b58d] Problem(s) during processing, failed for the following files/folders: 
2022-12-18 16:16:45 WARNING  Thread_11 :: [0b9b58d] Missed file: /home/abc/abcswap/sabnzbd/complete/tv4/1923 S01E01 1080p AMZN WEB-DL DDP5 1 H 264-NTb/1923.S01E01.1923.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb-transcoded.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2022-12-18 16:16:45 WARNING  Thread_11 :: [0b9b58d] Not enough information to parse release name into a valid show. Consider adding scene exceptions or improve naming for: 1923.S01E01.1923.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb-transcoded
Traceback (most recent call last):
  File "/home/abc/.pymedusa/medusa/failed_processor.py", line 45, in _process_release_name
    parse_result = NameParser().parse(release_name, use_cache=False)
  File "/home/abc/.pymedusa/medusa/name_parser/parser.py", line 455, in parse
    self.assert_supported(result)
  File "/home/abc/.pymedusa/medusa/name_parser/parser.py", line 474, in assert_supported
    'Parser result: {result}'.format(result=result))
medusa.name_parser.parser.InvalidShowException: Unable to match 1923.S01E01.1923.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb-transcoded to a series in your database. Parser result: season: 1, episode: [1], year: 1923, screen_size: 1080p, streaming_service: Amazon Prime, source: Web, audio_codec: Dolby Digital Plus, audio_channels: 5.1, video_codec: H.264, title: NTb-transcoded, type: episode, parsing_time: 0.17785882949829102, absolute_episode: [], quality: 1080p WEB-DL, total_time: 0.2493743896484375
2022-12-18 16:16:45 WARNING  Thread_11 :: [0b9b58d] Failed Download Processing failed: None, /home/abc/abcswap/sabnzbd/complete/tv4/1923 S01E01 1080p AMZN WEB-DL DDP5 1 H 264-NTb: 
2022-12-18 16:13:30 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [0b9b58d] Warning: unable to find a valid release name.
2022-12-18 16:13:30 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [0b9b58d] Failed Download Processing failed: 1923 S01E01 1080p AMZN WEB-DL DDP5 1 H 264-NTb, /home/abc/Downloads/sabnzbd/complete/tv4/1923 S01E01 1080p AMZN WEB-DL DDP5 1 H 264-NTb: 
```
</details>

**Comment by anonvoy** [comment]
When copying the file to the season folder manually and renaming it to follow the usual conventions, Medusa does recognize the file when performing a "re-scan files" and is also able to find subtitles.

**Comment by papampi** [comment]
+1

**Comment by Midavalo** [comment]
+1.  The show 1923 isn't seen on indexers, and if manually downloaded the post processor doesn't recognize the file as belonging to the already added show.

```
Post-processing video files: ['1923.S01E01.1080p.x265-ELiTE.mkv']
Processing failed for /mnt/abc/1923.S01E01.1080p.x265-ELiTE/1923.S01E01.1080p.x265-ELiTE.mkv: This show isn't in your list, you need to add it before post-processing an episode
```

**Comment by bdunnaway** [comment]
I renamed the show files "Y1923*" in my torrent client, and then added a scene exception for "Y1923", and it worked.

**Comment by papampi** [comment]
Just manually move the downloaded file to series/season folder, then let Medusa scan and rename episodes until its fixed.

**Comment by thompatry** [comment]
I have requested a pull request to solve this issues. It is a problem with GuessIt and labeling it as 1923 as the year. You can see the pull request [here](https://github.com/pymedusa/Medusa/pull/11081).

**Comment by x9906789x** [comment]
looks like you have this solved in what i'm reading but just wanted to point out that 1883 worked fine. not sure what logic made that work and not 1923. but figured i'd note in case it changes how you solved for it.

**Comment by thompatry** [comment]
1883 was recognized as an absolute episode number via guessit. 1923 is being recognized by the release year only. We had to account for both situations.

**Comment by haqthat** [comment]
Is this currently only in the dev branch?I looked, I didn’t see it in main. On Jan 3, 2023, at 4:59 PM, Thomas Patry ***@***.***> wrote:﻿
1883 was recognized as an absolute episode number via guessit. 1923 is being recognized by the release year only. We had to account for both situations.

**Comment by thompatry** [comment]
It will be merged in the main when the next release occurs.

**Comment by jxer** [comment]
> It will be merged in the main when the next release occurs.

do you have a rough eta on the release?

**Comment by medariox** [comment]
Fixed with the new release.
