### ISSUE TITLE
WARNING: Unhashable type encountered. Please report this warning to the developers.

### ISSUE THREAD

**Issue by hetap01** [pymedusa/Medusa#11095]
Occurs multiple times every 24 hours

```
023-01-11 18:14:52 WARNING	SNATCHQUEUE-SNATCH-272644 :: [0b9b58d] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable
```
Version info

<html><body>

Medusa Info: | Branch:                 master                  Commit:                 0b9b58d184ae4fc5467f3474d452f888dfbaac10                  Version:                 1.0.10                  Database:                 44.19
-- | --
Python Version: | 3.8.12 (default, Nov 15 2021, 06:04:41)  [GCC 8.5.0]
SSL Version: | OpenSSL 1.1.1o  3 May 2022
OS: | Linux-4.4.180+-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8
Timezone: | AEDT

**Comment by hetap01** [comment]
`2023-02-15 04:33:00 WARNING  SHOWQUEUE-UPDATE :: [b9292f9] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable`

Still occurring intermittently, unable to force it to generate. This just appears in the warning log from time to time now.
