### ISSUE TITLE
[APP SUBMITTED]: KeyError: 'streams'

### ISSUE THREAD

**Issue by mooneye14** [pymedusa/Medusa#11092]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@552f1199853dfce905f9ba6e27194da67070ea6a
**Link to Log**: https://gist.github.com/dc45b9450c04be5a871c3e9bafb1bcea
### ERROR
<pre>
2023-01-06 16:00:05 ERROR    Thread_0 :: [552f119] Exception generated: 'streams'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/552f1199853dfce905f9ba6e27194da67070ea6a/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/552f1199853dfce905f9ba6e27194da67070ea6a/medusa/server/web/home/post_process.py#L101">medusa/server/web/home/post_process.py</a>", line 101, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "/app/medusa/<a href="../blob/552f1199853dfce905f9ba6e27194da67070ea6a/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/552f1199853dfce905f9ba6e27194da67070ea6a/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/552f1199853dfce905f9ba6e27194da67070ea6a/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/552f1199853dfce905f9ba6e27194da67070ea6a/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
  File "/app/medusa/<a href="../blob/552f1199853dfce905f9ba6e27194da67070ea6a/medusa/post_processor.py#L1050">medusa/post_processor.py</a>", line 1050, in process
    result = FfMpeg().check_for_video_and_audio_streams(self.file_path)
  File "/app/medusa/<a href="../blob/552f1199853dfce905f9ba6e27194da67070ea6a/medusa/helpers/ffmpeg.py#L62">medusa/helpers/ffmpeg.py</a>", line 62, in check_for_video_and_audio_streams
    video_streams = [item for item in video_details['streams'] if item['codec_type'] == 'video']
KeyError: 'streams'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bhawson** [comment]
### INFO
**Python Version**: `3.9.6 (default, Oct 18 2022, 12:41:40) [Clang 14.0.0 (clang-1400.0.29.202)]`
**Operating System**: `macOS-12.6.5-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476
**Link to Log**: https://gist.github.com/bhawson/7b9ddf2afad638e29e7f21a5279238eb
### ERROR
<pre>
2023-04-26 02:14:56 ERROR    POSTPROCESSOR :: [6b37ad0] Exception generated: 'streams'
Traceback (most recent call last):
  File "/Users/**********/Library/Application Support/Medusa/medusa/schedulers/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/Users/**********/Library/Application Support/Medusa/medusa/process_tv.py", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/Users/**********/Library/Application Support/Medusa/medusa/process_tv.py", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/Users/**********/Library/Application Support/Medusa/medusa/process_tv.py", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/Users/**********/Library/Application Support/Medusa/medusa/process_tv.py", line 890, in process_media
    self.result = processor.process()
  File "/Users/**********/Library/Application Support/Medusa/medusa/post_processor.py", line 1050, in process
    result = FfMpeg().check_for_video_and_audio_streams(self.file_path)
  File "/Users/**********/Library/Application Support/Medusa/medusa/helpers/ffmpeg.py", line 62, in check_for_video_and_audio_streams
    video_streams = [item for item in video_details['streams'] if item['codec_type'] == 'video']
KeyError: 'streams'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fexofenadine** [comment]
### INFO
**Python Version**: `3.10.11 (main, Apr  6 2023, 01:16:54) [GCC 12.2.1 20220924]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-05-19 17:02:14 ERROR    POSTPROCESSOR :: [baad1e5] Exception generated: 'streams'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/schedulers/scheduler.py#L78">medusa/schedulers/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/post_processor.py#L1050">medusa/post_processor.py</a>", line 1050, in process
    result = FfMpeg().check_for_video_and_audio_streams(self.file_path)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/helpers/ffmpeg.py#L62">medusa/helpers/ffmpeg.py</a>", line 62, in check_for_video_and_audio_streams
    video_streams = [item for item in video_details['streams'] if item['codec_type'] == 'video']
KeyError: 'streams'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Kramasz** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-3.10.108-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@3d656652ab277e47689483912ed7fc443e7023e8
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-08-31 06:46:42 ERROR    POSTPROCESSOR :: [3d65665] Exception generated: 'streams'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/schedulers/scheduler.py#L78">medusa/schedulers/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/post_processor.py#L1050">medusa/post_processor.py</a>", line 1050, in process
    result = FfMpeg().check_for_video_and_audio_streams(self.file_path)
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/helpers/ffmpeg.py#L62">medusa/helpers/ffmpeg.py</a>", line 62, in check_for_video_and_audio_streams
    video_streams = [item for item in video_details['streams'] if item['codec_type'] == 'video']
KeyError: 'streams'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Kramasz** [comment]
### INFO
**Python Version**: `3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-3.10.108-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@3d656652ab277e47689483912ed7fc443e7023e8
**Link to Log**: https://gist.github.com/Kramasz/83f8b103d1546ed5c1acea62903db393
### ERROR
<pre>
2023-09-01 06:01:44 ERROR    Thread_1 :: [3d65665] Exception generated: 'streams'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/server/web/home/post_process.py#L101">medusa/server/web/home/post_process.py</a>", line 101, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/post_processor.py#L1050">medusa/post_processor.py</a>", line 1050, in process
    result = FfMpeg().check_for_video_and_audio_streams(self.file_path)
  File "/app/medusa/<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/helpers/ffmpeg.py#L62">medusa/helpers/ffmpeg.py</a>", line 62, in check_for_video_and_audio_streams
    video_streams = [item for item in video_details['streams'] if item['codec_type'] == 'video']
KeyError: 'streams'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Zeagl3** [comment]
### INFO
**Python Version**: `3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19045-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@3d656652ab277e47689483912ed7fc443e7023e8
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-10-13 13:07:46 ERROR    POSTPROCESSOR :: [3d65665] Exception generated: 'streams'
Traceback (most recent call last):
  File "D:\Medusa\<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/schedulers/scheduler.py#L78">medusa\schedulers\scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "D:\Medusa\<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L240">medusa\process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "D:\Medusa\<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L399">medusa\process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "D:\Medusa\<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L665">medusa\process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "D:\Medusa\<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/process_tv.py#L890">medusa\process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
                  ^^^^^^^^^^^^^^^^^^^
  File "D:\Medusa\<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/post_processor.py#L1050">medusa\post_processor.py</a>", line 1050, in process
    result = FfMpeg().check_for_video_and_audio_streams(self.file_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Medusa\<a href="../blob/3d656652ab277e47689483912ed7fc443e7023e8/medusa/helpers/ffmpeg.py#L62">medusa\helpers\ffmpeg.py</a>", line 62, in check_for_video_and_audio_streams
    video_streams = [item for item in video_details['streams'] if item['codec_type'] == 'video']
                                      ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'streams'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Kramasz** [comment]
It only happens if the video file is corrupt. It's from trying to determine encoding I believe. If this fails on a file, delete that file and re run processing and it will continue. It actually helps prevent overwriting a good video file with a busted one. I half suspect these files are are being put out there for that reason.

**Comment by fexofenadine** [comment]
### INFO
**Python Version**: `3.11.8 (main, Feb 19 2024, 17:01:17) [GCC 13.2.1 20231014]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-03-24 21:47:51 ERROR    POSTPROCESSOR :: [baad1e5] Exception generated: 'streams'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/schedulers/scheduler.py#L78">medusa/schedulers/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/process_tv.py#L240">medusa/process_tv.py</a>", line 240, in run
    process_results.process(force=force, **kwargs)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/process_tv.py#L399">medusa/process_tv.py</a>", line 399, in process
    self.process_files(dir_path, force=force, is_priority=is_priority,
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/process_tv.py#L665">medusa/process_tv.py</a>", line 665, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/process_tv.py#L890">medusa/process_tv.py</a>", line 890, in process_media
    self.result = processor.process()
                  ^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/post_processor.py#L1050">medusa/post_processor.py</a>", line 1050, in process
    result = FfMpeg().check_for_video_and_audio_streams(self.file_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/helpers/ffmpeg.py#L62">medusa/helpers/ffmpeg.py</a>", line 62, in check_for_video_and_audio_streams
    video_streams = [item for item in video_details['streams'] if item['codec_type'] == 'video']
                                      ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'streams'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
