### ISSUE TITLE
Scene exceptions keep diapering 

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#11106]
**Describe the bug**
Scene exceptions keep diapering 

I enter scene exceptions;
![image](https://user-images.githubusercontent.com/14140816/214130048-9ec2378b-6062-469c-a15c-6c6e00e32925.png)

and within a week they are gone..
I keep get log messages;

2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Problem(s) during processing, failed for the following files/folders: 
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Miss Scarlet And The Duke (2020) S01E01 720p HDTV x264[eztv io].mp4: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Miss Scarlet And The Duke (2020) S01E05 720p HDTV x264 Cherzo[eztv io].mp4: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E01 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E02 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E03 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E04 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E05 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E06 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E07 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E08 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E09 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Get.Even.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Get Even (2020) S01E10 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Inside the Heist (2022) S01E01 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Inside the Heist (2022) S01E02 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Inside the Heist (2022) S01E03 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Inside the Heist (2022) S01E04 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Inside the Heist (2022) S01E05 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:17:05 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Missed file: \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Inside the Heist (2022) S01E06 720p WEBRip x264 GalaxyTV.mkv: Processing failed: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:14:23 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Failed Download Processing failed: None, \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]: 
2023-01-23 08:14:23 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Processing failed for \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Inside the Heist (2022) S01E06 720p WEBRip x264 GalaxyTV.mkv: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:14:23 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Not enough information to parse release name into a valid show. Consider adding scene exceptions or improve naming for: Inside the Heist (2022) S01E06 720p WEBRip x264 GalaxyTV
Traceback (most recent call last):
  File "C:\Medusa_2020\medusa\failed_processor.py", line 45, in _process_release_name
    parse_result = NameParser().parse(release_name, use_cache=False)
  File "C:\Medusa_2020\medusa\name_parser\parser.py", line 455, in parse
    self.assert_supported(result)
  File "C:\Medusa_2020\medusa\name_parser\parser.py", line 473, in assert_supported
    raise InvalidShowException('Unable to match {result.original_name} to a series in your database. '
medusa.name_parser.parser.InvalidShowException: Unable to match Inside the Heist (2022) S01E06 720p WEBRip x264 GalaxyTV to a series in your database. Parser result: title: Inside the Heist, alias: Inside the Heist 2022, year: 2022, season: 1, episode: [6], screen_size: 720p, source: Web, other: Rip, video_codec: H.264, video_encoder: x264, release_group: GalaxyTV, type: episode, parsing_time: 0.09372568130493164, absolute_episode: [], quality: 720p WEB-DL, total_time: 0.17182517051696777
2023-01-23 08:14:22 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Processing failed for \\192.168.29.75\Downloads\Medusa\MU2020\Inside.the.Heist.S01.COMPLETE.720p.WEBRip.x264-GalaxyTV[TGx]\Inside the Heist (2022) S01E05 720p WEBRip x264 GalaxyTV.mkv: This show isn't in your list, you need to add it before post-processing an episode
2023-01-23 08:14:22 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Not enough information to parse release name into a valid show. Consider adding scene exceptions or improve naming for: Inside the Heist (2022) S01E05 720p WEBRip x264 GalaxyTV
Traceback (most recent call last):
  File "C:\Medusa_2020\medusa\failed_processor.py", line 45, in _process_release_name
    parse_result = NameParser().parse(release_name, use_cache=False)
  File "C:\Medusa_2020\medusa\name_parser\parser.py", line 455, in parse
    self.assert_supported(result)
  File "C:\Medusa_2020\medusa\name_parser\parser.py", line 473, in assert_supported
    raise InvalidShowException('Unable to match {result.original_name} to a series in your database. '
medusa.name_parser.parser.InvalidShowException: Unable to match Inside the Heist (2022) S01E05 720p WEBRip x264 GalaxyTV to a series in your database. Parser result: title: Inside the Heist, alias: Inside the Heist 2022, year: 2022, season: 1, episode: [5], screen_size: 720p, source: Web, other: Rip, video_codec: H.264, video_encoder: x264, release_group: GalaxyTV, type: episode, parsing_time: 0.09377479553222656, absolute_episode: [], quality: 720p WEB-DL, total_time: 0.15627598762512207
2023-01-23 08:14:21 WARNING  POSTPROCESSQUEUE-POST-PROCESS :: [b9292f9] Not enough information to parse release name into a valid show. Consider adding scene exceptions or improve naming for: Inside the Heist (2022) S01E03 720p WEBRip x264 GalaxyTV
Traceback (most recent call last):

That they aren't in the list..... sure enough they are missing again..  It happens every day to different shows''
Also the download gets deleted...  I loose whole seasons because of this and have to re-downlod..

Thats GB per week,  common shows are the worst.

Please fix this....

Also why doesn't it match if the show name is;
![image](https://user-images.githubusercontent.com/14140816/214132707-11a08fb5-2411-4e14-9545-8b1035a0eb94.png)

and the download is;
![image](https://user-images.githubusercontent.com/14140816/214132790-112dcfd9-dff1-4d50-ac1e-bf334b277c9b.png)

I have to create a scene exception just like the show name to get it to match....

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
![image](https://user-images.githubusercontent.com/14140816/214131297-4d974f07-5462-4c54-a08c-a6750365fb91.png)

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by crxed9** [comment]
Are you pressing the Save Changes button after adding an exception?

Download shouldn't get deleted if it's not processed.

(and place the log between the correct tags please)

**Comment by nydave69** [comment]
> Are you pressing the Save Changes button after adding an exception?
> 
> Download shouldn't get deleted if it's not processed.
> 
> (and place the log between the correct tags please)

Yes I am pressing the Save Changes button after adding the exceptions
Download shouldn't get deleted if it's not processed.  but it is...  as shown in the log..  It tries to processing it but no match is found and it does a cleanup of the folder and removes the files, at the end it does something and give the log message that it can't find the file. Because it deleted it...

sorry about the log..
