### ISSUE TITLE
After upgrading to Python 3.11.2, Medusa is unable to snatch an episode from NZB server

### ISSUE THREAD

**Issue by roscocheeta** [pymedusa/Medusa#11127]
**Describe the bug**
After upgrading to Python 3.11, Medusa is unable to snatch episodes from NZB server.

**To Reproduce**
1. Shutdown Medusa
2. Upgrade Python from 3.7 > 3.11
3. Load Medusa
4. Manually choose a NZB episode to Snatch from NZB server

**Expected behavior**
Medusa 1.0.11 should be able to successfully snatch an episode.

**Screenshots**
![firefox_NzKaHhOVq9](https://user-images.githubusercontent.com/9146800/218660337-5cecbd97-1e81-48bd-a16b-c1d5dd7805e5.png)

**Medusa (please complete the following information):**
 - OS: Windows-10-10.0.17763-SP0
 - Branch: master
 - Commit:  b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e
 - Python version:   3.11.2 
 - Database version: 44.19

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2023-02-14 14:41:47 ERROR	SNATCHQUEUE-SNATCH-196741 :: [b9292f9] Snatch failed! For result: The.Real.Housewives.of.Beverly.Hills.S08E19.Reunion.Part.1.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb

Traceback (most recent call last):

  File "C:\MediaApps\Medusa\Medusa\medusa\search\queue.py", line 516, in run

    self.success = snatch_result(result)

                   ^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Medusa\medusa\search\core.py", line 147, in snatch_result

    result_downloaded = nzbget.send_nzb(result, is_proper)

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Medusa\medusa\clients\nzb\nzbget.py", line 113, in send_nzb

    if not nzb_connection(url):

           ^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Medusa\medusa\clients\nzb\nzbget.py", line 31, in nzb_connection

    nzb_get_rpc = ServerProxy(url)

                  ^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1430, in __init__

    p = urllib.parse.urlsplit(uri)

        ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\urllib\parse.py", line 474, in urlsplit

    raise ValueError("Invalid IPv6 URL")

ValueError: Invalid IPv6 URL
2023-02-14 14:41:47 INFO	SNATCHQUEUE-SNATCH-196741 :: [b9292f9] Downloading The.Real.Housewives.of.Beverly.Hills.S08E19.Reunion.Part.1.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb with size: 4.87 GB from NZBFinder.ws, through a SearchType.MANUAL_SEARCH search
2023-02-14 14:41:47 INFO	SNATCHQUEUE-SNATCH-196741 :: [b9292f9] Beginning to snatch release: The.Real.Housewives.of.Beverly.Hills.S08E19.Reunion.Part.1.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb

```
</details>

**Additional context**
Rolling back to Python 3.7 resolves the issue as a temporary workaround.

**Comment by BenjV** [comment]
No logs?

**Comment by roscocheeta** [comment]
> No logs?

Hi @BenjV 

I included a log snippet within the Details section. It was the only errors being shown from the wider log set (with debug mode enabled).

![firefox_uxujR5zfWE](https://user-images.githubusercontent.com/9146800/218892716-6582bc31-60ed-4609-bfe0-6c97a893f8f0.gif)

**Comment by BenjV** [comment]
Useless, unreadable!

**Comment by roscocheeta** [comment]
> Useless, unreadable! Post a normal log from medusa

Thanks for advice.

As per the bug submission template it indicated in the template to provide at least 50 debug log lines, so that is what I did. So I am a little surprised that the snippet I provided is "useless and unreadable" as you state when I was simply following the very instructions provided in the template for a bug submission. Suggest you revise the template for bug submissions to meet your requirements. 

Attached is a full debug log snippet. During this log was a test to reproduce the issue. 

Hope this is what you are looking for. 

[application-debug14022023.log](https://github.com/pymedusa/Medusa/files/10741443/application-debug14022023.log)

**Comment by medariox** [comment]
Looks like Python 3.11 doesn't like the NZB server URL for some reason. Do you have any special characters in your server address or password?

**Comment by roscocheeta** [comment]
> Looks like Python 3.11 doesn't like the NZB server URL for some reason. Do you have any special characters in your server address or password?

Hi @medariox thanks for taking a look - appreciate it. 

I have two NZB servers configured as search providers. Neither of them have special characters in the URL and the passwords are just API keys which are just alphanumeric. 

NZB Search is configured to send the .nzb files to NZBGet, and the URL for that is just internal private IP address and port. The username has no special characters, however the password does have special characters.

**Comment by medariox** [comment]
@roscocheeta 
Can you try this PR and report if the fix works? https://github.com/pymedusa/Medusa/pull/11129

**Comment by roscocheeta** [comment]
> @roscocheeta Can you try this PR and report if the fix works? #11129

Thanks @medariox 

I tried the fix but seems to be throwing some additional log entries now as per the below snippet in the Details section below:

<details>

```
2023-02-15 21:11:51 DEBUG	TORNADO :: [b9292f9] Failed doing web ui get request 'destroy': Traceback (most recent call last):

  File "C:\MediaApps\Medusa\Medusa\medusa\server\web\core\base.py", line 218, in get

    method = getattr(self, route)

             ^^^^^^^^^^^^^^^^^^^^

AttributeError: 'WebRoot' object has no attribute 'destroy'
2023-02-15 21:11:25 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Transaction with 1 queries executed
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] 73762: Formatting pattern: %SN - %Sx06 - %EN - %QN -> Grey's Anatomy - 19x06 - Thunderstruck - 720p WEB-DL
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Found codec for Grey's Anatomy Thunderstruck
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Parsed D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06 into title: Grey's Anatomy, season: 19, episode: [6], type: episode, parsing_time: 0.029616117477416992, absolute_episode: [], quality: Unknown, total_time: 0.029616117477416992
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Matched release D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06 to a series in your database: Grey's Anatomy using guessit title: Grey's Anatomy
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] New guessit parse for item D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Trying guessit cache for item D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] 73762: Formatting pattern: Season %0S -> Season 19
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Found codec for Grey's Anatomy Thunderstruck
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Parsed D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06 into title: Grey's Anatomy, season: 19, episode: [6], type: episode, parsing_time: 0.015629291534423828, absolute_episode: [], quality: Unknown, total_time: 0.015629291534423828
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Matched release D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06 to a series in your database: Grey's Anatomy using guessit title: Grey's Anatomy
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] New guessit parse for item D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Trying guessit cache for item D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] 73762: Formatting pattern: %SN - S%0SE06  -> Grey's Anatomy - S19E06 
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Found codec for Grey's Anatomy Thunderstruck
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Parsed D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06 into title: Grey's Anatomy, season: 19, episode: [6], type: episode, parsing_time: 0.027644634246826172, absolute_episode: [], quality: Unknown, total_time: 0.027644634246826172
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Matched release D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06 to a series in your database: Grey's Anatomy using guessit title: Grey's Anatomy
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] New guessit parse for item D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Trying guessit cache for item D:\Media\TV\Grey's Anatomy\Season 19\Grey's Anatomy - S19E06
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Checking if we should stop searching for a better quality for for episode Greys.Anatomy.S19E06.720p.WEB.H264-CAKES
2023-02-15 21:11:24 WARNING	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Connect Error to NZBget: could not add Greys.Anatomy.S19E06.720p.WEB.H264-CAKES.nzb to the queue

Traceback (most recent call last):

  File "C:\MediaApps\Medusa\Medusa\medusa\clients\nzb\nzbget.py", line 149, in send_nzb

    nzbget_version_str = nzb_get_rpc.version()

                         ^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1122, in __call__

    return self.__send(self.__name, args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1464, in __request

    response = self.__transport.request(

               ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1166, in request

    return self.single_request(host, handler, request_body, verbose)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1178, in single_request

    http_conn = self.send_request(host, handler, request_body, verbose)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1291, in send_request

    self.send_content(connection, request_body)

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1321, in send_content

    connection.endheaders(request_body)

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 1277, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 1037, in _send_output

    self.send(msg)

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 975, in send

    self.connect()

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 1447, in connect

    super().connect()

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 941, in connect

    self.sock = self._create_connection(

                ^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\socket.py", line 827, in create_connection

    for res in getaddrinfo(host, port, 0, SOCK_STREAM):

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\socket.py", line 962, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

socket.gaierror: [Errno 11001] getaddrinfo failed
2023-02-15 21:11:24 DEBUG	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] URL: https://**********:**********@192.168.1.100%3A9092/xmlrpc
2023-02-15 21:11:24 INFO	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Sending NZB to NZBget
2023-02-15 21:11:24 WARNING	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Please check your NZBget host and port (if it is running). NZBget is not responding to this combination. Socket Error: [Errno 11001] getaddrinfo failed

Traceback (most recent call last):

  File "C:\MediaApps\Medusa\Medusa\medusa\clients\nzb\nzbget.py", line 34, in nzb_connection

    if nzb_get_rpc.writelog('INFO', 'Medusa connected to test connection.'):

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1122, in __call__

    return self.__send(self.__name, args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1464, in __request

    response = self.__transport.request(

               ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1166, in request

    return self.single_request(host, handler, request_body, verbose)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1178, in single_request

    http_conn = self.send_request(host, handler, request_body, verbose)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1291, in send_request

    self.send_content(connection, request_body)

  File "C:\MediaApps\Medusa\Python\Lib\xmlrpc\client.py", line 1321, in send_content

    connection.endheaders(request_body)

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 1277, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 1037, in _send_output

    self.send(msg)

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 975, in send

    self.connect()

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 1447, in connect

    super().connect()

  File "C:\MediaApps\Medusa\Python\Lib\http\client.py", line 941, in connect

    self.sock = self._create_connection(

                ^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\socket.py", line 827, in create_connection

    for res in getaddrinfo(host, port, 0, SOCK_STREAM):

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\MediaApps\Medusa\Python\Lib\socket.py", line 962, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

socket.gaierror: [Errno 11001] getaddrinfo failed
2023-02-15 21:11:24 INFO	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Downloading Greys.Anatomy.S19E06.720p.WEB.H264-CAKES with size: 766.24 MB from DOGnzb, through a SearchType.MANUAL_SEARCH search
2023-02-15 21:11:24 INFO	SNATCHQUEUE-SNATCH-73762 :: [b9292f9] Beginning to snatch release: Greys.Anatomy.S19E06.720p.WEB.H264-CAKES

```
</details>

**Comment by medariox** [comment]
@roscocheeta 
Can you update the branch and try again please?

**Comment by roscocheeta** [comment]
> @roscocheeta Can you update the branch and try again please?

Hi @medariox 

Looks to be working now. 

Will monitor a few more scheduled episodes and see if it's running smoothly. 

Thanks for looking into this.

**Comment by roscocheeta** [comment]
Hi @medariox 

Had a few more scheduled and manual snatches work successfully. 

Thankyou @medariox and @BenjV for taking time out of your day to review this bug.

**Comment by medariox** [comment]
@roscocheeta Thank you for testing. The PR has now been merged to develop and it will be included in the next release.
