### ISSUE TITLE
attempt to write a readonly database

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#11124]
`2023-02-12 11:19:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Hydra] :: [918cfe7] DB error: OperationalError('attempt to write a readonly database')
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database
2023-02-12 11:19:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Hydra] :: [918cfe7] DB error: attempt to write a readonly database
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database
2023-02-12 11:19:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Hydra] :: [918cfe7] DailySearchQueueItem Exception, error: OperationalError('attempt to write a readonly database')
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 295, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/app/medusa/medusa/search/core.py", line 536, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "/app/medusa/medusa/tv/cache.py", line 232, in update_cache
    self.updated = search_start_time
  File "/app/medusa/medusa/tv/cache.py", line 342, in updated
    self._set_time('last_update', value)
  File "/app/medusa/medusa/tv/cache.py", line 375, in _set_time
    cache_db_con.upsert(
  File "/app/medusa/medusa/db.py", line 355, in upsert
    self.action(query, list(itervalues(valueDict)) + list(itervalues(keyDict)))
  File "/app/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database
2023-02-12 09:16:21 ERROR    SEARCHQUEUE-BACKLOG-355567 :: [918cfe7] DB error: OperationalError('attempt to write a readonly database')
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database
2023-02-12 09:16:21 ERROR    SEARCHQUEUE-BACKLOG-355567 :: [918cfe7] DB error: attempt to write a readonly database
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database`

Suddenly Medusa stopped working, it cannot find any more episodes, and whenever I perform a search action it spams this in the error logs.

**Comment by BenjV** [comment]
It seems that the process does not have permissions on the database anymore.
What OS are you using?
Did you change anything?

**Comment by YoungC0DE** [comment]
You need to set permission for your database, if you are using Ubuntu then run this command:
`sudo chmod +777 yourDatabase.db`

Do this for the directory too

**Comment by Miicker** [comment]
> 

I am running Medusa in Docker on a Synology with DSM 7.1.1

I did a full reinstall of Medusa. It started working again for a few days, but now all of the suddon it stopped working. I get these errors everytime:
`2023-03-21 09:56:22 ERROR    APIv2-Thread_3 :: [918cfe7] DB error: OperationalError('attempt to write a readonly database')
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database
2023-03-21 09:56:22 ERROR    APIv2-Thread_3 :: [918cfe7] DB error: attempt to write a readonly database
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database
2023-03-21 09:56:22 ERROR    TORNADO :: [918cfe7] Uncaught exception in APIv2: OperationalError('attempt to write a readonly database')
Request: PATCH /api/v2/series/tvdb356202 (172.17.0.1)
With body:
{"config":{"aliases":[],"defaultEpisodeStatus":"Wanted","dvdOrder":false,"seasonFolders":true,"anime":false,"scene":false,"sports":false,"paused":false,"location":"/tv/For All Mankind","airByDate":false,"subtitlesEnabled":true,"release":{"requiredWords":[],"ignoredWords":[],"requiredWordsExclude":false,"ignoredWordsExclude":false},"qualities":{"preferred":[],"allowed":[32,128,512]},"airdateOffset":0,"showLists":["series"],"templates":false,"searchTemplates":[{"id":125,"title":"For All Mankind","template":"%SN S%0SE%0E","season":-1,"enabled":true,"default":true,"seasonSearch":false},{"id":126,"title":"For All Mankind","template":"%SN S%0S","season":-1,"enabled":true,"default":true,"seasonSearch":true}]},"language":"en"}
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/medusa/medusa/server/api/v2/series.py", line 176, in patch
    if patch_field and patch_field.patch(series, value):
  File "/app/medusa/medusa/server/api/v2/base.py", line 517, in patch
    setattr(target, self.attr, self.converter(value))
  File "/app/medusa/medusa/tv/base.py", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/app/medusa/medusa/tv/series.py", line 698, in aliases
    build_name_cache(self)
  File "/app/medusa/medusa/name_cache.py", line 117, in build_name_cache
    retrieve_exceptions()
  File "/app/medusa/medusa/scene_exceptions.py", line 257, in retrieve_exceptions
    custom_exceptions = _get_custom_exceptions(force) if exception_type in ['custom_exceptions', None] else defaultdict(dict)
  File "/app/medusa/medusa/scene_exceptions.py", line 344, in _get_custom_exceptions
    set_last_refresh('custom_exceptions')
  File "/app/medusa/medusa/scene_exceptions.py", line 115, in set_last_refresh
    cache_db_con.upsert(
  File "/app/medusa/medusa/db.py", line 355, in upsert
    self.action(query, list(itervalues(valueDict)) + list(itervalues(keyDict)))
  File "/app/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database`

**Comment by Miicker** [comment]
> You need to set permission for your database, if you are using Ubuntu then run this command: `sudo chmod +777 yourDatabase.db`
> 
> Do this for the directory too

Ok, so I did this, this solved my problems for two days, after those two days, the permissions of two files changed:
main.db = rw-r--r--
main.db-joernal = rw-r--r--

I changed it again to rwxrwxrwx for both files, that solved the issue again, but probably not for long. What could be causing this issue?
