### ISSUE TITLE
Seeing this error coming up in warnings each morning - IMDbPie error while loading show info: 403

### ISSUE THREAD

**Issue by jbman11** [pymedusa/Medusa#11137]
Medusa Info: | Branch: master Commit: b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e Version: 1.0.11 Database: 44.19
-- | --
Python Version: | 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
SSL Version: | OpenSSL 1.1.1n 15 Mar 2022
OS: | Linux-5.10.78-7-osmc-armv7l-with-glibc2.31
Locale: | en_US.UTF-8

Medusa Configuration
 Medusa Info:	Branch: [master](https://github.com/pymedusa/Medusa/tree/master) 
Commit: [b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e](https://github.com/pymedusa/Medusa/commit/b9292f9d786e90a3aa0ba9a9ebdfebe4e0c5297e) 
Version: [1.0.11](https://github.com/pymedusa/Medusa/releases/tag/v1.0.11) 
Database: 44.19
 Python Version:	3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
 SSL Version:	OpenSSL 1.1.1n 15 Mar 2022
 OS:	Linux-5.10.78-7-osmc-armv7l-with-glibc2.31
 Locale:	en_US.UTF-8

2023-02-21 05:27:31 WARNING  SHOWQUEUE-UPDATE :: [b9292f9] 156819: IMDbPie error while loading show info: 403 {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}
Traceback (most recent call last):
  File "/opt/medusa/medusa/tv/series.py", line 1704, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "/opt/medusa/ext/imdbpie/imdbpie.py", line 80, in get_title
    resource = self._get_resource(
  File "/opt/medusa/ext/imdbpie/imdbpie.py", line 299, in _get_resource
    return self._get(url=url)['resource']
  File "/opt/medusa/ext/imdbpie/imdbpie.py", line 315, in _get
    raise ImdbAPIError(msg)
imdbpie.exceptions.ImdbAPIError: 403 {"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}

**Comment by McEnnes** [comment]
Same Issue here.

**Comment by papampi** [comment]
Same issue here and the problem is it causes show queue update stop and not proceeding
