### ISSUE TITLE
Doesn't start anymore after latest update

### ISSUE THREAD

**Issue by MatthK** [pymedusa/Medusa#11164]
**Describe the bug**
Medusa told me that I am some comits behind, so I updated it as many times before. This time however Medusa didn't come back up again after the restart. I tried rebooting the whole machine, but that wouldn't help either.

```
matth@Ubuntu:~$ sudo service medusa status
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2023-03-08 22:53:27 HKT; 2s ago
 Main PID: 5315 (python3)
    Tasks: 1 (limit: 4542)
   CGroup: /system.slice/medusa.service
           └─5315 /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa

Mar 08 22:53:27 Ubuntu systemd[1]: medusa.service: Scheduled restart job, restart counter is at 100.
Mar 08 22:53:27 Ubuntu systemd[1]: Stopped Medusa Daemon.
Mar 08 22:53:27 Ubuntu systemd[1]: Started Medusa Daemon.
Mar 08 22:53:30 Ubuntu python3[5315]: /opt/medusa/lib/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.0
Mar 08 22:53:30 Ubuntu python3[5315]:   PkgResourcesDeprecationWarning,
Mar 08 22:53:30 Ubuntu python3[5315]: Traceback (most recent call last):
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/start.py", line 6, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa.__main__ import main
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/__main__.py", line 67, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa import (
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/providers/__init__.py", line 41, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     provider_names = import_providers(__name__)
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/providers/__init__.py", line 37, in import_providers
Mar 08 22:53:30 Ubuntu python3[5315]:     import_submodules(package_name)
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/providers/__init__.py", line 25, in import_submodules
Mar 08 22:53:30 Ubuntu python3[5315]:     module = importlib.import_module(full_name)
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
Mar 08 22:53:30 Ubuntu python3[5315]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/providers/generic_provider.py", line 18, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa import (
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/config.py", line 37, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa.updater.version_checker import CheckVersion
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/updater/version_checker.py", line 17, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa.updater.docker_updater import DockerUpdateManager
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/updater/docker_updater.py", line 9, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa.updater.source_updater import SourceUpdateManager
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/updater/source_updater.py", line 12, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from github import GithubException
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/ext/github/__init__.py", line 44, in <module>
```

```
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2023-03-08 22:53:27 HKT; 2s ago
 Main PID: 5315 (python3)
    Tasks: 1 (limit: 4542)
   CGroup: /system.slice/medusa.service
           └─5315 /usr/bin/python3 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa

Mar 08 22:53:27 Ubuntu systemd[1]: medusa.service: Scheduled restart job, restart counter is at 100.
Mar 08 22:53:27 Ubuntu systemd[1]: Stopped Medusa Daemon.
Mar 08 22:53:27 Ubuntu systemd[1]: Started Medusa Daemon.
Mar 08 22:53:30 Ubuntu python3[5315]: /opt/medusa/lib/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported
Mar 08 22:53:30 Ubuntu python3[5315]:   PkgResourcesDeprecationWarning,
Mar 08 22:53:30 Ubuntu python3[5315]: Traceback (most recent call last):
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/start.py", line 6, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa.__main__ import main
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/__main__.py", line 67, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa import (
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/providers/__init__.py", line 41, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     provider_names = import_providers(__name__)
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/providers/__init__.py", line 37, in import_providers
Mar 08 22:53:30 Ubuntu python3[5315]:     import_submodules(package_name)
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/providers/__init__.py", line 25, in import_submodules
Mar 08 22:53:30 Ubuntu python3[5315]:     module = importlib.import_module(full_name)
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
Mar 08 22:53:30 Ubuntu python3[5315]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/providers/generic_provider.py", line 18, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa import (
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/config.py", line 37, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa.updater.version_checker import CheckVersion
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/updater/version_checker.py", line 17, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa.updater.docker_updater import DockerUpdateManager
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/updater/docker_updater.py", line 9, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from medusa.updater.source_updater import SourceUpdateManager
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/medusa/updater/source_updater.py", line 12, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from github import GithubException
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/ext/github/__init__.py", line 44, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from github.MainClass import Github, GithubIntegration
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/ext/github/MainClass.py", line 57, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     import jwt
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/ext/jwt/__init__.py", line 1, in <module>
Mar 08 22:53:30 Ubuntu python3[5315]:     from .api_jwk import PyJWK, PyJWKSet
Mar 08 22:53:30 Ubuntu python3[5315]:   File "/opt/medusa/ext/jwt/api_jwk.py", line 1
Mar 08 22:53:30 Ubuntu python3[5315]:     from __future__ import annotations
Mar 08 22:53:30 Ubuntu python3[5315]:     ^
Mar 08 22:53:30 Ubuntu python3[5315]: SyntaxError: future feature annotations is not defined
~
```

This is the error message I get when I check for the `sudo service medusa status`.

I tried to run it manually, and get the following:

```
matth@Ubuntu:~$ sudo python3 /opt/medusa/start.py --datadir=/opt/medusa
/opt/medusa/lib/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/opt/medusa/medusa/providers/__init__.py", line 41, in <module>
    provider_names = import_providers(__name__)
  File "/opt/medusa/medusa/providers/__init__.py", line 37, in import_providers
    import_submodules(package_name)
  File "/opt/medusa/medusa/providers/__init__.py", line 25, in import_submodules
    module = importlib.import_module(full_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/medusa/medusa/providers/generic_provider.py", line 18, in <module>
    from medusa import (
  File "/opt/medusa/medusa/config.py", line 37, in <module>
    from medusa.updater.version_checker import CheckVersion
  File "/opt/medusa/medusa/updater/version_checker.py", line 17, in <module>
    from medusa.updater.docker_updater import DockerUpdateManager
  File "/opt/medusa/medusa/updater/docker_updater.py", line 9, in <module>
    from medusa.updater.source_updater import SourceUpdateManager
  File "/opt/medusa/medusa/updater/source_updater.py", line 12, in <module>
    from github import GithubException
  File "/opt/medusa/ext/github/__init__.py", line 44, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/opt/medusa/ext/github/MainClass.py", line 57, in <module>
    import jwt
  File "/opt/medusa/ext/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/opt/medusa/ext/jwt/api_jwk.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

Does this mean that Ubuntu 18.04 is no longer supported? How can I downgrade to the previous, working release?

**Medusa (please complete the following information):**
 - OS: Ubuntu 18.04.6 LTS
 - Branch: master
 - Commit: how to check when it's not running?
 - Python version: 3.6.9
 - Database version: how to check?

Any tips on how I can get that back working again?

**Comment by MatthK** [comment]
Got it back after I switched to Python version 3.7.16
