### ISSUE TITLE
Migrating to Docker

### ISSUE THREAD

**Issue by MatthK** [pymedusa/Medusa#11171]
**Describe the bug**
I have Medusa running on an old PC and I wanted to migrate this to a docker container. I can get the new Medusa up and running in Docker without problem. I then restore a backup from the old PC and restore this in the docker installation.
When I try to restart Medusa as suggested, it does not start up anymore but shows the following error messages in the log file:

```
2023-03-10 22:23:05 INFO     APIv2-Thread_1 :: [671a443] Restoring backup from location: /downloads/medusa-20230310210241.zip 
2023-03-10 22:23:13 INFO     APIv2-Thread_1 :: [671a443] Finished restore from location: /downloads/medusa-20230310210241.zip
2023-03-10 22:25:38 INFO     EVENT-QUEUE :: [671a443] Aborting all threads
2023-03-10 22:25:38 INFO     EVENT-QUEUE :: [671a443] Waiting for the DAILYSEARCHER thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the BACKLOG thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the SHOWUPDATER thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the EPISODEUPDATER thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the CHECKVERSION thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the SHOWQUEUE thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the SEARCHQUEUE thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the FORCEDSEARCHQUEUE thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the MANUALSNATCHQUEUE thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the TRAKTCHECKER thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the FINDPROPERS thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the FINDSUBTITLES thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the DOWNLOADHANDLER thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the POSTPROCESSOR thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the POSTPROCESSORQUEUE thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Waiting for the EVENT-QUEUE thread to exit
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Saving all shows to the database
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Saving config file to disk
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Shutting down Tornado
2023-03-10 22:25:39 INFO     EVENT-QUEUE :: [671a443] Restarting Medusa with ['/usr/local/bin/python', '/app/medusa/start.py', '--nolaunch', '--datadir', '/config']
Group already exists, re-using group abc
User already exists, re-using user abc
  User uid:    1000
  User gid:    1000
  -------------------------------------
  
Restore: restoring DB and config.ini SUCCESSFUL!
Traceback (most recent call last):
  File "/app/medusa/start.py", line 9, in <module>
    main()
  File "/app/medusa/medusa/__main__.py", line 2398, in main
    application.start(sys.argv[1:])
  File "/app/medusa/medusa/__main__.py", line 350, in start
    self.initialize(console_logging=self.console_logging)
  File "/app/medusa/medusa/__main__.py", line 480, in initialize
    if not helpers.make_dir(app.LOG_DIR):
  File "/app/medusa/medusa/helpers/__init__.py", line 182, in make_dir
    if not os.path.isdir(path):
  File "/usr/local/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Group already exists, re-using group abc
User already exists, re-using user abc
  User uid:    1000
  User gid:    1000
  -------------------------------------
  
ERROR:medusa.exception_handler:Environment error: [Errno 2] No such file or directory: '/config/restore/main.db'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/config/restore/main.db' -> '/config/main.db'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/medusa/__main__.py", line 2355, in restore_db
    shutil.move(src_file, dst_file)
  File "/usr/local/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/local/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/config/restore/main.db'
Restore: restoring DB and config.ini FAILED!
Traceback (most recent call last):
  File "/app/medusa/start.py", line 9, in <module>
    main()
  File "/app/medusa/medusa/__main__.py", line 2398, in main
    application.start(sys.argv[1:])
  File "/app/medusa/medusa/__main__.py", line 350, in start
    self.initialize(console_logging=self.console_logging)
  File "/app/medusa/medusa/__main__.py", line 480, in initialize
    if not helpers.make_dir(app.LOG_DIR):
  File "/app/medusa/medusa/helpers/__init__.py", line 182, in make_dir
    if not os.path.isdir(path):
  File "/usr/local/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Both the old version and the new docker setup are on version 1.0.12 with DB version 44.19. 

How can I get my installation over to the new setup?

**Comment by the-jeffski** [comment]
How is your docker-compose set up - have you set a permanent location for the data files as the above shows its not finding them.

**Comment by MatthK** [comment]
I'm not using docker-compose, but here is the docker command I am using to start the container:

```
docker run -d \
  --name=Medusa \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/Hong_Kong \
  -p 8081:8081 \
  -v /home/matth/Medusa:/config \
  -v /mnt/shares/movies/tSickrage:/downloads \
  -v /mnt/shares/movies/TV\ Shows:/tv \
  --restart unless-stopped \
  pymedusa/medusa
```

I ran a backup on the old system. I then used that file to run a restore in the new setup. The restore completed successfully and it said it needs to restart Medusa to complete the restore. When I restart Medusa (from the Webinterface, not restarting the container), it never comes back up again and I get the above messages in the container log.

Below is the directory before the restore (completely empty), after the restore finished successfully (main.db exists in the restore directory), and then again after I tried the restart (main.db disappears). 

```
matth@vs01:~/Medusa$ ls
matth@vs01:~/Medusa$ ls
Logs              failed.db          main.db.v44.10  main.db.v44.16  main.db.v44.5   restore
cache             failed.db.v2.None  main.db.v44.11  main.db.v44.17  main.db.v44.6
cache.db          main.db            main.db.v44.12  main.db.v44.18  main.db.v44.7
cache.db.v1.None  main.db.v42        main.db.v44.13  main.db.v44.2   main.db.v44.8
cache.db.v2.None  main.db.v43.1      main.db.v44.14  main.db.v44.3   main.db.v44.9
config.ini        main.db.v44.1      main.db.v44.15  main.db.v44.4   recommended.db
matth@vs01:~/Medusa$ cd restore/
matth@vs01:~/Medusa/restore$ ls
cache  cache.db  config.ini  failed.db  main.db  recommended.db
matth@vs01:~/Medusa/restore$ ls
cache
matth@vs01:~/Medusa/restore$
matth@vs01:~/Medusa/restore$ cd ..
matth@vs01:~/Medusa$ ls
Logs                            main.db.bak-20230411_111938  main.db.v44.18
cache                           main.db.v42                  main.db.v44.2
cache.db                        main.db.v43.1                main.db.v44.3
cache.db.bak-20230411_111933    main.db.v44.1                main.db.v44.4
cache.db.v1.None                main.db.v44.10               main.db.v44.5
cache.db.v2.None                main.db.v44.11               main.db.v44.6
config.ini                      main.db.v44.12               main.db.v44.7
config.ini.bak-20230411_111933  main.db.v44.13               main.db.v44.8
failed.db                       main.db.v44.14               main.db.v44.9
failed.db.bak-20230411_111933   main.db.v44.15               recommended.db
failed.db.v2.None               main.db.v44.16               recommended.db.bak-20230411_111933
main.db.bak-20230411_111933     main.db.v44.17               restore
matth@vs01:~/Medusa$
```

So something during the restart seems to be not working as it should.

**Comment by the-jeffski** [comment]
Odd. Config is like mine. (Why is there a space in the path for /tv ? 

Have you tried just cloning over the config folder completely and then starting the app - its how I migrated rather than use the backup.

**Comment by MatthK** [comment]
Ok, so I tried to copy over the whole /opt/medusa content to the config folder of the docker container. That didn't work either. When I restart the container, I get the following log error message:

```
Traceback (most recent call last):
  File "/app/medusa/start.py", line 9, in <module>
    main()
  File "/app/medusa/medusa/__main__.py", line 2398, in main
    application.start(sys.argv[1:])
  File "/app/medusa/medusa/__main__.py", line 350, in start
    self.initialize(console_logging=self.console_logging)
  File "/app/medusa/medusa/__main__.py", line 480, in initialize
    if not helpers.make_dir(app.LOG_DIR):
  File "/app/medusa/medusa/helpers/__init__.py", line 182, in make_dir
    if not os.path.isdir(path):
  File "/usr/local/lib/python3.10/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Group already exists, re-using group abc
User already exists, re-using user abc
  User uid:    1000
  User gid:    1000
  -------------------------------------
```

Not quite sure what that refers to, but possibly cos some directory does not exist in the same location?

And my directory with the TV Shows has a space in it. It is called `TV Shows`.

**Comment by MatthK** [comment]
After some more fiddling and trying, I did manage to get it going. Copying the whole directory over from the original site and then manually updating the config.ini eventually did the trick.

Thanks for your help.
