### ISSUE TITLE
WARNING  SHOWQUEUE-SEASON-UPDATE :: [9a36461] Unhashable type encountered. Please report this warning to the developers.

### ISSUE THREAD

**Issue by dug-g** [pymedusa/Medusa#11199]
**### **Describe the bug**
warning message generated daily at 4:26am

**To Reproduce**
1. Leave PyMedusa running it it's docker container on my synology system
2. wait until 4:26am
3. warning is generated

**Expected behavior**
should be no warning. I report it here as requested.

**Medusa (please complete the following information):**
 - OS: [Synology 6.x, Docker container, both most recent updates]
 - Branch: [master]
 - Commit: [9a364616d1bc7bed025f3c08270ac993cfa0c046](https://github.com/pymedusa/Medusa/commit/9a364616d1bc7bed025f3c08270ac993cfa0c046]
 - Python version: [unknown, in docker ]
 - Database version: []

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug

2023-04-01 04:26:56 WARNING  SHOWQUEUE-SEASON-UPDATE :: [9a36461] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/app/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable**

**Comment by dug-g** [comment]
just fyi! thanks for your work.

**Comment by dug-g** [comment]
I haven't seen this repeated for some days now, so I'm closing it.
