### ISSUE TITLE
[APP SUBMITTED]: dbm.error: db type is dbm.gnu, but the module is not available

### ISSUE THREAD

**Issue by fexofenadine** [pymedusa/Medusa#11192]
### INFO
**Python Version**: `3.10.10 (main, Feb  9 2023, 02:08:14) [GCC 12.2.1 20220924]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/fexofenadine/9659fef277832da738dc1535e25e4d48
### ERROR
<pre>
2023-03-23 17:30:08 ERROR    Thread_0 :: [baad1e5] Exception generated: db type is dbm.gnu, but the module is not available
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/server/web/home/handler.py#L1015">medusa/server/web/home/handler.py</a>", line 1015, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</app/medusa/ext/decorator.py:decorator-gen-21>", line 2, in get_release_groups_for_anime
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/dogpile/cache/region.py#L1577">ext/dogpile/cache/region.py</a>", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/dogpile/cache/region.py#L1042">ext/dogpile/cache/region.py</a>", line 1042, in get_or_create
    with Lock(
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/dogpile/lock.py#L185">ext/dogpile/lock.py</a>", line 185, in __enter__
    return self._enter()
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/dogpile/lock.py#L87">ext/dogpile/lock.py</a>", line 87, in _enter
    value = value_fn()
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/dogpile/cache/region.py#L977">ext/dogpile/cache/region.py</a>", line 977, in get_value
    value = self._get_from_backend(key)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/dogpile/cache/region.py#L1265">ext/dogpile/cache/region.py</a>", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/dogpile/cache/backends/file.py#L217">ext/dogpile/cache/backends/file.py</a>", line 217, in get_serialized
    with self._dbm_file(False) as dbm_obj:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/dogpile/cache/backends/file.py#L213">ext/dogpile/cache/backends/file.py</a>", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
  File "/usr/lib/python3.10/dbm/__init__.py", line 91, in open
    raise error[0]("db type is {0}, but the module is not "
dbm.error: db type is dbm.gnu, but the module is not available
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Try this: https://github.com/pymedusa/Medusa/issues/6804#issuecomment-570688415

**Comment by fexofenadine** [comment]
thanks :)

**Comment by Grievous1900** [comment]
### INFO
**Python Version**: `3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924]`
**Operating System**: `Linux-5.15.0-78-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/Grievous1900/132d6f597646150ce72f31e58e00be41
### ERROR
<pre>
2023-08-01 11:29:37 ERROR    Thread_0 :: [] Exception generated: db type is dbm.gnu, but the module is not available
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/web/home/handler.py", line 1015, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "</app/medusa/ext/decorator.py:decorator-gen-21>", line 2, in get_release_groups_for_anime
  File "/app/medusa/ext/dogpile/cache/region.py", line 1593, in get_or_create_for_user_func
    return self.get_or_create(
           ^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/dogpile/cache/region.py", line 1053, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
           ^^^^^^^^^^^^^
  File "/app/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
            ^^^^^^^^^^
  File "/app/medusa/ext/dogpile/cache/region.py", line 988, in get_value
    value = self._get_from_backend(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/dogpile/cache/region.py", line 1281, in _get_from_backend
    self.backend.get_serialized(key)
  File "/app/medusa/ext/dogpile/cache/backends/file.py", line 217, in get_serialized
    with self._dbm_file(False) as dbm_obj:
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/app/medusa/ext/dogpile/cache/backends/file.py", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dbm/__init__.py", line 91, in open
    raise error[0]("db type is {0}, but the module is not "
dbm.error: db type is dbm.gnu, but the module is not available
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fexofenadine** [comment]
https://github.com/pymedusa/Medusa/issues/11192#issuecomment-1480861771 worked for me
