### ISSUE TITLE
TVDB API connection fails

### ISSUE THREAD

**Issue by dbdavid44** [pymedusa/Medusa#11214]
Looks like the indexer TVDB stopped working for me. The API connection fails every time there it looks for an update or I try to search for a new show.

Was there any recent change with the TVDB API?

Here is the log:
```
2023-05-01 00:19:12 WARNING  APIv2-Thread_0 :: [6b37ad0] Could not connect to TheTvdb.com, with reason: IndexerUnavailable('RequestException\nMissing response')
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/ext/tvdbapiv2/rest.py", line 55, in request
    raise RequestException('Missing response')
requests.exceptions.RequestException: Missing response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/medusa/indexers/tvdbv2/api.py", line 136, in _show_search
    results = self.config['session'].search_api.search_series_get(name=show, accept_language=request_language)
  File "/volume1/@appstore/medusa/src/ext/tvdbapiv2/apis/search_api.py", line 117, in search_series_get
    response = self.api_client.call_api(resource_path, method,
  File "/volume1/@appstore/medusa/src/ext/tvdbapiv2/api_client.py", line 292, in call_api
    return self.__call_api(resource_path, method,
  File "/volume1/@appstore/medusa/src/ext/tvdbapiv2/api_client.py", line 119, in __call_api
    response_data = self.request(method, url,
  File "/volume1/@appstore/medusa/src/ext/tvdbapiv2/api_client.py", line 313, in request
    return self.rest_client.get(url,
  File "/volume1/@appstore/medusa/src/ext/tvdbapiv2/rest.py", line 71, in get
    return self.request("GET", url,
  File "/volume1/@appstore/medusa/src/ext/tvdbapiv2/rest.py", line 66, in request
    raise ApiException(status=status, reason=msg)
tvdbapiv2.exceptions.ApiException: (0)
Reason: RequestException
Missing response


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/medusa/indexers/tvdbv2/fallback.py", line 111, in __call__
    return self.func(*args, **kwargs)
  File "/volume1/@appstore/medusa/src/medusa/indexers/tvdbv2/api.py", line 162, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/volume1/@appstore/medusa/src/medusa/indexers/tvdbv2/api.py", line 148, in _show_search
    raise IndexerUnavailable(error.reason)
medusa.indexers.exceptions.IndexerUnavailable: RequestException
Missing response
2023-05-01 00:19:12 WARNING  APIv2-Thread_0 :: [6b37ad0] Enabling Plex fallback as TheTvdb.com API is having some connectivity issues
```

**Comment by BenjV** [comment]
No problems here with Tvdb.
So maybe a hickup on their servers or a hickup in your internet connection?

**Comment by dbdavid44** [comment]
Thanks for the reply. Installed Medusa again and problem solved. I guess it was my setup.
