### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Medusa\\Logs\\application.log.6'

### ISSUE THREAD

**Issue by Bilbo** [pymedusa/Medusa#11223]
### INFO
**Python Version**: `3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-05-17 16:07:27 ERROR    TORNADO :: [6b37ad0] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/log?level=INFO&thread=&period=one_day&query=&limit=1000 (127.0.0.1)
Traceback (most recent call last):
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/ext/tornado/web.py#L1704">ext\tornado\web.py</a>", line 1704, in _execute
    result = await result
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/ext/tornado/gen.py#L769">ext\tornado\gen.py</a>", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/server/api/v2/base.py#L64">medusa\server\api\v2\base.py</a>", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/ext/tornado/gen.py#L762">ext\tornado\gen.py</a>", line 762, in run
    value = future.result()
  File "C:\Python3\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/server/api/v2/log.py#L144">medusa\server\api\v2\log.py</a>", line 144, in get
    return self._paginate(data_generator=data_generator)
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/server/api/v2/base.py#L343">medusa\server\api\v2\base.py</a>", line 343, in _paginate
    results = list(data_generator())[:arg_limit]
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/server/api/v2/log.py#L140">medusa\server\api\v2\log.py</a>", line 140, in data_generator
    for line in read_loglines(**reader_kwargs):
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/logger/__init__.py#L166">medusa\logger\__init__.py</a>", line 166, in read_loglines
    for line in reverse_readlines(f):
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/logger/__init__.py#L259">medusa\logger\__init__.py</a>", line 259, in reverse_readlines
    for block in block_generator(file_path, size=block_size):
  File "C:\Program Files\Medusa\<a href="../blob/6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476/medusa/logger/__init__.py#L225">medusa\logger\__init__.py</a>", line 225, in blocks_r
    with io.open(file_path, 'rb') as file_obj:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Medusa\\Logs\\application.log.6'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bilbo** [comment]
### INFO
**Python Version**: `3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e98773f869de7c132b45fa8c76fa66cfc64d1e7b
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-06-01 23:31:30 ERROR    TORNADO :: [e98773f] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/log?level=INFO&thread=&period=one_day&query=&limit=1000 (127.0.0.1)
Traceback (most recent call last):
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/tornado/web.py#L1704">ext\tornado\web.py</a>", line 1704, in _execute
    result = await result
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/tornado/gen.py#L769">ext\tornado\gen.py</a>", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/server/api/v2/base.py#L64">medusa\server\api\v2\base.py</a>", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/tornado/gen.py#L762">ext\tornado\gen.py</a>", line 762, in run
    value = future.result()
  File "C:\Python3\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/server/api/v2/log.py#L144">medusa\server\api\v2\log.py</a>", line 144, in get
    return self._paginate(data_generator=data_generator)
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/server/api/v2/base.py#L343">medusa\server\api\v2\base.py</a>", line 343, in _paginate
    results = list(data_generator())[:arg_limit]
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/server/api/v2/log.py#L140">medusa\server\api\v2\log.py</a>", line 140, in data_generator
    for line in read_loglines(**reader_kwargs):
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/logger/__init__.py#L166">medusa\logger\__init__.py</a>", line 166, in read_loglines
    for line in reverse_readlines(f):
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/logger/__init__.py#L259">medusa\logger\__init__.py</a>", line 259, in reverse_readlines
    for block in block_generator(file_path, size=block_size):
  File "C:\Program Files\Medusa\<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/logger/__init__.py#L225">medusa\logger\__init__.py</a>", line 225, in blocks_r
    with io.open(file_path, 'rb') as file_obj:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Medusa\\Logs\\application.log.6'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Check your permissions.
