### ISSUE TITLE
Unhashable type encountered

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#11224]
**Describe the bug**
it just said to report the warning..

**Medusa (please complete the following information):**
Medusa Info:	
Branch: develop
Commit: 7559c509940a22fc9689d24ee6b93559c65ca60f
Version: 1.0.13
Database: 44.19
 Python Version:	3.11.3 (main, Apr 7 2023, 19:30:05) [Clang 13.0.0 (clang-1300.0.29.30)]
 SSL Version:	OpenSSL 1.1.1t 7 Feb 2023
 OS:	macOS-11.7.6-x86_64-i386-64bit
 Locale:	Unknown.UTF-8
 Timezone:	AEST

**Debug logs (at least 50 lines):**
```
2023-05-16 14:10:41 WARNING  APIv2-Thread_3 :: [7559c50] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/Users/ADMIN/Apps/Medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable
2023-05-16 09:31:13 WARNING  DAILYSEARCHER :: [7559c50] Manual search is running. Unable to start Daily search
```

I do not have the log file as I just noticed this & my logs don't go back that far.

**Comment by MrFearmanDK** [comment]
I am getting the following error regulary lately:

Medusa Info: 
Branch: master
Commit: 6b37ad0ae6dfc3c2b102e2d9a377ced1fc849476
Version: 1.0.16
Database: 44.19
Python Version: | 3.10.8 (main, Oct 13 2022, 23:33:11) [GCC 10.3.1 20211027]
SSL Version: | OpenSSL 1.1.1q 5 Jul 2022
OS: | Linux-4.4.180+-x86_64-with
Locale: | en_US.UTF-8
Timezone: | CEST

2023-05-28 22:18:57 WARNING	FINDSUBTITLES :: [6b37ad0] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/app/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
  File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable
