### ISSUE TITLE
Show is missing from show list but get error messages it can't find the path..

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#11347]
**Describe the bug**

This is an old show that has been listed for years "O:\series\Enigma Station X (1999)"
I get errors for it, but can no longer find it in the show listing.
The files are in the correct place.
I was going to remove the show and reload it but it's not in the list.
If I try to add an existing show it doesn't show in the list as it's already available.

Only thing I haven't tried is to add the show again as a new show, not sure if that would really mess things up.

I need to know the best solution to fix this problem. 
I'm reluctant to just try anything because the database has;

250 Shows (11 Active) | 19472 [+1572](http://192.168.##.##:####/manage/episodeStatuses?status=2) Snatched / 34028 Episodes Downloaded (57.2%) | Daily Search: 0:01:23 | Backlog Search: 0:01:42
Branch: master | Now: 2023-06-16 10:26:43 AM

I am not sure how long it has been like this, this database has only older shows in it  <2000

**To Reproduce**

**Expected behavior**
That the show was there as before..

**Screenshots**

**Medusa (please complete the following information):**
<html><body>
<h1 class="header">Medusa Configuration</h1> <div data-v-0e222bd8="" id="config-content">

Medusa Info: | Branch:                 master                  Commit:                 e98773f869de7c132b45fa8c76fa66cfc64d1e7b                  Version:                 1.0.16                  Database:                 44.19
-- | --
Python Version: | 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
SSL Version: | OpenSSL 1.1.1d  10 Sep 2019
OS: | Windows-10-10.0.22000-SP0
Locale: | en_US.cp65001
Timezone: | Eastern Daylight Time
  |  
  |  
User: | plex
Program Folder: | C:\Medusa_1900
Config File: | C:\Medusa_1900\Data\config.ini
Database File: | C:\Medusa_1900\Data\main.db
Cache Folder: | C:\Medusa_1900\Data\cache
Log Folder: | C:\Medusa_1900\Data\Logs
Arguments: | --nolaunch --port 8081 --datadir=C:\Medusa_1900\Data

</div>
</body>
</html>Medusa Configuration
Medusa Info: 	Branch: [master](https://github.com/pymedusa/Medusa/tree/master)
Commit: [e98773f869de7c132b45fa8c76fa66cfc64d1e7b](https://github.com/pymedusa/Medusa/commit/e98773f869de7c132b45fa8c76fa66cfc64d1e7b)
Version: [1.0.16](https://github.com/pymedusa/Medusa/releases/tag/v1.0.16)
Database: 44.19
Python Version:	3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)]
SSL Version:	OpenSSL 1.1.1d 10 Sep 2019
OS:	Windows-10-10.0.22000-SP0
Locale:	en_US.cp65001
Timezone:	Eastern Daylight Time
 	 
 	 
User:	plex
Program Folder:	C:\Medusa_1900
Config File:	C:\Medusa_1900\Data\config.ini
Database File:	C:\Medusa_1900\Data\main.db
Cache Folder:	C:\Medusa_1900\Data\cache
Log Folder:	C:\Medusa_1900\Data\Logs
Arguments:	

--nolaunch --port 8081 --datadir=C:\Medusa_1900\Data
**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2023-06-16 10:19:04 WARNING  SHOWQUEUE-CHANGE-INDEXER :: [e98773f] Aspect ratio (0.8306159420289855) does not match any known types.
2023-06-16 10:19:04 WARNING  SHOWQUEUE-CHANGE-INDEXER :: [e98773f] Unable to determine image type for O:\series\Enigma Station X (1999)\folder.jpg
2023-06-16 09:47:28 WARNING  SHOWQUEUE-REFRESH :: [e98773f] 2190: Show directory doesn't exist, skipping NFO generation
2023-06-16 09:47:28 WARNING  SHOWQUEUE-REFRESH :: [e98773f] Path does not exist. Unable to search it for images.
Traceback (most recent call last):
  File "C:\Medusa_1900\medusa\image_cache.py", line 308, in fill_cache
    path = provider.get_image_path(series_obj, img_type)
  File "C:\Medusa_1900\medusa\metadata\generic.py", line 194, in get_image_path
    return banner_path[image_type](show_obj)
  File "C:\Medusa_1900\medusa\metadata\generic.py", line 184, in get_banner_path
    return os.path.join(show_obj.validate_location, self.banner_name)
  File "C:\Medusa_1900\medusa\tv\series.py", line 423, in validate_location
    raise ShowDirectoryNotFoundException('Show folder does not exist.')
medusa.helper.exceptions.ShowDirectoryNotFoundException: Show folder does not exist.
2023-06-16 09:47:26 WARNING  SHOWQUEUE-REFRESH :: [e98773f] Unable to scan video: . Error: ValueError('Path does not exist')
Traceback (most recent call last):
  File "C:\Medusa_1900\medusa\subtitles.py", line 731, in get_video
    video = scan_video(video_path)
  File "C:\Medusa_1900\ext\subliminal\core.py", line 362, in scan_video
    raise ValueError('Path does not exist')
ValueError: Path does not exist
```
</details>

**Additional context**

**Comment by nydave69** [comment]
Found one of the problems so far...
When updating to the new indexer, if the new indexer has a different show year (i save mine as show name (yesr) ) The show is updated with the new year but still points to the old folder (good), but at some point that gets changed to the new year and creates the folder with the new year, but nothing is in it. and the show then goes missing from the data base. history list the episodes show name as missing, You have to dig to find what show is missing. you can't add the show back because it is already added, can't delete because you can't select it...   Wound up with 30+ show going from the old TVDB to TMDB (plex uses), some shows are not on TMDB has to use TVmaze..  

wound up deleting everything but the config file, Installing the latest version (then) 
<html><body>


Medusa Info: | Branch:                 master                  Commit:                 3d656652ab277e47689483912ed7fc443e7023e8                  Version:                 1.0.3                  Database:                 44.19
-- | --



</body>
</html>Medusa Info: 	Branch: [master](https://github.com/pymedusa/Medusa/tree/master)
Commit: [3d656652ab277e47689483912ed7fc443e7023e8](https://github.com/pymedusa/Medusa/commit/3d656652ab277e47689483912ed7fc443e7023e8)
Version: [1.0.3](https://github.com/pymedusa/Medusa/releases/tag/v1.0.3)
Database: 44.19

But it hasn't update since and manual update says I'm at the current release.

My shows are saved as;
Battlestar Galactica (2004) (S02E01) (2005-07-15) [eng] (720p-x264 BluRay AAC-2ch) Scattered

since medusa can't do renames as above (note I add BluRay to keep Meduse from constantly searching for better media otherwise it wouldn't be there)
I request a rename tag as %FN file name, just use the existing file name..

Then I can remove the additional process to rename the files.

thanks for reading
