### ISSUE TITLE
[APP SUBMITTED]: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=None)

### ISSUE THREAD

**Issue by steinilux** [pymedusa/Medusa#11340]
### INFO
**Python Version**: `3.7.12 (default, Oct 22 2021, 20:32:25) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-2.6.32.12-ppc-with-glibc2.0`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e98773f869de7c132b45fa8c76fa66cfc64d1e7b
**Link to Log**: https://gist.github.com/steinilux/5d80f8e92555af93bb783a755e8b25f9
### ERROR
<pre>
2023-06-06 01:09:42 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [e98773f] Could not connect to Trakt service: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=None)
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L466">ext/urllib3/connectionpool.py</a>", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L461">ext/urllib3/connectionpool.py</a>", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/var/packages/python3/target/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/var/packages/python3/target/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/var/packages/python3/target/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/var/packages/python3/target/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/var/packages/python3/target/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/var/packages/python3/target/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/requests/adapters.py#L497">ext/requests/adapters.py</a>", line 497, in send
    chunked=chunked,
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L799">ext/urllib3/connectionpool.py</a>", line 799, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/util/retry.py#L550">ext/urllib3/util/retry.py</a>", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/packages/six.py#L770">ext/urllib3/packages/six.py</a>", line 770, in reraise
    raise value
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L721">ext/urllib3/connectionpool.py</a>", line 721, in urlopen
    chunked=chunked,
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L468">ext/urllib3/connectionpool.py</a>", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L375">ext/urllib3/connectionpool.py</a>", line 375, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/show/recommendations/trakt.py#L145">medusa/show/recommendations/trakt.py</a>", line 145, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/show/recommendations/trakt.py#L128">medusa/show/recommendations/trakt.py</a>", line 128, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/wrapt/wrappers.py#L579">ext/wrapt/wrappers.py</a>", line 579, in __call__
    args, kwargs)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/deprecated/classic.py#L186">ext/deprecated/classic.py</a>", line 186, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/trakt/core.py#L578">ext/trakt/core.py</a>", line 578, in inner
    json_data = self._handle_request('get', url)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/trakt/core.py#L544">ext/trakt/core.py</a>", line 544, in _handle_request
    params=data)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/requests/sessions.py#L589">ext/requests/sessions.py</a>", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/requests/sessions.py#L703">ext/requests/sessions.py</a>", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/requests/adapters.py#L532">ext/requests/adapters.py</a>", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=None)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by steinilux** [comment]
### INFO
**Python Version**: `3.7.12 (default, Oct 22 2021, 20:32:25) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-2.6.32.12-ppc-with-glibc2.0`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e98773f869de7c132b45fa8c76fa66cfc64d1e7b
**Link to Log**: **No Log available**
### ERROR
<pre>
2023-06-09 00:29:15 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [e98773f] Could not connect to Trakt service: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=None)
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L466">ext/urllib3/connectionpool.py</a>", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L461">ext/urllib3/connectionpool.py</a>", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/var/packages/python3/target/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/var/packages/python3/target/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/var/packages/python3/target/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/var/packages/python3/target/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/var/packages/python3/target/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/var/packages/python3/target/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/requests/adapters.py#L497">ext/requests/adapters.py</a>", line 497, in send
    chunked=chunked,
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L799">ext/urllib3/connectionpool.py</a>", line 799, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/util/retry.py#L550">ext/urllib3/util/retry.py</a>", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/packages/six.py#L770">ext/urllib3/packages/six.py</a>", line 770, in reraise
    raise value
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L721">ext/urllib3/connectionpool.py</a>", line 721, in urlopen
    chunked=chunked,
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L468">ext/urllib3/connectionpool.py</a>", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/urllib3/connectionpool.py#L375">ext/urllib3/connectionpool.py</a>", line 375, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/show/recommendations/trakt.py#L173">medusa/show/recommendations/trakt.py</a>", line 173, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "</volume1/@appstore/medusa/var/src/ext/decorator.py:decorator-gen-56>", line 2, in _create_recommended_show
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/dogpile/cache/region.py#L1594">ext/dogpile/cache/region.py</a>", line 1594, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/dogpile/cache/region.py#L1058">ext/dogpile/cache/region.py</a>", line 1058, in get_or_create
    async_creator,
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/dogpile/lock.py#L185">ext/dogpile/lock.py</a>", line 185, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/dogpile/lock.py#L94">ext/dogpile/lock.py</a>", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/dogpile/lock.py#L178">ext/dogpile/lock.py</a>", line 178, in _enter_create
    return self.creator()
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/dogpile/cache/region.py#L1007">ext/dogpile/cache/region.py</a>", line 1007, in gen_value
    *creator_args[0], **creator_args[1]
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/medusa/show/recommendations/trakt.py#L76">medusa/show/recommendations/trakt.py</a>", line 76, in _create_recommended_show
    **{'rating': show.ratings['rating'],
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/trakt/core.py#L578">ext/trakt/core.py</a>", line 578, in inner
    json_data = self._handle_request('get', url)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/trakt/core.py#L544">ext/trakt/core.py</a>", line 544, in _handle_request
    params=data)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/requests/sessions.py#L589">ext/requests/sessions.py</a>", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/requests/sessions.py#L703">ext/requests/sessions.py</a>", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/e98773f869de7c132b45fa8c76fa66cfc64d1e7b/ext/requests/adapters.py#L532">ext/requests/adapters.py</a>", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=None)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
