### ISSUE TITLE
History Broken since Version 1.0.16

### ISSUE THREAD

**Issue by maticks81** [pymedusa/Medusa#11434]
When clicking next on the history pages does nothing can only see the 50 on screen with Detailed only. Changing to Compact has a completely blank screen.

Log errors are as per below. Seen a few Docker patches come out but still broken for over a month can't see anyone reporting the issue.
Could be a local problem not sure, I tried deleting cache files but that didn't help. any suggestions?

2023-08-04 07:25:29 ERROR	TORNADO :: Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /api/v2/history?page=1&limit=50&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (10.0.10.15)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
            ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
2023-08-04 07:25:29 ERROR	TORNADO :: Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /api/v2/history?page=1&limit=50&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (10.0.10.15)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
            ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
2023-08-04 07:23:58 ERROR	TORNADO :: Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /api/v2/history?page=1&limit=50&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (10.0.10.15)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
            ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
2023-08-04 07:23:57 ERROR	TORNADO :: Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /api/v2/history?page=2&limit=50&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (10.0.10.15)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
            ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
2023-08-04 07:23:56 ERROR	TORNADO :: Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /api/v2/history?page=1&limit=50&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (10.0.10.15)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
            ^^^^^^^^^^^

**Comment by medariox** [comment]
Delete the browser cookies for Medusa.

**Comment by maticks81** [comment]
I have cleared the cookies and restarted Chrome but it still errors for me.

**Comment by medariox** [comment]
Does it work if you use incognito mode in Chrome?

**Comment by maticks81** [comment]
interesting.. it works in incognito but not after i have cleared the cache, cookies and data in chrome.

**Comment by maticks81** [comment]
that looks like it's fixed it loading via incognito has now dropped the problem in the browser normally thank you :)
