### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Grievous1900** [pymedusa/Medusa#11431]
### INFO
**Python Version**: `3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924]`
**Operating System**: `Linux-5.15.0-78-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/Grievous1900/c9adcc646bf4f305f4e6a229b7c1e301
### ERROR
<pre>
2023-08-01 11:19:22 ERROR    SHOWQUEUE-REFRESH :: [] 326109: Error while refreshing show Made in Abyss. Error: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/medusa/medusa/queues/show_queue.py", line 758, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 2117, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 1136, in load_episodes_from_dir
    parse_result = NameParser(series=self, try_indexers=True).parse(ep_file_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/name_parser/parser.py", line 451, in parse
    result = self._parse_string(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/name_parser/parser.py", line 374, in _parse_string
    new_episode_numbers, new_season_numbers, new_absolute_numbers = self._parse_series(result)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/name_parser/parser.py", line 284, in _parse_series
    ex_season = scene_exceptions.get_season_from_name(result.series, result.series_name) or result.season_number
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/scene_exceptions.py", line 168, in get_season_from_name
    if exception.title.lower() == exception_name.lower():
                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fexofenadine** [comment]
### INFO
**Python Version**: `3.11.6 (main, Oct 13 2023, 15:52:55) [GCC 13.1.1 20230722]`
**Operating System**: `Linux-4.4.302+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-01-16 03:35:51 ERROR    SHOWQUEUE-REFRESH :: [baad1e5] 5: Error while refreshing show True Detective. Error: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/queues/show_queue.py#L758">medusa/queues/show_queue.py</a>", line 758, in run
    self.show.refresh_dir()
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/tv/series.py#L2117">medusa/tv/series.py</a>", line 2117, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/tv/series.py#L1136">medusa/tv/series.py</a>", line 1136, in load_episodes_from_dir
    parse_result = NameParser(series=self, try_indexers=True).parse(ep_file_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/name_parser/parser.py#L451">medusa/name_parser/parser.py</a>", line 451, in parse
    result = self._parse_string(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/name_parser/parser.py#L374">medusa/name_parser/parser.py</a>", line 374, in _parse_string
    new_episode_numbers, new_season_numbers, new_absolute_numbers = self._parse_series(result)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/name_parser/parser.py#L284">medusa/name_parser/parser.py</a>", line 284, in _parse_series
    ex_season = scene_exceptions.get_season_from_name(result.series, result.series_name) or result.season_number
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/scene_exceptions.py#L168">medusa/scene_exceptions.py</a>", line 168, in get_season_from_name
    if exception.title.lower() == exception_name.lower():
                                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
