### ISSUE TITLE
[3d65665] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")

### ISSUE THREAD

**Issue by shizo971** [pymedusa/Medusa#11446]
**Describe the bug**
Had this bug when search for subtitle automatically.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
- OS: [Linux-4.4.302+-x86_64-with-glibc2.34] - DSM 7.2-64570 Update 2
- Branch: [master]
- Commit: [https://github.com/pymedusa/Medusa/commit/3d656652ab277e47689483912ed7fc443e7023e8]
- Python version: [3.8.15]
- Database version: [44.19]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2023-08-08 20:12:26 ERROR    TORNADO :: [3d65665] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /api/v2/history?page=1&limit=100&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (10.10.60.140)
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/volume1/@appstore/medusa/src/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/volume1/@appstore/medusa/src/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/volume1/@appstore/medusa/src/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/volume1/@appstore/medusa/src/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
AttributeError: 'list' object has no attribute 'get'
```
</details>

**Additional context**

**Comment by medariox** [comment]
See: https://github.com/pymedusa/Medusa/issues/11434
