### ISSUE TITLE
PermissionError(13, 'Permission denied')

### ISSUE THREAD

**Issue by coelho78** [pymedusa/Medusa#11479]
**Describe the bug**
From one moment to the other, without any changes to my Synology nor to Medusa installation, I'm getting post-processing issues for multiple files. Has been working fine for years. It looks like a permission issue, but I didn't change anything.

**Medusa (please complete the following information):**
 - OS: Linux-3.2.40-armv7l-with-glibc2.4
 - Branch: master
 - Commit: [3d656652ab277e47689483912ed7fc443e7023e8](https://github.com/pymedusa/Medusa/commit/3d656652ab277e47689483912ed7fc443e7023e8)
 - Python version: 3.7.12 (default, Oct 22 2021, 20:32:59) [GCC 4.9.3 20150311 (prerelease)]
 - Database version: 44.19

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
2023-09-26 10:10:25 ERROR    POSTPROCESSOR :: [3d65665] Unable to move file /volume1/Download/Compleet/TELEVISIE/Sex.Education.S04E08.720p.WEB.h264-EDITH.mkv to /volume1/TV-Series/Sex Education/Season 04: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/medusa/post_processor.py", line 1282, in process
    app.USE_SUBTITLES and bool(ep_obj.series.subtitles))
  File "/volume1/@appstore/medusa/var/src/medusa/post_processor.py", line 543, in post_process_action
    action=action, subtitles=subtitles, subtitle_action=subtitle_action)
  File "/volume1/@appstore/medusa/var/src/medusa/post_processor.py", line 445, in _combined_file_operation
    other_files += self.list_associated_files(file_path, subfolders=True, subtitles_only=True, refine=True)
  File "/volume1/@appstore/medusa/var/src/medusa/post_processor.py", line 218, in list_associated_files
    processed_names += tuple((_f for _f in (self._rar_basename(file_path, files),) if _f))
  File "/volume1/@appstore/medusa/var/src/medusa/post_processor.py", line 328, in _rar_basename
    for rar in rars:
  File "/volume1/@appstore/medusa/var/src/medusa/post_processor.py", line 326, in <genexpr>
    rars = (x for x in files if os.path.isfile(x) and rarfile.is_rarfile(x))
  File "/volume1/@appstore/medusa/var/src/ext/rarfile.py", line 419, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/volume1/@appstore/medusa/var/src/ext/rarfile.py", line 404, in _get_rar_version
    with XFile(xfile) as fd:
  File "/volume1/@appstore/medusa/var/src/ext/rarfile.py", line 2434, in __init__
    self._fd = open(xfile, 'rb', bufsize)`
</details>

**Comment by medariox** [comment]
Check that your files have the correct permissions.
