### ISSUE TITLE
'Rows per page' in 'History' broken

### ISSUE THREAD

**Issue by albatros69** [pymedusa/Medusa#11481]
**Describe the bug**

**To Reproduce**
1. Go to 'History'
2. Increase the number of 'Rows per page'
3. See error

**Expected behavior**
The number of rows should increase and the error must not be present

**Medusa (please complete the following information):**
 - OS: raspbian
 - Branch: master
 - Commit: [3d656652ab277e47689483912ed7fc443e7023e8](https://github.com/pymedusa/Medusa/commit/3d656652ab277e47689483912ed7fc443e7023e8)
 - Python version: 3.9.2
 - Database version: 44.19

**Debug logs (at least 50 lines):**

```
2023-10-02 17:43:31 ERROR	TORNADO :: [3d65665] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /sr/api/v2/history?page=1&limit=25&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (::1)
Traceback (most recent call last):
  File "/home/deploy/Medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/deploy/Medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/deploy/Medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
AttributeError: 'list' object has no attribute 'get'
2023-10-02 17:43:19 ERROR	TORNADO :: [3d65665] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /sr/api/v2/history?page=1&limit=100&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (::1)
Traceback (most recent call last):
  File "/home/deploy/Medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/deploy/Medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/deploy/Medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
AttributeError: 'list' object has no attribute 'get'
2023-10-02 17:42:42 ERROR	TORNADO :: [3d65665] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /sr/api/v2/history?page=1&limit=100&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (::1)
Traceback (most recent call last):
  File "/home/deploy/Medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/deploy/Medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/deploy/Medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
AttributeError: 'list' object has no attribute 'get'
2023-10-02 17:42:28 ERROR	TORNADO :: [3d65665] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /sr/api/v2/history?page=1&limit=100&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (::1)
Traceback (most recent call last):
  File "/home/deploy/Medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/deploy/Medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/deploy/Medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
AttributeError: 'list' object has no attribute 'get'
2023-10-02 17:39:10 ERROR	TORNADO :: [3d65665] Uncaught exception in APIv2: AttributeError("'list' object has no attribute 'get'")
Request: GET /sr/api/v2/history?page=1&limit=25&sort[]=[%7B%22field%22:%22date%22,%22type%22:%22desc%22%7D]&filter=%7B%7D (::1)
Traceback (most recent call last):
  File "/home/deploy/Medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/deploy/Medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/home/deploy/Medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/deploy/Medusa/medusa/server/api/v2/history.py", line 139, in get
    field = sort[0].get('field').lower()
AttributeError: 'list' object has no attribute 'get'
```

**Comment by medariox** [comment]
See: https://github.com/pymedusa/Medusa/issues/11434
