### ISSUE TITLE
[APP SUBMITTED]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows?extended=noseasons (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1c785fe640>: Failed to establish a new connection: [Errno -2] Name or service not known'))

### ISSUE THREAD

**Issue by Ombouwleusden** [pymedusa/Medusa#11619]
### INFO
**Python Version**: `3.8.15 (default, Nov 24 2022, 04:20:39) [GCC 12.2.0]`
**Operating System**: `Linux-4.4.302+-x86_64-with-glibc2.34`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3
**Link to Log**: **No Log available**
### ERROR
<pre>
2024-02-02 00:10:02 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [c5a1e37] Could not connect to Trakt service: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows?extended=noseasons (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1c785fe640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/connection.py#L174">ext/urllib3/connection.py</a>", line 174, in _new_conn
    conn = connection.create_connection(
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/util/connection.py#L72">ext/urllib3/util/connection.py</a>", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/connectionpool.py#L715">ext/urllib3/connectionpool.py</a>", line 715, in urlopen
    httplib_response = self._make_request(
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/connectionpool.py#L404">ext/urllib3/connectionpool.py</a>", line 404, in _make_request
    self._validate_conn(conn)
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/connectionpool.py#L1058">ext/urllib3/connectionpool.py</a>", line 1058, in _validate_conn
    conn.connect()
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/connection.py#L363">ext/urllib3/connection.py</a>", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/connection.py#L186">ext/urllib3/connection.py</a>", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1c785fe640>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/requests/adapters.py#L486">ext/requests/adapters.py</a>", line 486, in send
    resp = conn.urlopen(
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/connectionpool.py#L799">ext/urllib3/connectionpool.py</a>", line 799, in urlopen
    retries = retries.increment(
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/urllib3/util/retry.py#L592">ext/urllib3/util/retry.py</a>", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows?extended=noseasons (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1c785fe640>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/medusa/show/recommendations/trakt.py#L145">medusa/show/recommendations/trakt.py</a>", line 145, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/medusa/show/recommendations/trakt.py#L128">medusa/show/recommendations/trakt.py</a>", line 128, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/wrapt/wrappers.py#L578">ext/wrapt/wrappers.py</a>", line 578, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/deprecated/classic.py#L186">ext/deprecated/classic.py</a>", line 186, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/trakt/core.py#L578">ext/trakt/core.py</a>", line 578, in inner
    json_data = self._handle_request('get', url)
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/trakt/core.py#L543">ext/trakt/core.py</a>", line 543, in _handle_request
    response = session.request(method, url, headers=HEADERS,
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/requests/sessions.py#L589">ext/requests/sessions.py</a>", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/requests/sessions.py#L703">ext/requests/sessions.py</a>", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/volume1/@appstore/medusa/src/<a href="../blob/c5a1e37bbaaebd49dd57ce5adf4e92c308fa6de3/ext/requests/adapters.py#L519">ext/requests/adapters.py</a>", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows?extended=noseasons (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1c785fe640>: Failed to establish a new connection: [Errno -2] Name or service not known'))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by atrament00** [comment]
Same problem here.

2024-02-09 12:29:16 ERROR    TRAKTCHECKER :: [c5a1e37] Trakt exception while running trakt_checker.
Error: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /users/settings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c5448170>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/lib/python3.10/socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff9c5448170>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /users/settings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c5448170>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/schedulers/trakt_checker.py", line 92, in run
    self.sync_watchlist()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/schedulers/trakt_checker.py", line 314, in sync_watchlist
    if self._get_show_watchlist():
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/schedulers/trakt_checker.py", line 722, in _get_show_watchlist
    user = get_trakt_user()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/helpers/trakt.py", line 23, in get_trakt_user
    user = users.get_user_settings()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/trakt/core.py", line 578, in inner
    json_data = self._handle_request('get', url)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/trakt/core.py", line 543, in _handle_request
    response = session.request(method, url, headers=HEADERS,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /users/settings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9c5448170>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-02-09 00:00:04 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [c5a1e37] Could not connect to Trakt service: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows?extended=noseasons (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9d041fd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/lib/python3.10/socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff9d041fd90>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows?extended=noseasons (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9d041fd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/show/recommendations/trakt.py", line 145, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/show/recommendations/trakt.py", line 128, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/wrapt/wrappers.py", line 578, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/deprecated/classic.py", line 186, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/trakt/core.py", line 578, in inner
    json_data = self._handle_request('get', url)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/trakt/core.py", line 543, in _handle_request
    response = session.request(method, url, headers=HEADERS,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/watched/shows?extended=noseasons (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff9d041fd90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-02-08 15:05:39 ERROR    MAIN :: [c5a1e37] Missing time zone for network: Extension765
