### ISSUE TITLE
Can't connect to medusa, as soon as you hit web interface it breaks.

### ISSUE THREAD

**Issue by jaxjexjox** [pymedusa/Medusa#11704]
**Describe the bug**

Medusa WebUI is no longer opening.
"Unable to connect to Medusa!"

**To Reproduce**
Stop container
Remove container
Pull latest container.
Re-Run Medusa (this is how I've upgraded Medusa for 3 years)

Medusa runs fine with NO ERRORS in "docker logs"
As soon as you open the WebUI it says "unable to connect to medusa!"

All menus are missing all options.
Docker logs shows stuff breaking, note that I left it up for 5 minutes before connecting, as soon as I did, ERROR TORNADO

```

2024-04-14 11:06:06 INFO     MAIN :: [34a67cf] Starting Medusa [master] using '/config/config.ini'
2024-04-14 11:06:06 INFO     TORNADO :: [34a67cf] Starting Medusa on http://0.0.0.0:8081/
2024-04-14 11:06:06 INFO     MAIN :: [34a67cf] Updating exception_cache and exception_season_cache
2024-04-14 11:06:06 INFO     MAIN :: [34a67cf] Finished processing 4829 scene exceptions.
2024-04-14 11:06:06 INFO     MAIN :: [34a67cf] Building internal name cache for all shows
2024-04-14 11:11:15 **ERROR    TORNADO** :: [34a67cf] Uncaught exception in APIv2: BlockingIOError(11, 'Resource temporarily unavailable')
Request: GET /api/v2/config/ (192.168.0.148)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
```
Error:
https://i.imgur.com/BFssfUi.png

All settings seem missing:
https://i.imgur.com/ZnVClyi.png
https://i.imgur.com/yOUWQFM.png
https://i.imgur.com/9zm52cU.png

**Expected behavior**
Program works.

**Screenshots**
See above

**Medusa (please complete the following information):**
Ubuntu 22.04 latest patches, all other docker containers fine.
I think it's Master branch:
pymedusa/medusa docker container, although Linuxserver.io one didn't work either

**Debug logs (at least 50 lines):**
Cannot get debug logs, the WebUI isn't 'actually talking' to Medusa properly.

**Additional context**

The permissions to my config for medusa container have not changed.

**Comment by StudioEtrange** [comment]
same thing +1

**Comment by StudioEtrange** [comment]
It seems to be a bug in cifs, https://forums.linuxmint.com/viewtopic.php?t=417371
this error is not linked to medusa

**Comment by jaxjexjox** [comment]
I should have closed this apologies.  It was indeed CIFS being broken by a patch to Ubuntu LTS, kind of shocking to be honest.
Medusa carries along fine once CIFS was repaired, appreciate the ongoing hard work team.
