### ISSUE TITLE
[APP SUBMITTED]: UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 0: invalid start byte

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1171]
### INFO

**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@161bce5a8892b239e700175e76f8addc6f048a9a
**Link to Log**: https://gist.github.com/e0298432850201c4d2259ebddd8515b3
### ERROR

<pre>
2016-09-22 18:25:56 ERROR    Thread-15 :: [161bce5] Failed doing web ui callback: Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/server/web/core/base.py#L270">medusa/server/web/core/base.py</a>", line 270, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/server/web/core/error_logs.py#L136">medusa/server/web/core/error_logs.py</a>", line 136, in submit_errors
    results = self.issue_submitter.submit_github_issue(CheckVersion())
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/issuesubmitter.py#L170">medusa/issuesubmitter.py</a>", line 170, in submit_github_issue
    return IssueSubmitter.submit_issues(github, github_repo, loglines, similar_issues)
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/issuesubmitter.py#L197">medusa/issuesubmitter.py</a>", line 197, in submit_issues
    gist = IssueSubmitter.create_gist(github, logline)
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/issuesubmitter.py#L52">medusa/issuesubmitter.py</a>", line 52, in create_gist
    context_loglines = logline.get_context_loglines()
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/logger.py#L347">medusa/logger.py</a>", line 347, in get_context_loglines
    for logline in read_loglines(modification_time=start_timestamp):
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/logger.py#L138">medusa/logger.py</a>", line 138, in read_loglines
    for line in reverse_readlines(f):
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/logger.py#L195">medusa/logger.py</a>", line 195, in reverse_readlines
    buf = fh.read(min(remaining_size, buf_size))
  File "/usr/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 0: invalid start byte
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/server/web/core/base.py#L270">medusa/server/web/core/base.py</a>", line 270, in async_call
    result = function(**kwargs)
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/server/web/core/error_logs.py#L136">medusa/server/web/core/error_logs.py</a>", line 136, in submit_errors
    results = self.issue_submitter.submit_github_issue(CheckVersion())
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/issuesubmitter.py#L170">medusa/issuesubmitter.py</a>", line 170, in submit_github_issue
    return IssueSubmitter.submit_issues(github, github_repo, loglines, similar_issues)
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/issuesubmitter.py#L197">medusa/issuesubmitter.py</a>", line 197, in submit_issues
    gist = IssueSubmitter.create_gist(github, logline)
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/issuesubmitter.py#L52">medusa/issuesubmitter.py</a>", line 52, in create_gist
    context_loglines = logline.get_context_loglines()
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/logger.py#L347">medusa/logger.py</a>", line 347, in get_context_loglines
    for logline in read_loglines(modification_time=start_timestamp):
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/logger.py#L138">medusa/logger.py</a>", line 138, in read_loglines
    for line in reverse_readlines(f):
  File "/home/home/SickRage/<a href="../blob/161bce5a8892b239e700175e76f8addc6f048a9a/medusa/logger.py#L195">medusa/logger.py</a>", line 195, in reverse_readlines
    buf = fh.read(min(remaining_size, buf_size))
  File "/usr/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbb in position 0: invalid start byte
</pre>

---

_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato confirm the fix?  The fix is already in `manual_sub_search` branch

**Comment by Contusio** [comment]
### INFO
**Python Version**: `2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.77-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@daf5388bff4c78985a98ac59ece113c59527df8e
**Link to Log**: https://gist.github.com/22a7685722f9d6dffee201ffa8b4bc2f
### ERROR
<pre>
2016-12-10 14:09:36 ERROR    Thread-232 :: [daf5388] Exception generated: 'utf8' codec can't decode byte 0xed in position 29: invalid continuation byte
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/SickBeard/medusa/server/web/core/base.py#L271">SickBeard/medusa/server/web/core/base.py</a>", line 271, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/SickBeard/medusa/server/web/home/post_process.py#L46">SickBeard/medusa/server/web/home/post_process.py</a>", line 46, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type, ignore_subs=argToBool(ignore_subs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/SickBeard/medusa/process_tv.py#L249">SickBeard/medusa/process_tv.py</a>", line 249, in processDir
    for curDir in [x for x in dirs if validateDir(path, x, nzbNameOriginal, failed, result)]:
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/SickBeard/medusa/process_tv.py#L386">SickBeard/medusa/process_tv.py</a>", line 386, in validateDir
    for _, processdir, fileList in os.walk(os.path.join(path, dirName), topdown=False):
  File "/usr/local/sickbeard-custom/env/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/local/sickbeard-custom/env/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/local/sickbeard-custom/env/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/SickBeard/medusa/init/filesystem.py#L85">SickBeard/medusa/init/filesystem.py</a>", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/SickBeard/medusa/init/filesystem.py#L44">SickBeard/medusa/init/filesystem.py</a>", line 44, in _handle_output_u
    return map(_handle_output_u, result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/SickBeard/medusa/init/filesystem.py#L41">SickBeard/medusa/init/filesystem.py</a>", line 41, in _handle_output_u
    return decode(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/SickBeard/medusa/init/filesystem.py#L26">SickBeard/medusa/init/filesystem.py</a>", line 26, in decode
    return text_type(value, 'utf-8' if os.name != 'nt' else fs_encoding)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 29: invalid continuation byte
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
@Contusio 
Which file are you trying to process?

**Comment by medariox** [comment]
Closing until we have more info
