### ISSUE TITLE
Can someone please assist if "resource busy" is source or destination path?

### ISSUE THREAD

**Issue by jaxjexjox** [pymedusa/Medusa#11729]
This is not a bug, apologies, very sorry.

I'm curious if the cause of this is the source or destination? I see it infrequently.

2024-06-02 19:03:37 ERROR    Thread_0 :: [34a67cf] Unable to move file /downloads/SOURCEFILE.MKV  to /tv/DESTINATION-FILE-NICE-NAMING-CONVENTION/Season 07: OSError(16, 'Resource busy')
Traceback (most recent call last):
  File "/app/medusa/medusa/post_processor.py", line 1281, in process
    self.post_process_action(self.file_path, dest_path, new_base_name, bool(app.MOVE_ASSOCIATED_FILES),
  File "/app/medusa/medusa/post_processor.py", line 542, in post_process_action
    self._combined_file_operation(file_path, new_path, new_basename, associated_files=associated_files,
  File "/app/medusa/medusa/post_processor.py", line 443, in _combined_file_operation
    other_files += self.list_associated_files(file_path, refine=True)
  File "/app/medusa/medusa/post_processor.py", line 218, in list_associated_files
    processed_names += tuple((_f for _f in (self._rar_basename(file_path, files),) if _f))
  File "/app/medusa/medusa/post_processor.py", line 328, in _rar_basename
    for rar in rars:
  File "/app/medusa/medusa/post_processor.py", line 326, in <genexpr>
    rars = (x for x in files if os.path.isfile(x) and rarfile.is_rarfile(x))
  File "/app/medusa/ext/rarfile.py", line 419, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/app/medusa/ext/rarfile.py", line 404, in _get_rar_version
    with XFile(xfile) as fd:
  File "/app/medusa/ext/rarfile.py", line 2434, in __init__
    self._fd = open(xfile, 'rb', bufsize)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]
 - Python version: [e.g. 3.6.8]
 - Database version: [e.g. 44.12]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
your running medusa in docker container?
