### ISSUE TITLE
Unable to bdecode torrent. Invalid torrent

### ISSUE THREAD

**Issue by jaytonic** [pymedusa/Medusa#11836]
**Describe the bug**
I tried to do a manual search on a season, then clicked on the right button to download one of the proposed result for the tv show.
It doesn't get downloaded and I get a warning.

**To Reproduce**
1. Go to a TV Show( in my case: https://www.themoviedb.org/tv/112738-hpi )
2. Click on 'Manual search' of a season
3. Select one of the season by clicking on the right button

**Expected behavior**
The tv show gets downloaded, I receive a confirmation and no error

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Linux-5.15.0-107
 - Branch: master
 - Commit: Unknown(Deplyoed with docker: 
lscr.io/linuxserver/medusa:latest@sha256:573f15d75c530d3f3662e1ff1e13ec2039872df3c4a1255fedd4e73cfc6d5722 )
 - Python version: 3.11.10 
 - Database version: 44.19
 - Medusa version: 1.0.21

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2024-09-21 09:40:36 WARNING	SNATCHQUEUE-SNATCH-387368 :: Unable to bdecode torrent. Invalid torrent: HPI.S01.FRENCH.720p.WEB.H264-FREAMON.(Haut.potentiel.Intellectuel). Deleting cached result if exists
Traceback (most recent call last):
  File "/app/medusa/medusa/init/__init__.py", line 173, in decode
    data, length = self.decode_func[value[0:1]](value, 0)
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: b'<'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/medusa/clients/torrent/generic.py", line 193, in _get_info_hash
    torrent_bdecode = BENCODE.decode(result.content, allow_extra_data=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/init/__init__.py", line 193, in decode
    return self.decoder.decode(value, allow_extra_data=allow_extra_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/init/__init__.py", line 175, in decode
    raise bencodepy.BencodeDecodeError('not a valid bencoded string')
bencodepy.exceptions.BencodeDecodeError: not a valid bencoded string
2024-09-21 09:40:35 INFO	SNATCHQUEUE-SNATCH-387368 :: Downloading HPI.S01.FRENCH.720p.WEB.H264-FREAMON.(Haut.potentiel.Intellectuel) with 86 seeders and 3 leechers and size 9.13 GB from Yggtorrent, through a SearchType.MANUAL_SEARCH search
2024-09-21 09:40:35 INFO	SNATCHQUEUE-SNATCH-387368 :: Beginning to snatch release: HPI.S01.FRENCH.720p.WEB.H264-FREAMON.(Haut.potentiel.Intellectuel)
2024-09-21 09:33:45 WARNING	SNATCHQUEUE-SNATCH-387368 :: Unable to bdecode torrent. Invalid torrent: HPI.S01.FRENCH.AD.1080p.WEB.H264-BTT. Deleting cached result if exists
Traceback (most recent call last):
  File "/app/medusa/medusa/init/__init__.py", line 173, in decode
    data, length = self.decode_func[value[0:1]](value, 0)
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: b'<'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/medusa/clients/torrent/generic.py", line 193, in _get_info_hash
    torrent_bdecode = BENCODE.decode(result.content, allow_extra_data=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/init/__init__.py", line 193, in decode
    return self.decoder.decode(value, allow_extra_data=allow_extra_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/medusa/init/__init__.py", line 175, in decode
    raise bencodepy.BencodeDecodeError('not a valid bencoded string')
bencodepy.exceptions.BencodeDecodeError: not a valid bencoded string
2024-09-21 09:33:44 INFO	SNATCHQUEUE-SNATCH-387368 :: Downloading HPI.S01.FRENCH.AD.1080p.WEB.H264-BTT with 51 seeders and 3 leechers and size 14.83 GB from Yggtorrent, through a SearchType.MANUAL_SEARCH search
2024-09-21 09:33:44 INFO	SNATCHQUEUE-SNATCH-387368 :: Beginning to snatch release: HPI.S01.FRENCH.AD.1080p.WEB.H264-BTT
```
</details>

**Additional context**

**Comment by karlitros** [comment]
Which search providers are causing the issue? All or just a few?
