### ISSUE TITLE
SHOWQUEUE-REFRESH - Unable to contact TMDB

### ISSUE THREAD

**Issue by tarteens** [pymedusa/Medusa#11853]
** INFO
Branch: [master](https://github.com/pymedusa/Medusa/tree/master)
Commit: 34a67cf159acab69017dd5b95e0233ecde0de28a

** Error

```
2024-10-06 03:50:22 WARNING  SHOWQUEUE-REFRESH :: [34a67cf] 203737: Unable to contact TMDB. Aborting: Could not get episodes for series 203737 using indexer TMDB. Cause: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/tv/203737/season/2?language=en&api_key=edc5f123313769de83a71e157758030b
Traceback (most recent call last):
  File "/opt/pymedusa/medusa/indexers/tmdb/api.py", line 277, in _get_episodes
    season_info = self.tmdb.TV_Seasons(tmdb_id, season).info(language=self.config['language'])
  File "/opt/pymedusa/ext/tmdbsimple/tv.py", line 524, in info
    response = self._GET(path, kwargs)
  File "/opt/pymedusa/ext/tmdbsimple/base.py", line 110, in _GET
    return self._request('GET', path, params=params)
  File "/opt/pymedusa/ext/tmdbsimple/base.py", line 105, in _request
    response.raise_for_status()
  File "/opt/pymedusa/ext/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/tv/203737/season/2?language=en&api_key=edc5f123313769de83a71e157758030b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pymedusa/medusa/queues/show_queue.py", line 758, in run
    self.show.refresh_dir()
  File "/opt/pymedusa/medusa/tv/series.py", line 2117, in refresh_dir
    self.load_episodes_from_dir()
  File "/opt/pymedusa/medusa/tv/series.py", line 1115, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/opt/pymedusa/medusa/tv/series.py", line 1490, in make_ep_from_file
    root_ep.create_meta_files()
  File "/opt/pymedusa/medusa/tv/episode.py", line 1160, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/opt/pymedusa/medusa/tv/episode.py", line 1182, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/opt/pymedusa/medusa/metadata/generic.py", line 369, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/opt/pymedusa/medusa/tv/episode.py", line 759, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/opt/pymedusa/medusa/indexers/tmdb/api.py", line 280, in _get_episodes
    raise IndexerException(
medusa.indexers.exceptions.IndexerException: Could not get episodes for series 203737 using indexer TMDB. Cause: 404 Client Error: Not Found for url: https://api.themoviedb.org/3/tv/203737/season/2?language=en&api_key=edc5f123313769de83a71e157758030b
```

**Comment by tarteens** [comment]
not an issue on pymedusa, the serie is not known on TMDB
