### ISSUE TITLE
TypeError('Object of type Episode is not JSON serializable')

### ISSUE THREAD

**Issue by Antaneyes** [pymedusa/Medusa#11864]
When trying to process some files, this message appears

 Locale:	es_ES.cp1252
 OS:	Windows-10-10.0.22621-SP0
 SSL Version:	OpenSSL 1.1.0j 20 Nov 2018
 Python Version:	3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
Database: 44.19
Version: [1.0.21](https://github.com/pymedusa/Medusa/releases/tag/v1.0.21)
Commit: [34a67cf159acab69017dd5b95e0233ecde0de28a](https://github.com/pymedusa/Medusa/commit/34a67cf159acab69017dd5b95e0233ecde0de28a)
Medusa Info:

`2024-10-23 21:26:17 WARNING	APIv2-Thread-33 :: [34a67cf] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\ws\__init__.py", line 41, in json
    return json.dumps(self.content)
  File "C:\Medusa\Python\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Medusa\Python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Medusa\Python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Medusa\Python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable`

**Comment by rdeherder** [comment]
Same here. A bit more detailed error log:

Medusa Info: 	Branch: master
Commit: Unknown
Version: 1.0.22
Database: 44.19
Python Version:	3.11.11 (main, Dec 6 2024, 11:15:21) [GCC 13.2.1 20231014]
SSL Version:	OpenSSL 3.1.7 3 Sep 2024
OS:	Linux-5.10.60-qnap-x86_64-with
Locale:	en_US.UTF-8
Timezone:	UTC


```
2025-01-09 16:37:49 WARNING  SEARCHQUEUE-BACKLOG-190351 :: [] Unhashable type encountered. Please report this warning to the developers.
TypeError('Object of type Episode is not JSON serializable')
Traceback (most recent call last):
  File "/app/medusa/medusa/ws/__init__.py", line 41, in json
    return json.dumps(self.content)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Episode is not JSON serializable
```
