### ISSUE TITLE
Error while searching in viewlog (develop)

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1261]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: develop
OS: windows
What you did: opened viewlog and typed something in searchbox
What happened: medusa gave error and froze on the viewlog screen
What you expected: not to get error supplied in logs
Logs:
```
PASTE LOGS HERE
```
https://0paste.com/9324-b348eb3b

**Comment by wimpyrbx** [comment]
2016-10-13 16:20:44 DEBUG    MAIN :: [ed345b5] Internal name cache for Haters Back Off set to: [ haters back off ]
2016-10-13 16:20:44 DEBUG    MAIN :: [ed345b5] Internal name cache for Zapped! set to: [ zapped ]
2016-10-13 16:20:44 DEBUG    MAIN :: [ed345b5] Internal name cache for Crazyhead set to: [ crazyhead ]
2016-10-13 16:20:44 DEBUG    MAIN :: [ed345b5] Internal name cache for Beck set to: [ beck ]
2016-10-13 16:20:44 DEBUG    MAIN :: [ed345b5] Finished updating network timezones
2016-10-13 16:21:24 ERROR    Thread-28 :: [ed345b5] Failed doing web ui callback: Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\SickRageMedusa\**********\logger.py", line 148, in read_loglines
    if predicate(logline):
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 135, in <lambda>
    search_query=log_search))]
  File "C:\SickRageMedusa\**********\logger.py", line 237, in filter_logline
    if (not logline.message or search_query not in logline.message.lower()) and (
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 24: character maps to <undefined>
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\SickRageMedusa\**********\logger.py", line 148, in read_loglines
    if predicate(logline):
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 135, in <lambda>
    search_query=log_search))]
  File "C:\SickRageMedusa\**********\logger.py", line 237, in filter_logline
    if (not logline.message or search_query not in logline.message.lower()) and (
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 24: character maps to <undefined>
2016-10-13 16:21:24 DEBUG    TORNADO :: [ed345b5] Failed doing web ui request u'viewlog': Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 253, in get
    results = yield self.async_call(method)
  File "C:\SickRageMedusa\lib\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\SickRageMedusa\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\SickRageMedusa\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\SickRageMedusa\**********\logger.py", line 148, in read_loglines
    if predicate(logline):
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 135, in <lambda>
    search_query=log_search))]
  File "C:\SickRageMedusa\**********\logger.py", line 237, in filter_logline
    if (not logline.message or search_query not in logline.message.lower()) and (
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 24: character maps to <undefined>

2016-10-13 16:21:27 ERROR    Thread-30 :: [ed345b5] Failed doing web ui callback: Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\SickRageMedusa\**********\logger.py", line 148, in read_loglines
    if predicate(logline):
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 135, in <lambda>
    search_query=log_search))]
  File "C:\SickRageMedusa\**********\logger.py", line 237, in filter_logline
    if (not logline.message or search_query not in logline.message.lower()) and (
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 24: character maps to <undefined>
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\SickRageMedusa\**********\logger.py", line 148, in read_loglines
    if predicate(logline):
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 135, in <lambda>
    search_query=log_search))]
  File "C:\SickRageMedusa\**********\logger.py", line 237, in filter_logline
    if (not logline.message or search_query not in logline.message.lower()) and (
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 24: character maps to <undefined>
2016-10-13 16:21:27 DEBUG    TORNADO :: [ed345b5] Failed doing web ui request u'viewlog': Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 253, in get
    results = yield self.async_call(method)
  File "C:\SickRageMedusa\lib\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\SickRageMedusa\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\SickRageMedusa\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "C:\SickRageMedusa\**********\logger.py", line 148, in read_loglines
    if predicate(logline):
  File "C:\SickRageMedusa\**********\server\web\core\error_logs.py", line 135, in <lambda>
    search_query=log_search))]
  File "C:\SickRageMedusa\**********\logger.py", line 237, in filter_logline
    if (not logline.message or search_query not in logline.message.lower()) and (
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 24: character maps to <undefined>

2016-10-13 16:30:14 DEBUG    POSTPROCESSOR :: [ed345b5] Starting new thread: POSTPROCESSOR
2016-10-13 16:30:14 DEBUG    POSTPROCESSOR :: [ed345b5] Processing folder D:\DOWNLOAD\complete\TV
2016-10-13 16:30:14 INFO     POSTPROCESSOR :: [ed345b5] PostProcessing Path: D:\DOWNLOAD\complete\TV
2016-10-13 16:30:14 DEBUG    POSTPROCESSOR :: [ed345b5] PostProcessing Dirs: []
2016-10-13 16:30:14 DEBUG    POSTPROCESSOR :: [ed345b5] PostProcessing Files: []
2016-10-13 16:30:14 DEBUG    POSTPROCESSOR :: [ed345b5] PostProcessing VideoFiles: []
2016-10-13 16:30:14 DEBUG    POSTPROCESSOR :: [ed345b5] PostProcessing RarContent:
2016-10-13 16:30:14 DEBUG    POSTPROCESSOR :: [ed345b5] PostProcessing VideoInRar:
2016-10-13 16:30:14 INFO     POSTPROCESSOR :: [ed345b5] Successfully processed

**Comment by wimpyrbx** [comment]
Release: Would.I.Lie.to.You.S10E06.720p.WEB.h264-HEAT
Show Folder: Would I Lie To You
Show Title: "Would I Lie To You?"

**Comment by OmgImAlexis** [comment]
@ratoaq2 is that an issue from removing ek?

**Comment by ratoaq2** [comment]
Fixed by #1272
