### ISSUE TITLE
[APP SUBMITTED]: error: need 'c' or 'n' flag to open new db

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1270]
### INFO
**Python Version**: `2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.16-6-osmc-armv7l-with-debian-8.6`
**Locale**: `UTF-8`
**Branch**: [optimized](../tree/optimized)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@592020977076ce70974612212bd50e66f29bbc77
**Link to Log**: https://gist.github.com/f08d326c12de366a8161c24f0a7de9c8
### ERROR
<pre>
2016-10-15 10:03:55 ERROR    Thread-18 :: [5920209] Error while manual searching subtitles. Error: need 'c' or 'n' flag to open new db
Traceback (most recent call last):
  File "/home/osmc/Medusa/<a href="../blob/592020977076ce70974612212bd50e66f29bbc77/medusa/server/web/home/handler.py#L1995">medusa/server/web/home/handler.py</a>", line 1995, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/home/osmc/Medusa/<a href="../blob/592020977076ce70974612212bd50e66f29bbc77/medusa/subtitles.py#L273">medusa/subtitles.py</a>", line 273, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/home/osmc/Medusa/<a href="../blob/592020977076ce70974612212bd50e66f29bbc77/lib/dogpile/cache/region.py#L973">lib/dogpile/cache/region.py</a>", line 973, in set
    self.backend.set(key, self._value(value))
  File "/home/osmc/Medusa/<a href="../blob/592020977076ce70974612212bd50e66f29bbc77/lib/dogpile/cache/backends/file.py#L237">lib/dogpile/cache/backends/file.py</a>", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/osmc/Medusa/<a href="../blob/592020977076ce70974612212bd50e66f29bbc77/lib/dogpile/cache/backends/file.py#L215">lib/dogpile/cache/backends/file.py</a>", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python2.7/anydbm.py", line 79, in open
    raise error, "need 'c' or 'n' flag to open new db"
error: need 'c' or 'n' flag to open new db
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 this happens when I delete subliminal and application cache files and run a subtitle search

**Comment by ratoaq2** [comment]
You shouldn't delete the cache files while medusa is running
