### ISSUE TITLE
View Log and Submit Errors broken

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#1287]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit**: Develop / 6eca5cd5343536f4ca9df32097e872c1a74dc4de
**OS**: Win 10x64
**What you did**: View Logs in GUI by either `Tools -> View` or getting redirected to the View Logs page by clearing errors or warnings in the GUI.
**What happened**: GUI message "Oops You have reached this page by accident, please check the url."
**What you expected**:  View Logs as before
**Logs**:  Traceback included below
```
2016-10-19 21:48:16 ERROR    Thread-24 :: [6eca5cd] Failed doing web ui callback: Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "H:\usr\local\medusa\medusa\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "H:\usr\local\medusa\medusa\logger.py", line 137, in read_loglines
    for line in reverse_readlines(f):
  File "H:\usr\local\medusa\medusa\logger.py", line 196, in reverse_readlines
    buf = text_type(buf.decode(sys.getfilesystemencoding()) if os.name == 'nt' else buf, errors='replace')
TypeError: decoding Unicode is not supported
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "H:\usr\local\medusa\medusa\server\web\core\error_logs.py", line 133, in viewlog
    predicate=lambda l: filter_logline(l, min_level=min_level,
  File "H:\usr\local\medusa\medusa\logger.py", line 137, in read_loglines
    for line in reverse_readlines(f):
  File "H:\usr\local\medusa\medusa\logger.py", line 196, in reverse_readlines
    buf = text_type(buf.decode(sys.getfilesystemencoding()) if os.name == 'nt' else buf, errors='replace')
TypeError: decoding Unicode is not supported
```

**Comment by labrys** [comment]
This is caused by fcf84481bcbcab7d489aaf9d33d03386d3892ca2.

**Comment by medariox** [comment]
Same issue with Windows 10.
