### ISSUE TITLE
[APP SUBMITTED]: TypeError: <bound method TVEpisode.__getstate__ of <medusa.tv.TVEpisode object at 0x67edbd50>> is not JSON serializable

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1289]
### INFO
**Python Version**: `2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.16-6-osmc-armv7l-with-debian-8.6`
**Locale**: `UTF-8`
**Branch**: [optimized](../tree/optimized)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@a49506db6e9fe7a97d4d0fb2729c68e24711640f
**Link to Log**: https://gist.github.com/5c87087de043113a4b7bbb7083b2271f
### ERROR
<pre>
2016-10-20 14:50:47 ERROR    FINDSUBTITLES :: [a49506d] Exception generated in thread FINDSUBTITLES: <bound method TVEpisode.__getstate__ of <medusa.tv.TVEpisode object at 0x67edbd50>> is not JSON serializable
Traceback (most recent call last):
  File "/home/osmc/Medusa/<a href="../blob/a49506db6e9fe7a97d4d0fb2729c68e24711640f/medusa/scheduler.py#L105">medusa/scheduler.py</a>", line 105, in run
    self.action.run(self.force)
  File "/home/osmc/Medusa/<a href="../blob/a49506db6e9fe7a97d4d0fb2729c68e24711640f/medusa/subtitles.py#L883">medusa/subtitles.py</a>", line 883, in run
    self.subtitles_download_in_pp()
  File "/home/osmc/Medusa/<a href="../blob/a49506db6e9fe7a97d4d0fb2729c68e24711640f/medusa/subtitles.py#L832">medusa/subtitles.py</a>", line 832, in subtitles_download_in_pp
    subtitles=False, embedded_subtitles=False)
  File "/home/osmc/Medusa/<a href="../blob/a49506db6e9fe7a97d4d0fb2729c68e24711640f/medusa/subtitles.py#L344">medusa/subtitles.py</a>", line 344, in download_subtitles
    logger.debug(u'Current tv episode object: %s', tv_episode.to_json())
  File "/home/osmc/Medusa/<a href="../blob/a49506db6e9fe7a97d4d0fb2729c68e24711640f/medusa/tv.py#L2246">medusa/tv.py</a>", line 2246, in to_json
    return json.dumps(self.__getstate__)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <bound method TVEpisode.__getstate__ of <medusa.tv.TVEpisode object at 0x67edbd50>> is not JSON serializable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
https://github.com/pymedusa/Medusa/pull/1281
