### ISSUE TITLE
Markins shows add 'anime' will show error when opening editShow for that show

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1300]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: feature/fix-error-when-both-files-exist (also in dev)
OS: windows 7
What you did:
* Add an anime show (don't configure it as anime)
* Use massEdit to change it to anime
* Open the shows editShow page.
What happened: Getting the following error:
![image](https://cloud.githubusercontent.com/assets/1331394/19605440/4fc83a3c-97ba-11e6-8640-a0dfe2bba056.png)

What you expected: To open the editShow page.
Logs:
```
2016-10-21 18:10:44 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Seeing if we still need an image of type 2: True
2016-10-21 18:10:45 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Fetching image from http://thetvdb.com/banners/posters/273005-1.jpg
2016-10-21 18:10:46 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Seeing if we still need an image of type 1: True
2016-10-21 18:10:47 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Fetching image from http://thetvdb.com/banners/graphical/273005-g2.jpg
2016-10-21 18:10:47 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Seeing if we still need an image of type 4: True
2016-10-21 18:10:49 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Fetching image from http://thetvdb.com/banners/_cache/posters/273005-1.jpg
2016-10-21 18:10:49 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Seeing if we still need an image of type 3: True
2016-10-21 18:10:50 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Fetching image from http://thetvdb.com/banners/_cache/graphical/273005-g2.jpg
2016-10-21 18:10:50 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Seeing if we still need an image of type 5: True
2016-10-21 18:10:51 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Fetching image from http://thetvdb.com/banners/fanart/original/273005-5.jpg
2016-10-21 18:10:52 INFO     SHOWQUEUE-ADD :: [ac9f69b] Done cache check
2016-10-21 18:10:52 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Checking if trakt watchlist wants to search for episodes from new show Ace of Diamond
2016-10-21 18:10:53 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Adding Ace of Diamond to Trakt library
2016-10-21 18:10:53 INFO     SHOWQUEUE-ADD :: [ac9f69b] update watchlist
2016-10-21 18:10:54 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Looking up XEM scene mapping for show 273005 on theTVDB
2016-10-21 18:10:54 DEBUG    SHOWQUEUE-ADD :: [ac9f69b] Transaction with 252 queries executed
2016-10-21 18:11:15 DEBUG    Thread-32 :: [ac9f69b] 273005: Saving to database: Ace of Diamond
2016-10-21 18:11:17 DEBUG    Thread-32 :: [ac9f69b] 114801: Saving to database: Fairy Tail
2016-10-21 18:11:27 ERROR    Thread-31 :: [ac9f69b] Failed doing web ui callback: Traceback (most recent call last):
  File "D:\Development\ManualSearch\medusa\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "D:\Development\ManualSearch\medusa\server\web\home\handler.py", line 1284, in editShow
    whitelist = show_obj.release_groups.whitelist
AttributeError: 'NoneType' object has no attribute 'whitelist'
Traceback (most recent call last):
  File "D:\Development\ManualSearch\medusa\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "D:\Development\ManualSearch\medusa\server\web\home\handler.py", line 1284, in editShow
    whitelist = show_obj.release_groups.whitelist
AttributeError: 'NoneType' object has no attribute 'whitelist'
2016-10-21 18:11:27 DEBUG    TORNADO :: [ac9f69b] Failed doing web ui request u'editShow': Traceback (most recent call last):
  File "D:\Development\ManualSearch\medusa\server\web\core\base.py", line 253, in get
    results = yield self.async_call(method)
  File "D:\Development\ManualSearch\lib\tornado\gen.py", line 1008, in run
    value = future.result()
  File "D:\Development\ManualSearch\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\Development\ManualSearch\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Development\ManualSearch\medusa\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "D:\Development\ManualSearch\medusa\server\web\home\handler.py", line 1284, in editShow
    whitelist = show_obj.release_groups.whitelist
AttributeError: 'NoneType' object has no attribute 'whitelist'
```

**Comment by p0psicles** [comment]
#1305
