### ISSUE TITLE
2 servers both dead

### ISSUE THREAD

**Issue by jxer** [pymedusa/Medusa#1374]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:1.7
OS:Debian
What you did:updated via gui
What happened:no shows on 1 server other server will not start
What you expected:
Logs:
```
Traceback (most recent call last):
  File "/home/n0r00t/.sickrage/SickBeard.py", line 9, in <module>
    from start import Application
  File "/home/n0r00t/.sickrage/start.py", line 104, in <module>
    from medusa.server.core import AppWebServer
  File "/home/n0r00t/.sickrage/medusa/server/core.py", line 17, in <module>
    from .web import CalendarHandler, KeyHandler, LoginHandler, LogoutHandler
  File "/home/n0r00t/.sickrage/medusa/server/web/__init__.py", line 7, in <module>
    from .home import Home, HomeAddShows, HomeChangeLog, HomeIRC, HomeNews, HomePostProcess
  File "/home/n0r00t/.sickrage/medusa/server/web/home/__init__.py", line 4, in <module>
    from .add_shows import HomeAddShows
  File "/home/n0r00t/.sickrage/medusa/server/web/home/add_shows.py", line 29, in <module>
    from ....show.recommendations.trakt import TraktPopular
  File "/home/n0r00t/.sickrage/medusa/show/recommendations/trakt.py", line 170, in <module>
    tvdb_api_v2 = get_tvdbv2_api()
  File "/home/n0r00t/.sickrage/medusa/show/recommendations/trakt.py", line 41, in get_tvdbv2_api
    access_token = auth_api.login_post(authentication_string)
  File "/home/n0r00t/.sickrage/lib/tvdbapiv2/apis/authentication_api.py", line 124, in login_post
    callback=params.get('callback'))
  File "/home/n0r00t/.sickrage/lib/tvdbapiv2/api_client.py", line 324, in call_api
    response_type, auth_settings, callback)
  File "/home/n0r00t/.sickrage/lib/tvdbapiv2/api_client.py", line 150, in __call_api
    post_params=post_params, body=body)
  File "/home/n0r00t/.sickrage/lib/tvdbapiv2/api_client.py", line 360, in request
    body=body)
  File "/home/n0r00t/.sickrage/lib/tvdbapiv2/rest.py", line 208, in POST
    body=body)
  File "/home/n0r00t/.sickrage/lib/tvdbapiv2/rest.py", line 143, in request
    headers=headers)
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/request.py", line 73, in request
    **urlopen_kw)
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/poolmanager.py", line 165, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/connectionpool.py", line 814, in _validate_conn
    conn.connect()
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 328, in ssl_wrap_socket
    ctx.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 303, in load_verify_locations
    raise TypeError("cafile must be None or a byte string")
TypeError: cafile must be None or a byte string

```

**Comment by jxer** [comment]
other server starts but has no shows, tried to follow 1364, but there were no bak files just db.42 etc, deleted all of them, and nothing.

**Comment by duramato** [comment]
https://github.com/pymedusa/Medusa/issues/1368

**Comment by jxer** [comment]
Traceback (most recent call last):
  File "/home/n0r00t/.sickrage/SickBeard.py", line 9, in <module>
    from start import Application
  File "/home/n0r00t/.sickrage/start.py", line 101, in <module>
    import medusa as app
  File "/home/n0r00t/.sickrage/medusa/__init__.py", line 32, in <module>
    import requests
  File "/home/n0r00t/.sickrage/lib/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/n0r00t/.sickrage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'

**Comment by jxer** [comment]
fixed the error with 
sudo apt-get purge python-openssl
sudo pip install pyopenssl
