### ISSUE TITLE
[APP SUBMITTED]: TypeError: __init__() got an unexpected keyword argument 'file_path'

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/Medusa#1403]
### INFO
**Python Version**: `2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]`
**Operating System**: `Linux-4.4.26-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@8bd740179469f2281588cc8e2859d7dc7fb0e025
**Link to Log**: https://gist.github.com/aa91ceeb0ab67473f88d358729cfe436
### ERROR
<pre>
2016-10-30 11:21:44 ERROR    Thread-18 :: [8bd7401] Exception generated in thread HTTP REQUEST: __init__() got an unexpected keyword argument 'file_path'
Traceback (most recent call last):
  File "/app/sickrage/medusa/server/web/core/base.py", line 271, in async_call
    result = function(**kwargs)
  File "/app/sickrage/medusa/server/web/home/post_process.py", line 49, in processEpisode
    is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=type, ignore_subs=argToBool(ignore_subs)
  File "/app/sickrage/medusa/processTV.py", line 239, in processDir
    process_media(path, [video], nzbName, process_method, force, is_priority, ignore_subs, result)
  File "/app/sickrage/medusa/processTV.py", line 567, in process_media
    result.result = processor.process()
  File "/app/sickrage/medusa/postProcessor.py", line 1161, in process
    self._add_to_anidb_mylist(self.file_path)
  File "/app/sickrage/medusa/postProcessor.py", line 499, in _add_to_anidb_mylist
    self.anidbEpisode = self._build_anidb_episode(app.ADBA_CONNECTION, file_path)
  File "/app/sickrage/medusa/postProcessor.py", line 487, in _build_anidb_episode
    paramsA=['epno', 'english_name', 'short_name_list', 'other_name', 'synonym_list'])
TypeError: __init__() got an unexpected keyword argument 'file_path'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Thraxis** [comment]
fix adba.Episode parameter name #1400
