### ISSUE TITLE
[APP SUBMITTED]: TypeEError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1410]
### INFO
**Python Version**: `2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.27-1-osmc-armv7l-with-debian-8.6`
**Locale**: `UTF-8`
**Branch**: [optimized2](../tree/optimized2)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@ff8dcfa6034366fa6c9d0b526b67e3cdb02fafe6
**Link to Log**: https://gist.github.com/2f6af155ba86624566e4d31c88f94e40
### ERROR
<pre>
2016-10-31 12:46:51 ERROR    SEARCHQUEUE-MANUAL-248835 :: [T411] :: [ff8dcfa] Unknown exception while searching T411. Error: "'int' object has no attribute '__getitem__'"
Traceback (most recent call last):
  File "/home/osmc/Medusa/<a href="../blob/ff8dcfa6034366fa6c9d0b526b67e3cdb02fafe6/medusa/search/core.py#L621">medusa/search/core.py</a>", line 621, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/home/osmc/Medusa/<a href="../blob/ff8dcfa6034366fa6c9d0b526b67e3cdb02fafe6/medusa/providers/generic_provider.py#L182">medusa/providers/generic_provider.py</a>", line 182, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/osmc/Medusa/<a href="../blob/ff8dcfa6034366fa6c9d0b526b67e3cdb02fafe6/medusa/providers/torrent/json/t411.py#L106">medusa/providers/torrent/json/t411.py</a>", line 106, in search
    results += self.parse(jdata, mode)
  File "/home/osmc/Medusa/<a href="../blob/ff8dcfa6034366fa6c9d0b526b67e3cdb02fafe6/medusa/providers/torrent/json/t411.py#L121">medusa/providers/torrent/json/t411.py</a>", line 121, in parse
    torrent_rows = sorted(unsorted_torrent_rows, key=itemgetter('added'), reverse=True)
TypeError: 'int' object has no attribute '__getitem__'
</pre>

---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by poplolnman** [comment]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@7be72185530d20219a194e1528e7eaf6986091f7
**Link to Log**: https://gist.github.com/6b0538b2d91c19ad0202cf87db2398c5
### ERROR
<pre>
2016-11-23 19:57:39 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: [7be7218] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "C:\\Medusa-develop\\medusa\\providers\\torrent\\html\\transmitthenet.py", line 166, in parse\n    pubdate_raw = cells[4].find(\'span\')[\'title\']\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "C:\Medusa-develop\medusa\providers\torrent\html\transmitthenet.py", line 166, in parse
    pubdate_raw = cells[4].find('span')['title']
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@54fd60a6ac37931391b1d9f77f85dfd43ae44f7e
**Link to Log**: https://gist.github.com/eaef8470d3bfd0c6dab8fc1a95367388
### ERROR
<pre>
2016-11-24 01:08:40 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TransmitTheNet] :: [54fd60a] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/home/SickRage/**********/providers/torrent/html/transmitthenet.py", line 166, in parse\n    pubdate_raw = cells[4].find(\'span\')[\'title\']\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/54fd60a6ac37931391b1d9f77f85dfd43ae44f7e/**********/providers/torrent/html/transmitthenet.py#L166">**********/providers/torrent/html/transmitthenet.py</a>", line 166, in parse
    pubdate_raw = cells[4].find('span')['title']
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/remove_ratio_reached](../tree/feature/remove_ratio_reached)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@3dfc593f7eaaefbb9488ce27de596b0d76b382a3
**Link to Log**: https://gist.github.com/b22a42933393da6cdd55895ea465b657
### ERROR
<pre>
2016-12-15 18:41:08 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [HDSpace] :: [3dfc593] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/hdspace.py", line 142, in parse\n    title = row.findAll(\'td\', class_=\'lista\', attrs={\'align\': \'center\'})[4].find(\'a\')[\'title\'][10:] or \\\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/3dfc593f7eaaefbb9488ce27de596b0d76b382a3/medusa/providers/torrent/html/hdspace.py#L142">medusa/providers/torrent/html/hdspace.py</a>", line 142, in parse
    title = row.findAll('td', class_='lista', attrs={'align': 'center'})[4].find('a')['title'][10:] or \
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
@duramato 
What's the point of this?
```
title = row.findAll('td', class_='lista', attrs={'align': 'center'})[4].find('a')['title'][10:] or \
    row.find('td', class_='lista', attrs={'align': 'left'}).find('a').get_text()
```

**Comment by duramato** [comment]
Get the actual release name, that doesn't have CF protection on the @s otherwise get the one which isn't exactly like the original. The first doesn't exist always

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/remove_ratio_reached](../tree/feature/remove_ratio_reached)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@19b06413e0f05ff5cdfcdf2db0eef9207c47a464
**Link to Log**: https://gist.github.com/96be678f508df9596470c80d0fcf4b1b
### ERROR
<pre>
2016-12-17 09:54:21 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [HDSpace] :: [19b0641] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/hdspace.py", line 142, in parse\n    title = row.findAll(\'td\', class_=\'lista\', attrs={\'align\': \'center\'})[4].find(\'a\')[\'title\'][10:] or \\\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/19b06413e0f05ff5cdfcdf2db0eef9207c47a464/medusa/providers/torrent/html/hdspace.py#L142">medusa/providers/torrent/html/hdspace.py</a>", line 142, in parse
    title = row.findAll('td', class_='lista', attrs={'align': 'center'})[4].find('a')['title'][10:] or \
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
Getting the same issue with BitSnoop.

```
2016-12-28 12:33:58 ERROR    SEARCHQUEUE-BACKLOG-75682 :: [BitSnoop] :: [677b47a] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/app/sickrage/medusa/providers/torrent/xml/bitsnoop.py", line 117, in parse\n    download_url = row.enclosure[\'url\']\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/app/sickrage/medusa/providers/torrent/xml/bitsnoop.py", line 117, in parse
    download_url = row.enclosure['url']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by OmgImAlexis** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]`
**Operating System**: `Linux-4.4.30-unRAID-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/8777a048f1bc2c56dc0dc746a0bc84da
### ERROR
<pre>
2016-12-28 12:33:58 ERROR    SEARCHQUEUE-BACKLOG-75682 :: [BitSnoop] :: [677b47a] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/app/sickrage/medusa/providers/torrent/xml/bitsnoop.py", line 117, in parse\n    download_url = row.enclosure[\'url\']\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/app/sickrage/medusa/providers/torrent/xml/bitsnoop.py", line 117, in parse
    download_url = row.enclosure['url']
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by zdeev** [comment]
### INFO
**Python Version**: `2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-8-6.2.9200`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/9491d3445963f6b083dc0ded5b47ddce
### ERROR
<pre>
2016-12-28 13:59:41 ERROR    SEARCHQUEUE-BACKLOG-264739 :: [TorrentLeech] :: [677b47a] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "C:\\SickRage-Medusa\\medusa\\providers\\torrent\\html\\torrentleech.py", line 145, in parse\n    download_url = urljoin(self.url, row.find(\'td\', class_=\'quickdownload\').find(\'a\')[\'href\'])\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "C:\SickRage-Medusa\medusa\providers\torrent\html\torrentleech.py", line 145, in parse
    download_url = urljoin(self.url, row.find('td', class_='quickdownload').find('a')['href'])
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/fix-ui-scaling](../tree/feature/fix-ui-scaling)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@3519fd1af59f50daf67dabd16d4af727645dadd0
**Link to Log**: https://gist.github.com/f86910a6d079c252a631c321acc0e3fe
### ERROR
<pre>
2016-12-31 07:13:33 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BITHDTV] :: [3519fd1] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/bithdtv.py", line 138, in parse\n    title = cells[2].find(\'a\')[\'title\']\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/3519fd1af59f50daf67dabd16d4af727645dadd0/medusa/providers/torrent/html/bithdtv.py#L138">medusa/providers/torrent/html/bithdtv.py</a>", line 138, in parse
    title = cells[2].find('a')['title']
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [fix-nzb-names](../tree/fix-nzb-names)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@c32ebe25fdc4d9bb12dc045da841a71161e81568
**Link to Log**: https://gist.github.com/ec6b47bae49247c9aaf988d0bd8a4934
### ERROR
<pre>
2017-03-19 19:59:14 ERROR    SEARCHQUEUE-MANUAL-69659 :: [T411] :: [c32ebe2] Unknown exception while searching T411. Error: "'int' object has no attribute '__getitem__'"
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/c32ebe25fdc4d9bb12dc045da841a71161e81568/medusa/search/core.py#L549">medusa/search/core.py</a>", line 549, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/home/pi/Medusa/<a href="../blob/c32ebe25fdc4d9bb12dc045da841a71161e81568/medusa/providers/generic_provider.py#L212">medusa/providers/generic_provider.py</a>", line 212, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/pi/Medusa/<a href="../blob/c32ebe25fdc4d9bb12dc045da841a71161e81568/medusa/providers/torrent/json/t411.py#L130">medusa/providers/torrent/json/t411.py</a>", line 130, in search
    results += self.parse(jdata, mode)
  File "/home/pi/Medusa/<a href="../blob/c32ebe25fdc4d9bb12dc045da841a71161e81568/medusa/providers/torrent/json/t411.py#L154">medusa/providers/torrent/json/t411.py</a>", line 154, in parse
    torrent_rows = sorted(unsorted_torrent_rows, key=itemgetter('added'), reverse=True)
TypeError: 'int' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [proc-singles](../tree/proc-singles)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@283a8f591f8910f66e6e4453398d65add7e8d5e0
**Link to Log**: https://gist.github.com/77169c26573f4471a57fafa7438a7d87
### ERROR
<pre>
2017-03-23 01:09:15 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BITHDTV] :: [283a8f5] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/bithdtv.py", line 142, in parse\n    title = cells[2].find(\'a\')[\'title\']\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/283a8f591f8910f66e6e4453398d65add7e8d5e0/medusa/providers/torrent/html/bithdtv.py#L142">medusa/providers/torrent/html/bithdtv.py</a>", line 142, in parse
    title = cells[2].find('a')['title']
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato can you fix this one?

**Comment by duramato** [comment]
I don't know what the issue is

**Comment by fernandog** [comment]
Cell[2] is None

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [binsearch_search](../tree/binsearch_search)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b99a467f0768139ffcf091b3207cfec607951a51
**Link to Log**: https://gist.github.com/7f1da9ad924494d8bdb76dd70c2b2c4f
### ERROR
<pre>
2017-04-25 04:36:33 ERROR    SEARCHQUEUE-BACKLOG-82616 :: [BinSearch] :: [b99a467] Unknown exception while searching BinSearch. Error: "'NoneType' object has no attribute '__getitem__'"
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/search/core.py#L547">medusa/search/core.py</a>", line 547, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/providers/generic_provider.py#L211">medusa/providers/generic_provider.py</a>", line 211, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/providers/nzb/binsearch.py#L91">medusa/providers/nzb/binsearch.py</a>", line 91, in search
    results += self.parse(response.text, mode)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/providers/nzb/binsearch.py#L128">medusa/providers/nzb/binsearch.py</a>", line 128, in parse
    nzb_id = col[1].find('input')['name']
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
