### ISSUE TITLE
SSL Import issues?

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/Medusa#1418]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Debian
What you did: @fernandog knows about this
What happened: Can't start Medusa in Develop mode
What you expected: for it to start.
Logs:
```
python ~/.sickrage/SickBeard.py -d --pidfile="$HOME/.sickrage/sickrage.pid"
Traceback (most recent call last):
  File "/media/sdq1/home/whipcracker/.sickrage/SickBeard.py", line 9, in <module>
    from start import Application
  File "/media/sdq1/home/whipcracker/.sickrage/start.py", line 101, in <module>
    import medusa as app
  File "/media/sdq1/home/whipcracker/.sickrage/medusa/__init__.py", line 32, in <module>
    import requests
  File "/media/sdq1/home/whipcracker/.sickrage/lib/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/media/sdq1/home/whipcracker/.sickrage/lib/requests/packages/urllib3/contrib/pyopenssl.py", l               ine 54, in <module>
    import OpenSSL.SSL
  File "/media/sdq1/home/whipcracker/.sickrage/lib/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/media/sdq1/home/whipcracker/.sickrage/lib/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'

```

**Comment by whipcracker** [comment]
@ratoaq2 - been told to tag you on this traceback issue.

**Comment by fernandog** [comment]
@ratoaq2 @medariox 
disabling ssl_verify and removing the pyopenssl commits works. no cafile error

**Comment by fernandog** [comment]
@whipcracker so, disable updates and keep `ssl_verify` disabled for now

**Comment by whipcracker** [comment]
Done and done. Updates were already disabled, so I just turned off notifications for now and confirmed that ssl_verify is set to 0. Will wait on the Develop branch until I hear back from one of you lot.

Cheers for the help, lads!

**Comment by ratoaq2** [comment]
This issue is not current anymore, using #1422 instead.
