### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1432]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@1d9e07aa7e8f1ae0bdc3f8cc8d0dc798b93e1b74
**Link to Log**: https://gist.github.com/4948fc9420a8b5fd93a152c75cf7a51c
### ERROR
<pre>
2016-11-01 15:42:23 ERROR    POSTPROCESSOR :: [1d9e07a] Unable to write file to /media/extssd/Shows/Gotham/Season 03/Gotham.S03E07.Mad.City.Red.Queen.1080p.HDTV.x264-DIMENSION.nfo - are you sure the folder is writable? error 28 : No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/1d9e07aa7e8f1ae0bdc3f8cc8d0dc798b93e1b74/medusa/metadata/generic.py#L450">medusa/metadata/generic.py</a>", line 450, in write_ep_file
    data.write(nfo_file, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._**********, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 944, in _serialize_xml
    write(_escape_cdata(elem.tail, encoding))
IOError: [Errno 28] No space left on device
</pre>

---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
@ratoaq2 shouldn't this be a thing of the past now? lol

**Comment by ratoaq2** [comment]
Fixed by #1437

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@1fdd694705afae43337fced099f2595575570fae
**Link to Log**: https://gist.github.com/490b22e717575c75bfcad4e5e08fe0f8
### ERROR
<pre>
2016-11-02 15:07:18 ERROR    SHOWQUEUE-REFRESH :: [1fdd694] Unable to write image to /media/extssd/Shows/Paul and Nick’s Big American Food Trip/season-all-poster.jpg: Exception generated: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/1fdd694705afae43337fced099f2595575570fae/medusa/metadata/generic.py#L695">medusa/metadata/generic.py</a>", line 695, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@1fdd694705afae43337fced099f2595575570fae
**Link to Log**: https://gist.github.com/7854914214d7375a6a816f1f35f492e5
### ERROR
<pre>
2016-11-02 15:07:04 ERROR    SHOWQUEUE-REFRESH :: [1fdd694] Unable to write image to /media/extssd/Shows/Paul and Nick’s Big American Food Trip/poster.jpg: Exception generated: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/1fdd694705afae43337fced099f2595575570fae/medusa/metadata/generic.py#L695">medusa/metadata/generic.py</a>", line 695, in _write_image
    outFile.write(image_data)
IOError: [Errno 28] No space left on device
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/indexer/tmdb](../tree/feature/indexer/tmdb)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3
**Link to Log**: https://gist.github.com/7aea1ca8f6e869f9b20f6ad1d13c6c95
### ERROR
<pre>
2016-11-14 22:02:52 ERROR    SEARCHQUEUE-MANUAL-75978 :: [d4746ea] Checking AniDB scene exceptions update failed for Billboard Music Awards. Error: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/medusa/scene_exceptions.py#L335">medusa/scene_exceptions.py</a>", line 335, in _get_anidb_exceptions
    anime = adba.Anime(None, name=show.name, tvdbid=show.indexerid, autoCorrectName=True)
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBAbstracter.py#L123">lib/adba/aniDBAbstracter.py</a>", line 123, in __init__
    self.tvDBMap = TvDBMap()
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBtvDBmaper.py#L32">lib/adba/aniDBtvDBmaper.py</a>", line 32, in __init__
    self.xmlMap = fileInfo.read_tvdb_map_xml(filePath)
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBfileInfo.py#L121">lib/adba/aniDBfileInfo.py</a>", line 121, in read_tvdb_map_xml
    if not get_anime_list_xml(filePath):
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBfileInfo.py#L93">lib/adba/aniDBfileInfo.py</a>", line 93, in get_anime_list_xml
    return download_file("https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list.xml", path)
  File "/home/home/SickRage/<a href="../blob/d4746eaedd0553bf2e0b4bcdea7c5fea9eaf51e3/lib/adba/aniDBfileInfo.py#L79">lib/adba/aniDBfileInfo.py</a>", line 79, in download_file
    fp.flush()
IOError: [Errno 28] No space left on device
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@b43c0243963b01bda683acdee3c96da0858c1da4
**Link to Log**: https://gist.github.com/278d6e2c6a7a4d2a3a088eeaad0f7199
### ERROR
<pre>
2016-11-25 17:14:01 ERROR    Thread-15 :: [b43c024] Zip extraction error: IOError(28, 'No space left on device')
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/b43c0243963b01bda683acdee3c96da0858c1da4/**********/helpers.py#L1094">**********/helpers.py</a>", line 1094, in restoreConfigZip
    zip_file.extract(member, targetDir)
  File "/usr/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/lib/python2.7/shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@6f3231a732fae94a05aa47c9d7dc227e0c2790f4
**Link to Log**: https://gist.github.com/2f41e072748eb7fc4c2d1f110dfe0d16
### ERROR
<pre>
2017-02-19 17:23:28 ERROR    Thread-16 :: [6f3231a] Error while manual downloading subtitles. Error: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/6f3231a732fae94a05aa47c9d7dc227e0c2790f4/medusa/server/web/home/handler.py#L2103">medusa/server/web/home/handler.py</a>", line 2103, in manual_search_subtitles
    new_manual_subtitle = subtitles.save_subtitle(tv_episode=ep_obj, subtitle_id=picked_id, video_path=video_path)
  File "/home/pi/Medusa/<a href="../blob/6f3231a732fae94a05aa47c9d7dc227e0c2790f4/medusa/subtitles.py#L363">medusa/subtitles.py</a>", line 363, in save_subtitle
    return save_subs(tv_episode, video, [subtitle], video_path=video_path)
  File "/home/pi/Medusa/<a href="../blob/6f3231a732fae94a05aa47c9d7dc227e0c2790f4/medusa/subtitles.py#L475">medusa/subtitles.py</a>", line 475, in save_subs
    single=not app.SUBTITLES_MULTI)
  File "/home/pi/Medusa/<a href="../blob/6f3231a732fae94a05aa47c9d7dc227e0c2790f4/lib/subliminal/core.py#L696">lib/subliminal/core.py</a>", line 696, in save_subtitles
    f.write(subtitle.content)
IOError: [Errno 28] No space left on device
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
All good right?

**Comment by duramato** [comment]
This should be a friendly warning, not a submitable error

**Comment by labrys** [comment]
Also to make sure that it doesn't crash the thread when the exception occurs.

**Comment by fernandog** [comment]
@ratoaq2 @medariox this PR should catch this right?

https://github.com/pymedusa/Medusa/pull/1520

any idea why its not as its a `IOError`.
Maybe because it was an issue in subliminal and not in medusa's code?

**Comment by fernandog** [comment]
https://github.com/pymedusa/Medusa/issues/2173

**Comment by ratoaq2** [comment]
It would catch if others didn't catch it first. That part of the code in subtitles.py has tons of try/except and this is logged by one of them

**Comment by fernandog** [comment]
this is one of the errors that could happen there:
https://github.com/pymedusa/Medusa/issues/1980

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [binsearch_search](../tree/binsearch_search)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b99a467f0768139ffcf091b3207cfec607951a51
**Link to Log**: https://gist.github.com/51d2dd94a7bae3b959a5814904315b22
### ERROR
<pre>
2017-04-25 15:51:29 ERROR    Thread-19 :: [b99a467] Error while manual downloading subtitles. Error: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/server/web/home/handler.py#L2245">medusa/server/web/home/handler.py</a>", line 2245, in manual_search_subtitles
    new_manual_subtitle = subtitles.save_subtitle(tv_episode=ep_obj, subtitle_id=picked_id, video_path=video_path)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/subtitles.py#L362">medusa/subtitles.py</a>", line 362, in save_subtitle
    return save_subs(tv_episode, video, [subtitle], video_path=video_path)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/subtitles.py#L462">medusa/subtitles.py</a>", line 462, in save_subs
    single=not app.SUBTITLES_MULTI)
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/lib/subliminal/core.py#L696">lib/subliminal/core.py</a>", line 696, in save_subtitles
    f.write(subtitle.content)
IOError: [Errno 28] No space left on device
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2668
