### ISSUE TITLE
Unexpected error in provider 'addic7ed'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#1446]
Searching PT-br subtitles

```
2016-11-01 22:23:20 WARNING  Thread-15 :: [f2b9ff3] Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/home/osmc/Medusa/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/home/osmc/Medusa/lib/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/home/osmc/Medusa/lib/subliminal/providers/addic7ed.py", line 256, in query
    language = Language.fromaddic7ed(cells[3].text)
  File "/home/osmc/Medusa/lib/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/home/osmc/Medusa/lib/babelfish/converters/__init__.py", line 240, in __getitem__
    self.converters[ep.name] = ep.load()()
  File "/home/osmc/Medusa/lib/pkg_resources.py", line 1957, in load
    if require: self.require(env, installer)
  File "/home/osmc/Medusa/lib/pkg_resources.py", line 1970, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/home/osmc/Medusa/lib/pkg_resources.py", line 569, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: futures>=3.0
```

```
pip show futures

---
Metadata-Version: 2.0
Name: futures
Version: 3.0.5
```

@ratoaq2 no idea what is the issue

**Comment by fernandog** [comment]
removing futures `pip uninstall futures` doesn't work

**Comment by fernandog** [comment]
I uninstalled local subliminal (not medusa lib) install and installed again.
Some how it worked again.
