### ISSUE TITLE
[APP SUBMITTED]: ParseError: not well-formed (invalid token): line 1, column 0

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#1459]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.10586`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@e7065496e182b1746b471ce584b09113ad3b0b4a
**Link to Log**: https://gist.github.com/7d72d52ca2efcdb93cb6598bebde6983
### ERROR
<pre>
2016-11-03 11:34:15 ERROR    SEARCHQUEUE-BACKLOG-247909 :: [NZBStars] :: [e706549] Unable to parse the XML of House.of.Lies.S05.720p.HDTV.x264, not splitting it
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\nzb_splitter.py", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 0
</pre>

---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
re-open if happens again.

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/6a1668217482f9cbe43cf2e2ed9a159a
### ERROR
<pre>
2017-07-19 10:47:31 ERROR    SEARCHQUEUE-BACKLOG-299350 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Casual.S02.FRENCH.720p.HDTV.x264-AMB3R, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/eb45847809593c3818e2c9fc083b5079
### ERROR
<pre>
2017-07-19 10:10:11 ERROR    SEARCHQUEUE-BACKLOG-81189 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Breaking.Bad.S03.MULTi.720p.BluRay.DTS.AC3.x264.BoO, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/0015f54cd35f4324c7b38f0d9c5f987e
### ERROR
<pre>
2017-07-19 10:03:07 ERROR    SEARCHQUEUE-BACKLOG-81189 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Breaking.Bad.S01.MULTi.720p.BluRay.DTS.AC3.x264.BoO, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/37953739d722dcf0602ca9d0a5f8afda
### ERROR
<pre>
2017-07-19 10:00:52 ERROR    SEARCHQUEUE-BACKLOG-253463 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Black.Mirror.S01.FRENCH.720p.NF.WEBRip.DD5.1.x264-FRATERNiTY, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/92b2d2b732385eb176d74afc56f42438
### ERROR
<pre>
2017-07-19 09:51:50 ERROR    SEARCHQUEUE-BACKLOG-257655 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Arrow.S02.FRENCH.720p.BluRay.x264-AUTHORiTY, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/8cd03f5229ceb840cbdd3f2f51adc67e
### ERROR
<pre>
2017-07-19 22:37:28 ERROR    SEARCHQUEUE-BACKLOG-212961 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Hell.On.Wheels.S02.MULTi.720p.BluRay.x264-JRabbit, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/4b7bea084c0792f9db018bd4a22be401
### ERROR
<pre>
2017-07-19 22:34:15 ERROR    SEARCHQUEUE-BACKLOG-328292 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Gypsy.S01.FRENCH.720p.NF.WEBRip.DD5.1.x264-FRATERNiTY, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/f2611a9ddbcac5685aafc5142fe922c5
### ERROR
<pre>
2017-07-19 22:21:21 ERROR    SEARCHQUEUE-BACKLOG-299350 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Casual.S02.FRENCH.720p.HDTV.x264-AMB3R, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/559ae9f3874ac696f9584cc746815fc8
### ERROR
<pre>
2017-07-19 22:01:16 ERROR    SEARCHQUEUE-BACKLOG-81189 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Breaking.Bad.S03.MULTi.720p.BluRay.DTS.AC3.x264.BoO, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/a319e668c547e6059496b08cdb5ace00
### ERROR
<pre>
2017-07-19 21:58:16 ERROR    SEARCHQUEUE-BACKLOG-253463 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Black.Mirror.S01.FRENCH.720p.NF.WEBRip.DD5.1.x264-FRATERNiTY, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/5fa7a45adeda068d4fd043ecf244cccf
### ERROR
<pre>
2017-07-19 21:52:21 ERROR    SEARCHQUEUE-BACKLOG-257655 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Arrow.S02.FRENCH.720p.BluRay.x264-AUTHORiTY, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/63a66a4456788f5ecdedb47d6c2b1492
### ERROR
<pre>
2017-07-19 18:13:38 ERROR    SEARCHQUEUE-BACKLOG-74845 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Weeds.S07.MULTI.720p.BluRay.x264-DWD, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/91944ab9994fe7efb97bf3d2daf93c80
### ERROR
<pre>
2017-07-19 18:07:39 ERROR    SEARCHQUEUE-BACKLOG-74845 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Weeds.S05.MULTI.720p.BluRay.x264-DWD, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/79a60b89218c4efab6cf3b9f4e9d60a7
### ERROR
<pre>
2017-07-19 18:04:24 ERROR    SEARCHQUEUE-BACKLOG-74845 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Weeds.S04.MULTI.720p.BluRay.x264-DWD, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/03d05e469e45ee4ac5965a29d35d9d9c
### ERROR
<pre>
2017-07-19 17:59:54 ERROR    SEARCHQUEUE-BACKLOG-74845 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Weeds.S03.MULTI.720p.BluRay.x264-DWD, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/fea075d74fcb61bcedc9578561eab3a4
### ERROR
<pre>
2017-07-19 17:56:00 ERROR    SEARCHQUEUE-BACKLOG-74845 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Weeds.S02.MULTI.720p.BluRay.x264-DWD, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/5cab6174cc2a467805aac4f105f8c50d
### ERROR
<pre>
2017-07-19 17:54:09 ERROR    SEARCHQUEUE-BACKLOG-74845 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Weeds.S01.REPACK.MULTI.720p.BluRay.x264-DWS, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/4a8a244ea84274bcb97a4ca02e3b5774
### ERROR
<pre>
2017-07-19 17:27:42 ERROR    SEARCHQUEUE-BACKLOG-79126 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of The.Wire.S05.FRENCH.720p.BluRay.x264-SODAPOP, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/aac072565187e67195c6703caab85d2a
### ERROR
<pre>
2017-07-19 17:23:42 ERROR    SEARCHQUEUE-BACKLOG-79126 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of The.Wire.S03.FRENCH.720p.BluRay.x264-VENUE, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/fd5cedcb393be5d1fe028cc8c8a54493
### ERROR
<pre>
2017-07-19 17:22:45 ERROR    SEARCHQUEUE-BACKLOG-79126 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of The.Wire.S02.FRENCH.720p.BluRay.x264-VENUE, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/42e108b87c18490af9d71ab6d44b9f4f
### ERROR
<pre>
2017-07-19 17:20:03 ERROR    SEARCHQUEUE-BACKLOG-79126 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of The.Wire.S01.FRENCH.720p.BluRay.x264-VENUE, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/b6a4ae22acbafe48c82dc04c66228985
### ERROR
<pre>
2017-07-19 15:12:15 ERROR    SEARCHQUEUE-BACKLOG-80379 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of The.Big.Bang.Theory.S08.FRENCH.720p.WEB-DL.H264-LiBERTY, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/715289e607fa2d03a1a43827c53e760a
### ERROR
<pre>
2017-07-19 13:22:11 ERROR    SEARCHQUEUE-BACKLOG-305288 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Stranger.Things.S01.FRENCH.720p.WEBRip.x264-SH0W, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/018ce32065b64472efff050b6a4f77cf
### ERROR
<pre>
2017-07-19 12:24:45 ERROR    SEARCHQUEUE-BACKLOG-264586 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Orange.Is.The.New.Black.S01.FRENCH.720p.BluRay.x264-AUTHORiTY, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/880480ba2bd338c4f33d5c1de2c95bb2
### ERROR
<pre>
2017-07-19 12:18:39 ERROR    SEARCHQUEUE-BACKLOG-273402 :: [J-eThor] :: [49e9fc3] Unable to parse the XML of Murder.In.The.First.S01.FRENCH.720p.WEB-DL.DD5.1.H264-LiBERTY, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OldMike** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.67-1-pve-x86_64-with-debian-8.8`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/411c6f17b6c04b81c59719b108768a2e
### ERROR
<pre>
2017-07-19 11:09:01 ERROR    SEARCHQUEUE-BACKLOG-269613 :: [J-Elite] :: [49e9fc3] Unable to parse the XML of Fargo.S02.FRENCH.REPACK.720p.WEBRiP.x264-MULTiGRP, not splitting it
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/nzb_splitter.py#L56">medusa/nzb_splitter.py</a>", line 56, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
