### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1486]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@cd82439ba29f036a02377cd759ce102d100b2245
**Link to Log**: https://gist.github.com/e226ae386eadf1f64978fffdb4957b70
### ERROR
<pre>
2016-11-06 14:08:52 ERROR    POSTPROCESSOR :: [cd82439] [Errno 13] Permission denied
Traceback (most recent call last):
  File "C:\Medusa\medusa\helpers.py", line 277, in copyFile
    shutil.copyfile(src_file, dest_file)
  File "C:\Medusa\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 13] Permission denied
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@a1c30b8f69f232c2f16abb28c10af64c799a185c
**Link to Log**: https://gist.github.com/c0efff3bd354f2b6c14817a6767cbec2
### ERROR
<pre>
2016-12-13 07:22:25 ERROR    Thread-33 :: [a1c30b8] [Errno 13] Permission denied
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\helpers.py", line 292, in copyFile
    shutil.copyfile(src_file, dest_file)
  File "C:\pymedusaSickRage\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 13] Permission denied
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
