### ISSUE TITLE
[APP SUBMITTED]: TypeError: expected string or buffer

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1489]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2
**Link to Log**: https://gist.github.com/e7fbc18c87d61531da87a1fb455f444e
### ERROR
<pre>
2016-11-06 06:29:49 ERROR    POSTPROCESSOR :: [f7926f8] Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/medusa/subtitles.py#L415">medusa/subtitles.py</a>", line 415, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/medusa/subtitles.py#L284">medusa/subtitles.py</a>", line 284, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/lib/subliminal/score.py#L106">lib/subliminal/score.py</a>", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/lib/subliminal/providers/opensubtitles.py#L78">lib/subliminal/providers/opensubtitles.py</a>", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/lib/subliminal/subtitle.py#L205">lib/subliminal/subtitle.py</a>", line 205, in guess_matches
    if video.title and 'episode_title' in guess and sanitize(guess['episode_title']) == sanitize(video.title):
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/lib/subliminal/utils.py#L125">lib/subliminal/utils.py</a>", line 125, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/medusa/subtitles.py#L415">medusa/subtitles.py</a>", line 415, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/medusa/subtitles.py#L284">medusa/subtitles.py</a>", line 284, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/lib/subliminal/score.py#L106">lib/subliminal/score.py</a>", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/lib/subliminal/providers/opensubtitles.py#L78">lib/subliminal/providers/opensubtitles.py</a>", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/lib/subliminal/subtitle.py#L205">lib/subliminal/subtitle.py</a>", line 205, in guess_matches
    if video.title and 'episode_title' in guess and sanitize(guess['episode_title']) == sanitize(video.title):
  File "/home/home/SickRage/<a href="../blob/f7926f8f4aaf60d9f970d6fb5d30c3c9ab9a5fd2/lib/subliminal/utils.py#L125">lib/subliminal/utils.py</a>", line 125, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
</pre>

---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [feature/search-show-lang-feedback](../tree/feature/search-show-lang-feedback)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@4b392abf8a7ddf8a66d9039f03db4260cd3d471c
**Link to Log**: https://gist.github.com/c9c64d1f0ea8e55b0145b0f847313a84
### ERROR
<pre>
2016-11-06 23:44:54 ERROR    POSTPROCESSOR :: [4b392ab] Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/medusa/subtitles.py#L415">medusa/subtitles.py</a>", line 415, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/medusa/subtitles.py#L284">medusa/subtitles.py</a>", line 284, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/lib/subliminal/score.py#L106">lib/subliminal/score.py</a>", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/lib/subliminal/providers/opensubtitles.py#L78">lib/subliminal/providers/opensubtitles.py</a>", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/lib/subliminal/subtitle.py#L205">lib/subliminal/subtitle.py</a>", line 205, in guess_matches
    if video.title and 'episode_title' in guess and sanitize(guess['episode_title']) == sanitize(video.title):
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/lib/subliminal/utils.py#L125">lib/subliminal/utils.py</a>", line 125, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/medusa/subtitles.py#L415">medusa/subtitles.py</a>", line 415, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/medusa/subtitles.py#L284">medusa/subtitles.py</a>", line 284, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/lib/subliminal/score.py#L106">lib/subliminal/score.py</a>", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/lib/subliminal/providers/opensubtitles.py#L78">lib/subliminal/providers/opensubtitles.py</a>", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/lib/subliminal/subtitle.py#L205">lib/subliminal/subtitle.py</a>", line 205, in guess_matches
    if video.title and 'episode_title' in guess and sanitize(guess['episode_title']) == sanitize(video.title):
  File "/home/home/SickRage/<a href="../blob/4b392abf8a7ddf8a66d9039f03db4260cd3d471c/lib/subliminal/utils.py#L125">lib/subliminal/utils.py</a>", line 125, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
Should be fixed by #1544

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@8d653a6165f7b40d69418f9c01be9125b2b83f4d
**Link to Log**: https://gist.github.com/9cb1e66062197bcba9fd3b17b5104825
### ERROR
<pre>
2016-11-24 07:19:08 ERROR    SHOWQUEUE-ADD :: [8d653a6] 17803 Error while loading information from indexer TVmaze. Error: 'expected string or buffer'
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\show_queue.py", line 348, in run
    s = t[self.indexer_id]
  File "C:\pymedusaSickRage\medusa\indexers\indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "C:\pymedusaSickRage\medusa\indexers\tvmaze\tvmaze_api.py", line 402, in _get_show_data
    self._get_episodes(tvmaze_id, specials=False, aired_season=None)
  File "C:\pymedusaSickRage\medusa\indexers\tvmaze\tvmaze_api.py", line 237, in _get_episodes
    results = self.API.episode_list(tvmaze_id, specials)
  File "C:\pymedusaSickRage\lib\pytvmaze\tvmaze.py", line 277, in episode_list
    return [Episode(self, episode) for episode in q]
  File "C:\pymedusaSickRage\lib\pytvmaze\tvmaze.py", line 553, in __init__
    self.summary = _remove_tags(data.get('summary'))
  File "C:\pymedusaSickRage\lib\pytvmaze\tvmaze.py", line 25, in _remove_tags
    return re_tag.sub('', text)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@8757d27bf361e334fa27b8d860bc80c9ac312f96
**Link to Log**: https://gist.github.com/6b14891dd1d4798dd483b8d6fe9361ed
### ERROR
<pre>
2016-11-27 18:52:50 ERROR    SHOWQUEUE-ADD :: [8757d27] 19669 Error while loading information from indexer TVmaze. Error: 'expected string or buffer'
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/8757d27bf361e334fa27b8d860bc80c9ac312f96/**********/show_queue.py#L348">**********/show_queue.py</a>", line 348, in run
    s = t[self.indexer_id]
  File "/home/home/SickRage/<a href="../blob/8757d27bf361e334fa27b8d860bc80c9ac312f96/**********/indexers/indexer_base.py#L254">**********/indexers/indexer_base.py</a>", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/home/SickRage/<a href="../blob/8757d27bf361e334fa27b8d860bc80c9ac312f96/**********/indexers/tvmaze/tvmaze_api.py#L402">**********/indexers/tvmaze/tvmaze_api.py</a>", line 402, in _get_show_data
    self._get_episodes(tvmaze_id, specials=False, aired_season=None)
  File "/home/home/SickRage/<a href="../blob/8757d27bf361e334fa27b8d860bc80c9ac312f96/**********/indexers/tvmaze/tvmaze_api.py#L237">**********/indexers/tvmaze/tvmaze_api.py</a>", line 237, in _get_episodes
    results = self.API.episode_list(tvmaze_id, specials)
  File "/home/home/SickRage/<a href="../blob/8757d27bf361e334fa27b8d860bc80c9ac312f96/lib/pytvmaze/tvmaze.py#L277">lib/pytvmaze/tvmaze.py</a>", line 277, in episode_list
    return [Episode(self, episode) for episode in q]
  File "/home/home/SickRage/<a href="../blob/8757d27bf361e334fa27b8d860bc80c9ac312f96/lib/pytvmaze/tvmaze.py#L553">lib/pytvmaze/tvmaze.py</a>", line 553, in __init__
    self.summary = _remove_tags(data.get('summary'))
  File "/home/home/SickRage/<a href="../blob/8757d27bf361e334fa27b8d860bc80c9ac312f96/lib/pytvmaze/tvmaze.py#L25">lib/pytvmaze/tvmaze.py</a>", line 25, in _remove_tags
    return re_tag.sub('', text)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
@p0psicles happen trying to add this [show](http://www.tvmaze.com/shows/19669/ice)

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jul 18 2016, 15:04:44) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@837556436e7138e4b62eceb2a0186f78c733d5ea
**Link to Log**: https://gist.github.com/582494f2fba6abc78512f1ad8fa97431
### ERROR
<pre>
2016-11-28 19:36:36 ERROR    SHOWQUEUE-ADD :: [8375564] 21941 Error while loading information from indexer TVmaze. Error: 'expected string or buffer'
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/**********/show_queue.py#L348">**********/show_queue.py</a>", line 348, in run
    s = t[self.indexer_id]
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/**********/indexers/indexer_base.py#L254">**********/indexers/indexer_base.py</a>", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/**********/indexers/tvmaze/tvmaze_api.py#L402">**********/indexers/tvmaze/tvmaze_api.py</a>", line 402, in _get_show_data
    self._get_episodes(tvmaze_id, specials=False, aired_season=None)
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/**********/indexers/tvmaze/tvmaze_api.py#L237">**********/indexers/tvmaze/tvmaze_api.py</a>", line 237, in _get_episodes
    results = self.API.episode_list(tvmaze_id, specials)
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/lib/pytvmaze/tvmaze.py#L277">lib/pytvmaze/tvmaze.py</a>", line 277, in episode_list
    return [Episode(self, episode) for episode in q]
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/lib/pytvmaze/tvmaze.py#L553">lib/pytvmaze/tvmaze.py</a>", line 553, in __init__
    self.summary = _remove_tags(data.get('summary'))
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/lib/pytvmaze/tvmaze.py#L25">lib/pytvmaze/tvmaze.py</a>", line 25, in _remove_tags
    return re_tag.sub('', text)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
@p0psicles

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jul 18 2016, 15:04:44) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@837556436e7138e4b62eceb2a0186f78c733d5ea
**Link to Log**: https://gist.github.com/a5c85a6e784d960fd9aeb5a9dea2d6ca
### ERROR
<pre>
2016-11-28 22:01:51 ERROR    SHOWQUEUE-ADD :: [8375564] 22541 Error while loading information from indexer TVmaze. Error: 'expected string or buffer'
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/**********/show_queue.py#L348">**********/show_queue.py</a>", line 348, in run
    s = t[self.indexer_id]
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/**********/indexers/indexer_base.py#L254">**********/indexers/indexer_base.py</a>", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/**********/indexers/tvmaze/tvmaze_api.py#L402">**********/indexers/tvmaze/tvmaze_api.py</a>", line 402, in _get_show_data
    self._get_episodes(tvmaze_id, specials=False, aired_season=None)
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/**********/indexers/tvmaze/tvmaze_api.py#L237">**********/indexers/tvmaze/tvmaze_api.py</a>", line 237, in _get_episodes
    results = self.API.episode_list(tvmaze_id, specials)
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/lib/pytvmaze/tvmaze.py#L277">lib/pytvmaze/tvmaze.py</a>", line 277, in episode_list
    return [Episode(self, episode) for episode in q]
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/lib/pytvmaze/tvmaze.py#L553">lib/pytvmaze/tvmaze.py</a>", line 553, in __init__
    self.summary = _remove_tags(data.get('summary'))
  File "/home/home/SickRage/<a href="../blob/837556436e7138e4b62eceb2a0186f78c733d5ea/lib/pytvmaze/tvmaze.py#L25">lib/pytvmaze/tvmaze.py</a>", line 25, in _remove_tags
    return re_tag.sub('', text)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed
