### ISSUE TITLE
[help please] Recuring error findsubtitles

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1513]
Branch/Commit: last dev
OS: Ubuntu 16.4 LTS
What you did: auto snatch after backlog search
What happened:
I have had this error for about 20 episodes now:
```
2016-11-08 08:27:19 ERROR    FINDSUBTITLES :: [b0731a1] Unable to move file /home/nicoleoca/Downloads/AutoDL/Black.Mirror.S03.COMPLETE.1080p.WEBRip.X264-DEFLATE-READ/Black.Mirror.S03E04.PROPER.1080p.WEBRip.X264-DEFLATE.mkv to /media/media/TV Shows/Black Mirror/Season 03/Black.Mirror.S03E04.PROPER.1080p.WEBRip.X264-DEFLATE.mkv: OSError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/opt/Medusa/medusa/post_processor.py", line 398, in _int_move
    helpers.moveFile(cur_file_path, new_file_path)
  File "/opt/Medusa/medusa/helpers.py", line 305, in moveFile
    os.unlink(src_file)
  File "/opt/Medusa/medusa/init/filesystem.py", line 85, in 
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))


OSError: [Errno 2] No such file or directory: '/home/nicoleoca/Downloads/AutoDL/Black.Mirror.S03.COMPLETE.1080p.WEBRip.X264-DEFLATE-READ/Black.Mirror.S03E04.PROPER.1080p.WEBRip.X264-DEFLATE.mkv'
```

Can you please help me to identify why?
I didn't move the file manually
It may have been moved by auto PP.

https://gist.github.com/NicoLeOca/4629e21d127d1e21abbeb4d14ed2e8b5

**Comment by medariox** [comment]
Still having this issue?

**Comment by NicoLeOca** [comment]
@medariox 
nope, not this one

but I get this very often:

````
2016-12-14 10:50:09 WARNING  FINDSUBTITLES :: [a1c30b8] Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Medusa\lib\subliminal\core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Medusa\lib\subliminal\providers\addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "C:\Medusa\lib\subliminal\providers\addic7ed.py", line 238, in query
    raise TooManyRequests()
TooManyRequests
2016-12-14 00:50:32 WARNING  FINDSUBTITLES :: [a1c30b8] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "C:\Medusa\lib\subliminal\core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Medusa\lib\subliminal\providers\opensubtitles.py", line 220, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "C:\Medusa\lib\subliminal\providers\opensubtitles.py", line 175, in query
    response = checked(self.server.SearchSubtitles(self.token, criteria))
  File "C:\Python27\lib\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "C:\Python27\lib\xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\lib\xmlrpclib.py", line 1313, in single_request
    response = h.getresponse(buffering=True)
  File "C:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "C:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "C:\Python27\lib\ssl.py", line 756, in recv
    return self.read(buflen)
  File "C:\Python27\lib\ssl.py", line 643, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)
````

**Comment by fernandog** [comment]
I already talked to @ratoaq2 about this.

We need to add some kind of req/s limit in addi7ed. maybe a sleep(2)

**Comment by NicoLeOca** [comment]
did addi7ed change their policy lately?
cause I don't have many episode waiting for subtitles.
And again, if knowit was used, it would detect that embedded would be english and medusa wouldn't try to get other subtitles

what about the opensubtitles error above?

**Comment by medariox** [comment]
Addic7ed is quite strict about request limits. I suggest you use another provider or disable logging for subtitles. Opensubtitles' issue is on their end, nothing we can do about that. Closing this issue as it's solved.
