### ISSUE TITLE
Renamer issue?

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#1555]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: develop
**OS: windows
**What you did: tried to rename files
**What happened: it did not rename files
**What you expected: for it to rename files
**Logs:**
```
2016-11-16 09:38:36 DEBUG    Thread-33 :: [32ca6ae] 314334: Renaming/moving episode from the base path F:\TV\SHOWS\Chappelle's Show\Season 03\Chappelle's.Show.dvdrip.S03E03.mkv to F:\TV\SHOWS\Chappelle's Show\Season 03\Chappelle's Show - S03E03 - Los
t Episode 3 (SD.DVD)
2016-11-16 09:38:36 ERROR    Thread-33 :: [32ca6ae] Exception generated: path is on drive F:, start on drive D:
Traceback (most recent call last):
  File "C:\SickRageMedusa\**********\server\web\core\base.py", line 271, in async_call
    result = function(**kwargs)
  File "C:\SickRageMedusa\**********\server\web\home\handler.py", line 1891, in doRename
    root_ep_obj.rename()
  File "C:\SickRageMedusa\**********\tv.py", line 3191, in rename
    related_files = post_processor.PostProcessor(self.location).list_associated_files(
  File "C:\SickRageMedusa\**********\post_processor.py", line 69, in __init__
    self.rel_path = self._get_rel_path()
  File "C:\SickRageMedusa\**********\post_processor.py", line 109, in _get_rel_path
    rel_path = os.path.relpath(self.file_path, app.TV_DOWNLOAD_DIR)
  File "C:\SickRageMedusa\**********\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\Python27\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive F:, start on drive D:
```

**Comment by wimpyrbx** [comment]
show is located at F:\TV\SHOWS\
not sure why it generates exception saying start on D:\

**Comment by medariox** [comment]
Will be fixed with https://github.com/pymedusa/Medusa/pull/1558
