### ISSUE TITLE
Unable to search on AnimeBytes

### ISSUE THREAD

**Issue by absinthewww** [pymedusa/Medusa#1577]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
master/b3a16bee625f6e48930e1dc66c8ddf8ac6ded394
**OS:**
Debian GNU/Linux 8.6
**What you did:**
Added an anime, manually searched it using AnimeBytes as provider
**What happened:**
The anime was not found
**What you expected:**
The anime to be found and snatched from AnimeBytes
**Logs:**
```
2016-11-17 15:00:36 ERROR    SEARCHQUEUE-FORCED-303073 :: [AnimeBytes] :: [b3a16be] Unknown exception while searching AnimeBytes. Error: "'NoneType' object has no attribute 'text'"
Traceback (most recent call last):
  File "/opt/**********/**********/search/core.py", line 562, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/opt/**********/**********/providers/generic_provider.py", line 187, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/opt/**********/**********/providers/torrent/html/animebytes.py", line 90, in search
    if not self.login():
  File "/opt/**********/**********/providers/torrent/html/animebytes.py", line 314, in login
    with BS4Parser(response.text, 'html5lib') as html:
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/1578
Thanks for the report.
