### ISSUE TITLE
Doesn't snatch if connection timeout to torrent client exists

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/Medusa#1644]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: Master - daf5388bff4c78985a98ac59ece113c59527df8e
**OS: Debian 8.6
**What you did: Nothing
**What happened: Episode snatched, but never made it to Deluge client
**What you expected: For it to end up downloading...

Basically it appeared that Medusa snatched the show successfully, called Deluge to drop the torrent onto it, but ended up with a HTTPS timeout for whatever reason. I assume that if this timeout happens, Medusa doesn't try to attempt to re-upload the torrent into Deluge again?

I guess the next point is this - Would enabling "Use failed downloads" tickbox sort this problem out in the future? This has never been a problem before, so I assume Medusa has always been able to call the Deluge client successfully each time and this could be a once-off, but just trying to sort it out either way.

**Logs:**
```
2016-11-23 02:11:07 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Transaction with 1 queries executed
2016-11-23 02:11:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] 72108: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> NCIS - 14x08 - Enemy Combatant - SDTV
2016-11-23 02:11:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Checking if we should stop searching for a better quality for for episode NCIS.S14E08.HDTV.x264-LOL
2016-11-23 02:11:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Deluge: Response to POST request is {"id": 5, "result": null, "error": null}
2016-11-23 02:11:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Deluge: Requested a POST connection to https://hestia.feralhosting.com/**********/deluge/json with Params: None Data: {"params": ["bab787d4cc06b3856be85cee9fafcd1fc84296bc", false], "method": "core.set_torrent_stop_at...
2016-11-23 02:11:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Deluge: Response to POST request is {"id": 2, "result": "bab787d4cc06b3856be85cee9fafcd1fc84296bc", "error": null}
2016-11-23 02:11:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Deluge: Requested a POST connection to https://hestia.feralhosting.com/**********/deluge/json with Params: None Data: {"params": ["NCIS.S14E08.HDTV.x264-LOL.torrent", "ZDg6YW5ub3VuY2U2ODpodHRwczovL3NzbC5pcHRvcnJlbnRzL...
2016-11-23 02:11:05 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Calling Deluge Client
2016-11-23 02:11:05 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] GET URL: https://iptorrents.eu/download.php/2073407/NCIS.S14E08.HDTV.x264-LOL.torrent [Status: 200]
2016-11-23 02:11:05 INFO     SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Downloading NCIS.S14E08.HDTV.x264-LOL with 126 seeders and 29 leechers from IPTorrents
2016-11-23 02:11:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Transaction with 1 queries executed
2016-11-23 02:11:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] 279121: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> The Flash (2014) - 3x07 - Killer Frost - SDTV
2016-11-23 02:11:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Checking if we should stop searching for a better quality for for episode The.Flash.2014.S03E07.HDTV.x264-LOL
2016-11-23 02:11:03 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Deluge: Connection Timeout HTTPSConnectionPool(host='hestia.feralhosting.com', port=443): Read timed out. (read timeout=120)
2016-11-23 02:09:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Deluge: Requested a POST connection to https://hestia.feralhosting.com/**********/deluge/json with Params: None Data: {"params": [true, false], "method": "core.set_torrent_stop_at_ratio", "id": 5}
2016-11-23 02:09:03 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Deluge: Connection Timeout HTTPSConnectionPool(host='hestia.feralhosting.com', port=443): Read timed out. (read timeout=120)
2016-11-23 02:07:02 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Deluge: Requested a POST connection to https://hestia.feralhosting.com/**********/deluge/json with Params: None Data: {"params": ["The.Flash.2014.S03E07.HDTV.x264-LOL.torrent", "ZDg6YW5ub3VuY2U2ODpodHRwczovL3NzbC5pcHR...
2016-11-23 02:07:02 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Calling Deluge Client
2016-11-23 02:07:02 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [daf5388] GET URL: https://iptorrents.eu/download.php/2073409/The.Flash.2014.S03E07.HDTV.x264-LOL.torrent [Status: 200]
2016-11-23 02:07:02 INFO     SEARCHQUEUE-DAILY-SEARCH :: [daf5388] Downloading The.Flash.2014.S03E07.HDTV.x264-LOL with 201 seeders and 47 leechers from IPTorrents
```

**Comment by NicoLeOca** [comment]
I get a similar issue
and these logs:

2016-11-23 06:56:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Traceback (most recent call last):
  File "/opt/Medusa/medusa/search/queue.py", line 411, in run
    self.success = snatchEpisode(search_result)
  File "/opt/Medusa/medusa/search/core.py", line 146, in snatchEpisode
    failed_history.logSnatch(result)
  File "/opt/Medusa/medusa/failed_history.py", line 203, in logSnatch
    logDate = datetime.datetime.today().strftime(History.date_format)
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2016-11-23 06:56:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Deluge: Response to POST request is {"id": 6, "result": null, "error": null}
2016-11-23 06:56:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Deluge: Requested a POST connection to http://163.172.217.195:9092/json with Params: None Data: {"params": ["9519185de40407db59f7399f5e39140ea99512e5", 0.0], "method": "core.set_torrent_stop_rati...
2016-11-23 06:56:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Deluge: Response to POST request is {"id": 5, "result": null, "error": null}
2016-11-23 06:56:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Deluge: Requested a POST connection to http://163.172.217.195:9092/json with Params: None Data: {"params": ["9519185de40407db59f7399f5e39140ea99512e5", true], "method": "core.set_torrent_stop_at_...
2016-11-23 06:56:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Deluge: Response to POST request is {"id": 2, "result": "9519185de40407db59f7399f5e39140ea99512e5", "error": null}
2016-11-23 06:56:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Deluge: Requested a POST connection to http://163.172.217.195:9092/json with Params: None Data: {"params": ["magnet:?xt=urn:btih:9519185de40407db59f7399f5e39140ea99512e5&dn=The.Wire.S04.1080p.Blu...
2016-11-23 06:56:10 DEBUG    SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Calling Deluge Client
2016-11-23 06:56:10 INFO     SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Downloading The.Wire.S04.1080p.BluRay.x264-ROVERS[rartv] with 3 seeders and 4 leechers from Rarbg
2016-11-23 06:56:10 INFO     SNATCHQUEUE-MANUALSNATCH-79126 :: [235685e] Beginning to manual snatch release: The.Wire.S04.1080p.BluRay.x264-ROVERS[rartv]

**Comment by fernandog** [comment]
It will keep trying until success.
You can see in history that there is no snatch there.

**Comment by NicoLeOca** [comment]
@fernandog 
You'are right
it did snatch later
thank you

**Comment by NicoLeOca** [comment]
@fernandog 
it looks like a new behaviour to me
what changed?

**Comment by fernandog** [comment]
this error `AttributeError: type object 'datetime.datetime' has no attribute 'datetime'` is already fixed in develop

**Comment by NicoLeOca** [comment]
@fernandog 
ok thanks
I wasn't sure as this issue wasn't closed and linked to the PR

**Comment by whipcracker** [comment]
For what it's worth, how long should I be waiting for it to snatch? I waited around 3 hours before I attempted to manually snatch... does the attempt to re-snatch depend on the "backlog search frequency" or something?

**Comment by fernandog** [comment]
@whipcracker if episode is backloged then it should be snatched in the next backlog search.

**Comment by whipcracker** [comment]
Backlog search is default 7 days mate... is that acceptable? What you think?

**Comment by labrys** [comment]
@whipcracker depends on how many episodes you have in your backlog and how frequently you want them searched for

**Comment by whipcracker** [comment]
I assume there's no optimal value for it, but as it's just the first time it's happened, I'm just trying to figure a way to fix it and snatch the episode earlier than usual, on the off-chance Medusa times out with the torrent client.

Can backlog search be set earlier than 1 day at all?

**Comment by whipcracker** [comment]
Sorry, I read that wrong... backlog search happens every 720 minutes but covers 7 days. 

All good, I'll bring the 720 mins down to 120 mins instead. Seem reasonable?

**Comment by fernandog** [comment]
@whipcracker just open /manage and hit force backlog

**Comment by whipcracker** [comment]
@fernandog , the plan is for this to do it automagically, one where less input from me is better. I understand that Medusa isn't perfect and all (works the best out of the lot) but just trying to understand how to circumvent the issue I'm having is all.

**Comment by fernandog** [comment]
backlog min is 720.
you just have to wait for the next backlog or force backlog. There is nothing much to do

**Comment by whipcracker** [comment]
@fernandog , check IRC lol... I'm uncertain if I've found a problem with how Medusa handles the HTTP timeout or not... discussing this with @medariox at the second.

Not trying to be a pain, just trying to understand and hopefully get a solution or some attention to the issue I had.

**Comment by whipcracker** [comment]
@fernandog ... some out takes of IRC chat.

Medusa knows it didn't get to add the torrent to the client, as it timed out (even has it in the logs). My question ultimately is what solution is needed so this doesn't happen in the future? I was merely asking if this is something that "failed downloads" did, or how Medusa would know to try a backlog search in 720 mins and cap that same torrent, even though it set itself to "snatched". Maybe the question is this - If Medusa can't add the torrent file because of a HTTP timeout for whatever reason, maybe Medusa should automatically set it back to "Wanted" instead? So that when the backlog search initiates, it'll look for wanted episodes... I can't see Medusa backlog searching for shows that are "technically" already snatched.

**Comment by whipcracker** [comment]
@fernandog ?

**Comment by fernandog** [comment]
medusa doesn't change status if can't send the snatch.

**Comment by whipcracker** [comment]
Well... it did.

It said "snatched" hence why it didn't try to snatch it when it couldn't upload the file to my torrent client... wouldn't have bothered raising this ticket if it worked mate! Just trying to fix a potential issue!

**Comment by fernandog** [comment]
@whipcracker all good now?

**Comment by whipcracker** [comment]
Can't say it's been a problem for a while. Close it off if you need (or have implemented a fix) cheers!

**Comment by fernandog** [comment]
ok, re-open if happens again
