### ISSUE TITLE
[APP SUBMITTED]: ShowNotFound: Maze id 295068 not found

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1648]
### INFO
**Python Version**: `2.7.11 (default, Apr 20 2016, 09:51:11) [GCC 4.7.2]`
**Operating System**: `Linux-3.2.0-4-686-pae-i686-with-debian-7.9`
**Locale**: `UTF-8`
**Branch**: [feature/indexer/tvmaze](../tree/feature/indexer/tvmaze)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@190e50bc1ae3931eeb6376793e489d4194d974b6
**Link to Log**: https://gist.github.com/0283080f487b3171f864598ac5f50f07
### ERROR
<pre>
2016-11-23 14:19:49 ERROR    SHOWQUEUE-ADD :: [190e50b] 295068 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/opt/medusa/medusa/show_queue.py", line 348, in run
    s = t[self.indexer_id]
  File "/home/opt/medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/opt/medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 384, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/opt/medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.API.get_show(tvmaze_id)
  File "/home/opt/medusa/lib/pytvmaze/tvmaze.py", line 109, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 295068 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec 12 2016, 13:32:24) [GCC 4.9.3]`
**Operating System**: `Linux-4.9.13-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/899e806b06f0b5a9ac4a9f0135b58d0c
### ERROR
<pre>
2017-03-14 18:22:57 ERROR    SHOWQUEUE-ADD :: [a011615] 265834 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/neko/Programs/Medusa/medusa/show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "/home/neko/Programs/Medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 412, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "/home/neko/Programs/Medusa/lib/pytvmaze/tvmaze.py", line 663, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 265834 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec 12 2016, 13:32:24) [GCC 4.9.3]`
**Operating System**: `Linux-4.9.13-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/cbb5366ea4a03c54ff125170dee8fac0
### ERROR
<pre>
2017-03-14 18:22:48 ERROR    SHOWQUEUE-ADD :: [a011615] 295779 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/neko/Programs/Medusa/medusa/show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "/home/neko/Programs/Medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 412, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "/home/neko/Programs/Medusa/lib/pytvmaze/tvmaze.py", line 663, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 295779 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec 12 2016, 13:32:24) [GCC 4.9.3]`
**Operating System**: `Linux-4.9.13-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/707e047ed5acf703b0574a0dfb3836f8
### ERROR
<pre>
2017-03-14 18:22:36 ERROR    SHOWQUEUE-ADD :: [a011615] 255316 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/neko/Programs/Medusa/medusa/show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "/home/neko/Programs/Medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 412, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "/home/neko/Programs/Medusa/lib/pytvmaze/tvmaze.py", line 663, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 255316 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec 12 2016, 13:32:24) [GCC 4.9.3]`
**Operating System**: `Linux-4.9.13-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/72684784c8283e77f588633af39b4d37
### ERROR
<pre>
2017-03-14 18:22:20 ERROR    SHOWQUEUE-ADD :: [a011615] 296762 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/neko/Programs/Medusa/medusa/show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "/home/neko/Programs/Medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 412, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "/home/neko/Programs/Medusa/lib/pytvmaze/tvmaze.py", line 663, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 296762 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec 12 2016, 13:32:24) [GCC 4.9.3]`
**Operating System**: `Linux-4.9.13-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/5280e2b2647addde21682527b1bd4196
### ERROR
<pre>
2017-03-14 18:22:17 ERROR    SHOWQUEUE-ADD :: [a011615] 320558 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/neko/Programs/Medusa/medusa/show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "/home/neko/Programs/Medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 412, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "/home/neko/Programs/Medusa/lib/pytvmaze/tvmaze.py", line 663, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 320558 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec 12 2016, 13:32:24) [GCC 4.9.3]`
**Operating System**: `Linux-4.9.13-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/8dcb400f36948001bed4ce144745fd11
### ERROR
<pre>
2017-03-14 18:22:14 ERROR    SHOWQUEUE-ADD :: [a011615] 320674 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/neko/Programs/Medusa/medusa/show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "/home/neko/Programs/Medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 412, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "/home/neko/Programs/Medusa/lib/pytvmaze/tvmaze.py", line 663, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 320674 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec 12 2016, 13:32:24) [GCC 4.9.3]`
**Operating System**: `Linux-4.9.13-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/b127254f4018cdd8e6a329f04acc1942
### ERROR
<pre>
2017-03-14 18:22:05 ERROR    SHOWQUEUE-ADD :: [a011615] 266398 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/neko/Programs/Medusa/medusa/show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "/home/neko/Programs/Medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 412, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "/home/neko/Programs/Medusa/lib/pytvmaze/tvmaze.py", line 663, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 266398 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by YogSottot** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec 12 2016, 13:32:24) [GCC 4.9.3]`
**Operating System**: `Linux-4.9.13-gentoo-nvidia-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/a06f81d045bb597486a9a5393b4c15a2
### ERROR
<pre>
2017-03-14 18:21:56 ERROR    SHOWQUEUE-ADD :: [a011615] 295684 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/neko/Programs/Medusa/medusa/show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "/home/neko/Programs/Medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 412, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/neko/Programs/Medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "/home/neko/Programs/Medusa/lib/pytvmaze/tvmaze.py", line 663, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 295684 not found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
