### ISSUE TITLE
Can't add show with tvmaze or tmdb when it has tvdb metadata.

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#1649]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:feature/indexer/tvmaze**
**OS: debian**
**What you did: I've already had show dragon ball super added using tvdb. Then I removed it, without removing files. Then I tried to add it through tvmaze. And using the existing folder. It would not add, and give the error below.**
**Logs:**
```
2016-11-23 14:19:49 ERROR    SHOWQUEUE-ADD :: [190e50b] 295068 Error while loading information from indexer TVmaze. Error: u''
Traceback (most recent call last):
  File "/home/opt/medusa/medusa/show_queue.py", line 348, in run
    s = t[self.indexer_id]
  File "/home/opt/medusa/medusa/indexers/indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/opt/medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 384, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "/home/opt/medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 218, in _get_show_by_id
    results = self.API.get_show(tvmaze_id)
  File "/home/opt/medusa/lib/pytvmaze/tvmaze.py", line 109, in get_show
    raise ShowNotFound(' ,'.join(errors))
ShowNotFound: Maze id 295068 not found
```

**Comment by p0psicles** [comment]
Fixed in latest commit. Had to rewrite part of the addExistingShow flow. As it was trying to 'reuse' the tvdb indexerid when adding as tvmaze show.
