### ISSUE TITLE
SHOWQUEUE-UPDATE :: [f50f2ca] DB error: OperationalError('near "indexer_id": syntax error',)

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#1664]
Using latest develop.

```
2016-11-25 11:28:46 ERROR    SHOWQUEUE-UPDATE :: [f50f2ca] DB error: OperationalError('near "indexer_id": syntax error',)
Traceback (most recent call last):
  File "/Users/**********/code/Medusa/medusa/db.py", line 106, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: near "indexer_id": syntax error
2016-11-25 11:28:46 ERROR    SHOWQUEUE-UPDATE :: [f50f2ca] DB error: near "indexer_id": syntax error
Traceback (most recent call last):
  File "/Users/**********/code/Medusa/medusa/db.py", line 266, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/Users/**********/code/Medusa/medusa/db.py", line 106, in _execute
    sql_results = self.connection.cursor().execute(query, args)
OperationalError: near "indexer_id": syntax error
```

**Comment by p0psicles** [comment]
Need rest of the logs. As I can't really see, what is causing the exception.

**Comment by fernandog** [comment]
@p0psicles isnt this the fix i found?

**Comment by p0psicles** [comment]
You might be right
