### ISSUE TITLE
[APP SUBMITTED]: IndexError: list index out of range

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1675]
### INFO
**Python Version**: `2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@617ad17ebd39c84054269f7a2a451cbc488f8fc5
**Link to Log**: https://gist.github.com/69fdacbf863b864733bcd1fa16b15429
### ERROR
<pre>
2016-11-26 00:57:09 ERROR    SEARCHQUEUE-BACKLOG-279271 :: [LimeTorrents] :: [617ad17] Unknown exception while searching LimeTorrents. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/617ad17ebd39c84054269f7a2a451cbc488f8fc5/**********/search/core.py#L560">**********/search/core.py</a>", line 560, in searchProviders
    down_cur_quality, manual_search, manual_search_type)
  File "/home/home/SickRage/<a href="../blob/617ad17ebd39c84054269f7a2a451cbc488f8fc5/**********/providers/generic_provider.py#L193">**********/providers/generic_provider.py</a>", line 193, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/<a href="../blob/617ad17ebd39c84054269f7a2a451cbc488f8fc5/**********/providers/torrent/html/limetorrents.py#L98">**********/providers/torrent/html/limetorrents.py</a>", line 98, in search
    results += self.parse(response.text, mode)
  File "/home/home/SickRage/<a href="../blob/617ad17ebd39c84054269f7a2a451cbc488f8fc5/**********/providers/torrent/html/limetorrents.py#L121">**********/providers/torrent/html/limetorrents.py</a>", line 121, in parse
    torrent_table = torrent_table[0 if mode == 'RSS' else 1]
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@c86d3aa8f2d6c96e494625e42809b78c2a778715
**Link to Log**: https://gist.github.com/ab216709f9410e3bfd11560ce382dbfb
### ERROR
<pre>
2016-11-27 01:13:45 ERROR    SEARCHQUEUE-MANUAL-91891 :: [LimeTorrents] :: [c86d3aa] Unknown exception while searching LimeTorrents. Error: 'list index out of range'
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/c86d3aa8f2d6c96e494625e42809b78c2a778715/**********/search/core.py#L560">**********/search/core.py</a>", line 560, in searchProviders
    down_cur_quality, manual_search, manual_search_type)
  File "/home/home/SickRage/<a href="../blob/c86d3aa8f2d6c96e494625e42809b78c2a778715/**********/providers/generic_provider.py#L193">**********/providers/generic_provider.py</a>", line 193, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/<a href="../blob/c86d3aa8f2d6c96e494625e42809b78c2a778715/**********/providers/torrent/html/limetorrents.py#L98">**********/providers/torrent/html/limetorrents.py</a>", line 98, in search
    results += self.parse(response.text, mode)
  File "/home/home/SickRage/<a href="../blob/c86d3aa8f2d6c96e494625e42809b78c2a778715/**********/providers/torrent/html/limetorrents.py#L121">**********/providers/torrent/html/limetorrents.py</a>", line 121, in parse
    torrent_table = torrent_table[0 if mode == 'RSS' else 1]
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/1684

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/remove_ratio_reached](../tree/feature/remove_ratio_reached)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@c805314903d16f7086d2c1d3d2c0daa8e613ee38
**Link to Log**: https://gist.github.com/693ef3888342d44fbd07e2172b9112b4
### ERROR
<pre>
2016-12-13 08:29:39 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BITHDTV] :: [c805314] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/bithdtv.py", line 133, in parse\n    title = cells[2].find(\'a\')[\'title\']\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/c805314903d16f7086d2c1d3d2c0daa8e613ee38/medusa/providers/torrent/html/bithdtv.py#L133">medusa/providers/torrent/html/bithdtv.py</a>", line 133, in parse
    title = cells[2].find('a')['title']
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
pubdate not yet in develop

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/remove_ratio_reached](../tree/feature/remove_ratio_reached)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@24bc313a70092bb358f925d043cc0900deae628c
**Link to Log**: https://gist.github.com/d93dbd2a487a9ee028c89a9238ee02ae
### ERROR
<pre>
2016-12-14 13:30:27 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BITHDTV] :: [24bc313] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/bithdtv.py", line 138, in parse\n    seeders = try_int(cells[8].get_text(strip=True))\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/24bc313a70092bb358f925d043cc0900deae628c/medusa/providers/torrent/html/bithdtv.py#L138">medusa/providers/torrent/html/bithdtv.py</a>", line 138, in parse
    seeders = try_int(cells[8].get_text(strip=True))
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
branch  feature/remove_ratio_reached is already updated with develop with that fix. please update

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/remove_ratio_reached](../tree/feature/remove_ratio_reached)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@24bc313a70092bb358f925d043cc0900deae628c
**Link to Log**: https://gist.github.com/2c190aef979567f4d731fcc210daebd1
### ERROR
<pre>
2016-12-14 03:37:17 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BITHDTV] :: [24bc313] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/bithdtv.py", line 139, in parse\n    leechers = try_int(cells[9].get_text(strip=True))\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/24bc313a70092bb358f925d043cc0900deae628c/medusa/providers/torrent/html/bithdtv.py#L139">medusa/providers/torrent/html/bithdtv.py</a>", line 139, in parse
    leechers = try_int(cells[9].get_text(strip=True))
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bangorbob** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]`
**Operating System**: `Linux-3.13.0-100-generic-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@daf5388bff4c78985a98ac59ece113c59527df8e
**Link to Log**: https://gist.github.com/07dec2c721a437a51cf2219861076754
### ERROR
<pre>
2016-12-15 10:34:18 ERROR    SEARCHQUEUE-BACKLOG-266631 :: [LimeTorrents] :: [daf5388] Unknown exception while searching LimeTorrents. Error: 'list index out of range'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/medusa/search/core.py#L562">medusa/search/core.py</a>", line 562, in searchProviders
    downCurQuality, manual_search, manual_search_type)
  File "/opt/medusa/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/medusa/providers/generic_provider.py#L187">medusa/providers/generic_provider.py</a>", line 187, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/opt/medusa/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/medusa/providers/torrent/html/limetorrents.py#L99">medusa/providers/torrent/html/limetorrents.py</a>", line 99, in search
    results += self.parse(response.text, mode)
  File "/opt/medusa/<a href="../blob/daf5388bff4c78985a98ac59ece113c59527df8e/medusa/providers/torrent/html/limetorrents.py#L122">medusa/providers/torrent/html/limetorrents.py</a>", line 122, in parse
    torrent_table = torrent_table[0 if mode == 'RSS' else 1]
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
@medariox this is fixed right? or fix is not on master yet?

**Comment by medariox** [comment]
@duramato 
It's fixed in develop and not on master yet.

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/fix-ui-scaling](../tree/feature/fix-ui-scaling)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@637e877e5efbc8a6fd2975a30e5feaa1af8f7225
**Link to Log**: https://gist.github.com/a3c9366673fca81f69c5bd686f9b1e59
### ERROR
<pre>
2017-01-03 11:56:11 ERROR    TORNADO :: [637e877] API :: list index out of range
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/637e877e5efbc8a6fd2975a30e5feaa1af8f7225/medusa/server/api/v1/core.py#L121">medusa/server/api/v1/core.py</a>", line 121, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/pi/Medusa/<a href="../blob/637e877e5efbc8a6fd2975a30e5feaa1af8f7225/medusa/server/api/v1/core.py#L190">medusa/server/api/v1/core.py</a>", line 190, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/pi/Medusa/<a href="../blob/637e877e5efbc8a6fd2975a30e5feaa1af8f7225/medusa/server/api/v1/core.py#L1629">medusa/server/api/v1/core.py</a>", line 1629, in run
    results.append({indexer_ids[_indexer]: int(cur_series['id']),
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
Happen while trying to search for a show with a third party app, ShowsRage to be specific

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/fix-show-updates](../tree/feature/fix-show-updates)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@8628e374bc1bf8ba76136cc463090f1c658b4837
**Link to Log**: https://gist.github.com/8e8ed03a7bc5280efdbb38eef764b9cc
### ERROR
<pre>
2017-01-03 23:12:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BITHDTV] :: [8628e37] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/bithdtv.py", line 143, in parse\n    seeders = try_int(cells[8].get_text(strip=True))\nIndexError: list index out of range\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/8628e374bc1bf8ba76136cc463090f1c658b4837/medusa/providers/torrent/html/bithdtv.py#L143">medusa/providers/torrent/html/bithdtv.py</a>", line 143, in parse
    seeders = try_int(cells[8].get_text(strip=True))
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
### INFO
**Python Version**: `2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.27-5-osmc-armv7l-with-debian-8.6`
**Locale**: `UTF-8`
**Branch**: [optimized](../tree/optimized)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@998e6942327604e69c9fbcebfbe11e633b31084e
**Link to Log**: https://gist.github.com/b50fbd79450e2c5825d4aff6886bbf02
### ERROR
<pre>
2017-01-04 19:44:08 ERROR    TORNADO :: [998e694] API :: list index out of range
Traceback (most recent call last):
  File "/home/osmc/Medusa/<a href="../blob/998e6942327604e69c9fbcebfbe11e633b31084e/medusa/server/api/v1/core.py#L121">medusa/server/api/v1/core.py</a>", line 121, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/osmc/Medusa/<a href="../blob/998e6942327604e69c9fbcebfbe11e633b31084e/medusa/server/api/v1/core.py#L190">medusa/server/api/v1/core.py</a>", line 190, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/osmc/Medusa/<a href="../blob/998e6942327604e69c9fbcebfbe11e633b31084e/medusa/server/api/v1/core.py#L1629">medusa/server/api/v1/core.py</a>", line 1629, in run
    results.append({indexer_ids[_indexer]: int(cur_series['id']),
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
