### ISSUE TITLE
[APP SUBMITTED]: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1701]
### INFO
**Python Version**: `2.7.12 (default, Jul 18 2016, 15:04:44) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@b88941f18a9edf16bb19c1ced166544ead7f8e17
**Link to Log**: https://gist.github.com/7c72df6db27a07d03dddceb7869d910c
### ERROR
<pre>
2016-11-28 22:40:59 ERROR    SEARCHQUEUE-MANUAL-21756 :: [BTN] :: [b88941f] Unknown error while accessing provider. Error: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/b88941f18a9edf16bb19c1ced166544ead7f8e17/**********/providers/torrent/json/btn.py#L255">**********/providers/torrent/json/btn.py</a>", line 255, in _api_call
    parsed_json = server.getTorrents(apikey, params or {}, int(results_per_page), int(offset))
  File "/home/home/SickRage/<a href="../blob/b88941f18a9edf16bb19c1ced166544ead7f8e17/lib/jsonrpclib/jsonrpc.py#L288">lib/jsonrpclib/jsonrpc.py</a>", line 288, in __call__
    return self.__send(self.__name, args)
  File "/home/home/SickRage/<a href="../blob/b88941f18a9edf16bb19c1ced166544ead7f8e17/lib/jsonrpclib/jsonrpc.py#L237">lib/jsonrpclib/jsonrpc.py</a>", line 237, in _request
    response = self._run_request(request)
  File "/home/home/SickRage/<a href="../blob/b88941f18a9edf16bb19c1ced166544ead7f8e17/lib/jsonrpclib/jsonrpc.py#L267">lib/jsonrpclib/jsonrpc.py</a>", line 267, in _run_request
    return_obj = loads(response)
  File "/home/home/SickRage/<a href="../blob/b88941f18a9edf16bb19c1ced166544ead7f8e17/lib/jsonrpclib/jsonrpc.py#L543">lib/jsonrpclib/jsonrpc.py</a>", line 543, in loads
    result = jloads(data)
  File "/home/home/SickRage/<a href="../blob/b88941f18a9edf16bb19c1ced166544ead7f8e17/lib/jsonrpclib/jsonrpc.py#L106">lib/jsonrpclib/jsonrpc.py</a>", line 106, in jloads
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/remove_ratio_reached](../tree/feature/remove_ratio_reached)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@24bc313a70092bb358f925d043cc0900deae628c
**Link to Log**: https://gist.github.com/a581ff81f09f4e9cba1e67ceb37fbd73
### ERROR
<pre>
2016-12-14 01:05:05 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [24bc313] Transmission: Failed Sending Torrent
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/24bc313a70092bb358f925d043cc0900deae628c/medusa/clients/generic.py#L238">medusa/clients/generic.py</a>", line 238, in send_torrent
    r_code = self._add_torrent_file(result)
  File "/home/pi/Medusa/<a href="../blob/24bc313a70092bb358f925d043cc0900deae628c/medusa/clients/transmission_client.py#L117">medusa/clients/transmission_client.py</a>", line 117, in _add_torrent_file
    return self.response.json()['result'] == 'success'
  File "/home/pi/Medusa/<a href="../blob/24bc313a70092bb358f925d043cc0900deae628c/lib/requests/models.py#L812">lib/requests/models.py</a>", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
seems daily conflicted with torrent checker while connecting to transmission

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [binsearch_search](../tree/binsearch_search)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b99a467f0768139ffcf091b3207cfec607951a51
**Link to Log**: https://gist.github.com/8e17661da07d76788aa49c94d484e421
### ERROR
<pre>
2017-04-28 18:00:34 ERROR    SNATCHQUEUE-MANUALSNATCH-26755 :: [b99a467] Transmission: Failed Sending Torrent
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/clients/torrent/generic.py#L288">medusa/clients/torrent/generic.py</a>", line 288, in send_torrent
    if result.priority != 0 and not self._set_torrent_priority(result):
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/medusa/clients/torrent/transmission_client.py#L183">medusa/clients/torrent/transmission_client.py</a>", line 183, in _set_torrent_priority
    return self.response.json()['result'] == 'success'
  File "/home/pi/Medusa/<a href="../blob/b99a467f0768139ffcf091b3207cfec607951a51/lib/requests/models.py#L812">lib/requests/models.py</a>", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@duramato problem is in _self_request in generic we don't check/validate if self.response before convert to json
