### ISSUE TITLE
[APP SUBMITTED]: TypeError: cannot serialize 60 (type int)

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1719]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.34-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@dd57c33e77ff6f7b3fac5db4b888336ddb3c3407
**Link to Log**: https://gist.github.com/e0e19276bb629584edc0a9ed0d65f163

Show: X-Ray Mega Airport
Indexer: Tvmaze

### ERROR
<pre>
2016-12-01 20:08:24 ERROR    SHOWQUEUE-REFRESH :: [dd57c33] 11478: Error while refreshing show X-Ray Mega Airport. Error: cannot serialize 60 (type int)
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/show_queue.py#L588">medusa/show_queue.py</a>", line 588, in run
    self.show.refresh_dir()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L1481">medusa/tv.py</a>", line 1481, in refresh_dir
    self.load_episodes_from_dir()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L727">medusa/tv.py</a>", line 727, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L1142">medusa/tv.py</a>", line 1142, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L2605">medusa/tv.py</a>", line 2605, in create_meta_files
    self.__create_nfo()
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/tv.py#L2617">medusa/tv.py</a>", line 2617, in __create_nfo
    result = cur_provider.create_episode_metadata(self) or result
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/generic.py#L254">medusa/metadata/generic.py</a>", line 254, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/home/pi/Medusa/<a href="../blob/dd57c33e77ff6f7b3fac5db4b888336ddb3c3407/medusa/metadata/generic.py#L451">medusa/metadata/generic.py</a>", line 451, in write_ep_file
    data.write(nfo_file, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._**********, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1075, in _escape_cdata
    _raise_serialization_error(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize 60 (type int)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
no idea about this one

**Comment by duramato** [comment]
@p0psicles

**Comment by p0psicles** [comment]
@duramato please test using the branch.
