### ISSUE TITLE
SHOWUPDATER :: [daf5388] Exception generated: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#1737]
Branch: master
Commit: daf5388bff4c78985a98ac59ece113c59527df8e
Version: v0.1.8.1
Database: 44.2
Python Version:	2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]
SSL Version:	OpenSSL 1.0.1f 6 Jan 2014
OS:	Linux-4.4.30-unRAID-x86_64-with-Ubuntu-14.04-trusty
Locale:	en_US.UTF-8
```
2016-12-04 03:01:51 ERROR    SHOWUPDATER :: [daf5388] Exception generated: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/app/sickrage/medusa/scheduler.py", line 103, in run
    self.action.run(self.force)
  File "/app/sickrage/medusa/show_updater.py", line 74, in run
    updated_shows = t.get_last_updated_series(last_update, update_max_weeks)
  File "/app/sickrage/medusa/indexers/tvdbv2/tvdbv2_api.py", line 511, in get_last_updated_series
    last_update_ts = max(x.last_updated for x in updates)
TypeError: 'NoneType' object is not iterable
```

**Comment by p0psicles** [comment]
Fixed in develop.
