### ISSUE TITLE
[APP SUBMITTED]: hostname 'api.thetvdb.com' doesn't match 'ssl440628.cloudflaressl.com'' (0)

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#1745]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@b6439a90aab82ec9adbd508c5be6ad07ab32d736
**Link to Log**: https://gist.github.com/b5532819af772cfa040b8b5911701695
### ERROR
<pre>
2016-12-07 03:00:35 ERROR    SHOWUPDATER :: [b6439a9] Exception generated: Indexer unavailable with reason 'SSLError
hostname 'api.thetvdb.com' doesn't match 'ssl440628.cloudflaressl.com'' (0)
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "C:\pymedusaSickRage\medusa\show_updater.py", line 60, in run
    t = indexerApi(show.indexer).indexer(**indexer_api_params)
  File "C:\pymedusaSickRage\medusa\indexers\indexer_api.py", line 34, in indexer
    return indexerConfig[self.indexer_id]['module'](*args, **kwargs)
  File "C:\pymedusaSickRage\medusa\indexers\tvdbv2\tvdbv2_api.py", line 72, in __init__
    raise IndexerUnavailable("Indexer unavailable with reason '%s' (%s)" % (e.reason, e.status))
IndexerUnavailable: Indexer unavailable with reason 'SSLError
hostname 'api.thetvdb.com' doesn't match 'ssl440628.cloudflaressl.com'' (0)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
pull 1751 fixes this for me
