### ISSUE TITLE
[APP SUBMITTED]: MaxRetryError: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /updated/query?fromTime=1481076044 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out.",))

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#1749]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@b6439a90aab82ec9adbd508c5be6ad07ab32d736
**Link to Log**: https://gist.github.com/207f701a783d6ed07f216d4e0e13aaa6
### ERROR
<pre>
2016-12-08 03:03:26 ERROR    SHOWUPDATER :: [b6439a9] Exception generated: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /updated/query?fromTime=1481076044 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out.",))
Traceback (most recent call last):
  File "C:\Medusa\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "C:\Medusa\medusa\show_updater.py", line 89, in run
    updated_shows = t.get_last_updated_series(last_update, update_max_weeks)
  File "C:\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 525, in get_last_updated_series
    updates = self.updates_api.updated_query_get(from_time).data
  File "C:\Medusa\lib\tvdbapiv2\apis\updates_api.py", line 130, in updated_query_get
    callback=params.get('callback'))
  File "C:\Medusa\lib\tvdbapiv2\api_client.py", line 324, in call_api
    response_type, auth_settings, callback)
  File "C:\Medusa\lib\tvdbapiv2\api_client.py", line 150, in __call_api
    post_params=post_params, body=body)
  File "C:\Medusa\lib\tvdbapiv2\api_client.py", line 344, in request
    headers=headers)
  File "C:\Medusa\lib\tvdbapiv2\rest.py", line 184, in GET
    query_params=query_params)
  File "C:\Medusa\lib\tvdbapiv2\rest.py", line 161, in request
    headers=headers)
  File "C:\Medusa\lib\requests\packages\urllib3\request.py", line 69, in request
    **urlopen_kw)
  File "C:\Medusa\lib\requests\packages\urllib3\request.py", line 90, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Medusa\lib\requests\packages\urllib3\poolmanager.py", line 165, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Medusa\lib\requests\packages\urllib3\connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\Medusa\lib\requests\packages\urllib3\connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\Medusa\lib\requests\packages\urllib3\connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "C:\Medusa\lib\requests\packages\urllib3\connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Medusa\lib\requests\packages\urllib3\util\retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /updated/query?fromTime=1481076044 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out.",))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/1751
