### ISSUE TITLE
[APP SUBMITTED]: IndexerUnavailable: Indexer unavailable with reason 'Origin Unreachable' (523)

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#1750]
### INFO
**Python Version**: `2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@b6439a90aab82ec9adbd508c5be6ad07ab32d736
**Link to Log**: https://gist.github.com/241073791dbc04fcc877ed166bd58e53
### ERROR
<pre>
2016-12-08 01:01:05 ERROR    SHOWUPDATER :: [b6439a9] Exception generated: Indexer unavailable with reason 'Origin Unreachable' (523)
Traceback (most recent call last):
  File "C:\pymedusaSickRage\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "C:\pymedusaSickRage\medusa\show_updater.py", line 60, in run
    t = indexerApi(show.indexer).indexer(**indexer_api_params)
  File "C:\pymedusaSickRage\medusa\indexers\indexer_api.py", line 34, in indexer
    return indexerConfig[self.indexer_id]['module'](*args, **kwargs)
  File "C:\pymedusaSickRage\medusa\indexers\tvdbv2\tvdbv2_api.py", line 72, in __init__
    raise IndexerUnavailable("Indexer unavailable with reason '%s' (%s)" % (e.reason, e.status))
IndexerUnavailable: Indexer unavailable with reason 'Origin Unreachable' (523)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ripper1967** [comment]
here is what i got for server status 
![eror](https://cloud.githubusercontent.com/assets/7034303/20999829/48c106f6-bce5-11e6-9c5d-2949e99a7d68.png)
none of my shows are auto updating

**Comment by ripper1967** [comment]
here is my server starus 
![error](https://cloud.githubusercontent.com/assets/7034303/20999891/b5bc7e02-bce5-11e6-9b4b-83f79cfedb8f.png) none of my shows are updating

**Comment by ripper1967** [comment]
pull 1751 fixes this for me
