### ISSUE TITLE
[APP SUBMITTED]: ValueError: String does not contain a date.

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/Medusa#1759]
### INFO
**Python Version**: `2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]`
**Operating System**: `Linux-4.4.30-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@c5c150457c6ad0fff685f7e83da77c55b0ef0a07
**Link to Log**: https://gist.github.com/29c3b0a209c80cd910d5904bdd278f65
### ERROR
<pre>
2016-12-09 19:22:40 ERROR    SEARCHQUEUE-FORCED-311816 :: [Hydra] :: [c5c1504] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/app/sickrage/medusa/providers/nzb/newznab.py", line 196, in search\n    pubdate = parser.parse(pubdate_raw, fuzzy=True) if pubdate_raw else None\n  File "/app/sickrage/lib/dateutil/parser.py", line 1168, in parse\n    return DEFAULTPARSER.parse(timestr, **kwargs)\n  File "/app/sickrage/lib/dateutil/parser.py", line 562, in parse\n    raise ValueError("String does not contain a date.")\nValueError: String does not contain a date.\n'
Traceback (most recent call last):
  File "/app/sickrage/medusa/providers/nzb/newznab.py", line 196, in search
    pubdate = parser.parse(pubdate_raw, fuzzy=True) if pubdate_raw else None
  File "/app/sickrage/lib/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/app/sickrage/lib/dateutil/parser.py", line 562, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@21ec574d66160255f9de95a78ad5742ac256cad5
**Link to Log**: https://gist.github.com/c213d69e3b27c17babdf62e2a30b5126
### ERROR
<pre>
2017-06-11 06:24:29 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [HDSpace] :: [21ec574] Failed parsing publishing date: Yesterday at Today at 
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/21ec574d66160255f9de95a78ad5742ac256cad5/medusa/providers/generic_provider.py#L512">medusa/providers/generic_provider.py</a>", line 512, in parse_pubdate
    dt = parser.parse(pubdate, fuzzy=True)
  File "/home/pi/Medusa/<a href="../blob/21ec574d66160255f9de95a78ad5742ac256cad5/lib/dateutil/parser.py#L1181">lib/dateutil/parser.py</a>", line 1181, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/pi/Medusa/<a href="../blob/21ec574d66160255f9de95a78ad5742ac256cad5/lib/dateutil/parser.py#L565">lib/dateutil/parser.py</a>", line 565, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
