### ISSUE TITLE
MaxRetryError: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /login (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#1781]
```
2016-12-13 03:05:01 ERROR    SHOWUPDATER :: [a1c30b8] Exception generated: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /login (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))
Traceback (most recent call last):
  File "/home/marx/medusa/medusa/scheduler.py", line 103, in run
    self.action.run(self.force)
  File "/home/marx/medusa/medusa/show_updater.py", line 62, in run
    t = indexerApi(show.indexer).indexer(**indexer_api_params)
  File "/home/marx/medusa/medusa/indexers/indexer_api.py", line 34, in indexer
    return indexerConfig[self.indexer_id]['module'](*args, **kwargs)
  File "/home/marx/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 69, in __init__
    access_token = auth_api.login_post(authentication_string)
  File "/home/marx/medusa/lib/tvdbapiv2/apis/authentication_api.py", line 124, in login_post
    callback=params.get('callback'))
  File "/home/marx/medusa/lib/tvdbapiv2/api_client.py", line 324, in call_api
    response_type, auth_settings, callback)
  File "/home/marx/medusa/lib/tvdbapiv2/api_client.py", line 150, in __call_api
    post_params=post_params, body=body)
  File "/home/marx/medusa/lib/tvdbapiv2/api_client.py", line 360, in request
    body=body)
  File "/home/marx/medusa/lib/tvdbapiv2/rest.py", line 208, in POST
    body=body)
  File "/home/marx/medusa/lib/tvdbapiv2/rest.py", line 143, in request
    headers=headers)
  File "/home/marx/medusa/lib/requests/packages/urllib3/request.py", line 73, in request
    **urlopen_kw)
  File "/home/marx/medusa/lib/requests/packages/urllib3/request.py", line 151, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/home/marx/medusa/lib/requests/packages/urllib3/poolmanager.py", line 165, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/marx/medusa/lib/requests/packages/urllib3/connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/marx/medusa/lib/requests/packages/urllib3/connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/marx/medusa/lib/requests/packages/urllib3/connectionpool.py", line 651, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/marx/medusa/lib/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/marx/medusa/lib/requests/packages/urllib3/util/retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Max retries exceeded with url: /login (Caused by ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')))
```

**Comment by medariox** [comment]
Duplicate of https://github.com/pymedusa/Medusa/issues/1569
