### ISSUE TITLE
[APP SUBMITTED]: WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'T:\\The Simpsons\\Season 12\\The Simpsons S12E09 HOM?.avi'

### ISSUE THREAD

**Issue by Xenocell12** [pymedusa/Medusa#1808]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.2`
**Commit**: pymedusa/Medusa@daf5388bff4c78985a98ac59ece113c59527df8e
**Link to Log**: https://gist.github.com/d60203a404a931358b8ccdc44bc2038c
### ERROR
<pre>
2016-12-18 23:12:35 ERROR    Thread-31 :: [daf5388] Unable to get size for file T:\The Simpsons\Season 12\The Simpsons S12E09 HOM?.avi Error: u'error 123 : The filename, directory name, or volume label syntax is incorrect'
Traceback (most recent call last):
  File "C:\Users\uTorrentVM\Medusa\medusa\helpers.py", line 1353, in get_size
    total_size += os.path.getsize(fp)
  File "C:\Users\uTorrentVM\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
  File "C:\Users\uTorrentVM\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'T:\\The Simpsons\\Season 12\\The Simpsons S12E09 HOM?.avi'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Xenocell12** [comment]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/e256290f773ec0f10eb232a226ebb77f
### ERROR
<pre>
2016-12-24 15:15:44 ERROR    Thread-35 :: [677b47a] Unable to get size for file T:\The Simpsons\Season 12\The Simpsons S12E09 HOM?.avi Error: u'error 123 : The filename, directory name, or volume label syntax is incorrect'
Traceback (most recent call last):
  File "C:\Users\uTorrentVM\Medusa\medusa\helpers.py", line 1326, in get_size
    total_size += os.path.getsize(fp)
  File "C:\Users\uTorrentVM\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
  File "C:\Users\uTorrentVM\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'T:\\The Simpsons\\Season 12\\The Simpsons S12E09 HOM?.avi'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Xenocell12** [comment]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/7c2e0298688a4030d6b1bc48c822a7fd
### ERROR
<pre>
2016-12-24 21:20:27 ERROR    Thread-32 :: [677b47a] Unable to get size for file T:\The Simpsons\Season 12\The Simpsons S12E09 HOM?.avi Error: u'error 123 : The filename, directory name, or volume label syntax is incorrect'
Traceback (most recent call last):
  File "C:\Users\uTorrentVM\Medusa\medusa\helpers.py", line 1326, in get_size
    total_size += os.path.getsize(fp)
  File "C:\Users\uTorrentVM\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
  File "C:\Users\uTorrentVM\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'T:\\The Simpsons\\Season 12\\The Simpsons S12E09 HOM?.avi'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
