### ISSUE TITLE
[APP SUBMITTED]: WindowsError: [Error 2] The system cannot find the file specified: "A:\\Yo-kai Watch\\Season 2\\Yo-kai Watch S02E08 Yo-Kai Kayukayu - Morezo Panic! - Jibanyan's Summer Vacation.mkv"

### ISSUE THREAD

**Issue by Xenocell12** [pymedusa/Medusa#1832]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.3`
**Commit**: pymedusa/Medusa@677b47ac1f6a75abc71c4472f3fb9c4eecb6413f
**Link to Log**: https://gist.github.com/c09a04ff82b43aefc8ff2ffe03fe4277
### ERROR
<pre>
2016-12-24 13:04:13 ERROR    Thread-35 :: [677b47a] Unable to get size for file A:\Yo-kai Watch\Season 2\Yo-kai Watch S02E08 Yo-Kai Kayukayu - Morezo Panic! - Jibanyan's Summer Vacation.mkv Error: u'error 2 : The system cannot find the file specified'
Traceback (most recent call last):
  File "C:\Users\uTorrentVM\Medusa\medusa\helpers.py", line 1326, in get_size
    total_size += os.path.getsize(fp)
  File "C:\Users\uTorrentVM\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\Python27\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
  File "C:\Users\uTorrentVM\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 2] The system cannot find the file specified: "A:\\Yo-kai Watch\\Season 2\\Yo-kai Watch S02E08 Yo-Kai Kayukayu - Morezo Panic! - Jibanyan's Summer Vacation.mkv"
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
@Xenocell12 
What are you doing to trigger this error?

**Comment by Xenocell12** [comment]
Sorry friend. And sorry for the spam. This occurred when adding existing shows. It's running on Windows 10 and to be honest I was having horrendous issues even with other python programs. I will close this. I am now running on Windows 8.1
