### ISSUE TITLE
torrentleech

### ISSUE THREAD

**Issue by jxer** [pymedusa/Medusa#1860]
2016-12-28 23:13:55 ERROR    SEARCHQUEUE-BACKLOG-75897 :: [TorrentLeech] :: [677b47a] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/**********/.sickrage/medusa/providers/torrent/html/torrentleech.py", line 145, in parse\n    download_url = urljoin(self.url, row.find(\'td\', class_=\'quickdownload\').find(\'a\')[\'href\'])\nTypeError: \'NoneType\' object has no attribute \'__getitem__\'\n'
Traceback (most recent call last):
  File "/home/**********/.sickrage/medusa/providers/torrent/html/torrentleech.py", line 145, in parse
    download_url = urljoin(self.url, row.find('td', class_='quickdownload').find('a')['href'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by medariox** [comment]
Already fixed in develop: https://github.com/pymedusa/Medusa/pull/1858
Will be released to master ASAP.
