### ISSUE TITLE
Add show from api not working

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1890]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/fix-ui-scaling](../tree/feature/fix-ui-scaling)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@637e877e5efbc8a6fd2975a30e5feaa1af8f7225
**Link to Log**: https://gist.github.com/a3c9366673fca81f69c5bd686f9b1e59
### ERROR
<pre>
2017-01-03 11:56:11 ERROR    TORNADO :: [637e877] API :: list index out of range
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/637e877e5efbc8a6fd2975a30e5feaa1af8f7225/medusa/server/api/v1/core.py#L121">medusa/server/api/v1/core.py</a>", line 121, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/pi/Medusa/<a href="../blob/637e877e5efbc8a6fd2975a30e5feaa1af8f7225/medusa/server/api/v1/core.py#L190">medusa/server/api/v1/core.py</a>", line 190, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/pi/Medusa/<a href="../blob/637e877e5efbc8a6fd2975a30e5feaa1af8f7225/medusa/server/api/v1/core.py#L1629">medusa/server/api/v1/core.py</a>", line 1629, in run
    results.append({indexer_ids[_indexer]: int(cur_series['id']),
IndexError: list index out of range
</pre>
Happens when trying to add a show via the api, in this case ShowsRage

**Comment by FireBladeNooT** [comment]
It seems I've the same problem:
````
2017-01-03 15:30:13 ERROR    SHOWQUEUE-ADD :: [677b47a] Error trying to add show: Could not connect to Trakt. No http status code
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/show_queue.py", line 434, in run
    newShow.load_from_indexer(t)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv.py", line 1275, in load_from_indexer
    self.externals.update(get_externals(self))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/helper/externals.py", line 113, in get_externals
    new_show_externals.update(get_trakt_externals(new_show_externals))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/helper/externals.py", line 67, in get_trakt_externals
    result = trakt_request(trakt_api, url)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/helper/externals.py", line 40, in trakt_request
    result = api.request(url) or []
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/traktor/trakt.py", line 156, in request
    raise TraktException(u'Could not connect to Trakt. No http status code')
TraktException: Could not connect to Trakt. No http status code
````
I'll not duplicate with an other issue.

**Comment by p0psicles** [comment]
Well actually that's a different issue. Will fix it.

**Comment by medariox** [comment]
@duramato Please close if it's fixed.
