### ISSUE TITLE
KeyError during refresh - references an episode belonging to a different series

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#1960]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**  Dev ce6db48
**OS:** Windows 10
**What you did:**  Nothing - auto show refresh triggered
**What happened:** KeyError with traceback raised during showqueue-refresh.  Key references an episode that does not exist for series being refreshed.
**What you expected:** No key error, and not to try episodes from other series for the current series being refreshed.
**Logs:**
```
2017-01-10 08:59:51 ERROR    SHOWQUEUE-REFRESH :: [ce6db48] 73787: Error while refreshing show That '70s Show. Error: u'The Unit [2006] - S02E11 - Silver Star'
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\show_queue.py", line 592, in run
    self.show.refresh_dir()
  File "H:\usr\local\medusa\medusa\tv.py", line 1505, in refresh_dir
    self.load_episodes_from_dir()
  File "H:\usr\local\medusa\medusa\tv.py", line 728, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "H:\usr\local\medusa\medusa\tv.py", line 1033, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "H:\usr\local\medusa\medusa\name_parser\parser.py", line 239, in parse
    name_parser_cache.add(name, result)
  File "H:\usr\local\medusa\medusa\name_parser\parser.py", line 430, in add
    del self._previous_parsed[self._previous_parsed.keys()[0]]
  File "C:\Python\latest\lib\collections.py", line 85, in __delitem__
    dict_delitem(self, key)
KeyError: u'The Unit [2006] - S02E11 - Silver Star'
```
While refreshing 'That 70's show' a key error was raised for 'The Unit [2006] - S02E11 - Silver Star' which is in a different folder entirely.  Confirmed that the files were not misplaced, and no incorrect references on Shows page nor in NFOs.

**Comment by p0psicles** [comment]
Debug logs?

**Comment by labrys** [comment]
Logs rolled over... that was from the error page.
