### ISSUE TITLE
[APP SUBMITTED]: gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#1980]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@49af1f0a36e3072f0ba468428f07d6c6b72e73fe
**Link to Log**: https://gist.github.com/14455435c7b93d06b4311aeee6229b1b
### ERROR
<pre>
2017-01-16 09:19:26 ERROR    FINDSUBTITLES :: [49af1f0] Unable to find subtitles for A Series of Unfortunate Events S01E03. Error: error -2 : Name or service not known
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/49af1f0a36e3072f0ba468428f07d6c6b72e73fe/medusa/subtitles.py#L1031">medusa/subtitles.py</a>", line 1031, in run
    episode_object.download_subtitles()
  File "/home/pi/Medusa/<a href="../blob/49af1f0a36e3072f0ba468428f07d6c6b72e73fe/medusa/tv.py#L2141">medusa/tv.py</a>", line 2141, in download_subtitles
    notifiers.notify_subtitle_download(self.pretty_name(), subtitle_list)
  File "/home/pi/Medusa/<a href="../blob/49af1f0a36e3072f0ba468428f07d6c6b72e73fe/medusa/notifiers/__init__.py#L82">medusa/notifiers/__init__.py</a>", line 82, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "/home/pi/Medusa/<a href="../blob/49af1f0a36e3072f0ba468428f07d6c6b72e73fe/medusa/notifiers/nma.py#L25">medusa/notifiers/nma.py</a>", line 25, in notify_subtitle_download
    message=ep_name + ": " + lang)
  File "/home/pi/Medusa/<a href="../blob/49af1f0a36e3072f0ba468428f07d6c6b72e73fe/medusa/notifiers/nma.py#L62">medusa/notifiers/nma.py</a>", line 62, in _sendNMA
    response = p.push(application=title, event=event, description=message, priority=nma_priority, batch_mode=batch)
  File "/home/pi/Medusa/<a href="../blob/49af1f0a36e3072f0ba468428f07d6c6b72e73fe/lib/pynma/pynma.py#L106">lib/pynma/pynma.py</a>", line 106, in push
    res = self.callapi('POST', ADD_PATH, datas)
  File "/home/pi/Medusa/<a href="../blob/49af1f0a36e3072f0ba468428f07d6c6b72e73fe/lib/pynma/pynma.py#L119">lib/pynma/pynma.py</a>", line 119, in callapi
    http_handler.request(method, path, urlencode(args), headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 841, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1242, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 what should be done to fix this?

**Comment by fernandog** [comment]
@medariox
Why did you reopened? Do you have any new logs?

**Comment by fernandog** [comment]
If you have issue open a new one please

**Comment by medariox** [comment]
Why do you want to close an issue that is not fixed?

**Comment by fernandog** [comment]
you communication skill sucks. you close without showing logs of the issue
can you submit the issue please?

**Comment by fernandog** [comment]
if you can't provide info, i will close again

**Comment by fernandog** [comment]
btw, if you think is not fixed, comment in the closed PR.

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/pull/2377#issuecomment-285871810
https://github.com/pymedusa/Medusa/pull/2377#issuecomment-285872824

......

**Comment by fernandog** [comment]
see how your communication sucks? why not link the comment in the first place?! lol
italians....

**Comment by medariox** [comment]
They may suck, but they are still better than your Python skills, that's for sure.

We wrote directly in the PR, if you didn't receive the notification emails that's your problem, not ours.

**Comment by labrys** [comment]
As mentioned in the closed PR `RequestException` does not catch `socket.gaierror` as shown below:
```python
>>> try:
	raise socket.gaierror
except requests.exceptions.RequestException:
	pass

Traceback (most recent call last):
  File "<pyshell#19>", line 2, in <module>
    raise socket.gaierror
socket.gaierror
```
Need to catch `socket.gaierror` instead.

**Comment by fernandog** [comment]
Ok thanks. In the beach house and will fix soon
