### ISSUE TITLE
Episode name initiating check for another show?

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2047]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** develop
**OS:** windows
**What you did:** showqueue refresh job ran automatically
**What happened:** error on episode for the middle called "The 100th" linked to show "The 100"
**What you expected:** for this not to happen
**Logs:**
```
2017-01-27 04:28:30 ERROR    SHOWQUEUE-REFRESH :: [4200445] 268592: Error while refreshing show The 100. Error: u'D:\\TV\\COMEDY SERIES\\The Middle\\Season 05\\The Middle - S05E04 - The 100th.mkv'
Traceback (most recent call last):
  File "C:\Gits\Medusa\medusa\show_queue.py", line 591, in run
    self.show.refresh_dir()
  File "C:\Gits\Medusa\medusa\tv.py", line 1470, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Gits\Medusa\medusa\tv.py", line 716, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "C:\Gits\Medusa\medusa\tv.py", line 1013, in make_ep_from_file
    'normal', 'anime')[self.is_anime]).parse(filepath)
  File "C:\Gits\Medusa\medusa\name_parser\parser.py", line 239, in parse
    name_parser_cache.add(name, result)
  File "C:\Gits\Medusa\medusa\name_parser\parser.py", line 430, in add
    del self._previous_parsed[self._previous_parsed.keys()[0]]
  File "C:\Python27\lib\collections.py", line 85, in __delitem__
    dict_delitem(self, key)
KeyError: u'D:\\TV\\COMEDY SERIES\\The Middle\\Season 05\\The Middle - S05E04 - The 100th.mkv'
```

**Comment by fernandog** [comment]
@ratoaq2 

```
$ python report_guessit.py D:\TV\COMEDY SERIES\The Middle\Season 05\The Middle - S05E04 - The 100th.mkv
ERROR:stevedore.extension:Could not load 'thesubdb': futures>=3.0
ERROR:stevedore.extension:futures>=3.0
Traceback (most recent call last):
  File "/home/osmc/Medusa/lib/stevedore/extension.py", line 163, in _load_plugins
    verify_requirements,
  File "/home/osmc/Medusa/lib/stevedore/extension.py", line 186, in _load_one_plugin
    plugin = ep.load(require=verify_requirements)
  File "/home/osmc/Medusa/lib/pkg_resources.py", line 1958, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/osmc/Medusa/lib/subliminal/providers/thesubdb.py", line 38, in <module>
    class TheSubDBProvider(Provider):
  File "/home/osmc/Medusa/lib/subliminal/providers/thesubdb.py", line 40, in TheSubDBProvider
    languages = {Language.fromthesubdb(l) for l in language_converters['thesubdb'].codes}
  File "/home/osmc/Medusa/lib/babelfish/converters/__init__.py", line 240, in __getitem__
    self.converters[ep.name] = ep.load()()
  File "/home/osmc/Medusa/lib/pkg_resources.py", line 1957, in load
    if require: self.require(env, installer)
  File "/home/osmc/Medusa/lib/pkg_resources.py", line 1970, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/home/osmc/Medusa/lib/pkg_resources.py", line 569, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
DistributionNotFound: futures>=3.0
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
# show list: ['SERIESThe', 'MiddleSeason', '05The', 'Middle', '-', 'S05E04', '-', 'The', '100th.mkv']
? D:TVCOMEDY
  title: D:TVCOMEDY
  type: episode
  parsing_time: 0.253559112549

```

**Comment by ratoaq2** [comment]
This issue is not related to guessit at all:

```
python tests/report_guessit.py "D:/TV/COMEDY SERIES/The Middle/Season 05/The Middle - S05E04 - The 100th.mkv" "The 100"
# guessit: 2.1.2.dev0  rebulk: 0.8.3.dev0
# show list: ['The 100']
? D:/TV/COMEDY SERIES/The Middle/Season 05/The Middle - S05E04 - The 100th.mkv
  title: The Middle
  season: 5
  episode: 4
  episode_title: The 100th
  container: mkv
  mimetype: video/x-matroska
  type: episode
  parsing_time: 0.0685911178589
```

Maybe indexer search or something similar is getting the wrong show

**Comment by medariox** [comment]
This should be fixed. @wimpyrbx?

**Comment by fernandog** [comment]
https://github.com/pymedusa/Medusa/issues/1960
