### ISSUE TITLE
Exception generated: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#2106]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** develop / https://github.com/pymedusa/Medusa/commit/3e0273a8d115ddc9c2c730d01a1772c3a25a9591
**OS:** Debian 8.7
**What happened:** SHOWUPDATER run
**What you expected:** The exception to be caught
**Logs:**
```
2017-02-06 03:17:27 ERROR    SHOWUPDATER :: [3e0273a] Exception generated: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /updates/shows (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out',))",),)
Traceback (most recent call last):
  File "/home/marx/medusa/medusa/scheduler.py", line 103, in run
    self.action.run(self.force)
  File "/home/marx/medusa/medusa/show_updater.py", line 86, in run
    update_max_weeks)
  File "/home/marx/medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 460, in get_last_updated_series
    updates = self._get_all_updates(from_time, from_time + (weeks * 604800))  # + seconds in a week
  File "/home/marx/medusa/medusa/indexers/tvmaze/tvmaze_api.py", line 440, in _get_all_updates
    updates = self.tvmaze_api.show_updates()
  File "/home/marx/medusa/lib/pytvmaze/tvmaze.py", line 1177, in show_updates
    q = self._endpoint_standard_get(url)
  File "/home/marx/medusa/lib/pytvmaze/tvmaze.py", line 540, in _endpoint_standard_get
    raise ConnectionError(repr(e))
ConnectionError: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /updates/shows (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out',))",),)
```

**Comment by medariox** [comment]
Should be fixed with https://github.com/pymedusa/Medusa/pull/2128
