### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2109]
Branch: feature/fix-pnotify-unicode rebased with latest develop

Deletes/renames cache.db and run manually search

```
2017-02-06 10:29:44 INFO     SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Performing episode search for Hannibal
2017-02-06 10:29:44 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Search mode: Episode
2017-02-06 10:29:44 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Search string: Hannibal S01E04
2017-02-06 10:29:44 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Searching only confirmed torrents
2017-02-06 10:29:45 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] GET URL: https://www.limetorrents.cc/search/tv/Hannibal%20S01E04/ [Status: 200]
2017-02-06 10:29:46 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Discarding torrent because it doesn't meet the minimum seeders: Hannibal S01E04 PDTV x264-BATV [VTV]. Seeders: 0
2017-02-06 10:29:46 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Discarding torrent because it doesn't meet the minimum seeders: Hannibal S01E04 720p HDTV x264-MoTv mkv [eztv]. Seeders: 0
2017-02-06 10:29:46 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Discarding torrent because it doesn't meet the minimum seeders: Hannibal S01E04 Ceuf WebRip x264-ANON [eztv]. Seeders: 0
2017-02-06 10:29:46 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Discarding torrent because it doesn't meet the minimum seeders: Hannibal S01E04 Ceuf WebRip x264-ANON [eztv]. Seeders: 0
2017-02-06 10:29:46 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [LimeTorrents] :: [51ff22a] Discarding torrent because it doesn't meet the minimum seeders: Hannibal S01E04 Ceuf WebRip x264-ANON [eztv]. Seeders: 0
2017-02-06 10:29:46 INFO     SEARCHQUEUE-MANUAL-259063 :: [ExtraTorrent] :: [51ff22a] Performing episode search for Hannibal
2017-02-06 10:29:46 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [ExtraTorrent] :: [51ff22a] Search mode: Episode
2017-02-06 10:29:46 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [ExtraTorrent] :: [51ff22a] Search string: Hannibal S01E04
2017-02-06 10:29:47 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [ExtraTorrent] :: [51ff22a] GET URL: http://extratorrent.cc/search/?y=0&new=1&search=Hannibal+S01E04&x=0 [Status: 200]
2017-02-06 10:29:48 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [ExtraTorrent] :: [51ff22a] Data returned from provider does not contain any torrents
2017-02-06 10:29:48 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [51ff22a] Found codec for Hannibal Œuf
2017-02-06 10:29:48 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [51ff22a] 259063: Formatting pattern: %SN - S%0SE%0E - %EN -> Hannibal - S01E04 - Œuf
2017-02-06 10:29:48 INFO     SEARCHQUEUE-MANUAL-259063 :: [51ff22a] Unable to find manual results for: [Hannibal - S01E04 - Œuf]
2017-02-06 10:30:26 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [51ff22a] Found codec for Hannibal Œuf
2017-02-06 10:30:26 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [51ff22a] 259063: Formatting pattern: %SN - S%0SE%0E - %EN -> Hannibal - S01E04 - Œuf
2017-02-06 10:30:26 INFO     SEARCHQUEUE-MANUAL-259063 :: [51ff22a] Beginning manual search for: [Hannibal - S01E04 - Œuf]
2017-02-06 10:30:26 INFO     SEARCHQUEUE-MANUAL-259063 :: [51ff22a] Updating exception_cache and exception_season_cache
2017-02-06 10:30:26 INFO     SEARCHQUEUE-MANUAL-259063 :: [51ff22a] Finished processing 2396 scene exceptions.
2017-02-06 10:30:26 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [51ff22a] Building internal name cache for Hannibal
2017-02-06 10:30:26 DEBUG    SEARCHQUEUE-MANUAL-259063 :: [51ff22a] Traceback (most recent call last):
  File "C:/Users/Fernando/Documents/Medusa\medusa\search\queue.py", line 322, in run
    self.manual_search, self.manual_search_type)
  File "C:/Users/Fernando/Documents/Medusa\medusa\search\core.py", line 483, in search_providers
    name_cache.build_name_cache(show)
  File "C:/Users/Fernando/Documents/Medusa\medusa\name_cache.py", line 133, in build_name_cache
    _cache_name(show)
  File "C:/Users/Fernando/Documents/Medusa\medusa\name_cache.py", line 101, in _cache_name
    clear_cache(indexer_id)
  File "C:/Users/Fernando/Documents/Medusa\medusa\name_cache.py", line 80, in clear_cache
    for key in to_remove:
  File "C:/Users/Fernando/Documents/Medusa\medusa\name_cache.py", line 76, in <genexpr>
    key
RuntimeError: dictionary changed size during iteration
```

**Comment by fernandog** [comment]
i have no idea about this one

**Comment by fernandog** [comment]
shouldn't the `clear_cache`  be called inside the nameCacheLock after all name caches are created?
