### ISSUE TITLE
Error on nfo creation?

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2125]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** develop
**OS:** windows
**What you did:** rescan files
**What happened:** new files were matched, but no nfo created
**What you expected:** nfo to be created
**Logs:**
```
2017-02-08 04:28:50 ERROR    SHOWQUEUE-REFRESH :: [5df71dd] 164541: Error while refreshing show Hawaii Five-0. Error: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '37', 'X-Powered-By': 'Thundar!', 'Set-Cookie': '__cfduid=d8298d70c9d8e0cfd04812a566f424dff1486524532; expires=Thu, 08-Feb-18 03:28:52 GMT; path=/; domain=.thetvdb.com; HttpOnly', 'Vary': 'Accept-Language', 'X-Thetvdb-Api-Version': '2.1.2', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=600', 'Date': 'Wed, 08 Feb 2017 03:28:52 GMT', 'CF-RAY': '32dbfe76fc044261-OSL', 'Server': 'cloudflare-nginx', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {
  "Error": "ID: 164541 not found"
}
Traceback (most recent call last):
  File "C:\Gits\Medusa\medusa\show_queue.py", line 591, in run
    self.show.refresh_dir()
  File "C:\Gits\Medusa\medusa\tv.py", line 1489, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Gits\Medusa\medusa\tv.py", line 716, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "C:\Gits\Medusa\medusa\tv.py", line 1150, in make_ep_from_file
    root_ep.create_meta_files()
  File "C:\Gits\Medusa\medusa\tv.py", line 2613, in create_meta_files
    self.__create_nfo(metadata_provider)
  File "C:\Gits\Medusa\medusa\tv.py", line 2626, in __create_nfo
    result = metadata_provider.create_episode_metadata(self) or result
  File "C:\Gits\Medusa\medusa\metadata\generic.py", line 261, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "C:\Gits\Medusa\medusa\metadata\generic.py", line 443, in write_ep_file
    data = self._ep_data(ep_obj)
  File "C:\Gits\Medusa\medusa\metadata\kodi_12plus.py", line 221, in _ep_data
    my_show = self._get_show_data(ep_obj.show)
  File "C:\Gits\Medusa\medusa\metadata\generic.py", line 846, in _get_show_data
    my_show = self.indexer_api[int(show_id)]
  File "C:\Gits\Medusa\medusa\indexers\indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "C:\Gits\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 513, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "C:\Gits\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 199, in _get_show_by_id
    results = self.series_api.series_id_get(tvdbv2_id, accept_language=request_language)
  File "C:\Gits\Medusa\lib\tvdbapiv2\apis\series_api.py", line 126, in series_id_get
    callback=params.get('callback'))
  File "C:\Gits\Medusa\lib\tvdbapiv2\api_client.py", line 324, in call_api
    response_type, auth_settings, callback)
  File "C:\Gits\Medusa\lib\tvdbapiv2\api_client.py", line 150, in __call_api
    post_params=post_params, body=body)
  File "C:\Gits\Medusa\lib\tvdbapiv2\api_client.py", line 344, in request
    headers=headers)
  File "C:\Gits\Medusa\lib\tvdbapiv2\rest.py", line 184, in GET
    query_params=query_params)
  File "C:\Gits\Medusa\lib\tvdbapiv2\rest.py", line 177, in request
    raise ApiException(http_resp=r)
ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '37', 'X-Powered-By': 'Thundar!', 'Set-Cookie': '__cfduid=d8298d70c9d8e0cfd04812a566f424dff1486524532; expires=Thu, 08-Feb-18 03:28:52 GMT; path=/; domain=.thetvdb.com; HttpOnly', 'Vary': 'Accept-Language', 'X-Thetvdb-Api-Version': '2.1.2', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=600', 'Date': 'Wed, 08 Feb 2017 03:28:52 GMT', 'CF-RAY': '32dbfe76fc044261-OSL', 'Server': 'cloudflare-nginx', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {
  "Error": "ID: 164541 not found"
}

```

worth mentioning that 164541 is the ID for this show on thetvdb.com
http://thetvdb.com/?id=164541&tab=series

**Comment by wimpyrbx** [comment]
2017-02-08 04:27:39 WARNING  SHOWQUEUE-REFRESH :: [5df71dd] TVDBv2 is down, can't use its data to add this show

this might be related. however i was able to open thetvdb.com just fine from here. api down perhaps.. although i see it happened after i updated to latest develop earlier today.

2017-02-08 03:54:47 WARNING  POSTPROCESSOR :: [63f66cd] TVDBv2 is down, can't use its data to add this show
2017-02-08 03:44:47 WARNING  POSTPROCESSOR :: [63f66cd] TVDBv2 is down, can't use its data to add this show

**Comment by wimpyrbx** [comment]
related?

```
2017-02-08 18:47:48 ERROR    SHOWQUEUE-REFRESH :: [5df71dd] 247773: Error while refreshing show Switched at Birth. Error: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '92', 'X-Powered-By': 'Thundar!', 'Set-Cookie': '__cfduid=d2949ad40dc90d75339e8e2fc2c646ee71486576072; expires=Thu, 08-Feb-18 17:47:52 GMT; path=/; domain=.thetvdb.com; HttpOnly', 'Vary': 'Accept-Language', 'X-Thetvdb-Api-Version': '2.1.2', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=600', 'Date': 'Wed, 08 Feb 2017 17:47:52 GMT', 'CF-RAY': '32e0e8c43bf916d6-ARN', 'Server': 'cloudflare-nginx', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {
  "Error": "Error 1030: Got error 24 \"Too many open files\" from storage engine MyISAM"
}
Traceback (most recent call last):
  File "C:\Gits\Medusa\medusa\show_queue.py", line 591, in run
    self.show.refresh_dir()
  File "C:\Gits\Medusa\medusa\tv.py", line 1489, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Gits\Medusa\medusa\tv.py", line 716, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "C:\Gits\Medusa\medusa\tv.py", line 1150, in make_ep_from_file
    root_ep.create_meta_files()
  File "C:\Gits\Medusa\medusa\tv.py", line 2613, in create_meta_files
    self.__create_nfo(metadata_provider)
  File "C:\Gits\Medusa\medusa\tv.py", line 2626, in __create_nfo
    result = metadata_provider.create_episode_metadata(self) or result
  File "C:\Gits\Medusa\medusa\metadata\generic.py", line 261, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "C:\Gits\Medusa\medusa\metadata\generic.py", line 443, in write_ep_file
    data = self._ep_data(ep_obj)
  File "C:\Gits\Medusa\medusa\metadata\kodi_12plus.py", line 221, in _ep_data
    my_show = self._get_show_data(ep_obj.show)
  File "C:\Gits\Medusa\medusa\metadata\generic.py", line 846, in _get_show_data
    my_show = self.indexer_api[int(show_id)]
  File "C:\Gits\Medusa\medusa\indexers\indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "C:\Gits\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 539, in _get_show_data
    self._parse_actors(sid)
  File "C:\Gits\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 471, in _parse_actors
    actors = self.series_api.series_id_actors_get(sid)
  File "C:\Gits\Medusa\lib\tvdbapiv2\apis\series_api.py", line 285, in series_id_actors_get
    callback=params.get('callback'))
  File "C:\Gits\Medusa\lib\tvdbapiv2\api_client.py", line 324, in call_api
    response_type, auth_settings, callback)
  File "C:\Gits\Medusa\lib\tvdbapiv2\api_client.py", line 150, in __call_api
    post_params=post_params, body=body)
  File "C:\Gits\Medusa\lib\tvdbapiv2\api_client.py", line 344, in request
    headers=headers)
  File "C:\Gits\Medusa\lib\tvdbapiv2\rest.py", line 184, in GET
    query_params=query_params)
  File "C:\Gits\Medusa\lib\tvdbapiv2\rest.py", line 177, in request
    raise ApiException(http_resp=r)
ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '92', 'X-Powered-By': 'Thundar!', 'Set-Cookie': '__cfduid=d2949ad40dc90d75339e8e2fc2c646ee71486576072; expires=Thu, 08-Feb-18 17:47:52 GMT; path=/; domain=.thetvdb.com; HttpOnly', 'Vary': 'Accept-Language', 'X-Thetvdb-Api-Version': '2.1.2', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=600', 'Date': 'Wed, 08 Feb 2017 17:47:52 GMT', 'CF-RAY': '32e0e8c43bf916d6-ARN', 'Server': 'cloudflare-nginx', 'Content-Type': 'application/json; charset=utf-8'})
```

**Comment by p0psicles** [comment]
Will look at this.

**Comment by wimpyrbx** [comment]
without doing any changes or updates, today i ran another rescan files for these shows and it worked. could be my vpn was acting up.

**Comment by OmgImAlexis** [comment]
@wimpyrbx that's an issue with tvdb as `MyISAM` is a mysql issue.

**Comment by fernandog** [comment]
@p0psicles that PR that catch indexer exceptions will handle this right?

**Comment by p0psicles** [comment]
Yes it should. But I thought we got another bug report recently right? So maybe i missed something. Don't really have the time right now to look into this. I'll first be focusing on the anime xem numbering ticket.

**Comment by fernandog** [comment]
@p0psicles the other bug reported i just did a PR. he tried to add a show but language doesn't exist in the indexer

**Comment by wimpyrbx** [comment]
closed and will watch for this going forward.
