### ISSUE TITLE
SHOWUDATER not alive

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2127]
@p0psicles 
```
2017-02-08 03:00:06 ERROR    SHOWUPDATER :: [3fb68f2] Exception generated: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '92', 'X-Powered-By': 'Thundar!', 'Set-Cookie': '__cfduid=d72ab0bb4de352aa63ab823e9a1543d781486530005; expires=Thu, 08-Feb-18 05:00:05 GMT; path=/; domain=.thetvdb.com; HttpOnly', 'Vary': 'Accept-Language', 'X-Thetvdb-Api-Version': '2.1.2', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=600', 'Date': 'Wed, 08 Feb 2017 05:00:06 GMT', 'CF-RAY': '32dc8415ffa967c7-EZE', 'Server': 'cloudflare-nginx', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {
  "Error": "Error 1030: Got error 24 \"Too many open files\" from storage engine MyISAM"
}
Traceback (most recent call last):
  File "/home/osmc/Medusa/medusa/scheduler.py", line 103, in run
    self.action.run(self.force)
  File "/home/osmc/Medusa/medusa/show_updater.py", line 86, in run
    update_max_weeks)
  File "/home/osmc/Medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 558, in get_last_updated_series
    updates = self.updates_api.updated_query_get(from_time).data
  File "/home/osmc/Medusa/lib/tvdbapiv2/apis/updates_api.py", line 130, in updated_query_get
    callback=params.get('callback'))
  File "/home/osmc/Medusa/lib/tvdbapiv2/api_client.py", line 324, in call_api
    response_type, auth_settings, callback)
  File "/home/osmc/Medusa/lib/tvdbapiv2/api_client.py", line 150, in __call_api
    post_params=post_params, body=body)
  File "/home/osmc/Medusa/lib/tvdbapiv2/api_client.py", line 344, in request
    headers=headers)
  File "/home/osmc/Medusa/lib/tvdbapiv2/rest.py", line 184, in GET
    query_params=query_params)
  File "/home/osmc/Medusa/lib/tvdbapiv2/rest.py", line 177, in request
    raise ApiException(http_resp=r)
ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Length': '92', 'X-Powered-By': 'Thundar!', 'Set-Cookie': '__cfduid=d72ab0bb4de352aa63ab823e9a1543d781486530005; expires=Thu, 08-Feb-18 05:00:05 GMT; path=/; domain=.thetvdb.com; HttpOnly', 'Vary': 'Accept-Language', 'X-Thetvdb-Api-Version': '2.1.2', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=600', 'Date': 'Wed, 08 Feb 2017 05:00:06 GMT', 'CF-RAY': '32dc8415ffa967c7-EZE', 'Server': 'cloudflare-nginx', 'Content-Type': 'application/json; charset=utf-8'})
HTTP response body: {
  "Error": "Error 1030: Got error 24 \"Too many open files\" from storage engine MyISAM"
}
2017-02-08 03:00:03 INFO     SHOWUPDATER :: [3fb68f2] Started periodic show updates
```

**Comment by ripper1967** [comment]
I got this as well
