### ISSUE TITLE
issue with adding show - missing attribute series_name

### ISSUE THREAD

**Issue by wimpyrbx** [pymedusa/Medusa#2206]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** develop
**OS:** windows
**What you did:** added existing show
**What happened:** error
**What you expected:** no error
**Logs:**
```
2017-02-18 13:49:37 INFO     SHOWQUEUE-ADD :: [e86eabb] Starting to add show by ShowDir: D:\TV\NORDIC\Asylet
2017-02-18 13:49:37 INFO     SHOWQUEUE-ADD :: [e86eabb] TVDBv2: {'session': <requests.sessions.Session object at 0x0000000003B47048>, 'cache': u'C:\\Users\\user\\Documents\\Medusa\\cache\\indexers\\TVDBv2', 'language': 'en', 'use_zip': True}
2017-02-18 13:49:38 ERROR    SHOWQUEUE-ADD :: [e86eabb] 306392 Error while loading information from indexer TVDBv2. Error: 'Missing attribute series_name, cant index in language: en'
Traceback (most recent call last):
  File "C:\Users\user\Documents\Medusa\medusa\show_queue.py", line 354, in run
    s = t[self.indexer_id]
  File "C:\Users\user\Documents\Medusa\medusa\indexers\indexer_base.py", line 254, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "C:\Users\user\Documents\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 515, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "C:\Users\user\Documents\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 206, in _get_show_by_id
    .format(request_language), request_language)
IndexerShowNotFoundInLanguage: Missing attribute series_name, cant index in language: en
```

**Comment by medariox** [comment]
What's the show and language you are trying to add?

**Comment by fernandog** [comment]
@p0psicles didnt we handled this?
