### ISSUE TITLE
Error updating: KeyError: 'seasonnumber

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2310]
2017-02-27 03:01:16 ERROR    SHOWUPDATER :: [ecfd7b7] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Fear the Walking Dead. Cause: 'seasonnumber'
Traceback (most recent call last):
  File "/home/osmc/Medusa/medusa/show_updater.py", line 130, in run
    updated_seasons = t.get_last_updated_seasons([show.indexerid], last_update, update_max_weeks)
  File "/home/osmc/Medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 596, in get_last_updated_seasons
    total_updates.append(int(episode['seasonnumber']))
KeyError: 'seasonnumber'

**Comment by fernandog** [comment]
@p0psicles will send full logs soon. Any idea?

**Comment by ratoaq2** [comment]
I had the same issue. I wasn't able to submit the logs

**Comment by fernandog** [comment]
im trying to fix the submit issue now

**Comment by p0psicles** [comment]
Same error with just that show?

**Comment by fernandog** [comment]
https://gist.github.com/fernandog/0100931e4f0683add75765959a25b353

result from: https://api.thetvdb.com/series/290853/episodes'`

no `seasonnumber`there but there is a `airedSeason`

**Comment by ratoaq2** [comment]
Yeah, same error, same show

**Comment by fernandog** [comment]
We found out that show has some ep with airedSeason = null.

We will ignore those type of episodes (incomplete) in show update
