### ISSUE TITLE
[ FEATURE ] Show TORNADO errors by default in log even WEB_LOG is disabled

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2338]
It will help get any webserver errors that currently we don't know about

We only get this as ERROR if WEB_LOG is enabled BUT it spams too much the logger because of INFO logs

so my idea is:
IF WEB_LOG = 0, show only TORNADO ERROR logs.
IF WEB_LOG = 1, show everything

```
2017-03-02 13:07:10 ERROR    TORNADO :: [51ff22a] Uncaught exception GET /api/v2/show/tvdb269578/s4e9/description (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8081', method='GET', uri='/api/v2/show/tvdb269578/s4e9/description',.....)
Traceback (most recent call last):
  File "C:\Users\Fernando\Documents\Medusa\lib\tornado\web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:/Users/Fernando/Documents/Medusa\medusa\server\api\v2\show.py", line 68, in get
    return self._handle_episode(tv_show, ep_id, query)
  File "C:/Users/Fernando/Documents/Medusa\medusa\server\api\v2\show.py", line 110, in _handle_episode
    return self._handle_detailed_episode(tv_episode, query)
  File "C:/Users/Fernando/Documents/Medusa\medusa\server\api\v2\show.py", line 140, in _handle_detailed_episode
    data = tv_episode.to_json()
  File "C:/Users/Fernando/Documents/Medusa\medusa\tv\episode.py", line 714, in to_json
    ).isoformat('T')
TypeError: isoformat() argument 1 must be char, not unicode
```

```
2017-03-02 13:07:10 ERROR    TORNADO :: [51ff22a] 500 GET /api/v2/show/tvdb269578/s4e9/description (127.0.0.1) 12.00ms
Traceback (most recent call last):
  File "C:\Users\Fernando\Documents\Medusa\lib\tornado\web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:/Users/Fernando/Documents/Medusa\medusa\server\api\v2\show.py", line 68, in get
    return self._handle_episode(tv_show, ep_id, query)
  File "C:/Users/Fernando/Documents/Medusa\medusa\server\api\v2\show.py", line 110, in _handle_episode
    return self._handle_detailed_episode(tv_episode, query)
  File "C:/Users/Fernando/Documents/Medusa\medusa\server\api\v2\show.py", line 140, in _handle_detailed_episode
    data = tv_episode.to_json()
  File "C:/Users/Fernando/Documents/Medusa\medusa\tv\episode.py", line 714, in to_json
    ).isoformat('T')
TypeError: isoformat() argument 1 must be char, not unicode
``` 

ping @ratoaq2

**Comment by fernandog** [comment]
don't know if we can label this as BUG too.

**Comment by labrys** [comment]
@fernandog This is why I'm trying to move to a standardized logger... this is exactly what a log config is used for.  Same would apply to DB logging.

**Comment by fernandog** [comment]
@ratoaq2 after api v2 can you check this please?

**Comment by labrys** [comment]
Added to master feature request list #282 - discussion for feature will continue here even though issue is closed.
