### ISSUE TITLE
issue to connect to distant rtorrent 

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#2354]
Hi there,

I got a new distant seedbox and try to set it up properly.
I'd like to send torrent from Medusa to rtorrent but I can't get it working.
it says:
"Error: Unable to connect to rTorrent"
but It doesn't give much details

How can I get more details to know where it fails in the connection process please?

**Comment by fernandog** [comment]
@NicoLeOca check logs, filter by THREAD logs

**Comment by NicoLeOca** [comment]
@fernandog 
when I hit TEST, nothing appears in the logs.

**Comment by fernandog** [comment]
@NicoLeOca you should see something like this:

Did you select "Filter log by" with THREAD and DEBUG level?

2017-03-07 08:43:34 DEBUG    Thread-18 :: [5f0d9fc] Transmission: Response to POST request is {"arguments":.....,"result":"success"}
2017-03-07 08:43:34 DEBUG    Thread-18 :: [5f0d9fc] Transmission: Requested a POST connection to http://0000:xxxx

**Comment by NicoLeOca** [comment]
@fernandog 
yes I did filter by thread and debug
FYI, I succeeded to connect with deluge (daemon) but even with this software, I don't have anything in the logs

**Comment by NicoLeOca** [comment]
but I had something when I tried deluge web:

```
2017-03-07 12:52:04 ERROR    Thread-25 :: [134f473] Environment error: HTTPSConnectionPool(host='myserverip', port=): Read timed out. (read timeout=120)
Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 259, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\home\handler.py", line 302, in testTorrent
    _, acces_msg = client(host, username, password).test_authentication()
  File "C:\Medusa\medusa\clients\torrent\generic.py", line 279, in test_authentication
    self.response = self.session.get(self.url, timeout=120, verify=False)
  File "C:\Medusa\lib\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Medusa\lib\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Medusa\lib\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Medusa\lib\cachecontrol\adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\Medusa\lib\requests\adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='myserverIP', port=): Read timed out. (read timeout=120)
```

**Comment by duramato** [comment]
Check if the URL is correct, check the seedbox provider's wiki. Software RPC/webui etc runs under some proxy generally

**Comment by NicoLeOca** [comment]
@duramato 
I used a script (https://quickbox.io/) to install it on my dedicated server.
there is no proxy AFAIK

**Comment by NicoLeOca** [comment]
Guys,
I restarted everything for the (I don't even count) time and it works now, with settings I tried before a few times also...
It doesn't explain why logs are not tchaty but nevermind.
thanks for your help
