### ISSUE TITLE
[APP SUBMITTED]: IndexerUnavailable: Indexer unavailable with reason 'Origin SSL Handshake Error' (525)

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2356]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@134f473296627614417e317dfcd4f3106cd49a8e
**Link to Log**: https://gist.github.com/514418e9ba1dd65f7bf9616e7a54624a
### ERROR
<pre>
2017-03-07 03:55:59 ERROR    SHOWQUEUE-REFRESH :: [134f473] 194031: Error while refreshing show Bob's Burgers. Error: Indexer unavailable with reason 'Origin SSL Handshake Error' (525)
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/134f473296627614417e317dfcd4f3106cd49a8e/medusa/show_queue.py#L629">medusa/show_queue.py</a>", line 629, in run
    self.show.refresh_dir()
  File "/home/pi/Medusa/<a href="../blob/134f473296627614417e317dfcd4f3106cd49a8e/medusa/tv/series.py#L1421">medusa/tv/series.py</a>", line 1421, in refresh_dir
    self.create_indexer()
  File "/home/pi/Medusa/<a href="../blob/134f473296627614417e317dfcd4f3106cd49a8e/medusa/tv/series.py#L206">medusa/tv/series.py</a>", line 206, in create_indexer
    self._cached_indexer_api = api.indexer(**params)
  File "/home/pi/Medusa/<a href="../blob/134f473296627614417e317dfcd4f3106cd49a8e/medusa/indexers/indexer_api.py#L34">medusa/indexers/indexer_api.py</a>", line 34, in indexer
    return indexerConfig[self.indexer_id]['module'](*args, **kwargs)
  File "/home/pi/Medusa/<a href="../blob/134f473296627614417e317dfcd4f3106cd49a8e/medusa/indexers/tvdbv2/tvdbv2_api.py#L73">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 73, in __init__
    raise IndexerUnavailable("Indexer unavailable with reason '%s' (%s)" % (e.reason, e.status))
IndexerUnavailable: Indexer unavailable with reason 'Origin SSL Handshake Error' (525)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Duplicate: https://github.com/pymedusa/Medusa/issues/2348

**Comment by NicoLeOca** [comment]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a7a485d328a820bdf4d7a4ea1a7c479032c5d0e6
**Link to Log**: https://gist.github.com/fe9cceae7093f0094dec5fe357b4f4f3
### ERROR
<pre>
2017-03-16 06:44:42 ERROR    SHOWQUEUE-REFRESH :: [a7a485d] 269586: Error while refreshing show Brooklyn Nine-Nine. Error: Indexer unavailable with reason 'Origin SSL Handshake Error'
Traceback (most recent call last):
  File "C:\Medusa\medusa\show_queue.py", line 629, in run
    self.show.refresh_dir()
  File "C:\Medusa\medusa\tv\series.py", line 1422, in refresh_dir
    self.create_indexer()
  File "C:\Medusa\medusa\tv\series.py", line 207, in create_indexer
    self._cached_indexer_api = api.indexer(**params)
  File "C:\Medusa\medusa\indexers\indexer_api.py", line 34, in indexer
    return indexerConfig[self.indexer_id]['module'](*args, **kwargs)
  File "C:\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 73, in __init__
    raise IndexerUnavailable("Indexer unavailable with reason '%s'" % e.reason)
IndexerUnavailable: Indexer unavailable with reason 'Origin SSL Handshake Error'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
