### ISSUE TITLE
Post Processor deleting files that were not successfully processed

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#2362]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Develop
**OS:** Win 10
**What you did:**  Looked at SAB completed Queue - File listed as successfully processed by nzbtomedia script but file not available in library.
**What happened:**  External drive with media was disconnected before post processing yet auto postprocessor reported that the file was successfully post processed and deleted the downloaded
**What you expected:**  Release to remain in PP folder until target directory available
**Logs:**

Full log: https://gist.github.com/labrys/5f3b28e43d16f60c22d9508471977fd0
Pertinent log lines:
```
2017-03-07 06:42:59 INFO     Thread-39 :: [8b7318c] PostProcessing Path: G:\tmp\download\Emerald City


2017-03-07 06:43:00 ERROR    Thread-39 :: [8b7318c] Failed creating D:\- Series\Emerald City\Season 01 : WindowsError(3, 'The system cannot find the path specified')
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\helpers\__init__.py", line 418, in make_dirs
    os.makedirs(path)
  File "H:\usr\local\medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\Python\latest\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
  File "H:\usr\local\medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 3] The system cannot find the path specified: 'D:\\- Series\\Emerald City\\Season 01'


2017-03-07 06:43:00 DEBUG    Thread-39 :: [8b7318c] Moving file from G:\tmp\download\Emerald City\Season 1\Emerald City - S01E09 - The Villain That's Become.mkv to D:\- Series\Emerald City\Season 01\Emerald City - S01E09 - The Villain That's Become.mkv 
2017-03-07 06:43:00 ERROR    Thread-39 :: [8b7318c] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\helpers\__init__.py", line 296, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "H:\usr\local\medusa\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 2] No such file or directory


2017-03-07 06:43:05 DEBUG    Thread-39 :: [8b7318c] Metadata dir didn't exist, creating it at D:\- Series\Emerald City\Season 01
2017-03-07 06:43:05 INFO     Thread-39 :: [8b7318c] Could not create/update meta files. Continuing with post-processing...


2017-03-07 06:43:06 INFO     Thread-39 :: [8b7318c] Processing succeeded for G:\tmp\download\Emerald City\Season 1\Emerald City - S01E09 - The Villain That's Become.mkv


2017-03-07 06:43:06 DEBUG    Thread-39 :: [8b7318c] Found unwanted files: [u"Emerald City - S01E09 - The Villain That's Become"]
2017-03-07 06:43:06 INFO     Thread-39 :: [8b7318c] Deleting folder (if it's empty): G:\tmp\download\Emerald City\Season 1
2017-03-07 06:43:06 DEBUG    Thread-39 :: [8b7318c] Deleted folder: G:\tmp\download\Emerald City\Season 1
2017-03-07 06:43:06 INFO     Thread-39 :: [8b7318c] Successfully processed
```

**Comment by labrys** [comment]
`D:\- Series\` is a local directory
`D:\- Series\Emerald City` is a symlink to a drive that is disconnected

**Comment by fernandog** [comment]
@labrys first and third commit from this PR fixes it: https://github.com/pymedusa/Medusa/pull/2361

**Comment by fernandog** [comment]
@labrys can you test that PR?

**Comment by labrys** [comment]
Need to make sure this doesn't crash the post processor so it needs to be caught during the PP run.
