### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by zdeev** [pymedusa/Medusa#2422]
### INFO
**Python Version**: `2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-8-6.2.9200`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/28726cc652fea96fa7644213abca278d
### ERROR
<pre>
2017-03-16 16:39:19 ERROR    SHOWQUEUE-ADD :: [a011615] Error loading IMDb info: error 9 : Bad file descriptor
Traceback (most recent call last):
  File "C:\SickRage-Medusa\medusa\show_queue.py", line 499, in run
    self.show.load_imdb_info()
  File "C:\SickRage-Medusa\medusa\tv\series.py", line 1263, in load_imdb_info
    imdb_obj = imdb_api.get_title_by_id(self.imdb_id)
  File "C:\SickRage-Medusa\lib\imdbpie\imdbpie.py", line 62, in get_title_by_id
    print(response)
IOError: [Errno 9] Bad file descriptor
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
This happens because of the print(), already fixed in develop: https://github.com/pymedusa/Medusa/pull/2313
