### ISSUE TITLE
[APP SUBMITTED]: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2424]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a70a6df42ec915a51409a059df3a58f56c1b2bd7
**Link to Log**: https://gist.github.com/839dc72eb02a30a96952cd7150164207
### ERROR
<pre>
2017-03-17 02:01:22 ERROR    SHOWUPDATER :: [a70a6df] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Hannibal. Cause: 'NoneType' object is not iterable.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/a70a6df42ec915a51409a059df3a58f56c1b2bd7/medusa/show_updater.py#L86">medusa/show_updater.py</a>", line 86, in run
    update_max_weeks)
  File "/home/pi/Medusa/<a href="../blob/a70a6df42ec915a51409a059df3a58f56c1b2bd7/medusa/indexers/tvdbv2/tvdbv2_api.py#L565">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 565, in get_last_updated_series
    last_update_ts = max(x.last_updated for x in updates)
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Seems like https://github.com/pymedusa/Medusa/blob/a70a6df42ec915a51409a059df3a58f56c1b2bd7/medusa/indexers/tvdbv2/tvdbv2_api.py#L564 can return None without raising an exception. A simple ```if updates is not None:``` before it would do it. Or maybe we should raise an exception there.

**Comment by p0psicles** [comment]
yeah or:
`total_updates += [int(_.id) for _ in updates or []]`

**Comment by medariox** [comment]
@p0psicles 
The error happens a few lines before that:
```last_update_ts = max(x.last_updated for x in updates)```
We might also want to preserve the old ```from_time``` without overwriting it and still update the counter.
```
while updates and count < weeks:
    updates = self.updates_api.updated_query_get(from_time).data
    if updates is not None:
        last_update_ts = max(x.last_updated for x in updates)
        from_time = last_update_ts
        total_updates += [int(_.id) for _ in updates]
    count += 1
```

**Comment by Stonedestroyer** [comment]
### INFO
**Python Version**: `2.7.13 (default, Mar 30 2017, 15:15:10) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@ebdacab6f3da657d4069f9e4a391ad00595087f6
**Link to Log**: https://gist.github.com/f9c58414bb0569709308f2d86372ca76
### ERROR
<pre>
2017-05-23 03:52:04 ERROR    SEARCHQUEUE-FORCED-317828 :: [ShanaProject] :: [ebdacab] Unknown exception while searching ShanaProject. Error: "'NoneType' object is not iterable"
Traceback (most recent call last):
  File "C:\software\medusa\medusa\search\core.py", line 547, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "C:\software\medusa\medusa\providers\generic_provider.py", line 209, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "C:\software\medusa\medusa\providers\torrent\html\shanaproject.py", line 95, in search
    results += self.parse(response.text, mode)
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Jaska8** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 29 2017, 01:15:45) [GCC 4.2.1 Compatible FreeBSD Clang 3.8.0 (tags/RELEASE_380/final 262564)]`
**Operating System**: `FreeBSD-11.0-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@2a21fd430ad688cd633f8929d2fb90cd78362e9e
**Link to Log**: https://gist.github.com/104e489189caa19d6fff92283c692f90
### ERROR
<pre>
2017-06-15 08:18:56 ERROR    SEARCHQUEUE-MANUAL-272309 :: [ShanaProject] :: [2a21fd4] Unknown exception while searching ShanaProject. Error: "'NoneType' object is not iterable"
Traceback (most recent call last):
  File "/usr/home/**********/Medusa/medusa/search/core.py", line 547, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/usr/home/**********/Medusa/medusa/providers/generic_provider.py", line 209, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/usr/home/**********/Medusa/medusa/providers/torrent/html/shanaproject.py", line 95, in search
    results += self.parse(response.text, mode)
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@p0psicles we already check if response.text so not idea where the issue is

**Comment by p0psicles** [comment]
I think the issue is results being None, when it tries to add an item to it

**Comment by fernandog** [comment]
but results is initialize with `results = []`

**Comment by p0psicles** [comment]
Hasn't this been resolved last week?

**Comment by p0psicles** [comment]
Aah no real changes there.

**Comment by labrys** [comment]
L113 Returning None instead of `return results`
```
             if len(torrent_rows) < 2:
                return
```
