### ISSUE TITLE
Subtitles issue with db

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2449]
Happen while searching for subtitle from the Post-Processor

```
2017-03-21 19:28:07 WARNING  Thread-18 :: [79ebec8] Failed to refine video
Traceback (most recent call last):
  File "/home/pi/Medusa/lib/subliminal/core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/pi/Medusa/lib/subliminal/refiners/tvdb.py", line 267, in refine
    results = search_series(video.series.lower())
  File "/home/pi/Medusa/lib/dogpile/cache/region.py", line 1220, in decorate
    should_cache_fn)
  File "/home/pi/Medusa/lib/dogpile/cache/region.py", line 825, in get_or_create
    async_creator) as value:
  File "/home/pi/Medusa/lib/dogpile/lock.py", line 154, in __enter__
    return self._enter()
  File "/home/pi/Medusa/lib/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/home/pi/Medusa/lib/dogpile/cache/region.py", line 780, in get_value
    value = self.backend.get(key)
  File "/home/pi/Medusa/lib/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/pi/Medusa/lib/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python2.7/anydbm.py", line 79, in open
    raise error, "need 'c' or 'n' flag to open new db"
error: need 'c' or 'n' flag to open new db
```

Full log: https://gist.github.com/duramato/be8bbe41f5a01db74032d737b6cabae5

This happen after i enabled **"Erase subtitles cache on next boot"**
@ratoaq2 @fernandog 
Dont know if it's Medusa's issue or an upstream one

**Comment by ratoaq2** [comment]
Did you reboot?

**Comment by duramato** [comment]
Yes, this happen after the reboot

**Comment by ratoaq2** [comment]
Shutdown, remove cached files and start

**Comment by fernandog** [comment]
here works fine:

2017-03-24 08:07:49 INFO     EVENT-QUEUE :: [b4a8a54] Saving all shows to the database
2017-03-24 08:07:49 INFO     EVENT-QUEUE :: [b4a8a54] Saving config file to disk
2017-03-24 08:07:50 INFO     EVENT-QUEUE :: [b4a8a54] Shutting down Tornado
2017-03-24 08:07:50 INFO     EVENT-QUEUE :: [b4a8a54] Restarting Medusa with ['C:\\Python27\\python.exe', 
2017-03-24 08:08:28 INFO     MAIN :: [b4a8a54] Removing subtitles cache file: C:\Users\fernando\Documents\Medusa\cache\application.dbm
2017-03-24 08:08:36 INFO     MAIN :: [b4a8a54] Removing subtitles cache file: C:\Users\fernando\Documents\Medusa\cache\subliminal.dbm
2017-03-24 08:09:25 INFO     MAIN :: [b4a8a54] Starting Medusa [] using

**Comment by duramato** [comment]
Which files @ratoaq2 ?

**Comment by fernandog** [comment]
Removing subtitles cache file: 
C:\Users\fernando\Documents\Medusa\cache\application.dbm
C:\Users\fernando\Documents\Medusa\cache\subliminal.dbm

**Comment by fernandog** [comment]
@duramato do you still have this issue while enabling the set to erase cache on next boot?
