### ISSUE TITLE
FINDPROPERS :: [230e4ec] Exception generated: 'ProperFinder' object has no attribute '_set_last_proper_search'

### ISSUE THREAD

**Issue by medariox** [pymedusa/Medusa#2557]
```
2017-04-01 17:15:05 ERROR    FINDPROPERS :: [230e4ec] Exception generated: 'ProperFinder' object has no attribute '_set_last_proper_search'
Traceback (most recent call last):
  File "/home/marx/medusa/medusa/scheduler.py", line 103, in run
    self.action.run(self.force)
  File "/home/marx/medusa/medusa/search/proper.py", line 82, in run
    self._set_last_proper_search(datetime.datetime.today().toordinal())
AttributeError: 'ProperFinder' object has no attribute '_set_last_proper_search'
```

For reference:
Removed here: https://github.com/pymedusa/Medusa/pull/2492
PR merged without review and/or approval.

**Comment by fernandog** [comment]
be patient. everything will be fixed

**Comment by labrys** [comment]
On the same not about review... if you have a set and a get then thats a really big clue that it should be a property and not two separate methods... lets try and be properly pythonic with our code.
