### ISSUE TITLE
Can't post-process in unionfs-fuse dir while Sickrage can

### ISSUE THREAD

**Issue by Aerya** [pymedusa/Medusa#2563]
Hi,

Medusa Info:	Branch: master
Commit: a0116154f262786d6f5274459cb8f9cdb23012cc
Version: v0.1.11
Database: 44.5
Python Version:	2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
SSL Version:	OpenSSL 1.0.1t 3 May 2016
OS:	Linux-4.4.44-1-pve-x86_64-with-debian-8.7
Locale:	Unknown.Unknown

**What you did:**
I use rClone to mount/crypt an Amazon Cloud so as to store files. I don't want to lose any file on my Amazon Cloud so I mount it in ReadOnly mod in /Enc_ACD.
Thus, completed torrent files are move to /Pre, ReadWrite mod, where Medusa as to post-process them to an unionfuse-fs dir /Union (/Pre=RW, /Enc_ACD=RO).
Then an rClone script move the files to my Amazon Cloud.
Medusa and Sickrage are ran with the same user.

**What happened:**
It works perfectly with Couchpotato, Sonarr, Radarr, Watcher and Sickrage. But Medusa keep failing at post-processing files.

**Logs:**

Medusa
```
2017-04-03 08:25:18 INFO     POSTPROCESSOR :: [a011615] Processing succeeded for /home/xxx/Pre/PreSeries/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv
2017-04-03 08:25:18 DEBUG    POSTPROCESSOR :: [a011615] 303236: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> Outsiders - 2x07 - Home for Supper - 720p HDTV
2017-04-03 08:25:18 DEBUG    POSTPROCESSOR :: [a011615] Found codec for Outsiders Home for Supper
2017-04-03 08:25:18 DEBUG    POSTPROCESSOR :: [a011615] Using cached parse result for 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual'
2017-04-03 08:25:18 DEBUG    POSTPROCESSOR :: [a011615] Parsed '/home/xxx/Union/Series/Outsiders/Season 02/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual' into title: Outsiders, season: 2, episode: [7], other: Fastsub, subtitle_language: fr, screen_size: 720p, format: HDTV, video_codec: h264, video_encoder: x264, release_group: Visual, type: episode, parsing_time: 0.0575048923492, total_time: 0.057569026947, absolute_episode: [], quality: 720p HDTV
2017-04-03 08:25:18 DEBUG    POSTPROCESSOR :: [a011615] Matched release '/home/xxx/Union/Series/Outsiders/Season 02/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual' to a show in your database: 'Outsiders'
2017-04-03 08:25:16 DEBUG    POSTPROCESSOR :: [a011615] 303236: Setter sets location to /home/xxx/Union/Series/Outsiders/Season 02/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv
2017-04-03 08:25:15 ERROR    POSTPROCESSOR :: [a011615] [Errno 13] Permission denied: '/home/xxx/Union/Series/Outsiders/Season 02/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv'
Traceback (most recent call last):
  File "/opt/medusa/medusa/helpers.py", line 296, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/opt/medusa/lib/shutil_custom/__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 13] Permission denied: '/home/xxx/Union/Series/Outsiders/Season 02/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv'
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Copying file from /home/xxx/Pre/PreSeries/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv to /home/xxx/Union/Series/Outsiders/Season 02/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Checking if the path /home/xxx/Union/Series/Outsiders/Season 02 already exists
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Destination folder for this episode: /home/xxx/Union/Series/Outsiders/Season 02
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Found codec for Outsiders Home for Supper
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Using cached parse result for 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual'
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] 303236: Formatting pattern: %RN -> Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Found codec for Outsiders Home for Supper
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Using cached parse result for 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual'
2017-04-03 08:25:15 INFO     POSTPROCESSOR :: [a011615] Release name (Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual) found from file (Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.nfo)
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Parsed 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual' into title: Outsiders, season: 2, episode: [7], other: Fastsub, subtitle_language: fr, screen_size: 720p, format: HDTV, video_codec: h264, video_encoder: x264, release_group: Visual, type: episode, parsing_time: 0.022390127182, total_time: 0.022481918335, absolute_episode: [], quality: 720p HDTV
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Matched release 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual' to a show in your database: 'Outsiders'
2017-04-03 08:25:15 DEBUG    POSTPROCESSOR :: [a011615] Found release name Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual
2017-04-03 08:25:14 DEBUG    POSTPROCESSOR :: [a011615] Retrieving episode object for Outsiders S02E07
2017-04-03 08:25:14 DEBUG    POSTPROCESSOR :: [a011615] Parsed 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv' into title: Outsiders, season: 2, episode: [7], other: Fastsub, subtitle_language: fr, screen_size: 720p, format: HDTV, video_codec: h264, video_encoder: x264, release_group: Visual, container: mkv, mimetype: video/x-matroska, type: episode, parsing_time: 0.021134853363, total_time: 0.0212137699127, absolute_episode: [], quality: 720p HDTV
2017-04-03 08:25:14 DEBUG    POSTPROCESSOR :: [a011615] Matched release 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv' to a show in your database: 'Outsiders'
2017-04-03 08:25:14 DEBUG    POSTPROCESSOR :: [a011615] Analyzing name: Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv
2017-04-03 08:25:14 INFO     POSTPROCESSOR :: [a011615] Processing /home/xxx/Pre/PreSeries/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv
2017-04-03 08:25:14 DEBUG    POSTPROCESSOR :: [a011615] Parsed 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv' into title: Outsiders, season: 2, episode: [7], other: Fastsub, subtitle_language: fr, screen_size: 720p, format: HDTV, video_codec: h264, video_encoder: x264, release_group: Visual, container: mkv, mimetype: video/x-matroska, type: episode, parsing_time: 0.0218191146851, total_time: 0.0219118595123, absolute_episode: [], quality: 720p HDTV
2017-04-03 08:25:14 DEBUG    POSTPROCESSOR :: [a011615] Matched release 'Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual.mkv' to a show in your database: 'Outsiders'
2017-04-03 08:25:14 DEBUG    POSTPROCESSOR :: [a011615] Processing folder /home/xxx/Pre/PreSeries/Outsiders.S02E07.FASTSUB.VOSTFR.720p.HDTV.x264-Visual
```

Sickrages post-process works fine
```
2017-04-03 06:46:03 INFO POSTPROCESSOR-AUTO :: Processing succeeded for /home/xxx/Pre/PreSeries/Taboo.UK.S01E03.FASTSUB.VOSTFR.720p.WEB-DL.x264.AC3-GOBO2S/Taboo.UK.S01E03.FASTSUB.VOSTFR.720p.WEB-DL.x264.AC3-GOBO2S.mkv
2017-04-03 06:45:59 INFO POSTPROCESSOR-AUTO :: Release name (Taboo.UK.S01E03.FASTSUB.VOSTFR.720p.WEB-DL.x264.AC3-GOBO2S) found from file (Taboo.UK.S01E03.FASTSUB.VOSTFR.720p.WEB-DL.x264.AC3-GOBO2S.nfo)
2017-04-03 06:45:59 INFO POSTPROCESSOR-AUTO :: Processing /home/xxx/Pre/PreSeries/Taboo.UK.S01E03.FASTSUB.VOSTFR.720p.WEB-DL.x264.AC3-GOBO2S/Taboo.UK.S01E03.FASTSUB.VOSTFR.720p.WEB-DL.x264.AC3-GOBO2S.mkv (None)
2017-04-03 06:40:48 INFO SEARCHQUEUE-BACKLOG-292157 :: Saved result to /home/xxx/watch/PreSeries/Taboo.UK.S01E03.FASTSUB.VOSTFR.720p.WEB-DL.x264.AC3-GOBO2S.torrent
```

**Comment by fernandog** [comment]
@Aerya looks like a permission issue as logs : `OSError: [Errno 13] Permission denied: `

**Comment by fernandog** [comment]
the user that runs sickrage is the same as the medusa?
check if medusa user has same access

**Comment by Aerya** [comment]
I confirm I run SR and Medusa with the same user: xxx (/home/xxx). This is why I don't understand my logs :/

**Comment by fernandog** [comment]
@Aerya what is your PPmethod?  (copy, move, symlink, hardlink) ?

**Comment by Aerya** [comment]
Should be copy but also tried move.

**Comment by fernandog** [comment]
No idea.
Hope other @pymedusa/developers  could help

**Comment by Aerya** [comment]
Thanks

**Comment by Aerya** [comment]
I don't understand "why", I'll look into it, but it works fine when running with root... Prob on my side.

**Comment by labrys** [comment]
@Aerya almost definitely something ran as root on the medusa folder or the PP folder
try using `chown` to correct the permissions
```
