### ISSUE TITLE
[APP SUBMITTED]: WindowsError: [Error 2] The system cannot find the file specified: "X:\\DC's Legends of Tomorrow\\DCs.Legends.of.Tomorrow.S02E10.1080p.WEB-DL.DD5.1.H264-RARBG.mkv"

### ISSUE THREAD

**Issue by zdeev** [pymedusa/Medusa#2577]
### INFO
**Python Version**: `2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-8-6.2.9200`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a0116154f262786d6f5274459cb8f9cdb23012cc
**Link to Log**: https://gist.github.com/1f30fe5552c8c199c1214490d1e1f4a5
### ERROR
<pre>
2017-04-10 20:07:03 ERROR    Thread-20 :: [a011615] Unable to get size for file X:\DC's Legends of Tomorrow\DCs.Legends.of.Tomorrow.S02E10.1080p.WEB-DL.DD5.1.H264-RARBG.mkv Error: u'error 2 : The system cannot find the file specified'
Traceback (most recent call last):
  File "C:\SickRage-Medusa\medusa\helpers.py", line 1329, in get_size
    total_size += os.path.getsize(fp)
  File "C:\SickRage-Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\SickRage\Python\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
  File "C:\SickRage-Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 2] The system cannot find the file specified: "X:\\DC's Legends of Tomorrow\\DCs.Legends.of.Tomorrow.S02E10.1080p.WEB-DL.DD5.1.H264-RARBG.mkv"
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
https://github.com/pymedusa/Medusa/issues/2576
