### ISSUE TITLE
[APP SUBMITTED]: TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#2596]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [file-size-log](../tree/file-size-log)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@5db71ce532f073b0cd9807865388a1db74ca2388
**Link to Log**: https://gist.github.com/bd56768c9b46611944e846beb60378e2
### ERROR
<pre>
2017-04-15 08:52:38 ERROR    POSTPROCESSOR :: [5db71ce] Exception generated: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "H:\usr\local\medusa\medusa\auto_post_processor.py", line 57, in run
    process_tv.ProcessResult(app.TV_DOWNLOAD_DIR, app.PROCESS_METHOD).process(force=force)
  File "H:\usr\local\medusa\medusa\process_tv.py", line 162, in process
    ignore_subs=ignore_subs)
  File "H:\usr\local\medusa\medusa\process_tv.py", line 336, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "H:\usr\local\medusa\medusa\process_tv.py", line 577, in process_media
    self.result = processor.process()
  File "H:\usr\local\medusa\medusa\post_processor.py", line 1075, in process
    if int(ep_obj.season) > int(max_season[0][0]):
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
The show has no seasons?

**Comment by labrys** [comment]
No it was caused by a race condition when a series was removed, it crashed the PP though.

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@627aad75fb55de611256c20404ba44670fb3db1c
**Link to Log**: https://gist.github.com/9826a004023326bdf8a6a27f6c3c5457
### ERROR
<pre>
2017-05-15 16:42:53 ERROR    Thread-36 :: [Speedcd] :: [627aad7] Exception generated: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/627aad75fb55de611256c20404ba44670fb3db1c/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/home/pi/Medusa/<a href="../blob/627aad75fb55de611256c20404ba44670fb3db1c/medusa/server/web/home/handler.py#L1141">medusa/server/web/home/handler.py</a>", line 1141, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/home/pi/Medusa/<a href="../blob/627aad75fb55de611256c20404ba44670fb3db1c/medusa/search/manual.py#L208">medusa/search/manual.py</a>", line 208, in get_provider_cache_results
    minseed = int(cur_provider.minseed) if hasattr(cur_provider, 'minseed') else -1
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
