### ISSUE TITLE
Unexpected error in provider u'addic7ed'

### ISSUE THREAD

**Issue by achatillon** [pymedusa/Medusa#2678]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch:** master
**Commit:** 9c19b10731765197136e042f30ebca793414cac1
**Version:** v0.1.12rc1
**OS:** Linux-3.2.40-i686-with-glibc2.0 (DSM 6.1 on a DS214play Synology)
**What you did:** Trying to manual search subtitles
**What happened:** Nothing, no popin displayed to choose the desired subtitle
**Logs:**
```
2017-04-28 17:13:16 WARNING  Thread-19 :: [9c19b10] Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/providers/addic7ed.py", line 238, in query
    raise TooManyRequests()
TooManyRequests
2017-04-28 17:13:13 INFO     Thread-19 :: [9c19b10] Manual searching subtitles for: The.Flash.2014.S03E19.720p.WEB-DL.H264-FUM[ettv]
2017-04-28 17:13:13 INFO     Thread-19 :: [9c19b10] Starting to manual searching subtitles
```

**Comment by medariox** [comment]
```addic7ed``` has a quite strict requests limit. There is not much we can do about this. Either reduce the amount of requests to the provider (e.g. don't search too many subs at once) or use another subtitles provider.

**Comment by achatillon** [comment]
Do you know how this limit works ? Is it a maximum number of request per day, or is it a fix number per account and when you reach it you are f*** ?
I have a lot of old episodes with missing subtitles but as they are old I don't need to dowload them, is there a way to tell Meduse to don't download subtitles if episodes has been downloaded X months earlier ?
I switched few weaks ago from Sickrage to Medusa and I haven't any issues with addic7ed before.

**Comment by medariox** [comment]
That's what I could find:

>   Visitors - Limited to 15 files / 24 hours
Registered - Has an increased download limit to 40 subtitles / 24 hours

As you can see, it's not much.

There are some limits, but it's not possible to change these manually:
> Shows with air date <= 30 days, have a limit of 100 results
      Shows with air date > 30 days, have a limit of 200 results

So it should get better in a few days. Alternatively you could disable subtitles for some shows for now or compensate with another subtitles provider in the meantime.

**Comment by fernandog** [comment]
@medariox this is a connection block as user can't search. Not that he can't download (you can see in the log that there is no download, just a search). 

Its the same block as RARBG does that limit 2req/s

Similar issue:
https://github.com/pymedusa/Medusa/issues/1513#issuecomment-267087677

I already proposed a decorator retry for Addi7ed here:
https://github.com/pymedusa/Medusa/pull/2026/commits/7bb8017db880cc1e4cca07db3bb8a07330eba1ed

That fixed the issue but it wasn't approved

Anyway we can still do something as we now have a custom providers fixes as in here:
https://github.com/pymedusa/Medusa/pull/2562

**Comment by fernandog** [comment]
another one:
https://github.com/pymedusa/Medusa/issues/393

**Comment by fernandog** [comment]
I did some tests and Addi7ed is blocking the Subliminal user-agent.

**Comment by ward0** [comment]
Still having this error :(

2017-07-13 10:09:40 DEBUG    FINDSUBTITLES :: [6b7e935] Discarding provider addic7ed
2017-07-13 10:09:40 WARNING  FINDSUBTITLES :: [6b7e935] Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/providers/addic7ed.py", line 238, in query
    raise TooManyRequests()
TooManyRequests

**Comment by fernandog** [comment]
@achatillon Latest subliminal which is already in master wont raise Too many requests anymore. It will debug log that provider didn't replied with any data

**Comment by ward0** [comment]
@fernandog yay! finally no more deleting this error 👍
