### ISSUE TITLE
Scaning/Refining video in the _unpack folder causing MalformedMKVError

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2696]
It should ignore `_unpack` folder

```
2017-05-05 02:12:38 DEBUG    FINDSUBTITLES :: [36052ba] Scanning video u'eac78f3f87564f4a8069530a8c22824a.mkv' in u'/media/SAMSUNG/media/downloaded/series/Show.S01E20.1080p.AMZN.WEBRip.DD.5.1.x264-RTN-Scrambled/_unpack'
2017-05-05 02:12:41 DEBUG    FINDSUBTITLES :: [36052ba] Refining video with metadata
2017-05-05 02:12:41 WARNING  FINDSUBTITLES :: [36052ba] Failed to refine video
Traceback (most recent call last):
  File "/home/osmc/Medusa/lib/subliminal/core.py", line 543, in refine
    refiner_manager[refiner].plugin(video, **kwargs)
  File "/home/osmc/Medusa/lib/subliminal/refiners/metadata.py", line 32, in refine
    mkv = MKV(f)
  File "/home/osmc/Medusa/lib/enzyme/mkv.py", line 56, in __init__
    raise MalformedMKVError('Parsing error: %s' % e)
MalformedMKVError: Parsing error: Less than 1 bytes read (0)
```

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2698
