### ISSUE TITLE
[APP SUBMITTED]: TypeError: level must be an integer

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2779]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@289e34a0ff1556d94f314ee1d268036bccbc19ba
**Link to Log**: https://gist.github.com/fab36c448ceab560ac5437227d5f393a
### ERROR
<pre>
2017-05-10 00:06:46 ERROR    SEARCHQUEUE-MANUAL-274431 :: [Danishbits] :: [289e34a] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/danishbits.py", line 174, in parse\n    title, seeders, leechers)\n  File "/home/pi/Medusa/medusa/logger/adapters/style.py", line 79, in log\n    self.logger.log(level, brace_msg, **kwargs)\n  File "/usr/lib/python2.7/logging/__init__.py", line 1482, in log\n    self.logger.log(level, msg, *args, **kwargs)\n  File "/usr/lib/python2.7/logging/__init__.py", line 1220, in log\n    raise TypeError("level must be an integer")\nTypeError: level must be an integer\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/289e34a0ff1556d94f314ee1d268036bccbc19ba/medusa/providers/torrent/html/danishbits.py#L174">medusa/providers/torrent/html/danishbits.py</a>", line 174, in parse
    title, seeders, leechers)
  File "/home/pi/Medusa/<a href="../blob/289e34a0ff1556d94f314ee1d268036bccbc19ba/medusa/logger/adapters/style.py#L79">medusa/logger/adapters/style.py</a>", line 79, in log
    self.logger.log(level, brace_msg, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1482, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1220, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
@labrys  one slipped through.

**Comment by medariox** [comment]
Fixed here: https://github.com/pymedusa/Medusa/pull/2780

**Comment by labrys** [comment]
It probably won't be the only one 😬

**Comment by neoatomic** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@69b471204467dd3434af0b5799984f3f3e6bbc60
**Link to Log**: https://gist.github.com/b0226593fc2dc2d527b036f73c6da96c
### ERROR
<pre>
2017-08-17 03:33:32 ERROR    Thread-17 :: [69b4712] Exception generated: level must be an integer
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/69b471204467dd3434af0b5799984f3f3e6bbc60/SickBeard/medusa/server/web/core/base.py#L258">SickBeard/medusa/server/web/core/base.py</a>", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/69b471204467dd3434af0b5799984f3f3e6bbc60/SickBeard/medusa/server/web/home/post_process.py#L50">SickBeard/medusa/server/web/home/post_process.py</a>", line 50, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/69b471204467dd3434af0b5799984f3f3e6bbc60/SickBeard/medusa/process_tv.py#L142">SickBeard/medusa/process_tv.py</a>", line 142, in process
    if not self.should_process(path, failed):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/69b471204467dd3434af0b5799984f3f3e6bbc60/SickBeard/medusa/process_tv.py#L234">SickBeard/medusa/process_tv.py</a>", line 234, in should_process
    self.process_failed(path)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/69b471204467dd3434af0b5799984f3f3e6bbc60/SickBeard/medusa/process_tv.py#L587">SickBeard/medusa/process_tv.py</a>", line 587, in process_failed
    self.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/69b471204467dd3434af0b5799984f3f3e6bbc60/SickBeard/medusa/failed_processor.py#L51">SickBeard/medusa/failed_processor.py</a>", line 51, in process
    self.log(u'Parsed info: {result}'.format(result=parsed), logger.DEBUG)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/69b471204467dd3434af0b5799984f3f3e6bbc60/SickBeard/medusa/failed_processor.py#L72">SickBeard/medusa/failed_processor.py</a>", line 72, in log
    log.log(level, message)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/69b471204467dd3434af0b5799984f3f3e6bbc60/SickBeard/medusa/logger/adapters/style.py#L82">SickBeard/medusa/logger/adapters/style.py</a>", line 82, in log
    self.logger.log(level, brace_msg, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1489, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1227, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [feature/add-cookies-bithdtv](../tree/feature/add-cookies-bithdtv)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@85e237e560749d23561f09e9e68f39f7a1ed9ac2
**Link to Log**: https://gist.github.com/f6fe0e4d94e25287ea8d8ebe2be42ae4
### ERROR
<pre>
2017-08-17 14:53:00 ERROR    Thread-19 :: [85e237e] Exception generated: level must be an integer
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/85e237e560749d23561f09e9e68f39f7a1ed9ac2/medusa/server/web/core/base.py#L258">medusa/server/web/core/base.py</a>", line 258, in async_call
    result = function(**kwargs)
  File "/home/pi/Medusa/<a href="../blob/85e237e560749d23561f09e9e68f39f7a1ed9ac2/medusa/server/web/home/post_process.py#L50">medusa/server/web/home/post_process.py</a>", line 50, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/home/pi/Medusa/<a href="../blob/85e237e560749d23561f09e9e68f39f7a1ed9ac2/medusa/process_tv.py#L142">medusa/process_tv.py</a>", line 142, in process
    if not self.should_process(path, failed):
  File "/home/pi/Medusa/<a href="../blob/85e237e560749d23561f09e9e68f39f7a1ed9ac2/medusa/process_tv.py#L234">medusa/process_tv.py</a>", line 234, in should_process
    self.process_failed(path)
  File "/home/pi/Medusa/<a href="../blob/85e237e560749d23561f09e9e68f39f7a1ed9ac2/medusa/process_tv.py#L587">medusa/process_tv.py</a>", line 587, in process_failed
    self.result = processor.process()
  File "/home/pi/Medusa/<a href="../blob/85e237e560749d23561f09e9e68f39f7a1ed9ac2/medusa/failed_processor.py#L53">medusa/failed_processor.py</a>", line 53, in process
    self.log(u'Parsed info: {result}'.format(result=parsed), logger.DEBUG)
  File "/home/pi/Medusa/<a href="../blob/85e237e560749d23561f09e9e68f39f7a1ed9ac2/medusa/failed_processor.py#L74">medusa/failed_processor.py</a>", line 74, in log
    log.log(level, message)
  File "/home/pi/Medusa/<a href="../blob/85e237e560749d23561f09e9e68f39f7a1ed9ac2/medusa/logger/adapters/style.py#L82">medusa/logger/adapters/style.py</a>", line 82, in log
    self.logger.log(level, brace_msg, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1482, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1220, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Update
