### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'BraceAdapter' object has no attribute 'DEBUG'

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2786]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@a2aaaf4dd43c018019a67fe1a27074b124681fa4
**Link to Log**: https://gist.github.com/66f5f5fc2f3cc2fbaec732d8d994335e
### ERROR
<pre>
2017-05-12 08:29:52 ERROR    SEARCHQUEUE-FORCED-309269 :: [Rarbg] :: [a2aaaf4] Unknown exception while searching Rarbg. Error: "'BraceAdapter' object has no attribute 'DEBUG'"
Traceback (most recent call last):
  File "C:\Medusa\medusa\search\core.py", line 547, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "C:\Medusa\medusa\providers\generic_provider.py", line 207, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "C:\Medusa\medusa\providers\torrent\json\rarbg.py", line 136, in search
    log_level = log.DEBUG
AttributeError: 'BraceAdapter' object has no attribute 'DEBUG'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2787
