### ISSUE TITLE
[APP SUBMITTED]: TypeError: izip argument #1 must support iteration

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#2795]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@627aad75fb55de611256c20404ba44670fb3db1c
**Link to Log**: https://gist.github.com/81277ff907ebe35eefe8c683033f93d8
### ERROR
<pre>
2017-05-15 10:17:52 ERROR    Thread-34 :: [627aad7] Exception generated: izip argument #1 must support iteration
Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 259, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\core\history.py", line 30, in index
    app.instance.save_config()
  File "C:\Medusa\medusa\__main__.py", line 1527, in save_config
    encrypted_attribute = helpers.encrypt(getattr(provider, attr, ''), app.ENCRYPTION_VERSION)
  File "C:\Medusa\medusa\helpers\__init__.py", line 979, in encrypt
    ''.join(chr(ord(x) ^ ord(y)) for (x, y) in izip(data, cycle(app.ENCRYPTION_SECRET)))).strip()
TypeError: izip argument #1 must support iteration
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by JigSawFr** [comment]
same error encountered now, will post more infos as soon as possible
