### ISSUE TITLE
[APP SUBMITTED]: TypeError: unsupported type for timedelta seconds component: NoneType

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2799]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@fffcab6b58c3ff22a20a4540e0df10f9e8591d0f
**Link to Log**: https://gist.github.com/70e920963c7c822996b79e1f64f754d8
### ERROR
<pre>
2017-05-16 10:09:22 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [LimeTorrents] :: [fffcab6] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/limetorrents.py", line 172, in parse\n    if pubdate_raw else None\nTypeError: unsupported type for timedelta seconds component: NoneType\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/fffcab6b58c3ff22a20a4540e0df10f9e8591d0f/medusa/providers/torrent/html/limetorrents.py#L172">medusa/providers/torrent/html/limetorrents.py</a>", line 172, in parse
    if pubdate_raw else None
TypeError: unsupported type for timedelta seconds component: NoneType
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@c6cfffda61889c79e68cb028149fa354f8cd7462
**Link to Log**: https://gist.github.com/1f64dce24d5facd826f0cc80b18f4ec3
### ERROR
<pre>
2017-05-19 07:34:02 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [LimeTorrents] :: [c6cfffd] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/pi/Medusa/medusa/providers/torrent/html/limetorrents.py", line 172, in parse\n    if pubdate_raw else None\nTypeError: unsupported type for timedelta seconds component: NoneType\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/c6cfffda61889c79e68cb028149fa354f8cd7462/medusa/providers/torrent/html/limetorrents.py#L172">medusa/providers/torrent/html/limetorrents.py</a>", line 172, in parse
    if pubdate_raw else None
TypeError: unsupported type for timedelta seconds component: NoneType
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
I think this is good input for #2788

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2788
