### ISSUE TITLE
T411 Exception

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2805]
``` python
SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Unknown exception while searching T411. Error: "'int' object has no attribute '__getitem__'"
Traceback (most recent call last):
  File "/opt/Medusa/medusa/search/core.py", line 547, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/opt/Medusa/medusa/providers/generic_provider.py", line 207, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/opt/Medusa/medusa/providers/torrent/json/t411.py", line 120, in search
    results += self.parse(jdata, mode)
  File "/opt/Medusa/medusa/providers/torrent/json/t411.py", line 144, in parse
    torrent_rows = sorted(unsorted_torrent_rows, key=itemgetter('added'), reverse=True)
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by p0psicles** [comment]
Need some more info. Which commit, what did you search for?

**Comment by fernandog** [comment]
from the log:
https://github.com/pymedusa/Medusa/blob/2e9e2b4/medusa/providers/torrent/json/t411.py

**Comment by fernandog** [comment]
@p0psicles `itemgetter` may raise that if unsorted_torrent_rows doesn't have `added` ?

**Comment by p0psicles** [comment]
Don't know. Thats why I need more info, so I can reproduce.

**Comment by IDerr** [comment]
Yep, sorry for the lack of informations, I'll dive in the log today and keep this issue updated.

**Comment by p0psicles** [comment]
We can also have a chat on irc, if you want

**Comment by IDerr** [comment]
``` shell
2017-05-18 14:09:09 INFO     SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Guessed more than one 'format' for 'One.Piece.Marine.Ford.Vol.3.Dvd.9.(498.à.502).DVDrip.ISO.VF': DVD,DVDRip
2017-05-18 14:09:09 INFO     SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Guessed more than one 'format' for 'One.Piece.Marine.Ford.Vol.3.Dvd.9.(498.à.502).DVDrip.ISO.VF': DVD,DVDRip
2017-05-18 14:09:02 INFO     SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Guessed more than one 'format' for 'One.Piece.Marine.Ford.Vol.1.Dvd.1.(457.à.461).DVDrip.ISO.VF': DVD,DVDRip
2017-05-18 14:09:02 INFO     SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Guessed more than one 'format' for 'One.Piece.Marine.Ford.Vol.1.Dvd.1.(457.à.461).DVDrip.ISO.VF': DVD,DVDRip
2017-05-18 14:09:02 INFO     SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Guessed more than one 'format' for 'One.Piece.Impel.Down.Vol.1.DVD.3.(430.à.434).DVDrip.ISO.VF': DVD,DVDRip
2017-05-18 14:09:02 ERROR    SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Unknown exception while searching T411. Error: "'int' object has no attribute '__getitem__'"
Traceback (most recent call last):
  File "/opt/Medusa/medusa/search/core.py", line 547, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/opt/Medusa/medusa/providers/generic_provider.py", line 207, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/opt/Medusa/medusa/providers/torrent/json/t411.py", line 120, in search
    results += self.parse(jdata, mode)
  File "/opt/Medusa/medusa/providers/torrent/json/t411.py", line 144, in parse
    torrent_rows = sorted(unsorted_torrent_rows, key=itemgetter('added'), reverse=True)
TypeError: 'int' object has no attribute '__getitem__'
2017-05-18 14:09:02 INFO     SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Guessed more than one 'format' for 'One.Piece.Impel.Down.Vol.1.DVD.3.(430.à.434).DVDrip.ISO.VF': DVD,DVDRip
2017-05-18 14:09:01 INFO     SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Guessed more than one 'format' for 'One.Piece.Impel.Down.Vol.1.Dvd.1.(422.à.425).DVDrip.ISO.VF': DVD,DVDRip
2017-05-18 14:09:01 INFO     SEARCHQUEUE-BACKLOG-81797 :: [T411] :: [2e9e2b4] Guessed more than one 'format' for 'One.Piece.Impel.Down.Vol.1.Dvd.1.(422.à.425).DVDrip.ISO.VF': DVD,DVDRip
```

**Comment by p0psicles** [comment]
Can you enable debug logs, and reproduce? I can't reproduce the error.
Also I asume your still on develop branch? Could you switch to the branch `feature/improve_t411_search`

**Comment by p0psicles** [comment]
Also what kind of search did you perform to get this?

**Comment by fernandog** [comment]
@p0psicles i could reproduce by doing this:


Notice that I didn't used `unsorted_torrent_rows` in the code but `[1,2,3]`
maybe we should check if `unsorted_torrent_rows` is a list of dict before sort it

![image](https://cloud.githubusercontent.com/assets/2620870/26250622/0389a7c0-3c81-11e7-853b-9f2a72549f0b.png)

**Comment by IDerr** [comment]
I'll dig into logs today

**Comment by IDerr** [comment]
Log rotation deleted logs  :(

I can't reproduce too so I'll close this issue
