### ISSUE TITLE
Anidex Exception

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#2806]
On develop, I'm getting this exception because they don't always post a torrent file but only a magnet link. But I don't if magnets links are fully supported by Medusa.
``` shell 
2017-05-19 09:18:34 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AniDex] :: [c6cfffd] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/opt/Medusa/medusa/providers/torrent/html/anidex.py", line 120, in parse\n    download_url = cells[labels.index(\'Torrent\')].a.get(\'href\')\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
Traceback (most recent call last):
  File "/opt/Medusa/medusa/providers/torrent/html/anidex.py", line 120, in parse
    download_url = cells[labels.index('Torrent')].a.get('href')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by p0psicles** [comment]
Yes they are, but we need to make a small change to the provider's code for that.

**Comment by p0psicles** [comment]
@medariox can you take a look at this?

**Comment by medariox** [comment]
Yes, it's a quick fix.

**Comment by medariox** [comment]
@IDerr 
Can you tell me a file that only has the magnet please?

**Comment by medariox** [comment]
Never mind, the issue was different. AniDex should always provide the download links. Fixed here: https://github.com/pymedusa/Medusa/pull/2808

**Comment by p0psicles** [comment]
To be sure i've tested about 10000 torrents. Some didn't have a magnet. But they always have a torrent link.

**Comment by IDerr** [comment]
Oops, my bad.
