### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#2846]
```
2017-05-31 17:10:51 INFO     MAIN :: [72e3c23] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tmdb.json
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/opt/python/2.7.9/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/home/travis/build/pymedusa/Medusa/medusa/logger/__init__.py", line 532, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/opt/python/2.7.9/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/opt/python/2.7.9/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by fernandog** [comment]
From @duramato:

```
2017-05-31 20:49:27 DEBUG    CHECKVERSION :: [94e0649] {cmd} : returned successful
2017-05-31 20:49:27 DEBUG    CHECKVERSION :: [94e0649] Executing {cmd} with your shell in {dir}
2017-05-31 20:49:27 DEBUG    CHECKVERSION :: [94e0649] {cmd} : returned successful
2017-05-31 20:49:27 DEBUG    CHECKVERSION :: [94e0649] Executing {cmd} with your shell in {dir}
2017-05-31 20:49:27 DEBUG    CHECKVERSION :: [94e0649] {cmd} : returned successful
2017-05-31 20:49:27 DEBUG    CHECKVERSION :: [94e0649] check_for_new_news: Checking GitHub for latest news.
```

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2852
