### ISSUE TITLE
[APP SUBMITTED]: ValueError: day is out of range for month

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#2847]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@94e0649919e9e05ac380f8e6d3817c18255931ee
**Link to Log**: https://gist.github.com/dd3f17857aff5dd573c7ee76011419cf
### ERROR
<pre>
2017-06-01 10:23:43 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [94e0649] Failed parsing publishing date: 31 mins ago
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/94e0649919e9e05ac380f8e6d3817c18255931ee/medusa/providers/generic_provider.py#L512">medusa/providers/generic_provider.py</a>", line 512, in parse_pubdate
    dt = parser.parse(pubdate, fuzzy=True)
  File "/home/pi/Medusa/<a href="../blob/94e0649919e9e05ac380f8e6d3817c18255931ee/lib/dateutil/parser.py#L1181">lib/dateutil/parser.py</a>", line 1181, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/pi/Medusa/<a href="../blob/94e0649919e9e05ac380f8e6d3817c18255931ee/lib/dateutil/parser.py#L584">lib/dateutil/parser.py</a>", line 584, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2851

**Comment by ripper1967** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@2a21fd430ad688cd633f8929d2fb90cd78362e9e
**Link to Log**: https://gist.github.com/49c0c867059d2aca48c2ef8709e72833
### ERROR
<pre>
2017-06-02 23:57:21 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [2a21fd4] Failed parsing publishing date: 31 mins ago
Traceback (most recent call last):
  File "C:\Medusa\medusa\providers\generic_provider.py", line 512, in parse_pubdate
    dt = parser.parse(pubdate, fuzzy=True)
  File "C:\Medusa\lib\dateutil\parser.py", line 1181, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Medusa\lib\dateutil\parser.py", line 584, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [danishbits_api](../tree/danishbits_api)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@4f80780808e57ebebdd3a9f6ee74f6d7607d1ec7
**Link to Log**: https://gist.github.com/e4cc1f690cb56d96aaf84caf77ee79f9
### ERROR
<pre>
2017-06-05 08:31:26 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [4f80780] Failed parsing publishing date.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/4f80780808e57ebebdd3a9f6ee74f6d7607d1ec7/medusa/providers/generic_provider.py#L502">medusa/providers/generic_provider.py</a>", line 502, in parse_pubdate
    dt = parser.parse(pubdate, fuzzy=True)
  File "/home/pi/Medusa/<a href="../blob/4f80780808e57ebebdd3a9f6ee74f6d7607d1ec7/lib/dateutil/parser.py#L1181">lib/dateutil/parser.py</a>", line 1181, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/pi/Medusa/<a href="../blob/4f80780808e57ebebdd3a9f6ee74f6d7607d1ec7/lib/dateutil/parser.py#L584">lib/dateutil/parser.py</a>", line 584, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
This is fixed. Your branch is not up to date with develop.

**Comment by ward0** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]`
**Operating System**: `Linux-3.2.40-armv7l-with-glibc2.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@2a21fd430ad688cd633f8929d2fb90cd78362e9e
**Link to Log**: https://gist.github.com/f17a0ebb4ea1ccb4b177375bedd022ea
### ERROR
<pre>
2017-06-15 21:50:43 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [2a21fd4] Failed parsing publishing date: 31 mins ago
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/SickBeard/medusa/providers/generic_provider.py#L512">SickBeard/medusa/providers/generic_provider.py</a>", line 512, in parse_pubdate
    dt = parser.parse(pubdate, fuzzy=True)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/SickBeard/lib/dateutil/parser.py#L1181">SickBeard/lib/dateutil/parser.py</a>", line 1181, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/SickBeard/lib/dateutil/parser.py#L584">SickBeard/lib/dateutil/parser.py</a>", line 584, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bangorbob** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]`
**Operating System**: `Linux-3.13.0-100-generic-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@2a21fd430ad688cd633f8929d2fb90cd78362e9e
**Link to Log**: https://gist.github.com/c1184c75c60be8d114e8bf2b3ccfc3d6
### ERROR
<pre>
2017-06-30 08:35:49 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [2a21fd4] Failed parsing publishing date: 31 mins ago
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/medusa/providers/generic_provider.py#L512">medusa/providers/generic_provider.py</a>", line 512, in parse_pubdate
    dt = parser.parse(pubdate, fuzzy=True)
  File "/opt/medusa/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/lib/dateutil/parser.py#L1181">lib/dateutil/parser.py</a>", line 1181, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/medusa/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/lib/dateutil/parser.py#L584">lib/dateutil/parser.py</a>", line 584, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bangorbob** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]`
**Operating System**: `Linux-3.13.0-100-generic-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@2a21fd430ad688cd633f8929d2fb90cd78362e9e
**Link to Log**: https://gist.github.com/8418fdc9c17264d1eb971951c1e923ce
### ERROR
<pre>
2017-06-29 20:05:10 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [2a21fd4] Failed parsing publishing date: 31 secs ago
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/medusa/providers/generic_provider.py#L512">medusa/providers/generic_provider.py</a>", line 512, in parse_pubdate
    dt = parser.parse(pubdate, fuzzy=True)
  File "/opt/medusa/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/lib/dateutil/parser.py#L1181">lib/dateutil/parser.py</a>", line 1181, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/medusa/<a href="../blob/2a21fd430ad688cd633f8929d2fb90cd78362e9e/lib/dateutil/parser.py#L584">lib/dateutil/parser.py</a>", line 584, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Already fixed in latest develop
