### ISSUE TITLE
failed restore of old sickrage env..

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#2856]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

 Medusa Info:	Branch: master
Commit: 2a21fd430ad688cd633f8929d2fb90cd78362e9e
Version: v0.1.12
Database: .0
 Python Version:	2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]
 SSL Version:	OpenSSL 1.0.2j 26 Sep 2016
 OS:	Linux-3.2.40-armv7l-with-glibc2.4
 Locale:	en_US.UTF-8
**What you did: backup from old sickrage, restore in medusa
**What happened: nothing, still blank medusa screen
**What you expected: my old SR environment...
**Logs:**
```
2017-06-03 12:46:47 DEBUG    MAIN :: [2a21fd4] Matched release Show.Name.S02E03.HDTV.x264-RLSGROUP to a series in your database: Show Name
2017-06-03 12:46:47 DEBUG    MAIN :: [2a21fd4] Parsed Show.Name.S02E03.HDTV.x264-RLSGROUP into title: Show Name, season: 2, episode: [3], format: HDTV, video_codec: h264, video_encoder: x264, release_group: RLSGROUP, type: episode, parsing_time: 1.64791989326, total_time: 1.65780210495, absolute_episode: [], quality: SDTV
2017-06-03 12:46:47 DEBUG    MAIN :: [2a21fd4] Found codec for Show Name Ep Name
2017-06-03 12:46:47 DEBUG    MAIN :: [2a21fd4] 1: Episode has no release group, replacing it with RLSGROUP
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] 1: Formatting pattern: %SN - S%0SE%0E - %EN -> Show Name - S02E03 - Ep Name
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] Matched release Show.Name.S02E03.HDTV.x264-RLSGROUP to a series in your database: Show Name
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] Parsed Show.Name.S02E03.HDTV.x264-RLSGROUP into title: Show Name, season: 2, episode: [3], format: HDTV, video_codec: h264, video_encoder: x264, release_group: RLSGROUP, type: episode, parsing_time: 0.474743843079, total_time: 0.477031946182, absolute_episode: [], quality: SDTV
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] Found codec for Show Name Ep Name
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] 1: Formatting pattern: Season %0S -> Season 02
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] Trying to parse Show Name - S02E03 - Ep Name.ext
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] Matched release Show Name - S02E03 - Ep Name.ext to a series in your database: Show Name
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] Parsed Show Name - S02E03 - Ep Name.ext into title: Show Name, season: 2, episode: [3], episode_title: Ep Name ext, type: episode, parsing_time: 0.266019105911, total_time: 0.267113924026, absolute_episode: [], quality: Unknown
2017-06-03 12:46:48 DEBUG    MAIN :: [2a21fd4] The name Show Name - S02E03 - Ep Name.ext parsed into title: Show Name, season: 2, episode: [3], episode_title: Ep Name ext, type: episode, parsing_time: 0.266019105911, total_time: 0.267113924026, absolute_episode: [], quality: Unknown
2017-06-03 12:46:49 INFO     MAIN :: [2a21fd4] Broken providers found: [u'sdbits', u'binsearch', u'extratorrent', u'freshontv', u'bithdtv']
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] Checking if we can use git commands: git version
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] Executing git version with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] git version : returned successful
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] Using: git
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] Executing git symbolic-ref -q HEAD with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] git symbolic-ref -q HEAD : returned successful
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] Executing git rev-parse HEAD with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] git rev-parse HEAD : returned successful
2017-06-03 12:46:49 DEBUG    MAIN :: [2a21fd4] Executing git describe --tags --abbrev=0 2a21fd430ad688cd633f8929d2fb90cd78362e9e with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:46:50 DEBUG    MAIN :: [2a21fd4] git describe --tags --abbrev=0 2a21fd430ad688cd633f8929d2fb90cd78362e9e : returned successful
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking database structure...main.db
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Initial Schema database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Initial Schema
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] InitialSchema upgrade completed
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Add Version To Tv Episodes database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] AddVersionToTvEpisodes upgrade not required
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Add Default Ep Status To Tv Shows database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] AddDefaultEpStatusToTvShows upgrade not required
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Alter Shows Field Types database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] AlterTVShowsFieldTypes upgrade not required
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Add Minor Version database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Add Minor Version
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Add minor version numbers to database
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Updated to: 42.1
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] AddMinorVersion upgrade completed
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Test Increase Major Version database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Test Increase Major Version
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Test major and minor version updates database
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Updated to: 43.1
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] TestIncreaseMajorVersion upgrade completed
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Add Proper Tags database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Add Proper Tags
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Adding column proper_tags to history
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking for old propers without proper tags
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Updated to: 43.2
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] AddProperTags upgrade completed
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Add Manual Searched database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Add Manual Searched
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Adding column manually_searched to history
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Adding column manually_searched to tv_episodes
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking for old propers without proper tags
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Updated to: 43.3
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] AddManualSearched upgrade completed
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Add Info Hash database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Add Info Hash
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:55 INFO     MAIN :: [2a21fd4] Adding column info_hash in history
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] AddInfoHash upgrade completed
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Checking Add Plot database upgrade
2017-06-03 12:46:55 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Add Plot
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Adding column plot in imdb_info
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Adding column plot in tv_show
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddPlot upgrade completed
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Resource Size database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Add Resource Size
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Adding column size in history
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddResourceSize upgrade completed
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Indexer Mapping database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Add Indexer Mapping
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Adding PK to mindexer column in indexer_mapping table
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddPKIndexerMapping upgrade completed
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Indexer Integer database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Database upgrade required: Add Indexer Integer
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Backing up database before upgrade
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Proceeding with upgrade
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Make indexer and indexer_id as INTEGER in tv_episodes table
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddIndexerInteger upgrade completed
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking database structure...cache.db
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Initial Schema database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] InitialSchema upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Scene Exceptions database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddSceneExceptions upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Scene Name Cache database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddSceneNameCache upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Network Timezones database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddNetworkTimezones upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Last Search database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddLastSearch upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Scene Exceptions Seasons database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddSceneExceptionsSeasons upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Scene Exceptions Custom database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddSceneExceptionsCustom upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Scene Exceptions Refresh database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddSceneExceptionsRefresh upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Convert Scene Exeptions To Indexer Scheme database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] ConvertSceneExeptionsToIndexerScheme upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Convert Scene Names To Indexer Scheme database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] ConvertSceneNamesToIndexerScheme upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Remove Indexer Update Schema database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] RemoveIndexerUpdateSchema upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Add Indexer Scene Exceptions database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] AddIndexerSceneExceptions upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Performing a vacuum on the CACHE database
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking database structure...failed.db
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Initial Schema database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] InitialSchema upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking Size And Provider database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] SizeAndProvider upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking History database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] History upgrade not required
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking History Status database upgrade
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] HistoryStatus upgrade not required
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Missing idx_tv_episodes_showid_airdate for TV Episodes table detected!, fixing...
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Missing idx_showid for TV Episodes table detected!, fixing...
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Missing idx_status for TV Episodes table detected!, fixing...
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Missing idx_sta_epi_air for TV Episodes table detected!, fixing...
2017-06-03 12:46:56 INFO     MAIN :: [2a21fd4] Missing idx_sta_epi_sta_air for TV Episodes table detected!, fixing...
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking for archived episodes not qualified
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking for delete episodes with subtitle reference
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking for null indexer mappings
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Checking if we can use git commands: git version
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] Executing git version with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:46:56 DEBUG    MAIN :: [2a21fd4] git version : returned successful
2017-06-03 12:46:57 DEBUG    MAIN :: [2a21fd4] Using: git
2017-06-03 12:46:57 DEBUG    MAIN :: [2a21fd4] Executing git symbolic-ref -q HEAD with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:46:57 DEBUG    MAIN :: [2a21fd4] git symbolic-ref -q HEAD : returned successful
2017-06-03 12:46:57 DEBUG    MAIN :: [2a21fd4] Retrieving the last check time from the DB
2017-06-03 12:46:57 INFO     MAIN :: [2a21fd4] Writing PID: 26814 to /usr/local/sickbeard-custom/var/sickbeard-custom.pid
2017-06-03 12:46:57 DEBUG    MAIN :: [2a21fd4] Loading initial show list
2017-06-03 12:46:57 INFO     MAIN :: [2a21fd4] Starting Medusa [master] using '/usr/local/sickbeard-custom/var/config.ini'
2017-06-03 12:46:58 INFO     TORNADO :: [2a21fd4] Starting Medusa on http://0.0.0.0:8083/
2017-06-03 12:46:59 DEBUG    CHECKVERSION :: [2a21fd4] Starting new thread: CHECKVERSION
2017-06-03 12:46:59 DEBUG    CHECKVERSION :: [2a21fd4] Executing git config remote.origin.url https://github.com/pymedusa/Medusa with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:46:59 INFO     MAIN :: [2a21fd4] Updating exception_cache and exception_season_cache
2017-06-03 12:46:59 DEBUG    CHECKVERSION :: [2a21fd4] git config remote.origin.url https://github.com/pymedusa/Medusa : returned successful
2017-06-03 12:46:59 DEBUG    CHECKVERSION :: [2a21fd4] Executing git symbolic-ref -q HEAD with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:47:00 DEBUG    CHECKVERSION :: [2a21fd4] git symbolic-ref -q HEAD : returned successful
2017-06-03 12:47:00 DEBUG    CHECKVERSION :: [2a21fd4] Executing git ls-remote --heads origin with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:47:00 INFO     MAIN :: [2a21fd4] Finished processing 2448 scene exceptions.
2017-06-03 12:47:00 INFO     MAIN :: [2a21fd4] Building internal name cache for all shows
2017-06-03 12:47:00 DEBUG    MAIN :: [2a21fd4] Started updating network timezones
2017-06-03 12:47:04 DEBUG    CHECKVERSION :: [2a21fd4] git ls-remote --heads origin : returned successful
2017-06-03 12:47:04 INFO     CHECKVERSION :: [2a21fd4] Checking for updates using GIT
2017-06-03 12:47:04 DEBUG    CHECKVERSION :: [2a21fd4] Executing git symbolic-ref -q HEAD with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:47:05 DEBUG    CHECKVERSION :: [2a21fd4] git symbolic-ref -q HEAD : returned successful
2017-06-03 12:47:05 DEBUG    CHECKVERSION :: [2a21fd4] Executing git rev-parse HEAD with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:47:05 DEBUG    CHECKVERSION :: [2a21fd4] git rev-parse HEAD : returned successful
2017-06-03 12:47:05 DEBUG    CHECKVERSION :: [2a21fd4] Executing git config remote.origin.url https://github.com/pymedusa/Medusa with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:47:05 DEBUG    CHECKVERSION :: [2a21fd4] git config remote.origin.url https://github.com/pymedusa/Medusa : returned successful
2017-06-03 12:47:05 DEBUG    CHECKVERSION :: [2a21fd4] Executing git fetch origin with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:47:06 DEBUG    MAIN :: [2a21fd4] Finished updating network timezones
2017-06-03 12:47:07 DEBUG    CHECKVERSION :: [2a21fd4] git fetch origin : returned successful
2017-06-03 12:47:07 DEBUG    CHECKVERSION :: [2a21fd4] Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:47:08 DEBUG    CHECKVERSION :: [2a21fd4] git rev-parse --verify --quiet "@{upstream}" : returned successful
2017-06-03 12:47:08 DEBUG    CHECKVERSION :: [2a21fd4] Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /volume1/@appstore/sickbeard-custom/var/SickBeard
2017-06-03 12:47:08 DEBUG    CHECKVERSION :: [2a21fd4] git rev-list --left-right "@{upstream}"...HEAD : returned successful
2017-06-03 12:47:08 DEBUG    CHECKVERSION :: [2a21fd4] cur_commit = 2a21fd430ad688cd633f8929d2fb90cd78362e9e, newest_commit = 2a21fd430ad688cd633f8929d2fb90cd78362e9e, num_commits_behind = 0, num_commits_ahead = 0
2017-06-03 12:47:08 DEBUG    CHECKVERSION :: [2a21fd4] check_for_new_news: Checking GitHub for latest news.
2017-06-03 12:48:33 ERROR    Thread-16 :: [2a21fd4] Exception generated: list index out of range
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/error_logs.py", line 138, in viewlog
    t = PageTemplate(rh=self, filename='viewlogs.mako')
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 61, in __init__
    self.template = lookup.get_template(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/mako/compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/sickbeard-custom/var/cache/mako/viewlogs.mako.py", line 24, in <module>
    random_show = choice(app.showList)
  File "/usr/local/python/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```
I already did like 4times the restore and waited 8houres(sleep)

sidenode, when medusa tells me to restart after restore, my application in synology is 'stopped', i have to manually start it again.

**Comment by medariox** [comment]
Can you access ```/home```? The error you posted should only occur if you access ```/errorlogs/viewlog``` without shows in your library. The restore should have been completed. What is the issue exactly? Please try to describe the problem.

**Comment by ward0** [comment]
@medariox 

i have these rights:

![image](https://cloud.githubusercontent.com/assets/15545810/26753168/cbb0b550-4860-11e7-83d6-e1471100f39b.png)

so that should not be a problem...

I had a 'old' sickrage install, i did a backup in the menu, and i'm doing a restore in medusa. it says succesful restored backup, restart medusa.

i do that and then in synoloy my app goes into state stoppend and nothing more.

**Comment by medariox** [comment]
So Medusa doesn't even start? Do you have debug logs for that? The error you posted above is a different issue.

**Comment by ward0** [comment]
it does start, its just that after the restore, i have to restart the package...

then the 'application' in synology goes into stopped state.

I don't have logs of that.

**Comment by ratoaq2** [comment]
If you ssh in your synology, you can find the logs in:
`/usr/local/sickbeard-custom/var/Logs`

**Comment by ward0** [comment]
I already showed those logs.. i just did a clean install and manually reset my settings.. i'l close the ticket.
