### ISSUE TITLE
TypeError: sequence item 0: expected string or Unicode, int found

### ISSUE THREAD

**Issue by ratoaq2** [pymedusa/Medusa#2871]
Latest dev

While doing a manual search

```
2017-06-10 20:09:09 ERROR    SEARCHQUEUE-MANUAL-272644 :: [Torrentz2] :: [21ec574] Unknown exception while searching Torrentz2. Error: 'sequence item 0: expected string or Unicode, int found'
Traceback (most recent call last):
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/search/core.py", line 553, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/volumeUSB1/usbshare/applications/sickrage/SickBeard/medusa/providers/generic_provider.py", line 402, in find_search_results
    ', '.join(search_result.parsed_result.episode_numbers),
TypeError: sequence item 0: expected string or Unicode, int found
```

**Comment by NicoLeOca** [comment]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@21ec574d66160255f9de95a78ad5742ac256cad5
**Link to Log**: https://gist.github.com/23a3406832e5d6534b146c1cee87f28a
### ERROR
<pre>
2017-06-10 23:17:13 ERROR    SEARCHQUEUE-BACKLOG-320724 :: [Nzb.su] :: [21ec574] Unknown exception while searching Nzb.su. Error: 'sequence item 0: expected string or Unicode, int found'
Traceback (most recent call last):
  File "C:\Medusa\medusa\search\core.py", line 553, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "C:\Medusa\medusa\providers\generic_provider.py", line 402, in find_search_results
    ', '.join(search_result.parsed_result.episode_numbers),
TypeError: sequence item 0: expected string or Unicode, int found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by NicoLeOca** [comment]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@21ec574d66160255f9de95a78ad5742ac256cad5
**Link to Log**: https://gist.github.com/bae68b33afe134a641deb6416d2c7be3
### ERROR
<pre>
2017-06-10 23:07:58 ERROR    SEARCHQUEUE-BACKLOG-313999 :: [Rarbg] :: [21ec574] Unknown exception while searching Rarbg. Error: 'sequence item 0: expected string or Unicode, int found'
Traceback (most recent call last):
  File "C:\Medusa\medusa\search\core.py", line 553, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "C:\Medusa\medusa\providers\generic_provider.py", line 402, in find_search_results
    ', '.join(search_result.parsed_result.episode_numbers),
TypeError: sequence item 0: expected string or Unicode, int found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by NicoLeOca** [comment]
### INFO
**Python Version**: `2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@21ec574d66160255f9de95a78ad5742ac256cad5
**Link to Log**: https://gist.github.com/0e484b534f70fa331f9e4894965c6eb0
### ERROR
<pre>
2017-06-10 22:27:53 ERROR    SEARCHQUEUE-BACKLOG-280706 :: [Usenet-Crawler] :: [21ec574] Unknown exception while searching Usenet-Crawler. Error: 'sequence item 0: expected string or Unicode, int found'
Traceback (most recent call last):
  File "C:\Medusa\medusa\search\core.py", line 553, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "C:\Medusa\medusa\providers\generic_provider.py", line 402, in find_search_results
    ', '.join(search_result.parsed_result.episode_numbers),
TypeError: sequence item 0: expected string or Unicode, int found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/2877

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@21ec574d66160255f9de95a78ad5742ac256cad5
**Link to Log**: https://gist.github.com/ed0b43e97d2c9ecbea2365fd58453261
### ERROR
<pre>
2017-06-13 01:01:49 ERROR    SEARCHQUEUE-BACKLOG-324080 :: [Torrentz2] :: [21ec574] Unknown exception while searching Torrentz2. Error: 'sequence item 0: expected string or Unicode, int found'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/21ec574d66160255f9de95a78ad5742ac256cad5/medusa/search/core.py#L553">medusa/search/core.py</a>", line 553, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/home/pi/Medusa/<a href="../blob/21ec574d66160255f9de95a78ad5742ac256cad5/medusa/providers/generic_provider.py#L402">medusa/providers/generic_provider.py</a>", line 402, in find_search_results
    ', '.join(search_result.parsed_result.episode_numbers),
TypeError: sequence item 0: expected string or Unicode, int found
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
