### ISSUE TITLE
Updating Network Timezones failed

### ISSUE THREAD

**Issue by jsirota554** [pymedusa/Medusa#2876]
### Before submitting your issue:
2017-06-12 13:31:54 WARNING  MAIN :: [2a21fd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**Master 0.1.
**OS:**Windows 7
**What you did:**Installed Medusa within a VMWare VM
**What happened:** Receive this error frequently 2017-06-12 13:31:54 WARNING  MAIN :: [2a21fd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt cannot goto schedule page without getting

Mako Error
A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.
Show/Hide Error

File C:\Medusa-0.1.13\lib\dateutil\tz\win.py:178, in transitions:
dstoff -= self._dst_base_offset
OverflowError: date value out of range

**What you expected:**
**Logs:**
```
Mako Error
A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.
Show/Hide Error


File C:\Medusa-0.1.13\lib\dateutil\tz\win.py:178, in transitions:
dstoff -= self._dst_base_offset
OverflowError: date value out of range

2017-06-12 13:35:08 INFO     Thread-16 :: [2a21fd4] OverflowError: date value out of range
2017-06-12 13:31:55 INFO     Thread-16 :: [2a21fd4] OverflowError: date value out of range
2017-06-12 13:31:54 WARNING  MAIN :: [2a21fd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
```

**Comment by fernandog** [comment]
@p0psicles maybe we finally got the issue of network timezones: `OverflowError: date value out of range`  ? but no idea what's wrong....

**Comment by fernandog** [comment]
@jsirota554  can you send the full error please? open logs file and search for: OverflowError: date value out of range

**Comment by jsirota554** [comment]
2017-06-12 12:41:22 INFO     Thread-16 :: [2a21fd4] OverflowError: date value out of range

This is what im finding in the application.log

**Comment by fernandog** [comment]
@jsirota554 can you send some logs after and some logs before that line?

**Comment by jsirota554** [comment]
2017-06-13 04:09:45 ERROR    DAILYSEARCHER :: [2a21fd4] Exception generated: date value out of range
Traceback (most recent call last):
  File "C:\Medusa-0.1.13\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "C:\Medusa-0.1.13\medusa\search\daily.py", line 55, in run
    cur_time = datetime.now(app_timezone)
  File "C:\Medusa-0.1.13\lib\dateutil\tz\_common.py", line 280, in fromutc
    transitions = self.transitions(dt.year)
  File "C:\Medusa-0.1.13\lib\dateutil\tz\win.py", line 178, in transitions
    dstoff -= self._dst_base_offset
OverflowError: date value out of range
2017-06-13 03:29:48 ERROR    CHECKVERSION :: [2a21fd4] Environment error: [Errno 11004] getaddrinfo failed
Traceback (most recent call last):
  File "C:\Medusa-0.1.13\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "C:\Medusa-0.1.13\medusa\version_checker.py", line 58, in run
    self.list_remote_branches()
  File "C:\Medusa-0.1.13\medusa\version_checker.py", line 349, in list_remote_branches
    app.GIT_REMOTE_BRANCHES = self.updater.list_remote_branches()
  File "C:\Medusa-0.1.13\medusa\version_checker.py", line 983, in list_remote_branches
    gh = get_github_repo(app.GIT_ORG, app.GIT_REPO)
  File "C:\Medusa-0.1.13\medusa\github_client.py", line 95, in get_github_repo
    return gh.get_organization(organization).get_repo(repo)
  File "C:\Medusa-0.1.13\lib\github\MainClass.py", line 189, in get_organization
    "/orgs/" + login
  File "C:\Medusa-0.1.13\lib\github\Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\Medusa-0.1.13\lib\github\Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Medusa-0.1.13\lib\github\Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\Medusa-0.1.13\lib\github\Requester.py", line 277, in __requestRaw
    requestHeaders
  File "C:\Python27\lib\httplib.py", line 946, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 987, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 940, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 803, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 755, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1152, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 551, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 11004] getaddrinfo failed

**Comment by jsirota554** [comment]
2017-06-13 08:28:09 INFO     Thread-17 :: [2a21fd4] OverflowError: date value out of range
2017-06-13 08:19:55 INFO     POSTPROCESSOR :: [2a21fd4] Successfully processed.
2017-06-13 08:15:03 INFO     FINDPROPERS :: [2a21fd4] Completed the search for new propers, next check in approx. 14m, 53s

The overflowError occurs when browsing to the Schedule page in the above example no logs above or below

**Comment by p0psicles** [comment]
@jsirota554, what's your local timezone?
LIke if you go to the bottom of the page, you'll see something like this:
![image](https://user-images.githubusercontent.com/1331394/27088306-9ad0b774-5057-11e7-8cf8-5c3279dbf092.png)

Is that correct?

**Comment by jsirota554** [comment]
![image](https://user-images.githubusercontent.com/27033997/27088518-80de570c-501d-11e7-8a0e-6f97d1071697.png)

**Comment by p0psicles** [comment]
I have no idea where to start to fix this. Maybe this branch, can give some more info.
feature/issue-2876-add-warning-logging

running: 
```git fetch origin
git checkout -t origin/feature/issue-2876-add-warning-logging
```
`Don't forget to restart medusa.`
Should do the trick.

**Comment by jsirota554** [comment]
2017-06-13 11:40:27 DEBUG    MAIN :: [2a21fd4] Started updating network timezones
2017-06-13 11:40:27 WARNING  Thread-20 :: [2a21fd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-06-13 11:40:27 DEBUG    Thread-21 :: [2a21fd4] Started updating network timezones
2017-06-13 11:40:27 DEBUG    Thread-20 :: [2a21fd4] Started updating network timezones
2017-06-13 11:40:27 DEBUG    MAIN :: [2a21fd4] Error requesting url https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt. Error: [Errno 1] _ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2017-06-13 11:40:27 WARNING  MAIN :: [2a21fd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-06-13 11:40:27 DEBUG    Thread-21 :: [2a21fd4] Error requesting url https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt. Error: [Errno 1] _ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2017-06-13 11:40:27 DEBUG    MAIN :: [2a21fd4] Started updating network timezones
2017-06-13 11:40:27 DEBUG    Thread-20 :: [2a21fd4] Error requesting url https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt. Error: [Errno 1] _ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
2017-06-13 11:40:27 WARNING  Thread-21 :: [2a21fd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-06-13 11:40:28 WARNING  Thread-20 :: [2a21fd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-06-13 11:40:28 DEBUG    MAIN ::

**Comment by fernandog** [comment]
@jsirota554 did you open Schedule page? what is the warning after you opened it?

**Comment by jsirota554** [comment]
Error on Schedule Page

Mako Error
A mako error has occured.
If this happened during an update a simple page refresh may be the solution.
Mako errors that happen during updates may be a one time error if there were significant ui changes.

File C:\Users\sirota554\Documents\GitHub\Medusa2\lib\dateutil\tz\win.py:178, in transitions:
dstoff -= self._dst_base_offset
OverflowError: date value out of range

This is log after schedule page

017-06-13 12:12:24 INFO     Thread-34 :: [4538dd4] OverflowError: date value out of range
2017-06-13 12:12:01 WARNING  MAIN :: [4538dd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-06-13 12:12:00 INFO     MAIN :: [4538dd4] Building internal name cache for all shows

**Comment by fernandog** [comment]
@jsirota554 

Stop medusa
Open file /medusa/search/daily.py in notepad or other text editor, erase everything and paste this https://raw.githubusercontent.com/pymedusa/Medusa/4538dd4b5b52c1dc1810e9fb5a29c86052d71f12/medusa/search/daily.py
Start Medusa

Open schedule page again and report us this log message: `Could not get current time using the timezone: .....`

**Comment by jsirota554** [comment]
Still only get these logs when opening Schedule page

2017-06-13 12:25:41 INFO     Thread-27 :: [4538dd4] OverflowError: date value out of range
2017-06-13 12:25:31 WARNING  MAIN :: [4538dd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt

**Comment by jsirota554** [comment]
Debug logs 

2017-06-13 12:29:13 INFO     Thread-34 :: [4538dd4] OverflowError: date value out of range
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:\Users\**********\Documents\GitHub\Medusa2\lib\dateutil\tz\win.py, line 178, in transitions
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:\Users\**********\Documents\GitHub\Medusa2\lib\dateutil\tz\_common.py, line 333, in _isdst
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:\Users\**********\Documents\GitHub\Medusa2\lib\dateutil\tz\_common.py, line 245, in utcoffset
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:/Users/**********/Documents/GitHub/Medusa2/views/schedule.mako, line 223, in render_content
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:/Users/**********/Documents/GitHub/Medusa2/views/layouts/main.mako, line 57, in render_body
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:\Users\**********\Documents\GitHub\Medusa2\lib\mako\runtime.py, line 890, in _exec_template
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:\Users\**********\Documents\GitHub\Medusa2\lib\mako\runtime.py, line 864, in _render_context
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:\Users\**********\Documents\GitHub\Medusa2\lib\mako\runtime.py, line 829, in _render
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:\Users\**********\Documents\GitHub\Medusa2\lib\mako\template.py, line 454, in render_unicode
2017-06-13 12:29:13 DEBUG    Thread-34 :: [4538dd4] File C:\Users\**********\Documents\GitHub\Medusa2\medusa\server\web\core\base.py, line 126, in render
2017-06-13 12:28:34 INFO     Thread-27 :: [4538dd4] OverflowError: date value out of range

**Comment by fernandog** [comment]
@jsirota554 can you join IRC inside the medusa app? check wrench menu

**Comment by p0psicles** [comment]
I forgot to mention. You have to start a daily search. The mako error, can be related. But for now, I only have added the logs in the daily search.

**Comment by jsirota554** [comment]
2017-06-13 12:37:25 ERROR    DAILYSEARCHER :: [4538dd4] Exception generated: date value out of range
Traceback (most recent call last):
  File "C:\Users\**********\Documents\GitHub\Medusa2\medusa\scheduler.py", line 103, in run
    self.action.run(self.force)
  File "C:\Users\**********\Documents\GitHub\Medusa2\medusa\search\daily.py", line 94, in run
    end_time = show_air_time.astimezone(app_timezone) + timedelta(minutes=try_int(show.runtime, 60))
  File "C:\Users\**********\Documents\GitHub\Medusa2\lib\dateutil\tz\_common.py", line 280, in fromutc
    transitions = self.transitions(dt.year)
  File "C:\Users\**********\Documents\GitHub\Medusa2\lib\dateutil\tz\win.py", line 178, in transitions
    dstoff -= self._dst_base_offset
OverflowError: date value out of range
2017-06-13 12:37:25 WARNING  DAILYSEARCHER :: [4538dd4] Could not get current time using the timezone: tzwinlocal(). Error: OverflowError('date value out of range',)
2017-06-13 12:37:24 WARNING  DAILYSEARCHER :: [4538dd4] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2017-06-13 12:37:24 INFO     Thread-34 :: [4538dd4] Daily search forced

**Comment by jsirota554** [comment]
joined IRC

**Comment by jsirota554** [comment]
>>> try:
...     app_timezone = tz.tzwinlocal() if tz.tzwinlocal else tz.tzlocal()
... except Exception:
...     app_timezone = tz.tzlocal()
...
>>> print app_timezone
tzwinlocal(u'Central Standard Time')
>>> cur_time = datetime.now(app_timezone)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\dateutil\tz\_common.py", line 280, in from
utc
    transitions = self.transitions(dt.year)
  File "C:\Python27\lib\site-packages\dateutil\tz\win.py", line 178, in transiti
ons
    dstoff -= self._dst_base_offset
OverflowError: date value out of range

**Comment by fernandog** [comment]
@p0psicles I teamviewed and runned that ^^

**Comment by jsirota554** [comment]
So this was my first time trying out vmware i rebuilt the machine using virtualbox, timezone settings are working properly don't know if the issue was related to a setting in vmware but removed the system
