### ISSUE TITLE
Failed parsing publishing date: 31 mins ago

### ISSUE THREAD

**Issue by dany20mh** [pymedusa/Medusa#2887]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: master / 2a21fd430ad688cd633f8929d2fb90cd78362e9e
**OS: macOS 10.13
**What you did: Search for episode
**What happened: Getting these errors while searching in log
**What you expected: -- 
**Logs:

```
  File "/Applications/Medusa/medusa/show_queue.py", line 629, in run
    self.show.refresh_dir()
  File "/Applications/Medusa/medusa/tv/series.py", line 1721, in refresh_dir
    self.load_episodes_from_dir()
  File "/Applications/Medusa/medusa/tv/series.py", line 919, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/Applications/Medusa/medusa/tv/series.py", line 1377, in make_ep_from_file
    root_ep.create_meta_files()
  File "/Applications/Medusa/medusa/tv/episode.py", line 1076, in create_meta_files
    if not self.show.is_location_valid():
  File "/Applications/Medusa/medusa/tv/episode.py", line 291, in __getattr__
    item=item, refactor=refactor, trace=traceback.print_stack(),
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
```

I also got this in error log

```
2017-06-14 11:56:39 ERROR    SHOWQUEUE-ADD :: [2a21fd4] Error searching dir for episodes: 
Traceback (most recent call last):
  File "/Applications/Medusa/medusa/show_queue.py", line 562, in run
    self.show.load_episodes_from_dir()
  File "/Applications/Medusa/medusa/tv/series.py", line 907, in load_episodes_from_dir
    media_files = helpers.list_media_files(self.location)
  File "/Applications/Medusa/medusa/helpers/__init__.py", line 256, in list_media_files
    for cur_file in os.listdir(path):
  File "/Applications/Medusa/medusa/init/filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
OSError: [Errno 2] No such file or directory: '/Users/danial/mtng/Plex/TV Show/Salvation'
2017-06-14 10:12:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentProject] :: [2a21fd4] Failed parsing publishing date: 31 mins ago
Traceback (most recent call last):
  File "/Applications/Medusa/medusa/providers/generic_provider.py", line 512, in parse_pubdate
    dt = parser.parse(pubdate, fuzzy=True)
  File "/Applications/Medusa/lib/dateutil/parser.py", line 1181, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Applications/Medusa/lib/dateutil/parser.py", line 584, in parse
    ret = default.replace(**repl)
ValueError: day is out of range for month
```

**Comment by fernandog** [comment]
@medariox @duramato already fixed?

**Comment by p0psicles** [comment]
First error is fixed in latest develop.

The parse_pubdate error should have already been fixed in current master. So I don't know how that got in there.

**Comment by medariox** [comment]
2nd error is fixed in develop, but not in master: https://github.com/pymedusa/Medusa/commit/28b523c451e13f478c605db0c44b4765b84a55b4
