### ISSUE TITLE
TypeError: pick_best_result() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#2909]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:**
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
2017-06-23 07:23:31 DEBUG    SEARCHQUEUE-BACKLOG-220411 :: [NZBStars] :: [dd1c995] Seeing if we want to bother with multi-episode result 2.Broke.Girls.S06E01-E02.720p.HDTV.X264-DIMENSION
2017-06-23 07:23:31 DEBUG    SEARCHQUEUE-BACKLOG-220411 :: [NZBStars] :: [dd1c995] Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\search\queue.py", line 531, in run
    search_result = search_providers(self.show, self.segment)
  File "H:\usr\local\medusa\medusa\search\core.py", line 743, in search_providers
    multi_result = pick_best_result(_multi_result, show)
TypeError: pick_best_result() takes exactly 1 argument (2 given)
```

**Comment by p0psicles** [comment]
The _multi_result includes the show object.

**Comment by p0psicles** [comment]
@fernandog
