### ISSUE TITLE
Search Error to Find Files

### ISSUE THREAD

**Issue by dany20mh** [pymedusa/Medusa#2922]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: master**
**OS: macOS 10.13**
**What you did: Just search for file that so the library get update base on the file in the drive**
**What happened: It find some of them, but the error was keep repeating in the terminal**
**What you expected:**
**Logs:**

```
2017-06-28 12:08:08 INFO     SHOWQUEUE-REFRESH :: [2a21fd4] 275557: Performing refresh on Broad City
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Applications/Medusa/medusa/show_queue.py", line 629, in run
    self.show.refresh_dir()
  File "/Applications/Medusa/medusa/tv/series.py", line 1721, in refresh_dir
    self.load_episodes_from_dir()
  File "/Applications/Medusa/medusa/tv/series.py", line 919, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/Applications/Medusa/medusa/tv/series.py", line 1377, in make_ep_from_file
    root_ep.create_meta_files()
  File "/Applications/Medusa/medusa/tv/episode.py", line 1076, in create_meta_files
    if not self.show.is_location_valid():
  File "/Applications/Medusa/medusa/tv/episode.py", line 291, in __getattr__
    item=item, refactor=refactor, trace=traceback.print_stack(),
```

Also this 

```
2017-06-28 12:18:52 ERROR    SHOWQUEUE-REFRESH :: [2a21fd4] 325517: Error while refreshing show Salvation. Error: 
Traceback (most recent call last):
  File "/Applications/Medusa/medusa/show_queue.py", line 629, in run
    self.show.refresh_dir()
  File "/Applications/Medusa/medusa/tv/series.py", line 1721, in refresh_dir
    self.load_episodes_from_dir()
  File "/Applications/Medusa/medusa/tv/series.py", line 907, in load_episodes_from_dir
    media_files = helpers.list_media_files(self.location)
  File "/Applications/Medusa/medusa/helpers/__init__.py", line 256, in list_media_files
    for cur_file in os.listdir(path):
  File "/Applications/Medusa/medusa/init/filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
OSError: [Errno 2] No such file or directory: '/Users/danial/mtng/Plex/TV Show/Salvation'
```

**Comment by dany20mh** [comment]
@p0psicles any reason you close this?

**Comment by p0psicles** [comment]
Accident. Sorry

**Comment by medariox** [comment]
@dany20mh 
Looks like the connection to the drive was shortly interrupted while refreshing?

**Comment by dany20mh** [comment]
@medariox 
No, the connection is there, and the files are there too and I can access them, it's just those error keep repeating in the terminal, over and over, but I can see that app is accessing the file to search if they exist so add them to the library.

And the second log is for an empty folder that I have, which is telling that it's not exist.

**Comment by p0psicles** [comment]
First one is a refactor warning. For which I need to check if it's already fixed in develop. Second one can be a bug related to empty show folders.

**Comment by medariox** [comment]
@p0psicles 
That warning should only show if running Medusa with ```-Wd``` argument. Anyway, I can confirm it is already fixed in develop.

**Comment by dany20mh** [comment]
@p0psicles @medariox 
I install the develop branch and I'm not getting those error anymore, but I didn't check for empty folder.
