### ISSUE TITLE
[APP SUBMITTED]: TypeError: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by rssfed23** [pymedusa/Medusa#2986]
### INFO
**Python Version**: `2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]`
**Operating System**: `Linux-4.10.17-1-pve-x86_64-with-Ubuntu-17.04-zesty`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@49e9fc38856200768d41a74139807886acefa054
**Link to Log**: https://gist.github.com/6efb3185b4d9a53fa511b7b52f9dff30
### ERROR
<pre>
2017-08-07 20:56:53 ERROR    SHOWQUEUE-ADD :: [49e9fc3] Error searching dir for episodes: execv() arg 2 must contain only strings
Traceback (most recent call last):
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/show_queue.py#L562">medusa/show_queue.py</a>", line 562, in run
    self.show.load_episodes_from_dir()
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/tv/series.py#L919">medusa/tv/series.py</a>", line 919, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/tv/series.py#L1345">medusa/tv/series.py</a>", line 1345, in make_ep_from_file
    filepath)
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/tv/series.py#L1214">medusa/tv/series.py</a>", line 1214, in should_refresh_file
    new_quality = Quality.name_quality(filepath, anime)
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/common.py#L302">medusa/common.py</a>", line 302, in name_quality
    return Quality._extend_quality(name)
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/common.py#L401">medusa/common.py</a>", line 401, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/medusa/common.py#L422">medusa/common.py</a>", line 422, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/lib/knowit/api.py#L49">lib/knowit/api.py</a>", line 49, in know
    return provider.describe(video_path, context)
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/lib/knowit/providers/ffmpeg.py#L214">lib/knowit/providers/ffmpeg.py</a>", line 214, in describe
    data = self.executor.extract_info(video_path)
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/lib/knowit/providers/ffmpeg.py#L76">lib/knowit/providers/ffmpeg.py</a>", line 76, in extract_info
    json_dump = self._execute(filename)
  File "/var/lib/sickrage/<a href="../blob/49e9fc38856200768d41a74139807886acefa054/lib/knowit/providers/ffmpeg.py#L110">lib/knowit/providers/ffmpeg.py</a>", line 110, in _execute
    '-show_format', '-show_streams', '-sexagesimal', filename])
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment]
Are you able to confirm whether this is happening only with videos which has accent characters on their names?

Just for you to know, a workaround is to install mediainfo, which will be used instead of ffmpeg.

**Comment by rssfed23** [comment]
Yep only seems to happen on videos with accent.

FWIW I did install mediainfo from apt but this is still occasionally happening.

**Comment by rssfed23** [comment]
So this seems to have the same cause as https://github.com/pymedusa/Medusa/issues/2984

I'll close this one and put all details in 2984.
