### ISSUE TITLE
AnimeBytes Won't search 

### ISSUE THREAD

**Issue by gameguyalien** [pymedusa/Medusa#3003]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
Master
**OS:**
Linux
**What you did:**
set up animebytes with the correct credentials 
**What happened:**
Nothing, but some weird errors
**What you expected:**
For it to find the show
**Logs:**
```2017-08-12 04:05:26 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [49e9fc3] DailySearchQueueItem Exception, error: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/mnt/mpathy/gameguyalien/Medusa-master/medusa/search/queue.py", line 262, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/mnt/mpathy/gameguyalien/Medusa-master/medusa/search/core.py", line 444, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/mnt/mpathy/gameguyalien/Medusa-master/medusa/tv/cache.py", line 196, in update_cache
    data = self._get_rss_data()
  File "/mnt/mpathy/gameguyalien/Medusa-master/medusa/tv/cache.py", line 179, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)}
  File "/mnt/mpathy/gameguyalien/Medusa-master/medusa/providers/torrent/html/animebytes.py", line 113, in search
    results += self.parse(response.text, mode)
  File "/mnt/mpathy/gameguyalien/Medusa-master/medusa/providers/torrent/html/animebytes.py", line 133, in parse
    torrent_group = torrent_div('div', class_='group_cont box anime')
TypeError: 'NoneType' object is not callable
PASTE LOGS HERE
```

**Comment by p0psicles** [comment]
We don't have an account anymore, so we can't fix this by our self. What you could do try to do search for a show. And save the pages source. Then give us a visit on irc and share a gist. Then we can try fixing it from that.
