### ISSUE TITLE
Exception generated: level must be an integer Traceback (most recent call last)

### ISSUE THREAD

**Issue by neoatomic** [pymedusa/Medusa#3025]
After download finished, nzbget calls the nzbtomedia script and below traceback happens.

```
Medusa Info: 	Branch: develop
Commit: 69b471204467dd3434af0b5799984f3f3e6bbc60
Version: v0.1.14
Database: 44.8
Python Version:	2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]
SSL Version:	OpenSSL 1.0.2j 26 Sep 2016
OS:	Linux-3.10.102-x86_64-with-glibc2.2.5
Locale:	en_US.UTF-8
```

```
2017-08-17 03:20:59 DEBUG    SEARCHQUEUE-BACKLOG-326208 :: [69b4712] Transaction with 1 queries executed
2017-08-17 03:21:49 DEBUG    Thread-19 :: [69b4712] Broken providers already updated in the last hour
2017-08-17 03:25:17 INFO     TORNADO :: [69b4712] User logged into the Medusa web interface
2017-08-17 03:25:17 DEBUG    Thread-19 :: [69b4712] Processing path: /volume1/public/Temp/American.Ripper.S01E01.Devil.in.the.Details.720p.HIST.WEB-DL.AAC2.0.x264-RTN.#1921
2017-08-17 03:25:17 INFO     Thread-19 :: [69b4712] Failed download detected: (American.Ripper.S01E01.Devil.in.the.Details.720p.HIST.WEB-DL.AAC2.0.x264-RTN, /volume1/public/Temp/American.Ripper.S01E01.Devil.in.the.Details.720p.HIST.WEB-DL.AAC2.0.x264-RTN.#1921)
2017-08-17 03:25:17 INFO     Thread-19 :: [69b4712] Using nzb_name for release name.
2017-08-17 03:25:17 DEBUG    Thread-19 :: [69b4712] Matched release American.Ripper.S01E01.Devil.in.the.Details.720p.HIST.WEB-DL.AAC2.0 to a series in your database: American Ripper
2017-08-17 03:25:17 DEBUG    Thread-19 :: [69b4712] Parsed American.Ripper.S01E01.Devil.in.the.Details.720p.HIST.WEB-DL.AAC2.0 into title: American Ripper, season: 1, episode: [1], episode_title: Devil in the Details, screen_size: 720p, streaming_service: History, format: WEB-DL, audio_codec: AAC, audio_channels: 2.0, type: episode, parsing_time: 0.108777999878, total_time: 0.109412908554, absolute_episode: [], quality: 720p WEB-DL
2017-08-17 03:25:17 ERROR    Thread-19 :: [69b4712] Exception generated: level must be an integer
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/home/post_process.py", line 50, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/process_tv.py", line 142, in process
    if not self.should_process(path, failed):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/process_tv.py", line 234, in should_process
    self.process_failed(path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/process_tv.py", line 587, in process_failed
    self.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/failed_processor.py", line 51, in process
    self.log(u'Parsed info: {result}'.format(result=parsed), logger.DEBUG)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/failed_processor.py", line 72, in log
    log.log(level, message)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/logger/adapters/style.py", line 82, in log
    self.logger.log(level, brace_msg, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1489, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1227, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
```

EDIT: Unrelated, but might be usefull. :

![29405627-b2882bb2-833e-11e7-8382-a5aad085235e](https://user-images.githubusercontent.com/7928052/29411641-0404b322-8356-11e7-93f3-2cf0a1c65e41.jpg)
![medusa2](https://user-images.githubusercontent.com/7928052/29405625-b286af08-833e-11e7-9a47-99a965dea9da.jpg)
![medusa3](https://user-images.githubusercontent.com/7928052/29405626-b286fd14-833e-11e7-9c41-c18577622eec.jpg)

**Comment by duramato** [comment]
https://github.com/pymedusa/Medusa/issues/2779#issuecomment-323085419

nzbtomedia log

```
[14:52:51] [INFO]::MAIN: Loading config from [/home/pi/nzbToMedia/autoProcessMedia.cfg]
[14:52:51] [INFO]::MAIN: Checking database structure...
[14:52:51] [DEBUG]::MAIN: Checking Initial Schema database upgrade
[14:52:51] [DEBUG]::MAIN: InitialSchema upgrade not required
[14:52:51] [DEBUG]::MAIN: Checking if we can use git commands: git version
[14:52:51] [DEBUG]::MAIN: Executing git version with your shell in /home/pi/nzbToMedia
[14:52:51] [DEBUG]::MAIN: git version : returned successful
[14:52:51] [DEBUG]::MAIN: Using: git
[14:52:51] [DEBUG]::MAIN: Executing git symbolic-ref -q HEAD with your shell in /home/pi/nzbToMedia
[14:52:51] [DEBUG]::MAIN: git symbolic-ref -q HEAD : returned successful
[14:52:51] [INFO]::MAIN: Checking if git needs an update
[14:52:51] [DEBUG]::MAIN: Executing git rev-parse HEAD with your shell in /home/pi/nzbToMedia
[14:52:51] [DEBUG]::MAIN: git rev-parse HEAD : returned successful
[14:52:51] [DEBUG]::MAIN: Executing git fetch origin with your shell in /home/pi/nzbToMedia
[14:52:52] [DEBUG]::MAIN: git fetch origin : returned successful
[14:52:52] [DEBUG]::MAIN: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /home/pi/nzbToMedia
[14:52:52] [DEBUG]::MAIN: git rev-parse --verify --quiet "@{upstream}" : returned successful
[14:52:52] [DEBUG]::MAIN: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /home/pi/nzbToMedia
[14:52:52] [DEBUG]::MAIN: git rev-list --left-right "@{upstream}"...HEAD : returned successful
[14:52:52] [DEBUG]::MAIN: cur_commit = 2779cb69616fc43bb3fc8adaca4685f9e8138708 % (newest_commit)= 2779cb69616fc43bb3fc8adaca4685f9e8138708, num_commits_behind = 0, num_commits_ahead = 0
[14:52:52] [INFO]::MAIN: No update needed
[14:52:52] [INFO]::MAIN: nzbToMedia Version:2779cb69616fc43bb3fc8adaca4685f9e8138708 Branch:nightly (Linux 4.9.35-v7+)
[14:52:53] [DEBUG]::MAIN: Connecting to transmission: http://localhost:9091
[14:52:53] [INFO]::MAIN: #########################################################
[14:52:53] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[14:52:53] [INFO]::MAIN: #########################################################
[14:52:53] [DEBUG]::MAIN: Options passed into nzbToMedia: ['/home/pi/nzbToMedia/nzbToMedia.py', '/media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb', 'Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb.nzb', 'Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb', '', 'tve', 'alt.binaries.inner-sanctum', '0', 'https://dognzb.cr/fail/62dc05c3e3e5a3d45f3ec87557278599/fa27cd97c07b4bf0b38fdca0bb6c249a']
[14:52:53] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[14:52:53] [DEBUG]::MAIN: Searching for nzoid from SAbnzbd ...
[14:52:53] [DEBUG]::MAIN: Found nzoid: SABnzbd_nzo_Cta7Vb
[14:52:53] [DEBUG]::MAIN: Adding NZB download info for directory /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb to database
[14:52:53] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[14:52:53] [DEBUG]::MAIN: Checking for archives to extract in directory: /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb
[14:52:53] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .11
[14:52:53] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .21
[14:52:54] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .31
[14:52:54] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .41
[14:52:54] [INFO]::MAIN: Calling SickBeard:tve to post-process:Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb.nzb
[14:52:54] [DEBUG]::SERVER: Attempting to connect to server at http://localhost:8081
[14:52:54] [DEBUG]::SERVER: Server responded at http://localhost:8081
[14:52:54] [INFO]::MAIN: SickBeard:tve fork set to medusa
[14:52:54] [DEBUG]::EXCEPTION: Replacing file name 5fe7c8ad0d07a9cf18f64512cbfe7811 with directory name Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb
[14:52:54] [DEBUG]::EXCEPTION: Replacing file name /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb/5fe7c8ad0d07a9cf18f64512cbfe7811.11 with download name /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb.11
[14:52:54] [DEBUG]::EXCEPTION: Replacing file name 5fe7c8ad0d07a9cf18f64512cbfe7811 with directory name Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb
[14:52:54] [DEBUG]::EXCEPTION: Replacing file name /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb/5fe7c8ad0d07a9cf18f64512cbfe7811.21 with download name /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb.21
[14:52:54] [DEBUG]::EXCEPTION: Replacing file name 5fe7c8ad0d07a9cf18f64512cbfe7811 with directory name Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb
[14:52:54] [DEBUG]::EXCEPTION: Replacing file name /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb/5fe7c8ad0d07a9cf18f64512cbfe7811.31 with download name /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb.31
[14:52:54] [DEBUG]::EXCEPTION: Replacing file name 5fe7c8ad0d07a9cf18f64512cbfe7811 with directory name Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb
[14:52:54] [DEBUG]::EXCEPTION: Replacing file name /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb/5fe7c8ad0d07a9cf18f64512cbfe7811.41 with download name /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb.41
[14:52:54] [DEBUG]::MAIN: Checking for archives to extract in directory: /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb
[14:52:54] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .11
[14:52:54] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .21
[14:52:54] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .31
[14:52:54] [DEBUG]::MAIN: EXTRACTOR: Unknown file type: .41
[14:52:54] [WARNING]::SICKBEARD: No media files found in directory /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb. Processing this as a failed download
[14:52:54] [INFO]::MAIN: Sending failure notification to indexer site
[14:52:55] [POSTPROCESS]::SICKBEARD: FAILED: The download failed. Sending 'failed' process request to medusa branch
[14:52:55] [DEBUG]::SICKBEARD: Opening URL: http://localhost:8081/home/postprocess/processEpisode with params: {'nzbName': 'Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb.nzb', 'quiet': 1, 'failed': 1, 'process_method': 'move', 'proc_dir': '/media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb', 'delete_on': 1}
[14:53:00] [POSTPROCESS]::SICKBEARD: Deleting failed files and folder /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb
[14:53:00] [INFO]::MAIN: Deleting /media/ssd/Download/Mr.Mercedes.S01E02.On.Your.Mark.720p.DTV.WEB-DL.DD2.0.x264-NTb
[14:53:00] [ERROR]::MAIN: A problem was reported in the /home/pi/nzbToMedia/nzbToMedia.py script.
SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!
```

**Comment by p0psicles** [comment]
Already fixed in dev.
