### ISSUE TITLE
Error Date Yggtorrent

### ISSUE THREAD

**Issue by IDerr** [pymedusa/Medusa#3033]
2017-08-19 23:35:31 ERROR    SEARCHQUEUE-BACKLOG-326490 :: [Yggtorrent] :: [56f4337] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/medusa/providers/torrent/html/yggtorrent.py", line 138, in parse
    pubdate = self.parse_pubdate(pubdate_raw, human_time=True)
  File "/opt/medusa/medusa/providers/generic_provider.py", line 536, in parse_pubdate
    return datetime.now(tz.tzlocal()) - timedelta(seconds=seconds)
TypeError: unsupported type for timedelta seconds component: NoneType

**Comment by p0psicles** [comment]
Tnx @IDerr will try to look at this today!

**Comment by p0psicles** [comment]
As this is a backlog search, it would help me if I know what you where looking for. Then I can reproduce the error.

**Comment by p0psicles** [comment]
Never mind, found it. I didn't translate `heures`.

**Comment by p0psicles** [comment]
fixed

**Comment by IDerr** [comment]
2017-10-23 02:33:35 ERROR    SEARCHQUEUE-BACKLOG-81797 :: [Yggtorrent] :: [75951e6] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/medusa/providers/torrent/html/yggtorrent.py", line 139, in parse
    pubdate = self.parse_pubdate(pubdate_raw, human_time=True)
  File "/opt/medusa/medusa/providers/generic_provider.py", line 564, in parse_pubdate
    return datetime.now(tz.tzlocal()) - timedelta(seconds=seconds)
TypeError: unsupported type for timedelta seconds component: NoneType

**Comment by IDerr** [comment]
Still the same on last develop

**Comment by OmgImAlexis** [comment]
@IDerr still an issue?

**Comment by IDerr** [comment]
Since the refactor of Ygg, the error has gone away.

I'll close this  :)
