### ISSUE TITLE
OpenSubs backend failed 503

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#3121]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: master
**OS: Synology
**What you did: searching for subs 
**What happened: ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Backend fetch failed>
**What you expected:  finding these subs: https://www.opensubtitles.org/nl/search/sublanguageid-dut/imdbid-5939140
**Logs:**
```
2017-09-18 20:43:05 INFO     Thread-17 :: [3f23fd2] 269533: No subtitles found for The Last Ship S04E05
2017-09-18 20:43:05 DEBUG    Thread-17 :: [3f23fd2] 269533: Saving last subtitles search to database
2017-09-18 20:43:05 INFO     Thread-17 :: [3f23fd2] No subtitles found for The.Last.Ship.S04E05.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.mkv
2017-09-18 20:43:05 DEBUG    Thread-17 :: [3f23fd2] Could not search in addic7ed provider. Discarding for now
2017-09-18 20:43:05 DEBUG    Thread-17 :: [3f23fd2] Could not search in opensubtitles provider. Discarding for now
2017-09-18 20:43:05 DEBUG    Thread-17 :: [3f23fd2] Discarding provider addic7ed
2017-09-18 20:43:05 WARNING  Thread-17 :: [3f23fd2] Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/providers/addic7ed.py", line 238, in query
    raise TooManyRequests()
TooManyRequests
2017-09-18 20:43:05 DEBUG    Thread-17 :: [3f23fd2] Initializing provider addic7ed
2017-09-18 20:43:05 DEBUG    Thread-17 :: [3f23fd2] Listing subtitles with provider u'addic7ed' and languages set([<Language [nl]>])
2017-09-18 20:43:05 DEBUG    Thread-17 :: [3f23fd2] Discarding provider opensubtitles
2017-09-18 20:43:04 WARNING  Thread-17 :: [3f23fd2] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/providers/opensubtitles.py", line 220, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/subliminal/providers/opensubtitles.py", line 175, in query
    response = checked(self.server.SearchSubtitles(self.token, criteria))
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/python/lib/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 503 Backend fetch failed>
2017-09-18 20:43:04 DEBUG    Thread-17 :: [3f23fd2] Searching subtitles [{'moviebytesize': '2922245755', 'sublanguageid': u'dut', 'moviehash': '006ac1342ab1be51'}, {'sublanguageid': u'dut', 'tag': u'The.Last.Ship.S04E05.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.mkv'}, {'query': 'The Last Ship', 'sublanguageid': u'dut', 'episode': 5, 'season': 4}]
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Logging in
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Initializing provider opensubtitles
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Listing subtitles with provider u'opensubtitles' and languages set([<Language [nl]>])
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Creating a new ProviderPool instance
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Video information cached under key medusa.subtitles:video|/volume1/A_SERIES/The Last Ship/The.Last.Ship.S04E05.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.mkv
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Refining video with omdb
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Refining video with tvdb
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Attribute tvdb_id changed from None to 5904919
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Attribute title changed from None to Allegiance
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Refining using Episode information.
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Attribute year changed from None to 2014
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Attribute series_imdb_id changed from None to tt2402207
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Attribute series_tvdb_id changed from None to 269533
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Refining using Series information.
2017-09-18 20:42:58 DEBUG    Thread-17 :: [3f23fd2] Refining video with tvepisode
2017-09-18 20:42:57 DEBUG    Thread-17 :: [3f23fd2] Guessing using /volume1/A_SERIES/The Last Ship/The.Last.Ship.S04E05.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.mkv
2017-09-18 20:42:57 DEBUG    Thread-17 :: [3f23fd2] Starting release refiner [extension=release, release_name=The.Last.Ship.S04E05.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ, release_file=None]
2017-09-18 20:42:57 DEBUG    Thread-17 :: [3f23fd2] Refining video with release
2017-09-18 20:42:57 DEBUG    Thread-17 :: [3f23fd2] Refining video with metadata
2017-09-18 20:42:55 DEBUG    Thread-17 :: [3f23fd2] Scanning video u'The.Last.Ship.S04E05.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.mkv' in u'/volume1/A_SERIES/The Last Ship'
2017-09-18 20:42:55 DEBUG    Thread-17 :: [3f23fd2] Scanning video /volume1/A_SERIES/The Last Ship/The.Last.Ship.S04E05.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.mkv...
2017-09-18 20:42:55 DEBUG    Thread-17 :: [3f23fd2] Checking subtitle candidates for The Last Ship S04E05 (The.Last.Ship.S04E05.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.mkv)
```

**Comment by ward0** [comment]
problem resolved itself.
