### ISSUE TITLE
Error when sending to uTorrent

### ISSUE THREAD

**Issue by Olivier6767** [pymedusa/Medusa#3162]
Error when sending torrent to uTorrent

Branch: master
Commit: 3f23fd272652b10cf781e3058fee50daf79f11b6
Version: v0.1.15
Database: 44.8
Python Version: | 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
SSL Version: | OpenSSL 1.0.1t 3 May 2016
OS: | Linux-3.16.0-4-amd64-x86_64-with-debian-8.9
Locale: | fr_FR.UTF-8

2017-10-17 08:32:00 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [3f23fd2] uTorrent: Unknown exception raised when send torrent to uTorrent : 'utf8' codec can't decode byte 0xfd in position 2181: invalid start byte
Traceback (most recent call last):
  File "/home/Services/cinema/medusa/Medusa/medusa/clients/torrent/generic.py", line 79, in _request
    cookies=cookies, timeout=120, verify=False)
  File "/home/Services/cinema/medusa/Medusa/lib/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/Services/cinema/medusa/Medusa/lib/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/Services/cinema/medusa/Medusa/lib/requests/sessions.py", line 591, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/Services/cinema/medusa/Medusa/lib/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/Services/cinema/medusa/Medusa/medusa/session/hooks.py", line 28, in log_url
    log.debug('With post data: {data}'.format(data=resp.request.body))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfd in position 2181: invalid start byte

**Comment by medariox** [comment]
This should be already fixed in develop with https://github.com/pymedusa/Medusa/pull/3100/files

**Comment by Olivier6767** [comment]
Thanks, I swithed to the develop branch.
