### ISSUE TITLE
Subs provider podnapisi error

### ISSUE THREAD

**Issue by zaggash** [pymedusa/Medusa#3175]
**Branch/Commit:**
```
Branch: master
Commit: 3f23fd272652b10cf781e3058fee50daf79f11b6
Version: v0.1.15
Database: 44.8
--
Python Version: | 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
SSL Version: | LibreSSL 2.5.5
OS: | Linux-3.16.0-4-amd64-x86_64-with
Locale: | Unknown.Unknown
```

**OS:**
`Using the linuxserver.io docker image.`

**What you did:**
`Activate the provider, start a manual sub search on an episode`
**What happened:**
`Error while parsing the website I guess`

**What you expected:**
Subs search on this provider

**Logs:**
```
2017-10-25 11:41:49 WARNING  Thread-21 :: [3f23fd2] Unexpected error in provider u'podnapisi'
Traceback (most recent call last):
  File "/app/medusa/lib/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/app/medusa/lib/subliminal/providers/podnapisi.py", line 164, in list_subtitles
    episode=video.episode, year=video.year)]
  File "/app/medusa/lib/subliminal/providers/podnapisi.py", line 111, in query
    xml = etree.fromstring(self.session.get(self.server_url + 'search/old', params=params, timeout=10).content)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79010)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
XMLSyntaxError: Opening and ending tag mismatch: hr line 5 and body, line 6, column 8 (line 6)
```

**Comment by zaggash** [comment]
This happens to any shows

**Comment by p0psicles** [comment]
I think you have a better chance of getting this fixed, when reporting with subliminal.
