### ISSUE TITLE
Unable to start medusa

### ISSUE THREAD

**Issue by XenoBIT78** [pymedusa/Medusa#3184]
this morning medusa is closed down and i cant restart it..  i get this in my log:
```
-- Subject: Unit medusa.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit medusa.service has begun starting up.
Oct 26 08:41:40 server python2.7[5035]: Traceback (most recent call last):
Oct 26 08:41:40 server python2.7[5035]:   File "/opt/medusa/start.py", line 4, in <module>
Oct 26 08:41:40 server python2.7[5035]:     from medusa.__main__ import main
Oct 26 08:41:40 server python2.7[5035]:   File "/opt/medusa/medusa/__main__.py", line 67, in <module>
Oct 26 08:41:40 server python2.7[5035]:     from . import (
Oct 26 08:41:40 server python2.7[5035]:   File "/opt/medusa/medusa/naming.py", line 22, in <module>
Oct 26 08:41:40 server python2.7[5035]:     from . import app, common, logger, tv
Oct 26 08:41:40 server python2.7[5035]:   File "/opt/medusa/medusa/tv/__init__.py", line 5, in <module>
Oct 26 08:41:40 server python2.7[5035]:     from medusa.tv.episode import Episode
Oct 26 08:41:40 server python2.7[5035]:   File "/opt/medusa/medusa/tv/episode.py", line 18, in <module>
Oct 26 08:41:40 server python2.7[5035]:     from medusa import (
Oct 26 08:41:40 server python2.7[5035]:   File "/opt/medusa/medusa/notifiers/__init__.py", line 8, in <module>
Oct 26 08:41:40 server python2.7[5035]:     from medusa.notifiers import (
Oct 26 08:41:40 server python2.7[5035]:   File "/opt/medusa/medusa/notifiers/plex.py", line 8, in <module>
Oct 26 08:41:40 server python2.7[5035]:     from medusa.helper.utils import generate
Oct 26 08:41:40 server python2.7[5035]:   File "/opt/medusa/medusa/helper/utils.py", line 5, in <module>
Oct 26 08:41:40 server python2.7[5035]:     from collections import Iterable
Oct 26 08:41:40 server python2.7[5035]: ImportError: cannot import name Iterable
Oct 26 08:41:40 server systemd[1]: medusa.service: Control process exited, code=exited status=1
Oct 26 08:41:40 server systemd[1]: Failed to start Medusa Daemon.
-- Subject: Unit medusa.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit medusa.service has failed.
```

Any thougths ??

**Comment by labrys** [comment]
check the folder `/opt/medusa/medusa/helper` and see if there is a file called `collections.py` in that folder.  If so, delete it and relaunch medusa.

**Comment by XenoBIT78** [comment]
it was named collections.pyc
and it helped deleting it :)

Thanks alot for the quick reply!!  :) :D

**Comment by labrys** [comment]
No problem
