### ISSUE TITLE
Yggtorrent automatic schedule search error.

### ISSUE THREAD

**Issue by zaggash** [pymedusa/Medusa#3208]
**Branch/Commit:**
```
branch: master
Commit: b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
Version: v0.1.17
Database: 44.8
--
Python Version: | 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
SSL Version: | LibreSSL 2.5.5
OS: | Linux-3.16.0-4-amd64-x86_64-with
Locale: | Unknown.Unknown
```
**OS:**
`Using the linuxserver.io docker image.`
**What you did:**
`Nothing, automatic schedule search`
**What happened:**
`Error while parsing the website I guess`

**Logs:**
```
2017-10-30 14:35:42 ERROR    FINDPROPERS :: [Yggtorrent] :: [b16e0e5] Failed parsing provider.
Traceback (most recent call last):
  File "/app/medusa/medusa/providers/torrent/html/yggtorrent.py", line 139, in parse
    pubdate = self.parse_pubdate(pubdate_raw, human_time=True)
  File "/app/medusa/medusa/providers/generic_provider.py", line 564, in parse_pubdate
    return datetime.now(tz.tzlocal()) - timedelta(seconds=seconds)
TypeError: unsupported type for timedelta seconds component: NoneType
```

**Comment by adaur** [comment]
Weird, I have ygg enabled and never encountered this error

**Comment by naonilio** [comment]
Hello.

I have mostly the same issue :
2017-11-19 12:37:52 ERROR    SEARCHQUEUE-FORCED-1418 :: [Yggtorrent] :: [b16e0e5] Failed parsing provider.
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/providers/torrent/html/yggtorrent.py", line 125, in parse
    download_url = urljoin(self.url, cells[0].find('a', target='_blank')['href'])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by medariox** [comment]
@naonilio 
That issue was already fixed [here](https://github.com/pymedusa/Medusa/pull/3281) and will be available in the next release.

**Comment by naonilio** [comment]
Thank you for your fedd back and your work. So I just have to wait now. 
Have  a nice day.
