### ISSUE TITLE
PostProcessing Error With _unpack And NZBGet

### ISSUE THREAD

**Issue by play3rZA** [pymedusa/Medusa#3219]
Good afternoon,

I have moved over to Medusa and also back to NZBGet and picked up an issue when the post processor starts whilst NZBGet is busy unpacking a download.  (See logs below)

I found [this commit](https://github.com/SickRage/SickRage/commit/30e3902cdb0f56b6e4deef92a1e7b6a40fffea86) from SickRage (hope it's OK to reference it here) which adds a _or folder_name.upper().endswith(u'_UNPACK'):_  in processTV.py (I'm assuming process_tv.py in Medusa line 227)

- If I look at my logs it looks like created a subfolder called _unpack which should then be picked up with the code as is or is it because it is a subfolder inside a subfolder of the folder being postprocessed?

**Branch/Commit:** Master
**OS:** Raspberry Pi 3 OSMC 2017.10-1
**What you did:** PostProcessing started whilst NZBGet is unpacking
**What happened:** Errors in the logs
**What you expected:** "Being Unpacked" warning
**Logs:** (Copied from /errorlogs/viewlog/, so read from bottom to top. Did not have debug logs enabled. I can try and reproduce if needed?)
```
2017-11-02 14:52:53 WARNING  POSTPROCESSOR :: [b16e0e5] /mnt/External/Downloads/completed/Series/Mr.Robot.S03e04.720p.Hdtv.Hevc.X265.Rmteam/_unpack/mr.robot.s03e04.720p.hdtv.hevc.x265.rmteam.mkv: Processing failed: Unable to move the files to their new home
2017-11-02 14:52:53 WARNING  POSTPROCESSOR :: [b16e0e5] Problem(s) during processing, failed for the following files/folders: 
2017-11-02 14:52:53 WARNING  POSTPROCESSOR :: [b16e0e5] Processing failed for /mnt/External/Downloads/completed/Series/Mr.Robot.S03e04.720p.Hdtv.Hevc.X265.Rmteam/_unpack/mr.robot.s03e04.720p.hdtv.hevc.x265.rmteam.mkv: Unable to move the files to their new home
2017-11-02 14:52:53 ERROR    POSTPROCESSOR :: [b16e0e5] Unable to move file /mnt/External/Downloads/completed/Series/Mr.Robot.S03e04.720p.Hdtv.Hevc.X265.Rmteam/_unpack/mr.robot.s03e04.720p.hdtv.hevc.x265.rmteam.mkv to /mnt/External/Series/Mr. Robot/Season 3/Mr. Robot - S03E04 - eps3.3_m3tadata.par2.mkv: OSError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/opt/medusa/medusa/post_processor.py", line 449, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/opt/medusa/medusa/helpers/__init__.py", line 316, in move_file
    os.unlink(src_file)
  File "/opt/medusa/medusa/init/filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
OSError: [Errno 2] No such file or directory: '/mnt/External/Downloads/completed/Series/Mr.Robot.S03e04.720p.Hdtv.Hevc.X265.Rmteam/_unpack/mr.robot.s03e04.720p.hdtv.hevc.x265.rmteam.mkv'
2017-11-02 14:50:05 INFO     POSTPROCESSOR :: [b16e0e5] This download is marked a priority download so I'm going to replace an existing file if I find one
2017-11-02 14:50:05 INFO     POSTPROCESSOR :: [b16e0e5] New size: 52.00 MB
2017-11-02 14:50:05 INFO     POSTPROCESSOR :: [b16e0e5] New file: /mnt/External/Downloads/completed/Series/Mr.Robot.S03e04.720p.Hdtv.Hevc.X265.Rmteam/_unpack/mr.robot.s03e04.720p.hdtv.hevc.x265.rmteam.mkv
2017-11-02 14:50:05 INFO     POSTPROCESSOR :: [b16e0e5] Processing /mnt/External/Downloads/completed/Series/Mr.Robot.S03e04.720p.Hdtv.Hevc.X265.Rmteam/_unpack/mr.robot.s03e04.720p.hdtv.hevc.x265.rmteam.mkv
```

**Comment by medariox** [comment]
Thank you for the bug report!

A lot of stuff changed from the SR times, so the fix wasn't as easy as adding a simple `or`.
Your assumption was right indeed, the necessary checks weren't taking place for 2nd level subfolders. It will be fixed with: https://github.com/pymedusa/Medusa/pull/3221

**Comment by play3rZA** [comment]
That was quick! Thank you very much!

**Comment by medariox** [comment]
Merged to develop. Will be available with the next release.
