### ISSUE TITLE
DailySearchQueueItem Exception, error: timed out - crashing daily search

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#3226]
```
2017-10-31 23:59:28 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [b5a5d3c] DailySearchQueueItem Exception, error: timed out
Traceback (most recent call last):
  File "/home/osmc/Medusa/medusa/search/queue.py", line 288, in run
    self.success = snatch_episode(result)
  File "/home/osmc/Medusa/medusa/search/core.py", line 214, in snatch_episode
    result.leechers, result.provider.name), is_proper)
  File "/home/osmc/Medusa/medusa/notifiers/__init__.py", line 109, in notify_snatch
    n.notify_snatch(ep_name, is_proper)
  File "/home/osmc/Medusa/medusa/notifiers/nma.py", line 22, in notify_snatch
    message=ep_name)
  File "/home/osmc/Medusa/medusa/notifiers/nma.py", line 72, in _sendNMA
    response = p.push(application=title, event=event, description=message, priority=nma_priority, batch_mode=batch)
  File "/home/osmc/Medusa/ext/pynma/pynma.py", line 106, in push
    res = self.callapi('POST', ADD_PATH, datas)
  File "/home/osmc/Medusa/ext/pynma/pynma.py", line 119, in callapi
    http_handler.request(method, path, urlencode(args), headers)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 841, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1242, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
timeout: timed out
```

@p0psicles daily search crashed. had to restart

**Comment by fernandog** [comment]
also as the notifier failed, it did't updated the DB and it snatched again the same torrent
afaik it does like this: Send to Client > Notifier > update DB.

**Comment by p0psicles** [comment]
Is that reproducible?

**Comment by fernandog** [comment]
Maybel block the notifier URL in the "hosts" ? Dont know If It will raise that exception

**Comment by p0psicles** [comment]
Does it throw the exception on each snatch?

**Comment by fernandog** [comment]
No. It a timed out exception. Sockets time out right? Its a external lib. Maybel catch requests exception in medusa?

**Comment by p0psicles** [comment]
Just wanted to be sure it does not have anything to do with config migration.

**Comment by fernandog** [comment]
Pretty sure is not related

**Comment by fernandog** [comment]
I think this can be fixed in /Medusa/medusa/notifiers/nma.py

**Comment by labrys** [comment]
iirc `socket.timeout` is not caught by `requests.RequestException`

**Comment by labrys** [comment]
More specifically, I believe `requests` catches `socket.timeout` internally, but the `requests.RequestException` will not catch it since `requests` handles it internally.  I believe `nma` does not use `requests` though so we have to catch the `socket.timeout` explicitly.
