### ISSUE TITLE
[APP SUBMITTED]: ImportError: No module named gdbm

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#3247]
### INFO
**Python Version**: `2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]`
**Operating System**: `Linux-4.9.0-4-amd64-x86_64-with-debian-9.2`
**Locale**: `UTF-8`
**Branch**: [feature/fix-saving-nn-cats](../tree/feature/fix-saving-nn-cats)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@e3363605d0119d2f3411746bcc3ad46948aae15f
**Link to Log**: https://gist.github.com/d35af7a3c9c8a581e85ef8bf8eae323c
### ERROR
<pre>
2017-11-08 22:11:48 ERROR    Thread-87 :: [e336360] Exception generated: No module named gdbm
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/handler.py", line 2248, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/opt/medusa/medusa/subtitles.py", line 333, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/opt/medusa/ext/dogpile/cache/region.py", line 984, in set
    self.backend.set(key, self._value(value))
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
ImportError: No module named gdbm
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Installed python-gdbm and now getting this error:
```
File "/usr/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
error: (22, 'Invalid argument')
```

**Comment by p0psicles** [comment]
It's happening when it tries to open the lists with subtitles for an episode, when using the manual subtitle search feature. Think it's related to the dogpile cache.

**Comment by fernandog** [comment]
Weird I don't have this error

**Comment by p0psicles** [comment]
i've installed package gdbm through apt-get install python-gdbm. That resolved the first error. But still strange I need to install a module for that. Now i'm looking into why i'm getting the second error. Maybe corrupt gdm file? Is the subliminal.gdm used for the subtitles?

**Comment by fernandog** [comment]
Erase all .dbm files inside cache folder

**Comment by p0psicles** [comment]
I did, same error.

**Comment by p0psicles** [comment]
Yes, it's working now. Still strange i needed to install python-gdbm though. But okay.

**Comment by fernandog** [comment]
Try uninstall. Maybe dogpile depends on it for a newer/a wrong release
