### ISSUE TITLE
File postprocessed then immediately deleted

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3256]
So all of my system is working great. Except one episode of one show. It keeps downloading then properly post processing then deleting. No other eps do this nor other shows.

```
2017-11-10 18:27:52 WARNING  Thread-17 :: [b16e0e5] Unable to get size for file /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL.mkv Error: OSError(2, 'No such file or directory')
2017-11-10 18:27:28 INFO     Thread-19 :: [b16e0e5] Successfully processed.
2017-11-10 18:27:28 INFO     Thread-19 :: [b16e0e5] Processing succeeded for /Media/Videos/tv/South.Park.S21E03.holiday.special.repack.uncensored.720p.web.h264/south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv
2017-11-10 18:27:28 WARNING  Thread-19 :: [b16e0e5] Unable to get info to move torrent later as no info hash available for: /Media/Videos/tv/South.Park.S21E03.holiday.special.repack.uncensored.720p.web.h264/south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 8a0fc957-c38d-11e7-95da-0242ac110004)
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] GET URL: http://192.168.1.2:32400/library/sections/1/refresh [Status: 200]
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] PLEX: Updating hosts where TV section paths match the downloaded show: 1
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] User-Agent: Medusa/0.0.1 (Linux; 4.9.49-moby; 8a0fc957-c38d-11e7-95da-0242ac110004)
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] GET URL: http://192.168.1.2:32400/library/sections [Status: 200]
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] Notification for NMJ scan update not enabled, skipping this notification
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] 75897: Formatting pattern: %SN - %Sx%0E - %EN - %QN -> South Park - 21x03 - Holiday Special - 720p WEB-DL
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] Found codec for South Park Holiday Special
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] Using cached parse result for south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] Parsed /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL into title: South Park, season: 21, episode: [3], episode_title: Holiday Special, episode_details: Special, screen_size: 720p, format: WEB-DL, type: episode, parsing_time: 0.0606949329376, total_time: 0.0607500076294, absolute_episode: [], quality: 720p WEB-DL
2017-11-10 18:27:28 DEBUG    Thread-19 :: [b16e0e5] Matched release /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL to a series in your database: South Park
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Unable to find a file path to use for this thumbnail, not generating it
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Metadata provider KODI 12+ creating episode thumbnail for South Park - S21E03 - Holiday Special
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] 75897: Formatting pattern: %SN - S%0SE%0E - %EN -> South Park - S21E03 - Holiday Special
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Found codec for South Park Holiday Special
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Using cached parse result for south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Parsed /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL into title: South Park, season: 21, episode: [3], episode_title: Holiday Special, episode_details: Special, screen_size: 720p, format: WEB-DL, type: episode, parsing_time: 0.0587439537048, total_time: 0.0588030815125, absolute_episode: [], quality: 720p WEB-DL
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Matched release /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL to a series in your database: South Park
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Setting permissions for /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL.nfo to 438 as parent directory has 511
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Writing episode nfo file to /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL.nfo
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Creating metadata for episode S21E03
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Metadata provider KODI 12+ creating episode metadata for South Park - S21E03 - Holiday Special
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] 75897: Formatting pattern: %SN - S%0SE%0E - %EN -> South Park - S21E03 - Holiday Special
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Found codec for South Park Holiday Special
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Using cached parse result for south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Parsed /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL into title: South Park, season: 21, episode: [3], episode_title: Holiday Special, episode_details: Special, screen_size: 720p, format: WEB-DL, type: episode, parsing_time: 0.0636367797852, total_time: 0.0637030601501, absolute_episode: [], quality: 720p WEB-DL
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Matched release /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL to a series in your database: South Park
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Checking if /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL.nfo exists: False
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Transaction with 1 queries executed
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] 75897: Setter sets location to /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL.mkv
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Transaction with 1 queries executed
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Moving then symbolic linking file from /Media/Videos/tv/South.Park.S21E03.holiday.special.repack.uncensored.720p.web.h264/south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv to /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL.mkv
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Checking if the path /mnt/Resources/TV/South Park/Season.21 already exists
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Destination folder for this episode: /mnt/Resources/TV/South Park/Season.21
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] 75897: Formatting pattern: Season.%0S -> Season.21
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Found codec for South Park Holiday Special
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Using cached parse result for south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] 75897: Formatting pattern: %S.N.S%0SE%0E.%EN.%QN -> South.Park.S21E03.Holiday Special.720p WEB-DL
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Found codec for South Park Holiday Special
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Using cached parse result for south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn
2017-11-10 18:27:27 INFO     Thread-19 :: [b16e0e5] Using nzb_name for release name.
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Found release name south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Trying to determine free space on destination drive
2017-11-10 18:27:27 INFO     Thread-19 :: [b16e0e5] This download is marked a priority download so I'm going to replace an existing file if I find one
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] There is no existing file so there's no worries about replacing it
2017-11-10 18:27:27 INFO     Thread-19 :: [b16e0e5] New size: 184.48 MB
2017-11-10 18:27:27 INFO     Thread-19 :: [b16e0e5] New file: /Media/Videos/tv/South.Park.S21E03.holiday.special.repack.uncensored.720p.web.h264/south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] This episode is a priority download: True
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Proper: True
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] New quality: 720p WEB-DL
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Current quality: 720p WEB-DL
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Manually snatched: False
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Snatch in history: True
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Quality of the episode we are processing: 720p WEB-DL
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] This episode was found in history as SNATCHED.
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] The episode file has a quality in it, using that: 720p WEB-DL
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Retrieving episode object for South Park S21E03
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Show information parsed from file name
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Parsed south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv into title: south park, season: 21, episode: [3], episode_title: holiday special, episode_details: Special, other: Proper, proper_count: 1, proper_tag: REPACK, edition: Uncensored, screen_size: 720p, format: WEB-DL, video_codec: h264, release_group: kiddieporn, container: mkv, type: episode, parsing_time: 0.0374188423157, total_time: 0.0376989841461, absolute_episode: [], quality: 720p WEB-DL
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Matched release south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv to a series in your database: South Park
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Analyzing name: south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv
2017-11-10 18:27:27 INFO     Thread-19 :: [b16e0e5] Processing /Media/Videos/tv/South.Park.S21E03.holiday.special.repack.uncensored.720p.web.h264/south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Post-processing video files: [u'south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv']
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Post-processing files: [u'south.park.s21e03.holiday.special.repack.uncensored.720p.web.h264-kiddieporn.mkv']
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Processing folder: /Media/Videos/tv/South.Park.S21E03.holiday.special.repack.uncensored.720p.web.h264
2017-11-10 18:27:27 DEBUG    Thread-19 :: [b16e0e5] Processing path: /Media/Videos/tv/South.Park.S21E03.holiday.special.repack.uncensored.720p.web.h264
```

**Comment by bobbysteel** [comment]
This also creates an error afterwards
```
2017-11-11 07:12:13 ERROR    SHOWQUEUE-REFRESH :: [b16e0e5] 75897: Error while refreshing show South Park. Error: 
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 629, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1829, in refresh_dir
    cur_loc, subfolders=True)
  File "/app/medusa/medusa/post_processor.py", line 190, in list_associated_files
    processed_names += filter(None, (self._rar_basename(file_path, files),))
  File "/app/medusa/medusa/post_processor.py", line 300, in _rar_basename
    for rar in rars:
  File "/app/medusa/medusa/post_processor.py", line 298, in <genexpr>
    rars = (x for x in files if rarfile.is_rarfile(x))
  File "/app/medusa/ext/rarfile.py", line 404, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "/app/medusa/ext/rarfile.py", line 389, in _get_rar_version
    with XFile(xfile) as fd:
  File "/app/medusa/ext/rarfile.py", line 2401, in __init__
    self._fd = open(xfile, 'rb', bufsize)
IOError: [Errno 2] No such file or directory: u'/mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL.mkv'
```

**Comment by medariox** [comment]
Is it also deleting the file if you try `copy` or `move`?

**Comment by bobbysteel** [comment]
I've not yet tried that. Will try later today.

**Comment by bobbysteel** [comment]
Trying to re-download it, it says already processed, so it's being marked as completed somewhere (show status is just snatched).
Using copy and force, result is the same. File deleted.
```
2017-11-11 13:43:42 WARNING  Thread-16 :: [b16e0e5] Unable to get size for file /mnt/Resources/TV/South Park/Season.21/South.Park.S21E03.Holiday Special.720p WEB-DL.mkv Error: OSError(2, 'No such file or directory')
```

**Comment by medariox** [comment]
Can you please try to remove the word `Special` from the title and precess again?

**Comment by bobbysteel** [comment]
Still fails - seems that the show name is being forcibly added in 
```
Processing path: /Media/Videos/South.Park.S21E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb
Processing folder: /Media/Videos/South.Park.S21E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb
Post-processing files: [u'South.Park.S21E03.Holiday.Special.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv']
Post-processing video files: [u'South.Park.S21E03.Holiday.Special.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv']
Processing failed for /Media/Videos/South.Park.S21E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb/South.Park.S21E03.Holiday.Special.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv: Unable to delete the existing files
Problem(s) during processing, failed for the following files/folders: 
/Media/Videos/South.Park.S21E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb/South.Park.S21E03.Holiday.Special.1080p.AMZN.WEB-DL.DDP2.0.H.264-NTb.mkv: Processing failed: Unable to delete the existing files
```
