### ISSUE TITLE
[APP SUBMITTED]: ValueError: invalid literal for int() with base 10: '/media/SAMSUNG/media/series'

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#3267]
### INFO
**Python Version**: `2.7.9 (default, Aug 13 2016, 17:56:53) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.29-10-osmc-armv7l-with-debian-8.9`
**Locale**: `UTF-8`
**Branch**: [optimized](../tree/optimized)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@0f24093e8000bd10f2c1ce99327570aaf3046fc9
**Link to Log**: https://gist.github.com/4d50ef1a0248108156abd54bc0febbd8
### ERROR
<pre>
2017-11-12 22:05:05 ERROR    TORNADO :: [0f24093] API :: "invalid literal for int() with base 10: '/media/SAMSUNG/media/series'"
Traceback (most recent call last):
  File "/home/osmc/Medusa/<a href="../blob/0f24093e8000bd10f2c1ce99327570aaf3046fc9/medusa/server/api/v1/core.py#L126">medusa/server/api/v1/core.py</a>", line 126, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/osmc/Medusa/<a href="../blob/0f24093e8000bd10f2c1ce99327570aaf3046fc9/medusa/server/api/v1/core.py#L196">medusa/server/api/v1/core.py</a>", line 196, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/osmc/Medusa/<a href="../blob/0f24093e8000bd10f2c1ce99327570aaf3046fc9/medusa/server/api/v1/core.py#L1530">medusa/server/api/v1/core.py</a>", line 1530, in run
    return _responds(RESULT_SUCCESS, _get_root_dirs())
  File "/home/osmc/Medusa/<a href="../blob/0f24093e8000bd10f2c1ce99327570aaf3046fc9/medusa/server/api/v1/core.py#L555">medusa/server/api/v1/core.py</a>", line 555, in _get_root_dirs
    default_index = int(app.ROOT_DIRS[0])
ValueError: invalid literal for int() with base 10: '/media/SAMSUNG/media/series'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
This is weird as my config is like this:
root_dirs = 0, /media/SAMSUNG/media/series

**Comment by p0psicles** [comment]
0, is translated to a list: [0]

**Comment by fernandog** [comment]
Seems the API changed my root dirs:

2017-11-13 19:54:23 INFO     MAIN :: [4c3cff8] Starting Medusa [optimized] using '/home/osmc/Medusa/config.ini'
Traceback (most recent call last):
  File "start.py", line 7, in <module>
    main()
  File "/home/osmc/Medusa/medusa/__main__.py", line 2109, in main
    application.start(sys.argv[1:])
  File "/home/osmc/Medusa/medusa/__main__.py", line 347, in start
    self.web_server = AppWebServer(self.web_options)
  File "/home/osmc/Medusa/medusa/server/core.py", line 95, in __init__
    self.video_root = root_dirs[int(root_dirs[0]) + 1]

I had to change my config.ini back to : `root_dirs = 0,/media/SAMSUNG/media/series,`

API changed to `root_dirs = /media/SAMSUNG/media/series,` cause medusa to not boot
without the 0 that indicates the default root dir

**Comment by labrys** [comment]
The getrootdirs API call works and doesn't change the rootdir.  The addrootdir call fails though, but it does not change the config.ini.

**Comment by fernandog** [comment]
@labrys just install Show'sRage  and you will see the root_dirs gets modified in config.ini and Medusa doesn't restart

**Comment by labrys** [comment]
@fernandog even after the fixes?
