### ISSUE TITLE
"BadRarFile: Failed the read enough data" when downloadind subtitles with legendas.tv

### ISSUE THREAD

**Issue by hackedbellini** [pymedusa/Medusa#3277]
**Branch/Commit:**

latest master

**OS:**

Debian Linux

**What you did:**

Both trying to manually download some subtitles and also from automatic download from post-processing.

**What happened:**

The process crashed. Based on it I think that it tried to open the file as a rar file, but it was actually already the .str

**What you expected:**

The subtitle to be successfully downloaded without errors.

**Logs:**
```
2017-11-16 20:39:31 ERROR    POSTPROCESSOR :: [b16e0e5] Bad archive for Silicon.Valley.S04E08.WEBRip.x264-RARBG.srt
Traceback (most recent call last):
  File "/opt/medusa/medusa/subtitle_providers/legendastv.py", line 501, in download_subtitle
    subtitle.content = fix_line_ending(subtitle.archive.content.read(subtitle.name))
  File "/opt/medusa/ext/rarfile.py", line 772, in read
    return f.read()
  File "/opt/medusa/ext/rarfile.py", line 2010, in read
    raise BadRarFile("Failed the read enough data")
BadRarFile: Failed the read enough data
2017-11-16 19:33:49 ERROR    Thread-16 :: [b16e0e5] Bad archive for South.Park.S21E07.WEBRip.x264-RARBG.srt
Traceback (most recent call last):
  File "/opt/medusa/medusa/subtitle_providers/legendastv.py", line 501, in download_subtitle
    subtitle.content = fix_line_ending(subtitle.archive.content.read(subtitle.name))
  File "/opt/medusa/ext/rarfile.py", line 772, in read
    return f.read()
  File "/opt/medusa/ext/rarfile.py", line 2010, in read
    raise BadRarFile("Failed the read enough data")
BadRarFile: Failed the read enough data
2017-11-16 19:33:30 ERROR    Thread-16 :: [b16e0e5] Bad archive for The.Last.Man.On.Earth.S04E02.WEB-DL.x264-RARBG.srt
Traceback (most recent call last):
  File "/opt/medusa/medusa/subtitle_providers/legendastv.py", line 501, in download_subtitle
    subtitle.content = fix_line_ending(subtitle.archive.content.read(subtitle.name))
  File "/opt/medusa/ext/rarfile.py", line 772, in read
    return f.read()
  File "/opt/medusa/ext/rarfile.py", line 2010, in read
    raise BadRarFile("Failed the read enough data")
BadRarFile: Failed the read enough data
2017-11-16 19:32:56 ERROR    Thread-16 :: [b16e0e5] Bad archive for Halt.and.Catch.Fire.S04E04.720p.HDTV.x264-aAF.srt
Traceback (most recent call last):
  File "/opt/medusa/medusa/subtitle_providers/legendastv.py", line 501, in download_subtitle
    subtitle.content = fix_line_ending(subtitle.archive.content.read(subtitle.name))
  File "/opt/medusa/ext/rarfile.py", line 772, in read
    return f.read()
  File "/opt/medusa/ext/rarfile.py", line 2010, in read
    raise BadRarFile("Failed the read enough data")
BadRarFile: Failed the read enough data
```

**Comment by hackedbellini** [comment]
> The process crashed. Based on it I think that it tried to open the file as a rar file, but it was actually already the .str

Reading the code now I think this isn't the error actually.

**Comment by hackedbellini** [comment]
One thing that I noticed was that those subtitles (the `.str` files) ended up in my checkout/data directory. So, they were actually extracted

**Comment by fernandog** [comment]
@hackedbellini can you confirm that archive in ltv is a SRT file and not a .rar file ?

**Comment by hackedbellini** [comment]
@fernandog ok, I just debugged the code and found the problem.

The code expects the file to be extracted to stdout when using the external `rar` tool. However, I had `unrar-free` (from debian archive) here, and it behaves a little different than `unrar`.

Just uninstalled the first package and installed the second one and the error is now gone.

Maybe it is something nice to document in the installation notes for debian.

**Comment by fernandog** [comment]
Fixed upstream
