### ISSUE TITLE
Error: no element found: line 15, column 15

### ISSUE THREAD

**Issue by thyeestes** [pymedusa/Medusa#3297]
I receive this error with multiple series:

```
SHOWQUEUE-REFRESH :: [b16e0e5] Received an invalid XML for Chicago P.D., try again later. Error: no element found: line 15, column 15
```

The line differs but always column 15

**Comment by labrys** [comment]
Which indexer do you use?

**Comment by thyeestes** [comment]
Do you mean search provider? 

NZBHydra which is configured for Spotweb(local on NAS), Binsearch, DogNZB, NZBClub and NZBIndex

**Comment by labrys** [comment]
No I mean indexer.  The error is during SHOWQUEUE-REFRESH which means its refreshing the show.  The error is either from the indexer (TVDB, TVMAZE, or TMDB) or (more likely) an error in the NFO file created for the series.

**Comment by thyeestes** [comment]
I have it set to use all indexers

**Comment by medariox** [comment]
Which indexer did you use to add the show?

![img](https://snapr.pw/i/59e87d903c.png)

**Comment by thyeestes** [comment]
Both are indexed with theTVBD.com

**Comment by labrys** [comment]
Most likely the cause is the series metadata.  Can you post the metadata for one of the affected files?  For example an NFO file if it uses KODI metata.

**Comment by thyeestes** [comment]
I do not see a NFO file. There is a XML file however. The attached txt file is the XML file but I had to rename it.
[series.txt](https://github.com/pymedusa/Medusa/files/1500905/series.txt)

**Comment by p0psicles** [comment]
That file is malformed. Can you remove it, and refresh?

**Comment by thyeestes** [comment]
I tried. I deleted the file and did a Forced Full Update. That resulted in th errors below.

2017-11-24 11:36:21 ERROR    SHOWQUEUE-REFRESH :: [b16e0e5] 269641: Error while refreshing show Chicago P.D.. Error: cannot serialize 269641 (type int)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/show_queue.py", line 632, in run
    self.show.write_metadata()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/series.py", line 849, in write_metadata
    self.__write_show_nfo(metadata_provider)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/series.py", line 832, in __write_show_nfo
    result = metadata_provider.create_show_metadata(self) or result
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/metadata/generic.py", line 242, in create_show_metadata
    return self.write_show_file(show_obj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/metadata/mede8er.py", line 346, in write_show_file
    data.write(nfo_file, encoding='utf-8', xml_declaration=True)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1075, in _escape_cdata
    _raise_serialization_error(text)
  File "/usr/local/python/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize 269641 (type int)

**Comment by p0psicles** [comment]
Just to be sure, you really use the mede8er metadata?

**Comment by thyeestes** [comment]
I have a Mede8er box, can  I live without this metadata? Of course

**Comment by labrys** [comment]
@thyeestes Obviously we would much rather get this fixed 😁, just wanted to confirm that you could actually test a mede8er file.  Can I assume that the metadata was generated by Medusa?

**Comment by labrys** [comment]
It looks like the file writes until the error and truncates there.

**Comment by thyeestes** [comment]
@labrys I do not exactly know what you mean with the original metadata. I added the serie in Medusa and started from there. Today I deleted the series.xml file and did a forced full update which resulted in the errors listed above.
