### ISSUE TITLE
No module named gdbm

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3301]
Just enabled subtitles for the first time in a pretty fresh install.

Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/handler.py", line 2248, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/app/medusa/medusa/subtitles.py", line 333, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/app/medusa/ext/dogpile/cache/region.py", line 984, in set
    self.backend.set(key, self._value(value))
  File "/app/medusa/ext/dogpile/cache/backends/file.py", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/app/medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
ImportError: No module named gdbm

This is not in the normal Docker image, so I'll have to add a PR for this module into the Dockerfile on linuxserver/medusa.

**Comment by medariox** [comment]
What Python version are you running? If this is really needed, we need to add it to `requirements.txt` instead, as we currently bundle all external libraries.

**Comment by bobbysteel** [comment]
It's running dockerized, so seems like Alpine Linux 3.6 with Python 2.7.13. 

I don't know whether it's needed but there's an error thrown when searching for subs unless this module is downloaded.

**Comment by medariox** [comment]
Ah, I see. Seems like Alpine Linux's Python version doesn't come with default GNU dbm support. In that case this should be right thing to do, thanks!
