### ISSUE TITLE
Post Processor crash: Exception generated: u'dk'

### ISSUE THREAD

**Issue by OoGuru** [pymedusa/Medusa#3304]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
Branch: master
Commit: b16e0e5eb4ded727eebd2ab2cd9683ab597662f5

**OS:**
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:          8.6
Codename:     jessie

**What you did:**
Let post processor run

**What happened:**
It crashed

**What you expected:**
It not to crash

**Logs:**
```
2017-11-24 19:50:54 ERROR    POSTPROCESSOR :: [b16e0e5] Exception generated: u'dk'
Traceback (most recent call last):
  File "/opt/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/opt/medusa/medusa/auto_post_processor.py", line 57, in run
    process_tv.ProcessResult(app.TV_DOWNLOAD_DIR, app.PROCESS_METHOD).process(force=force)
  File "/opt/medusa/medusa/process_tv.py", line 162, in process
    ignore_subs=ignore_subs)
  File "/opt/medusa/medusa/process_tv.py", line 334, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/opt/medusa/medusa/process_tv.py", line 535, in process_media
    self.result = processor.process()
  File "/opt/medusa/medusa/post_processor.py", line 1200, in process
    app.MOVE_ASSOCIATED_FILES, app.USE_SUBTITLES and ep_obj.series.subtitles)
  File "/opt/medusa/medusa/post_processor.py", line 491, in post_process_action
    action=action, subtitle_action=subtitle_action, subtitles=subtitles)
  File "/opt/medusa/medusa/post_processor.py", line 426, in _combined_file_operation
    new_file_path = self.rename_associated_file(new_path, new_basename, cur_associated_file)
  File "/opt/medusa/medusa/post_processor.py", line 373, in rename_associated_file
    if from_code(code, unknown='') or from_ietf_code(code, unknown=''):
  File "/opt/medusa/medusa/subtitles.py", line 212, in from_ietf_code
    return Language.fromietf(code)
  File "/opt/medusa/ext/babelfish/language.py", line 124, in fromietf
    language = cls.fromalpha2(language_subtag)
  File "/opt/medusa/ext/babelfish/language.py", line 110, in fromcode
    return cls(*language_converters[converter].reverse(code))
  File "/opt/medusa/ext/babelfish/converters/__init__.py", line 165, in reverse
    raise LanguageReverseError(code)
LanguageReverseError: u'dk'
```

**Comment by OoGuru** [comment]
It seems that files name *.dk.srt is resulting in the error. The correct naming standard is *.da.srt, however *.dk.srt does not seem that unlikely to be used. I hope this information helps.

**Comment by p0psicles** [comment]
We can't make any changes for this. Please report your issue here: https://github.com/Diaoul/babelfish/issues
Maybe @fernandog can be of assistance.

**Comment by fernandog** [comment]
I think we should catch exception that and log.warning user. Language code is invalid

**Comment by p0psicles** [comment]
Then these subtitles will not be accepted right?

**Comment by p0psicles** [comment]
@OoGuru if you want to use these subs, you will have to report the short lang code, with the babelfish repo. At least for now we'll make sure the thread will not crash anymore.

**Comment by OoGuru** [comment]
After reviewing the files it seems like they were mistakenly named this way as everything else used the correct naming standard of *.da.srt, I don't believe it's a problem - other than as you said the whole post processor crashing because of it.

**Comment by fernandog** [comment]
Fixed in develop
