### ISSUE TITLE
[APP SUBMITTED]: TypeError: encoded string too long (574, maximum length 519)

### ISSUE THREAD

**Issue by ChaosTherum** [pymedusa/Medusa#3315]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.15063`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@76e0401eabf7abc7392897f478c4d090a65b3e2c
**Link to Log**: https://gist.github.com/1df99d7f9962dbb07a62737ab0fde87f
### ERROR
<pre>
2017-11-26 03:57:07 ERROR    Thread-23 :: [76e0401] Exception generated: encoded string too long (574, maximum length 519)
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 263, in async_call
    result = function(**kwargs)
  File "C:\Medusa\Medusa\medusa\server\web\home\post_process.py", line 50, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "C:\Medusa\Medusa\medusa\process_tv.py", line 146, in process
    ignore_subs=ignore_subs)
  File "C:\Medusa\Medusa\medusa\process_tv.py", line 331, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "C:\Medusa\Medusa\medusa\process_tv.py", line 532, in process_media
    self.result = processor.process()
  File "C:\Medusa\Medusa\medusa\post_processor.py", line 1202, in process
    app.MOVE_ASSOCIATED_FILES, app.USE_SUBTITLES and ep_obj.series.subtitles)
  File "C:\Medusa\Medusa\medusa\post_processor.py", line 491, in post_process_action
    action=action, subtitle_action=subtitle_action, subtitles=subtitles)
  File "C:\Medusa\Medusa\medusa\post_processor.py", line 434, in _combined_file_operation
    action(cur_associated_file, new_file_path)
  File "C:\Medusa\Medusa\medusa\post_processor.py", line 449, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "C:\Medusa\Medusa\medusa\helpers\__init__.py", line 312, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\Medusa\Python\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "C:\Medusa\Python\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Medusa\Medusa\lib\shutil_custom\__init__.py", line 13, in copyfile_custom
    if _samefile(src, dst):
  File "C:\Medusa\Python\lib\shutil.py", line 64, in _samefile
    os.path.normcase(os.path.abspath(dst)))
  File "C:\Medusa\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
  File "C:\Medusa\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: encoded string too long (574, maximum length 519)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by freitagdavid** [comment]
To add to this. It's causing the entire post processor to crash when it tries to process. I have it setup to move with a naming scheme is this.
`Season %0S/%SN - S%0SE%0E - %EN [%SQ.N][%RG]`

**Comment by ChaosTherum** [comment]
To add to this. It's causing the entire post processor to crash when it tries to process. I have it setup to move with a naming scheme like this.
`Season %0S/%SN - S%0SE%0E - %EN [%SQ.N][%RG]`

**Comment by medariox** [comment]
Your season folder name is confusing guessit. 
Rename
```G:\Downloads\Complete Torrents\medusa\iZombie (Season 02) Episodes 01-19 [1080p] [BD] [5.1 AAC] [HEVC] [x265] [pseudo]```
to
```G:\Downloads\Complete Torrents\medusa\iZombie (Season 02) [1080p] [BD] [5.1 AAC] [HEVC] [x265] [pseudo]```

or report the issue to guessit https://github.com/guessit-io/guessit/issues

**Comment by ChaosTherum** [comment]
Thank you. I think I'll also report to guessit so that at least this edge case won't cause any other crashes.
