### ISSUE TITLE
[APP SUBMITTED]: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/306475 (404)

### ISSUE THREAD

**Issue by mikeo999** [pymedusa/Medusa#3321]
### INFO
**Python Version**: `2.7.13 (default, Dec 18 2016, 23:11:11) [GCC 4.6.4]`
**Operating System**: `Linux-3.2.40-armv7l-with-glibc2.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@76e0401eabf7abc7392897f478c4d090a65b3e2c
**Link to Log**: https://gist.github.com/cb9c876770149ea24b2e71f81ea43439
### ERROR
<pre>
2017-11-26 14:31:36 ERROR    SHOWQUEUE-ADD :: [76e0401] 306475 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/306475 (404)'
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/76e0401eabf7abc7392897f478c4d090a65b3e2c/SickBeard/medusa/show_queue.py#L376">SickBeard/medusa/show_queue.py</a>", line 376, in run
    s = indexer_api[self.indexer_id]
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/76e0401eabf7abc7392897f478c4d090a65b3e2c/SickBeard/medusa/indexers/indexer_base.py#L243">SickBeard/medusa/indexers/indexer_base.py</a>", line 243, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/76e0401eabf7abc7392897f478c4d090a65b3e2c/SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py#L561">SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 561, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/76e0401eabf7abc7392897f478c4d090a65b3e2c/SickBeard/medusa/indexers/tvdbv2/fallback.py#L110">SickBeard/medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/76e0401eabf7abc7392897f478c4d090a65b3e2c/SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py#L199">SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 199, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/306475 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Remove the show and add it again, the show ID has changed.
Also, this should probably be a Warning instead of Error.

**Comment by fernandog** [comment]
In this case yes but 404 must be error so we check if API has changed

**Comment by medariox** [comment]
We can close this then.

**Comment by mikeo999** [comment]
I was a brand new installation of Medusa. While adding my existing shows it goes wrong with the show
https://www.thetvdb.com/?tab=series&id=274260&lid=7 (De Ridder)

The show was not added after the error. So i search again for new shows and again i get more show and also De Ridder. I was recognized by the APIV2 and again an error the he could not add the show.

In the main screen i see the show De Ridder. But again same error and could not change it.


I also a lot of Warnings, so maybe it got something to do with that.

2017-11-27 07:28:02 WARNING  SHOWQUEUE-ADD :: [76e0401] 329895: Data retrieved from TVDBv2 was incomplete. The indexer does not provide show information in the searched language en. Aborting: Missing attribute series_name, cant index in language: en
2017-11-26 16:58:44 WARNING  TORNADO :: [76e0401] 400 GET /api/v2/series/264586/asset/fanart?api_key=**********
2017-11-26 16:58:01 WARNING  TORNADO :: [76e0401] 400 GET /api/v2/series/321060/asset/fanart?api_key=**********
2017-11-26 16:57:18 WARNING  TORNADO :: [76e0401] 400 GET /api/v2/series/310516/asset/fanart?api_key=**********
2017-11-26 16:56:46 WARNING  TORNADO :: [76e0401] 400 GET /api/v2/series/289590/asset/fanart?api_key=**********
2017-11-26 16:55:48 WARNING  TORNADO :: [76e0401] 400 GET /api/v2/series/311904/asset/fanart?api_key=**********
2017-11-26 16:55:18 WARNING  TORNADO :: [76e0401] 400 GET /api/v2/series/313024/asset/fanart?api_key=**********

**Comment by mikeo999** [comment]
Found the problem. While adding the show it goes wrong with English language.  I find the show and tries to add it but then it goes wrong and while it looks like it is added, the show is later removed again.

Switching to Dutch solved the problem and show is now added.

Now i only need to get rid of the other errors.

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/12bff2546ba06fc1f0598620c6ea402f
### ERROR
<pre>
2018-02-11 13:25:19 ERROR    SHOWQUEUE-ADD :: [ccbc0ce] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L559">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 559, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/8fb5507019e7c2d9cf57c5e7c106ed59
### ERROR
<pre>
2018-02-11 17:25:26 ERROR    SHOWQUEUE-ADD :: [ccbc0ce] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L559">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 559, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/bc0aa20fdbe8c3a3ccf87caf2050746c
### ERROR
<pre>
2018-02-11 22:27:06 ERROR    SHOWQUEUE-ADD :: [ccbc0ce] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L559">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 559, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/caac686a0fd14c8f79c309d6541799c9
### ERROR
<pre>
2018-02-12 09:25:26 ERROR    SHOWQUEUE-ADD :: [ccbc0ce] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L559">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 559, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/e0fb262d54c07d7e499ad4b2dc6a9606
### ERROR
<pre>
2018-02-12 10:25:26 ERROR    SHOWQUEUE-ADD :: [ccbc0ce] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L559">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 559, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Seems to be an issue with the selected locale. Please check your adding using a supported locale on tvdb.

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/7adfb69cd0e9e5eb211d01816554d776
### ERROR
<pre>
2018-02-15 18:57:34 ERROR    SHOWQUEUE-ADD :: [ccbc0ce] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L559">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 559, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/43de29196334340ebeaf776f64c4f409
### ERROR
<pre>
2018-02-27 06:03:52 ERROR    SHOWQUEUE-ADD :: [ccbc0ce] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L559">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 559, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/3b283d0134cdaaf4b45cd4fe112e4e97
### ERROR
<pre>
2018-03-02 06:27:15 ERROR    SHOWQUEUE-ADD :: [d6eb72d] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/tvdbv2_api.py#L585">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 585, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by laurentl1** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.14.12-xxxx-std-ipv6-64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/d682d8d615ed2051ed18d58d9a88161d
### ERROR
<pre>
2018-03-26 06:02:44 ERROR    SHOWQUEUE-ADD :: [d6eb72d] 307934 Error while loading information from indexer TVDBv2. Error: 'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)'
Traceback (most recent call last):
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/show_queue.py#L379">medusa/show_queue.py</a>", line 379, in run
    s = indexer_api[self.indexer_id]
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/indexer_base.py#L398">medusa/indexers/indexer_base.py</a>", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/tvdbv2_api.py#L585">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 585, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/home/governorma/.medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/tvdbv2_api.py#L200">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/307934 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by droo88** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-6-amd64-x86_64-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@55b472b377f5e6c89142eb3c211602ceb1084f3b
**Link to Log**: https://gist.github.com/e3efd8e9a77d70b3cf486a7505754ede
### ERROR
<pre>
2018-06-04 22:42:39 ERROR    SHOWQUEUE-ADD :: [55b472b] 329749 Error while loading information from indexer TVDBv2. Error: u'Show search failed in getting a result with reason: HTTPError\n404 Client Error: Not Found for url: https://api.thetvdb.com/series/329749 (404)'
Traceback (most recent call last):
  File "/home8/**********/.apps/medusa/medusa/medusa/show_queue.py", line 381, in run
    s = indexer_api[self.indexer_id]
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/indexer_base.py", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 585, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/fallback.py", line 112, in __call__
    return self.func(*args, **kwargs)
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/329749 (404)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
