### ISSUE TITLE
Search system of Yggtorrent has changed

### ISSUE THREAD

**Issue by Djedje93270** [pymedusa/Medusa#3334]
Hi, like i said, the search system has changed, and medusa can't search in Yggtorrent anymore.

```
2017-11-28 18:45:00 ERROR    SEARCHQUEUE-FORCED-257655 :: [Yggtorrent] :: [b96b3ee] Failed parsing provider.
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/torrent/html/yggtorrent.py", line 141, in parse
    pubdate = self.parse_pubdate(pubdate_raw, human_time=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/providers/generic_provider.py", line 557, in parse_pubdate
    return datetime.now(tz.tzlocal()) - timedelta(seconds=seconds)
TypeError: unsupported type for timedelta seconds component: NoneType
```
regards

**Comment by p0psicles** [comment]
This happening for every search or occasional?

**Comment by adaur** [comment]
Occasional
