### ISSUE TITLE
[APP SUBMITTED]: SSLError: ('The read operation timed out',)

### ISSUE THREAD

**Issue by ITOpsMgr** [pymedusa/Medusa#3347]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.8-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@b96b3ee10760ffa03a15a207841a1a2bc65798dd
**Link to Log**: https://gist.github.com/c6e3750d79799b47f800ad5582e11a18
### ERROR
<pre>
2017-11-29 16:33:59 ERROR    CHECKVERSION :: [b96b3ee] Environment error: ('The read operation timed out',)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/medusa/scheduler.py#L90">medusa/scheduler.py</a>", line 90, in run
    self.action.run(self.force)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/medusa/version_checker.py#L63">medusa/version_checker.py</a>", line 63, in run
    self.list_remote_branches()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/medusa/version_checker.py#L354">medusa/version_checker.py</a>", line 354, in list_remote_branches
    app.GIT_REMOTE_BRANCHES = self.updater.list_remote_branches()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/medusa/version_checker.py#L991">medusa/version_checker.py</a>", line 991, in list_remote_branches
    gh = get_github_repo(app.GIT_ORG, app.GIT_REPO)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/medusa/github_client.py#L95">medusa/github_client.py</a>", line 95, in get_github_repo
    return gh.get_organization(organization).get_repo(repo)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/ext/github/MainClass.py#L198">ext/github/MainClass.py</a>", line 198, in get_organization
    "/orgs/" + login
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/ext/github/Requester.py#L172">ext/github/Requester.py</a>", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/ext/github/Requester.py#L213">ext/github/Requester.py</a>", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/ext/github/Requester.py#L252">ext/github/Requester.py</a>", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/b96b3ee10760ffa03a15a207841a1a2bc65798dd/ext/github/Requester.py#L279">ext/github/Requester.py</a>", line 279, in __requestRaw
    response = cnx.getresponse()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/lib/python2.7/ssl.py", line 766, in recv
    return self.read(buflen)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/lib/python2.7/ssl.py", line 653, in read
    v = self._sslobj.read(len)
SSLError: ('The read operation timed out',)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bobbysteel** [comment]
can you send more debug logs context?

**Comment by fernandog** [comment]
Its was an environment. Maybe your internet was having issues/time outing
