### ISSUE TITLE
config.ini upgrade from version 8(?)->9->10 errors on "enable_manualsearch"

### ISSUE THREAD

**Issue by SunMar** [pymedusa/Medusa#3364]
Hi,

I am trying out Medusa and migrating my SickRage data to it and came across this problem.

**Branch/Commit:** master
**OS:** Windows
**What you did:** Copied my SickRage data folder to my new Medusa data folder
**What happened:** An error on `enable_manualsearch` when upgrading `config.ini` to version 10
**What you expected:** No error
**Logs:**
```
2017-12-01 22:36:15 INFO     MAIN :: [b96b3ee] Backing up config before upgrade
2017-12-01 22:36:15 DEBUG    MAIN :: [b96b3ee] Trying to back up ***\Medusa\Data\config.ini to new
2017-12-01 22:36:15 DEBUG    MAIN :: [b96b3ee] Backup done
2017-12-01 22:36:15 INFO     MAIN :: [b96b3ee] Proceeding with upgrade
2017-12-01 22:36:15 INFO     MAIN :: [b96b3ee] Migrating config up to version 9 : Added setting "enable_manualsearch" for providers (dynamic setting)
2017-12-01 22:36:15 INFO     MAIN :: [b96b3ee] Saving config file to disk
2017-12-01 22:36:15 DEBUG    MAIN :: [b96b3ee] Broken providers already updated in the last hour
2017-12-01 22:36:15 INFO     MAIN :: [b96b3ee] Backing up config before upgrade
2017-12-01 22:36:15 DEBUG    MAIN :: [b96b3ee] Trying to back up ***\Medusa\Data\config.ini to new
2017-12-01 22:36:15 DEBUG    MAIN :: [b96b3ee] Backup done
2017-12-01 22:36:15 INFO     MAIN :: [b96b3ee] Proceeding with upgrade
2017-12-01 22:36:15 INFO     MAIN :: [b96b3ee] Migrating config up to version 10 : Convert all csv config items to lists
Traceback (most recent call last):
  File "***\Medusa\Medusa\SickBeard.py", line 7, in <module>
    main()
  File "***\Medusa\Medusa\medusa\__main__.py", line 2104, in main
    application.start(sys.argv[1:])
  File "***\Medusa\Medusa\medusa\__main__.py", line 297, in start
    self.initialize(console_logging=self.console_logging)
  File "***\Medusa\Medusa\medusa\__main__.py", line 1063, in initialize
    migrator.migrate_config()
  File "***\Medusa\Medusa\medusa\config.py", line 835, in migrate_config
    getattr(self, '_migrate_v' + str(next_version))()
  File "***\Medusa\Medusa\medusa\config.py", line 1241, in _migrate_v10
    self.config_obj['Newznab']['newznab_data']
  File "***\Medusa\Medusa\medusa\providers\nzb\newznab.py", line 351, in get_providers_list
    (NewznabProvider._make_provider(x) for x in provider_data.split('!!!'))
  File "***\Medusa\Medusa\medusa\providers\nzb\newznab.py", line 351, in <genexpr>
    (NewznabProvider._make_provider(x) for x in provider_data.split('!!!'))
  File "***\Medusa\Medusa\medusa\providers\nzb\newznab.py", line 465, in _make_provider
    enable_manualsearch=bool(int(enable_manualsearch)))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comments:**

Perhaps after the version 9 upgrade the config file isn't properly re-read or it forgets to update the changed values internally as well?

If I run Medusa again after the failure (without changing anything) it works:

```
2017-12-01 22:36:31 INFO     MAIN :: [b96b3ee] Backing up config before upgrade
2017-12-01 22:36:31 INFO     MAIN :: [b96b3ee] Proceeding with upgrade
2017-12-01 22:36:31 INFO     MAIN :: [b96b3ee] Migrating config up to version 10 : Convert all csv config items to lists
2017-12-01 22:36:31 INFO     MAIN :: [b96b3ee] Saving config file to disk
```

**Comment by labrys** [comment]
More likely this is a migration issue as SickRage doesn't have Manual Search.  It thinks your SickRage config is a Medusa config and errored when trying to convert that setting.  After the first run, it used the default value and worked properly.  Migrations don't happen very frequently and aren't thoroughly tested so any reports about migration issues are greatly appreciated.

**Comment by SunMar** [comment]
Perhaps it could also help to put in the config a value with which you can identify if it's a Medusa config or not? That'll help with version collisions, though probably at some point SR and Medusa will diverge so much that maintaining migration support isn't feasible.

**Comment by labrys** [comment]
I think migrations might be better moved to a utility to migrate the config/database and disallow in-place migration.
