### ISSUE TITLE
[APP SUBMITTED]: BufferError: Existing exports of data: object cannot be re-sized

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3424]
### INFO
        **Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]
        **Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
        **Locale**: `UTF-8`
        **Branch**: [develop](../tree/develop)
        **Database**: `44.8`
        **Commit**: pymedusa/Medusa@1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5
        **Link to Log**: https://gist.github.com/95e6decc9dc14b0f043c615af5e0fc54
        
### ERROR     
<pre>
2017-12-06 20:45:23 ERROR    Thread-18 :: [1ea0f2e] Exception generated: Existing exports of data: object cannot be re-sized
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5/medusa/server/web/core/base.py#L263">medusa/server/web/core/base.py</a>", line 263, in async_call
    result = function(**kwargs)
  File "/home/pi/Medusa/<a href="../blob/1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5/medusa/server/web/config/search.py#L139">medusa/server/web/config/search.py</a>", line 139, in saveSearch
    ui.notifications.message('Configuration Saved', os.path.join(app.CONFIG_FILE))
  File "/home/pi/Medusa/<a href="../blob/1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5/medusa/ui.py#L51">medusa/ui.py</a>", line 51, in message
    'hash': hash(new_notification)}}))
  File "/home/pi/Medusa/<a href="../blob/1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5/medusa/ws/MedusaWebSocketHandler.py#L12">medusa/ws/MedusaWebSocketHandler.py</a>", line 12, in push_to_web_socket
    client.write_message(msg)
  File "/home/pi/Medusa/<a href="../blob/1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5/ext/tornado/websocket.py#L252">ext/tornado/websocket.py</a>", line 252, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/pi/Medusa/<a href="../blob/1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5/ext/tornado/websocket.py#L785">ext/tornado/websocket.py</a>", line 785, in write_message
    return self._write_frame(True, opcode, message, flags=flags)
  File "/home/pi/Medusa/<a href="../blob/1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5/ext/tornado/websocket.py#L768">ext/tornado/websocket.py</a>", line 768, in _write_frame
    return self.stream.write(frame)
  File "/home/pi/Medusa/<a href="../blob/1ea0f2e791d80b585f9a9d6561e91d21ee1d4ac5/ext/tornado/iostream.py#L395">ext/tornado/iostream.py</a>", line 395, in write
    self._write_buffer += data
BufferError: Existing exports of data: object cannot be re-sized
</pre>
        ---
        _STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
I think your HDD is dying...

**Comment by labrys** [comment]
This is a threading issue with tornado.  If this is a single occurrence I would suggest closing the issue as an anomaly.  If it recurs then we can reopen.  Up to you @duramato.

**Comment by duramato** [comment]
I can reproduce this just by hitting the "Save settings" button more than once.

**Comment by labrys** [comment]
@duramato can you try to reproduce this in some older releases to try to narrow down which commit may have caused this.  Also do you have python 2.7.10 or greater available for testing?

**Comment by duramato** [comment]
I'll do that @labrys , i have Python 2.7.9

This latest report happen when making a manual snatch.

**Comment by shadownetdev1** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.9.30-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@bd0832551d836713481dd0a93f4118372bb5d963
**Link to Log**: https://gist.github.com/49a0f27b8cae292912904c1440e1de20
### ERROR
<pre>
2018-01-23 23:12:04 ERROR    Thread-266 :: [bd08325] Exception generated: Existing exports of data: object cannot be re-sized
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 280, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/config/general.py", line 214, in saveGeneral
    ui.notifications.message('Configuration Saved', os.path.join(app.CONFIG_FILE))
  File "/app/medusa/medusa/ui.py", line 51, in message
    'hash': hash(new_notification)}}))
  File "/app/medusa/medusa/ws/MedusaWebSocketHandler.py", line 12, in push_to_web_socket
    client.write_message(msg)
  File "/app/medusa/ext/tornado/websocket.py", line 252, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/app/medusa/ext/tornado/websocket.py", line 785, in write_message
    return self._write_frame(True, opcode, message, flags=flags)
  File "/app/medusa/ext/tornado/websocket.py", line 768, in _write_frame
    return self.stream.write(frame)
  File "/app/medusa/ext/tornado/iostream.py", line 395, in write
    self._write_buffer += data
BufferError: Existing exports of data: object cannot be re-sized
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by trancen** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]`
**Operating System**: `Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@bd0832551d836713481dd0a93f4118372bb5d963
**Link to Log**: https://gist.github.com/41d3513db0d6ddd2d335f059d2a4efce
### ERROR
<pre>
2018-02-06 13:39:07 ERROR    Thread-19 :: [bd08325] Exception generated: Existing exports of data: object cannot be re-sized
Traceback (most recent call last):
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/medusa/server/web/core/base.py#L280">medusa/server/web/core/base.py</a>", line 280, in async_call
    result = function(**kwargs)
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/medusa/server/web/home/handler.py#L707">medusa/server/web/home/handler.py</a>", line 707, in updateCheck
    app.version_check_scheduler.action.check_for_new_version(force=True)
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/medusa/version_checker.py#L291">medusa/version_checker.py</a>", line 291, in check_for_new_version
    ui.notifications.message('No update needed')
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/medusa/ui.py#L51">medusa/ui.py</a>", line 51, in message
    'hash': hash(new_notification)}}))
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/medusa/ws/MedusaWebSocketHandler.py#L12">medusa/ws/MedusaWebSocketHandler.py</a>", line 12, in push_to_web_socket
    client.write_message(msg)
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/ext/tornado/websocket.py#L252">ext/tornado/websocket.py</a>", line 252, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/ext/tornado/websocket.py#L785">ext/tornado/websocket.py</a>", line 785, in write_message
    return self._write_frame(True, opcode, message, flags=flags)
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/ext/tornado/websocket.py#L768">ext/tornado/websocket.py</a>", line 768, in _write_frame
    return self.stream.write(frame)
  File "/var/www/sickrage/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/ext/tornado/iostream.py#L395">ext/tornado/iostream.py</a>", line 395, in write
    self._write_buffer += data
BufferError: Existing exports of data: object cannot be re-sized
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/issues/3424

**Comment by jcarlos001** [comment]
### INFO
**Python Version**: `2.7.14 (default, Jan  6 2018, 18:53:10) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.1-STABLE-amd64-64bit-ELF`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/186a362d3cb52160df95f46345afc36b
### ERROR
<pre>
2018-02-19 21:27:59 ERROR    Thread-17 :: [ccbc0ce] Exception generated: Existing exports of data: object cannot be re-sized
Traceback (most recent call last):
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/server/web/core/base.py#L280">medusa/server/web/core/base.py</a>", line 280, in async_call
    result = function(**kwargs)
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/server/web/config/providers.py#L595">medusa/server/web/config/providers.py</a>", line 595, in saveProviders
    ui.notifications.message('Configuration Saved', os.path.join(app.CONFIG_FILE))
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/ui.py#L51">medusa/ui.py</a>", line 51, in message
    'hash': hash(new_notification)}}))
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/ws/MedusaWebSocketHandler.py#L12">medusa/ws/MedusaWebSocketHandler.py</a>", line 12, in push_to_web_socket
    client.write_message(msg)
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/ext/tornado/websocket.py#L252">ext/tornado/websocket.py</a>", line 252, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/ext/tornado/websocket.py#L793">ext/tornado/websocket.py</a>", line 793, in write_message
    return self._write_frame(True, opcode, message, flags=flags)
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/ext/tornado/websocket.py#L776">ext/tornado/websocket.py</a>", line 776, in _write_frame
    return self.stream.write(frame)
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/ext/tornado/iostream.py#L406">ext/tornado/iostream.py</a>", line 406, in write
    self._handle_write()
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/ext/tornado/iostream.py#L872">ext/tornado/iostream.py</a>", line 872, in _handle_write
    del self._write_buffer[:self._write_buffer_pos]
BufferError: Existing exports of data: object cannot be re-sized
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
