### ISSUE TITLE
[APP SUBMITTED]: WindowsError: [Error 58] The specified server cannot perform the requested operation: 'G:\\1 ALL Series\\South Park/*.*'

### ISSUE THREAD

**Issue by nl05369** [pymedusa/Medusa#3433]
### INFO

**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/9b69cdc0d58193c4a21a462528977a48

### ERROR
```
2017-12-07 20:53:22 ERROR    SHOWQUEUE-REFRESH :: [1a8dc66] 75897: Error while refreshing show South Park. Error: 
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\show_queue.py", line 629, in run
    self.show.refresh_dir()
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 1746, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 916, in load_episodes_from_dir
    media_files = helpers.list_media_files(self.location)
  File "C:\Medusa\Medusa\medusa\helpers\__init__.py", line 257, in list_media_files
    for cur_file in os.listdir(path):
  File "C:\Medusa\Medusa\medusa\init\filesystem.py", line 85, in <lambda>
    return lambda *args, **kwargs: handle_output(f(*[handle_arg(arg) for arg in args], **{k: handle_arg(arg) for k, arg in kwargs.items()}))
WindowsError: [Error 58] The specified server cannot perform the requested operation: 'G:\\1 ALL Series\\South Park/*.*'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Your network share died? Was this a one time issue or is it more frequent?

**Comment by sharkykh** [comment]
Closed due to lack of response.
