### ISSUE TITLE
[APP SUBMITTED]: ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by ripper1967** [pymedusa/Medusa#3442]
### INFO
        **Python Version**: `2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
        **Operating System**: `Linux-4.10.0-42-generic-x86_64-with-LinuxMint-18.3-sylvia`
        **Locale**: `UTF-8`
        **Branch**: [develop](../tree/develop)
        **Database**: `44.8`
        **Commit**: pymedusa/Medusa@7813c7956c2efb350f2589cc783064575dbf801e
        **Link to Log**: https://gist.github.com/2e9804bb8071edae91dbfe3603bf9177
        ### ERROR
        <pre>
2017-12-09 18:28:51 ERROR    SNATCHQUEUE-MANUALSNATCH-164541 :: [7813c79] qbittorrent: Unable to connect ('Connection aborted.', BadStatusLine("''",))
Traceback (most recent call last):
  File "/opt/Medusa/<a href="../blob/7813c7956c2efb350f2589cc783064575dbf801e/medusa/clients/torrent/generic.py#L76">medusa/clients/torrent/generic.py</a>", line 76, in _request
    cookies=cookies, timeout=120, verify=False)
  File "/opt/Medusa/<a href="../blob/7813c7956c2efb350f2589cc783064575dbf801e/medusa/session/core.py#L94">medusa/session/core.py</a>", line 94, in request
    **kwargs)
  File "/opt/Medusa/<a href="../blob/7813c7956c2efb350f2589cc783064575dbf801e/ext/requests/sessions.py#L508">ext/requests/sessions.py</a>", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/Medusa/<a href="../blob/7813c7956c2efb350f2589cc783064575dbf801e/ext/requests/sessions.py#L618">ext/requests/sessions.py</a>", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/Medusa/<a href="../blob/7813c7956c2efb350f2589cc783064575dbf801e/ext/requests/adapters.py#L490">ext/requests/adapters.py</a>", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
</pre>
        ---
        _STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
        But it did connect and send the torrent. here is the test button from search settings Success: Connected and Authenticated

**Comment by NicoLeOca** [comment]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@2c3767d0b68cc92e0716e3c3f8e57495e05996c3
**Link to Log**: https://gist.github.com/d6e399d0789d5340845f8e1eb328af6d
### ERROR
<pre>
2018-01-17 19:41:19 ERROR    Thread-26 :: [2c3767d] Environment error: ('Connection aborted.', BadStatusLine("''",))
Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 280, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\home\handler.py", line 708, in updateCheck
    app.version_check_scheduler.action.check_for_new_news(force=True)
  File "C:\Medusa\medusa\version_checker.py", line 310, in check_for_new_news
    response = self.session.get(app.NEWS_URL)
  File "C:\Medusa\ext\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Medusa\medusa\session\core.py", line 94, in request
    **kwargs)
  File "C:\Medusa\ext\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Medusa\ext\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Medusa\ext\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@OmgImAlexis ^^

**Comment by TTLucian** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/8b1e1a4f6a57396c3a932ba94a430027
### ERROR
<pre>
2018-04-19 20:02:20 ERROR    SNATCHQUEUE-MANUALSNATCH-295760 :: [d6eb72d] qbittorrent: Unable to connect ('Connection aborted.', BadStatusLine("''",))
Traceback (most recent call last):
  File "C:\Data\Medusa\Medusa\medusa\clients\torrent\generic.py", line 76, in _request
    cookies=cookies, timeout=120, verify=False)
  File "C:\Data\Medusa\Medusa\medusa\session\core.py", line 101, in request
    **kwargs)
  File "C:\Data\Medusa\Medusa\ext\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Data\Medusa\Medusa\ext\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Data\Medusa\Medusa\ext\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
