### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 22] invalid mode ('rb') or filename: u'D:\\series\\active\\Simpsons, The (1989)\\Season 12\\The Simpsons - S12E09 - HOM?-thumb.jpg'

### ISSUE THREAD

**Issue by labrys** [pymedusa/Medusa#3445]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [feature/issuesubmitter](../tree/feature/issuesubmitter)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@34bd8b6987153c30e6bc7d065683c570c0c3140f
**Link to Log**: https://gist.github.com/3a0a07d654682b0256bf7a8aa4cbbfac
### ERROR
<pre>
2017-12-09 23:29:52 ERROR    SHOWQUEUE-REFRESH :: [34bd8b6] 71663: Error while refreshing show The Simpsons. Error: 
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\show_queue.py", line 629, in run
    self.show.refresh_dir()
  File "H:\usr\local\medusa\medusa\tv\series.py", line 1831, in refresh_dir
    cur_loc, subfolders=True)
  File "H:\usr\local\medusa\medusa\post_processor.py", line 190, in list_associated_files
    processed_names += filter(None, (self._rar_basename(file_path, files),))
  File "H:\usr\local\medusa\medusa\post_processor.py", line 300, in _rar_basename
    for rar in rars:
  File "H:\usr\local\medusa\medusa\post_processor.py", line 298, in <genexpr>
    rars = (x for x in files if rarfile.is_rarfile(x))
  File "H:\usr\local\medusa\ext\rarfile.py", line 404, in is_rarfile
    return _get_rar_version(xfile) > 0
  File "H:\usr\local\medusa\ext\rarfile.py", line 389, in _get_rar_version
    with XFile(xfile) as fd:
  File "H:\usr\local\medusa\ext\rarfile.py", line 2401, in __init__
    self._fd = open(xfile, 'rb', bufsize)
IOError: [Errno 22] invalid mode ('rb') or filename: u'D:\\series\\active\\Simpsons, The (1989)\\Season 12\\The Simpsons - S12E09 - HOM?-thumb.jpg'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Can you confirm this is fixed in develop @labrys?

**Comment by medariox** [comment]
Should be fixed. Please reopen if not.
