### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by pucelano7** [pymedusa/Medusa#3462]
**OS:** DSM 6 (NAS Synology)
**What happened:** Daily Search is FALSE...when I restart MEDUSA the value of Daily Search change to TRUE but the second time it has to search change to FALSE again.
**Logs:**
```
2017-12-13 20:57:04 ERROR    DAILYSEARCHER :: [1a8dc66] Exception generated: astimezone() cannot be applied to a naive datetime
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/scheduler.py", line 90, in run
    self.action.run(self.force)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/search/daily.py", line 89, in run
    end_time = show_air_time.astimezone(app_timezone) + timedelta(minutes=try_int(show.runtime, 60))
ValueError: astimezone() cannot be applied to a naive datetime
2017-12-13 20:47:24 ERROR    Thread-16 :: [1a8dc66] Exception generated: can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 263, in async_call
    result = function(**kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 351, in schedule
    results = ComingEpisodes.get_coming_episodes(ComingEpisodes.categories, app.COMING_EPS_SORT, False)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/show/coming_episodes.py", line 121, in get_coming_episodes
    results.sort(ComingEpisodes.sorts[sort])
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/show/coming_episodes.py", line 40, in <lambda>
    'date': (lambda a, b: cmp(a['localtime'], b['localtime'])),
TypeError: can't compare offset-naive and offset-aware datetimes
```
Parameters of search:
![captura1](https://user-images.githubusercontent.com/24883267/33968338-bcc2359c-e067-11e7-8435-78f3262eba54.PNG)

Here you can see the FALSE value in Daily Search
![captura](https://user-images.githubusercontent.com/24883267/33968383-e34731a4-e067-11e7-975b-923720516e06.PNG)

**Comment by labrys** [comment]
@pucelano7 did you have medusa working previously?  was this a migration from sickrage?  would you be willing/able to switch to another branch to test possible fixes?

**Comment by pucelano7** [comment]
@labrys This is muy first time using Medusa or similar application (I installed it 10-15 days ago).
So, I’m learning and this wasn’t a migration from sickrage.
Yes, I’m willing to switch to another branch to test possible fixes.
By the way, this is my first experience with Github (forks, branches and this kind of things)

**Comment by labrys** [comment]
@pucelano7 Since this is a new fresh install and in your logs from #3459 I see medusa failed to downlad the network timezones:
```
2017-12-13 11:59:53 DEBUG    DAILYSEARCHER :: [1a8dc66] Error requesting url https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt. Error: ('Connection aborted.', error(104, 'Connection reset by peer'))
```
So it looks like our CDN is having issues.  I have tagged the dev that runs the server to have them look into it.  While this may resolve your issue, Medusa still should not be crashing when it fails to download the network time zones.

**Comment by pucelano7** [comment]
ok, thanks!!!
If you need any more information I will be pleased of do it.

**Comment by pucelano7** [comment]
By the way, I have several episodes with "Wanted" status but now no one start the downloading (auto) ...maybe the origin is the problem with "Daily Search" task? 

Sorry if the question is easy but I don't know the work that "Daily Search" task do, maybe it just search the TV Show's info and it doesn't send the .torrent file to the Download Station.

**Comment by labrys** [comment]
There are three main types of search.  Daily, Backlog, and Manual.  `Daily` checks your providers list of most recently posted releases for any wanted episodes.  `Backlog` uses the provider's search to search for specific episodes.  `Manual` gives you a page with all releases Medusa has found so that you can select which release you want to download for an episode.

**Comment by pucelano7** [comment]
Thanks for the explanation!!! That's cool and so good for my learning :-)

**Comment by labrys** [comment]
@pucelano7 Did this ever resolve itself?  That will help to determine if its just due to lack of timezone data or if there is a bug so we can properly fix this issue.

**Comment by pucelano7** [comment]
@labrys No, it still happens...this morning I restarted Medusa and when it starts again the same error appears ,
So, I cann't download automaticly

`
2017-12-15 13:00:39 ERROR    DAILYSEARCHER :: [1a8dc66] Exception generated: astimezone() cannot be applied to a naive datetime
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/scheduler.py", line 90, in run
    self.action.run(self.force)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/medusa/search/daily.py", line 89, in run
    end_time = show_air_time.astimezone(app_timezone) + timedelta(minutes=try_int(show.runtime, 60))
ValueError: astimezone() cannot be applied to a naive datetime
`

If you wish I do any test I'll be glad of it.

**Comment by labrys** [comment]
@pucelano7 I'll see if I can work on this some this weekend.

**Comment by pucelano7** [comment]
Thanks!!!

**Comment by pucelano7** [comment]
@labrys This morning I received a surprise when I have seen a notification in my cell phone from medusa and new downloaded tasks :-)
Have you done anything?
Thanks!!!

**Comment by medariox** [comment]
Not sure what happened, but glad it's solved for you. Closing the issue at this point.

**Comment by jorgebouza** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.80-v7+-armv7l-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/a363e966591b2b1cea16d8551cb568d0
### ERROR
<pre>
2018-04-06 10:55:29 ERROR    Thread-16 :: [d6eb72d] Exception generated: can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/server/web/core/base.py#L283">medusa/server/web/core/base.py</a>", line 283, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/server/web/core/base.py#L371">medusa/server/web/core/base.py</a>", line 371, in schedule
    results = ComingEpisodes.get_coming_episodes(ComingEpisodes.categories, app.COMING_EPS_SORT, False)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/show/coming_episodes.py#L129">medusa/show/coming_episodes.py</a>", line 129, in get_coming_episodes
    results.sort(ComingEpisodes.sorts[sort])
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/show/coming_episodes.py#L45">medusa/show/coming_episodes.py</a>", line 45, in <lambda>
    'date': (lambda a, b: cmp(a['localtime'], b['localtime'])),
TypeError: can't compare offset-naive and offset-aware datetimes
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by jorgebouza** [comment]
The above error leads to an empty schedule page. Tried both master and dev branches. Thanks in advance :-)
