### ISSUE TITLE
Problem with root dirs

### ISSUE THREAD

**Issue by thisaintgonnahappen** [pymedusa/Medusa#3483]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
Branch: master
Commit: 1a8dc66c7ec9231be0d3444710e476437c9ae1c8
Version: v0.1.20
**OS:**
Linux MInt 18.2
**What you did:**
My apologies if this isn't a supported function, this is my first time dealing with the Medusa API as well as root dirs. I attempted to add a new show using a program called PlexRequests.
**What happened:**
When I added the show, Medusa received an error when working with Tornado. 
**What you expected:**
The show is supposed to add remotely (or at the least not cause Medusa to go error in this fashion?). 
**Logs:**

I noticed that someone had similar issues recently (https://github.com/pymedusa/Medusa/issues/3404) and I attempted their fix. I went into the config.ini, added the 0, /my/path/to/stuff to the root dirs =  config entry, and when Medusa started up the directory was present in the root dirs section of options. As soon as I clicked the 'Request' button from PlexRequests, I got the log entries shown below. I have never used PlexRequests before, so I again apologize if it should not function with Medusa. It claims to work with SickRage, which while similar isn't exact so I understand if this will not work with Medusa. When all is said and done, after the error occurs and you go back to the root dirs settings page, the list is empty. Thanks in advance!

PASTE LOGS HERE
```
2017-12-16 19:18:32 ERROR    TORNADO :: [1a8dc66] API :: "invalid literal for int() with base 10: '/media/media/TV Recordings'"
Traceback (most recent call last):
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 126, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 2066, in run
    default_index = int(app.ROOT_DIRS[0])
ValueError: invalid literal for int() with base 10: '/media/media/TV Recordings'
2017-12-16 19:18:32 DEBUG    TORNADO :: [1a8dc66] API :: show.addnew: {'tvdbid': '311714'}
2017-12-16 19:18:32 DEBUG    TORNADO :: [1a8dc66] API :: all kwargs: {'cmd': 'show.addnew', 'tvdbid': '311714'}
2017-12-16 19:18:32 DEBUG    TORNADO :: [1a8dc66] API :: all args: ()
2017-12-16 19:18:32 DEBUG    TORNADO :: [1a8dc66] API :: 192.168.0.131 - gave correct API KEY. ACCESS GRANTED
2017-12-16 19:18:32 DEBUG    TORNADO :: [1a8dc66] API :: show: {'tvdbid': '311714'}
2017-12-16 19:18:32 DEBUG    TORNADO :: [1a8dc66] API :: all kwargs: {'cmd': 'show', 'tvdbid': '311714'}
2017-12-16 19:18:32 DEBUG    TORNADO :: [1a8dc66] API :: all args: ()
2017-12-16 19:18:32 DEBUG    TORNADO :: [1a8dc66] API :: 192.168.0.131 - gave correct API KEY. ACCESS GRANTED
```

**Comment by labrys** [comment]
@pmaciocia Did you make sure you shut down before changing the config?  If not the changes get overwritten.

**Comment by thisaintgonnahappen** [comment]
yes, absolutely. After the error occurs, and the view has no directories listed (in options), the config still reads correctly:
root_dirs = 0, /media/media/TV Recordings

**Comment by thisaintgonnahappen** [comment]
In case it helps, I activated the 'enable logs from the internal Tornado web server' and got a few extra lines of info:

2017-12-16 20:32:38 INFO     TORNADO :: [1a8dc66] 200 GET /api/**********?cmd=show.addnew&tvdbid=311714 (192.168.0.131) 18.50ms
2017-12-16 20:32:38 ERROR    TORNADO :: [1a8dc66] API :: "invalid literal for int() with base 10: '/media/media/TV Recordings'"
Traceback (most recent call last):
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 126, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 2066, in run
    default_index = int(app.ROOT_DIRS[0])
ValueError: invalid literal for int() with base 10: '/media/media/TV Recordings'
2017-12-16 20:32:38 INFO     TORNADO :: [1a8dc66] 200 GET /api/**********?cmd=show&tvdbid=311714 (192.168.0.131) 4.00ms

**Comment by labrys** [comment]
I have not used plex requests, but if your config.ini is listed as you say, then the error doesn't make sense.  The line `default_index = int(app.ROOT_DIRS[0])` takes the first element from the apps ROOT_DIRS which and converts it to an int.  In your case its trying to convert `/media/media/TV REcordings` which is obviously not an integer.   Would you be willing to change branches to try out some tests?

**Comment by thisaintgonnahappen** [comment]
yeah no problem

**Comment by labrys** [comment]
I think I found the problem.  Pushing a fix for you.

**Comment by thisaintgonnahappen** [comment]
awesome! its very much appreciated!

**Comment by labrys** [comment]
If you could try the branch `feature/rootdirs` and let me know if it works for you.

**Comment by thisaintgonnahappen** [comment]
confirmed I updated to the right one:

Branch: feature/rootdirs
Commit: 1a8dc66c7ec9231be0d3444710e476437c9ae1c8
Version: v0.1.20
Database: 44.8
--
But still had same problem (no log changes):
2017-12-16 20:56:04 ERROR    TORNADO :: [1a8dc66] API :: "invalid literal for int() with base 10: '/media/media/TV Recordings'"
Traceback (most recent call last):
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 126, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 2066, in run
    default_index = int(app.ROOT_DIRS[0])
ValueError: invalid literal for int() with base 10: '/media/media/TV Recordings'

and config.ini reads: root_dirs = 0, /media/media/TV Recordings
(and the root dirs diplayed properly when started as well)

**Comment by labrys** [comment]
@thisaintgonnahappen 1a8dc66 is still master.  Make sure you restart after changing branches.

**Comment by thisaintgonnahappen** [comment]
sorry Im a git nub, I did it via command line 'git checkout -b feature/rootdirs' then a 'git fetch' and still have the same commit value. Is there a better way?

**Comment by thisaintgonnahappen** [comment]
oh geeze figured it out, don't use -b lol. Anyhow, it still came back with an error:
2017-12-16 22:34:01 ERROR    TORNADO :: [27d02c4] API :: "int() argument must be a string or a number, not 'list'"
Traceback (most recent call last):
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 126, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 2066, in run
    default_index = int(index)
TypeError: int() argument must be a string or a number, not 'list'

**Comment by thisaintgonnahappen** [comment]
sorry, didn't realize you added some additional debug info, here's the extended log:
2017-12-16 22:34:01 INFO     TORNADO :: [27d02c4] 200 GET /api/**********?cmd=show.addnew&tvdbid=311714 (192.168.0.131) 5.01ms
2017-12-16 22:34:01 ERROR    TORNADO :: [27d02c4] API :: "int() argument must be a string or a number, not 'list'"
Traceback (most recent call last):
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 126, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 2066, in run
    default_index = int(index)
TypeError: int() argument must be a string or a number, not 'list'
2017-12-16 22:34:01 DEBUG    TORNADO :: [27d02c4] Root directories: [u'0', u'/media/media/TV Recordings']
2017-12-16 22:34:01 DEBUG    TORNADO :: [27d02c4] API :: show.addnew: {'tvdbid': '311714'}
2017-12-16 22:34:01 DEBUG    TORNADO :: [27d02c4] API :: all kwargs: {'cmd': 'show.addnew', 'tvdbid': '311714'}
2017-12-16 22:34:01 DEBUG    TORNADO :: [27d02c4] API :: all args: ()
2017-12-16 22:34:01 DEBUG    TORNADO :: [27d02c4] API :: 192.168.0.131 - gave correct API KEY. ACCESS GRANTED
2017-12-16 22:34:01 INFO     TORNADO :: [27d02c4] 200 GET /api/**********?cmd=show&tvdbid=311714 (192.168.0.131) 4.76ms

**Comment by thisaintgonnahappen** [comment]
ah! because 'app.ROOT_DIRS[:1]' is returning a list instead of the index 0:
index, root_dirs = app.ROOT_DIRS[:1], app.ROOT_DIRS[1:]
default_index = int(index)

**Comment by thisaintgonnahappen** [comment]
I made that change in my local repository (ie app.ROOT_DIRS[:1] to app.ROOT_DIRS[0]) and all worked

**Comment by thisaintgonnahappen** [comment]
thanks for the outstanding support and response on this, that was amazingly fast!
