### ISSUE TITLE
Adding Series via API multiple issues

### ISSUE THREAD

**Issue by tidusjar** [pymedusa/Medusa#3501]
Hello, I am attempting to integrate Medusa into Ombi. I have successfully got SickRage working so I thought this would be pretty similar.

**Branch/Commit:** master/ 1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**OS:** Docker
**What you did:**
GET request to: http://192.168.1.7:9090/api/APIKEY/?cmd=show.addnew&tvdbid=75760&status=ignored&initial=sddvd

Now I did this 3 times with different errors (see Logs)

Response with the latest error:
```
{"data": {"args": [], "error_msg": "pop from empty list", "kwargs": {"initial": "sddvd", "status": "ignored", "tvdbid": "75760"}}, "message": "Medusa encountered an internal error! Please report to the Devs", "result": "fatal"}
```

**What happened:**
**What you expected:**
**Logs:**
```
Traceback (most recent call last):
File "/app/medusa/medusa/server/api/v1/core.py", line 126, in get
out_dict = _call_dispatcher(args, kwargs)
File "/app/medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
cur_out_dict = func(cur_args, cur_kwargs).run() # call function and get response
File "/app/medusa/medusa/server/api/v1/core.py", line 2066, in run
default_index = int(app.ROOT_DIRS[0])
IndexError: list index out of range
2017-12-19 21:40:48 ERROR TORNADO :: [1a8dc66] API :: "invalid literal for int() with base 10: '/downloads'"

Traceback (most recent call last):
File "/app/medusa/medusa/server/api/v1/core.py", line 126, in get
out_dict = _call_dispatcher(args, kwargs)
File "/app/medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
cur_out_dict = func(cur_args, cur_kwargs).run() # call function and get response
File "/app/medusa/medusa/server/api/v1/core.py", line 2066, in run
default_index = int(app.ROOT_DIRS[0])
ValueError: invalid literal for int() with base 10: '/downloads'
2017-12-19 21:42:26 ERROR TORNADO :: [1a8dc66] API :: 'list index out of range'

Traceback (most recent call last):
File "/app/medusa/medusa/server/api/v1/core.py", line 126, in get
out_dict = _call_dispatcher(args, kwargs)
File "/app/medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
cur_out_dict = func(cur_args, cur_kwargs).run() # call function and get response
File "/app/medusa/medusa/server/api/v1/core.py", line 2066, in run
default_index = int(app.ROOT_DIRS[0])
IndexError: list index out of range
2017-12-19 21:43:18 ERROR TORNADO :: [1a8dc66] API :: 'pop from empty list'

Traceback (most recent call last):
File "/app/medusa/medusa/server/api/v1/core.py", line 126, in get
out_dict = _call_dispatcher(args, kwargs)
File "/app/medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
cur_out_dict = func(cur_args, cur_kwargs).run() # call function and get response
File "/app/medusa/medusa/server/api/v1/core.py", line 2065, in run
root_dirs.pop(0)
IndexError: pop from empty list
```

If there is any more information I can provide please let me know.

**Comment by p0psicles** [comment]
Try develop branch. Think that's recently fixed.

**Comment by OoGuru** [comment]
I have just tried out

Ombi 
- Version: v3.0.2052
Medusa
- Branch: develop
- Commit: c28b816ee42e40afc73f2386f2047b95c11852e0
- Version: v0.1.17

And it does indeed seem to work!

Do you think the next version including this fix is far into the future? Trying to estimate whether I should switch all my medusa instances to develop or just hold on for moment.

Thanks :)

**Comment by p0psicles** [comment]
Matter of days
