### ISSUE TITLE
[APP SUBMITTED]: KeyError: "u'version'"

### ISSUE THREAD

**Issue by sephrat** [pymedusa/Medusa#3556]
### INFO
**Python Version**: `2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]`
**Operating System**: `Linux-3.2.40-armv7l-with-glibc2.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@7b9111eef5836a6846499ef257ffff3f1f35df8f
**Link to Log**: https://gist.github.com/adaeb1415fefd1083f59da7f01134ac6
### ERROR
<pre>
2017-12-29 19:52:25 ERROR    FINDPROPERS :: [7b9111e] BraceMessage string formatting failed. Using representation instead.
  File "/usr/local/python/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/scheduler.py#L90">SickBeard/medusa/scheduler.py</a>", line 90, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/search/proper.py#L65">SickBeard/medusa/search/proper.py</a>", line 65, in run
    self._download_propers(propers)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/search/proper.py#L353">SickBeard/medusa/search/proper.py</a>", line 353, in _download_propers
    snatch_episode(cur_proper)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/search/core.py#L159">SickBeard/medusa/search/core.py</a>", line 159, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/clients/torrent/generic.py#L254">SickBeard/medusa/clients/torrent/generic.py</a>", line 254, in send_torrent
    r_code = self._add_torrent_uri(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/clients/torrent/download_station_client.py#L124">SickBeard/medusa/clients/torrent/download_station_client.py</a>", line 124, in _add_torrent_uri
    log.debug('Add torrent URI with data: {}'.format(data))
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/logger/adapters/style.py#L89">SickBeard/medusa/logger/adapters/style.py</a>", line 89, in log
    self.logger.log(level, brace_msg, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1489, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/logger/__init__.py#L546">SickBeard/medusa/logger/__init__.py</a>", line 546, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/init/logconfig.py#L80">SickBeard/medusa/init/logconfig.py</a>", line 80, in __str__
    result = text_type(self.fmt)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/logger/adapters/style.py#L49">SickBeard/medusa/logger/adapters/style.py</a>", line 49, in __str__
    ''.join(traceback.format_stack()),
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/logger/adapters/style.py#L39">SickBeard/medusa/logger/adapters/style.py</a>", line 39, in __str__
    return msg.format(*args, **kwargs)
KeyError: "u'version'"
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sephrat** [comment]
Some additionnal info: this seems to happen whenever Medusa sends a torrent to download to Synology DS. 
It does work but this error message keeps popping in the logs.
I've played around with users permissions lately so I'm probably guilty (it worked fine a couple of days ago), however the error message is a bit harsh. :-)

**Comment by fernandog** [comment]
Did you install Medusa using GitHub or downloading files from the repository?

**Comment by sephrat** [comment]
@fernandog I installed it using GitHub.

**Comment by labrys** [comment]
@sephrat this has nothing to do with anything you did, it's due to a change in the logger to try to catch some errors that were slipping past unlogged.  A fix is in progress for this.

**Comment by labrys** [comment]
See #3531

**Comment by mattail** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@7b9111eef5836a6846499ef257ffff3f1f35df8f
**Link to Log**: https://gist.github.com/747dfc43210300a2eb2db7b9ba6295a7
### ERROR
<pre>
2018-01-14 20:00:47 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [7b9111e] BraceMessage string formatting failed. Using representation instead.
  File "/usr/local/python/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/search/queue.py#L288">SickBeard/medusa/search/queue.py</a>", line 288, in run
    self.success = snatch_episode(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/search/core.py#L159">SickBeard/medusa/search/core.py</a>", line 159, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/clients/torrent/generic.py#L256">SickBeard/medusa/clients/torrent/generic.py</a>", line 256, in send_torrent
    r_code = self._add_torrent_file(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/clients/torrent/download_station_client.py#L147">SickBeard/medusa/clients/torrent/download_station_client.py</a>", line 147, in _add_torrent_file
    log.debug('Add torrent files with data: {}'.format(data))
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/logger/adapters/style.py#L89">SickBeard/medusa/logger/adapters/style.py</a>", line 89, in log
    self.logger.log(level, brace_msg, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1489, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/logger/__init__.py#L546">SickBeard/medusa/logger/__init__.py</a>", line 546, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/init/logconfig.py#L80">SickBeard/medusa/init/logconfig.py</a>", line 80, in __str__
    result = text_type(self.fmt)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/logger/adapters/style.py#L49">SickBeard/medusa/logger/adapters/style.py</a>", line 49, in __str__
    ''.join(traceback.format_stack()),
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/SickBeard/medusa/logger/adapters/style.py#L39">SickBeard/medusa/logger/adapters/style.py</a>", line 39, in __str__
    return msg.format(*args, **kwargs)
KeyError: "u'session'"
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by labrys** [comment]
@mattail fixed in develop
