### ISSUE TITLE
[APP SUBMITTED]: KeyError: 'destination'

### ISSUE THREAD

**Issue by jgrossrieder** [pymedusa/Medusa#3563]
### INFO
**Python Version**: `2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]`
**Operating System**: `Linux-4.10.0-37-generic-x86_64-with-Ubuntu-17.04-zesty`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@7b9111eef5836a6846499ef257ffff3f1f35df8f
**Link to Log**: https://gist.github.com/e793752e47d920be5b838eb5f5ab1fa2
### ERROR
<pre>
2017-12-31 00:22:04 ERROR    POSTPROCESSOR :: [7b9111e] BraceMessage string formatting failed. Using representation instead.
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/scheduler.py#L90">medusa/scheduler.py</a>", line 90, in run
    self.action.run(self.force)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/auto_post_processor.py#L57">medusa/auto_post_processor.py</a>", line 57, in run
    process_tv.ProcessResult(app.TV_DOWNLOAD_DIR, app.PROCESS_METHOD).process(force=force)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/process_tv.py#L146">medusa/process_tv.py</a>", line 146, in process
    ignore_subs=ignore_subs)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/process_tv.py#L335">medusa/process_tv.py</a>", line 335, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/process_tv.py#L536">medusa/process_tv.py</a>", line 536, in process_media
    self.result = processor.process()
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/post_processor.py#L1203">medusa/post_processor.py</a>", line 1203, in process
    app.MOVE_ASSOCIATED_FILES, app.USE_SUBTITLES and ep_obj.series.subtitles)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/post_processor.py#L493">medusa/post_processor.py</a>", line 493, in post_process_action
    action=action, subtitle_action=subtitle_action, subtitles=subtitles)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/post_processor.py#L436">medusa/post_processor.py</a>", line 436, in _combined_file_operation
    action(cur_associated_file, new_file_path)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/post_processor.py#L482">medusa/post_processor.py</a>", line 482, in symlink
    helpers.move_and_symlink_file(cur_file_path, new_file_path)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/helpers/__init__.py#L417">medusa/helpers/__init__.py</a>", line 417, in move_and_symlink_file
    'error': msg,
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/logger/adapters/style.py#L89">medusa/logger/adapters/style.py</a>", line 89, in log
    self.logger.log(level, brace_msg, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1489, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/logger/__init__.py#L546">medusa/logger/__init__.py</a>", line 546, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/init/logconfig.py#L80">medusa/init/logconfig.py</a>", line 80, in __str__
    result = text_type(self.fmt)
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/logger/adapters/style.py#L49">medusa/logger/adapters/style.py</a>", line 49, in __str__
    ''.join(traceback.format_stack()),
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/7b9111eef5836a6846499ef257ffff3f1f35df8f/medusa/logger/adapters/style.py#L39">medusa/logger/adapters/style.py</a>", line 39, in __str__
    return msg.format(*args, **kwargs)
KeyError: 'destination'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@jgrossrieder can you open Server status page and check if there is any row in red?

**Comment by jgrossrieder** [comment]
@fernandog  No everything is in green.

**Comment by fernandog** [comment]
Did you restart after that error?

**Comment by jgrossrieder** [comment]
I got it first some days ago, then I did an update(that should have restarted), then I got the exception again.

But I can try to restart again now.

**Comment by fernandog** [comment]
No need

**Comment by jgrossrieder** [comment]
duplicate of?

**Comment by p0psicles** [comment]
It should be fixed in the develop branch. Can you verify for us?
