### ISSUE TITLE
[APP SUBMITTED]: UnicodeEncodeError: 'charmap' codec can't encode characters in position 22-25: character maps to <undefined>

### ISSUE THREAD

**Issue by Bangorbob** [pymedusa/Medusa#3602]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@7b9111eef5836a6846499ef257ffff3f1f35df8f
**Link to Log**: https://gist.github.com/04290420741e9520c8f669deb9dc2f00
### ERROR
<pre>
2018-01-12 10:47:04 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Torrentz2] :: [7b9111e] BraceMessage string formatting failed. Using representation instead.
  File "C:\Medusa\Python\lib\threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "C:\Medusa\Python\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Medusa\Medusa\medusa\search\queue.py", line 262, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "C:\Medusa\Medusa\medusa\search\core.py", line 454, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "C:\Medusa\Medusa\medusa\tv\cache.py", line 225, in update_cache
    result = self._parse_item(item)
  File "C:\Medusa\Medusa\medusa\tv\cache.py", line 304, in _parse_item
    leechers, size, pubdate)
  File "C:\Medusa\Medusa\medusa\tv\cache.py", line 375, in add_cache_entry
    log.debug('{0}', error)
  File "C:\Medusa\Medusa\medusa\logger\adapters\style.py", line 89, in log
    self.logger.log(level, brace_msg, **kwargs)
  File "C:\Medusa\Python\lib\logging\__init__.py", line 1489, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "C:\Medusa\Python\lib\logging\__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "C:\Medusa\Python\lib\logging\__init__.py", line 1286, in _log
    self.handle(record)
  File "C:\Medusa\Python\lib\logging\__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "C:\Medusa\Python\lib\logging\__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "C:\Medusa\Python\lib\logging\__init__.py", line 759, in handle
    self.emit(record)
  File "C:\Medusa\Python\lib\logging\handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "C:\Medusa\Python\lib\logging\handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "C:\Medusa\Python\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "C:\Medusa\Medusa\medusa\logger\__init__.py", line 546, in format
    msg = super(CensoredFormatter, self).format(record)
  File "C:\Medusa\Python\lib\logging\__init__.py", line 469, in format
    s = self._fmt % record.__dict__
  File "C:\Medusa\Medusa\medusa\init\logconfig.py", line 80, in __str__
    result = text_type(self.fmt)
  File "C:\Medusa\Medusa\medusa\logger\adapters\style.py", line 49, in __str__
    ''.join(traceback.format_stack()),
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\logger\adapters\style.py", line 39, in __str__
    return msg.format(*args, **kwargs)
  File "C:\Medusa\Python\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 22-25: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Should be already fixed in develop.

**Comment by imrman** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1255`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@7cfc79d5280b719c6288090fb805521dfc0402cd
**Link to Log**: https://gist.github.com/c987f50c50b618a306a01b02e569d4ce
### ERROR
<pre>
2018-07-05 08:53:08 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [7cfc79d] DailySearchQueueItem Exception, error: 'charmap' codec can't encode character u'\xf6' in position 43: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/search/queue.py#L289">medusa\search\queue.py</a>", line 289, in run
    self.success = snatch_episode(result)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/search/core.py#L230">medusa\search\core.py</a>", line 230, in snatch_episode
    result.leechers, result.provider.name), is_proper)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/notifiers/__init__.py#L108">medusa\notifiers\__init__.py</a>", line 108, in notify_snatch
    n.notify_snatch(ep_name, is_proper)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/notifiers/telegram.py#L101">medusa\notifiers\telegram.py</a>", line 101, in notify_snatch
    self._notify_telegram(title, ep_name)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/notifiers/telegram.py#L165">medusa\notifiers\telegram.py</a>", line 165, in _notify_telegram
    return self._send_telegram_msg(title, message, user_id, api_key)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/notifiers/telegram.py#L62">medusa\notifiers\telegram.py</a>", line 62, in _send_telegram_msg
    message = '%s : %s' % (title.encode(), msg.encode())
  File "C:\Medusa\Python\lib\encodings\cp1255.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xf6' in position 43: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by imrman** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1255`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@7cfc79d5280b719c6288090fb805521dfc0402cd
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-07-05 02:53:57 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [7cfc79d] DailySearchQueueItem Exception, error: 'charmap' codec can't encode character u'\xf3' in position 26: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/search/queue.py#L289">medusa\search\queue.py</a>", line 289, in run
    self.success = snatch_episode(result)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/search/core.py#L230">medusa\search\core.py</a>", line 230, in snatch_episode
    result.leechers, result.provider.name), is_proper)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/notifiers/__init__.py#L108">medusa\notifiers\__init__.py</a>", line 108, in notify_snatch
    n.notify_snatch(ep_name, is_proper)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/notifiers/telegram.py#L101">medusa\notifiers\telegram.py</a>", line 101, in notify_snatch
    self._notify_telegram(title, ep_name)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/notifiers/telegram.py#L165">medusa\notifiers\telegram.py</a>", line 165, in _notify_telegram
    return self._send_telegram_msg(title, message, user_id, api_key)
  File "C:\Medusa\Medusa\<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/notifiers/telegram.py#L62">medusa\notifiers\telegram.py</a>", line 62, in _send_telegram_msg
    message = '%s : %s' % (title.encode(), msg.encode())
  File "C:\Medusa\Python\lib\encodings\cp1255.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xf3' in position 26: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by imrman** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1255`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64
**Link to Log**: https://gist.github.com/a7ce6cc8c2822b87b57ded2171a59678
### ERROR
<pre>
2018-07-07 10:54:40 ERROR    FINDSUBTITLES :: [e7c4ff3] Exception generated: 'charmap' codec can't encode character u'\xf9' in position 25: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/scheduler.py#L93">medusa\scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "C:\Medusa\Medusa\<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/subtitles.py#L1065">medusa\subtitles.py</a>", line 1065, in run
    episode_object.download_subtitles()
  File "C:\Medusa\Medusa\<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/tv/episode.py#L503">medusa\tv\episode.py</a>", line 503, in download_subtitles
    notifiers.notify_subtitle_download(self.pretty_name(), subtitle_list)
  File "C:\Medusa\Medusa\<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/notifiers/__init__.py#L100">medusa\notifiers\__init__.py</a>", line 100, in notify_subtitle_download
    n.notify_subtitle_download(ep_name, lang)
  File "C:\Medusa\Medusa\<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/notifiers/telegram.py#L122">medusa\notifiers\telegram.py</a>", line 122, in notify_subtitle_download
    self._notify_telegram(title, '%s: %s' % (ep_name, lang))
  File "C:\Medusa\Medusa\<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/notifiers/telegram.py#L165">medusa\notifiers\telegram.py</a>", line 165, in _notify_telegram
    return self._send_telegram_msg(title, message, user_id, api_key)
  File "C:\Medusa\Medusa\<a href="../blob/e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64/medusa/notifiers/telegram.py#L62">medusa\notifiers\telegram.py</a>", line 62, in _send_telegram_msg
    message = '%s : %s' % (title.encode(), msg.encode())
  File "C:\Medusa\Python\lib\encodings\cp1255.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xf9' in position 25: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bartolomesoriano** [comment]
### INFO
**Python Version**: `2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18252`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/e239f0a3e546f2b9fdb7a6ae13311f10
### ERROR
<pre>
2018-10-18 03:19:56 ERROR    SHOWQUEUE-REFRESH :: [4614efc] 268972: Error while refreshing show Chef's Table. Error: 'charmap' codec can't encode character u'\u011f' in position 80: character maps to <undefined>
Traceback (most recent call last):
  File "C:\pyMedusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/show_queue.py#L686">medusa\show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "C:\pyMedusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1730">medusa\tv\series.py</a>", line 1730, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\pyMedusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1036">medusa\tv\series.py</a>", line 1036, in load_episodes_from_dir
    cur_episode.refresh_subtitles()
  File "C:\pyMedusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/episode.py#L441">medusa\tv\episode.py</a>", line 441, in refresh_subtitles
    current_subtitles = subtitles.get_current_subtitles(self)
  File "C:\pyMedusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L593">medusa\subtitles.py</a>", line 593, in get_current_subtitles
    video = get_video(tv_episode, video_path)
  File "C:\pyMedusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L720">medusa\subtitles.py</a>", line 720, in get_video
    video_path = _encode(video_path)
  File "C:\pyMedusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L624">medusa\subtitles.py</a>", line 624, in _encode
    return value.encode(fallback or app.SYS_ENCODING)
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u011f' in position 80: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pct00** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/115f3e2e04931ea6b7305476b1687f34
### ERROR
<pre>
2018-10-18 21:39:30 ERROR    SHOWQUEUE-REFRESH :: [4614efc] 259063: Error while refreshing show Hannibal. Error: 'charmap' codec can't encode character u'\u014d' in position 54: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/show_queue.py#L686">medusa\show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1730">medusa\tv\series.py</a>", line 1730, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1036">medusa\tv\series.py</a>", line 1036, in load_episodes_from_dir
    cur_episode.refresh_subtitles()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/episode.py#L441">medusa\tv\episode.py</a>", line 441, in refresh_subtitles
    current_subtitles = subtitles.get_current_subtitles(self)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L593">medusa\subtitles.py</a>", line 593, in get_current_subtitles
    video = get_video(tv_episode, video_path)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L720">medusa\subtitles.py</a>", line 720, in get_video
    video_path = _encode(video_path)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L624">medusa\subtitles.py</a>", line 624, in _encode
    return value.encode(fallback or app.SYS_ENCODING)
  File "C:\Program Files\Medusa\Python\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u014d' in position 54: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pct00** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/04532ce1833f66b7f5916947e6cdeeb8
### ERROR
<pre>
2018-10-17 19:19:47 ERROR    POSTPROCESSOR :: [4614efc] Exception generated: 'charmap' codec can't encode character u'\u014d' in position 54: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/scheduler.py#L93">medusa\scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/auto_post_processor.py#L58">medusa\auto_post_processor.py</a>", line 58, in run
    process_tv.ProcessResult(app.TV_DOWNLOAD_DIR, app.PROCESS_METHOD).process(force=force)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/process_tv.py#L145">medusa\process_tv.py</a>", line 145, in process
    ignore_subs=ignore_subs)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/process_tv.py#L333">medusa\process_tv.py</a>", line 333, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/process_tv.py#L554">medusa\process_tv.py</a>", line 554, in process_media
    self.result = processor.process()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/post_processor.py#L1256">medusa\post_processor.py</a>", line 1256, in process
    cur_ep.refresh_subtitles()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/episode.py#L441">medusa\tv\episode.py</a>", line 441, in refresh_subtitles
    current_subtitles = subtitles.get_current_subtitles(self)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L593">medusa\subtitles.py</a>", line 593, in get_current_subtitles
    video = get_video(tv_episode, video_path)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L720">medusa\subtitles.py</a>", line 720, in get_video
    video_path = _encode(video_path)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L624">medusa\subtitles.py</a>", line 624, in _encode
    return value.encode(fallback or app.SYS_ENCODING)
  File "C:\Program Files\Medusa\Python\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u014d' in position 54: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pct00** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/c867d8de12302577dc069e31da6a02da
### ERROR
<pre>
2018-10-20 13:20:14 ERROR    SHOWQUEUE-REFRESH :: [4614efc] 259063: Error while refreshing show Hannibal. Error: 'charmap' codec can't encode character u'\u014d' in position 54: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/show_queue.py#L686">medusa\show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1730">medusa\tv\series.py</a>", line 1730, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/series.py#L1036">medusa\tv\series.py</a>", line 1036, in load_episodes_from_dir
    cur_episode.refresh_subtitles()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/tv/episode.py#L441">medusa\tv\episode.py</a>", line 441, in refresh_subtitles
    current_subtitles = subtitles.get_current_subtitles(self)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L593">medusa\subtitles.py</a>", line 593, in get_current_subtitles
    video = get_video(tv_episode, video_path)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L720">medusa\subtitles.py</a>", line 720, in get_video
    video_path = _encode(video_path)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/subtitles.py#L624">medusa\subtitles.py</a>", line 624, in _encode
    return value.encode(fallback or app.SYS_ENCODING)
  File "C:\Program Files\Medusa\Python\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u014d' in position 54: character maps to <undefined>
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
