### ISSUE TITLE
Medusa over https with Apache Reverse Proxy

### ISSUE THREAD

**Issue by saitoh183** [pymedusa/Medusa#3607]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

![image](https://user-images.githubusercontent.com/1534197/34923769-dbad4de8-f96c-11e7-94e6-9248ba826249.png)

**What you did:** I tried to copy the RP settings of sickrage and got the error in the log below. I also tried to copy the apache reverse proxy settings from the wiki but with those setting the page never loads...just keeps spinning 
**What happened:**  I get a blank page
**What you expected:**  Page loads properly
**Logs:**
```
Mixed Content: The page at 'https://tiny.seedhost.eu/saitoh183/medusa/home/status/'; was loaded over HTTPS, but requested an insecure stylesheet 'http://saitoh183.tiny.seedhost.eu/saitoh183/medusa/css/style.css?8335';. This request has been blocked; the content must be served over HTTPS.
```
Here are the RP settings that allow me to still navigate in http:
```
Include /etc/apache2/mods-available/proxy.load
Include /etc/apache2/mods-available/proxy_http.load
Include /etc/apache2/mods-available/headers.load
Include /etc/apache2/mods-available/ssl.load
 
ProxyRequests  Off
ProxyPreserveHost On
ProxyVia On
SSLProxyEngine on
 
ProxyPass /saitoh183/medusa http://127.0.0.1:19527/saitoh183/medusa
ProxyPassReverse /saitoh183/medusa http://127.0.0.1:19527/saitoh183/medusa
```

This is on a seedbox at seedhost.eu. I already reached out to there support and since this isnt a software installed by them, im on my own. I cant use nginx.

**Comment by p0psicles** [comment]
Before we really get started, what is your version of apache?

**Comment by saitoh183** [comment]
@p0psicles 
Server version: Apache/2.4.7 (Ubuntu)

**Comment by adaur** [comment]
You can already start by using https

```
ProxyPass /saitoh183/medusa https://127.0.0.1:19527/saitoh183/medusa
ProxyPassReverse /saitoh183/medusa https://127.0.0.1:19527/saitoh183/medusa
```

**Comment by saitoh183** [comment]
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /saitoh183/medusa/home.

Reason: Error reading from remote server

**Comment by adaur** [comment]
If you go on https://yourip:yourport is it working?

**Comment by saitoh183** [comment]
@adaur 
Traceback (most recent call last):
  File "/home28/saitoh183/software/Medusa/ext/tornado/web.py", line 1488, in _execute
    result = self.prepare()
  File "/home28/saitoh183/software/Medusa/ext/tornado/web.py", line 2223, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found

**Comment by saitoh183** [comment]
When i turn on HTTPS and Reverse Proxy in the config file, i get
500 Proxy Error

Proxy Error
The proxy server could not handle the request GET /saitoh183/medusa.
Reason: Error during SSL Handshake with remote server

**Comment by p0psicles** [comment]
Just to be sure. Youve not enabled https in Medusa right.?

**Comment by saitoh183** [comment]
i tried with it on and off.. When i enable only 

handle_reverse_proxy = 1

It spins for a long time and then i get a 502 Proxy Error

**Comment by saitoh183** [comment]
With both set to 0 and the change to the medusa.conf to https, i also get the 502

**Comment by saitoh183** [comment]
when ProxyPass /saitoh183/medusa https://127.0.0.1:19527/saitoh183/medusa

i get 502 

ProxyPass /saitoh183/medusa http://127.0.0.1:19527/saitoh183/medusa

i get blank page but http and http://ip:port/saitoh183/medusa work

**Comment by saitoh183** [comment]
@p0psicles 

any other ideas?

**Comment by p0psicles** [comment]
I'm setting up an apache proxy, to have a reference.

**Comment by saitoh183** [comment]
ok

**Comment by saitoh183** [comment]
Any luck?

**Comment by p0psicles** [comment]
Yeah, the meat of it, is that your missing this line:
```
RequestHeader set X-Forwarded-Proto "https" env=HTTPS
```
But i'll update the wiki with the usage of a VirtualHost, which I advice to always use icw apache.

**Comment by saitoh183** [comment]
@p0psicles 

still cant get it to work. I tried your config and replaced the values that needed to be replacing. I turned on RP and https in the config but Apache was failing to start. I got Apache to start with the following config:

```
<VirtualHost *:443>
Include /etc/apache2/mods-available/proxy.load
Include /etc/apache2/mods-available/proxy_http.load
Include /etc/apache2/mods-available/headers.load
Include /etc/apache2/mods-available/ssl.load
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyRequests Off

    # make sure we keep communicating over https
    RequestHeader set X-Forwarded-Proto "https" env=HTTPS

    ProxyPreserveHost On
    

    #SSLEngine on

    # Medusa proxy config
    ProxyPass /saitoh183/medusa/ws wss://127.0.0.1:19527/saitoh183/medusa/ws keepalive=On timeout=600 retry=1 acquire=3000

    # websockets
    ProxyPassReverse /saitoh183/medusa/ws wss://127.0.0.1:19527/saitoh183/medusa/ws
    ProxyPassReverseCookieDomain 127.0.0.1 %{HTTP:Host}

    # webserver
    ProxyPass /saitoh183/medusa https://localhost:19527/saitoh183/medusa keepalive=On timeout=600 retry=1 acquire=3000
    ProxyPassReverse /saitoh183/medusa https://localhost:19527/saitoh183/medusa


</VirtualHost>
```
but then i get

![image](https://user-images.githubusercontent.com/1534197/34958355-91703f86-f9ff-11e7-88a4-e172d01f2f16.png)

Apache logs:

```
[Mon Jan 15 20:24:02.029170 2018] [ssl:warn] [pid 14460] AH01916: Init: (tiny.seedhost.eu:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Mon Jan 15 20:24:02.042166 2018] [so:warn] [pid 14460] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:24:02.042230 2018] [so:warn] [pid 14460] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:24:02.042257 2018] [so:warn] [pid 14460] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:24:02.042274 2018] [so:warn] [pid 14460] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:24:02.042289 2018] [so:warn] [pid 14460] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:24:02.042329 2018] [so:warn] [pid 14460] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:24:02.042344 2018] [so:warn] [pid 14460] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:24:02.042360 2018] [so:warn] [pid 14460] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:24:02.042376 2018] [so:warn] [pid 14460] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:24:02.042402 2018] [so:warn] [pid 14460] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:24:02.042418 2018] [so:warn] [pid 14460] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:24:02.042436 2018] [so:warn] [pid 14460] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:24:02.042463 2018] [so:warn] [pid 14460] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:24:02.042506 2018] [so:warn] [pid 14460] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:24:02.042539 2018] [so:warn] [pid 14460] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:24:02.042569 2018] [so:warn] [pid 14460] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:24:02.042600 2018] [so:warn] [pid 14460] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:24:02.042645 2018] [so:warn] [pid 14460] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:24:02.042673 2018] [so:warn] [pid 14460] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:24:02.042699 2018] [so:warn] [pid 14460] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:24:02.042725 2018] [so:warn] [pid 14460] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:24:02.081567 2018] [ssl:warn] [pid 14473] AH01916: Init: (tiny.seedhost.eu:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Mon Jan 15 20:24:02.086565 2018] [mpm_prefork:notice] [pid 14473] AH00163: Apache/2.4.7 (Ubuntu) mod_scgi/1.13 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Jan 15 20:24:02.086587 2018] [core:notice] [pid 14473] AH00094: Command line: '/usr/sbin/apache2'

```

**Comment by saitoh183** [comment]
I also tried with this config

```
<VirtualHost *:443>
    LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
    LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so
    LoadModule proxy_wstunnel_module /usr/lib/apache2/modules/mod_proxy_wstunnel.so
    LoadModule ssl_module modules/mod_ssl.so
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyRequests Off

    # make sure we keep communicating over https
    RequestHeader set X-Forwarded-Proto "https" env=HTTPS

    ProxyRequests On
    ProxyPreserveHost Off
    #ServerName your_server_name

    SSLEngine on
    SSLCertificateFile /home28/saitoh183/software/medusa/server.crt
    SSLCertificateKeyFile /home28/saitoh183/software/medusa/server.key

    # Medusa proxy config
    ProxyPass /saitoh183/medusa/ws ws://127.0.0.1:19527/medusa/ws keepalive=On timeout=600 retry=1 acquire=3000

    # websockets
    ProxyPassReverse /saitoh183/medusa/ws ws://127.0.0.1:19527/saitoh183/medusa/ws
    ProxyPassReverseCookieDomain 127.0.0.1 %{HTTP:Host}

    # webserver
    ProxyPass /saitoh183/medusa http://localhost:19527/saitoh183/medusa keepalive=On timeout=600 retry=1 acquire=3000
    ProxyPassReverse /saitoh183/medusa http://localhost:19527/saitoh183/medusa
	
</VirtualHost>
```

Still get 

![image](https://user-images.githubusercontent.com/1534197/34958721-17ddf9b8-fa01-11e7-9e8f-85bee55b8dde.png)

```
[Mon Jan 15 20:32:30.899111 2018] [ssl:warn] [pid 19232] AH01909: RSA certificate configured for tiny.seedhost.eu:443 does NOT include an ID which matches the server name
[Mon Jan 15 20:32:30.910396 2018] [so:warn] [pid 19232] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:32:30.910428 2018] [so:warn] [pid 19232] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:32:30.910436 2018] [so:warn] [pid 19232] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:32:30.910507 2018] [so:warn] [pid 19232] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:32:30.910553 2018] [so:warn] [pid 19232] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:32:30.910570 2018] [so:warn] [pid 19232] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:32:30.910586 2018] [so:warn] [pid 19232] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:32:30.910603 2018] [so:warn] [pid 19232] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:32:30.910640 2018] [so:warn] [pid 19232] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:32:30.910673 2018] [so:warn] [pid 19232] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:32:30.910714 2018] [so:warn] [pid 19232] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:32:30.910749 2018] [so:warn] [pid 19232] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:32:30.910799 2018] [so:warn] [pid 19232] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:32:30.910830 2018] [so:warn] [pid 19232] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:32:30.910861 2018] [so:warn] [pid 19232] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:32:30.910892 2018] [so:warn] [pid 19232] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:32:30.910942 2018] [so:warn] [pid 19232] AH01574: module proxy_module is already loaded, skipping
[Mon Jan 15 20:32:30.910974 2018] [so:warn] [pid 19232] AH01574: module proxy_http_module is already loaded, skipping
[Mon Jan 15 20:32:30.911006 2018] [so:warn] [pid 19232] AH01574: module headers_module is already loaded, skipping
[Mon Jan 15 20:32:30.911038 2018] [so:warn] [pid 19232] AH01574: module ssl_module is already loaded, skipping
[Mon Jan 15 20:32:30.938547 2018] [ssl:warn] [pid 19233] AH01909: RSA certificate configured for tiny.seedhost.eu:443 does NOT include an ID which matches the server name
[Mon Jan 15 20:32:30.943315 2018] [mpm_prefork:notice] [pid 19233] AH00163: Apache/2.4.7 (Ubuntu) mod_scgi/1.13 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon Jan 15 20:32:30.943335 2018] [core:notice] [pid 19233] AH00094: Command line: '/usr/sbin/apache2'
```

**Comment by p0psicles** [comment]
No, use /saitoh183 as your web_root. In my example I used /medusa. You can't add one after the other. Medusa doesn't support that.
So if you would start medusa directly, you would access the home page by: `http://host:19527/saitoh183`. And that would redirect to for example: `http://host:19527/saitoh183/home`

**Comment by saitoh183** [comment]
hummm...i think that would be a problem because since this is a seedbox everything is under all the URLs are built https://host/saitoh183/<application name>
in HTTP its saitoh183.myhost.com/saitoh183/medusa (which loads just fine)

**Comment by p0psicles** [comment]
OK I need to reproduce that. Give me a day.

**Comment by saitoh183** [comment]
ok, do you need any other info from me to help with the reproduction?

**Comment by saitoh183** [comment]
@p0psicles

Made any headway?

**Comment by p0psicles** [comment]
Could you start giving me some more info on how this is setup with your provider? Your running your own apache right? How is it you need the extra subfolder?

**Comment by saitoh183** [comment]
Im with Seedhost and they use apache as webserver.

From what i saw when using there one-click install, it creates a conf file for apache in my home directory (/home28/saitoh183/.apache2/conf.d) and adds the web root /saitoh183/application_name in the application's config. from what i saw all of the conf file look the same in format

conf of sickrage:

```
Include /etc/apache2/mods-available/proxy.load
Include /etc/apache2/mods-available/proxy_http.load
Include /etc/apache2/mods-available/headers.load
Include /etc/apache2/mods-available/ssl.load

ProxyRequests  Off
ProxyPreserveHost On
ProxyVia On
SSLProxyEngine on

ProxyPass /saitoh183/sickrage http://127.0.0.1:11600/saitoh183/sickrage
ProxyPassReverse /saitoh183/sickrage http://127.0.0.1:11600/saitoh183/sickrage
```
So i just did the same for medusa but its not working. I have read permissions on the rest of the box. So if there is a config you want me to post, just give me the path you think it should be in and i can post it

**Comment by p0psicles** [comment]
And if you combine this config (change the sickrage values of course) and add the: `RequestHeader set X-Forwarded-Proto "https" env=HTTPS` ?

**Comment by p0psicles** [comment]
An alternative could be, using a virtualHost. For this you'll need to own a domain name. But then you could just access medusa using: www.myowndomain.com/medusa.

**Comment by saitoh183** [comment]
RequestHeader set X-Forwarded-Proto "https" env=HTTPS

didnt help

im used to nginx so apache virtualhost would be what you put in the wiki? but i had tried that but without the Servername because i didnt know what it would be...in there nginx config i found 

```
location /saitoh183/ {
            proxy_pass http://saitoh183.tiny.seedhost.eu;
        }
```

so would that be my server name?

**Comment by p0psicles** [comment]
I'll be on IRC in two hours

**Comment by saitoh183** [comment]
ok

**Comment by saitoh183** [comment]
@p0psicles 

Hi sorry i had to go out of town and couldnt get on to try out a fix. Any chance i could once again get help on this. Its really frustrating and support at Seedhost.eu wont help
