### ISSUE TITLE
[APP SUBMITTED]: TypeError: argument 2 to map() must support iteration

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#3661]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@c0f2ffe417e8075a26518969d9a563312c89115e
**Link to Log**: https://gist.github.com/4bb40e4873197ef94e574fff9082495b
### ERROR
<pre>
2018-01-24 14:35:16 ERROR    Thread-16 :: [c0f2ffe] Exception generated: argument 2 to map() must support iteration
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/c0f2ffe417e8075a26518969d9a563312c89115e/medusa/server/web/core/base.py#L280">medusa/server/web/core/base.py</a>", line 280, in async_call
    result = function(**kwargs)
  File "/home/pi/Medusa/<a href="../blob/c0f2ffe417e8075a26518969d9a563312c89115e/medusa/server/web/home/handler.py#L1051">medusa/server/web/home/handler.py</a>", line 1051, in pickManualSearch
    ep_objs.extend(series_obj.get_all_episodes(int(cached_result[b'season'])))
  File "/home/pi/Medusa/<a href="../blob/c0f2ffe417e8075a26518969d9a563312c89115e/medusa/tv/series.py#L613">medusa/tv/series.py</a>", line 613, in get_all_episodes
    sql_args.append(','.join(map(text_type, season)))
TypeError: argument 2 to map() must support iteration
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
Happen when trying to snatch: `Spies.Of.Warsaw.S01.720p.BluRay.X264-FLHD ` from omgwtfnzbs.

**Comment by duramato** [comment]
Actually, happens for _**all**_ manual snatch attempts.

**Comment by medariox** [comment]
You mean for all season manual snatch attempts. Fixed here: https://github.com/pymedusa/Medusa/pull/3664

**Comment by thisaintgonnahappen** [comment]
Hi There,
     I've run into this issue via a different method, but it appears the fix in the development branch is what's breaking my functionality vs master. I have been running on the dev branch and just recently started using 'Ombi'. Once I created a request for a show and to add a season, I got the following error:

2018-02-03 14:20:10 DEBUG    TORNADO :: [c807f43] API :: episode.setstatus: {'status': 'wanted', 'season': '1', 'tvdbid': '79349'}
2018-02-03 14:20:10 ERROR    TORNADO :: [c807f43] API :: 'argument 2 to map() must support iteration'
Traceback (most recent call last):
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 126, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 196, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/home/**********/Medusa/Medusa/medusa/server/api/v1/core.py", line 848, in run
    ep_list = show_obj.get_all_episodes(season=self.s)
  File "/home/**********/Medusa/Medusa/medusa/tv/series.py", line 613, in get_all_episodes
    sql_args.append(','.join(map(text_type, season)))
TypeError: argument 2 to map() must support iteration
2018-02-03 14:20:10 INFO     TORNADO :: [c807f43] 200 G

After some digging I saw that this section of the code had changed from the issue reported here. When I switched back to the master branch, I no longer saw the error (it didn't change the fact that all episodes were still in 'IGNORE' status, but that's something I'm still working to fix). Should this fix be reopened?
