### ISSUE TITLE
TD: IndexError: list index out of range

### ISSUE THREAD

**Issue by fernandog** [pymedusa/Medusa#3670]
2018-01-25 20:40:04 ERROR    FINDPROPERS :: [TorrentDay] :: [ad04c6b] Failed parsing provider.
Traceback (most recent call last):
  File "/home/osmc/Medusa/medusa/providers/torrent/html/torrentday.py", line 158, in parse
    name = cells[labels.index('name')]
IndexError: list index out of range
2018-01-25 20:40:03 INFO     FINDPROPERS :: [TorrentDay] :: [ad04c6b] Searching for any new PROPER releases from TorrentDay

@p0psicles @OmgImAlexis

**Comment by angrywar** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@0fe5730f8b9a6b9209720549c7853648dd4a486b
**Link to Log**: https://gist.github.com/4c68ad4ebd8e5173d6d5b16f89eb1cba
### ERROR
<pre>
2018-01-26 00:24:43 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: [0fe5730] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\torrentday.py", line 182, in parse
    pubdate_raw = name.find('div').get_text(strip=True).split('|')[1].strip()
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Tnx for the report. Will fix today

**Comment by fernandog** [comment]
Thanks @p0psicles

**Comment by Rumia** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/2be693b9230a6d9f54b7090e753fd634
### ERROR
<pre>
2018-02-23 20:59:53 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Newpct] :: [ccbc0ce] Failed parsing provider.
Traceback (most recent call last):
  File "/home/aubi/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L140">medusa/providers/torrent/html/newpct.py</a>", line 140, in parse
    torrent_content = self._get_content(anchor.get('href'), mode)
  File "/home/aubi/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L213">medusa/providers/torrent/html/newpct.py</a>", line 213, in _get_content
    return self._parse_download(torrent_content, mode)
  File "/home/aubi/.medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L227">medusa/providers/torrent/html/newpct.py</a>", line 227, in _parse_download
    pubdate_raw = spans[2].contents[1].strip()
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by jcarlos001** [comment]
### INFO
**Python Version**: `2.7.14 (default, Jan  6 2018, 18:53:10) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.1-STABLE-amd64-64bit-ELF`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/8be934a2f6a0a6886af00a84f3f019bc
### ERROR
<pre>
2018-02-24 06:55:42 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Newpct] :: [ccbc0ce] Failed parsing provider.
Traceback (most recent call last):
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L140">medusa/providers/torrent/html/newpct.py</a>", line 140, in parse
    torrent_content = self._get_content(anchor.get('href'), mode)
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L213">medusa/providers/torrent/html/newpct.py</a>", line 213, in _get_content
    return self._parse_download(torrent_content, mode)
  File "/usr/local/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L227">medusa/providers/torrent/html/newpct.py</a>", line 227, in _parse_download
    pubdate_raw = spans[2].contents[1].strip()
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by aferpa94** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.13.0-36-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/7efe3145fc93e72e47641b0abe22565f
### ERROR
<pre>
2018-02-25 12:40:21 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Newpct] :: [ccbc0ce] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L140">medusa/providers/torrent/html/newpct.py</a>", line 140, in parse
    torrent_content = self._get_content(anchor.get('href'), mode)
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L213">medusa/providers/torrent/html/newpct.py</a>", line 213, in _get_content
    return self._parse_download(torrent_content, mode)
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L227">medusa/providers/torrent/html/newpct.py</a>", line 227, in _parse_download
    pubdate_raw = spans[2].contents[1].strip()
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Already fixed in develop

**Comment by trancen** [comment]
### INFO
**Python Version**: `2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]`
**Operating System**: `Linux-2.6.32-042stab108.8-x86_64-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/94629d439ff5f6aa1f1cc3cf8b6f9656
### ERROR
<pre>
2018-02-26 13:26:09 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Newpct] :: [ccbc0ce] Failed parsing provider.
Traceback (most recent call last):
  File "/var/www/sickrage/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L140">medusa/providers/torrent/html/newpct.py</a>", line 140, in parse
    torrent_content = self._get_content(anchor.get('href'), mode)
  File "/var/www/sickrage/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L213">medusa/providers/torrent/html/newpct.py</a>", line 213, in _get_content
    return self._parse_download(torrent_content, mode)
  File "/var/www/sickrage/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/providers/torrent/html/newpct.py#L227">medusa/providers/torrent/html/newpct.py</a>", line 227, in _parse_download
    pubdate_raw = spans[2].contents[1].strip()
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by aerandir83** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-4.2.8-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/094d4274d44d54a5313bac96f5748bf6
### ERROR
<pre>
2018-03-01 00:39:07 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Newpct] :: [ccbc0ce] Failed parsing provider.
Traceback (most recent call last):
  File "/app/medusa/medusa/providers/torrent/html/newpct.py", line 140, in parse
    torrent_content = self._get_content(anchor.get('href'), mode)
  File "/app/medusa/medusa/providers/torrent/html/newpct.py", line 213, in _get_content
    return self._parse_download(torrent_content, mode)
  File "/app/medusa/medusa/providers/torrent/html/newpct.py", line 227, in _parse_download
    pubdate_raw = spans[2].contents[1].strip()
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
