### ISSUE TITLE
Error keeps occurring when adding/searching for shows and episode

### ISSUE THREAD

**Issue by peterbrinck** [pymedusa/Medusa#3683]
**Branch/Commit:** master
**OS:** Debian 9.3
**What you did:** Added a new show/episode AND/OR searching for one
**Logs:**
```
2018-01-29 12:55:22 ERROR    SHOWQUEUE-ADD :: [bd08325] Error loading IMDb info: unable to open database file
Traceback (most recent call last):
  File "/home1/**********/.apps/medusa/medusa/medusa/show_queue.py", line 533, in run
    self.show.load_imdb_info()
  File "/home1/**********/.apps/medusa/medusa/medusa/tv/series.py", line 1572, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "/home1/**********/.apps/medusa/medusa/ext/imdbpie/imdbpie.py", line 52, in get_title
    '/title/{0}/auxiliary'.format(imdb_id)
  File "/home1/**********/.apps/medusa/medusa/ext/imdbpie/imdbpie.py", line 288, in _get_resource
    return self._get(url=url)['resource']
  File "/home1/**********/.apps/medusa/medusa/ext/imdbpie/imdbpie.py", line 293, in _get
    headers.update(self.get_auth_headers(path))
  File "/home1/**********/.apps/medusa/medusa/ext/imdbpie/auth.py", line 113, in get_auth_headers
    creds, soon_expires = self._creds_soon_expiring()
  File "/home1/**********/.apps/medusa/medusa/ext/imdbpie/auth.py", line 98, in _creds_soon_expiring
    creds = self._get_creds()
  File "/home1/**********/.apps/medusa/medusa/ext/imdbpie/auth.py", line 85, in _get_creds
    with diskcache.Cache(directory=self._cachedir) as cache:
  File "/home1/**********/.apps/medusa/medusa/ext/diskcache/core.py", line 380, in __init__
    sql('CREATE TABLE IF NOT EXISTS Settings ('
OperationalError: unable to open database file
```

**Comment by medariox** [comment]
This is almost certainly a permissions issue. Check that the user you are running Medusa with has the rights to write/read to Python's tempfile directory. See: https://docs.python.org/2/library/tempfile.html#tempfile.gettempdir

**Comment by peterbrinck** [comment]
Just tested, as far as I can see, the user has read/write permissions to the temp dir, which is `/tmp` according to ``` tempfile.gettempdir() ```

**Comment by medariox** [comment]
Are you sure you are running Medusa (Python) with the same user?

**Comment by peterbrinck** [comment]
Under `Help & info` it says the same user as I'm testing with - But I don't know if that's the user running it or just the user logged in?

**Comment by medariox** [comment]
That's very strange. Try deleting anything Medusa related in your `/tmp` directory. Maybe some files were created by another user?

**Comment by labrys** [comment]
Check if your `/tmp` directory is full. Run `df /tmp`

**Comment by peterbrinck** [comment]
As far as I can see, nothing related to Medusa is in the `/tmp` directory at the moment
Also, the `/tmp` directory is not full

**Comment by medariox** [comment]
Don't know what to do about this.

**Comment by sharkykh** [comment]
@peterbrinck 
As a temporary solution, you can try this:
https://github.com/pymedusa/Medusa/issues/4689#issuecomment-407377717

Run (as the same user running Medusa):
```
python -c "import tempfile, os.path; print os.path.join(tempfile.gettempdir(), 'cache.db')"
```
And try removing that file.

**Comment by medariox** [comment]
Fixed in develop with: https://github.com/pymedusa/Medusa/pull/4745
