### ISSUE TITLE
AttributeError: 'int' object has no attribute 'indexer_name'

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#3731]
```
curl 'http://localhost:8081/api/v2/series' -H 'Pragma: no-cache' -H 'Origin: http://localhost:4000' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-AU,en;q=0.9,en-GB;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36' -H 'content-type: application/json' -H 'accept: application/json' -H 'Cache-Control: no-cache' -H 'authorization: Bearer JWT_TOKEN_WAS_HERE' -H 'Connection: keep-alive' -H 'Referer: http://localhost:4000/' -H 'DNT: 1' --compressed
```

```
Traceback (most recent call last):
  File "/Users/xo/code/Medusa/ext/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/xo/code/Medusa/medusa/server/api/v2/series.py", line 43, in get
    data = [s.to_json(detailed=detailed) for s in Series.find_series(predicate=filter_series)]
  File "/Users/xo/code/Medusa/medusa/tv/series.py", line 2020, in to_json
    data['cache']['poster'] = self.poster
  File "/Users/xo/code/Medusa/medusa/tv/series.py", line 527, in poster
    return image_cache.get_artwork(img_type, self.series_id)
  File "/Users/xo/code/Medusa/medusa/image_cache.py", line 111, in get_artwork
    location = get_path(img_type, series_obj)
  File "/Users/xo/code/Medusa/medusa/image_cache.py", line 94, in get_path
    location = _cache_dir(series_obj)
  File "/Users/xo/code/Medusa/medusa/image_cache.py", line 71, in _cache_dir
    return os.path.abspath(os.path.join(app.CACHE_DIR, 'images', series_obj.indexer_name))
AttributeError: 'int' object has no attribute 'indexer_name'
```

**Comment by medariox** [comment]
Fixed in develop.
