### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'dict' object has no attribute 'format'

### ISSUE THREAD

**Issue by iioodii** [pymedusa/Medusa#3736]
### INFO
**Python Version**: `2.7.13 (default, Dec 19 2016, 02:32:04) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@bd0832551d836713481dd0a93f4118372bb5d963
**Link to Log**: https://gist.github.com/77f0b1d85cc8099b88389e504ca9ac34
### ERROR
<pre>
2018-02-10 06:12:09 ERROR    SNATCHQUEUE-MANUALSNATCH-328634 :: [bd08325] BraceMessage string formatting failed. Using representation instead.
  File "/usr/local/python/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/local/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/search/queue.py#L487">SickBeard/medusa/search/queue.py</a>", line 487, in run
    self.success = snatch_episode(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/search/core.py#L159">SickBeard/medusa/search/core.py</a>", line 159, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/clients/torrent/generic.py#L256">SickBeard/medusa/clients/torrent/generic.py</a>", line 256, in send_torrent
    r_code = self._add_torrent_file(result)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/clients/torrent/download_station_client.py#L149">SickBeard/medusa/clients/torrent/download_station_client.py</a>", line 149, in _add_torrent_file
    return self._check_response()
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/clients/torrent/download_station_client.py#L77">SickBeard/medusa/clients/torrent/download_station_client.py</a>", line 77, in _check_response
    log.info(self.error_map.get(error_code, jdata))
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/logger/adapters/style.py#L90">SickBeard/medusa/logger/adapters/style.py</a>", line 90, in log
    self.logger.log(level, msg, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1489, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/local/python/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/logger/__init__.py#L546">SickBeard/medusa/logger/__init__.py</a>", line 546, in format
    msg = super(CensoredFormatter, self).format(record)
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/local/python/lib/python2.7/logging/__init__.py", line 325, in getMessage
    msg = str(self.msg)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/init/logconfig.py#L80">SickBeard/medusa/init/logconfig.py</a>", line 80, in __str__
    result = text_type(self.fmt)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/logger/adapters/style.py#L49">SickBeard/medusa/logger/adapters/style.py</a>", line 49, in __str__
    ''.join(traceback.format_stack()),
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/bd0832551d836713481dd0a93f4118372bb5d963/SickBeard/medusa/logger/adapters/style.py#L37">SickBeard/medusa/logger/adapters/style.py</a>", line 37, in __str__
    return self.msg.format(*args, **kwargs)
AttributeError: 'dict' object has no attribute 'format'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed in develop.
