### ISSUE TITLE
Can't mark old show archived

### ISSUE THREAD

**Issue by bobbysteel** [pymedusa/Medusa#3747]
Problem: one episode 10+ seasons ago keeps re-downloading over and over. Trying to mark as ignored or Archived gives white screen (UI crash) and following logs:

(the build is master from today, running on Docker)
```
2018-02-11 12:25:22 ERROR    Thread-108 :: [bd08325] Exception generated: setStatus() got an unexpected keyword argument 'show'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 280, in async_call
    result = function(**kwargs)
TypeError: setStatus() got an unexpected keyword argument 'show'
2018-02-11 12:25:19 ERROR    Thread-106 :: [bd08325] Exception generated: getManualSearchStatus() got an unexpected keyword argument 'show'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 280, in async_call
    result = function(**kwargs)
TypeError: getManualSearchStatus() got an unexpected keyword argument 'show'
2018-02-11 12:24:49 ERROR    Thread-109 :: [bd08325] Exception generated: getSeasonSceneExceptions() got an unexpected keyword argument 'indexer_id'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 280, in async_call
    result = function(**kwargs)
TypeError: getSeasonSceneExceptions() got an unexpected keyword argument 'indexer_id'
2018-02-11 12:24:47 ERROR    Thread-107 :: [bd08325] Exception generated: getManualSearchStatus() got an unexpected keyword argument 'show'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 280, in async_call
    result = function(**kwargs)
TypeError: getManualSearchStatus() got an unexpected keyword argument 'show'
```

**Comment by p0psicles** [comment]
In the latest medusa update routes have been changed.
This means that you need to make sure medusa is fully restarted. And that you have closed all old tabs in your webbrowser.

**Comment by bobbysteel** [comment]
it's dockerized. what does browser have to do with it?

**Comment by bobbysteel** [comment]
Weird. I tried an explicit logout and login again and it seems to work. Odd. Thanks @p0psicles
