### ISSUE TITLE
medusa qnap start error

### ISSUE THREAD

**Issue by Blisk** [pymedusa/Medusa#3748]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:*qnap ARM*
**What you did:*start medusa*
**What happened:*error*
**What you expected:**
**Logs:**
```
PASTE LOGS HERE
[/share/CACHEDEV1_DATA/.qpkg/Medusa] # ./Medusa.sh start
file exists
ln: /opt/Medusa/Medusa: cannot overwrite directory
mediainfo: error while loading shared libraries: librtmp.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "SickBeard.py", line 4, in <module>
    from medusa.__main__ import main
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/__init__.py", line 23, in <module>
    initialize()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/init/__init__.py", line 29, in initialize
    _configure_knowit()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/init/__init__.py", line 163, in _configure_knowit
    api.initialize({'mediainfo': suggested_path})
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/lib/knowit/api.py", line 27, in initialize
    available_providers[name] = provider_cls(config, context.get(name) or config.general.get(name))
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/lib/knowit/providers/mediainfo.py", line 318, in __init__
    self.executor = MediaInfoExecutor.get_executor_instance(suggested_path)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/lib/knowit/providers/mediainfo.py", line 101, in get_executor_instance
    executor = exec_cls.create(os_family, suggested_path)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/lib/knowit/providers/mediainfo.py", line 129, in create
    check_output([candidate, '--version'])
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'mediainfo', u'--version']' returned non-zero exit status 127

```

**Comment by medariox** [comment]
Try installing/removing mediainfo?
