### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by ztaale** [pymedusa/Medusa#3762]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-5-amd64-x86_64-with-debian-9.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@ccbc0ce9a2d3977a71bde03e29be503464ebe3cd
**Link to Log**: https://gist.github.com/dfa18f49ecff2e7a4a6a20aafb2a2299
### ERROR
<pre>
2018-02-12 23:34:53 ERROR    SHOWQUEUE-ADD :: [ccbc0ce] Error searching dir for episodes: Show episode search exception, could not get any episodes. Did a season [3] search. Exception: ReadTimeout
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/show_queue.py#L569">medusa/show_queue.py</a>", line 569, in run
    self.show.load_episodes_from_dir()
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/tv/series.py#L931">medusa/tv/series.py</a>", line 931, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/tv/series.py#L1397">medusa/tv/series.py</a>", line 1397, in make_ep_from_file
    root_ep.create_meta_files()
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/tv/episode.py#L1108">medusa/tv/episode.py</a>", line 1108, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/tv/episode.py#L1131">medusa/tv/episode.py</a>", line 1131, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/metadata/generic.py#L326">medusa/metadata/generic.py</a>", line 326, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/tv/episode.py#L679">medusa/tv/episode.py</a>", line 679, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L223">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 223, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/opt/medusa/<a href="../blob/ccbc0ce9a2d3977a71bde03e29be503464ebe3cd/medusa/indexers/tvdbv2/tvdbv2_api.py#L303">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 303, in _query_series
    (search_type='full' if not aired_season else 'season {season}'.format(season=aired_season), e=e.reason)
IndexerShowIncomplete: Show episode search exception, could not get any episodes. Did a season [3] search. Exception: ReadTimeout
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by TTLucian** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/6f54c5dc6c13ed32a186208bd3df93a8
### ERROR
<pre>
2018-03-17 18:59:17 ERROR    SHOWQUEUE-ADD :: [d6eb72d] 332331 Error while loading information from indexer TVDBv2. Error: "Show search failed in getting a result with reason: ReadTimeout\nHTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30) (0)"
Traceback (most recent call last):
  File "C:\Data\Medusa\Medusa\medusa\show_queue.py", line 379, in run
    s = indexer_api[self.indexer_id]
  File "C:\Data\Medusa\Medusa\medusa\indexers\indexer_base.py", line 398, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "C:\Data\Medusa\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 585, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "C:\Data\Medusa\Medusa\medusa\indexers\tvdbv2\fallback.py", line 110, in __call__
    return self.func(*args, **kwargs)
  File "C:\Data\Medusa\Medusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 200, in _get_show_by_id
    reason=error.reason, status=error.status
IndexerShowNotFound: Show search failed in getting a result with reason: ReadTimeout
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30) (0)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by abeloin** [comment]
@TTLucian thetvdb.com api is currently having some issue.

For more info, see: https://forums.thetvdb.com/viewtopic.php?f=4&t=39984&start=30

**Comment by DDA78** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 16:23:38) [GCC 6.4.0]`
**Operating System**: `Linux-4.4.71+-armv7l-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/0d86e132d87c282b7820683d88e80d07
### ERROR
<pre>
2018-03-30 01:19:51 ERROR    SHOWQUEUE-REFRESH :: [d6eb72d] 281623: Error while refreshing show Madam Secretary. Error: Show episode search exception, could not get any episodes. Did a season [2] search. Exception: ReadTimeout
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 635, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1753, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 931, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1397, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/app/medusa/medusa/tv/episode.py", line 1108, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/app/medusa/medusa/tv/episode.py", line 1131, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/app/medusa/medusa/metadata/generic.py", line 326, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/app/medusa/medusa/tv/episode.py", line 679, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 223, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/app/medusa/medusa/indexers/tvdbv2/fallback.py", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 303, in _query_series
    (search_type='full' if not aired_season else 'season {season}'.format(season=aired_season), e=e.reason)
IndexerShowIncomplete: Show episode search exception, could not get any episodes. Did a season [2] search. Exception: ReadTimeout
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ztaale** [comment]
### INFO
**Python Version**: `2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-43-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/b846bef728004f6f4a480dd1b1cc7b74
### ERROR
<pre>
2019-02-23 02:33:06 ERROR    SHOWQUEUE-ADD :: [918cfe7] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/logger/adapters/style.py#L53">medusa/logger/adapters/style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: 'season'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/logger/adapters/style.py#L60">medusa/logger/adapters/style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/show_queue.py#L619">medusa/show_queue.py</a>", line 619, in run
    self.show.load_episodes_from_dir()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/series.py#L1006">medusa/tv/series.py</a>", line 1006, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/series.py#L1372">medusa/tv/series.py</a>", line 1372, in make_ep_from_file
    root_ep.create_meta_files()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/episode.py#L1110">medusa/tv/episode.py</a>", line 1110, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/episode.py#L1133">medusa/tv/episode.py</a>", line 1133, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/metadata/generic.py#L365">medusa/metadata/generic.py</a>", line 365, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/episode.py#L698">medusa/tv/episode.py</a>", line 698, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/indexers/tvdbv2/tvdbv2_api.py#L222">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 222, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/indexers/tvdbv2/fallback.py#L112">medusa/indexers/tvdbv2/fallback.py</a>", line 112, in __call__
    return self.func(*args, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/indexers/tvdbv2/tvdbv2_api.py#L302">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 302, in _query_series
    (search_type='full' if not aired_season else 'season {season}'.format(season=aired_season), e=e.reason)
IndexerShowIncomplete: Show episode search exception, could not get any episodes. Did a season [9] search. Exception: ReadTimeout
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ztaale** [comment]
### INFO
**Python Version**: `2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-43-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/0e297ca7560779e456e65fd84d46d9ed
### ERROR
<pre>
2019-02-23 02:33:06 ERROR    SHOWQUEUE-ADD :: [918cfe7] Error searching dir for episodes: Show episode search exception, could not get any episodes. Did a season [9] search. Exception: ReadTimeout
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/show_queue.py#L619">medusa/show_queue.py</a>", line 619, in run
    self.show.load_episodes_from_dir()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/series.py#L1006">medusa/tv/series.py</a>", line 1006, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/series.py#L1372">medusa/tv/series.py</a>", line 1372, in make_ep_from_file
    root_ep.create_meta_files()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/episode.py#L1110">medusa/tv/episode.py</a>", line 1110, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/episode.py#L1133">medusa/tv/episode.py</a>", line 1133, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/metadata/generic.py#L365">medusa/metadata/generic.py</a>", line 365, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/episode.py#L698">medusa/tv/episode.py</a>", line 698, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/indexers/tvdbv2/tvdbv2_api.py#L222">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 222, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/indexers/tvdbv2/fallback.py#L112">medusa/indexers/tvdbv2/fallback.py</a>", line 112, in __call__
    return self.func(*args, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/indexers/tvdbv2/tvdbv2_api.py#L302">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 302, in _query_series
    (search_type='full' if not aired_season else 'season {season}'.format(season=aired_season), e=e.reason)
IndexerShowIncomplete: Show episode search exception, could not get any episodes. Did a season [9] search. Exception: ReadTimeout
HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
