### ISSUE TITLE
[APP SUBMITTED]: gaierror: [Errno -3] Try again

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#3764]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.13-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/212ab4678c35e5302bdeaf6e01179859
### ERROR
<pre>
2018-02-13 01:38:28 ERROR    CHECKVERSION :: [1a8dc66] Environment error: [Errno -3] Try again
Traceback (most recent call last):
  File "/app/medusa/medusa/scheduler.py", line 90, in run
    self.action.run(self.force)
  File "/app/medusa/medusa/version_checker.py", line 63, in run
    self.list_remote_branches()
  File "/app/medusa/medusa/version_checker.py", line 353, in list_remote_branches
    app.GIT_REMOTE_BRANCHES = self.updater.list_remote_branches()
  File "/app/medusa/medusa/version_checker.py", line 990, in list_remote_branches
    gh = get_github_repo(app.GIT_ORG, app.GIT_REPO)
  File "/app/medusa/medusa/github_client.py", line 95, in get_github_repo
    return gh.get_organization(organization).get_repo(repo)
  File "/app/medusa/ext/github/MainClass.py", line 198, in get_organization
    "/orgs/" + login
  File "/app/medusa/ext/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/medusa/ext/github/Requester.py", line 213, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/ext/github/Requester.py", line 252, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/app/medusa/ext/github/Requester.py", line 277, in __requestRaw
    requestHeaders
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -3] Try again
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Please update, this should already be fixed.

**Comment by p0psicles** [comment]
Ooh I don't know. This is the GitHub lib. Not our request session.
