### ISSUE TITLE
Medusa won't start on synology if all settings and shows are set (fresh install work)

### ISSUE THREAD

**Issue by Galork** [pymedusa/Medusa#3804]
Branch/Commit: master
OS: Synology DS213 with DSM 6.1.5-15254
What you did: upgrade Python to 2.7.14-18 and Medusa to 0.2.0
What happened: Medusa failed to start. If I try to reinstall it, it works, but each time I set up back my settings manually or using the restore option from medusa it doesn't want to start anymore and I have the error below
What you expected: Medusa working

Logs:
Sat Feb 24 00:59:15 CET 2018
Starting sickbeard-custom command /volume1/@appstore/sickbeard-custom/env/bin/python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.pid --config /volume1/@appstore/sickbeard-custom/var/config.ini --datadir /volume1/@appstore/sickbeard-custom/var/ 
/var/packages/python/target/lib/python2.7/urllib.py:1298: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py", line 7, in <module>
    main()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 2151, in main
    application.start(sys.argv[1:])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 333, in start
    self.initialize(console_logging=self.console_logging)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/__main__.py", line 1083, in initialize
    app_logger.rebuild_censored_list()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/logger/__init__.py", line 88, in rebuild_censored_list
    results |= {quote(item) for item in results}
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/logger/__init__.py", line 88, in <setcomp>
    results |= {quote(item) for item in results}
  File "/var/packages/python/target/lib/python2.7/urllib.py", line 1298, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe9'

Thanks for your future help, and keep doing good job

Edit : I'm french, sorry for bad english

**Comment by abeloin** [comment]
Hello,
Look in your config.ini for the letter é.
Not sure why it would failed on that, maybe a codepage convertion issue?
----
Salut,
Regarde dans ton fichier config.ini pour une ligne qui contient la lettre é. Ça doit être relié à une erreur lors de la conversion du code page du Synology à Unicode

**Comment by Galork** [comment]
Hello,

Thanks! It's working now :D I changed one of my torrent password recently and add é inside, that's why the problem started ^^

Thanks again!
