### ISSUE TITLE
Newpct provider broken

### ISSUE THREAD

**Issue by ligreman** [pymedusa/Medusa#3810]
It seems that newpct has changed something. Now the provider can't find any torrent. It throws this error:

```
2018-02-25 21:23:57 ERROR    SEARCHQUEUE-MANUAL-1412 :: [Newpct] :: [ccbc0ce] Failed parsing provider.
Traceback (most recent call last):
  File "R:\Medusa\medusa\providers\torrent\html\newpct.py", line 151, in parse
    torrent_info = self._parse_download(row, mode)
  File "R:\Medusa\medusa\providers\torrent\html\newpct.py", line 227, in _parse_download
    pubdate_raw = spans[2].contents[1].strip()
IndexError: list index out of range
```

Thanks!

**Comment by p0psicles** [comment]
Already fixed in develop.
Where finishing some last bugfixes to go for a release to master.
