### ISSUE TITLE
OSError handling on invalid filename (tab character)

### ISSUE THREAD

**Issue by EraYaN** [pymedusa/Medusa#3839]
**Branch/Commit:**
Branch: master
Commit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
Version: v0.2.1
**OS:**
Windows Server 2016
**What you did:**
Post processing
**What happened:**
File got removed from download folder but did not show up in Correct place, because OSError is not catch as a failure state for the post processing.
**What you expected:**
Correct file movement (stripping of bad chars from filename)
**Logs:**
```
2018-03-07 20:42:22 ERROR    Thread-34 :: [d6eb72d] OSError: 
Traceback (most recent call last):
  File "C:\PythonPrograms\Medusa\medusa\helpers\__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "C:\PythonPrograms\Medusa\lib\shutil_custom\__init__.py", line 42, in copyfile_custom
    fout = os.open(dst, WRITE_FLAGS)
OSError: [Errno 22] Invalid argument
2018-03-07 20:42:22 ERROR    Thread-34 :: [d6eb72d] Unable to write file to D:\media\Videos\TV Shows\Ask Us Anything\Season 01\Ask Us Anything - S01E98 - Episode 98 with Jung-soo & Ha Yeon-soo	.nfo: Environment error: [Errno 22] Invalid argument: u'D:\\media\\Videos\\TV Shows\\Ask Us Anything\\Season 01\\Ask Us Anything - S01E98 - Episode 98 with Jung-soo & Ha Yeon-soo\t.nfo'
```

A quick fix would be to strip and illegal characters from file names. In this case the TheTVDB episode name ended in a tab character. Proper exception handling would probably be a better fix.

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/4351
