### ISSUE TITLE
[APP SUBMITTED]: TypeError: tuple indices must be integers, not unicode

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#3850]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.13-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/0d5552591a518974da995a25a335ecaa
### ERROR
<pre>
2018-03-11 15:02:39 ERROR    TORRENTCHECKER :: [1a8dc66] Exception while checking torrent status.
Traceback (most recent call last):
  File "/app/medusa/medusa/torrent_checker.py", line 41, in run
    client.remove_ratio_reached()
  File "/app/medusa/medusa/clients/torrent/deluge_client.py", line 473, in remove_ratio_reached
    info_hash_to_remove = read_torrent_status(torrent_data)
  File "/app/medusa/medusa/clients/torrent/deluge_client.py", line 72, in read_torrent_status
    ratio_limit=torrent['stop_ratio'],
TypeError: tuple indices must be integers, not unicode
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3853

**Comment by OmgImAlexis** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.13-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/a0d84c32ff5c6dc66da2a56d9a1efdae
### ERROR
<pre>
2018-03-12 00:02:47 ERROR    TORRENTCHECKER :: [1a8dc66] Exception while checking torrent status.
Traceback (most recent call last):
  File "/app/medusa/medusa/torrent_checker.py", line 41, in run
    client.remove_ratio_reached()
  File "/app/medusa/medusa/clients/torrent/deluge_client.py", line 473, in remove_ratio_reached
    info_hash_to_remove = read_torrent_status(torrent_data)
  File "/app/medusa/medusa/clients/torrent/deluge_client.py", line 72, in read_torrent_status
    ratio_limit=torrent['stop_ratio'],
TypeError: tuple indices must be integers, not unicode
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Aste88** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-3.16.0-5-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/e2c32e06bf60cfca47e9617490a618c9
### ERROR
<pre>
2018-04-09 20:24:27 ERROR    TORRENTCHECKER :: [d6eb72d] Exception while checking torrent status.
Traceback (most recent call last):
  File "/app/medusa/medusa/torrent_checker.py", line 41, in run
    client.remove_ratio_reached()
  File "/app/medusa/medusa/clients/torrent/**********_client.py", line 473, in remove_ratio_reached
    info_hash_to_remove = read_torrent_status(torrent_data)
  File "/app/medusa/medusa/clients/torrent/**********_client.py", line 72, in read_torrent_status
    ratio_limit=torrent['stop_ratio'],
TypeError: tuple indices must be integers, not unicode
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
