### ISSUE TITLE
Manual subtitle search

### ISSUE THREAD

**Issue by Dufman** [pymedusa/Medusa#3858]
**Branch/Commit:**

Branch: master
Commit: d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
Version: v0.2.1
Database: 44.9

**OS:**
DSM 5.2

**What you did:**
Try to perform a manual subtitle search with different subtitle plugin enabled with different episode

**What happened:**
Nothing

**What you expected:**
A list of matching subtitle

**Logs:**
```
PASTE LOGS HERE
2018-03-13 08:39:52 ERROR    Thread-18 :: [d6eb72d] Exception generated: 'NoneType' object has no attribute 'library'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 283, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/home/handler.py", line 2287, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/subtitles.py", line 331, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/dogpile/cache/region.py", line 984, in set
    self.backend.set(key, self._value(value))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/dogpile/cache/backends/file.py", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/local/python/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/local/python/lib/python2.7/anydbm.py", line 71, in open
    result=whichdb(file)
  File "/usr/local/python/lib/python2.7/whichdb.py", line 35, in whichdb
    if not (dbm.library == "GNU gdbm" and sys.platform == "os2emx"):
AttributeError: 'NoneType' object has no attribute 'library'

**Comment by Dufman** [comment]
Hello,

Any news regarding this issue?
Thanks

**Comment by p0psicles** [comment]
@medariox wasn't this fixed some time ago?
@Dufman why still on such an old version DSM?

**Comment by Dufman** [comment]
It's an xpenology install and I'm afraid of loosing all my configuration... :-P

**Comment by sharkykh** [comment]
@Dufman 
Just to be clear: I don't have a Synology DS.
If you're still on version 5.2, and if your still using/want to use Medusa...
Looks like your OS is missing the `gdbm` and/or `python-gdbm` package.

http://www.hang321.net/2015/06/09/debian-chroot-on-dsm-5-2/
If you install that you can have access to the Debian shell,
with it you should be able to install the missing packages.

https://packages.debian.org/wheezy/libgdbm3
https://packages.debian.org/wheezy/python-gdbm

I don't know about the specifics of installing packages on Debian,
but I do know from the error that Python can't find this package, and that's what's causing the issue.
