### ISSUE TITLE
[APP SUBMITTED]: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/Medusa#3870]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-4.14.11-feral-x86_64-with-debian-8.10`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/122e4ed719471a1c9052d17cf239277e
### ERROR
<pre>
2018-03-17 09:52:59 ERROR    SEARCHQUEUE-FORCED-263365 :: [d6eb72d] Deluge: Failed Sending Torrent
Traceback (most recent call last):
  File "/media/sdq1/home/**********/.sickrage/medusa/clients/torrent/generic.py", line 256, in send_torrent
    r_code = self._add_torrent_file(result)
  File "/media/sdq1/home/**********/.sickrage/medusa/clients/torrent/deluge_client.py", line 247, in _add_torrent_file
    result.hash = self.response.json()['result']
  File "/media/sdq1/home/**********/.sickrage/ext/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
Should be fixed now on `develop`.
