### ISSUE TITLE
Exception generated: invalid literal for int() with base 10: 'false'

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#3873]
```
2018-03-18 12:11:29 ERROR    Thread-17 :: [e11c71e] Exception generated: invalid literal for int() with base 10: 'false'
Traceback (most recent call last):
  File "/Users/xo/code/Medusa/medusa/server/web/core/base.py", line 281, in async_call
    result = function(**kwargs)
  File "/Users/xo/code/Medusa/medusa/server/web/core/file_browser.py", line 23, in index
    return json.dumps(list_folders(path, True, bool(int(includeFiles))))
ValueError: invalid literal for int() with base 10: 'false'
```

@p0psicles can we allow this to use Booleans instead of 0/1?

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3900
