### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3c9ba70150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

### ISSUE THREAD

**Issue by ztaale** [pymedusa/Medusa#3874]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-5-amd64-x86_64-with-debian-9.3`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/32db637ae5c076ae690c6a16d6e09726
### ERROR
<pre>
2018-03-18 03:15:22 ERROR    SHOWQUEUE-REFRESH :: [d6eb72d] 289108: Error while refreshing show American Crime Story. Error: Show episode search exception, could not get any episodes. Did a season [2] search. Exception: ConnectionError
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3c9ba70150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/show_queue.py#L635">medusa/show_queue.py</a>", line 635, in run
    self.show.refresh_dir()
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/series.py#L1753">medusa/tv/series.py</a>", line 1753, in refresh_dir
    self.load_episodes_from_dir()
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/series.py#L931">medusa/tv/series.py</a>", line 931, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/series.py#L1397">medusa/tv/series.py</a>", line 1397, in make_ep_from_file
    root_ep.create_meta_files()
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/episode.py#L1108">medusa/tv/episode.py</a>", line 1108, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/episode.py#L1131">medusa/tv/episode.py</a>", line 1131, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/metadata/generic.py#L326">medusa/metadata/generic.py</a>", line 326, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/tv/episode.py#L679">medusa/tv/episode.py</a>", line 679, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/tvdbv2_api.py#L223">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 223, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/fallback.py#L110">medusa/indexers/tvdbv2/fallback.py</a>", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/opt/medusa/<a href="../blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/indexers/tvdbv2/tvdbv2_api.py#L303">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 303, in _query_series
    (search_type='full' if not aired_season else 'season {season}'.format(season=aired_season), e=e.reason)
IndexerShowIncomplete: Show episode search exception, could not get any episodes. Did a season [2] search. Exception: ConnectionError
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3c9ba70150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Tvdb fallback is down.

**Comment by DDA78** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 16:23:38) [GCC 6.4.0]`
**Operating System**: `Linux-4.4.71+-armv7l-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/97baebff64f305ebdc521904c1256dea
### ERROR
<pre>
2018-03-30 01:53:32 ERROR    SHOWQUEUE-REFRESH :: [d6eb72d] 308986: Error while refreshing show Marcella. Error: Show episode search exception, could not get any episodes. Did a season [2] search. Exception: ConnectionError
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xad649110>: Failed to establish a new connection: [Errno -3] Try again',))
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 635, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1753, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 931, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1397, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/app/medusa/medusa/tv/episode.py", line 1108, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/app/medusa/medusa/tv/episode.py", line 1131, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/app/medusa/medusa/metadata/generic.py", line 326, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/app/medusa/medusa/tv/episode.py", line 679, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 223, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/app/medusa/medusa/indexers/tvdbv2/fallback.py", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 303, in _query_series
    (search_type='full' if not aired_season else 'season {season}'.format(season=aired_season), e=e.reason)
IndexerShowIncomplete: Show episode search exception, could not get any episodes. Did a season [2] search. Exception: ConnectionError
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xad649110>: Failed to establish a new connection: [Errno -3] Try again',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by DDA78** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 16:23:38) [GCC 6.4.0]`
**Operating System**: `Linux-4.4.71+-armv7l-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/c46cd0fd4f3b20c1c98a1b5ddafccdac
### ERROR
<pre>
2018-03-30 01:50:37 ERROR    SHOWQUEUE-REFRESH :: [d6eb72d] 252800: Error while refreshing show Death in Paradise. Error: Show episode search exception, could not get any episodes. Did a season [5] search. Exception: ConnectionError
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xae855310>: Failed to establish a new connection: [Errno -3] Try again',))
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 635, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1753, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 931, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1397, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/app/medusa/medusa/tv/episode.py", line 1108, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/app/medusa/medusa/tv/episode.py", line 1131, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/app/medusa/medusa/metadata/generic.py", line 326, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/app/medusa/medusa/tv/episode.py", line 679, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 223, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/app/medusa/medusa/indexers/tvdbv2/fallback.py", line 110, in __call__
    return self.func(*args, **kwargs)
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 303, in _query_series
    (search_type='full' if not aired_season else 'season {season}'.format(season=aired_season), e=e.reason)
IndexerShowIncomplete: Show episode search exception, could not get any episodes. Did a season [5] search. Exception: ConnectionError
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xae855310>: Failed to establish a new connection: [Errno -3] Try again',))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
