### ISSUE TITLE
UnboundLocalError: local variable 'title' referenced before assignment

### ISSUE THREAD

**Issue by darthShadow** [pymedusa/Medusa#3876]
**Branch/Commit:** master/release 0.2.1
**OS:** Ubuntu 16.04
**What you did:** Daily Search
**What happened:** Exception
**What you expected:** Successful Daily Search
**Logs:**
```
2018-03-18 10:59:18 INFO     SEARCHQUEUE-DAILY-SEARCH :: [d6eb72d] Using daily search providers
2018-03-18 10:59:30 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [d6eb72d] DailySearchQueueItem Exception, error: local variable 'title' referenced be
fore assignment
Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 262, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/opt/medusa/medusa/search/core.py", line 456, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/opt/medusa/medusa/tv/cache.py", line 200, in update_cache
    data = self._get_rss_data()
  File "/opt/medusa/medusa/tv/cache.py", line 183, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)}
  File "/opt/medusa/medusa/providers/torrent/html/animebytes.py", line 113, in search
    results += self.parse(response.text, mode)
  File "/opt/medusa/medusa/providers/torrent/html/animebytes.py", line 242, in parse
    'title': title,
UnboundLocalError: local variable 'title' referenced before assignment
```

My guess is that the lines [animebytes.py: L255-L280]() should be before the line [animebytes.py: L192](https://github.com/pymedusa/Medusa/blob/d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe/medusa/providers/torrent/html/animebytes.py#L192), otherwise the release type is not set.

**Comment by p0psicles** [comment]
AB provider has been broken for a while now. We don't have any access to it, so we can't do any maintenance.

If you want to have it fixed, better look into it your self.

**Comment by p0psicles** [comment]
We could do some trial & error.

**Comment by darthShadow** [comment]
Sure, what do you need?

**Comment by medariox** [comment]
This is going to be difficult without direct access to the provider.

**Comment by darthShadow** [comment]
This issue occurred rarely and I have not seen it happen again. I also recently switched over to Jackett and it is working fine. You can look into their [AnimeBytes parser](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/AnimeBytes.cs) if that helps.
If you need something, I am willing to help.

**Comment by duramato** [comment]
### INFO
**Python Version**: `3.7.2 (default, Jan  3 2019, 02:55:40) [GCC 8.2.0]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-buster-sid`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@a79d1b7a7bf4fe35ed1c9102a3ec729e605b3af5
**Link to Log**: https://gist.github.com/23c18e51672cd33c5397afcc4fd8ed41
### ERROR
<pre>
2019-03-01 02:20:51 ERROR    FINDPROPERS :: [Torrenting] :: [a79d1b7] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/a79d1b7a7bf4fe35ed1c9102a3ec729e605b3af5/medusa/scheduler.py#L93">medusa/scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "/home/pi/Medusa/<a href="../blob/a79d1b7a7bf4fe35ed1c9102a3ec729e605b3af5/medusa/search/proper.py#L66">medusa/search/proper.py</a>", line 66, in run
    propers = self._get_proper_results()
  File "/home/pi/Medusa/<a href="../blob/a79d1b7a7bf4fe35ed1c9102a3ec729e605b3af5/medusa/search/proper.py#L124">medusa/search/proper.py</a>", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "/home/pi/Medusa/<a href="../blob/a79d1b7a7bf4fe35ed1c9102a3ec729e605b3af5/medusa/providers/generic_provider.py#L207">medusa/providers/generic_provider.py</a>", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "/home/pi/Medusa/<a href="../blob/a79d1b7a7bf4fe35ed1c9102a3ec729e605b3af5/medusa/providers/torrent/html/torrenting.py#L86">medusa/providers/torrent/html/torrenting.py</a>", line 86, in search
    results += self.parse(response.text, mode)
  File "/home/pi/Medusa/<a href="../blob/a79d1b7a7bf4fe35ed1c9102a3ec729e605b3af5/medusa/providers/torrent/html/torrenting.py#L107">medusa/providers/torrent/html/torrenting.py</a>", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rbhamilton** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@b34f1df336e52cf0a690acbc393440ac9f8b3581
**Link to Log**: https://gist.github.com/3d8cd6520668c44b365a3eef9a2fb1c2
### ERROR
<pre>
2019-03-30 01:54:46 ERROR    FINDPROPERS :: [Torrenting] :: [b34f1df] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/scheduler.py#L93">medusa\scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "C:\Medusa\Medusa\<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/search/proper.py#L66">medusa\search\proper.py</a>", line 66, in run
    propers = self._get_proper_results()
  File "C:\Medusa\Medusa\<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/search/proper.py#L124">medusa\search\proper.py</a>", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "C:\Medusa\Medusa\<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/providers/generic_provider.py#L207">medusa\providers\generic_provider.py</a>", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "C:\Medusa\Medusa\<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/providers/torrent/html/torrenting.py#L86">medusa\providers\torrent\html\torrenting.py</a>", line 86, in search
    results += self.parse(response.text, mode)
  File "C:\Medusa\Medusa\<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/providers/torrent/html/torrenting.py#L107">medusa\providers\torrent\html\torrenting.py</a>", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by flick1999** [comment]
### INFO
**Python Version**: `2.7.15 (default, Jan 24 2019, 16:32:39) [GCC 8.2.0]`
**Operating System**: `Linux-4.18.20-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@94fae847b6e7e443d74c59cb11bdbd37c464b363
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-04-06 19:50:55 ERROR    FINDPROPERS :: [Torrenting] :: [94fae84] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/scheduler.py#L93">medusa/scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/search/proper.py#L66">medusa/search/proper.py</a>", line 66, in run
    propers = self._get_proper_results()
  File "/app/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/search/proper.py#L124">medusa/search/proper.py</a>", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "/app/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/providers/generic_provider.py#L207">medusa/providers/generic_provider.py</a>", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "/app/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/providers/torrent/html/torrenting.py#L86">medusa/providers/torrent/html/torrenting.py</a>", line 86, in search
    results += self.parse(response.text, mode)
  File "/app/medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/providers/torrent/html/torrenting.py#L107">medusa/providers/torrent/html/torrenting.py</a>", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rbhamilton** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/b61f4808ae9a24ddc0d0bd799df6292d
### ERROR
<pre>
2019-04-26 23:21:33 ERROR    FINDPROPERS :: [Torrenting] :: [f46bfac] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/scheduler.py#L93">medusa\scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L66">medusa\search\proper.py</a>", line 66, in run
    propers = self._get_proper_results()
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L124">medusa\search\proper.py</a>", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/generic_provider.py#L207">medusa\providers\generic_provider.py</a>", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L86">medusa\providers\torrent\html\torrenting.py</a>", line 86, in search
    results += self.parse(response.text, mode)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L107">medusa\providers\torrent\html\torrenting.py</a>", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rbhamilton** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-05-09 00:18:34 ERROR    FINDPROPERS :: [Torrenting] :: [f46bfac] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/scheduler.py#L93">medusa\scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L66">medusa\search\proper.py</a>", line 66, in run
    propers = self._get_proper_results()
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L124">medusa\search\proper.py</a>", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/generic_provider.py#L207">medusa\providers\generic_provider.py</a>", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L86">medusa\providers\torrent\html\torrenting.py</a>", line 86, in search
    results += self.parse(response.text, mode)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L107">medusa\providers\torrent\html\torrenting.py</a>", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rbhamilton** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-05-13 21:41:49 ERROR    FINDPROPERS :: [Torrenting] :: [f46bfac] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/scheduler.py#L93">medusa\scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L66">medusa\search\proper.py</a>", line 66, in run
    propers = self._get_proper_results()
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L124">medusa\search\proper.py</a>", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/generic_provider.py#L207">medusa\providers\generic_provider.py</a>", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L86">medusa\providers\torrent\html\torrenting.py</a>", line 86, in search
    results += self.parse(response.text, mode)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L107">medusa\providers\torrent\html\torrenting.py</a>", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bangorbob** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/6212a6e8131476dabe010d118e68b311
### ERROR
<pre>
2019-05-17 20:54:17 ERROR    FINDPROPERS :: [Torrenting] :: [f46bfac] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/scheduler.py#L93">medusa\scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L66">medusa\search\proper.py</a>", line 66, in run
    propers = self._get_proper_results()
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L124">medusa\search\proper.py</a>", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/generic_provider.py#L207">medusa\providers\generic_provider.py</a>", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L86">medusa\providers\torrent\html\torrenting.py</a>", line 86, in search
    results += self.parse(response.text, mode)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L107">medusa\providers\torrent\html\torrenting.py</a>", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rbhamilton** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@f46bfacf8763204fbde4f26a5916095371d494d1
**Link to Log**: https://gist.github.com/c167e1738eae8792bb792e542547e607
### ERROR
<pre>
2019-05-19 12:32:23 ERROR    FINDPROPERS :: [Torrenting] :: [f46bfac] Exception generated: local variable 'torrent_rows' referenced before assignment
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/scheduler.py#L93">medusa\scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L66">medusa\search\proper.py</a>", line 66, in run
    propers = self._get_proper_results()
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/search/proper.py#L124">medusa\search\proper.py</a>", line 124, in _get_proper_results
    cur_propers = cur_provider.find_propers(recently_aired)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/generic_provider.py#L207">medusa\providers\generic_provider.py</a>", line 207, in find_propers
    for item in self.search(search_strings[0], ep_obj=episode_obj):
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L86">medusa\providers\torrent\html\torrenting.py</a>", line 86, in search
    results += self.parse(response.text, mode)
  File "C:\Medusa\Medusa\<a href="../blob/f46bfacf8763204fbde4f26a5916095371d494d1/medusa/providers/torrent/html/torrenting.py#L107">medusa\providers\torrent\html\torrenting.py</a>", line 107, in parse
    if len(torrent_rows) < 2:
UnboundLocalError: local variable 'torrent_rows' referenced before assignment
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
