### ISSUE TITLE
Manual Post-processing never completes

### ISSUE THREAD

**Issue by gilfrade** [pymedusa/Medusa#3878]
**Branch/Commit: master
**OS: Centos 7
**What you did: Manual post-processing
**What happened: Never completes, stays in the same view
**What you expected: Post-processing fails, should give Message Error 
```
...
2018-03-19 13:50:32 INFO     SEARCHQUEUE-DAILY-SEARCH :: [d6eb72d] Beginning daily search for new episodes
2018-03-19 13:28:14 INFO     POSTPROCESSOR :: [d6eb72d] Found subtitle for *** in opensubtitles provider with language eng
2018-03-19 13:20:35 ERROR    POSTPROCESSOR :: [d6eb72d] OSError: 
Traceback (most recent call last):
  File "/opt/medusa/medusa/helpers/__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/opt/medusa/lib/shutil_custom/__init__.py", line 44, in copyfile_custom
    os.write(fout, x)
OSError: [Errno 5] Input/output error
2018-03-19 13:20:30 INFO     POSTPROCESSOR :: [d6eb72d] Release name (***) found from file (***)
2018-03-19 13:20:30 INFO     POSTPROCESSOR :: [d6eb72d] This download is marked a priority download so I'm going to replace an existing file if I find one
2018-03-19 13:20:30 INFO     POSTPROCESSOR :: [d6eb72d] New size: 1.02 GB
2018-03-19 13:20:30 INFO     POSTPROCESSOR :: [d6eb72d] New file: /opt/torrents/complete/medusa/***.mkv
2018-03-19 13:20:30 INFO     POSTPROCESSOR :: [d6eb72d] Processing /opt/torrents/complete/medusa/***.mkv
2018-03-19 13:11:08 INFO     Thread-16 :: [d6eb72d] Release name (***) found from file (***)
2018-03-19 13:11:07 INFO     Thread-16 :: [d6eb72d] This download is marked a priority download so I'm going to replace an existing file if I find one
2018-03-19 13:11:07 INFO     Thread-16 :: [d6eb72d] New size: 1.02 GB
2018-03-19 13:11:07 INFO     Thread-16 :: [d6eb72d] New file: /opt/torrents/complete/medusa/***.mkv
2018-03-19 13:11:07 INFO     Thread-16 :: [d6eb72d] Processing /opt/torrents/complete/medusa/***.mkv
2018-03-19 13:10:44 ERROR    Thread-16 :: [d6eb72d] Missing time zone for network: MBS TV
...
```

**Comment by medariox** [comment]
If your post-processing folder is located remotely this can happen from time to time, e.g. on unstable connections or it can also be caused by very slow hardware, that can't keep up with the number of requests.

**Comment by gilfrade** [comment]
I understand, and its exactly what is happening. I'm only referring this to a user experience issue.

**Comment by OmgImAlexis** [comment]
@gilfrade I've opened an issue to fix this. https://github.com/pymedusa/Medusa/issues/3885
