### ISSUE TITLE
[APP SUBMITTED]: ImportError: No module named pkgutl

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#3880]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1255`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@e188f0a7115deca2718f7d62fda107e72541f2d4
**Link to Log**: https://gist.github.com/cb61bce3b11f14a95b088fae38ddf16f
### ERROR
<pre>
2018-03-20 15:22:57 ERROR    Thread-33 :: [e188f0a] Exception generated: No module named pkgutl
Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 281, in async_call
    result = function(**kwargs)
  File "C:\Medusa\medusa\server\web\home\post_process.py", line 21, in index
    t = PageTemplate(rh=self, filename='home_postprocess.mako')
  File "C:\Medusa\medusa\server\web\core\base.py", line 88, in __init__
    self.template = lookup.get_template(filename)
  File "C:\Medusa\ext\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\Medusa\ext\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\Medusa\ext\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Medusa\ext\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\Medusa\ext\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\Medusa\Data\cache\mako\home_postprocess.mako.py", line 17, in <module>
    import pkgutl
ImportError: No module named pkgutl
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Any idea how this issue was triggered? Did it happen only once or does it happen regularly?

**Comment by sharkykh** [comment]
Triggered by navigating to the Manual Post-Proccessing page. This happens consistently, every time I try and open that page.

**Comment by p0psicles** [comment]
Did you try deleting your mako cache?

**Comment by sharkykh** [comment]
Yep, and restarting. I am a bit rusty on Python packages, is `pkgutl` supposed to be available out of the box for 2.7.13?

**Comment by medariox** [comment]
Yep, it should be available since version 2.3

**Comment by p0psicles** [comment]
I think pkgutil is but don't know about pkgutl

**Comment by sharkykh** [comment]
Oh. I just figured it out. It's a typo. Should be `pkgutil`, not `pkgutl`. I looked at [this](https://github.com/pymedusa/Medusa/commit/729945df71be24182c3ab1cfabec707b32969c90#diff-e4dc290b12059557cd7d02c23cb581c2)

**Comment by p0psicles** [comment]
Aah good it's only in develop

**Comment by p0psicles** [comment]
We put that typo I there to get you involved again ;-).
