### ISSUE TITLE
Unexpected error in provider 'opensubtitles'

### ISSUE THREAD

**Issue by kantjer** [pymedusa/Medusa#3901]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: Master / d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**OS DSM 6.1.5-15254 Update 1
**What you did: enable subtitel search
**What happened: see error log
**What you expected: no errors
**Logs:**
```
2018-03-23 17:05:19 WARNING  FINDSUBTITLES :: [d6eb72d] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 228, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 194, in query
    language = Language.fromopensubtitles(subtitle_item['SubLanguageID'])
TypeError: string indices must be integers, not str
2018-03-23 16:05:42 WARNING  FINDSUBTITLES :: [d6eb72d] Provider u'opensubtitles' unavailable
```

**Comment by h3llrais3r** [comment]
Already logged it at Subliminal: https://github.com/Diaoul/subliminal/issues/902

**Comment by medariox** [comment]
Yep, it's a subliminal issue, nothing we can do about it here.
