### ISSUE TITLE
YGGtorrent no longer work with MEDUSA

### ISSUE THREAD

**Issue by Silvers12** [pymedusa/Medusa#3945]
With the new site yggtorrent.com become yggtorrent.is and the provider don't work anymore on MEDUSA. 

I have edited the yggtorrent.py with the good path but it doesnt work ...
Can someone help me to repare ygg please ?
Thx a lot.

**Branch/Commit:**
**OS: Debian 9**
**What you did: Searching for episode With YGGTORRENT provider**
**What happened: No result**
**What you expected: Result ^^**
**Logs:**
```
PASTE LOGS HERE
[Yggtorrent] :: [d6eb72d] Error requesting url https://YGGTORRENT.IS/user/login. Error: ('Connection aborted.', error(107, "Noeud final de transport n'est pas connect\xc3\xa9"))

**Comment by medariox** [comment]
The website is not working atm.

**Comment by IDerr** [comment]
It should be now.

**Comment by Silvers12** [comment]
Ok i test that thx ;)

**Comment by Silvers12** [comment]
Ok the site is come back but MEDUSA still return no result ...

**Comment by Silvers12** [comment]
I change yggtorrent.com by yggtorrent.is and i delete the file yggtorrent.pyc. I restart MEDUSA and now no more error, but still no result :
`2018-04-02 15:56:27 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] No unknown qualities in results
2018-04-02 15:56:27 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Found qualities: []
2018-04-02 15:56:27 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Found 0 unique items
2018-04-02 15:56:27 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Data returned from provider does not contain any torrents
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] User-Agent: Medusa/0.1.23 (Linux; 4.9.87-xxxx-std-ipv6-64; 7c47d230-367d-11e8-be20-00224dae32cd)
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] GET URL: https://yggtorrent.is/engine/search?category=2145&q=The+Walking+Dead+S08E13 [Status: 200]
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Search string: The Walking Dead S08E13
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Search mode: Episode
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] User-Agent: Medusa/0.1.23 (Linux; 4.9.87-xxxx-std-ipv6-64; 7c47d230-367d-11e8-be20-00224dae32cd)
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] GET URL: https://yggtorrent.is/ [Status: 200]
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] With post data: id=**********&submit=&pass=**********
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] User-Agent: Medusa/0.1.23 (Linux; 4.9.87-xxxx-std-ipv6-64; 7c47d230-367d-11e8-be20-00224dae32cd)
2018-04-02 15:56:26 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] POST URL: https://yggtorrent.is/user/login [Status: 200]
2018-04-02 15:56:26 INFO     SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Performing episode search for The Walking Dead`

**Comment by Silvers12** [comment]
Ok so now ^^ (I believe in myself !)

This code refuse to work ...

`pubdate = None
                    pubdate_match = re.match(r'(\d+)\s(\w+)', cells[4].get_text(strip=True))
                    if pubdate_match:
                        translated = self.translation.get(pubdate_match.group(2))
                        if not translated:
                            log.exception('No translation mapping available for value: {0}', pubdate_match.group(2))
                        else:
                            pubdate_raw = '{0} {1}'.format(pubdate_match.group(1), translated)
                            **pubdate = self.parse_pubdate(pubdate_raw, human_time=True)**
                    else:
                        log.warning('Could not translate publishing date with value: {0}',
                                    cells[4].get_text(strip=True))

                     Filter unseeded torrent`

The bold ligne bug... My column date have this string : "4 heures" but this code crash... An idea ?

**Comment by IDerr** [comment]
If your code seems good to you, you can open a pull request :D and someone from medusa will check your code ;)

**Comment by IDerr** [comment]
Is it possible to send the Exception of this part ?

**Comment by Silvers12** [comment]
yes i send this when i can because ygg is down

**Comment by Silvers12** [comment]
Ok ygg is back so, this is the log :

`2018-04-03 12:14:12 DEBUG    SEARCHQUEUE-MANUAL-153021 :: [Yggtorrent] :: [d6eb72d] Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 351, in run
    self.manual_search, self.manual_search_type)
  File "/opt/medusa/medusa/search/core.py", line 609, in search_providers
    down_cur_quality, manual_search, manual_search_type)
  File "/opt/medusa/medusa/providers/generic_provider.py", line 235, in find_search_results
    search_string, ep_obj=episode, manual_search=manual_search
  File "/opt/medusa/medusa/providers/torrent/html/yggtorrent.py", line 112, in search
    results += self.parse(response.text, mode)
  File "/opt/medusa/medusa/providers/torrent/html/yggtorrent.py", line 165, in parse
    pubdate = self.parse_pubdate(pubdate_raw, human_time=True)
  File "/opt/medusa/medusa/providers/generic_provider.py", line 601, in parse_pubdate
    return datetime.now(tz.tzlocal()) - timedelta(seconds=seconds)
OverflowError: normalized days too large to fit in a C int`

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/3950 and https://github.com/pymedusa/Medusa/pull/3952
