### ISSUE TITLE
[APP SUBMITTED]: ParseError: not well-formed (invalid token): line 1, column 19

### ISSUE THREAD

**Issue by poplolnman** [pymedusa/Medusa#3946]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe
**Link to Log**: https://gist.github.com/b93f708a0f5b80e1ab608f3c9b1259c2
### ERROR
<pre>
2018-04-02 05:11:25 ERROR    SEARCHQUEUE-BACKLOG-290853 :: [filelist] :: [d6eb72d] Unable to parse the XML of Fear.The.Walking.Dead.S02.HDTV.AAC2.0.x264-Scene, not splitting it
Traceback (most recent call last):
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\nzb_splitter.py", line 60, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by poplolnman** [comment]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@0da7d0a5b457a7acf6686949361aa1a1c2fcf93d
**Link to Log**: https://gist.github.com/8bec4adb14fec09c362cc7c433aefa2c
### ERROR
<pre>
2018-04-04 19:11:40 ERROR    SEARCHQUEUE-BACKLOG-193131 :: [bitmetv] :: [0da7d0a] Unable to parse the XML of Downton.Abbey.S06.BDRip.SUBS-HAGGiS, not splitting it
Traceback (most recent call last):
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\nzb_splitter.py", line 61, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by poplolnman** [comment]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@0da7d0a5b457a7acf6686949361aa1a1c2fcf93d
**Link to Log**: https://gist.github.com/7b3f339a9ad9f7964032138d1e723637
### ERROR
<pre>
2018-04-04 19:00:39 ERROR    SEARCHQUEUE-BACKLOG-193131 :: [bitmetv] :: [0da7d0a] Unable to parse the XML of Downton.Abbey.S02.DVDRip.XviD-HAGGiS, not splitting it
Traceback (most recent call last):
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\nzb_splitter.py", line 61, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 20
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by poplolnman** [comment]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@0da7d0a5b457a7acf6686949361aa1a1c2fcf93d
**Link to Log**: https://gist.github.com/e4e5ae27fb68f31e5d68f88c8a3c39e3
### ERROR
<pre>
2018-04-04 18:53:48 ERROR    SEARCHQUEUE-BACKLOG-193131 :: [filelist] :: [0da7d0a] Unable to parse the XML of Downton.Abbey.S01.RoSubbed.HDTV.XviD-FL, not splitting it
Traceback (most recent call last):
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\nzb_splitter.py", line 61, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by TTLucian** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/c58b70f551e37d47db739520991eec4d
### ERROR
<pre>
2018-04-22 22:28:26 ERROR    SEARCHQUEUE-BACKLOG-295760 :: [Jackett FileList.ro] :: [77b2091] Unable to parse the XML of DCs.Legends.Of.Tomorrow.S03.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ, not splitting it
Traceback (most recent call last):
  File "C:\Data\Medusa\Medusa\medusa\nzb_splitter.py", line 61, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 19
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
For the record: This is caused due to using Custom Newznab providers as Jackett/Torznab providers.
Dedicated Jackett/Torznab providers support was added to the config, please convert your current providers to it.
