### ISSUE TITLE
TypeError: <medusa.tv.series.Series object at 0x10fbdb190> is not JSON serializable

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#3958]
Using `json.dumps` on a Series object doesn't work.

We should add the needed methods for `json.dumps` to work natively.

```
Traceback (most recent call last):
  File "/Users/xo/code/Medusa/medusa/server/web/core/base.py", line 279, in async_call
    result = function(**kwargs)
  File "/Users/xo/code/Medusa/medusa/server/web/home/handler.py", line 999, in displayShow
    title=series_obj.name, controller='home', action='displayShow',
  File "/Users/xo/code/Medusa/medusa/server/web/core/base.py", line 163, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "/Users/xo/code/Medusa/ext/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/Users/xo/code/Medusa/ext/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/Users/xo/code/Medusa/ext/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/xo/code/Medusa/ext/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/Users/xo/code/Medusa/cache/mako/layouts/main.mako.py", line 101, in render_body
    runtime._include_file(context, u'/partials/submenu.mako', _template_uri)
  File "/Users/xo/code/Medusa/ext/mako/runtime.py", line 761, in _include_file
    callable_(ctx, **kwargs)
  File "/Users/xo/code/Medusa/cache/mako/partials/submenu.mako.py", line 120, in render_body
    __M_writer(unicode(json.dumps(sortedShowLists)))
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <medusa.tv.series.Series object at 0x10fbdb190> is not JSON serializable
```

**Comment by sharkykh** [comment]
The cleanest solution IMO is to [monkeypatch `JSONEncoder`](https://stackoverflow.com/a/38764817).
We can do that in `medusa/init/*.py` just like all the other patches. This would affect every `json.dump[s]` call and `JSONEncoder` instance within Medusa.
It will look for the `to_json` attribute on the object and use that as the serializer, otherwise it falls back to the default serialize function.
You can easily override this by using the `default=callable` keyword argument.

**Comment by OmgImAlexis** [comment]
`datetime` also needs to be patched to be converted over to a ISO timestamp so we can use it in js.

```
File /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py:184, in default:
raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2018, 10, 1, 9, 30, tzinfo=tzlocal()) is not JSON serializable
```

**Comment by sharkykh** [comment]
I should add that I looked into monkey-patching `json.dumps`.
[As I said, it can be done](https://github.com/pymedusa/Medusa/commit/707f88376a3c2f43981f96afbd437e85170e6aa4), but I'm not so sure we should do it.
Eventually we won't need to do `json.dumps` on an object, since the API will provide the information.
