### ISSUE TITLE
red error

### ISSUE THREAD

**Issue by poplolnman** [pymedusa/Medusa#3989]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: mastet
**OS windows 10
**What you did:**
**What happened:**
**What you expected:**
**Logs:**
```
2018-04-10 16:30:06 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: [d6eb72d] DailySearchQueueItem Exception, error: disk I/O error
Traceback (most recent call last):
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\search\queue.py", line 262, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\search\core.py", line 456, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\tv\cache.py", line 196, in update_cache
    if not self.should_update():
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\tv\cache.py", line 362, in should_update
    if time() - self.updated < self.minTime * 60:
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\tv\cache.py", line 316, in updated
    return self._get_time(b'last_update')
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\tv\cache.py", line 338, in _get_time
    [self.provider_id]
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\db.py", line 298, in select
    sql_results = self.action(query, args, fetchall=True)
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\db.py", line 268, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\Users\Mat\Documents\Medusa-0.2.1\medusa\db.py", line 108, in _execute
    sql_results = cursor.execute(query, args)
OperationalError: disk I/O error


im getting this error for multiple indexers and im not sure if this is bad or not?
```

**Comment by OmgImAlexis** [comment]
Duplicate https://github.com/pymedusa/Medusa/issues/970

You likely have an issue with one of your hard drives. It's either near full, really busy or about to fail.
