### ISSUE TITLE
Manual Subtitles Search Error

### ISSUE THREAD

**Issue by tomsema** [pymedusa/Medusa#4008]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit: master
**OS:Linux-4.4.0-119-generic-x86_64-with-Ubuntu-16.04-xenial
**SSL Version: OpenSSL 1.0.2g
**Python Version: 2.7.12

**What you did: Manual Subtitles Search. 
**What happened: Subtitles was not found and received error
**What you expected: Receive subtitles for episode
**Logs:**
```
PASTE LOGS HERE
2018-04-13 11:03:10 ERROR    Thread-29 :: [d6eb72d] Exception generated: need 'c' or 'n' flag to open new db
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 283, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/handler.py", line 2287, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/opt/medusa/medusa/subtitles.py", line 331, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/opt/medusa/ext/dogpile/cache/region.py", line 984, in set
    self.backend.set(key, self._value(value))
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python2.7/anydbm.py", line 79, in open
    raise error, "need 'c' or 'n' flag to open new db"
error: need 'c' or 'n' flag to open new db

**Comment by medariox** [comment]
Thanks for the bug report. Fixed with: https://github.com/pymedusa/Medusa/pull/4011
