### ISSUE TITLE
[APP SUBMITTED]: TypeError: cannot serialize 7.5 (type float)

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#4013]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@e47aad8bdf5d0a9f3297a112da7005310d2f32e8
**Link to Log**: https://gist.github.com/6d931b2ef653624fdb16d903d29cdcb8
### ERROR
<pre>
2018-04-13 20:10:30 ERROR    ThreadPoolExecutor-0_0 :: [e47aad8] Exception generated: cannot serialize 7.5 (type float)
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/server/web/core/base.py#L279">medusa/server/web/core/base.py</a>", line 279, in async_call
    result = function(**kwargs)
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/server/web/home/post_process.py#L49">medusa/server/web/home/post_process.py</a>", line 49, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/process_tv.py#L148">medusa/process_tv.py</a>", line 148, in process
    ignore_subs=ignore_subs)
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/process_tv.py#L336">medusa/process_tv.py</a>", line 336, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/process_tv.py#L537">medusa/process_tv.py</a>", line 537, in process_media
    self.result = processor.process()
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/post_processor.py#L1139">medusa/post_processor.py</a>", line 1139, in process
    ep_obj.series.write_metadata(True)
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/tv/series.py#L853">medusa/tv/series.py</a>", line 853, in write_metadata
    self.__write_show_nfo(metadata_provider)
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/tv/series.py#L836">medusa/tv/series.py</a>", line 836, in __write_show_nfo
    result = metadata_provider.create_show_metadata(self) or result
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/metadata/generic.py#L245">medusa/metadata/generic.py</a>", line 245, in create_show_metadata
    return self.write_show_file(show_obj)
  File "/home/pi/Medusa/<a href="../blob/e47aad8bdf5d0a9f3297a112da7005310d2f32e8/medusa/metadata/generic.py#L432">medusa/metadata/generic.py</a>", line 432, in write_show_file
    data.write(nfo_file, encoding=u'UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._**********, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1075, in _escape_cdata
    _raise_serialization_error(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize 7.5 (type float)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
@duramato 
I found and, I believe, fixed the issue.
7.5 = 75% - user rating of the show Atlanta on TMDB.
This value was mapped to `contentrating`, which is the MPAA rating [`TV-MA`], instead of `rating`.

Had to update the `tmdbsimple` library for that, but it's fixed now, as the `tvshow.nfo` that didn't properly generate before the fix, is all good now.

I will open a PR as soon as I get the commits in order.

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/4026
