### ISSUE TITLE
torrent get_client_module - AttributeError

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#4044]
develop - ae0d40cb54d16748cf0d6b8a54917f2447641bdc

```
2018-04-18 11:47:56 ERROR    Thread_6 :: [1a8dc66] Exception generated: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/Users/xo/code/Medusa/medusa/server/web/core/base.py", line 285, in async_call
    result = function(**kwargs)
  File "/Users/xo/code/Medusa/medusa/server/web/home/handler.py", line 321, in testTorrent
    client = torrent.get_client_class(torrent_method)
  File "/Users/xo/code/Medusa/medusa/clients/torrent/__init__.py", line 48, in get_client_class
    return get_client_module(name).api
  File "/Users/xo/code/Medusa/medusa/clients/torrent/__init__.py", line 37, in get_client_module
    return __import__('{prefix}.{name}_client'.format(prefix=__name__, name=name.lower()), fromlist=_clients)
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by MattCorp** [comment]
### INFO
**Python Version**: `2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]`
**Operating System**: `Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Debian-8`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/1aca63265f10adb1edb1f667e81fab4f
### ERROR
<pre>
2018-04-25 09:46:14 ERROR    SEARCHQUEUE-BACKLOG-24624 :: [EliteTracker] :: [77b2091] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/home/**********/medusa/medusa/providers/torrent/html/elitetracker.py", line 139, in parse\n    title = torrent.find(class_=\'tooltip-content\').div.get_text(strip=True)\nAttributeError: \'NoneType\' object has no attribute \'div\'\n'
Traceback (most recent call last):
  File "/home/**********/medusa/medusa/providers/torrent/html/elitetracker.py", line 139, in parse
    title = torrent.find(class_='tooltip-content').div.get_text(strip=True)
AttributeError: 'NoneType' object has no attribute 'div'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
@MattCorp Looks like something may have changed in EliteTracker's search page layout.

**Comment by calmcacil** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.35-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.10`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/1b1c65cf0de750e79df02d41ebcb24be
### ERROR
<pre>
2018-04-26 21:41:44 ERROR    SEARCHQUEUE-MANUAL-304900 :: [HorribleSubs] :: [77b2091] Failed parsing provider.
Traceback (most recent call last):
  File "/app/medusa/medusa/providers/torrent/torznab/torznab.py", line 182, in parse
    seeders = int(seeders_attr.get('value', 0))
AttributeError: 'NoneType' object has no attribute 'get'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
