### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 2] No such file or directory: '/config/cache/mako/tmp2pyvK4'

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#4080]
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-3.10.102-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/b7adea61330980950313c5a4031219ff
### ERROR
<pre>
2018-04-23 10:29:34 ERROR    Thread_5 :: [77b2091] Environment error: [Errno 2] No such file or directory: '/config/cache/mako/tmp2pyvK4'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 285, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/handler.py", line 841, in displayShow
    t = PageTemplate(rh=self, filename='displayShow.mako')
  File "/app/medusa/medusa/server/web/core/base.py", line 81, in __init__
    self.template = lookup.get_template(filename)
  File "/app/medusa/ext/mako/lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "/app/medusa/ext/mako/lookup.py", line 323, in _load
    **self.template_args)
  File "/app/medusa/ext/mako/template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/app/medusa/ext/mako/template.py", line 395, in _compile_from_file
    self.module_writer)
  File "/app/medusa/ext/mako/template.py", line 731, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/config/cache/mako/tmp2pyvK4'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by jasimancas** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.16.0-0.bpo.2-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@49f4f98b30fb58340aef2a46104d94bd7b37ca66
**Link to Log**: https://gist.github.com/fd27eb789c6ee0c59891069ee8077b81
### ERROR
<pre>
2018-07-13 10:52:21 ERROR    Thread_2 :: [49f4f98] Environment error: [Errno 2] No such file or directory: '/config/cache/mako/tmpvIfZcA'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/49f4f98b30fb58340aef2a46104d94bd7b37ca66/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/49f4f98b30fb58340aef2a46104d94bd7b37ca66/medusa/server/web/home/handler.py#L850">medusa/server/web/home/handler.py</a>", line 850, in displayShow
    t = PageTemplate(rh=self, filename='displayShow.mako')
  File "/app/medusa/<a href="../blob/49f4f98b30fb58340aef2a46104d94bd7b37ca66/medusa/server/web/core/base.py#L76">medusa/server/web/core/base.py</a>", line 76, in __init__
    self.template = lookup.get_template(filename)
  File "/app/medusa/<a href="../blob/49f4f98b30fb58340aef2a46104d94bd7b37ca66/ext/mako/lookup.py#L258">ext/mako/lookup.py</a>", line 258, in get_template
    return self._load(srcfile, uri)
  File "/app/medusa/<a href="../blob/49f4f98b30fb58340aef2a46104d94bd7b37ca66/ext/mako/lookup.py#L323">ext/mako/lookup.py</a>", line 323, in _load
    **self.template_args)
  File "/app/medusa/<a href="../blob/49f4f98b30fb58340aef2a46104d94bd7b37ca66/ext/mako/template.py#L338">ext/mako/template.py</a>", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/app/medusa/<a href="../blob/49f4f98b30fb58340aef2a46104d94bd7b37ca66/ext/mako/template.py#L395">ext/mako/template.py</a>", line 395, in _compile_from_file
    self.module_writer)
  File "/app/medusa/<a href="../blob/49f4f98b30fb58340aef2a46104d94bd7b37ca66/ext/mako/template.py#L731">ext/mako/template.py</a>", line 731, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/config/cache/mako/tmpvIfZcA'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
@sharkykh if it's closed as a dupe is there any way we can get the comment added to the original instead of the newer issue? Do we maybe need to lock the dupes so it'll try the old one?

**Comment by HPMSGEN8** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-3.10.102-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-09-16 09:54:52 ERROR    Thread_2 :: [4614efc] Environment error: [Errno 2] No such file or directory: '/config/cache/mako/tmp1vtNhT'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/home/handler.py#L848">medusa/server/web/home/handler.py</a>", line 848, in displayShow
    t = PageTemplate(rh=self, filename='displayShow.mako')
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/core/base.py#L76">medusa/server/web/core/base.py</a>", line 76, in __init__
    self.template = lookup.get_template(filename)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/lookup.py#L258">ext/mako/lookup.py</a>", line 258, in get_template
    return self._load(srcfile, uri)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/lookup.py#L323">ext/mako/lookup.py</a>", line 323, in _load
    **self.template_args)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/template.py#L338">ext/mako/template.py</a>", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/template.py#L395">ext/mako/template.py</a>", line 395, in _compile_from_file
    self.module_writer)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/template.py#L731">ext/mako/template.py</a>", line 731, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/config/cache/mako/tmp1vtNhT'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by HPMSGEN8** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-3.10.102-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-10-08 20:48:16 ERROR    Thread_27 :: [4614efc] Environment error: [Errno 2] No such file or directory: '/config/cache/mako/tmpM4zKto'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/home/add_shows.py#L76">medusa/server/web/home/add_shows.py</a>", line 76, in newShow
    t = PageTemplate(rh=self, filename='addShows_newShow.mako')
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/core/base.py#L76">medusa/server/web/core/base.py</a>", line 76, in __init__
    self.template = lookup.get_template(filename)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/lookup.py#L258">ext/mako/lookup.py</a>", line 258, in get_template
    return self._load(srcfile, uri)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/lookup.py#L323">ext/mako/lookup.py</a>", line 323, in _load
    **self.template_args)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/template.py#L338">ext/mako/template.py</a>", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/template.py#L395">ext/mako/template.py</a>", line 395, in _compile_from_file
    self.module_writer)
  File "/app/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/template.py#L731">ext/mako/template.py</a>", line 731, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/config/cache/mako/tmpM4zKto'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
