### ISSUE TITLE
[APP SUBMITTED]: TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by hrxfab** [pymedusa/Medusa#4092]
### INFO
**Python Version**: `2.7.14 (default, Feb 23 2018, 14:28:08) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-4.4.15+-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/a9e8675deaed951b2f10e04f8d5baca0
### ERROR
<pre>
2018-04-23 21:42:52 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [RARBG2] :: [77b2091] DailySearchQueueItem Exception, error: object of type 'bool' has no len()
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/SickBeard/medusa/search/queue.py#L263">SickBeard/medusa/search/queue.py</a>", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/SickBeard/medusa/search/core.py#L463">SickBeard/medusa/search/core.py</a>", line 463, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/SickBeard/medusa/tv/cache.py#L239">SickBeard/medusa/tv/cache.py</a>", line 239, in update_cache
    cache_db_con.mass_action(results)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/SickBeard/medusa/db.py#L203">SickBeard/medusa/db.py</a>", line 203, in mass_action
    querylist = [i for i in querylist if i is not None and len(i)]
TypeError: object of type 'bool' has no len()
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
This:
https://github.com/pymedusa/Medusa/blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/db.py#L202-L203
Has at least one `False` item:
https://github.com/pymedusa/Medusa/blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/tv/cache.py#L229-L231
Which probably came from this:
https://github.com/pymedusa/Medusa/blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/tv/cache.py#L313

That function (`_parse_item`) is used in one place only, as far as I can tell.
Should be an easy fix to change that last return to `None` instead of `False`.

**Comment by medariox** [comment]
Fixed with: https://github.com/pymedusa/Medusa/pull/4096

**Comment by DazzFX** [comment]
### INFO
**Python Version**: `2.7.13 (default, Dec 18 2016, 22:44:40) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-3.10.102-armv7l-with-glibc2.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/a8058e1e7d8fb5ddf74f593eeaab17b4
### ERROR
<pre>
2018-05-01 07:24:57 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [EZTV] :: [77b2091] DailySearchQueueItem Exception, error: object of type 'bool' has no len()
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/SickBeard/medusa/search/queue.py#L263">SickBeard/medusa/search/queue.py</a>", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/SickBeard/medusa/search/core.py#L463">SickBeard/medusa/search/core.py</a>", line 463, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/SickBeard/medusa/tv/cache.py#L239">SickBeard/medusa/tv/cache.py</a>", line 239, in update_cache
    cache_db_con.mass_action(results)
  File "/volume1/@appstore/sickbeard-custom/var/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/SickBeard/medusa/db.py#L203">SickBeard/medusa/db.py</a>", line 203, in mass_action
    querylist = [i for i in querylist if i is not None and len(i)]
TypeError: object of type 'bool' has no len()
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by STX2k** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.4.0-127-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/90d2302b377b61f6e0aff3ee94d71e6b
### ERROR
<pre>
2018-06-14 00:44:38 ERROR    TORNADO :: [c65ca26] API :: "object of type 'int' has no len()"
Traceback (most recent call last):
  File "/app/medusa/medusa/server/api/v1/core.py", line 141, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/app/medusa/medusa/server/api/v1/core.py", line 211, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/app/medusa/medusa/server/api/v1/core.py", line 1053, in run
    history = History().get(self.limit, self.type).detailed
  File "/app/medusa/medusa/show/history.py", line 69, in get
    filter_sql = 'AND action in (' + ','.join(['?'] * len(actions)) + ') '
TypeError: object of type 'int' has no len()
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by STX2k** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.4.0-127-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/03b4cddf6d3def3382f75345d4bff1c3
### ERROR
<pre>
2018-06-14 00:47:13 ERROR    TORNADO :: [c65ca26] API :: "object of type 'int' has no len()"
Traceback (most recent call last):
  File "/app/medusa/medusa/server/api/v1/core.py", line 141, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/app/medusa/medusa/server/api/v1/core.py", line 211, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/app/medusa/medusa/server/api/v1/core.py", line 1053, in run
    history = History().get(self.limit, self.type).detailed
  File "/app/medusa/medusa/show/history.py", line 69, in get
    filter_sql = 'AND action in (' + ','.join(['?'] * len(actions)) + ') '
TypeError: object of type 'int' has no len()
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
