### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 2] No such file or directory: u'/home/user/.apps/medusa/cache/mako/layouts/main.mako.py'

### ISSUE THREAD

**Issue by jawooten3** [pymedusa/Medusa#4094]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/39578c245d377d6016b6d5974d0da9eb
### ERROR
<pre>
2018-04-23 20:24:38 ERROR    Thread_73 :: [77b2091] Environment error: [Errno 2] No such file or directory: u'/home/user/.apps/medusa/cache/mako/layouts/main.mako.py'
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 285, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/core/schedule.py", line 56, in index
    topmenu='schedule', controller='schedule', action='index')
  File "/opt/medusa/medusa/server/web/core/base.py", line 149, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/medusa/ext/mako/exceptions.py", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/medusa/ext/mako/exceptions.py", line 165, in _init
    module_source = info.code
  File "/opt/medusa/ext/mako/template.py", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/opt/medusa/ext/mako/util.py", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/user/.apps/medusa/cache/mako/layouts/main.mako.py'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MillerBoss** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.121-1.el7.elrepo.x86_64-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/06723f8c81905004e8e19dd26aca7214
### ERROR
<pre>
2018-09-10 03:47:51 ERROR    Thread_0 :: [4614efc] Environment error: [Errno 2] No such file or directory: u'/home/user/.apps/medusa/cache/mako/layouts/main.mako.py'
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/home/handler.py#L170">medusa/server/web/home/handler.py</a>", line 170, in index
    max_download_count=stats[1], controller='home', action='index')
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/core/base.py#L123">medusa/server/web/core/base.py</a>", line 123, in render
    kwargs['backtrace'] = RichTraceback()
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/exceptions.py#L93">ext/mako/exceptions.py</a>", line 93, in __init__
    self.records = self._init(traceback)
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/exceptions.py#L165">ext/mako/exceptions.py</a>", line 165, in _init
    module_source = info.code
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/template.py#L660">ext/mako/template.py</a>", line 660, in code
    return util.read_python_file(self.module_filename)
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/ext/mako/util.py#L374">ext/mako/util.py</a>", line 374, in read_python_file
    fp = open(path, "rb")
IOError: [Errno 2] No such file or directory: u'/home/user/.apps/medusa/cache/mako/layouts/main.mako.py'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
