### ISSUE TITLE
[APP SUBMITTED]: TypeError: int() argument must be a string or a number, not 'datetime.datetime'

### ISSUE THREAD

**Issue by TrendaFet** [pymedusa/Medusa#4097]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-6-686-pae-i686-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/1b8dd24a9485ef7a7325abd3702947c6
### ERROR
<pre>
2018-04-24 05:09:23 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [77b2091] DailySearchQueueItem Exception, error: int() argument must be a string or a number, not 'datetime.datetime'
Traceback (most recent call last):
  File "/home/smln/.medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/queue.py#L263">medusa/search/queue.py</a>", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/home/smln/.medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L492">medusa/search/core.py</a>", line 492, in search_for_needed_episodes
    if delay_search(best_result):
  File "/home/smln/.medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L523">medusa/search/core.py</a>", line 523, in delay_search
    results['found_items'].sort(key=lambda d: int(d['date_added']))
  File "/home/smln/.medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L523">medusa/search/core.py</a>", line 523, in <lambda>
    results['found_items'].sort(key=lambda d: int(d['date_added']))
TypeError: int() argument must be a string or a number, not 'datetime.datetime'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by TrendaFet** [comment]
Could the cause for this error be the Search Delay setting? I had that enabled, a delay of 3 hours. I have disabled it now but there isn't anything in queue to test this theory until tomorrow.

No clue if it's related, just thought I'd mention it.

**Comment by sharkykh** [comment]
[Caused by this change](https://github.com/pymedusa/Medusa/pull/3920/files#diff-6d749d3f11b7318fd75c4ffd36e683e4). Need to either convert it back to timestamp of update the code to account for the change.

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.14393`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/33caed5a66595da37c1e5fb4f19bae0c
### ERROR
<pre>
2018-04-25 12:56:11 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [77b2091] DailySearchQueueItem Exception, error: int() argument must be a string or a number, not 'datetime.datetime'
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\search\queue.py", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "C:\GitHub\Medusa\medusa\search\core.py", line 492, in search_for_needed_episodes
    if delay_search(best_result):
  File "C:\GitHub\Medusa\medusa\search\core.py", line 523, in delay_search
    results['found_items'].sort(key=lambda d: int(d['date_added']))
  File "C:\GitHub\Medusa\medusa\search\core.py", line 523, in <lambda>
    results['found_items'].sort(key=lambda d: int(d['date_added']))
TypeError: int() argument must be a string or a number, not 'datetime.datetime'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by TrendaFet** [comment]
@medariox Thanks for the quick fix, much appreciated.

**Comment by apafitis** [comment]
### INFO
**Python Version**: `2.7.14 (default, Apr  5 2018, 01:14:31) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.0-RELEASE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/c58c605b3b200e35b6680bced48800cd
### ERROR
<pre>
2018-04-25 19:34:17 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Jackett - TorrentDay] :: [77b2091] DailySearchQueueItem Exception, error: int() argument must be a string or a number, not 'datetime.datetime'
Traceback (most recent call last):
  File "/usr/local/medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/queue.py#L263">medusa/search/queue.py</a>", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/usr/local/medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L492">medusa/search/core.py</a>", line 492, in search_for_needed_episodes
    if delay_search(best_result):
  File "/usr/local/medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L523">medusa/search/core.py</a>", line 523, in delay_search
    results['found_items'].sort(key=lambda d: int(d['date_added']))
  File "/usr/local/medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L523">medusa/search/core.py</a>", line 523, in <lambda>
    results['found_items'].sort(key=lambda d: int(d['date_added']))
TypeError: int() argument must be a string or a number, not 'datetime.datetime'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by apafitis** [comment]
### INFO
**Python Version**: `2.7.14 (default, Apr  5 2018, 01:14:31) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]`
**Operating System**: `FreeBSD-11.0-RELEASE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/56c9900f9402f257f50fa1d9715928f8
### ERROR
<pre>
2018-04-25 20:14:21 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Jackett - TorrentDay] :: [77b2091] DailySearchQueueItem Exception, error: int() argument must be a string or a number, not 'datetime.datetime'
Traceback (most recent call last):
  File "/usr/local/medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/queue.py#L263">medusa/search/queue.py</a>", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/usr/local/medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L492">medusa/search/core.py</a>", line 492, in search_for_needed_episodes
    if delay_search(best_result):
  File "/usr/local/medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L523">medusa/search/core.py</a>", line 523, in delay_search
    results['found_items'].sort(key=lambda d: int(d['date_added']))
  File "/usr/local/medusa/<a href="../blob/77b20916ab577b82112ebc624f816054788c63f2/medusa/search/core.py#L523">medusa/search/core.py</a>", line 523, in <lambda>
    results['found_items'].sort(key=lambda d: int(d['date_added']))
TypeError: int() argument must be a string or a number, not 'datetime.datetime'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
