### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'module' object has no attribute 'set_up_anidb_connection'

### ISSUE THREAD

**Issue by Thraxis** [pymedusa/Medusa#4135]
### INFO
**Python Version**: `2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]`
**Operating System**: `Linux-4.14.26-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@44439bc9609758f337f0db1fa92564f010eda820
**Link to Log**: https://gist.github.com/ca64b1a1995aa191e8763ca1d7a10065
### ERROR
<pre>
2018-04-28 22:15:58 ERROR    POSTPROCESSOR :: [44439bc] Exception generated: 'module' object has no attribute 'set_up_anidb_connection'
Traceback (most recent call last):
  File "/app/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/app/medusa/medusa/auto_post_processor.py", line 58, in run
    process_tv.ProcessResult(app.TV_DOWNLOAD_DIR, app.PROCESS_METHOD).process(force=force)
  File "/app/medusa/medusa/process_tv.py", line 148, in process
    ignore_subs=ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 336, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 537, in process_media
    self.result = processor.process()
  File "/app/medusa/medusa/post_processor.py", line 1211, in process
    self._add_to_anidb_mylist(self.file_path)
  File "/app/medusa/medusa/post_processor.py", line 530, in _add_to_anidb_mylist
    if helpers.set_up_anidb_connection():
AttributeError: 'module' object has no attribute 'set_up_anidb_connection'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Thraxis** [comment]
This breaks Anime post processing
