### ISSUE TITLE
[APP SUBMITTED]: WindowsError: [Error 3] The system cannot find the path specified: u''

### ISSUE THREAD

**Issue by MotleyC** [pymedusa/Medusa#4151]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/03b6b30e0942f09fdde49375a5bccf93
### ERROR
<pre>
2018-04-30 19:05:44 ERROR    SHOWQUEUE-REFRESH :: [77b2091] 76204: Error while refreshing show The Jetsons. Error: 
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\show_queue.py", line 640, in run
    self.show.write_metadata()
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 856, in write_metadata
    self.__write_episode_nfos()
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 885, in __write_episode_nfos
    cur_ep.create_meta_files()
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 1110, in create_meta_files
    self.__create_nfo(metadata_provider)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 1124, in __create_nfo
    result = metadata_provider.create_episode_metadata(self) or result
  File "C:\Medusa\Medusa\medusa\metadata\generic.py", line 254, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "C:\Medusa\Medusa\medusa\metadata\generic.py", line 469, in write_ep_file
    os.makedirs(nfo_file_dir)
  File "C:\Medusa\Medusa\medusa\init\filesystem.py", line 113, in patched_output
    return handle_output(f(*args, **kwargs))
  File "C:\Medusa\Python\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
  File "C:\Medusa\Medusa\medusa\init\filesystem.py", line 113, in patched_output
    return handle_output(f(*args, **kwargs))
WindowsError: [Error 3] The system cannot find the path specified: u''
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/4144
