### ISSUE TITLE
[APP SUBMITTED]: KeyError: 3276803

### ISSUE THREAD

**Issue by p0psicles** [pymedusa/Medusa#4165]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-4-amd64-x86_64-with-debian-9.2`
**Locale**: `UTF-8`
**Branch**: [feature/fix-setting-status-back-to-wanted](../tree/feature/fix-setting-status-back-to-wanted)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@6d15060f9e21f93ad568770f59e88a69b045895f
**Link to Log**: https://gist.github.com/27767b5148b706871b92d18903a1d702
### ERROR
<pre>
2018-05-05 17:02:03 ERROR    DAILYSEARCHER :: [6d15060] Exception generated: 3276803
Traceback (most recent call last):
  File "/opt/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/opt/medusa/medusa/search/daily.py", line 103, in run
    'status': common.statusStrings[cur_ep.status],
  File "/opt/medusa/medusa/numdict.py", line 43, in __getitem__
    return self.__class__.__missing__(self, key)
  File "/opt/medusa/medusa/common.py", line 879, in __missing__
    raise KeyError(key)  # ... so the key is invalid
KeyError: 3276803
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
#4157

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/23ec9e10e89fba634e251b13c394af27
### ERROR
<pre>
2018-06-19 16:01:00 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 71790: Error while refreshing show Crusade. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/e34d65333d7c64d3db12c8da640ca59e
### ERROR
<pre>
2018-06-19 15:59:57 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 70726: Error while refreshing show Babylon 5. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2017, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/3a4c496fce298e7d76f8837027bc51bf
### ERROR
<pre>
2018-06-19 15:59:33 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 257655: Error while refreshing show Arrow. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/aa69f13a2d81d559ddd59395e7aa2566
### ERROR
<pre>
2018-06-19 15:59:06 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 152831: Error while refreshing show Adventure Time. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/43f9fd1565e3173e8770f6bfb58b9652
### ERROR
<pre>
2018-06-19 15:41:28 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [c65ca26] DailySearchQueueItem Exception, error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/app/medusa/medusa/search/core.py", line 445, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/app/medusa/medusa/search/core.py", line 410, in wanted_episodes
    cur_status, cur_quality, series_obj, episode[b'manually_searched']
  File "/app/medusa/medusa/common.py", line 527, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/8eb68b695abd9b0f9799ec21912cfeb6
### ERROR
<pre>
2018-06-19 04:02:59 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 75978: Error while refreshing show Family Guy. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/20febd896c935a1ca9d56b98e992cf9a
### ERROR
<pre>
2018-06-19 04:02:56 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 295759: Error while refreshing show Supergirl. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/b17567827b732d8eb09604e719536f10
### ERROR
<pre>
2018-06-19 04:02:44 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 279121: Error while refreshing show The Flash (2014). Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/bb8356765a01bf9f1a391d8176c9b308
### ERROR
<pre>
2018-06-19 04:02:43 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 75734: Error while refreshing show Robot Chicken. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/0719c68caf243113567f785577ec7e39
### ERROR
<pre>
2018-06-19 04:01:53 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 153021: Error while refreshing show The Walking Dead. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/3cda8e7806e109f60868c93cd09dcaff
### ERROR
<pre>
2018-06-19 04:01:52 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 71663: Error while refreshing show The Simpsons. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2017, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Magnus010** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.15.0-23-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/467291e83647fdfeedc1cd32eb059884
### ERROR
<pre>
2018-06-19 16:26:25 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 153021: Error while refreshing show The Walking Dead. Error: 3276806
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 686, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by doul59** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@2d6485ce33c52ab0a495800d341467314111db3c
**Link to Log**: https://gist.github.com/c76f6c02d08a789f427cb85073f1c517
### ERROR
<pre>
2018-06-21 08:19:09 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [2d6485c] DailySearchQueueItem Exception, error: 3276806
Traceback (most recent call last):
  File "/media/NAS/Medusa/<a href="../blob/2d6485ce33c52ab0a495800d341467314111db3c/medusa/search/queue.py#L263">medusa/search/queue.py</a>", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/media/NAS/Medusa/<a href="../blob/2d6485ce33c52ab0a495800d341467314111db3c/medusa/search/core.py#L445">medusa/search/core.py</a>", line 445, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/media/NAS/Medusa/<a href="../blob/2d6485ce33c52ab0a495800d341467314111db3c/medusa/search/core.py#L410">medusa/search/core.py</a>", line 410, in wanted_episodes
    cur_status, cur_quality, series_obj, episode[b'manually_searched']
  File "/media/NAS/Medusa/<a href="../blob/2d6485ce33c52ab0a495800d341467314111db3c/medusa/common.py#L527">medusa/common.py</a>", line 527, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
@doul59 
Looks like your database didn't upgrade correctly.
Try this fix: https://github.com/pymedusa/Medusa/issues/4335#issuecomment-396208650

**Comment by doul59** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7
**Link to Log**: https://gist.github.com/aeb02cf50c0acea6e650462ea4aec6ca
### ERROR
<pre>
2018-06-24 14:46:10 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [32f7a7c] DailySearchQueueItem Exception, error: 3276806
Traceback (most recent call last):
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/search/queue.py#L263">medusa/search/queue.py</a>", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/search/core.py#L445">medusa/search/core.py</a>", line 445, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/search/core.py#L410">medusa/search/core.py</a>", line 410, in wanted_episodes
    cur_status, cur_quality, series_obj, episode[b'manually_searched']
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/common.py#L520">medusa/common.py</a>", line 520, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by doul59** [comment]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7
**Link to Log**: https://gist.github.com/88038c4e130a895fe5851eb5537bfee6
### ERROR
<pre>
2018-06-24 12:48:38 ERROR    SHOWQUEUE-REFRESH :: [32f7a7c] 66: Error while refreshing show The Big Bang Theory. Error: 3276806
Traceback (most recent call last):
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/show_queue.py#L686">medusa/show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/tv/series.py#L1713">medusa/tv/series.py</a>", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/tv/series.py#L986">medusa/tv/series.py</a>", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/tv/series.py#L1330">medusa/tv/series.py</a>", line 1330, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/media/NAS/Medusa/<a href="../blob/32f7a7c01b8896bc3bc559a6bfe9bb8aa35539e7/medusa/tv/episode.py#L2029">medusa/tv/episode.py</a>", line 2029, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by jstorgaard** [comment]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.9.0-6-amd64-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@7cfc79d5280b719c6288090fb805521dfc0402cd
**Link to Log**: https://gist.github.com/44dc00c5d23122415ff2b593261be911
### ERROR
<pre>
2018-07-04 14:30:13 ERROR    Thread_1 :: [7cfc79d] Exception generated: 3276806
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/server/web/core/base.py#L283">medusa/server/web/core/base.py</a>", line 283, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/server/web/manage/handler.py#L423">medusa/server/web/manage/handler.py</a>", line 423, in backlogOverview
    manually_searched=cur_result[b'manually_searched'])
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/tv/series.py#L2223">medusa/tv/series.py</a>", line 2223, in get_overview
    elif Quality.should_search(ep_status, ep_quality, self, manually_searched)[0]:
  File "/app/medusa/<a href="../blob/7cfc79d5280b719c6288090fb805521dfc0402cd/medusa/common.py#L520">medusa/common.py</a>", line 520, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
@jstorgaard 
>Looks like your database didn't upgrade correctly.
Try this fix: #4335 (comment)

**Comment by jstorgaard** [comment]
@medariox 
Looks better now. Thanks!
