### ISSUE TITLE
[APP SUBMITTED]: gaierror: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by poplolnman** [pymedusa/Medusa#4182]
### INFO
**Python Version**: `2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.16299`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@77b20916ab577b82112ebc624f816054788c63f2
**Link to Log**: https://gist.github.com/4c6aa96c0689cfab64fa01ba654e60c6
### ERROR
<pre>
2018-05-10 13:27:06 ERROR    CHECKVERSION :: [77b2091] Environment error: [Errno 11001] getaddrinfo failed
Traceback (most recent call last):
  File "C:\Users\Mat\Documents\Medusa-0.2.2\medusa\scheduler.py", line 93, in run
    self.action.run(self.force)
  File "C:\Users\Mat\Documents\Medusa-0.2.2\medusa\version_checker.py", line 67, in run
    self.list_remote_branches()
  File "C:\Users\Mat\Documents\Medusa-0.2.2\medusa\version_checker.py", line 357, in list_remote_branches
    app.GIT_REMOTE_BRANCHES = self.updater.list_remote_branches()
  File "C:\Users\Mat\Documents\Medusa-0.2.2\medusa\version_checker.py", line 981, in list_remote_branches
    gh = get_github_repo(app.GIT_ORG, app.GIT_REPO)
  File "C:\Users\Mat\Documents\Medusa-0.2.2\medusa\github_client.py", line 96, in get_github_repo
    return gh.get_organization(organization).get_repo(repo)
  File "C:\Users\Mat\Documents\Medusa-0.2.2\ext\github\MainClass.py", line 214, in get_organization
    "/orgs/" + login
  File "C:\Users\Mat\Documents\Medusa-0.2.2\ext\github\Requester.py", line 185, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\Users\Mat\Documents\Medusa-0.2.2\ext\github\Requester.py", line 231, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\Users\Mat\Documents\Medusa-0.2.2\ext\github\Requester.py", line 284, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\Users\Mat\Documents\Medusa-0.2.2\ext\github\Requester.py", line 309, in __requestRaw
    requestHeaders
  File "C:\Python27\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "C:\Python27\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "C:\Python27\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 11001] getaddrinfo failed
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
According to StackOverflow, looks like you might be having issues resolving hostnames (`github.com` in this case).
This may be related to your DNS configuration, or your proxy configuration, if you're using one.

**Comment by sharkykh** [comment]
No response.
