### ISSUE TITLE
Bug after updating to latest version

### ISSUE THREAD

**Issue by desapoint** [pymedusa/Medusa#4213]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:Windows**
**What you did:Updated Medusa**
**What happened:Stopped working**
**What you expected:**
**Logs:**
```
Error

{0: u'N/A', 32768: u'Unknown', 2: u'SD DVD', 4: u'720p HDTV', None: u'None', 4096: u'8K UHD TV', 1: u'SDTV', 8: u'RawHD', 64: u'1080p WEB-DL', 128: u'720p BluRay', 256: u'1080p BluRay', 16384: u'8K UHD BluRay', 16: u'1080p HDTV', 32: u'720p WEB-DL', 8192: u'8K UHD WEB-DL', 512: u'4K UHD TV', 1024: u'4K UHD WEB-DL', 2048: u'4K UHD BluRay'} is not JSON serializable
Traceback

Traceback (most recent call last):
File "C:\Medusa\Medusa\ext\tornado\web.py", line 1541, in _execute result = method(*self.path_args, **self.path_kwargs)
File "C:\Medusa\Medusa\medusa\server\web\core\authentication.py", line 65, in get self.finish(t.render(title='Login', header='Login', topmenu='login'))
File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 155, in render
File "C:\Medusa\Medusa\ext\mako\template.py", line 471, in render_unicode as_unicode=True)
File "C:\Medusa\Medusa\ext\mako\runtime.py", line 838, in _render **_kwargs_for_callable(callable_, data))
File "C:\Medusa\Medusa\ext\mako\runtime.py", line 873, in _render_context _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "C:\Medusa\Medusa\ext\mako\runtime.py", line 899, in _exec_template callable_(context, *args, **kwargs)
File "C:\Medusa\Data\cache\mako\layouts\main.mako.py", line 191, in render_body runtime._include_file(context, u'/vue-components/quality-chooser.mako', _template_uri)
File "C:\Medusa\Medusa\ext\mako\runtime.py", line 761, in _include_file callable_(ctx, **kwargs)
File "C:\Medusa\Data\cache\mako\vue-components\quality-chooser.mako.py", line 61, in render_body __M_writer(unicode(convert(Quality.qualityStrings)))
File "C:\Medusa\Data\cache\mako\vue-components\quality-chooser.mako.py", line 51, in convert return json.dumps(obj)
File "C:\Medusa\Python\lib\json\__init__.py", line 244, in dumps return _default_encoder.encode(obj)
File "C:\Medusa\Python\lib\json\encoder.py", line 207, in encode chunks = self.iterencode(o, _one_shot=True)
File "C:\Medusa\Python\lib\json\encoder.py", line 270, in iterencode return _iterencode(o, 0)
File "C:\Medusa\Python\lib\json\encoder.py", line 184, in default raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {0: u'N/A', 32768: u'Unknown', 2: u'SD DVD', 4: u'720p HDTV', None: u'None', 4096: u'8K UHD TV', 1: u'SDTV', 8: u'RawHD', 64: u'1080p WEB-DL', 128: u'720p BluRay', 256: u'1080p BluRay', 16384: u'8K UHD BluRay', 16: u'1080p HDTV', 32: u'720p WEB-DL', 8192: u'8K UHD WEB-DL', 512: u'4K UHD TV', 1024: u'4K UHD WEB-DL', 2048: u'4K UHD BluRay'} is not JSON serializable
Request Info

body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /login/?next=%2Ferrorlogs%2F
query_arguments: {'next': ['/errorlogs/']}
_start_time: 1526576658.48
headers: Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0 Host: 192.168.1.19:8082 Referer: http://192.168.1.19:8082/login/?next=%2Fhome Cache-Control: max-age=0 Upgrade-Insecure-Requests: 1
host: 192.168.1.19:8082
version: HTTP/1.1
server_connection:
host_name: 192.168.1.19
_finish_time: None
query: next=%2Ferrorlogs%2F
arguments: {'next': ['/errorlogs/']}
path: /login/
_cookies:
method: GET
remote_ip: 192.168.1.19
```

**Comment by p0psicles** [comment]
@medariox it doesnt like None: none.

**Comment by desapoint** [comment]
How to fix it? I can't access medusa at all

**Comment by sharkykh** [comment]
Try restarting Medusa. If you can't access the Web UI,  kill the python process.

**Comment by p0psicles** [comment]
Well it shouldn't prevent you from starting medusa. Are you maybe trying to access the same page?
Try just navigating to ../home

**Comment by udochrist** [comment]
Same here (o linux). medusa seems to work however. the "ERROR" below could not be created automatically as issue on github FWIW.


Branch: master
Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
Version: 0.2.4
Database: 44.9

```
2018-05-17 21:32:27 ERROR    Thread_14 :: [212cd1c] Exception generated: {0: u'N/A', 32768: u'Unknown', 2: u'SD DVD', 4096: u'8K UHD TV', 4: u'720p HDTV', None: u'None', 1: u'SDTV', 8: u'RawHD', 64: u'1080p WEB-DL', 128: u'720p BluRay', 256: u'1080p BluRay', 16384: u'8K UHD BluRay', 16: u'1080p HDTV', 32: u'720p WEB-DL', 8192: u'8K UHD WEB-DL', 512: u'4K UHD TV', 1024: u'4K UHD WEB-DL', 2048: u'4K UHD BluRay'} is not JSON serializable
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 285, in async_call
    except Exception as e:
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/home/handler.py", line 740, in update
    controller='home', action='restart')
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 155, in render
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/mako/template.py", line 471, in render_unicode
    as_unicode=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/usr/local/sickbeard-custom/var/cache/mako/layouts/main.mako.py", line 191, in render_body
    runtime._include_file(context, u'/vue-components/quality-chooser.mako', _template_uri)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/mako/runtime.py", line 761, in _include_file
    callable_(ctx, **kwargs)
  File "/usr/local/sickbeard-custom/var/cache/mako/vue-components/quality-chooser.mako.py", line 61, in render_body
    __M_writer(unicode(convert(Quality.qualityStrings)))
  File "/usr/local/sickbeard-custom/var/cache/mako/vue-components/quality-chooser.mako.py", line 51, in convert
    return json.dumps(obj)
  File "/usr/local/python/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/python/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/python/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {0: u'N/A', 32768: u'Unknown', 2: u'SD DVD', 4096: u'8K UHD TV', 4: u'720p HDTV', None: u'None', 1: u'SDTV', 8: u'RawHD', 64: u'1080p WEB-DL', 128: u'720p BluRay', 256: u'1080p BluRay', 16384: u'8K UHD BluRay', 16: u'1080p HDTV', 32: u'720p WEB-DL', 8192: u'8K UHD WEB-DL', 512: u'4K UHD TV', 1024: u'4K UHD WEB-DL', 2048: u'4K UHD BluRay'} is not JSON serializable
2018-05-17 21:32:27 INFO     Thread_14 :: [212cd1c] TypeError: {0: u'N/A', 32768: u'Unknown', 2: u'SD DVD', 4096: u'8K UHD TV', 4: u'720p HDTV', None: u'None', 1: u'SDTV', 8: u'RawHD', 64: u'1080p WEB-DL', 128: u'720p BluRay', 256: u'1080p BluRay', 16384: u'8K UHD BluRay', 16: u'1080p HDTV', 32: u'720p WEB-DL', 8192: u'8K UHD WEB-DL', 512: u'4K UHD TV', 1024: u'4K UHD WEB-DL', 2048: u'4K UHD BluRay'} is not JSON serializable
```

**Comment by sharkykh** [comment]
@udochrist This should happen once, because when you update Medusa it changes some files, but others are only updated after the app restarts. It should work fine after that.
If not, restart Medusa manually.

> however. the "ERROR" below could not be created automatically as issue on github FWIW.

what do you mean? why not? can you find anything in the debug logs about why the issue submitter couldn't post the issue?

**Comment by desapoint** [comment]
Restarting everything fixed it!
