### ISSUE TITLE
[APP SUBMITTED]: OperationalError: database or disk is full

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#4223]
### INFO
**Python Version**: `2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.13-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@1a8dc66c7ec9231be0d3444710e476437c9ae1c8
**Link to Log**: https://gist.github.com/fe95f3ffe64693d13162c85c8388b9ed
### ERROR
<pre>
2018-05-20 03:10:47 ERROR    SHOWQUEUE-SEASON-UPDATE :: [1a8dc66] Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 892, in run
    self.show.save_to_db()
  File "/app/medusa/medusa/tv/series.py", line 1925, in save_to_db
    main_db_con.upsert('tv_shows', new_value_dict, control_value_dict)
  File "/app/medusa/medusa/db.py", line 342, in upsert
    self.action(query, list(itervalues(valueDict)) + list(itervalues(keyDict)))
  File "/app/medusa/medusa/db.py", line 274, in action
    self.connection.commit()
OperationalError: database or disk is full
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 892, in run
    self.show.save_to_db()
  File "/app/medusa/medusa/tv/series.py", line 1925, in save_to_db
    main_db_con.upsert('tv_shows', new_value_dict, control_value_dict)
  File "/app/medusa/medusa/db.py", line 342, in upsert
    self.action(query, list(itervalues(valueDict)) + list(itervalues(keyDict)))
  File "/app/medusa/medusa/db.py", line 274, in action
    self.connection.commit()
OperationalError: database or disk is full
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/pymedusa/Medusa/issues/4222
