### ISSUE TITLE
[APP SUBMITTED]: ProtocolError: (u'api.broadcasthe.net/', 524, 'Origin Time-out', <httplib.HTTPMessage instance at 0x65effda0>)

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#4226]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@f1c04d4bbeec508f8e8d59648f9c30858fa020a9
**Link to Log**: https://gist.github.com/447b35a960c9507d72e1fa46f021ee07
### ERROR
<pre>
2018-05-20 18:06:29 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: [f1c04d4] JSON-RPC protocol error while accessing provider. Error: ''
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/f1c04d4bbeec508f8e8d59648f9c30858fa020a9/medusa/providers/torrent/json/btn.py#L246">medusa/providers/torrent/json/btn.py</a>", line 246, in _api_call
    int(offset)
  File "/home/pi/Medusa/<a href="../blob/f1c04d4bbeec508f8e8d59648f9c30858fa020a9/ext/jsonrpclib/jsonrpc.py#L650">ext/jsonrpclib/jsonrpc.py</a>", line 650, in __call__
    return self.__send(self.__name, args)
  File "/home/pi/Medusa/<a href="../blob/f1c04d4bbeec508f8e8d59648f9c30858fa020a9/ext/jsonrpclib/jsonrpc.py#L531">ext/jsonrpclib/jsonrpc.py</a>", line 531, in _request
    response = self._run_request(request)
  File "/home/pi/Medusa/<a href="../blob/f1c04d4bbeec508f8e8d59648f9c30858fa020a9/ext/jsonrpclib/jsonrpc.py#L564">ext/jsonrpclib/jsonrpc.py</a>", line 564, in _run_request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/pi/Medusa/<a href="../blob/f1c04d4bbeec508f8e8d59648f9c30858fa020a9/ext/jsonrpclib/jsonrpc.py#L387">ext/jsonrpclib/jsonrpc.py</a>", line 387, in single_request
    response.msg)
ProtocolError: (u'api.broadcasthe.net/', 524, 'Origin Time-out', <httplib.HTTPMessage instance at 0x65effda0>)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/commit/11f3b5097c4dbfa0ac814b24fe8ce07546afcec5

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [bugfix/imdb-none](../tree/bugfix/imdb-none)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4e21883bbedad8c4346c14b063ade74d1ac31893
**Link to Log**: https://gist.github.com/52265d085f9dcb7a4d203201ef191e5c
### ERROR
<pre>
2018-08-29 01:56:47 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BTN] :: [4e21883] JSON-RPC protocol error while accessing provider. Error: u'api.broadcasthe.net/'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/4e21883bbedad8c4346c14b063ade74d1ac31893/medusa/providers/torrent/json/btn.py#L251">medusa/providers/torrent/json/btn.py</a>", line 251, in _api_call
    int(offset)
  File "/home/pi/Medusa/<a href="../blob/4e21883bbedad8c4346c14b063ade74d1ac31893/ext/jsonrpclib/jsonrpc.py#L650">ext/jsonrpclib/jsonrpc.py</a>", line 650, in __call__
    return self.__send(self.__name, args)
  File "/home/pi/Medusa/<a href="../blob/4e21883bbedad8c4346c14b063ade74d1ac31893/ext/jsonrpclib/jsonrpc.py#L531">ext/jsonrpclib/jsonrpc.py</a>", line 531, in _request
    response = self._run_request(request)
  File "/home/pi/Medusa/<a href="../blob/4e21883bbedad8c4346c14b063ade74d1ac31893/ext/jsonrpclib/jsonrpc.py#L564">ext/jsonrpclib/jsonrpc.py</a>", line 564, in _run_request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/pi/Medusa/<a href="../blob/4e21883bbedad8c4346c14b063ade74d1ac31893/ext/jsonrpclib/jsonrpc.py#L387">ext/jsonrpclib/jsonrpc.py</a>", line 387, in single_request
    response.msg)
ProtocolError: (u'api.broadcasthe.net/', 524, 'Timeout', <httplib.HTTPMessage instance at 0x5aee8580>)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
@sharkykh

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5081
