### ISSUE TITLE
SEARCHQUEUE-DAILY-SEARCH :: [212cd1c] DailySearchQueueItem Exception, error: nonnumeric port: 'QnV'

### ISSUE THREAD

**Issue by Roofuzz** [pymedusa/Medusa#4270]
Hello! Here's my report, hope you can help me out :) Thanks in advance for the help and replies!

**Branch/Commit: Master
**OS: Synology/Linux
Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
Version: 0.2.4
Python Version: | 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]

**What you did: Forced a daily search
**What happened: Error , NZB's not being send to NZBGet
**What you expected: Snatched/found episodes should be send to NZBGet to be processed, files don't end up in NZBGet.  Don't know if there is another post about this already , but is this the same as : https://github.com/pymedusa/Medusa/pull/3832 ?

**Logs:**
```
2018-05-29 10:31:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NZBPlanet.net] :: [212cd1c] 305719: 'Big Little Lies' S01E07 status is: 'Wanted'. Accepting result with quality 'SDTV'. Reason: Current status is 'WANTED'. Accepting result with quality 'SDTV'
2018-05-29 10:31:47 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [NZBPlanet.net] :: [212cd1c] Picked Big.Little.Lies.S01E07.BDRip.x264-DEMAND as the best
2018-05-29 10:31:47 INFO     SEARCHQUEUE-DAILY-SEARCH :: [212cd1c] Downloading blindspot.s03e22.1080p.web.x264-tbs with size: 1.38 GB from NZBPlanet.net

2018-05-29 10:31:47 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [212cd1c] DailySearchQueueItem Exception, error: nonnumeric port: 'QnV'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/search/queue.py", line 289, in run
    self.success = snatch_episode(result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/search/core.py", line 147, in snatch_episode
    result_downloaded = **********.sendNZB(result, is_proper)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/clients/nzb/**********.py", line 92, in sendNZB
    if not NZBConnection(url):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/clients/nzb/**********.py", line 29, in NZBConnection
    if nzbGetRPC.writelog('INFO', 'Medusa connected to test connection.'):
  File "/var/packages/python/target/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/var/packages/python/target/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/var/packages/python/target/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/var/packages/python/target/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    h = self.make_connection(host)
  File "/var/packages/python/target/lib/python2.7/xmlrpclib.py", line 1389, in make_connection
    self._connection = host, httplib.HTTPConnection(chost)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 736, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 777, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
InvalidURL: nonnumeric port: 'QnV'

**Comment by sharkykh** [comment]
@Roofuzz 
I believe your the NZBGet configuration you entered is somehow incorrect, specifically - the `host:port` setting. Could you check that it's in the correct format?
It should be `localhost:port` or `ip:port`.

**Comment by Roofuzz** [comment]
@sharkykh 
I have checked the settings but i can't find any mistypes in the field as you pointed out (see screenshot).
As i see in the logs, Medusa can connect to my device (Medusa connected to test connection). Can it be Python version installed ?

I don't know where the problem lies atm.. thanks tho for the attention.
![medusa_nzbget](https://user-images.githubusercontent.com/13979197/40714078-ea92de68-6401-11e8-85d8-7196c060e322.JPG)

**Comment by sharkykh** [comment]
Python version is fine.
The special characters is a good idea. Can you try changing the password?

**Comment by Roofuzz** [comment]
Hmm, well i am asshamed to tell but changing the NZBget password worked.
Everything is now being pumped to NZBGet and my internetconnection is busy for the next coming day lol..

Weird that some special characters break the process.. still weird that Medusa could (or says) it could connect with the test server button, ah well problem solved i supose! Thanks for the help @sharkykh

**Comment by sharkykh** [comment]
@Roofuzz Could you please give me an example password you had with special characters?
If you can give me the your original password with the alphanumeric characters changed that is fine too.
I can't seem to replicate the issue.

**Comment by Roofuzz** [comment]
Hi @sharkykh ,

I changed the password to a password without special characters (just upper and lowercase) and that seemed to do the trick. All things in backlog, daily searches now end-up in the NZBget queue!

I am happy about that, since it was just a simple solution, but sad that the strong password was cousing the issue. And what you said about the "test connection" button is correct, it only verifies credentials i guess.

Sample with special chars : PnV#%1Gapp>6
Sample without special chars : PnVGdap6

Hope it contributes to something usefull.

**Comment by sharkykh** [comment]
I still can't reproduce it... Sorry.

**Comment by Roofuzz** [comment]
@sharkykh That's a bummer, but happens. 
Think we can close the thread and hope it's just me :) 

Thank you for taking the time to reproduce it and check out my error!
I'll stick with "normal" passwords for now
