### ISSUE TITLE
Animebytes daily search throwing error - local variable 'title' referenced before assignment Traceback

### ISSUE THREAD

**Issue by LiverBlow** [pymedusa/Medusa#4291]
I am seeing this error everytime a search is conducted in my logs. 

**Branch/Commit:**  Branch: master, Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
**OS:** Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
**What you did:** Daily search was triggered 
**What happened:** Animebytes throwing up an error 
**What you expected:** No error to be thrown up
**Logs:
```
2018-05-31 11:30:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [212cd1c] DailySearchQueueItem Exception, error: local variable 'title' referenced before assignment
Traceback (most recent call last):
  File "/home/**********/apps/medusa/medusa/search/queue.py", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/home/**********/apps/medusa/medusa/search/core.py", line 462, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/home/hd21/**********/apps/medusa/medusa/tv/cache.py", line 202, in update_cache
    data = self._get_rss_data()
  File "/home/**********/apps/medusa/medusa/tv/cache.py", line 185, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)}
  File "/home/**********/apps/medusa/medusa/providers/torrent/html/animebytes.py", line 112, in search
    results += self.parse(response.text, mode)
  File "/home/**********/apps/medusa/medusa/providers/torrent/html/animebytes.py", line 241, in parse
    'title': title,
UnboundLocalError: local variable 'title' referenced before assignment
2018-05-31 10:49:47 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [212cd1c] Failed parsing provider.
Traceback (most recent call last):
  File "/home/**********/apps/medusa/medusa/providers/torrent/html/animebytes.py", line 257, in parse
    episode = re.match('^Episode.([0-9]+)', info).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by p0psicles** [comment]
Can you check the develop branch?

**Comment by LiverBlow** [comment]
I can't actually as I don't have the necessary permissions.

**Comment by medariox** [comment]
Then you have no other choice but to wait for the next release.

**Comment by LiverBlow** [comment]
No problem, just wanted to bring this to your attention :)
