### ISSUE TITLE
Massedit showing blank white page when change for root directories.

### ISSUE THREAD

**Issue by Myster-Gh0s7** [pymedusa/Medusa#4300]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:**
**OS:** Windows 10
**What you did:** When i tries to change the root directories i get white blank page and doesn't update or change the settings.
**What happened:** One of my disk is full so i tried to change the root directories for all TV shows and won't change. Please help.
**What you expected:** Obviously, to change the root directory for all my TV shows.
**Logs:**
```
 11:19:54 WARNING  CHECKVERSION :: [212cd1c] git fetch --prune origin returned : fatal: unable to access 'https://github.com/pymedusa/Medusa/': Couldn't resolve host 'github.com'
2018-06-03 11:19:54 WARNING  CHECKVERSION :: [212cd1c] Unable to contact github, can't check for update
2018-06-03 11:49:42 INFO     Thread_3 :: [212cd1c] Broken providers found: [u'']
2018-06-03 11:50:16 INFO     Thread_6 :: [212cd1c] For show Better Call Saul changing dir from G:\qTorr\Better Call Saul to D:\Tv Shows\Better Call Saul
2018-06-03 11:50:16 INFO     Thread_6 :: [212cd1c] Changing show location to: D:\Tv Shows\Better Call Saul
2018-06-03 11:50:16 WARNING  Thread_6 :: [212cd1c] New location 'D:\Tv Shows\Better Call Saul' does not exist. Enable setting 'Create missing show dirs'
2018-06-03 11:50:16 ERROR    Thread_6 :: [212cd1c] Exception generated: Invalid show folder!
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 283, in async_call
    result = function(**kwargs)
  File "C:\Medusa\Medusa\medusa\server\web\manage\handler.py", line 688, in massEditSubmit
    directCall=True)
  File "C:\Medusa\Medusa\medusa\server\web\home\handler.py", line 1665, in editShow
    series_obj.location = new_location
  File "C:\Medusa\Medusa\medusa\tv\base.py", line 57, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 393, in location
    raise ShowDirectoryNotFoundException(u'Invalid show folder!')
ShowDirectoryNotFoundException: Invalid show folder!

```

**Comment by sharkykh** [comment]
`New location 'D:\Tv Shows\Better Call Saul' does not exist. Enable setting 'Create missing show dirs'`
@Myster-Gh0s7 Medusa will not move the files for you. If you want to move TV shows, move them first then change their location in Medusa.

I agree it shouldn't be a white page though.

**Comment by sharkykh** [comment]
Fixed in develop.
