### ISSUE TITLE
Error When Adding Show

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#4306]
Hi,

I am getting this issue when i try and add shows. I have done it now with 2 different Indexes and still the same issue

Branch: master
Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
What you did: Add A Show
What happened: Errors In Logs
What you expected: Show To Add With No issues
```
2018-06-06 00:57:30 ERROR    SHOWQUEUE-ADD :: [212cd1c] Error loading IMDb info: Title not found. tt5834204 is a redirection imdb id
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/show_queue.py", line 542, in run
    self.show.load_imdb_info()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/series.py", line 1530, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/imdbpie.py", line 77, in get_title
    self._redirection_title_check(imdb_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/imdbpie.py", line 300, in _redirection_title_check
    msg='{0} is a redirection imdb id'.format(imdb_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/imdbpie.py", line 323, in _title_not_found
    raise LookupError('Title not found.{0}'.format(msg))
LookupError: Title not found. tt5834204 is a redirection imdb id
```

Thanks

**Comment by sharkykh** [comment]
Already fixed in develop: #4253.

**Comment by HPMSGEN8** [comment]
@sharkykh Thanks alot is there an ETA when Dev will get Merged ? If not i will try the Dev Branch.

**Comment by sharkykh** [comment]
@HPMSGEN8 Next version is planned for this weekend: [v0.2.5 Milestone](https://github.com/pymedusa/Medusa/milestone/37)

**Comment by HPMSGEN8** [comment]
@sharkykh Thanks :)
