### ISSUE TITLE
Add Existing Show(s) -- Error IMDB?

### ISSUE THREAD

**Issue by jun6lee** [pymedusa/Medusa#4318]
**Branch/Commit:** Master / v0.2.4
**OS:** QNAP QTS 4.3.4 (Unix-Based)
**What you did:**
Shows -- Add Shows -- Add Existing Shows -- Choose 1 or more.
Leaving as All Indexers TVDB2 or TMDB (tried these 3).
Next -- Choose Quality etc --> Submit.

**What happened:**
Returns to Home with: "Oops, You have reached this page by accident, please check the url."
Refreshing shows that it does add ONE of the shows, but only one.

**What you expected:**
Returning to my other ticked shows, to pick their qualities, subtitles etc
ie; not having to do this one show at a time.

Looking at below logs, I don't know if IMDB should be relevant.

**Logs:**
```

`2018-06-09 09:40:06 INFO     SHOWQUEUE-ADD :: [212cd1c] Setting all previously aired episodes to the specified status: Skipped
2018-06-09 09:40:02 INFO     SHOWQUEUE-ADD :: [212cd1c] 344186: Unable to find the show in the database
2018-06-09 09:39:56 INFO     SHOWQUEUE-ADD :: [212cd1c] TVDBv2: {u'session': <medusa.session.core.MedusaSession object at 0x7fc878fa8890>, u'cache': u'/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/cache/indexers/TVDBv2', u'language': u'en', u'use_zip': True}
2018-06-09 09:39:56 INFO     SHOWQUEUE-ADD :: [212cd1c] Starting to add show by ShowDir: /share/Download/@TV/Dietland
2018-06-09 09:39:15 INFO     Thread_0 :: [212cd1c] Broken providers found: [u'']
2018-06-09 09:33:09 INFO     Thread_4 :: [212cd1c] No update needed
2018-06-09 09:33:06 INFO     Thread_4 :: [212cd1c] Checking for updates using SOURCE
2018-06-09 09:30:52 INFO     SHOWQUEUE-ADD :: [212cd1c] Cache check completed
2018-06-09 09:30:50 INFO     SHOWQUEUE-ADD :: [212cd1c] Copying from /share/Download/@TV/Younger/poster.jpg to /share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/cache/images/tvdb/280706.poster.jpg
2018-06-09 09:30:50 INFO     SHOWQUEUE-ADD :: [212cd1c] 280706: Updating NFOs for show with new indexer info
2018-06-09 09:30:39 INFO     SHOWQUEUE-ADD :: [212cd1c] Selected poster for series 280706 (score=0.5, score_bay=0.0, rating=0, votes=0, res=680x1000): http://thetvdb.com/banners/posters/280706-7.jpg
2018-06-09 09:30:39 INFO     SHOWQUEUE-ADD :: [212cd1c] Selected fanart for series 280706 (score=1.0, score_bay=0.0, rating=0, votes=0, res=1920x1080): http://thetvdb.com/banners/fanart/original/280706-1.jpg
2018-06-09 09:30:34 INFO     SHOWQUEUE-ADD :: [212cd1c] Building internal name cache for Younger
2018-06-09 09:30:34 INFO     SHOWQUEUE-ADD :: [212cd1c] Finished processing 2783 scene exceptions.
2018-06-09 09:30:34 INFO     SHOWQUEUE-ADD :: [212cd1c] Updating exception_cache and exception_season_cache
2018-06-09 09:30:32 ERROR    SHOWQUEUE-ADD :: [212cd1c] Error loading IMDb info: Title not found. tt3288518 is a redirection imdb id
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/show_queue.py", line 542, in run
    self.show.load_imdb_info()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/tv/series.py", line 1530, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/ext/imdbpie/imdbpie.py", line 77, in get_title
    self._redirection_title_check(imdb_id)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/ext/imdbpie/imdbpie.py", line 300, in _redirection_title_check
    msg='{0} is a redirection imdb id'.format(imdb_id)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/ext/imdbpie/imdbpie.py", line 323, in _title_not_found
    raise LookupError('Title not found.{0}'.format(msg))
LookupError: Title not found. tt3288518 is a redirection imdb id`

```

**Comment by sharkykh** [comment]
Both the IMDB issue and the issue with adding existing shows are fixed in develop.
The next version will have those fixes.
References: #4253 & #4298
