### ISSUE TITLE
Overflow Error: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by elrock** [pymedusa/Medusa#4326]
Branch Master
Commit c65ca26

Error below prevents Medusa from launching

```
2018-06-10 09:31:33 ERROR    MAIN :: [c65ca26] DB error: OverflowError('Python int too large to convert to SQLite INTEGER',)
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OverflowError: Python int too large to convert to SQLite INTEGER
2018-06-10 09:31:33 ERROR    MAIN :: [c65ca26] Error in ShiftQualities: error b'Python int too large to convert to SQLite INTEGER'
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 465, in _processUpgrade
    instance.execute()
  File "/opt/medusa/medusa/databases/main_db.py", line 769, in execute
    self.shift_tv_qualities()
  File "/opt/medusa/medusa/databases/main_db.py", line 797, in shift_tv_qualities
    [new_quality, quality]
  File "/opt/medusa/medusa/db.py", line 284, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OverflowError: Python int too large to convert to SQLite INTEGER
Traceback (most recent call last):
  File "start.py", line 9, in <module>
    main()
  File "/opt/medusa/medusa/__main__.py", line 2157, in main
    application.start(sys.argv[1:])
  File "/opt/medusa/medusa/__main__.py", line 339, in start
    self.initialize(console_logging=self.console_logging)
  File "/opt/medusa/medusa/__main__.py", line 1097, in initialize
    db.upgradeDatabase(main_db_con, main_db.InitialSchema)
  File "/opt/medusa/medusa/db.py", line 452, in upgradeDatabase
    _processUpgrade(connection, schema)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 475, in _processUpgrade
    _processUpgrade(connection, upgradeSubClass)
  File "/opt/medusa/medusa/db.py", line 465, in _processUpgrade
    instance.execute()
  File "/opt/medusa/medusa/databases/main_db.py", line 769, in execute
    self.shift_tv_qualities()
  File "/opt/medusa/medusa/databases/main_db.py", line 797, in shift_tv_qualities
    [new_quality, quality]
  File "/opt/medusa/medusa/db.py", line 284, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OverflowError: Python int too large to convert to SQLite INTEGER
```

**Comment by elrock** [comment]
2.7.13
(I believe I also have some version of 3.n installed but it's not active. This is on a Raspberry Pi.)

**Comment by medariox** [comment]
Can you please join our IRC channel on `freenode #pymedusa` - we need your `main.db` to see what's wrong. Sadly we can't help you without the DB.

**Comment by elrock** [comment]
Ok, will join in a bit. I think it could be a corrupted database--the
regular update stalled so I did a manual git pull.

**Comment by medariox** [comment]
The issue was caused because the upgrade process was interrupted. If you have a similar issue, restore from a backup and let the upgrade process finish entirely (even if it takes some time).
