### ISSUE TITLE
'NoneType' object has no attribute 'findall'

### ISSUE THREAD

**Issue by DarkSupremo** [pymedusa/Medusa#4344]
Found this error many times in the log, reseted the log yesterday to see if it was already fixed problem, and it still happens..

**Branch/Commit:** develop
**OS:** Windows
**Logs:**
```
2018-06-11 19:52:16 ERROR    SEARCHQUEUE-BACKLOG-290853 :: [7cb2039] Checking AniDB scene exceptions update failed for Dragon Ball Super. Error: 'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "D:\Programacao\Pessoal\Python\Medusa\medusa\scene_exceptions.py", line 409, in _get_anidb_exceptions
    autoCorrectName=True
  File "D:\Programacao\Pessoal\Python\Medusa\lib\adba\aniDBAbstracter.py", line 131, in __init__
    self.aid = self.tvDBMap.get_anidb_for_tvdb(self.tvdb_id)
  File "D:\Programacao\Pessoal\Python\Medusa\lib\adba\aniDBtvDBmaper.py", line 38, in get_anidb_for_tvdb
    return self._get_x_for_y(tvdb_id,"tvdbid","anidbid")
  File "D:\Programacao\Pessoal\Python\Medusa\lib\adba\aniDBtvDBmaper.py", line 44, in _get_x_for_y
    for anime in self.xmlMap.findall("anime"):
AttributeError: 'NoneType' object has no attribute 'findall'
```

**Comment by sharkykh** [comment]
@DarkSupremo 
Can you please check if you have the following file?
`D:\Programacao\Pessoal\Python\Medusa\lib\adba\anime-list.xml`

**Comment by sharkykh** [comment]
@DarkSupremo 
Yeah, it seemed like an edge case.
Basically the aniDB library we use downloads this file if it doesn't exist, so it should always be available, unless the file was manually removed while Medusa was running.

I'm going to close this since I believe a restart should fix this issue if it happens again.
But if you know anything that can point me in the right direction,
like if you did some config changes before that error popped up or something?
