### ISSUE TITLE
[APP SUBMITTED]: 

### ISSUE THREAD

**Issue by 007revad** [pymedusa/Medusa#4369]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/630e44e3868f93cdf7fb75418c951727
### ERROR
<pre>
2018-06-14 15:13:45 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 256002: Error while refreshing show America's Book of Secrets. Error: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/256002/actors
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/show_queue.py#L686">SickBeard/medusa/show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/series.py#L1713">SickBeard/medusa/tv/series.py</a>", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/series.py#L986">SickBeard/medusa/tv/series.py</a>", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/series.py#L1352">SickBeard/medusa/tv/series.py</a>", line 1352, in make_ep_from_file
    root_ep.create_meta_files()
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/episode.py#L1105">SickBeard/medusa/tv/episode.py</a>", line 1105, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/episode.py#L1128">SickBeard/medusa/tv/episode.py</a>", line 1128, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/metadata/generic.py#L331">SickBeard/medusa/metadata/generic.py</a>", line 331, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/metadata/generic.py#L501">SickBeard/medusa/metadata/generic.py</a>", line 501, in save_thumbnail
    thumb_data = self._retrieve_show_image(u'thumbnail', ep_obj.series, ep_obj)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/metadata/generic.py#L738">SickBeard/medusa/metadata/generic.py</a>", line 738, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/metadata/generic.py#L863">SickBeard/medusa/metadata/generic.py</a>", line 863, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/indexers/indexer_base.py#L399">SickBeard/medusa/indexers/indexer_base.py</a>", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py#L611">SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 611, in _get_show_data
    self._parse_actors(sid)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/indexers/tvdbv2/fallback.py#L136">SickBeard/medusa/indexers/tvdbv2/fallback.py</a>", line 136, in __call__
    return self.func(*args, **kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py#L545">SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 545, in _parse_actors
    actors = self.config['session'].series_api.series_id_actors_get(sid)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/apis/series_api.py#L282">SickBeard/lib/tvdbapiv2/apis/series_api.py</a>", line 282, in series_id_actors_get
    callback=params.get('callback'))
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/api_client.py#L295">SickBeard/lib/tvdbapiv2/api_client.py</a>", line 295, in call_api
    response_type, auth_settings, callback)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/api_client.py#L122">SickBeard/lib/tvdbapiv2/api_client.py</a>", line 122, in __call_api
    post_params=post_params, body=body)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/api_client.py#L315">SickBeard/lib/tvdbapiv2/api_client.py</a>", line 315, in request
    headers=headers)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/rest.py#L70">SickBeard/lib/tvdbapiv2/rest.py</a>", line 70, in get
    query_params=query_params)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/rest.py#L63">SickBeard/lib/tvdbapiv2/rest.py</a>", line 63, in request
    raise ApiException(status=status, reason=msg)
ApiException: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/256002/actors

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fexofenadine** [comment]
I had the same, but for a different show (Cops)

And, not sure if this is related, but my machine snatched a bunch of episodes of random shows that had already been marked as Downloaded monts/years previously

I also use a Synology, latest firmware, DSM 6.2

**Comment by 007revad** [comment]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.102-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/11b8800f83f3f60d9b80cdde927f7d20
### ERROR
<pre>
2018-06-14 20:17:29 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 270202: Error while refreshing show Street Outlaws. Error: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/270202/actors
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/show_queue.py#L686">SickBeard/medusa/show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/series.py#L1713">SickBeard/medusa/tv/series.py</a>", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/series.py#L986">SickBeard/medusa/tv/series.py</a>", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/series.py#L1352">SickBeard/medusa/tv/series.py</a>", line 1352, in make_ep_from_file
    root_ep.create_meta_files()
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/episode.py#L1105">SickBeard/medusa/tv/episode.py</a>", line 1105, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/tv/episode.py#L1128">SickBeard/medusa/tv/episode.py</a>", line 1128, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/metadata/generic.py#L331">SickBeard/medusa/metadata/generic.py</a>", line 331, in create_episode_thumb
    return self.save_thumbnail(ep_obj)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/metadata/generic.py#L501">SickBeard/medusa/metadata/generic.py</a>", line 501, in save_thumbnail
    thumb_data = self._retrieve_show_image(u'thumbnail', ep_obj.series, ep_obj)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/metadata/generic.py#L738">SickBeard/medusa/metadata/generic.py</a>", line 738, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/metadata/generic.py#L863">SickBeard/medusa/metadata/generic.py</a>", line 863, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/indexers/indexer_base.py#L399">SickBeard/medusa/indexers/indexer_base.py</a>", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py#L611">SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 611, in _get_show_data
    self._parse_actors(sid)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/indexers/tvdbv2/fallback.py#L136">SickBeard/medusa/indexers/tvdbv2/fallback.py</a>", line 136, in __call__
    return self.func(*args, **kwargs)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py#L545">SickBeard/medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 545, in _parse_actors
    actors = self.config['session'].series_api.series_id_actors_get(sid)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/apis/series_api.py#L282">SickBeard/lib/tvdbapiv2/apis/series_api.py</a>", line 282, in series_id_actors_get
    callback=params.get('callback'))
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/api_client.py#L295">SickBeard/lib/tvdbapiv2/api_client.py</a>", line 295, in call_api
    response_type, auth_settings, callback)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/api_client.py#L122">SickBeard/lib/tvdbapiv2/api_client.py</a>", line 122, in __call_api
    post_params=post_params, body=body)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/api_client.py#L315">SickBeard/lib/tvdbapiv2/api_client.py</a>", line 315, in request
    headers=headers)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/rest.py#L70">SickBeard/lib/tvdbapiv2/rest.py</a>", line 70, in get
    query_params=query_params)
  File "/volume2/@appstore/sickbeard-custom/var/<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/SickBeard/lib/tvdbapiv2/rest.py#L63">SickBeard/lib/tvdbapiv2/rest.py</a>", line 63, in request
    raise ApiException(status=status, reason=msg)
ApiException: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/270202/actors

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by droo88** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-6-amd64-x86_64-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@2809aa4781bdc3997d8dd4391b3635451b674501
**Link to Log**: https://gist.github.com/da087feb3628bc275b49aa9ac8586994
### ERROR
<pre>
2018-06-14 16:41:00 ERROR    Thread_2 :: [2809aa4] Exception generated: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/347115/actors
Traceback (most recent call last):
  File "/home8/**********/.apps/medusa/medusa/medusa/server/web/core/base.py", line 283, in async_call
    result = function(**kwargs)
  File "/home8/**********/.apps/medusa/medusa/medusa/server/web/manage/handler.py", line 753, in massUpdate
    image_cache.replace_images(series_obj)
  File "/home8/**********/.apps/medusa/medusa/medusa/image_cache.py", line 167, in replace_images
    fill_cache(series_obj)
  File "/home8/**********/.apps/medusa/medusa/medusa/image_cache.py", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "/home8/**********/.apps/medusa/medusa/medusa/image_cache.py", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "/home8/**********/.apps/medusa/medusa/medusa/metadata/generic.py", line 738, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/home8/**********/.apps/medusa/medusa/medusa/metadata/generic.py", line 863, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/indexer_base.py", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 611, in _get_show_data
    self._parse_actors(sid)
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/fallback.py", line 136, in __call__
    return self.func(*args, **kwargs)
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 545, in _parse_actors
    actors = self.config['session'].series_api.series_id_actors_get(sid)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/apis/series_api.py", line 282, in series_id_actors_get
    callback=params.get('callback'))
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/api_client.py", line 295, in call_api
    response_type, auth_settings, callback)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/api_client.py", line 122, in __call_api
    post_params=post_params, body=body)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/api_client.py", line 315, in request
    headers=headers)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/rest.py", line 70, in get
    query_params=query_params)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/rest.py", line 63, in request
    raise ApiException(status=status, reason=msg)
ApiException: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/347115/actors

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by droo88** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-6-amd64-x86_64-with-debian-9.4`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@a4653907075cbdb0e634444ad17753dc9cdb7a4a
**Link to Log**: https://gist.github.com/17fd8a2f5f4aa3aa9f57287017ec5f1d
### ERROR
<pre>
2018-06-15 21:38:20 ERROR    Thread_3 :: [a465390] Exception generated: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/347046/actors
Traceback (most recent call last):
  File "/home8/**********/.apps/medusa/medusa/medusa/server/web/core/base.py", line 283, in async_call
    result = function(**kwargs)
  File "/home8/**********/.apps/medusa/medusa/medusa/server/web/manage/handler.py", line 753, in massUpdate
    image_cache.replace_images(series_obj)
  File "/home8/**********/.apps/medusa/medusa/medusa/image_cache.py", line 167, in replace_images
    fill_cache(series_obj)
  File "/home8/**********/.apps/medusa/medusa/medusa/image_cache.py", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "/home8/**********/.apps/medusa/medusa/medusa/image_cache.py", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "/home8/**********/.apps/medusa/medusa/medusa/metadata/generic.py", line 738, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/home8/**********/.apps/medusa/medusa/medusa/metadata/generic.py", line 863, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/indexer_base.py", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 611, in _get_show_data
    self._parse_actors(sid)
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/fallback.py", line 136, in __call__
    return self.func(*args, **kwargs)
  File "/home8/**********/.apps/medusa/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 545, in _parse_actors
    actors = self.config['session'].series_api.series_id_actors_get(sid)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/apis/series_api.py", line 282, in series_id_actors_get
    callback=params.get('callback'))
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/api_client.py", line 295, in call_api
    response_type, auth_settings, callback)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/api_client.py", line 122, in __call_api
    post_params=post_params, body=body)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/api_client.py", line 315, in request
    headers=headers)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/rest.py", line 70, in get
    query_params=query_params)
  File "/home8/**********/.apps/medusa/medusa/lib/tvdbapiv2/rest.py", line 63, in request
    raise ApiException(status=status, reason=msg)
ApiException: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/347046/actors

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by markkamphorst** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@c65ca2607fae74405dcceaaf8c02f3d29d0313ea
**Link to Log**: https://gist.github.com/801c2cf1a8f112ba04a9b3dde2023d69
### ERROR
<pre>
2018-06-18 02:03:51 ERROR    SHOWQUEUE-REFRESH :: [c65ca26] 253695: Error while refreshing show Moonshiners. Error: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/253695/actors
Traceback (most recent call last):
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/show_queue.py#L686">medusa\show_queue.py</a>", line 686, in run
    self.show.refresh_dir()
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/tv/series.py#L1713">medusa\tv\series.py</a>", line 1713, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/tv/series.py#L986">medusa\tv\series.py</a>", line 986, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/tv/series.py#L1352">medusa\tv\series.py</a>", line 1352, in make_ep_from_file
    root_ep.create_meta_files()
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/tv/episode.py#L1104">medusa\tv\episode.py</a>", line 1104, in create_meta_files
    self.__create_nfo(metadata_provider)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/tv/episode.py#L1118">medusa\tv\episode.py</a>", line 1118, in __create_nfo
    result = metadata_provider.create_episode_metadata(self) or result
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/metadata/generic.py#L254">medusa\metadata\generic.py</a>", line 254, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/metadata/generic.py#L457">medusa\metadata\generic.py</a>", line 457, in write_ep_file
    data = self._ep_data(ep_obj)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/metadata/kodi_12plus.py#L220">medusa\metadata\kodi_12plus.py</a>", line 220, in _ep_data
    series_obj = self._get_show_data(ep_obj.series)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/metadata/generic.py#L863">medusa\metadata\generic.py</a>", line 863, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/indexers/indexer_base.py#L399">medusa\indexers\indexer_base.py</a>", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/indexers/tvdbv2/tvdbv2_api.py#L611">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 611, in _get_show_data
    self._parse_actors(sid)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/indexers/tvdbv2/fallback.py#L136">medusa\indexers\tvdbv2\fallback.py</a>", line 136, in __call__
    return self.func(*args, **kwargs)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/medusa/indexers/tvdbv2/tvdbv2_api.py#L545">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 545, in _parse_actors
    actors = self.config['session'].series_api.series_id_actors_get(sid)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/lib/tvdbapiv2/apis/series_api.py#L282">lib\tvdbapiv2\apis\series_api.py</a>", line 282, in series_id_actors_get
    callback=params.get('callback'))
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/lib/tvdbapiv2/api_client.py#L295">lib\tvdbapiv2\api_client.py</a>", line 295, in call_api
    response_type, auth_settings, callback)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/lib/tvdbapiv2/api_client.py#L122">lib\tvdbapiv2\api_client.py</a>", line 122, in __call_api
    post_params=post_params, body=body)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/lib/tvdbapiv2/api_client.py#L315">lib\tvdbapiv2\api_client.py</a>", line 315, in request
    headers=headers)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/lib/tvdbapiv2/rest.py#L70">lib\tvdbapiv2\rest.py</a>", line 70, in get
    query_params=query_params)
  File "C:\Medusa\<a href="../blob/c65ca2607fae74405dcceaaf8c02f3d29d0313ea/lib/tvdbapiv2/rest.py#L63">lib\tvdbapiv2\rest.py</a>", line 63, in request
    raise ApiException(status=status, reason=msg)
ApiException: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/253695/actors

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
