### ISSUE TITLE
DB errors updating from 0.2.4 -> 0.2.5 - "no such column: quality"

### ISSUE THREAD

**Issue by ChumpMunky** [pymedusa/Medusa#4389]
**Branch/Commit:** 
Branch: master
Commit: 212cd1c8a350f2d5ca40f172ed5a227d9a5cb80f
Version: v0.2.4
Database: 44.10
**OS:**
Linux-4.2.8-x86_64-with
**What you did:**
Updated Docker container (linuxserver/medusa) from v0.2.4 to v 0.2.5
**What happened:**
Database errors on startup and web UI is unavailable
**What you expected:**
Medusa starts normally
**Logs:**
```
2018-06-10 15:16:40 INFO     MAIN :: [212cd1c] Broken providers found: [u'']
2018-06-10 15:16:41 INFO     MAIN :: [c65ca26] Backing up database before upgrade
2018-06-10 15:16:41 INFO     MAIN :: [c65ca26] Proceeding with upgrade
2018-06-10 15:16:41 INFO     MAIN :: [c65ca26] Shift qualities in tv_shows one place to the left.
2018-06-10 15:16:41 INFO     MAIN :: [c65ca26] Shift qualities in tv_episodes one place to the left.
2018-06-10 15:16:41 INFO     MAIN :: [c65ca26] Query: 'SELECT quality FROM tv_episodes WHERE quality != 0 GROUP BY quality ORDER BY quality DESC;'. Arguments: 'None'
2018-06-10 15:16:41 ERROR    MAIN :: [c65ca26] DB error: OperationalError('no such column: quality',)
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: no such column: quality
2018-06-10 15:16:41 ERROR    MAIN :: [c65ca26] DB error: error b'no such column: quality'
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 284, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: no such column: quality
2018-06-10 15:16:41 ERROR    MAIN :: [c65ca26] Error in ShiftQualities: error b'no such column: quality'
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 465, in _processUpgrade
    instance.execute()
  File "/app/medusa/medusa/databases/main_db.py", line 770, in execute
    self.shift_episode_qualities()
  File "/app/medusa/medusa/databases/main_db.py", line 807, in shift_episode_qualities
    sql_results = self.connection.select("SELECT quality FROM tv_episodes WHERE quality != 0 GROUP BY quality"
  File "/app/medusa/medusa/db.py", line 314, in select
    sql_results = self.action(query, args, fetchall=True)
  File "/app/medusa/medusa/db.py", line 284, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: no such column: quality
```

It continues idefinitely in the same error loop

**Comment by medariox** [comment]
Look like something went wrong with your upgrade process. You should have a file called main.db.v44.9 in Medusa's main folder. Shut down Medusa, rename that file to main.db replacing the current main.db - start Medusa again and let it finish the upgrade process, don't interrupt it! See if that works out for you.

**Comment by ChumpMunky** [comment]
I had main.db.v44.8 and main.db.v44.10, but not main.db.v44.9

I renamed main.db.v44.8 to main.db and it was able to upgrade succesfully from that. Had to re-add a couple of shows but otherwise everything seems fine.

I'll close this unless there's anything else I can pull from the logs which might help you.
