### ISSUE TITLE
Images Not Loading/Downloading Anymore

### ISSUE THREAD

**Issue by dcrdev** [pymedusa/Medusa#4458]
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** master
**OS:** CentOS 7.5
**What you did:** Tried manually updating images via the "mass update" option, tried removing the cache folder and cache database.
**What happened:** Images won't load it doesn't matter whether the image is in the folder or not. Strangely shows that have not updated in a while still show the image.
**What you expected:** Images to work?
**Logs:**
```
2018-06-24 15:40:15 ERROR    Thread_1 :: [c65ca26] Exception generated: Struct() argument 1 must be string, not unicode
Traceback (most recent call last):
  File "/usr/share/medusa/medusa/server/web/core/base.py", line 283, in async_call
    result = function(**kwargs)
  File "/usr/share/medusa/medusa/server/web/manage/handler.py", line 753, in massUpdate
    image_cache.replace_images(series_obj)
  File "/usr/share/medusa/medusa/image_cache.py", line 167, in replace_images
    fill_cache(series_obj)
  File "/usr/share/medusa/medusa/image_cache.py", line 307, in fill_cache
    file_type = which_type(filename)
  File "/usr/share/medusa/medusa/image_cache.py", line 139, in which_type
    image_dimension = get_image_size(path)
  File "/usr/share/medusa/medusa/helpers/__init__.py", line 1583, in get_image_size
    return struct.unpack('>HH', f.read(4))
TypeError: Struct() argument 1 must be string, not unicode
```

**Comment by medariox** [comment]
What's your Python version?

**Comment by dcrdev** [comment]
It's 2.7.5

**Comment by medariox** [comment]
That'd be the reason why it's not working. We require at least Python 2.7.10. You can compile it yourself, see: https://gist.github.com/andriisoldatenko/6d155ec6ca4fc9532bfc
