### ISSUE TITLE
Upgrade failure: db upgrade it seems

### ISSUE THREAD

**Issue by Thibouille** [pymedusa/Medusa#4461]
I have no longer access to Medusa since the failure happens during boot.
It is running in a docker container. This happens following an update to Medusa.
db corruption I guess.
Anyway to get my db back or do I need to set up the whole thing again ?

```
 -------------------------------------
           _         ()
          | |  ___   _    __
          | | / __| | |  /  \
          | | \__ \ | | | () |
          |_| |___/ |_|  \__/


 Brought to you by linuxserver.io
 We gratefully accept donations at:
 https://www.linuxserver.io/donations/
 -------------------------------------
 GID/UID
 -------------------------------------

 User uid:    911
 User gid:    911
 -------------------------------------

 [cont-init.d] 10-adduser: exited 0.
 [cont-init.d] 30-config: executing...
 [cont-init.d] 30-config: exited 0.
 [cont-init.d] done.
 [services.d] starting services
 [services.d] done.
 2018-06-25 10:02:46 INFO     MAIN :: [c65ca26] Broken providers found: [u'torrent9']
 2018-06-25 10:02:46 INFO     MAIN :: [c65ca26] Backing up database before upgrade
 2018-06-25 10:02:46 INFO     MAIN :: [c65ca26] Proceeding with upgrade
 2018-06-25 10:02:46 INFO     MAIN :: [c65ca26] Shift qualities in tv_shows one place to the left.
 2018-06-25 10:02:47 INFO     MAIN :: [c65ca26] Shift qualities in tv_episodes one place to the left.
 2018-06-25 10:02:47 INFO     MAIN :: [c65ca26] Query: 'SELECT quality FROM tv_episodes WHERE quality != 0 GROUP BY quality ORDER BY quality DESC;'. Arguments: 'None'
 2018-06-25 10:02:47 ERROR    MAIN :: [c65ca26] DB error: OperationalError('no such column: quality',)
 Traceback (most recent call last):
   File "/app/medusa/medusa/db.py", line 113, in _execute
     sql_results = cursor.execute(query)
 OperationalError: no such column: quality
 2018-06-25 10:02:47 ERROR    MAIN :: [c65ca26] DB error: error b'no such column: quality'
 Traceback (most recent call last):
   File "/app/medusa/medusa/db.py", line 284, in action
     sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
   File "/app/medusa/medusa/db.py", line 113, in _execute
     sql_results = cursor.execute(query)
 OperationalError: no such column: quality
 2018-06-25 10:02:47 ERROR    MAIN :: [c65ca26] Error in ShiftQualities: error b'no such column: quality'
 Traceback (most recent call last):
   File "/app/medusa/medusa/db.py", line 465, in _processUpgrade
     instance.execute()
   File "/app/medusa/medusa/databases/main_db.py", line 770, in execute
     self.shift_episode_qualities()
   File "/app/medusa/medusa/databases/main_db.py", line 807, in shift_episode_qualities
     sql_results = self.connection.select("SELECT quality FROM tv_episodes WHERE quality != 0 GROUP BY quality"
   File "/app/medusa/medusa/db.py", line 314, in select
     sql_results = self.action(query, args, fetchall=True)
   File "/app/medusa/medusa/db.py", line 284, in action
     sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
   File "/app/medusa/medusa/db.py", line 113, in _execute
     sql_results = cursor.execute(query)
 OperationalError: no such column: quality
 Traceback (most recent call last):
   File "/app/medusa/start.py", line 9, in <module>
     main()
   File "/app/medusa/medusa/__main__.py", line 2157, in main
     application.start(sys.argv[1:])
   File "/app/medusa/medusa/__main__.py", line 339, in start
     self.initialize(console_logging=self.console_logging)
   File "/app/medusa/medusa/__main__.py", line 1097, in initialize
     db.upgradeDatabase(main_db_con, main_db.InitialSchema)
   File "/app/medusa/medusa/db.py", line 452, in upgradeDatabase
     _processUpgrade(connection, schema)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 465, in _processUpgrade
     instance.execute()
   File "/app/medusa/medusa/databases/main_db.py", line 770, in execute
     self.shift_episode_qualities()
   File "/app/medusa/medusa/databases/main_db.py", line 807, in shift_episode_qualities
     sql_results = self.connection.select("SELECT quality FROM tv_episodes WHERE quality != 0 GROUP BY quality"
   File "/app/medusa/medusa/db.py", line 314, in select
     sql_results = self.action(query, args, fetchall=True)
   File "/app/medusa/medusa/db.py", line 284, in action
     sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
   File "/app/medusa/medusa/db.py", line 113, in _execute
     sql_results = cursor.execute(query)
 sqlite3.OperationalError: no such column: quality
root@ds3615xs:~# -------------------------------------
     sql_results = self.action(query, args, fetchall=True)
   File "/app/medusa/medusa/db.py", line 284, in action
     sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
   File "/app/medusa/medusa/db.py", line 113, in _execute
     sql_results = cursor.execute(query)
 OperationalError: no such column: quality
 Traceback (most recent call last):
   File "/app/medusa/start.py", line 9, in <module>
     main()
   Fil-ash: -------------------------------------: command not found
e "/app/medusa/medusa/__main__.py", line 2157, in main
     application.start(sys.argv[1:])
   File "/app/medusa/medusa/__main__.py", line 339, in start
     self.initialize(console_logging=self.console_logging)
   File "/app/medusa/medusa/__main__.py", line 1097, in initialize
     db.upgradeDatabase(main_db_con, main_db.InitialSchema)
   File "/app/medusa/medusa/db.py", line 452, in upgradeDatabase
     _processUpgrade(connection, schema)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "/app/medusa/medusa/db.py", line 475, in _processUpgrade
     _processUpgrade(connection, upgradeSubClass)
   File "root@ds3615xs:~#
```

**Comment by p0psicles** [comment]
Something went wrong with your the upgrade process. Please follow these instructions to revert to a previous db, and let it upgrade the db from there: https://github.com/pymedusa/Medusa/issues/4335#issuecomment-396208650

**Comment by Thibouille** [comment]
Thank you very much.
It didn't work at first and (no 44.9 db) and inside a docker, it really is very annoying not being able to do a simple ls.
But I kind of guessed that it might be a bit earlier update and main.db.v44.8 did exist. renamed and voilà.

Kudozz ;)

**Comment by sharkykh** [comment]
@Thibouille 

I'm testing a theory that may fix this issue in the future.
Looks like you're using the Medusa Docker container.

Please go into your Medusa general configuration, and under advanced settings enable the `No Restart` option, and save.
I am looking at solutions for fixing this issue in the Docker container.
