### ISSUE TITLE
fail on db conversion

### ISSUE THREAD

**Issue by mgaulton** [pymedusa/Medusa#4640]
**Describe the bug**
On attempting to launch using my SickRage database to convert, its dying during proper assignment on a show with the year in the name.

**To Reproduce**
Copied the latest of my SickRage DB over to main.db in an attempt to switch repos. sickrage.db > main.db and copied the config.ini. No other changes.

**Expected behavior**
Able to complete load and conversion and start the app.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Opensuse 42.3
 - Branch: Master
 - Commit: fresh pull

**Logs:**
<details>

```
2018-07-09 15:37:53 ERROR    MAIN :: [e7c4ff3] Error in AddProperTags: Discarding result. Multi-season detected for 'XIII.The.Series.2011.S01E12.The.Key.Proper.720p.WEB.DL.AVC.iON': MatchesDict([('title', u'X
III The'), ('season', [2011, 1]), ('year', 2011), ('episode', 12), ('episode_title', u'The Key'), ('other', u'Proper'), ('proper_count', 1), (u'proper_tag', u'PROPER'), ('screen_size', u'720p'), ('format', u'
WEB-DL'), ('video_codec', u'h264'), ('release_group', u'iON'), ('type', u'episode'), (u'parsing_time', 0.16138195991516113)])
Traceback (most recent call last):
  File "/opt/Medusa/medusa/db.py", line 465, in _processUpgrade
    instance.execute()
  File "/opt/Medusa/medusa/databases/main_db.py", line 416, in execute
    MainSanityCheck(self.connection).update_old_propers()
  File "/opt/Medusa/medusa/databases/main_db.py", line 65, in update_old_propers
    parse_result = NameParser()._parse_string(proper_release)
  File "/opt/Medusa/medusa/name_parser/parser.py", line 275, in _parse_string
    result = self.to_parse_result(name, guess)
  File "/opt/Medusa/medusa/name_parser/parser.py", line 417, in to_parse_result
    raise InvalidNameException("Discarding result. Multi-season detected for '{name}': {guess}".format(name=name, guess=guess))
InvalidNameException: Discarding result. Multi-season detected for 'XIII.The.Series.2011.S01E12.The.Key.Proper.720p.WEB.DL.AVC.iON': MatchesDict([('title', u'XIII The'), ('season', [2011, 1]), ('year', 2011),
 ('episode', 12), ('episode_title', u'The Key'), ('other', u'Proper'), ('proper_count', 1), (u'proper_tag', u'PROPER'), ('screen_size', u'720p'), ('format', u'WEB-DL'), ('video_codec', u'h264'), ('release_gro
up', u'iON'), ('type', u'episode'), (u'parsing_time', 0.16138195991516113)])
```
</details>

**Additional context**

**Comment by sharkykh** [comment]
Looks like the year is throwing it off:
```
$ python tests\report_guessit.py "XIII.The.Series.2011.S01E12.The.Key.Proper.720p.WEB.DL.AVC.iON"
# guessit: 2.1.4  rebulk: 0.9.0
? XIII.The.Series.2011.S01E12.The.Key.Proper.720p.WEB.DL.AVC.iON
: title: XIII The
  season: [2011, 1]
  year: 2011
  episode: 12
  episode_title: The Key
  other: Proper
  proper_count: 1
  proper_tag: PROPER
  screen_size: 720p
  format: WEB-DL
  video_codec: h264
  release_group: iON
  type: episode
  parsing_time: 0.0820000171661
```
Without a year:
```
$ python tests\report_guessit.py "XIII.The.Series.S01E12.The.Key.Proper.720p.WEB.DL.AVC.iON"
# guessit: 2.1.4  rebulk: 0.9.0
? XIII.The.Series.S01E12.The.Key.Proper.720p.WEB.DL.AVC.iON
: title: XIII The Series
  season: 1
  episode: 12
  episode_title: The Key
  other: Proper
  proper_count: 1
  proper_tag: PROPER
  screen_size: 720p
  format: WEB-DL
  video_codec: h264
  release_group: iON
  type: episode
  parsing_time: 0.0720000267029
```

**Comment by mgaulton** [comment]
Yea, that's what I figured, i just don't know what I can do about it lol

**Comment by sharkykh** [comment]
You can try clearing your history (or selectively removing any history of this show) on SickRage before migrating to Medusa.
It might fix this issue and let you run Medusa, but it still remains a bug, because you probably won't be able to post-process files for this show.

**Comment by mgaulton** [comment]
hmm, ok, thanks.

**Comment by medariox** [comment]
Starting from Medusa v0.2.10 you will be able to import this show by adding a scene exception with the name ` XIII The 2011`.

**Comment by medariox** [comment]
With the next release you will be able to use the original title without any issues.
