### ISSUE TITLE
Read only database

### ISSUE THREAD

**Issue by metabaron** [pymedusa/Medusa#4743]
**Describe the bug**
Message about attempting to write a read only database

**To Reproduce**
1. Go to 'Manage > Mass Update'
2. Click on 'Update'

**Expected behavior**
Ne error message

**Medusa (please complete the following information):**
Medusa Info: | Branch: master Commit: e7c4ff3bc9a48b47c932b0e40a539d62e3a62f64 Version: v0.2.6 Database: 44.11
-- | --
Python Version: | 2.7.14 (default, May 28 2018, 14:47:09) [GCC 4.3.2]
SSL Version: | OpenSSL 1.0.2n 7 Dec 2017
OS: | Linux-2.6.32.12-ppc-with-glibc2.0 (Synology up to date box)
Locale: | Unknown.Unknown

**Logs:**
<details>

```
2018-07-24 14:24:33 ERROR    SHOWQUEUE-ADD :: [e7c4ff3] Error loading IMDb info: attempt to write a readonly database
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/show_queue.py", line 587, in run
    self.show.load_imdb_info()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/series.py", line 1543, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/imdbpie.py", line 80, in get_title
    '/title/{0}/auxiliary'.format(imdb_id)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/imdbpie.py", line 265, in _get_resource
    return self._get(url=url)['resource']
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/imdbpie.py", line 272, in _get
    headers.update(self.get_auth_headers(path))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/auth.py", line 112, in get_auth_headers
    creds, soon_expires = self._creds_soon_expiring()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/auth.py", line 97, in _creds_soon_expiring
    creds = self._get_creds()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/imdbpie/auth.py", line 84, in _get_creds
    with diskcache.Cache(directory=self._cachedir) as cache:
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/diskcache/core.py", line 408, in __init__
    sql(query, (key, value))
OperationalError: attempt to write a readonly database
```
</details>

**Additional context**
Everything else works as expected, adding new tv series, renaming and such.
I did saved the configuration, remove Medusa, installed it again, restored the configuration files and same problem.

**Comment by sharkykh** [comment]
@medariox 
I looked at the code for `imdbpie` and I think we can override the location of the cache.
https://github.com/pymedusa/Medusa/blob/aa9bb8805bdeb1ee74413c97e15b98983d19ccf0/ext/imdbpie/auth.py#L75-L81
https://github.com/pymedusa/Medusa/blob/aa9bb8805bdeb1ee74413c97e15b98983d19ccf0/ext/imdbpie/imdbpie.py#L53-L60

We should be able to subclass `Imdb` and change that to a folder in the user's data folder.

What are your thoughts on that?

----
Related to: #4689 #3683

**Comment by medariox** [comment]
@sharkykh 
Yes, I agree that subclassing and setting it to our own cache folder (`Medusa/cache`) would solve the issue. It would be better if we could have an optional argument that doesn't force us to subclass it tho. I think the author of `imdbpie` might be open to that change, sadly the repo is not on GH anymore.

**Comment by metabaron** [comment]
@sharkykh 
```
xxx@yyy:/volume1/@appstore/sickbeard-custom$ python -c "import tempfile, os.path; print os.path.join(tempfile.gettempdir(), 'cache.db')"
/tmp/cache.db
xxx@yyy:/volume1/@appstore/sickbeard-custom$ sudo rm -rf /tmp/cache.db         
Password:
xxx@yyy:/volume1/@appstore/sickbeard-custom$
```

And associated logs:
```
2018-07-24 21:27:06 INFO     SHOWQUEUE-REFRESH :: [e7c4ff3] Cache check completed
2018-07-24 21:27:06 INFO     SHOWQUEUE-REFRESH :: [e7c4ff3] 296295: Updating NFOs for show with new indexer info
2018-07-24 21:27:06 INFO     SHOWQUEUE-REFRESH :: [e7c4ff3] Trying to clean any empty folder under /volume1/video/tv/Ash vs Evil Dead
2018-07-24 21:27:06 INFO     SHOWQUEUE-REFRESH :: [e7c4ff3] 296295: Performing refresh on Ash vs Evil Dead
2018-07-24 21:27:04 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Cache check completed
2018-07-24 21:27:03 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Selected poster for series 296295 (score=3.86922592198, score_bay=6.73845184395, rating=7.8, votes=13, res=680x1000): https://www.thetvdb.com/banners/posters/296295-8.jpg
2018-07-24 21:27:03 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Selected fanart for series 296295 (score=4.53353960256, score_bay=7.06707920513, rating=7.9, votes=15, res=1920x1080): https://www.thetvdb.com/banners/fanart/original/296295-4.jpg
2018-07-24 21:27:01 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Copying from /volume1/video/tv/Ash vs Evil Dead/poster.jpg to /volume1/@appstore/sickbeard-custom/var/cache/images/tvdb/296295.poster.jpg
2018-07-24 21:27:01 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Removed fanart for series Ash vs Evil Dead
2018-07-24 21:27:01 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Removed poster_thumb for series Ash vs Evil Dead
2018-07-24 21:27:01 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Removed banner_thumb for series Ash vs Evil Dead
2018-07-24 21:27:01 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Removed poster for series Ash vs Evil Dead
2018-07-24 21:27:01 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] Removed banner for series Ash vs Evil Dead
2018-07-24 21:27:01 INFO     SHOWQUEUE-UPDATE :: [e7c4ff3] 296295: Replacing images for show Ash vs Evil Dead
```

So, as you can see, it worked. This is a solution for anyone that should face the same problem as I do.
Thank you.

**Comment by medariox** [comment]
Fixed in develop with: https://github.com/pymedusa/Medusa/pull/4745
