### ISSUE TITLE
[APP SUBMITTED]: ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#4776]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/3df7613ad0568cc12f9fdcb7573afe31
### ERROR
<pre>
2018-07-28 02:02:50 ERROR    Thread_12 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/manage/handler.py#L176">medusa/server/web/manage/handler.py</a>", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/home/handler.py#L1928">medusa/server/web/home/handler.py</a>", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Xenocell12** [comment]
### INFO
**Python Version**: `2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/6a9cea7b7c9ea56c88bd6d7d3ad79a37
### ERROR
<pre>
2018-07-27 22:16:42 ERROR    Thread_1 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "C:\Users\uTorrentVM\Medusa\<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/core/base.py#L259">medusa\server\web\core\base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "C:\Users\uTorrentVM\Medusa\<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/manage/handler.py#L176">medusa\server\web\manage\handler.py</a>", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "C:\Users\uTorrentVM\Medusa\<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/home/handler.py#L1928">medusa\server\web\home\handler.py</a>", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
In the meantime you can use the per-show status/quality setter. The episode status managment page seems to be broken.

**Comment by medariox** [comment]
Fixed in develop with: https://github.com/pymedusa/Medusa/pull/4783

**Comment by benfishbus** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.8-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/a3af3176eaa4bf965c23b59e449c2549
### ERROR
<pre>
2018-07-28 14:13:01 ERROR    Thread_0 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/manage/handler.py#L176">medusa/server/web/manage/handler.py</a>", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/home/handler.py#L1928">medusa/server/web/home/handler.py</a>", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Sarcas666** [comment]
### INFO
**Python Version**: `2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]`
**Operating System**: `Darwin-17.7.0-x86_64-i386-64bit`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/21b6139152413f57468553cf550b036d
### ERROR
<pre>
2018-08-03 20:31:39 ERROR    Thread_1 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/Applications/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/Applications/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/manage/handler.py#L176">medusa/server/web/manage/handler.py</a>", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/Applications/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/home/handler.py#L1928">medusa/server/web/home/handler.py</a>", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bassings** [comment]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/cbfb4740727d96f19cf8bfe8c24a835e
### ERROR
<pre>
2018-08-21 10:26:51 ERROR    Thread_13 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/manage/handler.py", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/home/handler.py", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ozhound** [comment]
### INFO
**Python Version**: `2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]`
**Operating System**: `Linux-3.10.102-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/2a43d44c01723891f86ddbe6eb45cb3c
### ERROR
<pre>
2018-09-01 19:52:04 ERROR    Thread_5 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/manage/handler.py#L176">medusa/server/web/manage/handler.py</a>", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/app/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/home/handler.py#L1928">medusa/server/web/home/handler.py</a>", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by blakadder** [comment]
### INFO
**Python Version**: `2.7.14 (default, Jan 10 2018, 14:55:03) [GCC 6.3.0]`
**Operating System**: `Linux-2.6.31.8-armv5tel-with-glibc2.4`
**Locale**: `ISO8859-1`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/afe6a5e22bfb9a1e6553cc033bbbeb09
### ERROR
<pre>
2018-09-03 09:15:59 ERROR    Thread_4 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/local/zy-pkgs/opt/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/usr/local/zy-pkgs/opt/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/manage/handler.py#L176">medusa/server/web/manage/handler.py</a>", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/usr/local/zy-pkgs/opt/Medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/home/handler.py#L1928">medusa/server/web/home/handler.py</a>", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mdimura** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with-debian-9.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/f74dca5a82ec13a0a5bea899146fdb5c
### ERROR
<pre>
2018-09-06 19:07:46 ERROR    Thread_8 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/opt/yunohost/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/opt/yunohost/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/manage/handler.py#L176">medusa/server/web/manage/handler.py</a>", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/opt/yunohost/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/home/handler.py#L1928">medusa/server/web/home/handler.py</a>", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mdimura** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with-debian-9.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.11`
**Commit**: pymedusa/Medusa@f5973b28465246e67465d7d86bdc8aa74d13e659
**Link to Log**: https://gist.github.com/34278c5b3f646ee0ad6e47461ecc62b6
### ERROR
<pre>
2018-09-06 19:10:19 ERROR    Thread_8 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/opt/yunohost/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/opt/yunohost/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/manage/handler.py#L176">medusa/server/web/manage/handler.py</a>", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/opt/yunohost/medusa/<a href="../blob/f5973b28465246e67465d7d86bdc8aa74d13e659/medusa/server/web/home/handler.py#L1928">medusa/server/web/home/handler.py</a>", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
### INFO
**Python Version**: `2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1255`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@fd35974129b74e51a4d40d79ea985956b08dbd72
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-09-25 19:05:04 ERROR    Thread_13 :: [fd35974] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "C:\Medusa\<a href="../blob/fd35974129b74e51a4d40d79ea985956b08dbd72/medusa/server/web/core/base.py#L258">medusa\server\web\core\base.py</a>", line 258, in async_call
    result = function(**kwargs)
  File "C:\Medusa\<a href="../blob/fd35974129b74e51a4d40d79ea985956b08dbd72/medusa/server/web/manage/handler.py#L307">medusa\server\web\manage\handler.py</a>", line 307, in downloadSubtitleMissed
    season, episode = epResult.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by blakadder** [comment]
### INFO
**Python Version**: `2.7.15+ (default, Aug 31 2018, 11:56:52) [GCC 8.2.0]`
**Operating System**: `Linux-4.18.4-kirkwood-tld-1-armv5tel-with-debian-9.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4614efc77151ded92ef458a09dec39f8bd5acfc6
**Link to Log**: https://gist.github.com/bd050107e3cf6a22d9e31ff4cd176bde
### ERROR
<pre>
2018-10-16 12:32:57 ERROR    Thread_3 :: [4614efc] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/core/base.py#L259">medusa/server/web/core/base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/4614efc77151ded92ef458a09dec39f8bd5acfc6/medusa/server/web/home/handler.py#L1907">medusa/server/web/home/handler.py</a>", line 1907, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by buzolich** [comment]
### INFO
**Python Version**: `2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]`
**Operating System**: `Linux-4.14.49-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/c6e89bdad230759dc389f09ff44bef95
### ERROR
<pre>
2018-11-14 08:10:12 ERROR    Thread_1 :: [77b2091] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/server/web/core/base.py#L258">medusa/server/web/core/base.py</a>", line 258, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/server/web/home/handler.py#L1897">medusa/server/web/home/handler.py</a>", line 1897, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rwanou88** [comment]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-4.4.59+-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@54da0c77d705a23f1ce67945ba4af3e1b978dcfc
**Link to Log**: https://gist.github.com/099cb4f8ee72c61c34d1a5b726aaad7d
### ERROR
<pre>
2018-12-12 14:50:45 ERROR    Thread_4 :: [54da0c7] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/server/web/core/base.py#L258">medusa/server/web/core/base.py</a>", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/server/web/home/handler.py#L1883">medusa/server/web/home/handler.py</a>", line 1883, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pax0707** [comment]
### INFO
**Python Version**: `2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/c35c4385e54508c0e1333ae58b6a48c5
### ERROR
<pre>
2019-01-21 00:32:18 ERROR    Thread_3 :: [918cfe7] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "D:\Plex\Medusa\<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/server/web/core/base.py#L258">medusa\server\web\core\base.py</a>", line 258, in async_call
    result = function(**kwargs)
  File "D:\Plex\Medusa\<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/server/web/home/handler.py#L1883">medusa\server\web\home\handler.py</a>", line 1883, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
