### ISSUE TITLE
changing episodes to archived from download fails

### ISSUE THREAD

**Issue by jxer** [pymedusa/Medusa#4809]
2018-07-28 17:07:51 ERROR    Thread_12 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/home/littlebill/.sickrage/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/home/littlebill/.sickrage/medusa/server/web/manage/handler.py", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/home/littlebill/.sickrage/medusa/server/web/home/handler.py", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/4776
