### ISSUE TITLE
Change status from skipped to wanted error

### ISSUE THREAD

**Issue by Naokor** [pymedusa/Medusa#4893]
**Describe the bug**
When an entire season is selected wich the checkbox before changing the status from skipped to wanted an error occurs. 

**To Reproduce**
1. Go to a show page
2. Click on one season's chekbox (see picture)
<img width="352" alt="capture" src="https://user-images.githubusercontent.com/26311252/43980730-90ef7408-9cef-11e8-8c33-0654c2e00c9d.PNG">
3. Select Wanted from this dropdown menu and hit the "Go" Button on the right
<img width="303" alt="capture2" src="https://user-images.githubusercontent.com/26311252/43980825-daaaf1f8-9cef-11e8-850e-0c06578f425a.png">
4. See error on the logs

**Expected behavior**
A change of status of the episodes.

**Medusa (please complete the following information):**

Branch: develop Commit: ff9b16ebe215adbb033c4c74254a30d59093f776 
Version: v0.2.8 Database: 44.11
Python Version: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | en_US.UTF-8

**Logs:**
<details>

```
018-08-10 22:41:05 ERROR    Thread_10 :: [ff9b16e] Exception generated: near "watched": syntax error
Traceback (most recent call last):
  File "/home/**********/.medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/home/**********/.medusa/medusa/server/web/home/handler.py", line 2005, in setStatus
    main_db_con.mass_action(sql_l)
  File "/home/**********/.medusa/medusa/db.py", line 221, in mass_action
    sql_results.append(self._execute(qu[0], qu[1], fetchall=fetchall))
  File "/home/**********/.medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OperationalError: near "watched": syntax error
2018-08-10 22:41:05 ERROR    Thread_10 :: [ff9b16e] DB error: OperationalError('near "watched": syntax error',)
Traceback (most recent call last):
  File "/home/**********/.medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OperationalError: near "watched": syntax error
2018-08-10 22:41:05 ERROR    Thread_10 :: [ff9b16e] DB error: error b'near "watched": syntax error'
Traceback (most recent call last):
  File "/home/**********/.medusa/medusa/db.py", line 221, in mass_action
    sql_results.append(self._execute(qu[0], qu[1], fetchall=fetchall))
  File "/home/**********/.medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OperationalError: near "watched": syntax error```
</details>

**Additional context**
Develop Branch

**Comment by p0psicles** [comment]
fixed in develop.
