### ISSUE TITLE
All shows have disappeared

### ISSUE THREAD

**Issue by kingblah** [pymedusa/Medusa#4911]
I logged onto my medusa install today after restarting my server and all of my shows have disappeared!

I've tried restoring from backup (which seem to be saved in /home/owner/.config/medusa) but nothing happens. The file-picker doesn't let me select any files. There seem to be a few .bak files - one is 27kb and one is 552kb. But I can't select them?

Here is the error:

```
2018-08-18 13:39:20 ERROR    Thread_7 :: [f5973b2] Exception generated: File is not a zip file
Traceback (most recent call last):
  File "/home/owner/.medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/home/owner/.medusa/medusa/server/web/config/backup_restore.py", line 67, in restore
    if helpers.restore_config_zip(source, target_dir):
  File "/home/owner/.medusa/medusa/helpers/__init__.py", line 1132, in restore_config_zip
    zip_file = zipfile.ZipFile(archive, 'r', allowZip64=True)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
```

**Comment by medariox** [comment]
Medusa won't delete any shows just like that. I'd make sure the HDD is alright. You should have some backup files called `main.db.v44.9`, `main.db.v44.10`, etc. in the medusa folder. Shut down Medusa, rename of those to `main.db` and restart.

**Comment by kingblah** [comment]
Thanks for the reply - unfortunately didn't work, those files were last edited at a time a few weeks ago when I installed Medusa, I guess I'll have to try rebuilding my Medusa showlist  from scratch
