### ISSUE TITLE
Unable to update episodes from snatched to failed  in the episode status management

### ISSUE THREAD

**Issue by bassings** [pymedusa/Medusa#4926]
**Describe the bug**
In the Manage > Episode status management interface, I filter episodes that have been snatched (these are usually shows I've tried to download which have failed). I try to select the episodes and change status to "Failed" so that it will try and find another version. It opens up the URL
http://[medusa server path]/manage/changeEpisodeStatuses

**To Reproduce**
1. Go to 'Manage Menu'
2. Click on 'Episode status management '
3. Change Manage episodes with status filter to "Snatched"
4. Select all the episode and change the Set checked shows/episodes to "Failed"
5. http://[medusa server path]/manage/changeEpisodeStatuses opens with a blank page.
6. If you check the episode status again the episodes are still in snatched status.

**Expected behavior**
The episodes should be marked as failed and the search should kick off again to find new versions of the episodes.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: CentOS Linux release 7.5.1804 (Core)
 - Branch: Master 
 - Commit: f5973b28465246e67465d7d86bdc8aa74d13e659 

**Logs:**
<details>
2018-08-21 10:39:50 ERROR    Thread_19 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/manage/handler.py", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/home/handler.py", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
2018-08-21 10:39:48 INFO     POSTPROCESSOR :: [f5973b2] Successfully processed.
2018-08-21 10:29:47 INFO     POSTPROCESSOR :: [f5973b2] Successfully processed.
2018-08-21 10:27:30 INFO     Thread_7 :: [f5973b2] Commented on existing issue #4776 successfully!
2018-08-21 10:26:51 ERROR    Thread_13 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/manage/handler.py", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/home/handler.py", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
2018-08-21 10:23:28 ERROR    Thread_5 :: [f5973b2] Exception generated: changeEpisodeStatuses() takes at least 3 arguments (1 given)
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
TypeError: changeEpisodeStatuses() takes at least 3 arguments (1 given)
2018-08-21 10:22:58 ERROR    Thread_10 :: [f5973b2] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/core/base.py", line 259, in async_call
    result = function(**kwargs)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/manage/handler.py", line 176, in changeEpisodeStatuses
    self.setStatus(indexer_id_to_name(int(cur_indexer_id)), cur_series_id, '|'.join(to_change[(cur_indexer_id, cur_series_id)]), newStatus, direct=True)
  File "/var/lib/**********mediaserver/medusa/medusa/server/web/home/handler.py", line 1928, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
</details>

**Additional context**
Medusa Info: 
Branch: master 
Commit: f5973b28465246e67465d7d86bdc8aa74d13e659 
Version: v0.2.8 
Database: 44.11
Python Version: | 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
SSL Version: | OpenSSL 1.0.2k-fips 26 Jan 2017
OS: | Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core
Locale: | en_AU.UTF-8

**Comment by medariox** [comment]
This is already fixed in develop with: https://github.com/pymedusa/Medusa/commit/b7275b89a4ad96f8f1eae96ac4bb1ad43ac3427f

Need to wait for the next release.
