### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'get_text'

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#4993]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [bugfix/imdb-none](../tree/bugfix/imdb-none)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4e21883bbedad8c4346c14b063ade74d1ac31893
**Link to Log**: https://gist.github.com/15695a17210f4eefab418e5f82e0d89b
### ERROR
<pre>
2018-08-28 23:16:00 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [4e21883] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/4e21883bbedad8c4346c14b063ade74d1ac31893/medusa/providers/torrent/html/speedcd.py#L132">medusa/providers/torrent/html/speedcd.py</a>", line 132, in parse
    title = cells[1].find('a', class_='torrent').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [bugfix/imdb-none](../tree/bugfix/imdb-none)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@4e21883bbedad8c4346c14b063ade74d1ac31893
**Link to Log**: https://gist.github.com/14afacd8c916ba5403a5a985e886e389
### ERROR
<pre>
2018-08-29 11:54:42 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [4e21883] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/4e21883bbedad8c4346c14b063ade74d1ac31893/medusa/providers/torrent/html/speedcd.py#L132">medusa/providers/torrent/html/speedcd.py</a>", line 132, in parse
    title = cells[1].find('a', class_='torrent').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Temporary issue or did they change the HTML?

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@d7da5942b5307d5ca1e982d7073155a84699751a
**Link to Log**: https://gist.github.com/ceb39f3cdcc310236f70e281fe4a9ac9
### ERROR
<pre>
2018-09-01 13:12:06 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [d7da594] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/d7da5942b5307d5ca1e982d7073155a84699751a/medusa/providers/torrent/html/speedcd.py#L132">medusa/providers/torrent/html/speedcd.py</a>", line 132, in parse
    title = cells[1].find('a', class_='torrent').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
Seems like the HTML has changed, been getting this always now.

**Comment by fernandog** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.14.34-5-osmc-armv7l-with-debian-9.5`
**Locale**: `UTF-8`
**Branch**: [optimized](../tree/optimized)
**Database**: `44.9`
**Commit**: pymedusa/Medusa@8c415716ec5b8d5a761cf34704ba43b7637fadba
**Link to Log**: https://gist.github.com/7b3d36d17128abd6b84c553e7c05f1cd
### ERROR
<pre>
2018-09-06 09:55:55 ERROR    SEARCHQUEUE-MANUAL-290853 :: [Speedcd] :: [8c41571] Failed parsing provider.
Traceback (most recent call last):
  File "/home/osmc/Medusa/<a href="../blob/8c415716ec5b8d5a761cf34704ba43b7637fadba/medusa/providers/torrent/html/speedcd.py#L132">medusa/providers/torrent/html/speedcd.py</a>", line 132, in parse
    title = cells[1].find('a', class_='torrent').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Seems something changed in the second field of the row. It expects to find an anchor. Can you post a piece of html for these rows?

**Comment by medariox** [comment]
I can have a look if someone gives me temporary access.

**Comment by medariox** [comment]
Try changing https://github.com/pymedusa/Medusa/blob/8c415716ec5b8d5a761cf34704ba43b7637fadba/medusa/providers/torrent/html/speedcd.py#L132 

```
title = cells[1].find('a', class_='torrent').get_text()
```
to
```
title = cells[1].find('a', class_='lft').get_text()
```

That should be all that's needed.

**Comment by medariox** [comment]
Can anyone confirm if it worked?

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@1435fcbfe0412abca06a18a5ab7ee56ec60370fe
**Link to Log**: https://gist.github.com/409319ccdf381d82a15ee49c178b8d5f
### ERROR
<pre>
2018-09-08 22:15:55 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/1435fcbfe0412abca06a18a5ab7ee56ec60370fe/medusa/providers/torrent/html/speedcd.py#L132">medusa/providers/torrent/html/speedcd.py</a>", line 132, in parse
    title = cells[1].find('a', class_='torrent').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
Can only on Monday

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@1435fcbfe0412abca06a18a5ab7ee56ec60370fe
**Link to Log**: https://gist.github.com/88ad9959f61cb0cf53aa4e0cc82fcfcc
### ERROR
<pre>
2018-09-09 13:39:00 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/1435fcbfe0412abca06a18a5ab7ee56ec60370fe/medusa/providers/torrent/html/speedcd.py#L132">medusa/providers/torrent/html/speedcd.py</a>", line 132, in parse
    title = cells[1].find('a', class_='torrent').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
Doesn't fix it @medariox 

```
2018-09-09 14:07:00 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] Updating providers cache
2018-09-09 14:07:00 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] GET URL: https://speed.cd/login.php [Status: 200]
2018-09-09 14:07:00 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] User-Agent: Medusa/0.2.9 (Linux; 4.9.35-v7+; f0cbe848-b42d-11e8-b491-b827eb6b4d4c)
2018-09-09 14:07:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] POST URL: https://speed.cd/takelogin.php [Status: 302]
2018-09-09 14:07:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] User-Agent: Medusa/0.2.9 (Linux; 4.9.35-v7+; f0cbe848-b42d-11e8-b491-b827eb6b4d4c)
2018-09-09 14:07:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] With post data: username=**********&password=**********
2018-09-09 14:07:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] GET URL: https://speed.cd/ [Status: 200]
2018-09-09 14:07:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] User-Agent: Medusa/0.2.9 (Linux; 4.9.35-v7+; f0cbe848-b42d-11e8-b491-b827eb6b4d4c)
2018-09-09 14:07:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] Search mode: RSS
2018-09-09 14:07:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] GET URL: https://speed.cd/browse.php?c55=1&c52=1&search=&c41=1&c50=1&c2=1&c30=1&c49=1 [Status: 200]
2018-09-09 14:07:01 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] User-Agent: Medusa/0.2.9 (Linux; 4.9.35-v7+; f0cbe848-b42d-11e8-b491-b827eb6b4d4c)
2018-09-09 14:07:05 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/medusa/providers/torrent/html/speedcd.py", line 132, in parse
    title = cells[1].find('a', class_='lft').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
2018-09-09 14:07:05 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/medusa/providers/torrent/html/speedcd.py", line 132, in parse
    title = cells[1].find('a', class_='lft').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
2018-09-09 14:07:05 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [1435fcb] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/medusa/providers/torrent/html/speedcd.py", line 132, in parse
    title = cells[1].find('a', class_='lft').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```

**Comment by medariox** [comment]
In that case, I'll need access from any of you. You can PM me on Slack.

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@b2dbc4d3f6b41235d7d174b25352fb7d66520ce0
**Link to Log**: https://gist.github.com/6c6f007df8822acd0f63667a12439070
### ERROR
<pre>
2018-09-09 15:03:00 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [b2dbc4d] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/b2dbc4d3f6b41235d7d174b25352fb7d66520ce0/medusa/providers/torrent/html/speedcd.py#L132">medusa/providers/torrent/html/speedcd.py</a>", line 132, in parse
    title = cells[1].find('a', class_='lft').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@78d2474d05040d15ee3b8cc351481554ccd85b22
**Link to Log**: https://gist.github.com/c12a8df80b1b2338811281ad269ba00b
### ERROR
<pre>
2018-09-12 09:14:34 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [78d2474] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/78d2474d05040d15ee3b8cc351481554ccd85b22/medusa/providers/torrent/html/speedcd.py#L132">medusa/providers/torrent/html/speedcd.py</a>", line 132, in parse
    title = cells[1].find('a', class_='lft').get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5190
