### ISSUE TITLE
[APP SUBMITTED]: ParseError: syntax error: line 1, column 0

### ISSUE THREAD

**Issue by bassings** [pymedusa/Medusa#5141]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@db3d9d767bbf3fe7c365df20d92099b0cbbd91b4
**Link to Log**: https://gist.github.com/d231e6c17d10a15684123cec26f05985
### ERROR
<pre>
2018-09-08 21:11:50 ERROR    SEARCHQUEUE-RETRY-74156 :: [BinSearch] :: [db3d9d7] Unable to parse the XML of Big.Love.S02.1080p.Amazon.WEB-DL.DD+.5.1.x264-TrollHD, not splitting it
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/nzb_splitter.py", line 67, in get_season_nzbs
    show_xml = ETree.ElementTree(ETree.XML(url_data))
  File "<string>", line 124, in XML
ParseError: syntax error: line 1, column 0
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5175
