### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 2] No such file or directory: '/var/cache/sab/ragetv/Paw.Patrol.S01E03E04.1080p.NF.WEBRip.DD5.1.x264-LAZY-xpost/Paw.Patrol.S01E03E04.Pups.Save.the.Sea.Turtles.-.Pups.and.the.Very.Big.Baby.1080p.NF.WEBRip.DDP5.1.x264-LAZY.mkv'

### ISSUE THREAD

**Issue by bassings** [pymedusa/Medusa#5143]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@db3d9d767bbf3fe7c365df20d92099b0cbbd91b4
**Link to Log**: https://gist.github.com/b507a35f132c5b44a019e04a79dd29c0
### ERROR
<pre>
2018-09-08 21:57:25 ERROR    Thread_4 :: [db3d9d7] Unable to move file /var/cache/sab/ragetv/Paw.Patrol.S01E03E04.1080p.NF.WEBRip.DD5.1.x264-LAZY-xpost/Paw.Patrol.S01E03E04.Pups.Save.the.Sea.Turtles.-.Pups.and.the.Very.Big.Baby.1080p.NF.WEBRip.DDP5.1.x264-LAZY.mkv to /var/media/TV/Paw Patrol/Paw Patrol - S01E05E07 - Pups Save the Sea Turtles & Pups Save the Circus.mkv: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/post_processor.py", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/var/lib/**********mediaserver/medusa/medusa/helpers/__init__.py", line 315, in move_file
    copy_file(src_file, dest_file)
  File "/var/lib/**********mediaserver/medusa/medusa/helpers/__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/var/lib/**********mediaserver/medusa/lib/shutil_custom/__init__.py", line 32, in copyfile_custom
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "/var/lib/**********mediaserver/medusa/medusa/init/filesystem.py", line 113, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 2] No such file or directory: '/var/cache/sab/ragetv/Paw.Patrol.S01E03E04.1080p.NF.WEBRip.DD5.1.x264-LAZY-xpost/Paw.Patrol.S01E03E04.Pups.Save.the.Sea.Turtles.-.Pups.and.the.Very.Big.Baby.1080p.NF.WEBRip.DDP5.1.x264-LAZY.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
We don't support Python version prior to 2.7.10
