### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'dict' object has no attribute 'replace'

### ISSUE THREAD

**Issue by cairobraga** [pymedusa/Medusa#5155]
so my Auto Post Processing is not working and when I try to do Manual PP, this happens:

### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@db3d9d767bbf3fe7c365df20d92099b0cbbd91b4
**Link to Log**: https://gist.github.com/9676ce5b08d10ad0969db89b2764bc06
### ERROR
<pre>
2018-09-08 01:07:49 ERROR    Thread_7 :: [db3d9d7] Exception generated: 'dict' object has no attribute 'replace'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/server/web/core/base.py#L259">medusa\server\web\core\base.py</a>", line 259, in async_call
    result = function(**kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/server/web/home/post_process.py#L49">medusa\server\web\home\post_process.py</a>", line 49, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "C:\Medusa\Medusa\<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/process_tv.py#L138">medusa\process_tv.py</a>", line 138, in process
    postpone = app.POSTPONE_IF_SYNC_FILES and any(sync_files)
  File "C:\Medusa\Medusa\<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/process_tv.py#L135">medusa\process_tv.py</a>", line 135, in <genexpr>
    if is_sync_file(filename))
  File "C:\Medusa\Medusa\<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/helper/common.py#L162">medusa\helper\common.py</a>", line 162, in is_sync_file
    any(fnmatch(filename, match) for match in app.SYNC_FILES))
  File "C:\Medusa\Medusa\<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/helper/common.py#L162">medusa\helper\common.py</a>", line 162, in <genexpr>
    any(fnmatch(filename, match) for match in app.SYNC_FILES))
  File "C:\Medusa\Python\lib\fnmatch.py", line 42, in fnmatch
    pat = os.path.normcase(pat)
  File "C:\Medusa\Medusa\<a href="../blob/db3d9d767bbf3fe7c365df20d92099b0cbbd91b4/medusa/init/filesystem.py#L113">medusa\init\filesystem.py</a>", line 113, in patched_output
    return handle_output(f(*args, **kwargs))
  File "C:\Medusa\Python\lib\ntpath.py", line 47, in normcase
    return s.replace("/", "\\").lower()
AttributeError: 'dict' object has no attribute 'replace'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by sharkykh** [comment]
@cairobraga 
What is your `Sync Files` configuration under Post Processing config?

**Comment by sharkykh** [comment]
**Confirmed:**

![image](https://user-images.githubusercontent.com/10238474/45256181-8b1c7180-b39b-11e8-87ec-e39c356dd51f.png)

**Comment by sharkykh** [comment]
@cairobraga 
If you can post me the `sync_files` value from your `config.ini`, I'll give you a correct one to fix the issue for now.

**Comment by cairobraga** [comment]
@sharkykh, here it is:

`sync_files = "{u'id': 6, u'value': u'!sync'}", "{u'id': 7, u'value': u'lftp-pget-status'}", "{u'id': 8, u'value': u'part'}", "{u'id': 9, u'value': u'bts'}", "{u'id': 10, u'value': u'!qb'}", "{u'id': 11, u'value': u'!qB'}"`

`extra_scripts = ,`

`allowed_extensions = nfo, idx, sub, srt`

**Comment by sharkykh** [comment]
Alright, if you want to fix this yourself (it will be fixed automatically in the next version):
1. Shut down Medusa
2. In `config.ini` Replace the entire `sync_files` line with:
`sync_files = !sync, lftp-pget-status, part, bts, !qb, !qB`
3. Start Medusa - should be fixed

Just keep in mind that until #5163 is merged and released,
if you save the post-processing config, it might go back to the invalid values.

**Comment by cairobraga** [comment]
okay @sharkykh, thank you very very much!
