### ISSUE TITLE
Checking AniDB scene exceptions update failed for <anime title>. Error: 'NoneType' object has no attribute 'findall'

### ISSUE THREAD

**Issue by bellini666** [pymedusa/Medusa#5295]
I'm seeing this issue sometimes in my error log. I'm using the latest medusa version released.

```2018-09-22 10:33:36 ERROR    MAIN :: [4614efc] Checking AniDB scene exceptions update failed for One-Punch Man. Error: 'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "/srv/extra/tvmedia/apps/medusa/medusa/scene_exceptions.py", line 415, in _get_anidb_exceptions
    cache_path=join(app.CACHE_DIR, 'adba')
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBAbstracter.py", line 119, in __init__
    self.aid = self.tvDBMap.get_anidb_for_tvdb(self.tvdb_id)
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBtvDBmaper.py", line 30, in get_anidb_for_tvdb
    return self._get_x_for_y(tvdb_id, "tvdbid", "anidbid")
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBtvDBmaper.py", line 35, in _get_x_for_y
    for anime in self.xmlMap.findall("anime"):
AttributeError: 'NoneType' object has no attribute 'findall'
2018-09-22 10:33:36 ERROR    MAIN :: [4614efc] Checking AniDB scene exceptions update failed for Attack on Titan. Error: 'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "/srv/extra/tvmedia/apps/medusa/medusa/scene_exceptions.py", line 415, in _get_anidb_exceptions
    cache_path=join(app.CACHE_DIR, 'adba')
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBAbstracter.py", line 119, in __init__
    self.aid = self.tvDBMap.get_anidb_for_tvdb(self.tvdb_id)
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBtvDBmaper.py", line 30, in get_anidb_for_tvdb
    return self._get_x_for_y(tvdb_id, "tvdbid", "anidbid")
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBtvDBmaper.py", line 35, in _get_x_for_y
    for anime in self.xmlMap.findall("anime"):
AttributeError: 'NoneType' object has no attribute 'findall'
2018-09-22 10:33:36 ERROR    MAIN :: [4614efc] Checking AniDB scene exceptions update failed for Neon Genesis Evangelion. Error: 'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "/srv/extra/tvmedia/apps/medusa/medusa/scene_exceptions.py", line 415, in _get_anidb_exceptions
    cache_path=join(app.CACHE_DIR, 'adba')
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBAbstracter.py", line 119, in __init__
    self.aid = self.tvDBMap.get_anidb_for_tvdb(self.tvdb_id)
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBtvDBmaper.py", line 30, in get_anidb_for_tvdb
    return self._get_x_for_y(tvdb_id, "tvdbid", "anidbid")
  File "/srv/extra/tvmedia/apps/medusa/ext/adba/aniDBtvDBmaper.py", line 35, in _get_x_for_y
    for anime in self.xmlMap.findall("anime"):
AttributeError: 'NoneType' object has no attribute 'findall'```

**Comment by hackedbellini** [comment]
@p0psicles there's no xml file inside my `cache/abda/` folder. The only xml file that I saw there was inside the `cache/` folder itself named `anime-list.xml`

**Comment by bellini666** [comment]
@p00chie I'm always seeing this issue from time to time. Anything else you want me to try?

**Comment by h3llrais3r** [comment]
Having the same issue lately...
```
2018-12-30 14:35:45 ERROR    SEARCHQUEUE-BACKLOG-281249 :: [918cfe7] Checking AniDB scene exceptions update failed for Solty Rei. Error: 'NoneType' object has no attribute 'findall'
Traceback (most recent call last):
  File "C:\Tools\Github\Medusa\medusa\scene_exceptions.py", line 421, in _get_anidb_exceptions
    cache_path=join(app.CACHE_DIR, 'adba')
  File "C:\Tools\Github\Medusa\ext\adba\aniDBAbstracter.py", line 122, in __init__
    self.aid = self.tvDBMap.get_anidb_for_tvdb(self.tvdb_id)
  File "C:\Tools\Github\Medusa\ext\adba\aniDBtvDBmaper.py", line 30, in get_anidb_for_tvdb
    return self._get_x_for_y(tvdb_id, "tvdbid", "anidbid")
  File "C:\Tools\Github\Medusa\ext\adba\aniDBtvDBmaper.py", line 35, in _get_x_for_y
    for anime in self.xmlMap.findall("anime"):
AttributeError: 'NoneType' object has no attribute 'findall'
```

Running version:
```
Branch: master 
Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 
Version: v0.2.14 
Database: 44.12
```

**Comment by gomera** [comment]
same as @h3llrais3r, I have exactly the same log

**Comment by gomera** [comment]
it is an xml of 28k lines, maybe a parsing issue? :)

**Comment by p0psicles** [comment]
it should be near 82k lines?

**Comment by gomera** [comment]
don't know @p0psicles, but it looks quite good. Anyway, I removed it like an hour ago and so far the file was not re generated. The "Add show" is still not working but I'm not seeing the error on the logs anymore ...

**Comment by p0psicles** [comment]
What do you mean with the "add show" is still not working?

**Comment by gomera** [comment]
Sorry, it was a very lousy statement from my part ... I am talking about:

Home > Add Recommended Shows > Add From Anidb's Hot Anime list

Route: /addShows/popularAnime/

That routing shows only one entry that I checked from here and it is the 11th most popular anime at anidb right now.

https://anidb.net/perl-bin/animedb.pl?show=latest2&do=hotanime

**Comment by p0psicles** [comment]
Aah yes I also noticed that. I'll check that out. Normally it's showing like around 6 of them. It's mostly because it only displays shows which have a mapping to tvdb.

**Comment by p0psicles** [comment]
If this is still an issue, go into cache folder and remove recommended.dbm and anidb.dbm. Should show about 6 anime now
