### ISSUE TITLE
[APP SUBMITTED]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#5303]
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@fd35974129b74e51a4d40d79ea985956b08dbd72
**Link to Log**: https://gist.github.com/d6598ac3792c812ba2b2cacc19cbcae0
### ERROR
<pre>
2018-09-24 23:56:40 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [CinemaZ] :: [fd35974] BraceMessage string formatting failed. Using representation instead.
u'  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap\n    self.__bootstrap_inner()\n  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner\n    self.run()\n  File "/home/pi/Medusa/medusa/search/queue.py", line 296, in run\n    log.exception(\'DailySearchQueueItem Exception, error: {error}\', {\'error\': error})\n  File "/home/pi/Medusa/medusa/logger/adapters/style.py", line 101, in exception\n    self.log(logging.ERROR, msg, *args, **kwargs)\n  File "/home/pi/Medusa/medusa/logger/adapters/style.py", line 96, in log\n    self.logger.log(level, msg, **kwargs)\n  File "/usr/lib/python2.7/logging/__init__.py", line 1482, in log\n    self.logger.log(level, msg, *args, **kwargs)\n  File "/usr/lib/python2.7/logging/__init__.py", line 1224, in log\n    self._log(level, msg, args, **kwargs)\n  File "/usr/lib/python2.7/logging/__init__.py", line 1279, in _log\n    self.handle(record)\n  File "/usr/lib/python2.7/logging/__init__.py", line 1289, in handle\n    self.callHandlers(record)\n  File "/usr/lib/python2.7/logging/__init__.py", line 1329, in callHandlers\n    hdlr.handle(record)\n  File "/usr/lib/python2.7/logging/__init__.py", line 757, in handle\n    self.emit(record)\n  File "/usr/lib/python2.7/logging/handlers.py", line 78, in emit\n    logging.FileHandler.emit(self, record)\n  File "/usr/lib/python2.7/logging/__init__.py", line 950, in emit\n    StreamHandler.emit(self, record)\n  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit\n    msg = self.format(record)\n  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format\n    return fmt.format(record)\n  File "/home/pi/Medusa/medusa/logger/__init__.py", line 562, in format\n    msg = super(CensoredFormatter, self).format(record)\n  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format\n    record.message = record.getMessage()\n  File "/usr/lib/python2.7/logging/__init__.py", line 331, in getMessage\n    msg = str(self.msg)\n  File "/home/pi/Medusa/medusa/init/logconfig.py", line 84, in __str__\n    result = text_type(self.fmt)\n  File "/home/pi/Medusa/ext2/future/types/newobject.py", line 78, in __unicode__\n    s = type(self).__str__(self)\n  File "/home/pi/Medusa/medusa/logger/adapters/style.py", line 55, in __str__\n    \'\'.join(traceback.format_stack()),\n'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/fd35974129b74e51a4d40d79ea985956b08dbd72/medusa/logger/adapters/style.py#L40">medusa/logger/adapters/style.py</a>", line 40, in __str__
    return self.msg.format(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
@medariox Is this what's expected? https://github.com/pymedusa/Medusa/issues/3575#issuecomment-424680190

**Comment by medariox** [comment]
@duramato It should have only reported https://github.com/pymedusa/Medusa/issues/3575#issuecomment-424680190

**Comment by p0psicles** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-4-amd64-x86_64-with-debian-9.2`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@65697f1ff981604661aa60885482207d4bcf9055
**Link to Log**: https://gist.github.com/99060e5bbc3a6ee3e89a2ea673faedbd
### ERROR
<pre>
2018-09-28 07:03:58 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TokyoToshokan] :: [65697f1] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/65697f1ff981604661aa60885482207d4bcf9055/medusa/logger/adapters/style.py#L37">medusa/logger/adapters/style.py</a>", line 37, in __str__
    return self.msg.format(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 133: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
### INFO
**Python Version**: `2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-4-amd64-x86_64-with-debian-9.2`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@65697f1ff981604661aa60885482207d4bcf9055
**Link to Log**: https://gist.github.com/72920808a5f892f24a21b3be3a6558eb
### ERROR
<pre>
2018-09-27 21:54:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Nyaa] :: [65697f1] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/65697f1ff981604661aa60885482207d4bcf9055/medusa/logger/adapters/style.py#L37">medusa/logger/adapters/style.py</a>", line 37, in __str__
    return self.msg.format(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 171: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Olivier6767** [comment]
### INFO
**Python Version**: `2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with-debian-9.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/3ca766685e401c0ddf9ae944c9e52505
### ERROR
<pre>
2018-11-01 13:34:52 ERROR    POSTPROCESSOR :: [0c0a735] Exception generated: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/Services/cinema/medusa/Medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/scheduler.py#L93">medusa/scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "/home/Services/cinema/medusa/Medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/auto_post_processor.py#L58">medusa/auto_post_processor.py</a>", line 58, in run
    process_tv.ProcessResult(app.TV_DOWNLOAD_DIR, app.PROCESS_METHOD).process(force=force)
  File "/home/Services/cinema/medusa/Medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/process_tv.py#L145">medusa/process_tv.py</a>", line 145, in process
    ignore_subs=ignore_subs)
  File "/home/Services/cinema/medusa/Medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/process_tv.py#L335">medusa/process_tv.py</a>", line 335, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/home/Services/cinema/medusa/Medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/process_tv.py#L556">medusa/process_tv.py</a>", line 556, in process_media
    self.result = processor.process()
  File "/home/Services/cinema/medusa/Medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/post_processor.py#L1289">medusa/post_processor.py</a>", line 1289, in process
    notifiers.notify_download(ep_obj._format_pattern('%SN - %Sx%0E - %EN - %QN'))
  File "/home/Services/cinema/medusa/Medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/notifiers/__init__.py#L92">medusa/notifiers/__init__.py</a>", line 92, in notify_download
    n.notify_download(ep_name)
  File "/home/Services/cinema/medusa/Medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/notifiers/emailnotify.py#L153">medusa/notifiers/emailnotify.py</a>", line 153, in notify_download
    msg['Subject'] = 'Downloaded: ' + ep_name
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Sarcas666** [comment]
### INFO
**Python Version**: `2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]`
**Operating System**: `Darwin-18.2.0-x86_64-i386-64bit`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-02-04 22:19:20 ERROR    FINDSUBTITLES :: [918cfe7] Exception generated: 'ascii' codec can't decode byte 0xe2 in position 25: ordinal not in range(128)
Traceback (most recent call last):
  File "/Applications/Medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/scheduler.py#L93">medusa/scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "/Applications/Medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/subtitles.py#L1061">medusa/subtitles.py</a>", line 1061, in run
    episode_object.download_subtitles()
  File "/Applications/Medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/tv/episode.py#L485">medusa/tv/episode.py</a>", line 485, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/Applications/Medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/subtitles.py#L452">medusa/subtitles.py</a>", line 452, in download_subtitles
    return save_subs(tv_episode, video, found_subtitles, video_path=video_path)
  File "/Applications/Medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/subtitles.py#L477">medusa/subtitles.py</a>", line 477, in save_subs
    single=not app.SUBTITLES_MULTI)
  File "/Applications/Medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/subliminal/core.py#L755">ext/subliminal/core.py</a>", line 755, in save_subtitles
    subtitle_path = os.path.join(directory, os.path.split(subtitle_path)[1])
  File "/Applications/Medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/init/filesystem.py#L112">medusa/init/filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 25: ordinal not in range(128)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
