### ISSUE TITLE
Yggtorrent (again)

### ISSUE THREAD

**Issue by Naokor** [pymedusa/Medusa#5322]
Hello !

Yggtorrent changed (again) its url to yggtorrent.to recently. I don't know if this is related but I have the following error in develop :

```
2018-09-28 17:02:32 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Yggtorrent] :: [eea3396] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/home/**********/.medusa/medusa/logger/adapters/style.py", line 37, in __str__
    return self.msg.format(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 164: ordinal not in range(128)
2018-09-28 17:02:32 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Yggtorrent] :: [eea3396] BraceMessage(u'DailySearchQueueItem Exception, error: {error}', {u'error': GuessitException('An internal error has occured in guessit.\n===================== Guessit Exception Report =====================\nversion=3.0.0\nstring=Steins;Gate..-.Fuka.Ryouiki.no.D\xc3\xa9j\xc3\xa0.vu.VOSTFR.WEB-DL.1080p.x264-GoGoL\noptions={\'allowed_languages\': [\'de\', \'en\', \'es\', \'ca\', \'fr\', \'he\', \'hu\', \'it\', \'jp\', \'nl\', \'pl\', \'pt\', \'ro\', \'ru\', \'sv\', \'uk\', \'mul\', \'und\'], \'expected_group\': [\'TV2LAX9\', \'DHD\', \'20-40\', \'E7\'], \'expected_title\': [], \'allowed_countries\': [\'us\', \'gb\'], \'episode_prefer_number\': False, \'show_type\': None, \'type\': \'episode\', \'implicit\': True}\n--------------------------------------------------------------------\nTraceback (most recent call last):\n  File "/home/**********/.medusa/ext/guessit/api.py", line 170, in guessit\n    matches = self.rebulk.matches(string, options)\n  File "/home/**********/.medusa/ext/rebulk/rebulk.py", line 288, in matches\n    self._execute_rules(matches, context)\n  File "/home/**********/.medusa/ext/rebulk/rebulk.py", line 319, in _execute_rules\n    rules.execute_all_rules(matches, context)\n  File "/home/**********/.medusa/ext/rebulk/rules.py", line 318, in execute_all_rules\n    when_response = execute_rule(rule, matches, context)\n  File "/home/**********/.medusa/ext/rebulk/rules.py", line 339, in execute_rule\n    when_response = rule.when(matches, context)\n  File "/home/**********/.medusa/medusa/name_parser/rules/rules.py", line 330, in when\n    alias.value += separator + alternative_title.value\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc3 in position 17: ordinal not in range(128)\n--------------------------------------------------------------------\nPlease report at https://github.com/guessit-io/guessit/issues.\n====================================================================',)}, exc_info=1, extra=None)
Traceback (most recent call last):
  File "/home/**********/.medusa/medusa/search/queue.py", line 263, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/home/**********/.medusa/medusa/search/core.py", line 532, in search_for_needed_episodes
    cur_provider.cache.update_cache()
  File "/home/**********/.medusa/medusa/tv/cache.py", line 233, in update_cache
    result = self._parse_item(item)
  File "/home/**********/.medusa/medusa/tv/cache.py", line 312, in _parse_item
    leechers, size, pubdate)
  File "/home/**********/.medusa/medusa/tv/cache.py", line 381, in add_cache_entry
    parse_result = parsed_result or NameParser().parse(name)
  File "/home/**********/.medusa/medusa/name_parser/parser.py", line 367, in parse
    result = self._parse_string(name)
  File "/home/**********/.medusa/medusa/name_parser/parser.py", line 275, in _parse_string
    guess = guessit.guessit(name, dict(show_type=self.show_type))
  File "/home/**********/.medusa/medusa/name_parser/guessit_parser.py", line 80, in guessit
    result = default_api.guessit(name, options=final_options)
  File "/home/**********/.medusa/ext/guessit/api.py", line 182, in guessit
    raise GuessitException(string, options)
GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.0.0
string=Steins;Gate..-.Fuka.Ryouiki.no.Déjà.vu.VOSTFR.WEB-DL.1080p.x264-GoGoL
options={'allowed_languages': ['de', 'en', 'es', 'ca', 'fr', 'he', 'hu', 'it', 'jp', 'nl', 'pl', 'pt', 'ro', 'ru', 'sv', 'uk', 'mul', 'und'], 'expected_group': ['TV2LAX9', 'DHD', '20-40', 'E7'], 'expected_title': [], 'allowed_countries': ['us', 'gb'], 'episode_prefer_number': False, 'show_type': None, 'type': 'episode', 'implicit': True}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/**********/.medusa/ext/guessit/api.py", line 170, in guessit
    matches = self.rebulk.matches(string, options)
  File "/home/**********/.medusa/ext/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/home/**********/.medusa/ext/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/home/**********/.medusa/ext/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/home/**********/.medusa/ext/rebulk/rules.py", line 339, in execute_rule
    when_response = rule.when(matches, context)
  File "/home/**********/.medusa/medusa/name_parser/rules/rules.py", line 330, in when
    alias.value += separator + alternative_title.value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```

Branch: develop Commit: eea33961878329cda8cc0aff9b8c76f241717cb8 
Version: v0.2.10 Database: 44.12
Python Version: | 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | en_US.UTF-8

Thank you for your help 👍

**Comment by medariox** [comment]
This is fixed in the latest release.
