### ISSUE TITLE
Conflict with scheduled post-processor and post-processing called by NZBtoMedia

### ISSUE THREAD

**Issue by desepticon** [pymedusa/Medusa#5396]
**Describe the bug**
Sometimes I get an error that a post-process can't be completed. But, it also reports that it has been completed. And the episode does show up in my server in the right place. Best I can figure, this is caused by a conflict with post-processing called by the NZBtoMedia completion script and the scheduled post-processor built into Medusa.

**To Reproduce**
1. Have SABnzb setup to call NZBtoMedia.py on completion
2. Also have scheduled post-processing enabled in Medusa
3. Sometimes the timing will match up and there is a conflict

**Expected behavior**
Perhaps Medusa should know that the post-processor is already running and decline to run another instance at that time.

**Medusa (please complete the following information):**
 - OS: [Mac OS 10.13.6 (running from source)]
 - Branch: [master]
 - Commit: [dunno what this means. latest version?]

**Logs:**
<details>

```
2018-10-13 05:45:05 INFO     POSTPROCESSOR :: [4614efc] Successfully processed.
2018-10-13 05:36:18 WARNING  POSTPROCESSOR :: [4614efc] /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv: Processing failed: Unable to move the files to their new home
2018-10-13 05:36:18 WARNING  POSTPROCESSOR :: [4614efc] Problem(s) during processing, failed for the following files/folders: 
2018-10-13 05:36:18 WARNING  POSTPROCESSOR :: [4614efc] Processing failed for /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv: Unable to move the files to their new home
2018-10-13 05:36:18 ERROR    POSTPROCESSOR :: [4614efc] Unable to move file /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv to /Volumes/azerty.7tb/TV/Crazy Ex-Girlfriend/Season 04/Crazy.Ex-Girlfriend.S04E01.I.Want.to.Be.Here.720p.HDTV-SVA.mkv: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/Users/matt/Builds/medusa/medusa/post_processor.py", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/Users/matt/Builds/medusa/medusa/helpers/__init__.py", line 315, in move_file
    copy_file(src_file, dest_file)
  File "/Users/matt/Builds/medusa/medusa/helpers/__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/Users/matt/Builds/medusa/lib/shutil_custom/__init__.py", line 32, in copyfile_custom
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "/Users/matt/Builds/medusa/medusa/init/filesystem.py", line 113, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 2] No such file or directory: '/Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv'
2018-10-13 05:36:10 INFO     TORNADO :: [4614efc] Successfully processed.
2018-10-13 05:36:10 INFO     TORNADO :: [4614efc] Deleting folder (if it's empty): /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA
2018-10-13 05:36:10 INFO     TORNADO :: [4614efc] Processing succeeded for /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv
2018-10-13 05:36:09 INFO     TORNADO :: [4614efc] Updating KODI library via JSON method for host: 127.0.0.1:8083
2018-10-13 05:36:09 INFO     TORNADO :: [4614efc] Pushover notification successful.
2018-10-13 05:36:08 INFO     TORNADO :: [4614efc] 295777: Changed modify date of Crazy.Ex-Girlfriend.S04E01.I.Want.to.Be.Here.720p.HDTV-SVA.mkv to series air date Oct 12,2018 (21:00)
2018-10-13 05:35:04 INFO     POSTPROCESSOR :: [4614efc] This download is marked a priority download so I'm going to replace an existing file if I find one
2018-10-13 05:35:04 INFO     POSTPROCESSOR :: [4614efc] New size: 1.02 GB
2018-10-13 05:35:04 INFO     POSTPROCESSOR :: [4614efc] New file: /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv
2018-10-13 05:35:04 INFO     POSTPROCESSOR :: [4614efc] Processing /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv
2018-10-13 05:34:50 INFO     TORNADO :: [4614efc] This download is marked a priority download so I'm going to replace an existing file if I find one
2018-10-13 05:34:50 INFO     TORNADO :: [4614efc] New size: 1.02 GB
2018-10-13 05:34:50 INFO     TORNADO :: [4614efc] New file: /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv
2018-10-13 05:34:50 INFO     TORNADO :: [4614efc] Processing /Volumes/dvorak.8tb/SABnzbd/tv/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA/Crazy.Ex-girlfriend.S04E01.720p.HDTV.x264-SVA.mkv
```
</details>

**Comment by medariox** [comment]
Post-processor won't run multiple times since a few versions.
