### ISSUE TITLE
API errors should always be JSON

### ISSUE THREAD

**Issue by OmgImAlexis** [pymedusa/Medusa#5425]
I'm currently getting this when trying to use the API without a valid key. This should be returning JSON even if I'm not asking for it.

```
Traceback (most recent call last):
  File "/Users/xo/code/Medusa/ext/tornado/web.py", line 1571, in _execute
    result = yield result
  File "/Users/xo/code/Medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/xo/code/Medusa/ext/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/Users/xo/code/Medusa/ext/tornado/gen.py", line 1221, in handle_yield
    self.future = convert_yielded(yielded)
  File "/Users/xo/code/Medusa/ext/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/xo/code/Medusa/ext/tornado/gen.py", line 1357, in convert_yielded
    return multi(yielded)
  File "/Users/xo/code/Medusa/ext/tornado/gen.py", line 773, in multi
    return multi_future(children, quiet_exceptions=quiet_exceptions)
  File "/Users/xo/code/Medusa/ext/tornado/gen.py", line 868, in multi_future
    children = list(map(convert_yielded, children))
  File "/Users/xo/code/Medusa/ext/singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/xo/code/Medusa/ext/tornado/gen.py", line 1363, in convert_yielded
    raise BadYieldError("yielded unknown object %r" % (yielded,))
BadYieldError: yielded unknown object u'No authorization token.'
```

**Comment by sharkykh** [comment]
Fixed with #6703
