### ISSUE TITLE
opensubtitles discarded

### ISSUE THREAD

**Issue by jerresmail** [pymedusa/Medusa#5484]
I am unable to download subtitles with opensubtitles.

Medusa Info: | Branch: master Commit: 4614efc77151ded92ef458a09dec39f8bd5acfc6 Version: v0.2.10 Database: 44.12
-- | --
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j 26 Sep 2016
OS: | Windows-10-10.0.17134
Locale: | en_BE.cp1252

```
2018-10-24 20:59:40 WARNING  Thread_6 :: [4614efc] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Medusa\Medusa\ext\subliminal\providers\opensubtitles.py", line 228, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "C:\Medusa\Medusa\ext\subliminal\providers\opensubtitles.py", line 183, in query
    response = checked(self.server.SearchSubtitles(self.token, criteria))
  File "C:\Medusa\Python\lib\xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "C:\Medusa\Python\lib\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "C:\Medusa\Python\lib\xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Medusa\Python\lib\xmlrpclib.py", line 1313, in single_request
    response = h.getresponse(buffering=True)
  File "C:\Medusa\Python\lib\httplib.py", line 1108, in getresponse
    raise ResponseNotReady()
ResponseNotReady
```

**Comment by jerresmail** [comment]
No, the error keeps coming.

I created a new account to verify and immediately get the error:
2018-11-01 20:34:01 DEBUG    FINDSUBTITLES :: [0c0a735] Discarding provider opensubtitles
2018-11-01 20:34:01 WARNING  FINDSUBTITLES :: [0c0a735] Provider u'opensubtitles' unavailable
2018-11-01 20:34:00 DEBUG    FINDSUBTITLES :: [0c0a735] Initializing provider opensubtitles
2018-11-01 20:34:00 DEBUG    FINDSUBTITLES :: [0c0a735] Listing subtitles with provider u'opensubtitles' and languages set([<Language [nl]>])

**Comment by medariox** [comment]
You are IP blocked or something.

**Comment by jerresmail** [comment]
I can manually download without issues.

**Comment by medariox** [comment]
Manual download != API hits.
