### ISSUE TITLE
[APP SUBMITTED]: BraceException: {indexerid}: {error}

### ISSUE THREAD

**Issue by aboodi0** [pymedusa/Medusa#5560]
### INFO
**Python Version**: `2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.15.0-38-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-10-30 03:20:40 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/home/quickbox/.medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa/logger/adapters/style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "/home/quickbox/.medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa/logger/adapters/style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Thank you for the bug report. This will be fixed with: https://github.com/pymedusa/Medusa/pull/5562

**Comment by fatb0y** [comment]
### INFO
**Python Version**: `2.7.15 (default, Sep 12 2018, 19:21:21) [GCC 7.3.0]`
**Operating System**: `Linux-4.14.40-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2699_v3_@_2.30GHz-with-gentoo-2.4.1`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/a0be81e973667e6f0dee5469f9f5824d
### ERROR
<pre>
2018-10-31 03:03:52 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/mnt/mpatho/**********/medusa/medusa/logger/adapters/style.py", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "/mnt/mpatho/**********/medusa/medusa/logger/adapters/style.py", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/854c50d0a0fb5bd51488bb892ecd99f8
### ERROR
<pre>
2018-10-31 12:07:44 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bassings** [comment]
### INFO
**Python Version**: `2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]`
**Operating System**: `Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/ee40933cf4008621aba62fcaa155c2a2
### ERROR
<pre>
2018-11-04 03:08:39 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/logger/adapters/style.py", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "/var/lib/**********mediaserver/medusa/medusa/logger/adapters/style.py", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/3c6ff2c1deb57f15d87bbeb5cd8f65de
### ERROR
<pre>
2018-11-05 12:09:17 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/ed17980d8eed6a40058fba72ba1ad3c0
### ERROR
<pre>
2018-11-06 12:08:56 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by theystillcallmemister** [comment]
### INFO
**Python Version**: `2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]`
**Operating System**: `Linux-4.18.15-unRAID-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/d59cdf6213566121631c837179a86009
### ERROR
<pre>
2018-11-07 03:37:07 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa/logger/adapters/style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa/logger/adapters/style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pct00** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/a34c056577ddaca3cc4efd95630122f8
### ERROR
<pre>
2018-11-07 02:50:42 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pct00** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/568e8942784ecea83ff2cba94ab6f238
### ERROR
<pre>
2018-11-09 02:34:27 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/2cd3643c7bb4bb8de3d820ad59341048
### ERROR
<pre>
2018-11-09 12:03:59 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/78cec0c4c6084e7cb29e1d074ed95abc
### ERROR
<pre>
2018-11-12 12:09:47 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MotleyC** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/484f04fdfd58de8111d5b45c9eb71b5e
### ERROR
<pre>
2018-11-14 12:05:48 ERROR    SHOWQUEUE-REFRESH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: u'indexerid'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: {indexerid}: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
