### ISSUE TITLE
[APP SUBMITTED]: ValueError: Supported authentication are: basic and digest

### ISSUE THREAD

**Issue by fatb0y** [pymedusa/Medusa#5566]
### INFO
**Python Version**: `2.7.15 (default, Sep 12 2018, 19:21:21) [GCC 7.3.0]`
**Operating System**: `Linux-4.14.40-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2699_v3_@_2.30GHz-with-gentoo-2.4.1`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/7419aaad28c9eaf72744aad229ecda2b
### ERROR
<pre>
2018-10-30 20:43:52 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [0c0a735] DailySearchQueueItem Exception, error: Supported authentication are: basic and digest
Traceback (most recent call last):
  File "/mnt/mpatho/**********/medusa/medusa/search/queue.py", line 289, in run
    self.success = snatch_episode(result)
  File "/mnt/mpatho/**********/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/mnt/mpatho/**********/medusa/medusa/clients/torrent/generic.py", line 246, in send_torrent
    if not self._get_auth():
  File "/mnt/mpatho/**********/medusa/medusa/clients/torrent/rtorrent_client.py", line 53, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 82, in __init__
    self._verify_conn()
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 121, in _verify_conn
    assert 'system.client_version' in self._get_rpc_methods(
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 159, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 149, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 113, in _get_conn
    proxies=proxies),
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 73, in __init__
    "Supported authentication are: basic and digest")
ValueError: Supported authentication are: basic and digest
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
What does your rTorrent configuration look like?

**Comment by fatb0y** [comment]
### INFO
**Python Version**: `2.7.15 (default, Sep 12 2018, 19:21:21) [GCC 7.3.0]`
**Operating System**: `Linux-4.14.40-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2699_v3_@_2.30GHz-with-gentoo-2.4.1`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: https://gist.github.com/df1a6ff29eeffd034497f4fdc0f36f55
### ERROR
<pre>
2018-10-31 13:14:47 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [0c0a735] DailySearchQueueItem Exception, error: Supported authentication are: basic and digest
Traceback (most recent call last):
  File "/mnt/mpatho/**********/medusa/medusa/search/queue.py", line 289, in run
    self.success = snatch_episode(result)
  File "/mnt/mpatho/**********/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/mnt/mpatho/**********/medusa/medusa/clients/torrent/generic.py", line 246, in send_torrent
    if not self._get_auth():
  File "/mnt/mpatho/**********/medusa/medusa/clients/torrent/rtorrent_client.py", line 53, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 82, in __init__
    self._verify_conn()
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 121, in _verify_conn
    assert 'system.client_version' in self._get_rpc_methods(
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 159, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 149, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/__init__.py", line 113, in _get_conn
    proxies=proxies),
  File "/mnt/mpatho/**********/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 73, in __init__
    "Supported authentication are: basic and digest")
ValueError: Supported authentication are: basic and digest
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
