### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 13] Permission denied: u'F:\\TV Shows\\The Good Place\\The Good Place - 3x03 - The Snowplow.mkv'

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/Medusa#5600]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@0c0a73583452f988c518adeafa75ee1f17987bdf
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-10-30 15:36:02 ERROR    POSTPROCESSOR :: [0c0a735] Unable to move file D:\ADMIN\comp\tv\The Good Place S03E04 1080p AMZN WEB-DL DDP5 1 H264-SiGMA\The.Good.Place.S03E04.Jeremy.Bearimy.1080p.AMZN.WEB-DL.DDP5.1.H264-SiGMA.mkv to F:\TV Shows\The Good Place\The Good Place - 3x03 - The Snowplow.mkv: IOError(13, 'Permission denied')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/post_processor.py#L472">medusa\post_processor.py</a>", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/helpers/__init__.py#L312">medusa\helpers\__init__.py</a>", line 312, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/init/filesystem.py#L112">medusa\init\filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "C:\Python27\Lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "C:\Python27\Lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/lib/shutil_custom/__init__.py#L32">lib\shutil_custom\__init__.py</a>", line 32, in copyfile_custom
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "C:\Medusa\Medusa\<a href="../blob/0c0a73583452f988c518adeafa75ee1f17987bdf/medusa/init/filesystem.py#L112">medusa\init\filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 13] Permission denied: u'F:\\TV Shows\\The Good Place\\The Good Place - 3x03 - The Snowplow.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by amandalfrench** [comment]
I am having this issue as well. Am unable to move or copy any files to my file system and I have given everything full access

**Comment by p0psicles** [comment]
Tried replicating the action with the same user medusa is running?

**Comment by amandalfrench** [comment]
my system isn't allowing me to login as the medusa user. When I try it kicks me out
