### ISSUE TITLE
New Post-Processing error with newest vesion 0.2.11

### ISSUE THREAD

**Issue by QuickSwitchLK** [pymedusa/Medusa#5614]
Since the latest version I can no longer manually process this directory on my Synology,

/volume1/My NAS Downloads/09 ] - My Clean TV Series ➡ Medusa

it results in the following error in the log.

2018-11-04 11:58:55 ERROR    Thread_16 :: [0c0a735] Exception generated: 'ascii' codec can't decode byte 0xe2 in position 52: ordinal not in range(128)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/server/web/home/post_process.py", line 46, in processEpisode
    result = process_tv.ProcessResult(ss(proc_dir), process_method=process_method).process(
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/process_tv.py", line 34, in __init__
    self.directory = path
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/process_tv.py", line 52, in directory
    self.log('Processing path: {0}'.format(path), logger.DEBUG)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 52: ordinal not in range(128)

Obviously it is the "➡" character in the directory that is the problem as I have made another directory of the same name, but have just omitted the "➡"

/volume1/My NAS Downloads/09 ] - My Clean TV Series Medusa

This works fine.

**Medusa (please complete the following information):**
 - OS: Synology
 - Branch: master
 - Version 0.2.11 (2018-10-29)

**Comment by medariox** [comment]
Closing as solved, please reply if it's not the case.
