### ISSUE TITLE
Trying to import existing shows (former sickrage user)

### ISSUE THREAD

**Issue by Shadey1** [pymedusa/Medusa#5618]
I've moved to medusa after the recent drama, I waited a while to see if it stabilised but it was messy and I thought it was time for a new option.

I mapped to the same localport as the old install, removed the old service, replaced it with medusa. Renamed the old sickrage driectory to take out any startuplinks, and keep a copy just in case I needed anything.

Used symlinks to map my network drive, can see all the folders, checked all the shows I wanted adding/tried all shows once too...

...it appears to stall while adding.
I check the error log and get the below, my loose understanding is it's failing with the metadata which I'm pretty sure was set as Kodi compliant in sickrage.
```
2018-11-04 12:17:23 ERROR    Thread_9 :: [0c0a735] Exception generated: 'ascii' codec can't decode byte 0xe2 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "E:\Medusa\Medusa\medusa\server\web\core\base.py", line 258, in async_call
    result = function(**kwargs)
  File "E:\Medusa\Medusa\medusa\server\web\home\add_shows.py", line 543, in addExistingShows
    if '|' not in cur_dir:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 23: ordinal not in range(128)
```
The warning log is full of;
```
WARNING  APIv2-Thread_3 :: [0c0a735] There was an error parsing your existing metadata file: E:\TVLINK\The Walking Dead\tvshow.nfo error: error b'no element found: line 1, column 0'
```
As a way of checking that it was all working, I also tried to use 'add from IMDB's popular shows' and it just seems to time out on 'waiting for localhost...'

Trakt most anticipated shows opens, but just sits on 'loading trending shows'

I can add a new show from scratch, set the quality etc. I picked a show the wife has watched on netflix to test.

I tried to add 1 show only before hitting upload on this, and it actually started to add it, and seems to have worked, which now has me hugely confused. I also got the exact same errors as before! 
Actually I can get it to do 4 at a time, is it by adding say 50+ it craps out?

So I've been adding maybe 5-10 at a time, and I get things like:
```
2018-11-04 14:04:23 INFO     SHOWQUEUE-ADD :: [0c0a735] Building internal name cache for BoJack Horseman
2018-11-04 14:04:23 INFO     SHOWQUEUE-ADD :: [0c0a735] Finished processing 2906 scene exceptions.
2018-11-04 14:04:23 INFO     SHOWQUEUE-ADD :: [0c0a735] Updating exception_cache and exception_season_cache
2018-11-04 14:04:16 INFO     SHOWQUEUE-ADD :: [0c0a735] Setting all previously aired episodes to the specified status: Skipped
**2018-11-04 14:04:13 INFO     SHOWQUEUE-ADD :: [0c0a735] 282254: Unable to find the show in the database**
2018-11-04 14:04:09 INFO     SHOWQUEUE-ADD :: [0c0a735] TVDBv2: {u'session': <medusa.session.core.MedusaSession object at 0x0000000006FB6EF0>, u'cache': u'E:\\Medusa\\Data\\cache\\indexers\\TVDBv2', u'language': u'en', u'use_zip': True}
2018-11-04 14:04:09 INFO     SHOWQUEUE-ADD :: [0c0a735] Starting to add show by ShowDir: E:\TVLINK\Bojack Horseman
```
I've bolded the bits that jump out.

**Comment by p0psicles** [comment]
The add from recommended should work now. First time loading takes long, but everything is cached for next time.

**Comment by p0psicles** [comment]
Can you share the content of this nfo? `:\TVLINK\The Walking Dead\tvshow.nfo`

**Comment by Shadey1** [comment]
I've just opened it, and its blank!

**Comment by p0psicles** [comment]
Then I would remove the nfo's. as those are bugging your import.

**Comment by Shadey1** [comment]
Yeah just did, I can import a chunk at a time now, but I've got about 150 I want to add now to rectify the nfo issue. It simply stalls if I do more than 10, no error, no time out, it's like I never clicked submit.

But if I look to the log (2 tabs open):

2018-11-04 16:05:58 ERROR    Thread_0 :: [0c0a735] Exception generated: 'ascii' codec can't decode byte 0xe2 in position 23: ordinal not in range(128)
Traceback (most recent call last):
  File "E:\Medusa\Medusa\medusa\server\web\core\base.py", line 258, in async_call
    result = function(**kwargs)
  File "E:\Medusa\Medusa\medusa\server\web\home\add_shows.py", line 543, in addExistingShows
    if '|' not in cur_dir:

Am i simply asking too much of it?

**Comment by p0psicles** [comment]
any shows with unicode chars in the path?

**Comment by Shadey1** [comment]
1, 3% but I've skipped past that one now after doing it manually.
The ' is the only other thing I can think of that might be unicode, but there are a tonne of them in the directory list. Everything else is letters or numbers

Best I've got is about 30 in one go.

**Comment by OmgImAlexis** [comment]
@Shadey1 just a tip if you have a section of logs, etc. add three backticks before it so you have a code block like so.

````
```
Logs go here
```
````

**Comment by p0psicles** [comment]
I have a fix in the works for importing existing shows wit accents

**Comment by Shadey1** [comment]
> I have a fix in the works for importing existing shows wit accents

Thanks dude.

**Comment by medariox** [comment]
This should be fixed, just update to the latest version. Please reply if it's not the case.
