### ISSUE TITLE
[0c0a735] BraceMessage string formatting failed. Using representation instead.

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#5632]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Synology
 - Branch: master

Medusa Info: | Branch: master Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf Version: v0.2.11 Database: 44.12
-- | --
Python Version: | 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]
SSL Version: | OpenSSL 1.0.2n 7 Dec 2017
OS: | Linux-4.4.59+-x86_64-with-glibc2.2.5
Locale: | Unknown.Unknown

**Logs:**
<details>

```
2018-11-05 07:34:32 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [0c0a735] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/logger/adapters/style.py", line 53, in __str__
    return self.msg.format(*args)
KeyError: u"u'version'"
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/logger/adapters/style.py", line 60, in __str__
    raise BraceException(self.msg)
BraceException: Add torrent URI with data: {u'version': u'1', u'api': u'SYNO.DownloadStation.Task', u'destination': u'DOWNLOADSTATION', u'uri': u'magnet:?xt=urn:btih:b68a96c9adb3aca40c3234216b71ba1e3f392a3f&dn=The.Last.Ship.S05E09.720p.WEBRip.x264-TBS%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=http://tracker.opentrackr.org:1337/announce&tr=udp://p4p.arenabg.com:1337/announce&tr=http://p4p.arenabg.com:1337/announce&tr=udp://explodie.org:6969/announce&tr=udp://9.rarbg.com:2710/announce&tr=http://explodie.org:6969/announce&tr=http://tracker.dler.org:6969/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://ipv4.tracker.harry.lu:80/announce&tr=http://ipv4.tracker.harry.lu:80/announce&tr=udp://mgtracker.org:2710/announce&tr=http://mgtracker.org:6969/announce&tr=udp://tracker.mg64.net:6969/announce&tr=http://tracker.mg64.net:6881/announce&tr=http://torrentsmd.com:8080/announce', u'session': u'DownloadStation', u'method': u'create'}
```
</details>

**Additional context**

**Comment by LaBoss** [comment]
See issue #5588

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5644
