### ISSUE TITLE
[ERROR] Adding Exisiting shows

### ISSUE THREAD

**Issue by Tearow** [pymedusa/Medusa#5661]
**Describe the bug**
Does not process exisiting shows upon pressing the submit button nothing happens. in the log an error will show

**To Reproduce**
1. Go to 'Shows'
2. Click on 'Add Exisiting Show'
3. Scroll down to 'Submit'

**Expected behavior**
Process the existing shows

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Synology
 - Branch: Master
 - Commit: 0c0a73583452f988c518adeafa75ee1f17987bdf 

**Logs:**
<details>
2018-11-07 09:40:17 ERROR    Thread_3 :: [0c0a735] Exception generated: 'ascii' codec can't decode byte 0xc2 in position 16: ordinal not in range(128)
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/add_shows.py", line 543, in addExistingShows
    if '|' not in cur_dir:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 16: ordinal not in range(128)
</details>

**Additional context**

**Comment by p0psicles** [comment]
Im in process of fixing it. As in a fix is being tested right now

**Comment by medariox** [comment]
Should be fixed in develop with https://github.com/pymedusa/Medusa/pull/5635
