### ISSUE TITLE
White page when manual searching after upgrading to 0.2.11

### ISSUE THREAD

**Issue by ParnBlade** [pymedusa/Medusa#5664]
**Describe the bug**
Hello, When i launch a manual search i have got a white page and a error ( afte the last upgrade 0.2.11) : 
````
2018-11-07 18:30:40 ERROR    Thread_2 :: [J-Downloadville] :: [0c0a735] Exception generated: 'ascii' codec can't encode character u'\xe9' in position 22: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/handler.py", line 1152, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/opt/medusa/medusa/search/manual.py", line 200, in get_provider_cache_results
    threading.currentThread().name = '{thread} :: [{provider}]'.format(thread=original_thread_name, provider=cur_provider.name)
  File "/usr/lib/python2.7/threading.py", line 972, in name
    self.__name = str(name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 22: ordinal not in range(128)
````

**To Reproduce**
1. Go to any series en lauch manual search
2. Got a white page

**Medusa (please complete the following information):**
 - OS: Ubuntu 16.04.5 LTS
 - Branch: master
- git show
commit 0c0a73583452f988c518adeafa75ee1f17987bdf
Merge: 4614efc 0f03ffd
Author: Dario <medariox@users.noreply.github.com>
Date:   Mon Oct 29 18:02:38 2018 +0100

    Merge pull request #5542 from pymedusa/release/release-0.2.11

    Release 0.2.11
- try with the docker version and have the same issue

**Logs:**
```
2018-11-07 18:30:40 ERROR    Thread_2 :: [J-Downloadville] :: [0c0a735] Exception generated: 'ascii' codec can't encode character u'\xe9' in position 22: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/handler.py", line 1152, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "/opt/medusa/medusa/search/manual.py", line 200, in get_provider_cache_results
    threading.currentThread().name = '{thread} :: [{provider}]'.format(thread=original_thread_name, provider=cur_provider.name)
  File "/usr/lib/python2.7/threading.py", line 972, in name
    self.__name = str(name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 22: ordinal not in range(128)

```
</details>

**Additional context**
This append afterthe last upgrade to 0.2.11

I tried to find a solution bug got nothing that help me.
Thanks to Medusa !!!! Great Job ;)

**Comment by p0psicles** [comment]
Did you add a provider name with unicode chars in it?

**Comment by ParnBlade** [comment]
Hi ! Thanks :)
I have those provider (and i got them befor the update with no problem) : 
I will try to remove "-" and "é" ...

![image](https://user-images.githubusercontent.com/15016812/48151307-388b0300-e2c1-11e8-8818-3d75a6fe463d.png)

**Comment by medariox** [comment]
Just replace the `é` with `e`, that will be enough. We removed a dirty hack in the last update, so that could be the reason why it was working for you before. Do you have your locale set? That might solve your issue as well.

**Comment by ParnBlade** [comment]
Greate !!! I remove the "é" from J-Mononoké-BT and the manual search work again !!!

My locale are : 
```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Thanks for the help and have a nice day !

**Comment by ParnBlade** [comment]
I still have the issue when i post process series witch have "é" or perhaps other characters.
- Is my locales wrong ?
I have already do what you say (for the root user) [in your wiki](https://github.com/pymedusa/Medusa/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-é-etc-what-can-i-do)

- How to define the good locales ?

Thanks

**Comment by p0psicles** [comment]
Can you share a debug log of the postprocessing?

**Comment by ParnBlade** [comment]
Should i wait for a release or change to develop branch and how to do it properly ?

**Comment by medariox** [comment]
Thanks for the confirmation @ParnBlade 👍

**Comment by shaavik** [comment]
I have the same error in last build 2.14 (either master or develop).
Using Windows version.
I am searching "13 Reason Why", so no accent inside.

2019-01-12 18:46:15 ERROR    Thread_8 :: [Yggtorrent] :: [abbb17e] Exception generated: 'ascii' codec can't encode character u'\xe9' in position 20: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 262, in async_call
    result = function(**kwargs)
  File "C:\Medusa\Medusa\medusa\server\web\home\handler.py", line 1139, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "C:\Medusa\Medusa\medusa\search\manual.py", line 200, in get_provider_cache_results
    threading.currentThread().name = '{thread} :: [{provider}]'.format(thread=original_thread_name, provider=cur_provider.name)
  File "C:\Python27\lib\threading.py", line 972, in name
    self.__name = str(name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 20: ordinal not in range(128)
2019-01-12 18:41:08 ERROR    Thread_3 :: [Yggtorrent] :: [abbb17e] Exception generated: 'ascii' codec can't encode character u'\xe9' in position 20: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 262, in async_call
    result = function(**kwargs)
  File "C:\Medusa\Medusa\medusa\server\web\home\handler.py", line 1139, in snatchSelection
    show_all_results=show_all_results, **search_show)
  File "C:\Medusa\Medusa\medusa\search\manual.py", line 200, in get_provider_cache_results
    threading.currentThread().name = '{thread} :: [{provider}]'.format(thread=original_thread_name, provider=cur_provider.name)
  File "C:\Python27\lib\threading.py", line 972, in name
    self.__name = str(name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 20: ordinal not in range(128)

**Comment by p0psicles** [comment]
There is an accented `e` `é` somewhere?

**Comment by p0psicles** [comment]
Probably the provider in the list after yggtorrents

**Comment by shaavik** [comment]
Yes, one of the provider contains accent. When unchecking it, I can see manuel search page again.
