### ISSUE TITLE
Cannot connect to NAS File System

### ISSUE THREAD

**Issue by amandalfrench** [pymedusa/Medusa#5682]
I have tried giving the Medusa user permissions and changing the permissions of the mount point. Everytime it post process, i get these errors. Also tested with other user's folder on the same system, would not create folder or post process. Have tried giving the user medusa sudo privileges and that did not work.

```
2018-11-09 19:41:14 WARNING  POSTPROCESSOR :: [0c0a735] /home/odysseus/post/Titans.2018.S01E05.WEB.x264-PHOENiX[eztv].mkv: Processing failed: Unable to copy the files to their new home
2018-11-09 19:41:14 WARNING  POSTPROCESSOR :: [0c0a735] Problem(s) during processing, failed for the following files/folders: 
2018-11-09 19:41:14 WARNING  POSTPROCESSOR :: [0c0a735] Processing failed for /home/odysseus/post/Titans.2018.S01E05.WEB.x264-PHOENiX[eztv].mkv: Unable to copy the files to their new home
2018-11-09 19:41:14 ERROR    POSTPROCESSOR :: [0c0a735] Unable to copy file /home/odysseus/post/Titans.2018.S01E05.WEB.x264-PHOENiX[eztv].mkv to /mnt/atlas/TV Shows/Titans (2018)/Season 1 - 1x05 - Together.mkv: IOError(13, 'Permission denied')
Traceback (most recent call last):
  File "/opt/medusa/medusa/post_processor.py", line 482, in copy
    helpers.copy_file(cur_file_path, new_file_path)
  File "/opt/medusa/medusa/helpers/__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/opt/medusa/lib/shutil_custom/__init__.py", line 32, in copyfile_custom
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "/opt/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 13] Permission denied: '/mnt/atlas/TV Shows/Titans (2018)/Season 1 - 1x05 - Together.mkv'
2018-11-09 19:41:14 INFO     POSTPROCESSOR :: [0c0a735] This download is marked a priority download so I'm going to replace an existing file if I find one
2018-11-09 19:41:14 INFO     POSTPROCESSOR :: [0c0a735] New size: 179.18 MB
2018-11-09 19:41:14 INFO     POSTPROCESSOR :: [0c0a735] New file: /home/odysseus/post/Titans.2018.S01E05.WEB.x264-PHOENiX[eztv].mkv
2018-11-09 19:41:14 INFO     POSTPROCESSOR :: [0c0a735] Processing /home/odysseus/post/Titans.2018.S01E05.WEB.x264-PHOENiX[eztv].mkv
```

**Comment by amandalfrench** [comment]
sure thing. i apologize.

**Comment by medariox** [comment]
It's a permission issue, check the rights/owners. We can't really help you more.
