### ISSUE TITLE
Adding existing show with an ascii in it. Doesn't work

### ISSUE THREAD

**Issue by Diovarus** [pymedusa/Medusa#5706]
**Describe the bug**
2018-11-13 10:45:05 ERROR    Thread_5 :: [0c0a735] Exception generated: 'ascii' codec can't decode byte 0xe2 in position 31: ordinal not in range(128)
Traceback (most recent call last):
  File "D:\Medusa\medusa\server\web\core\base.py", line 258, in async_call
    result = function(**kwargs)
  File "D:\Medusa\medusa\server\web\home\add_shows.py", line 543, in addExistingShows
    if '|' not in cur_dir:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 31: ordinal not in range(128)

**To Reproduce**
When trying to an show that already exist as folder with Add show button freezes and red error message shows up.

Show name is: America’s Got Talent The Champions

I have Sickrage as an back-up there the show is no problem.

**Comment by p0psicles** [comment]
Fixed in develop
