### ISSUE TITLE
Problem with MEdusa in general aftyer latest commit

### ISSUE THREAD

**Issue by kebogaer** [pymedusa/Medusa#5750]
I am having issues since the update of last commit of 16/11.
My shows seem not to be updating anymore, All archived episodes show up, but the ones which are still on disc, don't seem to scan, and they disappeared out of the list, example:

On top of that all episodes went to 720p, while I know I had put them on 1080p in the settings and other strange behaviors.
So to make it short it doesn't work anymore.
**Medusa (please complete the following information):**
 - OS: Libreelec 8.2
 - Branch: [e.g. master, develop]
 - Commit: a1d899b

**Logs:**
I see these kinds of errors through my logs:
```
2018-11-19 06:01:44 ERROR    SHOWQUEUE-REFRESH :: [a1d899b] 73762: Error while refreshing show Grey's Anatomy. Error: 6404
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/show_queue.py", line 688, in run
    self.show.refresh_dir()
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/tv/series.py", line 1741, in refresh_dir
    self.load_episodes_from_dir()
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/tv/series.py", line 1006, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/tv/series.py", line 1350, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/tv/episode.py", line 2056, in update_status_quality
    'status_old': statusStrings[old_status],
KeyError: 6404

2018-11-19 07:22:41 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [a1d899b] DailySearchQueueItem Exception, error: 6404
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/queue.py", line 262, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 500, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 457, in wanted_episodes
    cur_status, cur_quality, series_obj, episode['manually_searched']
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/common.py", line 523, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 6404
2018-11-19 06:42:41 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [a1d899b] DailySearchQueueItem Exception, error: 6404
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/queue.py", line 262, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 500, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 457, in wanted_episodes
    cur_status, cur_quality, series_obj, episode['manually_searched']
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/common.py", line 523, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 6404
2018-11-19 06:02:37 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [a1d899b] DailySearchQueueItem Exception, error: 6404
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/queue.py", line 262, in run
    found_results = search_for_needed_episodes(force=self.force)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 500, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 457, in wanted_episodes
    cur_status, cur_quality, series_obj, episode['manually_searched']
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/common.py", line 523, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 6404
```
**Additional context**

**Comment by kebogaer** [comment]
![image](https://user-images.githubusercontent.com/12339594/48715826-35273e00-ec16-11e8-87d9-c39be6a390a8.png)

I added the episode manually in the download folder, the post processing seems to work ...

**Comment by medariox** [comment]
Your update didn't work properly. I suggest you use a backed-up database. Shut down Medusa, rename e.g. `main.db.v44.11` to `main.db` and start again. See if that helps. Otherwise start with a fresh database.

**Comment by kebogaer** [comment]
couldn't restore it, so built from scratch.
Thanks for the suggestions
