### ISSUE TITLE
Medusa crashes in the background after update ( maybe related to #3186 )

### ISSUE THREAD

**Issue by plato79** [pymedusa/Medusa#5756]
**Describe the bug**
Medusa crashes after update

**To Reproduce**
It's happening in the backlog..

**Expected behavior**
It shouldn't crash obviously.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: FreeBSD-11.1-STABLE-amd64-64bit-ELF
 - Branch: master
 - Commit: a1d899bc882da047b3d6ff936e8b78b62b169b05 

**Logs:**
<details>

```
2018-11-16 21:12:49 INFO     FINDSUBTITLES :: [0c0a735] Checking for missed subtitles
2018-11-16 21:13:00 INFO     CHECKVERSION :: [0c0a735] New update found, starting auto-updater ...
2018-11-16 21:13:02 INFO     CHECKVERSION :: [0c0a735] Config backup in progress...
2018-11-16 21:13:25 INFO     CHECKVERSION :: [0c0a735] Config backup successful, updating...
2018-11-16 21:13:29 INFO     CHECKVERSION :: [a1d899b] Update was successful!
2018-11-16 21:13:29 INFO     EVENT-QUEUE :: [a1d899b] Aborting all threads
2018-11-16 21:13:29 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the DAILYSEARCHER thread to exit
2018-11-16 21:13:29 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the BACKLOG thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the SHOWUPDATER thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the CHECKVERSION thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the SHOWQUEUE-REFRESH thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the FORCEDSEARCHQUEUE thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the MANUALSNATCHQUEUE thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the POSTPROCESSOR thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the TRAKTCHECKER thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the FINDPROPERS thread to exit
2018-11-16 21:13:30 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the FINDSUBTITLES thread to exit
2018-11-16 21:13:40 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the TORRENTCHECKER thread to exit
2018-11-16 21:13:40 INFO     EVENT-QUEUE :: [a1d899b] Waiting for the EVENT-QUEUE thread to exit
2018-11-16 21:13:40 INFO     EVENT-QUEUE :: [a1d899b] Releasing socket and stopping link thread
2018-11-16 21:13:40 INFO     EVENT-QUEUE :: [a1d899b] Restarting Medusa with ['/usr/local/bin/python2.7', u'/usr/local/Medusa/start.py', '--datadir', '/usr/local/Medusa', '-d', $
2018-11-16 21:13:40 ERROR    Thread-342 :: [a1d899b] Exception: need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/local/Medusa/ext/adba/aniDBlink.py", line 114, in run
    resp = ResponseResolver(tmp)
  File "/usr/local/Medusa/ext/adba/aniDBresponses.py", line 24, in __init__
    restag, rescode, resstr, datalines = self.parse(data)
  File "/usr/local/Medusa/ext/adba/aniDBresponses.py", line 36, in parse
    rescode, resstr = resline.split(' ', 1)
ValueError: need more than 1 value to unpack
2018-11-16 21:13:40 ERROR    Thread-342 :: [a1d899b] Exception: need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/local/Medusa/ext/adba/aniDBlink.py", line 114, in run
    resp = ResponseResolver(tmp)
  File "/usr/local/Medusa/ext/adba/aniDBresponses.py", line 24, in __init__
    restag, rescode, resstr, datalines = self.parse(data)
  File "/usr/local/Medusa/ext/adba/aniDBresponses.py", line 36, in parse
    rescode, resstr = resline.split(' ', 1)
ValueError: need more than 1 value to unpack
2018-11-16 21:13:40 ERROR    Thread-342 :: [a1d899b] Avoiding flood by paranoidly panicing: Aborting link thread, killing connection, releasing waiters and quiting
Traceback (most recent call last):
  File "/usr/local/Medusa/ext/adba/aniDBlink.py", line 123, in run
    raise AniDBPacketCorruptedError("Either decrypting, decompressing or parsing the packet failed")
AniDBPacketCorruptedError: Either decrypting, decompressing or parsing the packet failed
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Nothing changed there in the last update. Seems something is going wrong with getting the anidb release groups. But that doesnt happen on startup.

So medusa does startup? 
When does it crashes? 
Can you enable debug logs?

**Comment by p0psicles** [comment]
The thread is specific to anidb udp api calls. It could be thats causing it to crash. Ill add some exception handling, to prevent that.

Still the exception is strange. Debug logs might tell us which anime is used.

**Comment by plato79** [comment]
Just realized I posted in the wrong thread.. Stupid me..

Here is the log after debug is enabled... Though as far as I see there's nothing new:

```
....
2018-11-21 21:31:34 DEBUG    CHECKVERSION :: [a1d899b] "/usr/local/bin/git" clean -d -f -x lib lib2 lib3 ext ext2 ext3 medusa.app static Medusa/helper Medusa/helpers sickbeard sickrage gui : retur$
2018-11-21 21:31:34 DEBUG    CHECKVERSION :: [a1d899b] Executing "/usr/local/bin/git" symbolic-ref -q HEAD with your shell in /usr/local/Medusa
2018-11-21 21:31:35 DEBUG    CHECKVERSION :: [a1d899b] "/usr/local/bin/git" symbolic-ref -q HEAD : returned successful
2018-11-21 21:31:35 DEBUG    CHECKVERSION :: [a1d899b] Executing "/usr/local/bin/git" pull -f origin master with your shell in /usr/local/Medusa
2018-11-21 21:31:35 DEBUG    FINDSUBTITLES :: [a1d899b] Episode already has all needed subtitles, skipping The Good Place S03E07
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [a1d899b] "/usr/local/bin/git" pull -f origin master : returned successful
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [a1d899b] Executing "/usr/local/bin/git" clean -d -f -x lib lib2 lib3 ext ext2 ext3 medusa.app static Medusa/helper Medusa/helpers sickbeard sickrage g$
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [a1d899b] "/usr/local/bin/git" clean -d -f -x lib lib2 lib3 ext ext2 ext3 medusa.app static Medusa/helper Medusa/helpers sickbeard sickrage gui : retur$
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [a1d899b] Executing "/usr/local/bin/git" rev-parse HEAD with your shell in /usr/local/Medusa
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [a1d899b] "/usr/local/bin/git" rev-parse HEAD : returned successful
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [54da0c7] Notification for Boxcar2 not enabled, skipping this notification
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [54da0c7] Unable to send update notification. Continuing the update process
2018-11-21 21:31:36 INFO     CHECKVERSION :: [54da0c7] Update was successful!
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [54da0c7] Checking GitHub for latest news.
2018-11-21 21:31:36 INFO     EVENT-QUEUE :: [54da0c7] Aborting all threads
2018-11-21 21:31:36 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the DAILYSEARCHER thread to exit
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [54da0c7] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2018-11-21 21:31:36 DEBUG    CHECKVERSION :: [54da0c7] User-Agent: Medusa/0.2.12 (FreeBSD; 11.1-STABLE; 2ee35e99-ec96-11e8-bf81-be4b0aa9f35f)
2018-11-21 21:31:36 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the BACKLOG thread to exit
2018-11-21 21:31:36 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the SHOWUPDATER thread to exit
2018-11-21 21:31:36 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the CHECKVERSION thread to exit
2018-11-21 21:31:37 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the SHOWQUEUE-REFRESH thread to exit
2018-11-21 21:31:37 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the SEARCHQUEUE-BACKLOG-72454 thread to exit
2018-11-21 21:31:37 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the FORCEDSEARCHQUEUE thread to exit
2018-11-21 21:31:37 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the SNATCHQUEUE-SNATCH-72454 thread to exit
2018-11-21 21:31:37 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the POSTPROCESSOR thread to exit
2018-11-21 21:31:37 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the TRAKTCHECKER thread to exit
2018-11-21 21:31:37 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the FINDPROPERS thread to exit
2018-11-21 21:31:37 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the FINDSUBTITLES thread to exit
2018-11-21 21:31:37 DEBUG    FINDSUBTITLES :: [54da0c7] Episode already has all needed subtitles, skipping The Good Place S03E08
2018-11-21 21:31:39 DEBUG    FINDSUBTITLES :: [54da0c7] Subtitle search for DuckTales (2017) S02E04 delayed for 2 hours, 59 minutes
2018-11-21 21:31:40 DEBUG    SEARCHQUEUE-BACKLOG-72454 :: [ThePirateBay] :: [54da0c7] Error requesting url https://thepiratebay.org/search/Detective Conan 717/0/3/200 Error: HTTPSConnectionPool(ho$
2018-11-21 21:31:40 DEBUG    SEARCHQUEUE-BACKLOG-72454 :: [ThePirateBay] :: [54da0c7] No data returned from provider
2018-11-21 21:31:40 DEBUG    SEARCHQUEUE-BACKLOG-72454 :: [ThePirateBay] :: [54da0c7] Search string: Case Closed 717
2018-11-21 21:31:40 DEBUG    SEARCHQUEUE-BACKLOG-72454 :: [ThePirateBay] :: [54da0c7] Searching only confirmed torrents
2018-11-21 21:31:41 DEBUG    FINDSUBTITLES :: [54da0c7] Subtitle search for Arrow S07E03 delayed for 4 hours, 59 minutes
2018-11-21 21:31:43 DEBUG    FINDSUBTITLES :: [54da0c7] Subtitle search for Channel Zero S04E06 delayed for 4 hours, 59 minutes
2018-11-21 21:31:45 DEBUG    FINDSUBTITLES :: [54da0c7] Subtitle search for South Park S22E05 delayed for 4 hours, 59 minutes
2018-11-21 21:31:47 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the TORRENTCHECKER thread to exit
2018-11-21 21:31:47 INFO     EVENT-QUEUE :: [54da0c7] Waiting for the EVENT-QUEUE thread to exit
2018-11-21 21:31:47 DEBUG    Thread-377 :: [54da0c7] NetIO < 'T001 501 LOGIN FIRST\n'
2018-11-21 21:31:47 INFO     EVENT-QUEUE :: [54da0c7] Releasing socket and stopping link thread
2018-11-21 21:31:47 INFO     EVENT-QUEUE :: [54da0c7] Restarting Medusa with ['/usr/local/bin/python2.7', u'/usr/local/Medusa/start.py', '--datadir', '/usr/local/Medusa', '-d', '--pidfile', '/var/$
2018-11-21 21:31:47 DEBUG    Thread-377 :: [54da0c7] NetIO < ''
2018-11-21 21:31:47 ERROR    Thread-377 :: [54da0c7] Exception: need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/local/Medusa/ext/adba/aniDBlink.py", line 114, in run
    resp = ResponseResolver(tmp)
  File "/usr/local/Medusa/ext/adba/aniDBresponses.py", line 24, in __init__
    restag, rescode, resstr, datalines = self.parse(data)
  File "/usr/local/Medusa/ext/adba/aniDBresponses.py", line 36, in parse
    rescode, resstr = resline.split(' ', 1)
ValueError: need more than 1 value to unpack
2018-11-21 21:31:47 ERROR    Thread-377 :: [54da0c7] Exception: need more than 1 value to unpack
Traceback (most recent call last):
  File "/usr/local/Medusa/ext/adba/aniDBlink.py", line 114, in run
    resp = ResponseResolver(tmp)
  File "/usr/local/Medusa/ext/adba/aniDBresponses.py", line 24, in __init__
    restag, rescode, resstr, datalines = self.parse(data)
  File "/usr/local/Medusa/ext/adba/aniDBresponses.py", line 36, in parse
    rescode, resstr = resline.split(' ', 1)
ValueError: need more than 1 value to unpack
2018-11-21 21:31:47 ERROR    Thread-377 :: [54da0c7] Avoiding flood by paranoidly panicing: Aborting link thread, killing connection, releasing waiters and quiting
Traceback (most recent call last):
  File "/usr/local/Medusa/ext/adba/aniDBlink.py", line 123, in run
    raise AniDBPacketCorruptedError("Either decrypting, decompressing or parsing the packet failed")
AniDBPacketCorruptedError: Either decrypting, decompressing or parsing the packet failed
2018-11-21 21:31:47 DEBUG    FINDSUBTITLES :: [54da0c7] Subtitle search for Channel Zero S04E05 delayed for 4 hours, 59 minutes
...
```

After the last line it crashed again..
