### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 13] Permission denied: '/srv/media/series/The Good Doctor/The Good Doctor S02/The Good Doctor S02E09.mkv'

### ISSUE THREAD

**Issue by PxReaz** [pymedusa/Medusa#5809]
### INFO
**Python Version**: `2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with-debian-9.6`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@54da0c77d705a23f1ce67945ba4af3e1b978dcfc
**Link to Log**: https://gist.github.com/4abb7c6798ebed9c1f52f71bbb01c137
### ERROR
<pre>
2018-12-01 10:43:36 ERROR    POSTPROCESSOR :: [54da0c7] Unable to move file /srv/media/automatic/The Good Doctor - S02E09.mkv to /srv/media/series/The Good Doctor/The Good Doctor S02/The Good Doctor S02E09.mkv: IOError(13, 'Permission denied')
Traceback (most recent call last):
  File "/srv/medusa/<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/post_processor.py#L472">medusa/post_processor.py</a>", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/srv/medusa/<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/helpers/__init__.py#L312">medusa/helpers/__init__.py</a>", line 312, in move_file
    shutil.move(src_file, dest_file)
  File "/srv/medusa/<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/init/filesystem.py#L112">medusa/init/filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/srv/medusa/<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/lib/shutil_custom/__init__.py#L32">lib/shutil_custom/__init__.py</a>", line 32, in copyfile_custom
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "/srv/medusa/<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/init/filesystem.py#L112">medusa/init/filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 13] Permission denied: '/srv/media/series/The Good Doctor/The Good Doctor S02/The Good Doctor S02E09.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
LIke the message says. Permisssion error.
