### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 13] Permission denied: u'F:\\Series\\Supergirl\\Season 04\\Supergirl - S04E08 - Bunker Hill.mkv'

### ISSUE THREAD

**Issue by Norsixa** [pymedusa/Medusa#5841]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17134`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@54da0c77d705a23f1ce67945ba4af3e1b978dcfc
**Link to Log**: **No Log available**
### ERROR
<pre>
2018-12-06 14:51:49 ERROR    POSTPROCESSOR :: [54da0c7] Unable to move file F:\Downloads\Supergirl\Supergirl.S04E08.720p.HDTV.x264-AVS[rarbg]\Supergirl.S04E08.720p.HDTV.x264-AVS.mkv to F:\Series\Supergirl\Season 04\Supergirl - S04E08 - Bunker Hill.mkv: IOError(13, 'Permission denied')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/post_processor.py#L472">medusa\post_processor.py</a>", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "C:\Medusa\Medusa\<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/helpers/__init__.py#L312">medusa\helpers\__init__.py</a>", line 312, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Medusa\<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/init/filesystem.py#L112">medusa\init\filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "C:\Medusa\Python\lib\shutil.py", line 302, in move
    copy2(src, real_dst)
  File "C:\Medusa\Python\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Medusa\Medusa\<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/lib/shutil_custom/__init__.py#L32">lib\shutil_custom\__init__.py</a>", line 32, in copyfile_custom
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "C:\Medusa\Medusa\<a href="../blob/54da0c77d705a23f1ce67945ba4af3e1b978dcfc/medusa/init/filesystem.py#L112">medusa\init\filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 13] Permission denied: u'F:\\Series\\Supergirl\\Season 04\\Supergirl - S04E08 - Bunker Hill.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Norsixa** [comment]
Full debug log
[debuglogmedusa.txt](https://github.com/pymedusa/Medusa/files/2653578/debuglogmedusa.txt)

**Comment by p0psicles** [comment]
This is a permission error

**Comment by p0psicles** [comment]
Check user running medusa, and fix access on your system. Medusa app/config folder. And series folders

**Comment by Norsixa** [comment]
Not the only issue I have, it doesnt update shows, doesnt make a backlog and doesnt seem to find all the episodes from the providers either.

**Comment by p0psicles** [comment]
Yeah well. Lets start here

**Comment by Norsixa** [comment]
So i'm guessing you just mean adding full control to user account of windows to both medusa and series folder?

**Comment by medariox** [comment]
You should enable debug logging, trigger a manual search of the episode you expect to find, and post the complete log on GitHub.
Anyway, you seem to have also some major permission problems. Did you start with a fresh database and `config.ini`? Also make sure to install Medusa for all users.

**Comment by p0psicles** [comment]
So something is definitely wrong with the access rights to your F:\.. Mount. Fix that first. maybe something stupid like disk full?
Then enable debug logs and restart medusa. Go to config - general (advanced settings -> logging)
 check enable logging. now restart medusa.

Disable all the other providers and for the anime and only leave shanaproject and nyaa enabled.
Go to show black clover. Make sure you have this shows marked as anime. See screenshot.
![image](https://user-images.githubusercontent.com/1331394/49611846-2923d600-f9a3-11e8-8de2-2ec1671b2c6b.png)

Now behind episode 61 click the manual search button. A small icon with magnifying glass and three lines. It should come up with horribesubs releases for both providers:
![image](https://user-images.githubusercontent.com/1331394/49611936-7d2eba80-f9a3-11e8-8b85-9c61a5a66db3.png)

**Comment by Norsixa** [comment]
I should probaly just reinstall it, cause it loads really slow for some reason. And the hd thing is probaly because of my torrent still seeding or not being open, I dont tend to delete torrents untill I actually watch it cause sometimes it doesnt download properly and i have to redownload. Can I just delete the medusa folder or is it better to uninstall it properly for a clean install?

**Comment by Norsixa** [comment]
https://gyazo.com/2e5c6a02fd4a6da8c0f9b0dea686f7aa - Only takes those 2 from nyaa & shana. Should defo should with a proper clean reinstall first I would say.

**Comment by medariox** [comment]
It's always better to uninstall and install it again. You can't move a file that is being used by another program. You need to use copy in that case.

**Comment by medariox** [comment]
Closing for now. Let us know if you need more help.
