### ISSUE TITLE
[APP SUBMITTED]: TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#5884]
### INFO
**Python Version**: `3.6.7 (default, Oct 21 2018, 08:08:16) [GCC 8.2.0]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-buster-sid`
**Locale**: `UTF-8`
**Branch**: [feature/py3_2](../tree/feature/py3_2)
**Database**: `44.12`
**Commit**: pymedusa/Medusa@523cd325297cb7cabf9ddbf3b83c8571a114419b
**Link to Log**: https://gist.github.com/88f05b353a8aad7dba465d111ef96285
### ERROR
<pre>
2018-12-12 00:00:09 ERROR    SNATCHQUEUE-SNATCH-48552 :: [523cd32] Transmission: Failed Sending Torrent
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/523cd325297cb7cabf9ddbf3b83c8571a114419b/medusa/clients/torrent/generic.py#L263">medusa/clients/torrent/generic.py</a>", line 263, in send_torrent
    r_code = self._add_torrent_file(result)
  File "/home/pi/Medusa/<a href="../blob/523cd325297cb7cabf9ddbf3b83c8571a114419b/medusa/clients/torrent/transmission_client.py#L121">medusa/clients/torrent/transmission_client.py</a>", line 121, in _add_torrent_file
    'method': 'torrent-add',
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Should be fixed in the branch, please update.

**Comment by gerbil42** [comment]
### INFO
**Python Version**: `3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@d588a2c92bb007d4346e5f46811f896775efb3be
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-02-26 17:53:10 ERROR    Thread_10 :: [d588a2c] Exception generated: Object of type bytes is not JSON serializable
Traceback (most recent call last):
  File "D:\Medusa\<a href="../blob/d588a2c92bb007d4346e5f46811f896775efb3be/medusa/server/web/core/base.py#L262">medusa\server\web\core\base.py</a>", line 262, in async_call
    result = function(**kwargs)
  File "D:\Medusa\<a href="../blob/d588a2c92bb007d4346e5f46811f896775efb3be/medusa/server/web/home/add_shows.py#L514">medusa\server\web\home\add_shows.py</a>", line 514, in addNewShow
    return finishAddShow()
  File "D:\Medusa\<a href="../blob/d588a2c92bb007d4346e5f46811f896775efb3be/medusa/server/web/home/add_shows.py#L404">medusa\server\web\home\add_shows.py</a>", line 404, in finishAddShow
    for i, cur_dir in enumerate(other_shows)
  File "D:\Medusa\<a href="../blob/d588a2c92bb007d4346e5f46811f896775efb3be/medusa/server/web/home/add_shows.py#L52">medusa\server\web\home\add_shows.py</a>", line 52, in json_response
    'params': params or [],
  File "D:\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Thanks for the report! Fixed with https://github.com/pymedusa/Medusa/pull/6252

**Comment by gerbil42** [comment]
I can confirm that I can add more than 2 existing shows now.

Thanks!

**Comment by akang6** [comment]
### INFO
**Python Version**: `3.6.8 (default, Dec 24 2018, 19:24:27) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.4.0-142-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@94fae847b6e7e443d74c59cb11bdbd37c464b363
**Link to Log**: https://gist.github.com/91bbe7f002401e676e39f654e29d3276
### ERROR
<pre>
2019-03-15 08:49:56 ERROR    Thread_8 :: [94fae84] Error Sending Slack message
Traceback (most recent call last):
  File "/opt/Medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/notifiers/slack.py#L108">medusa/notifiers/slack.py</a>", line 108, in _send_slack
    r = requests.post(webhook, data=json.dumps(data), headers=headers)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by nucshuco** [comment]
### INFO
**Python Version**: `3.6.8 (default, Feb  7 2019, 01:14:59) [GCC 4.2.1 Compatible FreeBSD Clang 6.0.0 (tags/RELEASE_600/final 326565)]`
**Operating System**: `FreeBSD-11.2-STABLE-amd64-64bit-ELF`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@94fae847b6e7e443d74c59cb11bdbd37c464b363
**Link to Log**: https://gist.github.com/e73dff1a6249589322b51c153218f80d
### ERROR
<pre>
2019-03-15 12:26:24 ERROR    Thread_4 :: [94fae84] Error Sending Slack message
Traceback (most recent call last):
  File "/usr/local/share/medusa/Medusa/<a href="../blob/94fae847b6e7e443d74c59cb11bdbd37c464b363/medusa/notifiers/slack.py#L108">medusa/notifiers/slack.py</a>", line 108, in _send_slack
    r = requests.post(webhook, data=json.dumps(data), headers=headers)
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Already fixed in develop.
