### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Vodka34** [pymedusa/Medusa#5887]
**Describe the bug**
Does not seem to connect to Deluge even tho port/host/username and password are correct.

**To Reproduce**

Just add your deluge details and search away

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]

Medusa Info: | Branch: master Commit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfc Version: v0.2.13 Database: 44.12
-- | --
Python Version: | 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
SSL Version: | LibreSSL 2.7.4
OS: | Linux-4.18.0-0.bpo.1-amd64-x86_64-with
Locale: | Unknown.Unknown

**Logs:**
<details>

```
2018-12-13 09:22:35 ERROR    SNATCHQUEUE-SNATCH-295647 :: [54da0c7] Snatch failed! For result: Blindspot.S04E08.PROPER.WEBRip.x264-ION10
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 502, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 246, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/deluged_client.py", line 45, in _get_auth
    return True if self.connect() else None
  File "/app/medusa/medusa/clients/torrent/deluged_client.py", line 58, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
2018-12-13 09:21:48 ERROR    SNATCHQUEUE-SNATCH-72108 :: [54da0c7] Snatch failed! For result: NCIS.S16E10.HDTV.x264-SVA[TGx]
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 502, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 246, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/deluged_client.py", line 45, in _get_auth
    return True if self.connect() else None
  File "/app/medusa/medusa/clients/torrent/deluged_client.py", line 58, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
2018-12-13 09:21:33 ERROR    SNATCHQUEUE-SNATCH-270408 :: [54da0c7] Snatch failed! For result: Outlander.S04E06.WEB.H264-MEMENTO[ettv]
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 502, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 246, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/deluged_client.py", line 45, in _get_auth
    return True if self.connect() else None
  File "/app/medusa/medusa/clients/torrent/deluged_client.py", line 58, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
2018-12-13 09:20:54 ERROR    SNATCHQUEUE-SNATCH-260449 :: [54da0c7] Snatch failed! For result: Vikings.S05E13.HDTV.x264-SVA[ettv].torrent
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 502, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 246, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/deluged_client.py", line 45, in _get_auth
    return True if self.connect() else None
  File "/app/medusa/medusa/clients/torrent/deluged_client.py", line 58, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
```
</details>

**Comment by medariox** [comment]
Did you try with deluge instead of deluged?

**Comment by Vodka34** [comment]
what do you mean i didn't know there was a deluged
![deluge](https://user-images.githubusercontent.com/45845314/49929990-9d86d980-febb-11e8-8ddc-409dd2403e9d.jpg)

**Comment by medariox** [comment]
The other deluge in the list of torrent clients.

**Comment by Vodka34** [comment]
![image](https://user-images.githubusercontent.com/45845314/49930179-f3f41800-febb-11e8-8e40-74e196d714ea.png)
I don't see deluged, only deluge which is what using

**Comment by medariox** [comment]
Are you really using the Daemon? Otherwise you need to choose Deluge (via WebUI).

**Comment by Vodka34** [comment]
Is it nit the same as sick rage?, I have alot using  the deamon on delgue never had a issue multiple clients using it at the same time.

**Comment by medariox** [comment]
Look at the hostname example, you need to add `scgi://`.

**Comment by Vodka34** [comment]
Wow didn't need that in sickrage lol working now very sorry and thanks!

**Comment by medariox** [comment]
No problem, enjoy!

**Comment by cproxy** [comment]
### INFO
**Python Version**: `2.7.15 (default, Nov 26 2018, 01:42:21) [GCC 7.3.0]`
**Operating System**: `Linux-4.14.65-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2697_v4_@_2.30GHz-with-gentoo-2.6`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@b34f1df336e52cf0a690acbc393440ac9f8b3581
**Link to Log**: https://gist.github.com/443d647ca77e434582bfab8e093f3482
### ERROR
<pre>
2019-03-27 20:00:03 ERROR    SNATCHQUEUE-SNATCH-328487 :: [b34f1df] Snatch failed! For result: The.Orville.S02E11.720p.WEB.x264-TBS
Traceback (most recent call last):
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/search/queue.py#L503">medusa/search/queue.py</a>", line 503, in run
    self.success = snatch_episode(result)
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/search/core.py#L167">medusa/search/core.py</a>", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/generic.py#L238">medusa/clients/torrent/generic.py</a>", line 238, in send_torrent
    if not self._get_auth():
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/deluged.py#L44">medusa/clients/torrent/deluged.py</a>", line 44, in _get_auth
    return True if self.connect() else None
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/deluged.py#L57">medusa/clients/torrent/deluged.py</a>", line 57, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by cproxy** [comment]
### INFO
**Python Version**: `2.7.15 (default, Nov 26 2018, 01:42:21) [GCC 7.3.0]`
**Operating System**: `Linux-4.14.65-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2697_v4_@_2.30GHz-with-gentoo-2.6`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@b34f1df336e52cf0a690acbc393440ac9f8b3581
**Link to Log**: https://gist.github.com/e67753a00dc2d27c8e8d3d02acceadce
### ERROR
<pre>
2019-03-27 19:58:18 ERROR    SNATCHQUEUE-SNATCH-328487 :: [b34f1df] Snatch failed! For result: The.Orville.S02E11.1080p.WEB.x264-TBS
Traceback (most recent call last):
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/search/queue.py#L503">medusa/search/queue.py</a>", line 503, in run
    self.success = snatch_episode(result)
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/search/core.py#L167">medusa/search/core.py</a>", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/generic.py#L238">medusa/clients/torrent/generic.py</a>", line 238, in send_torrent
    if not self._get_auth():
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/deluged.py#L44">medusa/clients/torrent/deluged.py</a>", line 44, in _get_auth
    return True if self.connect() else None
  File "/mnt/mpathq/hillarytits/Medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/deluged.py#L57">medusa/clients/torrent/deluged.py</a>", line 57, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Enter the address like in the example.

**Comment by barukh27** [comment]
### INFO
**Python Version**: `3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.14.78-4-osmc-armv7l-with-debian-9.8`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@b34f1df336e52cf0a690acbc393440ac9f8b3581
**Link to Log**: https://gist.github.com/7e5fd1d88034e76cd5f956610beae2d3
### ERROR
<pre>
2019-04-03 21:00:45 ERROR    SNATCHQUEUE-SNATCH-289079 :: [b34f1df] Snatch failed! For result: Into.the.Badlands.S03E11.WEBRip.x264-ION10
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/search/queue.py#L503">medusa/search/queue.py</a>", line 503, in run
    self.success = snatch_episode(result)
  File "/opt/medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/search/core.py#L167">medusa/search/core.py</a>", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/opt/medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/generic.py#L238">medusa/clients/torrent/generic.py</a>", line 238, in send_torrent
    if not self._get_auth():
  File "/opt/medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/deluged.py#L44">medusa/clients/torrent/deluged.py</a>", line 44, in _get_auth
    return True if self.connect() else None
  File "/opt/medusa/<a href="../blob/b34f1df336e52cf0a690acbc393440ac9f8b3581/medusa/clients/torrent/deluged.py#L57">medusa/clients/torrent/deluged.py</a>", line 57, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
