### ISSUE TITLE
Python v3.7.1 - No module named 'importlib' 

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#5909]
**Describe the bug**
Since I'm building a new server with a fresh environment I was looking into Python v3, not entirely sure if Medusa is already Python v3 ready.
In the start.py it does mention `Medusa supports Python 2 from version 2.7.10 and Python 3 from version 3.5.0, exiting!`

Just did a clean Windows Server 2019 installation with Python 3.7.1 and did a git clone.
When starting I get the following error.

**Medusa (please complete the following information):**
 - OS: Windows Server 2019
 - Branch: master
 - Commit: Latest Commit

**Logs:**
<details>

```
PS C:\GitHub\Medusa> python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
PS C:\GitHub\Medusa> python .\start.py
Error processing line 1 of C:\GitHub\Medusa\ext\configparser.pth:

  Traceback (most recent call last):
    File "C:\Python37\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'importlib'

Remainder of file ignored
Traceback (most recent call last):
  File ".\start.py", line 8, in <module>
    from medusa.__main__ import main
  File "C:\GitHub\Medusa\medusa\__init__.py", line 24, in <module>
    initialize()
  File "C:\GitHub\Medusa\medusa\init\__init__.py", line 33, in initialize
    _configure_guessit()
  File "C:\GitHub\Medusa\medusa\init\__init__.py", line 179, in _configure_guessit
    import guessit
  File "C:\GitHub\Medusa\ext\guessit\__init__.py", line 8, in <module>
    from .api import guessit, GuessItApi
  File "C:\GitHub\Medusa\ext\guessit\api.py", line 20, in <module>
    from .rules import rebulk_builder
  File "C:\GitHub\Medusa\ext\guessit\rules\__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "C:\GitHub\Medusa\ext\guessit\rules\properties\episodes.py", line 14, in <module>
    from .title import TitleFromPosition
  File "C:\GitHub\Medusa\ext\guessit\rules\properties\title.py", line 11, in <module>
    from .language import SubtitlePrefixLanguageRule, SubtitleSuffixLanguageRule, SubtitleExtensionRule
  File "C:\GitHub\Medusa\ext\guessit\rules\properties\language.py", line 10, in <module>
    import babelfish
  File "C:\GitHub\Medusa\ext\babelfish\__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "C:\GitHub\Medusa\ext\babelfish\converters\__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
  File "C:\GitHub\Medusa\lib\pkg_resources\__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "C:\GitHub\Medusa\lib\pkg_resources\_vendor\packaging\requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\GitHub\Medusa\lib\pkg_resources\extern\__init__.py", line 43, in load_module
    __import__(extant)
  File "C:\GitHub\Medusa\lib\pkg_resources\_vendor\pyparsing.py", line 4715, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "C:\GitHub\Medusa\lib\pkg_resources\_vendor\pyparsing.py", line 1261, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "C:\GitHub\Medusa\lib\pkg_resources\_vendor\pyparsing.py", line 1043, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "C:\GitHub\Medusa\lib\pkg_resources\_vendor\pyparsing.py", line 1027, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "C:\Python37\lib\traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "C:\Python37\lib\traceback.py", line 363, in extract
    f.line
  File "C:\Python37\lib\traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Python37\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "C:\Python37\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Python37\lib\linecache.py", line 142, in updatecache
    size, mtime = stat.st_size, stat.st_mtime
AttributeError: 'list' object has no attribute 'st_size'
PS C:\GitHub\Medusa>
```
</details>

**Comment by p0psicles** [comment]
Try develop branch. We Just merged py3 support to develop.

**Comment by medariox** [comment]
Medusa will support Python 3 starting with the next release (0.3.0). What we have added to `start.py` is just to prepare for the next release. If you want to try out Python 3 support and help us test it, you are more than welcome to check out the [develop branch](https://github.com/pymedusa/Medusa/tree/develop).

**Comment by Rouzax** [comment]
Wow, thanks for the fast responses.
When will that dev merge into the master?

**Comment by p0psicles** [comment]
When it has been tested nu enough users.
There are allot of configs that should still be tested. And we expect a number of bugs to reach the surface first.
