### ISSUE TITLE
[py-3.7.0] Config encryption exception

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#5910]
**Describe the bug**
Medusa won't run on Python 3.7 with config password encryption enabled.

**To Reproduce**
1. Enable password encryption
2. Run using Python 3.7 (probably affects 3.6 & 3.5 as well)

**Medusa (please complete the following information):**
- **Python**: 3.7.0
 - **OS:** Windows 7 x64 SP1 (7601)
 - **Branch:** develop
 - **Commit:** 3c4fc5155e989c9268f20120cd3dee7e36d1802d

**Logs:**
<details>
<summary>:book: </summary>

```
Traceback (most recent call last):
  File "C:\Python37\lib\base64.py", line 517, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Medusa\medusa\config.py", line 729, in check_setting_str
    my_val = helpers.decrypt(config[cfg_name][item_name], encryption_version)
  File "C:\Medusa\medusa\helpers\__init__.py", line 977, in decrypt
    return encrypt(data, encryption_version, _decrypt=True)
  File "C:\Medusa\medusa\helpers\__init__.py", line 966, in encrypt
    return ''.join(chr(ord(x) ^ ord(y)) for (x, y) in zip(base64.decodestring(data),
  File "C:\Python37\lib\base64.py", line 561, in decodestring
    return decodebytes(s)
  File "C:\Python37\lib\base64.py", line 552, in decodebytes
    _input_type_check(s)
  File "C:\Python37\lib\base64.py", line 520, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\base64.py", line 517, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Medusa\medusa\config.py", line 735, in check_setting_str
    config[cfg_name][item_name] = helpers.encrypt(my_val, encryption_version)
  File "C:\Medusa\medusa\helpers\__init__.py", line 970, in encrypt
    ''.join(chr(ord(x) ^ ord(y)) for (x, y) in zip(data, cycle(app.ENCRYPTION_SECRET)))).strip()
  File "C:\Python37\lib\base64.py", line 547, in encodestring
    return encodebytes(s)
  File "C:\Python37\lib\base64.py", line 534, in encodebytes
    _input_type_check(s)
  File "C:\Python37\lib\base64.py", line 520, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\base64.py", line 517, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Medusa\start.py", line 14, in <module>
    main()
  File "C:\Medusa\medusa\__main__.py", line 2184, in main
    application.start(sys.argv[1:])
  File "C:\Medusa\medusa\__main__.py", line 317, in start
    self.initialize(console_logging=self.console_logging)
  File "C:\Medusa\medusa\__main__.py", line 425, in initialize
    app.GIT_PASSWORD = check_setting_str(app.CFG, 'General', 'git_password', '', censor_log='low')
  File "C:\Medusa\medusa\config.py", line 738, in check_setting_str
    config[cfg_name][item_name] = helpers.encrypt(my_val, encryption_version)
  File "C:\Medusa\medusa\helpers\__init__.py", line 970, in encrypt
    ''.join(chr(ord(x) ^ ord(y)) for (x, y) in zip(data, cycle(app.ENCRYPTION_SECRET)))).strip()
  File "C:\Python37\lib\base64.py", line 547, in encodestring
    return encodebytes(s)
  File "C:\Python37\lib\base64.py", line 534, in encodebytes
    _input_type_check(s)
  File "C:\Python37\lib\base64.py", line 520, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```
</details>

**Comment by p0psicles** [comment]
Is this `the sharkykh` reporting? This for the bug report bro.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/5912

**Comment by sharkykh** [comment]
I'm running 3.7.0 now, looks good so far.
Thanks @medariox

**Comment by labrys** [comment]
Now that you have python 3 working, I would consider deprecating Python 2 support so people can start considering migration to Python 3.  Python 2.7 is expected to reach end of life in 2020.

**Comment by medariox** [comment]
@labrys That's the plan! We will gradually ask people to move to Python 3. Support for Python 2 will end around the time Python 2 reaches EOL.

**Comment by p0psicles** [comment]
Yeah it's not our intention to keep supporting both
