### ISSUE TITLE
Findsubtitles exception

### ISSUE THREAD

**Issue by neojoe666** [pymedusa/Medusa#5929]
Since November, I can't download any subtitle anymore. I always get the same error. It can be with the automatic subtitles search or manual.

**To Reproduce**
1. Go to a TV show
2. Click on the button to download subtitles
3. See error

**Medusa (please complete the following information):**
 - OS: Synology - Linux-3.2.40-armv7l-with-glibc2.4
 - Branch: master
 - Commit: 918cfe7

**Logs:**
<details>

```
2018-12-29 15:05:57 ERROR    FINDSUBTITLES :: [918cfe7] Exception generated: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/subtitles.py", line 1061, in run
    episode_object.download_subtitles()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/episode.py", line 485, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/subtitles.py", line 452, in download_subtitles
    return save_subs(tv_episode, video, found_subtitles, video_path=video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/subtitles.py", line 477, in save_subs
    single=not app.SUBTITLES_MULTI)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 755, in save_subtitles
    subtitle_path = os.path.join(directory, os.path.split(subtitle_path)[1])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/volume1/@appstore/sickbeard-custom/env/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
```
</details>

**Comment by medariox** [comment]
Same as https://github.com/pymedusa/Medusa/issues/5930
