### ISSUE TITLE
Can't start service

### ISSUE THREAD

**Issue by MatthK** [pymedusa/Medusa#5947]
I just installed Medusa on Ubuntu using the guide here. https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Debian-Ubuntu-14-15-16

At first it did no recognize the service, so I had to add the command

```
sudo chmod +x /etc/init.d/medusa
```

After that, when I try to start the service, I get the following messages (see below) but medusa is not started.

How can I get this to work? What about those missing default settings?

 - OS: Ubuntu 14.04.5 LTS
   Release: 14.04
   Codename: trusty

**Logs:**
```
root@Ubuntu:~# service medusa start
/etc/default/medusa not found using default settings.
Starting Medusa
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/opt/medusa/medusa/metadata/__init__.py", line 24, in <module>
    from medusa.metadata import (
  File "/opt/medusa/medusa/metadata/generic.py", line 17, in <module>
    from medusa.indexers.indexer_config import INDEXER_TMDB, INDEXER_TVDBV2, INDEXER_TVMAZE
  File "/opt/medusa/medusa/indexers/indexer_config.py", line 10, in <module>
    from medusa.indexers.tvdbv2.tvdbv2_api import TVDBv2
  File "/opt/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 17, in <module>
    from medusa.indexers.tvdbv2.fallback import PlexFallback
  File "/opt/medusa/medusa/indexers/tvdbv2/fallback.py", line 9, in <module>
    from medusa import app, ui
  File "/opt/medusa/medusa/ui.py", line 24, in <module>
    from medusa import app, ws
  File "/opt/medusa/medusa/ws/__init__.py", line 9, in <module>
    from medusa.ws.handler import backlogged_msgs, clients  # noqa: F401
  File "/opt/medusa/medusa/ws/handler.py", line 11, in <module>
    from tornado.websocket import WebSocketClosedError, WebSocketHandler
  File "/opt/medusa/ext/tornado/websocket.py", line 27, in <module>
    import tornado.web
  File "/opt/medusa/ext/tornado/web.py", line 89, in <module>
    from tornado import iostream
  File "/opt/medusa/ext/tornado/iostream.py", line 41, in <module>
    from tornado.netutil import ssl_wrap_socket, _client_ssl_defaults, _server_ssl_defaults
  File "/opt/medusa/ext/tornado/netutil.py", line 44, in <module>
    _client_ssl_defaults = ssl.create_default_context(
AttributeError: 'module' object has no attribute 'create_default_context'
root@Ubuntu:~#
```
</details>

**Comment by medariox** [comment]
You need a more recent Python version. See https://www.reddit.com/r/PyMedusa/comments/a4ihl7/launch_on_ubuntu_1404_fails_with_ssl_error_help/

**Comment by MatthK** [comment]
Sweet, thanks. Works like a charm now. Thanks
