### ISSUE TITLE
Error Exception generated: No module named gdbm

### ISSUE THREAD

**Issue by ngosang** [pymedusa/Medusa#5980]
**Medusa (please complete the following information):**
 - OS: Linux / Python2.7
 - Branch: master
 - Commit: 918cfe7  v0.2.14

**Logs:**
```
2019-01-10 21:49:01 ERROR    Thread_0 :: [918cfe7] Exception generated: No module named gdbm
Traceback (most recent call last):
  File "/root/scripts/medusa/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/root/scripts/medusa/medusa/server/web/home/handler.py", line 2212, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/root/scripts/medusa/medusa/subtitles.py", line 335, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/root/scripts/medusa/ext/dogpile/cache/region.py", line 1015, in set
    self.backend.set(key, self._value(value))
  File "/root/scripts/medusa/ext/dogpile/cache/backends/file.py", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/root/scripts/medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
ImportError: No module named gdbm
```

**Comment by ngosang** [comment]
@medariox I don't have another version of subliminal, the only one is provided by you in `ext/subliminal` folder.

```
root@RasPi:~/scripts/medusa# python2
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subliminal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named subliminal
>>> import gdbm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gdbm

root@RasPi:~/scripts/medusa# python2 -m pip list | grep sub
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@RasPi:~/scripts/medusa#
```

**Comment by ngosang** [comment]
After installing  `apt-get install python-gdbm`  (it's not in the guide https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Ubuntu-15) I get this error:
```
Jan 11 20:13:43 RasPi medusa[16291]: 2019-01-11 20:13:43 INFO     Thread_9 :: [918cfe7] Starting to manual searching subtitles
Jan 11 20:13:43 RasPi medusa[16291]: 2019-01-11 20:13:43 INFO     Thread_9 :: [918cfe7] Manual searching subtitles for: Mind.Field.S03E04.1080p.WEB-DL-AAC2
Jan 11 20:13:44 RasPi medusa[16291]: 2019-01-11 20:13:44 DEBUG    Thread_9 :: [918cfe7] Scanning video /media/SEA3TB/TV_EN/Mind Field/Season 03/Mind.Field.S03E04.1080p.WEB-DL-AAC2.mkv...
Jan 11 20:13:46 RasPi medusa[16291]: 2019-01-11 20:13:46 DEBUG    Thread_9 :: [918cfe7] Starting release refiner [extension=release, release_name=Mind.Field.S03E04.1080p.WEB-DL-AAC2, release_file=None]
Jan 11 20:13:46 RasPi medusa[16291]: 2019-01-11 20:13:46 DEBUG    Thread_9 :: [918cfe7] Guessing using /media/SEA3TB/TV_EN/Mind Field/Season 03/Mind.Field.S03E04.1080p.WEB-DL-AAC2.mkv
Jan 11 20:13:47 RasPi medusa[16291]: 2019-01-11 20:13:47 DEBUG    Thread_9 :: [918cfe7] Refining using Series information.
Jan 11 20:13:47 RasPi medusa[16291]: 2019-01-11 20:13:47 DEBUG    Thread_9 :: [918cfe7] Attribute series_tvdb_id changed from None to 322873
Jan 11 20:13:47 RasPi medusa[16291]: 2019-01-11 20:13:47 DEBUG    Thread_9 :: [918cfe7] Attribute series_imdb_id changed from None to u'tt6439562'
Jan 11 20:13:47 RasPi medusa[16291]: 2019-01-11 20:13:47 DEBUG    Thread_9 :: [918cfe7] Attribute year changed from None to 2017
Jan 11 20:13:47 RasPi medusa[16291]: 2019-01-11 20:13:47 DEBUG    Thread_9 :: [918cfe7] Refining using Episode information.
Jan 11 20:13:47 RasPi medusa[16291]: 2019-01-11 20:13:47 DEBUG    Thread_9 :: [918cfe7] Attribute title changed from None to u'The Stanford Prison Experiment'
Jan 11 20:13:47 RasPi medusa[16291]: 2019-01-11 20:13:47 DEBUG    Thread_9 :: [918cfe7] Attribute tvdb_id changed from None to 6945624
Jan 11 20:13:47 RasPi medusa[16291]: 2019-01-11 20:13:47 DEBUG    Thread_9 :: [918cfe7] Video information cached under key medusa.subtitles:video|/media/SEA3TB/TV_EN/Mind Field/Season 03/Mind.Field.S03E04.1080p.WEB-DL-AAC2.mkv
Jan 11 20:13:49 RasPi medusa[16291]: 2019-01-11 20:13:49 ERROR    Thread_9 :: [918cfe7] Exception generated: Bad magic number
Jan 11 20:13:49 RasPi medusa[16291]: Traceback (most recent call last):
Jan 11 20:13:49 RasPi medusa[16291]:   File "/root/scripts/medusa/medusa/server/web/core/base.py", line 258, in async_call
Jan 11 20:13:49 RasPi medusa[16291]:     result = function(**kwargs)
Jan 11 20:13:49 RasPi medusa[16291]:   File "/root/scripts/medusa/medusa/server/web/home/handler.py", line 2212, in manual_search_subtitles
Jan 11 20:13:49 RasPi medusa[16291]:     found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
Jan 11 20:13:49 RasPi medusa[16291]:   File "/root/scripts/medusa/medusa/subtitles.py", line 335, in list_subtitles
Jan 11 20:13:49 RasPi medusa[16291]:     cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
Jan 11 20:13:49 RasPi medusa[16291]:   File "/root/scripts/medusa/ext/dogpile/cache/region.py", line 1015, in set
Jan 11 20:13:49 RasPi medusa[16291]:     self.backend.set(key, self._value(value))
Jan 11 20:13:49 RasPi medusa[16291]:   File "/root/scripts/medusa/ext/dogpile/cache/backends/file.py", line 237, in set
Jan 11 20:13:49 RasPi medusa[16291]:     with self._dbm_file(True) as dbm:
Jan 11 20:13:49 RasPi medusa[16291]:   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
Jan 11 20:13:49 RasPi medusa[16291]:     return self.gen.next()
Jan 11 20:13:49 RasPi medusa[16291]:   File "/root/scripts/medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
Jan 11 20:13:49 RasPi medusa[16291]:     "w" if write else "r")
Jan 11 20:13:49 RasPi medusa[16291]:   File "/usr/lib/python2.7/anydbm.py", line 85, in open
Jan 11 20:13:49 RasPi medusa[16291]:     return mod.open(file, flag, mode)
Jan 11 20:13:49 RasPi medusa[16291]: error: Bad magic number
```

**Comment by p0psicles** [comment]
Remove the dbm dog pile files

**Comment by ngosang** [comment]
Could you be more specific?
I removed `ext/dogpile/cache/backends/file.py` and medusa can't start as expected.

**Comment by p0psicles** [comment]
No, not that. The files in your Medusa cache folder.

**Comment by ngosang** [comment]
It's working now. I updated recently but through medusa web ui.
