### ISSUE TITLE
Post Process does not move files 

### ISSUE THREAD

**Issue by adman120** [pymedusa/Medusa#6024]
Post Process does not move files even when run as manual.

**Comment by adman120** [comment]
2019-01-16 23:27:15 ERROR    POSTPROCESSOR :: [918cfe7] Unable to move file /mnt/Download/Done/[Asakura].Tensei.Shitara.Slime.Datta.Ken-14.[1080p][73CEAF0F]/[Asakura] Tensei Shitara Slime Datta Ken - 14 [1080p][73CEAF0F].mkv to /mnt/Media/videos/shows/anime/That Time I Got Reincarnated as a Slime/Season 01/That Time I Got Reincarnated as a Slime - S01E14 - The One Who Devours All.mkv: IOError(5, 'Input/output error')
Traceback (most recent call last):
  File "/opt/medusa/medusa/post_processor.py", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/opt/medusa/medusa/helpers/__init__.py", line 312, in move_file
    shutil.move(src_file, dest_file)
  File "/opt/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/usr/lib/python2.7/shutil.py", line 316, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/opt/medusa/lib/shutil_custom/__init__.py", line 37, in copyfile_custom
    fdst.write(buf)
IOError: [Errno 5] Input/output error

**Comment by p0psicles** [comment]
Your having io errors. Disk full? Access rights?

**Comment by adman120** [comment]
Disk isnt full and it has full access rights, so thats why im confused because it worked fine with sonarr

**Comment by medariox** [comment]
Related to hw issues or similar. We can't help you.
