### ISSUE TITLE
Medusa Keeps Downloading Episodes Multiple Times

### ISSUE THREAD

**Issue by DanGarion** [pymedusa/Medusa#6156]
I have been experiencing issues with Medusa the past few weeks where it downloads the same episode multiple times (usually twice) via BitTorrent. It could either be two completely different versions of the show or two different versions. It could also download it either from the same torrent site or two different torrent sites. In addition, although episodes get fully downloaded the system never is able to pick up that they are completed and the episode either stays in the "wanted" or "snatched" status and the system doesn't conduct post-processing. I have to manually post-process for it to recognize that the episode was downloaded. All of this started about 3 weeks ago.

**Expected behavior**
The expected behavior is ONE single episode is snatched, post-processed, and then marked as downloaded.

**Screenshots**

**Medusa (please complete the following information):**
Medusa Info: | Branch: master Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 Version: Unknown Database: 44.12
-- | --
Python Version: | 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
SSL Version: | LibreSSL 2.7.4
OS: | Linux-4.9.0-8-amd64-x86_64-with

**Logs:**  --- As you can see the log shows that it downloads the show twice.
```
2019-01-29 19:39:00 ERROR    Thread_7 :: [918cfe7] Exception generated: 'unicode' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 258, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/post_process.py", line 55, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 145, in process
    ignore_subs=ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 335, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 556, in process_media
    self.result = processor.process()
  File "/app/medusa/medusa/post_processor.py", line 1289, in process
    notifiers.notify_download(ep_obj)
  File "/app/medusa/medusa/notifiers/__init__.py", line 100, in notify_download
    n.notify_download(ep_obj)
  File "/app/medusa/medusa/notifiers/join.py", line 51, in notify_download
    message=ep_obj.pretty_name_with_quality()
  File "/app/medusa/medusa/notifiers/join.py", line 99, in _sendjoin
    log.warning('Join notification failed: {0}', failed.get('message'))
AttributeError: 'unicode' object has no attribute 'get'
2019-01-29 19:18:10 ERROR    SNATCHQUEUE-SNATCH-279121 :: [918cfe7] Snatch failed! For result: The.Flash.2014.S05E12.720p.HDTV.x264-SVA
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 222, in snatch_episode
    notifiers.notify_snatch(curEpObj, result)
  File "/app/medusa/medusa/notifiers/__init__.py", line 127, in notify_snatch
    n.notify_snatch(title, message)
  File "/app/medusa/medusa/notifiers/join.py", line 43, in notify_snatch
    message=message
  File "/app/medusa/medusa/notifiers/join.py", line 99, in _sendjoin
    log.warning('Join notification failed: {0}', failed.get('message'))
AttributeError: 'unicode' object has no attribute 'get'
2019-01-29 18:38:10 ERROR    SNATCHQUEUE-SNATCH-279121 :: [918cfe7] Snatch failed! For result: The.Flash.2014.S05E12.720p.HEVC.x265-MeGusta
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 222, in snatch_episode
    notifiers.notify_snatch(curEpObj, result)
  File "/app/medusa/medusa/notifiers/__init__.py", line 127, in notify_snatch
    n.notify_snatch(title, message)
  File "/app/medusa/medusa/notifiers/join.py", line 43, in notify_snatch
    message=message
  File "/app/medusa/medusa/notifiers/join.py", line 99, in _sendjoin
    log.warning('Join notification failed: {0}', failed.get('message'))
AttributeError: 'unicode' object has no attribute 'get'
```
</details>

**Comment by p0psicles** [comment]
Already fixed in develop branch
