### ISSUE TITLE
Unexpected error in provider u'legendastv'

### ISSUE THREAD

**Issue by tvcsantos** [pymedusa/Medusa#6163]
**Description**
Can't download subtitles using LegendasTV.

**To Reproduce**
Configure LegendasTV on subtitle search and try to search for a tv show for which you know that subtitles would be found. Check that there is a warning stating that an unexpected error has occurred.

**Expected behavior**
Subtitle has to be found and downloaded.

**Medusa:**
Branch: master 
Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 
Version: v0.2.14 
Database: 44.12

Python Version: 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
SSL Version: LibreSSL 2.7.4
OS: Linux-4.19.0-0.bpo.1-amd64-x86_64-with

**Logs:**
<details>

```
2019-02-02 19:13:49 WARNING  FINDSUBTITLES :: [918cfe7] Unexpected error in provider u'legendastv'
Traceback (most recent call last):
  File "/app/medusa/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/app/medusa/ext/subliminal/providers/legendastv.py", line 502, in list_subtitles
    self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/app/medusa/ext/subliminal/providers/legendastv.py", line 434, in query
    titles = self.search_titles(title, season, year)
  File "/app/medusa/ext/dogpile/cache/region.py", line 1270, in decorate
    should_cache_fn)
  File "/app/medusa/ext/dogpile/cache/region.py", line 864, in get_or_create
    async_creator) as value:
  File "/app/medusa/ext/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 93, in _enter
    generated = self._enter_create(value, createdtime)
  File "/app/medusa/ext/dogpile/lock.py", line 179, in _enter_create
    return self.creator()
  File "/app/medusa/ext/dogpile/cache/region.py", line 831, in gen_value
    created_value = creator()
  File "/app/medusa/ext/dogpile/cache/region.py", line 1266, in creator
    return fn(*arg, **kw)
  File "/app/medusa/ext/subliminal/providers/legendastv.py", line 272, in search_titles
    r = self.session.get(self.server_url + 'legenda/sugestao/{}'.format(sanitized_title), timeout=10)
  File "/app/medusa/ext/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/ext/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
</details>

**Comment by tvcsantos** [comment]
ok now i got it working. probabably i was being blocked. also i've changed my dns to google dns since i was being blocked in some websites. I have a question though. How can I change the minscore of a subtitle I'm getting 340 out of 345 wich seems pretty close to me that I would like to tune it and lower it a bit.

Thanks

**Comment by medariox** [comment]
@tvcsantos 
There is no way to fine tune it atm, but you can disable "Perfect matches" (min. score 330) or use manual subtitle search.
