### ISSUE TITLE
Phantom Volumes Causing Errors

### ISSUE THREAD

**Issue by desepticon** [pymedusa/Medusa#6196]
**Describe the bug**
I recently moved a bunch of media files around to consolidate space on the array of drives I have. While I was at it I reformatted them one by one and gave them new names. Then I copied the data back to the different drives. I then went through all my shows in Medusa and pointed them to the new locations. This was simple enough. However, I now occasionally get errors pertaining to phantom drives that no longer exist. 

I also noticed in the show listed in the error, most of the episodes are correctly pointed to the new drive name. However, one or 2 is still pointing to the old one. Neither "Re-scan Files" or "Force Full Update" is able to clear them, even if I delete the files where they should be on the new drive. They still remain listed.

**Expected behavior**
I want to remove the phantom behavior.

**Medusa (please complete the following information):**
 - MacOS 10.14.3
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76 

**Logs:**
<details>

```
2019-02-10 03:09:15 ERROR    SHOWQUEUE-REFRESH :: [918cfe7] 72231: Error while refreshing show Real Time with Bill Maher. Error: [Errno 13] Permission denied: '/Volumes/WD 4 TB 1'
Traceback (most recent call last):
  File "/Users/matt/Builds/medusa/medusa/show_queue.py", line 691, in run
    self.show.write_metadata()
  File "/Users/matt/Builds/medusa/medusa/tv/series.py", line 930, in write_metadata
    self.__write_episode_nfos()
  File "/Users/matt/Builds/medusa/medusa/tv/series.py", line 959, in __write_episode_nfos
    cur_ep.create_meta_files()
  File "/Users/matt/Builds/medusa/medusa/tv/episode.py", line 1109, in create_meta_files
    self.__create_nfo(metadata_provider)
  File "/Users/matt/Builds/medusa/medusa/tv/episode.py", line 1123, in __create_nfo
    result = metadata_provider.create_episode_metadata(self) or result
  File "/Users/matt/Builds/medusa/medusa/metadata/generic.py", line 283, in create_episode_metadata
    return self.write_ep_file(ep_obj)
  File "/Users/matt/Builds/medusa/medusa/metadata/generic.py", line 508, in write_ep_file
    os.makedirs(nfo_file_dir)
  File "/Users/matt/Builds/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/matt/Builds/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/matt/Builds/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/matt/Builds/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/matt/Builds/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
  File "/Users/matt/Builds/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
OSError: [Errno 13] Permission denied: '/Volumes/WD 4 TB 1'
```
</details>

**Additional context**
There is no WD 4 TB 1 anymore. This got changed. However Medusa seems to think it still exists.

**Comment by medariox** [comment]
Try to remove the affected shoes and re-add them (you don't need to delete the media files).
