### ISSUE TITLE
Medusa won't start anymore

### ISSUE THREAD

**Issue by W13N3N** [pymedusa/Medusa#6229]
For some reason my Medusa setup won't start anymore. As far as i can remember i didn't update anything on my machine (Server 2016) besides the Windows Updates.

When i manually run start.py i'm getting the following error;
`Traceback (most recent call last):
  File "C:\Program Files (x86)\Medusa2\start.py", line 14, in <module>
    main()
  File "C:\Program Files (x86)\Medusa2\medusa\__main__.py", line 2184, in main
    application.start(sys.argv[1:])
  File "C:\Program Files (x86)\Medusa2\medusa\__main__.py", line 314, in start
    app.CFG = ConfigObj(app.CONFIG_FILE, encoding='UTF-8', default_encoding='UTF-8')
  File "C:\Program Files (x86)\Medusa2\ext\configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "C:\Program Files (x86)\Medusa2\ext\configobj.py", line 1318, in _load
    raise error
configobj.ParseError: Invalid line (u'subtitles_') (matched as neither section nor keyword) at line 1348.`

I'm on the master branch commit 918cfe7. Even when i do a fresh git clone and copy over the config.ini and main.db file i'm getting the same error.

Hopefully anyone can help me out!

Thanks in advance!

**Comment by p0psicles** [comment]
There something wrong with your config.ini
Check for the subtitles key

**Comment by W13N3N** [comment]
Thanks for your quick response.

I've checked my config.ini and it ends at line 1348 with "subtitles_".
It seems my config file isn't complete anymore. I've noticed the last save time and it was exactly at the same time my server gets an scheduled shutdown to save power over night.

Then i checked the log file and this is the last entry;
'2019-02-15 01:00:21 INFO     MAIN :: [918cfe7] Signal 2 caught, saving and exiting...
2019-02-15 01:00:21 INFO     EVENT-QUEUE :: [918cfe7] Aborting all threads
2019-02-15 01:00:21 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the DAILYSEARCHER thread to exit
2019-02-15 01:00:22 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the BACKLOG thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the SHOWUPDATER thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the CHECKVERSION thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the SHOWQUEUE-REFRESH thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the FORCEDSEARCHQUEUE thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the MANUALSNATCHQUEUE thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the POSTPROCESSOR thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the TRAKTCHECKER thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the FINDPROPERS thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the FINDSUBTITLES thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the TORRENTCHECKER thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Waiting for the EVENT-QUEUE thread to exit
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Saving all shows to the database
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Saving config file to disk
2019-02-15 01:00:23 INFO     EVENT-QUEUE :: [918cfe7] Unable to update the list with broken providers. This list is used to disable broken providers. You may encounter errors in the log files if you are using a broken provider.'

So it seems the config.ini wasn't succesfully saved before the server shut down.

Is there some backup config.ini file automatically stored? Or another way how i can restore the config.ini file without a fresh install?

**Comment by p0psicles** [comment]
Do you have any config.ini.v*? Else you can try to cut off the config clean

**Comment by medariox** [comment]
Luckily you didn't loose too much information, basically just the subtitle section and a bit more.
Shut down Medusa, search for `[Subtitles]` in your config.ini and replace it with this:

```
[Subtitles]
use_subtitles = 1
subtitles_erase_cache = 0
subtitles_languages = eng,
SUBTITLES_SERVICES_LIST = addic7ed, itasa, legendastv, napiprojekt, opensubtitles, podnapisi, shooter, thesubdb, tvsubtitles, wizdom
SUBTITLES_SERVICES_ENABLED = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
subtitles_dir = ""
subtitles_default = 0
subtitles_history = 0
subtitles_perfect_match = 1
embedded_subtitles_all = 0
subtitles_stop_at_first = 0
embedded_subtitles_unknown_lang = 0
subtitles_hearing_impaired = 0
subtitles_finder_frequency = 1
subtitles_multi = 1
subtitles_extra_scripts = ,
subtitles_pre_scripts = ,
subtitles_keep_only_wanted = 0
addic7ed_username = ""
addic7ed_password = ""
itasa_username = ""
itasa_password = ""
legendastv_username = ""
legendastv_password = ""
opensubtitles_username = ""
opensubtitles_password = ""
[FailedDownloads]
use_failed_downloads = 0
delete_failed = 0
[ANIDB]
use_anidb = 0
anidb_username = ""
anidb_password = ""
anidb_use_mylist = 0
[ANIME]
anime_split_home = 0
anime_split_home_in_tabs = 0
```

Save and restart Medusa. Change the settings that were lost accordingly.

**Comment by sharkykh** [comment]
You can also look for the automatic backups. Each time Medusa is updated through the web UI a backup is made, it should be in the `backup` folder in your data folder.

**Comment by W13N3N** [comment]
Thanks all!! @sharkykh i've found the backup files. Extracted the config.ini and indeed @medariox  there was only a little bit missing. Added the missing parts to the corrupted config.ini and now Medusa starts fine again.

Again, thanks all for your quick replies. Case closed!
