### ISSUE TITLE
error with addic7ed

### ISSUE THREAD

**Issue by bibi32** [pymedusa/Medusa#6281]
**Describe the bug**
I can't download french subtitle from addic7ed with old and new install, with debian x64 and docker on stable or develop and 2 addic7ed account.
One exemple bellow:

**To Reproduce**
1. Go to subtitle 
2. Click on Subtitle Languages set french
3. Go to Subtitle Providers set addic7ed
4. Go to Provider Settings and enter the addic7ed account

**Medusa (please complete the following information):**
 - OS: docker on raspberry pi, image: linuxserver/medusa:latest
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76

**Logs:**
2019-03-07 16:44:22 INFO     SNATCHQUEUE-SNATCH-71663 :: [918cfe7] Downloading The.Simpsons.S30E15.WEB.x264-TBS[rartv] with 244 seeders and 6 leechers and size 158.05 MB from Rarbg, through a SearchType.MANUAL_SEARCH search

2019-03-07 16:52:00 INFO     Thread_15 :: [918cfe7] Successfully processed.
2019-03-07 16:51:44 INFO     POSTPROCESSOR :: [918cfe7] Successfully processed.
2019-03-07 16:51:44 INFO     POSTPROCESSOR :: [918cfe7] Deleting folder (if it's empty): /downloads/completed/The.Simpsons.S30E15.WEB.x264-TBS[rarbg]
2019-03-07 16:51:44 INFO     POSTPROCESSOR :: [918cfe7] Processing succeeded for /downloads/completed/The.Simpsons.S30E15.WEB.x264-TBS[rarbg]/the.simpsons.s30e15.web.x264-tbs.mkv
2019-03-07 16:51:43 INFO     POSTPROCESSOR :: [918cfe7] 71663: No subtitles found for The Simpsons S30E15
2019-03-07 16:51:43 INFO     POSTPROCESSOR :: [918cfe7] No subtitles found for The Simpsons.S30E15.101 Mitigations.mkv
2019-03-07 16:51:34 INFO     POSTPROCESSOR :: [918cfe7] Release name (the.simpsons.s30e15.web.x264-tbs) found from file (the.simpsons.s30e15.web.x264-tbs.nfo)
2019-03-07 16:51:34 INFO     POSTPROCESSOR :: [918cfe7] Trying to clean any empty folder under /data/series/The Simpsons/Saison 30
2019-03-07 16:51:34 INFO     POSTPROCESSOR :: [918cfe7] This download is marked a priority download so I'm going to replace an existing file if I find one
2019-03-07 16:51:34 INFO     POSTPROCESSOR :: [918cfe7] New size: 158.05 MB
2019-03-07 16:51:34 INFO     POSTPROCESSOR :: [918cfe7] New file: /downloads/completed/The.Simpsons.S30E15.WEB.x264-TBS[rarbg]/the.simpsons.s30e15.web.x264-tbs.mkv
2019-03-07 16:51:33 INFO     POSTPROCESSOR :: [918cfe7] Processing /downloads/completed/The.Simpsons.S30E15.WEB.x264-TBS[rarbg]/the.simpsons.s30e15.web.x264-tbs.mkv

2019-03-07 16:53:58 INFO     Thread_4 :: [918cfe7] Manual searching subtitles for: the.simpsons.s30e15.web.x264-tbs
2019-03-07 16:53:58 INFO     Thread_4 :: [918cfe7] Starting to manual searching subtitles

2019-03-07 17:28:29 INFO     SHOWQUEUE-SUBTITLE :: [918cfe7] 71663: No subtitles found for The Simpsons S30E15
2019-03-07 17:28:29 INFO     SHOWQUEUE-SUBTITLE :: [918cfe7] No subtitles found for The Simpsons.S30E15.101 Mitigations.mkv
2019-03-07 17:28:25 INFO     SHOWQUEUE-SUBTITLE :: [918cfe7] 71663: Downloading subtitles for The Simpsons

[
![capture d ecran_2019-03-07_16-51-33](https://user-images.githubusercontent.com/26071810/53970094-45e2bd80-40fa-11e9-9859-356c2eee42f6.png)
](url)

**Comment by Tpsw242** [comment]
Hi, I've the same problem, can't download the French subtitle on Addic7ed with medusa :/

> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Scores computed for release: The.Flash.2014.S05E13.Goldfaced.mkv
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Searching subtitles [{'moviebytesize': '2561247037', 'sublanguageid': u'fre', 'moviehash': 'b12ac382f0072533'}, {'sublanguageid': u'fre', 'tag': u'The.Flash.2014.S05E13.Goldfaced.mkv'}, {'query': u'The Flash', 'sublanguageid': u'fre', 'episode': 13, 'season': 5}]
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Listing subtitles with provider u'opensubtitles' and languages set([<Language [fr]>])
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Listing subtitles with provider u'addic7ed' and languages set([<Language [fr]>])
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Video information cached under key medusa.subtitles:video|/home/**********/Video/Series/The Flash (2014)/Season 05/The.Flash.2014.S05E13.Goldfaced.mkv
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Refining video with omdb
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Refining video with tvdb
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Attribute tvdb_id changed from None to 7000467
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Refining using Episode information.
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Attribute series_imdb_id changed from None to u'tt3107288'
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Attribute series_tvdb_id changed from None to 279121
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Refining using Series information.
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Refining video with tvepisode
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Attribute release_group changed from None to u'lucidtv'
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Attribute resolution changed from None to u'1080p'
> 2019-03-07 22:48:54 DEBUG Thread_18 :: [5418ce6] Attribute source changed from None to u'HDTV'
> 2019-03-07 22:48:53 DEBUG Thread_18 :: [5418ce6] Guessing using /home/**********/Video/Series/The Flash (2014)/Season 05/the.flash.2014.s05e13.1080p.hdtv.x264-lucidtv.mkv
> 2019-03-07 22:48:53 DEBUG Thread_18 :: [5418ce6] Starting release refiner [extension=release, release_name=the.flash.2014.s05e13.1080p.hdtv.x264-lucidtv, release_file=None]
> 2019-03-07 22:48:53 DEBUG Thread_18 :: [5418ce6] Refining video with release
> 2019-03-07 22:48:53 DEBUG Thread_18 :: [5418ce6] Refining video with metadata
> 2019-03-07 22:48:53 DEBUG Thread_18 :: [5418ce6] Scanning video u'The.Flash.2014.S05E13.Goldfaced.mkv' in u'/home/**********/Video/Series/The Flash (2014)/Season 05'
> 2019-03-07 22:48:53 DEBUG Thread_18 :: [5418ce6] Scanning video /home/**********/Video/Series/The Flash (2014)/Season 05/The.Flash.2014.S05E13.Goldfaced.mkv...
> 2019-03-07 22:48:53 INFO Thread_18 :: [5418ce6] Manual searching subtitles for: the.flash.2014.s05e13.1080p.hdtv.x264-lucidtv
> 2019-03-07 22:48:53 INFO Thread_18 :: [5418ce6] Starting to manual searching subtitles
> 2019-03-07 22:48:50 DEBUG Thread_38 :: [5418ce6] Scores computed for release: The.Flash.2014.S05E15.King.Shark.vs.Gorilla.Grodd.mkv
> 2019-03-07 22:48:50 DEBUG Thread_38 :: [5418ce6] Searching subtitles [{'moviebytesize': '2525942050', 'sublanguageid': u'fre', 'moviehash': 'c1bc4c6a3d3fd65a'}, {'sublanguageid': u'fre', 'tag': u'The.Flash.2014.S05E15.King.Shark.vs.Gorilla.Grodd.mkv'}, {'query': u'The Flash', 'sublanguageid': u'fre', 'episode': 15, 'season': 5}]
> 2019-03-07 22:48:50 DEBUG Thread_38 :: [5418ce6] Listing subtitles with provider u'opensubtitles' and languages set([<Language [fr]>])
> 2019-03-07 22:48:50 DEBUG Thread_38 :: [5418ce6] Listing subtitles with provider u'addic7ed' and languages set([<Language [fr]>])
> 2019-03-07 22:48:50 DEBUG Thread_38 :: [5418ce6] Found cached video information under key medusa.subtitles:video|/home/**********/Video/Series/The Flash (2014)/Season 05/The.Flash.2014.S05E15.King.Shark.vs.Gorilla.Grodd.mkv
> 2019-03-07 22:48:50 INFO Thread_38 :: [5418ce6] Manual searching subtitles for: the.flash.2014.s05e15.1080p.web.h264-tbs
> 2019-03-07 22:48:50 INFO Thread_38 :: [5418ce6] Starting to manual searching subtitles
> 2019-03-07 22:48:40 DEBUG Thread_36 :: [5418ce6] Scores computed for release: The.Flash.2014.S05E14.Cause.and.XS.mkv
> 2019-03-07 22:48:40 DEBUG Thread_36 :: [5418ce6] Computed score 245 with final matches set(['episode', 'title', 'series', 'season', 'video_codec', 'resolution', 'hearing_impaired'])
> 2019-03-07 22:48:40 DEBUG Thread_36 :: [5418ce6] Computing score of <OpenSubtitlesSubtitle '1956230339' [fr]> for video <Episode [u'The Flash', 2014, 5x14]> with {'hearing_impaired': 0}
> 2019-03-07 22:48:40 DEBUG Thread_36 :: [5418ce6] Computed score 357 with final matches set(['episode', 'title', 'series', 'year', 'source', 'hearing_impaired', 'season', 'video_codec', 'resolution', 'release_group'])
> 2019-03-07 22:48:40 DEBUG Thread_36 :: [5418ce6] Computing score of <OpenSubtitlesSubtitle '1956230690' [fr]> for video <Episode [u'The Flash', 2014, 5x14]> with {'hearing_impaired': 0}
> 2019-03-07 22:48:40 DEBUG Thread_36 :: [5418ce6] Computed score 340 with final matches set(['episode', 'title', 'series', 'year', 'source', 'season', 'video_codec', 'hearing_impaired'])
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Computing score of <OpenSubtitlesSubtitle '1956230490' [fr]> for video <Episode [u'The Flash', 2014, 5x14]> with {'hearing_impaired': 0}
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Computed score 340 with final matches set(['episode', 'title', 'series', 'year', 'source', 'season', 'video_codec', 'hearing_impaired'])
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Computing score of <OpenSubtitlesSubtitle '1956230401' [fr]> for video <Episode [u'The Flash', 2014, 5x14]> with {'hearing_impaired': 0}
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Computed score 335 with final matches set(['episode', 'title', 'series', 'year', 'season', 'video_codec', 'resolution', 'hearing_impaired'])
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Computing score of <OpenSubtitlesSubtitle '1956230340' [fr]> for video <Episode [u'The Flash', 2014, 5x14]> with {'hearing_impaired': 0}
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Searching subtitles [{'moviebytesize': '2289927418', 'sublanguageid': u'fre', 'moviehash': 'c924648566bc781f'}, {'sublanguageid': u'fre', 'tag': u'The.Flash.2014.S05E14.Cause.and.XS.mkv'}, {'query': u'The Flash', 'sublanguageid': u'fre', 'episode': 14, 'season': 5}]
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Listing subtitles with provider u'opensubtitles' and languages set([<Language [fr]>])
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Listing subtitles with provider u'addic7ed' and languages set([<Language [fr]>])
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Video information cached under key medusa.subtitles:video|/home/**********/Video/Series/The Flash (2014)/Season 05/The.Flash.2014.S05E14.Cause.and.XS.mkv
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Refining video with omdb
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Refining video with tvdb
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Attribute tvdb_id changed from None to 7026407
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Refining using Episode information.
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Attribute series_imdb_id changed from None to u'tt3107288'
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Attribute series_tvdb_id changed from None to 279121
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Refining using Series information.
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Refining video with tvepisode
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Attribute release_group changed from None to u'lucidtv'
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Attribute resolution changed from None to u'1080p'
> 2019-03-07 22:48:39 DEBUG Thread_36 :: [5418ce6] Attribute source changed from None to u'HDTV'
> 2019-03-07 22:48:38 DEBUG Thread_36 :: [5418ce6] Guessing using /home/**********/Video/Series/The Flash (2014)/Season 05/the.flash.2014.s05e14.1080p.hdtv.x264-lucidtv.mkv
> 2019-03-07 22:48:38 DEBUG Thread_36 :: [5418ce6] Starting release refiner [extension=release, release_name=the.flash.2014.s05e14.1080p.hdtv.x264-lucidtv, release_file=None]
> 2019-03-07 22:48:38 DEBUG Thread_36 :: [5418ce6] Refining video with release
> 2019-03-07 22:48:38 DEBUG Thread_36 :: [5418ce6] Refining video with metadata
> 2019-03-07 22:48:38 DEBUG Thread_36 :: [5418ce6] Scanning video u'The.Flash.2014.S05E14.Cause.and.XS.mkv' in u'/home/**********/Video/Series/The Flash (2014)/Season 05'
> 2019-03-07 22:48:38 DEBUG Thread_36 :: [5418ce6] Scanning video /home/**********/Video/Series/The Flash (2014)/Season 05/The.Flash.2014.S05E14.Cause.and.XS.mkv...
> 2019-03-07 22:48:38 INFO Thread_36 :: [5418ce6] Manual searching subtitles for: the.flash.2014.s05e14.1080p.hdtv.x264-lucidtv
> 2019-03-07 22:48:38 INFO Thread_36 :: [5418ce6] Starting to manual searching subtitles

**Comment by p0psicles** [comment]
Did you try the manual subtitle search feature in Medusa?

**Comment by bibi32** [comment]
yes, no windows open to select subtitle, and auto nothing.

**Comment by p0psicles** [comment]
Can I get a debug log of that? Also check for errors in Chrome console?

**Comment by bibi32** [comment]
the debug of manual subtitle ? And I haven't google chrome.

**Comment by bibi32** [comment]
`2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Scores computed for release: The Simpsons.S30E15.101 Mitigations.mkv
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Video information cached under key medusa.subtitles:video|/data/series/The Simpsons/Saison 30/The Simpsons.S30E15.101 Mitigations.mkv
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Attribute tvdb_id changed from None to 7044993
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Refining using Episode information.
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Attribute year changed from None to 1989
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Attribute series_imdb_id changed from None to u'tt0096697'
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Attribute series_tvdb_id changed from None to 71663
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Attribute series changed from u'the simpsons' to u'The Simpsons'
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Refining using Series information.
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Attribute release_group changed from None to u'tbs'
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Attribute series changed from 'The Simpsons' to u'the simpsons'
2019-03-08 07:46:17 DEBUG    Thread_15 :: [918cfe7] Attribute source changed from None to u'Web'
2019-03-08 07:46:16 DEBUG    Thread_15 :: [918cfe7] Guessing using /data/series/The Simpsons/Saison 30/the.simpsons.s30e15.web.x264-tbs.mkv
2019-03-08 07:46:16 DEBUG    Thread_15 :: [918cfe7] Starting release refiner [extension=release, release_name=the.simpsons.s30e15.web.x264-tbs, release_file=None]
2019-03-08 07:46:15 DEBUG    Thread_15 :: [918cfe7] Scanning video /data/series/The Simpsons/Saison 30/The Simpsons.S30E15.101 Mitigations.mkv...
2019-03-08 07:46:15 INFO     Thread_15 :: [918cfe7] Manual searching subtitles for: the.simpsons.s30e15.web.x264-tbs
2019-03-08 07:46:15 INFO     Thread_15 :: [918cfe7] Starting to manual searching subtitles`

**Comment by bibi32** [comment]
with develop today:

2019-03-10 22:03:45 WARNING  Thread_2 :: [b7cb0e9] Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "/app/medusa/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/app/medusa/ext/subliminal/core.py", line 72, in __getitem__
    provider.initialize()
  File "/app/medusa/ext/subliminal/providers/addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: tux32
2019-03-10 22:03:45 INFO     Thread_2 :: [b7cb0e9] Manual searching subtitles for: Supergirl.S04E13.HDTV.x264-SVA
2019-03-10 22:03:45 INFO     Thread_2 :: [b7cb0e9] Starting to manual searching subtitles

**Comment by p0psicles** [comment]
Looks like Auth issue. Can also be a rate limmiter

**Comment by bibi32** [comment]
my addicted account:

Downloads by User Today | 0 of 40 |  
Downloads from IP Today | 0

**Comment by p0psicles** [comment]
If there is an Auth issue or bug, you'll need to report it with the subliminal project. Nothing we can do about it.

**Comment by bibi32** [comment]
why that work with sonarr and bazarr with this account ??

**Comment by p0psicles** [comment]
Sonarr doesn't use subliminal. Bazarr does. Good question. We pass your credentials on to subliminal.
@medariox thoughts?

**Comment by bibi32** [comment]
I don't understand " We pass your credentials on to subliminal.@medariox thoughts?"

**Comment by p0psicles** [comment]
In the application. The Medusa code uses subliminal as a dependency. So we call upon subliminal using the credentials the user provides.

**Comment by bibi32** [comment]
ok give my logs to subliminal, if you have a french guy in your team that can help me.

**Comment by sharkykh** [comment]
FYI:
This is the reason the addic7ed subtitle provider is not working right now:
https://twitter.com/addic7ed/status/1104855032774709248
> For the moment, a reCaptcha v2 was implemented on the login page. We're also working on an API to make things easier for people that want to automate subtitle downloads (and uploads!). More info soon.

![image](https://user-images.githubusercontent.com/10238474/54177421-dc1c3800-449a-11e9-85bb-4062f4d4d1ae.png)

**Comment by bibi32** [comment]
Ok thanks for info.

**Comment by BenTotoro** [comment]
Hello,
I noticed that the issue is closed till Addi7ed adds an API feature, btw Addic7ed is the biggest source for french subtitles, and there are some scrapper and API that could do the job : 
https://github.com/adrian-maurin/addic7ed
https://github.com/same31/addic7ed-api
Is it possible to add this feature ?
Thank you

**Comment by p0psicles** [comment]
Those other projects also struggle with the captcha on the site. And AFAIK addic7ed still hasn't released an api

**Comment by p0psicles** [comment]
And if an api was available it would need to be implement at subliminal, not here

**Comment by BenTotoro** [comment]
But how do you explain that a Kodi plugin can do the job ? Shouldn't it be struggled to ?

**Comment by p0psicles** [comment]
Don't know the details. Maybe Kodi isn't loging in. And subliminal does to get certain information. You'll have to ask those questions at subliminal. Doesn't have anything to do with medusa
