### ISSUE TITLE
Comma's, Special Characters, need to be stripped from file-names and searches

### ISSUE THREAD

**Issue by trumblejoe** [pymedusa/Medusa#6345]
3.0 Medusa, but confirmed the previous version of Medusa as-well.

Please note, the issue here is with the resulting filenames, not just the pre-post-processed filenames; though from what I have observed, Medusa struggles on special characters in a a number of places, including manual search.

After removing this file, the post-processing completed successfully.

**Logs:**
2019-03-14 04:56:39 WARNING POSTPROCESSOR :: [94fae84] /home6/**********/files/Medusa/The.Flash.2014.S04.1080p.BluRay.x264-YELLOWBiRD/The.Flash.2014.S04E16.1080p.BluRay.x264-YELLOWBiRD.mkv: Processing failed: Unable to copy the files to their new home
2019-03-14 04:56:39 WARNING POSTPROCESSOR :: [94fae84] Problem(s) during processing, failed for the following files/folders: 
2019-03-14 04:56:39 WARNING POSTPROCESSOR :: [94fae84] Processing failed for /home6/**********/files/Medusa/The.Flash.2014.S04.1080p.BluRay.x264-YELLOWBiRD/The.Flash.2014.S04E16.1080p.BluRay.x264-YELLOWBiRD.mkv: Unable to copy the files to their new home
2019-03-14 04:56:37 ERROR POSTPROCESSOR :: [94fae84] Unable to copy file /home6/**********/files/Medusa/The.Flash.2014.S04.1080p.BluRay.x264-YELLOWBiRD/The.Flash.2014.S04E16.1080p.BluRay.x264-YELLOWBiRD.mkv to /home6/**********/files/rclone/gdriveCryptPlain/Media/TV Shows/The Flash (2014)/Season 04/The Flash - S04E16 - Run, Iris, Run.mkv: IOError(2, 'No such file or directory') Traceback (most recent call last): File "/home6/**********/.apps/medusa/medusa/medusa/post_processor.py", line 482, in copy helpers.copy_file(cur_file_path, new_file_path) File "/home6/**********/.apps/medusa/medusa/medusa/helpers/__init__.py", line 285, in copy_file shutil.copyfile(src_file, dest_file) File "/home6/**********/.apps/medusa/medusa/lib/shutil_custom/__init__.py", line 32, in copyfile_custom with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst: File "/home6/**********/.apps/medusa/medusa/medusa/init/filesystem.py", line 112, in patched_output return handle_output(f(*args, **kwargs)) IOError: [Errno 2] No such file or directory: '/home6/**********/files/rclone/gdriveCryptPlain/Media/TV Shows/The Flash (2014)/Season 04/The Flash - S04E16 - Run, Iris, Run.mkv'

I propose that these characters be stripped. This is my own personal solution with FileBot for the past few years and it has taken care of the issue in an elegant manner.

**Comment by medariox** [comment]
This already happens during searches, otherwise you wouldn't be finding much.

This only happens during post-processing when the renamed file contains commas, do I understand this correctly?

**Comment by trumblejoe** [comment]
Yes, that is correct.

**Comment by medariox** [comment]
Is your locale set to the correct encoding? Otherwise I'd suggest to switch to Python 3, that will definitely solve your issue.
