### ISSUE TITLE
Update to 0.30 error: shared file access (poster.png , "Medusa")

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#6367]
Win 10/x86

2019-03-16 09:42:55 ERROR    Thread_2 :: [54da0c7] Error while trying to update: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\Program Files\\Medusa\\Medusa\\themes\\dark\\assets\\img\\poster.png'
Traceback (most recent call last):
  File "D:\Program Files\Medusa\Medusa\medusa\updater\source_updater.py", line 240, in update
    os.remove(new_path)
  File "D:\Program Files\Medusa\Medusa\medusa\init\filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\Program Files\\Medusa\\Medusa\\themes\\dark\\assets\\img\\poster.png'

**Comment by medariox** [comment]
Restart your PC and try to update again.

**Comment by rafi-d** [comment]
Did not help. 

2019-03-16 18:37:17 ERROR    Thread_7 :: [54da0c7] Error while trying to update: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\Program Files\\Medusa\\Medusa\\themes\\dark\\assets\\js\\medusa-runtime.js'
Traceback (most recent call last):
  File "D:\Program Files\Medusa\Medusa\medusa\updater\source_updater.py", line 240, in update
    os.remove(new_path)
  File "D:\Program Files\Medusa\Medusa\medusa\init\filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'D:\\Program Files\\Medusa\\Medusa\\themes\\dark\\assets\\js\\medusa-runtime.js'

Replacing main.db with the old main.db and re-starting medusa seem to have w/a the issue. 

I believe  the "use-case" was that he version DID update (showing 0.30 in help-info, but  the message above (alerting for a new version) was *still* showing , and pressing update with this situation was not possible.

Anyway, all is OK now.
