### ISSUE TITLE
DailySearchQueueItem Exception, error: 'ascii' codec can't encode character '\xe9' in position 54: ordinal not in range(128)

### ISSUE THREAD

**Issue by coptere** [pymedusa/Medusa#6374]
Since the change to python3 (and forcing a launch with python3), I have this problem that has appeared.

To install medusa with python3 support by default, I changed few lines in sickbeard-custom app from synocommunity like this in service-setup.sh:
PYTHON_DIR="/volume1/@appstore/py3k/usr/local"
PYTHON="${SYNOPKG_PKGDEST}/env/bin/python3"

**Medusa :**
Synology 216 DSM 6.2.1-23824 Update 6
Branch: master
Commit: 94fae847b6e7e443d74c59cb11bdbd37c464b363
Version: 0.3.0
Database: 44.14

Python Version: 3.5.1 (default, Jan 29 2018, 14:16:30)  [GCC 4.9.3 20150311 (prerelease)]
SSL Version: OpenSSL 1.0.2o-fips  27 Mar 2018
OS: Linux-3.10.105-armv7l-with-glibc2.4
Locale: Unknown.Unknown

**Logs:**
<details>
```
2019-03-18 09:48:09 WARNING  MAIN :: [94fae84] Your system is using an invalid encoding: ascii. Please change your encoding as soon as possible or you could encounter unexpected issues.

...

2019-03-18 09:34:16 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [94fae84] DailySearchQueueItem Exception, error: 'ascii' codec can't encode character '\xe9' in position 54: ordinal not in range(128)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/episode.py", line 276, in __setattr__
    refactor = self.__refactored[key]
KeyError: 'location'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/search/queue.py", line 263, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/search/core.py", line 501, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/search/core.py", line 470, in wanted_episodes
    ep_obj = series_obj.get_episode(episode['season'], episode['episode'])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/series.py", line 844, in get_episode
    ep = Episode(self, season, episode)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/episode.py", line 270, in __init__
    self._specify_episode(self.season, self.episode)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/episode.py", line 561, in _specify_episode
    sql_results = self.load_from_db(season, episode)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/episode.py", line 646, in load_from_db
    self.location = os.path.normpath(sql_results[0]['location'])
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/episode.py", line 278, in __setattr__
    super(Episode, self).__setattr__(key, value)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/base.py", line 57, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/episode.py", line 400, in location
    self.file_size = os.path.getsize(value) if value and self.is_location_valid(value) else 0
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/tv/episode.py", line 440, in is_location_valid
    return os.path.isfile(location or self._location)
  File "/volume1/@appstore/sickbeard-custom/env/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 54: ordinal not in range(128)
```
</details>

**Comment by medariox** [comment]
Set your locale, see: http://www.xn--brwolff-5wa.de/tech-notes/synology-diskstation-howto-set-locale.txt

**Comment by coptere** [comment]
Thx but, my locale in shell as admin:
# locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8

# locale -a
C
cs_CZ.utf8
da_DK.utf8
de_DE.utf8
en_US.utf8
es_ES.utf8
fr_FR.utf8
hu_HU.utf8
it_IT.utf8
ja_JP.utf8
ko_KR.utf8
nb_NO.utf8
nl_NL.utf8
pl_PL.utf8
POSIX
pt_BR.utf8
pt_PT.utf8
ru_RU.utf8
sv_SE.utf8
tr_TR.utf8
zh_CN.utf8
zh_TW.utf8

In DSM web language, i set to french.

medusa run with sc-sickbeard-custom user without bash, so i don't understand why sys.getfilesystemencoding find 'ascii' encondig

**Comment by medariox** [comment]
Did you set it in your profile and rebooted?
```
vi /etc/profile
 # add:
 LANG=de_DE.UTF-8
 LC_ALL=de_DE.UTF-8
 export LANG LC_ALL
reboot
```

**Comment by coptere** [comment]
reboot done

/etc/profile 
...
export LC_ALL=en_US.utf8
export LANG=en_US.utf8
...

in medusa, i always set US language (show description too) to avoid this bug. I only choose fr subtitle. So all my shows are on filesystem with US title.
bash# ls
Blindspot
Le Bureau des Legendes <= Maybe the one causing the bug https://www.imdb.com/title/tt4063800/
Narcos Mexico
The 100
Whiskey Cavalier
Deep State
Homeland
Lethal Weapon
SEAL Team
Van Helsing
Designated Survivor
Into the Badlands
Lost in Space (2018)
Star Trek Discovery
Vikings

**Comment by coptere** [comment]
More info:

admin@DS216:/volume1/Series$ LC_ALL=C find . -name '*[! -~]*'
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E08.??pisode.8.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E06.??pisode.6.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E02.??pisode.2.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E03.??pisode.3.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E01.??pisode.1.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E04.??pisode.4.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E07.??pisode.7.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E10.??pisode.10.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E09.??pisode.9.avi
./Le Bureau des Legendes/Le.Bureau.des.l??gendes.S03E05.??pisode.5.avi
admin@DS216:/volume1/Series$ ls Le\ Bureau\ des\ Legendes/
Le.Bureau.des.légendes.S03E01.Épisode.1.avi  Le.Bureau.des.légendes.S03E06.Épisode.6.avi
Le.Bureau.des.légendes.S03E02.Épisode.2.avi  Le.Bureau.des.légendes.S03E07.Épisode.7.avi
Le.Bureau.des.légendes.S03E03.Épisode.3.avi  Le.Bureau.des.légendes.S03E08.Épisode.8.avi
Le.Bureau.des.légendes.S03E04.Épisode.4.avi  Le.Bureau.des.légendes.S03E09.Épisode.9.avi
Le.Bureau.des.légendes.S03E05.Épisode.5.avi  Le.Bureau.des.légendes.S03E10.Épisode.10.avi

**Comment by medariox** [comment]
Yeah, that's because your Python install doesn't support non ASCII chars (like é). What you should do is ask Synology how to setup the locale for your Python install.

**Comment by coptere** [comment]
Thx but i changed tvshow to the US version.
Another one question, all my scheduler aren't alive, it's normal ? Should i open an issue ?

Thx

![image](https://user-images.githubusercontent.com/5759602/54595949-fa061180-4a33-11e9-9bf8-cd070a02b89d.png)
