### ISSUE TITLE
Manual subtitle download doesn't work

### ISSUE THREAD

**Issue by Superpiffer** [pymedusa/Medusa#6383]
If I try to manually download a subtitle for an episode, I have an error.

**To Reproduce**
1. Go to a tv show.
2. Click on the CC button.
3. Click on "Manual"

**Expected behavior**
I expect to find the page with a list of subtitle candidates.

**Medusa (please complete the following information):**
 - OS: ArchLinux
 - Version: 0.3.0

**Logs:**
<details>

```
Traceback (most recent call last):
  File "/usr/lib/pymedusa/medusa/server/web/core/base.py", line 262, in async_call
    result = function(**kwargs)
  File "/usr/lib/pymedusa/medusa/server/web/home/handler.py", line 2099, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/usr/lib/pymedusa/medusa/subtitles.py", line 335, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/usr/lib/pymedusa/ext/dogpile/cache/region.py", line 1030, in set
    self.backend.set(key, self._value(value))
  File "/usr/lib/pymedusa/ext/dogpile/cache/backends/file.py", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/lib/pymedusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/lib/python3.7/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```
</details>

**Comment by p0psicles** [comment]
You switched to py3. You'll have to delete all dbm files in your cache folder

**Comment by Superpiffer** [comment]
I searched the error without find any result, it works now! Thanks!
