### ISSUE TITLE
Error: ReferenceError: atob is not defined (CloudFlare / js2py)

### ISSUE THREAD

**Issue by kavod** [pymedusa/Medusa#6401]
**Describe the bug**
I have just updated to v0.3.1.
During episode search (manual or auto), no result is found and the following message appears on logs:
```
2019-03-21 23:48:56 INFO     SEARCHQUEUE-MANUAL-320766 :: [b34f1df] Unable to find manual results for: The Good Fight - S03E01 - The One About the Recent Troubles
2019-03-21 23:48:56 INFO     SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] Unknown exception in url https://www.yggtorrent.to/engine/search Error: ReferenceError: atob is not defined
2019-03-21 23:48:49 INFO     SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] Performing episode search for The Good Fight
```
I am using yggtorrent as torrent provider.

**Medusa (please complete the following information):**
 - OS: Synology DSM6 ( Linux-3.10.105-armv7l-with-glibc2.4 )
 - Branch: master
 - Commit: b34f1df336e52cf0a690acbc393440ac9f8b3581 
 - Version: 0.3.1

**Logs:** (debug level)
<details>

```
2019-03-21 23:48:56 INFO     SEARCHQUEUE-MANUAL-320766 :: [b34f1df] Unable to find manual results for: The Good Fight - S03E01 - The One About the Recent Troubles
2019-03-21 23:48:56 DEBUG    SEARCHQUEUE-MANUAL-320766 :: [b34f1df] 320766: Formatting pattern: %SN - S%0SE01 - %EN -> The Good Fight - S03E01 - The One About the Recent Troubles
2019-03-21 23:48:56 DEBUG    SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] Found qualities: []
2019-03-21 23:48:56 DEBUG    SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] Found 0 unique items
2019-03-21 23:48:56 DEBUG    SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] No data returned from provider
2019-03-21 23:48:56 DEBUG    SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/session/core.py", line 155, in request
    timeout=timeout, verify=verify, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/session/core.py", line 105, in request
    response = handlers.cloudflare(self, response, timeout=timeout, verify=ssl_cert, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/medusa/session/handlers.py", line 44, in cloudflare
    tokens, user_agent = cfscrape.get_tokens(original_request.url)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/cfscrape/__init__.py", line 159, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/cfscrape/__init__.py", line 71, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/cfscrape/__init__.py", line 103, in solve_cf_challenge
    params["jschl_answer"] = float(js2py.eval_js(js))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/evaljs.py", line 113, in eval_js
    return e.eval(js)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/evaljs.py", line 182, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/evaljs.py", line 177, in execute
    exec(compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/base.py", line 899, in __call__
    return self.call(self.GlobalObject, args)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/base.py", line 1344, in call
    return Js(self.code(*args))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/host/jseval.py", line 42, in Eval
    executor(py_code)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/host/jseval.py", line 49, in executor
    exec(code, globals())
  File "<string>", line 36, in <module>
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/base.py", line 899, in __call__
    return self.call(self.GlobalObject, args)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/base.py", line 1344, in call
    return Js(self.code(*args))
  File "<string>", line 33, in PyJs_anonymous_11_
  File "<string>", line 32, in PyJs_LONG_12_
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/base.py", line 1074, in get
    return self.prototype.get(prop, throw)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/js2py/base.py", line 1079, in get
    raise MakeError('ReferenceError', '%s is not defined' % prop)
JsException: ReferenceError: atob is not defined
2019-03-21 23:48:56 INFO     SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] Unknown exception in url https://www.yggtorrent.to/engine/search Error: ReferenceError: atob is not defined
2019-03-21 23:48:52 DEBUG    SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] CloudFlare protection detected, trying to bypass it
2019-03-21 23:48:52 DEBUG    SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] User-Agent: Medusa/0.3.1 (Linux; 3.10.105; 3eb15b47-4c2b-11e9-a4b9-0011324a6fe7)
2019-03-21 23:48:52 DEBUG    SEARCHQUEUE-MANUAL-320766 :: [Yggtorrent] :: [b34f1df] GET URL: https://www2.yggtorrent.gg/engine/search?category=2145&do=search&name=The+Good+Fight+S03E01 [Status: 503]
```
</details>

**Comment by medariox** [comment]
It's working again.
