### ISSUE TITLE
New install - IPTorrents 

### ISSUE THREAD

**Issue by cproxy** [pymedusa/Medusa#6419]
**Describe the bug**
IndexError: list index out of range
IPTorrents

Manual Snatch, Wanted Snatch - 

**Expected behavior**
Manual Snatch should work

**Medusa (please complete the following information):**

Medusa Info: | Branch: master Commit: b34f1df336e52cf0a690acbc393440ac9f8b3581 Version: 0.3.1 Database: 44.14
Python Version: | 2.7.15 (default, Nov 26 2018, 01:42:21) [GCC 7.3.0]
SSL Version: | OpenSSL 1.0.2r 26 Feb 2019
OS: | Linux-4.14.65-gentoo-whatbox-x86_64-Intel-R-_Xeon-R-_CPU_E5-2697_v4_@_2.30GHz-with-gentoo-2.6
Locale: | en_US.UTF-8

**Logs:**
2019-03-27 21:03:04 ERROR    SNATCHQUEUE-SNATCH-328487 :: [b34f1df] Snatch failed! For result: The.Orville.S02E11.720p.WEB.x264-TBS
Traceback (most recent call last):
  File "/mnt/mpathq/**********/Medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/mnt/mpathq/**********/Medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/mnt/mpathq/**********/Medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/mnt/mpathq/**********/Medusa/medusa/clients/torrent/deluged.py", line 44, in _get_auth
    return True if self.connect() else None
  File "/mnt/mpathq/**********/Medusa/medusa/clients/torrent/deluged.py", line 57, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
</details>

**Additional context**
Recently lost my seedbox and had to reinstall. Not sure what is happening here.

**Comment by medariox** [comment]
Already answered you. You need to write the deluged address like in the example.
