### ISSUE TITLE
Python3 error

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#6464]
**Describe the bug**
This is probably not actually a bug, but more likely operator error on my part.  But I'm running release 0.3.1 and it works fine using python 2.7.15

I also have python 3.7.3 installed and wanted to run it using python3.  When I do I get this error:

```
python3 ./start.py
Traceback (most recent call last):
  File "./start.py", line 8, in <module>
    from medusa.__main__ import main
  File "/opt/Medusa-master/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/opt/Medusa-master/medusa/init/__init__.py", line 34, in initialize
    _urllib3_disable_warnings()
  File "/opt/Medusa-master/medusa/init/__init__.py", line 150, in _urllib3_disable_warnings
    import requests
  File "/opt/Medusa-master/ext/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/opt/Medusa-master/ext/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/opt/Medusa-master/ext/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/opt/Medusa-master/ext/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/opt/Medusa-master/ext/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/opt/Medusa-master/ext/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/opt/Medusa-master/ext/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/opt/Medusa-master/ext/http/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

Any ideas on what the problem could be?

**Comment by bluelavalamp** [comment]
Ok, I solved my own problem.  I found there were a bunch of directories in ext/ that shouldn't be there.  I had to move out:

http
queue
concurrent
xmlrpc
html
_markupbase
socketserver

I'm guessing it's leftover stuff from upgrades.  So, my next question is, how do I keep my current installed/config Medusa but do a clean install of release 0.3.1 so I don't have any leftover bits that shouldn't be there?

Thanks

**Comment by p0psicles** [comment]
Checkout the `Git clean` command

**Comment by bluelavalamp** [comment]
My original install wasn't using git, I downloaded the zip version and installed that way.  So when I run the git command I get:

```
git clean -n https://github.com/pymedusa/Medusa.git /opt/Medusa-master
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by p0psicles** [comment]
I would separate your data folder. And start with a new Git clone.

**Comment by bluelavalamp** [comment]
That worked perfect, thank you!
