### ISSUE TITLE
Medusa can't snatch Deluge

### ISSUE THREAD

**Issue by barukh27** [pymedusa/Medusa#6465]
**Describe the bug**
Deluge can't snatch torrents from Medusa.

**Expected behavior**
I expect to automatically snatch episodes.

**Medusa (please complete the following information):**
 - OS: Linux-4.14.78-4-osmc-armv7l-with-debian-9.8
 - Branch: master
 - Commit: b34f1df336e52cf0a690acbc393440ac9f8b3581
- Python version: 3.5.3 (default, Sep 27 2018, 17:25:39)  [GCC 6.3.0 20170516]
- Locale: en_US.UTF-8

**Logs:**
2019-04-03 21:00:45 ERROR    SNATCHQUEUE-SNATCH-289079 :: [b34f1df] Snatch failed! For result: XXXXXX
Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/opt/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/opt/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/opt/medusa/medusa/clients/torrent/deluged.py", line 44, in _get_auth
    return True if self.connect() else None
  File "/opt/medusa/medusa/clients/torrent/deluged.py", line 57, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range

**Additional context**
I hope you can help me. Thanks!

**Comment by medariox** [comment]
You just need to enter the address like shown in the example `IP or Hostname of your Deluge Daemon (e.g. scgi://localhost:58846)`.

**Comment by barukh27** [comment]
> 
> 
> You just need to enter the address like shown in the example `IP or Hostname of your Deluge Daemon (e.g. scgi://localhost:58846)`.

That's something already done. I checked the connection and it works. Any other hint?

**Comment by medariox** [comment]
That is the reason of the error. There is nothing more to add.

**Comment by barukh27** [comment]
Excuse me medariox,

You are mistaken, that's not the reason for the error. Form the beginning I configured the address and it didn't work.

**Comment by andystevo** [comment]
I receive this same error even though in Search Settings a Test Connection returns: Success: Connected and Authenticated. Haven't found a solution yet.

**Comment by barukh27** [comment]
2019-04-03 21:21:00 ERROR    SNATCHQUEUE-SNATCH-289079 :: [b34f1df] Snatch failed! For result: XXXXXX
Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/opt/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/opt/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/opt/medusa/medusa/clients/torrent/deluged.py", line 44, in _get_auth
    return True if self.connect() else None
  File "/opt/medusa/medusa/clients/torrent/deluged.py", line 57, in connect
    self.drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range

**Comment by medariox** [comment]
Post a screen shot of how you have it configured.

**Comment by barukh27** [comment]
Here you have.
![Config](https://user-images.githubusercontent.com/49249214/55507707-8893a900-5658-11e9-9280-e852e5c77c5f.PNG)

**Comment by medariox** [comment]
You need to add the scgi:// before it LIKE in the example!

**Comment by barukh27** [comment]
Thanks!
 I had have the same configuration without scgi: for ages without any issues and I gave the configuration for granted.

Thank you for your time again. Excuse my misreading.

Problem solved :)

**Comment by medariox** [comment]
You are welcome! I expected it, you are not the first one having this issue.
