### ISSUE TITLE
Torrentleech Backlog Issues

### ISSUE THREAD

**Issue by maticks81** [pymedusa/Medusa#6474]
Seeing the below errors in a backlog since last update.
Backlong function no longer works.

2019-04-06 20:32:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [94fae84] DB error: InterfaceError('Error binding parameter 12 - probably unsupported type.',)
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
InterfaceError: Error binding parameter 12 - probably unsupported type.
2019-04-06 20:32:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [94fae84] DailySearchQueueItem Exception, error: Error binding parameter 12 - probably unsupported type.
Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 263, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/opt/medusa/medusa/search/core.py", line 524, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "/opt/medusa/medusa/tv/cache.py", line 244, in update_cache
    cache_db_con.mass_action(results)
  File "/opt/medusa/medusa/db.py", line 222, in mass_action
    sql_results.append(self._execute(qu[0], qu[1], fetchall=fetchall))
  File "/opt/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
InterfaceError: Error binding parameter 12 - probably unsupported type.

**Comment by medariox** [comment]
You need to post a relevant debug log like it is stated in the issue template.
