### ISSUE TITLE
Move errors

### ISSUE THREAD

**Issue by elpedriyo** [pymedusa/Medusa#6478]
Hello,

Does anyone why am I receiving this errors?

```
2019-04-07 17:32:42 ERROR    TORNADO :: [b34f1df] Unable to move file /mnt/media/descargas_completadas/American Gods - Temporada 2 [HDTV 720p][Cap.202][AC3 5.1 Castellano][www.pctnew.com]/American Gods - Temporada 2 [HDTV 720p][Cap.202][AC3 5.1 Castellano][www.pctnew.com].mkv to /home/pedro/series_gd/American Gods/American Gods - 2x02 - El cautivador.mkv: IOError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/opt/medusa/medusa/post_processor.py", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/opt/medusa/medusa/helpers/__init__.py", line 312, in move_file
    shutil.move(src_file, dest_file)
  File "/opt/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/medusa/lib/shutil_custom/__init__.py", line 37, in copyfile_custom
    fdst.write(buf)
IOError: [Errno 9] Bad file descriptor
2019-04-07 17:32:36 ERROR    TORNADO :: [b34f1df] Unable to move file /mnt/media/descargas_completadas/American Gods - Temporada 2 [HDTV 720p][Cap.203][AC3 5.1 Castellano][www.pctnew.com]/American Gods - Temporada 2 [HDTV 720p][Cap.203][AC3 5.1 Castellano][www.pctnew.com].mkv to /home/pedro/series_gd/American Gods/American Gods - 2x03 - Munninn.mkv: IOError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/opt/medusa/medusa/post_processor.py", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/opt/medusa/medusa/helpers/__init__.py", line 312, in move_file
    shutil.move(src_file, dest_file)
  File "/opt/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/medusa/lib/shutil_custom/__init__.py", line 37, in copyfile_custom
    fdst.write(buf)
IOError: [Errno 9] Bad file descriptor
2019-04-07 17:32:30 ERROR    TORNADO :: [b34f1df] Unable to move file /mnt/media/descargas_completadas/Osmosis - Temporada 1 [HDTV 720p][Cap.101_104][AC3 5.1 Castellano][www.pctnew.com]/Osmosis - Temporada 1 [HDTV 720p][Cap.103][AC3 5.1 Castellano][www.pctnew.com].mkv to /home/pedro/series_gd/Osmosis/Osmosis - 1x03 - Episodio 3.mkv: IOError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/opt/medusa/medusa/post_processor.py", line 472, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/opt/medusa/medusa/helpers/__init__.py", line 312, in move_file
    shutil.move(src_file, dest_file)
  File "/opt/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/medusa/lib/shutil_custom/__init__.py", line 37, in copyfile_custom
    fdst.write(buf)
IOError: [Errno 9] Bad file descriptor
```

Kind regards

**Comment by medariox** [comment]
See https://stackoverflow.com/questions/7686275/what-can-lead-to-ioerror-errno-9-bad-file-descriptor-during-os-system

We can't do anything from our side.
