### ISSUE TITLE
No download anything

### ISSUE THREAD

**Issue by d3xt3repg** [pymedusa/Medusa#6496]
**Describe the bug**
No download transmission
Hello, first congratulations for your work, I do not know what happens but it does not download anything, I have changed the torrent client and it happens the same. I am sorry for my english.
Thz

**Medusa (please complete the following information):**
 - OS: coreelec
 - Branch: 
 - Commit: 

**Logs:**
<details>

```
<-- Please replace this whole line with your logs -->
2019-04-12 02:36:13 ERROR    SNATCHQUEUE-SNATCH-253463 :: [b34f1df] Snatch failed! For result: Black.Mirror.S03E04.WEBRip.x264-RARBG
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/clients/torrent/transmission.py", line 67, in _get_auth
    verify=app.TORRENT_VERIFY_CERT)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/session/core.py", line 103, in request
    timeout=timeout, verify=ssl_cert, **kwargs)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'transmission/rpc': No schema supplied. Perhaps you meant http://transmission/rpc?
2019-04-12 02:36:13 INFO     SNATCHQUEUE-SNATCH-253463 :: [b34f1df] Downloading Black.Mirror.S03E04.WEBRip.x264-RARBG with 1 seeders and 0 leechers and size 534.00 MB from Torrentz2, through a SearchType.MANUAL_SEARCH search
2019-04-12 02:36:13 INFO     SNATCHQUEUE-SNATCH-253463 :: [b34f1df] Beginning to snatch release: Black.Mirror.S03E04.WEBRip.x264-RARBG
2019-04-12 02:36:10 ERROR    SNATCHQUEUE-SNATCH-253463 :: [b34f1df] Snatch failed! For result: Black.Mirror.S03E04.2160p.NF.WEBRip.DD5.1.x264-FGT
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/clients/torrent/transmission.py", line 67, in _get_auth
    verify=app.TORRENT_VERIFY_CERT)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/session/core.py", line 103, in request
    timeout=timeout, verify=ssl_cert, **kwargs)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'transmission/rpc': No schema supplied. Perhaps you meant http://transmission/rpc?
2019-04-12 02:36:10 INFO     SNATCHQUEUE-SNATCH-253463 :: [b34f1df] Downloading Black.Mirror.S03E04.2160p.NF.WEBRip.DD5.1.x264-FGT with 1 seeders and 0 leechers and size 10.00 MB from Torrentz2, through a SearchType.MANUAL_SEARCH search
2019-04-12 02:36:10 INFO     SNATCHQUEUE-SNATCH-253463 :: [b34f1df] Beginning to snatch release: Black.Mirror.S03E04.2160p.NF.WEBRip.DD5.1.x264-FGT
2019-04-12 02:35:59 INFO     SEARCHQUEUE-MANUAL-253463 :: [LimeTorrents] :: [b34f1df] Performing episode search for Black Mirror
2019-04-12 02:35:58 INFO     SEARCHQUEUE-MANUAL-253463 :: [Nyaa] :: [b34f1df] Performing episode search for Black Mirror
2019-04-12 02:35:58 INFO     SEARCHQUEUE-MANUAL-253463 :: [ThePirateBay] :: [b34f1df] Performing episode search for Black Mirror
2019-04-12 02:35:58 INFO     SEARCHQUEUE-MANUAL-253463 :: [TNTVillage] :: [b34f1df] Performing episode search for Black Mirror
2019-04-12 02:35:49 INFO     SEARCHQUEUE-MANUAL-253463 :: [Torrentz2] :: [b34f1df] Performing episode search for Black Mirror
2019-04-12 02:35:49 INFO     SEARCHQUEUE-MANUAL-253463 :: [b34f1df] Using manual search providers
2019-04-12 02:35:49 INFO     SEARCHQUEUE-MANUAL-253463 :: [b34f1df] Building internal name cache for Black Mirror
2019-04-12 02:35:49 INFO     SEARCHQUEUE-MANUAL-253463 :: [b34f1df] Finished processing 2967 scene exceptions.
2019-04-12 02:35:48 INFO     SEARCHQUEUE-MANUAL-253463 :: [b34f1df] Updating exception_cache and exception_season_cache
2019-04-12 02:35:48 INFO     SEARCHQUEUE-MANUAL-253463 :: [b34f1df] Beginning manual search for: Black Mirror - S03E04 - San Junipero
2019-04-12 02:26:37 ERROR    SNATCHQUEUE-SNATCH-253463 :: [b34f1df] Snatch failed! For result: Black.Mirror.S04E06.WEBRip.x264-RARBG
Traceback (most recent call last):
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/clients/torrent/transmission.py", line 67, in _get_auth
    verify=app.TORRENT_VERIFY_CERT)
  File "/storage/.kodi/addons/service.medusa/medusa/ext/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/storage/.kodi/addons/service.medusa/medusa/medusa/session/core.py", line 103, in request
    timeout=timeout, verify=ssl_cert, **kwargs)``
</details>

**Comment by medariox** [comment]
Setup your client (Transmission?) properly. Post screenshots of what you have now to get further help.

**Comment by d3xt3repg** [comment]
<a href="https://ibb.co/S6RtYDM"><img src="https://i.ibb.co/YNpcn41/transmission.png" alt="transmission" border="0"></a>
thanks for answering

**Comment by medariox** [comment]
Missing http:// before the IP

**Comment by d3xt3repg** [comment]
now YES, I'm ashamed that it was that idiocy
thank you very much friend
