### ISSUE TITLE
[APP SUBMITTED]: ImportError: No module named _bsddb

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#6518]
### INFO
**Python Version**: `2.7.10 (default, Feb 22 2019, 21:17:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]`
**Operating System**: `Darwin-18.5.0-x86_64-i386-64bit`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a161686d0217f3d4b1a011c73925d9a7a671179
**Link to Log**: https://gist.github.com/9dd8a0c0002b7fc4fa6b08841045de36
### ERROR
<pre>
2019-04-15 21:55:32 ERROR    Thread_3 :: [9a16168] Exception generated: No module named _bsddb
Traceback (most recent call last):
  File "/Applications/Medusa/<a href="../blob/9a161686d0217f3d4b1a011c73925d9a7a671179/medusa/server/web/core/base.py#L262">medusa/server/web/core/base.py</a>", line 262, in async_call
    result = function(**kwargs)
  File "/Applications/Medusa/<a href="../blob/9a161686d0217f3d4b1a011c73925d9a7a671179/medusa/server/web/home/handler.py#L2099">medusa/server/web/home/handler.py</a>", line 2099, in manual_search_subtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/Applications/Medusa/<a href="../blob/9a161686d0217f3d4b1a011c73925d9a7a671179/medusa/subtitles.py#L334">medusa/subtitles.py</a>", line 334, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/Applications/Medusa/<a href="../blob/9a161686d0217f3d4b1a011c73925d9a7a671179/ext/dogpile/cache/region.py#L1030">ext/dogpile/cache/region.py</a>", line 1030, in set
    self.backend.set(key, self._value(value))
  File "/Applications/Medusa/<a href="../blob/9a161686d0217f3d4b1a011c73925d9a7a671179/ext/dogpile/cache/backends/file.py#L237">ext/dogpile/cache/backends/file.py</a>", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/Applications/Medusa/<a href="../blob/9a161686d0217f3d4b1a011c73925d9a7a671179/ext/dogpile/cache/backends/file.py#L215">ext/dogpile/cache/backends/file.py</a>", line 215, in _dbm_file
    "w" if write else "r")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Your Python install is not compiled properly, as it should have working bsddb out of the box. You can try installing bsddb with pip by running `pip install bsddb3`. Alternatively you can compile an up to date Python version yourself from source.

**Comment by NicoLeOca** [comment]
@medariox thanks for your support
pip install bsddb3 didn't work
but for some reasons I don't have this error anymore.
I close the issue until it comes back
thanks
