### ISSUE TITLE
[APP SUBMITTED]: IOError: [Errno 13] Permission denied: '/mounts/tv1/Wisting/Season 01/Wisting - S01E04 - Episode 4 1080p.WEB-DL -WEEDPOT.mkv'

### ISSUE THREAD

**Issue by ztaale** [pymedusa/Medusa#6612]
### INFO
**Python Version**: `2.7.15 (default, Jan 24 2019, 16:32:39) [GCC 8.2.0]`
**Operating System**: `Linux-4.15.0-47-generic-x86_64-with`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/affc0436a43c34a9bde7db96975561aa
### ERROR
<pre>
2019-04-26 18:40:26 ERROR    POSTPROCESSOR :: [] Unable to copy file /mounts/torrent/finished/tv/Wisting.S01E04.NORDIC.1080p.WEB-DL.H.264-WEEDPOT/Wisting.S01E04.NORDIC.1080p.WEB-DL.H.264-WEEDPOT.mkv to /mounts/tv1/Wisting/Season 01/Wisting - S01E04 - Episode 4 1080p.WEB-DL -WEEDPOT.mkv: IOError(13, 'Permission denied')
Traceback (most recent call last):
  File "/app/medusa/medusa/post_processor.py", line 482, in copy
    helpers.copy_file(cur_file_path, new_file_path)
  File "/app/medusa/medusa/helpers/__init__.py", line 285, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/app/medusa/lib/shutil_custom/__init__.py", line 32, in copyfile_custom
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
  File "/app/medusa/medusa/init/filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
IOError: [Errno 13] Permission denied: '/mounts/tv1/Wisting/Season 01/Wisting - S01E04 - Episode 4 1080p.WEB-DL -WEEDPOT.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by IDerr** [comment]
@ztaale I don't think this is an issue related to Medusa. Seems like an error on the destination folder or on your file. Check your permissions :)
