### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes' when rescanning files.

### ISSUE THREAD

**Issue by GAZ082** [pymedusa/Medusa#6616]
**Describe the bug**

**To Reproduce**
1. Go to the show.
2. Hit rescan files.

**Expected behavior**
Files detected.

**Screenshots**

**Medusa (please complete the following information):**
- Pi3 with raspbian: linux kraken 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
 - Branch: master
 - Commit: f46bfacf8763204fbde4f26a5916095371d494d1

**Logs:**
<details>

```
2019-04-27 17:18:23 ERROR    SHOWQUEUE-REFRESH :: [f46bfac] 80379: Error while refreshing show The Big Bang Theory. Error: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/opt/medusa/medusa/show_queue.py", line 688, in run
    self.show.refresh_dir()
  File "/opt/medusa/medusa/tv/series.py", line 1792, in refresh_dir
    self.load_episodes_from_dir()
  File "/opt/medusa/medusa/tv/series.py", line 1053, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/opt/medusa/medusa/tv/series.py", line 1397, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/opt/medusa/medusa/tv/episode.py", line 2031, in update_status_quality
    new_quality = Quality.name_quality(filepath, self.series.is_anime)
  File "/opt/medusa/medusa/common.py", line 283, in name_quality
    return Quality._extend_quality(name)
  File "/opt/medusa/medusa/common.py", line 382, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/opt/medusa/medusa/common.py", line 403, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/opt/medusa/ext/knowit/api.py", line 49, in know
    return provider.describe(video_path, context)
  File "/opt/medusa/ext/knowit/providers/ffmpeg.py", line 214, in describe
    data = self.executor.extract_info(video_path)
  File "/opt/medusa/ext/knowit/providers/ffmpeg.py", line 77, in extract_info
    return json.loads(json_dump)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
2019-04-27 17:15:56 ERROR    SHOWQUEUE-REFRESH :: [f46bfac] 121361: Error while refreshing show Game of Thrones. Error: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/opt/medusa/medusa/show_queue.py", line 688, in run
    self.show.refresh_dir()
  File "/opt/medusa/medusa/tv/series.py", line 1792, in refresh_dir
    self.load_episodes_from_dir()
  File "/opt/medusa/medusa/tv/series.py", line 1053, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/opt/medusa/medusa/tv/series.py", line 1397, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/opt/medusa/medusa/tv/episode.py", line 2031, in update_status_quality
    new_quality = Quality.name_quality(filepath, self.series.is_anime)
  File "/opt/medusa/medusa/common.py", line 283, in name_quality
    return Quality._extend_quality(name)
  File "/opt/medusa/medusa/common.py", line 382, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/opt/medusa/medusa/common.py", line 403, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/opt/medusa/ext/knowit/api.py", line 49, in know
    return provider.describe(video_path, context)
  File "/opt/medusa/ext/knowit/providers/ffmpeg.py", line 214, in describe
    data = self.executor.extract_info(video_path)
  File "/opt/medusa/ext/knowit/providers/ffmpeg.py", line 77, in extract_info
    return json.loads(json_dump)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
</details>

**Additional context**

**Comment by medariox** [comment]
This looks like a knowit bug to me. Can you open the issue over there please?

**Comment by GAZ082** [comment]
I will and report back. Thanks @medariox
