### ISSUE TITLE
Archive in backlog

### ISSUE THREAD

**Issue by mrdeadlocked** [pymedusa/Medusa#6627]
Error when trying to archive episodes on the backlog page.

2019-04-30 16:26:04 ERROR    Thread_24 :: [f46bfac] Exception generated: need more than 1 value to unpack
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 262, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/handler.py", line 1770, in setStatus
    season_no, episode_no = cur_ep.lstrip('s').split('e')
ValueError: need more than 1 value to unpack
2019-04-30 16:26:04 DEBUG    Thread_24 :: [f46bfac] Attempting to set status for episode Adventure Time 10x4 to 6

**Comment by medariox** [comment]
Thanks for the bug report. Next time please use the issue template.
Fixed with: https://github.com/pymedusa/Medusa/pull/6636
