### ISSUE TITLE
Core Dumping During Unpacking

### ISSUE THREAD

**Issue by jefferymcjefferson** [pymedusa/Medusa#6684]
**Describe the bug**
Medusa logs that it is unable to unpack an archive. I believe that is causing the core dumps to occur. This ends up filling my 20 GB drive provisioned for this container to work with; normally consuming ~300 MB.

**To Reproduce**
1. Mount /srv/data via autofs to a remote host, accessible across a VPN (#6683).
2. Execute the docker container `docker run -d --name=medusa -v /etc/opt/medusa/config:/config -v /etc/opt/medusa/downloads:/downloads -v /srv/samba/TV\ Shows/:/tv -v /srv/data/.rtorrent/watch_medusa:/torrentdir -v /srv/data/completed/ -e PGID=1000 -e PUID=1000 --restart=unless-stopped --security-opt="label=disable" -e http_proxy="http://192.168.1.136:3128" linuxserver/medusa`
3. Wait a few days. A lot of core dumps will be present.

**Expected behavior**
Core dumps not fill up the drive.

**Medusa (please complete the following information):**
 - OS: CentOS 7
 - Branch: master
 - Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76

**Logs:**

Here's the last log data before the space issue occurs from the frequent core dumps.

```
2019-04-29 03:13:04 INFO     SEARCHQUEUE-DAILY-SEARCH :: [918cfe7] Beginning daily search for new episodes
2019-04-29 03:13:08 INFO     SEARCHQUEUE-DAILY-SEARCH :: [918cfe7] Using daily search providers
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E01.GERMAN.DL.DUBBED.1080p.WEB.h264-OMGtv is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Ignoring Game.of.Thrones.S08E01.GERMAN.DL.DUBBED.1080p.WEB.h264-OMGtv based on ignored words filter: german
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E01.Kings.Landing.1080p.AMZN.WEB-DL.DDP5.1.H.264-GoT is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E01.1080p.AMZN.WEB-DL.DD+.5.1.H.264-GoT is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E01.1080p.WEB.H264-MEMENTO is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E01.GERMAN.DL.1080p.HDTV.x264.PROPER-MDGP is 1080p HDTV
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Ignoring Game.of.Thrones.S08E01.GERMAN.DL.1080p.HDTV.x264.PROPER-MDGP based on ignored words filter: german
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E01.GERMAN.DL.DUBBED.1080p.WEB.h264.REPACK-OMGtv is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Ignoring Game.of.Thrones.S08E01.GERMAN.DL.DUBBED.1080p.WEB.h264.REPACK-OMGtv based on ignored words filter: german
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E01.MULTi.1080p.HDTV.H264-HYBRiS is 1080p HDTV
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Picked Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO as the best result.
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E03.1080p.AMZN.WEB-DL.DDP5.1.H.264-GoT is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Game.of.Thrones.S08E03.1080p.AMZN.WEB-DL.DD+.5.1.H.264-GoT is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Picked Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO as the best result.
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb is 1080p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Modern.Family.S09E21.The.Escape.720p.AMZN.WEBRip.DDP5.1.X264-NTb is 720p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Modern.Family.S09E21.iNTERNAL.720p.WEB.x264-BAMBOOZLE is 720p WEB-DL
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Modern.Family.S09E21.720p.HDTV.x264-AVS is 720p HDTV
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Quality of Modern.Family.S09E21.HDTV.x264-SVA is SDTV
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: [918cfe7] Picked Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb as the best result.
2019-04-29 03:13:22 INFO     SEARCHQUEUE-DAILY-SEARCH :: [918cfe7] Downloading Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO with 1555 seeders and 275 leechers and size 3.18 GB from TorrentLeech
2019-04-29 03:13:24 INFO     SEARCHQUEUE-DAILY-SEARCH :: [918cfe7] Downloading Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO with 2429 seeders and 462 leechers and size 4.93 GB from TorrentLeech
2019-04-29 03:13:25 INFO     SNATCHQUEUE-SNATCH-121361 :: [918cfe7] Beginning to snatch release: Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO
2019-04-29 03:13:25 INFO     SNATCHQUEUE-SNATCH-121361 :: [918cfe7] Downloading Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO with 1555 seeders and 275 leechers and size 3.18 GB from TorrentLeech, through a SearchType.DAILY_SEARCH search
2019-04-29 03:13:25 INFO     SNATCHQUEUE-SNATCH-121361 :: [918cfe7] Downloading Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO from TorrentLeech at https://www.torrentleech.org/download/1315803/Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO.torrent
2019-04-29 03:13:26 INFO     SNATCHQUEUE-SNATCH-121361 :: [918cfe7] Saved Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO to /torrentdir/Game.of.Thrones.S08E01.REPACK.1080p.WEB.H264-MEMENTO.torrent
2019-04-29 03:13:26 INFO     SEARCHQUEUE-DAILY-SEARCH :: [918cfe7] Downloading Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb with 31 seeders and 1 leechers and size 2.03 GB from TorrentLeech
2019-04-29 03:13:31 INFO     SNATCHQUEUE-SNATCH-121361 :: [918cfe7] Beginning to snatch release: Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO
2019-04-29 03:13:31 INFO     SNATCHQUEUE-SNATCH-121361 :: [918cfe7] Downloading Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO with 2429 seeders and 462 leechers and size 4.93 GB from TorrentLeech, through a SearchType.DAILY_SEARCH search
2019-04-29 03:13:31 INFO     SNATCHQUEUE-SNATCH-121361 :: [918cfe7] Downloading Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO from TorrentLeech at https://www.torrentleech.org/download/1327270/Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO.torrent
2019-04-29 03:13:32 INFO     SNATCHQUEUE-SNATCH-121361 :: [918cfe7] Saved Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO to /torrentdir/Game.of.Thrones.S08E03.1080p.WEB.H264-MEMENTO.torrent
2019-04-29 03:13:43 INFO     SNATCHQUEUE-SNATCH-95011 :: [918cfe7] Beginning to snatch release: Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2019-04-29 03:13:43 INFO     SNATCHQUEUE-SNATCH-95011 :: [918cfe7] Downloading Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb with 31 seeders and 1 leechers and size 2.03 GB from TorrentLeech, through a SearchType.DAILY_SEARCH search
2019-04-29 03:13:43 INFO     SNATCHQUEUE-SNATCH-95011 :: [918cfe7] Downloading Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb from TorrentLeech at https://www.torrentleech.org/download/1078721/Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.torrent
2019-04-29 03:13:44 INFO     SNATCHQUEUE-SNATCH-95011 :: [918cfe7] Saved Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb to /torrentdir/Modern.Family.S09E21.The.Escape.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.torrent
2019-04-29 03:14:53 WARNING  POSTPROCESSOR :: [918cfe7] Failed unpacking archive South.Park.S05E01.720p.BluRay.X264-REWARD.rar:
2019-04-29 03:16:25 WARNING  POSTPROCESSOR :: [918cfe7] Failed unpacking archive south.park.s05e10.720p.bluray.x264-reward.rar:
2019-04-29 03:16:53 WARNING  POSTPROCESSOR :: [918cfe7] Failed unpacking archive South.Park.S09E02.720p.BluRay.X264-REWARD.rar:
2019-04-29 03:18:25 WARNING  SHOWQUEUE-REFRESH :: [918cfe7] DB error: OperationalError('unable to open database file',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    stream.write(ufs % msg)
  File "/usr/lib/python2.7/codecs.py", line 708, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 370, in write
    self.stream.write(data)
IOError: [Errno 28] No space left on device
Logged from file __init__.py, line 732
2019-04-29 03:18:25 WARNING  POSTPROCESSOR :: [918cfe7] Failed unpacking archive South.Park.S07E06.720p.BluRay.X264-REWARD.rar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    stream.write(ufs % msg)
  File "/usr/lib/python2.7/codecs.py", line 708, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 370, in write
    self.stream.write(data)
IOError: [Errno 28] No space left on device
Logged from file __init__.py, line 732
2019-04-29 03:18:26 WARNING  SHOWQUEUE-REFRESH :: [918cfe7] DB error: OperationalError('unable to open database file',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 879, in emit
    stream.write(ufs % msg)
  File "/usr/lib/python2.7/codecs.py", line 708, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 370, in write
    self.stream.write(data)
IOError: [Errno 28] No space left on device
Logged from file __init__.py, line 732
```

**Additional context**
I'm very aware that having this communication running across a VPN link is definitely not optimal. However, the VPN is relatively stable, and the internet at the Medusa location is pretty good, but the seedbox connectivity is way, way better.

Not having core dumps generated would be a great solution.

`/tmp/core.15069: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'python /app/medusa/start.py --nolaunch --datadir /config', real uid: 1000, effective uid: 1000, real gid: 1000, effective gid: 1000
`

**Comment by medariox** [comment]
How do you come to the conclusion that Medusa is causing this?

**Comment by nine13tech** [comment]
Core dumps are a function of the OS, not Medusa. You will want to turn them off there.
For all users which include root and the system:
```# vi /etc/security/limits.conf```
add or edit the following directive:
```* hard core 0```
That sets the hard limit of core dumps to 0. Next you must set a 0 limit on the userspace so they can't expand it outside this setting:
```# echo 'fs.suid_dumpable = 0' >> /etc/sysctl.conf```
```# sysctl -p```
Finally, stop the core dumps from being created.
```# echo 'ulimit -S -c 0 > /dev/null 2>&1' >> /etc/profile```
Best of luck.
