### ISSUE TITLE
OpenSubtitlesError: 408 Invalid parameters; episode is not number

### ISSUE THREAD

**Issue by Thilas** [pymedusa/Medusa#6698]
Search for subtitles on multi-episode doesn't seem to be supported correctly with OpenSubtitles because the subliminal provider is sending a list of episode numbers whereas OpenSubtitles expects a single one.

This looks like the same issue as #3695 but it has been closed a year ago without any comment.

Looking at subliminal's repository, this topic has been discussed for instance in https://github.com/Diaoul/subliminal/issues/858. And the actual cause has been reverted in order to fix this (https://github.com/Diaoul/subliminal/pull/885).

But it seems that Medusa's copy of subliminal already has these changes.

Any ideas? If needed, I can try working on it and propose a pull request.

**Medusa (please complete the following information):**
 - OS: Linux-4.4.59+-x86_64-with
 - Branch: master
 - Commit: 0625bc20e77046c8c7d9581a7d3f816eb7203826

**Logs:**
<details>

```
2019-05-19 13:50:49 WARNING  Thread_9 :: [0625bc2] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "/app/medusa/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/app/medusa/ext/subliminal/providers/opensubtitles.py", line 228, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "/app/medusa/ext/subliminal/providers/opensubtitles.py", line 183, in query
    response = checked(self.server.SearchSubtitles(self.token, criteria))
  File "/app/medusa/ext/subliminal/providers/opensubtitles.py", line 295, in checked
    raise OpenSubtitlesError(response['status'])
OpenSubtitlesError: 408 Invalid parameters; episode is not number
2019-05-19 13:50:49 DEBUG    Thread_9 :: [0625bc2] Searching subtitles [{'moviebytesize': '1137044374', 'sublanguageid': u'eng,fre', 'moviehash': 'cbf88087c9d36375'}, {'sublanguageid': u'eng,fre', 'tag': u'The.Big.Bang.Theory.S12E23-E24.The.Change.Constant.and.The.Stockholm.Syndrome.720p.HDTV-AVS.mkv'}, {'query': u'The Big Bang Theory', 'sublanguageid': u'eng,fre', 'episode': [23, 24], 'season': 12}]
```
</details>

**Comment by medariox** [comment]
Fixed.
