### ISSUE TITLE
Cannot add new shows

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#6713]
Branch: master Commit: f46bfacf8763204fbde4f26a5916095371d494d1 Version: 0.3.1 Database: 44.14
--
Python Version: | 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Linux-4.14.66+-armv7l-with-debian-9.9
Locale: | en_GB.UTF-8

Tried to add new show using the three indexers, ended up with empty directory and the show not in the database. Everything else works. New install on Odroid XU4 with dietpi Debian variant using configs backed up from old install and restored to new install.

Excerpts from log:

2019-05-22 16:47:56 INFO     SHOWQUEUE-ADD :: [f46bfac] Setting all previously aired episodes to the specified status: Wanted
2019-05-22 16:47:53 INFO     SHOWQUEUE-ADD :: [f46bfac] 79410: Unable to find the show in the database
2019-05-22 16:47:47 INFO     SHOWQUEUE-ADD :: [f46bfac] TMDB: {u'session': <medusa.session.core.MedusaSession object at 0xaf3e4730>, u'cache': u'/mnt/dietpi_userdata/medusa/cache/indexers/TMDB', u'language': u'en', u'use_zip': True}
2019-05-22 16:47:47 INFO     SHOWQUEUE-ADD :: [f46bfac] Starting to add show by ShowDir: /mnt/usb_2/tv/After Life

2019-05-22 16:51:07 WARNING  SHOWQUEUE-ADD :: [f46bfac] 363205: Error while loading information from indexer TVDBv2. Error: Show episode search exception, could not get any episodes. Did a full search. Exception: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/363205/episodes/query?page=1
2019-05-22 16:51:06 INFO     SHOWQUEUE-ADD :: [f46bfac] TVDBv2: {u'session': <medusa.session.core.MedusaSession object at 0xaf439d50>, u'cache': u'/mnt/dietpi_userdata/medusa/cache/indexers/TVDBv2', u'language': u'en', u'use_zip': True}
2019-05-22 16:51:06 INFO     SHOWQUEUE-ADD :: [f46bfac] Starting to add show by ShowDir: /mnt/usb_2/media/tv/After Life

2019-05-22 17:06:17 INFO     SHOWQUEUE-ADD :: [f46bfac] TVmaze: {u'session': <medusa.session.core.MedusaSession object at 0xaf447c10>, u'cache': u'/mnt/dietpi_userdata/medusa/cache/indexers/TVmaze', u'language': u'en', u'use_zip': True}
2019-05-22 17:06:17 INFO     SHOWQUEUE-ADD :: [f46bfac] Starting to add show by ShowDir: /mnt/usb_2/media/tv/After Life

**Comment by medariox** [comment]
Sounds like you are being being rate limited or the TVDB API was temporarily offline. Enable tornado logging for more detailed information.

**Comment by johnvick** [comment]
I had wondered about that so tried the other indexers with the same result.

But his has just appeared in the log:

2019-05-22 21:06:37 ERROR    DAILYSEARCHER :: [f46bfac] Exception generated: attempt to write a readonly database
Traceback (most recent call last):
  File "/home/john/medusa/medusa/scheduler.py", line 93, in run
  File "/home/john/medusa/medusa/search/daily.py", line 137, in run
  File "/home/john/medusa/medusa/db.py", line 222, in mass_action
  File "/home/john/medusa/medusa/db.py", line 115, in _execute
OperationalError: attempt to write a readonly database
2019-05-22 21:06:37 ERROR    DAILYSEARCHER :: [f46bfac] DB error: OperationalError('attempt to write a readonly database',)
Traceback (most recent call last):
  File "/home/john/medusa/medusa/db.py", line 115, in _execute
OperationalError: attempt to write a readonly database
2019-05-22 21:06:37 ERROR    DAILYSEARCHER :: [f46bfac] DB error: Error: 'attempt to write a readonly database'
Traceback (most recent call last):
  File "/home/john/medusa/medusa/db.py", line 222, in mass_action
  File "/home/john/medusa/medusa/db.py", line 115, in _execute
OperationalError: attempt to write a readonly database

I am sure the permissions were correct but have reset them to what they should, restarted medusa and tried again. This was in the logs:

2019-05-22 22:26:44 WARNING  SHOWQUEUE-ADD :: [f46bfac] 363205: Error while loading information from indexer TVDBv2. Error: Show episode search exception, could not get any episodes. Did a full search. Exception: HTTPError
404 Client Error: Not Found for url: https://api.thetvdb.com/series/363205/episodes/query?page=1

I've set tornado to log and will see what happens in the morning.

Thanks for the help.

**Comment by sharkykh** [comment]
The show has no seasons, and therefore no episodes.
The 404 is correct, the handling of it isn't.

**Comment by johnvick** [comment]
Thanks for your reply but I'm not sure what you mean? I tried Whiskey Cavalier and got the same result i.e. an empty folder, no metadata and the series not in the medusa database. Could this have anything to do with the database previously having been used with medusa under python 3.7 and now I'm on a new install using python 2.7?

**Comment by johnvick** [comment]
I've sorted this out, not sure exactly what the problem was but starting from the very beginning has fixed it.
Thanks for the help.
