### ISSUE TITLE
Exception in `GET /api/v2/alias?type=local`

### ISSUE THREAD

**Issue by sharkykh** [pymedusa/Medusa#6721]
Dredd tests on Python 3.7.3
Branch: `renovate/js/dredd-11.x` (#6668)
```
2019-05-24 07:02:03 ERROR    TORNADO :: [9c29e79] Uncaught exception in APIv2: TypeError("'>=' not supported between instances of 'NoneType' and 'int'")
Request: GET /api/v2/alias?type=local (127.0.0.1)
Traceback (most recent call last):
  File "C:\Dev\Medusa\ext\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Dev\Medusa\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Dev\Medusa\ext\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Dev\Medusa\medusa\server\api\v2\base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Dev\Medusa\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Dev\Medusa\medusa\server\api\v2\alias.py", line 77, in get
    d['season'] = item['season'] if item['season'] >= 0 else None
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
fail: GET (200) /api/v2/alias?type=local duration: 11ms
```

<details>
<summary>More logs</summary>

```
info: Displaying failed tests...
fail: GET (200) /api/v2/alias?type=local duration: 11ms
fail: headers: At '/x-pagination-page' Missing required property: x-pagination-page
headers: At '/x-pagination-limit' Missing required property: x-pagination-limit
headers: At '/x-pagination-count' Missing required property: x-pagination-count
headers: At '/link' Missing required property: link
body: At '' Invalid type: object (expected array)
statusCode: Status code is '500' instead of '200'

request:
method: GET
uri: /api/v2/alias?type=local
headers:
    Content-Type: application/json
    Accept: application/json; charset=UTF-8
    User-Agent: Dredd/11.1.4 (Windows_NT 10.0.17763; x64)
    x-api-key: 1234567890ABCDEF1234567890ABCDEF

body:



expected:
headers:
    Content-Type: application/json; charset=UTF-8
    X-Pagination-Page:
    X-Pagination-Limit:
    X-Pagination-Count:
    Link:

body:
[
  {
    "series": "tvdb301824",
    "name": "TheBig",
    "type": "local"
  }
]
statusCode: 200
bodySchema: {"type":"array","items":{"$ref":"#/definitions/Alias"},"definitions":{"Alias":{"type":"object","properties":{"id":{"type":"integer","minimum":1},"series":{"type":"string"},"name":{"type":"string"},"season":{"type":["integer","null"],"minimum":1},"type":{"type":["string","null"]}},"examples":[{"series":"tvdb301824","name":"TheBig","type":"local"}]}}}


actual:
statusCode: 500
headers:
    server: TornadoServer/5.1.1
    content-type: application/json; charset=UTF-8
    date: Fri, 24 May 2019 04:02:03 GMT
    x-medusa-server: 0.3.1
    access-control-allow-origin: *
    access-control-allow-headers: Origin, Accept, Authorization, Content-Type, X-Requested-With, X-CSRF-Token, X-Api-Key, X-Medusa-Server
    access-control-allow-methods: OPTIONS, GET, POST, PUT, DELETE
    content-length: 34
    vary: Accept-Encoding
    connection: close

bodyEncoding: utf-8
body:
{
  "error": "Internal Server Error"
}
```
</details>

**Comment by sharkykh** [comment]
Fixed with e361be8fc4fcc4d869f20925d6378ad6f17b5167
