### ISSUE TITLE
addic7ed subtitle plugin broken

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#6778]
**Describe the bug**
Medusa is not fetching subtitles from Addic7ed, I've setup Addic7ed with username and password
![image](https://user-images.githubusercontent.com/4103090/58969472-0e96b200-87b8-11e9-8a58-72c99dbbf4ab.png)
![image](https://user-images.githubusercontent.com/4103090/58969515-22421880-87b8-11e9-8f72-9172d1bea135.png)

**Medusa (please complete the following information):**

Medusa Info: | Branch: master Commit: 6a21a6001b10827d14d450135bae61729b01edf1 Version: 0.3.2 Database: 44.14
-- | --
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2o 27 Mar 2018
OS: | Windows-10-10.0.17763
Locale: | nl_NL.cp1252

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-06-05 17:31:22 INFO     Thread_28 :: [6a21a60] Starting to manual searching subtitles
2019-06-05 17:31:22 INFO     Thread_28 :: [6a21a60] Manual searching subtitles for: the.goldbergs.2013.s06e22.1080p.web.h264-tbs
2019-06-05 17:31:22 DEBUG    Thread_28 :: [6a21a60] Found cached video information under key medusa.subtitles:video|C:\DATA\TVSeries\The Goldbergs (2013)\Season 06\The Goldbergs (2013) - S06E22 - Mom Trumps Willow (1080p.WEB-DL.tbs).mkv
2019-06-05 17:31:22 DEBUG    Thread_28 :: [6a21a60] Listing subtitles with provider u'addic7ed' and languages set([<Language [en]>])
2019-06-05 17:31:22 DEBUG    Thread_28 :: [6a21a60] Initializing provider addic7ed
2019-06-05 17:31:22 WARNING  Thread_28 :: [6a21a60] Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\GitHub\Medusa\ext\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\GitHub\Medusa\ext\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\GitHub\Medusa\ext\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: **********
2019-06-05 17:31:22 DEBUG    Thread_28 :: [6a21a60] Discarding provider addic7ed
2019-06-05 17:31:22 DEBUG    Thread_28 :: [6a21a60] Listing subtitles with provider u'thesubdb' and languages set([<Language [en]>])
2019-06-05 17:31:22 DEBUG    Thread_28 :: [6a21a60] Searching subtitles {'action': 'search', 'hash': '3cd31c4a9c1f6601415d375730278bb4'}
2019-06-05 17:31:23 DEBUG    Thread_28 :: [6a21a60] Listing subtitles with provider u'opensubtitles' and languages set([<Language [en]>])
2019-06-05 17:31:23 DEBUG    Thread_28 :: [6a21a60] Searching subtitles [{'moviebytesize': '944493922', 'sublanguageid': u'eng', 'moviehash': '641d5c0fa5c7d660'}, {'sublanguageid': u'eng', 'tag': u'The Goldbergs (2013) - S06E22 - Mom Trumps Willow (1080p.WEB-DL.tbs).mkv'}, {'query': u'The Goldbergs', 'sublanguageid': u'eng', 'episode': 22, 'season': 6}]
2019-06-05 17:31:23 DEBUG    Thread_28 :: [6a21a60] Listing subtitles with provider u'tvsubtitles' and languages set([<Language [en]>])
2019-06-05 17:31:23 DEBUG    Thread_28 :: [6a21a60] Computing score of <OpenSubtitlesSubtitle '1956315670' [en]> for video <Episode [u'The Goldbergs', 2013, 6x22]> with {'hearing_impaired': 0}
2019-06-05 17:31:23 DEBUG    Thread_28 :: [6a21a60] Computed score 333 with final matches set(['episode', 'title', 'series', 'year', 'season', 'video_codec', 'hearing_impaired'])
2019-06-05 17:31:23 DEBUG    Thread_28 :: [6a21a60] Computing score of <OpenSubtitlesSubtitle '1956315675' [en]> for video <Episode [u'The Goldbergs', 2013, 6x22]> with {'hearing_impaired': 0}
2019-06-05 17:31:24 DEBUG    Thread_28 :: [6a21a60] Computed score 332 with final matches set(['episode', 'title', 'series', 'year', 'season', 'video_codec'])
2019-06-05 17:31:24 DEBUG    Thread_28 :: [6a21a60] Computing score of <TVsubtitlesSubtitle '341506' [en]> for video <Episode [u'The Goldbergs', 2013, 6x22]> with {'hearing_impaired': 0}
2019-06-05 17:31:24 DEBUG    Thread_28 :: [6a21a60] Computed score 331 with final matches set(['episode', 'hearing_impaired', 'year', 'series', 'season'])
2019-06-05 17:31:24 DEBUG    Thread_28 :: [6a21a60] Scores computed for release: The Goldbergs (2013) - S06E22 - Mom Trumps Willow (1080p.WEB-DL.tbs).mkv

```
</details>

**Comment by medariox** [comment]
See https://github.com/Diaoul/subliminal/issues/966
There is nothing we can do about it. If it doesn't get fixed by the next release we will remove it altogether.

**Comment by Rouzax** [comment]
Sorry, that makes sense.
