### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by gers1978** [pymedusa/Medusa#6782]
Open the UI to be told I was 136 commits behind.  Clicked "Update" and Medusa wouldn't restart.  Terminal shows:

`
Mac-Mini:~ <me>$ python /Volumes/Macintosh\ HD/Applications/Medusa/SickBeard.py
Traceback (most recent call last):
  File "/Volumes/Macintosh HD/Applications/Medusa/SickBeard.py", line 6, in <module>
    from medusa.__main__ import main
  File "/Applications/Medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/Applications/Medusa/medusa/init/__init__.py", line 37, in initialize
    _monkey_patch_cfscrape()
  File "/Applications/Medusa/medusa/init/__init__.py", line 184, in _monkey_patch_cfscrape
    from medusa.init.cfscrape import patch_cfscrape
  File "/Applications/Medusa/medusa/init/cfscrape.py", line 9, in <module>
    import cfscrape
  File "/Applications/Medusa/ext/cfscrape/__init__.py", line 26, in <module>
    with open(USER_AGENTS_PATH) as f:
IOError: [Errno 2] No such file or directory: u'/Applications/Medusa/ext/cfscrape/user_agents.json'
Mac-Mini:~ <me>$`

**Comment by medariox** [comment]
For some reason you are missing a file that should be located in `/Applications/Medusa/ext/cfscrape` called `user_agents.json`. I have no idea why it is missing. You can try pulling Medusa again with `git reset --hard origin/master` (recommended) or add [the file](https://github.com/pymedusa/Medusa/blob/master/ext/cfscrape/user_agents.json) manually to that folder.

Next time please use the issue template or the issue will be closed without answer.
