### ISSUE TITLE
Docker on Synology: WARNING  SHOWQUEUE-ADD : An error occurred while parsing:

### ISSUE THREAD

**Issue by DAVIZINH0** [pymedusa/Medusa#6793]
**Describe the bug**
Hello, i have medusa in docker with a synology and i have a problem when i add any tvshow.
Not special configuration.
not ocurrs with all chapters and all have the same format.
It happens with official docker repository and de linuxserver repository
Appears the warning that i put in the log

**To Reproduce**
Fress install in docker

**Expected behavior**
no warnings

**Medusa (please complete the following information):**
OS: synology DSM and DOCKER. 
Linux-4.4.59+-x86_64-with
Branch: master
Commit: Unknown
Version: 0.3.2
Database: 44.14
Python Version: | 2.7.16 (default, May  6 2019, 19:35:26)  [GCC 8.3.0]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-06-07 17:37:57 WARNING  SHOWQUEUE-ADD :: [] An error occurred while parsing: /series/American Gods/Temporada 1/American Gods - 1x01 - La plantación de huesos.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                          4.0                          |
|                   libmediainfo.so.0                   |
|                        v18.8.1                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/app/medusa/lib/pymediainfo/__init__.py", line 296, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 68: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2019-06-07 17:37:56 WARNING  SHOWQUEUE-ADD :: [] An error occurred while parsing: /series/American Gods/Temporada 1/American Gods - 1x08 - Ven a Jesús.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                          4.0                          |
|                   libmediainfo.so.0                   |
|                        v18.8.1                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/app/medusa/lib/pymediainfo/__init__.py", line 296, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 66: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
```
</details>

**Additional context**

**Comment by medariox** [comment]
```
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
```

**Comment by DAVIZINH0** [comment]
ok sorry.
i think if this occurs as stock docker image, maybe the problem will be the docker image.
I will ask in knowit repository

thanks

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/6796
New release tomorrow.

**Comment by DAVIZINH0** [comment]
great!, thanks a lot
