### ISSUE TITLE
error after update - Medusa won't start anymore

### ISSUE THREAD

**Issue by NicoLeOca** [pymedusa/Medusa#6797]
Hi,

After a manual update of a dev branch, to update 43 commits a minute ago, my Medusa won't start anymore.

 - OS: MacOS Mojave
 - Branch: dev
 - Commit: 6a21a6001b10827d14d450135bae61729b01edf1
 - Python version: 2.7.10
 - Database version: don't know

I don't know what's brocken; when I manually launch Medusa; I get this:
```
python sickbeard.py
Traceback (most recent call last):
  File "sickbeard.py", line 6, in <module>
    from medusa.__main__ import main
  File "/Applications/Medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/Applications/Medusa/medusa/init/__init__.py", line 39, in initialize
    _configure_subliminal()
  File "/Applications/Medusa/medusa/init/__init__.py", line 215, in _configure_subliminal
    refiner_manager.register('release = {basename}.refiners.release:refine'.format(basename=basename))
  File "/Applications/Medusa/ext/subliminal/extensions.py", line 64, in register
    ext = self._load_one_plugin(ep, False, (), {}, False)
  File "/Applications/Medusa/ext/stevedore/extension.py", line 223, in _load_one_plugin
    plugin = ep.resolve()
  File "/Applications/Medusa/lib/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Applications/Medusa/medusa/refiners/release.py", line 10, in <module>
    from medusa.logger.adapters.style import BraceAdapter
  File "/Applications/Medusa/medusa/logger/__init__.py", line 45, in <module>
    import knowit
  File "/Applications/Medusa/ext/knowit/__init__.py", line 27, in <module>
    from .api import KnowitException, know
  File "/Applications/Medusa/ext/knowit/api.py", line 8, in <module>
    from .providers import (
  File "/Applications/Medusa/ext/knowit/providers/__init__.py", line 5, in <module>
    from .enzyme import EnzymeProvider
  File "/Applications/Medusa/ext/knowit/providers/enzyme.py", line 25, in <module>
    from ..rules import (
  File "/Applications/Medusa/ext/knowit/rules/__init__.py", line 4, in <module>
    from .audio import AtmosRule
  File "/Applications/Medusa/ext/knowit/rules/audio/__init__.py", line 4, in <module>
    from .atmos import AtmosRule
ImportError: No module named atmos
```

I won't be home for a couple of days. Appologies if I answer your additional questions on my return only.
I post know, in case you can fix it before others update and get brocken too.

**Comment by medariox** [comment]
Something went wrong with your update. Just pull a new copy of Medusa (with git or manually) or reinstall (make a backup of main.db and config.ini first).

**Comment by NicoLeOca** [comment]
@medariox 
Sorry I forgot to pass by and thank you for the tip
pulling everything again worked, thanks
