### ISSUE TITLE
linuxserver/medusa Add Show cannot read existing files.

### ISSUE THREAD

**Issue by nenyiarkaah** [pymedusa/Medusa#6814]
**Describe the bug**
When adding an existing show the existing files are not being scanned. 
Currently both the files and the Medusa use the same naming convention
Show Name.Season NumberXEpisode Number.Episode Name

**To Reproduce**

1. add a show
2. choose the path with the existing show
3. let Medusa do its magic
4. Medusa sets most of the episodes to wanted, even though they are already available in the selected path.

**Expected behavior**
Have Medusa find the files and mark them as DOWNLOADED

**Screenshots**

**Medusa (please complete the following information):**

- Branch: master
- Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76
- Version: 0.3.2
- Database: 44.15
- Docker Image: linuxserver/medusa

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-06-10 21:56:39 ERROR	SHOWQUEUE-ADD :: [918cfe7] Error searching dir for e**********sodes: 'MediaInfo' object has no attribute 'xml_dom'
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 619, in run
    self.show.load_e**********sodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 1053, in load_e**********sodes_from_dir
    cur_e**********sode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1397, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/e**********sode.py", line 2040, in update_status_quality
    new_quality = Quality.name_quality(filepath, self.series.is_anime)
  File "/app/medusa/medusa/common.py", line 284, in name_quality
    return Quality._extend_quality(name)
  File "/app/medusa/medusa/common.py", line 383, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/app/medusa/medusa/common.py", line 405, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/app/medusa/ext/knowit/a**********.py", line 70, in know
    raise KnowitException(debug_info(context=context, exc_info=True))
  File "/app/medusa/ext/knowit/a**********.py", line 121, in debug_info
    lines.append(debug_data())
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 289, in debug_data
    xml = ensure_text(ElementTree.tostring(media_info.xml_dom)).replace('\r', '').replace('\n', '')
AttributeError: 'MediaInfo' object has no attribute 'xml_dom'
```
</details>

**Additional context**

**Comment by medariox** [comment]
Fixed with the new release.
