### ISSUE TITLE
NotImplementedError with rtorrent

### ISSUE THREAD

**Issue by FlyingPersian** [pymedusa/Medusa#6872]
**Describe the bug**
When I try to download a torrent, it fails. Blackhole works, but using rtorrent as the client with RPC2 doesn't (http://rtorrentIP/RPC2). The connection is established, but pushing the .torrent seems to fail. Works fine with rtorrent.

**To Reproduce**
Forced, manual, or backlog search does this when downloading a wanted episode

**Expected behavior**
It should push the .torrent file to rtorrent successfully

**Medusa (please complete the following information):**
 - OS: FreeNAS 11.2 (iocage jail)
 - Branch: master
 - Commit: 74c3f12
 - Python version: 3.6.8
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-06-24 19:00:16 ERROR	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] Snatch failed! For result: Fear.the.Walking.Dead.S05E04.720p.WEB.h264-TBS
Traceback (most recent call last):
  File "/usr/home/medusa/Medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/usr/home/medusa/Medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/usr/home/medusa/Medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/usr/home/medusa/Medusa/medusa/clients/torrent/rtorrent.py", line 55, in _get_auth
    self.auth = RTorrent(self.host, None, None, True)
  File "/usr/home/medusa/Medusa/lib/rtorrent/__init__.py", line 75, in __init__
    raise NotImplementedError()
NotImplementedError
2019-06-24 19:00:16 DEBUG	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] Calling rTorrent Client
2019-06-24 19:00:16 DEBUG	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] User-Agent: Medusa/0.3.4 (FreeBSD; 11.2-STABLE; dd32bc54-969f-11e9-93d8-0cc47a406253)
2019-06-24 19:00:16 DEBUG	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] GET URL: http://192.168.178.105:9117/dl/xxx [Status: 200]
2019-06-24 19:00:16 DEBUG	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] User-Agent: Medusa/0.3.4 (FreeBSD; 11.2-STABLE; dd32bc54-969f-11e9-93d8-0cc47a406253)
2019-06-24 19:00:16 DEBUG	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] GET URL: http://192.168.178.105:9117/dl/xxx [Status: 200]
2019-06-24 19:00:16 DEBUG	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] Retrieving redirect URL for http://192.168.178.105:9117/dl/xxx
2019-06-24 19:00:16 INFO	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] Downloading Fear.the.Walking.Dead.S05E04.720p.WEB.h264-TBS with 663 seeders and 668 leechers and size 860.00 MB from IPT Jacket, through a SearchType.BACKLOG_SEARCH search
2019-06-24 19:00:16 INFO	SNATCHQUEUE-SNATCH-290853 :: [74c3f12] Beginning to snatch release: Fear.the.Walking.Dead.S05E04.720p.WEB.h264-TBS
```
</details>

**Comment by medariox** [comment]
That's not how you setup RPC for rtorrent. Refer to their manual for proper setup: https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC

**Comment by FlyingPersian** [comment]
I did that now, still getting the same error.

2019-06-24 21:03:51 ERROR    SNATCHQUEUE-SNATCH-304262 :: [74c3f12] Snatch failed! For result: Animal.Kingdom.US.S04E04.720p.WEBRip.x264-TBS
Traceback (most recent call last):
  File "/usr/home/medusa/Medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/usr/home/medusa/Medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/usr/home/medusa/Medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/usr/home/medusa/Medusa/medusa/clients/torrent/rtorrent.py", line 55, in _get_auth
    self.auth = RTorrent(self.host, None, None, True)
  File "/usr/home/medusa/Medusa/lib/rtorrent/__init__.py", line 75, in __init__
    raise NotImplementedError()
NotImplementedError

**Comment by medariox** [comment]
How does your `rTorrent host:port` look like?

**Comment by FlyingPersian** [comment]
192.168.178.103/RPC2

Doing it like that works on radarr.

**Comment by medariox** [comment]
Okay. Now set it up like you are supposed to (showed in the example when you configure it).

**Comment by FlyingPersian** [comment]
Same.

2019-06-24 21:12:18 ERROR	SNATCHQUEUE-SNATCH-264586 :: [74c3f12] Snatch failed! For result: Orange.Is.the.New.Black.S06E13.REAL.PROPER.720p.WEB.x264-STRiFE
Traceback (most recent call last):
  File "/usr/home/medusa/Medusa/medusa/search/queue.py", line 503, in run
    self.success = snatch_episode(result)
  File "/usr/home/medusa/Medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/usr/home/medusa/Medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/usr/home/medusa/Medusa/medusa/clients/torrent/rtorrent.py", line 55, in _get_auth
    self.auth = RTorrent(self.host, None, None, True)
  File "/usr/home/medusa/Medusa/lib/rtorrent/__init__.py", line 75, in __init__
    raise NotImplementedError()
NotImplementedError
2019-06-24 21:12:18 DEBUG	SNATCHQUEUE-SNATCH-264586 :: [74c3f12] Calling rTorrent Client
2019-06-24 21:12:18 DEBUG	SNATCHQUEUE-SNATCH-264586 :: [74c3f12] User-Agent: Medusa/0.3.4 (FreeBSD; 11.2-STABLE; 20434cc6-96a2-11e9-a731-0cc47a406253)
2019-06-24 21:12:18 DEBUG	SNATCHQUEUE-SNATCH-264586 :: [74c3f12] GET URL: http://192.168.178.105:9117/dl/xxx

**Comment by medariox** [comment]
How does your `rTorrent host:port` look like?

**Comment by FlyingPersian** [comment]
192.168.178.103/plugins/httprpc/action.php

**Comment by medariox** [comment]
> URL to your rTorrent client (e.g. scgi://localhost:5000 
or https://localhost/rutorrent/plugins/httprpc/action.php)

Notice any difference?

**Comment by FlyingPersian** [comment]
scgi://localhost:5000 <-- I can't do that since I'm using a unix socket as you mentioned before.
https://localhost/rutorrent/plugins/httprpc/action.php <-- looks the same as in my link. Wanna tell me the difference?

Hope you don't mean the "rutorrent" part in the link. It's not needed as 192.168.178.103 already leads to rutorrent. Also, I added it and the test returns a failure

**Comment by medariox** [comment]
... you are missing the protocol.

**Comment by FlyingPersian** [comment]
I'll be damned! I didn't think I'd need that since it automatically switched to http (when I enter scgi it removes everything http-related"). Thanks, it's working and can be closed!
