### ISSUE TITLE
Added shows not imported properly

### ISSUE THREAD

**Issue by FlyingPersian** [pymedusa/Medusa#6873]
**Describe the bug**
I just installed medusa and added about 40 existing shows. Some of them work fine, others output an error. Of those with error, some get set to "downloaded" (either with known or unknown quality), others are set to wanted and then medusa downloads them, even though the files are there. I don't mind the faulty quality, but it should at least recognize that the shows are all there. I have about 1500 warnings so far, all in the same way. I have about 15 shows for medusa still to go through. 
I installed medusa by downloading the git, installed python3.6, sqlite3, openssl, and pip, and then installed the requirements.txt using pip install. It finished with no error.

**Expected behavior**
It should add all the shows/episodes and recognize them.

**Screenshots*
https://i.imgur.com/Ev11YmG.jpg

All of the shows are fully existing. Some, if not all of the episodes that are shown as downloaded still outputted that same error.

**Medusa (please complete the following information):**
 - OS: FreeNAS 11.2 (iocage jail)
 - Branch: master
 - Commit: 74c3f12
 - Python version: 3.6.8
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] 321060: Loading all episodes from the show directory: /media/shows/The OA
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] 321060: Found files: ['/media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv', '/media/shows/The OA/S01/The OA - S01E08 - Invisible Self.mkv', '/media/shows/The OA/S01/The OA - S01E06 - Forking Paths.mkv', '/media/shows/The OA/S01/The OA - S01E03 - Champion.mkv', '/media/shows/The OA/S01/The OA - S01E02 - New Colossus.mkv', '/media/shows/The OA/S01/The OA - S01E04 - Away.mkv', '/media/shows/The OA/S01/The OA - S01E01 - Homecoming.mkv', '/media/shows/The OA/S01/The OA - S01E07 - Empire of Light.mkv', '/media/shows/The OA/S02/The OA - S02E05 - Chapter 5 The Medium & the Engineer.mkv', '/media/shows/The OA/S02/The OA - S02E07 - Chapter 7.mkv', '/media/shows/The OA/S02/The OA - S02E02 - Chapter 2.mkv', '/media/shows/The OA/S02/The OA - S02E01 - Angel of Death.mkv', '/media/shows/The OA/S02/The OA - S02E04 - Syzygy.mkv', '/media/shows/The OA/S02/The OA - S02E08 - Chapter 8 Overview.mkv', '/media/shows/The OA/S02/The OA - S02E03 - Chapter 3 Magic Mirror.mkv', '/media/shows/The OA/S02/The OA - S02E06 - Chapter 6 Mirror Mirror.mkv']
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] 321060: Creating episode from: /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] 321060: Creating episode object from /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Scene numbering enabled series The OA using indexer numbering: S01E05
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Converted parsed result /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv into title: The OA, season: 1, episode: [5], episode_title: Paradise, container: mkv, type: episode, parsing_time: 0.04376697540283203, absolute_episode: [], quality: Unknown, total_time: None
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Matched release /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv to a series in your database: The OA
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Parsed /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv into title: The OA, season: 1, episode: [5], episode_title: Paradise, container: mkv, type: episode, parsing_time: 0.04376697540283203, absolute_episode: [], quality: Unknown, total_time: 0.04496479034423828
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] 321060: /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv parsed to The OA S01E05
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] 321060: Setter sets location to /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] The OA: The old episode had a different file associated with it, re-checking the quality using the new filename /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Video '/media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv' scanned using enzyme '0.4.2' has raw data:
<function EnzymeProvider.describe.<locals>.debug_data at 0x816f0b598>
2019-06-24 19:29:43 WARNING  SHOWQUEUE-ADD :: [74c3f12] An error occurred while parsing: /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                          4.0                          |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "1:00:17",
        "date_utc": "2016-12-19 07:19:29",
        "muxing_app": "libebml v1.3.4 + libmatroska v1.4.5",
        "writing_app": "mkvmerge v9.3.1 ('Mask Machine') 32bit"
    },
    "video_tracks": [
        {
            "type": 1,
            "number": 1,
            "language": "und",
            "enabled": true,
            "default": true,
            "forced": false,
            "lacing": false,
            "codec_id": "V_MPEG4/ISO/AVC",
            "width": 1280,
            "height": 720,
            "interlaced": false,
            "stereo_mode": 0,
            "crop": {},
            "display_width": 1280,
            "display_height": 720,
            "aspect_ratio_type": 0
        }
    ],
    "audio_tracks": [
        {
            "type": 2,
            "number": 2,
            "language": "und",
            "enabled": true,
            "default": true,
            "forced": false,
            "lacing": true,
            "codec_id": "A_AC3",
            "sampling_frequency": 48000.0,
            "channels": 6,
            "output_sampling_frequency": 48000.0
        }
    ],
    "subtitle_tracks": [],
    "chapters": [],
    "tags": [],
    "recurse_seek_head": false
}
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/usr/home/medusa/Medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/usr/home/medusa/Medusa/ext/knowit/providers/enzyme.py", line 135, in describe
    video_path=video_path, version=enzyme.__version__, data=json.dumps(data))
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'timedelta' is not JSON serializable

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] The OA: Setting the status from 'Wanted' to 'Downloaded' and quality 'N/A' to 'Unknown' based on file: /media/shows/The OA/S01/The OA - S01E05 - Paradise.mkv
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Transaction with 1 queries executed
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Scene numbering enabled series The OA using indexer numbering: S01E05
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Converted parsed result The OA - S01E05 - Paradise into title: The OA, season: 1, episode: [5], episode_title: Paradise, type: episode, parsing_time: 0.023275375366210938, absolute_episode: [], quality: Unknown, total_time: None
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Matched release The OA - S01E05 - Paradise to a series in your database: The OA
2019-06-24 19:29:43 DEBUG    SHOWQUEUE-ADD :: [74c3f12] Parsed The OA - S01E05 - Paradise into title: The OA, season: 1, episode: [5], episode_title: Paradise, type: episode, parsing_time: 0.023275375366210938, absolute_episode: [], quality: Unknown, total_time: 0.024496078491210938
```
</details>

**Additional context**
The log is just for one episode that is there, but was gave me this error and was set to "wanted" and then snatched afterwards

**Comment by medariox** [comment]
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+

**Comment by medariox** [comment]
To elaborate: KnowIt is what Medusa uses to find out the quality of the files when the videos are named without quality in them (like yours do). Since you haven't installed `mediainfo` or `ffmpeg` like we suggest in the setup, KnowIt will use `enzyme` to try to find out the quality. `enzyme` only works for `.mkv` files and is generally less reliable compared to `mediainfo` or `ffmpeg`. If you get that warning it means something went wrong with KnowIt, please report the bug to the KnowIt repository. You'll probably have better results by installing `mediainfo` or `ffmpeg`.

**Comment by FlyingPersian** [comment]
Thanks! I didn't know that mediainfo or ffmpeg had to be installed. I followed an external tutorial and looked through the Ubuntu one linked on the site, but none of them mentioned any of those two programs. Installed them now and I hope it will run better.

**Comment by medariox** [comment]
I figured, most of those guides are incomplete/outdated. 

https://github.com/pymedusa/Medusa/wiki/Medusa-installation-Debian-Ubuntu
In step 1) we ask to install mediainfo as dependency (as it's usually the better choice):
> sudo apt-get update && sudo apt-get install unrar-free git-core openssl mediainfo

You're welcome, enjoy!
