### ISSUE TITLE
[APP SUBMITTED]: adba.aniDBerrors.AniDBCommandTimeoutError: Command has timed out

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#6878]
### INFO
**Python Version**: `3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]`
**Operating System**: `Darwin-18.6.0-x86_64-i386-64bit`
**Locale**: `unknown`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/b0ef6e1f40946fd50bb90fcccc1eb255
### ERROR
<pre>
2019-06-27 01:13:09 ERROR    TORNADO :: [74c3f12] Exception: Command has timed out
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/ext/adba/__init__.py#L166">ext/adba/__init__.py</a>", line 166, in handle
    command.resp
AttributeError: 'MyListAddCommand' object has no attribute 'resp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/ext/adba/aniDBAbstracter.py#L280">ext/adba/aniDBAbstracter.py</a>", line 280, in add_to_mylist
    self.aniDB.mylistadd(size=self.size, ed2k=self.ed2k, state=state, viewed=viewed, source=source, storage=storage, other=other)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/ext/adba/__init__.py#L730">ext/adba/__init__.py</a>", line 730, in mylistadd
    return self.handle(MyListAddCommand(lid, fid, size, ed2k, aid, aname, gid, gname, epno, edit, state, viewed, source, storage, other), callback)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/ext/adba/__init__.py#L169">ext/adba/__init__.py</a>", line 169, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
adba.aniDBerrors.AniDBCommandTimeoutError: Command has timed out
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.7.4 (default, Sep 28 2019, 16:39:19) [Clang 11.0.0 (clang-1100.0.33.8)]`
**Operating System**: `Darwin-19.0.0-x86_64-i386-64bit`
**Locale**: `unknown`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/49ab34567b8b649e846935ae7c7f0acf
### ERROR
<pre>
2019-10-10 15:27:00 ERROR    TORNADO :: [baad1e5] Exception: Command has timed out
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/adba/__init__.py#L166">ext/adba/__init__.py</a>", line 166, in handle
    command.resp
AttributeError: 'MyListAddCommand' object has no attribute 'resp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/adba/aniDBAbstracter.py#L280">ext/adba/aniDBAbstracter.py</a>", line 280, in add_to_mylist
    self.aniDB.mylistadd(size=self.size, ed2k=self.ed2k, state=state, viewed=viewed, source=source, storage=storage, other=other)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/adba/__init__.py#L730">ext/adba/__init__.py</a>", line 730, in mylistadd
    return self.handle(MyListAddCommand(lid, fid, size, ed2k, aid, aname, gid, gname, epno, edit, state, viewed, source, storage, other), callback)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/ext/adba/__init__.py#L169">ext/adba/__init__.py</a>", line 169, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
adba.aniDBerrors.AniDBCommandTimeoutError: Command has timed out
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]`
**Operating System**: `Darwin-19.3.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@16ee2be21e10d97fe651e67a6c1fbd64431002c6
**Link to Log**: https://gist.github.com/db5e16ba0862ee48306bfe0265c66a96
### ERROR
<pre>
2020-02-07 17:48:47 ERROR    TORNADO :: [16ee2be] Exception: Command has timed out
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/16ee2be21e10d97fe651e67a6c1fbd64431002c6/ext/adba/__init__.py#L166">ext/adba/__init__.py</a>", line 166, in handle
    command.resp
AttributeError: 'MyListAddCommand' object has no attribute 'resp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/16ee2be21e10d97fe651e67a6c1fbd64431002c6/ext/adba/aniDBAbstracter.py#L280">ext/adba/aniDBAbstracter.py</a>", line 280, in add_to_mylist
    self.aniDB.mylistadd(size=self.size, ed2k=self.ed2k, state=state, viewed=viewed, source=source, storage=storage, other=other)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/16ee2be21e10d97fe651e67a6c1fbd64431002c6/ext/adba/__init__.py#L730">ext/adba/__init__.py</a>", line 730, in mylistadd
    return self.handle(MyListAddCommand(lid, fid, size, ed2k, aid, aname, gid, gname, epno, edit, state, viewed, source, storage, other), callback)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/16ee2be21e10d97fe651e67a6c1fbd64431002c6/ext/adba/__init__.py#L169">ext/adba/__init__.py</a>", line 169, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
adba.aniDBerrors.AniDBCommandTimeoutError: Command has timed out
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by samjaninf** [comment]
I have the same error, but mine is running on docker.

```
2020-08-02 11:50:12 ERROR    POSTPROCESSOR :: [] Exception: Command has timed out
Traceback (most recent call last):
  File "/app/medusa/ext/adba/__init__.py", line 166, in handle
    command.resp
AttributeError: 'MyListAddCommand' object has no attribute 'resp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/adba/aniDBAbstracter.py", line 280, in add_to_mylist
    self.aniDB.mylistadd(size=self.size, ed2k=self.ed2k, state=state, viewed=viewed, source=source, storage=storage, other=other)
  File "/app/medusa/ext/adba/__init__.py", line 730, in mylistadd
    return self.handle(MyListAddCommand(lid, fid, size, ed2k, aid, aname, gid, gname, epno, edit, state, viewed, source, storage, other), callback)
  File "/app/medusa/ext/adba/__init__.py", line 169, in handle
    raise AniDBCommandTimeoutError("Command has timed out")
adba.aniDBerrors.AniDBCommandTimeoutError: Command has timed out
2020-08-02 11:30:07 ERROR    POSTPROCESSOR :: [] Exception: You must provide <lid XOR fid XOR size+ed2k XOR a(id|name)+g(id|name)+epno> for MYLISTADD command
Traceback (most recent call last):
  File "/app/medusa/ext/adba/aniDBAbstracter.py", line 280, in add_to_mylist
    self.aniDB.mylistadd(size=self.size, ed2k=self.ed2k, state=state, viewed=viewed, source=source, storage=storage, other=other)
  File "/app/medusa/ext/adba/__init__.py", line 730, in mylistadd
    return self.handle(MyListAddCommand(lid, fid, size, ed2k, aid, aname, gid, gname, epno, edit, state, viewed, source, storage, other), callback)
  File "/app/medusa/ext/adba/aniDBcommands.py", line 353, in __init__
    raise AniDBIncorrectParameterError("You must provide <lid XOR fid XOR size+ed2k XOR a(id|name)+g(id|name)+epno> for MYLISTADD command")
adba.aniDBerrors.AniDBIncorrectParameterError: You must provide <lid XOR fid XOR size+ed2k XOR a(id|name)+g(id|name)+epno> for MYLISTADD command```
