### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by muertocaloh** [pymedusa/Medusa#6885]
### INFO
**Python Version**: `3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.19.42-v7+-armv7l-with-debian-9.9`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/6a1abae501a06e3a5b22e65b6e7ac6e4
### ERROR
<pre>
2019-06-28 15:10:33 ERROR    POSTPROCESSOR :: [74c3f12] OSError: OSError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/helpers/__init__.py#L295">medusa/helpers/__init__.py</a>", line 295, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/usr/lib/python3.5/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/usr/lib/python3.5/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 9] Bad file descriptor
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Kp1003** [comment]
### INFO
**Python Version**: `2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.15.0-55-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/c86adf4f4cba7c16f911eeec63935028
### ERROR
<pre>
2019-09-03 20:14:18 ERROR    POSTPROCESSOR :: [74c3f12] Unable to copy file /home/hd25/**********/torrents/completed medusa/Quantico.S01.NORDiC.720p.WEB-DL.DD5.1.H.264-DBRETAiL/Quantico.S01E22.NORDiC.720p.WEB-DL.DD5.1.H.264-DBRETAiL.mkv to /home/hd25/**********/mnt/gdriveC/media/serier/Quantico/Season 01/Episode 22/Quantico.S01.E22-Yes-720p.WEB-DL.DBRETAiL.mkv: IOError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/home/hd25/**********/apps/medusa/medusa/post_processor.py", line 482, in copy
    helpers.copy_file(cur_file_path, new_file_path)
  File "/home/hd25/**********/apps/medusa/medusa/helpers/__init__.py", line 295, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/home/hd25/**********/apps/medusa/lib/shutil_custom/__init__.py", line 37, in copyfile_custom
    fdst.write(buf)
IOError: [Errno 9] Bad file descriptor
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Kp1003** [comment]
### INFO
**Python Version**: `2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.15.0-55-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/b8fe35eef5b60a1c7574370839da0071
### ERROR
<pre>
2019-09-03 20:13:54 ERROR    POSTPROCESSOR :: [74c3f12] Unable to copy file /home/hd25/**********/torrents/completed medusa/Quantico.S01.NORDiC.720p.WEB-DL.DD5.1.H.264-DBRETAiL/Quantico.S01E16.NORDiC.720p.WEB-DL.DD5.1.H.264-DBRETAiL.mkv to /home/hd25/**********/mnt/gdriveC/media/serier/Quantico/Season 01/Episode 16/Quantico.S01.E16-Clue-720p.WEB-DL.DBRETAiL.mkv: IOError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/home/hd25/**********/apps/medusa/medusa/post_processor.py", line 482, in copy
    helpers.copy_file(cur_file_path, new_file_path)
  File "/home/hd25/**********/apps/medusa/medusa/helpers/__init__.py", line 295, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/home/hd25/**********/apps/medusa/lib/shutil_custom/__init__.py", line 37, in copyfile_custom
    fdst.write(buf)
IOError: [Errno 9] Bad file descriptor
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
