### ISSUE TITLE
Fails to start, AttributeError: 'NoneType' object has no attribute 'lstrip'

### ISSUE THREAD

**Issue by tortfeaser** [pymedusa/Medusa#6971]
**Describe the bug**
Medusa fails to start.

**To Reproduce**
1. Try to start medusa with 'service medusa start'
2. See error

**Expected behavior**
Medusa fails to start. See console error description below.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: FreeBSD 11.2-RELEASE-p9
 - Branch: master
 - Python version: 3.6.9
 
**Additional context**
```
root@medusa:/ # service medusa start
Starting medusa.
Traceback (most recent call last):
  File "/usr/local/medusa/start.py", line 9, in <module>
    main()
  File "/usr/local/medusa/medusa/__main__.py", line 2185, in main
    application.start(sys.argv[1:])
  File "/usr/local/medusa/medusa/__main__.py", line 319, in start
    self.initialize(console_logging=self.console_logging)
  File "/usr/local/medusa/medusa/__main__.py", line 997, in initialize
    app.APP_VERSION = updater.current_version
  File "/usr/local/medusa/medusa/updater/github_updater.py", line 53, in current_version
    return cur_version.lstrip('v')
AttributeError: 'NoneType' object has no attribute 'lstrip'
/usr/local/etc/rc.d/medusa: WARNING: failed to start medusa
```

**Comment by medariox** [comment]
Need previous logs. You can find them in your Logs folder.

**Comment by tortfeaser** [comment]
Thanks for the reply. Only log in the .../medusa/config/Logs folder is a very brief application log. Here's the terminal result and the log:

```
root@medusa:/usr/local/medusa/config/Logs # service medusa start
Starting medusa.
Traceback (most recent call last):
  File "/usr/local/medusa/start.py", line 9, in <module>
    main()
  File "/usr/local/medusa/medusa/__main__.py", line 2185, in main
    application.start(sys.argv[1:])
  File "/usr/local/medusa/medusa/__main__.py", line 319, in start
    self.initialize(console_logging=self.console_logging)
  File "/usr/local/medusa/medusa/__main__.py", line 997, in initialize
    app.APP_VERSION = updater.current_version
  File "/usr/local/medusa/medusa/updater/github_updater.py", line 53, in current_version
    return cur_version.lstrip('v')
AttributeError: 'NoneType' object has no attribute 'lstrip'
/usr/local/etc/rc.d/medusa: WARNING: failed to start medusa
root@medusa:/usr/local/medusa/config/Logs # ll
total 4
-rw-r--r--  1 root  FISH  788 24 Jul 11:57 application.log
root@medusa:/usr/local/medusa/config/Logs # cat *log
2019-07-24 11:57:56 INFO     MAIN :: [] Broken providers found: ['torrent9', 'newpct', 'tntvillage']
2019-07-24 11:57:56 WARNING  MAIN :: [] git version returned : /bin/sh: git: not found. Treat as error for now
2019-07-24 11:57:56 WARNING  MAIN :: [] git version returned : /bin/sh: git: not found. Treat as error for now
2019-07-24 11:57:56 WARNING  MAIN :: [] No git specified, can't use git commands
2019-07-24 11:57:56 WARNING  MAIN :: [] git version returned : /bin/sh: git: not found. Treat as error for now
2019-07-24 11:57:56 WARNING  MAIN :: [] No git specified, can't use git commands
2019-07-24 11:57:56 WARNING  MAIN :: [] git version returned : /bin/sh: git: not found. Treat as error for now
2019-07-24 11:57:56 WARNING  MAIN :: [] No git specified, can't use git commands
```

If this is a git problem, git is installed:
```
root@medusa:/usr/local/medusa/config/Logs # pkg info git
git-2.22.0
Name           : git
Version        : 2.22.0
Installed on   : Tue Jul 23 11:49:30 2019 AEST
Origin         : devel/git
Architecture   : FreeBSD:11:amd64
Prefix         : /usr/local
Categories     : devel
Licenses       : GPLv2
Maintainer     : garga@FreeBSD.org
WWW            : https://git-scm.com/
Comment        : Distributed source code management tool
Options        :
        CONTRIB        : on
        CURL           : on
        CVS            : on
        GITWEB         : on
        GUI            : off
        HTMLDOCS       : off
        ICONV          : on
        NLS            : on
        P4             : on
        PCRE           : on
        PCRE2          : off
        PERL           : on
        SEND_EMAIL     : on
        SUBTREE        : on
        SVN            : off
Shared Libs required:
        libexpat.so.1
        libpcre.so.1
        libintl.so.8
        libcurl.so.4
Annotations    :
        FreeBSD_version: 1102000
        repo_type      : binary
        repository     : FreeBSD
Flat size      : 31.6MiB
Description    :
Git is a free and open source distributed version control system designed to
handle everything from small to very large projects with speed and efficiency.

WWW: https://git-scm.com/
root@medusa:/usr/local/medusa/config/Logs #
```
/usr/local/bin is in my path. So I added a symlink to /usr/local/bin/git in /bin and it started. Weird.

**Comment by medariox** [comment]
Medusa tries to run `git` by default. If that's not available, you can specify a custom path in your `config.ini`. This shouldn't prevent Medusa from starting off, so I'm going to consider this a bug.

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/8884
