### ISSUE TITLE
[APP SUBMITTED]: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by mule007** [pymedusa/Medusa#6980]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/e7e26a7da80f9f5b797f730c25796299
### ERROR
<pre>
2019-07-26 10:24:30 ERROR    SHOWQUEUE-ADD :: [74c3f12] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/logger/adapters/style.py#L53">medusa\logger\adapters\style.py</a>", line 53, in __str__
    return self.msg.format(*args)
KeyError: 'external_id'
Traceback (most recent call last):
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/logger/adapters/style.py#L60">medusa\logger\adapters\style.py</a>", line 60, in __str__
    raise BraceException(self.msg)
BraceException: Traceback (most recent call last):
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/show_queue.py#L518">medusa\show_queue.py</a>", line 518, in run
    newShow.load_from_indexer(indexer_api)
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/tv/series.py#L1556">medusa\tv\series.py</a>", line 1556, in load_from_indexer
    self.externals.update(get_externals(self))
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/helpers/externals.py#L110">medusa\helpers\externals.py</a>", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/medusa/indexers/tvmaze/tvmaze_api.py#L489">medusa\indexers\tvmaze\tvmaze_api.py</a>", line 489, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/lib/pytvmaze/tvmaze.py#L643">lib\pytvmaze\tvmaze.py</a>", line 643, in get_show
    return self.show_main_info(self.lookup_tvdb(tvdb_id).id, embed=embed)
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/lib/pytvmaze/tvmaze.py#L1021">lib\pytvmaze\tvmaze.py</a>", line 1021, in lookup_tvdb
    q = self._endpoint_standard_get(url)
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/lib/pytvmaze/tvmaze.py#L548">lib\pytvmaze\tvmaze.py</a>", line 548, in _endpoint_standard_get
    results = r.json()
  File "D:\Medusa\Medusa\<a href="../blob/74c3f124fb599ad923e23f46fc320778b8b4217c/ext/requests/models.py#L897">ext\requests\models.py</a>", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Medusa\Python\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\Medusa\Python\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Medusa\Python\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mule007** [comment]
Noticed the captive portal, it was my ISP interfering.  Apologies.
