### ISSUE TITLE
could not connect to TheTvdb.com, with reason 'ValueError("invalid literal for int() with base 10: ''")'

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#7035]
**Describe the bug**
keeps failing to fetch metadata from tvdb, missing posters & images as it' falling back to plex tvdb.

**To Reproduce**
just add any new show or for exsample: Nagi-Asu: A Lull in the Sea

**Screenshots**
![Screen Shot 2019-08-03 at 4 52 20 am](https://user-images.githubusercontent.com/2242880/62392326-857adc00-b5aa-11e9-8639-53675e7b4d88.jpg)

**Medusa (please complete the following information):**
 - OS: macOS 10.14.6 (Darwin-18.7.0-x86_64-i386-64bit)
 - Branch: develop
 - Commit: d382651b7575b193719db89602f4d963e88f5bd0
 - Python version: 3.7.4 (default, Jul 9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
 - Database version: Database: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-08-03 04:41:38 WARNING  SHOWQUEUE-UPDATE :: [74c3f12] could not connect to TheTvdb.com, with reason 'ValueError("invalid literal for int() with base 10: ''")'
2019-08-03 04:41:38 WARNING  SHOWQUEUE-UPDATE :: [74c3f12] Enabling Plex fallback as TheTvdb.com API is having some connectivity issues
```
</details>

**Additional context**
Full Log: https://gist.github.com/XxUnkn0wnxX/be53e198eefa9b9aee8d135ee2a21e8d

i dont know if this is a temp issue, api update issue. but plex doesnt have any issues fetching from tvdb api (like posters, banner & show info) at the time this issue is occuring with Medusa.

**Comment by medariox** [comment]
Plex has a private TVDB API. The whole TVDB v2 API is down/broken. See: https://forums.thetvdb.com/viewtopic.php?f=17&t=46729&sid=b6219ce3a276e65943db6c27cef1d33c&start=30

**Comment by XxUnkn0wnxX** [comment]
Also go this error just now:
<Log>
```
2019-08-03 05:11:34 ERROR    SHOWQUEUE-REFRESH :: [d382651] 319982: Error while refreshing show Fuuka. Error: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/medusa/show_queue.py", line 692, in run
    self.show.populate_cache()
  File "/Users/ovidijus/Apps/Medusa/medusa/tv/series.py", line 1802, in populate_cache
    image_cache.fill_cache(self)
  File "/Users/ovidijus/Apps/Medusa/medusa/image_cache.py", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "/Users/ovidijus/Apps/Medusa/medusa/image_cache.py", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "/Users/ovidijus/Apps/Medusa/medusa/metadata/generic.py", line 773, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/Users/ovidijus/Apps/Medusa/medusa/metadata/generic.py", line 898, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/Users/ovidijus/Apps/Medusa/medusa/indexers/indexer_base.py", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/Users/ovidijus/Apps/Medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 610, in _get_show_data
    self._parse_images(sid)
  File "/Users/ovidijus/Apps/Medusa/medusa/indexers/tvdbv2/fallback.py", line 136, in __call__
    return self.func(*args, **kwargs)
  File "/Users/ovidijus/Apps/Medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 490, in _parse_images
    if int(image.sub_key) not in _images[image_type][resolution]:
ValueError: invalid literal for int() with base 10: ''
```
</Log>

**Comment by medariox** [comment]
This is the actual issue: https://forums.thetvdb.com/viewtopic.php?f=118&t=57702

You can make pressure to the TVDB devs, we can't do anything from our side. They just broke their API. It's probably going to be fixed soon.

**Comment by medariox** [comment]
This now fixed.
