### ISSUE TITLE
[APP SUBMITTED]: BraceException: DailySearchQueueItem Exception, error: {error}

### ISSUE THREAD

**Issue by VexingHex** [pymedusa/Medusa#7049]
### INFO
**Python Version**: `2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]`
**Operating System**: `Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-08-10 09:14:54 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Nyaa] :: [74c3f12] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/opt/**********/**********/logger/adapters/style.py", line 43, in __str__
    return self.msg.format(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 151: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/**********/**********/logger/adapters/style.py", line 60, in __str__
    raise BraceException(self.msg)
BraceException: DailySearchQueueItem Exception, error: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Should be fixed in develop.

**Comment by VexingHex** [comment]
### INFO
**Python Version**: `2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]`
**Operating System**: `Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-09-05 15:22:24 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Nyaa] :: [74c3f12] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/opt/**********/**********/logger/adapters/style.py", line 43, in __str__
    return self.msg.format(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 138: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/**********/**********/logger/adapters/style.py", line 60, in __str__
    raise BraceException(self.msg)
BraceException: DailySearchQueueItem Exception, error: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by VexingHex** [comment]
### INFO
**Python Version**: `2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]`
**Operating System**: `Linux-4.15.0-55-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/de40a3df87b9e94d4211bf0e1a23bb40
### ERROR
<pre>
2019-09-23 11:38:00 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Nyaa] :: [baad1e5] BraceMessage string formatting failed. Using representation instead.
Traceback (most recent call last):
  File "/opt/**********/**********/logger/adapters/style.py", line 43, in __str__
    return self.msg.format(*args, **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 133: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/**********/**********/logger/adapters/style.py", line 60, in __str__
    raise BraceException(self.msg)
BraceException: DailySearchQueueItem Exception, error: {error}
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
