### ISSUE TITLE
Unexpected error in provider u'opensubtitles' - OpenSubtitlesError: 408 Invalid parameters; episode is not number

### ISSUE THREAD

**Issue by ward0** [pymedusa/Medusa#7076]
**Describe the bug**

**To Reproduce**
Manual search for subtitles for dual episode (E21E22)
**Expected behavior**
A list of subtitles, download this one:
https://www.opensubtitles.org/nl/subtitles/7809118/blindspot-masters-of-war-1-5-8-nl

**Screenshots**
not needed

**Medusa (please complete the following information):**

Medusa Info: | Branch: master Commit: 74c3f124fb599ad923e23f46fc320778b8b4217c Version: 0.3.4 Database: 44.14
-- | --
Python Version: | 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]
SSL Version: | OpenSSL 1.0.2n 7 Dec 2017
OS: | Linux-4.4.59+-x86_64-with-glibc2.2.5
Locale: | Unknown.Unknown

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-08-20 22:50:36 DEBUG	DAILYSEARCHER :: [74c3f12] Finished updating network timezones
2019-08-20 22:50:36 DEBUG	DAILYSEARCHER :: [74c3f12] User-Agent: Medusa/0.3.4 (Linux; 4.4.59+; c8ac75b5-c375-11e9-bca0-001132906ee2)
2019-08-20 22:50:36 DEBUG	DAILYSEARCHER :: [74c3f12] GET URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt [Status: 200]
2019-08-20 22:50:36 DEBUG	DAILYSEARCHER :: [74c3f12] Started updating network timezones
2019-08-20 22:42:20 DEBUG	Thread-7 :: [74c3f12] Scores computed for release: Blindspot.S04E21E22.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
2019-08-20 22:42:20 DEBUG	Thread-7 :: [74c3f12] Discarding provider tvsubtitles
2019-08-20 22:42:20 WARNING	Thread-7 :: [74c3f12] Unexpected error in provider u'tvsubtitles'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/tvsubtitles.py", line 206, in list_subtitles
    subtitles = [s for s in self.query(show_id, title, video.season, video.episode, video.year)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/tvsubtitles.py", line 169, in query
    if episode not in episode_ids:
TypeError: unhashable type: 'list'
2019-08-20 22:42:17 DEBUG	Thread-7 :: [74c3f12] Initializing provider tvsubtitles
2019-08-20 22:42:17 DEBUG	Thread-7 :: [74c3f12] Listing subtitles with provider u'tvsubtitles' and languages set([<Language [nl]>])
2019-08-20 22:42:17 DEBUG	Thread-7 :: [74c3f12] Searching subtitles {'action': 'search', 'hash': '8f57cf32acd82507ba22d112f77af414'}
2019-08-20 22:42:17 DEBUG	Thread-7 :: [74c3f12] Initializing provider thesubdb
2019-08-20 22:42:17 DEBUG	Thread-7 :: [74c3f12] Listing subtitles with provider u'thesubdb' and languages set([<Language [nl]>])
2019-08-20 22:42:17 DEBUG	Thread-7 :: [74c3f12] Discarding provider opensubtitles
2019-08-20 22:42:17 WARNING	Thread-7 :: [74c3f12] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 228, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 183, in query
    response = checked(self.server.SearchSubtitles(self.token, criteria))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 295, in checked
    raise OpenSubtitlesError(response['status'])
OpenSubtitlesError: 408 Invalid parameters; episode is not number
2019-08-20 22:42:17 DEBUG	Thread-7 :: [74c3f12] Searching subtitles [{'moviebytesize': '6063714588', 'sublanguageid': u'dut', 'moviehash': 'd9f2b70efe1cd3c8'}, {'sublanguageid': u'dut', 'tag': u'Blindspot.S04E21E22.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv'}, {'query': u'Blindspot', 'sublanguageid': u'dut', 'episode': [21, 22], 'season': 4}]
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Logging in
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Initializing provider opensubtitles
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Listing subtitles with provider u'opensubtitles' and languages set([<Language [nl]>])
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Creating a new ProviderPool instance
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Video information cached under key medusa.subtitles:video|/volume1/A_SERIES/Blindspot/Blindspot.S04E21E22.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Refining video with omdb
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Refining video with tvdb
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Attribute tvdb_id changed from None to 7176737
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Refining using Episode information.
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Attribute year changed from None to 2015
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Attribute series_imdb_id changed from None to u'tt4474344'
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Attribute series_tvdb_id changed from None to 295647
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Refining using Series information.
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Refining video with tvepisode
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Attribute episode changed from 21 to [21, 22]
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Guessing using /volume1/A_SERIES/Blindspot/Blindspot.S04E21E22.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Starting release refiner [extension=release, release_name=Blindspot.S04E21E22.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb, release_file=None]
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Refining video with release
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Refining video with metadata
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Scanning video u'Blindspot.S04E21E22.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv' in u'/volume1/A_SERIES/Blindspot'
2019-08-20 22:42:16 DEBUG	Thread-7 :: [74c3f12] Scanning video /volume1/A_SERIES/Blindspot/Blindspot.S04E21E22.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv...
2019-08-20 22:42:16 INFO	Thread-7 :: [74c3f12] Manual searching subtitles for: Blindspot.S04E21E22.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2019-08-20 22:42:16 INFO	Thread-7 :: [74c3f12] Starting to manual searching subtitles
```
</details>

**Additional context**
In 'View warnings' i get:

2019-08-20 22:42:20 WARNING  Thread_7 :: [74c3f12] Unexpected error in provider u'tvsubtitles'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/tvsubtitles.py", line 206, in list_subtitles
    subtitles = [s for s in self.query(show_id, title, video.season, video.episode, video.year)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/tvsubtitles.py", line 169, in query
    if episode not in episode_ids:
TypeError: unhashable type: 'list'
2019-08-20 22:42:17 WARNING  Thread_7 :: [74c3f12] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 228, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 183, in query
    response = checked(self.server.SearchSubtitles(self.token, criteria))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 295, in checked
    raise OpenSubtitlesError(response['status'])
OpenSubtitlesError: 408 Invalid parameters; episode is not number

**Comment by medariox** [comment]
subliminal bug. Report upstream
