### ISSUE TITLE
[APP SUBMITTED]: ValueError: u'Name' is not in list

### ISSUE THREAD

**Issue by Kp1003** [pymedusa/Medusa#7110]
### INFO
**Python Version**: `2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.15.0-55-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@74c3f124fb599ad923e23f46fc320778b8b4217c
**Link to Log**: https://gist.github.com/da3a611da982c7864f38c7a5723d2be9
### ERROR
<pre>
2019-09-03 20:10:44 ERROR    SEARCHQUEUE-MANUAL-247808 :: [NordicBits] :: [74c3f12] Failed parsing provider.
Traceback (most recent call last):
  File "/home/hd25/**********/apps/medusa/medusa/providers/torrent/html/nordicbits.py", line 133, in parse
    title = cells[labels.index('Name')].a
ValueError: u'Name' is not in list
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Was this a one time issue or did the provider change the layout?

**Comment by Kp1003** [comment]
> 
> 
> Was this a one time issue or did the provider change the layout?

I dont really know actually, as i just signed up on the site.

It's a pretty new site i think.

And has gotten the error again today. Looks like this.

2019-09-06 13:20:01 ERROR    SEARCHQUEUE-BACKLOG-28120 :: [NordicBits] :: [74c3f12] Failed parsing provider.
Traceback (most recent call last):
  File "/home/hd25/**********/apps/medusa/medusa/providers/torrent/html/nordicbits.py", line 133, in parse
    title = cells[labels.index('Name')].a
ValueError: u'Name' is not in list
2019-09-06 13:03:54 ERROR    Thread_11 :: [74c3f12] Exception generated: 'ascii' codec can't encode character u'\xf8' in position 44: ordinal not in range(128)

**Comment by Kp1003** [comment]
### INFO
**Python Version**: `2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-4.15.0-55-generic-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/febc501a8841dc9f39a9bf3617a81145
### ERROR
<pre>
2019-09-10 00:12:33 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [NordicBits] :: [baad1e5] Failed parsing provider.
Traceback (most recent call last):
  File "/home/hd25/**********/apps/medusa/medusa/providers/torrent/html/nordicbits.py", line 133, in parse
    title = cells[labels.index('Name')].a
ValueError: u'Name' is not in list
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Would you mind lending us temp your creds? Contact us on discord

**Comment by Manzzon** [comment]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@4d1e78726dc94979cc7908651d13e40f199959a9
**Link to Log**: https://gist.github.com/6b11762af0496057e8cd435f8fcd4801
### ERROR
<pre>
2020-04-13 13:53:54 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [NordicBits] :: [4d1e787] Failed parsing provider.
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/providers/torrent/html/nordicbits.py#L133">medusa/providers/torrent/html/nordicbits.py</a>", line 133, in parse
    title = cells[labels.index('Name')].a
ValueError: u'Name' is not in list
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
