### ISSUE TITLE
medusa crash and doesn't start after auto-update

### ISSUE THREAD

**Issue by lasauce25** [pymedusa/Medusa#7125]
2019-09-08 09:05:55 INFO     CHECKVERSION :: [74c3f12] New update found, starting auto-updater ...
2019-09-08 09:05:57 INFO     CHECKVERSION :: [74c3f12] Config backup in progress...
2019-09-08 09:07:07 INFO     CHECKVERSION :: [74c3f12] Config backup successful, updating...
2019-09-08 09:07:09 INFO     CHECKVERSION :: [baad1e5] Update was successful!
2019-09-08 09:07:09 INFO     EVENT-QUEUE :: [baad1e5] Aborting all threads
2019-09-08 09:07:09 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the DAILYSEARCHER thread to exit
2019-09-08 09:07:09 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the BACKLOG thread to exit
2019-09-08 09:07:09 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the SHOWUPDATER thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the CHECKVERSION thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the SHOWQUEUE-REFRESH thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the FORCEDSEARCHQUEUE thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the SNATCHQUEUE-SNATCH-276515 thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the POSTPROCESSOR thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the TRAKTCHECKER thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the FINDPROPERS thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the FINDSUBTITLES thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the TORRENTCHECKER thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Waiting for the EVENT-QUEUE thread to exit
2019-09-08 09:07:10 INFO     EVENT-QUEUE :: [baad1e5] Saving all shows to the database
2019-09-08 09:07:14 INFO     EVENT-QUEUE :: [baad1e5] Saving config file to disk
2019-09-08 09:07:14 INFO     EVENT-QUEUE :: [baad1e5] Shutting down Tornado
2019-09-08 09:07:14 INFO     EVENT-QUEUE :: [baad1e5] Restarting Medusa with ['/usr/bin/python', u'/apps/medusa/start.py', '--nolaunch']
['/usr/bin/python', u'/apps/medusa/start.py', '--nolaunch']
Traceback (most recent call last):
  File "/apps/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/apps/medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/apps/medusa/medusa/init/__init__.py", line 37, in initialize
    _monkey_patch_cfscrape()
  File "/apps/medusa/medusa/init/__init__.py", line 184, in _monkey_patch_cfscrape
    from medusa.init.cfscrape import patch_cfscrape
  File "/apps/medusa/medusa/init/cfscrape.py", line 11, in <module>
    import js2py
  File "/apps/medusa/ext/js2py/__init__.py", line 73, in <module>
    from .evaljs import *
  File "/apps/medusa/ext/js2py/evaljs.py", line 155
    exec (DEFAULT_HEADER, self._context)
SyntaxError: unqualified exec is not allowed in function '__init__' it contains a nested function with free variables

**Comment by medariox** [comment]
Please use the issue template.
