### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'indexer'

### ISSUE THREAD

**Issue by gilly65** [pymedusa/Medusa#7206]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/404beaae2c977ac9d50f3a8c9fa61f7a
### ERROR
<pre>
2019-10-04 16:09:56 ERROR    Thread_16 :: [baad1e5] Exception generated: 'NoneType' object has no attribute 'indexer'
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/server/web/home/handler.py#L741">medusa/server/web/home/handler.py</a>", line 741, in getSeasonSceneExceptions
    in iteritems(get_all_scene_exceptions(series_obj))},
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/scene_exceptions.py#L136">medusa/scene_exceptions.py</a>", line 136, in get_all_scene_exceptions
    return exceptions_cache.get((series_obj.indexer, series_obj.series_id), defaultdict(set))
AttributeError: 'NoneType' object has no attribute 'indexer'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.8.7 (default, Dec 30 2020, 10:14:55) [Clang 12.0.0 (clang-1200.0.32.28)]`
**Operating System**: `macOS-11.2-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [feature/add-fdh](../tree/feature/add-fdh)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@c335ee528cf98e833272f26313c4e13bb8e6ee7b
**Link to Log**: https://gist.github.com/81e5b0c3236ccb567f5294be679ccc95
### ERROR
<pre>
2021-02-02 07:20:49 ERROR    Thread_0 :: [c335ee5] Exception generated: 'NoneType' object has no attribute 'indexer'
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/c335ee528cf98e833272f26313c4e13bb8e6ee7b/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/c335ee528cf98e833272f26313c4e13bb8e6ee7b/medusa/server/web/home/handler.py#L1280">medusa/server/web/home/handler.py</a>", line 1280, in getManualSearchStatus
    series_obj = Series.find_by_identifier(SeriesIdentifier.from_slug(showslug))
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/c335ee528cf98e833272f26313c4e13bb8e6ee7b/medusa/tv/series.py#L285">medusa/tv/series.py</a>", line 285, in find_by_identifier
    result = Show.find_by_id(app.showList, identifier.indexer.id, identifier.id)
AttributeError: 'NoneType' object has no attribute 'indexer'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.8.7 (default, Dec 30 2020, 10:14:55) [Clang 12.0.0 (clang-1200.0.32.28)]`
**Operating System**: `macOS-11.2-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [feature/add-fdh](../tree/feature/add-fdh)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@c335ee528cf98e833272f26313c4e13bb8e6ee7b
**Link to Log**: https://gist.github.com/5822dd3ac9e336b4c030b38cdb0c252b
### ERROR
<pre>
2021-02-02 14:24:57 ERROR    Thread_0 :: [c335ee5] Exception generated: 'NoneType' object has no attribute 'indexer'
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/c335ee528cf98e833272f26313c4e13bb8e6ee7b/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/c335ee528cf98e833272f26313c4e13bb8e6ee7b/medusa/server/web/home/handler.py#L1280">medusa/server/web/home/handler.py</a>", line 1280, in getManualSearchStatus
    series_obj = Series.find_by_identifier(SeriesIdentifier.from_slug(showslug))
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/c335ee528cf98e833272f26313c4e13bb8e6ee7b/medusa/tv/series.py#L285">medusa/tv/series.py</a>", line 285, in find_by_identifier
    result = Show.find_by_id(app.showList, identifier.indexer.id, identifier.id)
AttributeError: 'NoneType' object has no attribute 'indexer'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rikbon** [comment]
### INFO
**Python Version**: `3.8.10 (default, May  6 2021, 06:30:44) [GCC 9.3.0]`
**Operating System**: `Linux-5.10.17-v7l+-armv7l-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/38896052c89344cd127ec9038c8e4d40
### ERROR
<pre>
2021-07-14 10:32:58 ERROR    TRAKTCHECKER :: [] Exception generated: 'NoneType' object has no attribute 'indexer'
Traceback (most recent call last):
  File "/app/medusa/medusa/schedulers/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/medusa/schedulers/trakt_checker.py", line 87, in run
    self.sync_watchlist()
  File "/app/medusa/medusa/schedulers/trakt_checker.py", line 314, in sync_watchlist
    self.remove_episode_watchlist()
  File "/app/medusa/medusa/schedulers/trakt_checker.py", line 358, in remove_episode_watchlist
    indexer=show_obj.indexer, indexer_id=show_obj.series_id,
AttributeError: 'NoneType' object has no attribute 'indexer'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
