### ISSUE TITLE
[APP SUBMITTED]: IndexError: list index out of range

### ISSUE THREAD

**Issue by pax0707** [pymedusa/Medusa#7235]
### INFO
**Python Version**: `2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/ab11d90176bced5f9931431f8818cc8c
### ERROR
<pre>
2019-10-06 13:46:48 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing provider.
Traceback (most recent call last):
  File "D:\Plex\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/providers/torrent/html/beyondhd.py#L114">medusa\providers\torrent\html\beyondhd.py</a>", line 114, in parse
    link = cells[1].find('a')
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
Seeing the same issue on Beyond-HD
```
2019-10-07 21:18:52 ERROR	FORCEDSEARCHQUEUE-MANUAL-357223 :: Beyond-HD :: [baad1e5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\torrent\html\beyondhd.py", line 114, in parse
    link = cells[1].find('a')
IndexError: list index out of range
2019-10-07 21:18:52 ERROR	FORCEDSEARCHQUEUE-MANUAL-357223 :: Beyond-HD :: [baad1e5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\torrent\html\beyondhd.py", line 114, in parse
    link = cells[1].find('a')
IndexError: list index out of range
```

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-10-11 09:30:50 ERROR    FORCEDSEARCHQUEUE-MANUAL-311714 :: [Beyond-HD] :: [baad1e5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\GitHub\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/providers/torrent/html/beyondhd.py#L114">medusa\providers\torrent\html\beyondhd.py</a>", line 114, in parse
    link = cells[1].find('a')
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Anyone willing to share creds?

**Comment by Rouzax** [comment]
@p0psicles sure, let's exchange on Discord

**Comment by Rouzax** [comment]
```
2019-10-11 13:27:27 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing human time: 104.77  GiB
2019-10-11 13:27:27 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing human time: 1.24  GiB
2019-10-11 13:27:27 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing human time: 179.46  GiB
2019-10-11 13:27:27 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing human time: 181.9  GiB
2019-10-11 13:27:27 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing human time: 182.48  GiB
2019-10-11 13:27:27 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing human time: 173.7  GiB
2019-10-11 13:27:27 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing human time: 115.71  GiB
```

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.7.5 (default, Nov  1 2019, 02:16:23) [Clang 11.0.0 (clang-1100.0.33.8)]`
**Operating System**: `Darwin-19.0.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@44cfeb76b7b2fd731dc0259d82dd166f808f2026
**Link to Log**: https://gist.github.com/a62f08ee2f37948ce0dc6cf2bbf064fb
### ERROR
<pre>
2019-12-05 22:44:35 ERROR    TORNADO :: [44cfeb7] Uncaught exception in APIv2: IndexError('list index out of range')
Request: GET /api/v2/alias-source (127.0.0.1)
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/ext/tornado/web.py#L1592">ext/tornado/web.py</a>", line 1592, in _execute
    result = yield result
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/ext/tornado/gen.py#L1141">ext/tornado/gen.py</a>", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/medusa/server/api/v2/base.py#L83">medusa/server/api/v2/base.py</a>", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/medusa/server/api/v2/alias_source.py#L44">medusa/server/api/v2/alias_source.py</a>", line 44, in get
    data = find_alias_sources()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/medusa/server/api/v2/alias_source.py#L19">medusa/server/api/v2/alias_source.py</a>", line 19, in find_alias_sources
    last_refresh = get_last_refresh(mapping.get(identifier, identifier))[0]['last_refreshed']
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.7.5 (default, Nov  1 2019, 02:16:23) [Clang 11.0.0 (clang-1100.0.33.8)]`
**Operating System**: `Darwin-19.0.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@44cfeb76b7b2fd731dc0259d82dd166f808f2026
**Link to Log**: https://gist.github.com/885ccb6e9bc143331a5ba21e38cba1c2
### ERROR
<pre>
2019-12-05 22:47:21 ERROR    TORNADO :: [44cfeb7] Uncaught exception in APIv2: IndexError('list index out of range')
Request: GET /api/v2/alias-source (127.0.0.1)
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/ext/tornado/web.py#L1592">ext/tornado/web.py</a>", line 1592, in _execute
    result = yield result
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/ext/tornado/gen.py#L1141">ext/tornado/gen.py</a>", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/medusa/server/api/v2/base.py#L83">medusa/server/api/v2/base.py</a>", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/medusa/server/api/v2/alias_source.py#L44">medusa/server/api/v2/alias_source.py</a>", line 44, in get
    data = find_alias_sources()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/44cfeb76b7b2fd731dc0259d82dd166f808f2026/medusa/server/api/v2/alias_source.py#L19">medusa/server/api/v2/alias_source.py</a>", line 19, in find_alias_sources
    last_refresh = get_last_refresh(mapping.get(identifier, identifier))[0]['last_refreshed']
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
yeah that's weird. Can you reproduce it?

**Comment by pcliff069** [comment]
### INFO
**Python Version**: `3.8.1 (default, Dec 30 2019, 15:43:37) [GCC 9.2.0]`
**Operating System**: `Linux-4.19.83-xanmod40-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/92d0865c9f846c62118fd30cb526b8a4
### ERROR
<pre>
2020-02-29 02:21:02 ERROR    SNATCHQUEUE-SNATCH-355838 :: [] Snatch failed! For result: Lincoln.Rhyme.Hunt.for.the.Bone.Collector.S01E07.720p.HDTV.x264-AVS
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 459, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/deluged.py", line 44, in _get_auth
    return True if self.connect() else None
  File "/app/medusa/medusa/clients/torrent/deluged.py", line 57, in connect
    drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pcliff069** [comment]
### INFO
**Python Version**: `3.8.1 (default, Dec 30 2019, 15:43:37) [GCC 9.2.0]`
**Operating System**: `Linux-4.19.83-xanmod40-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/e6dfc31c32720c6df0ca651407b8c184
### ERROR
<pre>
2020-02-29 02:20:32 ERROR    SNATCHQUEUE-SNATCH-311902 :: [] Snatch failed! For result: MacGyver.2016.S04E04.720p.HDTV.x264-AVS
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 459, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/deluged.py", line 44, in _get_auth
    return True if self.connect() else None
  File "/app/medusa/medusa/clients/torrent/deluged.py", line 57, in connect
    drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pcliff069** [comment]
### INFO
**Python Version**: `3.8.1 (default, Dec 30 2019, 15:43:37) [GCC 9.2.0]`
**Operating System**: `Linux-4.19.83-xanmod40-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/b1a467ba73cd6e636906f431c0647f8b
### ERROR
<pre>
2020-02-29 02:20:29 ERROR    SNATCHQUEUE-SNATCH-349317 :: [] Snatch failed! For result: Charmed.2018.S02E14.720p.HDTV.x264-SVA
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 459, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/deluged.py", line 44, in _get_auth
    return True if self.connect() else None
  File "/app/medusa/medusa/clients/torrent/deluged.py", line 57, in connect
    drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by baya44** [comment]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/0bc2c75adcaa8faf2447e7ec200d5f55
### ERROR
<pre>
2020-05-26 09:19:44 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [EliteTracker] :: [d9c31da] DailySearchQueueItem Exception, error: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/search/queue.py#L266">medusa/search/queue.py</a>", line 266, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/search/core.py#L526">medusa/search/core.py</a>", line 526, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/tv/cache.py#L225">medusa/tv/cache.py</a>", line 225, in update_cache
    data = self._get_rss_data()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/tv/cache.py#L200">medusa/tv/cache.py</a>", line 200, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)}
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/providers/torrent/html/elitetracker.py#L100">medusa/providers/torrent/html/elitetracker.py</a>", line 100, in search
    results += self.parse(response.text, mode, keywords=search_string)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/providers/torrent/html/elitetracker.py#L122">medusa/providers/torrent/html/elitetracker.py</a>", line 122, in parse
    if torrent_rows[1].get_text(strip=True) == 'Aucun résultat':
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ssafhi** [comment]
### INFO
**Python Version**: `3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]`
**Operating System**: `Linux-5.8.3-050803-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@708c2e9351e61b3f96345ab013f52e83b5a474b5
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-09-07 00:21:26 ERROR    TORNADO :: [708c2e9] Uncaught exception in APIv2: IndexError('list index out of range')
Request: GET /**********/medusa/api/v2/internal/existingSeries?rootDirs=0,1 (127.0.0.1)
Traceback (most recent call last):
  File "/home/**********/.medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/**********/.medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/**********/.medusa/ext/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/**********/.medusa/medusa/server/api/v2/base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/home/**********/.medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/**********/.medusa/medusa/server/api/v2/internal.py", line 55, in get
    return resource_function()
  File "/home/**********/.medusa/medusa/server/api/v2/internal.py", line 76, in resource_existing_series
    root_dirs = [root_dirs[idx] for idx in root_dirs_indices]
  File "/home/**********/.medusa/medusa/server/api/v2/internal.py", line 76, in <listcomp>
    root_dirs = [root_dirs[idx] for idx in root_dirs_indices]
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@e6025de42a034b5887e5806fda210e30f5a1e150
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-11-27 15:53:20 ERROR    SEARCHQUEUE-BACKLOG-361753 :: [Beyond-HD] :: [e6025de] Failed parsing provider.
Traceback (most recent call last):
  File "C:\GitHub\Medusa\<a href="../blob/e6025de42a034b5887e5806fda210e30f5a1e150/medusa/providers/torrent/html/beyondhd.py#L128">medusa\providers\torrent\html\beyondhd.py</a>", line 128, in parse
    download_url = urljoin(self.url, cells[2].find('a')['href'])
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@e6025de42a034b5887e5806fda210e30f5a1e150
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-11-29 22:36:45 ERROR    SEARCHQUEUE-BACKLOG-360295 :: [Beyond-HD] :: [e6025de] Failed parsing provider.
Traceback (most recent call last):
  File "C:\GitHub\Medusa\<a href="../blob/e6025de42a034b5887e5806fda210e30f5a1e150/medusa/providers/torrent/html/beyondhd.py#L128">medusa\providers\torrent\html\beyondhd.py</a>", line 128, in parse
    download_url = urljoin(self.url, cells[2].find('a')['href'])
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pax0707** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-5.4.83-v7l+-armv7l-with-debian-10.7`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@698ca1db9903a9f716d9ed1910972cbf70ea50e8
**Link to Log**: https://gist.github.com/415e3d1cd34c658e68dc074ecb7dbf45
### ERROR
<pre>
2021-01-12 20:21:59 ERROR    SEARCHQUEUE-BACKLOG-368121 :: [Beyond-HD] :: [698ca1d] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/698ca1db9903a9f716d9ed1910972cbf70ea50e8/medusa/providers/torrent/html/beyondhd.py#L128">medusa/providers/torrent/html/beyondhd.py</a>", line 128, in parse
    download_url = urljoin(self.url, cells[2].find('a')['href'])
IndexError: list index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Chopp3rDave** [comment]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-4.15.0-128-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@2b874c2c6a3c33d653eec6e50598a194627a6f76
**Link to Log**: https://gist.github.com/8a6409ab3a143e2dab26c7598ef483ba
### ERROR
<pre>
2021-01-24 12:24:11 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Speedcd] :: [2b874c2] DailySearchQueueItem Exception, error: IndexError('string index out of range')
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/medusa/search/queue.py#L295">medusa/search/queue.py</a>", line 295, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/app/medusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/medusa/search/core.py#L526">medusa/search/core.py</a>", line 526, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "/app/medusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/medusa/tv/cache.py#L226">medusa/tv/cache.py</a>", line 226, in update_cache
    data = self._get_rss_data()
  File "/app/medusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/medusa/tv/cache.py#L201">medusa/tv/cache.py</a>", line 201, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)}
  File "/app/medusa/<a href="../blob/2b874c2c6a3c33d653eec6e50598a194627a6f76/medusa/providers/torrent/html/speedcd.py#L104">medusa/providers/torrent/html/speedcd.py</a>", line 104, in search
    html = response_json['Fs'][0][1][1][1]
IndexError: string index out of range
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
