### ISSUE TITLE
[APP SUBMITTED]: ConnectionError: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /shows/13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000CC49940>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))",),)

### ISSUE THREAD

**Issue by MadMungo** [pymedusa/Medusa#7240]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/8a84f3456c44ee30715636355408a8b1
### ERROR
<pre>
2019-10-09 18:38:49 ERROR    SHOWQUEUE-REFRESH :: [baad1e5] 13: Error while refreshing show The Flash. Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /shows/13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000CC49940>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))",),)
Traceback (most recent call last):
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/show_queue.py#L709">medusa\show_queue.py</a>", line 709, in run
    self.show.populate_cache()
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/tv/series.py#L1802">medusa\tv\series.py</a>", line 1802, in populate_cache
    image_cache.fill_cache(self)
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/image_cache.py#L339">medusa\image_cache.py</a>", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/image_cache.py#L262">medusa\image_cache.py</a>", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/metadata/generic.py#L773">medusa\metadata\generic.py</a>", line 773, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/metadata/generic.py#L898">medusa\metadata\generic.py</a>", line 898, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/indexers/indexer_base.py#L399">medusa\indexers\indexer_base.py</a>", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/indexers/tvmaze/tvmaze_api.py#L406">medusa\indexers\tvmaze\tvmaze_api.py</a>", line 406, in _get_show_data
    series_info = self._get_show_by_id(tvmaze_id, request_language=get_show_in_language)
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/medusa/indexers/tvmaze/tvmaze_api.py#L208">medusa\indexers\tvmaze\tvmaze_api.py</a>", line 208, in _get_show_by_id
    results = self.tvmaze_api.get_show(maze_id=tvmaze_id)
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/lib/pytvmaze/tvmaze.py#L638">lib\pytvmaze\tvmaze.py</a>", line 638, in get_show
    return self.show_main_info(maze_id, embed=embed)
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/lib/pytvmaze/tvmaze.py#L1060">lib\pytvmaze\tvmaze.py</a>", line 1060, in show_main_info
    q = self._endpoint_standard_get(url)
  File "G:\Medusa\Medusa\<a href="../blob/baad1e5af59d7f29606c1fed1c110af1424bb117/lib/pytvmaze/tvmaze.py#L540">lib\pytvmaze\tvmaze.py</a>", line 540, in _endpoint_standard_get
    raise ConnectionError(repr(e))
ConnectionError: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /shows/13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000000CC49940>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))",),)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by onehans** [comment]
`2019-11-03 19:19:03 ERROR	SHOWQUEUE-REFRESH :: [baad1e5] 295068: Error while refreshing show Dragon Ball Super. Error: ord() expected a character, but string of length 0 found
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/show_queue.py", line 709, in run
    self.show.populate_cache()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/tv/series.py", line 1802, in populate_cache
    image_cache.fill_cache(self)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/image_cache.py", line 307, in fill_cache
    file_type = which_type(filename)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/image_cache.py", line 139, in which_type
    image_dimension = get_image_size(path)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/medusa/helpers/__init__.py", line 1590, in get_image_size
    while ord(byte) == 0xff:
TypeError: ord() expected a character, but string of length 0 found`

**Comment by papampi** [comment]
Keep getting the same error:

```
2020-01-04 17:16:39 WARNING  SHOWQUEUE-ADD :: [d0c136d] Could not get tvmaze externals. Cause: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?imdb=tt8593252 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55cc007b60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2020-01-04 17:13:43 WARNING  SHOWQUEUE-ADD :: [d0c136d] Error loading IMDb info: ('Connection aborted.', error(0, 'Error'))
2020-01-04 17:10:59 WARNING  SHOWQUEUE-ADD :: [d0c136d] Could not get tvmaze externals. Cause: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?imdb=tt7551216 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f55c0022920>, 'Connection to api.tvmaze.com timed out. (connect timeout=30)'))",),)
2020-01-04 17:07:55 WARNING  SHOWQUEUE-ADD :: [d0c136d] Could not get tvmaze externals. Cause: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?thetvdb=351028 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f55c002ac00>, 'Connection to api.tvmaze.com timed out. (connect timeout=30)'))",),)
2020-01-04 17:02:39 WARNING  SHOWQUEUE-ADD :: [d0c136d] Could not get tvmaze externals. Cause: ConnectionError(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?imdb=tt7551216 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55c000fdf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
2020-01-04 16:59:39 WARNING  SHOWQUEUE-ADD :: [d0c136d] Error loading IMDb info: HTTPSConnectionPool(host='api.imdbws.com', port=443): Max retries exceeded with url: /authentication/credentials/temporary/ios82 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f55c40fc070>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2020-01-04 16:58:41 WARNING  APIv2-Thread_14 :: [d0c136d] Config patch ignored {u'postprocessing': {u'postponeIfSyncFiles': True, u'showDownloadDir': u'/share/Download/torrents/completed/series', u'reflinkAvailable': False, u'naming': {u'enableCustomNamingSports': False, u'multiEp': 1, u'pattern': u'Season %0S/%SN - S%0SE%0E - %EN', u'patternAnime': u'Season %0S/%SN - S%0SE%0E - %EN', u'animeNamingType': 3, u'stripYear': False, u'patternAirByDate': u'%SN - %A.D - %EN', u'enableCustomNamingAirByDate': False, u'enableCustomNamingAnime': False, u'patternSports': u'%SN - %A-D - %EN', u'animeMultiEp': 1}, u'addShowsWithoutDir': False, u'renameEpisodes': True, u'moveAssociatedFiles': False, u'extraScriptsUrl': u'https://github.com/pymedusa/Medusa/wiki/Post-Processing#extra-scripts', u'deleteRarContent': False, u'extraScripts': [], u'noDelete': False, u'allowedExtensions': [u'srt', u'nfo', u'srr', u'sfv'], u'processMethod': u'move', u'processAutomatically': True, u'autoPostprocessorFrequency': 10, u'fileTimestampTimezone': u'local', u'syncFiles': [u'!sync', u'lftp-pget-status', u'bts', u'!qb', u'!qB'], u'unpack': False, u'postponeIfNoSubs': False, u'createMissingShowDirs': False, u'nfoRename': True, u'multiEpStrings': {u'16': u'Repeat (Separated)', u'32': u'Extend (Limited, E-prefixed)', u'1': u'Repeat', u'2': u'Extend', u'64': u'Extend (Limited, e-prefixed)', u'4': u'Duplicate', u'8': u'Extend (Limited)'}, u'airdateEpisodes': False}}
2020-01-04 16:57:50 WARNING  APIv2-Thread_9 :: [d0c136d] Config patch ignored {u'showDefaults': {u'subtitles': False}}
2020-01-04 16:55:13 WARNING  SHOWQUEUE-ADD :: [d0c136d] Could not get tvmaze externals. Cause: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?imdb=tt8111088 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f55c4032850>, 'Connection to api.tvmaze.com timed out. (connect timeout=30)'))",),)
2020-01-04 16:52:08 WARNING  SHOWQUEUE-ADD :: [d0c136d] Could not get tvmaze externals. Cause: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?thetvdb=361753 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f55c402ffa0>, 'Connection to api.tvmaze.com timed out. (connect timeout=30)'))",),)
2020-01-04 16:46:53 WARNING  SHOWQUEUE-ADD :: [d0c136d] Could not get tvmaze externals. Cause: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?imdb=tt8111088 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f55c4026da0>, 'Connection to api.tvmaze.com timed out. (connect timeout=30)'))",),)
2020-01-04 16:43:20 WARNING  SHOWQUEUE-ADD :: [d0c136d] Error loading IMDb info: HTTPSConnectionPool(host='api.imdbws.com', port=443): Max retries exceeded with url: /authentication/credentials/temporary/ios82 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f55bc126060>: Failed to establish a new connection: [Errno 110] Connection timed out',))
2020-01-04 16:38:53 WARNING  SHOWQUEUE-ADD :: [d0c136d] Could not get tvmaze externals. Cause: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /lookup/shows?imdb=tt7016936 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f55bc017a00>, 'Connection to api.tvmaze.com timed out. (connect timeout=30)'))",),)
```
