### ISSUE TITLE
Installing on Netgear Readynas (debian Jesse)

### ISSUE THREAD

**Issue by Bogey** [pymedusa/Medusa#7259]
Hi,

After moving from Sickrage to Sickchill I'm now trying to Install Medusa on my Netgear Readynas. It's a debian Jesse system.
I followed the debian instructions but I can't get it to run via service start. 
When I execute: 
/usr/bin/python2.7 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
it just runs :)
Some help would be appreciated.
Thanks!
Eddie

**Comment by medariox** [comment]
This is usually a permission problem. Which user:group are you using for Medusa? Does the user have the rights to execute Python scripts and access the `/opt/medusa` location?

**Comment by Bogey** [comment]
I did exactly as the instructions suggested: 
```
sudo addgroup --system medusa
sudo adduser --disabled-password --system --home /var/lib/medusa --gecos "Medusa" --ingroup medusa medusa

sudo chown -R medusa:medusa /opt/medusa
```

These are results when I try to run it:
```
root@RN204:/etc/init# sudo systemctl status medusa
● medusa.service - Medusa Daemon
   Loaded: loaded (/etc/systemd/system/medusa.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Wed 2019-10-16 21:32:13 CEST; 5s ago
  Process: 21242 ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa (code=ex
ited, status=1/FAILURE)
 Main PID: 21242 (code=exited, status=1/FAILURE)

Oct 16 21:32:13 RN204 systemd[1]: medusa.service: Unit entered failed state.
Oct 16 21:32:13 RN204 systemd[1]: medusa.service: Failed with result 'exit-code'.
Oct 16 21:32:13 RN204 systemd[1]: medusa.service: Service hold-off time over, scheduling restart.
Oct 16 21:32:13 RN204 systemd[1]: Stopped Medusa Daemon.
Oct 16 21:32:13 RN204 systemd[1]: medusa.service: Start request repeated too quickly.
Oct 16 21:32:13 RN204 systemd[1]: Failed to start Medusa Daemon.
Oct 16 21:32:13 RN204 systemd[1]: medusa.service: Unit entered failed state.
Oct 16 21:32:13 RN204 systemd[1]: medusa.service: Failed with result 'start-limit-hit'.
```

**Comment by medariox** [comment]
Post the result of `journalctl -xe` and the content of `medusa.service`.

**Comment by Bogey** [comment]
journalctl -xe
```
Oct 16 22:09:04 RN204 systemd[1]: Started Medusa Daemon.
-- Subject: Unit medusa.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit medusa.service has finished starting up.
-- 
-- The start-up result is done.
Oct 16 22:09:05 RN204 python2.7[6196]: Traceback (most recent call last):
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/start.py", line 6, in <module>
Oct 16 22:09:05 RN204 python2.7[6196]:     from medusa.__main__ import main
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/medusa/__init__.py", line 24, in <module>
Oct 16 22:09:05 RN204 python2.7[6196]:     initialize()
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/medusa/init/__init__.py", line 23, in initialize
Oct 16 22:09:05 RN204 python2.7[6196]:     _monkey_patch_fs_functions()
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/medusa/init/__init__.py", line 94, in _monkey_patch_fs_funct
ions
Oct 16 22:09:05 RN204 python2.7[6196]:     from medusa.init import filesystem
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/medusa/init/filesystem.py", line 16, in <module>
Oct 16 22:09:05 RN204 python2.7[6196]:     import rarfile
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/ext/rarfile.py", line 2950, in <module>
Oct 16 22:09:05 RN204 python2.7[6196]:     _check_unrar_tool()
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/ext/rarfile.py", line 2931, in _check_unrar_tool
Oct 16 22:09:05 RN204 python2.7[6196]:     custom_check([ORIG_UNRAR_TOOL], True)
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/ext/rarfile.py", line 2823, in custom_check
Oct 16 22:09:05 RN204 python2.7[6196]:     p = custom_popen(cmd)
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/opt/medusa/ext/rarfile.py", line 2813, in custom_popen
Oct 16 22:09:05 RN204 python2.7[6196]:     creationflags=creationflags)
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
Oct 16 22:09:05 RN204 python2.7[6196]:     errread, errwrite)
Oct 16 22:09:05 RN204 python2.7[6196]:   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
Oct 16 22:09:05 RN204 python2.7[6196]:     raise child_exception
Oct 16 22:09:05 RN204 python2.7[6196]: OSError: [Errno 13] Permission denied
Oct 16 22:09:05 RN204 systemd[1]: medusa.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 22:09:05 RN204 systemd[1]: medusa.service: Unit entered failed state.
Oct 16 22:09:05 RN204 systemd[1]: medusa.service: Failed with result 'exit-code'.
Oct 16 22:09:05 RN204 CRON[6151]: pam_unix(cron:session): session closed for user root
Oct 16 22:09:05 RN204 systemd[1]: medusa.service: Service hold-off time over, scheduling restart.
Oct 16 22:09:05 RN204 systemd[1]: systemd-journald-audit.socket: Cannot add dependency job, ignoring: Unit syst
emd-journald-audit.socket is masked.
Oct 16 22:09:05 RN204 systemd[1]: Stopped Medusa Daemon.
-- Subject: Unit medusa.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit medusa.service has finished shutting down.
Oct 16 22:09:05 RN204 systemd[1]: medusa.service: Start request repeated too quickly.
Oct 16 22:09:05 RN204 systemd[1]: Failed to start Medusa Daemon.
-- Subject: Unit medusa.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit medusa.service has failed.
-- 
-- The result is failed.
Oct 16 22:09:05 RN204 systemd[1]: medusa.service: Unit entered failed state.
Oct 16 22:09:05 RN204 systemd[1]: medusa.service: Failed with result 'start-limit-hit'.
Oct 16 22:09:07 RN204 systemd[1]: Started Clean php session files.
-- Subject: Unit phpsessionclean.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit phpsessionclean.service has finished starting up.
-- 
-- The start-up result is done.
Oct 16 22:09:29 RN204 sudo[6266]:     root : TTY=pts/0 ; PWD=/home/Erwin ; USER=root ; COMMAND=/bin/systemctl s
tatus medusa
```
medusa.service
```
# Medusa systemd service unit file
#
# Configuration Notes
#
#    - Option names (e.g. ExecStart=, Type=) are case-sensitive)
#
#    - Adjust User= and Group= to the user/group you want Medusa to run as.
#
#    - Optional adjust EnvironmentFile= path to configuration file
#        Can ONLY be used for configuring extra options used in ExecStart.
#        Putting a minus (-) in front of file means no error warning if the file doesn't exist
#
#    - Adjust ExecStart= to point to your python and Medusa executables.
#       The FIRST token of the command line must be an ABSOLUTE FILE NAME,
#       then followed by arguments for the process.
#       If no --datadir is given, data is stored in same dir as start.py
#       Arguments can also be set in EnvironmentFile (except python)
#
#    - WantedBy= specifies which target (i.e. runlevel) to start Medusa for.
#        multi-user.target equates to runlevel 3 (multi-user text mode)
#        graphical.target  equates to runlevel 5 (multi-user X11 graphical mode)
#

### Example Using Medusa as daemon with pid file
# Type=forking
# PIDFile=/var/run/PyMedusa/Medusa.pid
# ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --nolaunch --pidfile=/var/run/PyMedusa/Medusa.pid --datadir=/opt/medusa

## Example Using Medusa as daemon without pid file
# Type=forking
# GuessMainPID=no
# ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --daemon --nolaunch --datadir=/opt/medusa

### Example Using simple
# Type=simple
# ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --nolaunch

### Example Using simple with EnvironmentFile where APP_DATA=/home/medusa/.medusa in /etc/medusa.conf
# Type=simple
# EnvironmentFile=/etc/medusa.conf
# ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --nolaunch --datadir=${APP_DATA}

### Configuration

[Unit]
Description=Medusa Daemon
After=network.target

[Service]
User=medusa
Group=medusa

Type=simple
ExecStart=/usr/bin/python2.7 /opt/medusa/start.py -q --nolaunch --datadir=/opt/medusa
TimeoutStopSec=25
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by medariox** [comment]
This is definitely a permission issue.
Make sure your files and folders have the correct rights.

Try with:
```
sudo find /opt/medusa -type d -exec chmod 755 {} \;
sudo find /opt/medusa -type f -exec chmod 644 {} \;
```

**Comment by Bogey** [comment]
Both find commands resulted with nothing found.

But you made me think and try the following:
Because no other service on the Readynas plays nice with User/Group (afaik) I removed 
User=medusa
Group=medusa
from the medusa.service file, did a reload and then a start.... it worked!

**Comment by ArieKindicator** [comment]
FWIW, I've written a Medusa package for [ReadyNAS](https://github.com/ArieKindicator/ReadyNAS/tree/master/Medusa) and installs directly from source.

**Comment by p0psicles** [comment]
That's amazing! Thanks for the contribution. FYI. Where going to drop support for python2 prob end of this year. So we could use your help around or before that time.

**Comment by Bogey** [comment]
@ArieKindicator Thank you!! I had MedUSA running, but was unable to get the app control in FrontView. And now that's working too :)

**Comment by ArieKindicator** [comment]
Yep, that app control was a pain.

**Comment by ArieKindicator** [comment]
> 
> 
> @ArieKindicator Thank you!! I had MedUSA running, but was unable to get the app control in FrontView. And now that's working too :)

Yes, app control was quite frustrating. While installing Medusa manually was very easy to do.
