### ISSUE TITLE
Addic7ed subtitle search not working and causing errors

### ISSUE THREAD

**Issue by duncaner** [pymedusa/Medusa#7264]
### INFO

 - OS: Linux-4.4.59+-x86_64-with-glibc2.2.5 (Synology NAS DSM 6.2.2)
 - Branch: master
 - Commit: baad1e5
 - Python version: 2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]
 - Database version: Database: 44.14

### PROBLEM DESCRIPTION

I am new to Medusa that I installed a week ago. It works well but I could never get any subtitle from Addic7ed. Debug Log shows "_unexpected errors in provider Addic7ed_"

My setup is to get both French and English subs primarily from Addic7ed then from Opensubtitles. I was getting some English subs from Opensubtitles but no French ones because they did not exist. However, there were French subs on Addic7ed but they were not picked up. To make sure, I removed Opensubtitles from the providers list and kept Addic7ed only but I never get any sub, French or English. I have the Perfect matches option checked and ignore embedded subs.

To explain the issue, I have manually searched for one episode for which I see at least the English subs on Addic7ed (The Good Place S04E04, release AVS). The same happens systematically in similar situations for other files.
I also have a file in the Post-Process folder with no subtitle (This is us S04E04). I think it went there after a manual postprocessing. There is no sub for that release on Addic7ed so here, the behavior is normal.

#### Debug Log
>2019-10-18 23:59:14 INFO	POSTPROCESSOR :: [baad1e5] Post-processing completed.
2019-10-18 23:59:14 INFO	POSTPROCESSOR :: [baad1e5] Not deleting folder /volume1/homes/Username/Downloads/Medusa/The.Good.Place.S04E04.720p.HDTV.x264-AVS[rarbg] found the following files: [u'The.Good.Place.S04E04.720p.HDTV.x264-AVS.mkv']
2019-10-18 23:59:14 INFO	POSTPROCESSOR :: [baad1e5] Feature 'postpone post-processing if no subtitle available' is enabled.
2019-10-18 23:54:32 INFO	SNATCHQUEUE-SNATCH-2790 :: [baad1e5] Destination is now homes/Username/Downloads/Medusa
2019-10-18 23:54:31 INFO	SNATCHQUEUE-SNATCH-2790 :: [baad1e5] Downloading The.Good.Place.S04E04.720p.HDTV.x264-AVS[rartv] with 159 seeders and 1148 leechers and size 447.48 MB from Rarbg, through a SearchType.MANUAL_SEARCH search
2019-10-18 23:54:31 INFO	SNATCHQUEUE-SNATCH-2790 :: [baad1e5] Beginning to snatch release: The.Good.Place.S04E04.720p.HDTV.x264-AVS[rartv]

At that moment, the Good Place file is still in the Downloaded folder (unnecessary files were automatically deleted). I force a subtitle search and I get an Authentication Error though I have my addic7ed username and password set up. They are correct, I double checked in config.ini.

#### Debug Log
>2019-10-19 00:09:14 INFO	POSTPROCESSOR :: [baad1e5] Post-processing completed.
2019-10-19 00:09:14 INFO	POSTPROCESSOR :: [baad1e5] Not deleting folder /volume1/homes/Username/Downloads/Medusa/The.Good.Place.S04E04.720p.HDTV.x264-AVS[rarbg] found the following files: [u'The.Good.Place.S04E04.720p.HDTV.x264-AVS.mkv']
2019-10-19 00:09:14 INFO	POSTPROCESSOR :: [baad1e5] Feature 'postpone post-processing if no subtitle available' is enabled.
2019-10-19 00:04:43 INFO	FINDSUBTITLES :: [baad1e5] Finished checking for missed subtitles
2019-10-19 00:04:43 INFO	FINDSUBTITLES :: [baad1e5] 17128: No subtitles found for This Is Us S04E04
2019-10-19 00:04:42 INFO	FINDSUBTITLES :: [baad1e5] No subtitles found for this is us s04e04 - 1080p hdtv  lucidtv.mkv
2019-10-19 00:04:40 INFO	FINDSUBTITLES :: [baad1e5] Checking for missed subtitles
2019-10-19 00:04:40 INFO	FINDSUBTITLES :: [baad1e5] No subtitles found for The.Good.Place.S04E04.720p.HDTV.x264-AVS.mkv
2019-10-19 00:04:40 WARNING	FINDSUBTITLES :: [baad1e5] Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 72, in __getitem__
    provider.initialize()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: **********
2019-10-19 00:04:39 INFO	FINDSUBTITLES :: [baad1e5] Checking for needed subtitles in Post-Process folder
2019-10-19 00:04:39 INFO	Thread-1 :: [baad1e5] Subtitle search forced

One last note: I used to see my Addic7ed username after AuthenticationError, now I see only 10 stars (my username is 5 characters long). It happened after I stopped and restarted Medusa.

**Comment by medariox** [comment]
We use subliminal to handle the subtitles and Addic7ed has been broken for quite some time, see: https://github.com/Diaoul/subliminal/issues/966. They have blocked access to their API, so there is not much to do about it. I suggest you start using a different subs provider.

**Comment by duncaner** [comment]
Thanks for the answer. I was worried this would be the answer as I could find such info in much older threads. I was hoping the situation had changed as Addic7ed is still present in the provider list. Disappointing and probably a deal-breaker for me as far as French subs are concerned.

It may be a good idea to update the list of subtitles providers to remove those that don't exist anymore or don't work as Addic7ed.

**Comment by Anatharias** [comment]
It can actually work, but you must subscribe to a CAPTCHA resolving solution (meaning you'd be paying Indians to solve CAPTCHA for you). It is like 3 or 4USD for 1000 CAPTCHA solving. This is ridiculous, this goes beyond the point. Making third world countries residents to work 12-14 hours a day for minimum wage. Addi7ed should change their business model.
