### ISSUE TITLE
[APP SUBMITTED]: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)

### ISSUE THREAD

**Issue by pokyto** [pymedusa/Medusa#7273]
### INFO
**Python Version**: `3.7.5 (default, Oct 16 2019, 06:53:15) [GCC 8.3.0]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/a29bf80ea33d2f99fb7d601b3a1eddf6
### ERROR
<pre>
2019-10-21 17:16:34 ERROR    CHECKVERSION :: [918cfe7] Environment error: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L384">ext/urllib3/connectionpool.py</a>", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L380">ext/urllib3/connectionpool.py</a>", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L449">ext/requests/adapters.py</a>", line 449, in send
    timeout=timeout
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L638">ext/urllib3/connectionpool.py</a>", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/util/retry.py#L367">ext/urllib3/util/retry.py</a>", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/packages/six.py#L686">ext/urllib3/packages/six.py</a>", line 686, in reraise
    raise value
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L600">ext/urllib3/connectionpool.py</a>", line 600, in urlopen
    chunked=chunked)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L386">ext/urllib3/connectionpool.py</a>", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L306">ext/urllib3/connectionpool.py</a>", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/scheduler.py#L93">medusa/scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L45">medusa/updater/version_checker.py</a>", line 45, in run
    if self.check_for_new_version(force):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L253">medusa/updater/version_checker.py</a>", line 253, in check_for_new_version
    if not self.updater.need_update():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/docker_updater.py#L28">medusa/updater/docker_updater.py</a>", line 28, in need_update
    if self.branch == 'master' and not self.is_latest_version():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/update_manager.py#L42">medusa/updater/update_manager.py</a>", line 42, in is_latest_version
    if LooseVersion(self.newest_version) > LooseVersion(self.current_version):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/source_updater.py#L67">medusa/updater/source_updater.py</a>", line 67, in newest_version
    latest_release = get_latest_release(self.github_org, self.github_repo)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/github_client.py#L119">medusa/github_client.py</a>", line 119, in get_latest_release
    return gh.get_organization(organization).get_repo(repo).get_latest_release()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext3/github/Organization.py#L755">ext3/github/Organization.py</a>", line 755, in get_repo
    "/repos/" + self.login + "/" + name
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext3/github/Requester.py#L275">ext3/github/Requester.py</a>", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext3/github/Requester.py#L335">ext3/github/Requester.py</a>", line 335, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext3/github/Requester.py#L388">ext3/github/Requester.py</a>", line 388, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext3/github/Requester.py#L412">ext3/github/Requester.py</a>", line 412, in __requestRaw
    response = cnx.getresponse()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext3/github/Requester.py#L114">ext3/github/Requester.py</a>", line 114, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify, allow_redirects=False)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L546">ext/requests/sessions.py</a>", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L533">ext/requests/sessions.py</a>", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L646">ext/requests/sessions.py</a>", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L529">ext/requests/adapters.py</a>", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by manu4387** [comment]
i also got the same issue have you able to solve this issue:

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
