### ISSUE TITLE
We aren't interested in this result...

### ISSUE THREAD

**Issue by whoamikyo** [pymedusa/Medusa#7279]
**Describe the bug**

 i cannot find this releases

I want to get these releases https://nyaa.si/?f=0&c=0_0&q=%5BEA%5DFate_Grand_Order_-_Zettai_Majuu_Sensen_Babylonia

 i think some bug

**Screenshots**

![](https://i.imgur.com/yb304Lv.png)

**Medusa (please complete the following information):**
 - OS: Debian 10
 - Branch: Master
 - Commit: baad1e5af59d7f29606c1fed1c110af1424bb117
 - Python version: 2.7.16 (default, Apr 6 2019, 01:42:57) [GCC 8.3.0]
 - Database version: Database: 44.14

**Debug logs (at least 50 lines):**

[log.txt](https://github.com/pymedusa/Medusa/files/3764494/log.txt)

**Comment by medariox** [comment]
Add `Fate Grand Order` to the scene names.

**Comment by whoamikyo** [comment]
OMG, works!!!

can you ask me another question?

Because even if I put certain words in the ignore list the releases are still listed?

![](https://i.imgur.com/SXLj7k4.png)

**Comment by medariox** [comment]
Manual search **always** lists all releases, because it is a manual action and gives you all the choices. In the "normal" search the words will be effectively ignored.

**Comment by whoamikyo** [comment]
in normal search give this error

2019-10-24 00:04:06 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-353666 :: Nyaa :: [baad1e5] Traceback (most recent call last):
  File "/home/juniorkyo/.medusa/medusa/search/queue.py", line 503, in run
    search_result = search_providers(self.show, self.segment)
  File "/home/juniorkyo/.medusa/medusa/search/core.py", line 711, in search_providers
    [], series_obj, down_cur_quality)
  File "/home/juniorkyo/.medusa/medusa/search/core.py", line 786, in collect_candidates
    single_results = collect_single_candidates(found_results[provider.name], single_results)
  File "/home/juniorkyo/.medusa/medusa/search/core.py", line 831, in collect_single_candidates
    wanted_results = filter_results(candidates[episode])
  File "/home/juniorkyo/.medusa/medusa/search/core.py", line 263, in filter_results
    if not series_obj.release_groups.is_valid(cur_result):
AttributeError: 'NoneType' object has no attribute 'is_valid'
2019-10-24 00:04:06 DEBUG	FORCEDSEARCHQUEUE-BACKLOG-353666 :: Nyaa :: [baad1e5] Transaction with 1 queries executed
2019-10-24 00:04:06 INFO	FORCEDSEARCHQUEUE-BACKLOG-353666 :: Nyaa :: [baad1e5] Performing episode search for Fate/Grand Order - Absolute Demonic Front: Babylonia

**Comment by whoamikyo** [comment]
I can't save  release group too...

![](https://i.imgur.com/EJX4HaO.png)

i add on the field and save, but disappear...


whats the trick?

**Comment by whoamikyo** [comment]
am i doing right?

https://imgur.com/WvxPENj

**Comment by medariox** [comment]
Release groups should be either in the white or blacklist
