### ISSUE TITLE
[BEYOND-HD] - Failed parsing publishing date

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#7292]
Beyond-HD again changed their layout.
```
2019-10-28 16:26:24 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 109.96 GiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 109.96  GiB
2019-10-28 16:26:24 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\torrent\html\beyondhd.py", line 114, in parse
    link = cells[1].find('a')
IndexError: list index out of range
2019-10-28 16:26:24 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 1.74 GiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 1.74  GiB
2019-10-28 16:26:24 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 193.2 GiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 193.2  GiB
2019-10-28 16:26:24 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 735.26 MiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 735.26  MiB
2019-10-28 16:06:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 1.27 GiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 1.27  GiB
2019-10-28 15:46:16 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 2.83 GiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 2.83  GiB
2019-10-28 15:46:16 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 1.95 GiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 1.95  GiB
2019-10-28 15:36:17 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 913.13 MiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 913.13  MiB
2019-10-28 15:16:25 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 410.12 MiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 410.12  MiB
2019-10-28 15:16:25 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 371.75 MiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 371.75  MiB
2019-10-28 15:09:39 ERROR    FINDPROPERS :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 1.16 GiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 1.16  GiB
2019-10-28 14:56:16 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 1.58 GiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 1.58  GiB
2019-10-28 14:56:16 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Beyond-HD] :: [baad1e5] Failed parsing publishing date: 980.09 MiB
Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 603, in parse_pubdate
    raise ValueError('Failed parsing human time: {0} {1}'.format(matched_time, matched_granularity))
ValueError: Failed parsing human time: 980.09  MiB
```

**Comment by p0psicles** [comment]
can you try out develop branch? Or wait for a release.
Think it's fixed in develop

**Comment by Rouzax** [comment]
They have introduced 2 themes which seems to break the support

**Comment by p0psicles** [comment]
Yes I did. As I assumed I was a little premature in claiming it was fixed in develop

**Comment by Rouzax** [comment]
Looks like more fixes are needed, for login they now also need a Captcha so likely Medusa needs to switch to add also the cookie info
See for more info: https://github.com/Jackett/Jackett/issues/6281

**Comment by p0psicles** [comment]
Fixed for both themes. The provider needs to have one cookie set. It's the cookie started with rememember_web_...
