### ISSUE TITLE
Medusa errors out after updating, won't stay running

### ISSUE THREAD

**Issue by Dragonsys** [pymedusa/Medusa#7294]
This is what I get on the screen when trying to launch Medusa:

2019-10-28 20:44:04 INFO     MAIN :: [baad1e5] Broken providers found: [u'torrent9', u'newpct', u'tntvillage']
2019-10-28 20:44:04 WARNING  MAIN :: [baad1e5] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2019-10-28 20:44:04 WARNING  MAIN :: [baad1e5] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2019-10-28 20:44:04 WARNING  MAIN :: [baad1e5] No git specified, can't use git commands
2019-10-28 20:44:04 WARNING  MAIN :: [baad1e5] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2019-10-28 20:44:04 WARNING  MAIN :: [baad1e5] No git specified, can't use git commands
2019-10-28 20:44:05 WARNING  MAIN :: [baad1e5] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2019-10-28 20:44:05 WARNING  MAIN :: [baad1e5] No git specified, can't use git commands
Traceback (most recent call last):
  File "C:\Tools\Medusa\Medusa\SickBeard.py", line 9, in <module>
    main()
  File "C:\Tools\Medusa\Medusa\medusa\__main__.py", line 2199, in main
    application.start(sys.argv[1:])
  File "C:\Tools\Medusa\Medusa\medusa\__main__.py", line 322, in start
    self.initialize(console_logging=self.console_logging)
  File "C:\Tools\Medusa\Medusa\medusa\__main__.py", line 1011, in initialize
    app.APP_VERSION = updater.current_version
  File "C:\Tools\Medusa\Medusa\medusa\updater\github_updater.py", line 53, in current_version
    return cur_version.lstrip('v')
AttributeError: 'NoneType' object has no attribute 'lstrip'

and then it exits
I tried using the below cmds, but they did not help.
git fetch origin
git reset --hard origin/master
[HEAD is now at baad1e5 Merge pull request #7120 from pymedusa/release/release-0.3.5]

**Comment by p0psicles** [comment]
We use a GitHub issue template. You ignored it

**Comment by Dragonsys** [comment]
Sorry, where do I find the template? I will correct it.

**Comment by Dragonsys** [comment]
Sorry, I am fixing that now
