### ISSUE TITLE
ascii decoding

### ISSUE THREAD

**Issue by Aethrios** [pymedusa/Medusa#7318]
**Describe the bug**
From the logfile: 

2019-11-04 19:08:58 ERROR	POSTPROCESSOR :: [baad1e5] Exception generated: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/usr/local/medusa/medusa/process_tv.py", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/usr/local/medusa/medusa/process_tv.py", line 184, in process
    self.log('Processing folder: {0}'.format(dir_path), logger.DEBUG)

**To Reproduce**
Triggers on the first run of the post processor after restarting Medusa - whether manually or on the scheduled timer.

**Expected behavior**
Runs like normal

**Medusa (please complete the following information):**
 - OS: FreeNAS iocage, 11.2-U6
 - Branch: master 0.3.5 - attempting to update says nothing is available
 - commit: baad1e5af59d7f29606c1fed1c110af1424bb117

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-11-04 19:08:58 ERROR    POSTPROCESSOR :: [baad1e5] Exception generated: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/usr/local/medusa/medusa/process_tv.py", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/usr/local/medusa/medusa/process_tv.py", line 184, in process
    self.log('Processing folder: {0}'.format(dir_path), logger.DEBUG)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Checking if we can use git commands: git version
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git version with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git version : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Using: git
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git symbolic-ref -q HEAD with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git symbolic-ref -q HEAD : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git symbolic-ref -q HEAD with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git symbolic-ref -q HEAD : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git rev-parse HEAD with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git rev-parse HEAD : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git config remote.origin.url https://github.com/pymedusa/Medusa with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git config remote.origin.url https://github.com/pymedusa/Medusa : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git config remote.origin.pushurl https://github.com/pymedusa/Medusa with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git config remote.origin.pushurl https://github.com/pymedusa/Medusa : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git fetch --prune origin with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git fetch --prune origin : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git rev-parse --verify --quiet "@{upstream}" : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /usr/local/medusa
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] git rev-list --left-right "@{upstream}"...HEAD : returned successful
2019-11-04 19:23:02 DEBUG    Thread_2 :: [baad1e5] cur_commit = baad1e5af59d7f29606c1fed1c110af1424bb117, newest_commit = baad1e5af59d7f29606c1fed1c110af1424bb117, num_commits_behind = 0, num_commits_ahead = 0
2019-11-04 19:23:03 DEBUG    Thread_2 :: [baad1e5] Searching for issues similar to:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
2019-11-04 19:23:13 DEBUG    Thread_2 :: [baad1e5] Found issue #5304 (UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 175: ordinal not in range(128)) to be similar (90%) to UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
2019-11-04 19:23:13 DEBUG    Thread_2 :: [baad1e5] Found 1 similar issues for 1 log lines.
2019-11-04 19:23:13 DEBUG    Thread_2 :: [baad1e5] Creating gist for error: 2019-11-04 19:08:58 ERROR    POSTPROCESSOR :: [baad1e5] Exception generated: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/usr/local/medusa/medusa/process_tv.py", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/usr/local/medusa/medusa/process_tv.py", line 184, in process
    self.log('Processing folder: {0}'.format(dir_path), logger.DEBUG)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
2019-11-04 19:23:14 DEBUG    Thread_2 :: [baad1e5] Creating issue data for error: 2019-11-04 19:08:58 ERROR    POSTPROCESSOR :: [baad1e5] Exception generated: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/usr/local/medusa/medusa/process_tv.py", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/usr/local/medusa/medusa/process_tv.py", line 184, in process
    self.log('Processing folder: {0}'.format(dir_path), logger.DEBUG)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 109: ordinal not in range(128)
```
</details>

**Additional context**
I did run across this error, but am unsure what correction to take: 

2019-11-04 18:57:41 WARNING  MAIN :: [baad1e5] Your system is using an invalid encoding: US-ASCII. Please change your encoding as soon as possible or you could encounter unexpected issues.

running # locale inside the jail returns: 

root@medusa:~ # locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=

But again, I'm not clear on whether or not this is correct.

**Comment by medariox** [comment]
You need to set LC_ALL as well.

Try with this:
Next we need to set the locale. In my case it's en_US.UTF-8:
```
setenv LANG en_US.UTF-8 && setenv LC_ALL en_US.UTF-8
```

And to make that persistent after reboot:
```
printf "setenv LANG en_US.UTF-8\nsetenv LC_ALL en_US.UTF-8\n" >> /root/.cshrc
```

From https://github.com/Nekmo/amazon-dash/issues/107#issuecomment-439735967

**Comment by Aethrios** [comment]
After posting, I had gone through and set LC_ALL manually, though in a slightly different way, and was still encountering errors. That last line did the trick! Thank you!
> ```
> printf "setenv LANG en_US.UTF-8\nsetenv LC_ALL en_US.UTF-8\n" >> /root/.cshrc
> ```
