### ISSUE TITLE
[APP SUBMITTED]: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by zaans2** [pymedusa/Medusa#7329]
### INFO
**Python Version**: `3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0]`
**Operating System**: `Linux-5.0.0-32-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@baad1e5af59d7f29606c1fed1c110af1424bb117
**Link to Log**: https://gist.github.com/5d4658dcec80f9163648e7883e080446
### ERROR
<pre>
2019-11-09 23:20:21 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Zooqle] :: [baad1e5] DailySearchQueueItem Exception, error: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/**********/**********/search/queue.py", line 266, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/opt/**********/**********/search/core.py", line 533, in search_for_needed_episodes
    found_results = cur_provider.cache.find_needed_episodes(episodes)
  File "/opt/**********/**********/tv/cache.py", line 477, in find_needed_episodes
    cache_results = self.find_episodes(episodes)
  File "/opt/**********/**********/tv/cache.py", line 562, in find_episodes
    sql_results = list(itertools.chain(*sql_results))
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by HtomSirveaux** [comment]
### INFO
**Python Version**: `3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]`
**Operating System**: `Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-03-14 02:18:04 ERROR    SHOWUPDATER :: [ee1b898] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Outlander. Cause: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_updater.py#L147">medusa/show_updater.py</a>", line 147, in run
    update_max_weeks)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L666">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/fallback.py#L135">medusa/indexers/tvdbv2/fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L279">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 279, in _query_series
    results += paged_episodes.data
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MadMungo** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-03-15 04:03:50 ERROR    SHOWUPDATER :: [ee1b898] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Star Trek: Picard. Cause: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_updater.py#L147">medusa\show_updater.py</a>", line 147, in run
    update_max_weeks)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L666">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/fallback.py#L135">medusa\indexers\tvdbv2\fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L279">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 279, in _query_series
    results += paged_episodes.data
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MadMungo** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-03-15 03:51:33 ERROR    SHOWUPDATER :: [ee1b898] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Superstore. Cause: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_updater.py#L147">medusa\show_updater.py</a>", line 147, in run
    update_max_weeks)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L666">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/fallback.py#L135">medusa\indexers\tvdbv2\fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L279">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 279, in _query_series
    results += paged_episodes.data
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by MadMungo** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-03-15 03:45:26 ERROR    SHOWUPDATER :: [ee1b898] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show The Walking Dead. Cause: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_updater.py#L147">medusa\show_updater.py</a>", line 147, in run
    update_max_weeks)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L666">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/fallback.py#L135">medusa\indexers\tvdbv2\fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "G:\Medusa\Medusa\<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L279">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 279, in _query_series
    results += paged_episodes.data
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pmhaustein** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/5282e5b306b37b676e7456cfdbd0683e
### ERROR
<pre>
2020-03-14 02:09:09 ERROR    SHOWUPDATER :: [ee1b898] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Ghost Adventures. Cause: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_updater.py#L147">medusa/show_updater.py</a>", line 147, in run
    update_max_weeks)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L666">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/fallback.py#L86">medusa/indexers/tvdbv2/fallback.py</a>", line 86, in __call__
    return self.func(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L279">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 279, in _query_series
    results += paged_episodes.data
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by doncoque** [comment]
### INFO
**Python Version**: `3.8.1 (default, Dec 30 2019, 15:43:37) [GCC 9.2.0]`
**Operating System**: `Linux-5.3.0-40-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-03-14 04:18:06 ERROR    SHOWUPDATER :: [] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Star Trek: Picard. Cause: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "/app/medusa/medusa/show_updater.py", line 146, in run
    updated_seasons = indexer_api.get_last_updated_seasons([show.indexerid], last_update,
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 666, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "/app/medusa/medusa/indexers/tvdbv2/fallback.py", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 279, in _query_series
    results += paged_episodes.data
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
