### ISSUE TITLE
Impossible to scan subtitles : errors in .py files since the migration to python 3.5

### ISSUE THREAD

**Issue by tomzic59** [pymedusa/Medusa#7346]
A few months ago I migrated to Python 3.5.
Since it is impossible for me to scan the subtitles available on any provider.
I receive the error messages below...

**Medusa (please complete the following information):**
 - OS: Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-debian-8.11
 - Branch: master
 - Commit: 80b323eefca7c8d3c233ded9f389b0af35725f17
 - Python version: 3.5.0 (default, Apr 15 2019, 23:23:34) [GCC 4.9.2]
 - Database version: 44.14

<details>

```
2019-11-13 19:54:12 ERROR    Thread-21 :: [80b323e] Exception generated: db type could not be determined
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/handler.py", line 1802, in manualSearchSubtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/opt/medusa/medusa/subtitles.py", line 340, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/opt/medusa/ext/dogpile/cache/region.py", line 1030, in set
    self.backend.set(key, self._value(value))
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/local/lib/python3.5/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
2019-11-13 19:54:20 WARNING  Thread-18 :: [80b323e] Unexpected error in provider 'tvsubtitles'
Traceback (most recent call last):
  File "/opt/medusa/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/opt/medusa/ext/subliminal/providers/tvsubtitles.py", line 200, in list_subtitles
    show_id = self.search_show_id(title, video.year)
  File "</opt/medusa/ext/decorator.py:decorator-gen-5>", line 2, in search_show_id
  File "/opt/medusa/ext/dogpile/cache/region.py", line 1272, in get_or_create_for_user_func
    should_cache_fn, (arg, kw))
  File "/opt/medusa/ext/dogpile/cache/region.py", line 879, in get_or_create
    async_creator) as value:
  File "/opt/medusa/ext/dogpile/lock.py", line 186, in __enter__
    return self._enter()
  File "/opt/medusa/ext/dogpile/lock.py", line 86, in _enter
    value = value_fn()
  File "/opt/medusa/ext/dogpile/cache/region.py", line 826, in get_value
    value = self.backend.get(key)
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 220, in get
    with self._dbm_file(False) as dbm:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/local/lib/python3.5/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
2019-11-13 19:54:20 WARNING  Thread-18 :: [80b323e] Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/opt/medusa/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/opt/medusa/ext/subliminal/core.py", line 72, in __getitem__
    provider.initialize()
  File "/opt/medusa/ext/subliminal/providers/addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
subliminal.exceptions.AuthenticationError: tomzic59
```
</details>

**Comment by medariox** [comment]
1. Delete the `subliminal.dbm*` files in your `cache` folder.
2. Disable addic7ed provider as it is not working since quite some time and probably can't be fixed, see: https://github.com/Diaoul/subliminal/issues/966

**Comment by tomzic59** [comment]
I did not know about Addi7ed.
I deleted the cache subliminal.dbm file, then restarted medusa service.
But I am still getting the error in logs and can not scan subtitles.

**Comment by p0psicles** [comment]
You disabled addi7ed?

**Comment by tomzic59** [comment]
Yes I disabled addic7ed in "Subtitles Settings", so i do not receive any any errors about it.
But when I run a subtitle scan for an episode, I continue to receive this:
<details>
```
2019-11-14 09:13:50 ERROR    Thread-26 :: [80b323e] Exception generated: db type could not be determined
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 251, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/handler.py", line 1802, in manualSearchSubtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/opt/medusa/medusa/subtitles.py", line 340, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/opt/medusa/ext/dogpile/cache/region.py", line 1030, in set
    self.backend.set(key, self._value(value))
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 237, in set
    with self._dbm_file(True) as dbm:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/opt/medusa/ext/dogpile/cache/backends/file.py", line 215, in _dbm_file
    "w" if write else "r")
  File "/usr/local/lib/python3.5/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```
</details>

**Comment by medariox** [comment]
You need to shut down Medusa first.
Delete all the files that start with `subliminal` in your cache folder.
Start Medusa again.

 We already had this report before and everyone was able to solve the issue by doing this.

**Comment by tomzic59** [comment]
Mine seems to be more persistent.
I did what you said, but I always get the same error when I do a manual scan...

**Comment by Rouzax** [comment]
@medariox and @p0psicles  it looks like they are in the process of creating a API.
http://www.sub-talk.net/topic/7767-automatic-subtitle-download-synchronization/?do=findComment&comment=51384

**Comment by p0psicles** [comment]
I think that when they release their api, it wouldn't take long before it's added to subliminal or we add it as external provider.

**Comment by Forceflow** [comment]
Fwiw, I've been having good results using https://pypi.org/project/addic7ed-cli/ for automated / scripted subtitle grabbing from Addic7ed.

**Comment by p0psicles** [comment]
That would require allot of hacking to get that integrated. Then I'd prefer for them to have added the api. So we can add it as a subtitle provider

**Comment by Forceflow** [comment]
> That would require allot of hacking to get that integrated. Then I'd prefer for them to have added the api. So we can add it as a subtitle provider

Fair enough - do we have an ETA on the addic7ed API?

I'm going to try and add this addic7ed script as a post-processing step using Medusa's existing capabilities. The subliminal dev tree (which I suppose Medusa's also using?) is failing for addic7ed (expected) and sometimes for opensubtitles for me, so some additional attempts to get subtitles must be added :)
