### ISSUE TITLE
Add TVDB2 show fails with invalid imdb id

### ISSUE THREAD

**Issue by ukharley** [pymedusa/Medusa#7383]
Add TVDB2 show fails with invalid imdb id

**Expected behavior**

Show gets added.

**Medusa (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Branch: master
 - Commit:  fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
 - Python version: 3.7.4
 - Database version:  44.14

<details>
```

2019-11-19 10:20:25 INFO     SHOWQUEUE-ADD :: [fcb5a19] Starting to add show by ShowDir: D:\Multimedia\TV_Shows\Cold Call
2019-11-19 10:20:25 INFO     SHOWQUEUE-ADD :: [fcb5a19] TVDBv2: {'language': 'en', 'use_zip': True, 'session': <medusa.session.core.MedusaSession object at 0x0000017BCB186088>, 'cache': 'C:\\GitHub\\Medusa-master\\cache\\indexers\\TVDBv2'}
2019-11-19 10:20:26 INFO     SHOWQUEUE-ADD :: [fcb5a19] 371990: Unable to find the show in the database
2019-11-19 10:20:28 INFO     SHOWQUEUE-ADD :: [fcb5a19] Setting all previously aired episodes to the specified status: Ignored
Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "C:\GitHub\Medusa-master\ext\imdbpie\imdbpie.py", line 279, in validate_imdb_id
    re.match(match_id, imdb_id, re.IGNORECASE).group()
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\GitHub\Medusa-master\medusa\show_queue.py", line 560, in run
    self.show.load_imdb_info()
  File "C:\GitHub\Medusa-master\medusa\tv\series.py", line 1640, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "C:\GitHub\Medusa-master\ext\imdbpie\imdbpie.py", line 77, in get_title
    self.validate_imdb_id(imdb_id)
  File "C:\GitHub\Medusa-master\ext\imdbpie\imdbpie.py", line 281, in validate_imdb_id
    raise ValueError('invalid imdb id')
ValueError: invalid imdb id

```
</details>

**Comment by p0psicles** [comment]
First exception is generated bij imdbpie. Ao you should report this there.

**Comment by medariox** [comment]
Which show are you trying to add?

**Comment by ukharley** [comment]
It's a TVDB issue for the show: https://www.thetvdb.com/series/cold-call
The IMDB link there isn't a valid link: http://www.imdb.com/title/https://www.imdb.com/titl
Therefore, imdb-pie fails.
BTW there is no error or warning with this failure to add the show.

**Comment by medariox** [comment]
Fixed.
