### ISSUE TITLE
Lots of APIv2 warning that continue to come up

### ISSUE THREAD

**Issue by jgeorge1983** [pymedusa/Medusa#7389]
Morning, 

Hope someone can help me, i get the below errors a lot.  The NAS it relates to is always on, the files are there and Medusa has access to the locations as it can create folders there for new TV Shows.  Medusa also runs the service from my local account .\jay as appose to local system or network service.

2019-11-20 18:44:49 WARNING  APIv2-Thread_10 :: [fcb5a19] Unable to get size for file \\192.168.0.19\video\TV Shows\Show Name\Season 09\.thumb\S09E03.mkv.jpg Error: WindowsError(64, 'The specified network name is no longer available')
2019-11-20 18:44:49 WARNING  APIv2-Thread_10 :: [fcb5a19] Unable to get size for file \\192.168.0.19\video\TV Shows\Show Name\Season 09\.thumb\S09E04.mkv.jpg Error: WindowsError(64, 'The specified network name is no longer available')
2019-11-20 18:44:47 WARNING  APIv2-Thread_10 :: [fcb5a19] Unable to get size for file \\192.168.0.19\video\TV Shows\Show Name\Season 09\S09E08.mkv Error: WindowsError(64, 'The specified network name is no longer available')
2019-11-20 18:44:46 WARNING  APIv2-Thread_10 :: [fcb5a19] Unable to get size for file \\192.168.0.19\video\TV Shows\Show Name\Season 09\S09E04.mkv Error: WindowsError(64, 'The specified network name is no longer available')

**Comment by medariox** [comment]
See this: https://social.technet.microsoft.com/Forums/windows/de-DE/7083d98c-ce6c-4007-8bb3-ac5e13805e71/the-specified-network-name-is-no-longer-available?forum=win10itprogeneral

This is not a Medusa issue, we can't really help you.

**Comment by jgeorge1983** [comment]
Thanks for the advice, I'll give it a go.  I'm not sure that will work.  

The drives are mapped in windows via IP address
The folder locations in Medusa are mapped via IP address, not done via drive letter.

That being said I'm always happy to be proved wrong so I will give it a go, thanks for the help Medariox, I'll report back

**Comment by jgeorge1983** [comment]
Unfortunately that didnt make any difference :(

If it helps i now get a full error, could it be wherever it is getting the \\\\ and the \\??

2019-11-21 12:42:39 ERROR    SHOWQUEUE-REFRESH :: [fcb5a19] 359569: Error while refreshing show Good Omens. Error: [Error 64] The specified network name is no longer available: u'\\\\192.168.0.19\\video\\TV Shows\\Good Omens\\Season 01\\S01E06.mkv'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\show_queue.py", line 676, in run
    self.show.refresh_dir()
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 1818, in refresh_dir
    self.load_episodes_from_dir()
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 1079, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 1423, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 2052, in update_status_quality
    self.location = filepath
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 280, in __setattr__
    super(Episode, self).__setattr__(key, value)
  File "C:\Medusa\Medusa\medusa\tv\base.py", line 57, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 402, in location
    self.file_size = os.path.getsize(value) if value and self.is_location_valid(value) else 0
  File "C:\Medusa\Medusa\medusa\init\filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "C:\Medusa\Python\lib\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
  File "C:\Medusa\Medusa\medusa\init\filesystem.py", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
WindowsError: [Error 64] The specified network name is no longer available: u'\\\\192.168.0.19\\video\\TV Shows\\Good Omens\\Season 01\\S01E06.mkv'

**Comment by jgeorge1983** [comment]
For some reason when i copy and paste the error instead of a screenshot it removes "\\" please see the screenshot attached.
![error](https://user-images.githubusercontent.com/34232973/69339436-3510b280-0c5d-11ea-8497-bd6c57276179.PNG)

**Comment by medariox** [comment]
Try using for forward slashes instead. Also, why are you still using Python 2.7?

**Comment by jgeorge1983** [comment]
would I need to re-map all my TV shows?

TBH, pyhon installed with Medusa and I havent touched it since.  Does that need a seperate update to medusa's update?

**Comment by medariox** [comment]
No, just make sure to make a backup.

**Comment by jgeorge1983** [comment]
Sorry for the slow reply but I think I have fixed it.  I created a user on my NAS that mirrors my local user on the Windows machine and since then I havent seen this error again.  Thanks for all your help, I know you dont necessarily supprot direct NAS to Medusa integration but this is a solution to bare in mind!
