### ISSUE TITLE
[APP SUBMITTED]: KeyError: 359264

### ISSUE THREAD

**Issue by akosasante** [pymedusa/Medusa#7414]
### INFO
**Python Version**: `3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.19.55-6-osmc-armv7l-with-debian-9.11`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-11-21 02:00:37 ERROR    SHOWUPDATER :: [fcb5a19] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show The Kenan Show. Cause: KeyError(359264,)
Traceback (most recent call last):
  File "/opt/**********/ext/tvdbapiv2/rest.py", line 54, in request
    r.raise_for_status()
  File "/opt/**********/ext/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/359264/episodes/query?page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/**********/**********/indexers/tvdbv2/tvdbv2_api.py", line 277, in _query_series
    tvdb_id, page=page, accept_language=self.config['language']
  File "/opt/**********/ext/tvdbapiv2/apis/series_api.py", line 468, in series_id_episodes_query_get
    callback=params.get('callback'))
  File "/opt/**********/ext/tvdbapiv2/api_client.py", line 295, in call_api
    response_type, auth_settings, callback)
  File "/opt/**********/ext/tvdbapiv2/api_client.py", line 122, in __call_api
    post_params=post_params, body=body)
  File "/opt/**********/ext/tvdbapiv2/api_client.py", line 315, in request
    headers=headers)
  File "/opt/**********/ext/tvdbapiv2/rest.py", line 70, in get
    query_params=query_params)
  File "/opt/**********/ext/tvdbapiv2/rest.py", line 63, in request
    raise ApiException(status=status, reason=msg)
tvdbapiv2.exceptions.ApiException: (404)
Reason: HTTPError
404 Client Error: Not Found for url: https://tvdb2.plex.tv/series/359264/episodes/query?page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/**********/**********/show_updater.py", line 147, in run
    update_max_weeks)
  File "/opt/**********/**********/indexers/tvdbv2/tvdbv2_api.py", line 657, in get_last_updated_seasons
    episodes = self._query_series(show_id)
  File "/opt/**********/**********/indexers/tvdbv2/fallback.py", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/opt/**********/**********/indexers/tvdbv2/tvdbv2_api.py", line 294, in _query_series
    if error.status == 404 and not self.shows[tvdb_id]['firstaired']:
KeyError: 359264
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Is this a returning error?

**Comment by medariox** [comment]
Probably happened when theTVDB API was down. No response, no support.
