### ISSUE TITLE
Issue searching and snatching shows

### ISSUE THREAD

**Issue by iLlama** [pymedusa/Medusa#7440]
**Describe the bug**
When searching for a show, for about the last week, no shows are snatched. Reviewing the logs, I see "[fcb5a19] Unknown exception in url https://speed.cd/browse.php Error: 'location'" along with with "[fcb5a19] Cloudflare protection detected, trying to bypass it". This happens for on all searches for any show/episode that I have tested with. If I take the "GET URL" for the search and view it in the browser it does return results. 

**To Reproduce**
1. Manual search of any episode/show 
2. No episodes snatched 
3. View logs and observed errors. 

**Expected behavior**
Episode to snatch/download

**Medusa (please complete the following information):**
 - OS: Win7 
 - Branch: master
 - Commit: fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
 - Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
 - Database version:  44.14

**Debug logs (at least 50 lines):**
`2019-12-02 11:12:41 INFO	SEARCHQUEUE-DAILY-SEARCH :: [fcb5a19] No needed episodes found
2019-12-02 11:12:41 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: [fcb5a19] No results to sort.
2019-12-02 11:12:41 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: [fcb5a19] Combining single and multi-episode results
2019-12-02 11:12:41 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] Transaction with 9 queries executed
2019-12-02 11:12:41 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] No data returned from provider
2019-12-02 11:12:41 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\session\core.py", line 155, in request
    timeout=timeout, verify=verify, **kwargs)
  File "C:\Medusa\Medusa\medusa\session\core.py", line 105, in request
    response = handlers.cloudflare(self, response, timeout=timeout, verify=ssl_cert, **kwargs)
  File "C:\Medusa\Medusa\medusa\session\handlers.py", line 43, in cloudflare
    tokens, user_agent = CloudflareScraper.get_tokens(original_request.url)
  File "C:\Medusa\Medusa\ext\cfscrape\__init__.py", line 336, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "C:\Medusa\Medusa\ext\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Medusa\Medusa\ext\cfscrape\__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\Medusa\Medusa\ext\cfscrape\__init__.py", line 195, in solve_cf_challenge
    redirect_location = urlparse(redirect.headers["Location"])
  File "C:\Medusa\Medusa\ext\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
2019-12-02 11:12:41 INFO	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] Unknown exception in url https://speed.cd/browse.php Error: 'location'
2019-12-02 11:12:36 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] Cloudflare protection detected, trying to bypass it.
2019-12-02 11:12:36 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] User-Agent: Medusa/0.3.7 (Windows; 7; c91b588f-14ff-11ea-8870-080027c3822d)
2019-12-02 11:12:36 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] GET URL: https://speed.cd/login.php [Status: 503]
2019-12-02 11:12:36 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] User-Agent: Medusa/0.3.7 (Windows; 7; c91b588f-14ff-11ea-8870-080027c3822d)
2019-12-02 11:12:36 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] GET URL: https://speed.cd/browse.php?c55=1&c52=1&search=&c41=1&c50=1&c2=1&c30=1&c49=1 [Status: 302]
2019-12-02 11:12:36 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] Search mode: RSS
2019-12-02 11:12:36 DEBUG	SEARCHQUEUE-DAILY-SEARCH :: Speedcd :: [fcb5a19] Updating providers cache`

**Comment by medariox** [comment]
Cloudflare updated their challenge. We need to wait for the upstream library to fix this. Sites that use Cloudflare protection may be broken. Try a provider that doesn't use CF protection.

**Comment by medariox** [comment]
Will be fixed when the PR is merged
