### ISSUE TITLE
WARNING  SHOWQUEUE-REFRESH :: [fcb5a19] An error occurred while parsing

### ISSUE THREAD

**Issue by anujpuri85** [pymedusa/Medusa#7441]
Lately, I've been getting constant errors for every show when a new episode is downloaded. The episode downloads automatically, but then it isn't automatically moved to the correct folders, renamed, and updated in Medusa. I get a bunch of the following warning messages:

`2019-12-03 10:23:13 WARNING  SHOWQUEUE-REFRESH :: [fcb5a19] An error occurred while parsing: I:\HD4 Shows\The Good Doctor\The Good Doctor Season 3\The Good Doctor S03E10.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "0:42:19", 
        "muxing_app": "libx264 + libebml + libmatroska + libfastrar", 
        "date_utc": "2019-12-03 03:03:58", 
        "writing_app": "FastLE v3.0.0 - AVS"
    }, 
    "video_tracks": [
        {
            "forced": false, 
            "display_height": 718, 
            "language": "und", 
            "default": true, 
            "aspect_ratio_type": 0, 
            "enabled": true, 
            "number": 1, 
            "crop": {}, 
            "height": 718, 
            "width": 1280, 
            "codec_id": "V_MPEG4/ISO/AVC", 
            "stereo_mode": 0, 
            "lacing": false, 
            "type": 1, 
            "display_width": 1280, 
            "interlaced": false
        }
    ], 
    "tags": [], 
    "chapters": [], 
    "audio_tracks": [
        {
            "forced": false, 
            "language": "und", 
            "default": true, 
            "output_sampling_frequency": 48000.0, 
            "enabled": true, 
            "number": 2, 
            "sampling_frequency": 48000.0, 
            "channels": 6, 
            "codec_id": "A_AC3", 
            "lacing": true, 
            "type": 2
        }
    ], 
    "recurse_seek_head": false, 
    "subtitle_tracks": []
}
+-------------------------------------------------------+
Traceback (most recent call last):
  File "D:\Medusa\Medusa\ext\knowit\api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "D:\Medusa\Medusa\ext\knowit\providers\enzyme.py", line 135, in describe
    video_path=video_path, version=enzyme.__version__, data=json.dumps(data))
  File "D:\Medusa\Python\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "D:\Medusa\Python\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Medusa\Python\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "D:\Medusa\Python\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.timedelta(0, 2539, 662000) is not JSON serializable`

**Medusa (please complete the following information):**
 - OS: Windows 10
 - Branch: Master
 - Commit: fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
 - Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-12-03 10:33:29 INFO	Thread-59 :: [fcb5a19] No update needed
2019-12-03 10:23:13 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Cache check completed
2019-12-03 10:23:13 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Trying to clean any empty folder under I:\HD4 Shows\The Good Doctor
2019-12-03 10:23:13 WARNING	SHOWQUEUE-REFRESH :: [fcb5a19] An error occurred while parsing: I:\HD4 Shows\The Good Doctor\The Good Doctor Season 3\The Good Doctor S03E10.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "0:42:19", 
        "muxing_app": "libx264 + libebml + libmatroska + libfastrar", 
        "date_utc": "2019-12-03 03:03:58", 
        "writing_app": "FastLE v3.0.0 - AVS"
    }, 
    "video_tracks": [
        {
            "forced": false, 
            "display_height": 718, 
            "language": "und", 
            "default": true, 
            "aspect_ratio_type": 0, 
            "enabled": true, 
            "number": 1, 
            "crop": {}, 
            "height": 718, 
            "width": 1280, 
            "codec_id": "V_MPEG4/ISO/AVC", 
            "stereo_mode": 0, 
            "lacing": false, 
            "type": 1, 
            "display_width": 1280, 
            "interlaced": false
        }
    ], 
    "tags": [], 
    "chapters": [], 
    "audio_tracks": [
        {
            "forced": false, 
            "language": "und", 
            "default": true, 
            "output_sampling_frequency": 48000.0, 
            "enabled": true, 
            "number": 2, 
            "sampling_frequency": 48000.0, 
            "channels": 6, 
            "codec_id": "A_AC3", 
            "lacing": true, 
            "type": 2
        }
    ], 
    "recurse_seek_head": false, 
    "subtitle_tracks": []
}
+-------------------------------------------------------+
Traceback (most recent call last):
  File "D:\Medusa\Medusa\ext\knowit\api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "D:\Medusa\Medusa\ext\knowit\providers\enzyme.py", line 135, in describe
    video_path=video_path, version=enzyme.__version__, data=json.dumps(data))
  File "D:\Medusa\Python\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "D:\Medusa\Python\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Medusa\Python\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "D:\Medusa\Python\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.timedelta(0, 2539, 662000) is not JSON serializable
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2019-12-03 10:23:06 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] 328634: Performing refresh on The Good Doctor
2019-12-03 10:22:17 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Cache check completed
2019-12-03 10:22:17 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Trying to clean any empty folder under I:\HD4 Shows\Silicon Valley
2019-12-03 10:22:17 WARNING	SHOWQUEUE-REFRESH :: [fcb5a19] An error occurred while parsing: I:\HD4 Shows\Silicon Valley\Silicon Valley Season 6\Silicon Valley S06E06.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
2019-12-03 10:22:09 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] 277165: Performing refresh on Silicon Valley
2019-12-03 10:20:10 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Cache check completed
2019-12-03 10:20:10 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Trying to clean any empty folder under I:\HD4 Shows\Black Lightning
2019-12-03 10:20:09 WARNING	SHOWQUEUE-REFRESH :: [fcb5a19] An error occurred while parsing: I:\HD4 Shows\Black Lightning\Black Lightning Season 3\Black Lightning S03E08.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "0:41:18", 
        "muxing_app": "libebml v1.3.3 + libmatroska v1.4.4", 
        "date_utc": "2019-12-03 04:28:15", 
        "writing_app": "mkvmerge v8.8.0 ('Wind at my back') 64bit"
    }, 
    "video_tracks": [
        {
            "forced": false, 
            "display_height": 720, 
            "language": "und", 
            "default": true, 
2019-12-03 10:20:08 WARNING	SHOWQUEUE-REFRESH :: [fcb5a19] An error occurred while parsing: I:\HD4 Shows\Black Lightning\Black Lightning Season 3\Black Lightning S03E07.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "0:41:16", 
        "muxing_app": "libebml v1.3.5 + libmatroska v1.4.8", 
        "date_utc": "2019-11-26 15:24:20", 
        "writing_app": "mkvmerge v19.0.0 ('Brave Captain') 64-bit"
    }, 
    "video_tracks": [
        {
            "forced": false, 
            "display_height": 720, 
            "language": "und", 
            "default": true, 
            "aspect_ratio_type": 0, 
            "enabled": true, 
            "number": 1, 
            "crop": {}, 
            "height": 720, 
            "width": 1280, 
            "codec_id": "V_MPEG4/ISO/AVC", 
            "stereo_mode": 0, 
            "lacing": false, 
            "type": 1, 
            "display_width": 1280, 
            "interlaced": false
        }
    ], 
    "tags": [
        {
            "simpletags": [
                {
                    "default": 1, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "4716356"
                }, 
                {
                    "default": 1, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "00:41:16.016000000"
                }, 
                {
                    "default": 1, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "59365"
                }, 
                {
                    "default": 1, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "1459721653"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v19.0.0 ('Brave Captain') 64-bit"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2019-11-26 15:24:20"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TargetTypeValue", 
                    "level": 4, 
                    "data": 50, 
                    "position": 1658497685, 
                    "type": 1, 
                    "id": 26826, 
                    "size": 1
                }, 
2019-12-03 10:20:02 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] 332525: Performing refresh on Black Lightning
2019-12-03 10:18:48 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Cache check completed
2019-12-03 10:18:47 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] 73762: Updating NFOs for show with new indexer info
2019-12-03 10:18:47 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Trying to clean any empty folder under L:\HD7 Shows\Grey's Anatomy
2019-12-03 10:18:29 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] 73762: Performing refresh on Grey's Anatomy
2019-12-03 10:18:28 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Cache check completed
2019-12-03 10:18:27 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Selected poster for series 73762 (score=3.46694251968, score_bay=5.93388503936, rating=6.5, votes=3317, res=680x1000): https://www.thetvdb.com/banners/posters/73762-9.jpg
2019-12-03 10:18:27 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Selected fanart for series 73762 (score=3.31942272814, score_bay=5.63884545629, rating=6.2, votes=1521, res=1920x1080): https://www.thetvdb.com/banners/fanart/original/73762-44.jpg
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Copying from L:\HD7 Shows\Grey's Anatomy\backdrop.jpg to D:\Medusa\Data\cache\images\tvdb\73762.fanart.jpg
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Copying from L:\HD7 Shows\Grey's Anatomy\folder.jpg to D:\Medusa\Data\cache\images\tvdb\73762.poster.jpg
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Copying from L:\HD7 Shows\Grey's Anatomy\banner.jpg to D:\Medusa\Data\cache\images\tvdb\73762.banner.jpg
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Removed fanart for series Grey's Anatomy
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Removed poster_thumb for series Grey's Anatomy
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Removed banner_thumb for series Grey's Anatomy
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Removed poster for series Grey's Anatomy
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] Removed banner for series Grey's Anatomy
2019-12-03 10:18:26 INFO	SHOWQUEUE-UPDATE :: [fcb5a19] 73762: Replacing images for show Grey's Anatomy
2019-12-03 10:17:33 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Cache check completed
2019-12-03 10:17:32 INFO	SHOWQUEUE-REFRESH :: [fcb5a19] Trying to clean any empty folder under L:\HD7 Shows\Grey's Anatomy
2019-12-03 10:16:52 WARNING	SHOWQUEUE-REFRESH :: [fcb5a19] An error occurred while parsing: L:\HD7 Shows\Grey's Anatomy\Grey's Anatomy Season 12\Grey's Anatomy S12E20.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
```
</details>

**Comment by medariox** [comment]
Problem is with knowit. Please report it upstream: https://github.com/ratoaq2/knowit/issues
You can try removing mediainfo and installing ffmpeg instead.
