### ISSUE TITLE
Unable to add torrents after qBittorrent update to 4.2

### ISSUE THREAD

**Issue by pax0707** [pymedusa/Medusa#7473]
Medusa Info: | Branch: masterCommit: 8b7f433d4dce89058a8b9b62cc9bcd7a162a3344Version: 0.3.8Database: 44.14
-- | --
Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2o 27 Mar 2018
OS: | Windows-10-10.0.18362
Locale: | en_US.cp1252

Adding torrents not working after updating qBittorrent to 4.2.
Looks like they changed something in API.

```
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Sorting the following results: [u'The.Flash.2014.S06E09.720p.WEB.h264-TRUMP', u'The.Purge.S02E09.iNTERNAL.720p.WEB.h264-TRUMP', u'The.Purge.S02E09.720p.WEBRip.x264-TBS', u'Treadstone.S01E09.iNTERNAL.720p.WEB.h264-TRUMP', u'Treadstone.S01E09.720p.WEBRip.x264-TBS', u'The.Flash.2014.S06E09.720p.HDTV.x264-CRAVERS', u'Emergence.S01E09.720p.HDTV.x264-AVS', u'Treadstone.S01E09.The.Seoul.Asylum.720p.HDTV.x264-CRiMSON']
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Computed result scores:
Score  Release
100.00 The.Flash.2014.S06E09.720p.WEB.h264-TRUMP
100.00 The.Purge.S02E09.iNTERNAL.720p.WEB.h264-TRUMP
100.00 The.Purge.S02E09.720p.WEBRip.x264-TBS
100.00 Treadstone.S01E09.iNTERNAL.720p.WEB.h264-TRUMP
100.00 Treadstone.S01E09.720p.WEBRip.x264-TBS
100.00 The.Flash.2014.S06E09.720p.HDTV.x264-CRAVERS
100.00 Emergence.S01E09.720p.HDTV.x264-AVS
100.00 Treadstone.S01E09.The.Seoul.Asylum.720p.HDTV.x264-CRiMSON
2019-12-11 14:20:03 INFO     SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Picked The.Flash.2014.S06E09.720p.WEB.h264-TRUMP as the best result.
2019-12-11 14:20:03 INFO     SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Quality of Castle.Rock.S02E10.Clean.720p.HULU.WEB-DL.DD+5.1.H.264-AJP69 is 720p WEB-DL
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] 331600: Allowed, Preferred = [ 720p HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ 720p WEB-DL ]
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] 331600: 'Castle Rock' S02E10 status is: 'Wanted'. Accepting result with quality '720p WEB-DL'. Reason: Current status is 'WANTED'. Accepting result with quality '720p WEB-DL'
2019-12-11 14:20:03 INFO     SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Episodes [10] of season 2 are needed with this quality for Castle Rock
2019-12-11 14:20:03 INFO     SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Quality of Castle.Rock.S02E10.720p.WEBRip.x264-TBS is 720p WEB-DL
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] 331600: Allowed, Preferred = [ 720p HDTV, 720p WEB-DL, 720p BluRay ] [ None ] Found = [ 720p WEB-DL ]
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] 331600: 'Castle Rock' S02E10 status is: 'Wanted'. Accepting result with quality '720p WEB-DL'. Reason: Current status is 'WANTED'. Accepting result with quality '720p WEB-DL'
2019-12-11 14:20:03 INFO     SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Episodes [10] of season 2 are needed with this quality for Castle Rock
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Found wanted results.
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Sorting the following results: [u'Castle.Rock.S02E10.Clean.720p.HULU.WEB-DL.DD+5.1.H.264-AJP69', u'Castle.Rock.S02E10.720p.WEBRip.x264-TBS']
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Computed result scores:
Score  Release
100.00 Castle.Rock.S02E10.Clean.720p.HULU.WEB-DL.DD+5.1.H.264-AJP69
100.00 Castle.Rock.S02E10.720p.WEBRip.x264-TBS
2019-12-11 14:20:03 INFO     SEARCHQUEUE-DAILY-SEARCH :: [MoreThanTV] :: [8b7f433] Picked Castle.Rock.S02E10.Clean.720p.HULU.WEB-DL.DD+5.1.H.264-AJP69 as the best result.
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [8b7f433] Combining single and multi-episode results
2019-12-11 14:20:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [8b7f433] No results to sort.
2019-12-11 14:20:03 INFO     SEARCHQUEUE-DAILY-SEARCH :: [8b7f433] Downloading The.Flash.2014.S06E09.Crisis.on.Infinite.Earths.Part.3.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb with 10 seeders and 0 leechers and size 1.25 GB from Beyond-HD
2019-12-11 14:20:04 INFO     SNATCHQUEUE-SNATCH-279121 :: [8b7f433] Beginning to snatch release: The.Flash.2014.S06E09.Crisis.on.Infinite.Earths.Part.3.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2019-12-11 14:20:04 INFO     SNATCHQUEUE-SNATCH-279121 :: [8b7f433] Downloading The.Flash.2014.S06E09.Crisis.on.Infinite.Earths.Part.3.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb with 10 seeders and 0 leechers and size 1.25 GB from Beyond-HD, through a SearchType.DAILY_SEARCH search
2019-12-11 14:20:04 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] GET URL: https://beyond-hd.me/ [Status: 200]
2019-12-11 14:20:04 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] GET URL: https://beyond-hd.me/download/the-flash-2014-s06e09-crisis-on-infinite-earths-part-3-720p-amzn-web-dl-ddp51-h264-ntb.44196 [Status: 200]
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] Calling qbittorrent Client
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] POST URL: https://172.16.1.7:9098/api/v2/auth/login [Status: 403]
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] With post data: username=**********&password=**********
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] GET URL: https://172.16.1.7:9098/api/v2/app/webapiVersion [Status: 403]
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:05 ERROR    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] qbittorrent: Unable to get API version. Error: ValueError("invalid literal for int() with base 10: ''",)
Traceback (most recent call last):
  File "D:\Plex\Medusa\medusa\clients\torrent\qbittorrent.py", line 47, in api
    version = list(map(int, version.text.split('.')))
ValueError: invalid literal for int() with base 10: ''
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] GET URL: https://172.16.1.7:9098/version/api [Status: 404]
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] qbittorrent: Requested a POST connection to https://172.16.1.7:9098/command/upload with params: None Data: None Files: {u'torrents': (u'The.Flash.2014.S06E09.Crisis.on.Infinite.Earths.Part.3.720p.AMZN.WEB-DL.DDP5.1.H.2...
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] POST URL: https://172.16.1.7:9098/command/upload [Status: 404]
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:05 DEBUG    SNATCHQUEUE-SNATCH-279121 :: [8b7f433] With post data: --408d4425032a65a702a530d394272293
 Content-Disposition: form-data; name="torrents"; filename="The....
2019-12-11 14:20:05 INFO     SNATCHQUEUE-SNATCH-279121 :: [8b7f433] qbittorrent: Not Found
2019-12-11 14:20:05 WARNING  SNATCHQUEUE-SNATCH-279121 :: [8b7f433] qbittorrent: Unable to send Torrent
2019-12-11 14:20:05 INFO     SEARCHQUEUE-DAILY-SEARCH :: [8b7f433] Downloading Castle.Rock.S02E10.Clean.720p.HULU.WEB-DL.DD+5.1.H.264-AJP69 with 7 seeders and 0 leechers and size 722.79 MB from Beyond-HD
2019-12-11 14:20:07 INFO     SEARCHQUEUE-DAILY-SEARCH :: [8b7f433] Downloading Patriot.Act.with.Hasan.Minhaj.S05E05.Dont.Ignore.the.Asian.Vote.in.2020.1080p.NF.WEB-DL.DDP2.0.x264-GLUE with 5 seeders and 0 leechers and size 1.10 GB from Beyond-HD
2019-12-11 14:20:10 INFO     SNATCHQUEUE-SNATCH-331600 :: [8b7f433] Beginning to snatch release: Castle.Rock.S02E10.Clean.720p.HULU.WEB-DL.DD+5.1.H.264-AJP69
2019-12-11 14:20:10 INFO     SNATCHQUEUE-SNATCH-331600 :: [8b7f433] Downloading Castle.Rock.S02E10.Clean.720p.HULU.WEB-DL.DD+5.1.H.264-AJP69 with 7 seeders and 0 leechers and size 722.79 MB from Beyond-HD, through a SearchType.DAILY_SEARCH search
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] GET URL: https://beyond-hd.me/ [Status: 200]
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] GET URL: https://beyond-hd.me/download/castle-rock-s02e10-clean-720p-hulu-web-dl-dd5-1-h264-ajp69.44177 [Status: 200]
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] Calling qbittorrent Client
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] POST URL: https://172.16.1.7:9098/api/v2/auth/login [Status: 403]
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] With post data: username=**********&password=**********
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] GET URL: https://172.16.1.7:9098/api/v2/app/webapiVersion [Status: 403]
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:11 ERROR    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] qbittorrent: Unable to get API version. Error: ValueError("invalid literal for int() with base 10: ''",)
Traceback (most recent call last):
  File "D:\Plex\Medusa\medusa\clients\torrent\qbittorrent.py", line 47, in api
    version = list(map(int, version.text.split('.')))
ValueError: invalid literal for int() with base 10: ''
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] GET URL: https://172.16.1.7:9098/version/api [Status: 404]
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] qbittorrent: Requested a POST connection to https://172.16.1.7:9098/command/upload with params: None Data: None Files: {u'torrents': (u'Castle.Rock.S02E10.Clean.720p.HULU.WEB-DL.DD+5.1.H.264-AJP69.torrent', 'd8:announc...
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] POST URL: https://172.16.1.7:9098/command/upload [Status: 404]
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:11 DEBUG    SNATCHQUEUE-SNATCH-331600 :: [8b7f433] With post data: --c5eeae6d90a0a7c863b06c7c3096ad25
 Content-Disposition: form-data; name="torrents"; filename="Cast...
2019-12-11 14:20:11 INFO     SNATCHQUEUE-SNATCH-331600 :: [8b7f433] qbittorrent: Not Found
2019-12-11 14:20:11 WARNING  SNATCHQUEUE-SNATCH-331600 :: [8b7f433] qbittorrent: Unable to send Torrent
2019-12-11 14:20:13 INFO     SNATCHQUEUE-SNATCH-351269 :: [8b7f433] Beginning to snatch release: Patriot.Act.with.Hasan.Minhaj.S05E05.Dont.Ignore.the.Asian.Vote.in.2020.1080p.NF.WEB-DL.DDP2.0.x264-GLUE
2019-12-11 14:20:13 INFO     SNATCHQUEUE-SNATCH-351269 :: [8b7f433] Downloading Patriot.Act.with.Hasan.Minhaj.S05E05.Dont.Ignore.the.Asian.Vote.in.2020.1080p.NF.WEB-DL.DDP2.0.x264-GLUE with 5 seeders and 0 leechers and size 1.10 GB from Beyond-HD, through a SearchType.DAILY_SEARCH search
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] GET URL: https://beyond-hd.me/ [Status: 200]
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] GET URL: https://beyond-hd.me/download/patriot-act-with-hasan-minhaj-s05e05-dont-ignore-the-asian-vote-in-2020-1080p-nf-web-dl-ddp20-x264-glue.44168 [Status: 200]
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] Calling qbittorrent Client
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] POST URL: https://172.16.1.7:9098/api/v2/auth/login [Status: 403]
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] With post data: username=**********&password=**********
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] GET URL: https://172.16.1.7:9098/api/v2/app/webapiVersion [Status: 403]
2019-12-11 14:20:14 DEBUG    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] User-Agent: Medusa/0.3.8 (Windows; 10; 7dd83070-1ba7-11ea-8977-001fd0a2a684)
2019-12-11 14:20:14 ERROR    SNATCHQUEUE-SNATCH-351269 :: [8b7f433] qbittorrent: Unable to get API version. Error: ValueError("invalid literal for int() with base 10: ''",)
Traceback (most recent call last):
  File "D:\Plex\Medusa\medusa\clients\torrent\qbittorrent.py", line 47, in api
    version = list(map(int, version.text.split('.')))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by sharkykh** [comment]
https://github.com/pymedusa/Medusa/issues/3134#issuecomment-562262927

**Comment by pax0707** [comment]
Sorry, I didn't see my reports went there.
