### ISSUE TITLE
Emby notifications in docker version

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#7486]
I have Medusa running on Ubuntu server 18.04 installed in conventional way and working fine.

I decided to try to change to docker version:

Medusa Info:	Branch: master
Commit: d0c136d7a528a471b51676140bd35d24d97f65c6
Version: 0.3.9
Database: 44.14
 Python Version:	3.7.5 (default, Nov 15 2019, 03:17:07) [GCC 8.3.0]
 SSL Version:	OpenSSL 1.1.1d 10 Sep 2019
 OS:	Linux-4.15.0-58-generic-x86_64-with
 Locale:	en_US.UTF-8

Everything is working OK with one exception - Emby notifications. The following error is in the logs:

Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 251, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/handler.py", line 434, in testEMBY
    result = notifiers.emby_notifier.test_notify(unquote_plus(host), emby_apikey)
  File "/app/medusa/medusa/notifiers/emby.py", line 80, in test_notify
    return self._notify_emby('This is a test notification from Medusa', host, emby_apikey)
  File "/app/medusa/medusa/notifiers/emby.py", line 60, in _notify_emby
    log.debug('EMBY: HTTP response: {0}', resp.content.replace('\n', ''))
TypeError: a bytes-like object is required, not 'str'

And:

2019-12-14 15:28:19 WARNING  Thread_1 :: [d0c136d] EMBY: Warning: Unable to contact Emby at http://192.168.1.2:8096/emby/Notifications/Admin: Error: MaxRetryError("HTTPConnectionPool(host='192.168.1.2', port=8096): Max retries exceeded with url: /emby/Notifications/Admin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4915cc5950>, 'Connection to 192.168.1.2 timed out. (connect timeout=30)'))")

No clues in the Emby log.

Thanks

**Comment by johnvick** [comment]
Tested a bit further:

Having the Emby address as 192.168.1.2:8096 does not work.
Having it as myname.mydns.net:8096 does work. 
So maybe not Medusa but a docker thing?

**Comment by sharkykh** [comment]
Looks like the first error **is** related to Medusa. It won't fix the timeout, but still...

**Comment by johnvick** [comment]
For what it's worth I tested this a lot yesterday and the Medusa error above only appeared once.
