### ISSUE TITLE
[HD-Torrents] not working Unknown exception in url https://hd-torrents.org/torrents.php Error: 'location'

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#7493]
**Describe the bug**
HD-Torrents is not working anymore.

Medusa Info: | Branch: masterCommit: d0c136d7a528a471b51676140bd35d24d97f65c6Version: 0.3.9Database: 44.14
-- | --
Python Version: | 3.7.4 (tags/v3.7.4:e09359112e, Jul 8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1c 28 May 2019
OS: | Windows-10-10.0.17763-SP0
Locale: | nl_NL.cp1252

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2019-12-15 09:43:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: [d0c136d] Updating providers cache
2019-12-15 09:43:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: [d0c136d] Search mode: RSS
2019-12-15 09:43:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: [d0c136d] GET URL: https://hd-torrents.org/torrents.php?search=&active=1&options=0&category%5B0%5D=59&category%5B1%5D=60&category%5B2%5D=30&category%5B3%5D=38&category%5B4%5D=65 [Status: 503]
2019-12-15 09:43:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: [d0c136d] User-Agent: Medusa/0.3.9 (Windows; 10; 3f214f0a-1cf4-11ea-a992-00155d02b401)
2019-12-15 09:43:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: [d0c136d] Cloudflare protection detected, trying to bypass it.
2019-12-15 09:43:35 INFO     SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: [d0c136d] Unknown exception in url https://hd-torrents.org/torrents.php Error: 'location'
2019-12-15 09:43:35 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: [d0c136d] Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\session\core.py", line 155, in request
    timeout=timeout, verify=verify, **kwargs)
  File "C:\GitHub\Medusa\medusa\session\core.py", line 105, in request
    response = handlers.cloudflare(self, response, timeout=timeout, verify=ssl_cert, **kwargs)
  File "C:\GitHub\Medusa\medusa\session\handlers.py", line 43, in cloudflare
    tokens, user_agent = CloudflareScraper.get_tokens(original_request.url)
  File "C:\GitHub\Medusa\ext\cfscrape\__init__.py", line 336, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "C:\GitHub\Medusa\ext\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\GitHub\Medusa\ext\cfscrape\__init__.py", line 128, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\GitHub\Medusa\ext\cfscrape\__init__.py", line 195, in solve_cf_challenge
    redirect_location = urlparse(redirect.headers["Location"])
  File "C:\GitHub\Medusa\ext\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

```
</details>

**Additional context**
Can provide access, reach out to me on discord

**Comment by medariox** [comment]
Same reason as https://github.com/pymedusa/Medusa/issues/7440
