### ISSUE TITLE
change address in jackett provider

### ISSUE THREAD

**Issue by zorrax2b** [pymedusa/Medusa#7536]
**Describe the bug**
I changed the address of the jackett server. Since that the old address is still use when I tried to dl something (the xxx.ddns.net is not available in log)

**To Reproduce**
1. change address of jackett provider
2. Click on 'save'
3. Go to a serie or anime
4. try to dl an episode
5. check log error

**Screenshots**
https://ibb.co/82NC1kh

**Medusa (please complete the following information):**
Medusa Info: | Branch: master
Commit: d0c136d7a528a471b51676140bd35d24d97f65c6
Version: 0.3.9
Database: 44.14
-- | --
Python Version: | 2.7.9 (default, Jun 21 2019, 00:38:53) [GCC 4.9.2]
SSL Version: | 
OpenSSL 1.0.1t 3 May 2016
OS: | Linux-3.16.0-9-amd64-x86_64-with-Debian-8
Locale: | fr_FR.UTF-8

**Debug logs (at least 50 lines):**
```
SNATCHQUEUE-SNATCH-361753 :: [d0c136d] Failed to download any results for The.Mandalorian.S01E03.FRENCH.720p.WEB-DL.DDP5.1.H264-NEO
2019-12-28 18:39:39 INFO	SNATCHQUEUE-SNATCH-361753 :: [d0c136d] Downloading The.Mandalorian.S01E03.FRENCH.720p.WEB-DL.DDP5.1.H264-NEO from xxxx at http://**********.ddns.net:9117/dl/xxx/?jackett_apikey=k1euk0m5oj568mwspfogko17c0xadb3u&path=QZ3&file=The.Mandalorian.S01E03.FRENCH.720p.WEB-DL.DDP5.1.H264-NEO
2019-12-28 18:39:39 INFO	SNATCHQUEUE-SNATCH-361753 :: [d0c136d] Downloading The.Mandalorian.S01E03.FRENCH.720p.WEB-DL.DDP5.1.H264-NEO with 25 seeders and 28 leechers and size 1.10 GB from Xthor, through a SearchType.MANUAL_SEARCH search
2019-12-28 18:39:39 INFO	SNATCHQUEUE-SNATCH-361753 :: [d0c136d] Beginning to snatch release: The.Mandalorian.S01E03.FRENCH.720p.WEB-DL.DDP5.1.H264-NEO
```
</details>

**Comment by p0psicles** [comment]
I'm not sure what the issue is. Is it using an old download url, after you changed the address.

Or is the new address not stored?

Could be you need to force a new search for the episode to get the download url?

**Comment by zorrax2b** [comment]
I tested a lot of thing
yes, it is using an old dl url after I chnaged the address.
it seems that the new address is not well stored

- I removed the jackett provider and created a new one but same thing
- I restart Medusa
- I checked for several series
- I force/rescan a new search
- 

but nothing works

**Comment by medariox** [comment]
This is almost always a caching issue. If you remove your `cache.db` does it work? You can also just move it and restore it later.

**Comment by zorrax2b** [comment]
nope 
since I remove cache.db

` SEARCHQUEUE-DAILY-SEARCH :: [ygg2] :: [d0c136d] DB error: OperationalError('attempt to write a readonly database',)
Traceback (most recent call last):
  File "/var/www/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OperationalError: attempt to write a readonly database
2019-12-28 20:42:05 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [ygg2] :: [d0c136d] DailySearchQueueItem Exception, error: OperationalError('attempt to write a readonly database',)
Traceback (most recent call last):
  File "/var/www/medusa/medusa/search/queue.py", line 266, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/var/www/medusa/medusa/search/core.py", line 526, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "/var/www/medusa/medusa/tv/cache.py", line 231, in update_cache
    self.updated = search_start_time
  File "/var/www/medusa/medusa/tv/cache.py", line 341, in updated
    self._set_time('last_update', value)
  File "/var/www/medusa/medusa/tv/cache.py", line 377, in _set_time
    {'provider': self.provider_id}
  File "/var/www/medusa/medusa/db.py", line 355, in upsert
    self.action(query, list(itervalues(valueDict)) + list(itervalues(keyDict)))
  File "/var/www/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/var/www/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OperationalError: attempt to write a readonly database
2019-12-28 20:42:05 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [ygg2] :: [d0c136d] DB error: Error: 'attempt to write a readonly database'
Traceback (most recent call last):
  File "/var/www/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/var/www/medusa/medusa/db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
OperationalError: attempt to write a readonly database`

**Comment by medariox** [comment]
1. Shut down Medusa
2. Delete the cache.db
3. Start Medusa

**Comment by medariox** [comment]
Also, in case you don't know:
1. You are using an unsupported Python version
2. We have Yggtorrent as inbuilt provider and it works perfectly fine

**Comment by zorrax2b** [comment]
okay it seems working
I removed all cache files (2 files cache.db.vx.NONE )
I update my python version (I saw that the version is old)
I used jackett for other provider not only ygg

**Comment by medariox** [comment]
Glad to hear that.

The only cache used is the cache.db, the others are backups, but you can't delete the DB while Medusa is running.
