### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by angrywar** [pymedusa/Medusa#7540]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@d0c136d7a528a471b51676140bd35d24d97f65c6
**Link to Log**: **No Log available**
### ERROR
<pre>
2019-12-24 06:40:25 ERROR    TORNADO :: [d0c136d] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/series/tvdb250487/asset/posterThumb?api_key=********** (127.0.0.1)
Traceback (most recent call last):
  File "C:\**********\ext\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\**********\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\**********\ext\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\**********\medusa\server\api\v2\base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\**********\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\**********\medusa\server\api\v2\series_asset.py", line 37, in get
    media = asset.media
  File "C:\**********\medusa\media\generic.py", line 70, in media
    return content.read()
PermissionError: [Errno 13] Permission denied
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
File permission issue with your cache folder

**Comment by angrywar** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@942040af95311a71d9663236c7136434b6711ca5
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-01-22 21:04:07 ERROR    TORNADO :: [942040a] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/series/tvdb250487/asset/posterThumb?api_key=********** (127.0.0.1)
Traceback (most recent call last):
  File "C:\**********\ext\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\**********\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\**********\ext\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\**********\medusa\server\api\v2\base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\**********\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\**********\medusa\server\api\v2\series_asset.py", line 37, in get
    media = asset.media
  File "C:\**********\medusa\media\generic.py", line 70, in media
    return content.read()
PermissionError: [Errno 13] Permission denied
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
