### ISSUE TITLE
qBittorrent Authentication Failed - Except it doesn't

### ISSUE THREAD

**Issue by ZMOT7S** [pymedusa/Medusa#7595]
**Describe the bug**
When I search and medusa sends the download, I get the error qBittorrent: Authentication failed. 

When I go to settings and test qbittorrent, it's successful and connected. See image below.

**To Reproduce**
1. Click on show
2. Click download button
3. Check logs

**Expected behavior**
The show should download

**Screenshots**
https://i.imgur.com/x7TzyTW.png

**Medusa (please complete the following information):**
 - OS: ubuntu 18.04.3 LTS
 - Branch: master
 - Commit: 942040af95311a71d9663236c7136434b6711ca5
 - Python version: 3.6.9
 - Database version: 44.14

**Debug logs (at least 50 lines):**

```
2020-01-17 19:09:32 WARNING	SNATCHQUEUE-SNATCH-80337 :: [942040a] qBittorrent: Authentication Failed
2020-01-17 19:09:32 WARNING	SNATCHQUEUE-SNATCH-80337 :: [942040a] qBittorrent: Exception while trying to authenticate: Invalid URL 'api/v2/auth/login': No schema supplied. Perhaps you meant http://api/v2/auth/login?
Traceback (most recent call last):
  File "/opt/medusa/medusa/clients/torrent/qbittorrent.py", line 90, in _get_auth_v2
    self.response = self.session.post(self.url, data=data, verify=app.TORRENT_VERIFY_CERT)
  File "/opt/medusa/ext/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/medusa/medusa/session/core.py", line 104, in request
    timeout=timeout, verify=ssl_cert, **kwargs)
  File "/opt/medusa/ext/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/opt/medusa/ext/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/medusa/ext/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/opt/medusa/ext/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'api/v2/auth/login': No schema supplied. Perhaps you meant http://api/v2/auth/login?
2020-01-17 19:09:31 INFO	SNATCHQUEUE-SNATCH-80337 :: [942040a] Downloading Mad.Men.S03.720p.BluRay.x264-EbP with 4 seeders and 1 leechers and size 29.10 GB from IPTorrents, through a SearchType.MANUAL_SEARCH search
2020-01-17 19:09:31 INFO	SNATCHQUEUE-SNATCH-80337 :: [942040a] Beginning to snatch release: Mad.Men.S03.720p.BluRay.x264-EbP
2020-01-17 19:09:26 WARNING	APIv2-Thread-19 :: [942040a] Config patch ignored {'showDefaults': {'subtitles': False}, 'layout': {'historyLimit': 100}}
2020-01-17 19:05:23 WARNING	SNATCHQUEUE-SNATCH-80337 :: [942040a] qBittorrent: Authentication Failed
2020-01-17 19:05:23 WARNING	SNATCHQUEUE-SNATCH-80337 :: [942040a] qBittorrent: Exception while trying to authenticate: Invalid URL 'api/v2/auth/login': No schema supplied. Perhaps you meant http://api/v2/auth/login?
Traceback (most recent call last):
  File "/opt/medusa/medusa/clients/torrent/qbittorrent.py", line 90, in _get_auth_v2
    self.response = self.session.post(self.url, data=data, verify=app.TORRENT_VERIFY_CERT)
  File "/opt/medusa/ext/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/medusa/medusa/session/core.py", line 104, in request
    timeout=timeout, verify=ssl_cert, **kwargs)
  File "/opt/medusa/ext/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/opt/medusa/ext/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/medusa/ext/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/opt/medusa/ext/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'api/v2/auth/login': No schema supplied. Perhaps you meant http://api/v2/auth/login?
2020-01-17 19:05:22 INFO	SNATCHQUEUE-SNATCH-80337 :: [942040a] Downloading Mad.Men.S03.720p.BluRay.x264-EbP with 4 seeders and 1 leechers and size 29.10 GB from IPTorrents, through a SearchType.MANUAL_SEARCH search
2020-01-17 19:05:22 INFO	SNATCHQUEUE-SNATCH-80337 :: [942040a] Beginning to snatch release: Mad.Men.S03.720p.BluRay.x264-EbP
2020-01-17 19:04:50 INFO	APIv2-Thread-1 :: [942040a] Broken providers found: ['torrent9', 'newpct', 'tntvillage']
2020-01-17 19:04:02 WARNING	SNATCHQUEUE-SNATCH-80337 :: [942040a] qBittorrent: Authentication Failed
2020-01-17 19:04:02 WARNING	SNATCHQUEUE-SNATCH-80337 :: [942040a] qBittorrent: Exception while trying to authenticate: Invalid URL 'api/v2/auth/login': No schema supplied. Perhaps you meant http://api/v2/auth/login?

```

**Additional context**

**Comment by ZMOT7S** [comment]
I fixed it by adding http:// in front of the qbittorrent address.

**Comment by bugsyb** [comment]
Did run into it too - what is weird is that test on the config page went through successfully.
Would be good to either automatically add http if nothing is specified or enforce http at UI level.
