### ISSUE TITLE
[APP SUBMITTED]: SSLEOFError: EOF occurred in violation of protocol (_ssl.c:661)

### ISSUE THREAD

**Issue by Tailslide** [pymedusa/Medusa#7624]
### INFO
**Python Version**: `2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@942040af95311a71d9663236c7136434b6711ca5
**Link to Log**: https://gist.github.com/d72d3d2ebfb27ca531b00192842227ff
### ERROR
<pre>
2020-01-24 07:11:39 ERROR    POSTPROCESSOR :: [942040a] Environment error: EOF occurred in violation of protocol (_ssl.c:661)
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/scheduler.py#L93">medusa/scheduler.py</a>", line 93, in run
    self.action.run(self.force)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/process_tv.py#L65">medusa/process_tv.py</a>", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/process_tv.py#L188">medusa/process_tv.py</a>", line 188, in process
    ignore_subs=ignore_subs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/process_tv.py#L378">medusa/process_tv.py</a>", line 378, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/process_tv.py#L599">medusa/process_tv.py</a>", line 599, in process_media
    self.result = processor.process()
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/post_processor.py#L1275">medusa/post_processor.py</a>", line 1275, in process
    notifiers.notify_download(ep_obj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/notifiers/__init__.py#L103">medusa/notifiers/__init__.py</a>", line 103, in notify_download
    n.notify_download(ep_obj)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/notifiers/pushover.py#L152">medusa/notifiers/pushover.py</a>", line 152, in notify_download
    self._notify_pushover(title, ep_obj.pretty_name_with_quality())
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/notifiers/pushover.py#L205">medusa/notifiers/pushover.py</a>", line 205, in _notify_pushover
    return self._send_pushover(message, title, sound=sound, user_key=user_key, api_key=api_key, priority=priority)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/<a href="../blob/942040af95311a71d9663236c7136434b6711ca5/medusa/notifiers/pushover.py#L97">medusa/notifiers/pushover.py</a>", line 97, in _send_pushover
    urlencode(args), {'Content-type': 'application/x-www-form-urlencoded'})
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/var/packages/python/target/lib/python2.7/ssl.py", line 363, in wrap_socket
    _context=self)
  File "/var/packages/python/target/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/var/packages/python/target/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:661)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by gers1978** [comment]
### INFO
**Python Version**: `2.7.16 (default, Feb 29 2020, 01:55:37) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-`
**Operating System**: `Darwin-19.4.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@4d1e78726dc94979cc7908651d13e40f199959a9
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-04-04 02:04:07 ERROR    POSTPROCESSOR :: [4d1e787] Environment error: EOF occurred in violation of protocol (_ssl.c:727)
Traceback (most recent call last):
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/scheduler.py#L79">medusa/scheduler.py</a>", line 79, in run
    self.action.run(self.force)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L65">medusa/process_tv.py</a>", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L188">medusa/process_tv.py</a>", line 188, in process
    ignore_subs=ignore_subs)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L378">medusa/process_tv.py</a>", line 378, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L599">medusa/process_tv.py</a>", line 599, in process_media
    self.result = processor.process()
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/post_processor.py#L1286">medusa/post_processor.py</a>", line 1286, in process
    notifiers.notify_download(ep_obj)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/notifiers/__init__.py#L103">medusa/notifiers/__init__.py</a>", line 103, in notify_download
    n.notify_download(ep_obj)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/notifiers/pushover.py#L152">medusa/notifiers/pushover.py</a>", line 152, in notify_download
    self._notify_pushover(title, ep_obj.pretty_name_with_quality())
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/notifiers/pushover.py#L205">medusa/notifiers/pushover.py</a>", line 205, in _notify_pushover
    return self._send_pushover(message, title, sound=sound, user_key=user_key, api_key=api_key, priority=priority)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/notifiers/pushover.py#L97">medusa/notifiers/pushover.py</a>", line 97, in _send_pushover
    urlencode(args), {'Content-type': 'application/x-www-form-urlencoded'})
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:727)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Use Python 3.6+

**Comment by gers1978** [comment]
### INFO
**Python Version**: `2.7.16 (default, Feb 29 2020, 01:55:37) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-`
**Operating System**: `Darwin-19.4.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@4d1e78726dc94979cc7908651d13e40f199959a9
**Link to Log**: https://gist.github.com/be23a0fa06ad42e248a4e26af0ecde92
### ERROR
<pre>
2020-04-09 15:13:07 ERROR    Thread_7 :: [4d1e787] Environment error: EOF occurred in violation of protocol (_ssl.c:727)
Traceback (most recent call last):
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/server/web/home/post_process.py#L61">medusa/server/web/home/post_process.py</a>", line 61, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L65">medusa/process_tv.py</a>", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L188">medusa/process_tv.py</a>", line 188, in process
    ignore_subs=ignore_subs)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L378">medusa/process_tv.py</a>", line 378, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L599">medusa/process_tv.py</a>", line 599, in process_media
    self.result = processor.process()
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/post_processor.py#L1286">medusa/post_processor.py</a>", line 1286, in process
    notifiers.notify_download(ep_obj)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/notifiers/__init__.py#L103">medusa/notifiers/__init__.py</a>", line 103, in notify_download
    n.notify_download(ep_obj)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/notifiers/pushover.py#L152">medusa/notifiers/pushover.py</a>", line 152, in notify_download
    self._notify_pushover(title, ep_obj.pretty_name_with_quality())
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/notifiers/pushover.py#L205">medusa/notifiers/pushover.py</a>", line 205, in _notify_pushover
    return self._send_pushover(message, title, sound=sound, user_key=user_key, api_key=api_key, priority=priority)
  File "/Applications/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/notifiers/pushover.py#L97">medusa/notifiers/pushover.py</a>", line 97, in _send_pushover
    urlencode(args), {'Content-type': 'application/x-www-form-urlencoded'})
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:727)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by gers1978** [comment]
### INFO
**Python Version**: `2.7.16 (default, Feb 29 2020, 01:55:37) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-`
**Operating System**: `Darwin-19.4.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@4d1e78726dc94979cc7908651d13e40f199959a9
**Link to Log**: https://gist.github.com/6edd8abf5ed39157b5a1e45866fd5535
### ERROR
<pre>
2020-04-13 15:57:44 ERROR    POSTPROCESSOR :: [4d1e787] Environment error: EOF occurred in violation of protocol (_ssl.c:727)
Traceback (most recent call last):
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:727)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by gers1978** [comment]
### INFO
**Python Version**: `2.7.16 (default, Feb 29 2020, 01:55:37) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-`
**Operating System**: `Darwin-19.4.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-04-24 02:16:03 ERROR    POSTPROCESSOR :: [8f6b666] Environment error: EOF occurred in violation of protocol (_ssl.c:727)
Traceback (most recent call last):
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:727)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
