### ISSUE TITLE
[APP SUBMITTED]: dbm.error: db type is dbm.gnu, but the module is not available

### ISSUE THREAD

**Issue by dirkr07** [pymedusa/Medusa#7715]
### INFO
**Python Version**: `3.5.6 (default, Nov 25 2018, 14:24:15) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-4.4.59+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/1f81fb575eddabfc4a3b16453576d383
### ERROR
<pre>
2020-02-08 17:41:08 ERROR    Thread-154 :: [9a36461] Exception generated: db type is dbm.gnu, but the module is not available
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/web/home/handler.py#L1971">medusa/server/web/home/handler.py</a>", line 1971, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</volume1/@appstore/medusa/var/Medusa/ext/decorator.py:decorator-gen-14>", line 2, in get_release_groups_for_anime
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/dogpile/cache/region.py#L1360">ext/dogpile/cache/region.py</a>", line 1360, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/dogpile/cache/region.py#L962">ext/dogpile/cache/region.py</a>", line 962, in get_or_create
    async_creator,
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/dogpile/lock.py#L187">ext/dogpile/lock.py</a>", line 187, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/dogpile/lock.py#L87">ext/dogpile/lock.py</a>", line 87, in _enter
    value = value_fn()
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/dogpile/cache/region.py#L902">ext/dogpile/cache/region.py</a>", line 902, in get_value
    value = self.backend.get(key)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/dogpile/cache/backends/file.py#L223">ext/dogpile/cache/backends/file.py</a>", line 223, in get
    with self._dbm_file(False) as dbm:
  File "/var/packages/python3/target/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/dogpile/cache/backends/file.py#L218">ext/dogpile/cache/backends/file.py</a>", line 218, in _dbm_file
    dbm = self.dbmmodule.open(self.filename, "w" if write else "r")
  File "/var/packages/python3/target/lib/python3.5/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by noodle-** [comment]
Same issue here. Seems to only happen when trying to edit anime series though.
If any additional logs could be useful just let me know.

Medusa Info: | Branch:                 master                  Commit:                 ee1b898d0f74750c4c265d077fcc0da73d17b41e                  Version:                 0.3.12                  Database:                 44.14
-- | --
Python Version: | 3.7.3 (default, Apr  3 2019, 05:39:12)  [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d  10 Sep 2019
OS: | Linux-3.4.113-bananian-armv7l-with-debian-10.2
Locale: | en_US.UTF-8

**Comment by medariox** [comment]
Did you try https://github.com/pymedusa/Medusa/issues/6804#issuecomment-570688415 ?

**Comment by noodle-** [comment]
> 
> 
> Did you try [#6804 (comment)](https://github.com/pymedusa/Medusa/issues/6804#issuecomment-570688415) ?

Oh I somehow didn't find that before... Thank you! This has solved the issue for me!

**Comment by medariox** [comment]
Great! We can close the issue then :)

**Comment by dirkr07** [comment]
### INFO
**Python Version**: `3.5.6 (default, Nov 25 2018, 14:24:15) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-4.4.59+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@4d1e78726dc94979cc7908651d13e40f199959a9
**Link to Log**: https://gist.github.com/baf6d1ad068a63897715dd20419d3573
### ERROR
<pre>
2020-04-03 15:35:31 ERROR    Thread-45 :: [4d1e787] Exception generated: db type is dbm.gnu, but the module is not available
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/server/web/home/handler.py#L1802">medusa/server/web/home/handler.py</a>", line 1802, in manualSearchSubtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/subtitles.py#L342">medusa/subtitles.py</a>", line 342, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/ext/dogpile/cache/region.py#L1112">ext/dogpile/cache/region.py</a>", line 1112, in set
    self.backend.set(key, self._value(value))
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/ext/dogpile/cache/backends/file.py#L240">ext/dogpile/cache/backends/file.py</a>", line 240, in set
    with self._dbm_file(True) as dbm:
  File "/var/packages/python3/target/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/ext/dogpile/cache/backends/file.py#L218">ext/dogpile/cache/backends/file.py</a>", line 218, in _dbm_file
    dbm = self.dbmmodule.open(self.filename, "w" if write else "r")
  File "/var/packages/python3/target/lib/python3.5/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
