### ISSUE TITLE
Upgraded Python from 3.7 to 3.8 - now cannot start Medusa

### ISSUE THREAD

**Issue by Avian-Flew** [pymedusa/Medusa#7738]
Upgraded Python 3.7 to 3.8 using Entware_ng (OPKG).

Now Medusa wont start-up, When I manually execute start.sh, the following messages show;

Starting Medusa ...
Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/SickBeard.py", line 6, in <module>
    from medusa.__main__ import main
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/medusa/init/__init__.py", line 27, in initialize
    _ssl_configuration()
  File "/mnt/HD/HD_a2/Nas_Prog/medusa/Medusa/medusa/init/__init__.py", line 111, in _ssl_configuration
    import ssl
  File "/ssl.py", line 98, in <module>
ModuleNotFoundError: No module named '_ssl'

Can anyone help - I'm not a Linux man.

Thanks

**Comment by p0psicles** [comment]
Ok. Well check it out.
If you can better stay on 3.7 for now

**Comment by Avian-Flew** [comment]
Used OPKG to upgrade all installed packages and remove obsolete files - seemed to do the trick.
