### ISSUE TITLE
[APP SUBMITTED]: TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by pmhaustein** [pymedusa/Medusa#7739]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/6f5844140fabb65484ce3d0ea3ad2faf
### ERROR
<pre>
2020-02-09 12:51:10 ERROR    SHOWQUEUE-ADD :: [ee1b898] None: Error while loading information from indexer TMDB. Error: TypeError("int() argument must be a string or a number, not 'NoneType'",)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_queue.py#L399">medusa/show_queue.py</a>", line 399, in run
    show_name = get_showname_from_indexer(self.indexer, self.indexer_id, self.lang)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/helpers/__init__.py#L1552">medusa/helpers/__init__.py</a>", line 1552, in get_showname_from_indexer
    s = indexer_api[int(indexer_id)]
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pmhaustein** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/3a7ec400a6e6c6d7d29920fd07feb0bd
### ERROR
<pre>
2020-02-09 13:39:08 ERROR    SHOWQUEUE-ADD :: [ee1b898] None: Error while loading information from indexer TMDB. Error: TypeError("int() argument must be a string or a number, not 'NoneType'",)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_queue.py#L399">medusa/show_queue.py</a>", line 399, in run
    show_name = get_showname_from_indexer(self.indexer, self.indexer_id, self.lang)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/helpers/__init__.py#L1552">medusa/helpers/__init__.py</a>", line 1552, in get_showname_from_indexer
    s = indexer_api[int(indexer_id)]
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pmhaustein** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/fec3163c74ec683defe72e96a8dbb792
### ERROR
<pre>
2020-02-09 13:42:08 ERROR    SHOWQUEUE-ADD :: [ee1b898] None: Error while loading information from indexer TMDB. Error: TypeError("int() argument must be a string or a number, not 'NoneType'",)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_queue.py#L399">medusa/show_queue.py</a>", line 399, in run
    show_name = get_showname_from_indexer(self.indexer, self.indexer_id, self.lang)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/helpers/__init__.py#L1552">medusa/helpers/__init__.py</a>", line 1552, in get_showname_from_indexer
    s = indexer_api[int(indexer_id)]
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pmhaustein** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/75a0733ec4f063598c35e5743fe7e841
### ERROR
<pre>
2020-02-09 14:48:10 ERROR    SHOWQUEUE-ADD :: [ee1b898] None: Error while loading information from indexer TMDB. Error: TypeError("int() argument must be a string or a number, not 'NoneType'",)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_queue.py#L399">medusa/show_queue.py</a>", line 399, in run
    show_name = get_showname_from_indexer(self.indexer, self.indexer_id, self.lang)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/helpers/__init__.py#L1552">medusa/helpers/__init__.py</a>", line 1552, in get_showname_from_indexer
    s = indexer_api[int(indexer_id)]
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pmhaustein** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/fed5ed22984174a5519372dde6567c7c
### ERROR
<pre>
2020-02-10 16:49:11 ERROR    SHOWQUEUE-ADD :: [ee1b898] None: Error while loading information from indexer TMDB. Error: TypeError("int() argument must be a string or a number, not 'NoneType'",)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_queue.py#L399">medusa/show_queue.py</a>", line 399, in run
    show_name = get_showname_from_indexer(self.indexer, self.indexer_id, self.lang)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/helpers/__init__.py#L1552">medusa/helpers/__init__.py</a>", line 1552, in get_showname_from_indexer
    s = indexer_api[int(indexer_id)]
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by highbread** [comment]
### INFO
**Python Version**: `2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]`
**Operating System**: `Linux-5.3.0-40-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/df3b05155229e77302189f977c85d5d9
### ERROR
<pre>
2020-02-29 17:57:41 ERROR    POSTPROCESSOR :: [ee1b898] Exception generated: int() argument must be a string or a number, not 'NoneType'
Traceback (most recent call last):
  File "/home/**********/.medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/home/**********/.medusa/medusa/process_tv.py", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/home/**********/.medusa/medusa/process_tv.py", line 188, in process
    ignore_subs=ignore_subs)
  File "/home/**********/.medusa/medusa/process_tv.py", line 372, in process_files
    self.process_media(path, video_files, force, is_priority, ignore_subs)
  File "/home/**********/.medusa/medusa/process_tv.py", line 599, in process_media
    self.result = processor.process()
  File "/home/**********/.medusa/medusa/post_processor.py", line 1092, in process
    if int(ep_obj.season) > int(max_season[0]['max']):
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pmhaustein** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.14.24-qnap-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/59958494f8d14a55330f85bec36fdeef
### ERROR
<pre>
2020-03-15 16:04:42 ERROR    SHOWQUEUE-ADD :: [ee1b898] None: Error while loading information from indexer TMDB. Error: TypeError("int() argument must be a string or a number, not 'NoneType'",)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_queue.py#L399">medusa/show_queue.py</a>", line 399, in run
    show_name = get_showname_from_indexer(self.indexer, self.indexer_id, self.lang)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/helpers/__init__.py#L1552">medusa/helpers/__init__.py</a>", line 1552, in get_showname_from_indexer
    s = indexer_api[int(indexer_id)]
TypeError: int() argument must be a string or a number, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
