### ISSUE TITLE
title with "'" (apostrophe) crashes medusa

### ISSUE THREAD

**Issue by cheese1** [pymedusa/Medusa#7748]
**Describe the bug**

**To Reproduce**
process an episode with an apostrophe in its name.

2020-02-09 23:59:06 ERROR    TORNADO :: [942040a] API :: UnicodeEncodeError('latin-1', '/home/sickbeard/Downloads/Serien.staging/Babylon_5/S04/S04E02 - Der letzte des Kha’ri.mkv', 82, 83, 'ordinal not in range(256)')
Traceback (most recent call last):
  File "/usr/share/medusa/medusa/server/api/v1/core.py", line 165, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/usr/share/medusa/medusa/server/api/v1/core.py", line 235, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/usr/share/medusa/medusa/server/api/v1/core.py", line 1336, in run
    proc_type=self.type
  File "/usr/share/medusa/medusa/process_tv.py", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/usr/share/medusa/medusa/process_tv.py", line 188, in process
    ignore_subs=ignore_subs)
  File "/usr/share/medusa/medusa/process_tv.py", line 378, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/usr/share/medusa/medusa/process_tv.py", line 599, in process_media
    self.result = processor.process()
  File "/usr/share/medusa/medusa/post_processor.py", line 1227, in process
    app.MOVE_ASSOCIATED_FILES, app.USE_SUBTITLES and ep_obj.series.subtitles)
  File "/usr/share/medusa/medusa/post_processor.py", line 524, in post_process_action
    action=action, subtitle_action=subtitle_action, subtitles=subtitles)
  File "/usr/share/medusa/medusa/post_processor.py", line 457, in _combined_file_operation
    action(cur_associated_file, new_file_path)
  File "/usr/share/medusa/medusa/post_processor.py", line 482, in copy
    helpers.copy_file(cur_file_path, new_file_path)
  File "/usr/share/medusa/medusa/helpers/__init__.py", line 295, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/usr/lib64/python3.7/shutil.py", line 103, in copyfile
    if _samefile(src, dst):
  File "/usr/lib64/python3.7/shutil.py", line 88, in _samefile
    return os.path.samefile(src, dst)
  File "/usr/lib64/python3.7/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 82: ordinal not in range(256)

**Comment by medariox** [comment]
The file uses an encoding that is not supported by your file system, probably utf-8. You should use utf-8 as your system encoding instead of latin-1 or keep all your files latin-1 (don't recommend this).
