### ISSUE TITLE
Startup failure after system update to python3-regex

### ISSUE THREAD

**Issue by hazbot72** [pymedusa/Medusa#7762]
After system update, Medusa fails to launch, with error output below.

Downgrade the python3-regex package to previous version and Medusa launches ok.

Working version of python3-regex: python3-regex-2019.08.19-1.fc31.x86_64

Broken version: python3-regex-2020.1.8-1.fc31.x86_64

**Describe the bug**
Medusa raises ValueError exception on startup.

**To Reproduce**
Update system to python3-regex-2020.1.8-1.fc31.x86_64

**Expected behavior**
Medusa launches successfully

**Medusa (please complete the following information):**
 - OS: Fedora 31 x64
 - Branch: master
 - Commit: ee1b898
 - Python version: 3.7.6
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
[xxxx@xxxx Medusa]$ python
Python 3.7.6 (default, Jan 30 2020, 09:44:41) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[xxxx@xxxx Medusa]$ python start.py
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/Medusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/opt/Medusa/medusa/init/__init__.py", line 38, in initialize
    _configure_guessit()
  File "/opt/Medusa/medusa/init/__init__.py", line 191, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "/opt/Medusa/medusa/name_parser/guessit_parser.py", line 13, in <module>
    from medusa.name_parser.rules import default_api
  File "/opt/Medusa/medusa/name_parser/rules/__init__.py", line 19, in <module>
    default_api.configure({})
  File "/opt/Medusa/ext/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/opt/Medusa/ext/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/opt/Medusa/ext/guessit/rules/properties/episodes.py", line 175, in episodes
    build_or_pattern(episode_markers + disc_markers, name='episodeMarker') + r'@?(?P<episode>\d+)')\
  File "/opt/Medusa/ext/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/opt/Medusa/ext/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/opt/Medusa/ext/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/opt/Medusa/ext/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib64/python3.7/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib64/python3.7/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'tags'
[xxxx@xxxx Medusa]$ 

```
</details>

**Additional context**

**Comment by medariox** [comment]
Medusa doesn't need the regex package, it is an optional dependency of guessit and the inbuilt Python regex module is just fine. You can safely remove it. If you depend on it because of other packages, please report to guessit instead.
