### ISSUE TITLE
Problems downloading with qbittorrent and utorrent 

### ISSUE THREAD

**Issue by danevd** [pymedusa/Medusa#7767]
Hi,

I`ve been struggling to set up medusa for a few days especially with the download part.
I`ve enabled only torrent search providers configured qbittorrent. The web ui is enabled and an username and password are set. After configuring these settings in Medusa I press test connection and it shows "Connected and authenticated".
However when i try to download an episode it gives me an error

2020-02-20 12:46:20 WARNING  SNATCHQUEUE-SNATCH-328724 :: [ee1b898] qBittorrent: Exception while trying to authenticate: Invalid URL 'http:/api/v2/auth/login': No schema supplied. Perhaps you meant http://http:/api/v2/auth/login?
Traceback (most recent call last):
  File "C:\Medusa2\Medusa\medusa\clients\torrent\qbittorrent.py", line 90, in _get_auth_v2
    self.response = self.session.post(self.url, data=data, verify=app.TORRENT_VERIFY_CERT)
  File "C:\Medusa2\Medusa\ext\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Medusa2\Medusa\medusa\session\core.py", line 104, in request
    timeout=timeout, verify=ssl_cert, **kwargs)
  File "C:\Medusa2\Medusa\ext\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Medusa2\Medusa\ext\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Medusa2\Medusa\ext\requests\models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "C:\Medusa2\Medusa\ext\requests\models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'http:/api/v2/auth/login': No schema supplied. Perhaps you meant http://http:/api/v2/auth/login?
2020-02-20 12:46:20 WARNING  SNATCHQUEUE-SNATCH-328724 :: [ee1b898] qBittorrent: Authentication Failed
![Capture](https://user-images.githubusercontent.com/25767893/74929863-0f728100-53e5-11ea-9fda-63f732174b80.PNG)
![Capture2](https://user-images.githubusercontent.com/25767893/74929865-10a3ae00-53e5-11ea-8e9e-08c18ad820ff.PNG)

**Comment by medariox** [comment]
Make sure to save the config, Medusa is not using the host:port you are showing in the picture.

**Comment by danevd** [comment]
Yes i`ve saved the config

**Comment by medariox** [comment]
Check config.ini for the value `torrent_host`.

**Comment by danevd** [comment]
[TORRENT]
torrent_username = danev
torrent_password = *******
torrent_host = " http://localhost:8080"
torrent_path = ""
torrent_seed_time = 0
torrent_paused = 0
torrent_high_bandwidth = 0
torrent_label = ""
torrent_label_anime = ""
torrent_verify_cert = 0
torrent_rpcurl = transmission
torrent_auth_type = ""
torrent_seed_location = ""

**Comment by medariox** [comment]
There is a leading space: `torrent_host = " http://localhost:8080"`

**Comment by danevd** [comment]
Feeling so dumb right now. 
This was the problem.
Thank you for the help
