### ISSUE TITLE
Seedbox.io

### ISSUE THREAD

**Issue by LostTech69** [pymedusa/Medusa#7773]
I am having a problem sending torrents to Seedbox.io.  They use a rtorrent/rutorrent combination.  Could someone please take a look at the sample log, and maybe point me in the right direction to proceed.  I have verified that the username and password are correct, as well as the web address.

2020-02-22 17:23:51 ERROR    SNATCHQUEUE-SNATCH-359581 :: [74c3f12] Snatch failed! For result: Stumptown.S01E15.HDTV.x264-SVA[rartv]
Traceback (most recent call last):
  File "/app/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 144, in request
    response.raise_for_status()
  File "/app/medusa/ext/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Not Allowed for url: http://**********.seedbox.io/ruttorent/plugins/httprpc/action.php

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 459, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/rtorrent.py", line 53, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/app/medusa/lib/rtorrent/__init__.py", line 87, in __init__
    self._verify_conn()
  File "/app/medusa/lib/rtorrent/__init__.py", line 126, in _verify_conn
    assert 'system.client_version' in self._get_rpc_methods(
  File "/app/medusa/lib/rtorrent/__init__.py", line 164, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/app/medusa/lib/rtorrent/__init__.py", line 154, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/app/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 147, in request
    error.message,
AttributeError: 'HTTPError' object has no attribute 'message'

**Comment by medariox** [comment]
You are getting  `405 Client Error: Not Allowed` as a response from the server. Are you sure you are using the correct endpoint?

**Comment by LostTech69** [comment]
Yes, I am sure it is the correct end point.  I tried both http and https, as well as converting the address into it's ip address.

The only message I have received from Seedbox.io, directs me to their knowledge base page with the instructions to setup Sonarr.   Here is what they show for Sonarr.  

I am at wits end here, is it possible it is a version issue, or client name issue?

![wtsiGVZ](https://user-images.githubusercontent.com/1265829/75099788-b72db180-5593-11ea-8630-303a33219b1e.png)

**Comment by p0psicles** [comment]
Post A screenshot of your current config

**Comment by LostTech69** [comment]
Thanks for looking into this.  I have blacked out the account information for security reasons .  I truly hope, you can see something I missed.


![Untitled](https://user-images.githubusercontent.com/1265829/75117085-79389800-563c-11ea-8fec-f3614b9a067a.png)

**Comment by medariox** [comment]
You are running a super old version. Please update.

**Comment by LostTech69** [comment]
Please explain. When I check for updates I am told no update needed in the log file.

2020-02-23 18:40:53 INFO	Thread-1 :: [74c3f12] No update needed
2020-02-23 18:40:37 INFO	Thread-1 :: [74c3f12] No update needed

**Comment by LostTech69** [comment]
For safeties sake Just downloaded the latest Docker image and I am still receiving the error.

**Comment by LostTech69** [comment]
Definitely something on their end, don't know what.  After receiving a email from them, basic authentication started working.  Thanks for the help.
