### ISSUE TITLE
[APP SUBMITTED]: ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#7808]
### INFO
**Python Version**: `3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]`
**Operating System**: `Darwin-19.3.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@65a9c84ef98d927b706d552a01617baf1554b713
**Link to Log**: https://gist.github.com/af37b8439d343e4199ced58c9bdbeefd
### ERROR
<pre>
2020-03-03 08:43:32 ERROR    SHOWQUEUE-REFRESH :: [65a9c84] 370377: Error while refreshing show ID: INVADED. Error: float division by zero
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/show_queue.py#L695">medusa/show_queue.py</a>", line 695, in run
    self.show.populate_cache()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/tv/series.py#L1742">medusa/tv/series.py</a>", line 1742, in populate_cache
    image_cache.fill_cache(self)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/image_cache.py#L339">medusa/image_cache.py</a>", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/image_cache.py#L262">medusa/image_cache.py</a>", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/metadata/generic.py#L773">medusa/metadata/generic.py</a>", line 773, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/metadata/generic.py#L908">medusa/metadata/generic.py</a>", line 908, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/indexer_base.py#L399">medusa/indexers/indexer_base.py</a>", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/tvdbv2/tvdbv2_api.py#L604">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 604, in _get_show_data
    self._parse_images(sid)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/tvdbv2/fallback.py#L135">medusa/indexers/tvdbv2/fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/tvdbv2/tvdbv2_api.py#L508">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 508, in _parse_images
    self._save_images(sid, _images)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/indexer_base.py#L392">medusa/indexers/indexer_base.py</a>", line 392, in _save_images
    self._save_images_by_type(img_type, series_id, images_by_type)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/indexer_base.py#L310">medusa/indexers/indexer_base.py</a>", line 310, in _save_images_by_type
    sorted_results = sorted(rated_images, key=itemgetter(0), reverse=True)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/indexer_base.py#L307">medusa/indexers/indexer_base.py</a>", line 307, in <genexpr>
    for image in merged_images
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/indexers/indexer_base.py#L237">medusa/indexers/indexer_base.py</a>", line 237, in result
    score_rated = weights.bayesian(weight, value, threshold, mean)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/65a9c84ef98d927b706d552a01617baf1554b713/medusa/statistics/weights.py#L14">medusa/statistics/weights.py</a>", line 14, in bayesian
    return (weight * value + threshold * mean) / (weight + threshold)
ZeroDivisionError: float division by zero
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by VexingHex** [comment]
### INFO
**Python Version**: `2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]`
**Operating System**: `Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-03-04 03:02:15 ERROR    SHOWQUEUE-REFRESH :: [ee1b898] 370377: Error while refreshing show ID: INVADED. Error: float division by zero
Traceback (most recent call last):
  File "/opt/**********/**********/show_queue.py", line 695, in run
    self.show.populate_cache()
  File "/opt/**********/**********/tv/series.py", line 1806, in populate_cache
    image_cache.fill_cache(self)
  File "/opt/**********/**********/image_cache.py", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "/opt/**********/**********/image_cache.py", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "/opt/**********/**********/metadata/generic.py", line 773, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/opt/**********/**********/metadata/generic.py", line 908, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/opt/**********/**********/indexers/indexer_base.py", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/opt/**********/**********/indexers/tvdbv2/tvdbv2_api.py", line 604, in _get_show_data
    self._parse_images(sid)
  File "/opt/**********/**********/indexers/tvdbv2/fallback.py", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/opt/**********/**********/indexers/tvdbv2/tvdbv2_api.py", line 508, in _parse_images
    self._save_images(sid, _images)
  File "/opt/**********/**********/indexers/indexer_base.py", line 392, in _save_images
    self._save_images_by_type(img_type, series_id, images_by_type)
  File "/opt/**********/**********/indexers/indexer_base.py", line 310, in _save_images_by_type
    sorted_results = sorted(rated_images, key=itemgetter(0), reverse=True)
  File "/opt/**********/**********/indexers/indexer_base.py", line 307, in <genexpr>
    for image in merged_images
  File "/opt/**********/**********/indexers/indexer_base.py", line 237, in result
    score_rated = weights.bayesian(weight, value, threshold, mean)
  File "/opt/**********/**********/statistics/weights.py", line 14, in bayesian
    return (weight * value + threshold * mean) / (weight + threshold)
ZeroDivisionError: float division by zero
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]`
**Operating System**: `Darwin-19.3.0-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@2d23fa480666b16eb0d6cc7683f43ec111fe4e1c
**Link to Log**: https://gist.github.com/710adcd133da206c68911e2eeaeb5085
### ERROR
<pre>
2020-03-09 04:39:53 ERROR    SHOWQUEUE-REFRESH :: [2d23fa4] 370377: Error while refreshing show ID: INVADED. Error: float division by zero
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/show_queue.py#L695">medusa/show_queue.py</a>", line 695, in run
    self.show.populate_cache()
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/tv/series.py#L1742">medusa/tv/series.py</a>", line 1742, in populate_cache
    image_cache.fill_cache(self)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/image_cache.py#L339">medusa/image_cache.py</a>", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/image_cache.py#L262">medusa/image_cache.py</a>", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/metadata/generic.py#L773">medusa/metadata/generic.py</a>", line 773, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/metadata/generic.py#L908">medusa/metadata/generic.py</a>", line 908, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/indexers/indexer_base.py#L399">medusa/indexers/indexer_base.py</a>", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/indexers/tvdbv2/tvdbv2_api.py#L604">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 604, in _get_show_data
    self._parse_images(sid)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/indexers/tvdbv2/fallback.py#L135">medusa/indexers/tvdbv2/fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/indexers/tvdbv2/tvdbv2_api.py#L508">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 508, in _parse_images
    self._save_images(sid, _images)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/indexers/indexer_base.py#L392">medusa/indexers/indexer_base.py</a>", line 392, in _save_images
    self._save_images_by_type(img_type, series_id, images_by_type)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/indexers/indexer_base.py#L310">medusa/indexers/indexer_base.py</a>", line 310, in _save_images_by_type
    sorted_results = sorted(rated_images, key=itemgetter(0), reverse=True)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/indexers/indexer_base.py#L307">medusa/indexers/indexer_base.py</a>", line 307, in <genexpr>
    for image in merged_images
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/indexers/indexer_base.py#L237">medusa/indexers/indexer_base.py</a>", line 237, in result
    score_rated = weights.bayesian(weight, value, threshold, mean)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/2d23fa480666b16eb0d6cc7683f43ec111fe4e1c/medusa/statistics/weights.py#L14">medusa/statistics/weights.py</a>", line 14, in bayesian
    return (weight * value + threshold * mean) / (weight + threshold)
ZeroDivisionError: float division by zero
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
It's just this show: https://thetvdb.com/series/id-invaded
It has negative rating...

**Comment by medariox** [comment]
Report it to TheTVDB.

**Comment by huxerFluxer** [comment]
### INFO
**Python Version**: `3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-05-01 21:20:18 ERROR    SHOWQUEUE-REFRESH :: [d9c31da] 362496: Error while refreshing show Marvel's The Falcon and the Winter Soldier. Error: float division by zero
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/show_queue.py#L695">medusa\show_queue.py</a>", line 695, in run
    self.show.populate_cache()
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/tv/series.py#L1749">medusa\tv\series.py</a>", line 1749, in populate_cache
    image_cache.fill_cache(self)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/image_cache.py#L339">medusa\image_cache.py</a>", line 339, in fill_cache
    _cache_image_from_indexer(series_obj, img_type)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/image_cache.py#L262">medusa\image_cache.py</a>", line 262, in _cache_image_from_indexer
    img_data = metadata_generator._retrieve_show_image(img_type_name, series_obj)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/metadata/generic.py#L773">medusa\metadata\generic.py</a>", line 773, in _retrieve_show_image
    indexer_show_obj = self._get_show_data(show_obj)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/metadata/generic.py#L908">medusa\metadata\generic.py</a>", line 908, in _get_show_data
    my_show = self.indexer_api[int(series_id)]
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/indexer_base.py#L399">medusa\indexers\indexer_base.py</a>", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/tvdbv2/tvdbv2_api.py#L575">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 575, in _get_show_data
    self._parse_images(sid)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/tvdbv2/fallback.py#L132">medusa\indexers\tvdbv2\fallback.py</a>", line 132, in __call__
    return self.func(*args, **kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/tvdbv2/tvdbv2_api.py#L479">medusa\indexers\tvdbv2\tvdbv2_api.py</a>", line 479, in _parse_images
    self._save_images(sid, _images)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/indexer_base.py#L392">medusa\indexers\indexer_base.py</a>", line 392, in _save_images
    self._save_images_by_type(img_type, series_id, images_by_type)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/indexer_base.py#L310">medusa\indexers\indexer_base.py</a>", line 310, in _save_images_by_type
    sorted_results = sorted(rated_images, key=itemgetter(0), reverse=True)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/indexer_base.py#L307">medusa\indexers\indexer_base.py</a>", line 307, in <genexpr>
    for image in merged_images
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/indexer_base.py#L237">medusa\indexers\indexer_base.py</a>", line 237, in result
    score_rated = weights.bayesian(weight, value, threshold, mean)
  File "C:\Medusa\Medusa\<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/statistics/weights.py#L14">medusa\statistics\weights.py</a>", line 14, in bayesian
    return (weight * value + threshold * mean) / (weight + threshold)
ZeroDivisionError: float division by zero
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by notho** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-4.19.107-Unraid-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/a2fa0c0991da87e6d0d4f012d6c3ddcb
### ERROR
<pre>
2020-09-03 18:08:54 ERROR    SHOWQUEUE-REFRESH :: [] 74205: Error while refreshing show Band of Brothers. Error: division by zero
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 700, in run
    self.show.populate_cache()
  File "/app/medusa/medusa/tv/series.py", line 1813, in populate_cache
    image_cache.fill_cache(self)
  File "/app/medusa/medusa/image_cache.py", line 307, in fill_cache
    file_type = which_type(filename)
  File "/app/medusa/medusa/image_cache.py", line 145, in which_type
    aspect_ratio = width / height
ZeroDivisionError: division by zero
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by notho** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-4.19.107-Unraid-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/b9af8899146273da1d5ceefc1fea405d
### ERROR
<pre>
2020-09-30 04:13:12 ERROR    SHOWQUEUE-REFRESH :: [] 74205: Error while refreshing show Band of Brothers. Error: division by zero
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 700, in run
    self.show.populate_cache()
  File "/app/medusa/medusa/tv/series.py", line 1829, in populate_cache
    image_cache.fill_cache(self)
  File "/app/medusa/medusa/image_cache.py", line 307, in fill_cache
    file_type = which_type(filename)
  File "/app/medusa/medusa/image_cache.py", line 145, in which_type
    aspect_ratio = width / height
ZeroDivisionError: division by zero
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
