### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'ConnectionError' object has no attribute 'message'

### ISSUE THREAD

**Issue by pcliff069** [pymedusa/Medusa#7813]
### INFO
**Python Version**: `3.8.1 (default, Dec 30 2019, 15:43:37) [GCC 9.2.0]`
**Operating System**: `Linux-4.19.83-xanmod40-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/94ed900dd418be4f95b3dc627b6dec62
### ERROR
<pre>
2020-03-04 12:42:45 ERROR    SNATCHQUEUE-SNATCH-328749 :: [] Snatch failed! For result: Dynasty.2017.S03E14.1080p.WEB.H264-XLF
Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/app/medusa/ext/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/app/medusa/ext/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/ext/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/app/medusa/ext/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/app/medusa/ext/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/app/medusa/ext/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fda4e59e4f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/ext/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/ext/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /rutorrent/plugins/httprpc/action.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda4e59e4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 119, in request
    response = requests.post(
  File "/app/medusa/ext/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/app/medusa/ext/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/ext/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /rutorrent/plugins/httprpc/action.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda4e59e4f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 459, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/rtorrent.py", line 53, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/app/medusa/lib/rtorrent/__init__.py", line 87, in __init__
    self._verify_conn()
  File "/app/medusa/lib/rtorrent/__init__.py", line 126, in _verify_conn
    assert 'system.client_version' in self._get_rpc_methods(
  File "/app/medusa/lib/rtorrent/__init__.py", line 164, in _get_rpc_methods
    return(self._rpc_methods or self._update_rpc_methods())
  File "/app/medusa/lib/rtorrent/__init__.py", line 154, in _update_rpc_methods
    self._rpc_methods = self._get_conn().system.listMethods()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/app/medusa/lib/rtorrent/lib/xmlrpc/requests_transport.py", line 147, in request
    error.message,
AttributeError: 'ConnectionError' object has no attribute 'message'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7819
