### ISSUE TITLE
Crash in  \Medusa\Medusa\ext\js2py\base.py while searching Torrentz2

### ISSUE THREAD

**Issue by rafi-d** [pymedusa/Medusa#7825]
This was while manual searching... 

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**

Medusa Info: | Branch:                 master                  Commit:                 ee1b898d0f74750c4c265d077fcc0da73d17b41e                  Version:                 0.3.12                  Database:                 44.14
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j  20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | en_IL.cp1252
  |  
  |  
User: | RAFI-PC-DELL$
Program Folder: | D:\Program Files\Medusa\Medusa
Config File: | D:\Program Files\Medusa\Data\config.ini
Database File: | D:\Program Files\Medusa\Data\main.db
Cache Folder: | D:\Program Files\Medusa\Data\cache
Log Folder: | D:\Program Files\Medusa\Data\Logs
Arguments: | --nolaunch --datadir=D:\Program Files\Medusa\Data

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-03-08 10:09:51 INFO     FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] Performing episode search for Outlander
2020-03-08 10:09:51 DEBUG    FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] Could not find any candidates in cache, searching provider.
2020-03-08 10:09:51 DEBUG    FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] Search mode: Episode
2020-03-08 10:09:51 DEBUG    FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] Search string: Outlander S05E04
2020-03-08 10:09:51 DEBUG    FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] GET URL: https://torrentz2.eu/feed?f=Outlander+S05E04 [Status: 503]
2020-03-08 10:09:51 DEBUG    FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] User-Agent: Medusa/0.3.12 (Windows; 10; f303422e-6112-11ea-84af-000af74c0cde)
2020-03-08 10:09:51 DEBUG    FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] Cloudflare protection detected, trying to bypass it.
2020-03-08 10:09:53 INFO     FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] Unknown exception in url https://torrentz2.eu/feed Error: TypeError: 'undefined' is not a function
2020-03-08 10:09:53 DEBUG    FORCEDSEARCHQUEUE-MANUAL-270408 :: [Torrentz2] :: [ee1b898] Traceback (most recent call last):
  File "D:\Program Files\Medusa\Medusa\medusa\session\core.py", line 156, in request
    timeout=timeout, verify=verify, **kwargs)
  File "D:\Program Files\Medusa\Medusa\medusa\session\core.py", line 106, in request
    response = handlers.cloudflare(self, response, timeout=timeout, verify=ssl_cert, **kwargs)
  File "D:\Program Files\Medusa\Medusa\medusa\session\handlers.py", line 43, in cloudflare
    tokens, user_agent = CloudflareScraper.get_tokens(original_request.url)
  File "D:\Program Files\Medusa\Medusa\ext\cfscrape\__init__.py", line 380, in get_tokens
    resp = scraper.get(url, **kwargs)
  File "D:\Program Files\Medusa\Medusa\ext\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "D:\Program Files\Medusa\Medusa\ext\cfscrape\__init__.py", line 129, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "D:\Program Files\Medusa\Medusa\ext\cfscrape\__init__.py", line 204, in solve_cf_challenge
    answer, delay = self.solve_challenge(body, domain)
  File "D:\Program Files\Medusa\Medusa\medusa\init\cfscrape.py", line 59, in _patched_solve_challenge
    result = js2py.eval_js(challenge)
  File "D:\Program Files\Medusa\Medusa\ext\js2py\evaljs.py", line 115, in eval_js
    return e.eval(js)
  File "D:\Program Files\Medusa\Medusa\ext\js2py\evaljs.py", line 204, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "D:\Program Files\Medusa\Medusa\ext\js2py\evaljs.py", line 199, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "D:\Program Files\Medusa\Medusa\ext\js2py\base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "D:\Program Files\Medusa\Medusa\ext\js2py\base.py", line 1463, in call
    return Js(self.code(*args))
  File "D:\Program Files\Medusa\Medusa\ext\js2py\host\jseval.py", line 45, in Eval
    executor(py_code)
  File "D:\Program Files\Medusa\Medusa\ext\js2py\host\jseval.py", line 51, in executor
    exec (code, globals())
  File "<string>", line 151, in <module>
  File "<string>", line 150, in PyJs_LONG_46_
  File "D:\Program Files\Medusa\Medusa\ext\js2py\base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "D:\Program Files\Medusa\Medusa\ext\js2py\base.py", line 1463, in call
    return Js(self.code(*args))
  File "<string>", line 148, in PyJs_anonymous_45_
  File "D:\Program Files\Medusa\Medusa\ext\js2py\base.py", line 994, in callprop
    '%s is not a function' % cand.typeof())
js2py.internals.simplex.JsException: TypeError: 'undefined' is not a function

```
</details>

**Additional context**

**Comment by medariox** [comment]
Already fixed in develop.
