### ISSUE TITLE
[APP SUBMITTED]: medusa.indexers.indexer_exceptions.IndexerException: Could not get episodes for series 81983 using indexer TMDB. Cause: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/tv/81983/season/2?language=en&api_key=edc5f123313769de83a71e157758030b (Caused by SSLError(SSLError('bad handshake: ZeroReturnError()')))

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#7828]
### INFO
**Python Version**: `3.7.5 (default, Oct 27 2019, 15:43:29) [GCC 9.2.1 20190909]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-debian-bullseye-sid`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@6088c79b53ac7175f07feafb4a2c846da9cd87a8
**Link to Log**: https://gist.github.com/5fb27d7e40624bc7ad1f2ef185f0c352
### ERROR
<pre>
2020-03-08 02:32:22 ERROR    SHOWQUEUE-REFRESH :: [6088c79] 81983: Error while refreshing show Paradise PD. Error: Could not get episodes for series 81983 using indexer TMDB. Cause: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/tv/81983/season/2?language=en&api_key=edc5f123313769de83a71e157758030b (Caused by SSLError(SSLError('bad handshake: ZeroReturnError()')))
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/contrib/pyopenssl.py#L453">ext/urllib3/contrib/pyopenssl.py</a>", line 453, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/dist-packages/OpenSSL/SSL.py", line 1626, in _raise_ssl_error
    raise ZeroReturnError()
OpenSSL.SSL.ZeroReturnError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/connectionpool.py#L600">ext/urllib3/connectionpool.py</a>", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/connectionpool.py#L343">ext/urllib3/connectionpool.py</a>", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/connectionpool.py#L839">ext/urllib3/connectionpool.py</a>", line 839, in _validate_conn
    conn.connect()
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/connection.py#L344">ext/urllib3/connection.py</a>", line 344, in connect
    ssl_context=context)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/util/ssl_.py#L344">ext/urllib3/util/ssl_.py</a>", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/contrib/pyopenssl.py#L459">ext/urllib3/contrib/pyopenssl.py</a>", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ('bad handshake: ZeroReturnError()',)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/requests/adapters.py#L449">ext/requests/adapters.py</a>", line 449, in send
    timeout=timeout
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/connectionpool.py#L638">ext/urllib3/connectionpool.py</a>", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/urllib3/util/retry.py#L398">ext/urllib3/util/retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/tv/81983/season/2?language=en&api_key=edc5f123313769de83a71e157758030b (Caused by SSLError(SSLError('bad handshake: ZeroReturnError()')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/indexers/tmdb/tmdb.py#L259">medusa/indexers/tmdb/tmdb.py</a>", line 259, in _get_episodes
    season_info = self.tmdb.TV_Seasons(tmdb_id, season).info(language=self.config['language'])
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/lib/tmdbsimple/tv.py#L392">lib/tmdbsimple/tv.py</a>", line 392, in info
    response = self._GET(path, kwargs)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/lib/tmdbsimple/base.py#L85">lib/tmdbsimple/base.py</a>", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/lib/tmdbsimple/base.py#L78">lib/tmdbsimple/base.py</a>", line 78, in _request
    headers=self.headers)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/requests/api.py#L61">ext/requests/api.py</a>", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/requests/sessions.py#L530">ext/requests/sessions.py</a>", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/requests/sessions.py#L643">ext/requests/sessions.py</a>", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/ext/requests/adapters.py#L514">ext/requests/adapters.py</a>", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/tv/81983/season/2?language=en&api_key=edc5f123313769de83a71e157758030b (Caused by SSLError(SSLError('bad handshake: ZeroReturnError()')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/show_queue.py#L691">medusa/show_queue.py</a>", line 691, in run
    self.show.refresh_dir()
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/tv/series.py#L1755">medusa/tv/series.py</a>", line 1755, in refresh_dir
    self.load_episodes_from_dir()
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/tv/series.py#L1016">medusa/tv/series.py</a>", line 1016, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/tv/series.py#L1382">medusa/tv/series.py</a>", line 1382, in make_ep_from_file
    **********_ep.create_meta_files()
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/tv/episode.py#L1134">medusa/tv/episode.py</a>", line 1134, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/tv/episode.py#L1157">medusa/tv/episode.py</a>", line 1157, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/metadata/generic.py#L365">medusa/metadata/generic.py</a>", line 365, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/tv/episode.py#L718">medusa/tv/episode.py</a>", line 718, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "/home/pi/Medusa/<a href="../blob/6088c79b53ac7175f07feafb4a2c846da9cd87a8/medusa/indexers/tmdb/tmdb.py#L264">medusa/indexers/tmdb/tmdb.py</a>", line 264, in _get_episodes
    series=tmdb_id, cause=error
medusa.indexers.indexer_exceptions.IndexerException: Could not get episodes for series 81983 using indexer TMDB. Cause: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/tv/81983/season/2?language=en&api_key=edc5f123313769de83a71e157758030b (Caused by SSLError(SSLError('bad handshake: ZeroReturnError()')))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/7837
