### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)

### ISSUE THREAD

**Issue by draden05** [pymedusa/Medusa#7836]
### INFO
**Python Version**: `3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.19-ovh-xxxx-std-ipv6-64-x86_64-with-debian-9.12`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@ee1b898d0f74750c4c265d077fcc0da73d17b41e
**Link to Log**: https://gist.github.com/9f075253ab6c0f6bff0cc009bd4c4603
### ERROR
<pre>
2020-03-11 18:43:52 ERROR    SHOWQUEUE-ADD :: [ee1b898] 275274: Error while loading information from indexer TVDBv2. Error: IndexerUnavailable("Error connecting to TVDB API. Reason: ReadTimeout\nHTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)",)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/connectionpool.py#L384">ext/urllib3/connectionpool.py</a>", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/connectionpool.py#L380">ext/urllib3/connectionpool.py</a>", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/contrib/pyopenssl.py#L307">ext/urllib3/contrib/pyopenssl.py</a>", line 307, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/requests/adapters.py#L449">ext/requests/adapters.py</a>", line 449, in send
    timeout=timeout
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/connectionpool.py#L638">ext/urllib3/connectionpool.py</a>", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/util/retry.py#L367">ext/urllib3/util/retry.py</a>", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/packages/six.py#L686">ext/urllib3/packages/six.py</a>", line 686, in reraise
    raise value
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/connectionpool.py#L600">ext/urllib3/connectionpool.py</a>", line 600, in urlopen
    chunked=chunked)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/connectionpool.py#L386">ext/urllib3/connectionpool.py</a>", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/urllib3/connectionpool.py#L306">ext/urllib3/connectionpool.py</a>", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/tvdbapiv2/rest.py#L52">ext/tvdbapiv2/rest.py</a>", line 52, in request
    r = self.session.request(method, url, params=query_params, headers=headers)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/session/core.py#L104">medusa/session/core.py</a>", line 104, in request
    timeout=timeout, verify=ssl_cert, **kwargs)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/requests/sessions.py#L533">ext/requests/sessions.py</a>", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/requests/sessions.py#L646">ext/requests/sessions.py</a>", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/cachecontrol/adapter.py#L53">ext/cachecontrol/adapter.py</a>", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/requests/adapters.py#L529">ext/requests/adapters.py</a>", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L277">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 277, in _query_series
    tvdb_id, page=page, accept_language=self.config['language']
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/tvdbapiv2/apis/series_api.py#L468">ext/tvdbapiv2/apis/series_api.py</a>", line 468, in series_id_episodes_query_get
    callback=params.get('callback'))
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/tvdbapiv2/api_client.py#L295">ext/tvdbapiv2/api_client.py</a>", line 295, in call_api
    response_type, auth_settings, callback)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/tvdbapiv2/api_client.py#L122">ext/tvdbapiv2/api_client.py</a>", line 122, in __call_api
    post_params=post_params, body=body)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/tvdbapiv2/api_client.py#L315">ext/tvdbapiv2/api_client.py</a>", line 315, in request
    headers=headers)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/tvdbapiv2/rest.py#L70">ext/tvdbapiv2/rest.py</a>", line 70, in get
    query_params=query_params)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/ext/tvdbapiv2/rest.py#L63">ext/tvdbapiv2/rest.py</a>", line 63, in request
    raise ApiException(status=status, reason=msg)
tvdbapiv2.exceptions.ApiException: (0)
Reason: ReadTimeout
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/show_queue.py#L394">medusa/show_queue.py</a>", line 394, in run
    s = indexer_api[self.indexer_id]
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/indexer_base.py#L399">medusa/indexers/indexer_base.py</a>", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L600">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 600, in _get_show_data
    self._get_episodes(sid, specials=False, aired_season=None)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L216">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 216, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/fallback.py#L135">medusa/indexers/tvdbv2/fallback.py</a>", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/opt/medusa/<a href="../blob/ee1b898d0f74750c4c265d077fcc0da73d17b41e/medusa/indexers/tvdbv2/tvdbv2_api.py#L300">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 300, in _query_series
    reason=error.reason
medusa.indexers.indexer_exceptions.IndexerUnavailable: Error connecting to TVDB API. Reason: ReadTimeout
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
TheTVDB was down. This won't raise an exception in the next release.

**Comment by papampi** [comment]
When TheTVDB is down tvdb2.plex.tv will be unreachable too?

**Comment by medariox** [comment]
Normally yes, as it's just a cached mirror.

**Comment by papampi** [comment]
So then its useless to set it as fallback, right?
