### ISSUE TITLE
Unauthorized (HTTP 401) Error with thetvdb

### ISSUE THREAD

**Issue by bartolomesoriano** [pymedusa/Medusa#7840]
There seems to be a problem again with thetvdb API, no actions with thetvdb can be performed.

Medusa Info: 
Branch: master
Commit: ee1b898d0f74750c4c265d077fcc0da73d17b41e
Version: 0.3.12
Database: 44.14
Python Version: | 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Windows-10-10.0.19577-SP0
Locale: | en_US.cp1252

Here is an excerpt from the log:

2020-03-14 06:04:00 WARNING  SHOWQUEUE-REFRESH :: [ee1b898] could not connect to TheTvdb.com, with reason 'IndexerAuthFailed('Authentication failed, possible bad API key. Reason: HTTPError\n401 Client Error:  for url: https://tvdb2.plex.tv/series/76548/episodes/query?airedSeason=47&page=1 (401)')'
2020-03-14 06:04:00 WARNING  SHOWQUEUE-REFRESH :: [ee1b898] Enabling Plex fallback as TheTvdb.com API is having some connectivity issues
2020-03-14 06:04:30 WARNING  SHOWQUEUE-REFRESH :: [ee1b898] 76548: TVDBv2 threw up an error: Error connecting to TVDB API. Reason: ReadTimeout
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)
2020-03-14 06:05:01 INFO     SHOWQUEUE-REFRESH :: [ee1b898] Could not get image count for show ID: 76548 with reason: ReadTimeout
HTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)
2020-03-14 06:05:02 INFO     SHOWQUEUE-REFRESH :: [ee1b898] Trying to clean any empty folder under U:\BaLi TV Shows\BaLi Series\Great Performances
2020-03-14 06:05:02 INFO     SHOWQUEUE-REFRESH :: [ee1b898] 76548: Updating NFOs for show with new indexer info
2020-03-14 06:05:32 WARNING  SHOWQUEUE-REFRESH :: [ee1b898] could not connect to TheTvdb.com, with reason 'IndexerUnavailable("Error connecting to TVDB API. Reason: ReadTimeout\nHTTPSConnectionPool(host='tvdb2.plex.tv', port=443): Read timed out. (read timeout=30)")'
2020-03-14 06:05:32 WARNING  SHOWQUEUE-REFRESH :: [ee1b898] Enabling Plex fallback as TheTvdb.com API is having some connectivity issues
2020-03-14 06:06:33 ERROR    SHOWQUEUE-REFRESH :: [ee1b898] 76548: Error while refreshing show Great Performances. Error: Authentication failed, possible bad API key. Reason: HTTPError
401 Client Error:  for url: https://tvdb2.plex.tv/series/76548/episodes/query?airedSeason=47&page=1 (401)
Traceback (most recent call last):
  File "C:\pyMedusa\ext\tvdbapiv2\rest.py", line 54, in request
    r.raise_for_status()
  File "C:\pyMedusa\ext\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error:  for url: https://tvdb2.plex.tv/series/76548/episodes/query?airedSeason=47&page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\pyMedusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 269, in _query_series
    tvdb_id, page=page, aired_season=season, accept_language=self.config['language']
  File "C:\pyMedusa\ext\tvdbapiv2\apis\series_api.py", line 468, in series_id_episodes_query_get
    callback=params.get('callback'))
  File "C:\pyMedusa\ext\tvdbapiv2\api_client.py", line 295, in call_api
    response_type, auth_settings, callback)
  File "C:\pyMedusa\ext\tvdbapiv2\api_client.py", line 122, in __call_api
    post_params=post_params, body=body)
  File "C:\pyMedusa\ext\tvdbapiv2\api_client.py", line 315, in request
    headers=headers)
  File "C:\pyMedusa\ext\tvdbapiv2\rest.py", line 70, in get
    query_params=query_params)
  File "C:\pyMedusa\ext\tvdbapiv2\rest.py", line 63, in request
    raise ApiException(status=status, reason=msg)
tvdbapiv2.exceptions.ApiException: (401)
Reason: HTTPError
401 Client Error:  for url: https://tvdb2.plex.tv/series/76548/episodes/query?airedSeason=47&page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\pyMedusa\medusa\show_queue.py", line 694, in run
    self.show.write_metadata()
  File "C:\pyMedusa\medusa\tv\series.py", line 1004, in write_metadata
    self.__write_episode_nfos()
  File "C:\pyMedusa\medusa\tv\series.py", line 1033, in __write_episode_nfos
    cur_ep.create_meta_files()
  File "C:\pyMedusa\medusa\tv\episode.py", line 1134, in create_meta_files
    self.__create_thumbnail(metadata_provider)
  File "C:\pyMedusa\medusa\tv\episode.py", line 1157, in __create_thumbnail
    result = metadata_provider.create_episode_thumb(self) or result
  File "C:\pyMedusa\medusa\metadata\generic.py", line 365, in create_episode_thumb
    ep_obj.set_indexer_data(season=ep_obj.season, indexer_api=self.indexer_api)
  File "C:\pyMedusa\medusa\tv\episode.py", line 718, in set_indexer_data
    api._get_episodes(self.series.series_id, aired_season=season)
  File "C:\pyMedusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 216, in _get_episodes
    episodes = self._query_series(tvdb_id, specials=specials, aired_season=aired_season, full_info=True)
  File "C:\pyMedusa\medusa\indexers\tvdbv2\fallback.py", line 135, in __call__
    return self.func(*args, **kwargs)
  File "C:\pyMedusa\medusa\indexers\tvdbv2\tvdbv2_api.py", line 291, in _query_series
    .format(reason=error.reason, status=error.status)
medusa.indexers.indexer_exceptions.IndexerAuthFailed: Authentication failed, possible bad API key. Reason: HTTPError
401 Client Error:  for url: https://tvdb2.plex.tv/series/76548/episodes/query?airedSeason=47&page=1 (401)

**Comment by medariox** [comment]
There is nothing to do about it. Just use a different indexer. Next update won't raise this issue as error anymore.
