### ISSUE TITLE
tvdb2 fail again..

### ISSUE THREAD

**Issue by segator** [pymedusa/Medusa#7844]
when adding a new tvshow...
```
2020-03-14 21:29:21 ERROR    SHOWQUEUE-ADD :: [ee1b898] 377784: Error while loading information from indexer TVDBv2. Error: IndexerAuthFailed('Authentication failed, possible bad API key. Reason: HTTPError\n401 Client Error: Unauthorized for url: https://tvdb2.plex.tv/series/377784 (401)')
Traceback (most recent call last):
  File "/app/medusa/ext/tvdbapiv2/rest.py", line 54, in request
    r.raise_for_status()
  File "/app/medusa/ext/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://tvdb2.plex.tv/series/377784

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 186, in _get_show_by_id
    results = self.config['session'].series_api.series_id_get(tvdbv2_id, accept_language=request_language)
  File "/app/medusa/ext/tvdbapiv2/apis/series_api.py", line 123, in series_id_get
    callback=params.get('callback'))
  File "/app/medusa/ext/tvdbapiv2/api_client.py", line 295, in call_api
    response_type, auth_settings, callback)
  File "/app/medusa/ext/tvdbapiv2/api_client.py", line 122, in __call_api
    post_params=post_params, body=body)
  File "/app/medusa/ext/tvdbapiv2/api_client.py", line 315, in request
    headers=headers)
  File "/app/medusa/ext/tvdbapiv2/rest.py", line 70, in get
    query_params=query_params)
  File "/app/medusa/ext/tvdbapiv2/rest.py", line 63, in request
    raise ApiException(status=status, reason=msg)
tvdbapiv2.exceptions.ApiException: (401)
Reason: HTTPError
401 Client Error: Unauthorized for url: https://tvdb2.plex.tv/series/377784


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 394, in run
    s = indexer_api[self.indexer_id]
  File "/app/medusa/medusa/indexers/indexer_base.py", line 399, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 582, in _get_show_data
    series_info = self._get_show_by_id(sid, request_language=get_show_in_language)
  File "/app/medusa/medusa/indexers/tvdbv2/fallback.py", line 135, in __call__
    return self.func(*args, **kwargs)
  File "/app/medusa/medusa/indexers/tvdbv2/tvdbv2_api.py", line 191, in _get_show_by_id
    .format(reason=error.reason, status=error.status)
medusa.indexers.indexer_exceptions.IndexerAuthFailed: Authentication failed, possible bad API key. Reason: HTTPError
401 Client Error: Unauthorized for url: https://tvdb2.plex.tv/series/377784 (401)
```

**Comment by medariox** [comment]
Please don't open duplicate issues: https://github.com/pymedusa/Medusa/issues/7843
