### ISSUE TITLE
[APP SUBMITTED]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe041861a00>: Failed to establish a new connection: [Errno -3] Try again'))

### ISSUE THREAD

**Issue by doncoque** [pymedusa/Medusa#7871]
### INFO
**Python Version**: `3.8.1 (default, Dec 30 2019, 15:43:37) [GCC 9.2.0]`
**Operating System**: `Linux-5.3.0-40-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-03-11 12:03:58 ERROR    CHECKVERSION :: [] Environment error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe041861a00>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/app/medusa/ext/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/ext/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/app/medusa/ext/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/app/medusa/ext/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/app/medusa/ext/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fe041861a00>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/ext/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/ext/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe041861a00>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/scheduler.py", line 93, in run
    self.action.run(self.force)
  File "/app/medusa/medusa/updater/version_checker.py", line 45, in run
    if self.check_for_new_version(force):
  File "/app/medusa/medusa/updater/version_checker.py", line 253, in check_for_new_version
    if not self.updater.need_update():
  File "/app/medusa/medusa/updater/docker_updater.py", line 28, in need_update
    if self.branch == 'master' and not self.is_latest_version():
  File "/app/medusa/medusa/updater/update_manager.py", line 42, in is_latest_version
    if LooseVersion(self.newest_version) > LooseVersion(self.current_version):
  File "/app/medusa/medusa/updater/source_updater.py", line 67, in newest_version
    latest_release = get_latest_release(self.github_org, self.github_repo)
  File "/app/medusa/medusa/github_client.py", line 119, in get_latest_release
    return gh.get_organization(organization).get_repo(repo).get_latest_release()
  File "/app/medusa/ext/github/MainClass.py", line 293, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
  File "/app/medusa/ext/github/Requester.py", line 321, in requestJsonAndCheck
    *self.requestJson(
  File "/app/medusa/ext/github/Requester.py", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/ext/github/Requester.py", line 474, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/app/medusa/ext/github/Requester.py", line 501, in __requestRaw
    response = cnx.getresponse()
  File "/app/medusa/ext/github/Requester.py", line 113, in getresponse
    r = verb(
  File "/app/medusa/ext/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/ext/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe041861a00>: Failed to establish a new connection: [Errno -3] Try again'))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by cainecool** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.19.97-v7+-armv7l-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/57ad7b18f25c0c5e12dd1c3534345b27
### ERROR
<pre>
2020-03-31 14:08:42 ERROR    CHECKVERSION :: [] Environment error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7299da00>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/app/medusa/ext/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/ext/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/app/medusa/ext/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/app/medusa/ext/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/app/medusa/ext/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7299da00>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/ext/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/ext/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7299da00>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/scheduler.py", line 79, in run
    self.action.run(self.force)
  File "/app/medusa/medusa/updater/version_checker.py", line 45, in run
    if self.check_for_new_version(force):
  File "/app/medusa/medusa/updater/version_checker.py", line 253, in check_for_new_version
    if not self.updater.need_update():
  File "/app/medusa/medusa/updater/docker_updater.py", line 28, in need_update
    if self.branch == 'master' and not self.is_latest_version():
  File "/app/medusa/medusa/updater/update_manager.py", line 42, in is_latest_version
    if LooseVersion(self.newest_version) > LooseVersion(self.current_version):
  File "/app/medusa/medusa/updater/source_updater.py", line 67, in newest_version
    latest_release = get_latest_release(self.github_org, self.github_repo)
  File "/app/medusa/medusa/github_client.py", line 119, in get_latest_release
    return gh.get_organization(organization).get_repo(repo).get_latest_release()
  File "/app/medusa/ext/github/MainClass.py", line 293, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
  File "/app/medusa/ext/github/Requester.py", line 321, in requestJsonAndCheck
    *self.requestJson(
  File "/app/medusa/ext/github/Requester.py", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/ext/github/Requester.py", line 474, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/app/medusa/ext/github/Requester.py", line 501, in __requestRaw
    response = cnx.getresponse()
  File "/app/medusa/ext/github/Requester.py", line 113, in getresponse
    r = verb(
  File "/app/medusa/ext/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/ext/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7299da00>: Failed to establish a new connection: [Errno -3] Try again'))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pokyto** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/1bba340356ba3dc4c3e45a70e55de078
### ERROR
<pre>
2020-05-13 01:18:06 ERROR    CHECKVERSION :: [918cfe7] Environment error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff4e49cb8b0>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connection.py#L158">ext/urllib3/connection.py</a>", line 158, in _new_conn
    conn = connection.create_connection(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/util/connection.py#L57">ext/urllib3/util/connection.py</a>", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L343">ext/urllib3/connectionpool.py</a>", line 343, in _make_request
    self._validate_conn(conn)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L839">ext/urllib3/connectionpool.py</a>", line 839, in _validate_conn
    conn.connect()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connection.py#L301">ext/urllib3/connection.py</a>", line 301, in connect
    conn = self._new_conn()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connection.py#L167">ext/urllib3/connection.py</a>", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ff4e49cb8b0>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L439">ext/requests/adapters.py</a>", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/util/retry.py#L398">ext/urllib3/util/retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff4e49cb8b0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/scheduler.py#L78">medusa/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L45">medusa/updater/version_checker.py</a>", line 45, in run
    if self.check_for_new_version(force):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L253">medusa/updater/version_checker.py</a>", line 253, in check_for_new_version
    if not self.updater.need_update():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/docker_updater.py#L28">medusa/updater/docker_updater.py</a>", line 28, in need_update
    if self.branch == 'master' and not self.is_latest_version():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/update_manager.py#L42">medusa/updater/update_manager.py</a>", line 42, in is_latest_version
    if LooseVersion(self.newest_version) > LooseVersion(self.current_version):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/source_updater.py#L67">medusa/updater/source_updater.py</a>", line 67, in newest_version
    latest_release = get_latest_release(self.github_org, self.github_repo)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/github_client.py#L119">medusa/github_client.py</a>", line 119, in get_latest_release
    return gh.get_organization(organization).get_repo(repo).get_latest_release()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/MainClass.py#L293">ext/github/MainClass.py</a>", line 293, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L321">ext/github/Requester.py</a>", line 321, in requestJsonAndCheck
    *self.requestJson(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L413">ext/github/Requester.py</a>", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L474">ext/github/Requester.py</a>", line 474, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L501">ext/github/Requester.py</a>", line 501, in __requestRaw
    response = cnx.getresponse()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L113">ext/github/Requester.py</a>", line 113, in getresponse
    r = verb(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L543">ext/requests/sessions.py</a>", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L530">ext/requests/sessions.py</a>", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L643">ext/requests/sessions.py</a>", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L516">ext/requests/adapters.py</a>", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff4e49cb8b0>: Failed to establish a new connection: [Errno -3] Try again'))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by mattail** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/f4b59b28c552107ed8244e634a480b25
### ERROR
<pre>
2020-05-20 00:55:05 ERROR    CHECKVERSION :: [] Environment error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a1cf4e910>: Failed to establish a new connection: [Errno -3] Try again'))
Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/app/medusa/ext/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/ext/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/app/medusa/ext/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/app/medusa/ext/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/app/medusa/ext/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a1cf4e910>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/ext/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/ext/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/ext/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a1cf4e910>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/medusa/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/medusa/updater/version_checker.py", line 45, in run
    if self.check_for_new_version(force):
  File "/app/medusa/medusa/updater/version_checker.py", line 253, in check_for_new_version
    if not self.updater.need_update():
  File "/app/medusa/medusa/updater/docker_updater.py", line 28, in need_update
    if self.branch == 'master' and not self.is_latest_version():
  File "/app/medusa/medusa/updater/update_manager.py", line 42, in is_latest_version
    if LooseVersion(self.newest_version) > LooseVersion(self.current_version):
  File "/app/medusa/medusa/updater/source_updater.py", line 67, in newest_version
    latest_release = get_latest_release(self.github_org, self.github_repo)
  File "/app/medusa/medusa/github_client.py", line 119, in get_latest_release
    return gh.get_organization(organization).get_repo(repo).get_latest_release()
  File "/app/medusa/ext/github/MainClass.py", line 293, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
  File "/app/medusa/ext/github/Requester.py", line 321, in requestJsonAndCheck
    *self.requestJson(
  File "/app/medusa/ext/github/Requester.py", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/ext/github/Requester.py", line 474, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/app/medusa/ext/github/Requester.py", line 501, in __requestRaw
    response = cnx.getresponse()
  File "/app/medusa/ext/github/Requester.py", line 113, in getresponse
    r = verb(
  File "/app/medusa/ext/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/ext/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/ext/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/pymedusa (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4a1cf4e910>: Failed to establish a new connection: [Errno -3] Try again'))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
