### ISSUE TITLE
[APP SUBMITTED]: FileNotFoundError: [Errno 2] No such file or directory: '/config/cache/mako/layouts/main.mako.py'

### ISSUE THREAD

**Issue by pokyto** [pymedusa/Medusa#7887]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/44f62cd8cdeae5b20e1b31469c98636a
### ERROR
<pre>
2020-03-29 03:30:25 ERROR    Thread_0 :: [918cfe7] Environment error: [Errno 2] No such file or directory: '/config/cache/mako/layouts/main.mako.py'
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/lookup.py#L249">ext/mako/lookup.py</a>", line 249, in get_template
    return self._check(uri, self._collection[uri])
KeyError: '/inc_blackwhitelist.mako'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/server/web/core/base.py#L116">medusa/server/web/core/base.py</a>", line 116, in render
    return self.template.render_unicode(*args, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/template.py#L481">ext/mako/template.py</a>", line 481, in render_unicode
    return runtime._render(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/runtime.py#L878">ext/mako/runtime.py</a>", line 878, in _render
    _render_context(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/runtime.py#L920">ext/mako/runtime.py</a>", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/runtime.py#L947">ext/mako/runtime.py</a>", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/config/cache/mako/layouts/main.mako.py", line 99, in render_body
  File "/config/cache/mako/addShows_addExistingShow.mako.py", line 93, in render_content
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/runtime.py#L795">ext/mako/runtime.py</a>", line 795, in _include_file
    callable_(ctx, **kwargs)
  File "/config/cache/mako/inc_addShowOptions.mako.py", line 73, in render_body
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/runtime.py#L782">ext/mako/runtime.py</a>", line 782, in _include_file
    template = _lookup_template(context, uri, calling_uri)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/runtime.py#L839">ext/mako/runtime.py</a>", line 839, in _lookup_template
    return lookup.get_template(uri)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/lookup.py#L260">ext/mako/lookup.py</a>", line 260, in get_template
    return self._load(srcfile, uri)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/lookup.py#L322">ext/mako/lookup.py</a>", line 322, in _load
    self._collection[uri] = template = Template(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/template.py#L348">ext/mako/template.py</a>", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/template.py#L413">ext/mako/template.py</a>", line 413, in _compile_from_file
    _compile_module_file(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/template.py#L765">ext/mako/template.py</a>", line 765, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python3.8/tempfile.py", line 332, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/config/cache/mako/tmpsoqhy87q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/exceptions.py#L162">ext/mako/exceptions.py</a>", line 162, in _init
    (line_map, template_lines, template_filename) = mods[filename]
KeyError: '/config/cache/mako/layouts/main.mako.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/server/web/home/add_shows.py#L265">medusa/server/web/home/add_shows.py</a>", line 265, in existingShows
    return t.render(enable_anime_options=True, blacklist=[], whitelist=[], groups=[],
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/server/web/core/base.py#L118">medusa/server/web/core/base.py</a>", line 118, in render
    kwargs['backtrace'] = RichTraceback()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/exceptions.py#L93">ext/mako/exceptions.py</a>", line 93, in __init__
    self.records = self._init(traceback)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/exceptions.py#L166">ext/mako/exceptions.py</a>", line 166, in _init
    module_source = info.code
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/template.py#L683">ext/mako/template.py</a>", line 683, in code
    return util.read_python_file(self.module_filename)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/mako/util.py#L392">ext/mako/util.py</a>", line 392, in read_python_file
    fp = open(path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/config/cache/mako/layouts/main.mako.py'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Try deleting the mako cache: `/config/cache/mako`. If that doesn't work, try using Python 3.7 - Python 3.8 is not officially supported yet.
