### ISSUE TITLE
Missing time zone and too many SQL variables Errors

### ISSUE THREAD

**Issue by specklesmike** [pymedusa/Medusa#7897]
Keep getting this in my error logs and not sure how to fix it, Was hoping the latest update would fix it but it doesn't. Medusa on Windows 10. Normal install. 
I also have the problem that a show doesn't auto update its air dates, Which is a real pain, I have to manual click on force full update per show and it works pulls the latest airtimes etc, Guessing it because of the below errors aswel. Is their a config file that needs  changing? Help
```
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: The CW
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Netflix
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: FOX
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Showtime
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: CBS
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: NBC
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Starz!
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: TV3 (NZ)
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Network Ten
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: HBO
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Paramount Network
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Seven Network
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Bravo
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: A&E
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: ITV2
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: ITV
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: ITV1
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: BBC Two
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: CBC (CA)
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: MTV (UK)
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Amazon
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: AMC
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Sky1
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: YouTube Premium
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Starz
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: ABC (US)
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: TVNZ
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Channel 4
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: Nine Network
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Syfy
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: Lifetime
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: USA Network
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: CNBC
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Channel 5 (UK)
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: FX
2020-03-30 21:51:01 ERROR    Thread_2 :: [fc471d2] Missing time zone for network: Audience Network
2020-03-30 21:51:01 ERROR    Thread_4 :: [fc471d2] Missing time zone for network: TV Land
2020-03-30 21:50:56 ERROR    MAIN :: [fc471d2] DB error: OperationalError('too many SQL variables')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: too many SQL variables
2020-03-30 21:50:56 ERROR    MAIN :: [fc471d2] DB error: too many SQL variables
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\db.py", line 222, in mass_action
    sql_results.append(self._execute(qu[0], qu[1], fetchall=fetchall))
  File "C:\Medusa\Medusa\medusa\db.py", line 115, in _execute
    sql_results = cursor.execute(query, args)
sqlite3.OperationalError: too many SQL variables
```

**Comment by medariox** [comment]
Sounds like you are having issues connecting to external servers. Make sure your connectivity is alright.
