### ISSUE TITLE
[APP SUBMITTED]: KeyError: 3276806

### ISSUE THREAD

**Issue by dug-g** [pymedusa/Medusa#7929]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/2ee78d79127353132e8542c4517b04d5
### ERROR
<pre>
2020-04-07 10:15:19 ERROR    TORNADO :: [9a36461] Uncaught exception in APIv2: KeyError(3276806)
Request: GET /api/v2/series/tvdb78804/episodes?limit=1000&season=11 (172.17.0.1)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/tornado/web.py#L1592">ext/tornado/web.py</a>", line 1592, in _execute
    result = yield result
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/tornado/gen.py#L1141">ext/tornado/gen.py</a>", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/api/v2/base.py#L83">medusa/server/api/v2/base.py</a>", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/api/v2/episodes.py#L60">medusa/server/api/v2/episodes.py</a>", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/api/v2/episodes.py#L60">medusa/server/api/v2/episodes.py</a>", line 60, in <listcomp>
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/tv/episode.py#L1090">medusa/tv/episode.py</a>", line 1090, in to_json
    data['status'] = self.status_name
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/tv/episode.py#L427">medusa/tv/episode.py</a>", line 427, in status_name
    return statusStrings[self.status]
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dug-g** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/4cdad9bccaca361ddb4e18bcd79b766b
### ERROR
<pre>
2020-04-07 10:21:36 ERROR    TORNADO :: [9a36461] Uncaught exception in APIv2: KeyError(3276806)
Request: GET /api/v2/series/tvdb330997/episodes?limit=1000&season=1 (172.17.0.1)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/tornado/web.py#L1592">ext/tornado/web.py</a>", line 1592, in _execute
    result = yield result
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/tornado/gen.py#L1141">ext/tornado/gen.py</a>", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/api/v2/base.py#L83">medusa/server/api/v2/base.py</a>", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/ext/tornado/gen.py#L1133">ext/tornado/gen.py</a>", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/api/v2/episodes.py#L60">medusa/server/api/v2/episodes.py</a>", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/api/v2/episodes.py#L60">medusa/server/api/v2/episodes.py</a>", line 60, in <listcomp>
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/tv/episode.py#L1090">medusa/tv/episode.py</a>", line 1090, in to_json
    data['status'] = self.status_name
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/tv/episode.py#L427">medusa/tv/episode.py</a>", line 427, in status_name
    return statusStrings[self.status]
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dug-g** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/8de4304a23bf999cd628c55e2c54422e
### ERROR
<pre>
2020-04-08 08:14:57 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [9a36461] DailySearchQueueItem Exception, error: KeyError(3276806)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/queue.py#L266">medusa/search/queue.py</a>", line 266, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/core.py#L503">medusa/search/core.py</a>", line 503, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/core.py#L458">medusa/search/core.py</a>", line 458, in wanted_episodes
    should_search, should_search_reason = Quality.should_search(
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/common.py#L543">medusa/common.py</a>", line 543, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dug-g** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/56a8c74b7d482e6bd115dfd6fcf04801
### ERROR
<pre>
2020-04-07 22:14:28 ERROR    BACKLOG :: [9a36461] Exception generated: 3276806
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/scheduler.py#L79">medusa/scheduler.py</a>", line 79, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/backlog.py#L169">medusa/search/backlog.py</a>", line 169, in run
    self.search_backlog()
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/backlog.py#L108">medusa/search/backlog.py</a>", line 108, in search_backlog
    segments = series_obj.get_wanted_segments(from_date=from_date)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/tv/series.py#L2467">medusa/tv/series.py</a>", line 2467, in get_wanted_segments
    should_search, should_search_reason = Quality.should_search(
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/common.py#L543">medusa/common.py</a>", line 543, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Remove the show and re-add it.

**Comment by dug-g** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/abd2a4e9cafc5a1e5757a33f9148144e
### ERROR
<pre>
2020-04-08 15:19:35 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [9a36461] DailySearchQueueItem Exception, error: KeyError(3276806)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/queue.py#L266">medusa/search/queue.py</a>", line 266, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/core.py#L503">medusa/search/core.py</a>", line 503, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/core.py#L458">medusa/search/core.py</a>", line 458, in wanted_episodes
    should_search, should_search_reason = Quality.should_search(
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/common.py#L543">medusa/common.py</a>", line 543, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dug-g** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/3cbde6ffb44def359a09bd15be2afeb1
### ERROR
<pre>
2020-04-12 13:14:58 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [9a36461] DailySearchQueueItem Exception, error: KeyError(3276806)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/queue.py#L266">medusa/search/queue.py</a>", line 266, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/core.py#L503">medusa/search/core.py</a>", line 503, in search_for_needed_episodes
    episodes.extend(wanted_episodes(cur_show, from_date))
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/core.py#L458">medusa/search/core.py</a>", line 458, in wanted_episodes
    should_search, should_search_reason = Quality.should_search(
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/common.py#L543">medusa/common.py</a>", line 543, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dug-g** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/cda89b69b9b291618c413906b7255326
### ERROR
<pre>
2020-04-09 06:33:26 ERROR    BACKLOG :: [9a36461] Exception generated: 3276806
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/scheduler.py#L79">medusa/scheduler.py</a>", line 79, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/backlog.py#L169">medusa/search/backlog.py</a>", line 169, in run
    self.search_backlog()
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/search/backlog.py#L108">medusa/search/backlog.py</a>", line 108, in search_backlog
    segments = series_obj.get_wanted_segments(from_date=from_date)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/tv/series.py#L2467">medusa/tv/series.py</a>", line 2467, in get_wanted_segments
    should_search, should_search_reason = Quality.should_search(
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/common.py#L543">medusa/common.py</a>", line 543, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dug-g** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-04-23 08:00:44 ERROR    Thread_0 :: [9a36461] Exception generated: 3276806
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/server/web/manage/handler.py#L429">medusa/server/web/manage/handler.py</a>", line 429, in backlogOverview
    cur_ep_cat = cur_show.get_overview(cur_result['status'], cur_result['quality'], backlog_mode=True,
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/tv/series.py#L2369">medusa/tv/series.py</a>", line 2369, in get_overview
    elif Quality.should_search(ep_status, ep_quality, self, manually_searched)[0]:
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/common.py#L543">medusa/common.py</a>", line 543, in should_search
    return False, 'Status is not allowed: {0}. Skipping episode'.format(statusStrings[cur_status])
KeyError: 3276806
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
