### ISSUE TITLE
Python crash when Deluge receives a .torrent

### ISSUE THREAD

**Issue by nygage** [pymedusa/Medusa#7933]
**Describe the bug**
When Medusa finds a torrent file and it sends to Deluge, python crash (more datails on logs)

**Expected behavior**
Download the torrent without news

**Medusa (please complete the following information):**
 - OS: Ubuntu 18.04
 - Branch: master
 - Commit: 4d1e78726dc94979cc7908651d13e40f199959a9
 - Python version: 2.7.17
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-04-08 00:03:23 ERROR	SNATCHQUEUE-SNATCH-266189 :: [4d1e787] Snatch failed! For result: The.Blacklist.S07E01.HDTV.720p.AC3.5.1.Español.Spanish
Traceback (most recent call last):
  File "/home/rubio2/.medusa/medusa/search/queue.py", line 459, in run
    self.success = snatch_episode(result)
  File "/home/rubio2/.medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/home/rubio2/.medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/home/rubio2/.medusa/medusa/clients/torrent/deluged.py", line 44, in _get_auth
    return True if self.connect() else None
  File "/home/rubio2/.medusa/medusa/clients/torrent/deluged.py", line 57, in connect
    drpc = DelugeRPC(hostname[1], port=hostname[2], username=self.username, password=self.password)
IndexError: list index out of range
2020-04-08 00:03:19 INFO	SNATCHQUEUE-SNATCH-266189 :: [4d1e787] Downloading The.Blacklist.S07E01.HDTV.720p.AC3.5.1.Español.Spanish with 1 seeders and 0 leechers and size 1.60 GB from NNew, through a SearchType.BACKLOG_SEARCH search
2020-04-08 00:03:19 INFO	SNATCHQUEUE-SNATCH-266189 :: [4d1e787] Beginning to snatch release: The.Blacklist.S07E01.HDTV.720p.AC3.5.1.Español.Spanish
2020-04-08 00:03:19 INFO	FORCEDSEARCHQUEUE-BACKLOG-266189 :: [4d1e787] Downloading The.Blacklist.S07E01.HDTV.720p.AC3.5.1.Español.Spanish with 1 seeders and 0 leechers and size 1.60 GB from NNew
```
</details>

**Additional context**

Thanks

**Comment by nygage** [comment]
Solved, sorry for the apologizes, forgot scgi://

**Comment by OmgImAlexis** [comment]
That error should be caught.
