### ISSUE TITLE
Unable to reinstall Medusa on Ubuntu after removal

### ISSUE THREAD

**Issue by shm613** [pymedusa/Medusa#7934]
**Describe the bug**
After I removed the medusa folder and followed the Ubuntu install guide, I am unable to start Medusa.

**To Reproduce**
sudo systemctl start medusa

**Medusa (please complete the following information):**
 - OS: Ubuntu 18.04 x64
 - Branch: master
 - Commit: 
 - Python version: 3.6.9
 - Database version: default from install

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-04-07 22:28:26 INFO     MAIN :: [] Broken providers found: [u'torrent9', u'newpct']
2020-04-07 22:28:26 INFO     MAIN :: [4d1e787] Query: 'CREATE TABLE blacklist (show_id INTEGER, range TEXT, keyword TEXT);'. Arguments: 'None'
2020-04-07 22:28:26 ERROR    MAIN :: [4d1e787] DB error: OperationalError('disk I/O error',)
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: disk I/O error
2020-04-07 22:28:26 ERROR    MAIN :: [4d1e787] DB error: Error: 'disk I/O error'
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: disk I/O error
2020-04-07 22:28:26 ERROR    MAIN :: [4d1e787] Error in InitialSchema: Error: 'disk I/O error'
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 466, in _processUpgrade
    instance.execute()
  File "/opt/medusa/medusa/databases/main_db.py", line 255, in execute
    self.connection.action(query)
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: disk I/O error
2020-04-07 22:28:29 INFO     MAIN :: [4d1e787] Broken providers found: [u'torrent9', u'newpct']
2020-04-07 22:28:30 INFO     MAIN :: [4d1e787] Backing up database before upgrade
2020-04-07 22:28:30 INFO     MAIN :: [4d1e787] Proceeding with upgrade
2020-04-07 22:28:30 INFO     MAIN :: [4d1e787] Adding column version to tv_episodes and history
2020-04-07 22:28:30 INFO     MAIN :: [4d1e787] Query: 'ALTER TABLE [tv_episodes] ADD version NUMERIC'. Arguments: 'None'
2020-04-07 22:28:30 ERROR    MAIN :: [4d1e787] DB error: OperationalError('duplicate column name: version',)
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: duplicate column name: version
2020-04-07 22:28:30 ERROR    MAIN :: [4d1e787] DB error: Error: 'duplicate column name: version'
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: duplicate column name: version
2020-04-07 22:28:30 ERROR    MAIN :: [4d1e787] Error in AddVersionToTvEpisodes: Error: 'duplicate column name: version'
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 466, in _processUpgrade
    instance.execute()
  File "/opt/medusa/medusa/databases/main_db.py", line 290, in execute
    self.addColumn('tv_episodes', 'version', 'NUMERIC', '-1')
  File "/opt/medusa/medusa/db.py", line 491, in addColumn
    self.connection.action('ALTER TABLE [%s] ADD %s %s' % (table, column, column_type))
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: duplicate column name: version
2020-04-07 22:28:33 INFO     MAIN :: [4d1e787] Broken providers found: [u'torrent9', u'newpct']
2020-04-07 22:28:33 INFO     MAIN :: [4d1e787] Backing up database before upgrade
2020-04-07 22:28:33 INFO     MAIN :: [4d1e787] Proceeding with upgrade
2020-04-07 22:28:33 INFO     MAIN :: [4d1e787] Adding column version to tv_episodes and history
2020-04-07 22:28:33 INFO     MAIN :: [4d1e787] Query: 'ALTER TABLE [tv_episodes] ADD version NUMERIC'. Arguments: 'None'
2020-04-07 22:28:33 ERROR    MAIN :: [4d1e787] DB error: OperationalError('duplicate column name: version',)
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
OperationalError: duplicate column name: version
2020-04-07 22:28:33 ERROR    MAIN :: [4d1e787] DB error: Error: 'duplicate column name: version'

```
</details>

**Additional context**
The log is from the application.log file

**Comment by medariox** [comment]
This is either a hard disk issue (unreliable mount, disk failing,..) or a permission issue (DB file not writable by the user,...).

**Comment by shm613** [comment]
> 
> 
> This is either a hard disk issue (unreliable mount, disk failing,..) or a permission issue (DB file not writable by the user,...).

Where is the DB file located? Here is a screenshot of the permissions on my medusa folder.

![image](https://user-images.githubusercontent.com/24711403/78845999-496d0600-79d8-11ea-8a69-dc20aba45608.png)

**Comment by shm613** [comment]
After removing the folder and following the directions again I now have medusa up and running. I must have done something wrong the last time.
