### ISSUE TITLE
[APP SUBMITTED]: FileNotFoundError: [Errno 2] No such file or directory: '/usr/syno/bin/synoindex'

### ISSUE THREAD

**Issue by dug-g** [pymedusa/Medusa#7936]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@9a364616d1bc7bed025f3c08270ac993cfa0c046
**Link to Log**: https://gist.github.com/661b0c16ea1137ef012309b6ff084a15
### ERROR
<pre>
2020-04-07 18:35:47 ERROR    POSTPROCESSOR :: [9a36461] Unable to run synoindex: Error: 2: No such file or directory
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9a364616d1bc7bed025f3c08270ac993cfa0c046/medusa/notifiers/synoindex.py#L72">medusa/notifiers/synoindex.py</a>", line 72, in makeObject
    p = subprocess.Popen(synoindex_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/syno/bin/synoindex'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Read about how to use external scripts correctly: https://github.com/pymedusa/Medusa/wiki/External-scripts
