### ISSUE TITLE
Existing shows not updating with new episode info and status

### ISSUE THREAD

**Issue by zodd721** [pymedusa/Medusa#7948]
I've been noticing that new episode info is not being pulled down.
So, newly released episodes are not getting updated and added to the schedule.
If I go into a show and click "Force Full Update" it will pull down the new episode info and status. However, this is no longer happening automatically.

Medusa Info: 
Branch: master
Commit: 4d1e78726dc94979cc7908651d13e40f199959a9
Version: 0.3.14
Database: 44.14
Python Version: | 3.7.7 (default, Mar 10 2020, 17:25:08) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.4.0-176-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | en_US.UTF-8

Errors logs:

2020-04-10 13:29:18 ERROR    APIv2-Thread_3 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 13:29:11 ERROR    TORNADO :: [4d1e787] Uncaught exception in APIv2: TypeError('an integer is required (got type NoneType)')
Request: GET /api/v2/series?limit=1000&page=1 (192.168.0.215)
Traceback (most recent call last):
  File "/opt/medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/medusa/ext/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/medusa/medusa/server/api/v2/base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/series.py", line 56, in get
    for s in Series.find_series(predicate=filter_series)
  File "/opt/medusa/medusa/server/api/v2/series.py", line 56, in <listcomp>
    for s in Series.find_series(predicate=filter_series)
  File "/opt/medusa/medusa/tv/series.py", line 2053, in to_json
    data['lastUpdate'] = datetime.date.fromordinal(self._last_update_indexer).isoformat()
TypeError: an integer is required (got type NoneType)

**Comment by medariox** [comment]
We need a debug logs.

**Comment by medariox** [comment]
Fill out the template and open a new issue, we can't help otherwise: https://github.com/pymedusa/Medusa/issues/new?template=bug_report.md
