### ISSUE TITLE
Existing shows not updating with new episode info and status

### ISSUE THREAD

**Issue by zodd721** [pymedusa/Medusa#7949]
**Describe the bug**
I've been noticing that new episode info is not being pulled and updated automatically.
I've seen this with multiple shows. It seems any shows that already downloaded the schedule info previously work fine. But if the episodes are unaired they never update.
So, newly released episodes are not getting updated and added to the schedule.
If I go into a show and click "Force Full Update" it will pull down the new episode info and status. 

**To Reproduce**
1. Go to a show that aired recently 1-2 days ago and shows aired on TVDB.
2. Episode status/info is not updated with a wanted status or info showing that it has already aired.
3. In the selected show click on "Force Full Update" button
4. After forced update the episode info updates

**Expected behavior**
Medusa automatically updates my continuing shows with new episode info as they air and get updated on TVDB.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Linux-4.4.0-176-generic-x86_64-with-Ubuntu-16.04-xenial
 - Branch: master
 - Commit: 4d1e78726dc94979cc7908651d13e40f199959a9
 - Python version: 3.7.7 (default, Mar 10 2020, 17:25:08) [GCC 5.4.0 20160609]
 - Database version: 44.14

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-04-10 12:01:26 INFO     TORNADO :: [4d1e787] 304 GET /api/v2/series/tvdb329089/episodes?limit=1000&season=2 (192.168.0.215) 47.95ms
2020-04-10 12:01:26 INFO     TORNADO :: [4d1e787] 200 GET /api/v2/series/tvdb329089/episodes?limit=1000&season=1 (192.168.0.215) 59.19ms
2020-04-10 12:01:26 ERROR    TORNADO :: [4d1e787] Uncaught exception in APIv2: TypeError('an integer is required (got type NoneType)')
Request: GET /api/v2/series?limit=1000&page=1 (192.168.0.215)
Traceback (most recent call last):
  File "/opt/medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/medusa/ext/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/medusa/medusa/server/api/v2/base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/series.py", line 56, in get
    for s in Series.find_series(predicate=filter_series)
  File "/opt/medusa/medusa/server/api/v2/series.py", line 56, in <listcomp>
    for s in Series.find_series(predicate=filter_series)
  File "/opt/medusa/medusa/tv/series.py", line 2053, in to_json
    data['lastUpdate'] = datetime.date.fromordinal(self._last_update_indexer).isoformat()
TypeError: an integer is required (got type NoneType)
2020-04-10 12:01:33 DEBUG    Thread_1 :: [4d1e787] GET URL: https://cdn.pymedusa.com/providers/broken_providers.json [Status: 200]
2020-04-10 12:01:33 DEBUG    Thread_1 :: [4d1e787] User-Agent: Medusa/0.3.14 (Linux; 4.4.0-176-generic; 1709da46-7878-11ea-babf-00155d006900)
2020-04-10 12:01:33 INFO     Thread_1 :: [4d1e787] Broken providers found: ['torrent9', 'newpct']
2020-04-10 12:01:34 INFO     TORNADO :: [4d1e787] 200 GET /history/ (192.168.0.215) 1380.10ms
2020-04-10 12:01:34 INFO     TORNADO :: [4d1e787] 101 GET /ws/ui (192.168.0.215) 0.48ms
2020-04-10 12:01:34 INFO     TORNADO :: [4d1e787] 200 GET /images/providers/rarbg.png (192.168.0.215) 5.10ms
2020-04-10 12:01:34 INFO     TORNADO :: [4d1e787] 200 GET /images/providers/nzbgeek.png (192.168.0.215) 7.05ms
2020-04-10 12:01:34 INFO     TORNADO :: [4d1e787] 200 GET /api/v2/config/ (192.168.0.215) 6.33ms
2020-04-10 12:01:35 INFO     TORNADO :: [4d1e787] 200 GET /api/v2/series/tvdb72170/asset/fanart?api_key=********** (192.168.0.215) 15.43ms
2020-04-10 12:01:35 INFO     TORNADO :: [4d1e787] 304 GET /api/v2/stats/ (192.168.0.215) 355.63ms
2020-04-10 12:01:43 INFO     TORNADO :: [4d1e787] 200 GET /home/displayShow?indexername=tvdb&seriesid=276515 (192.168.0.215) 10.13ms
2020-04-10 12:01:43 INFO     TORNADO :: [4d1e787] 101 GET /ws/ui (192.168.0.215) 0.78ms
2020-04-10 12:01:44 INFO     TORNADO :: [4d1e787] 200 GET /api/v2/config/ (192.168.0.215) 17.65ms
2020-04-10 12:01:44 INFO     TORNADO :: [4d1e787] 304 GET /api/v2/stats/ (192.168.0.215) 343.00ms
2020-04-10 12:01:44 DEBUG    APIv2-Thread_4 :: [4d1e787] Looking up XEM scene mapping for show ID 276515 on tvdb
2020-04-10 12:01:44 DEBUG    APIv2-Thread_4 :: [4d1e787] GET URL: http://thexem.de/map/havemap?origin=tvdb [Status: 200]
2020-04-10 12:01:44 DEBUG    APIv2-Thread_4 :: [4d1e787] User-Agent: Medusa/0.3.14 (Linux; 4.4.0-176-generic; 1709da46-7878-11ea-babf-00155d006900)
2020-04-10 12:01:44 DEBUG    APIv2-Thread_4 :: [4d1e787] No XEM data for show ID 276515 on tvdb
2020-04-10 12:01:44 INFO     TORNADO :: [4d1e787] 200 GET /api/v2/series/tvdb276515?detailed=true (192.168.0.215) 951.90ms
2020-04-10 12:01:45 INFO     TORNADO :: [4d1e787] 200 GET /api/v2/search/tvdb276515 (192.168.0.215) 32.41ms
2020-04-10 12:01:45 INFO     TORNADO :: [4d1e787] 304 GET /api/v2/series/tvdb276515/asset/banner?api_key=********** (192.168.0.215) 40.15ms
2020-04-10 12:01:45 INFO     TORNADO :: [4d1e787] 200 GET /api/v2/series/tvdb276515/asset/posterThumb?api_key=********** (192.168.0.215) 43.97ms
2020-04-10 12:01:45 INFO     TORNADO :: [4d1e787] 200 GET /api/v2/series/tvdb276515/asset/fanart?api_key=********** (192.168.0.215) 49.05ms
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__
    self._specify_episode(self.season, self.episode)
  File "/opt/medusa/medusa/tv/episode.py", line 572, in _specify_episode
    sql_results = self.load_from_db(season, episode)
Traceback (most recent call last):
  File "/opt/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: 'NULL'
2020-04-10 12:01:45 ERROR    APIv2-Thread_4 :: [4d1e787] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "/opt/medusa/medusa/tv/series.py", line 764, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "/opt/medusa/medusa/tv/series.py", line 878, in get_episode
    ep = Episode(self, season, episode)
  File "/opt/medusa/medusa/tv/episode.py", line 272, in __init__

```
</details>

**Additional context**

I can attach the entire application debug log if needed?

Thank you

**Comment by medariox** [comment]
Shows that have this issue were probably added while TheTVDB had big issues a few weeks ago. Sadly there is not much we can do about it from our side. The easiest thing to do is remove the affected shows (keep media) and add them back again.

**Comment by zodd721** [comment]
Weird, the first two tvdb ids I see in error don't fit that criteria. One was added last week and the other has been in my shows list for many years.
However, you've given me a solution to hopefully get it cleaned up and working. So, I'll give that a shot.

Thanks

**Comment by zodd721** [comment]
Further findings... this seems to affect the auto updates of all the shows I've checked. I've determined that the errors in the debug logs actually happen under two different events. 1.After deleting then during the process of adding the show back and 2. When I click the force full update button on any show.
I've also verified that all of the jobs under the scheduler seem to be running regularly.

So, since I have no idea what shows are affected by this, would it make the most sense to just delete  all of my shows and re-add them at this point? maybe there's a simpler en-mass way? Do you think doing this will actually fix the problem?

Thank you

**Comment by p0psicles** [comment]
You could do a force full update for the shows that are continuing. That should update them for now. And then (if tvdb has there shit together) it should update with the shows next change.

**Comment by medariox** [comment]
@zodd721 
If you upload your `main.db` file to https://send.firefox.com/ I can fix the entries for you.

**Comment by zodd721** [comment]
@medariox 
Here's the link to my main.db
[https://send.firefox.com/download/b9d5d33d6136ffe9/#A8PcN2QQEDMNYqUSjuxAPA](url)

I appreciate all of the help.

**Comment by medariox** [comment]
@zodd721

Here you go: https://send.firefox.com/download/3e0ad0e0c54fb531/#wXfrNddkYof5SvyFFLJU6g

I've removed the 2 shows that were causing the issue (Horace and Pete & Top Gear: Extra Gear). You can add them back now. The issue was surely caused by TheTVDB returning corrupt results and shouldn't happen anymore.

**Comment by HPMSGEN8** [comment]
So a Mass Update will solve this issue then ?

**Comment by medariox** [comment]
No, if the entries are corrupt send the `main.db` file. Otherwise the show updates work just fine.

**Comment by HPMSGEN8** [comment]
@medariox I have had no updates for a few weeks it seems so when i did an update on a show it updated it.  Is there an easy way to find show updates that are corrupt in the DB ?

**Comment by medariox** [comment]
You will get an error if a show is corrupt.

**Comment by HPMSGEN8** [comment]
@medariox Then how do i find it please what can i look for or do ?

**Comment by medariox** [comment]
What? If many people have this issue where are the error reports? What are you talking about? There is nothing wrong with the show updates. If you have an issue open a new issue with all relevant info and debug logs.
