### ISSUE TITLE
[APP SUBMITTED]: UnicodeDecodeError: 'utf8' codec can't decode byte 0x87 in position 6: invalid start byte

### ISSUE THREAD

**Issue by skiant** [pymedusa/Medusa#7952]
### INFO
**Python Version**: `2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]`
**Operating System**: `Linux-2.6.32-042stab139.1-x86_64-with-Ubuntu-16.04-xenial`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.14`
**Commit**: pymedusa/Medusa@4d1e78726dc94979cc7908651d13e40f199959a9
**Link to Log**: https://gist.github.com/c3aae0a9afc0e455218844cf0084d48a
### ERROR
<pre>
2020-04-11 13:30:02 ERROR    Thread_0 :: [4d1e787] Exception generated: 'utf8' codec can't decode byte 0x87 in position 6: invalid start byte
Traceback (most recent call last):
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/server/web/core/base.py#L251">medusa/server/web/core/base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/server/web/home/post_process.py#L61">medusa/server/web/home/post_process.py</a>", line 61, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L65">medusa/process_tv.py</a>", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L169">medusa/process_tv.py</a>", line 169, in process
    if not self.should_process(path, failed):
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/process_tv.py#L257">medusa/process_tv.py</a>", line 257, in should_process
    for root, dirs, files in os.walk(path):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/init/filesystem.py#L112">medusa/init/filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/init/filesystem.py#L49">medusa/init/filesystem.py</a>", line 49, in _handle_output_u
    return list(map(_handle_output_u, result))
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/init/filesystem.py#L46">medusa/init/filesystem.py</a>", line 46, in _handle_output_u
    return decode(result)
  File "/home/seedit4me/.medusa/<a href="../blob/4d1e78726dc94979cc7908651d13e40f199959a9/medusa/init/filesystem.py#L32">medusa/init/filesystem.py</a>", line 32, in decode
    return text_type(value, fs_encoding if valid_encoding else 'utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x87 in position 6: invalid start byte
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by skiant** [comment]
I assume there's a file in the download folder triggering this, but I cannot figure out which one.

**Comment by p0psicles** [comment]
Switch to python 3.7 or 3.8
