### ISSUE TITLE
Error 500 trying to create scene exception

### ISSUE THREAD

**Issue by johnvick** [pymedusa/Medusa#7971]
Branch: masterCommit: d0c136d7a528a471b51676140bd35d24d97f65c6Version: 0.3.15Database: 44.15
--
Python Version: | 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.15.0-58-generic-x86_64-with
Locale: | en_US.UTF-8

User: | root
Program Folder: | /app/medusa
Config File: | /config/config.ini
Database File: | /config/main.db
Cache Folder: | /config/cache
Log Folder: | /config/Logs
Arguments: | --nolaunch --datadir /config
Web Root: | /medusa
Runs in Docker: | Yes

Just updated Docker to above version new problem just arisen error 500 on trying to save scene exception. Log gives this:
```
2020-04-15 05:30:59 ERROR    TORNADO :: [d0c136d] Uncaught exception in APIv2: TypeError('string indices must be integers')
Request: PATCH /medusa/api/v2/series/tvdb374959 (127.0.0.1)
With body:
{"config":{"aliases":["xx"],"defaultEpisodeStatus":"Wanted","dvdOrder":false,"seasonFolders":true,"anime":false,"scene":false,"sports":false,"paused":false,"location":"/mnt/Documentaries/Welcome to HMP Belmarsh with Ross Kemp","airByDate":false,"subtitlesEnabled":false,"release":{"requiredWords":[],"ignoredWords":[],"requiredWordsExclude":false,"ignoredWordsExclude":false},"qualities":{"preferred":[],"allowed":[8,64,256]},"airdateOffset":0},"language":"en"}
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/app/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/app/medusa/ext/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/medusa/medusa/server/api/v2/base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/medusa/medusa/server/api/v2/series.py", line 152, in patch
    if patch_field and patch_field.patch(series, value):
  File "/app/medusa/medusa/server/api/v2/base.py", line 535, in patch
    setattr(target, self.attr, self.converter(value))
  File "/app/medusa/medusa/tv/base.py", line 57, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/app/medusa/medusa/tv/series.py", line 610, in aliases
    update_scene_exceptions(self, exceptions)
  File "/app/medusa/medusa/scene_exceptions.py", line 219, in update_scene_exceptions
    if exception['title'] not in exceptions_cache[(series_obj.indexer, series_obj.series_id)][exception['season']]:
TypeError: string indices must be integers
```

**Comment by p0psicles** [comment]
Can you reproduce the issue?
Also did you refresh the page after the update? Like make sure there is no cache.

**Comment by jvdivx** [comment]
I have the same problem

**Comment by p0psicles** [comment]
It's a cache issue. Close / open your browser.
Else create screenshots, of the exception list?

**Comment by medariox** [comment]
https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/

**Comment by johnvick** [comment]
Thanks all clearing the cache fixed it.
