### ISSUE TITLE
[APP SUBMITTED]: TypeError: expected string or buffer

### ISSUE THREAD

**Issue by andersonwallacerj** [pymedusa/Medusa#7978]
### INFO
**Python Version**: `2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]`
**Operating System**: `Linux-3.10.70-armv7l-with-glibc2.4`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/01ccde4bc86cb76afaa9efa0d1d77b22
### ERROR
<pre>
2020-04-15 20:29:52 ERROR    FINDSUBTITLES :: [8f6b666] Exception generated: expected string or buffer
Traceback (most recent call last):
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/scheduler.py#L78">medusa/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L1062">medusa/subtitles.py</a>", line 1062, in run
    episode_object.download_subtitles()
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/tv/episode.py#L503">medusa/tv/episode.py</a>", line 503, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L446">medusa/subtitles.py</a>", line 446, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L314">medusa/subtitles.py</a>", line 314, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/score.py#L112">ext/subliminal/score.py</a>", line 112, in compute_score
    matches = subtitle.get_matches(video)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/providers/opensubtitles.py#L87">ext/subliminal/providers/opensubtitles.py</a>", line 87, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': self.movie_kind}))
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L226">ext/subliminal/matches.py</a>", line 226, in guess_matches
    if key in matches_manager and matches_manager[key](video, partial=partial, **guess):
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L21">ext/subliminal/matches.py</a>", line 21, in series_matches
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L21">ext/subliminal/matches.py</a>", line 21, in <genexpr>
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/utils.py#L122">ext/subliminal/utils.py</a>", line 122, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/local/AppCentral/python/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bluelavalamp** [comment]
### INFO
**Python Version**: `2.7.15 (default, Jun 17 2018, 22:57:51) [GCC 7.3.0]`
**Operating System**: `Linux-5.1.4-x86_64-Intel-R-_Core-TM-_i5-9600K_CPU_@_3.70GHz-with-slackware-14.2`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/9e4c4677d95d3b023aff251bb3bc7000
### ERROR
<pre>
2020-04-15 17:41:17 ERROR    FINDSUBTITLES :: [8f6b666] Exception generated: expected string or buffer
Traceback (most recent call last):
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
This is a subliminal bug, please report here: https://github.com/Diaoul/subliminal/issues

**Comment by kidiavn** [comment]
### INFO
**Python Version**: `2.7.13 (default, Apr 11 2017, 16:05:39) [GCC 4.8.4]`
**Operating System**: `Linux-4.2.8-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/0bd69462e9ae72c12a922abf8b28a31c
### ERROR
<pre>
2020-04-16 20:52:30 ERROR    FINDSUBTITLES :: [8f6b666] Exception generated: expected string or buffer
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/scheduler.py#L78">medusa/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L1062">medusa/subtitles.py</a>", line 1062, in run
    episode_object.download_subtitles()
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/tv/episode.py#L503">medusa/tv/episode.py</a>", line 503, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L446">medusa/subtitles.py</a>", line 446, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L314">medusa/subtitles.py</a>", line 314, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/score.py#L112">ext/subliminal/score.py</a>", line 112, in compute_score
    matches = subtitle.get_matches(video)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/providers/opensubtitles.py#L87">ext/subliminal/providers/opensubtitles.py</a>", line 87, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': self.movie_kind}))
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L226">ext/subliminal/matches.py</a>", line 226, in guess_matches
    if key in matches_manager and matches_manager[key](video, partial=partial, **guess):
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L21">ext/subliminal/matches.py</a>", line 21, in series_matches
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L21">ext/subliminal/matches.py</a>", line 21, in <genexpr>
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/Medusa/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/utils.py#L122">ext/subliminal/utils.py</a>", line 122, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/share/CACHEDEV1_DATA/.qpkg/Medusa/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by andersonwallacerj** [comment]
### INFO
**Python Version**: `2.7.10 (default, Jan  6 2016, 14:39:32) [GCC 4.6.4]`
**Operating System**: `Linux-3.10.70-armv7l-with-glibc2.4`
**Locale**: `None`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-04-18 20:33:43 ERROR    FINDSUBTITLES :: [8f6b666] Exception generated: expected string or buffer
Traceback (most recent call last):
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/scheduler.py#L78">medusa/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L1062">medusa/subtitles.py</a>", line 1062, in run
    episode_object.download_subtitles()
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/tv/episode.py#L503">medusa/tv/episode.py</a>", line 503, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L446">medusa/subtitles.py</a>", line 446, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L314">medusa/subtitles.py</a>", line 314, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/score.py#L112">ext/subliminal/score.py</a>", line 112, in compute_score
    matches = subtitle.get_matches(video)
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/providers/opensubtitles.py#L87">ext/subliminal/providers/opensubtitles.py</a>", line 87, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': self.movie_kind}))
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L226">ext/subliminal/matches.py</a>", line 226, in guess_matches
    if key in matches_manager and matches_manager[key](video, partial=partial, **guess):
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L21">ext/subliminal/matches.py</a>", line 21, in series_matches
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L21">ext/subliminal/matches.py</a>", line 21, in <genexpr>
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/SickBeard-TVRage/<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/utils.py#L122">ext/subliminal/utils.py</a>", line 122, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/local/AppCentral/python/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by al31nosok** [comment]
### INFO
**Python Version**: `2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]`
**Operating System**: `Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/f99e66a4545af1667852064398dc8b1a
### ERROR
<pre>
2020-04-22 21:56:55 ERROR    FINDSUBTITLES :: [8f6b666] Exception generated: expected string or buffer
Traceback (most recent call last):
  File "/home/hd29/**********/apps/medusa/medusa/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/home/hd29/**********/apps/medusa/medusa/subtitles.py", line 1062, in run
    episode_object.download_subtitles()
  File "/home/hd29/**********/apps/medusa/medusa/tv/episode.py", line 503, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/home/hd29/**********/apps/medusa/medusa/subtitles.py", line 446, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/home/hd29/**********/apps/medusa/medusa/subtitles.py", line 314, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/home/hd29/**********/apps/medusa/ext/subliminal/score.py", line 112, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/hd29/**********/apps/medusa/ext/subliminal/providers/opensubtitles.py", line 87, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': self.movie_kind}))
  File "/home/hd29/**********/apps/medusa/ext/subliminal/matches.py", line 226, in guess_matches
    if key in matches_manager and matches_manager[key](video, partial=partial, **guess):
  File "/home/hd29/**********/apps/medusa/ext/subliminal/matches.py", line 21, in series_matches
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/home/hd29/**********/apps/medusa/ext/subliminal/matches.py", line 21, in <genexpr>
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/home/hd29/**********/apps/medusa/ext/subliminal/utils.py", line 122, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by al31nosok** [comment]
### INFO
**Python Version**: `2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]`
**Operating System**: `Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/b92e3c3cf65b60053f04fbef0d53be2a
### ERROR
<pre>
2020-04-23 10:36:15 ERROR    FINDSUBTITLES :: [8f6b666] Exception generated: expected string or buffer
Traceback (most recent call last):
  File "/home/hd29/**********/apps/medusa/medusa/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/home/hd29/**********/apps/medusa/medusa/subtitles.py", line 1062, in run
    episode_object.download_subtitles()
  File "/home/hd29/**********/apps/medusa/medusa/tv/episode.py", line 503, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "/home/hd29/**********/apps/medusa/medusa/subtitles.py", line 446, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "/home/hd29/**********/apps/medusa/medusa/subtitles.py", line 314, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "/home/hd29/**********/apps/medusa/ext/subliminal/score.py", line 112, in compute_score
    matches = subtitle.get_matches(video)
  File "/home/hd29/**********/apps/medusa/ext/subliminal/providers/opensubtitles.py", line 87, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': self.movie_kind}))
  File "/home/hd29/**********/apps/medusa/ext/subliminal/matches.py", line 226, in guess_matches
    if key in matches_manager and matches_manager[key](video, partial=partial, **guess):
  File "/home/hd29/**********/apps/medusa/ext/subliminal/matches.py", line 21, in series_matches
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/home/hd29/**********/apps/medusa/ext/subliminal/matches.py", line 21, in <genexpr>
    sanitize(name) for name in [video.series] + video.alternative_series
  File "/home/hd29/**********/apps/medusa/ext/subliminal/utils.py", line 122, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
already fixed in develop

**Comment by pct00** [comment]
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@8f6b6665c778cb456899809877c3bc15a547abf6
**Link to Log**: https://gist.github.com/680c10eba53a4d3949a678f77810987d
### ERROR
<pre>
2020-04-23 19:44:19 ERROR    Thread_5 :: [8f6b666] Exception generated: expected string or buffer
Traceback (most recent call last):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/server/web/core/base.py#L251">medusa\server\web\core\base.py</a>", line 251, in async_call
    result = function(**kwargs)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/server/web/home/post_process.py#L61">medusa\server\web\home\post_process.py</a>", line 61, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/process_tv.py#L65">medusa\process_tv.py</a>", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/process_tv.py#L188">medusa\process_tv.py</a>", line 188, in process
    ignore_subs=ignore_subs)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/process_tv.py#L378">medusa\process_tv.py</a>", line 378, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/process_tv.py#L599">medusa\process_tv.py</a>", line 599, in process_media
    self.result = processor.process()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/post_processor.py#L1254">medusa\post_processor.py</a>", line 1254, in process
    cur_ep.download_subtitles()
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/tv/episode.py#L503">medusa\tv\episode.py</a>", line 503, in download_subtitles
    new_subtitles = subtitles.download_subtitles(self, lang=lang)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L446">medusa\subtitles.py</a>", line 446, in download_subtitles
    scored_subtitles = score_subtitles(subtitles_list, video)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/medusa/subtitles.py#L314">medusa\subtitles.py</a>", line 314, in score_subtitles
    for s in subtitles_list], key=operator.itemgetter(1, 2), reverse=True)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/score.py#L112">ext\subliminal\score.py</a>", line 112, in compute_score
    matches = subtitle.get_matches(video)
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/providers/podnapisi.py#L54">ext\subliminal\providers\podnapisi.py</a>", line 54, in get_matches
    'episode': self.episode
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L226">ext\subliminal\matches.py</a>", line 226, in guess_matches
    if key in matches_manager and matches_manager[key](video, partial=partial, **guess):
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L21">ext\subliminal\matches.py</a>", line 21, in series_matches
    sanitize(name) for name in [video.series] + video.alternative_series
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/matches.py#L21">ext\subliminal\matches.py</a>", line 21, in <genexpr>
    sanitize(name) for name in [video.series] + video.alternative_series
  File "C:\Program Files\Medusa\Medusa\<a href="../blob/8f6b6665c778cb456899809877c3bc15a547abf6/ext/subliminal/utils.py#L122">ext\subliminal\utils.py</a>", line 122, in sanitize
    string = re.sub(r'[%s]' % re.escape(''.join(characters)), ' ', string)
  File "C:\Program Files\Medusa\Python\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
