### ISSUE TITLE
Show Update appears to not be running automatically

### ISSUE THREAD

**Issue by zodd721** [pymedusa/Medusa#7980]
**Describe the bug**
Under server status the "Show Update" hasn't run for 2 days.
The last run time was from the restart after applying the 0.3.15 update on 4/14

**To Reproduce**
1. Navigate to "Server Status".
2. Show Update status in False state
3. Show update hasn't run since 4/14/20
See screenshot

**Expected behavior**
Medusa automatically runs the show update and updates my show/episode info on a schedule.

**Screenshots**
![2020-04-16 09_04_35-Status_Medusa](https://user-images.githubusercontent.com/44557412/79465839-749bba80-7fc1-11ea-9346-5752cc3b4376.png)

**Medusa (please complete the following information):**
 - OS: Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic
 - Branch: master
 - Commit: 8f6b6665c778cb456899809877c3bc15a547abf6
 - Python version: 3.7.7 (default, Mar 10 2020, 17:25:08) [GCC 5.4.0 20160609]
 - Database version: 44.15

**Debug logs (at least 50 lines):**
```
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] Getting episodes for 259669
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] Getting all episodes of 259669
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] GET URL: https://api.thetvdb.com/series/259669/episodes/query?page=1 [Status: 200]
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] User-Agent: Medusa/0.3.15 (Linux; 4.15.0-96-generic; 549eb038-7e78-11ea-83e8-00155d006900)
2020-04-15 04:26:40 INFO     SHOWUPDATER :: [8f6b666] The show Black Sails is paused, not updating it.
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] Getting episodes for 78901
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] Getting all episodes of 78901
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] GET URL: https://api.thetvdb.com/series/78901/episodes/query?page=1 [Status: 200]
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] User-Agent: Medusa/0.3.15 (Linux; 4.15.0-96-generic; 549eb038-7e78-11ea-83e8-00155d006900)
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] GET URL: https://api.thetvdb.com/series/78901/episodes/query?page=2 [Status: 200]
2020-04-15 04:26:40 DEBUG    SHOWUPDATER :: [8f6b666] User-Agent: Medusa/0.3.15 (Linux; 4.15.0-96-generic; 549eb038-7e78-11ea-83e8-00155d006900)
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] GET URL: https://api.thetvdb.com/series/78901/episodes/query?page=3 [Status: 200]
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] User-Agent: Medusa/0.3.15 (Linux; 4.15.0-96-generic; 549eb038-7e78-11ea-83e8-00155d006900)
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] GET URL: https://api.thetvdb.com/series/78901/episodes/query?page=4 [Status: 200]
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] User-Agent: Medusa/0.3.15 (Linux; 4.15.0-96-generic; 549eb038-7e78-11ea-83e8-00155d006900)
2020-04-15 04:26:41 INFO     SHOWUPDATER :: [8f6b666] The show Frisky Dingo is paused, not updating it.
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] Skipping show update for Street Outlaws: New Orleans. Show was not in the indexers TVDBv2 list with updated shows and it was updated within the last 12 weeks.
2020-04-15 04:26:41 INFO     SHOWUPDATER :: [8f6b666] The show He-Man and the Masters of the Universe is paused, not updating it.
2020-04-15 04:26:41 INFO     SHOWUPDATER :: [8f6b666] The show He-Man and the Masters of the Universe (2002) is paused, not updating it.
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] Getting episodes for 305378
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] Getting all episodes of 305378
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] GET URL: https://api.thetvdb.com/series/305378/episodes/query?page=1 [Status: 200]
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] User-Agent: Medusa/0.3.15 (Linux; 4.15.0-96-generic; 549eb038-7e78-11ea-83e8-00155d006900)
2020-04-15 04:26:41 INFO     SHOWUPDATER :: [8f6b666] The show Transformers is paused, not updating it.
2020-04-15 04:26:41 INFO     SHOWUPDATER :: [8f6b666] The show Vinyl is paused, not updating it.
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] Getting episodes for 296762
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] Getting all episodes of 296762
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] GET URL: https://api.thetvdb.com/series/296762/episodes/query?page=1 [Status: 200]
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] User-Agent: Medusa/0.3.15 (Linux; 4.15.0-96-generic; 549eb038-7e78-11ea-83e8-00155d006900)
2020-04-15 04:26:41 INFO     SHOWUPDATER :: [8f6b666] Westworld: Adding the following seasons for update to queue: [3]

2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] Skipping show update for American Crime Story. Show was not in the indexers TVDBv2 list with updated shows and it was updated within the last 12 weeks.
2020-04-15 04:26:41 INFO     SHOWUPDATER :: [8f6b666] The show The Get Down is paused, not updating it.
2020-04-15 04:26:41 INFO     SHOWUPDATER :: [8f6b666] The show She-Ra: Princess of Power is paused, not updating it.
2020-04-15 04:26:41 DEBUG    SHOWUPDATER :: [8f6b666] Skipping show update for Cake Wars. Show was not in the indexers TVDBv2 list with updated shows and it was updated within the last 12 weeks.
2020-04-15 04:26:41 ERROR    SHOWUPDATER :: [8f6b666] Exception generated: an integer is required (got type NoneType)
Traceback (most recent call last):
  File "/opt/medusa/medusa/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/opt/medusa/medusa/show_updater.py", line 111, in run
    if show.last_update_indexer > time.time() - 604800 * update_max_weeks:
  File "/opt/medusa/medusa/tv/series.py", line 554, in last_update_indexer
    update_date = datetime.date.fromordinal(self._last_update_indexer)
TypeError: an integer is required (got type NoneType)
2020-04-15 04:26:44 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 4.94ms
2020-04-15 04:27:00 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 8.47ms
2020-04-15 04:27:16 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 4.08ms
2020-04-15 04:27:32 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 9.37ms
2020-04-15 04:27:48 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 6.63ms
2020-04-15 04:28:04 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 1.69ms
2020-04-15 04:28:20 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 3.42ms
2020-04-15 04:28:36 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 2.95ms
2020-04-15 04:28:52 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 8.91ms
2020-04-15 04:29:08 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 2.68ms
2020-04-15 04:29:24 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 2.33ms
2020-04-15 04:29:40 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 3.93ms
2020-04-15 04:29:56 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 7.93ms
2020-04-15 04:30:12 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 10.57ms
2020-04-15 04:30:28 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 13.37ms
2020-04-15 04:30:44 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 3.74ms
2020-04-15 04:31:00 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 4.48ms
2020-04-15 04:31:16 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 5.70ms
2020-04-15 04:31:32 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 21.90ms
2020-04-15 04:31:48 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 6.60ms
2020-04-15 04:32:04 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 6.36ms
2020-04-15 04:32:20 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 11.09ms
2020-04-15 04:32:36 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 7.28ms
2020-04-15 04:32:52 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 10.30ms
2020-04-15 04:33:08 INFO     TORNADO :: [8f6b666] 304 GET /api/v2/search/tvdb356163 (192.168.0.215) 6.45ms

```
</details>

**Additional context**
The traceback in this debug was the last error I've seen since I noticed this stopped working.

**Comment by medariox** [comment]
Thanks for the updated info, now we can actually help you. You have a real messed up DB... please upload your `main.db` to https://send.firefox.com/ so I can fix it.

**Comment by zodd721** [comment]
Here's the link to my DB file:
https://send.firefox.com/download/7979603a72efc2e2/#kj9-czch_Hyh-RNuCULubQ

Thanks

**Comment by medariox** [comment]
Here you go: https://send.firefox.com/download/97a5c7ad2a3ba3fb/#APa09b4Q6M7k-aAo5ViQBQ

How did you add these 2 shows again? With nfo files?

**Comment by zodd721** [comment]
Sorry, I'm not sure which 2 shows you're asking about? I add everything through the "add shows" wizard in Medusa. I'm not sure how to add them with nfo files.

Thanks

**Comment by medariox** [comment]
Horace and Pete and Top Gear Extra. Did you add them back from withing Medusa?

**Comment by zodd721** [comment]
No, I didn't add them back. I'm assuming you're saying they were in the DB again. So, if they came back I have no idea how. This time I also deleted the cache.db file before starting up your fixed copy of the DB. Do you think that might help?

**Comment by zodd721** [comment]
Ok, to put this one to bed. I checked the DB last night and this morning and both shows haven't returned. The show update also ran successfully last night... I'm going to say it had to be user error on my part. Somehow, I must've mixed up the copies of the DB. I'd like to think I don't do things like that but........
Anyways, thanks for all of your help and sorry about the confusion going through this twice. It's been 24 hours and my error log is clean. It hasn't been this way in a long time.
