### ISSUE TITLE
[APP SUBMITTED]: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)

### ISSUE THREAD

**Issue by Miicker** [pymedusa/Medusa#8005]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/4202f04cf25864f8d50d35e63368bc27
### ERROR
<pre>
2020-04-23 15:17:01 ERROR    CHECKVERSION :: [918cfe7] Environment error: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L384">ext/urllib3/connectionpool.py</a>", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L380">ext/urllib3/connectionpool.py</a>", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L439">ext/requests/adapters.py</a>", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/util/retry.py#L367">ext/urllib3/util/retry.py</a>", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/packages/six.py#L686">ext/urllib3/packages/six.py</a>", line 686, in reraise
    raise value
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L386">ext/urllib3/connectionpool.py</a>", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L306">ext/urllib3/connectionpool.py</a>", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/scheduler.py#L78">medusa/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L45">medusa/updater/version_checker.py</a>", line 45, in run
    if self.check_for_new_version(force):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L253">medusa/updater/version_checker.py</a>", line 253, in check_for_new_version
    if not self.updater.need_update():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/docker_updater.py#L28">medusa/updater/docker_updater.py</a>", line 28, in need_update
    if self.branch == 'master' and not self.is_latest_version():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/update_manager.py#L42">medusa/updater/update_manager.py</a>", line 42, in is_latest_version
    if LooseVersion(self.newest_version) > LooseVersion(self.current_version):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/source_updater.py#L67">medusa/updater/source_updater.py</a>", line 67, in newest_version
    latest_release = get_latest_release(self.github_org, self.github_repo)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/github_client.py#L119">medusa/github_client.py</a>", line 119, in get_latest_release
    return gh.get_organization(organization).get_repo(repo).get_latest_release()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/MainClass.py#L293">ext/github/MainClass.py</a>", line 293, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L321">ext/github/Requester.py</a>", line 321, in requestJsonAndCheck
    *self.requestJson(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L413">ext/github/Requester.py</a>", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L474">ext/github/Requester.py</a>", line 474, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L501">ext/github/Requester.py</a>", line 501, in __requestRaw
    response = cnx.getresponse()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L113">ext/github/Requester.py</a>", line 113, in getresponse
    r = verb(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L543">ext/requests/sessions.py</a>", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L530">ext/requests/sessions.py</a>", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L643">ext/requests/sessions.py</a>", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L529">ext/requests/adapters.py</a>", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pokyto** [comment]
### INFO
**Python Version**: `3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/53d33b73426b15333f1f0c2b12f017dc
### ERROR
<pre>
2020-04-23 15:21:55 ERROR    CHECKVERSION :: [918cfe7] Environment error: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L384">ext/urllib3/connectionpool.py</a>", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L380">ext/urllib3/connectionpool.py</a>", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L439">ext/requests/adapters.py</a>", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/util/retry.py#L367">ext/urllib3/util/retry.py</a>", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/packages/six.py#L686">ext/urllib3/packages/six.py</a>", line 686, in reraise
    raise value
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L386">ext/urllib3/connectionpool.py</a>", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L306">ext/urllib3/connectionpool.py</a>", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/scheduler.py#L78">medusa/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L45">medusa/updater/version_checker.py</a>", line 45, in run
    if self.check_for_new_version(force):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L253">medusa/updater/version_checker.py</a>", line 253, in check_for_new_version
    if not self.updater.need_update():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/docker_updater.py#L28">medusa/updater/docker_updater.py</a>", line 28, in need_update
    if self.branch == 'master' and not self.is_latest_version():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/update_manager.py#L42">medusa/updater/update_manager.py</a>", line 42, in is_latest_version
    if LooseVersion(self.newest_version) > LooseVersion(self.current_version):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/source_updater.py#L67">medusa/updater/source_updater.py</a>", line 67, in newest_version
    latest_release = get_latest_release(self.github_org, self.github_repo)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/github_client.py#L119">medusa/github_client.py</a>", line 119, in get_latest_release
    return gh.get_organization(organization).get_repo(repo).get_latest_release()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/MainClass.py#L293">ext/github/MainClass.py</a>", line 293, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L321">ext/github/Requester.py</a>", line 321, in requestJsonAndCheck
    *self.requestJson(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L413">ext/github/Requester.py</a>", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L474">ext/github/Requester.py</a>", line 474, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L501">ext/github/Requester.py</a>", line 501, in __requestRaw
    response = cnx.getresponse()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L113">ext/github/Requester.py</a>", line 113, in getresponse
    r = verb(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L543">ext/requests/sessions.py</a>", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L530">ext/requests/sessions.py</a>", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L643">ext/requests/sessions.py</a>", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L529">ext/requests/adapters.py</a>", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/8145

**Comment by pokyto** [comment]
### INFO
**Python Version**: `3.8.3 (default, May 15 2020, 01:53:50) [GCC 9.3.0]`
**Operating System**: `Linux-4.9.0-8-amd64-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@918cfe7ce01808499585ffe6c1356fd5ed369f76
**Link to Log**: https://gist.github.com/ef20bbc3bacce87105ec33d5f606ec05
### ERROR
<pre>
2020-06-29 11:10:18 ERROR    CHECKVERSION :: [918cfe7] Environment error: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L384">ext/urllib3/connectionpool.py</a>", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L380">ext/urllib3/connectionpool.py</a>", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L439">ext/requests/adapters.py</a>", line 439, in send
    resp = conn.urlopen(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L637">ext/urllib3/connectionpool.py</a>", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/util/retry.py#L367">ext/urllib3/util/retry.py</a>", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/packages/six.py#L686">ext/urllib3/packages/six.py</a>", line 686, in reraise
    raise value
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L597">ext/urllib3/connectionpool.py</a>", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L386">ext/urllib3/connectionpool.py</a>", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/urllib3/connectionpool.py#L306">ext/urllib3/connectionpool.py</a>", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/scheduler.py#L78">medusa/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L45">medusa/updater/version_checker.py</a>", line 45, in run
    if self.check_for_new_version(force):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/version_checker.py#L253">medusa/updater/version_checker.py</a>", line 253, in check_for_new_version
    if not self.updater.need_update():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/docker_updater.py#L28">medusa/updater/docker_updater.py</a>", line 28, in need_update
    if self.branch == 'master' and not self.is_latest_version():
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/update_manager.py#L42">medusa/updater/update_manager.py</a>", line 42, in is_latest_version
    if LooseVersion(self.newest_version) > LooseVersion(self.current_version):
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/updater/source_updater.py#L67">medusa/updater/source_updater.py</a>", line 67, in newest_version
    latest_release = get_latest_release(self.github_org, self.github_repo)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/medusa/github_client.py#L119">medusa/github_client.py</a>", line 119, in get_latest_release
    return gh.get_organization(organization).get_repo(repo).get_latest_release()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/MainClass.py#L293">ext/github/MainClass.py</a>", line 293, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L321">ext/github/Requester.py</a>", line 321, in requestJsonAndCheck
    *self.requestJson(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L413">ext/github/Requester.py</a>", line 413, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L474">ext/github/Requester.py</a>", line 474, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L501">ext/github/Requester.py</a>", line 501, in __requestRaw
    response = cnx.getresponse()
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/github/Requester.py#L113">ext/github/Requester.py</a>", line 113, in getresponse
    r = verb(
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L543">ext/requests/sessions.py</a>", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L530">ext/requests/sessions.py</a>", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/sessions.py#L643">ext/requests/sessions.py</a>", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/app/medusa/<a href="../blob/918cfe7ce01808499585ffe6c1356fd5ed369f76/ext/requests/adapters.py#L529">ext/requests/adapters.py</a>", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=15)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
