### ISSUE TITLE
Db error from the 0.3.15

### ISSUE THREAD

**Issue by thib3113** [pymedusa/Medusa#8028]
**Describe the bug**
Lot of Times I get errors talking about a missing table : 
```
MAIN :: [94fae84] Query: '
        SELECT indexer, series_id, title, season, custom
        FROM scene_exceptions
    '. Arguments: '[]'
2020-04-26 23:47:44 ERROR    MAIN :: [94fae84] DB error: OperationalError('no such table: scene_exceptions')
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 113, in _execute
   sql_results = cursor.execute(query)
sqlite3.OperationalError: no such table: scene_exceptions
2020-04-26 23:47:44 ERROR    MAIN :: [94fae84] DB error: no such table: scene_exceptions
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: no such table: scene_exceptions
```

**To Reproduce**
Upgrade from 0.3.14 to 0.3.15 ?

**Expected behavior**
No crash ?

**Medusa (please complete the following information):**
 - OS: docker image
Branch: master
Commit: 94fae847b6e7e443d74c59cb11bdbd37c464b363
Version: 0.3.15
Database: 44.15
Python Version: | 3.8.2 (default, Feb 29 2020, 17:03:31) [GCC 9.2.0]
SSL Version: | OpenSSL 1.1.1d 10 Sep 2019
OS: | Linux-4.15.0-96-generic-x86_64-with
Locale: | en_US.UTF-8

**Debug logs (at least 50 lines):**

```
2020-04-26 23:47:44 ERROR    MAIN :: [94fae84] DB error: OperationalError('no such table: scene_exceptions')
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: no such table: scene_exceptions
2020-04-26 23:47:44 ERROR    MAIN :: [94fae84] DB error: no such table: scene_exceptions
Traceback (most recent call last):
  File "/app/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/app/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: no such table: scene_exceptions
```
</details>

**Additional context**
Any way to update the database manually ?

**Comment by p0psicles** [comment]
Search the closed issues. Solution provided many times

**Comment by thib3113** [comment]
doesn't found it the first time I search . 

So I use this [comment ](https://github.com/pymedusa/Medusa/issues/7983#issuecomment-615194766) , to update manually the minor db version in the db (python not available for me)

**Comment by p0psicles** [comment]
Yes
