### ISSUE TITLE
[APP SUBMITTED]: json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

### ISSUE THREAD

**Issue by elstevega** [pymedusa/Medusa#8079]
### INFO
**Python Version**: `3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]`
**Operating System**: `Linux-5.3.18-3-pve-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/b6c29f77d7b3892c18b073bc564d443e
### ERROR
<pre>
2020-05-08 18:20:48 ERROR    SHOWQUEUE-ADD :: [d9c31da] 70566: Error while loading information from indexer TVDBv2. Error: JSONDecodeError('Expecting value: line 2 column 1 (char 1)',)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/show_queue.py#L431">medusa/show_queue.py</a>", line 431, in run
    check_existing_shows(s, self.indexer)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/helpers/externals.py#L136">medusa/helpers/externals.py</a>", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/helpers/externals.py#L110">medusa/helpers/externals.py</a>", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/tvmaze/tvmaze_api.py#L493">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 493, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L653">lib/pytvmaze/tvmaze.py</a>", line 653, in get_show
    return self.show_main_info(self.lookup_imdb(imdb_id).id, embed=embed)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L1029">lib/pytvmaze/tvmaze.py</a>", line 1029, in lookup_imdb
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L548">lib/pytvmaze/tvmaze.py</a>", line 548, in _endpoint_standard_get
    results = r.json()
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/ext/requests/models.py#L898">ext/requests/models.py</a>", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by elstevega** [comment]
### INFO
**Python Version**: `3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]`
**Operating System**: `Linux-5.4.41-1-pve-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/57c421ef57a2371b2cbe172ae9cabb51
### ERROR
<pre>
2020-06-01 16:09:38 ERROR    SHOWQUEUE-ADD :: [d9c31da] 93784: Error while loading information from indexer TMDB. Error: JSONDecodeError('Expecting value: line 2 column 1 (char 1)',)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/show_queue.py#L431">medusa/show_queue.py</a>", line 431, in run
    check_existing_shows(s, self.indexer)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/helpers/externals.py#L136">medusa/helpers/externals.py</a>", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/helpers/externals.py#L110">medusa/helpers/externals.py</a>", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/tvmaze/tvmaze_api.py#L493">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 493, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L643">lib/pytvmaze/tvmaze.py</a>", line 643, in get_show
    return self.show_main_info(self.lookup_tvdb(tvdb_id).id, embed=embed)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L1021">lib/pytvmaze/tvmaze.py</a>", line 1021, in lookup_tvdb
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L548">lib/pytvmaze/tvmaze.py</a>", line 548, in _endpoint_standard_get
    results = r.json()
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/ext/requests/models.py#L898">ext/requests/models.py</a>", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by elstevega** [comment]
### INFO
**Python Version**: `3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]`
**Operating System**: `Linux-5.4.41-1-pve-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.15`
**Commit**: pymedusa/Medusa@d9c31da063e6c4b4383749e19b27b13693a1b71e
**Link to Log**: https://gist.github.com/592fad14b398c49acd18b8621c986107
### ERROR
<pre>
2020-06-01 16:09:12 ERROR    APIv2-Thread_41 :: [d9c31da] Internal Error searching for show. term(s): ['Tales from the Loop'] indexer: tvmaze error: Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/server/api/v2/internal.py#L202">medusa/server/api/v2/internal.py</a>", line 202, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/indexer_base.py#L404">medusa/indexers/indexer_base.py</a>", line 404, in __getitem__
    selected_series = self._get_series(key)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/indexer_base.py#L158">medusa/indexers/indexer_base.py</a>", line 158, in _get_series
    all_series = self.search(series)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/tvmaze/tvmaze_api.py#L186">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 186, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/medusa/indexers/tvmaze/tvmaze_api.py#L167">medusa/indexers/tvmaze/tvmaze_api.py</a>", line 167, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L968">lib/pytvmaze/tvmaze.py</a>", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L985">lib/pytvmaze/tvmaze.py</a>", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/lib/pytvmaze/tvmaze.py#L548">lib/pytvmaze/tvmaze.py</a>", line 548, in _endpoint_standard_get
    results = r.json()
  File "/opt/medusa/<a href="../blob/d9c31da063e6c4b4383749e19b27b13693a1b71e/ext/requests/models.py#L898">ext/requests/models.py</a>", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fallenturtle** [comment]
I'm having this same issue, but I'm on Windows 10.

Medusa Info: | Branch: masterCommit: 471c8ed43f6125ebdcd471c260757d8c7cae2ad4Version: 0.4.0Database: 44.16
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | en_US.cp1252

`2020-08-17 16:39:33 ERROR    SHOWQUEUE-ADD :: [471c8ed] 364106: Error while loading information from indexer TVDBv2. Error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\show_queue.py", line 432, in run
    check_existing_shows(s, self.indexer)
  File "C:\Medusa\Medusa\medusa\helpers\externals.py", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "C:\Medusa\Medusa\medusa\helpers\externals.py", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "C:\Medusa\Medusa\medusa\indexers\tvmaze\api.py", line 508, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 653, in get_show
    return self.show_main_info(self.lookup_imdb(imdb_id).id, embed=embed)
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 1029, in lookup_imdb
    q = self._endpoint_standard_get(url)
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 548, in _endpoint_standard_get
    results = r.json()
  File "C:\Medusa\Medusa\ext\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by p0psicles** [comment]
Issue with a specific show. Or every show you try?

**Comment by elstevega** [comment]
For me it was 'Tales From the Loop' back in June. Haven't seen the issue pop up since then. I just added 3 new shows & they all showed up no problem. Thought it might be an indexer error, but it's happened on tvmaze & TVDBv2...

**Comment by p0psicles** [comment]
So you can correctly add that show now? Looking to get something reproduceable

**Comment by elstevega** [comment]
Yea, I just removed it (Tales From the Loop) & re-added & it worked fine. I've got debug logging turned on & will try adding some more shows over the next few days to see if I can reproduce...

**Comment by p0psicles** [comment]
It's probably a misconfigure on tvdb that got corrected. I'm closing this as it's not reproduceable

**Comment by fallenturtle** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@471c8ed43f6125ebdcd471c260757d8c7cae2ad4
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-08-17 17:31:46 ERROR    SHOWQUEUE-ADD :: [471c8ed] 328487: Error while loading information from indexer TVDBv2. Error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/show_queue.py#L432">medusa\show_queue.py</a>", line 432, in run
    check_existing_shows(s, self.indexer)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/helpers/externals.py#L136">medusa\helpers\externals.py</a>", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/helpers/externals.py#L110">medusa\helpers\externals.py</a>", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/indexers/tvmaze/api.py#L508">medusa\indexers\tvmaze\api.py</a>", line 508, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L653">lib\pytvmaze\tvmaze.py</a>", line 653, in get_show
    return self.show_main_info(self.lookup_imdb(imdb_id).id, embed=embed)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L1029">lib\pytvmaze\tvmaze.py</a>", line 1029, in lookup_imdb
    q = self._endpoint_standard_get(url)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L548">lib\pytvmaze\tvmaze.py</a>", line 548, in _endpoint_standard_get
    results = r.json()
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/ext/requests/models.py#L898">ext\requests\models.py</a>", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fallenturtle** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@471c8ed43f6125ebdcd471c260757d8c7cae2ad4
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-08-17 17:29:33 ERROR    SHOWQUEUE-ADD :: [471c8ed] 260449: Error while loading information from indexer TVDBv2. Error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/show_queue.py#L432">medusa\show_queue.py</a>", line 432, in run
    check_existing_shows(s, self.indexer)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/helpers/externals.py#L136">medusa\helpers\externals.py</a>", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/helpers/externals.py#L110">medusa\helpers\externals.py</a>", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/indexers/tvmaze/api.py#L508">medusa\indexers\tvmaze\api.py</a>", line 508, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L653">lib\pytvmaze\tvmaze.py</a>", line 653, in get_show
    return self.show_main_info(self.lookup_imdb(imdb_id).id, embed=embed)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L1029">lib\pytvmaze\tvmaze.py</a>", line 1029, in lookup_imdb
    q = self._endpoint_standard_get(url)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L548">lib\pytvmaze\tvmaze.py</a>", line 548, in _endpoint_standard_get
    results = r.json()
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/ext/requests/models.py#L898">ext\requests\models.py</a>", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fallenturtle** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@471c8ed43f6125ebdcd471c260757d8c7cae2ad4
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-08-17 17:27:21 ERROR    SHOWQUEUE-ADD :: [471c8ed] 332331: Error while loading information from indexer TVDBv2. Error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/show_queue.py#L432">medusa\show_queue.py</a>", line 432, in run
    check_existing_shows(s, self.indexer)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/helpers/externals.py#L136">medusa\helpers\externals.py</a>", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/helpers/externals.py#L110">medusa\helpers\externals.py</a>", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/indexers/tvmaze/api.py#L508">medusa\indexers\tvmaze\api.py</a>", line 508, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L653">lib\pytvmaze\tvmaze.py</a>", line 653, in get_show
    return self.show_main_info(self.lookup_imdb(imdb_id).id, embed=embed)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L1029">lib\pytvmaze\tvmaze.py</a>", line 1029, in lookup_imdb
    q = self._endpoint_standard_get(url)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L548">lib\pytvmaze\tvmaze.py</a>", line 548, in _endpoint_standard_get
    results = r.json()
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/ext/requests/models.py#L898">ext\requests\models.py</a>", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fallenturtle** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@471c8ed43f6125ebdcd471c260757d8c7cae2ad4
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-08-17 17:24:39 ERROR    SHOWQUEUE-ADD :: [471c8ed] 268592: Error while loading information from indexer TVDBv2. Error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/show_queue.py#L432">medusa\show_queue.py</a>", line 432, in run
    check_existing_shows(s, self.indexer)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/helpers/externals.py#L136">medusa\helpers\externals.py</a>", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/helpers/externals.py#L110">medusa\helpers\externals.py</a>", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/medusa/indexers/tvmaze/api.py#L508">medusa\indexers\tvmaze\api.py</a>", line 508, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L653">lib\pytvmaze\tvmaze.py</a>", line 653, in get_show
    return self.show_main_info(self.lookup_imdb(imdb_id).id, embed=embed)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L1029">lib\pytvmaze\tvmaze.py</a>", line 1029, in lookup_imdb
    q = self._endpoint_standard_get(url)
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/lib/pytvmaze/tvmaze.py#L548">lib\pytvmaze\tvmaze.py</a>", line 548, in _endpoint_standard_get
    results = r.json()
  File "C:\Medusa\Medusa\<a href="../blob/471c8ed43f6125ebdcd471c260757d8c7cae2ad4/ext/requests/models.py#L898">ext\requests\models.py</a>", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
