### ISSUE TITLE
Unused keyword argument 'conflict_solver'

### ISSUE THREAD

**Issue by dkasak** [pymedusa/Medusa#8083]
**Describe the bug**
pymedusa crashes with the following message shortly after starting:

```
Traceback (most recent call last):
  File "/usr/lib/pymedusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/usr/lib/pymedusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/usr/lib/pymedusa/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/usr/lib/pymedusa/medusa/init/__init__.py", line 184, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "/usr/lib/pymedusa/medusa/name_parser/guessit_parser.py", line 13, in <module>
    from medusa.name_parser.rules import default_api
  File "/usr/lib/pymedusa/medusa/name_parser/rules/__init__.py", line 19, in <module>
    default_api.configure({})
  File "/usr/lib/pymedusa/ext/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/pymedusa/ext/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/pymedusa/ext/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/pymedusa/ext/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/pymedusa/ext/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/pymedusa/ext/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/pymedusa/ext/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'conflict_solver'
```

**To Reproduce**
Just starting pymedusa 0.3.16 on my platform is enough to produce the crash.

**Expected behavior**
No crash.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Arch Linux
 - pymedusa version: 0.3.16
 - Commit: d9c31da
 - Python version: 3.8.2
 - Database version: Don't know

**Debug logs (at least 50 lines):**
Sadly, pymedusa does not run long enough to enable this.

**Comment by p0psicles** [comment]
You also didn't post the complete error

**Comment by dkasak** [comment]
Yes, sorry, that was a mistake. I've updated the original message with the complete error.

I've also noticed that the error is not exactly the same each time I try starting it. Here are two more errors I got:

```
Traceback (most recent call last):
  File "/usr/lib/pymedusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/usr/lib/pymedusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/usr/lib/pymedusa/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/usr/lib/pymedusa/medusa/init/__init__.py", line 184, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "/usr/lib/pymedusa/medusa/name_parser/guessit_parser.py", line 13, in <module>
    from medusa.name_parser.rules import default_api
  File "/usr/lib/pymedusa/medusa/name_parser/rules/__init__.py", line 19, in <module>
    default_api.configure({})
  File "/usr/lib/pymedusa/ext/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/pymedusa/ext/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/pymedusa/ext/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/pymedusa/ext/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/pymedusa/ext/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/pymedusa/ext/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/pymedusa/ext/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'private_parent'
```

```
Traceback (most recent call last):
  File "/usr/lib/pymedusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/usr/lib/pymedusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/usr/lib/pymedusa/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/usr/lib/pymedusa/medusa/init/__init__.py", line 184, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "/usr/lib/pymedusa/medusa/name_parser/guessit_parser.py", line 13, in <module>
    from medusa.name_parser.rules import default_api
  File "/usr/lib/pymedusa/medusa/name_parser/rules/__init__.py", line 19, in <module>
    default_api.configure({})
  File "/usr/lib/pymedusa/ext/guessit/api.py", line 163, in configure
    self.rebulk = rules_builder(advanced_config)
  File "/usr/lib/pymedusa/ext/guessit/rules/__init__.py", line 56, in rebulk_builder
    rebulk.rebulk(episodes(_config('episodes')))
  File "/usr/lib/pymedusa/ext/guessit/rules/properties/episodes.py", line 168, in episodes
    rebulk.chain(
  File "/usr/lib/pymedusa/ext/rebulk/builder.py", line 179, in regex
    return self.pattern(self.build_re(*pattern, **kwargs))
  File "/usr/lib/pymedusa/ext/rebulk/builder.py", line 107, in build_re
    return RePattern(*pattern, **kwargs)
  File "/usr/lib/pymedusa/ext/rebulk/pattern.py", line 441, in __init__
    pattern = call(re.compile, pattern, **self._kwargs)
  File "/usr/lib/pymedusa/ext/rebulk/loose.py", line 60, in call
    return function(*call_args, **call_kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 348, in compile
    return _compile(pattern, flags, ignore_unused, kwargs)
  File "/usr/lib/python3.8/site-packages/regex/regex.py", line 585, in _compile
    raise ValueError('unused keyword argument {!a}'.format(any_one))
ValueError: unused keyword argument 'tags'
```

**Comment by medariox** [comment]
This is a bug with rebulk and Python 3.8 - already fixed in develop.
