### ISSUE TITLE
WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing

### ISSUE THREAD

**Issue by akhlan** [pymedusa/Medusa#8118]
**Describe the bug**
When i put new TV Shows, Dragon Ball and Fairy Tail in my case, the naming isn't good... In season 8, Medusa want rename in season 3 tag for exemple... and in season 3, episode are missing (but there are present on my Nas)

**To Reproduce**

**Expected behavior**

**Screenshots**
https://zupimages.net/up/20/21/vrxv.png
https://zupimages.net/up/20/21/716e.png

**Medusa (please complete the following information):**
 - OS: Synology
 - Branch: master
 - Commit: d9c31da063e6c4b4383749e19b27b13693a1b71e
 - Version: 0.3.16
 - Database: 44.15

**Debug logs (at least 50 lines):**
`2020-05-22 14:31:14 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x25_La fleur qui s'épanouit sous la pluie.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 86: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:11 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x28_La loi des fées.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 83: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:11 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x45_L’avènement de Satan.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 72: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:11 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x20_Natsu et l'œuf du dragon.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0153' in position 82: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:09 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x35_L'appel des ténèbres.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 84: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:09 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x30_Prochaine génération.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 82: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:08 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x37_L'armure du cœur.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0153' in position 84: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:06 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x31_L'étoile tombée des cieux.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 73: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:06 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x40_La chute de la reine des fées.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 97: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:06 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x39_Une prière pour la lumière sainte.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 78: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:31:03 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x06_Fairy Tail au cœur de la tempête.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0153' in position 86: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:30:55 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x11_L'île maudite.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 73: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:30:51 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x46_Catastrophe à la cathédrale de Kaldia.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 83: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:30:47 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x08_La meilleure des équipes.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 88: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:30:45 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x38_Destinée.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 77: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2020-05-22 14:30:42 WARNING  SHOWQUEUE-ADD :: [d9c31da] An error occurred while parsing: /volume1/Videos/TV Series Animes/Fairy Tail/Saison 01/Fairy Tail_01x15_La magie éternelle.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|      /usr/local/mediainfo/lib/libmediainfo.so.0       |
|                        v0.7.93                        |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 80: ordinal not in range(128)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+`

```
<-- Please replace this whole line with your debug logs -->
```
</details>

**Additional context**

**Comment by medariox** [comment]
The issue has already been reported multiple times upstream: https://github.com/ratoaq2/knowit/issues/21

The solution is to use Python 3.6+
