### ISSUE TITLE
Unable to add show

### ISSUE THREAD

**Issue by maciekb** [pymedusa/Medusa#8248]
**Describe the bug**
Unable to add specific show. No error raised in Medusa, so i can't raise error from app.

**To Reproduce**
1. Go to 'Add new show'
2. Search  'Drinks, Crime and Prohibition'
3. Only one match found, so try to add

**Expected behavior**
Founded show should be added to database.

**Medusa (please complete the following information):**
 - OS: Ubuntu 20.04 x64
 - Branch: master
 - Commit: Unknown
 - Python version: 3.8.3 (default, May 15 2020, 01:53:50) [GCC 9.3.0]
 - Database version: 44.15

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-07-20 21:46:19 INFO     SHOWQUEUE-ADD :: [] Starting to add show by show_dir: /media/TV Shows/Drinks, Crime and Prohibition
2020-07-20 21:46:19 INFO     SHOWQUEUE-ADD :: [] TVDBv2: {'language': 'en', 'use_zip': True, 'session': <medusa.session.core.MedusaSession object at 0x7f54c9535d00>, 'cache': '/config/cache/indexers/TVDBv2'}
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Configured language en override show language of en
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Getting all series data for 348831
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Getting all show data for 348831
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] GET URL: https://api.thetvdb.com/series/348831 [Status: 200]
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] User-Agent: Medusa/0.3.16 (Linux; 5.4.0-40-generic; 81363bea-cac1-11ea-afe1-0242ac140002)
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Getting all episodes of 348831
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] GET URL: https://api.thetvdb.com/series/348831/episodes/query?page=1 [Status: 200]
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] User-Agent: Medusa/0.3.16 (Linux; 5.4.0-40-generic; 81363bea-cac1-11ea-afe1-0242ac140002)
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Trying other indexer: TVmaze get_id_by_external
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] GET URL: http://api.tvmaze.com/lookup/shows?imdb=https://www.imdb.com/titl [Status: 404]
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] User-Agent: Medusa/0.3.16 (Linux; 5.4.0-40-generic; 81363bea-cac1-11ea-afe1-0242ac140002)
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Could not get tvmaze externals using external key imdb_id and id https://www.imdb.com/titl
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Trying other indexer: TMDB get_id_by_external
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] 348831: Loading show info from database
2020-07-20 21:46:19 INFO     SHOWQUEUE-ADD :: [] 348831: Unable to find the show in the database
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] 348831: Loading show info from TVDBv2
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Trying other indexer: TVmaze get_id_by_external
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] GET URL: http://api.tvmaze.com/lookup/shows?thetvdb=348831 [Status: 404]
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] User-Agent: Medusa/0.3.16 (Linux; 5.4.0-40-generic; 81363bea-cac1-11ea-afe1-0242ac140002)
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Could not get tvmaze externals using external key tvdb_id and id 348831
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] GET URL: http://api.tvmaze.com/lookup/shows?imdb=https://www.imdb.com/titl [Status: 404]
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] User-Agent: Medusa/0.3.16 (Linux; 5.4.0-40-generic; 81363bea-cac1-11ea-afe1-0242ac140002)
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Could not get tvmaze externals using external key imdb_id and id https://www.imdb.com/titl
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Trying other indexer: TMDB get_id_by_external
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Transaction with 2 queries executed
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] TVDBv2 348831: Setting location: /media/TV Shows/Drinks, Crime and Prohibition
2020-07-20 21:46:19 INFO     SHOWQUEUE-ADD :: [] Setting all previously aired episodes to the specified status: Skipped
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] Retrieving show info from IMDb
2020-07-20 21:46:19 DEBUG    SHOWQUEUE-ADD :: [] 348831: Loading show info from IMDb with ID: https://www.imdb.com/titl
Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "/app/medusa/ext/imdbpie/imdbpie.py", line 279, in validate_imdb_id
    re.match(match_id, imdb_id, re.IGNORECASE).group()
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/app/medusa/medusa/show_queue.py", line 566, in run
    self.show.load_imdb_info()
  File "/app/medusa/medusa/tv/series.py", line 1584, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "/app/medusa/ext/imdbpie/imdbpie.py", line 77, in get_title
    self.validate_imdb_id(imdb_id)
  File "/app/medusa/ext/imdbpie/imdbpie.py", line 281, in validate_imdb_id
    raise ValueError('invalid imdb id')
ValueError: invalid imdb id
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Show has an invalid IMDb id set on tvdb. You can change that yourself

**Comment by medariox** [comment]
Please get it fixed on TheTVDB, it will help everyone.

**Comment by maciekb** [comment]
I have corrected invalid entry on https://thetvdb.com/series/drinks-crime-and-prohibition, but after many hours same error appears. Is there a cache that could cause a problem? I have never edited TheTVDB database and I don't know if the change should be visible to clients right away.

**Comment by medariox** [comment]
Takes up to 48h IIRC.
