### ISSUE TITLE
Show List not showing future episodes, not downloading

### ISSUE THREAD

**Issue by rr0ss0rr** [pymedusa/Medusa#8256]
Running Medusa 3.16 on macOS 10.15.  Episode list for some shows are only showing the 1st 4 episodes and no longer downloading new episodes.  This has been going on for a few months now.  Today, I deleted one of the shows and re-added it and received the following:

```2020-07-21 20:44:06 INFO	SHOWQUEUE-ADD :: [d9c31da] Setting all previously aired episodes to the specified status: Wanted
2020-07-21 20:44:03 INFO	SHOWQUEUE-ADD :: [d9c31da] 364928: Unable to find the show in the database
2020-07-21 20:44:00 INFO	SHOWQUEUE-ADD :: [d9c31da] TVDBv2: {u'session': <**********.session.core.MedusaSession object at 0x1108da790>, u'cache': u'/Applications/Medusa/cache/indexers/TVDBv2', u'language': u'en', u'use_zip': True}
2020-07-21 20:44:00 INFO	SHOWQUEUE-ADD :: [d9c31da] Starting to add show by show_dir: /Users/richard/mnt/Drobo-Public/SickBeard/Snowpiercer
```

I don't see any error when adding outside from the log, but the show is not added to the database

**Comment by rr0ss0rr** [comment]
additional info from the log:

```Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Applications/Medusa/medusa/show_queue.py", line 566, in run
    self.show.load_imdb_info()
  File "/Applications/Medusa/medusa/tv/series.py", line 1584, in load_imdb_info
    imdb_info = imdb_api.get_title(self.imdb_id)
  File "/Applications/Medusa/ext/imdbpie/imdbpie.py", line 81, in get_title
    '/title/{0}/auxiliary'.format(imdb_id)
  File "/Applications/Medusa/ext/imdbpie/imdbpie.py", line 299, in _get_resource
    return self._get(url=url)['resource']
  File "/Applications/Medusa/ext/imdbpie/imdbpie.py", line 307, in _get
    headers.update(self.get_auth_headers(full_url))
  File "/Applications/Medusa/ext/imdbpie/auth.py", line 112, in get_auth_headers
    creds, soon_expires = self._creds_soon_expiring()
  File "/Applications/Medusa/ext/imdbpie/auth.py", line 97, in _creds_soon_expiring
    creds = self._get_creds()
  File "/Applications/Medusa/ext/imdbpie/auth.py", line 85, in _get_creds
    return cache.get(self._CREDS_STORAGE_KEY)
  File "/Applications/Medusa/ext/diskcache/core.py", line 907, in get
    value = self._disk.fetch(mode, filename, db_value, read)
  File "/Applications/Medusa/ext/diskcache/core.py", line 279, in fetch
    return pickle.load(BytesIO(value))
ValueError: unsupported pickle protocol: 4
```

**Comment by rr0ss0rr** [comment]
And ... looking at the application exception, I noticed that I was running python 2.7 .. I added python 3.8 to my path so it finds that first.  I think this happened when I switched my shell from bash to zsh.
