### ISSUE TITLE
medusa wont run after restart, actually no python apps will only nabnzbd

### ISSUE THREAD

**Issue by akaguyver** [pymedusa/Medusa#8272]
(when trying to start manually i get this error)
c:\Medusa\Medusa> start.py
Unable to find C:\Medusa\Medusa\config.ini, all settings will be default!
2020-07-27 12:12:50 INFO     MAIN :: [] Broken providers found: ['']
2020-07-27 12:12:50 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 12:12:50 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 12:12:50 WARNING  MAIN :: [] No git specified, can't use git commands
2020-07-27 12:12:50 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 12:12:50 WARNING  MAIN :: [] No git specified, can't use git commands
2020-07-27 12:12:50 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 12:12:50 WARNING  MAIN :: [] No git specified, can't use git commands
Traceback (most recent call last):
  File "C:\Medusa\Medusa\start.py", line 9, in <module>
    main()
  File "C:\Medusa\Medusa\medusa\__main__.py", line 2199, in main
    application.start(sys.argv[1:])
  File "C:\Medusa\Medusa\medusa\__main__.py", line 328, in start
    self.initialize(console_logging=self.console_logging)
  File "C:\Medusa\Medusa\medusa\__main__.py", line 1017, in initialize
    app.APP_VERSION = updater.current_version
  File "C:\Medusa\Medusa\medusa\updater\github_updater.py", line 53, in current_version
    return cur_version.lstrip('v')
AttributeError: 'NoneType' object has no attribute 'lstrip'**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]
 - Python version: [e.g. 3.6.8]
 - Database version: [e.g. 44.12]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
<-- Please replace this whole line with your debug logs -->
```
</details>

also the nssm serrvice is stopped and wont run
<img width="849" alt="nssm" src="https://user-images.githubusercontent.com/11916214/88566022-69661b00-d003-11ea-8c65-95c5e906d18d.PNG">
<img width="744" alt="services" src="https://user-images.githubusercontent.com/11916214/88566033-6e2acf00-d003-11ea-8700-c1dacdc5c409.PNG">
im running windows server 2019 datacenterdidtion. medusa failed on me beforore eand ii reinstalled and it stopoped again. im also using nzbhydra and the service is runnning but not viewable at http://localhost:5076/config/main
neither it emby dashboard at http://localhost:8096/web/index.html?#!/dashboard

something is stopping these things from running after i restart. my firewall is disabled so i dont think its that. any help greatly appreciated
**Additional context**

**Comment by p0psicles** [comment]
You should start manually by running > python start.py

**Comment by akaguyver** [comment]
c:\Medusa\Medusa> start.py
Unable to find C:\Medusa\Medusa\config.ini, all settings will be default!
2020-07-27 12:12:50 INFO     MAIN :: [] Broken providers found: ['']
2020-07-27 12:12:50 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 12:12:50 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 12:12:50 WARNING  MAIN :: [] No git specified, can't use git commands
2020-07-27 12:12:50 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 12:12:50 WARNING  MAIN :: [] No git specified, can't use git commands
2020-07-27 12:12:50 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 12:12:50 WARNING  MAIN :: [] No git specified, can't use git commands
Traceback (most recent call last):
  File "C:\Medusa\Medusa\start.py", line 9, in <module>
    main()
  File "C:\Medusa\Medusa\medusa\__main__.py", line 2199, in main
    application.start(sys.argv[1:])
  File "C:\Medusa\Medusa\medusa\__main__.py", line 328, in start
    self.initialize(console_logging=self.console_logging)
  File "C:\Medusa\Medusa\medusa\__main__.py", line 1017, in initialize
    app.APP_VERSION = updater.current_version
  File "C:\Medusa\Medusa\medusa\updater\github_updater.py", line 53, in current_version
    return cur_version.lstrip('v')
AttributeError: 'NoneType' object has no attribute 'lstrip'

c:\Medusa\Medusa>python start.py
Unable to find c:\Medusa\Medusa\config.ini, all settings will be default!
2020-07-27 17:00:24 INFO     MAIN :: [] Broken providers found: ['']
2020-07-27 17:00:24 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 17:00:24 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 17:00:24 WARNING  MAIN :: [] No git specified, can't use git commands
2020-07-27 17:00:24 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 17:00:24 WARNING  MAIN :: [] No git specified, can't use git commands
2020-07-27 17:00:24 WARNING  MAIN :: [] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-07-27 17:00:24 WARNING  MAIN :: [] No git specified, can't use git commands
Traceback (most recent call last):
  File "start.py", line 9, in <module>
    main()
  File "c:\Medusa\Medusa\medusa\__main__.py", line 2199, in main
    application.start(sys.argv[1:])
  File "c:\Medusa\Medusa\medusa\__main__.py", line 328, in start
    self.initialize(console_logging=self.console_logging)
  File "c:\Medusa\Medusa\medusa\__main__.py", line 1017, in initialize
    app.APP_VERSION = updater.current_version
  File "c:\Medusa\Medusa\medusa\updater\github_updater.py", line 53, in current_version
    return cur_version.lstrip('v')
AttributeError: 'NoneType' object has no attribute 'lstrip'

c:\Medusa\Medusa>

**Comment by medariox** [comment]
You are getting that error because your are missing `git`. You should install Medusa with our installer https://github.com/pymedusa/MedusaInstaller/releases, or install git system wide, or point your git install manually in config.ini (git_path).

**Comment by akaguyver** [comment]
i did install with that installer, when trying to run it again it says
![medusa installed](https://user-images.githubusercontent.com/11916214/88978482-cd9c0f80-d28d-11ea-8947-ab50fbf7df04.PNG)

**Comment by akaguyver** [comment]
> You should start manually by running > python start.py

 Directory of c:\Medusa\Medusa

07/27/2020  11:45 AM    <DIR>          .
07/27/2020  11:45 AM    <DIR>          ..
06/11/2020  07:56 PM    <DIR>          .build
06/11/2020  07:56 PM             4,576 .codecov.yml
06/11/2020  07:56 PM               314 .dockerignore
06/11/2020  07:56 PM               464 .editorconfig
06/11/2020  07:56 PM             1,432 .gitattributes
06/11/2020  07:56 PM    <DIR>          .github
06/11/2020  07:56 PM             1,152 .gitignore
06/11/2020  07:56 PM             3,089 .travis.yml
06/11/2020  07:56 PM                79 .yarnrc
07/27/2020  11:45 AM    <DIR>          cache
06/11/2020  07:56 PM            28,076 CHANGELOG.md
06/11/2020  07:56 PM             2,648 CONTRIBUTING.md
06/11/2020  07:56 PM            35,132 COPYING.txt
06/11/2020  07:56 PM               634 Dockerfile
06/11/2020  07:56 PM    <DIR>          dredd
06/11/2020  07:57 PM    <DIR>          ext
06/11/2020  07:57 PM    <DIR>          ext2
06/11/2020  07:57 PM    <DIR>          ext3
06/11/2020  07:57 PM    <DIR>          hooks
06/11/2020  07:57 PM    <DIR>          lib
07/27/2020  11:45 AM    <DIR>          Logs
06/11/2020  07:56 PM               302 MANIFEST.in
06/11/2020  07:57 PM    <DIR>          medusa
06/11/2020  07:57 PM               390 package.json
06/11/2020  07:57 PM             8,514 readme.md
06/11/2020  07:57 PM             1,100 renovate.json
06/11/2020  07:57 PM             1,489 requirements.txt
06/11/2020  07:57 PM    <DIR>          runscripts
06/11/2020  07:57 PM             9,706 setup.cfg
06/11/2020  07:57 PM             4,222 setup.py
06/11/2020  07:56 PM               200 SickBeard.py
06/11/2020  07:57 PM               180 start.py
06/11/2020  07:57 PM    <DIR>          tests
06/11/2020  07:57 PM    <DIR>          themes
06/11/2020  07:57 PM    <DIR>          themes-default
06/11/2020  07:57 PM               306 tox.ini
06/11/2020  07:57 PM            59,158 yarn.lock
              22 File(s)        163,163 bytes
              17 Dir(s)  240,654,082,048 bytes free

c:\Medusa\Medusa>python start.py
Unable to find c:\Medusa\Medusa\config.ini, all settings will be default!
2020-07-30 18:00:29 INFO     MAIN :: [] Broken providers found: ['']
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Add minor version numbers to database
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated major version to: 43.0
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 43.1
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Test major and minor version updates database
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated major version to: 44.0
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.1
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column proper_tags to history
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.2
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column manually_searched to history
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column manually_searched to tv_episodes
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.3
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column info_hash in history
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.4
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column plot in imdb_info
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column plot in tv_show
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.5
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column size in history
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.6
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding PK to mindexer column in indexer_mapping table
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.7
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Make indexer and indexer_id as INTEGER in tv_episodes table
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.8
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column indexer_id in history
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column indexer_id in blacklist
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column indexer_id in whitelist
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding column indexer in imdb_info
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Dropping the unique index on idx_indexer_id
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Dropping the primary key on the table xem_refresh
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Updating indexer field on table blacklist. Using the series id to match with field show_id
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Updating indexer field on table whitelist. Using the series id to match with field show_id
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Updating indexer field on table history. Using the series id to match with field showid
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Updating indexer field on table imdb_info. Using the series id to match with field indexer_id
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.9
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:30 INFO     MAIN :: [d9c31da] Adding new quality field in the tv_episodes table
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Dropping the index on idx_sta_epi_air
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Dropping the index on idx_sta_epi_sta_air
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Dropping the index on idx_status
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Splitting the composite status into status and quality
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Removing the quality from the action field, as this is a composite status
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.10
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Shift qualities in tv_shows one place to the left.
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Shift qualities in tv_episodes one place to the left.
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Shift qualities in history one place to the left.
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.11
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Adding new watched field in the tv_episodes table
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.12
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Adding new airdate_offset field in the tv_shows table
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.13
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Adding release ignore and require exclude option flags to the tv_shows table
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.14
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Creating a new table scene_exceptions in the main.db database.
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [MAIN-DB] Updated minor version to: 44.15
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [CACHE-DB] Updated major version to: 2.None
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [CACHE-DB] Updated major version to: 3.None
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [CACHE-DB] Updated major version to: 4.None
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Backing up database before upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Proceeding with upgrade
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Shift qualities in history one place to the left.
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Update status UNKONWN from tv_episodes
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] [FAILED-DB] Updated major version to: 3.None
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Missing idx_tv_episodes_showid_airdate for TV Episodes table detected, fixing...
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Missing idx_showid for TV Episodes table detected, fixing...
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Missing idx_status for TV Episodes table detected, fixing...
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Missing idx_sta_epi_air for TV Episodes table detected, fixing...
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] Missing idx_sta_epi_sta_air for TV Episodes table detected, fixing...
2020-07-30 18:00:31 INFO     MAIN :: [d9c31da] 12345: Unable to find the show in the database
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Starting Medusa [master] using 'c:\\Medusa\\Medusa\\config.ini'
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Generating New API key
2020-07-30 18:00:32 INFO     TORNADO :: [d9c31da] Starting Medusa on http://0.0.0.0:8081/
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tvdb.json
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tvmaze.json
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tmdb.json
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Checking for XEM scene exceptions updates for TVDBv2
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Checking for scene exceptions updates from AniDB
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Updated scene exceptions.
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Updating exception_cache and exception_season_cache
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Finished processing 3274 scene exceptions.
2020-07-30 18:00:32 INFO     MAIN :: [d9c31da] Building internal name cache for all shows
when running manually it starts but with no shows showing up.
I also installed Git but still not working

**Comment by p0psicles** [comment]
Then  you have to uninstall the old version first.
