### ISSUE TITLE
JSONDecodeError when trying to add shows

### ISSUE THREAD

**Issue by fallenturtle** [pymedusa/Medusa#8360]
Any show I try to add never gets added. I'm able to go through the steps to add it and it finds it during the stage where you identify the show, but it never shows up and I see the errors in the logs below.

I've tried adding new shows, adding existing shows, and tried different indexers.... all with the same result.

Medusa Info: 
Branch:  master                  
Commit:  471c8ed43f6125ebdcd471c260757d8c7cae2ad4                  
Version:  0.4.0                  
Database:   44.16
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j  20 Nov 2018
OS: | Windows-10-10.0.18362-SP0
Locale: | en_US.cp1252
```

2020-08-18 08:51:32 ERROR    SHOWQUEUE-ADD :: [471c8ed] 338947: Error while loading information from indexer TVDBv2. Error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\show_queue.py", line 432, in run
    check_existing_shows(s, self.indexer)
  File "C:\Medusa\Medusa\medusa\helpers\externals.py", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "C:\Medusa\Medusa\medusa\helpers\externals.py", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "C:\Medusa\Medusa\medusa\indexers\tvmaze\api.py", line 508, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 653, in get_show
    return self.show_main_info(self.lookup_imdb(imdb_id).id, embed=embed)
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 1029, in lookup_imdb
    q = self._endpoint_standard_get(url)
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 548, in _endpoint_standard_get
    results = r.json()
  File "C:\Medusa\Medusa\ext\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2020-08-18 08:51:29 ERROR    SHOWQUEUE-ADD :: [471c8ed] 348598: Error while loading information from indexer TVDBv2. Error: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\show_queue.py", line 432, in run
    check_existing_shows(s, self.indexer)
  File "C:\Medusa\Medusa\medusa\helpers\externals.py", line 136, in check_existing_shows
    new_show_externals = get_externals(indexer=indexer, indexed_show=indexed_show)
  File "C:\Medusa\Medusa\medusa\helpers\externals.py", line 110, in get_externals
    new_show_externals.update(t.get_id_by_external(**new_show_externals))
  File "C:\Medusa\Medusa\medusa\indexers\tvmaze\api.py", line 508, in get_id_by_external
    result = self.tvmaze_api.get_show(**{external_id: kwargs.get(external_id)})
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 653, in get_show
    return self.show_main_info(self.lookup_imdb(imdb_id).id, embed=embed)
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 1029, in lookup_imdb
    q = self._endpoint_standard_get(url)
  File "C:\Medusa\Medusa\lib\pytvmaze\tvmaze.py", line 548, in _endpoint_standard_get
    results = r.json()
  File "C:\Medusa\Medusa\ext\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by p0psicles** [comment]
I'll create a workaround for you first. So you can add them. Or at least I expect. Would you be willing to change a file?

**Comment by fallenturtle** [comment]
Yes, I willing to change a file. Thanks.

I did want to add that I was having a similar issue with Sickchill which is why I decided to switch over to Medusa. The difference though is that Sickchill created a placeholder on the show list marked "Loading". I tried searching the logs for similar errors to the above, but couldn't find them... but I suspect that its not logging right or something.

After that initial Sickchill failure I tried completely reinstalling Sickchill from scratch with a fresh DB and when I tried to import my shows they all did that Loading thing. I also I found in both cases when I restarted the service the loading stuff went away and it was like I never tried to add the show in the first place.

**Comment by p0psicles** [comment]
Your having issues communicating with tvmaze. First I'll try catching the tvmaze error. Well go from there

**Comment by p0psicles** [comment]
Download this file as `api.py`
https://gist.githubusercontent.com/p0psicles/c6e3a6035cbd3dd4adb3551f58c15e5f/raw/acbe261e89c635190e325302ff08b8ad2c47d256/tvmaze_api.py
Now in `root/medusa/indexers/tvmaze/` replace api.py with that.
Restart medusa.

**Comment by fallenturtle** [comment]
Now the only error I see is:
2020-08-18 13:00:16 WARNING  SHOWQUEUE-ADD :: [a7236ee] Could not get tvmaze externals. Cause: Expecting value: line 1 column 1 (char 0)

And to confirm I replaced the file correctly, you meant for me to put it here?:
![image](https://user-images.githubusercontent.com/1149292/90559980-4981cd00-e153-11ea-8132-aad0a1c33dc4.png)

**Comment by medariox** [comment]
Shut down Medusa. Delete the `__pycache__` folder and try again.

**Comment by fallenturtle** [comment]
I also deleted the cache from Medusa/Data.
Still not adding.. here are the logs:
2020-08-18 13:27:09 INFO	SHOWQUEUE-ADD :: [a7236ee] Setting all previously aired episodes to the specified status: Skipped
2020-08-18 13:27:09 WARNING	SHOWQUEUE-ADD :: [a7236ee] Could not get tvmaze externals. Cause: Expecting value: line 1 column 1 (char 0)
2020-08-18 13:27:09 WARNING	SHOWQUEUE-ADD :: [a7236ee] Could not get tvmaze externals. Cause: Expecting value: line 1 column 1 (char 0)
2020-08-18 13:27:08 INFO	SHOWQUEUE-ADD :: [a7236ee] 332331: Unable to find the show in the database
2020-08-18 13:27:08 WARNING	SHOWQUEUE-ADD :: [a7236ee] Could not get tvmaze externals. Cause: Expecting value: line 1 column 1 (char 0)
2020-08-18 13:27:07 INFO	SHOWQUEUE-ADD :: [a7236ee] TVDBv2: {'language': 'en', 'use_zip': True, 'session': <medusa.session.core.MedusaSession object at 0x000001CD420FA240>, 'cache': 'C:\\Medusa\\Data\\cache\\indexers\\TVDBv2'}
2020-08-18 13:27:07 INFO	SHOWQUEUE-ADD :: [a7236ee] Starting to add show by show_dir: E:\Transfer\tv\Altered Carbon
2020-08-18 13:26:34 INFO	MAIN :: [a7236ee] Building internal name cache for all shows
2020-08-18 13:26:34 INFO	MAIN :: [a7236ee] Finished processing 3272 scene exceptions.
2020-08-18 13:26:34 INFO	MAIN :: [a7236ee] Updating exception_cache and exception_season_cache
2020-08-18 13:26:32 INFO	MAIN :: [a7236ee] Checking for scene exceptions updates from AniDB
2020-08-18 13:26:31 INFO	MAIN :: [a7236ee] Checking for XEM scene exceptions updates for TVDBv2
2020-08-18 13:26:31 INFO	MAIN :: [a7236ee] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tmdb.json
2020-08-18 13:26:31 INFO	MAIN :: [a7236ee] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tvmaze.json
2020-08-18 13:26:31 INFO	MAIN :: [a7236ee] Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions_tvdb.json
2020-08-18 13:26:31 INFO	TORNADO :: [a7236ee] Starting Medusa on http://0.0.0.0:8081/
2020-08-18 13:26:31 INFO	MAIN :: [a7236ee] Starting Medusa [develop] using 'C:\\Medusa\\Data\\config.ini'
2020-08-18 13:26:30 INFO	MAIN :: [a7236ee] 12345: Unable to find the show in the database
2020-08-18 13:26:30 INFO	MAIN :: [a7236ee] [CACHE-DB] Updated major version to: 4.None
2020-08-18 13:26:30 INFO	MAIN :: [a7236ee] [CACHE-DB] Updated major version to: 3.None
2020-08-18 13:26:30 INFO	MAIN :: [a7236ee] Proceeding with upgrade
2020-08-18 13:26:30 INFO	MAIN :: [a7236ee] Backing up database before upgrade
2020-08-18 13:26:30 INFO	MAIN :: [a7236ee] [CACHE-DB] Updated major version to: 2.None
2020-08-18 13:26:30 INFO	MAIN :: [a7236ee] Proceeding with upgrade
2020-08-18 13:26:30 INFO	MAIN :: [a7236ee] Backing up database before upgrade
2020-08-18 13:26:28 INFO	MAIN :: [a7236ee] Broken providers found: ['']

**Comment by fallenturtle** [comment]
If, on the logging page, I change it from info to debug, I see a LOT of these:
```
2020-08-18 13:30:07 DEBUG	TORNADO :: [a7236ee] Failed doing web ui get request 'ui/get_messages': Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 217, in get
    method = getattr(self, route)
AttributeError: 'WebRoot' object has no attribute 'ui/get_messages'
```

and also:
```
2020-08-18 13:27:09 DEBUG	SHOWQUEUE-ADD :: [a7236ee] Trying other indexer: TMDB get_id_by_external
2020-08-18 13:27:09 WARNING	SHOWQUEUE-ADD :: [a7236ee] Could not get tvmaze externals. Cause: Expecting value: line 1 column 1 (char 0)
2020-08-18 13:27:09 DEBUG	SHOWQUEUE-ADD :: [a7236ee] User-Agent: Medusa/0.4.0 (Windows; 10; 15486bbe-e191-11ea-86bc-d43d7e942993)
2020-08-18 13:27:09 DEBUG	SHOWQUEUE-ADD :: [a7236ee] GET URL: http://api.tvmaze.com/lookup/shows?imdb=tt2261227 [Status: 200]
2020-08-18 13:27:09 WARNING	SHOWQUEUE-ADD :: [a7236ee] Could not get tvmaze externals. Cause: Expecting value: line 1 column 1 (char 0)
2020-08-18 13:27:09 DEBUG	SHOWQUEUE-ADD :: [a7236ee] User-Agent: Medusa/0.4.0 (Windows; 10; 15486bbe-e191-11ea-86bc-d43d7e942993)
2020-08-18 13:27:09 DEBUG	SHOWQUEUE-ADD :: [a7236ee] GET URL: http://api.tvmaze.com/lookup/shows?thetvdb=332331 [Status: 200]
2020-08-18 13:27:08 DEBUG	SHOWQUEUE-ADD :: [a7236ee] Trying other indexer: TVmaze get_id_by_external
2020-08-18 13:27:08 DEBUG	SHOWQUEUE-ADD :: [a7236ee] 332331: Loading show info from TVDBv2
2020-08-18 13:27:08 INFO	SHOWQUEUE-ADD :: [a7236ee] 332331: Unable to find the show in the database
2020-08-18 13:27:08 DEBUG	SHOWQUEUE-ADD :: [a7236ee] 332331: Loading show info from database
2020-08-18 13:27:08 DEBUG	SHOWQUEUE-ADD :: [a7236ee] Trying other indexer: TMDB get_id_by_external
2020-08-18 13:27:08 WARNING	SHOWQUEUE-ADD :: [a7236ee] Could not get tvmaze externals. Cause: Expecting value: line 1 column 1 (char 0)
2020-08-18 13:27:08 DEBUG	SHOWQUEUE-ADD :: [a7236ee] User-Agent: Medusa/0.4.0 (Windows; 10; 15486bbe-e191-11ea-86bc-d43d7e942993)
2020-08-18 13:27:08 DEBUG	SHOWQUEUE-ADD :: [a7236ee] GET URL: http://api.tvmaze.com/lookup/shows?imdb=tt2261227 [Status: 200]
2020-08-18 13:27:08 DEBUG	SHOWQUEUE-ADD :: [a7236ee] Trying other indexer: TVmaze get_id_by_external
2020-08-18 13:27:07 DEBUG	SHOWQUEUE-ADD :: [a7236ee] User-Agent: Medusa/0.4.0 (Windows; 10; 15486bbe-e191-11ea-86bc-d43d7e942993)
2020-08-18 13:27:07 DEBUG	SHOWQUEUE-ADD :: [a7236ee] GET URL: https://api.thetvdb.com/series/332331/episodes/query?page=1 [Status: 200]
2020-08-18 13:27:07 DEBUG	SHOWQUEUE-ADD :: [a7236ee] Getting all episodes of 332331
2020-08-18 13:27:07 DEBUG	SHOWQUEUE-ADD :: [a7236ee] User-Agent: Medusa/0.4.0 (Windows; 10; 15486bbe-e191-11ea-86bc-d43d7e942993)
2020-08-18 13:27:07 DEBUG	SHOWQUEUE-ADD :: [a7236ee] GET URL: https://api.thetvdb.com/series/332331 [Status: 200]
2020-08-18 13:27:07 DEBUG	TORNADO :: [a7236ee] Failed doing web ui get request 'ui/get_messages': Traceback (most recent call last):

  File "C:\Medusa\Medusa\medusa\server\web\core\base.py", line 217, in get

    method = getattr(self, route)

AttributeError: 'WebRoot' object has no attribute 'ui/get_messages'
2020-08-18 13:27:07 DEBUG	SHOWQUEUE-ADD :: [a7236ee] Getting all show data for 332331
2020-08-18 13:27:07 DEBUG	SHOWQUEUE-ADD :: [a7236ee] Getting all series data for 332331
2020-08-18 13:27:07 DEBUG	SHOWQUEUE-ADD :: [a7236ee] Configured language en override show language of en
2020-08-18 13:27:07 INFO	SHOWQUEUE-ADD :: [a7236ee] TVDBv2: {'language': 'en', 'use_zip': True, 'session': <medusa.session.core.MedusaSession object at 0x000001CD420FA240>, 'cache': 'C:\\Medusa\\Data\\cache\\indexers\\TVDBv2'}
2020-08-18 13:27:07 INFO	SHOWQUEUE-ADD :: [a7236ee] Starting to add show by show_dir: E:\Transfer\tv\Altered Carbon

```

**Comment by p0psicles** [comment]
Can you try to get the full debug log for adding a show?

**Comment by fallenturtle** [comment]
[8360_application.log](https://github.com/pymedusa/Medusa/files/5094403/8360_application.log)

**Comment by p0psicles** [comment]
It has something to do with the ui messages. I'll have to look into that. But it's weird. As the ui messages error doesn't have anything to do with the add show thread. 

@medariox thoughts?

**Comment by p0psicles** [comment]
Maybe it has something to do with the notification send through the websocket?

**Comment by medariox** [comment]
The exception is probably crashing the thread, so the shows won't get added. But there are various issues with the report. The code that errors doesn't seem to exist. At least not in the current version. Also the log commit doesn't match what was reported in the first post. I think the best plan is to make a backup and start with a fresh copy.

**Comment by p0psicles** [comment]
I'm catching the exception with the file I send him. So that can't be the case. It's even showing the error through a warning, so that proves it's caught

**Comment by fallenturtle** [comment]
Could the difference between the OP log and what I posted later be related to the modification @p0psicles had me do? Another difference is that for the original I had Medusa pointing at my preexisting directory of shows and tried importing a existing show and adding a new one. For the full log I saw that it was reporting its scan of all those shows and I wasn't comfortable sharing that with the public so I set Medusa to use another temp directory on the same drive and cleared the cache. If you think thats coloring the results I can put it back to the original location and attempt to manually anonymize the log.

**Comment by p0psicles** [comment]
Can you reproduce it by adding a show for which you don't have a folder yet?

**Comment by fallenturtle** [comment]
The previously linked log file is adding a show which I didn't have a folder yet, unless you mean while setting Medusa back to using my original show root directory.
