### ISSUE TITLE
Transmission Add Error - AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by NunoHiggs** [pymedusa/Medusa#8361]
When i try to add a torrent to download, *sometimes*, i get this error:

Traceback (most recent call last):
  File "/opt/Medusa/medusa/search/queue.py", line 459, in run
    self.success = snatch_episode(result)
  File "/opt/Medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/opt/Medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/opt/Medusa/medusa/clients/torrent/transmission.py", line 77, in _get_auth
    self.auth = re.search(r'X-Transmission-Session-Id:\s*(\w+)', self.response.text).group(1)
**AttributeError: 'NoneType' object has no attribute 'group'**

The wierd part is that the error IS NOT persistent. Sometimes it ads the torrent, sometimes i get the error.
I am on the latest transmission-daemon, and this happens with or without auth on transmission-daemon.
The RPC path is correct, and when i test it, it sometimes the error is shown, and sometimes it does not.

**To Reproduce**
Search, try to auto-add the torrent via transmission. Test connection. This is an intermittent error.

**Expected behavior**
It to work always or not. This error being intermittent tells me that might be a bug

**Medusa (please complete the following information):**
 - OS: SuSE 15.1
 - Branch: master
 - Commit:  471c8ed43f6125ebdcd471c260757d8c7cae2ad4
 - Python version: Python 3.7.6
 - Database version: Database: 44.15

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-08-18 16:26:36 DEBUG    SNATCHQUEUE-SNATCH-329089 :: [471c8ed] Calling Transmission Client
2020-08-18 16:26:38 INFO     SEARCHQUEUE-DAILY-SEARCH :: [471c8ed] Downloading XXXXXXXXXXX with 2 seeders and 1 leechers and size 949.79 MB from ThePirateBay
2020-08-18 16:26:38 DEBUG    SNATCHQUEUE-SNATCH-329089 :: [471c8ed] POST URL: **********/transmission/rpc [Status: 403]
2020-08-18 16:26:38 DEBUG    SNATCHQUEUE-SNATCH-329089 :: [471c8ed] User-Agent: Medusa/0.3.16 (Linux; 5.3.12-lp151.2-default; d58fdad4-e154-11ea-b66d-02002baac1b2)
2020-08-18 16:26:38 DEBUG    SNATCHQUEUE-SNATCH-329089 :: [471c8ed] With post data: {"method": "session-get"}
2020-08-18 16:26:38 ERROR    SNATCHQUEUE-SNATCH-329089 :: [471c8ed] Snatch failed! For result: XXXXXXXXXXX

Traceback (most recent call last):
  File "/opt/Medusa/medusa/search/queue.py", line 459, in run
    self.success = snatch_episode(result)
  File "/opt/Medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/opt/Medusa/medusa/clients/torrent/generic.py", line 238, in send_torrent
    if not self._get_auth():
  File "/opt/Medusa/medusa/clients/torrent/transmission.py", line 77, in _get_auth
    self.auth = re.search(r'X-Transmission-Session-Id:\s*(\w+)', self.response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
</details>

**Additional context**

**Comment by NunoHiggs** [comment]
Found the error. I am using a proxy carousel for avoiding ip hammering when my daily scan runs.
Some of the proxy servers, are on a remove private network, with different ip address, that were not published on settings.json.

I know that the message error is generated by python and not medusa, but crap... if it was more explicit i could have found the error sooner :)

Thanks anyway.
