### ISSUE TITLE
Can't start Medusa anymore

### ISSUE THREAD

**Issue by MatthK** [pymedusa/Medusa#8409]
**Describe the bug**
I have installed Python 3.7 and made that the priority. I then tried to restart Medusa, but now it won't start up again. Now I get the following error messages in journalctl -xe:

```
Aug 29 00:40:46 Ubuntu systemd[1]: Started resolvconf-pull-resolved.service.
-- Subject: Unit resolvconf-pull-resolved.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit resolvconf-pull-resolved.service has finished starting up.
--
-- The start-up result is RESULT.
Aug 29 00:42:57 Ubuntu sudo[5776]:    matth : TTY=pts/0 ; PWD=/opt/medusa ; USER=root ; COMMAND=/usr/sbin/service medusa start
Aug 29 00:42:57 Ubuntu sudo[5776]: pam_unix(sudo:session): session opened for user root by matth(uid=0)
Aug 29 00:42:58 Ubuntu systemd[1]: Starting LSB: starts instance of Medusa...
-- Subject: Unit medusa.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit medusa.service has begun starting up.
Aug 29 00:42:58 Ubuntu medusa[5812]: /etc/default/medusa not found using default settings.
Aug 29 00:42:58 Ubuntu medusa[5812]: Starting Medusa
Aug 29 00:42:58 Ubuntu medusa[5812]: Traceback (most recent call last):
Aug 29 00:42:58 Ubuntu medusa[5812]:   File "start.py", line 6, in <module>
Aug 29 00:42:58 Ubuntu medusa[5812]:     from medusa.__main__ import main
Aug 29 00:42:58 Ubuntu medusa[5812]: ImportError: No module named medusa.__main__
Aug 29 00:42:58 Ubuntu systemd[1]: medusa.service: Control process exited, code=exited status=1
Aug 29 00:42:58 Ubuntu systemd[1]: medusa.service: Failed with result 'exit-code'.
Aug 29 00:42:58 Ubuntu systemd[1]: Failed to start LSB: starts instance of Medusa.
-- Subject: Unit medusa.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit medusa.service has failed.
--
-- The result is RESULT.
Aug 29 00:42:58 Ubuntu sudo[5776]: pam_unix(sudo:session): session closed for user root

```
systemctl status medusa.service shows the following:

```
● medusa.service - LSB: starts instance of Medusa
   Loaded: loaded (/etc/init.d/medusa; generated)
   Active: failed (Result: exit-code) since Sat 2020-08-29 00:42:58 HKT; 2min 28s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3513 ExecStop=/etc/init.d/medusa stop (code=exited, status=1/FAILURE)
  Process: 5812 ExecStart=/etc/init.d/medusa start (code=exited, status=1/FAILURE)

Aug 29 00:42:58 Ubuntu systemd[1]: Starting LSB: starts instance of Medusa...
Aug 29 00:42:58 Ubuntu medusa[5812]: /etc/default/medusa not found using default settings.
Aug 29 00:42:58 Ubuntu medusa[5812]: Starting Medusa
Aug 29 00:42:58 Ubuntu medusa[5812]: Traceback (most recent call last):
Aug 29 00:42:58 Ubuntu medusa[5812]:   File "start.py", line 6, in <module>
Aug 29 00:42:58 Ubuntu medusa[5812]:     from medusa.__main__ import main
Aug 29 00:42:58 Ubuntu medusa[5812]: ImportError: No module named medusa.__main__
Aug 29 00:42:58 Ubuntu systemd[1]: medusa.service: Control process exited, code=exited status=1
Aug 29 00:42:58 Ubuntu systemd[1]: medusa.service: Failed with result 'exit-code'.
Aug 29 00:42:58 Ubuntu systemd[1]: Failed to start LSB: starts instance of Medusa.

```
**Medusa (please complete the following information):**
 - OS: ubuntu 18.04.4 LTS
 - Branch: master
 - Python version: 3.7.19

I have also seen before warning messages that said 'attempt to write a readonly database'. Though I am not aware that I made any changes to that.

**Comment by p0psicles** [comment]
Why aren't you starting using systemd init? From /etc/systemd/system? We provide a systemd init script

**Comment by medariox** [comment]
Have you followed our guide to switch to Python 3? https://github.com/pymedusa/Medusa/wiki/Switch-to-Python-3

**Comment by MatthK** [comment]
I haven't started medusa for ages manually, so I wasn't aware of the differences anymore. When I try to start Medusa with `sudo systemctl start medusa` I do get the same error message.

I have followed similar instructions as in the mentioned guide, but haven't done the second part to update the systemd script at first. I found that a bit later, made the changes but I get still the same error message.

**Comment by p0psicles** [comment]
Do this.
Start medusa manually using python3 start.py... 
You can find rest of parameters from your init script. If its still erroring. Post more info. 

Content of init script. 
Location medusa folder
Content of folder
Access rights medusa folder

**Comment by MatthK** [comment]
So, I tried to manually start medusa using `/bin/sh /opt/medusa/start.py -q --daemon --nolaunch --pidfile=/var/run/PyMedusa/Medusa.pid --datadir=/opt/medusa`

That leads to the error message:

```
/opt/medusa/start.py: 3: /opt/medusa/start.py: Startup script.: not found
from: can't read /var/mail/__future__
from: can't read /var/mail/medusa.__main__
/opt/medusa/start.py: 10: /opt/medusa/start.py: Syntax error: end of file unexpected
```
c 
The start.py has the following contents:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*
"""Startup script."""
from __future__ import unicode_literals

from medusa.__main__ import main

if __name__ == '__main__':
    main()

```
The directory /opt/medusa has the following content/permissions:

```
matth@Ubuntu:/opt/medusa$ ls -l
total 85652
drw-rw-rw-  2 medusa medusa     4096 Aug 24 19:08 backup
drw-rw-rw-  6 medusa medusa     4096 Aug 24 19:08 cache
-rw-rw-rw-  1 medusa medusa 58449920 Aug 25 19:52 cache.db
-rw-rw-rw-  1 medusa medusa    13312 Jan  1  2019 cache.db.v1.None
-rw-rw-rw-  1 medusa medusa 15073280 Nov 12  2019 cache.db.v2.None
-rw-rw-rw-  1 medusa medusa    29982 Aug 24 19:08 CHANGELOG.md
-rw-rw-rw-  1 medusa medusa    40513 Aug 29 00:57 config.ini
-rw-rw-rw-  1 medusa medusa     2648 Jan  1  2019 CONTRIBUTING.md
-rw-rw-rw-  1 medusa medusa    35132 Jan  1  2019 COPYING.txt
-rw-rw-rw-  1 medusa medusa      634 Sep 14  2019 Dockerfile
drw-rw-rw-  2 medusa medusa     4096 Apr 29 09:26 dredd
drw-rw-rw- 53 medusa medusa     4096 Aug 24 19:08 ext
drw-rw-rw- 25 medusa medusa     4096 Aug 24 19:08 ext2
drw-rw-rw-  4 medusa medusa     4096 Feb 16  2020 ext3
-rw-rw-rw-  1 medusa medusa     4096 Jan  1  2019 failed.db
-rw-rw-rw-  1 medusa medusa     4096 Jan  1  2019 failed.db.v2.None
drw-rw-rw-  2 medusa medusa     4096 Sep 14  2019 hooks
drw-rw-rw- 12 medusa medusa     4096 Aug 24 19:08 lib
drw-rw-rw-  2 medusa medusa     4096 Aug 29 00:56 Logs
-rw-rw-rw-  1 medusa medusa  3813376 Aug 25 19:39 main.db
-rw-rw-rw-  1 medusa medusa    24576 Jan  1  2019 main.db.v42
-rw-rw-rw-  1 medusa medusa    24576 Jan  1  2019 main.db.v43.1
-rw-rw-rw-  1 medusa medusa    24576 Jan  1  2019 main.db.v44.1
-rw-rw-rw-  1 medusa medusa    27648 Jan  1  2019 main.db.v44.10
-rw-rw-rw-  1 medusa medusa    27648 Jan  1  2019 main.db.v44.11
-rw-rw-rw-  1 medusa medusa  1386496 Mar 18  2019 main.db.v44.12
-rw-rw-rw-  1 medusa medusa  1386496 Mar 18  2019 main.db.v44.13
-rw-rw-rw-  1 medusa medusa  3095552 Apr 24 22:39 main.db.v44.14
-rw-rw-rw-  1 medusa medusa  3810304 Aug 24 19:08 main.db.v44.15
-rw-rw-rw-  1 medusa medusa    24576 Jan  1  2019 main.db.v44.2
-rw-rw-rw-  1 medusa medusa    24576 Jan  1  2019 main.db.v44.3
-rw-rw-rw-  1 medusa medusa    24576 Jan  1  2019 main.db.v44.4
-rw-rw-rw-  1 medusa medusa    24576 Jan  1  2019 main.db.v44.5
-rw-rw-rw-  1 medusa medusa    24576 Jan  1  2019 main.db.v44.6
-rw-rw-rw-  1 medusa medusa    27648 Jan  1  2019 main.db.v44.7
-rw-rw-rw-  1 medusa medusa    27648 Jan  1  2019 main.db.v44.8
-rw-rw-rw-  1 medusa medusa    27648 Jan  1  2019 main.db.v44.9
-rw-rw-rw-  1 medusa medusa      302 Jun 13  2019 MANIFEST.in
drw-rw-rw- 28 medusa medusa     4096 Aug 24 19:08 medusa
-rw-rw-rw-  1 medusa medusa      390 Feb 16  2020 package.json
-rw-rw-rw-  1 medusa medusa     8525 Aug 24 19:08 readme.md
-rw-rw-rw-  1 medusa medusa     1287 Aug 24 19:08 renovate.json
-rw-rw-rw-  1 medusa medusa     1438 Aug 24 19:08 requirements.txt
drw-rw-rw-  2 medusa medusa     4096 Dec 10  2019 runscripts
-rw-rw-rw-  1 root   root       3554 Aug 28 15:10 server.crt
-rw-rw-rw-  1 root   root       1704 Aug 28 15:10 server.key
-rw-rw-rw-  1 medusa medusa     9662 Aug 24 19:08 setup.cfg
-rw-rw-rw-  1 medusa medusa     4222 Apr 29 09:26 setup.py
-rw-rw-rw-  1 medusa medusa      200 Jun 13  2019 SickBeard.py
-rw-rw-rw-  1 medusa medusa      180 Jun 13  2019 start.py
drw-rw-rw-  8 medusa medusa     4096 Aug 24 19:08 tests
drw-rw-rw-  4 medusa medusa     4096 Jan  1  2019 themes
drw-rw-rw-  3 medusa medusa     4096 Jun 13  2019 themes-default
-rw-rw-rw-  1 medusa medusa      306 Mar 18  2019 tox.ini
-rw-rw-rw-  1 medusa medusa    61687 Aug 24 19:08 yarn.lock
```
The /opt/medusa directory belongs to root:

```
matth@Ubuntu:/opt$ ls -ld medusa
drwxr-xr-x 19 root root 4096 Aug 29 12:37 medusa
```

The /etc/init.d/medusa init script has the following content:

```
#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          medusa
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of Medusa
# Description:       starts instance of Medusa using start-stop-daemon
### END INIT INFO

# Source Medusa configuration
if [ -f /etc/default/medusa ]; then
    . /etc/default/medusa
else
    echo "/etc/default/medusa not found using default settings.";
fi

# Source init functions
. /lib/lsb/init-functions

# Script name
NAME=medusa

# App name
DESC=Medusa

## Don't edit this file
## Edit user configuation in /etc/default/medusa to change
##
## APP_USER=         #$RUN_AS, username to run medusa under, the default is medusa
## APP_HOME=         #$APP_PATH, the location of start.py, the default is /opt/medusa
## APP_DATA=         #$DATA_DIR, the location of sickbeard.db, cache, logs, the default is /opt/medusa
## APP_PIDFILE=      #$PID_FILE, the location of medusa.pid, the default is /var/run/PyMedusa/Medusa.pid
## PYTHON_BIN=      #$DAEMON, the location of the python binary, the default is /usr/bin/python3
## APP_OPTS=         #$EXTRA_DAEMON_OPTS, extra cli option for medusa, i.e. " --config=/home/medusa/conf$
## SSD_OPTS=        #$EXTRA_SSD_OPTS, extra start-stop-daemon option like " --group=users"
##
## EXAMPLE if want to run as different user
## add APP_USER=username to /etc/default/medusa
## otherwise default medusa is used

## The defaults
# Run as username
RUN_AS=${APP_USER-medusa}

# Path to app APP_HOME=path_to_app_start.py
APP_PATH=${APP_HOME-/opt/medusa}

# Data directory where sickbeard.db, cache and logs are stored
DATA_DIR=${APP_DATA-/opt/medusa}

# Path to store PID file
PID_FILE=${APP_PIDFILE-/var/run/PyMedusa/Medusa.pid}

# path to python bin
DAEMON=${PYTHON_BIN-/usr/bin/python3}

# Extra daemon option like: APP_OPTS=" --config=/home/medusa/config.ini"
EXTRA_DAEMON_OPTS=${APP_OPTS-}

# Extra start-stop-daemon option like START_OPTS=" --group=users"
EXTRA_SSD_OPTS=${SSD_OPTS-}
##

PID_PATH=`dirname $PID_FILE`
DAEMON_OPTS=" start.py -q --daemon --nolaunch --pidfile=${PID_FILE} --datadir=${DATA_DIR} ${EXTRA_DAEMON$

##

test -x $DAEMON || exit 0

set -e

# Create PID directory if not exist and ensure the Medusa user can write to it
if [ ! -d $PID_PATH ]; then
    mkdir -p $PID_PATH
    chown $RUN_AS $PID_PATH
fi

if [ ! -d $DATA_DIR ]; then
    mkdir -p $DATA_DIR
    chown $RUN_AS $DATA_DIR
fi

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        rm $PID_FILE
    fi
fi

start_medusa() {
    echo "Starting $DESC"
    start-stop-daemon -d $APP_PATH -c $RUN_AS $EXTRA_SSD_OPTS --start --pidfile $PID_FILE --exec $DAEMON$
}

stop_medusa() {
    echo "Stopping $DESC"
    start-stop-daemon --stop --pidfile $PID_FILE --retry 15
}

case "$1" in
    start)
        start_medusa
        ;;
    stop)
        stop_medusa
        ;;

    restart|force-reload)
        stop_medusa
        sleep 2
        start_medusa
        ;;
    status)
        status_of_proc -p "$PID_FILE" "$DAEMON" "$DESC"
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
```

**Comment by p0psicles** [comment]
Two things, set up using systemd init script. 
And run start.py with python. Like `python3 start.py`

**Comment by MatthK** [comment]
When trying `python3 start.py` in /opt/medusa I get an error saying:

```
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    from medusa.__main__ import main
ModuleNotFoundError: No module named 'medusa.__main__'
```

When I start it with `sudo python3 start.py` then it starts up and is working.
But now I'm stuck on a screen. 

Is it a permission problem then, when root can run it but not the normal user?

**Comment by medariox** [comment]
I really suggest you to update your systemd script according to the guide posted above.

**Comment by p0psicles** [comment]
Make sure your all your files have the correct user/group.

**Comment by MatthK** [comment]
I have done the full part in the systemd section. Should I pull the whole thing down again and create the already existing user as well? Will that keep my existing database intact?

**Comment by MatthK** [comment]
The whole directory /opt/medusa is owned by the user medusa. Is there anything else that it should have?

**Comment by p0psicles** [comment]
Also the files deeper in the tree?
What does your systemd init look like?

**Comment by p0psicles** [comment]
In the medusa folder. Run: `chmod medusa:medusa -R  ./` that should set the rights. Now in your init make sure it's started with the medusa user

**Comment by MatthK** [comment]
That somehow did the trick. 

I first ran `find /opt/medusa -type d -exec chmod 774 {} +` to give all the directories the execute permission. Then I also ran your `chown medusa:medusa -R ./` (I used chown, as chmod needs the permission options) and tried to start it up again. And now it is up and running again.

Thank you very much. That's awesome and very fast support. Highly appreciated!
