### ISSUE TITLE
Speedcd - Failed parsing provider.

### ISSUE THREAD

**Issue by iLlama** [pymedusa/Medusa#8428]
While trying to snatch any show via Speed.cd, I get the following error - 

`2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'`

**Medusa (please complete the following information):**
 - OS: Windows 7 (Yeah I should probably upgrade lol)
 - Branch: master
 - Commit: 20915b56d64dc7522e484f326d9cfe7449a73193
 - Python version: 3.7.3
 - Database version: 44.16

**Debug logs (at least 50 lines):**
`2020-09-02 10:23:16 INFO     FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Performing episode search for The 100
2020-09-02 10:23:16 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Transaction with 1 queries executed
2020-09-02 10:23:16 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Could not find all candidates in cache, searching provider.
2020-09-02 10:23:17 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] GET URL: https://speed.cd/ [Status: 200]
2020-09-02 10:23:17 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] User-Agent: Medusa/0.4.1 (Windows; 7; e1f6f4cc-ed2f-11ea-a16c-080027c3822d)
2020-09-02 10:23:17 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Search mode: Episode
2020-09-02 10:23:17 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Search string: The 100 S07E12
2020-09-02 10:23:17 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] GET URL: https://speed.cd/browse.php?c30=1&c52=1&c57=1&c2=1&c49=1&c55=1&c41=1&c50=1&search=The+100+S07E12 [Status: 302]
2020-09-02 10:23:17 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] User-Agent: Medusa/0.4.1 (Windows; 7; e1f6f4cc-ed2f-11ea-a16c-080027c3822d)
2020-09-02 10:23:18 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] GET URL: https://speed.cd/browse/q/The+100+S07E12 [Status: 200]
2020-09-02 10:23:18 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] User-Agent: Medusa/0.4.1 (Windows; 7; e1f6f4cc-ed2f-11ea-a16c-080027c3822d)
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 ERROR    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Failed parsing provider.
Traceback (most recent call last):
  File "C:\Medusa\Medusa\medusa\providers\torrent\html\speedcd.py", line 124, in parse
    cells[2].find(title='Download').parent['href'])
AttributeError: 'NoneType' object has no attribute 'parent'
2020-09-02 10:23:18 DEBUG    FORCEDSEARCHQUEUE-BACKLOG-268592 :: [Speedcd] :: [20915b5] Found 0 unique search results`

**Comment by p0psicles** [comment]
I could take a look. But I'd need a login.

**Comment by Chopp3rDave** [comment]
I could provide you an invite.

**Comment by p0psicles** [comment]
Please pm me on discord.
@duramato do you have it? Just checking

**Comment by Chopp3rDave** [comment]
I have discord, but I am not in the Medusa server. Can you provide a link?

**Comment by Chopp3rDave** [comment]
I'll need an invite for the server.

**Comment by duramato** [comment]
Yeah @p0psicles

**Comment by medariox** [comment]
@Chopp3rDave https://discord.gg/zMdAdUK

**Comment by Chopp3rDave** [comment]
Sent you a dm on discord @p0psicles

**Comment by Chopp3rDave** [comment]
@p0psicles I sent you a DM on discord a few days ago but no response.

**Comment by medariox** [comment]
Fixed.
