### ISSUE TITLE
Error after updating today: "bad character range"

### ISSUE THREAD

**Issue by gers1978** [pymedusa/Medusa#8455]
`me@Mac-Mini ~ % python /Applications/Medusa/SickBeard.py
Traceback (most recent call last):
  File "/Applications/Medusa/SickBeard.py", line 6, in <module>
    from medusa.__main__ import main
  File "/Applications/Medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/Applications/Medusa/medusa/providers/__init__.py", line 41, in <module>
    provider_names = import_providers(__name__)
  File "/Applications/Medusa/medusa/providers/__init__.py", line 37, in import_providers
    import_submodules(package_name)
  File "/Applications/Medusa/medusa/providers/__init__.py", line 25, in import_submodules
    module = importlib.import_module(full_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Applications/Medusa/medusa/providers/torrent/__init__.py", line 29, in <module>
    import_submodules(__name__)
  File "/Applications/Medusa/medusa/providers/torrent/__init__.py", line 22, in import_submodules
    valid_pkg = import_submodules(full_name)
  File "/Applications/Medusa/medusa/providers/torrent/__init__.py", line 17, in import_submodules
    module = importlib.import_module(full_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Applications/Medusa/medusa/providers/torrent/html/thepiratebay.py", line 21, in <module>
    import validators
  File "/Applications/Medusa/ext/validators/__init__.py", line 23, in <module>
    from .url import url
  File "/Applications/Medusa/ext/validators/url.py", line 90, in <module>
    re.UNICODE | re.IGNORECASE
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
markmc78@Mac-Mini ~ % rl import url
  File "/Applications/Medusa/ext/validators/url.py", line 90, in <module>
    re.UNICODE | re.IGNORECASE
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range`

**Comment by medariox** [comment]
Python version?

**Comment by gers1978** [comment]
If I run `python --version` I get:

`2.7.16`

**Comment by p0psicles** [comment]
Try upgrading to python 3.6 or higher

**Comment by gers1978** [comment]
> Try upgrading to python 3.6 or higher

Is that awkward on a Mac?

**Comment by p0psicles** [comment]
I don't have a Mac. But fact is that you don't have a choice. As in a few versions, we don't allow any upgrades on py2

**Comment by gers1978** [comment]
Running using python 3 fixed it, thanks
