### ISSUE TITLE
Medusa fails to start after most recent release

### ISSUE THREAD

**Issue by dglodi** [pymedusa/Medusa#8466]
Recently rolled up to newest update. 
Service looks to be started however no UI page is accessible.
Windows Event log is cycling the following error messages:

Program C:\Medusa\Python\python.exe for service Medusa exited with return code 1.
Killing process tree of process 4988 for service Medusa with exit code 1
Killing PID 4988 in process tree of PID 4988 because service Medusa is stopping.
Service Medusa action for exit code 1 is Restart. Attempting to restart C:\Medusa\Python\python.exe.
Started C:\Medusa\Python\python.exe "C:\Medusa\Medusa\SickBeard.py" --nolaunch --port=8081 --datadir="C:\Medusa\Data" for service Medusa in C:\Medusa\Data.

 - Win Server 2016
 - Commit: Most recent? as of 9/8/2020
 - Python version: 2.7

**Additional context**
May need assistance gathering further logs as i'm not 100% sure where to look without the GUI working.

**Comment by p0psicles** [comment]
First upgrade to python3.6 or higher. 
Then try starting Medusa from prompt.
Run `C:\Medusa\Python\python.exe.
Started C:\Medusa\Python\python.exe "C:\Medusa\Medusa\SickBeard.py" --nolaunch --port=8081 --datadir="C:\Medusa\Data"` from Medusa program dir

**Comment by dglodi** [comment]
Perfect, i'll give that a try later tonight and post my results.

**Comment by dglodi** [comment]
I downloaded the 3.8.5 32 bit version
uninstalled other versions

ran the command you stated and got the following from cmd prompt

C:\Medusa>python.exe "c:\medusa\medusa\sickbeard.py" --nolaunch --port=8081 --datadir="C:\medusa\data"
2020-09-08 17:32:48 INFO     MAIN :: [708c2e9] Broken providers found: ['']
2020-09-08 17:32:48 WARNING  MAIN :: [708c2e9] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-09-08 17:32:48 WARNING  MAIN :: [708c2e9] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-09-08 17:32:48 WARNING  MAIN :: [708c2e9] No git specified, can't use git commands
2020-09-08 17:32:48 WARNING  MAIN :: [708c2e9] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-09-08 17:32:48 WARNING  MAIN :: [708c2e9] No git specified, can't use git commands
2020-09-08 17:32:48 WARNING  MAIN :: [708c2e9] git version returned : 'git' is not recognized as an internal or external command,
operable program or batch file.
2020-09-08 17:32:48 WARNING  MAIN :: [708c2e9] No git specified, can't use git commands
Traceback (most recent call last):
  File "c:\medusa\medusa\sickbeard.py", line 9, in <module>
    main()
  File "c:\medusa\medusa\medusa\__main__.py", line 2212, in main
    application.start(sys.argv[1:])
  File "c:\medusa\medusa\medusa\__main__.py", line 328, in start
    self.initialize(console_logging=self.console_logging)
  File "c:\medusa\medusa\medusa\__main__.py", line 1027, in initialize
    app.APP_VERSION = updater.current_version
  File "c:\medusa\medusa\medusa\updater\github_updater.py", line 53, in current_version
    return cur_version.lstrip('v')
AttributeError: 'NoneType' object has no attribute 'lstrip'

**Comment by dglodi** [comment]
![capture1](https://user-images.githubusercontent.com/68709030/92530879-38c8f200-f1fb-11ea-852a-2258eaa926eb.PNG)
![capture2](https://user-images.githubusercontent.com/68709030/92530955-6746cd00-f1fb-11ea-96b0-2564c6dcde69.PNG)

**Comment by medariox** [comment]
Please install using the Medusa installer we provide for Windows: https://github.com/pymedusa/MedusaInstaller/releases

**Comment by dglodi** [comment]
ANNNND we are back!
thank you very much!
