### ISSUE TITLE
Medusa not updating

### ISSUE THREAD

**Issue by Yellow1144** [pymedusa/Medusa#8482]
Medusa not updating

I notice there are updates so I back everything up and click Update Now. The notification shows that config is being backed up. It is taking longer than usual. Screen goes white and..... nothing.. After a long while a notification indicates backup was successful then still.... nothing. 

I can reload the page and it brings me to whatever page I was at before, show page, etc, but it is still showing there are updates.

This is what is in the log

 Thread_14 :: [c30eaa2] Config backup successful
2020-09-11 10:46:30 ERROR    Thread_14 :: [c30eaa2] Exception generated: Cant locate template for uri 'restart.mako'
Traceback (most recent call last):
  File "/home/user/.pymedusa/ext/mako/lookup.py", line 249, in get_template
    return self._check(uri, self._collection[uri])
KeyError: 'restart.mako'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pymedusa/medusa/server/web/core/base.py", line 251, in async_call
    result = function(**kwargs)
  File "/home/user/.pymedusa/medusa/server/web/home/handler.py", line 634, in update
    t = PageTemplate(rh=self, filename='restart.mako')
  File "/home/user/.pymedusa/medusa/server/web/core/base.py", line 75, in __init__
    self.template = lookup.get_template(filename)
  File "/home/user/.pymedusa/ext/mako/lookup.py", line 263, in get_template
    "Cant locate template for uri %r" % uri
mako.exceptions.TopLevelLookupException: Cant locate template for uri 'restart.mako'

Branch: develop
Commit: c30eaa2393a16c5589797ac173fd3c753439259a
Version: 0.4.1
Database: 44.16
--
Python Version: | 3.7.9 (default, Aug 18 2020, 06:24:24) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.15.0-112-generic-x86_64-with-LinuxMint-18.3-sylvia
Locale: | en_CA.UTF-8

**Comment by p0psicles** [comment]
I fixed that in develop. I think you'll need to update manually once using git. Make sure you chown after the git pull. And restart of course

**Comment by Kafkamorph** [comment]
I git pulled, and it's still happening.

**Comment by Kafkamorph** [comment]
I git pulled to fix this, but when restarting a new error pops up:

```
2020-09-18 08:14:39 ERROR    Thread_0 :: [efadfe9] Exception generated: update() got an unexpected keyword argument 'pid'
Traceback (most recent call last):
  File "/root/Medusa/medusa/server/web/core/base.py", line 251, in async_call
    result = function(**kwargs)
TypeError: update() got an unexpected keyword argument 'pid'
```

**Comment by p0psicles** [comment]
That will go away if all your browser tabs have refreshed
