### ISSUE TITLE
Lots of "Error while trying to fetch release groups for show <show name>" after swiching to Python 3

### ISSUE THREAD

**Issue by QuadPiece** [pymedusa/Medusa#8501]
**Describe the bug**
A warning in the logs recommended I switch from Python 2 to 3, so I did.  
However I now get a "Error while trying to fetch release groups for show <show name>" every single time I click on a show in search results.  
Accompanied with a "db type could not be determined traceback in the debug logs"

The bug does not seem to prevent medusa from working, it just generates an annoying error pop up every single time i select a search result.

**To Reproduce**
1. Run Medusa on Python 2.7.16 without issue
2. `systemctl stop medusa`
3. Use `update-alternatives` so Python 3.7.3 is now the default python
3. `systemctl start medusa`

**Expected behavior**
Nothing, medusa should not generate additional errors

**Screenshots**
Selecting any show in search results produces this pop-up:
![firefox_CuQYh66V7A](https://user-images.githubusercontent.com/6379091/93172769-c50f7380-f72b-11ea-8fc8-5abe4c289b76.png)

**Medusa (please complete the following information):**
 - OS: Debian Linux 10 (buster)
 - Branch: master
 - Commit: b352bb6924afcdfafce176a540d53ce405ca1312
 - Python version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0] (Was 2.7.16)
 - Database version: 44.16

**Debug logs (at least 50 lines):**
<details>

```
2020-09-15 06:06:38 ERROR	Thread-9 :: [b352bb6] Exception generated: db type could not be determined
Traceback (most recent call last):
  File "/home/quad/Medusa/medusa/server/web/core/base.py", line 251, in async_call
    result = function(**kwargs)
  File "/home/quad/Medusa/medusa/server/web/home/handler.py", line 1807, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</home/quad/Medusa/ext/decorator.py:decorator-gen-14>", line 2, in get_release_groups_for_anime
  File "/home/quad/Medusa/ext/dogpile/cache/region.py", line 1360, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/home/quad/Medusa/ext/dogpile/cache/region.py", line 962, in get_or_create
    async_creator,
  File "/home/quad/Medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/home/quad/Medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/home/quad/Medusa/ext/dogpile/cache/region.py", line 902, in get_value
    value = self.backend.get(key)
  File "/home/quad/Medusa/ext/dogpile/cache/backends/file.py", line 223, in get
    with self._dbm_file(False) as dbm:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/quad/Medusa/ext/dogpile/cache/backends/file.py", line 218, in _dbm_file
    dbm = self.dbmmodule.open(self.filename, "w" if write else "r")
  File "/usr/lib/python3.7/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
2020-09-15 06:06:38 INFO	Thread-9 :: [b352bb6] ReleaseGroups: Test
```
</details>

**Additional context**
Medusa runs in an unprivileged LXC container if that's somehow related.  
I've attempted a `pip install -r requirements.txt` in case I was missing some dependencies but that does not seem to have changed anything

**Comment by p0psicles** [comment]
Stop Medusa and remove all the dbm files in cache folder. And start.
