### ISSUE TITLE
[APP SUBMITTED]: TypeError: expected bytes-like object, not str

### ISSUE THREAD

**Issue by ssafhi** [pymedusa/Medusa#8506]
### INFO
**Python Version**: `3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]`
**Operating System**: `Linux-5.8.3-050803-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/d7d67a26ea15421451e1c94ac3d2e80f
### ERROR
<pre>
2020-09-17 08:34:15 ERROR    TORNADO :: [b352bb6] Uncaught exception in APIv2: TypeError('expected bytes-like object, not str')
Request: GET /**********/medusa/api/v2/series?limit=1000&page=1 (127.0.0.1)
Traceback (most recent call last):
  File "/usr/lib/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/**********/.medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/**********/.medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/**********/.medusa/ext/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/**********/.medusa/medusa/server/api/v2/base.py", line 57, in async_call
    content = self._check_authentication()
  File "/home/**********/.medusa/medusa/server/api/v2/base.py", line 130, in _check_authentication
    auth_decoded = base64.decodestring(authorization[6:])
  File "/usr/lib/python3.8/base64.py", line 554, in decodestring
    return decodebytes(s)
  File "/usr/lib/python3.8/base64.py", line 545, in decodebytes
    _input_type_check(s)
  File "/usr/lib/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed in develop with: https://github.com/pymedusa/Medusa/pull/8607
