### ISSUE TITLE
[APP SUBMITTED]: UnicodeDecodeError: 'utf8' codec can't decode bytes in position 92-93: invalid continuation byte

### ISSUE THREAD

**Issue by bluelavalamp** [pymedusa/Medusa#8529]
### INFO
**Python Version**: `2.7.15 (default, Jun 17 2018, 22:57:51) [GCC 7.3.0]`
**Operating System**: `Linux-5.1.4-x86_64-Intel-R-_Core-TM-_i5-9600K_CPU_@_3.70GHz-with-slackware-14.2`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/9c74b5f911f5ed81a69d33895245c186
### ERROR
<pre>
2020-09-24 22:36:34 ERROR    POSTPROCESSOR :: [b352bb6] Exception generated: 'utf8' codec can't decode bytes in position 92-93: invalid continuation byte
Traceback (most recent call last):
  File "/opt/Medusa-master/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/scheduler.py#L78">medusa/scheduler.py</a>", line 78, in run
    self.action.run(self.force)
  File "/opt/Medusa-master/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/process_tv.py#L65">medusa/process_tv.py</a>", line 65, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/opt/Medusa-master/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/process_tv.py#L169">medusa/process_tv.py</a>", line 169, in process
    if not self.should_process(path, failed):
  File "/opt/Medusa-master/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/process_tv.py#L257">medusa/process_tv.py</a>", line 257, in should_process
    for root, dirs, files in os.walk(path):
  File "/usr/lib64/python2.7/os.py", line 278, in walk
    names = listdir(top)
  File "/opt/Medusa-master/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/init/filesystem.py#L112">medusa/init/filesystem.py</a>", line 112, in patched_output
    return handle_output(f(*args, **kwargs))
  File "/opt/Medusa-master/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/init/filesystem.py#L49">medusa/init/filesystem.py</a>", line 49, in _handle_output_u
    return list(map(_handle_output_u, result))
  File "/opt/Medusa-master/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/init/filesystem.py#L46">medusa/init/filesystem.py</a>", line 46, in _handle_output_u
    return decode(result)
  File "/opt/Medusa-master/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/init/filesystem.py#L32">medusa/init/filesystem.py</a>", line 32, in decode
    return text_type(value, fs_encoding if valid_encoding else 'utf-8')
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 92-93: invalid continuation byte
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Switch to Python 3: https://github.com/pymedusa/Medusa/wiki/Switch-to-Python-3
