### ISSUE TITLE
HTTPS redirecting

### ISSUE THREAD

**Issue by Vince0511** [pymedusa/Medusa#8666]
Hello, I've install Medusa on Ubuntu 20.04 (server) and loving it! Really!
The webUI is available on my <internal.ip>:8081. Very nice.
I even created an forwarder (series.mydomain.com). With an simple Apache virtual host. Still working as a charm.
Then I added an SSL-certificate (with certbot on letsencrypt.org) now my https://series.mydomain.com is working, but medusa doenst like it. 
It said: 
Loading…
If this is taking too long,
click here to show the page.

The page isn't loading nor I can't click the link.
I'm I doing something wrong here? Do I need some configuration in Medusa that I've missed? Help would be apriciated.

**Comment by p0psicles** [comment]
https://github.com/pymedusa/Medusa/wiki/Reverse-Proxy-setup

**Comment by Vince0511** [comment]
Wow, that worked like a charm, thank you for the quick response. (i'm a little new to GitHub and searching the Wiki.)
After following the steps as described I get an error. "Error connecting to Websocket".
I'm using Apache2, and did some testing with the .conf. Am I missing something?
My /etc/apache2/sites-available/url-to-medusa.domain.com-le-ssl.conf is as followed:

```
<VirtualHost *:443>
    LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
    LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so
    LoadModule proxy_wstunnel_module /usr/lib/apache2/modules/mod_proxy_wstunnel.so
    LoadModule ssl_module modules/mod_ssl.so
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyRequests Off

    # make sure we keep communicating over https
    RequestHeader set X-Forwarded-Proto "https" env=HTTPS

    ProxyRequests On
    ProxyPreserveHost Off
    ServerName url-to-medusa.domain.com

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/url-to-medusa.domain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/url-to-medusa.domain.com/privkey.pem

    # Medusa proxy config
    ProxyPass / http://localhost:8081/

    # websockets
    ProxyPassReverse /medusa/ws wss://127.0.0.1:8081/medusa/ws
    ProxyPassReverseCookieDomain 127.0.0.1 %{HTTP:Host}

    # if you receive an error 400 (seen using at least Server version: Apache/2.4.33),
    # uncomment RewriteEngine, RewriteCond, RewriteRule below, and comment out the ProxyPass and
    # ProxyPassReverse statements above for the ws: urls

    #RewriteEngine On

    # When Upgrade:websocket header is present, redirect to ws
    # Using NC flag (case-insensitive) as some browsers will pass Websocket
    #RewriteCond %{HTTP:Upgrade} =websocket [NC]
    #RewriteRule ^/ws/(.*)    ws://127.0.0.1:5051/ws/$1 [P,L]

    # webserver
    ProxyPass /medusa http://localhost:8081/medusa keepalive=On timeout=600 retry=1 acquire=3000
    ProxyPassReverse /medusa http://localhost:8081/medusa

        # just some logging
    CustomLog /var/log/apache2/proxy-access.log combined
    ErrorLog /var/log/apache2/proxy-error.log
</VirtualHost>
```
Again, I'm fairly new to GitHub, if this is the wrong place to ask this question, please let me know.
Thanks in advance.

**Comment by medariox** [comment]
```
    # if you receive an error 400 (seen using at least Server version: Apache/2.4.33),
    # uncomment RewriteEngine, RewriteCond, RewriteRule below, and comment out the ProxyPass and
    # ProxyPassReverse statements above for the ws: urls

    #RewriteEngine On

    # When Upgrade:websocket header is present, redirect to ws
    # Using NC flag (case-insensitive) as some browsers will pass Websocket
    #RewriteCond %{HTTP:Upgrade} =websocket [NC]
    #RewriteRule ^/ws/(.*)    ws://127.0.0.1:5051/ws/$1 [P,L]
```


Did you try that?

**Comment by Vince0511** [comment]
> ```
> Did you try that?

Yes, I did. It doesn't make any different.

**Comment by p0psicles** [comment]
What does your config look like now?

**Comment by Vince0511** [comment]
I've tried starting over, but I broke more than I fixed.
My /opt/medusa/config.ini
```
[General]
git_auth_type = 0
git_username = *********
git_password = ********
git_token = ""
git_reset = 1
git_reset_branches = develop, master
branch = master
git_remote = origin
git_remote_url = https://github.com/pymedusa/Medusa
cur_commit_hash = b352bb6924afcdfafce176a540d53ce405ca1312
cur_commit_branch = ""
config_version = 10
encryption_version = 0
encryption_secret = "b'frpEFX7eR0ujXvsHMT5gm/BuG35Z2EWDpu3a3Wtai6U='"
log_dir = Logs
log_nr = 5
log_size = 10.0
socket_timeout = 30
web_port = 8081
web_host = 0.0.0.0
web_ipv6 = 0
web_log = 0
web_root = <mydomainname>
web_username = *******
web_password = *********
web_cookie_secret = "b'phSeP76bRBiLR08zTIfafLfGVd1nC0+8hw7UHu4JLpw='"
web_use_gzip = 1
subliminal_log = 0
privacy_level = normal
ssl_verify = 1
ssl_ca_bundle = ""
download_url = ""
localhost_ip = ""
cpu_preset = NORMAL
anon_redirect = http://dereferer.org/?
api_key = d873d86e5d44a598c0f1c22fd2d955af
debug = 1
dbdebug = 0
default_page = home
seeders_leechers_in_notify = 1
enable_https = 0
notify_on_login = 0
https_cert = /etc/letsencrypt/live/<mydomainname>/fullchain.pem
https_key = /etc/letsencrypt/live/<mydomainname>/privkey.pem
handle_reverse_proxy = 1
use_nzbs = 1
use_torrents = 1
nzb_method = nzbget
torrent_method = qbittorrent
usenet_retention = 1800
cache_trimming = 0
max_cache_age = 30
autopostprocessor_frequency = 10
torrent_checker_frequency = 60
dailysearch_frequency = 40
backlog_frequency = 720
update_frequency = 1
showupdate_hour = 3
download_propers = 1
propers_search_days = 2
remove_from_client = 0
randomize_providers = 1
check_propers_interval = 4h
allow_high_priority = 1
skip_removed_files = 0
allowed_extensions = srt, nfo, sub, idx
quality_default = 328
status_default = 5
status_default_after = 3
flatten_folders_default = 0
indexer_default = 0
indexer_timeout = 20
tvdb_dvd_order_ep_ignore = 0
anime_default = 0
scene_default = 0
provider_order = limetorrents, eztv, rarbg, binsearch, abnormal, alpharatio, anidex, animetorrents, archetorrent, avistaz, beyond_hd, bithd>
version_notify = 1
auto_update = 0
notify_on_update = 1
naming_strip_year = 0
naming_pattern = Season %0S/%SN - S%0SE%0E - %EN
naming_custom_abd = 0
naming_abd_pattern = %SN - %A.D - %EN
naming_custom_sports = 0
naming_sports_pattern = %SN - %A-D - %EN
naming_custom_anime = 0
naming_anime_pattern = Season %0S/%SN - S%0SE%0E - %EN
naming_multi_ep = 1
naming_anime_multi_ep = 1
naming_anime = 3
indexerDefaultLang = en
ep_default_deleted_status = 6
launch_browser = 1
trash_remove_show = 0
trash_rotate_logs = 0
sort_article = 0
proxy_setting = ""
proxy_indexers = 1
use_listview = 0
metadata_kodi = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_kodi_12plus = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_mediabrowser = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_ps3 = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_wdtv = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_tivo = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
metadata_mede8er = 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
backlog_days = 7
cache_dir = cache
root_dirs = 0, <my-tv-dir>, <my-movie-dir>
tv_download_dir = <my-download-dir>
keep_processed_dir = 1
process_method = move
del_rar_contents = 0
move_associated_files = 0
sync_files = !sync, lftp-pget-status, part, bts, !qb, !qB
postpone_if_sync_files = 1
postpone_if_no_subs = 0
nfo_rename = 1
process_automatically = 1
no_delete = 0
unpack = 0
rename_episodes = 0
airdate_episodes = 0
file_timestamp_timezone = network
create_missing_show_dirs = 0
add_shows_wo_dir = 0
extra_scripts = ,
git_path = ""
ignore_words = german, french, core2hd, swedish, reenc, MrLss, dubbed
preferred_words = ,
undesired_words = internal, xvid
trackers_list = udp://tracker.coppersurfer.tk:6969/announce, udp://tracker.leechers-paradise.org:6969/announce, udp://tracker.zer0day.to:13>
require_words = ,
ignored_subs_list = dk, fin, heb, kor, nor, nordic, pl, swe
ignore_und_subs = 0
calendar_unprotected = 0
calendar_icons = 0
no_restart = 0
developer = 0
python_version = 3, 8, 5
news_last_read = 1970-01-01
broken_providers = "",
selected_root = -1
backlog_period = all
backlog_status = all
fallback_plex_enable = 0
fallback_plex_notifications = 0
fallback_plex_timeout = 3

```
My /etc/apache2/sites-available/<mydomainname>-le-ssl.conf

```
<VirtualHost *:443>
    LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
    LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so
    LoadModule proxy_wstunnel_module /usr/lib/apache2/modules/mod_proxy_wstunnel.so
    LoadModule ssl_module modules/mod_ssl.so
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyRequests Off

    # make sure we keep communicating over https
    RequestHeader set X-Forwarded-Proto "https" env=HTTPS

    ProxyRequests On
    ProxyPreserveHost Off
    ServerName <mydomainname>

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/<mydomainname>/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/<mydomainname>/privkey.pem

    # Medusa proxy config
    ProxyPass /medusa/ws wss://127.0.0.1:8081/medusa/ws keepalive=On timeout=600 retry=1 acquire=3000

    # websockets
    ProxyPassReverse /medusa/ws ws://127.0.0.1:8081/medusa/ws
    ProxyPassReverseCookieDomain 127.0.0.1 %{HTTP:Host}

    # if you receive an error 400 (seen using at least Server version: Apache/2.4.33),
    # uncomment RewriteEngine, RewriteCond, RewriteRule below, and comment out the ProxyPass and
    # ProxyPassReverse statements above for the ws: urls

    #RewriteEngine On

    # When Upgrade:websocket header is present, redirect to ws
    # Using NC flag (case-insensitive) as some browsers will pass Websocket
    #RewriteCond %{HTTP:Upgrade} =websocket [NC]
    #RewriteRule ^/ws/(.*)    ws://127.0.0.1:5051/ws/$1 [P,L]

    # webserver
    ProxyPass /medusa https://localhost:8081/medusa keepalive=On timeout=600 retry=1 acquire=3000
    ProxyPassReverse /medusa https://localhost:8081/medusa

        # just some logging
    CustomLog /var/log/apache2/proxy-access.log combined
    ErrorLog /var/log/apache2/proxy-error.log
</VirtualHost>

```
And if it's any help... My  /etc/apache2/sites-available/<mydomainname>.conf

```
<VirtualHost *:80>
   ServerName <mydomainname>
   ErrorDocument 404 /404.html

   #HTTP proxy
   ProxyPass / http://localhost:8081/
   ProxyPassReverse / http://localhost:8081/

   #Websocket proxy
   #SSLProxyEngine on
   <Location /:/websockets/notifications>
        ProxyPass wss://localhost:8081/:/websockets/notifications
        ProxyPassReverse wss://localhost:8081/:/websockets/notifications
   </Location>

   Header always unset X-Frame-Options
RewriteEngine on
RewriteCond %{SERVER_NAME} =<mydomainname>
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

**Comment by Vince0511** [comment]
I think I've messed it up even more.
When I try to open medusa the page says:
```
Traceback (most recent call last):
  File "/opt/medusa/ext/tornado/web.py", line 1569, in _execute
    result = self.prepare()
  File "/opt/medusa/ext/tornado/web.py", line 2322, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
```
I disabled my apache virutual hosts, so I can resolve my config.ini problems first.
Is there a default config.ini to review with mine?

**Comment by p0psicles** [comment]
Just clone from GitHub in a new folder. And start. Or delete the config.ini. it's generated at start

**Comment by Vince0511** [comment]
>Or delete the config.ini. it's generated at start
I've deleted my config.ini and restarted ubuntu.
It worked, the settings are gone, but at least all my series are still there.

Thank you!

**Comment by Vince0511** [comment]
Actually. I've got it all working again. 
Medusa is working local on http://<local.ip.addr>:8081 and external om https://<mydomainname>with certificate and no errors.
Found some extra help in https://github.com/pymedusa/Medusa/issues/5382
