### ISSUE TITLE
[APP SUBMITTED]: AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by MaMoUs10** [pymedusa/Medusa#8674]
### INFO
**Python Version**: `3.7.8 (default, Aug  2 2020, 15:41:25) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.58-gentoo-whatbox-x86_64-AMD_EPYC_7702P_64-Core_Processor-with-gentoo-2.7`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/26e7571ca8300bfe80d3ea943135f1de
### ERROR
<pre>
2020-10-31 23:30:50 ERROR    FORCEDSEARCHQUEUE-BACKLOG-260586 :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/mnt/mpathae/**********/Medusa/medusa/providers/torrent/html/iptorrents.py", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by bootman2222** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]`
**Operating System**: `Linux-4.19.107-Unraid-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/d896c12dd4807a03fbb2df94eafbbab0
### ERROR
<pre>
2020-11-01 08:13:20 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/medusa/providers/torrent/html/iptorrents.py", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `3.8.5 (default, Aug  2 2020, 15:09:07) [GCC 9.3.0]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@29b4fe56fade07e4871bcc4f451fa3878e8160e0
**Link to Log**: https://gist.github.com/160db6e2cae814a1515f891ea5f7f8d8
### ERROR
<pre>
2020-11-01 10:04:48 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [29b4fe5] Failed parsing provider.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/29b4fe56fade07e4871bcc4f451fa3878e8160e0/medusa/providers/torrent/html/iptorrents.py#L116">medusa/providers/torrent/html/iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by pax0707** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]`
**Operating System**: `Linux-5.4.72-v7l+-armv7l-with-debian-10.6`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/20ecf144dfeb9dddd51413a3f535b79f
### ERROR
<pre>
2020-11-01 14:29:23 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/providers/torrent/html/iptorrents.py#L116">medusa/providers/torrent/html/iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Fixed with https://github.com/pymedusa/Medusa/pull/8675

**Comment by whipcracker** [comment]
### INFO
**Python Version**: `3.5.3 (default, Jul  9 2020, 13:00:10) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.19.123-feral-x86_64-with-debian-9.13`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/52548e5ccc9ac74f1fbda51bd4f1b9a9
### ERROR
<pre>
2020-11-01 23:13:56 ERROR    FORCEDSEARCHQUEUE-MANUAL-4395 :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/media/sdq1/**********/.sickrage/medusa/providers/torrent/html/iptorrents.py", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by madtempest** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-52-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/10627a6d88f98572e522ab3dd0db7ba5
### ERROR
<pre>
2020-11-02 07:29:15 ERROR    FORCEDSEARCHQUEUE-MANUAL-110381 :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/providers/torrent/html/iptorrents.py#L116">medusa/providers/torrent/html/iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by computerbox34** [comment]
### INFO
**Python Version**: `3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]`
**Operating System**: `Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-centos-7.7.1908-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/be31434b2f3afdfe2ee3aa32f0945b55
### ERROR
<pre>
2020-11-01 21:23:19 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/providers/torrent/html/iptorrents.py#L116">medusa/providers/torrent/html/iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by computerbox34** [comment]
### INFO
**Python Version**: `3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]`
**Operating System**: `Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-centos-7.7.1908-Core`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/519ebca971e71cf386fa69ccac255aa4
### ERROR
<pre>
2020-11-01 21:43:27 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/providers/torrent/html/iptorrents.py#L116">medusa/providers/torrent/html/iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by cilise** [comment]
### INFO
**Python Version**: `3.5.3 (default, Jul  9 2020, 13:00:10) [GCC 6.3.0 20170516]`
**Operating System**: `Linux-4.9.0-12-amd64-x86_64-with-debian-9.13`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/acd65b3fbb94b967d598a788fb1334be
### ERROR
<pre>
2020-11-02 03:00:56 ERROR    FORCEDSEARCHQUEUE-MANUAL-384494 :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/providers/torrent/html/iptorrents.py#L116">medusa/providers/torrent/html/iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Rouzax** [comment]
### INFO
**Python Version**: `3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.17763-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-11-02 13:24:32 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "C:\GitHub\Medusa\<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/providers/torrent/html/iptorrents.py#L116">medusa\providers\torrent\html\iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by thomeboy** [comment]
### INFO
**Python Version**: `3.8.2 (default, Sep 20 2020, 02:55:09) [GCC 7.5.0]`
**Operating System**: `Linux-4.19-ovh-xxxx-std-ipv6-64-x86_64-with-glibc2.27`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/93c76f02926480d831339d74a6bcae5d
### ERROR
<pre>
2020-11-02 13:09:35 ERROR    FORCEDSEARCHQUEUE-MANUAL-290853 :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/home/**********/.medusa/medusa/providers/torrent/html/iptorrents.py", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by BMoney4Fininng** [comment]
### INFO
**Python Version**: `3.8.5 (default, Sep 11 2020, 06:40:00) [GCC 8.4.0]`
**Operating System**: `Linux-3.4.6-armv5tel-with-glibc2.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/32fa50f6aa95fca2177a547d43b4f6f7
### ERROR
<pre>
2020-11-02 16:44:05 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/providers/torrent/html/iptorrents.py#L116">medusa/providers/torrent/html/iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by BMoney4Fininng** [comment]
### INFO
**Python Version**: `3.8.5 (default, Sep 11 2020, 06:40:00) [GCC 8.4.0]`
**Operating System**: `Linux-3.4.6-armv5tel-with-glibc2.4`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@b352bb6924afcdfafce176a540d53ce405ca1312
**Link to Log**: https://gist.github.com/bc9e273eac310dc4eecb185a99c921e2
### ERROR
<pre>
2020-11-02 20:43:46 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [b352bb6] Failed parsing provider.
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/OMedusa/OMedusa/<a href="../blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/providers/torrent/html/iptorrents.py#L116">medusa/providers/torrent/html/iptorrents.py</a>", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ztaale** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-4.15.0-118-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.16`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/abb0f04a1958bc348bd821df7fdb6f6f
### ERROR
<pre>
2020-11-03 10:08:59 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: [] Failed parsing provider.
Traceback (most recent call last):
  File "/app/medusa/medusa/providers/torrent/html/iptorrents.py", line 116, in parse
    seeders = int(row.find('td', attrs={'class': 'ac t_seeders'}).text)
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
### INFO
**Python Version**: `3.8.6 (default, Nov 20 2020, 23:57:10) [Clang 12.0.0 (clang-1200.0.32.27)]`
**Operating System**: `macOS-11.1-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [feature/add-fdh](../tree/feature/add-fdh)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@a4f101ca941f127534ff109796999aae1987fbb9
**Link to Log**: https://gist.github.com/92e8efb8d5852d15d932856c15726c05
### ERROR
<pre>
2021-01-12 11:28:37 ERROR    DOWNLOADHANDLER :: [a4f101c] qBittorrent: Unable to get API version. Error: AttributeError("'NoneType' object has no attribute 'text'")
Traceback (most recent call last):
AttributeError: 'NoneType' object has no attribute 'text'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
