### ISSUE TITLE
Snatch failed

### ISSUE THREAD

**Issue by benoitnsm** [pymedusa/Medusa#8702]
**Describe the bug**

Snatch an episode is failing, both manually or with forced search.

2020-11-07 12:50:07 ERROR    SNATCHQUEUE-SNATCH-80 :: [552f119] Snatch failed! For result: Modern.Family.S11E15.VOSTFR.1080p.web.h264-insidious
Traceback (most recent call last):
  File "/home7/**********/software/Medusa/medusa/search/queue.py", line 497, in run
    self.success = snatch_episode(result)
  File "/home7/**********/software/Medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/home7/**********/software/Medusa/medusa/clients/torrent/generic.py", line 239, in send_torrent
    if not self._get_auth():
  File "/home7/**********/software/Medusa/medusa/clients/torrent/rtorrent.py", line 53, in _get_auth
    self.auth = RTorrent(self.host, self.username, self.password, True, tp_kwargs=tp_kwargs)
  File "/home7/**********/software/Medusa/lib/rtorrent/__init__.py", line 75, in __init__
    raise NotImplementedError()
NotImplementedError

**To Reproduce**

Go to a show select an episode and launch a search.

**Medusa (please complete the following information):**

Branch: master
Commit: 552f1199853dfce905f9ba6e27194da67070ea6a
Version: 0.4.4
Database: 44.17

Python version : 2.7.12 (default, Apr 15 2020, 17:07:12) [GCC 5.4.0 20160609]
OS : Linux-4.15.18-seedhost-x86_64-with-Ubuntu-16.04-xenial

**Comment by medariox** [comment]
Add the host like in the example and it will work.

**Comment by benoitnsm** [comment]
Hello, where can I add the host ?

**Comment by medariox** [comment]
![screen](https://snapr.pw/i/35a3025421.png)

Add host:port like in the example below.

**Comment by benoitnsm** [comment]
Thanks
