### ISSUE TITLE
[APP SUBMITTED]: deluge.error.AddTorrentError: Torrent already in session (5af4170369ba4f1c52a0b700ce1c8257d3bef8aa).

### ISSUE THREAD

**Issue by zaans2** [pymedusa/Medusa#8705]
### INFO
**Python Version**: `3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]`
**Operating System**: `Linux-5.4.0-52-generic-x86_64-with-Ubuntu-18.04-bionic`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@552f1199853dfce905f9ba6e27194da67070ea6a
**Link to Log**: https://gist.github.com/bfe779e7e8053c62b9e4d34de591dddf
### ERROR
<pre>
2020-11-08 15:24:38 ERROR    SNATCHQUEUE-SNATCH-164541 :: [552f119] DelugeD: Failed Sending Torrent
Traceback (most recent call last):
  File "/opt/**********/**********/clients/torrent/generic.py", line 254, in send_torrent
    r_code = self._add_torrent_uri(result)
  File "/opt/**********/**********/clients/torrent/deluged.py", line 68, in _add_torrent_uri
    remote_torrent = self.drpc.add_torrent_magnet(result.url, options, result.hash)
  File "/opt/**********/**********/clients/torrent/deluged.py", line 268, in add_torrent_magnet
    torrent_id = self.client.core.add_torrent_magnet(torrent, options)
  File "/opt/**********/ext/deluge_client/client.py", line 290, in __call__
    return self.caller(self.method, *args, **kwargs)
  File "/opt/**********/ext/deluge_client/client.py", line 253, in call
    return self._receive_response(self.deluge_version, self.deluge_protocol_version)
  File "/opt/**********/ext/deluge_client/client.py", line 232, in _receive_response
    raise exception(exception_msg)
deluge_client.client.AddTorrentError: Torrent already in session (5af4170369ba4f1c52a0b700ce1c8257d3bef8aa).
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/core/rpcserver.py", line 326, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/deluge/core/core.py", line 571, in add_torrent_magnet
    return self.torrentmanager.add(magnet=uri, options=options)
  File "/usr/lib/python3/dist-packages/deluge/core/torrentmanager.py", line 537, in add
    torrent_info, magnet, options, resume_data
  File "/usr/lib/python3/dist-packages/deluge/core/torrentmanager.py", line 446, in _build_torrent_params
    raise AddTorrentError('Torrent already in session (%s).' % torrent_id)
deluge.error.AddTorrentError: Torrent already in session (5af4170369ba4f1c52a0b700ce1c8257d3bef8aa).

</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by zaans2** [comment]
BTW, I know that it throws an error because the torrent it is trying to add is already in the queue, however this used to be a warning and not an error.

Not sure what is better, but now every time I see that red circle in the top right I freak out and then find out it is nothing serious.
