### ISSUE TITLE
[APP SUBMITTED]: dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db

### ISSUE THREAD

**Issue by akosasante** [pymedusa/Medusa#8759]
### INFO
**Python Version**: `3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.18362-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@f39927ea6f0b3d18856dce32d86af43d57713720
**Link to Log**: **No Log available**
### ERROR
<pre>
2020-11-21 20:37:09 ERROR    Thread_1 :: [f39927e] Exception generated: db file doesn't exist; use 'c' or 'n' flag to create a new db
Traceback (most recent call last):
  File "D:\Medusa\Medusa\<a href="../blob/f39927ea6f0b3d18856dce32d86af43d57713720/**********/server/web/core/base.py#L252">**********\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "D:\Medusa\Medusa\<a href="../blob/f39927ea6f0b3d18856dce32d86af43d57713720/**********/server/web/home/handler.py#L1640">**********\server\web\home\handler.py</a>", line 1640, in manualSearchSubtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "D:\Medusa\Medusa\<a href="../blob/f39927ea6f0b3d18856dce32d86af43d57713720/**********/subtitles.py#L342">**********\subtitles.py</a>", line 342, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "D:\Medusa\Medusa\<a href="../blob/f39927ea6f0b3d18856dce32d86af43d57713720/ext/dogpile/cache/region.py#L1112">ext\dogpile\cache\region.py</a>", line 1112, in set
    self.backend.set(key, self._value(value))
  File "D:\Medusa\Medusa\<a href="../blob/f39927ea6f0b3d18856dce32d86af43d57713720/ext/dogpile/cache/backends/file.py#L240">ext\dogpile\cache\backends\file.py</a>", line 240, in set
    with self._dbm_file(True) as dbm:
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "D:\Medusa\Medusa\<a href="../blob/f39927ea6f0b3d18856dce32d86af43d57713720/ext/dogpile/cache/backends/file.py#L218">ext\dogpile\cache\backends\file.py</a>", line 218, in _dbm_file
    dbm = self.dbmmodule.open(self.filename, "w" if write else "r")
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python38\lib\dbm\__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
You removed the dbm files while running medusa. Just restart
