### ISSUE TITLE
[APP SUBMITTED]: ImportError: no dbm clone found; tried ['dbm.gnu', 'dbm.ndbm', 'dbm.dumb']

### ISSUE THREAD

**Issue by dirkronsmans** [pymedusa/Medusa#8780]
### INFO
**Python Version**: `3.5.1 (default, Jan 29 2018, 14:18:59) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-4.4.59+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@e6025de42a034b5887e5806fda210e30f5a1e150
**Link to Log**: https://gist.github.com/86cc08a5cf4a619abb8b69f3fd90a46e
### ERROR
<pre>
2020-11-28 20:21:04 ERROR    Thread-18 :: [e6025de] Exception generated: no dbm clone found; tried ['dbm.gnu', 'dbm.ndbm', 'dbm.dumb']
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/e6025de42a034b5887e5806fda210e30f5a1e150/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/e6025de42a034b5887e5806fda210e30f5a1e150/medusa/server/web/home/handler.py#L1639">medusa/server/web/home/handler.py</a>", line 1639, in manualSearchSubtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/e6025de42a034b5887e5806fda210e30f5a1e150/medusa/subtitles.py#L342">medusa/subtitles.py</a>", line 342, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/e6025de42a034b5887e5806fda210e30f5a1e150/ext/dogpile/cache/region.py#L1112">ext/dogpile/cache/region.py</a>", line 1112, in set
    self.backend.set(key, self._value(value))
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/e6025de42a034b5887e5806fda210e30f5a1e150/ext/dogpile/cache/backends/file.py#L240">ext/dogpile/cache/backends/file.py</a>", line 240, in set
    with self._dbm_file(True) as dbm:
  File "/usr/local/lib/python3.5/contextlib.py", line 59, in __enter__
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/e6025de42a034b5887e5806fda210e30f5a1e150/ext/dogpile/cache/backends/file.py#L218">ext/dogpile/cache/backends/file.py</a>", line 218, in _dbm_file
    dbm = self.dbmmodule.open(self.filename, "w" if write else "r")
  File "/usr/local/lib/python3.5/dbm/__init__.py", line 75, in open
ImportError: no dbm clone found; tried ['dbm.gnu', 'dbm.ndbm', 'dbm.dumb']
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Try upgrading python to 3.6 or higher

**Comment by dirkronsmans** [comment]
That's pretty strange. I'm on synology and have both the official and synocommunity package of python 3 installed.
both are above 3.5.

SynoCommunity: 3.7.7-15
Official (python foundation): 3.8.2-0150

Guess I'll do a backup, uninstall all and restore my backup. Packages seem to be messing up.
Any suggestion on what python package to use on synology?
