### ISSUE TITLE
Season Pack manual search broken

### ISSUE THREAD

**Issue by Rouzax** [pymedusa/Medusa#8802]
**Describe the bug**
When I initiate a new Season Pack manual search with I get these errors in the debug log and nothing actually happens in the GUI.

```
2020-11-30 17:33:41 INFO     FORCEDSEARCHQUEUE-MANUAL-269613 :: [e6025de] Beginning manual season pack search for: Fargo - S04E01 - Welcome to the Alternate Economy
2020-11-30 17:33:41 INFO     FORCEDSEARCHQUEUE-MANUAL-269613 :: [e6025de] Updating exception_cache and exception_season_cache
2020-11-30 17:33:41 INFO     FORCEDSEARCHQUEUE-MANUAL-269613 :: [e6025de] Finished processing 3449 scene exceptions.
2020-11-30 17:33:41 INFO     FORCEDSEARCHQUEUE-MANUAL-269613 :: [e6025de] Building internal name cache for Fargo
2020-11-30 17:33:41 DEBUG    FORCEDSEARCHQUEUE-MANUAL-269613 :: [e6025de] Internal name cache for fargo set to: fargo
2020-11-30 17:33:41 INFO     FORCEDSEARCHQUEUE-MANUAL-269613 :: [e6025de] Using manual search providers
2020-11-30 17:33:41 INFO     FORCEDSEARCHQUEUE-MANUAL-269613 :: [Rarbg] :: [e6025de] Performing season pack search for Fargo
2020-11-30 17:33:41 DEBUG    FORCEDSEARCHQUEUE-MANUAL-269613 :: [Rarbg] :: [e6025de] Could not find all candidates in cache, searching provider.
2020-11-30 17:33:41 DEBUG    FORCEDSEARCHQUEUE-MANUAL-269613 :: [Rarbg] :: [e6025de] Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\search\queue.py", line 385, in run
    search_result = search_providers(self.show, self.segment, forced_search=True, down_cur_quality=True,
  File "C:\GitHub\Medusa\medusa\search\core.py", line 714, in search_providers
    search_results = cur_provider.find_search_results(series_obj, needed_eps, search_mode, forced_search,
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 239, in find_search_results
    search_strings = self._get_season_search_strings(episode)
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 662, in _get_season_search_strings
    templated_episode_string = episode_string + season_template.format(season=episode.scene_season)
TypeError: unsupported format string passed to NoneType.__format__

2020-11-30 17:34:43 DEBUG    APIv2-Thread_3 :: [e6025de] Item already in the queue, skipping
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Matched release C:\DATA\TVSeries\Dash & Lily\Season 01\Dash & Lily - S01E01 - [1080p WEB h264][STRONTiUM] to a series in your database: Dash & Lily
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Parsed C:\DATA\TVSeries\Dash & Lily\Season 01\Dash & Lily - S01E01 - [1080p WEB h264][STRONTiUM] into title: Dash & Lily, season: 1, episode: [1], screen_size: 1080p, source: Web, video_codec: H.264, release_group: STRONTiUM, type: episode, parsing_time: 0.07956433296203613, absolute_episode: [], quality: 1080p WEB-DL, total_time: 0.07956433296203613
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Matched release Dash.and.Lily.S01E01.1080p.WEB.H264-STRONTiUM to a series in your database: Dash & Lily
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Parsed Dash.and.Lily.S01E01.1080p.WEB.H264-STRONTiUM into title: Dash and Lily, season: 1, episode: [1], screen_size: 1080p, source: Web, video_codec: H.264, release_group: STRONTiUM, type: episode, parsing_time: 0.025409936904907227, absolute_episode: [], quality: 1080p WEB-DL, total_time: 0.025409936904907227
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Found codec for Dash & Lily Dash
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] 371940: Formatting pattern: %SN - S%0SE01 - %EN -> Dash & Lily - S01E01 - Dash
2020-11-30 17:34:44 INFO     FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Beginning manual season pack search for: Dash & Lily - S01E01 - Dash
2020-11-30 17:34:44 INFO     FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Updating exception_cache and exception_season_cache
2020-11-30 17:34:44 INFO     FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Finished processing 3449 scene exceptions.
2020-11-30 17:34:44 INFO     FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Building internal name cache for Dash & Lily
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Internal name cache for dash and lily set to: dash and lily
2020-11-30 17:34:44 INFO     FORCEDSEARCHQUEUE-MANUAL-371940 :: [e6025de] Using manual search providers
2020-11-30 17:34:44 INFO     FORCEDSEARCHQUEUE-MANUAL-371940 :: [PrivateHD-Jackett] :: [e6025de] Performing season pack search for Dash & Lily
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [PrivateHD-Jackett] :: [e6025de] Could not find all candidates in cache, searching provider.
2020-11-30 17:34:44 DEBUG    FORCEDSEARCHQUEUE-MANUAL-371940 :: [PrivateHD-Jackett] :: [e6025de] Traceback (most recent call last):
  File "C:\GitHub\Medusa\medusa\search\queue.py", line 385, in run
    search_result = search_providers(self.show, self.segment, forced_search=True, down_cur_quality=True,
  File "C:\GitHub\Medusa\medusa\search\core.py", line 714, in search_providers
    search_results = cur_provider.find_search_results(series_obj, needed_eps, search_mode, forced_search,
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 239, in find_search_results
    search_strings = self._get_season_search_strings(episode)
  File "C:\GitHub\Medusa\medusa\providers\generic_provider.py", line 662, in _get_season_search_strings
    templated_episode_string = episode_string + season_template.format(season=episode.scene_season)
TypeError: unsupported format string passed to NoneType.__format__

```
![image](https://user-images.githubusercontent.com/4103090/100637123-cd427c80-3332-11eb-9c80-c7cf496aafe5.png)

Medusa Info: | Branch:                 master                  Commit:                 e6025de42a034b5887e5806fda210e30f5a1e150                  Version:                 .0.4.6                  Database:                 44.17
-- | --
Python Version: | 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.1g  21 Apr 2020
OS: | Windows-10-10.0.17763-SP0
Locale: | nl_NL.cp1252

Could this be related to: https://github.com/pymedusa/Medusa/issues/8670

**Comment by p0psicles** [comment]
That's fixed in develop
