### ISSUE TITLE
v.0.5.0. SyntaxError: invalid syntax starting up

### ISSUE THREAD

**Issue by macTh3Knif3** [pymedusa/Medusa#8808]
Getting syntax error in the latest release (0.5.0). 
Running on raspberry pi 3 on ubuntu

/usr/bin/python3 /opt/medusa/start.py -q --datadir=/opt/medusa/

Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/opt/medusa/medusa/naming.py", line 27, in <module>
    from medusa.tv import Episode, Series
  File "/opt/medusa/medusa/tv/__init__.py", line 6, in <module>
    from medusa.tv.cache import Cache
  File "/opt/medusa/medusa/tv/cache.py", line 27, in <module>
    from medusa.rss_feeds import getFeed
  File "/opt/medusa/medusa/rss_feeds.py", line 7, in <module>
    from feedparser.api import parse
  File "/opt/medusa/ext/feedparser/__init__.py", line 28, in <module>
    from .api import parse
  File "/opt/medusa/ext/feedparser/api.py", line 37, in <module>
    from . import http
  File "/opt/medusa/ext/feedparser/http.py", line 146
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'
                                                             ^
SyntaxError: invalid syntax

Reverting to 0.4.6 works correctly ... Is there a python lib dependency update ?

**Comment by medariox** [comment]
Since version 0.5.0 Medusa requires Python 3.6.0 or newer. This has been announced many months ago.
