### ISSUE TITLE
Cannot start Medusa following latest Master update - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by whipcracker** [pymedusa/Medusa#8809]
**Describe the bug**
Ever since the latest updates pushed to master in the last 24 hours, I cannot start Medusa and instead get the error code below.

I start Medusa using: python3 ~/.sickrage/SickBeard.py -d

```
Traceback (most recent call last):
  File "/media/sdq1/whipcracker/.sickrage/SickBeard.py", line 6, in <module>
    from medusa.__main__ import main
  File "/media/sdq1/whipcracker/.sickrage/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/media/sdq1/whipcracker/.sickrage/medusa/naming.py", line 27, in <module>
    from medusa.tv import Episode, Series
  File "/media/sdq1/whipcracker/.sickrage/medusa/tv/__init__.py", line 6, in <module>
    from medusa.tv.cache import Cache
  File "/media/sdq1/whipcracker/.sickrage/medusa/tv/cache.py", line 27, in <module>
    from medusa.rss_feeds import getFeed
  File "/media/sdq1/whipcracker/.sickrage/medusa/rss_feeds.py", line 7, in <module>
    from feedparser.api import parse
  File "/media/sdq1/whipcracker/.sickrage/ext/feedparser/__init__.py", line 28, in <module>
    from .api import parse
  File "/media/sdq1/whipcracker/.sickrage/ext/feedparser/api.py", line 37, in <module>
    from . import http
  File "/media/sdq1/whipcracker/.sickrage/ext/feedparser/http.py", line 146
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'
```
                                                             ^
SyntaxError: invalid syntax
**To Reproduce**

I use FeralHosting seedbox which runs on Debian OS on OldStable. The latest version of Python is 3.5 and cannot be updated.

**Expected behavior**

For me to manually start Medusa on the slot, I use this syntax:
```
python3 ~/.sickrage/SickBeard.py -d
```

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Debian
 - Branch: Master AND Develop
 - Commit: Unsure how to tell, seeing I can't get a web interface up and running.
 - Python version: 3.5
 - Database version: Unsure?

**Additional context**

**Comment by fluidsc** [comment]
Identical issue here:

`Traceback (most recent call last):
  File "./SickBeard.py", line 6, in <module>
    from medusa.__main__ import main
  File "/home/fluid/Medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/home/fluid/Medusa/medusa/naming.py", line 27, in <module>
    from medusa.tv import Episode, Series
  File "/home/fluid/Medusa/medusa/tv/__init__.py", line 6, in <module>
    from medusa.tv.cache import Cache
  File "/home/fluid/Medusa/medusa/tv/cache.py", line 27, in <module>
    from medusa.rss_feeds import getFeed
  File "/home/fluid/Medusa/medusa/rss_feeds.py", line 7, in <module>
    from feedparser.api import parse
  File "/home/fluid/Medusa/ext/feedparser/__init__.py", line 28, in <module>
    from .api import parse
  File "/home/fluid/Medusa/ext/feedparser/api.py", line 37, in <module>
    from . import http
  File "/home/fluid/Medusa/ext/feedparser/http.py", line 146
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'                                                             ^SyntaxError: invalid syntax`

**Comment by whipcracker** [comment]
> Identical issue here:
> 
> `Traceback (most recent call last): File "./SickBeard.py", line 6, in <module> from medusa.__main__ import main File "/home/fluid/Medusa/medusa/__main__.py", line 67, in <module> from medusa import ( File "/home/fluid/Medusa/medusa/naming.py", line 27, in <module> from medusa.tv import Episode, Series File "/home/fluid/Medusa/medusa/tv/__init__.py", line 6, in <module> from medusa.tv.cache import Cache File "/home/fluid/Medusa/medusa/tv/cache.py", line 27, in <module> from medusa.rss_feeds import getFeed File "/home/fluid/Medusa/medusa/rss_feeds.py", line 7, in <module> from feedparser.api import parse File "/home/fluid/Medusa/ext/feedparser/__init__.py", line 28, in <module> from .api import parse File "/home/fluid/Medusa/ext/feedparser/api.py", line 37, in <module> from . import http File "/home/fluid/Medusa/ext/feedparser/http.py", line 146 new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}' ^SyntaxError: invalid syntax`

You using FeralHosting or Debian as well?

**Comment by fluidsc** [comment]
Local installation of Debian Stretch. Can't compile Python3.6...i tried. Will try the latest Python tomorrow.

**Comment by p0psicles** [comment]
You can always run it with docker

**Comment by fluidsc** [comment]
Built and installed Python 3.9 and got things working again. No idea why 3.6 wouldn't compile.
