### ISSUE TITLE
Error finding and downloading  spanish subtitles with subtitulamos provider

### ISSUE THREAD

**Issue by porzino** [pymedusa/Medusa#8844]
**Describe the bug**
I can't get spanish subtitles from subtitulamos provider

**To Reproduce**
Get spanish subtitles automatic or manual using subtitulamos provider

**Expected behavior**
I want Medusa to find the subtitle and download like previous versions.

**Medusa (please complete the following information):**
 - OS: DSM 6.2.3-25426 (Synology)
 - Branch: master
 - Commit: ce68da57b3878591f77c21bb2acf28e6a58269fa
 - Python version: 3.7.7 (default, Sep 19 2020, 16:20:36)  [GCC 4.9.3 20150311 (prerelease)]
 - Database version:  44.17

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>
2020-12-07 12:27:54 WARNING	Thread-5 :: [ce68da5] Unexpected error. Provider subtitulamos
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/ext/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/medusa/var/src/medusa/subtitle_providers/subtitulamos.py", line 201, in list_subtitles
    video.year)
  File "/volume1/@appstore/medusa/var/src/medusa/subtitle_providers/subtitulamos.py", line 147, in query
    episode_url = self._search_url_titles(series, season, episode, year)
  File "</volume1/@appstore/medusa/var/src/ext/decorator.py:decorator-gen-12>", line 2, in _search_url_titles
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1360, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 962, in get_or_create
    async_creator,
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 178, in _enter_create
    return self.creator()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 916, in gen_value
    *creator_args[0], **creator_args[1]
  File "/volume1/@appstore/medusa/var/src/medusa/subtitle_providers/subtitulamos.py", line 137, in _search_url_titles
    for episode_data in result['episodes']:
KeyError: 'episodes'

2020-12-07 12:27:54 INFO	Thread-5 :: [ce68da5] Searching episode url for Young Sheldon, season 4, episode 1
2020-12-07 12:27:53 INFO	Thread-5 :: [ce68da5] Manual searching subtitles for: Young.Sheldon.S04E01.720p.HDTV.x264-syncopy
2020-12-07 12:27:53 INFO	Thread-5 :: [ce68da5] Starting to manual searching subtitles
</details>

**Additional context**

**Comment by medariox** [comment]
Debug logs required as written in the template.
