### ISSUE TITLE
Error finding and downloading spanish subtitles with subtitulamos provider

### ISSUE THREAD

**Issue by porzino** [pymedusa/Medusa#8845]
**Describe the bug**
I can't get spanish subtitles from subtitulamos provider

**To Reproduce**
Get spanish subtitles automatic or manual using subtitulamos provider.

**Expected behavior**
I want Medusa to find the subtitle and download like previous versions.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: DSM 6.2.3-25426 (Synology)
 - Branch: master
 - Commit: ce68da57b3878591f77c21bb2acf28e6a58269fa
 - Python version: 3.7.7 (default, Sep 19 2020, 16:20:36)  [GCC 4.9.3 20150311 (prerelease)]
 - Database version:  44.17

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2020-12-07 13:08:32 INFO	Thread-9 :: [ce68da5] 328724: No subtitles found for Young Sheldon S04E01
2020-12-07 13:08:32 DEBUG	Thread-9 :: [ce68da5] 328724: Saving episode to database: Young Sheldon S04E01
2020-12-07 13:08:32 DEBUG	Thread-9 :: [ce68da5] 328724: Saving last subtitles search to database
2020-12-07 13:08:32 INFO	Thread-9 :: [ce68da5] No subtitles found for Young.Sheldon.S04E01.720p.HDTV.x264-syncopy.mkv
2020-12-07 13:08:32 DEBUG	Thread-9 :: [ce68da5] Could not search in subtitulamos provider. Discarding for now
2020-12-07 13:08:32 DEBUG	Thread-9 :: [ce68da5] Discarding provider subtitulamos
2020-12-07 13:08:32 WARNING	Thread-9 :: [ce68da5] Unexpected error. Provider subtitulamos
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/ext/subliminal/core.py", line 115, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/medusa/var/src/medusa/subtitle_providers/subtitulamos.py", line 201, in list_subtitles
    video.year)
  File "/volume1/@appstore/medusa/var/src/medusa/subtitle_providers/subtitulamos.py", line 147, in query
    episode_url = self._search_url_titles(series, season, episode, year)
  File "</volume1/@appstore/medusa/var/src/ext/decorator.py:decorator-gen-12>", line 2, in _search_url_titles
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1360, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 962, in get_or_create
    async_creator,
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(value, createdtime)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 178, in _enter_create
    return self.creator()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 916, in gen_value
    *creator_args[0], **creator_args[1]
  File "/volume1/@appstore/medusa/var/src/medusa/subtitle_providers/subtitulamos.py", line 137, in _search_url_titles
    for episode_data in result['episodes']:
KeyError: 'episodes'
2020-12-07 13:08:31 INFO	Thread-9 :: [ce68da5] Searching episode url for Young Sheldon, season 4, episode 1
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Initializing provider subtitulamos
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Listing subtitles with provider 'subtitulamos' and languages {<Language [es]>}
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Creating a new ProviderPool instance
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Video information cached under key medusa.subtitles:video|/volume1/video/Series/El joven Sheldon/Season 4/Young.Sheldon.S04E01.720p.HDTV.x264-syncopy.mkv
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] No apikey. Skipping omdb refiner.
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Refining video with omdb
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Refining video with tvdb
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Attribute title changed from None to 'Graduation'
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Attribute tvdb_id changed from None to 7992342
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Refining using Episode information.
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Attribute year changed from None to 2017
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Attribute series_imdb_id changed from None to 'tt6226232'
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Attribute series_tvdb_id changed from None to 328724
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Refining using Series information.
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Refining video with tvepisode
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Guessing using /volume1/video/Series/El joven Sheldon/Season 4/Young.Sheldon.S04E01.720p.HDTV.x264-syncopy.mkv
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Starting release refiner [extension=release, release_name=Young.Sheldon.S04E01.720p.HDTV.x264-syncopy, release_file=None]
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Refining video with release
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Refining video with metadata
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Refining video with hash
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Scanning video 'Young.Sheldon.S04E01.720p.HDTV.x264-syncopy.mkv' in '/volume1/video/Series/El joven Sheldon/Season 4'
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Scanning video /volume1/video/Series/El joven Sheldon/Season 4/Young.Sheldon.S04E01.720p.HDTV.x264-syncopy.mkv...
2020-12-07 13:08:31 DEBUG	Thread-9 :: [ce68da5] Checking subtitle candidates for Young Sheldon S04E01 (Young.Sheldon.S04E01.720p.HDTV.x264-syncopy.mkv)
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
You can try to stop medusa. Delete all *.dbm files in cache folder. And start

**Comment by porzino** [comment]
I have done it with no success.
The error is the same.
