### ISSUE TITLE
Received "AttributeError: 'NoneType' object has no attribute 'raise_for_status'" error when trying to snatch episodes.

### ISSUE THREAD

**Issue by astronyu** [pymedusa/Medusa#8854]
**Describe the bug**
Received an error when trying to snatch episodes.

**To Reproduce**
1. Go to series
2. Click on manual search
3. Icon changed to "X"

**Expected behavior**
File sent to NZBGet as usual for downloading

**Medusa (please complete the following information):**
 Medusa Info:	Branch: master
 Commit: ce68da57b3878591f77c21bb2acf28e6a58269fa
 Version: 0.5.0
 Database: 44.17
 Python Version:	3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 SSL Version:	OpenSSL 1.1.1d 10 Sep 2019
 OS:	Linux-3.10.105-x86_64-with
 Locale:	en_US.UTF-8
 Runs in Docker:	Yes

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
2020-12-09 20:53:34 ERROR	SNATCHQUEUE-SNATCH-368523 :: [ce68da5] Snatch failed! For result: Living.with.Yourself.S01E05.WEBRip.X264-PHENOMENAL.EZTV
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 518, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 239, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/downloadstation.py", line 98, in _get_auth
    self.response.raise_for_status()
AttributeError: 'NoneType' object has no attribute 'raise_for_status'
2020-12-09 20:53:34 DEBUG	SNATCHQUEUE-SNATCH-368523 :: [ce68da5] Error requesting url webapi/auth.cgi Error: Invalid URL 'webapi/auth.cgi': No schema supplied. Perhaps you meant http://webapi/auth.cgi?
2020-12-09 20:53:34 DEBUG	SNATCHQUEUE-SNATCH-368523 :: [ce68da5] Calling DownloadStation Client
2020-12-09 20:53:34 DEBUG	SNATCHQUEUE-SNATCH-368523 :: [ce68da5] User-Agent: Medusa/0.5.0 (Linux; 3.10.105; 0c0fc9da-38d9-11eb-86fa-0242ac110002)
2020-12-09 20:53:34 DEBUG	SNATCHQUEUE-SNATCH-368523 :: [ce68da5] GET URL: https://zoink.ch/torrent/Living.with.Yourself.S01E05.WEBRip.X264-PHENOMENAL[eztv].mkv.torrent [Status: 200]
2020-12-09 20:53:34 INFO	SNATCHQUEUE-SNATCH-368523 :: [ce68da5] Downloading Living.with.Yourself.S01E05.WEBRip.X264-PHENOMENAL.EZTV with 5 seeders and 1 leechers and size 145.40 MB from Eztv, through a SearchType.DAILY_SEARCH search
2020-12-09 20:53:34 INFO	SNATCHQUEUE-SNATCH-368523 :: [ce68da5] Beginning to snatch release: Living.with.Yourself.S01E05.WEBRip.X264-PHENOMENAL.EZTV

```
2020-12-09 19:34:58 ERROR    SNATCHQUEUE-SNATCH-368523 :: [ce68da5] Snatch failed! For result: Living.With.Yourself.S01E03.480p.x264-mSD.EZTV
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 518, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 239, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/downloadstation.py", line 98, in _get_auth
    self.response.raise_for_status()
AttributeError: 'NoneType' object has no attribute 'raise_for_status'```
</details>

**Additional context**
Connection to both NZBGet and Download Station were tested to be working.

**Comment by medariox** [comment]
Enable debug logging, restart, go to view logs and select debug. 99% of the time this happens because of a misconfiguration and your client can't be reached.

**Comment by astronyu** [comment]
> Enable debug logging, restart, go to view logs and select debug. 99% of the time this happens because of a misconfiguration and your client can't be reached.

Thank you., Updated thread with debug log.

**Comment by astronyu** [comment]
[UPDATE - SOLVED]

Turns out in search provider settings, I need to add "http://" for the host:port field. Weird as without "http://" connection was shown as working.

**Comment by coops1967** [comment]
thanks for the update/fix...

I was having a very similar error with Torrent searches -"AttributeError: 'NoneType' object has no attribute 'raise_for_status'"

I did not have the "http://" preceeding my Synology Download Station IP address (and yes, without the http it would also pass the connection test ok).

Added http:// before the IP address for my Torrent search settings and all is good (including NZB searches)...

Now to add all my shows and then ditch Sickchill....
