### ISSUE TITLE
[APP SUBMITTED]: ValueError: invalid literal for int() with base 10: '44.59 GB'

### ISSUE THREAD

**Issue by maciekb** [pymedusa/Medusa#8858]
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-56-generic-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/c0a6d7647bb41ae1df79471429826478
### ERROR
<pre>
2020-12-10 09:37:46 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [PTE-RSS] :: [] Casting to int failed.
Stack trace:
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/app/medusa/medusa/search/queue.py", line 297, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/app/medusa/medusa/search/core.py", line 526, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "/app/medusa/medusa/tv/cache.py", line 250, in update_cache
    search_result = self.provider.get_result(series=parsed_result.series,
  File "/app/medusa/medusa/providers/torrent/torrent_provider.py", line 54, in get_result
    search_result = TorrentSearchResult(provider=self, series=series,
  File "/app/medusa/medusa/classes.py", line 342, in __init__
    super(TorrentSearchResult, self).__init__(provider, series=series, item=item, cache=cache)
  File "/app/medusa/medusa/classes.py", line 114, in __init__
    self.update_search_result()
  File "/app/medusa/medusa/classes.py", line 270, in update_search_result
    self.size = self.provider._get_size(self.item)
Traceback (most recent call last):
  File "/app/medusa/medusa/helper/common.py", line 331, in try_int
    return int(candidate)
ValueError: invalid literal for int() with base 10: '44.59 GB'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Which provider is this?

**Comment by maciekb** [comment]
This is pte.nu via Jackett proxy.

**Comment by medariox** [comment]
Weird. Try to delete your cache.db and restart.
