### ISSUE TITLE
Getting AttributeError: 'NoneType' object has no attribute 'group' trying to add to Transmission

### ISSUE THREAD

**Issue by ksolomon** [pymedusa/Medusa#8938]
**Describe the bug**
When trying to add an episode to Transmission for download, it fails trying to send to Transmission.  It happens whether the search is automated or manual.

**To Reproduce**
1. Try to send a download to Transmission.
2. Error happens

**Expected behavior**
Should send download to Transmission

**Medusa (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Branch: master
 - Python version: 3.8.5

**Debug logs:**
<details>

```
2020-12-29 18:20:20 ERROR	SNATCHQUEUE-SNATCH-335550 :: Snatch failed! For result: Corner.Gas.Animated.S03E11.720p.HDTV.x264.SYNCOPY.TGx
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 518, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 242, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/transmission.py", line 77, in _get_auth
    self.auth = re.search(r'X-Transmission-Session-Id:\s*(\w+)', self.response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2020-12-29 18:20:18 INFO	SNATCHQUEUE-SNATCH-335550 :: Downloading Corner.Gas.Animated.S03E11.720p.HDTV.x264.SYNCOPY.TGx with 8 seeders and 0 leechers and size 343.88 MB from 1337x, through a SearchType.DAILY_SEARCH search
2020-12-29 18:20:18 INFO	SNATCHQUEUE-SNATCH-335550 :: Beginning to snatch release: Corner.Gas.Animated.S03E11.720p.HDTV.x264.SYNCOPY.TGx
2020-12-29 18:20:17 ERROR	SNATCHQUEUE-SNATCH-161511 :: Snatch failed! For result: Shameless.US.S11E03.1080p.AMZN.WEBRip.x265.HEVC.10bit.AC3.5.1.Qman.UTR
Traceback (most recent call last):
  File "/app/medusa/medusa/search/queue.py", line 518, in run
    self.success = snatch_episode(result)
  File "/app/medusa/medusa/search/core.py", line 167, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/app/medusa/medusa/clients/torrent/generic.py", line 242, in send_torrent
    if not self._get_auth():
  File "/app/medusa/medusa/clients/torrent/transmission.py", line 77, in _get_auth
    self.auth = re.search(r'X-Transmission-Session-Id:\s*(\w+)', self.response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
</details>

**Comment by ksolomon** [comment]
Never mind.  I guess I was blind when I set up Transmission, since I used an incorrect IP address.  All good here...
