### ISSUE TITLE
error message when using force search

### ISSUE THREAD

**Issue by digitalgp** [pymedusa/Medusa#8946]
Hi, i noticed that tv show i follow had 4k version. I then changed the wanted category to 4k-webdl. I know one of my providers have these files.
I then go into the tv show and press force search.
Got these error messages below. And no results are shown from the provider (IPT) but other results from other providers are shown.
I can provoke thos errors several times with the same force search. After 3-4 rounds with same errors. I get no errors, and no results from IPT shown for the same episode or other episodes that are released.

But i get this message in jackett: Torznab search in IPTorrents for The Stand S01E02 => Found 41 releases, so the search does find releases.
IPT direct connection in medusa gives no results either.

Error in medusa:

2021-01-01 21:21:43 INFO	SEARCHQUEUE-DAILY-SEARCH :: [54da0c7] No needed episodes found
2021-01-01 21:21:42 ERROR	TORNADO :: [54da0c7] Uncaught exception in APIv2: OperationalError('duplicate column name: pubdate')
Request: GET /medusa/api/v2/providers/ipt/results?limit=1000&showslug=tvmaze35790&season=1&episode=3&page=1 (192.168.10.100)
Traceback (most recent call last):
  File "/opt/medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/medusa/ext/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/medusa/medusa/server/api/v2/base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/providers.py", line 58, in get
    provider_results = provider.cache.get_results(show_slug=show_slug, season=season, episode=episode)
  File "/opt/medusa/medusa/tv/cache.py", line 637, in get_results
    cache_db_con = self._get_db()
  File "/opt/medusa/medusa/tv/cache.py", line 141, in _get_db
    self.provider_db = CacheDBConnection(self.provider_id)
  File "/opt/medusa/medusa/tv/cache.py", line 103, in __init__
    self.addColumn(provider_id, column, data_type, default)
  File "/opt/medusa/medusa/db.py", line 425, in addColumn
    self.action('ALTER TABLE [%s] ADD %s %s' % (table, column, column_type))
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: pubdate
2021-01-01 21:21:42 ERROR	APIv2-Thread-2 :: [54da0c7] DB error: duplicate column name: pubdate
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: pubdate
2021-01-01 21:21:42 ERROR	APIv2-Thread-2 :: [54da0c7] DB error: OperationalError('duplicate column name: pubdate')
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: pubdate
2021-01-01 21:21:42 INFO	APIv2-Thread-2 :: [54da0c7] Query: 'ALTER TABLE [ipt] ADD pubdate NUMERIC'. Arguments: 'None'
2021-01-01 21:21:23 INFO	Thread-1 :: [54da0c7] Broken providers found: ['']

**Comment by digitalgp** [comment]
tried to delete cache.db and starting medusa again. then it gave a new error:

2021-01-02 08:41:32 ERROR	TORNADO :: [54da0c7] Uncaught exception in APIv2: OperationalError('duplicate column name: seeders')
Request: GET /medusa/api/v2/providers/ipt/results?limit=1000&season=1&episode=2&page=1 (192.168.10.100)
Traceback (most recent call last):
  File "/opt/medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/medusa/ext/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/medusa/medusa/server/api/v2/base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/providers.py", line 58, in get
    provider_results = provider.cache.get_results(show_slug=show_slug, season=season, episode=episode)
  File "/opt/medusa/medusa/tv/cache.py", line 637, in get_results
    cache_db_con = self._get_db()
  File "/opt/medusa/medusa/tv/cache.py", line 141, in _get_db
    self.provider_db = CacheDBConnection(self.provider_id)
  File "/opt/medusa/medusa/tv/cache.py", line 103, in __init__
    self.addColumn(provider_id, column, data_type, default)
  File "/opt/medusa/medusa/db.py", line 425, in addColumn
    self.action('ALTER TABLE [%s] ADD %s %s' % (table, column, column_type))
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: seeders
2021-01-02 08:41:32 ERROR	APIv2-Thread :: [54da0c7] DB error: duplicate column name: seeders
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: seeders
2021-01-02 08:41:32 ERROR	APIv2-Thread :: [54da0c7] DB error: OperationalError('duplicate column name: seeders')
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: seeders

**Comment by p0psicles** [comment]
Did you check medusa was stopped, when deleted cache.db?

**Comment by digitalgp** [comment]
I run medusa in docker. and the docker was stopped before renaming the cache.db

**Comment by medariox** [comment]
Don't use the same name to add IPT torznab provider. Remove the provider you have added, shut down Medusa, delete cache.db - add back the provider with name IPTJackett or something else that is no IPTorrents or IPT.

**Comment by p0psicles** [comment]
Nice catch @medariox

**Comment by digitalgp** [comment]
i did as you said. Added iptjackett.
Got this error:
2021-01-03 12:09:52 ERROR    APIv2-Thread_3 :: [54da0c7] DB error: OperationalError('duplicate column name: seeders')
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: seeders
2021-01-03 12:09:52 ERROR    APIv2-Thread_3 :: [54da0c7] DB error: duplicate column name: seeders
Traceback (most recent call last):
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: seeders
2021-01-03 12:09:52 ERROR    TORNADO :: [54da0c7] Uncaught exception in APIv2: OperationalError('duplicate column name: seeders')
Request: GET /medusa/api/v2/providers/eztvjacket/results?limit=1000&season=5&episode=5&page=1 (192.168.10.100)
Traceback (most recent call last):
  File "/opt/medusa/ext/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/medusa/ext/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/medusa/medusa/server/api/v2/base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/opt/medusa/ext/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/medusa/medusa/server/api/v2/providers.py", line 58, in get
    provider_results = provider.cache.get_results(show_slug=show_slug, season=season, episode=episode)
  File "/opt/medusa/medusa/tv/cache.py", line 637, in get_results
    cache_db_con = self._get_db()
  File "/opt/medusa/medusa/tv/cache.py", line 141, in _get_db
    self.provider_db = CacheDBConnection(self.provider_id)
  File "/opt/medusa/medusa/tv/cache.py", line 103, in __init__
    self.addColumn(provider_id, column, data_type, default)
  File "/opt/medusa/medusa/db.py", line 425, in addColumn
    self.action('ALTER TABLE [%s] ADD %s %s' % (table, column, column_type))
  File "/opt/medusa/medusa/db.py", line 285, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/medusa/medusa/db.py", line 113, in _execute
    sql_results = cursor.execute(query)
sqlite3.OperationalError: duplicate column name: seeders

**Comment by digitalgp** [comment]
deleted and added providers again. All seems to be working now. Thanks guys.

**Comment by digitalgp** [comment]
deleted and added providers again. All seems to be working now. Thanks guys.
