### ISSUE TITLE
NzbToMedia + SABnzbd tries to process __ADMIN__ folder on failed download

### ISSUE THREAD

**Issue by safety-orange** [pymedusa/Medusa#8967]
This used to work perfectly, but after some recent update of Medusa or NzbToMedia I have been getting an error in Medusa when it tries to handle failed downloads. Hopefully somebody here can help me to fix the issue or point me in the right direction what to try or where to ask for a solution.

I am running this all on a Synology in case it matters. All three programs are up to date as of writing this post. Using [Medusa master branch from the latest commit](https://github.com/pymedusa/Medusa/commit/1c1d3279ea1c3bb891b8581671e21543aea00c8c).    
This is all run with Python 3.7

My settings in the autoProcessMedia.cfg are as follows (with the identifying data changed of course):

	[SickBeard]
		[[tv]]
			enabled = 1
			host = localhost
			port = 12345
			apikey = 12345678
			username = **usr**
			password = **pswrd**
			web_root = ""
        		###### ADVANCED USE - ONLY EDIT IF YOU KNOW WHAT YOU'RE DOING ######
			ssl = 1
			fork = auto
			delete_failed = 1
			Torrent_NoLink = 0
			keep_archive = 1
			process_method = ""
			force = 0
			# tell SickRage/Medusa to delete all source files after processing.
			delete_on = 1
			# tell Medusa to ignore check for associated subtitle check when postponing release
			ignore_subs = 0
			extract = 1
			nzbExtractionBy = Downloader
			# Set this to minimum required size to consider a media file valid (in MB)
			minSize = 0
			# Enable/Disable deleting ignored files (samples and invalid media files)
			delete_ignored = 1
			##### Enable if SickBeard is on a remote server for this category
			remote_path = 0
			##### Set to path where download client places completed downloads locally for this category
			watch_dir = ""
			##### Set the recursive directory permissions to the following (0 to disable)
			chmodDirectory = 0

In Medusa I see the following error from the nzbToSickBeard.py script (remember it is reverse chronological order):

	2021-01-07 14:34:55 ERROR	TORNADO :: [1c1d327] API :: PermissionError(13, 'Permission denied')
	Traceback (most recent call last):
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/server/api/v1/core.py", line 165, in get
		out_dict = _call_dispatcher(args, kwargs)
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/server/api/v1/core.py", line 235, in call_dispatcher
		cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/server/api/v1/core.py", line 1336, in run
		proc_type=self.type
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 61, in run
		return ProcessResult(path, process_method).process(force=force, **kwargs)
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 170, in process
		if not self.should_process(path, failed):
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 251, in should_process
		if not self._is_valid_folder(path, failed):
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 286, in _is_valid_folder
		self.process_failed(path)
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 654, in process_failed
		self.result = processor.process()
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/failed_processor.py", line 41, in process
		releaseName = naming.determine_release_name(self.dir_name, self.nzb_name)
	  File "/volume1/@appstore/medusa/var/Medusa/medusa/show/naming.py", line 136, in determine_release_name
		files = [file_name for file_name in os.listdir(dir_name) if
	PermissionError: [Errno 13] Permission denied: '/volume2/Downloads/00_temp/The.Flight.Attendant.S01E07.Hitchcock.Double.1080p.HMAX.WEB-DL.DD5.1.H.264-NTG/\_\_ADMIN\_\_'
	2021-01-07 14:34:55 INFO	TORNADO :: [1c1d327] Failed download detected: (None, /volume2/Downloads/00_temp/The.Flight.Attendant.S01E07.Hitchcock.Double.1080p.HMAX.WEB-DL.DD5.1.H.264-NTG/\_\_ADMIN\_\_)
	2021-01-07 14:34:55 INFO	TORNADO :: [1c1d327] Failed Download Processing succeeded: None, /volume2/Downloads/00_temp/The.Flight.Attendant.S01E07.Hitchcock.Double.1080p.HMAX.WEB-DL.DD5.1.H.264-NTG
	2021-01-07 14:34:55 INFO	TORNADO :: [1c1d327] Failed download detected: (None, /volume2/Downloads/00_temp/The.Flight.Attendant.S01E07.Hitchcock.Double.1080p.HMAX.WEB-DL.DD5.1.H.264-NTG)
	2021-01-07 14:34:55 INFO	TORNADO :: [1c1d327] Processing path: /volume2/Downloads/00_temp/The.Flight.Attendant.S01E07.Hitchcock.Double.1080p.HMAX.WEB-DL.DD5.1.H.264-NTG

&nbsp;

SABnzbd makes a read-only folder named "\_\_ADMIN\_\_" inside the job folder of a download and it seems that Medusa is wrongly trying to post-process this folder. On successful downloads, this \_\_ADMIN\_\_ folder is removed by SABnzbd prior to calling the NzbToMedia script.

At first I had the "fork" in the autoProcessMedia.cfg file set to "Medusa". Changing it to auto at least made it possible for the failed download handling to continue trying to download alternative episodes as now the download itself is correctly flagged as "failed" prior to the error with the "\_\_ADMIN\_\_" folder and Medusa does try to download another version of the episode.

It is just bothersome that whenever I open Medusa, I have to clear the error and warning logs. If somebody has an idea for a fix, I'm all ears!

**Comment by medariox** [comment]
Please use Discussions: https://github.com/pymedusa/Medusa/discussions/categories/q-a
,Reddit or Discord for support. Issues is for bug reports only.
