### ISSUE TITLE
Since latest update 2021-01-10 unable to see any episodes

### ISSUE THREAD

**Issue by hawkeye73** [pymedusa/Medusa#8984]
**Describe the bug**
Since the update ran I'm unable to show any episodes when I chose a TV series. It shows the TV Series information but no season numbers or episodes list.

**To Reproduce**
1. Go to 'first tv series...'
2. Click on 'the name'
3. I don't see any episodes mentioned. Also choose other series 

2021-01-10 23:51:53 ERROR    TORNADO :: [5839c67] Uncaught exception in APIv2: TypeError("create_episode_structure() missing 1 required positional argument: 'episodes'")
Request: GET /api/v2/series/tvdb272644/episodes?limit=1000&season=0 (192.168.1.238)
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Medusa\Medusa\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Medusa\Medusa\ext\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Medusa\Medusa\medusa\server\api\v2\base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\Medusa\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Medusa\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\Medusa\medusa\server\api\v2\episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 831, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 944, in get_episode
    ep = Episode(self, season, episode)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 271, in __init__
    self._specify_episode(self.season, self.episode)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 642, in _specify_episode
    sql_results = self.load_from_db(season, episode)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 722, in load_from_db
    self.status = int(sql_results[0]['status'] or UNSET)
  File "C:\Medusa\Medusa\medusa\tv\base.py", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 428, in status
    self._sync_trakt(value)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 450, in _sync_trakt
    notifiers.trakt_notifier.update_watchlist_episode(self)
  File "C:\Medusa\Medusa\medusa\notifiers\trakt.py", line 120, in update_watchlist_episode
    result = sync.add_to_watchlist({'shows': [create_episode_structure(episodes)]})
TypeError: create_episode_structure() missing 1 required positional argument: 'episodes'
**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.'

![image](https://user-images.githubusercontent.com/3111785/104137908-997e5c00-53a0-11eb-849d-9f4094ea22fd.png)

**Medusa (please complete the following information):**
 - OS: Windows Server 2019 Build 17763.1637
 - Branch: master
 - Commit: 5839c67dd78e5d5eb9b058fac805c8bf4a51e22b
 - Python version: 3.7.3
 - Database version: 0.5.2.

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-01-11 00:08:04 ERROR    TORNADO :: [5839c67] Uncaught exception in APIv2: TypeError("create_episode_structure() missing 1 required positional argument: 'episodes'")
Request: GET /api/v2/series/tvdb73940/episodes?limit=1000&season=0 (192.168.1.238)
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Medusa\Medusa\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Medusa\Medusa\ext\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Medusa\Medusa\medusa\server\api\v2\base.py", line 83, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "C:\Medusa\Medusa\ext\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Medusa\Python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Medusa\Medusa\medusa\server\api\v2\episodes.py", line 60, in get
    data = [e.to_json(detailed=detailed) for e in series.get_all_episodes(season=season)]
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 831, in get_all_episodes
    cur_ep = self.get_episode(cur_result['season'], cur_result['episode'])
  File "C:\Medusa\Medusa\medusa\tv\series.py", line 944, in get_episode
    ep = Episode(self, season, episode)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 271, in __init__
    self._specify_episode(self.season, self.episode)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 642, in _specify_episode
    sql_results = self.load_from_db(season, episode)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 722, in load_from_db
    self.status = int(sql_results[0]['status'] or UNSET)
  File "C:\Medusa\Medusa\medusa\tv\base.py", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 428, in status
    self._sync_trakt(value)
  File "C:\Medusa\Medusa\medusa\tv\episode.py", line 450, in _sync_trakt
    notifiers.trakt_notifier.update_watchlist_episode(self)
  File "C:\Medusa\Medusa\medusa\notifiers\trakt.py", line 120, in update_watchlist_episode
    result = sync.add_to_watchlist({'shows': [create_episode_structure(episodes)]})
TypeError: create_episode_structure() missing 1 required positional argument: 'episodes'
```
</details>

**Additional context**
System running for many years without issues.

**Comment by hawkeye73** [comment]
As I read the history I saw changes in the trakt implementation. I reconnect trakt and it didn't work. When I disabled trakt it worked again! Enabling again the trakt notification and it looks working now. For me this can be closed but maybe the devs (keep up the good work!) can learn something from this as I'm not a programmer at all. Happy user. Cheers.

**Comment by medariox** [comment]
Glad you have found a workaround. Yes, this will need to be fixed no matter what, so I'll reopen it.

**Comment by hawkeye73** [comment]
I was too early :( Some series didn't show the content of the episodes so for now I disable the trakt notificaiton.

**Comment by pax0707** [comment]
Yes, this workaround is not working.
Breaks things like post-processing, clearing episodes from schedule etc.
Disabled Trakt integration for now.

**Comment by medariox** [comment]
Fixed with the new release: https://github.com/pymedusa/Medusa/releases

**Comment by hawkeye73** [comment]
I updated and enabled the trakt implementation and I saw only 1 season in stead of the full 9. I saw this error in my log:

2021-01-13 12:20:49 WARNING	APIv2-Thread-6 :: [698ca1d] Unable to update Trakt watchlist: RateLimitException()

For the time being I disabled the implementation. Is there anything I can try for you?

**Comment by p0psicles** [comment]
That's an error because you made too many trakt calls.

**Comment by hawkeye73** [comment]
> That's an error because you made too many trakt calls.

I understand the error states there are too many API calls but what I didn't expect to happen is that it didn't load my whole list of episodes anymore, only 1 season, the latest, not the other 8 seasons.
