### ISSUE TITLE
Medusa not starting after 0.5.2

### ISSUE THREAD

**Issue by sebeksd** [pymedusa/Medusa#8986]
**Describe the bug**
Medusa not starting after updating from 0.5.1 to 0.5.2 (starts after downgrade). I'm using docker image from "linuxserver/medusa".

`2021-01-11 08:27:41 INFO     MAIN :: [6bfdb22] Starting Medusa [master] using '/config/config.ini'
Traceback (most recent call last):
  File "/app/medusa/start.py", line 9, in <module>
    main()
  File "/app/medusa/medusa/__main__.py", line 2257, in main
    application.start(sys.argv[1:])
  File "/app/medusa/medusa/__main__.py", line 407, in start
    'https_cert': os.path.join(app.PROG_DIR, app.HTTPS_CERT),
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`

I think I know whats the problem, I have path for certs set:
`enable_https = 0
notify_on_login = 0
https_cert = /lecert/fullchain.pem
https_key = /lecert/privkey.pem`
but "enable_https" is disabled and path doesn't exists because I'm using Traefik.
This configuration is only there for quick revers from Traefik to direct https from medusa.

**To Reproduce**
1. Set configuration as described above.
2. Run medusa

**Expected behavior**
Medusa should ignore https cert paths when https is disabled.

**Screenshots**

**Medusa (please complete the following information):**
From last working version (0.5.1)
Branch: master
Commit: 6bfdb2236003331e639a1845f765ee0462ae8a5d
Version: 0.5.1
Database: 44.17
Python Version: | 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1i 8 Dec 2020
OS: | Linux-5.9.0-0.bpo.2-amd64-x86_64-with

**Debug logs (at least 50 lines):**
I removed lines with: "episode", "Building black and white", "Loading show info from database","Could not find a next episode"
<details>

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1003
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2021-01-11 09:11:40 DEBUG    MAIN :: [6bfdb22] GET URL: https://cdn.pymedusa.com/providers/broken_providers.json [Status: 200]
2021-01-11 09:11:40 DEBUG    MAIN :: [6bfdb22] User-Agent: Medusa/0.5.2 (Linux; 5.9.0-0.bpo.2-amd64; a176d416-53e4-11eb-aede-0242ac12000a)
2021-01-11 09:11:41 INFO     MAIN :: [6bfdb22] Broken providers found: ['']
2021-01-11 09:11:41 INFO     MAIN :: [6bfdb22] Changed TV download folder to /downloads
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Running in a docker container
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking database structure...main.db
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Initial Schema database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] InitialSchema upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Version To Tv Episodes database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddVersionToTvEpisodes upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Default Ep Status To Tv Shows database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddDefaultEpStatusToTvShows upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Alter Shows Field Types database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AlterTVShowsFieldTypes upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Minor Version database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddMinorVersion upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Test Increase Major Version database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] TestIncreaseMajorVersion upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Proper Tags database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddProperTags upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Manual Searched database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddManualSearched upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Info Hash database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddInfoHash upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Plot database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddPlot upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Resource Size database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddResourceSize upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Indexer Mapping database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddPKIndexerMapping upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Indexer Integer database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddIndexerInteger upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Indexer Ids database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddIndexerIds upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Separated Status Quality Fields database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddSeparatedStatusQualityFields upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Shift Qualities database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] ShiftQualities upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddEpisodeWatchedField upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Tvshow Start Search Offset database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddTvshowStartSearchOffset upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Release Ignore Require Exclude Options database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddReleaseIgnoreRequireExcludeOptions upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Move Scene Exceptions database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] MoveSceneExceptions upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Show Lists database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddShowLists upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Custom Logs database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddCustomLogs upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking database structure...cache.db
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Initial Schema database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] InitialSchema upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Scene Exceptions database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddSceneExceptions upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Scene Name Cache database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddSceneNameCache upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Network Timezones database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddNetworkTimezones upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Last Search database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddLastSearch upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Scene Exceptions Seasons database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddSceneExceptionsSeasons upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Scene Exceptions Custom database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddSceneExceptionsCustom upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Scene Exceptions Refresh database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddSceneExceptionsRefresh upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Convert Scene Exeptions To Indexer Scheme database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] ConvertSceneExeptionsToIndexerScheme upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Convert Scene Names To Indexer Scheme database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] ConvertSceneNamesToIndexerScheme upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Remove Indexer Update Schema database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] RemoveIndexerUpdateSchema upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Indexer Scene Exceptions database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddIndexerSceneExceptions upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Indexer Ids database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddIndexerIds upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Clear Provider Tables database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] ClearProviderTables upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Provider Tables Identifier database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddProviderTablesIdentifier upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Remove Scene Exceptions Table database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] RemoveSceneExceptionsTable upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Performing a vacuum on the CACHE database
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking database structure...failed.db
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Initial Schema database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] InitialSchema upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Size And Provider database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] SizeAndProvider upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking History database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] History upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking History Status database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] HistoryStatus upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Add Indexer Ids database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] AddIndexerIds upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Update History Table Quality database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] UpdateHistoryTableQuality upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking Shift Qualities database upgrade
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] ShiftQualities upgrade not required
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking for delete episodes with subtitle reference
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Checking for null indexer mappings
2021-01-11 09:11:41 INFO     MAIN :: [6bfdb22] 12345: Unable to find the show in the database
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] 12345: Show Name S02E03 not found in the database
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Using guessit cache item for Show.Name.013.HDTV.x264-RLSGROUP
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Matched release Show.Name.013.HDTV.x264-RLSGROUP to a series in your database: Show Name
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Parsed Show.Name.013.HDTV.x264-RLSGROUP into title: Show Name, episode: [13], absolute_episode: [13], source: HDTV, video_codec: H.264, video_encoder: x264, release_group: RLSGROUP, type: episode, parsing_time: 0.04691195487976074, season: None, quality: Unknown, total_time: 0.0486750602722168
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Found codec for Show Name Ep Name
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] 12345: Formatting pattern: %SN - S%0SE03 - %EN -> Show Name - S02E03 - Ep Name
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Using guessit cache item for Show.Name.013.HDTV.x264-RLSGROUP
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Using cache item for Show.Name.013.HDTV.x264-RLSGROUP
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Matched release Show.Name.013.HDTV.x264-RLSGROUP to a series in your database: Show Name
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Parsed Show.Name.013.HDTV.x264-RLSGROUP into title: Show Name, episode: [13], absolute_episode: [13], source: HDTV, video_codec: H.264, video_encoder: x264, release_group: RLSGROUP, type: episode, parsing_time: 0.00030732154846191406, season: None, quality: Unknown, total_time: 0.0003604888916015625
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Found codec for Show Name Ep Name
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] 12345: Formatting pattern: Season %0S -> Season 02
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Trying to parse Show Name - S02E03 - Ep Name.ext
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Using guessit cache item for Show Name - S02E03 - Ep Name.ext
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Matched release Show Name - S02E03 - Ep Name.ext to a series in your database: Show Name
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Parsed Show Name - S02E03 - Ep Name.ext into title: Show Name, season: 2, episode: [3], episode_title: Ep Name ext, type: episode, parsing_time: 0.02109384536743164, absolute_episode: [], quality: Unknown, total_time: 0.021195650100708008
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] The name Show Name - S02E03 - Ep Name.ext parsed into title: Show Name, season: 2, episode: [3], episode_title: Ep Name ext, type: episode, parsing_time: 0.02109384536743164, absolute_episode: [], quality: Unknown, total_time: 0.021195650100708008
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Retrieving the last check time from the DB
2021-01-11 09:11:41 DEBUG    MAIN :: [6bfdb22] Loading initial show list
2021-01-11 09:11:41 INFO     MAIN :: [6bfdb22] 81327: Unable to find IMDb info in the database: Włatcy Móch
2021-01-11 09:11:42 DEBUG    CHECKVERSION :: [6bfdb22] Starting new thread: CHECKVERSION
2021-01-11 09:11:42 DEBUG    MAIN :: [6bfdb22] 371310: Could not find a previous aired episode
2021-01-11 09:11:42 INFO     MAIN :: [6bfdb22] Starting Medusa [master] using '/config/config.ini'
Traceback (most recent call last):
  File "/app/medusa/start.py", line 9, in <module>
    main()
  File "/app/medusa/medusa/__main__.py", line 2257, in main
    application.start(sys.argv[1:])
  File "/app/medusa/medusa/__main__.py", line 407, in start
    'https_cert': os.path.join(app.PROG_DIR, app.HTTPS_CERT),
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
2021-01-11 09:11:42 INFO     CHECKVERSION :: [6bfdb22] Checking for updates using Docker Updater
2021-01-11 09:11:42 INFO     CHECKVERSION :: [6bfdb22] No update needed
2021-01-11 09:11:42 DEBUG    CHECKVERSION :: [6bfdb22] Checking GitHub for latest news.
2021-01-11 09:11:42 DEBUG    CHECKVERSION :: [6bfdb22] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2021-01-11 09:11:42 DEBUG    CHECKVERSION :: [6bfdb22] User-Agent: Medusa/0.5.2 (Linux; 5.9.0-0.bpo.2-amd64; a176d416-53e4-11eb-aede-0242ac12000a)

</details>

**Additional context**

**Comment by skaynl** [comment]
Thanks!!! I had the same error, Looking in the config.ini showed me that the path to the certs files wasn't correct in my case (old path on old server but not used because enable_https = 0). Changing the patch to existing pem files made Medusa work again :)

**Comment by sebeksd** [comment]
As a side note, when https is disabled paths in gui are hidden so user don't even know there something in those parameters:
![image](https://user-images.githubusercontent.com/18705953/104173004-6a4e0600-5405-11eb-96b2-1d01098c0d4e.png)
![image](https://user-images.githubusercontent.com/18705953/104172944-586c6300-5405-11eb-89d2-1b6c67e4f09c.png)

**Comment by p0psicles** [comment]
Ok will address that

**Comment by p0psicles** [comment]
Can any of you run medusa with a self signed cert? I've never used this feature. But i'm trying to generate a cert using puttyGen. Where I create a cert and .key file, using the export OpenSSH tool. But i'm getting errors when I try to access through https.

**Comment by sebeksd** [comment]
I did test this using builtin Medusa https with LetsEncrypt certs (like in config visible on my screenshots) and its working.

I was using self signed cert way back (maybe even on SickRage/SickChill), I only remember that it was always a pain to configure any certs in any app :P Right now I don't remember how to generate correct self signed certs.
