### ISSUE TITLE
Unable to edit any show after upgrading to last version.

### ISSUE THREAD

**Issue by hergonoway** [pymedusa/Medusa#9070]
**Describe the bug**
While opening an edit page for any show, I've got an error about non being able to retrieve release group and get systematicaly an error when trying to save > Can't edit any show, got red errors too.

This issue happens to any existing show

**To Reproduce**
1. Go to any show, then click "edit"
2. get an orange error while edit page is opening (see screenshot)
3. click "save" 
4. get a red error (see screenshot) and can't perform the required save.

**Screenshots**
error when you open the edit page:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/8405448/105254059-02c05500-5b81-11eb-96f6-ef144cca76ba.png">

error when you try to save the edit:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/8405448/105254123-22577d80-5b81-11eb-9442-e4a12cb8ac74.png">

**Medusa (please complete the following information):**

Branch: master
Commit: 918cfe7ce01808499585ffe6c1356fd5ed369f76
Version: 0.5.4
Database: 44.17
Python Version: 3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]
SSL Version: OpenSSL 1.1.1i 8 Dec 2020
OS: Linux-4.4.59+-x86_64-with
Locale: en_US.UTF-8

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-01-21 00:39:14 ERROR	TORNADO :: [918cfe7] Uncaught exception in APIv2: UnicodeDecodeError('utf-8', b'\x80\x05\x95L\x00\x00\x00\x00\x00\x00\x00\x8c\x11dogpile.cache.api\x94\x8c\x0bCachedValue\x94\x93\x94]\x94\x8c\x05Judas\x94a}\x94(\x8c\x02ct\x94GA\xd8\x00\xde7\x87\xdb@\x8c\x01v\x94K\x01u\x86\x94R\x94.', 0, 1, 'invalid start byte')
Request: PATCH /api/v2/series/tvdb372939 (172.17.0.1)
With body:
{"config":{"aliases":[{"season":-1,"title":"Majutsushi Orphen Hagure tabi","custom":false}],"defaultEpisodeStatus":"Wanted","dvdOrder":false,"seasonFolders":false,"anime":true,"scene":true,"sports":false,"paused":false,"location":"/anime/[TEMP SR]/Sorcerous Stabber Orphen","airByDate":false,"subtitlesEnabled":false,"release":{"requiredWords":[],"ignoredWords":[],"requiredWordsExclude":false,"ignoredWordsExclude":false,"blacklist":[],"whitelist":["Judas","Erai-raws"]},"qualities":{"preferred":[],"allowed":[32,128,512]},"airdateOffset":0,"showLists":[]},"language":"en"}
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/medusa/medusa/server/api/v2/series.py", line 174, in patch
    if patch_field and patch_field.patch(series, value):
  File "/app/medusa/medusa/server/api/v2/base.py", line 516, in patch
    setattr(target, self.attr, self.converter(value))
  File "/app/medusa/medusa/tv/base.py", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/app/medusa/medusa/tv/series.py", line 764, in whitelist
    self.release_groups.set_white_keywords(short_group_names(group_names))
  File "/app/medusa/medusa/helpers/anidb.py", line 106, in short_group_names
    short_group_list += get_short_group_name(group_name) or [group_name]
  File "</app/medusa/ext/decorator.py:decorator-gen-15>", line 2, in get_short_group_name
  File "/app/medusa/ext/dogpile/cache/region.py", line 1563, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1028, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/app/medusa/ext/dogpile/cache/region.py", line 963, in get_value
    value = self._get_from_backend(key)
  File "/app/medusa/ext/dogpile/cache/region.py", line 1250, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1207, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
2021-01-21 00:39:14 INFO	APIv2-Thread-2 :: [918cfe7] Building internal name cache for Sorcerous Stabber Orphen
2021-01-21 00:39:14 INFO	APIv2-Thread-2 :: [918cfe7] Finished processing 3514 scene exceptions.
2021-01-21 00:39:14 INFO	APIv2-Thread-2 :: [918cfe7] Updating exception_cache and exception_season_cache
2021-01-21 00:39:13 INFO	APIv2-Thread-2 :: [918cfe7] Updating scene exceptions...
2021-01-21 00:37:43 ERROR	Thread :: [918cfe7] Exception generated: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/handler.py", line 1806, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</app/medusa/ext/decorator.py:decorator-gen-14>", line 2, in get_release_groups_for_anime
  File "/app/medusa/ext/dogpile/cache/region.py", line 1563, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1028, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/app/medusa/ext/dogpile/cache/region.py", line 963, in get_value
    value = self._get_from_backend(key)
  File "/app/medusa/ext/dogpile/cache/region.py", line 1250, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1207, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
2021-01-21 00:37:43 INFO	Thread :: [918cfe7] ReleaseGroups: Sorcerous Stabber Orphen
2021-01-21 00:34:13 INFO	MAIN :: [918cfe7] Building internal name cache for all shows
2021-01-21 00:34:13 INFO	MAIN :: [918cfe7] Finished processing 3514 scene exceptions.
2021-01-21 00:34:13 INFO	MAIN :: [918cfe7] Updating exception_cache and exception_season_cache
```
</details>

**Additional context**

**Comment by medariox** [comment]
Delete the anidb.dbm cache in your cache folder (Medusa/cache):
```
anidb.dbm.bak
anidb.dbm.dat
anidb.dbm.dir
```
and restart.
