### ISSUE TITLE
Multi edit of shows failing.

### ISSUE THREAD

**Issue by digitalgp** [pymedusa/Medusa#9071]
When trying to edit aprox 20-23 shows after filter for pause field set to y to get shows that are paused i press edit on all shows visible for the filter. Edit the pause parameter to NO and press submit. i then get the error below and shows are not updated.
I can do the same with one show from the same menu option and then it got changed.

2021-01-21 02:00:10 ERROR    Thread_0 :: [54da0c7] Exception generated: tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/manage/handler.py", line 691, in massEditSubmit
    errors += self.massEditShow(
  File "/opt/medusa/medusa/server/web/home/handler.py", line 959, in massEditShow
    series_obj.aliases = get_scene_exceptions(series_obj)
  File "/opt/medusa/medusa/tv/base.py", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/opt/medusa/medusa/tv/series.py", line 669, in aliases
    update_scene_exceptions(self, exceptions)
  File "/opt/medusa/medusa/scene_exceptions.py", line 233, in update_scene_exceptions
    if exception['title'] not in exceptions_cache[(series_obj.indexer, series_obj.series_id)][exception['season']]:
TypeError: tuple indices must be integers or slices, not str

Medusa Info: | Branch: masterCommit: 54da0c77d705a23f1ce67945ba4af3e1b978dcfcVersion: Unknown Database: 44.17
-- | --
Python Version: | 3.9.0 (default, Oct 7 2020, 23:09:01) [GCC 10.2.0]
SSL Version: | OpenSSL 1.1.1h 22 Sep 2020
OS: | Linux-5.10.1-Unraid-x86_64-with-glibc2.32
Locale: | en_GB.UTF-8

feel free to ask me on medusa discord for more info: nick: moviefan

**Comment by medariox** [comment]
This is fixed in the newest version, update.
