### ISSUE TITLE
Problem to get recommend trakt.tv working on New shows & Season Premieres

### ISSUE THREAD

**Issue by plsharevme** [pymedusa/Medusa#9076]
**Describe the bug**
when click add recommend show from trakt the new show and Season Premieres no working
it appear
Fetching of Recommender Data failed. Exception:
init() got an unexpected keyword argument 'returns'

**To Reproduce**
1. Go to 'shows'
2. Click on 'add recommend shows'
3. Clink on 'Add From Trakt Lists'
4. Select Trakt List select 'New Shows'

**Expected behavior**
It should be come out New Show recommend from Trakt.

**Screenshots**
https://nimbus-screenshots.s3.amazonaws.com/s/18683d2b550370c50dd6acfb8782ee68.png

**Medusa (please complete the following information):**
 - OS: [OMV docker]
 - Branch: [e.g. master]
 - Commit: [Unknown]
 - Python version: [GCC 9.3.0]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-01-21 13:29:10 ERROR	Thread-4 :: Could not connect to Trakt service: __init__() got an unexpected keyword argument 'returns'
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 128, in fetch_popular_shows
    shows = get_trakt_show_collection(trakt_list, limit)
  File "/app/medusa/medusa/helpers/trakt.py", line 53, in get_trakt_show_collection
    return calendar.PremiereCalendar(days=30, extended='full,images', returns='shows')
TypeError: __init__() got an unexpected keyword argument 'returns'
2021-01-21 13:28:48 INFO	APIv2-Thread-1 :: Broken providers found: ['']
2021-01-21 13:26:51 INFO	FINDSUBTITLES :: Finished checking for missed subtitles
2021-01-21 13:23:51 INFO	FINDSUBTITLES :: 305089: No subtitles found for Re:ZERO -Starting Life in Another World- (2016) S02E16
2021-01-21 13:23:51 INFO	FINDSUBTITLES :: No subtitles found for ReZERO -Starting Life in Another World- - S02E16 - The Stone of Kuwen Rises Not For One Person.mkv
2021-01-21 13:23:48 ERROR	Thread :: Could not connect to Trakt service: __init__() got an unexpected keyword argument 'returns'
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 128, in fetch_popular_shows
    shows = get_trakt_show_collection(trakt_list, limit)
  File "/app/medusa/medusa/helpers/trakt.py", line 53, in get_trakt_show_collection
    return calendar.PremiereCalendar(days=30, extended='full,images', returns='shows')
TypeError: __init__() got an unexpected keyword argument 'returns'
```
</details>

**Additional context**

**Comment by p0psicles** [comment]
Tested on develop branch.
Works fine here. Might want to try out develop, or wait for next release. But this should already work fine, if you've authorized trakt in config - notifications - trakt
