### ISSUE TITLE
Can't add torrents to transmission

### ISSUE THREAD

**Issue by zodiacuhd** [pymedusa/Medusa#9087]
`2021-01-22 17:16:44 ERROR    SNATCHQUEUE-SNATCH-253463 :: [2b874c2] Snatch failed! For result: Black.Mirror.S05.720p.NF.WEB.DDP5.1.x264-NTb[rartv]
Traceback (most recent call last):
  File "/usr/local/medusa/medusa/search/queue.py", line 516, in run
    self.success = snatch_episode(result)
  File "/usr/local/medusa/medusa/search/core.py", line 168, in snatch_episode
    result_downloaded = client.send_torrent(result)
  File "/usr/local/medusa/medusa/clients/torrent/generic.py", line 242, in send_torrent
    if not self._get_auth():
  File "/usr/local/medusa/medusa/clients/torrent/transmission.py", line 77, in _get_auth
    self.auth = re.search(r'X-Transmission-Session-Id:\s*(\w+)', self.response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'text'
`

Hello, after a fresh install of medusa on Freenas, i'm getting this error. I'm not sure what the issue might be.

Cheers

**Comment by medariox** [comment]
Transmission host was setup wrong. See example for correct way.
