### ISSUE TITLE
[APP SUBMITTED]: TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [pymedusa/Medusa#9139]
### INFO
**Python Version**: `3.8.7 (default, Dec 30 2020, 10:14:55) [Clang 12.0.0 (clang-1200.0.32.28)]`
**Operating System**: `macOS-11.1-x86_64-i386-64bit`
**Locale**: `UTF-8`
**Branch**: [feature/add-fdh](../tree/feature/add-fdh)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@004dbb45797f96e9a0517daecc08976a07594016
**Link to Log**: https://gist.github.com/d54c2a886e432bac3eccb3f2a12c8b61
### ERROR
<pre>
2021-01-29 15:08:50 ERROR    TORNADO :: [004dbb4] API :: TypeError("join() argument must be str, bytes, or os.PathLike object, not 'NoneType'")
Traceback (most recent call last):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/004dbb45797f96e9a0517daecc08976a07594016/medusa/server/api/v1/core.py#L165">medusa/server/api/v1/core.py</a>", line 165, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/004dbb45797f96e9a0517daecc08976a07594016/medusa/server/api/v1/core.py#L235">medusa/server/api/v1/core.py</a>", line 235, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/004dbb45797f96e9a0517daecc08976a07594016/medusa/server/api/v1/core.py#L1329">medusa/server/api/v1/core.py</a>", line 1329, in run
    data = app.post_processor_scheduler.action.run(
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/004dbb45797f96e9a0517daecc08976a07594016/medusa/process_tv.py#L181">medusa/process_tv.py</a>", line 181, in run
    process_results.process(force=force, **kwargs)
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/004dbb45797f96e9a0517daecc08976a07594016/medusa/process_tv.py#L310">medusa/process_tv.py</a>", line 310, in process
    for dir_path, filelist in self._get_files(path):
  File "/Users/ovidijus/Apps/Medusa/<a href="../blob/004dbb45797f96e9a0517daecc08976a07594016/medusa/process_tv.py#L433">medusa/process_tv.py</a>", line 433, in _get_files
    resource_name_is_folder = os.path.isdir(os.path.join(path, self.resource_name))
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by XxUnkn0wnxX** [comment]
not sure what happened @p0psicles, last few commits broke @clinton-hall scripts from running, not sure if this is intended or he needs to update his scripts? 

[Logs.zip](https://github.com/pymedusa/Medusa/files/5891610/Logs.zip)

**Comment by p0psicles** [comment]
This is definitely a Medusa issue, related to the fdh branch

**Comment by XxUnkn0wnxX** [comment]
issue resolved commit: ccc224842301e425403b46f80dd08a5db7810d3b
