### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [Errno 1] Operation not permitted: '/mnt/plexdrive/Anime/Season 01/The Hidden Dungeon Only I Can Enter - S01E02 - The Guild and the Receptionist.mkv'

### ISSUE THREAD

**Issue by gilberth** [pymedusa/Medusa#9153]
### INFO
**Python Version**: `3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]`
**Operating System**: `Linux-5.8.0-29-generic-x86_64-with-glibc2.32`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@2ab9d450d31f554cd77a5477d69f5555cbec6156
**Link to Log**: https://gist.github.com/f48a2059e20e543ea5920dd0946883cf
### ERROR
<pre>
2021-02-01 22:14:00 ERROR    POSTPROCESSOR :: [2ab9d45] OSError: PermissionError(1, 'Operation not permitted')
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/home/transmission/complete/[PuyaSubs!] Ore dake Haireru Kakushi Dungeon - 02 [ESP-ENG][1080p][F9183946].mkv' -> '/mnt/plexdrive/Anime/Season 01/The Hidden Dungeon Only I Can Enter - S01E02 - The Guild and the Receptionist.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/2ab9d450d31f554cd77a5477d69f5555cbec6156/medusa/helpers/__init__.py#L320">medusa/helpers/__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "/usr/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 1] Operation not permitted: '/mnt/plexdrive/Anime/Season 01/The Hidden Dungeon Only I Can Enter - S01E02 - The Guild and the Receptionist.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/2ab9d450d31f554cd77a5477d69f5555cbec6156/medusa/helpers/__init__.py#L293">medusa/helpers/__init__.py</a>", line 293, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 1] Operation not permitted: '/mnt/plexdrive/Anime/Season 01/The Hidden Dungeon Only I Can Enter - S01E02 - The Guild and the Receptionist.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
This is a permission issue. Not much we can do, see https://stackoverflow.com/questions/10937806/oserror-error-1-operation-not-permitted
