### ISSUE TITLE
Traktchecker not finding watchlist entries

### ISSUE THREAD

**Issue by jeffski10** [pymedusa/Medusa#9182]
**Describe the bug**
I've noticed that shows I added to my Watchlist do not get added to Medusa.   This seems to be recent as this was working after the new library was used. 

I see in the log:  
2021-02-08 19:11:10 INFO	TRAKTCHECKER :: [6b11b4d] No episodes found in your Trakt watchlist. Nothing to sync
2021-02-08 19:11:10 INFO	TRAKTCHECKER :: [6b11b4d] No shows found in your Trakt watchlist. Nothing to sync

Thinking it could be a corruption I created a new Trakt profile to test with, added one show and then connected and synced. The same still happens.     

I see that episode updates occur when snatched these get added to the watchlist and removed without issue.

Medusa Info: | Branch: develop
Commit: 6b11b4d638b988a87efe6fe084a47add78a00890
Version: 0.5.6
Database: 44.17
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-10-10.0.19041-SP0
Locale: | en_GB.cp1252

**Comment by fexofenadine** [comment]
I can't actually add new shows from Trakt recommenations at all, might be related? Invalid API key

2021-02-10 18:32:55 ERROR    Thread_17 :: [baad1e5] Could not connect to Trakt service: Forbidden - invalid API key or unapproved app
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 113, in fetch_popular_shows
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/ext/trakt/core.py", line 548, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 525, in _handle_request
    raise self.error_map[response.status_code]()
trakt.errors.ForbiddenException: Forbidden - invalid API key or unapproved app

**Comment by jeffski10** [comment]
@fexofenadine That works fine for me still - think you may just need to authenticate your medusa to your account now the login method changed.

**Comment by fexofenadine** [comment]
You were right, I needed to set up a Trakt notification. Strangely enough I have never had that set before (didn't even have a Trakt account) and recommendations still worked anonymously until recently.

Thanks for pointing me in the right direction

**Comment by jeffski10** [comment]
Just as an update on this, I added an episode to my watch list, it then found that episode, and added the show. So it seems to be just shows themselves it won't identify now for some reason.

**Comment by jeffski10** [comment]
So, thought I would have a go a debugging this.  With basic python skills I put in some print statements to see what was being returned from Trakt in case that was the issue and the response was bad.   I can see in trakt_checker.py  this block doing the sync.:
            if self._get_show_watchlist():
                log.debug('Syncing shows with Trakt watchlist ##')
                self.add_show_watchlist()
                self.sync_trakt_shows()

When the add_show_watchlist runs the  self.show_watchlist  object has the shows within  as I get this print statement: 
[<TVShow> Your Honor, <TVShow> Zack Snyder's Justice League, <TVShow> Prodigal Son, <TVShow> FBI: Most Wanted, <TVShow> Unforgotten]

But then the sync_trakt_shows() runs and the object is empty so the if not self.show_watchlist: check made fails and it does nothing. 
I dont see any changes in git on this code at all when the new trakt module was applied so its a bit weird and like the scope of the object is lost somehow. 
I'll keep digging as its a learning experience for me but thought I would post this in case it helps in any way (or if not ignore me!)

**Comment by p0psicles** [comment]
Your analysis put me on the right path. And I dove in my self.
I've created a branch, `feature/fix-trakt-sync`. If you could test that out? There were some other parts also broken. So i'd like to thouroughly test this, before merging to develop.

The pull request: https://github.com/pymedusa/Medusa/pull/9319

**Comment by jeffski10** [comment]
The sync worked first time and the shows in my test watchlist were synced back OK.   I then checked the add shows/recommended and tried to add an anticipated show.  This throws an error (although show is added to medusa):
Exception in thread SHOWQUEUE-ADD:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\Medusa\Medusa\medusa\queues\show_queue.py", line 457, in run
    series.sync_trakt()
  File "D:\Medusa\Medusa\medusa\tv\series.py", line 1944, in sync_trakt
    app.trakt_checker_scheduler.action.manage_new_show(self)
  File "D:\Medusa\Medusa\medusa\schedulers\trakt_checker.py", line 649, in manage_new_show
    episodes = [i for i in self.todo_wanted if i[0] == show.indexerid]
  File "D:\Medusa\Medusa\medusa\schedulers\trakt_checker.py", line 649, in <listcomp>
    episodes = [i for i in self.todo_wanted if i[0] == show.indexerid]
TypeError: 'int' object is not subscriptable

**Comment by p0psicles** [comment]
I pushed a commit which should fix this

**Comment by jeffski10** [comment]
That works now.  Adds show.  I noticed that the show is added to the watchlist, the individual episodes are not addes though they get set to wanted status.   If I force sync that doesn't change. 

I then added a new show to trakt, then force sync show is added, episodes set to Wanted but not added to list of Trakt.  So looks like the show level sync is working but maybe not the episode level?

**Comment by the-jeffski** [comment]
Actually scrub my comment above.  I copied the .py across to my installation running Master with a full watchlist and its working as expected for episodes and shows.

**Comment by jeffski10** [comment]
Actually scrub my comment above. I copied the .py across to my installation running Master with a full watchlist and its working as expected for episodes and shows.

**Comment by p0psicles** [comment]
I'll merge it to develop
