### ISSUE TITLE
Guessit error due to medusa's additional rules (apparently)

### ISSUE THREAD

**Issue by 007revad** [pymedusa/Medusa#9183]
**Describe the bug**
"The Watch (2021)" causes this same guessit error every time a new episode is downloaded by py-medusa. Medusa then seems to stop post-processing any more downloaded files until I restart medusa.

See [(https://github.com/guessit-io/guessit/issues/673)] for comments from guessit (staff?) who commented that "Medusa has some additional rules and most likely this bug should be reported in their repo".

**To Reproduce**
1. Add "The Watch (2021)"
2. Enable subtitles for "The Watch (2021)"
3. Wait for next episode to be downloaded.
4. See error.

**Expected behavior**
I expect medusa to fetch subtitles like it does for other shows. And not stop post-processing after a guessit error.

**Medusa (please complete the following information):**
 - OS: Synology Diskstation DSM 6.2.3-25426 Update 3 (the latest available for DS1812+)
 - Branch: master
 - Commit: 2ab9d450d31f554cd77a5477d69f5555cbec6156
 - Python version: 3.7.7
 - Database version: 44.17

**Debug logs (at least 50 lines):**
<details>

```
2021-02-08 13:20:39 ERROR    POSTPROCESSOR :: [2ab9d45] Exception generated: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.2.0
string=/volume1/nimbustor/video/TV-Series/The Watch (2021)/Season 1/The Watch (2021) S01E07 - Episode 7 (720p web h264)  [the.watch.2021.s01e07.720p.web.h264-ggez]
options={'expected_title': ['OSS 117', 'This is Us', 'Archer (2009)', 'Doctor Who 2005', 'Doctor Who (2005)', 'In the Dark (2019)', 'Wanted (2016)', 'Yellowstone (2018)', 'The 100', 'Utopia (2020)', 'Formula 1: Drive to Survive', '5th Gear', 'Street Outlaws-Memphis', 'The Grand Tour (2016)', 'Big Sky 2020', 'Big Sky (2020)', 'Warrior 2019', 'Warrior (2019)', 'The Stand (2020)', 'The Stand 2020', 'The Watch (2021)', 'The Watch 2020'], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und', 'jp'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_channels': {'1.0': ['1ch', 'mono'], '2.0': ['2ch', 'stereo', 're:(2[\\W_]0(?:ch)?)(?=[^\\d]|$)'], '5.1': ['5ch', '6ch', 're:(5[\\W_][01](?:ch)?)(?=[^\\d]|$)', 're:(6[\\W_]0(?:ch)?)(?=[^\\d]|$)'], '7.1': ['7ch', '8ch', 're:(7[\\W_][01](?:ch)?)(?=[^\\d]|$)']}}, 'container': {'subtitles': ['srt', 'idx', 'sub', 'ssa', 'ass'], 'info': ['nfo'], 'videos': ['3g2', '3gp', '3gp2', 'asf', 'avi', 'divx', 'flv', 'iso', 'm4v', 'mk2', 'mk3d', 'mka', 'mkv', 'mov', 'mp4', 'mp4a', 'mpeg', 'mpg', 'ogg', 'ogm', 'ogv', 'qt', 'ra', 'ram', 'rm', 'ts', 'vob', 'wav', 'webm', 'wma', 'wmv'], 'torrent': ['torrent'], 'nzb': ['nzb']}, 'country': {'synonyms': {'ES': ['españa'], 'GB': ['UK'], 'BR': ['brazilian', 'bra'], 'CA': ['québec', 'quebec', 'qc'], 'MX': ['Latinoamérica', 'latin america']}}, 'episodes': {'season_max_range': 100, 'episode_max_range': 100, 'max_range_gap': 1, 'season_markers': ['s'], 'season_ep_markers': ['x'], 'disc_markers': ['d'], 'episode_markers': ['xe', 'ex', 'ep', 'e', 'x'], 'range_separators': ['-', '~', 'to', 'a'], 'discrete_separators': ['+', '&', 'and', 'et'], 'season_words': ['season', 'saison', 'seizoen', 'seasons', 'saisons', 'tem', 'temp', 'temporada', 'temporadas', 'stagione'], 'episode_words': ['episode', 'episodes', 'eps', 'ep', 'episodio', 'episodios', 'capitulo', 'capitulos'], 'of_words': ['of', 'sur'], 'all_words': ['All']}, 'language': {'synonyms': {'ell': ['gr', 'greek'], 'spa': ['esp', 'español', 'espanol'], 'fra': ['français', 'vf', 'vff', 'vfi', 'vfq'], 'swe': ['se'], 'por_BR': ['po', 'pb', 'pob', 'ptbr', 'br', 'brazilian'], 'deu_CH': ['swissgerman', 'swiss german'], 'nld_BE': ['flemish'], 'cat': ['català', 'castellano', 'espanol castellano', 'español castellano'], 'ces': ['cz'], 'ukr': ['ua'], 'zho': ['cn'], 'jpn': ['jp'], 'hrv': ['scr'], 'mul': ['multi', 'dl']}, 'subtitle_affixes': ['sub', 'subs', 'esub', 'esubs', 'subbed', 'custom subbed', 'custom subs', 'custom sub', 'customsubbed', 'customsubs', 'customsub', 'soft subtitles', 'soft subs'], 'subtitle_prefixes': ['st', 'vost', 'subforced', 'fansub', 'hardsub', 'legenda', 'legendas', 'legendado', 'subtitulado', 'soft', 'subtitles'], 'subtitle_suffixes': ['subforced', 'fansub', 'hardsub'], 'language_affixes': ['dublado', 'dubbed', 'dub'], 'language_prefixes': ['true'], 'language_suffixes': ['audio'], 'weak_affixes': ['v', 'audio', 'true']}, 'part': {'prefixes': ['pt', 'part']}, 'release_group': {'forbidden_names': ['bonus', 'by', 'for', 'par', 'pour', 'rip'], 'ignored_seps': '[]{}()'}, 'screen_size': {'frame_rates': ['23.976', '24', '25', '29.970', '30', '48', '50', '60', '120'], 'min_ar': 1.333, 'max_ar': 1.8979999999999999, 'interlaced': ['360', '480', '576', '900', '1080'], 'progressive': ['360', '480', '540', '576', '900', '1080', '368', '720', '1440', '2160', '4320']}, 'website': {'safe_tlds': ['com', 'net', 'org'], 'safe_subdomains': ['www'], 'safe_prefixes': ['co', 'com', 'net', 'org'], 'prefixes': ['from']}, 'streaming_service': {'A&E': ['AE', 'A&E'], 'ABC': 'AMBC', 'ABC Australia': 'AUBC', 'Al Jazeera English': 'AJAZ', 'AMC': 'AMC', 'Amazon Prime': ['AMZN', 'Amazon', 're:Amazon-?Prime'], 'Adult Swim': ['AS', 're:Adult-?Swim'], "America's Test Kitchen": 'ATK', 'Animal Planet': 'ANPL', 'AnimeLab': 'ANLB', 'AOL': 'AOL', 'ARD': 'ARD', 'BBC iPlayer': ['iP', 're:BBC-?iPlayer'], 'BravoTV': 'BRAV', 'Canal+': 'CNLP', 'Cartoon Network': 'CN', 'CBC': 'CBC', 'CBS': 'CBS', 'CNBC': 'CNBC', 'Comedy Central': ['CC', 're:Comedy-?Central'], 'Channel 4': '4OD', 'CHRGD': 'CHGD', 'Cinemax': 'CMAX', 'Country Music Television': 'CMT', 'Comedians in Cars Getting Coffee': 'CCGC', 'Crunchy Roll': ['CR', 're:Crunchy-?Roll'], 'Crackle': 'CRKL', 'CSpan': 'CSPN', 'CTV': 'CTV', 'CuriosityStream': 'CUR', 'CWSeed': 'CWS', 'Daisuki': 'DSKI', 'DC Universe': 'DCU', 'Deadhouse Films': 'DHF', 'DramaFever': ['DF', 'DramaFever'], 'Digiturk Diledigin Yerde': 'DDY', 'Discovery': ['DISC', 'Discovery'], 'Disney': ['DSNY', 'Disney'], 'DIY Network': 'DIY', 'Doc Club': 'DOCC', 'DPlay': 'DPLY', 'E!': 'ETV', 'ePix': 'EPIX', 'El Trece': 'ETTV', 'ESPN': 'ESPN', 'Esquire': 'ESQ', 'Family': 'FAM', 'Family Jr': 'FJR', 'Food Network': 'FOOD', 'Fox': 'FOX', 'Freeform': 'FREE', 'FYI Network': 'FYI', 'Global': 'GLBL', 'GloboSat Play': 'GLOB', 'Hallmark': 'HLMK', 'HBO Go': ['HBO', 're:HBO-?Go'], 'HGTV': 'HGTV', 'History': ['HIST', 'History'], 'Hulu': 'HULU', 'Investigation Discovery': 'ID', 'IFC': 'IFC', 'iTunes': 'iTunes', 'ITV': 'ITV', 'Knowledge Network': 'KNOW', 'Lifetime': 'LIFE', 'Motor Trend OnDemand': 'MTOD', 'MBC': ['MBC', 'MBCVOD'], 'MSNBC': 'MNBC', 'MTV': 'MTV', 'National Geographic': ['NATG', 're:National-?Geographic'], 'NBA TV': ['NBA', 're:NBA-?TV'], 'NBC': 'NBC', 'Netflix': ['NF', 'Netflix'], 'NFL': 'NFL', 'NFL Now': 'NFLN', 'NHL GameCenter': 'GC', 'Nickelodeon': ['NICK', 'Nickelodeon'], 'Norsk Rikskringkasting': 'NRK', 'OnDemandKorea': ['ODK', 'OnDemandKorea'], 'PBS': 'PBS', 'PBS Kids': 'PBSK', 'Playstation Network': 'PSN', 'Pluzz': 'PLUZ', 'RTE One': 'RTE', 'SBS (AU)': 'SBS', 'SeeSo': ['SESO', 'SeeSo'], 'Shomi': 'SHMI', 'Spike': 'SPIK', 'Spike TV': ['SPKE', 're:Spike-?TV'], 'Sportsnet': 'SNET', 'Sprout': 'SPRT', 'Stan': 'STAN', 'Starz': 'STZ', 'Sveriges Television': 'SVT', 'SwearNet': 'SWER', 'Syfy': 'SYFY', 'TBS': 'TBS', 'TFou': 'TFOU', 'The CW': ['CW', 're:The-?CW'], 'TLC': 'TLC', 'TubiTV': 'TUBI', 'TV3 Ireland': 'TV3', 'TV4 Sweeden': 'TV4', 'TVING': 'TVING', 'TV Land': ['TVL', 're:TV-?Land'], 'UFC': 'UFC', 'UKTV': 'UKTV', 'Univision': 'UNIV', 'USA Network': 'USAN', 'Velocity': 'VLCT', 'VH1': 'VH1', 'Viceland': 'VICE', 'Viki': 'VIKI', 'Vimeo': 'VMEO', 'VRV': 'VRV', 'W Network': 'WNET', 'WatchMe': 'WME', 'WWE Network': 'WWEN', 'Xbox Video': 'XBOX', 'Yahoo': 'YHOO', 'YouTube Red': 'RED', 'ZDF': 'ZDF'}}, 'show_type': 'normal', 'type': 'episode', 'implicit': True, 'episode_prefer_number': False, 'expected_group': ['TV2LAX9', 'DHD', '20-40', 'E7']}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/ext/guessit/api.py", line 192, in guessit
    matches = self.rebulk.matches(string, options)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rebulk.py", line 115, in matches
    self._execute_rules(matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rebulk.py", line 146, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 312, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 337, in execute_rule
    rule.then(matches, when_response, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 118, in then
    cons.then(matches, next(iterator), context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 136, in then
    matches.remove(match)
  File "/var/packages/python3/target/lib/python3.7/_collections_abc.py", line 1004, in remove
    del self[self.index(value)]
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/match.py", line 561, in __delitem__
    self._remove_match(match)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/match.py", line 136, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/ext/guessit/api.py", line 192, in guessit
    matches = self.rebulk.matches(string, options)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rebulk.py", line 115, in matches
    self._execute_rules(matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rebulk.py", line 146, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 312, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 337, in execute_rule
    rule.then(matches, when_response, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 118, in then
    cons.then(matches, next(iterator), context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 136, in then
    matches.remove(match)
  File "/var/packages/python3/target/lib/python3.7/_collections_abc.py", line 1004, in remove
    del self[self.index(value)]
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/match.py", line 561, in __delitem__
    self._remove_match(match)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/match.py", line 136, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/medusa/schedulers/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 61, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 188, in process
    ignore_subs=ignore_subs)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 380, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/process_tv.py", line 600, in process_media
    self.result = processor.process()
  File "/volume1/@appstore/medusa/var/Medusa/medusa/post_processor.py", line 1286, in process
    notifiers.notify_download(ep_obj)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/notifiers/__init__.py", line 103, in notify_download
    n.notify_download(ep_obj)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/notifiers/synology_notifier.py", line 26, in notify_download
    ep_obj.pretty_name_with_quality())
  File "/volume1/@appstore/medusa/var/Medusa/medusa/tv/episode.py", line 1466, in pretty_name_with_quality
    return self._format_pattern('%SN - %Sx%0E - %EN - %QN')
  File "/volume1/@appstore/medusa/var/Medusa/medusa/tv/episode.py", line 1670, in _format_pattern
    replace_map = self.__replace_map()
  File "/volume1/@appstore/medusa/var/Medusa/medusa/tv/episode.py", line 1556, in __replace_map
    rel_grp['location'] = release_group(self.series, self.location)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/tv/episode.py", line 1536, in release_group
    parse_result = NameParser(series=series, naming_pattern=True).parse(name)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/name_parser/parser.py", line 400, in parse
    result = self._parse_string(name)
  File "/volume1/@appstore/medusa/var/Medusa/medusa/name_parser/parser.py", line 304, in _parse_string
    guess = guessit.guessit(name, dict(show_type=self.show_type))
  File "/volume1/@appstore/medusa/var/Medusa/medusa/name_parser/guessit_parser.py", line 86, in guessit
    result = default_api.guessit(name, options=final_options)
  File "/volume1/@appstore/medusa/var/Medusa/ext/guessit/api.py", line 204, in guessit
    raise GuessitException(string, options) from err
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.2.0
string=/volume1/nimbustor/video/TV-Series/The Watch (2021)/Season 1/The Watch (2021) S01E07 - Episode 7 (720p web h264)  [the.watch.2021.s01e07.720p.web.h264-ggez]
options={'expected_title': ['OSS 117', 'This is Us', 'Archer (2009)', 'Doctor Who 2005', 'Doctor Who (2005)', 'In the Dark (2019)', 'Wanted (2016)', 'Yellowstone (2018)', 'The 100', 'Utopia (2020)', 'Formula 1: Drive to Survive', '5th Gear', 'Street Outlaws-Memphis', 'The Grand Tour (2016)', 'Big Sky 2020', 'Big Sky (2020)', 'Warrior 2019', 'Warrior (2019)', 'The Stand (2020)', 'The Stand 2020', 'The Watch (2021)', 'The Watch 2020'], 'allowed_countries': ['au', 'gb', 'us'], 'allowed_languages': ['ca', 'cs', 'de', 'en', 'es', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'mul', 'nl', 'no', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'und', 'jp'], 'advanced_config': {'common_words': ['ca', 'cat', 'de', 'he', 'it', 'no', 'por', 'rum', 'se', 'st', 'sub'], 'groups': {'starting': '([{', 'ending': ')]}'}, 'audio_codec': {'audio_channels': {'1.0': ['1ch', 'mono'], '2.0': ['2ch', 'stereo', 're:(2[\\W_]0(?:ch)?)(?=[^\\d]|$)'], '5.1': ['5ch', '6ch', 're:(5[\\W_][01](?:ch)?)(?=[^\\d]|$)', 're:(6[\\W_]0(?:ch)?)(?=[^\\d]|$)'], '7.1': ['7ch', '8ch', 're:(7[\\W_][01](?:ch)?)(?=[^\\d]|$)']}}, 'container': {'subtitles': ['srt', 'idx', 'sub', 'ssa', 'ass'], 'info': ['nfo'], 'videos': ['3g2', '3gp', '3gp2', 'asf', 'avi', 'divx', 'flv', 'iso', 'm4v', 'mk2', 'mk3d', 'mka', 'mkv', 'mov', 'mp4', 'mp4a', 'mpeg', 'mpg', 'ogg', 'ogm', 'ogv', 'qt', 'ra', 'ram', 'rm', 'ts', 'vob', 'wav', 'webm', 'wma', 'wmv'], 'torrent': ['torrent'], 'nzb': ['nzb']}, 'country': {'synonyms': {'ES': ['españa'], 'GB': ['UK'], 'BR': ['brazilian', 'bra'], 'CA': ['québec', 'quebec', 'qc'], 'MX': ['Latinoamérica', 'latin america']}}, 'episodes': {'season_max_range': 100, 'episode_max_range': 100, 'max_range_gap': 1, 'season_markers': ['s'], 'season_ep_markers': ['x'], 'disc_markers': ['d'], 'episode_markers': ['xe', 'ex', 'ep', 'e', 'x'], 'range_separators': ['-', '~', 'to', 'a'], 'discrete_separators': ['+', '&', 'and', 'et'], 'season_words': ['season', 'saison', 'seizoen', 'seasons', 'saisons', 'tem', 'temp', 'temporada', 'temporadas', 'stagione'], 'episode_words': ['episode', 'episodes', 'eps', 'ep', 'episodio', 'episodios', 'capitulo', 'capitulos'], 'of_words': ['of', 'sur'], 'all_words': ['All']}, 'language': {'synonyms': {'ell': ['gr', 'greek'], 'spa': ['esp', 'español', 'espanol'], 'fra': ['français', 'vf', 'vff', 'vfi', 'vfq'], 'swe': ['se'], 'por_BR': ['po', 'pb', 'pob', 'ptbr', 'br', 'brazilian'], 'deu_CH': ['swissgerman', 'swiss german'], 'nld_BE': ['flemish'], 'cat': ['català', 'castellano', 'espanol castellano', 'español castellano'], 'ces': ['cz'], 'ukr': ['ua'], 'zho': ['cn'], 'jpn': ['jp'], 'hrv': ['scr'], 'mul': ['multi', 'dl']}, 'subtitle_affixes': ['sub', 'subs', 'esub', 'esubs', 'subbed', 'custom subbed', 'custom subs', 'custom sub', 'customsubbed', 'customsubs', 'customsub', 'soft subtitles', 'soft subs'], 'subtitle_prefixes': ['st', 'vost', 'subforced', 'fansub', 'hardsub', 'legenda', 'legendas', 'legendado', 'subtitulado', 'soft', 'subtitles'], 'subtitle_suffixes': ['subforced', 'fansub', 'hardsub'], 'language_affixes': ['dublado', 'dubbed', 'dub'], 'language_prefixes': ['true'], 'language_suffixes': ['audio'], 'weak_affixes': ['v', 'audio', 'true']}, 'part': {'prefixes': ['pt', 'part']}, 'release_group': {'forbidden_names': ['bonus', 'by', 'for', 'par', 'pour', 'rip'], 'ignored_seps': '[]{}()'}, 'screen_size': {'frame_rates': ['23.976', '24', '25', '29.970', '30', '48', '50', '60', '120'], 'min_ar': 1.333, 'max_ar': 1.8979999999999999, 'interlaced': ['360', '480', '576', '900', '1080'], 'progressive': ['360', '480', '540', '576', '900', '1080', '368', '720', '1440', '2160', '4320']}, 'website': {'safe_tlds': ['com', 'net', 'org'], 'safe_subdomains': ['www'], 'safe_prefixes': ['co', 'com', 'net', 'org'], 'prefixes': ['from']}, 'streaming_service': {'A&E': ['AE', 'A&E'], 'ABC': 'AMBC', 'ABC Australia': 'AUBC', 'Al Jazeera English': 'AJAZ', 'AMC': 'AMC', 'Amazon Prime': ['AMZN', 'Amazon', 're:Amazon-?Prime'], 'Adult Swim': ['AS', 're:Adult-?Swim'], "America's Test Kitchen": 'ATK', 'Animal Planet': 'ANPL', 'AnimeLab': 'ANLB', 'AOL': 'AOL', 'ARD': 'ARD', 'BBC iPlayer': ['iP', 're:BBC-?iPlayer'], 'BravoTV': 'BRAV', 'Canal+': 'CNLP', 'Cartoon Network': 'CN', 'CBC': 'CBC', 'CBS': 'CBS', 'CNBC': 'CNBC', 'Comedy Central': ['CC', 're:Comedy-?Central'], 'Channel 4': '4OD', 'CHRGD': 'CHGD', 'Cinemax': 'CMAX', 'Country Music Television': 'CMT', 'Comedians in Cars Getting Coffee': 'CCGC', 'Crunchy Roll': ['CR', 're:Crunchy-?Roll'], 'Crackle': 'CRKL', 'CSpan': 'CSPN', 'CTV': 'CTV', 'CuriosityStream': 'CUR', 'CWSeed': 'CWS', 'Daisuki': 'DSKI', 'DC Universe': 'DCU', 'Deadhouse Films': 'DHF', 'DramaFever': ['DF', 'DramaFever'], 'Digiturk Diledigin Yerde': 'DDY', 'Discovery': ['DISC', 'Discovery'], 'Disney': ['DSNY', 'Disney'], 'DIY Network': 'DIY', 'Doc Club': 'DOCC', 'DPlay': 'DPLY', 'E!': 'ETV', 'ePix': 'EPIX', 'El Trece': 'ETTV', 'ESPN': 'ESPN', 'Esquire': 'ESQ', 'Family': 'FAM', 'Family Jr': 'FJR', 'Food Network': 'FOOD', 'Fox': 'FOX', 'Freeform': 'FREE', 'FYI Network': 'FYI', 'Global': 'GLBL', 'GloboSat Play': 'GLOB', 'Hallmark': 'HLMK', 'HBO Go': ['HBO', 're:HBO-?Go'], 'HGTV': 'HGTV', 'History': ['HIST', 'History'], 'Hulu': 'HULU', 'Investigation Discovery': 'ID', 'IFC': 'IFC', 'iTunes': 'iTunes', 'ITV': 'ITV', 'Knowledge Network': 'KNOW', 'Lifetime': 'LIFE', 'Motor Trend OnDemand': 'MTOD', 'MBC': ['MBC', 'MBCVOD'], 'MSNBC': 'MNBC', 'MTV': 'MTV', 'National Geographic': ['NATG', 're:National-?Geographic'], 'NBA TV': ['NBA', 're:NBA-?TV'], 'NBC': 'NBC', 'Netflix': ['NF', 'Netflix'], 'NFL': 'NFL', 'NFL Now': 'NFLN', 'NHL GameCenter': 'GC', 'Nickelodeon': ['NICK', 'Nickelodeon'], 'Norsk Rikskringkasting': 'NRK', 'OnDemandKorea': ['ODK', 'OnDemandKorea'], 'PBS': 'PBS', 'PBS Kids': 'PBSK', 'Playstation Network': 'PSN', 'Pluzz': 'PLUZ', 'RTE One': 'RTE', 'SBS (AU)': 'SBS', 'SeeSo': ['SESO', 'SeeSo'], 'Shomi': 'SHMI', 'Spike': 'SPIK', 'Spike TV': ['SPKE', 're:Spike-?TV'], 'Sportsnet': 'SNET', 'Sprout': 'SPRT', 'Stan': 'STAN', 'Starz': 'STZ', 'Sveriges Television': 'SVT', 'SwearNet': 'SWER', 'Syfy': 'SYFY', 'TBS': 'TBS', 'TFou': 'TFOU', 'The CW': ['CW', 're:The-?CW'], 'TLC': 'TLC', 'TubiTV': 'TUBI', 'TV3 Ireland': 'TV3', 'TV4 Sweeden': 'TV4', 'TVING': 'TVING', 'TV Land': ['TVL', 're:TV-?Land'], 'UFC': 'UFC', 'UKTV': 'UKTV', 'Univision': 'UNIV', 'USA Network': 'USAN', 'Velocity': 'VLCT', 'VH1': 'VH1', 'Viceland': 'VICE', 'Viki': 'VIKI', 'Vimeo': 'VMEO', 'VRV': 'VRV', 'W Network': 'WNET', 'WatchMe': 'WME', 'WWE Network': 'WWEN', 'Xbox Video': 'XBOX', 'Yahoo': 'YHOO', 'YouTube Red': 'RED', 'ZDF': 'ZDF'}}, 'show_type': 'normal', 'type': 'episode', 'implicit': True, 'episode_prefer_number': False, 'expected_group': ['TV2LAX9', 'DHD', '20-40', 'E7']}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/ext/guessit/api.py", line 192, in guessit
    matches = self.rebulk.matches(string, options)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rebulk.py", line 115, in matches
    self._execute_rules(matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rebulk.py", line 146, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 312, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 337, in execute_rule
    rule.then(matches, when_response, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 118, in then
    cons.then(matches, next(iterator), context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/rules.py", line 136, in then
    matches.remove(match)
  File "/var/packages/python3/target/lib/python3.7/_collections_abc.py", line 1004, in remove
    del self[self.index(value)]
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/match.py", line 561, in __delitem__
    self._remove_match(match)
  File "/volume1/@appstore/medusa/var/Medusa/ext/rebulk/match.py", line 136, in _remove_match
    _BaseMatches._base_remove(self._tag_dict[tag], match)
ValueError: list.remove(x): x not in list
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================
```
</details>

**Additional context**
This problem started after a medusa update (about 3 updates ago) in maybe October or November.

I can live with not getting subtitles for some shows, but having to restart medusa to get post-processing working again is very annoying.

**Comment by medariox** [comment]
Interesting naming you got there 😃 Thanks for the report, will be fixed with https://github.com/pymedusa/Medusa/issues/9183

**Comment by 007revad** [comment]
Thanks medariox.

I retain the original filename for a number of reasons:
- In case I later need to reseed a file.
-  It's also handy when medusa names them hdtv even though the original filename includes web.
-  Or web files contain channel logos so I can see which group to avoid.
