### ISSUE TITLE
[APP SUBMITTED]: TypeError: backlogShow() got an unexpected keyword argument 'showslug'

### ISSUE THREAD

**Issue by ac3nl** [pymedusa/Medusa#9208]
### INFO
**Python Version**: `3.6.8 (default, Feb 13 2019, 20:48:47) [GCC 4.7.3 20130102 (prerelease)]`
**Operating System**: `Linux-3.10.35-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-02-12 06:53:49 ERROR    Thread_13 :: [b21beeb] Exception generated: backlogShow() got an unexpected keyword argument 'showslug'
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: backlogShow() got an unexpected keyword argument 'showslug'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by snpster** [comment]
I can also generate this after going to the 'Backlog Overview' page. and clicking 'Force Backlog' on any show.

**Comment by p0psicles** [comment]
Tnx I'll fix it

**Comment by adix** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-02-12 18:20:03 ERROR    Thread_7 :: [b21beeb] Exception generated: backlogShow() got an unexpected keyword argument 'showslug'
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
TypeError: backlogShow() got an unexpected keyword argument 'showslug'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Fixed in develop branch. Sorry but it might take a few weeks before merged to master.

**Comment by ac3nl** [comment]
That is too bad, as backlog is now broken...

**Comment by medariox** [comment]
It's not. Just the forced backlog search (which should be only used very rarely anyway).

**Comment by rikbon** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-5.10.16-v7l+-armv7l-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/d1d466c342812dd440c46ade2da6dc76
### ERROR
<pre>
2021-02-21 01:41:16 ERROR    Thread_0 :: [] Exception generated: backlogShow() got an unexpected keyword argument 'showslug'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
TypeError: backlogShow() got an unexpected keyword argument 'showslug'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by rikbon** [comment]
### INFO
**Python Version**: `3.8.5 (default, Jul 20 2020, 23:11:29) [GCC 9.3.0]`
**Operating System**: `Linux-5.10.16-v7l+-armv7l-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/49970ee74028b1498fb2bffdaf24db50
### ERROR
<pre>
2021-02-22 23:45:22 ERROR    Thread_0 :: [] Exception generated: backlogShow() got an unexpected keyword argument 'showslug'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
TypeError: backlogShow() got an unexpected keyword argument 'showslug'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
