### ISSUE TITLE
[APP SUBMITTED]: dbm.error: db type is dbm.gnu, but the module is not available

### ISSUE THREAD

**Issue by Volodesi** [pymedusa/Medusa#9219]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-02-13 19:53:38 ERROR    Thread_1 :: [b21beeb] Exception generated: db type is dbm.gnu, but the module is not available
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/home/handler.py#L1511">medusa\server\web\home\handler.py</a>", line 1511, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "<C:\Medusa\Medusa\ext\decorator.py:decorator-gen-14>", line 2, in get_release_groups_for_anime
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/ext/dogpile/cache/region.py#L1578">ext\dogpile\cache\region.py</a>", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/ext/dogpile/cache/region.py#L1047">ext\dogpile\cache\region.py</a>", line 1047, in get_or_create
    async_creator,
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/ext/dogpile/lock.py#L185">ext\dogpile\lock.py</a>", line 185, in __enter__
    return self._enter()
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/ext/dogpile/lock.py#L87">ext\dogpile\lock.py</a>", line 87, in _enter
    value = value_fn()
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/ext/dogpile/cache/region.py#L977">ext\dogpile\cache\region.py</a>", line 977, in get_value
    value = self._get_from_backend(key)
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/ext/dogpile/cache/region.py#L1265">ext\dogpile\cache\region.py</a>", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/ext/dogpile/cache/backends/file.py#L217">ext\dogpile\cache\backends\file.py</a>", line 217, in get_serialized
    with self._dbm_file(False) as dbm_obj:
  File "C:\Medusa\Python\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/ext/dogpile/cache/backends/file.py#L213">ext\dogpile\cache\backends\file.py</a>", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
  File "C:\Medusa\Python\lib\dbm\__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Same fix as https://github.com/pymedusa/Medusa/issues/9070#issuecomment-764062860
