### ISSUE TITLE
help unable to get medusa to start post update to newest version

### ISSUE THREAD

**Issue by xmetisx** [pymedusa/Medusa#9237]
Used update feature inside medusa. Never came back. Tried removing .pyc and git fetch origin
git reset --hard origin/master.  Still not working.  Was working great prior to update.  Starting with systemd but have also tried manually using /usr/bin/python3 /opt/medusa/start.py --datadir=/opt/medusa

**Medusa (please complete the following information):**
 - OS: Debian Linux 9
 - Branch: master
 - Commit: b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
 - Python version: Python 3.8.6rc1
 - Database version: not sure...

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug

<details>

```
 Started Medusa Daemon.
Feb 17 18:37:52 fallen python3[12469]: Traceback (most recent call last):
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/start.py", line 6, in <module>
Feb 17 18:37:52 fallen python3[12469]:     from medusa.__main__ import main
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/medusa/__init__.py", line 24, in <module>
Feb 17 18:37:52 fallen python3[12469]:     initialize()
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/medusa/init/__init__.py", line 37, in initialize
Feb 17 18:37:52 fallen python3[12469]:     _configure_guessit()
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/medusa/init/__init__.py", line 202, in _configure_guessit
Feb 17 18:37:52 fallen python3[12469]:     from medusa.name_parser.guessit_parser import (
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/medusa/name_parser/guessit_parser.py", line 12, in <module>
Feb 17 18:37:52 fallen python3[12469]:     from medusa.logger.adapters.style import BraceAdapter
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/medusa/logger/__init__.py", line 44, in <module>
Feb 17 18:37:52 fallen python3[12469]:     import knowit
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/ext/knowit/__init__.py", line 27, in <module>
Feb 17 18:37:52 fallen python3[12469]:     from .api import KnowitException, know
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/ext/knowit/api.py", line 8, in <module>
Feb 17 18:37:52 fallen python3[12469]:     from .providers import (
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/ext/knowit/providers/__init__.py", line 7, in <module>
Feb 17 18:37:52 fallen python3[12469]:     from .mediainfo import MediaInfoProvider
Feb 17 18:37:52 fallen python3[12469]:   File "/opt/medusa/ext/knowit/providers/mediainfo.py", line 5, in <module>
Feb 17 18:37:52 fallen python3[12469]:     from ctypes import c_void_p, c_wchar_p
Feb 17 18:37:52 fallen python3[12469]:   File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
Feb 17 18:37:52 fallen python3[12469]:     from _ctypes import Union, Structure, Array
Feb 17 18:37:52 fallen python3[12469]: ModuleNotFoundError: No module named '_ctypes'
Feb 17 18:37:52 fallen systemd[1]: medusa.service: Main process exited, code=exited, status=1/FAILURE
Feb 17 18:37:52 fallen systemd[1]: medusa.service: Unit entered failed state.
Feb 17 18:37:52 fallen systemd[1]: medusa.service: Failed with result 'exit-code'.
Feb 17 18:37:52 fallen systemd[1]: medusa.service: Service hold-off time over, scheduling restart.
Feb 17 18:37:52 fallen systemd[1]: Stopped Medusa Daemon.
Feb 17 18:37:52 fallen systemd[1]: medusa.service: Start request repeated too quickly.
Feb 17 18:37:52 fallen systemd[1]: Failed to start Medusa Daemon.
Feb 17 18:37:52 fallen systemd[1]: medusa.service: Unit entered failed state.
Feb 17 18:37:52 fallen systemd[1]: medusa.service: Failed with result 'exit-code'.
Feb 17 18:37:56 fallen sudo[12474]:    metis : TTY=pts/0 ; PWD=/etc/systemd/system ; USER=root ; COMMAND=/bin/systemctl status medusa.service
Feb 17 18:37:56 fallen sudo[12474]: pam_unix(sudo:session): session opened for user root by metis(uid=0)

```
</details>

**Additional context**
Because it won't actually start up i don't actually have any logs, or the ability to toggle the advanced logs :(

**Comment by xmetisx** [comment]
removed and reinstalled python3.8.6 and all dependencies. fixed
