### ISSUE TITLE
[APP SUBMITTED]: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by gilberth** [pymedusa/Medusa#9245]
### INFO
**Python Version**: `3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-65-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: https://gist.github.com/8404c05fdb159e775103c6ab0e706870
### ERROR
<pre>
2021-02-20 01:04:30 ERROR    Thread_0 :: [b21beeb] Exception generated: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/server/web/home/post_process.py#L52">medusa/server/web/home/post_process.py</a>", line 52, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/process_tv.py#L61">medusa/process_tv.py</a>", line 61, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/process_tv.py#L189">medusa/process_tv.py</a>", line 189, in process
    self._clean_up(dir_path, proc_type, delete=delete_on)
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/process_tv.py#L236">medusa/process_tv.py</a>", line 236, in _clean_up
    os.path.normpath(path) != os.path.normpath(app.TV_DOWNLOAD_DIR)]):
  File "/usr/lib/python3.8/posixpath.py", line 336, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Please post the complete debug log (upload the whole file if possible) when this error occurred.

**Comment by akosasante** [comment]
### INFO
**Python Version**: `3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-02-22 22:49:36 ERROR    Thread_0 :: [b21beeb] Exception generated: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/**********/server/web/core/base.py#L252">**********\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "D:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/**********/server/web/home/post_process.py#L52">**********\server\web\home\post_process.py</a>", line 52, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "D:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/**********/process_tv.py#L61">**********\process_tv.py</a>", line 61, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "D:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/**********/process_tv.py#L189">**********\process_tv.py</a>", line 189, in process
    self._clean_up(dir_path, proc_type, delete=delete_on)
  File "D:\Medusa\Medusa\<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/**********/process_tv.py#L236">**********\process_tv.py</a>", line 236, in _clean_up
    os.path.normpath(path) != os.path.normpath(app.TV_DOWNLOAD_DIR)]):
  File "C:\Users\Cam\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Still waiting for a full debug log.

**Comment by akosasante** [comment]
@medariox Sorry about that, I ended up figuring out last night.

The line `os.path.normpath(app.TV_DOWNLOAD_DIR)])` led me to realize that the post-processing menu no longer had the expected download directory filled in. I'm not sure what happened to cause that value to get erased, but after entering the value in there again I was able to run manual post-processing successfully. 

Perhaps it could log a clearer error message if the post-processing directory field is blank/empty string?

**Comment by walterhpdx** [comment]
I've been experiencing this issue since about the switch over to Python 3, and have just enabled debug. When it happens in the next few hours, I'll submit debug logs.

**Comment by walterhpdx** [comment]
Actually since mine can be triggered on demand via the "Set episode status" and the debug is slightly different, I'll upload as a new issue, though it might be related to this one.

**Comment by medariox** [comment]
@walterhpdx Is it this one? https://github.com/pymedusa/Medusa/issues/9213
If yes, already fixed (will be available with the next release) in develop and unrelated to this issue.

**Comment by walterhpdx** [comment]
Yes, it’s that one, so I won’t open a new issue.  But this is just one of multiple Python errors I’m seeing.  I’ll leave debug on to recreate the others.  It’s when an episode is snatched but never actually gets snatched and throws a Python error.

walter

**Comment by adix** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@55cecb9e821fb15f20efe75b0f59d13e896e1d87
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-03-20 13:46:46 ERROR    TORNADO :: [55cecb9] API :: TypeError('expected str, bytes or os.PathLike object, not NoneType')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/server/api/v1/core.py#L165">medusa\server\api\v1\core.py</a>", line 165, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/server/api/v1/core.py#L235">medusa\server\api\v1\core.py</a>", line 235, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "C:\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/server/api/v1/core.py#L1336">medusa\server\api\v1\core.py</a>", line 1336, in run
    proc_type=self.type
  File "C:\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/process_tv.py#L196">medusa\process_tv.py</a>", line 196, in run
    process_results.process(force=force, **kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/process_tv.py#L345">medusa\process_tv.py</a>", line 345, in process
    self._clean_up(dir_path, proc_type, delete=delete_on)
  File "C:\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/process_tv.py#L397">medusa\process_tv.py</a>", line 397, in _clean_up
    os.path.normpath(path) != os.path.normpath(app.TV_DOWNLOAD_DIR)]):
  File "C:\Medusa\Python\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by elykkyle** [comment]
### INFO
**Python Version**: `3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@55cecb9e821fb15f20efe75b0f59d13e896e1d87
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-04-07 20:43:55 ERROR    Thread_0 :: [55cecb9] Exception generated: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\Program Files\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/server/web/core/base.py#L252">medusa\server\web\core\base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "D:\Program Files\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/server/web/home/post_process.py#L100">medusa\server\web\home\post_process.py</a>", line 100, in processEpisode
    result = app.post_processor_scheduler.action.run(
  File "D:\Program Files\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/process_tv.py#L196">medusa\process_tv.py</a>", line 196, in run
    process_results.process(force=force, **kwargs)
  File "D:\Program Files\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/process_tv.py#L345">medusa\process_tv.py</a>", line 345, in process
    self._clean_up(dir_path, proc_type, delete=delete_on)
  File "D:\Program Files\Medusa\Medusa\<a href="../blob/55cecb9e821fb15f20efe75b0f59d13e896e1d87/medusa/process_tv.py#L397">medusa\process_tv.py</a>", line 397, in _clean_up
    os.path.normpath(path) != os.path.normpath(app.TV_DOWNLOAD_DIR)]):
  File "C:\Program Files\Python38\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by adix** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@25e7b6072201a8a73e1220ee5ffe13cbefce45f8
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-08-14 20:32:52 ERROR    TORNADO :: [25e7b60] API :: TypeError('expected str, bytes or os.PathLike object, not NoneType')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/server/api/v1/core.py#L165">medusa\server\api\v1\core.py</a>", line 165, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/server/api/v1/core.py#L235">medusa\server\api\v1\core.py</a>", line 235, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/server/api/v1/core.py#L1336">medusa\server\api\v1\core.py</a>", line 1336, in run
    proc_type=self.type
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/process_tv.py#L208">medusa\process_tv.py</a>", line 208, in run
    process_results.process(force=force, **kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/process_tv.py#L361">medusa\process_tv.py</a>", line 361, in process
    self._clean_up(dir_path, proc_type, delete=delete_on)
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/process_tv.py#L413">medusa\process_tv.py</a>", line 413, in _clean_up
    os.path.normpath(path) != os.path.normpath(app.TV_DOWNLOAD_DIR)]):
  File "C:\Medusa\Python\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by adix** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-7-6.1.7601-SP1`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@25e7b6072201a8a73e1220ee5ffe13cbefce45f8
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-08-15 06:05:55 ERROR    TORNADO :: [25e7b60] API :: TypeError('expected str, bytes or os.PathLike object, not NoneType')
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/server/api/v1/core.py#L165">medusa\server\api\v1\core.py</a>", line 165, in get
    out_dict = _call_dispatcher(args, kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/server/api/v1/core.py#L235">medusa\server\api\v1\core.py</a>", line 235, in call_dispatcher
    cur_out_dict = func(cur_args, cur_kwargs).run()  # call function and get response
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/server/api/v1/core.py#L1336">medusa\server\api\v1\core.py</a>", line 1336, in run
    proc_type=self.type
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/process_tv.py#L208">medusa\process_tv.py</a>", line 208, in run
    process_results.process(force=force, **kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/process_tv.py#L361">medusa\process_tv.py</a>", line 361, in process
    self._clean_up(dir_path, proc_type, delete=delete_on)
  File "C:\Medusa\Medusa\<a href="../blob/25e7b6072201a8a73e1220ee5ffe13cbefce45f8/medusa/process_tv.py#L413">medusa\process_tv.py</a>", line 413, in _clean_up
    os.path.normpath(path) != os.path.normpath(app.TV_DOWNLOAD_DIR)]):
  File "C:\Medusa\Python\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
