### ISSUE TITLE
Cannot Create Issue from ERROR anymore in the GUI

### ISSUE THREAD

**Issue by udochrist** [pymedusa/Medusa#9246]
**Describe the bug**
In case there's an error logged i see the button to create an Issue with medusa on github. when i click the button i get the following log:

```
2021-02-20 08:14:43 WARNING  Thread_14 :: [b21beeb] GitHub returned an error "Not Found". If using a token, make sure the proper scopes are selected.
```

**To Reproduce**
1. Produce an Error
2. Create Issue

**Expected behavior**
The Error should be reported (pr possible being flagged as already reported

**Screenshots**
N/A

**Medusa (please complete the following information):**
Medusa 0.5.8 
Latest official Docker image

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-02-20 08:14:22 DEBUG    Thread_14 :: [b21beeb] Searching for issues similar to:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-02-20 08:14:36 DEBUG    Thread_14 :: [b21beeb] Found 0 similar issues for 1 log lines.
2021-02-20 08:14:36 DEBUG    Thread_14 :: [b21beeb] Creating gist for error: 2021-02-19 00:32:46 ERROR    Thread_16 :: [b21beeb] Exception generated: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/post_process.py", line 61, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 61, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/app/medusa/medusa/process_tv.py", line 188, in process
    ignore_subs=ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 380, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 600, in process_media
    self.result = processor.process()
  File "/app/medusa/medusa/post_processor.py", line 1300, in process
    notifiers.trakt_notifier.update_library(ep_obj)
  File "/app/medusa/medusa/notifiers/trakt.py", line 83, in update_library
    sync.add_to_collection(data)
  File "/app/medusa/ext/trakt/core.py", line 583, in inner
    json_data = self._handle_request('post', url, data=args)
  File "/app/medusa/ext/trakt/core.py", line 528, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-02-20 08:14:43 DEBUG    Thread_14 :: [b21beeb] Creating issue data for error: 2021-02-19 00:32:46 ERROR    Thread_16 :: [b21beeb] Exception generated: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/post_process.py", line 61, in processEpisode
    ignore_subs=argToBool(ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 61, in run
    return ProcessResult(path, process_method).process(force=force, **kwargs)
  File "/app/medusa/medusa/process_tv.py", line 188, in process
    ignore_subs=ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 380, in process_files
    self.process_media(path, self.video_files, force, is_priority, ignore_subs)
  File "/app/medusa/medusa/process_tv.py", line 600, in process_media
    self.result = processor.process()
  File "/app/medusa/medusa/post_processor.py", line 1300, in process
    notifiers.trakt_notifier.update_library(ep_obj)
  File "/app/medusa/medusa/notifiers/trakt.py", line 83, in update_library
    sync.add_to_collection(data)
  File "/app/medusa/ext/trakt/core.py", line 583, in inner
    json_data = self._handle_request('post', url, data=args)
  File "/app/medusa/ext/trakt/core.py", line 528, in _handle_request
    json_data = json.loads(response.content.decode('UTF-8', 'ignore'))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-02-20 08:14:43 DEBUG    Thread_14 :: [b21beeb] Issue submitter failed with error: UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'})
2021-02-20 08:14:43 WARNING  Thread_14 :: [b21beeb] GitHub returned an error "Not Found". If using a token, make sure the proper scopes are selected.
2021-02-20 08:14:50 DEBUG    Thread_18 :: [b21beeb] GET URL: https://cdn.pymedusa.com/providers/broken_providers.json [Status: 200]
2021-02-20 08:14:50 DEBUG    Thread_18 :: [b21beeb] User-Agent: Medusa/0.5.8 (Linux; 3.10.105; 26a876de-6ed0-11eb-acb3-0242ac120005)
2021-02-20 08:14:50 INFO     Thread_18 :: [b21beeb] Broken providers found: ['']
2021-02-20 08:15:22 DEBUG    Thread_2 :: [b21beeb] Broken providers already updated in the last hour```
</details>

**Additional context**
Add any other context about the problem here.

**Comment by medariox** [comment]
You need to autenticate with a GitHub personal access token, using user and pass is deprecated.

**Comment by udochrist** [comment]
Thanks for the info:

Deprecated? What? You mean **no longer supported.**

BTW;
It would be good to remove the username / pw field from the gui as these options are confusing if they are no longer supporte and claim to be required.....

![Screenshot 2021-02-21 at 15 15 09](https://user-images.githubusercontent.com/869637/108627926-3b8d6b80-7458-11eb-879d-8ef9f49e8d3f.png)

**Comment by medariox** [comment]
It is deprecated by the GitHub API. I mean **deprecated**.

**Comment by udochrist** [comment]
You mean **removed** as per GitHub Post talking about the deprecation timeline.

Anyway i stand by my screenshot:
The username/pw fields (and the "REQUIRED FOR SUBMITTING ISSUES" label) should be removed to not confuse users...
