### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 16] Device or resource busy: '/mnt/titan1/downloads/complete/American.Gods.S03E06.1080p.WEB.H264-GLHF[rarbg]/american.gods.s03e06.1080p.web.h264-glhf.mkv'

### ISSUE THREAD

**Issue by yrtria** [pymedusa/Medusa#9253]
### INFO
**Python Version**: `3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-65-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.17`
**Commit**: pymedusa/Medusa@b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9
**Link to Log**: https://gist.github.com/e7243db23cd14e223a637ae9662f64c8
### ERROR
<pre>
2021-02-22 13:40:11 ERROR    POSTPROCESSOR :: [b21beeb] Unable to move file /mnt/titan1/downloads/complete/American.Gods.S03E06.1080p.WEB.H264-GLHF[rarbg]/american.gods.s03e06.1080p.web.h264-glhf.mkv to /mnt/titan2/TVShows2/American Gods/American Gods - 3x06 - Conscience of the King.mkv: OSError(16, 'Device or resource busy')
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/mnt/titan1/downloads/complete/American.Gods.S03E06.1080p.WEB.H264-GLHF[rarbg]/american.gods.s03e06.1080p.web.h264-glhf.mkv' -> '/mnt/titan2/TVShows2/American Gods/American Gods - 3x06 - Conscience of the King.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/helpers/__init__.py#L320">medusa/helpers/__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "/usr/lib/python3.8/shutil.py", line 803, in move
    os.unlink(src)
OSError: [Errno 16] Device or resource busy: '/mnt/titan1/downloads/complete/American.Gods.S03E06.1080p.WEB.H264-GLHF[rarbg]/american.gods.s03e06.1080p.web.h264-glhf.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/post_processor.py#L477">medusa/post_processor.py</a>", line 477, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/opt/medusa/<a href="../blob/b21beeb3be5c7e1dec8cbe4bfc13b565b1e1a0b9/medusa/helpers/__init__.py#L324">medusa/helpers/__init__.py</a>", line 324, in move_file
    os.unlink(src_file)
OSError: [Errno 16] Device or resource busy: '/mnt/titan1/downloads/complete/American.Gods.S03E06.1080p.WEB.H264-GLHF[rarbg]/american.gods.s03e06.1080p.web.h264-glhf.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
See https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link
We already pretty much do all that's in our possibilities. Consider using a different post-processing method.
