### ISSUE TITLE
Constant warnings on ShowQueue refresh (and others)

### ISSUE THREAD

**Issue by dirkronsmans** [pymedusa/Medusa#9306]
**Describe the bug**
My system is throwing constant warnings

**Medusa (please complete the following information):**

Medusa Info: | 
Branch:                 master                  Commit:                 55cecb9e821fb15f20efe75b0f59d13e896e1d87                 
Version:                 0.5.10                  Database:                 44.18
Python Version: | 3.7.7 (default, Oct 13 2020, 16:39:42)  [GCC 4.9.3 20150311 (prerelease)]
SSL Version: | OpenSSL 1.1.1h  22 Sep 2020
OS: | Linux-4.4.59+-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-03-05 03:28:23 WARNING	SHOWQUEUE-REFRESH :: [55cecb9] Unexpected error. Failed to refine video '/volume1/Shared/somefile.mp4'
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/ext/subliminal/core.py", line 549, in refine
    refiner_manager[refiner].plugin(video, **dict((refiner_configs or {}).get(refiner, {}), **kwargs))
  File "/volume1/@appstore/medusa/var/src/ext/subliminal/refiners/tvdb.py", line 275, in refine
    results = search_series(video.series.lower())
  File "</volume1/@appstore/medusa/var/src/ext/decorator.py:decorator-gen-9>", line 2, in search_series
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1047, in get_or_create
    async_creator,
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/var/packages/python3/target/lib/python3.7/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
</details>

**Additional context**
While it doesn't give errors it does throw these warnings all the time.
Anybody got a clue what's going on? Seems not just related to the showqueue refresh but also other calls give the same error.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by p0psicles** [comment]
Probably your dogpile cache files are corrupt. 
Stop Medusa. 
In cache folder remove the *.dbm files. And start

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/search?q=UnicodeDecodeError%3A+%27utf-8%27+codec+can%27t+decode+byte+0x80+in+position+0&type=issues
