### ISSUE TITLE
Failed to get release groups for show

### ISSUE THREAD

**Issue by Greatmangaka** [pymedusa/Medusa#9318]
Hi,

Each time I want to edit an anime I have an error getting the release groups list. And it is the same when I want to add a new show with a whitelist release groups.

So I cannot add or modify the release groups whitelist.

Medusa
 - OS: Ubuntu 20.10
 - Branch: master
 - Commit: 0.5.10 (01-03-2021)
 - Python version: 3.8

Debug logs : 

2021-03-07 09:57:05 ERROR    Thread_0 :: [55cecb9] Exception generated: decode() argument 'encoding' must be str, not None
Traceback (most recent call last):
  File "/opt/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/opt/medusa/medusa/server/web/home/handler.py", line 1691, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</opt/medusa/ext/decorator.py:decorator-gen-15>", line 2, in get_release_groups_for_anime
  File "/opt/medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/opt/medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/opt/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/opt/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/opt/medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/opt/medusa/ext/dogpile/cache/region.py", line 1264, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/opt/medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.8/json/__init__.py", line 344, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
TypeError: decode() argument 'encoding' must be str, not None

Any Idea to solve the problem ?

Thanks

**Comment by medariox** [comment]
Have you tried searching before opening this issue?
https://github.com/pymedusa/Medusa/issues/9070#issuecomment-764062860

**Comment by Greatmangaka** [comment]
Yes I did but I did not find this topic since I searched with the error message and in that topic they were in a screenshot so they would not appear in the search results... 

Thank you I will  try that.
