### ISSUE TITLE
Animebytes provider daily search error

### ISSUE THREAD

**Issue by Entixs** [pymedusa/Medusa#9320]
**Describe the bug**

**To Reproduce**
It is the daily search on this provider. After daily search is done it usually happens

**Expected behavior**
Daily search should go without a hitch and shouldn't be having errors.

**Screenshots**

**Medusa (please complete the following information):**
 - OS: Linux-5.8.0-44-generic-x86_64-with-glibc2.32
 - Branch: develop
 - Commit: 2cefd1f5f90407ecb795d4d10cdb0fcb93fd5668
 - Python version: 3.8.6
 - Database version: 44.18

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-03-07 08:53:03 INFO     SEARCHQUEUE-DAILY-SEARCH :: [2cefd1f] Using daily search providers
2021-03-07 08:53:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [2cefd1f] Updating providers cache
2021-03-07 08:53:03 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [2cefd1f] Search Mode: RSS
2021-03-07 08:53:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [2cefd1f] GET URL: https://animebytes.tv/scrape.php?filter_cat%5B1%5D=1&filter_cat%5B5%5D=1&action=advanced&search_type=title&year=&year2=&tags=&tags_type=0&sort=time_added&way=desc&hentai=2&releasegroup=&epcount=&epcount2=&artbooktitle=&type=anime&username=**********&torrent_pass=********** [Status: 200]
2021-03-07 08:53:06 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [2cefd1f] User-Agent: Medusa/0.5.10 (Linux; 5.8.0-44-generic; afef34ec-7ece-11eb-85a9-cd16e8a3e843)
2021-03-07 08:53:06 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AnimeBytes] :: [2cefd1f] DailySearchQueueItem Exception, error: AttributeError("'NoneType' object has no attribute 'group'")
Traceback (most recent call last):
  File "/opt/medusa/medusa/search/queue.py", line 295, in run
    found_results = search_for_needed_episodes(self.scheduler_start_time, force=self.force)
  File "/opt/medusa/medusa/search/core.py", line 532, in search_for_needed_episodes
    cur_provider.cache.update_cache(scheduler_start_time)
  File "/opt/medusa/medusa/tv/cache.py", line 226, in update_cache
    data = self._get_rss_data()
  File "/opt/medusa/medusa/tv/cache.py", line 201, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)}
  File "/opt/medusa/medusa/providers/torrent/json/animebytes.py", line 115, in search
    results += self.parse(jdata, mode, show=ep_obj.series if ep_obj else None)
  File "/opt/medusa/medusa/providers/torrent/json/animebytes.py", line 193, in parse
    episode = re.match('^Episode.([0-9]+)', title_info).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Starting new thread: CHECKVERSION
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git config remote.origin.url https://github.com/pymedusa/Medusa with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git config remote.origin.url https://github.com/pymedusa/Medusa : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git config remote.origin.pushurl https://github.com/pymedusa/Medusa with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git config remote.origin.pushurl https://github.com/pymedusa/Medusa : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git symbolic-ref -q HEAD with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git symbolic-ref -q HEAD : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git ls-remote --heads origin with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git ls-remote --heads origin : returned successful
2021-03-07 08:53:08 INFO     CHECKVERSION :: [2cefd1f] Checking for updates using GitHub Updater
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git symbolic-ref -q HEAD with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git symbolic-ref -q HEAD : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git rev-parse HEAD with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git rev-parse HEAD : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git config remote.origin.url https://github.com/pymedusa/Medusa with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git config remote.origin.url https://github.com/pymedusa/Medusa : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git config remote.origin.pushurl https://github.com/pymedusa/Medusa with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git config remote.origin.pushurl https://github.com/pymedusa/Medusa : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git branch develop --set-upstream-to origin/develop with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git branch develop --set-upstream-to origin/develop : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git fetch --prune origin with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    EPISODEUPDATER :: [2cefd1f] Starting new thread: EPISODEUPDATER
2021-03-07 08:53:08 DEBUG    EPISODEUPDATER :: [2cefd1f] Started updating network timezones
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git fetch --prune origin : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git rev-parse --verify --quiet "@{upstream}" : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/medusa
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] git rev-list --left-right "@{upstream}"...HEAD : returned successful
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] cur_commit = 2cefd1f5f90407ecb795d4d10cdb0fcb93fd5668, newest_commit = 2cefd1f5f90407ecb795d4d10cdb0fcb93fd5668, num_commits_behind = 0, num_commits_ahead = 0
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] Checking GitHub for latest news.
2021-03-07 08:53:08 DEBUG    EPISODEUPDATER :: [2cefd1f] GET URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt [Status: 200]
2021-03-07 08:53:08 DEBUG    EPISODEUPDATER :: [2cefd1f] User-Agent: Medusa/0.5.10 (Linux; 5.8.0-44-generic; afef34ec-7ece-11eb-85a9-cd16e8a3e843)
2021-03-07 08:53:08 DEBUG    EPISODEUPDATER :: [2cefd1f] Finished updating network timezones
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] GET URL: https://cdn.pymedusa.com/news/news.md [Status: 200]
2021-03-07 08:53:08 DEBUG    CHECKVERSION :: [2cefd1f] User-Agent: Medusa/0.5.10 (Linux; 5.8.0-44-generic; afef34ec-7ece-11eb-85a9-cd16e8a3e843)
```
</details>

**Additional context**

**Comment by medariox** [comment]
Should be fixed.
