### ISSUE TITLE
Error loading release groups with anime titles

### ISSUE THREAD

**Issue by rgreenosborne** [pymedusa/Medusa#9354]
**Describe the bug**
When Medusa trys to read a list of release groups it fails due the input not being utc8 formatted.  

**To Reproduce**
1. Go to show in Anime list
2. Click on edit
3. See error and referral to log

**Expected behavior**
Everything works from the frontend but Medusa can't read the list.  Adding whitelisted/blacklisted release groups or removing groups does not change error.

**Medusa (please complete the following information):**
 - OS:  Linux-5.10.16-sunxi64-aarch64-with-debian-10.8
 - Branch: master
 - Commit: 55cecb9e821fb15f20efe75b0f59d13e896e1d87
 - Python version: 3.7.3
 - Database version: 44.18

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-03-16 16:51:12 ERROR    Thread_1 :: [55cecb9] Exception generated: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/medusa/server/web/home/handler.py", line 1691, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/ext/decorator.py:decorator-gen-15>", line 2, in get_release_groups_for_anime
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/ext/dogpile/cache/region.py", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/ext/dogpile/cache/region.py", line 1047, in get_or_create
    async_creator,
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/ext/dogpile/cache/region.py", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/mnt/cd0c4a35-c40a-44e4-bd1d-029931e24b13/dietpi_userdata/medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.7/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
</details>

**Comment by medariox** [comment]
See https://github.com/pymedusa/Medusa/issues/9070#issuecomment-764062860 for the fix.
