### ISSUE TITLE
[APP SUBMITTED]: TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by duramato** [pymedusa/Medusa#9386]
### INFO
**Python Version**: `3.8.5 (default, Aug  2 2020, 15:09:07) [GCC 9.3.0]`
**Operating System**: `Linux-4.9.35-v7+-armv7l-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@6522b5eef4f089d4a4bd0ca463b8828a077b479e
**Link to Log**: https://gist.github.com/86b7a50415672536bed7b6c2e2f92f35
### ERROR
<pre>
2021-03-27 04:29:31 ERROR    DOWNLOADHANDLER :: [6522b5e] Exception while checking torrent status. with error: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/6522b5eef4f089d4a4bd0ca463b8828a077b479e/medusa/schedulers/download_handler.py#L344">medusa/schedulers/download_handler.py</a>", line 344, in run
    self._check_torrent_ratio(torrent_client)
  File "/home/pi/Medusa/<a href="../blob/6522b5eef4f089d4a4bd0ca463b8828a077b479e/medusa/schedulers/download_handler.py#L244">medusa/schedulers/download_handler.py</a>", line 244, in _check_torrent_ratio
    desired_ratio = provider_ratio if provider_ratio > -1 else app.TORRENT_SEED_RATIO
TypeError: '>' not supported between instances of 'NoneType' and 'int'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
How to repro this? Judging from the code this should never happen.

**Comment by p0psicles** [comment]
Nah, it can happen. When provider.ratio is None. Probably for new providers that haven't been reconfigured.

**Comment by medariox** [comment]
It should be `''` for new providers: https://github.com/pymedusa/Medusa/blob/b352bb6924afcdfafce176a540d53ce405ca1312/medusa/server/web/config/providers.py#L401-L406 That's why I'm asking.

**Comment by p0psicles** [comment]
Yes I see

**Comment by duramato** [comment]
The providers are all set as `-1`

**Comment by medariox** [comment]
Can you check if they are all saved as `-1` in config.ini?

**Comment by duramato** [comment]
```
limetorrents_ratio = -1
btnext_ratio = -1
filelist_ratio = -1
ptfiles_ratio = -1
xspeeds_ratio = -1
isohunt_ratio = -1
torrentbytes_ratio = -1
pretome_ratio = -1
nebulance_ratio = -1
torrentday_ratio = -1
hdspace_ratio = -1
torrentleech_ratio = -1
alpharatio_ratio = -1
iptorrents_ratio = -1
bithdtv_ratio = -1
torrentseeds_ratio = -1
rarbg_ratio = -1
btn_ratio = -1
acid_lounge_ratio = -1
torrenting_ratio = -1
tvchaosuk_ratio = -1
hdtorrents_ratio = -1
hdme_ratio = -1
zooqle_ratio = -1
uhdbits_ratio = -1
scenetime_ratio = -1
demonoid_ratio = -1
polishsource_ratio = -1
speedcd_ratio = -1
eztv_ratio = -1
beyond_hd_ratio = -1
danishbits_ratio = -1
morethantv_ratio = -1
btdb_ratio = -1
nordicbits_ratio = -1
torrentproject_ratio = -1
btdigg_ratio = -1
torrentz2_ratio = -1
hdbits_ratio = -1
privatehd_ratio = -1
cinemaz_ratio = -1
thepiratebay_ratio = -1
sdbits_ratio = -1
bj_share_ratio = -1
bitcannon_ratio = 1
tokyotoshokan_ratio = -1
animebytes_ratio = -1
xthor_ratio = -1
shazbat_tv_ratio = -1
abnormal_ratio = -1
norbits_ratio = -1
animetorrents_ratio = -1
anidex_ratio = -1
shanaproject_ratio = -1
nyaa_ratio = -1
yggtorrent_ratio = -1
hebits_ratio = -1
elitetracker_ratio = -1
archetorrent_ratio = -1
avistaz_ratio = -1
ncore_ratio = -1
gimmepeers_ratio = -1
torrent_seed_ratio = 2.0
```

**Comment by p0psicles** [comment]
I can catch the exeption and log the provider?

**Comment by medariox** [comment]
This was likely a one time thing. It can only happen if a provider is added while the DH thread is running.

**Comment by duramato** [comment]
This happens always that the download checker runs. Just like this log: https://gist.github.com/86b7a50415672536bed7b6c2e2f92f35

**Comment by medariox** [comment]
Does it still happen if you restart?

**Comment by duramato** [comment]
Yup, just restarted to double check and still and same:
```
2021-03-28 22:05:14 ERROR    DOWNLOADHANDLER :: [4b7db50] Exception while checking torrent status. with error: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/pi/Medusa/medusa/schedulers/download_handler.py", line 344, in run
    self._check_torrent_ratio(torrent_client)
  File "/home/pi/Medusa/medusa/schedulers/download_handler.py", line 244, in _check_torrent_ratio
    desired_ratio = provider_ratio if provider_ratio > -1 else app.TORRENT_SEED_RATIO
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by medariox** [comment]
I guess we should add a catch at this point as you suggested @p0psicles

**Comment by p0psicles** [comment]
@duramato could you try running branch `feature/fix-ratio-error`

**Comment by duramato** [comment]
`2021-03-29 20:19:31 WARNING  DOWNLOADHANDLER :: [8da1f65] could not get provider ratio None for provider tvchaosuk`

**Comment by duramato** [comment]
Okay I think I've figuered what was the issue. I had a jackett provider added with the name `tvchaosuk`, while Medusa already has a `TVChaosUK` and it may have caused some confusion.
Maybe Medusa shouldn't accept a Jackett or NZB provider with a name that already exists? But well that's not an issue with the download handler.

**Comment by p0psicles** [comment]
Shall we merge the pr?

**Comment by WarEagleUS21** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-09-19 06:11:25 ERROR    SNATCHQUEUE-SNATCH-363955 :: [21e350c] Snatch failed! For result: Evil.S02E10.1080p.WEB.H264-GLHF[rartv]
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/search/queue.py#L516">medusa\search\queue.py</a>", line 516, in run
    self.success = snatch_result(result)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/search/core.py#L168">medusa\search\core.py</a>", line 168, in snatch_result
    result_downloaded = client.send_torrent(result)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/clients/torrent/generic.py#L230">medusa\clients\torrent\generic.py</a>", line 230, in send_torrent
    r_code = self._add_torrent_uri(result)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/clients/torrent/qbittorrent.py#L159">medusa\clients\torrent\qbittorrent.py</a>", line 159, in _add_torrent_uri
    command = 'api/v2/torrents/add' if self.api >= (2, 0, 0) else 'command/download'
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by WarEagleUS21** [comment]
### INFO
**Python Version**: `3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [develop](../tree/develop)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@f65c9fec620608434398855347ada8b37a9193b2
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-12-06 15:48:38 ERROR    SNATCHQUEUE-SNATCH-350665 :: [f65c9fe] Snatch failed! For result: The.Rookie.S04E08.1080p.WEB.H264-PECULATE[rartv]
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/f65c9fec620608434398855347ada8b37a9193b2/medusa/search/queue.py#L516">medusa\search\queue.py</a>", line 516, in run
    self.success = snatch_result(result)
  File "C:\Medusa\Medusa\<a href="../blob/f65c9fec620608434398855347ada8b37a9193b2/medusa/search/core.py#L168">medusa\search\core.py</a>", line 168, in snatch_result
    result_downloaded = client.send_torrent(result)
  File "C:\Medusa\Medusa\<a href="../blob/f65c9fec620608434398855347ada8b37a9193b2/medusa/clients/torrent/generic.py#L230">medusa\clients\torrent\generic.py</a>", line 230, in send_torrent
    r_code = self._add_torrent_uri(result)
  File "C:\Medusa\Medusa\<a href="../blob/f65c9fec620608434398855347ada8b37a9193b2/medusa/clients/torrent/qbittorrent.py#L159">medusa\clients\torrent\qbittorrent.py</a>", line 159, in _add_torrent_uri
    command = 'api/v2/torrents/add' if self.api >= (2, 0, 0) else 'command/download'
TypeError: '>=' not supported between instances of 'NoneType' and 'tuple'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
