### ISSUE TITLE
Unable to add new anime series with whitelisted group

### ISSUE THREAD

**Issue by k0mmsussert0d** [pymedusa/Medusa#9398]
**Describe the bug**
When I try adding new anime series and enter custom whitelisted release group (because list of available groups is empty), it's not getting added to the list. Instead, this error occurs:
```
2021-04-01 20:14:51 ERROR    SHOWQUEUE-ADD :: [] Error trying to configure show: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/app/medusa/medusa/queues/show_queue.py", line 414, in run
    series.configure(self)
  File "/app/medusa/medusa/tv/series.py", line 1768, in configure
    self.whitelist = options['whitelist']
  File "/app/medusa/medusa/tv/base.py", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/app/medusa/medusa/tv/series.py", line 763, in whitelist
    self.release_groups.set_white_keywords(short_group_names(group_names))
  File "/app/medusa/medusa/helpers/anidb.py", line 106, in short_group_names
    short_group_list += get_short_group_name(group_name) or [group_name]
  File "</app/medusa/ext/decorator.py:decorator-gen-16>", line 2, in get_short_group_name
  File "/app/medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/app/medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/app/medusa/ext/dogpile/cache/region.py", line 1264, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

This applies to any anime. I tracked the issue down to possible anidb cache file corruption. Here's the bytearray json module tries to decode and load:
```
b'\x80\x05\x95Q\x00\x00\x00\x00\x00\x00\x00\x8c\x11dogpile.cache.api\x94\x8c\x0bCachedValue\x94\x93\x94]\x94\x8c\nSubsPlease\x94a}\x94(\x8c\x02ct\x94GA\xd8\t\xaf\xcd\xe7\xe5:\x8c\x01v\x94K\x01u\x86\x94R\x94.'
```

Issue was resolved by renaming `anidb.dbm` file in cache directory. I can share it if you decide to work on this issue or confirm there's no personal data in it.

**To Reproduce**
1. Go to 'Add New Show'
2. Search for any anime show
3. See empty list of available groups
4. Try adding custom group name
5. Click 'Add Show'
6. Show doesn't get added. Error above is produced in log.

**Expected behavior**
Selected show with specified whitelisted group is added.

**Medusa (please complete the following information):**
 - OS: Linux-5.4.60-1-pve-x86_64-with
 - Branch: master
 - Commit: Unknown
 - Python version: 3.8.8
 - Database version: 44.18

**Debug logs (at least 50 lines):**
```
<details>
2021-04-01 15:49:01 ERROR	SHOWQUEUE-ADD :: Error trying to configure show: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/app/medusa/medusa/queues/show_queue.py", line 414, in run
    series.configure(self)
  File "/app/medusa/medusa/tv/series.py", line 1768, in configure
    self.whitelist = options['whitelist']
  File "/app/medusa/medusa/tv/base.py", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/app/medusa/medusa/tv/series.py", line 763, in whitelist
    self.release_groups.set_white_keywords(short_group_names(group_names))
  File "/app/medusa/medusa/helpers/anidb.py", line 106, in short_group_names
    short_group_list += get_short_group_name(group_name) or [group_name]
  File "</app/medusa/ext/decorator.py:decorator-gen-16>", line 2, in get_short_group_name
  File "/app/medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/app/medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/app/medusa/ext/dogpile/cache/region.py", line 1264, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
2021-04-01 15:49:01 INFO	SHOWQUEUE-ADD :: Setting all previously aired episodes to the specified status: Skipped
2021-04-01 15:48:57 INFO	SHOWQUEUE-ADD :: 378609: Unable to find the show in the database
2021-04-01 15:48:57 INFO	SHOWQUEUE-ADD :: Starting to add show by Indexer Id: 378609
2021-04-01 15:48:47 INFO	Thread :: ReleaseGroups: []
2021-04-01 15:48:43 INFO	Thread-1 :: ReleaseGroups: []
2021-04-01 15:48:43 INFO	Thread-1 :: ReleaseGroups: 86
2021-04-01 15:48:42 INFO	Thread :: ReleaseGroups: Get Smart
2021-04-01 15:48:12 INFO	MAIN :: Building internal name cache for all shows
2021-04-01 15:48:12 INFO	MAIN :: Finished processing 3583 scene exceptions.
2021-04-01 15:48:12 INFO	MAIN :: Updating exception_cache and exception_season_cache
2021-04-01 15:48:12 INFO	TORNADO :: Starting Medusa on http://0.0.0.0:8081/medusa/
2021-04-01 15:48:12 INFO	MAIN :: Starting Medusa [master] using '/config/config.ini'
2021-04-01 15:48:12 INFO	MAIN :: 12345: Unable to find the show in the database
2021-04-01 15:48:12 INFO	MAIN :: Changed TV download folder to /downloads/TV/medusa
2021-04-01 15:48:12 INFO	MAIN :: Broken providers found: ['']
2021-04-01 15:48:11 INFO	MAIN :: Changed https key path to server.key
2021-04-01 15:48:11 INFO	MAIN :: Changed https cert path to server.crt
</details>
```

**Additional context**
I was able to reproduce the issue copying the entire Medusa config directory (including corrupted anidb cache file), but only on Python 3.8.8. On 3.9.2, the show got successfully added.

**Comment by medariox** [comment]
Please see https://github.com/pymedusa/Medusa/issues/9070#issuecomment-764062860
