### ISSUE TITLE
500 error when trying to change whitelisted Release Groups

### ISSUE THREAD

**Issue by lcdt22890158** [pymedusa/Medusa#9400]
**Describe the bug**
I have noticed a bug affecting several (but not all) shows. Most recently it is affecting SSSS.DYNAZENON. When I try to add a release group to the whitelist, a 500 error appears and my changes are not saved.

**To Reproduce**
1. Add SSSS.DYNAZENON to Medusa.
2. Go to SSSS.DYNAZENON.
2. Click Edit.
3. Go to the Format tab.
4. Observe that the Release Groups list is not automatically populated. This is consistent across all affected shows, the Release Groups list doesn't appear.
5. Type "EMBER" into the "add custom group" field.
6. Click the arrow in the "Whitelist" box.
7. Click "Save Changes"
8. Observe the 500 error.

**Expected behavior**
My changes should be saved and no error should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/43034492/113463762-88ab2700-9473-11eb-9ddf-80cbd2cb368a.png)

**Medusa (please complete the following information):**
 - OS: linuxserver.io Docker image - v0.5.10
 - Branch: master
 - Commit: Not sure
 - Python version: Not sure
 - Database version: Not sure

**Debug logs (at least 50 lines):**

Here are the relevant Tornado logs with Logging level: Debug.

<details>

```
2021-04-03 11:55:43 ERROR	TORNADO :: [1ed3156] Uncaught exception in APIv2: UnicodeDecodeError('utf-8', b'\x80\x05\x95C\x00\x00\x00\x00\x00\x00\x00\x8c\x11dogpile.cache.api\x94\x8c\x0bCachedValue\x94\x93\x94]\x94}\x94(\x8c\x02ct\x94GA\xd8\x03C\xab\x818d\x8c\x01v\x94K\x01u\x86\x94R\x94.', 0, 1, 'invalid start byte')
Request: PATCH /api/v2/series/tvdb392925 (10.255.0.2)
With body:
{"config":{"aliases":[],"defaultEpisodeStatus":"Wanted","dvdOrder":false,"seasonFolders":true,"anime":true,"scene":false,"sports":false,"paused":false,"location":"/media/TV/SSSS.DYNAZENON","airByDate":false,"subtitlesEnabled":true,"release":{"requiredWords":[],"ignoredWords":[],"requiredWordsExclude":false,"ignoredWordsExclude":false,"blacklist":[],"whitelist":["EMBER"]},"qualities":{"preferred":[],"allowed":[8,32,64,128,256,512,1024,2048,4096,8192,16384,32768]},"airdateOffset":0,"showLists":["series"]},"language":"en"}
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/medusa/medusa/server/api/v2/series.py", line 174, in patch
    if patch_field and patch_field.patch(series, value):
  File "/app/medusa/medusa/server/api/v2/base.py", line 516, in patch
    setattr(target, self.attr, self.converter(value))
  File "/app/medusa/medusa/tv/base.py", line 63, in __setattr__
    super(TV, self).__setattr__(key, value)
  File "/app/medusa/medusa/tv/series.py", line 763, in whitelist
    self.release_groups.set_white_keywords(short_group_names(group_names))
  File "/app/medusa/medusa/helpers/anidb.py", line 106, in short_group_names
    short_group_list += get_short_group_name(group_name) or [group_name]
  File "</app/medusa/ext/decorator.py:decorator-gen-16>", line 2, in get_short_group_name
  File "/app/medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/app/medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/app/medusa/ext/dogpile/cache/region.py", line 1264, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
</details>

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/issues/9398#issuecomment-812507068
