### ISSUE TITLE
Snatch failed

### ISSUE THREAD

**Issue by Jaapdijkshoorn** [pymedusa/Medusa#9432]
**Describe the bug**
Medusa fails to download.

2021-04-14 09:26:47 ERROR    SNATCHQUEUE-SNATCH-361315 :: [55cecb9] Snatch failed! For result: 
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/medusa/search/queue.py", line 516, in run
    self.success = snatch_result(result)
  File "/volume1/@appstore/medusa/var/src/medusa/search/core.py", line 168, in snatch_result
    result_downloaded = client.send_torrent(result)
  File "/volume1/@appstore/medusa/var/src/medusa/clients/torrent/generic.py", line 240, in send_torrent
    if not self._get_auth():
  File "/volume1/@appstore/medusa/var/src/medusa/clients/torrent/downloadstation.py", line 98, in _get_auth
    self.response.raise_for_status()
AttributeError: 'NoneType' object has no attribute 'raise_for_status'

**Medusa (please complete the following information):**

Medusa Info: | Branch:                 master                  Commit:                 55cecb9e821fb15f20efe75b0f59d13e896e1d87                  Version:                 0.5.10                  Database:                 44.18
-- | --
Python Version: | 3.7.10 (default, Mar 14 2021, 11:04:23)  [GCC 4.9.3 20150311 (prerelease)]
SSL Version: | OpenSSL 1.1.1j  16 Feb 2021
OS: | Linux-4.4.59+-x86_64-with-glibc2.2.5
Locale: | en_US.UTF-8

**Comment by medariox** [comment]
Please use the template when opening an issue _**_including the debug logs_**_, otherwise there is no way we can help you. Closing until it is done.
