### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [Errno 13] Permission denied: '/config/cache/images/tvdb/366318.fanart.jpg'

### ISSUE THREAD

**Issue by Bogey** [pymedusa/Medusa#9450]
### INFO
**Python Version**: `3.8.8 (default, Mar 15 2021, 13:12:20) [GCC 9.3.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/4dc7a808e4d755dac4cb553dca2ecd8c
### ERROR
<pre>
2021-04-19 13:36:00 ERROR    TORNADO :: [] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/series/tvdb366318/asset/fanart?api_key=********** (172.17.0.1)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/medusa/medusa/server/api/v2/series_asset.py", line 37, in get
    media = asset.media
  File "/app/medusa/medusa/media/generic.py", line 69, in media
    with open(static_media_path, 'rb') as content:
PermissionError: [Errno 13] Permission denied: '/config/cache/images/tvdb/366318.fanart.jpg'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by Bogey** [comment]
### INFO
**Python Version**: `3.8.8 (default, Mar 15 2021, 13:12:20) [GCC 9.3.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/2c5eb27060a53e6f9903ce756064a7fa
### ERROR
<pre>
2021-04-19 13:39:52 ERROR    TORNADO :: [] Uncaught exception in APIv2: PermissionError(13, 'Permission denied')
Request: GET /api/v2/series/tvdb279536/asset/fanart?api_key=********** (172.17.0.1)
Traceback (most recent call last):
  File "/app/medusa/ext/tornado/web.py", line 1704, in _execute
    result = await result
  File "/app/medusa/ext/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/app/medusa/medusa/server/api/v2/base.py", line 64, in async_call
    content = yield IOLoop.current().run_in_executor(executor, prepared)
  File "/app/medusa/ext/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/medusa/medusa/server/api/v2/series_asset.py", line 37, in get
    media = asset.media
  File "/app/medusa/medusa/media/generic.py", line 69, in media
    with open(static_media_path, 'rb') as content:
PermissionError: [Errno 13] Permission denied: '/config/cache/images/tvdb/279536.fanart.jpg'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Please see:
https://github.com/pymedusa/Medusa/issues/9153
https://github.com/pymedusa/Medusa/issues/7540
