### ISSUE TITLE
TypeError: attrs() got an unexpected keyword argument 'eq'

### ISSUE THREAD

**Issue by John-Gee** [pymedusa/Medusa#9463]
**Describe the bug**
When trying to start Medusa I get this:

Traceback (most recent call last):
  File "/usr/lib/pymedusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/usr/lib/pymedusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/usr/lib/pymedusa/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/usr/lib/pymedusa/medusa/init/__init__.py", line 202, in _configure_guessit
    from medusa.name_parser.guessit_parser import (
  File "/usr/lib/pymedusa/medusa/name_parser/guessit_parser.py", line 12, in <module>
    from medusa.logger.adapters.style import BraceAdapter
  File "/usr/lib/pymedusa/medusa/logger/__init__.py", line 44, in <module>
    import knowit
  File "/usr/lib/pymedusa/ext/knowit/__init__.py", line 27, in <module>
    from .api import KnowitException, know
  File "/usr/lib/pymedusa/ext/knowit/api.py", line 7, in <module>
    from .config import Config
  File "/usr/lib/pymedusa/ext/knowit/config.py", line 11, in <module>
    from .serializer import get_yaml_loader
  File "/usr/lib/pymedusa/ext/knowit/serializer.py", line 12, in <module>
    from .units import units
  File "/usr/lib/pymedusa/ext/knowit/units.py", line 24, in <module>
    units = _build_unit_registry()
  File "/usr/lib/pymedusa/ext/knowit/units.py", line 6, in _build_unit_registry
    from pint import UnitRegistry
  File "/usr/lib/pymedusa/ext/pint/__init__.py", line 18, in <module>
    from .formatting import formatter
  File "/usr/lib/pymedusa/ext/pint/formatting.py", line 16, in <module>
    from .babel_names import _babel_units, _babel_lengths
  File "/usr/lib/pymedusa/ext/pint/babel_names.py", line 10, in <module>
    from pint.compat import HAS_PROPER_BABEL
  File "/usr/lib/pymedusa/ext/pint/compat/__init__.py", line 136, in <module>
    import pytest
  File "/usr/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/lib/python3.9/site-packages/_pytest/assertion/__init__.py", line 9, in <module>
    from _pytest.assertion import rewrite
  File "/usr/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 34, in <module>
    from _pytest.assertion import util
  File "/usr/lib/python3.9/site-packages/_pytest/assertion/util.py", line 13, in <module>
    import _pytest._code
  File "/usr/lib/python3.9/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/usr/lib/python3.9/site-packages/_pytest/_code/code.py", line 942, in <module>
    @attr.s(eq=False)
TypeError: attrs() got an unexpected keyword argument 'eq'

My guess is that the mix-match between bundle and system is the issue, so either attrs need to be updated in Medusa or it may need to bundle other packages such as pytest as well.

**Medusa (please complete the following information):**
 - OS: Arch Linux 
 - Version: 0.5.11
 - Python version: 3.9.4
 - Database version: What is this?

Thank you!

**Comment by medariox** [comment]
You need to remove the locally installed package that is causing this issue (attrs?). Medusa already bundles all required dependencies. You can see the exact version which are required here https://github.com/pymedusa/Medusa/blob/master/requirements.txt and here https://github.com/pymedusa/Medusa/blob/master/test_requirements.txt (for testing).

**Comment by John-Gee** [comment]
Thanks for the super quick reply!

I need to keep that package for other things so I cannot do that. Is there maybe a way to override what Medusa can and cannot use?

**Comment by p0psicles** [comment]
You could try running in virtualenv

**Comment by John-Gee** [comment]
I'll look into that, thank you!
