### ISSUE TITLE
PermissionError(13, 'Permission denied')

### ISSUE THREAD

**Issue by ausghostdog** [pymedusa/Medusa#9470]
**Describe the bug**
Can not post process files, everything gets PermissionError(13, 'Permission denied')
**To Reproduce**
Show is snatched no issues
show downloads and is moved to post processing file
file is not moved due to PermissionError(13, 'Permission denied')

**Expected behavior**
show post processed 

**Screenshots**
![image](https://user-images.githubusercontent.com/7588602/115866177-aa993780-a47c-11eb-851d-43d2a84d2695.png)

**Medusa (please complete the following information):**
 - OS: [Ubuntu 18.04.5 LTS]
 - Branch: [Master]
 - Commit: [e.g. c65ca2] - how do I tell? 
 - Python version: 3.6.9
 - Database version: [e.g. 44.12]  - how do I tell? 

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-04-23 21:43:58 WARNING	POSTPROCESSOR :: [918cfe7] Missed file: /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4: Processing failed: Unable to move the files to their new home
2021-04-23 21:43:58 WARNING	POSTPROCESSOR :: [918cfe7] Problem(s) during processing, failed for the following files/folders: 
2021-04-23 21:43:58 INFO	POSTPROCESSOR :: [918cfe7] Not deleting folder /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10 found the following files: ['Manifest.S03E03.WEBRip.x264-ION10.mp4', 'RARBG.txt', 'RARBG_DO_NOT_MIRROR.exe', 'Subs']
2021-04-23 21:43:58 WARNING	POSTPROCESSOR :: [918cfe7] Processing failed for /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4: Unable to move the files to their new home
2021-04-23 21:43:58 ERROR	POSTPROCESSOR :: [918cfe7] Unable to move file /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4 to /tvshows/Manifest/Season 03/03E03.mp4: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4' -> '/tvshows/Manifest/Season 03/03E03.mp4'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/medusa/helpers/__init__.py", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "/usr/lib/python3.8/shutil.py", line 806, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/medusa/post_processor.py", line 477, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/app/medusa/medusa/helpers/__init__.py", line 324, in move_file
    os.unlink(src_file)
PermissionError: [Errno 13] Permission denied: '/tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4'
2021-04-23 21:43:20 INFO	POSTPROCESSOR :: [918cfe7] This download is marked a priority download so I'm going to replace an existing file if I find one
2021-04-23 21:43:20 INFO	POSTPROCESSOR :: [918cfe7] New size: 413.90 MB
2021-04-23 21:43:20 INFO	POSTPROCESSOR :: [918cfe7] New file: /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4
2021-04-23 21:43:20 INFO	POSTPROCESSOR :: [918cfe7] Processing /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4
2021-04-23 21:43:20 INFO	POSTPROCESSOR :: [918cfe7] Not deleting folder /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Subs found the following files: ['2_English.srt']
2021-04-23 21:43:20 INFO	POSTPROCESSOR :: [918cfe7] Processing path: /tvshows/downloads
2021-04-23 21:33:19 WARNING	POSTPROCESSOR :: [918cfe7] Missed file: /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4: Processing failed: Unable to move the files to their new home
2021-04-23 21:33:19 WARNING	POSTPROCESSOR :: [918cfe7] Problem(s) during processing, failed for the following files/folders: 
2021-04-23 21:33:19 INFO	POSTPROCESSOR :: [918cfe7] Not deleting folder /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10 found the following files: ['Manifest.S03E03.WEBRip.x264-ION10.mp4', 'RARBG.txt', 'RARBG_DO_NOT_MIRROR.exe', 'Subs']
2021-04-23 21:33:19 WARNING	POSTPROCESSOR :: [918cfe7] Processing failed for /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4: Unable to move the files to their new home
2021-04-23 21:33:19 ERROR	POSTPROCESSOR :: [918cfe7] Unable to move file /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4 to /tvshows/Manifest/Season 03/03E03.mp4: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4' -> '/tvshows/Manifest/Season 03/03E03.mp4'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/medusa/helpers/__init__.py", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "/usr/lib/python3.8/shutil.py", line 806, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/medusa/post_processor.py", line 477, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "/app/medusa/medusa/helpers/__init__.py", line 324, in move_file
    os.unlink(src_file)
PermissionError: [Errno 13] Permission denied: '/tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4'
2021-04-23 21:32:41 INFO	POSTPROCESSOR :: [918cfe7] This download is marked a priority download so I'm going to replace an existing file if I find one
2021-04-23 21:32:41 INFO	POSTPROCESSOR :: [918cfe7] New size: 413.90 MB
2021-04-23 21:32:41 INFO	POSTPROCESSOR :: [918cfe7] New file: /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4
2021-04-23 21:32:41 INFO	POSTPROCESSOR :: [918cfe7] Processing /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Manifest.S03E03.WEBRip.x264-ION10.mp4
2021-04-23 21:32:41 INFO	POSTPROCESSOR :: [918cfe7] Not deleting folder /tvshows/downloads/Manifest.S03E03.WEBRip.x264-ION10/Subs found the following files: ['2_English.srt']
2021-04-23 21:32:41 INFO	POSTPROCESSOR :: [918cfe7] Processing path: /tvshows/downloads
```
</details>

**Additional context**
storage for the shows 
![image](https://user-images.githubusercontent.com/7588602/115867214-21830000-a47e-11eb-9839-08a89590ca1a.png)
inside the docker container 
![image](https://user-images.githubusercontent.com/7588602/115867267-38295700-a47e-11eb-8b15-3f9f23779ac1.png)
script 
![image](https://user-images.githubusercontent.com/7588602/115867387-64dd6e80-a47e-11eb-970a-0c2360bde126.png)

**Comment by ausghostdog** [comment]
Solved, the issue was to do with uid of the downloaders and how they were placing the files
