### ISSUE TITLE
[APP SUBMITTED]: trakt.errors.OAuthException: Unauthorized - OAuth must be provided

### ISSUE THREAD

**Issue by HPMSGEN8** [pymedusa/Medusa#9545]
### INFO
**Python Version**: `3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]`
**Operating System**: `Linux-3.10.105-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b
**Link to Log**: https://gist.github.com/662929c73749dad0009071ea1d1a7d6e
### ERROR
<pre>
2021-05-16 10:48:08 ERROR    Thread_30 :: [fcb5a19] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/medusa/show/recommendations/trakt.py#L113">medusa/show/recommendations/trakt.py</a>", line 113, in fetch_popular_shows
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/ext/trakt/core.py#L547">ext/trakt/core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/<a href="../blob/fcb5a1969dcd4ea0b6fb4a9debbf60179b0bbf4b/ext/trakt/core.py#L524">ext/trakt/core.py</a>", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by HPMSGEN8** [comment]
Hi All,

Any help on this please. Where do i need to add this Key to ?

Thanks

**Comment by p0psicles** [comment]
Config - notifications - trakt

**Comment by HPMSGEN8** [comment]
Hi @p0psicles 

Thanks a lot this is now working :)

**Comment by rikbon** [comment]
### INFO
**Python Version**: `3.8.10 (default, May  6 2021, 06:30:44) [GCC 9.3.0]`
**Operating System**: `Linux-5.10.17-v7l+-armv7l-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/0add268b1d2f19481da046c175a469b3
### ERROR
<pre>
2021-06-09 17:42:59 ERROR    TRAKTCHECKER :: [] Trakt exception while running trakt_checker.
Error: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/medusa/schedulers/trakt_checker.py", line 87, in run
    self.sync_watchlist()
  File "/app/medusa/medusa/schedulers/trakt_checker.py", line 307, in sync_watchlist
    if self._get_show_watchlist():
  File "/app/medusa/medusa/schedulers/trakt_checker.py", line 698, in _get_show_watchlist
    user = get_trakt_user()
  File "/app/medusa/medusa/helpers/trakt.py", line 20, in get_trakt_user
    user = users.get_user_settings()
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dmathurin** [comment]
### INFO
**Python Version**: `3.8.10 (default, May  6 2021, 06:30:44) [GCC 9.3.0]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/747abdee5f66cff93f85c8920839bcda
### ERROR
<pre>
2021-09-25 02:14:00 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 137, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 120, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dmathurin** [comment]
### INFO
**Python Version**: `3.8.10 (default, May  6 2021, 06:30:44) [GCC 9.3.0]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/a228f85232a3cb23eb337b9b1c0ac821
### ERROR
<pre>
2021-09-27 02:19:03 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 137, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 120, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dmathurin** [comment]
### INFO
**Python Version**: `3.8.10 (default, May  6 2021, 06:30:44) [GCC 9.3.0]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/92a7caf33ef0353d02f4e117538351e5
### ERROR
<pre>
2021-09-29 02:19:01 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 137, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 120, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dmathurin** [comment]
### INFO
**Python Version**: `3.8.10 (default, May  6 2021, 06:30:44) [GCC 9.3.0]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/94889e78a11d1173474e8f3763195d42
### ERROR
<pre>
2021-12-02 02:11:02 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 137, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 120, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dmathurin** [comment]
### INFO
**Python Version**: `3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@
**Link to Log**: https://gist.github.com/310a89c658c3343353ca9805de91b898
### ERROR
<pre>
2022-02-25 02:18:02 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 137, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/app/medusa/medusa/show/recommendations/trakt.py", line 120, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
Your not authenticated with trakt.
Pls re-auth in config - notification - trakt

**Comment by WarEagleUS21** [comment]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@e4870f8f4a322e67c77434597ccc09aa6524aa05
**Link to Log**: **No Log available**
### ERROR
<pre>
2022-05-22 00:37:01 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [e4870f8] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/show/recommendations/trakt.py#L137">medusa\show\recommendations\trakt.py</a>", line 137, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/medusa/show/recommendations/trakt.py#L120">medusa\show\recommendations\trakt.py</a>", line 120, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/ext/trakt/core.py#L547">ext\trakt\core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "C:\Medusa\Medusa\<a href="../blob/e4870f8f4a322e67c77434597ccc09aa6524aa05/ext/trakt/core.py#L524">ext\trakt\core.py</a>", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by GregWierzchowski** [comment]
### INFO
**Python Version**: `3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]`
**Operating System**: `Linux-4.19.0-21-amd64-x86_64-with-debian-10.12`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@f690170c2cbd9f2804c38a6047059cb1ace8afe3
**Link to Log**: https://gist.github.com/7f44c783046c4dbd191c89563b100608
### ERROR
<pre>
2022-10-09 02:05:02 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [f690170] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/f690170c2cbd9f2804c38a6047059cb1ace8afe3/medusa/show/recommendations/trakt.py#L145">medusa/show/recommendations/trakt.py</a>", line 145, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/opt/medusa/<a href="../blob/f690170c2cbd9f2804c38a6047059cb1ace8afe3/medusa/show/recommendations/trakt.py#L128">medusa/show/recommendations/trakt.py</a>", line 128, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/opt/medusa/<a href="../blob/f690170c2cbd9f2804c38a6047059cb1ace8afe3/ext/trakt/core.py#L547">ext/trakt/core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/opt/medusa/<a href="../blob/f690170c2cbd9f2804c38a6047059cb1ace8afe3/ext/trakt/core.py#L524">ext/trakt/core.py</a>", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by artificial-chaos** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@9b23c72f7e24bf638819e32d72f33e433f9649c4
**Link to Log**: https://gist.github.com/c5fc28e297c91a5c5642262dd3af370f
### ERROR
<pre>
2022-10-30 01:10:04 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [9b23c72] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/show/recommendations/trakt.py#L145">medusa/show/recommendations/trakt.py</a>", line 145, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/show/recommendations/trakt.py#L128">medusa/show/recommendations/trakt.py</a>", line 128, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/ext/trakt/core.py#L547">ext/trakt/core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/ext/trakt/core.py#L524">ext/trakt/core.py</a>", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by artificial-chaos** [comment]
### INFO
**Python Version**: `3.10.4 (main, Apr 20 2022, 01:09:52) [GCC 10.3.1 20211027]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.19`
**Commit**: pymedusa/Medusa@9b23c72f7e24bf638819e32d72f33e433f9649c4
**Link to Log**: https://gist.github.com/845544f9b73cd5842399d93e1b960de5
### ERROR
<pre>
2022-11-15 01:36:02 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [9b23c72] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/show/recommendations/trakt.py#L145">medusa/show/recommendations/trakt.py</a>", line 145, in fetch_popular_shows
    removed_from_medusa = self.get_removed_from_medusa()
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/medusa/show/recommendations/trakt.py#L128">medusa/show/recommendations/trakt.py</a>", line 128, in get_removed_from_medusa
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/ext/trakt/core.py#L547">ext/trakt/core.py</a>", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/app/medusa/<a href="../blob/9b23c72f7e24bf638819e32d72f33e433f9649c4/ext/trakt/core.py#L524">ext/trakt/core.py</a>", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
