### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 9] Bad file descriptor: '/mnt/4medusa/PLEX/Series1080/9-1-1/Temporada 3/9-1-1 - 3x17 - Impotente.mkv' -> '/mnt/Series-Continua/9-1-1 (2018) [Continua] [tt7235466]/Season 03/9-1-1 - S03E17 - Impotente.mkv'

### ISSUE THREAD

**Issue by Giakin** [pymedusa/Medusa#9579]
### INFO
**Python Version**: `3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-73-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@4d9c7927ebeb425e386b122a230c849163d065c7
**Link to Log**: https://gist.github.com/158b3c22454dd3cc2893957b3613b397
### ERROR
<pre>
2021-05-28 15:21:41 ERROR    POSTPROCESSQUEUE-POST-PROCESS :: [4d9c792] OSError: OSError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/4d9c7927ebeb425e386b122a230c849163d065c7/medusa/helpers/__init__.py#L293">medusa/helpers/__init__.py</a>", line 293, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/usr/lib/python3.8/shutil.py", line 272, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    raise err
  File "/usr/lib/python3.8/shutil.py", line 149, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 9] Bad file descriptor: '/mnt/4medusa/PLEX/Series1080/9-1-1/Temporada 3/9-1-1 - 3x17 - Impotente.mkv' -> '/mnt/Series-Continua/9-1-1 (2018) [Continua] [tt7235466]/Season 03/9-1-1 - S03E17 - Impotente.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
You modified/removed/copied/etc. the file manually while Medusa was working with it. Don't do it.
