### ISSUE TITLE
[APP SUBMITTED]: OSError: [Errno 29] Illegal seek: '/mnt/4medusa/PLEX/Series1080/Modern Family/Temporada 3/Modern Family - 3x19 - El día de las elecciones.mkv' -> '/mnt/Series-Continua/Modern Family (2009) [Terminó] [tt1442437]/Season 03/Modern Family - S03E19 - El día de las elecciones.mkv'

### ISSUE THREAD

**Issue by Giakin** [pymedusa/Medusa#9588]
### INFO
**Python Version**: `3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]`
**Operating System**: `Linux-5.4.0-73-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@4d9c7927ebeb425e386b122a230c849163d065c7
**Link to Log**: https://gist.github.com/a350af8e74c3427b8ed74fb6288126fc
### ERROR
<pre>
2021-05-29 07:49:42 ERROR    POSTPROCESSQUEUE-POST-PROCESS :: [4d9c792] OSError: OSError(29, 'Illegal seek')
Traceback (most recent call last):
  File "/opt/medusa/<a href="../blob/4d9c7927ebeb425e386b122a230c849163d065c7/medusa/helpers/__init__.py#L293">medusa/helpers/__init__.py</a>", line 293, in copy_file
    shutil.copyfile(src_file, dest_file)
  File "/usr/lib/python3.8/shutil.py", line 272, in copyfile
    _fastcopy_sendfile(fsrc, fdst)
  File "/usr/lib/python3.8/shutil.py", line 169, in _fastcopy_sendfile
    raise err
  File "/usr/lib/python3.8/shutil.py", line 149, in _fastcopy_sendfile
    sent = os.sendfile(outfd, infd, offset, blocksize)
OSError: [Errno 29] Illegal seek: '/mnt/4medusa/PLEX/Series1080/Modern Family/Temporada 3/Modern Family - 3x19 - El día de las elecciones.mkv' -> '/mnt/Series-Continua/Modern Family (2009) [Terminó] [tt1442437]/Season 03/Modern Family - S03E19 - El día de las elecciones.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
You modified/removed/copied/etc. the file manually while Medusa was working with it. Don't do it.
