### ISSUE TITLE
SYNOLOGY: db type is dbm.gnu, but the module is not available 

### ISSUE THREAD

**Issue by rdkruk** [pymedusa/Medusa#9612]
**Describe the bug**
I ge this error "db type is dbm.gnu, but the module is not available" when I open Trakt - Most anticipated shows. I do have my account set up properly.

**To Reproduce**
1. Go to 'Add Recommended shows'
2. Click on 'Add from Trakt lists.'
3. See error

**Expected behavior**
A list of shows to add. This is the case when Medusa ran on my laptop but on my Synology it is not possible....

**Screenshots**
Fetching of Recommender Data failed. Exception:

db type is dbm.gnu, but the module is not available

**Medusa (please complete the following information):**
 - OS: [e.g. ubuntu 14.04 x64]
 - Branch: [e.g. master, develop]
 - Commit: [e.g. c65ca2]
 - Python version: [e.g. 3.6.8]
 - Database version: [e.g. 44.12]

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-06-07 10:17:54 ERROR    Thread_0 :: [4d9c792] Could not connect to Trakt service: db type is dbm.gnu, but the module is not available
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/medusa/show/recommendations/trakt.py", line 143, in fetch_popular_shows
    trending_shows.append(self._create_recommended_show(
  File "</volume1/@appstore/medusa/var/src/ext/decorator.py:decorator-gen-52>", line 2, in _create_recommended_show
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/backends/file.py", line 217, in get_serialized
    with self._dbm_file(False) as dbm_obj:
  File "/var/packages/python38/target/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/backends/file.py", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
  File "/var/packages/python38/target/lib/python3.8/dbm/__init__.py", line 91, in open
    raise error[0]("db type is {0}, but the module is not "
dbm.error: db type is dbm.gnu, but the module is not available
```
</details>

**Additional context**

**Comment by medariox** [comment]
See https://github.com/pymedusa/Medusa/issues/9094#issuecomment-766845722

**Comment by rdkruk** [comment]
Did that but resulted in this error:

2021-06-09 09:31:32 ERROR    Thread_0 :: [4d9c792] Could not connect to Trakt service: db file doesn't exist; use 'c' or 'n' flag to create a new db
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/medusa/show/recommendations/trakt.py", line 143, in fetch_popular_shows
    trending_shows.append(self._create_recommended_show(
  File "</volume1/@appstore/medusa/var/src/ext/decorator.py:decorator-gen-52>", line 2, in _create_recommended_show
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/region.py", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/backends/file.py", line 217, in get_serialized
    with self._dbm_file(False) as dbm_obj:
  File "/var/packages/python38/target/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/volume1/@appstore/medusa/var/src/ext/dogpile/cache/backends/file.py", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
  File "/var/packages/python38/target/lib/python3.8/dbm/__init__.py", line 85, in open
    raise error[0]("db file doesn't exist; "
dbm.error: db file doesn't exist; use 'c' or 'n' flag to create a new db****

**Comment by rdkruk** [comment]
Restart of MEdusa will fix the latest error
