### ISSUE TITLE
Post-process directory lost after each reboot

### ISSUE THREAD

**Issue by Yellow1144** [pymedusa/Medusa#9672]
This has been going on for some time.

After the system reboots, the setting for the post-processing directory is empty. I have to set the directory after each reboot. 

I set the directory, save the change and restart Medusa. I restart Medusa to reset Post-Processor Alive status from False to True.

After the latest update Medusa throws the following error:

2021-06-24 14:17:46 ERROR    POSTPROCESSOR :: [75efce3] Exception generated: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/home/user/.pymedusa/medusa/schedulers/scheduler.py", line 78, in run
    self.action.run(self.force)
  File "/home/user/.pymedusa/medusa/process_tv.py", line 188, in run
    if not os.path.isdir(path):
  File "/usr/lib/python3.8/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Branch: develop
Commit: 75efce361775feb81977bfbad403701616a6370e
Version: 0.5.13
Database: 44.18
Python Version: | 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
SSL Version: | OpenSSL 1.1.1f 31 Mar 2020
OS: | Linux-5.8.0-55-generic-x86_64-with-glibc2.29
Locale: | en_CA.UTF-8
Timezone: | CDT

**Comment by p0psicles** [comment]
Can you save and immediately check the config.ini? It should be changed there. I think it's called download_dir

**Comment by Yellow1144** [comment]
Yeah, i forgot to mention that. Once saved the directory is in the config.ini

**Comment by p0psicles** [comment]
Then it's probably a rights issue

**Comment by Yellow1144** [comment]
nope, I thought about that too. Medusa resides in home folder, as always, nothing has changed there, and the same with the downloads folder. Rights are as they should be.

**Comment by medariox** [comment]
Are you sure the path is in the config.ini after the restart? It's called `tv_download_dir`.

**Comment by Yellow1144** [comment]
Yes.. I just did it again today. I have been having problems with system crashes, but this problem happens whether the system crashes or I shut down or reboot the system normally.

After reboot, the post process folder field in Settings>Post-Processing is blank. I look at the config.ini, sure enough tv_download_dir is empty. In Medusa I add the folder as I normally would and save settings. I look at the config.ini again and now the path appears where it should. ( I also have to update Settings > Advanced Settings > Anonymous Redirect since a couple of weeks back I changed this to anonym.to due to the deferer.org issue. This setting is lost in reboots too.)

Quite often I forget to do this soon after the reboot and I guess Medusa stops trying to post process because under Server Status> Scheduler>Post Process is showing False under the Alive column. So after adding the path I then go and restart from within Medusa. Medusa restarts normally, Post process alive status is True, and the path is still stored properly in config.ini and Medusa works properly until the next crash or reboot.

**Comment by Yellow1144** [comment]
Ok, the strangeness deepens.

I have always had Medusa running as a service. (The same way i run Jackett) Just for the heck of it I tried shutting down Medusa by stopping the service. No errors presented, but Medusa was still running!! Tried again, same thing. I listed the services on my machine (systemctl --type=service) and medusa isn't even in the list (Jackett is and shows loaded, active and running) but Medusa is running!!??

The medusa.service file is still in /etc/systemd/system along with various other services I have set up.

htop and KSysGuard both report Medusa running from the command:
/usr/bin/python3.8 /home/user/.pymedusa/start.py -q --nolaunch --datadir=/home/user/.pymedusa

Exactly as laid out in my service file except stopping, starting disabling the service has no effect and Medusa continues to run.

I shut down Medusa from within Medusa. Verify that it is not running. 

I then start the medusa service. Medusa starts and the service is now listed and running. AND the download directory and Anonymous Redirect are both still in the config file and are showing up properly in Medusa. All is just like it should be.

Then I decide to reboot and see what happens. 

Now the medusa service is listed and running. htop shows the correct command, the config.ini file has the correct download path and Anonymous Redirect settings. I look at Medusa and when I look at the Post Process settings, the path is not showing, yet is it in the config.ini!!?!?! (and post process status alive is showing false)

So despite the correct data being in the config file, I add the correct path to the blank field and then restart from within Medusa.

Medusa restarts, but the service is no longer listed and service status shows inactive (dead) This makes sense now as Medusa restarted itself. The Config.ini file modified time shows the correct time of the restart. 

So the question is after this last reboot, when the correct info it in the config file, is it not showing up in the settings?

**Comment by Yellow1144** [comment]
I just checked again. I just rebooted, config.ini contains the correct download path, but Medusa shows no path entered (and again same with Anonymous redirect). I tried just stopping and restarting the service, no change. Prior to the reboot, Medusa was working and post-processing normally.

**Comment by p0psicles** [comment]
What's the contents of your systemd file?

**Comment by Yellow1144** [comment]
I assume you are talking about the contents of the medusa.service file itself and not the complete list of everything in that /systemd/system folder

Here it is..

[Unit]
Description=Medusa Daemon
After=network.target

[Service]
SyslogIdentifier=medusa
User=user
Group=user
Type=simple
GuessMainPID=no
ExecStart=/usr/bin/python3.8 /home/user/.pymedusa/start.py -q --nolaunch --datadir=/home/user/.pymedusa
TimeoutStopSec=25
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
