### ISSUE TITLE
Trakt TV oAuth Issue

### ISSUE THREAD

**Issue by spattersTatt** [pymedusa/Medusa#9748]
Howdy,

This has only just started for me. I went to view recommeneded Trakt shows, which I have been doing for some time now.....  
and getting this error.

2021-07-24 12:04:01 ERROR    Thread_12 :: [9b23c72] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/opt/medusa/medusa/show/recommendations/trakt.py", line 113, in fetch_popular_shows
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/opt/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/opt/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided

Goto configuration motifications to set up link to Trakt again, sign in, its asking to enter a code which is being shown on the device????

Where is this code being displayed? otherwise the linking fails......

Debug Log:

2021-07-24 12:04:01 ERROR	Thread-12 :: [9b23c72] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/opt/medusa/medusa/show/recommendations/trakt.py", line 113, in fetch_popular_shows
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/opt/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/opt/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
2021-07-24 11:57:58 INFO	Thread-9 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:53 INFO	Thread-8 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:48 INFO	Thread-14 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:43 INFO	Thread-13 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:38 INFO	Thread-4 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:33 INFO	Thread-18 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:28 INFO	Thread-11 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:23 INFO	Thread-19 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:18 INFO	Thread-16 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:13 INFO	Thread-15 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:12 INFO	Thread-3 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:08 INFO	Thread-2 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:07 INFO	Thread-8 :: [9b23c72] Start Trakt token request
2021-07-24 11:57:03 INFO	Thread :: [9b23c72] Start Trakt token request
2021-07-24 11:57:02 INFO	Thread-12 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:57 INFO	Thread-1 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:52 INFO	Thread-6 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:47 INFO	Thread-17 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:42 INFO	Thread-10 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:36 INFO	Thread-9 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:31 INFO	Thread-5 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:26 INFO	Thread-14 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:21 INFO	Thread-13 :: [9b23c72] Start Trakt token request
2021-07-24 11:56:16 INFO	Thread-4 :: [9b23c72] Start Trakt token request
2021-07-24 11:55:24 INFO	Thread-11 :: [9b23c72] Start Trakt token request
2021-07-24 11:55:19 INFO	Thread-19 :: [9b23c72] Start Trakt token request
2021-07-24 11:55:14 INFO	Thread-16 :: [9b23c72] Start Trakt token request
2021-07-24 11:55:09 INFO	Thread-15 :: [9b23c72] Start Trakt token request
2021-07-24 11:55:04 INFO	Thread-3 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:59 INFO	Thread-2 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:54 INFO	Thread-8 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:49 INFO	Thread :: [9b23c72] Start Trakt token request
2021-07-24 11:54:44 INFO	Thread-12 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:39 INFO	Thread-1 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:34 INFO	Thread-18 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:29 INFO	Thread-6 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:24 INFO	Thread-17 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:19 INFO	Thread-9 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:14 INFO	Thread-5 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:09 INFO	Thread-14 :: [9b23c72] Start Trakt token request
2021-07-24 11:54:04 INFO	Thread-13 :: [9b23c72] Start Trakt token request
2021-07-24 11:53:58 INFO	Thread-4 :: [9b23c72] Start Trakt token request
2021-07-24 11:53:53 INFO	Thread-7 :: [9b23c72] Start Trakt token request
2021-07-24 11:53:48 WARNING	Thread-11 :: [9b23c72] Unable to test TRAKT: OAuthException(<Response [401]>)
2021-07-24 11:53:48 WARNING	Thread-11 :: [9b23c72] Unable to get trakt user, error: Unauthorized - OAuth must be provided
2021-07-24 11:53:47 INFO	Thread-18 :: [9b23c72] Start Trakt token request
2021-07-24 11:53:45 WARNING	Thread-10 :: [9b23c72] Unable to test TRAKT: OAuthException(<Response [401]>)
2021-07-24 11:53:45 WARNING	Thread-10 :: [9b23c72] Unable to get trakt user, error: Unauthorized - OAuth must be provided
2021-07-24 11:53:43 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 11:53:42 INFO	Thread-15 :: [9b23c72] Start Trakt token request
2021-07-24 11:53:40 WARNING	Thread-2 :: [9b23c72] Unable to test TRAKT: OAuthException(<Response [401]>)
2021-07-24 11:53:40 WARNING	Thread-2 :: [9b23c72] Unable to get trakt user, error: Unauthorized - OAuth must be provided
2021-07-24 11:53:37 INFO	Thread-8 :: [9b23c72] Start Trakt token request
2021-07-24 11:53:32 INFO	Thread :: [9b23c72] Start Trakt token request
2021-07-24 11:53:27 INFO	Thread-12 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:53 INFO	Thread-19 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:48 INFO	Thread-6 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:43 INFO	Thread-17 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:38 INFO	Thread-16 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:33 INFO	Thread-9 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:28 INFO	Thread-5 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:23 INFO	Thread-14 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:18 INFO	Thread-13 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:13 INFO	Thread-4 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:08 INFO	Thread-7 :: [9b23c72] Start Trakt token request
2021-07-24 11:51:03 INFO	Thread-11 :: [9b23c72] Start Trakt token request
2021-07-24 11:50:58 INFO	Thread-18 :: [9b23c72] Start Trakt token request
2021-07-24 11:48:53 ERROR	Thread-15 :: [9b23c72] Could not connect to Trakt service: Unauthorized - OAuth must be provided
Traceback (most recent call last):
  File "/opt/medusa/medusa/show/recommendations/trakt.py", line 113, in fetch_popular_shows
    library_shows = sync.get_watched('shows', extended='noseasons') + sync.get_collection('shows', extended='full')
  File "/opt/medusa/ext/trakt/core.py", line 547, in inner
    json_data = self._handle_request('get', url)
  File "/opt/medusa/ext/trakt/core.py", line 524, in _handle_request
    raise self.error_map[response.status_code](response)
trakt.errors.OAuthException: Unauthorized - OAuth must be provided
2021-07-24 11:41:41 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 11:40:10 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] No shows found in your Trakt library. Nothing to sync
2021-07-24 11:40:10 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] Unable to retrieve shows from Trakt collection. Error: OAuthException(<Response [401]>)
2021-07-24 11:39:47 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] No shows found in your Trakt library. Nothing to sync
2021-07-24 11:39:47 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] Unable to retrieve shows from Trakt collection. Error: OAuthException(<Response [401]>)
2021-07-24 11:39:22 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] No shows found in your Trakt library. Nothing to sync
2021-07-24 11:39:22 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] Unable to retrieve shows from Trakt collection. Error: OAuthException(<Response [401]>)
2021-07-24 11:38:53 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] No shows found in your Trakt library. Nothing to sync
2021-07-24 11:38:53 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] Unable to retrieve shows from Trakt collection. Error: OAuthException(<Response [401]>)
2021-07-24 11:36:35 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] No shows found in your Trakt library. Nothing to sync
2021-07-24 11:36:35 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] Unable to retrieve shows from Trakt collection. Error: OAuthException(<Response [401]>)
2021-07-24 11:36:08 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] No shows found in your Trakt library. Nothing to sync
2021-07-24 11:36:08 INFO	SHOWQUEUE-REMOVE-SHOW :: [9b23c72] Unable to retrieve shows from Trakt collection. Error: OAuthException(<Response [401]>)
2021-07-24 10:58:45 DEBUG	SHOWQUEUE-UPDATE :: [9b23c72] Looking for externals using Trakt and imdb id tt1319900
2021-07-24 10:41:41 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 09:41:40 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 08:41:39 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 07:41:38 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 06:41:38 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 05:41:37 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 04:41:36 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 04:33:36 WARNING	TORNADO :: [9b23c72] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-24 04:17:26 DEBUG	SHOWQUEUE-SEASON-UPDATE :: [9b23c72] Looking for externals using Trakt and imdb id tt10986410
2021-07-24 03:41:35 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 02:41:34 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 01:41:33 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-24 00:41:32 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-23 23:41:32 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-23 22:41:31 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-23 21:41:30 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-23 20:41:30 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-23 19:41:29 DEBUG	TRAKTCHECKER :: [9b23c72] Starting new thread: TRAKTCHECKER
2021-07-23 19:10:39 WARNING	TORNADO :: [9b23c72] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 18:41:06 INFO	EVENT-QUEUE :: [9b23c72] Waiting for the TRAKTCHECKER thread to exit
2021-07-23 18:07:07 DEBUG	TRAKTCHECKER :: [db102f3] Starting new thread: TRAKTCHECKER
2021-07-23 17:57:26 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 17:46:30 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 17:40:28 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 17:39:52 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 17:38:54 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 17:36:02 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 17:07:07 DEBUG	TRAKTCHECKER :: [db102f3] Starting new thread: TRAKTCHECKER
2021-07-23 16:07:06 DEBUG	TRAKTCHECKER :: [db102f3] Starting new thread: TRAKTCHECKER
2021-07-23 15:07:06 DEBUG	TRAKTCHECKER :: [db102f3] Starting new thread: TRAKTCHECKER
2021-07-23 14:57:50 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 14:43:06 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 14:23:24 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 14:21:44 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 14:19:42 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)
2021-07-23 14:07:05 DEBUG	TRAKTCHECKER :: [db102f3] Starting new thread: TRAKTCHECKER
2021-07-23 13:07:04 DEBUG	TRAKTCHECKER :: [db102f3] Starting new thread: TRAKTCHECKER
2021-07-23 12:48:17 WARNING	TORNADO :: [db102f3] Unable to update Trakt: OAuthException(<Response [401]>)

**Comment by p0psicles** [comment]
![image](https://user-images.githubusercontent.com/1331394/126892999-6ed96751-0b6a-4560-b9f2-760dbf61fa09.png)

**Comment by spattersTatt** [comment]
Thanks but i dont see that i medusa, and when i check for updates im at current version..Will check again tomorrowSent on the go with Vodafone
-------- Original message --------From: p0ps ***@***.***> Date: 25/7/21  18:06  (GMT+09:30) To: pymedusa/Medusa ***@***.***> Cc: spattersTatt ***@***.***>, Author ***@***.***> Subject: Re: [pymedusa/Medusa] Trakt TV oAuth Issue (#9748)

**Comment by spattersTatt** [comment]
Confirmed, code did appear, was just hiddenSent on the go with Vodafone
-------- Original message --------From: p0ps ***@***.***> Date: 25/7/21  18:06  (GMT+09:30) To: pymedusa/Medusa ***@***.***> Cc: spattersTatt ***@***.***>, Author ***@***.***> Subject: Re: [pymedusa/Medusa] Trakt TV oAuth Issue (#9748)
