### ISSUE TITLE
TypeError: attrs() got an unexpected keyword argument 'eq'

### ISSUE THREAD

**Issue by Nodens-** [pymedusa/Medusa#9773]
**Describe the bug**
Medusa won't start after upgrade to Fedora 34

**To Reproduce**
systemctl start medusa

**Expected behavior**
Medusa starting

**Medusa (please complete the following information):**
 - OS: Fedora 34 x64
 - Branch: Both master and develop
 - Commit: commit 9b23c72f7e24bf638819e32d72f33e433f9649c4 (HEAD -> master, tag: v0.5.15, origin/master)
 - Python version: 3.9.6
 - Database version: Not sure how to check this when medusa won't start.

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
python[2152612]: detected unhandled Python exception in '/opt/medusa/start.py'
abrt-server[2152613]: Not saving repeating crash in '/opt/medusa/start.py'
python[2152612]: Traceback (most recent call last):
python[2152612]:  File "/opt/medusa/start.py", line 6, in <module>
python[2152612]:    from medusa.__main__ import main
python[2152612]:  File "/opt/medusa/medusa/__init__.py", line 24, in <module>
python[2152612]:    initialize()
python[2152612]:  File "/opt/medusa/medusa/init/__init__.py", line 37, in initialize
python[2152612]:    _configure_guessit()
python[2152612]:  File "/opt/medusa/medusa/init/__init__.py", line 202, in _configure_guessit
python[2152612]:    from medusa.name_parser.guessit_parser import (
python[2152612]:  File "/opt/medusa/medusa/name_parser/guessit_parser.py", line 12, in <module>
python[2152612]:    from medusa.logger.adapters.style import BraceAdapter
python[2152612]:  File "/opt/medusa/medusa/logger/__init__.py", line 44, in <module>
python[2152612]:    import knowit
python[2152612]:  File "/opt/medusa/ext/knowit/__init__.py", line 27, in <module>
python[2152612]:    from .api import KnowitException, know
python[2152612]:  File "/opt/medusa/ext/knowit/api.py", line 7, in <module>
python[2152612]:    from .config import Config
python[2152612]:  File "/opt/medusa/ext/knowit/config.py", line 11, in <module>
python[2152612]:    from .serializer import get_yaml_loader
python[2152612]:  File "/opt/medusa/ext/knowit/serializer.py", line 12, in <module>
python[2152612]:    from .units import units
python[2152612]:  File "/opt/medusa/ext/knowit/units.py", line 24, in <module>
python[2152612]:    units = _build_unit_registry()
python[2152612]:  File "/opt/medusa/ext/knowit/units.py", line 6, in _build_unit_registry
python[2152612]:    from pint import UnitRegistry
python[2152612]:  File "/opt/medusa/ext/pint/__init__.py", line 18, in <module>
python[2152612]:    from .formatting import formatter
python[2152612]:  File "/opt/medusa/ext/pint/formatting.py", line 16, in <module>
python[2152612]:    from .babel_names import _babel_units, _babel_lengths
python[2152612]:  File "/opt/medusa/ext/pint/babel_names.py", line 10, in <module>
python[2152612]:    from pint.compat import HAS_PROPER_BABEL
python[2152612]:  File "/opt/medusa/ext/pint/compat/__init__.py", line 136, in <module>
python[2152612]:    import pytest
python[2152612]:  File "/usr/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
python[2152612]:    from _pytest.assertion import register_assert_rewrite
python[2152612]:  File "/usr/lib/python3.9/site-packages/_pytest/assertion/__init__.py", line 9, in <module>
python[2152612]:    from _pytest.assertion import rewrite
python[2152612]:  File "/usr/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 34, in <module>
python[2152612]:    from _pytest.assertion import util
python[2152612]:  File "/usr/lib/python3.9/site-packages/_pytest/assertion/util.py", line 13, in <module>
python[2152612]:    import _pytest._code
python[2152612]:  File "/usr/lib/python3.9/site-packages/_pytest/_code/__init__.py", line 2, in <module>
python[2152612]:    from .code import Code
python[2152612]:  File "/usr/lib/python3.9/site-packages/_pytest/_code/code.py", line 942, in <module>
python[2152612]:    @attr.s(eq=False)
python[2152612]: TypeError: attrs() got an unexpected keyword argument 'eq'

```
</details>

**Additional context**

**Comment by medariox** [comment]
You have an old / unsupported version of attrs installed on your machine.
You can remove it with `pip3 uninstall attrs` or `pip uninstall attrs`.

**Comment by Nodens-** [comment]
I don't have old version. I have python3-attrs package from the fedora repo and that's not old..it's ` python3-attrs-20.3.0-2.fc34.noarch`
Maybe something got deprecated in 20.3.0?

**Comment by medariox** [comment]
I wrote old / unsupported. In this case it seems to be both, since the latest attrs version is 21.2.0: https://pypi.org/project/attrs/
In any case you need to remove it. If it is not installed with pip, you will have to remove it with your package manager.

**Comment by Nodens-** [comment]
Sorry my bad for assuming. Usually the case with Fedora is that it is shipping too new packages and software hits deprecated stuff or syntax changes and not the other way around. Also surprised Medusa would support so cutting edge when 99% of distros would not even be shipping 20.3.0 heh.
In any case I removed it although I'm not sure if anything else breaks as this is a production server not administered and utilized solely by me and the package was installed at some point for a reason. In case things break, will Medusa be ok with pulling 21.2.0 from pip?

**Comment by medariox** [comment]
Sadly Medusa will try to use the system-wide packages first (I know this is not great, we need to change it), so it will probably cause the exception again if you install it with pip. Btw you were right about the package being too new. I just checked and Medusa seems to use attrs version 18.2.0 by default. You could try to install that version with pip or maybe even go up to 19.x - you will need to try it, because I'm not sure when the compatibility stops.

**Comment by Nodens-** [comment]
Understood, thank you very much. I would close this at this point but I'll leave it up to you in case you want to leave it open in order to deal with the compatibility of the newer attrs packages and/or the system-wide packages priority issue.

**Comment by BenjV** [comment]
This kind of issues can be resolved by using a virtual environment for medusa.
The side-packages that Medusa needs should then be installed in that virtual environment with:
pip install --ignore-installed 

If you do it this way medusa will use its own site-packages while the system-wide site-packages are left in place for other applications.
