### ISSUE TITLE
[APP SUBMITTED]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by wreid23** [pymedusa/Medusa#9839]
### INFO
**Python Version**: `3.8.10 (default, May  6 2021, 06:30:44) [GCC 9.3.0]`
**Operating System**: `Linux-4.4.59+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-08-29 19:49:24 ERROR    Thread_1 :: [] Exception generated: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/app/medusa/medusa/server/web/core/base.py", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/medusa/server/web/home/handler.py", line 1688, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</app/medusa/ext/decorator.py:decorator-gen-19>", line 2, in get_release_groups_for_anime
  File "/app/medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/app/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/app/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/app/medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/app/medusa/ext/dogpile/cache/region.py", line 1264, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/app/medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.8/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
In your cache folder delete your *.dbm files and restart

**Comment by dirkronsmans** [comment]
### INFO
**Python Version**: `3.7.11 (default, Aug 31 2021, 17:29:26) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-4.4.59+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@6f25e867c61de1dbcabe813d6ad62d8e5667f238
**Link to Log**: https://gist.github.com/1e50d2b89e820c79ff4e767b69e65efa
### ERROR
<pre>
2021-11-02 14:27:20 ERROR    Thread_7 :: [6f25e86] Exception generated: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/medusa/server/web/home/handler.py#L1012">medusa/server/web/home/handler.py</a>", line 1012, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</volume1/@appstore/medusa/var/src/ext/decorator.py:decorator-gen-19>", line 2, in get_release_groups_for_anime
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L1578">ext/dogpile/cache/region.py</a>", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L1047">ext/dogpile/cache/region.py</a>", line 1047, in get_or_create
    async_creator,
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/lock.py#L185">ext/dogpile/lock.py</a>", line 185, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/lock.py#L87">ext/dogpile/lock.py</a>", line 87, in _enter
    value = value_fn()
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L977">ext/dogpile/cache/region.py</a>", line 977, in get_value
    value = self._get_from_backend(key)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L1265">ext/dogpile/cache/region.py</a>", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L1221">ext/dogpile/cache/region.py</a>", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/var/packages/python3/target/lib/python3.7/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by dirkronsmans** [comment]
### INFO
**Python Version**: `3.7.11 (default, Aug 31 2021, 17:29:26) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-4.4.59+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@6f25e867c61de1dbcabe813d6ad62d8e5667f238
**Link to Log**: https://gist.github.com/32fcde1c9d8f257bf40b7e97e276753d
### ERROR
<pre>
2021-11-02 14:29:23 ERROR    Thread_8 :: [6f25e86] Exception generated: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/medusa/server/web/home/handler.py#L1012">medusa/server/web/home/handler.py</a>", line 1012, in fetch_releasegroups
    groups = get_release_groups_for_anime(series_name)
  File "</volume1/@appstore/medusa/var/src/ext/decorator.py:decorator-gen-19>", line 2, in get_release_groups_for_anime
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L1578">ext/dogpile/cache/region.py</a>", line 1578, in get_or_create_for_user_func
    key, user_func, timeout, should_cache_fn, (arg, kw)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L1047">ext/dogpile/cache/region.py</a>", line 1047, in get_or_create
    async_creator,
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/lock.py#L185">ext/dogpile/lock.py</a>", line 185, in __enter__
    return self._enter()
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/lock.py#L87">ext/dogpile/lock.py</a>", line 87, in _enter
    value = value_fn()
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L977">ext/dogpile/cache/region.py</a>", line 977, in get_value
    value = self._get_from_backend(key)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L1265">ext/dogpile/cache/region.py</a>", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/6f25e867c61de1dbcabe813d6ad62d8e5667f238/ext/dogpile/cache/region.py#L1221">ext/dogpile/cache/region.py</a>", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/var/packages/python3/target/lib/python3.7/json/__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
