### ISSUE TITLE
[APP SUBMITTED]: dbm.error: db type could not be determined

### ISSUE THREAD

**Issue by garak70** [pymedusa/Medusa#9848]
### INFO
**Python Version**: `3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]`
**Operating System**: `Linux-5.4.0-85-generic-x86_64-with-glibc2.29`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@fbd43ad634662f2353739391127fc77e00454b78
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-09-10 02:05:01 ERROR    GENERICQUEUESCHEDULER-UPDATE-RECOMMENDED-TRAKT :: [fbd43ad] Could not connect to Trakt service: db type could not be determined
Traceback (most recent call last):
  File "/media/**********/2TBHYBSG/medusa/medusa/show/recommendations/trakt.py", line 165, in fetch_popular_shows
    recommended_show = self._create_recommended_show(show, subcat=trakt_list)
  File "</media/**********/2TBHYBSG/medusa/ext/decorator.py:decorator-gen-54>", line 2, in _create_recommended_show
  File "/media/**********/2TBHYBSG/medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/media/**********/2TBHYBSG/medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/media/**********/2TBHYBSG/medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/media/**********/2TBHYBSG/medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/media/**********/2TBHYBSG/medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/media/**********/2TBHYBSG/medusa/ext/dogpile/cache/region.py", line 1265, in _get_from_backend
    self.backend.get_serialized(key)
  File "/media/**********/2TBHYBSG/medusa/ext/dogpile/cache/backends/file.py", line 217, in get_serialized
    with self._dbm_file(False) as dbm_obj:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/media/**********/2TBHYBSG/medusa/ext/dogpile/cache/backends/file.py", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
  File "/usr/lib/python3.8/dbm/__init__.py", line 89, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by p0psicles** [comment]
dogpille cache file is corrupt.

Stop medusa
go into your cache folder and delete all *.dbm files
start

**Comment by Bogey** [comment]
### INFO
**Python Version**: `3.8.10 (default, May  6 2021, 06:30:44) [GCC 9.3.0]`
**Operating System**: `Linux-4.4.180+-x86_64-with`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@0286e89d15c86c8a9586e82f373d019f656f8b42
**Link to Log**: https://gist.github.com/647bf96e14314a9ce01a76e48c5d7425
### ERROR
<pre>
2021-11-07 21:02:42 ERROR    Thread_0 :: [0286e89] Exception generated: db type could not be determined
Traceback (most recent call last):
  File "/app/medusa/<a href="../blob/0286e89d15c86c8a9586e82f373d019f656f8b42/medusa/server/web/core/base.py#L252">medusa/server/web/core/base.py</a>", line 252, in async_call
    result = function(**kwargs)
  File "/app/medusa/<a href="../blob/0286e89d15c86c8a9586e82f373d019f656f8b42/medusa/server/web/home/handler.py#L875">medusa/server/web/home/handler.py</a>", line 875, in manualSearchSubtitles
    found_subtitles = subtitles.list_subtitles(tv_episode=ep_obj, video_path=video_path)
  File "/app/medusa/<a href="../blob/0286e89d15c86c8a9586e82f373d019f656f8b42/medusa/subtitles.py#L343">medusa/subtitles.py</a>", line 343, in list_subtitles
    cache.set(subtitle_key.format(id=subtitle.id).encode('utf-8'), subtitle)
  File "/app/medusa/<a href="../blob/0286e89d15c86c8a9586e82f373d019f656f8b42/ext/dogpile/cache/region.py#L1319">ext/dogpile/cache/region.py</a>", line 1319, in set
    self.backend.set_serialized(key, self._serialized_payload(value))
  File "/app/medusa/<a href="../blob/0286e89d15c86c8a9586e82f373d019f656f8b42/ext/dogpile/cache/backends/file.py#L232">ext/dogpile/cache/backends/file.py</a>", line 232, in set_serialized
    with self._dbm_file(True) as dbm_obj:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/app/medusa/<a href="../blob/0286e89d15c86c8a9586e82f373d019f656f8b42/ext/dogpile/cache/backends/file.py#L213">ext/dogpile/cache/backends/file.py</a>", line 213, in _dbm_file
    with dbm.open(self.filename, "w" if write else "r") as dbm_obj:
  File "/usr/lib/python3.8/dbm/__init__.py", line 89, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators
