### ISSUE TITLE
Can't edit show if a release group has a unicode error

### ISSUE THREAD

**Issue by mwstowe** [pymedusa/Medusa#9869]
One cannot edit a show if the list of release groups retrieved has a Unicode error; this is naturally a problem with those shows associated with release groups that throw an error.  This is a typical exception:

`{"config":{"aliases":[{"season":4,"title":"Higurashi no Naku Koro ni Kira","custom":false},{"season":1,"title":"Higurashi no Naku Koro ni","custom":false},{"season":2,"title":"Higurashi no Naku Koro ni Kai","custom":false},{"season":3,"title":"Higurashi no Naku Koro ni Rei","custom":false}],"defaultEpisodeStatus":"Wanted","dvdOrder":false,"seasonFolders":false,"anime":true,"scene":true,"sports":false,"paused":false,"location":"/pub/video/Anime/When They Cry - Higurashi","airByDate":false,"subtitlesEnabled":false,"release":{"requiredWords":[],"ignoredWords":[],"requiredWordsExclude":false,"ignoredWordsExclude":false,"blacklist":["Ohys-Raws"],"whitelist":[]},"qualities":{"preferred":[],"allowed":[2,4,8,32,64,128,256,512,1024,2048,4096,8192,16384,32768]},"airdateOffset":0,"showLists":["Anime"]},"language":"en"}
Traceback (most recent call last):
  File "/opt/Medusa/medusa/helpers/anidb.py", line 102, in short_group_names
    short_group_list += get_short_group_name(group_name) or [group_name]
  File "</opt/Medusa/ext/decorator.py:decorator-gen-20>", line 2, in get_short_group_name
  File "/opt/Medusa/ext/dogpile/cache/region.py", line 1577, in get_or_create_for_user_func
    return self.get_or_create(
  File "/opt/Medusa/ext/dogpile/cache/region.py", line 1042, in get_or_create
    with Lock(
  File "/opt/Medusa/ext/dogpile/lock.py", line 185, in __enter__
    return self._enter()
  File "/opt/Medusa/ext/dogpile/lock.py", line 87, in _enter
    value = value_fn()
  File "/opt/Medusa/ext/dogpile/cache/region.py", line 977, in get_value
    value = self._get_from_backend(key)
  File "/opt/Medusa/ext/dogpile/cache/region.py", line 1264, in _get_from_backend
    return self._parse_serialized_from_backend(
  File "/opt/Medusa/ext/dogpile/cache/region.py", line 1221, in _parse_serialized_from_backend
    metadata = json.loads(bytes_metadata)
  File "/usr/lib/python3.9/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

I've created a patch that, well, sidesteps this issue by ignoring groups that throw this exception.
[anidb.py.txt](https://github.com/pymedusa/Medusa/files/7159045/anidb.py.txt)

**Comment by p0psicles** [comment]
Can you try deleting all *.dbm files in cache folder first. And restart

**Comment by mwstowe** [comment]
Well, that seems to solve it.

Thanks
