### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [Errno 13] Permission denied: "/volume2/series/NCIS  Nouvelle-Orléans/Season 07/metadata/NCIS  Nouvelle-Orléans - S07E01 - Quelque chose dans l'air, partie 1.jpg"

### ISSUE THREAD

**Issue by Orion83** [pymedusa/Medusa#9872]
### INFO
**Python Version**: `3.8.11 (default, Aug 31 2021, 13:38:08) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-4.4.59+-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@fbd43ad634662f2353739391127fc77e00454b78
**Link to Log**: https://gist.github.com/0bf64edc030f587c29697b3ad0a2fae2
### ERROR
<pre>
2021-09-14 12:39:10 ERROR    Thread_0 :: [fbd43ad] Failed renaming '/volume2/series/NCIS  Nouvelle-Orléans/Season 07/metadata/NCIS  Nouvelle-Orléans - S07E01 - Something in the Air (1).jpg' to '/volume2/series/NCIS  Nouvelle-Orléans/Season 07/metadata/NCIS  Nouvelle-Orléans - S07E01 - Quelque chose dans l'air, partie 1.jpg' : PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/var/packages/python38/target/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/volume2/series/NCIS  Nouvelle-Orléans/Season 07/metadata/NCIS  Nouvelle-Orléans - S07E01 - Something in the Air (1).jpg' -> "/volume2/series/NCIS  Nouvelle-Orléans/Season 07/metadata/NCIS  Nouvelle-Orléans - S07E01 - Quelque chose dans l'air, partie 1.jpg"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/src/<a href="../blob/fbd43ad634662f2353739391127fc77e00454b78/medusa/helpers/__init__.py#L577">medusa/helpers/__init__.py</a>", line 577, in rename_ep_file
    shutil.move(cur_path, new_path)
  File "/var/packages/python38/target/lib/python3.8/shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "/var/packages/python38/target/lib/python3.8/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/var/packages/python38/target/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: "/volume2/series/NCIS  Nouvelle-Orléans/Season 07/metadata/NCIS  Nouvelle-Orléans - S07E01 - Quelque chose dans l'air, partie 1.jpg"
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by medariox** [comment]
Check your permissions.
