### ISSUE TITLE
[APP SUBMITTED]: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'I:\\Downloads\\Ordinary.Joe.S01E01.1080p.WEB.H264-CAKES[rarbg]\\ordinary.joe.s01e01.1080p.web.h264-cakes.mkv'

### ISSUE THREAD

**Issue by WarEagleUS21** [pymedusa/Medusa#9897]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-09-21 04:51:15 ERROR    POSTPROCESSQUEUE-POST-PROCESS :: [21e350c] Unable to move file I:\Downloads\Ordinary.Joe.S01E01.1080p.WEB.H264-CAKES[rarbg]\ordinary.joe.s01e01.1080p.web.h264-cakes.mkv to L:\TV Shows\Ordinary Joe\Season 1\Ordinary Joe - 1x01 - Way Leads on to Way.mkv: PermissionError(13, 'The process cannot access the file because it is being used by another process')
Traceback (most recent call last):
  File "C:\Medusa\Python\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'I:\\Downloads\\Ordinary.Joe.S01E01.1080p.WEB.H264-CAKES[rarbg]\\ordinary.joe.s01e01.1080p.web.h264-cakes.mkv' -> 'L:\\TV Shows\\Ordinary Joe\\Season 1\\Ordinary Joe - 1x01 - Way Leads on to Way.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/helpers/__init__.py#L320">medusa\helpers\__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 578, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'I:\\Downloads\\Ordinary.Joe.S01E01.1080p.WEB.H264-CAKES[rarbg]\\ordinary.joe.s01e01.1080p.web.h264-cakes.mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/post_processor.py#L477">medusa\post_processor.py</a>", line 477, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/helpers/__init__.py#L324">medusa\helpers\__init__.py</a>", line 324, in move_file
    os.unlink(src_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'I:\\Downloads\\Ordinary.Joe.S01E01.1080p.WEB.H264-CAKES[rarbg]\\ordinary.joe.s01e01.1080p.web.h264-cakes.mkv'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by WarEagleUS21** [comment]
Again, no idea why this submitted but please close.
