### ISSUE TITLE
[APP SUBMITTED]: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9090): Max retries exceeded with url: /gui/?action=add-url&s=magnet%3A%3Fxt%3Durn%3Abtih%3Ad1c4884eceb25fecf5615830223816483c1a5636%26dn%3DSee.S02E05.HDR.2160p.WEB.H265-GGEZ%255Brartv%255D%26tr%3Dhttp%253A%252F%252Ftracker.trackerfix.com%253A80%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.me%253A2970%26tr%3Dudp%253A%252F%252F9.rarbg.to%253A2890%26tr%3Dudp%253A%252F%252Ftracker.thinelephant.org%253A12720%26tr%3Dudp%253A%252F%252Ftracker.slowcheetah.org%253A14740%26tr%3Dudp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce%26tr%3Dhttp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce%26tr%3Dhttp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Fexplodie.org%3A6969%2Fa

### ISSUE THREAD

**Issue by ledderi** [pymedusa/Medusa#9907]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.19041-SP0`
**Locale**: `cp1255`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-09-25 06:18:33 ERROR    SNATCHQUEUE-SNATCH-34345 :: [21e350c] Snatch failed! For result: See.S02E05.HDR.2160p.WEB.H265-GGEZ[rartv]
Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connection.py#L159">ext\urllib3\connection.py</a>", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/util/connection.py#L80">ext\urllib3\util\connection.py</a>", line 80, in create_connection
    raise err
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/util/connection.py#L70">ext\urllib3\util\connection.py</a>", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connectionpool.py#L600">ext\urllib3\connectionpool.py</a>", line 600, in urlopen
    chunked=chunked)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connectionpool.py#L354">ext\urllib3\connectionpool.py</a>", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Medusa\Python\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Medusa\Python\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Medusa\Python\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Medusa\Python\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Medusa\Python\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connection.py#L181">ext\urllib3\connection.py</a>", line 181, in connect
    conn = self._new_conn()
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connection.py#L168">ext\urllib3\connection.py</a>", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001ABEED41748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/adapters.py#L449">ext\requests\adapters.py</a>", line 449, in send
    timeout=timeout
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/connectionpool.py#L638">ext\urllib3\connectionpool.py</a>", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/urllib3/util/retry.py#L398">ext\urllib3\util\retry.py</a>", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9090): Max retries exceeded with url: /gui/?action=add-url&s=magnet%3A%3Fxt%3Durn%3Abtih%3Ad1c4884eceb25fecf5615830223816483c1a5636%26dn%3DSee.S02E05.HDR.2160p.WEB.H265-GGEZ%255Brartv%255D%26tr%3Dhttp%253A%252F%252Ftracker.trackerfix.com%253A80%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.me%253A2970%26tr%3Dudp%253A%252F%252F9.rarbg.to%253A2890%26tr%3Dudp%253A%252F%252Ftracker.thinelephant.org%253A12720%26tr%3Dudp%253A%252F%252Ftracker.slowcheetah.org%253A14740%26tr%3Dudp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce%26tr%3Dhttp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce%26tr%3Dhttp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Fexplodie.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2F9.rarbg.com%3A2710%2Fannounce%26tr%3Dhttp%3A%2F%2Fexplodie.org%3A6969%2Fannounce%26tr%3Dhttp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce%26tr%3Dhttp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce%26tr%3Dudp%3A%2F%2Fmgtracker.org%3A2710%2Fannounce%26tr%3Dhttp%3A%2F&path=%5CSee (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ABEED41748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/search/queue.py#L516">medusa\search\queue.py</a>", line 516, in run
    self.success = snatch_result(result)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/search/core.py#L168">medusa\search\core.py</a>", line 168, in snatch_result
    result_downloaded = client.send_torrent(result)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/clients/torrent/generic.py#L230">medusa\clients\torrent\generic.py</a>", line 230, in send_torrent
    r_code = self._add_torrent_uri(result)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/clients/torrent/utorrent.py#L112">medusa\clients\torrent\utorrent.py</a>", line 112, in _add_torrent_uri
    'path': torrent_subfolder,
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/clients/torrent/utorrent.py#L84">medusa\clients\torrent\utorrent.py</a>", line 84, in _request
    return super(UTorrentAPI, self)._request(method=method, params=ordered_params, data=data, files=files)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/clients/torrent/generic.py#L63">medusa\clients\torrent\generic.py</a>", line 63, in _request
    verify=self.verify if app.TORRENT_VERIFY_CERT else False
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/session/core.py#L131">medusa\session\core.py</a>", line 131, in request
    timeout=timeout, verify=ssl_cert, **kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/sessions.py#L542">ext\requests\sessions.py</a>", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/sessions.py#L655">ext\requests\sessions.py</a>", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/ext/requests/adapters.py#L516">ext\requests\adapters.py</a>", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9090): Max retries exceeded with url: /gui/?action=add-url&s=magnet%3A%3Fxt%3Durn%3Abtih%3Ad1c4884eceb25fecf5615830223816483c1a5636%26dn%3DSee.S02E05.HDR.2160p.WEB.H265-GGEZ%255Brartv%255D%26tr%3Dhttp%253A%252F%252Ftracker.trackerfix.com%253A80%252Fannounce%26tr%3Dudp%253A%252F%252F9.rarbg.me%253A2970%26tr%3Dudp%253A%252F%252F9.rarbg.to%253A2890%26tr%3Dudp%253A%252F%252Ftracker.thinelephant.org%253A12720%26tr%3Dudp%253A%252F%252Ftracker.slowcheetah.org%253A14740%26tr%3Dudp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce%26tr%3Dhttp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce%26tr%3Dhttp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Fexplodie.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2F9.rarbg.com%3A2710%2Fannounce%26tr%3Dhttp%3A%2F%2Fexplodie.org%3A6969%2Fannounce%26tr%3Dhttp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969%2Fannounce%26tr%3Dudp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce%26tr%3Dudp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce%26tr%3Dhttp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce%26tr%3Dudp%3A%2F%2Fmgtracker.org%3A2710%2Fannounce%26tr%3Dhttp%3A%2F&path=%5CSee (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001ABEED41748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by neo-neo1** [comment]
This isn't a Medusa problem. Your setup is improperly configured, the `ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused` it tells you everything you need to know.
