### ISSUE TITLE
Search for show returns no results

### ISSUE THREAD

**Issue by Tailslide** [pymedusa/Medusa#9910]
**Describe the bug**
Searching for any show returns no results

**To Reproduce**
1. Go to 'add new show'
2. Search for trek
3. See the message 'No results found, try a different search.'

**Expected behavior**
Finds results

**Screenshots**
![image](https://user-images.githubusercontent.com/5757188/134798610-9fdbfdea-1666-4184-9624-4eade9325e78.png)

**Medusa (please complete the following information):**
 - OS: Linux-4.4.59+-x86_64-with
 - Branch: master
 - Commit: 9b23c72f7e24bf638819e32d72f33e433f9649c4
 - Python version: 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 - Database version: 44.18
 - Running official docker image

**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-09-26 01:48:27 DEBUG	APIv2-Thread :: [9b23c72] Searching for show trek
2021-09-26 01:48:27 DEBUG	APIv2-Thread :: [9b23c72] Searching for show with search term(s): ['trek'] on indexer: tvmaze
2021-09-26 01:48:27 DEBUG	APIv2-Thread :: [9b23c72] Using custom UI: <class 'medusa.classes.AllShowsListUI'>
2021-09-26 01:48:27 DEBUG	APIv2-Thread :: [9b23c72] User-Agent: Medusa/0.5.18 (Linux; 4.4.59+; dbbea6d4-1e9c-11ec-a0dd-0242ac130003)
2021-09-26 01:48:27 DEBUG	APIv2-Thread :: [9b23c72] GET URL: https://api.thetvdb.com/search/series?name=trek [Status: 200]
2021-09-26 01:48:27 DEBUG	APIv2-Thread :: [9b23c72] Searching for show: trek
2021-09-26 01:48:27 DEBUG	APIv2-Thread :: [9b23c72] Searching for show with search term(s): ['trek'] on indexer: tvdb
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] Using custom UI: <class 'medusa.classes.AllShowsListUI'>
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] User-Agent: Medusa/0.5.18 (Linux; 4.4.59+; dbbea6d4-1e9c-11ec-a0dd-0242ac130003)
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] GET URL: https://api.themoviedb.org/3/search/tv?query=trek&language=en&page=2&api_key=edc5f123313769de83a71e157758030b [Status: 200]
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] User-Agent: Medusa/0.5.18 (Linux; 4.4.59+; dbbea6d4-1e9c-11ec-a0dd-0242ac130003)
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] GET URL: https://api.themoviedb.org/3/search/tv?query=trek&language=en&page=1&api_key=edc5f123313769de83a71e157758030b [Status: 200]
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] Searching for show: trek
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] Searching for show with search term(s): ['trek'] on indexer: tmdb
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] User-Agent: Medusa/0.5.18 (Linux; 4.4.59+; dbbea6d4-1e9c-11ec-a0dd-0242ac130003)
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] GET URL: https://api.themoviedb.org/3/configuration?api_key=edc5f123313769de83a71e157758030b [Status: 200]
2021-09-26 01:46:00 ERROR	APIv2-Thread-8 :: [9b23c72] Internal Error searching for show. term(s): ['trek'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/api/v2/internal.py", line 233, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/app/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/app/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/app/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/app/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/app/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/app/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/app/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
AttributeError: 'NoneType' object has no attribute 'status_code'
2021-09-26 01:46:00 DEBUG	APIv2-Thread-8 :: [9b23c72] Error requesting url http://api.tvmaze.com/search/shows?q=trek Error: HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /search/shows?q=trek (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4e8a6fa050>, 'Connection to api.tvmaze.com timed out. (connect timeout=30)'))
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] Using custom UI: <class 'medusa.classes.AllShowsListUI'>
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] User-Agent: Medusa/0.5.18 (Linux; 4.4.59+; dbbea6d4-1e9c-11ec-a0dd-0242ac130003)
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] GET URL: https://api.themoviedb.org/3/search/tv?query=trek&language=en&page=2&api_key=edc5f123313769de83a71e157758030b [Status: 200]
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] User-Agent: Medusa/0.5.18 (Linux; 4.4.59+; dbbea6d4-1e9c-11ec-a0dd-0242ac130003)
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] GET URL: https://api.themoviedb.org/3/search/tv?query=trek&language=en&page=1&api_key=edc5f123313769de83a71e157758030b [Status: 200]
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] Searching for show: trek
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] Searching for show with search term(s): ['trek'] on indexer: tmdb
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] User-Agent: Medusa/0.5.18 (Linux; 4.4.59+; dbbea6d4-1e9c-11ec-a0dd-0242ac130003)
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] GET URL: https://api.themoviedb.org/3/configuration?api_key=edc5f123313769de83a71e157758030b [Status: 200]
2021-09-26 01:44:01 ERROR	APIv2-Thread-10 :: [9b23c72] Internal Error searching for show. term(s): ['trek'] indexer: tvmaze error: 'NoneType' object has no attribute 'status_code'
Traceback (most recent call last):
  File "/app/medusa/medusa/server/api/v2/internal.py", line 233, in resource_search_indexers_for_show_name
    indexer_results = indexer_api[search_term]
  File "/app/medusa/medusa/indexers/base.py", line 403, in __getitem__
    selected_series = self._get_series(key)
  File "/app/medusa/medusa/indexers/base.py", line 157, in _get_series
    all_series = self.search(series)
  File "/app/medusa/medusa/indexers/tvmaze/api.py", line 190, in search
    results = self._show_search(series, request_language=self.config['language'])
  File "/app/medusa/medusa/indexers/tvmaze/api.py", line 164, in _show_search
    results = self.tvmaze_api.get_show_list(show)
  File "/app/medusa/lib/pytvmaze/tvmaze.py", line 968, in get_show_list
    shows = self.show_search(show_name)
  File "/app/medusa/lib/pytvmaze/tvmaze.py", line 985, in show_search
    q = self._endpoint_standard_get(url)
  File "/app/medusa/lib/pytvmaze/tvmaze.py", line 542, in _endpoint_standard_get
    if r.status_code in [404, 422]:
AttributeError: 'NoneType' object has no attribute 'status_code'
2021-09-26 01:44:01 DEBUG	APIv2-Thread-10 :: [9b23c72] Error requesting url http://api.tvmaze.com/search/shows?q=trek Error: HTTPConnectionPool(host='api.tvmaze.com', port=80): Max retries exceeded with url: /search/shows?q=trek (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f4e8a5596d0>, 'Connection to api.tvmaze.com timed out. (connect timeout=30)'))

```
</details>

**Additional context**
Switching from indexer 'all indexers' to TVDBv2 causes search results to appear but shows still fail to add.

**Comment by medariox** [comment]
Works fine here. You have problems connecting to TVmaze - maybe you are rate limited. Check your connectivity and try again later.

**Comment by Tailslide** [comment]
Weird.. the thing is it looks OK if I hit it directly here:
http://api.tvmaze.com/search/shows?q=trek

However if I hit this URL I get ```{"Error":"Not authorized"}```
https://api.thetvdb.com/search/series?name=trek

Does it fall back to the one that is working? Or does everything fail if any indexer is unavailable?
I'll wait another day and give it a try again.

**Comment by Tailslide** [comment]
Nevermind.. it was an overly restricted firewall rule.. thanks for your help!
