### ISSUE TITLE
Some new shows won't add

### ISSUE THREAD

**Issue by nydave69** [pymedusa/Medusa#9912]
If I try to add a new or exsisting show Mudusa will fail to add it.

**To Reproduce**
1. Go to '...' Add Shows
2. Click on '....' New Show or Exsisting Show
3. Scroll down to '....' Show Name and add the name of a show

**Expected behavior**
I expect to have the show added..

**Screenshots**
![image](https://user-images.githubusercontent.com/14140816/134915312-74de05a4-f5fe-47ba-ac1a-1be045d083df.png)

Here is a list of shows that just won't add..

**Medusa (please complete the following information):**
<html>
<body>
<h1 class="header" style="box-sizing: border-box; font-size: 36px; margin: 20px 0px 10px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: 500; line-height: 1.1; outline: 0px !important; clear: right; display: block; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Medusa Configuration</h1><div data-v-84755812="" id="config-content" style="box-sizing: border-box; outline: 0px !important; clear: both; display: block; margin: 0px auto; padding: 0px 0px 40px; text-align: left; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Medusa Info: | Branch: masterCommit: 21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6Version: 0.5.18Database: 44.18
-- | --
Python Version: | 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
SSL Version: | OpenSSL 1.1.0j 20 Nov 2018
OS: | Windows-7-6.1.7601-SP1
Locale: | en_US.cp1252
Timezone: | Eastern Daylight Time

</div>
</body>
</html>
**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
2021-09-27 08:31:05 WARNING	SHOWQUEUE-ADD :: [21e350c] Unable to add series: SaveSeriesException("Unable to load series from indexer: IndexerShowNotFoundInLanguage('Missing attribute series_name, cant index in language: en')")
2021-09-27 08:31:05 WARNING	SHOWQUEUE-ADD :: [21e350c] Unable to load series from indexer: IndexerShowNotFoundInLanguage('Missing attribute series_name, cant index in language: en')
2021-09-27 08:31:05 INFO	SHOWQUEUE-ADD :: [21e350c] 84838: Unable to find the show in the database
2021-09-27 08:31:05 INFO	SHOWQUEUE-ADD :: [21e350c] Starting to add show by show_dir: O:\series temp\Star Trek Science vs. Fiction (2006)
2021-09-27 08:29:52 INFO	APIv2-Thread-5 :: [21e350c] Error searching for show. term(s): ['Star Trek Science vs Fiction'] indexer: tmdb error: Show search returned zero results (cannot find show on Indexer)
2021-09-27 08:29:52 INFO	APIv2-Thread-5 :: [21e350c] Error searching for show. term(s): ['Star Trek Science vs Fiction'] indexer: tvmaze error: Tvmaze show search failed in getting a result for search term star trek science vs fiction
2021-09-27 08:29:44 INFO	APIv2-Thread-14 :: [21e350c] Error searching for show. term(s): ['Star Trek Science vs. Fiction'] indexer: tmdb error: Show search returned zero results (cannot find show on Indexer)
2021-09-27 08:29:44 INFO	APIv2-Thread-14 :: [21e350c] Error searching for show. term(s): ['Star Trek Science vs. Fiction'] indexer: tvmaze error: Tvmaze show search failed in getting a result for search term star trek science vs. fiction
2021-09-27 08:29:36 INFO	APIv2-Thread :: [21e350c] Error searching for show. term(s): ['Star Trek Science vs. Fiction'] indexer: tmdb error: Show search returned zero results (cannot find show on Indexer)
2021-09-27 08:29:36 INFO	APIv2-Thread :: [21e350c] Error searching for show. term(s): ['Star Trek Science vs. Fiction'] indexer: tvmaze error: Tvmaze show search failed in getting a result for search term star trek science vs. fiction

```
</details>

**Additional context**

It seems that special characters on the title are the problem..  (these used to add correctly something changed recently)
In the case of Star Trek there is a colon placed in the online data base name Star Trek: so trying to add any Star Trek series fails to add..   

Add new show
Enter for the Show Star Trek: (with colon)
then pick a show that you can add
![image](https://user-images.githubusercontent.com/14140816/134918762-0d794986-9090-4e2b-bc51-b70a487cfb95.png)
scroll to the bottom and add show

Medusa will act like it's adding the show 

In fact there is no show added,  sometimes it does create a new folder for it.
In either case there are no log entries at all for this action..

If you do it as an existing show you get the log errors as above.

**Comment by cautiouscoyote** [comment]
Am having the exact same issue with the Dutch series "Het Rampjaar 1672".
It doesn't matter if I select "English" or "Dutch" as language, it fails to add in both ways; although Medusa does find the series during the "Add Existing Shows"-procedure, since it allows me to select it and push the "add show" button.

But then it's barfing this in the logs:

2022-12-04 16:10:46 WARNING  SHOWQUEUE-ADD :: [e4b480c] Unable to load series from indexer: IndexerShowNotFoundInLanguage('Missing attribute series_name, cant index in language: en')
Traceback (most recent call last):
  File "/opt/medusa/medusa/queues/show_queue.py", line 624, in run
    if getattr(api[self.indexer_id], 'seriesname', None) is None:
  File "/opt/medusa/medusa/indexers/base.py", line 435, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/opt/medusa/medusa/indexers/tvdbv2/api.py", line 548, in _get_show_data
    series_info = self._get_show_by_id(tvdb_id, request_language=get_show_in_language)
  File "/opt/medusa/medusa/indexers/tvdbv2/fallback.py", line 111, in __call__
    return self.func(*args, **kwargs)
  File "/opt/medusa/medusa/indexers/tvdbv2/api.py", line 205, in _get_show_by_id
    .format(request_language), request_language)
medusa.indexers.exceptions.IndexerShowNotFoundInLanguage: Missing attribute series_name, cant index in language: en
2022-12-04 16:10:46 WARNING  SHOWQUEUE-ADD :: [e4b480c] Unable to add series: SaveSeriesException("Unable to load series from indexer: IndexerShowNotFoundInLanguage('Missing attribute series_name, cant index in language: en')")
Traceback (most recent call last):
  File "/opt/medusa/medusa/queues/show_queue.py", line 624, in run
    if getattr(api[self.indexer_id], 'seriesname', None) is None:
  File "/opt/medusa/medusa/indexers/base.py", line 435, in __getitem__
    self._get_show_data(key, self.config['language'])
  File "/opt/medusa/medusa/indexers/tvdbv2/api.py", line 548, in _get_show_data
    series_info = self._get_show_by_id(tvdb_id, request_language=get_show_in_language)
  File "/opt/medusa/medusa/indexers/tvdbv2/fallback.py", line 111, in __call__
    return self.func(*args, **kwargs)
  File "/opt/medusa/medusa/indexers/tvdbv2/api.py", line 205, in _get_show_by_id
    .format(request_language), request_language)
medusa.indexers.exceptions.IndexerShowNotFoundInLanguage: Missing attribute series_name, cant index in language: en

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/medusa/medusa/queues/show_queue.py", line 645, in run
    raise SaveSeriesException('Unable to load series from indexer: {0!r}'.format(error))
medusa.tv.series.SaveSeriesException: Unable to load series from indexer: IndexerShowNotFoundInLanguage('Missing attribute series_name, cant index in language: en')

**Comment by medariox** [comment]
Medusa currently requires the english name to exist on the indexer. You add the english name on TheTVDB or try with a different indexer.
