### ISSUE TITLE
[APP SUBMITTED]: FileNotFoundError: [WinError 2] The system cannot find the file specified: 'I:\\Downloads\\Foundation.S01E03.HDR.2160p.WEB.H265-GGEZ[rarbg]\\foundation.s01e03.hdr.2160p.web.h265-ggez.nfo'

### ISSUE THREAD

**Issue by WarEagleUS21** [pymedusa/Medusa#9920]
### INFO
**Python Version**: `3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]`
**Operating System**: `Windows-10-10.0.22000-SP0`
**Locale**: `cp1252`
**Branch**: [master](../tree/master)
**Database**: `44.18`
**Commit**: pymedusa/Medusa@21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6
**Link to Log**: **No Log available**
### ERROR
<pre>
2021-10-02 09:21:36 ERROR    POSTPROCESSQUEUE-POST-PROCESS :: [21e350c] Unable to move file I:\Downloads\Foundation.S01E03.HDR.2160p.WEB.H265-GGEZ[rarbg]\foundation.s01e03.hdr.2160p.web.h265-ggez.nfo to L:\TV Shows\Foundation (2021)\Season 1\Foundation (2021) - 1x03 - The Mathematician’s Ghost.nfo-orig: FileNotFoundError(2, 'The system cannot find the file specified')
Traceback (most recent call last):
  File "C:\Medusa\Python\lib\shutil.py", line 563, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'I:\\Downloads\\Foundation.S01E03.HDR.2160p.WEB.H265-GGEZ[rarbg]\\foundation.s01e03.hdr.2160p.web.h265-ggez.nfo' -> 'L:\\TV Shows\\Foundation (2021)\\Season 1\\Foundation (2021) - 1x03 - The Mathematician’s Ghost.nfo-orig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/helpers/__init__.py#L320">medusa\helpers\__init__.py</a>", line 320, in move_file
    shutil.move(src_file, dest_file)
  File "C:\Medusa\Python\lib\shutil.py", line 577, in move
    copy_function(src, real_dst)
  File "C:\Medusa\Python\lib\shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Medusa\Python\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'I:\\Downloads\\Foundation.S01E03.HDR.2160p.WEB.H265-GGEZ[rarbg]\\foundation.s01e03.hdr.2160p.web.h265-ggez.nfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/post_processor.py#L477">medusa\post_processor.py</a>", line 477, in move
    helpers.move_file(cur_file_path, new_file_path)
  File "C:\Medusa\Medusa\<a href="../blob/21e350cd4a21f6fb65f750ab5c2d1e9c92c621d6/medusa/helpers/__init__.py#L324">medusa\helpers\__init__.py</a>", line 324, in move_file
    os.unlink(src_file)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'I:\\Downloads\\Foundation.S01E03.HDR.2160p.WEB.H265-GGEZ[rarbg]\\foundation.s01e03.hdr.2160p.web.h265-ggez.nfo'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by WarEagleUS21** [comment]
Not sure why this submitted but please close.
